### ISSUE TITLE
MP: protein glycosylation relationship to protein maturation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10033]
Hi,
shouldn't protein maturation be an ancestor of some (all?) of the protein glycosylation terms?

Reported by: antonialock

Original Ticket: [geneontology/ontology-requests/9829](https://sourceforge.net/p/geneontology/ontology-requests/9829)

**Comment by ValWood** [comment]
@hdrabkin  is protein glycosylation always maturation?

Val

**Comment by hdrabkin** [comment]
I'm not sure I am expert enough to have an opinion. When would it NOT be?

**Comment by srengel** [comment]
is all modification considered 'maturation'?  i wouldn't immediately assume so.

**Comment by deustp01** [comment]
Like Harold, I can't think of a case in which it would NOT be part of maturation - changing a nascent polypeptide to its functional form, at least as part of the normal biology of a mammal. Can't think of a case where, as part of an infectious disease process, host proteins that otherwise would not be glycosylated become so, or are differently glycosylated than they normally would be. But complete ignorance here about possible other modification strategies in other taxa.

**Comment by srengel** [comment]
because glycosylation can occur variably in different cells, it seems more of a regulatory event/cascade than a maturation situation.  i do not consider all modification events to be part of maturation.

a helpful page about glycosylation from Thermo Fisher: 
https://www.thermofisher.com/us/en/home/life-science/protein-biology/protein-biology-learning-center/protein-biology-resource-library/pierce-protein-methods/protein-glycosylation.html

**Comment by ukemi** [comment]
Certainly not all modification is maturation. Proteins are tagged for degradation etc. But like Harold and Peter, I can't think of a case where protein glycosylation is part of protein maturation. Even in the case of folding and trafficking, doesn't it seem like it is all part of the maturation of the protein?

**Comment by ValWood** [comment]
I have always though of glycosylation as a maturation step. It isn't reversible is it? (except for quality control situations?)
The only deglycase I'm aware of is PARK7 which functions in protein repair...
http://www.uniprot.org/uniprot/Q99497

**Comment by hdrabkin** [comment]
Glycation/deglycation is not a maturation process;
"Glycation (sometimes called non-enzymatic glycosylation) is the result of the typically covalent bonding of a protein or lipid molecule with a sugar molecule, such as glucose, without the controlling action of an enzyme. All blood sugars are reducing molecules."
Like your A1c
Deglycase removes this from a protein; as you indicated, its a repair, not a maturation.

**Comment by ukemi** [comment]
OK. I will take the safe approach and not make this link.

**Comment by ValWood** [comment]
I still think all of the comments imply that it is a valid link.....

**Comment by hattrill** [comment]
Just to add an example of where glycosylation is not maturation:
O-GlcNAcylation
PMID:21391816

**Comment by ValWood** [comment]
Thanks Helen, happy now.
