### ISSUE TITLE
rename "carbon catabolite repression of transcription"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10131]
Could the GO term 
carbon catabolite repression of transcription be switched for consistency with parents and children to be the exact synonym
negative regulation of trasncription by carbon catabolites?

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9928](https://sourceforge.net/p/geneontology/ontology-requests/9928)

**Comment by ukemi** [comment]
@ValWood. I'm looking into this ticket again as part of the ontology developers' workshop. I think I agree with Jane that the general 'regulation of transcription of glucose' etc should be moved from being children of the carbon catabolite terms because they are less general. I think the catabolite terms reflect more the reason/result for the transcription regulation than the trigger. The general terms don't reflect this at all. I think these terms encompass the mechanism by which an organism controls the carbon source that it utilizes. 

I propose that the general terms that don't state 'of specific genes involved in the metabolism of other carbon sources.' be moved out of this branch and the other terms be renamed to be consistent with the branch. For example: 'regulation of transcription from RNA polymerase II promoter by a nonfermentable carbon source' will be renamed 'carbon catabolite regulation of transcription from RNA polymerase II promoter by a nonfermetable carbon source'. This way it is clear that the term reflects aspects of both the trigger and the response.

**Comment by ukemi** [comment]
also see #10613.
@jimhu-tamu any comments about this proposal as a start?

**Comment by jimhu-tamu** [comment]
Hi David, 

I may have forgotten some earlier input related to this, but here are my initial thoughts on seeing this today:

I would want to look at the proposals for how this fits more globally into catabolite repression and related topics. From looking at the current structure of GO, it seems to me that the existing structure doesn't fully capture the biology in bacteria, which I suspect has analogous parts in eukaryotes. 

General issues
In bacteria, catabolite repression tends to be taught in terms of how glucose represses the transcription initiation at lac based on the synthesis or lack of synthesis of cyclic AMP from adenyl cyclase (cya) and activation of initiation by CAP-cAMP (crp). But it's more complex. IIRC, there is data that suggest that CAP-cAMP is a minor contributor to the effect of glucose on lac expression induced by lactose (as opposed to the membrane permeable lactose analog IPTG), and a larger contribution comes from a phenomenon known as inducer exclusion. In that, transport of glucose via the PTS system negatively regulates the activity of a number of other proteins, including sugar transporters and adenyl cyclase. When lac permease is inhibited, the lactose can't get into the cell to derepress lac independent of CAP-cAMP. 

One could shoehorn this into regulation of transcription because the inducer exclusion does affect initiation. But in glycerol metabolism, the glucose effect on the PTS system acts by regulating the activity of glycerol kinase, the first step in metabolizing glycerol. Thus, I would argue for a more general umbrella term for catabolite regulation that is not specific to transcription.

The catabolite effects are not only seen with glucose. There is a hierarchy of C source preference in E. coli, and I think that's also true in S. cerevisiae. (http://mmbr.asm.org/content/62/2/334.full)

I'm also not sure that fermentable/nonfermentable is right here... glucose is fermentable.

**Comment by ukemi** [comment]
Thanks Jim. I think I will add the general catabolite repression term and then make the transcription regulatory terms children of it. But I think we are on the same page here that these terms are much more than just the regulation of transcription. The terms here really encompass a metabolic control system that controls the use of a carbon source. I'm not sure that I will add all of the detailed processes under catabolite repression until we need them for annotation, but at least the structure will be in place so that we can add them. I will sort out the transcription terms based on the new structure and the additional general catabolite repression parent. Hope all this makes sense.

-D

**Comment by jimhu-tamu** [comment]
sounds good!

**Comment by pgaudet** [comment]
I also think that these terms really try to capture some signaling event, which unfortunately is described as transcription in papers, since that's the last step. I am not sure it even makes sense to have this under transcription, especially if you think about how this groups when you do a slim (or any kind of enrichment analysis). 

Pascale

**Comment by ukemi** [comment]
Closed via #15152
