### ISSUE TITLE
Out of scope terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10146]
Sorry to raise yet more issues, I'm really not looking for them.
Yesterday i spotted these 2 terms, and they seem out of scope for GO, they aren't describing a process, they are describing a sequence elelment. I'm assigning to David as this is a lovely example for the annotation extension paper \(these are just describing a  type of promoter should be a extension with SO\)
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0001035
transcription from RNA polymerase III type 3 promoter

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0001009 
transcription from RNA polymerase III type 2 promoter

val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9943](https://sourceforge.net/p/geneontology/ontology-requests/9943)

**Comment by ValWood** [comment]
Its possible/likely that I don't understand what these promoters are (type 1 2,3).

However there is a comment
" Type 3 Pol III promoters have not been observed in S. cerevisiae."

Probably the best way to deal with this  is to add a taxon restriction "never in fungi"
This way, once we include taxon checks in our curation tool, these terms will not be visible ;)

**Comment by ukemi** [comment]
Does never in S. cerevisiae=never in fungi?

**Comment by ValWood** [comment]
Well they are just a bit misleading in general for fungi.I don't think we would refer to them as type 1 2 and 3 (promoters are less complex and they seem to be a hybrid, s the designations don't really work)....It's much better to capture the   promoter sequence variation at the SO level...

We have annotated to type II, but they aren't really  analogous to any of these...

**Comment by ValWood** [comment]
I just saw your comment

"This one should be quick. Even though the terms refer to the subtypes of
promoters, it looks as though the PROCESS of transcription initiation is
different for each of them, internal versus external. See figure 2 in
PMID:12381659. "

This makes it clearer what the distinction is. Can this be added to the defs?

**Comment by ukemi** [comment]
I made the taxon restrictions and added a clause in the definition gloss.

**Comment by krchristie** [comment]
Hi,

Edith asked me to take a look at this because I am the original source of a number of SGD's annotations to GO:0001009 "transcription from RNA polymerase III type 2 promoter", such as this one below.

While I agree with Val that type 3 promoters have not been observed in S. cerevisiae, it is definitely not true to add "never_in_taxon Fungi" to either the type 1 or type 2 promoters. I can't see taxon constraints in the version of the ontology I look at, but could you please remove this taxon constraint from the type 1 and 2 promoter term(s).

thanks,

-Karen


Karen Christie           GO:0001009 never_in_taxon Fungi                   protein     P32367      GO:0001008 transcription factor activity, RNA po...ECO:0000314 (IDA) PMID:2668737   559292   Saccharomyces cerevisiae (strain ATCC 204508 / S288c)

**Comment by ValWood** [comment]
The synthesis of RNA from a DNA template by RNA polymerase III (RNAP III), originating at a type 2 

Hi Karen,

While you are looking,  how do you identify the A-box and type B-box promoters referred to in the def?
This is the thing which seems to differentiate this promoter type but I'm not sure what it means? Or do you just assume that a tRNA  has a type 2 promoter?

The def is:
RNAP III promoter. Type 2 RNAP III promoters consist of an A box and a B box downstream of the transcription start site within the sequence within the sequence of the mature RNA and the process of initiation is different than from other promoter types. Type 2 promoters are found in many tRNA genes as well as in other small RNAs.

**Comment by krchristie** [comment]
With a tRNA, I generally assume that it is a type 2 promoter, because the A and B boxes are in highly conserved sequences of the tRNA. Note that it's not A-box or B-box promoters, a type 2 promoter is comprised of both an internal A box and an internal B box. Both boxes are required as each of the two ends of dumbbell shaped TFIIIC binds to one of the boxes as the initial step of promoter recognition for type 2 promoters.

With any other RNAP III transcript, I would only make a promoter type specific annotation if the researchers discussed the the promoter specifically.

-Karen

**Comment by ValWood** [comment]
OK got it, thanks. I   have no idea if these promoters are conserved. I should  probably go to the parent...

David, als small def tweak repeated "within the sequence"

**Comment by krchristie** [comment]
I read a lot on this when David Hill and I worked on this a long time ago, and I would think that the type 2 promoters are conserved quite widely since tRNAs themselves and also TFIIIC are quite conserved.

**Comment by ukemi** [comment]
Hi Karen,

Thanks for having a look. I removed the constraint from the type 2 promoter and left the one for the type 3 promoter in place. There is no single process for the type 1 promoter. I also fixed the duplicated text in the definition.

-D
