### ISSUE TITLE
regulation of cyclin-dependent protein kinase activity invol

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10231]
regulation of cyclin-dependent protein kinase activity involved in G2/M
Any process that modulates the frequency, rate or extent of CDK activity contributing to the G2/M transition of the cell cycle.

is currently part\_of
GO:0000086 G2/M transition of mitotic cell cycle
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0031662\#term=ancchart

but from the meeting the "regulation of the kinase" is part of the 
regulation of G2/M transition of mitotic cell cycle wasn't it  ? \(i.e this is what we would annotate cdc25 to\)

so it isn't part\_of the transition, its =\_ve\_regulation\_of the transition

which would be:
regulation of cyclin-dependent protein kinase activity involved in \*regulation\*  G2/M

can you have 2 regulates? it sounds wrong but  it sems more accurate.
I  guess we will get down to this level of detail when we look more closely at the contributing MFs

v

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10028](https://sourceforge.net/p/geneontology/ontology-requests/10028)

**Comment by ukemi** [comment]
Hi Val,

I think the issue here was in the parsing of the logical definitions. I have changed this one and the others like it to be a 'regulation of cyclin-dependent protein serine/threonine kinase activity' and regulates 'some cell cycle transition' instead of part_of 'some cell cycle transition'. I got rid of the offending part_of relations and reran the reasoner. The new inferred links are all to 'regulation of some cell cycle transition'. So I think this one is done. 

-David

Here is an example:
synonym: "regulation of cyclin-dependent protein kinase activity involved in G1/S" BROAD []
 is_a: GO:0000079 ! regulation of cyclin-dependent protein serine/threonine kinase activity
 intersection_of: GO:0000079 ! regulation of cyclin-dependent protein serine/threonine kinase activity
-intersection_of: part_of GO:0000082 ! G1/S transition of mitotic cell cycle
-relationship: part_of GO:0000082 ! G1/S transition of mitotic cell cycle
+intersection_of: regulates GO:0000082 ! G1/S transition of mitotic cell cycle
