### ISSUE TITLE
L-amino acid transport terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10278]
Hi--

I'm annotating a paper that demonstrates the activity of a lysosomal amino acid transporter and wanted to ask about some of the existing transport/transporter terms.  I know that some of these could be TermGenie requests, but I wasn't sure if I also had the right template for transport of a chemical from one CC to another CC.

I'd like to request some additional L-amino acid transport child terms:
GO:0015807 L-amino acid transport
GO:new L-lysine transport
GO:new L-lysine transport from lysosome to cytoplasm
GO:new L-arginine transport
GO:new L-arginine transport from lysosome to cytoplasm
GO:new L-histidine transport
GO:new L-histidine transport from lysosome to cytoplasm
GO:0015811 L-cystine transport
GO:new L-cystine transport from lysosome to cytoplasm

GO:0007041 lysosomal transport
GO:new L-lysine transport from lysosome to cytoplasm
GO:new L-arginine transport from lysosome to cytoplasm
GO:new L-histidine transport from lysosome to cytoplasm
GO:new L-cystine transport from lysosome to cytoplasm

The reference is: PMID: 22822152

Thanks,
\--Kimberly

Reported by: vanaukenk

Original Ticket: [geneontology/ontology-requests/10075](https://sourceforge.net/p/geneontology/ontology-requests/10075)

**Comment by paolaroncaglia** [comment]
@vanaukenk
Hi Kimberly,

This is an old request of yours. I followed up on it months ago, but I realise now that because of the move from SourceForge to GitHub, you were no longer being notified of ongoing conversation. Summing up, this is the situation: you asked for some terms to annotate PMID: 22822152. Jane added some. The following are still missing:

L-lysine transport from lysosome to cytoplasm
L-arginine transport from lysosome to cytoplasm
L-histidine transport from lysosome to cytoplasm
L-cystine transport from lysosome to cytoplasm

If you think you’d still like to use them, a TG template is now in place that you could use:
chemical_transport_from_to
(Description: transport of a chemical entity from and/or to a cellular component)

Please let me know, so I may go ahead and close this ticket if no other action is needed.

Thanks and apologies for the inconvenience.

Paola

**Comment by vanaukenk** [comment]
Hi Paola,
Thanks for following up with this.  Looking at the TG template, I think the most accurate terms to create would be, for example:
L-lysine transmembrane transport from lysosome to cytoplasm
so I will select that option in the template.
Does that sound okay?
--Kimberly

**Comment by dosumis** [comment]
* 'from' should probably be 'lysosomal lumen'
* 'to' should probably be cytosol

Besides that, looks good to me.

**Comment by paolaroncaglia** [comment]
Exactly. As long as it's transport across a membrane, looks good to me too :-)
I'll close this ticket then.
Thanks,
Paola

**Comment by vanaukenk** [comment]
Okay, thanks David and Paola. 
I will add the appropriate, more descriptive terms as you've suggested.

--Kimberly
