### ISSUE TITLE
muscle cell vs muscle fiber

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10399]
GO distinguishes between muscle cell and muscle fiber. However, in CL these are exact syns. 

id: CL:0000187
name: muscle cell
def: "A mature contractile cell, commonly known as a myocyte. This cell has as part of its cytoplasm myofibrils organized in various patterns." [MESH:A11.620]
synonym: "muscle fiber" EXACT []
synonym: "myocyte" EXACT []

I am sure we made the same decision in GO many years ago.

However, the distinction has bounced back

e.g.

GO:0048747 ! muscle fiber development [DEF: "The process whose specific outcome is the progression of the muscle fiber over time, from its formation to the mature structure. Muscle fibers are formed by the maturation of myotubes. They can be classed as slow, intermediate/fast or fast."]

GO:0055001 ! muscle cell development **\*  [DEF: "The process whose specific outcome is the progression of a muscle cell over time, from its formation to the mature structure. Muscle cell development does not include the steps involved in committing an unspecified cell to the muscle cell fate."]

This is blocking some changes to the xp file Heiko and I need to make.

EQUIVALENT_CLASS_PAIR: EquivalentClasses(
GO:0048739 'cardiac muscle fiber development'
GO:0055013 'cardiac muscle cell development' )

EQUIVALENT_CLASS_PAIR: EquivalentClasses(
GO:0048747 'muscle fiber development'
GO:0055001 'muscle cell development' )

I suggest we merge fiber into cell.

See attached image.

But there are other less serious problems at the terminological level. E.g.

 GO:0014856 ! skeletal muscle cell proliferation
 GO:0035914 ! skeletal muscle cell differentiation

 GO:0043503 ! skeletal muscle fiber adaptation
 GO:0048741 ! skeletal muscle fiber development

note that CL doesn't even include 'skeletal muscle fiber' as a syn of 'skeletal muscle cell' (presumably it should)

I suggest we always use the CL term as the primary label

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10199](https://sourceforge.net/p/geneontology/ontology-requests/10199)

**Comment by ValWood** [comment]
@cmungall  can you comment how we can close this? It seems to be about alignment with  CL and equivalence blah blah....

**Comment by raymond91125** [comment]
The term "muscle fiber development" should not logically mean muscle myofibril development because the IS_A relationship to "striated muscle cell development". "striated muscle cell development" IS_A "muscle cell development".
"muscle fiber development" has two is_a children "cardiac muscle fiber development" and "skeletal muscle fiber development".

Thus I suggest that we deprecate "muscle fiber development"; move its annotations to "muscle cell development" and rename "X muscle fiber development" to "X muscle cell development" and make them IS_A children of "striated muscle cell development".

I looked at the refs supporting several direct annotations of "muscle fiber development", from MGI, ZFIN, FB, and WB, and found that they can all be annotated with "muscle cell development". One WB paper described muscle filament defects of some pharyngeal muscle cells.

**Comment by pgaudet** [comment]
Sure - the only issue is there are 80 EXP annotations. If we believe that another term is equivalent, we would do a merge (for convenience for curators).

**Comment by raymond91125** [comment]
Yes, merge is a good idea.

**Comment by cmungall** [comment]
I'm OK with a merge here

**Comment by raymond91125** [comment]
In Cell Ontology, there is CL:0008002 ! skeletal muscle fiber with the Definition: A transversely striated, synctial cell of skeletal muscle. It is formed when proliferating myoblasts exit the cell cycle, differentiate and fuse.
Thus I suggest we keep the "skeletal muscle fiber" part in GO terms, not changing them to "skeletal muscle cell".

**Comment by raymond91125** [comment]
Remove synonyms of "muscle fiber/fibre" from contractile fiber terms. In general, the common usage of "muscle fiber" refers to a muscle cell rather than some actin/myosin filiments.
