### ISSUE TITLE
possibe "protein targeting problem" related to MVB sorting

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10484]
I am not an expert in this  (at all), but there seems to be a problem with the term
"GO:0043329 protein targeting to membrane involved in ubiquitin-dependent protein catabolic process via the multivesicular body sorting pathway"

I noticed this because I was looking a the list of proteins involved in "protein targeting".

As far as I'm aware "targeting" relies on signal intrinsic to the protein but this type of sorting is "ubiquitin dependent". If this interpretation is correct we could change to
"protein sorting" and remove the protein targeting parentage?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/10285](https://sourceforge.net/p/geneontology/ontology-requests/10285)

**Comment by ukemi** [comment]
Hi Val,

Looking at this item again now, I don't think a merge is in order. Proteins are also targeted to lysosomes as part of microautophagy and to late endosomes in the mammalian equivalent. So not all of this targeting is via MVBc. If I am not mistaken, sometimes this also involves ubiquitination. 

Could change the term to be sorting instead of trageting, but what would you suggest I use as a parent?

-D

**Comment by ValWood** [comment]
Or transport?
How does "sorting" differ from transport?
Val

**Comment by ukemi** [comment]
Presumably this term refers to the process by which the proteins are recognized, which is separate from the movement. Transport would be more than that.
If you look at the paper that supports this term, it describes an ESCRT complex and it specifically says that the complex is required to recognize the tagged protein and sort it correctly.
