### ISSUE TITLE
site specific tRNA (guanosine-2'-O-)-methyltransferase activity?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10557]
I am reading a paper (pmid:11927565) that concludes:

"TRM7 codes for a MTase that catalyses the formation of 2'-O-methylnucleotides at positions 32 and 34 of the yeast tRNAPhe, tRNATrp and, possibly, tRNALeu."

The available (relevant) terms are:
GO:0009020 tRNA (guanosine-2'-O-)-methyltransferase activity
GO:0052666 tRNA (cytosine-2'-O-)-methyltransferase activity

The problem is that they don't capture that this enzyme can only methylate some (32 and 34) of the potential sites (4, 18, 32, 34, 44) of yeast tRNAs. The positions might also be yeast specific.

Would it be possible to create child terms for each position and nucleotide (G/C and 32/34 - 4 all together, for now)? Or, perhaps just indicate that this is a site specific enzyme (not the only one) without specifying the actual position?

Thanks,
Janos

Reported by: jdemetert

Original Ticket: [geneontology/ontology-requests/10361](https://sourceforge.net/p/geneontology/ontology-requests/10361)

**Comment by paolaroncaglia** [comment]
@hdrabkin ,
When you're back, could you please take a look at this old request and advice?
I'm not sure if in the meantime our 'policy' has changed with regards to modification specific to a particular site - I can't find documentation now, but I suspect we may prefer not to have this much specificity. Also, you or @ukemi may have come across some of these terms during your recent addition of enzyme terms? 

Thanks.

**Comment by paolaroncaglia** [comment]
@hdrabkin 
@ukemi
Could you take a look please, see my previous comment. Thanks!

**Comment by paolaroncaglia** [comment]
(Pinging @hdrabkin for advice, thanks)

Summarizing:

There may be a few issues with existing terms like GO:0009020 tRNA (guanosine-2'-O-)-methyltransferase activity: Jane wrote:
“Many of the terms with general names and definitions are in fact specific to a particular site when you check the EC dbxref e.g. GO:0009020 tRNA (guanosine-2'-O-)-methyltransferase activity actually methylates guanosine 18. So these all need to be fixed.”

- [ ] Identify which terms have this issue;
- [ ] Fix them so that they are indeed general;
- [ ] Resolve on whether we should have/add terms for specific modifications such as the ones captured by the EC dbxref above, or not. My take is that no, we wouldn’t want to have these except for histone terms (e.g. histone acetyltransferase activity (H2A-K5 specific)), but apparently back in 2014 we decided otherwise. 

If we do resolve to have GO terms to represent e.g. tRNA (guanosine-2'-O-)-methyltransferase activity that specifically methylates guanosine 18,
- [ ] Get some advice about the best nomenclature to use for these modifications - the recommended names contain superscript which we can't use
- [ ] Add new term(s) as per Janos’ original request at the top of this ticket.

**Comment by hdrabkin** [comment]
Ok; I was initially opposed to putting in this specificity, but in my work with the plant enzyme project, it appears that metacyc is giving them specific ids, and I put them in per request. At the moment, I don't see any other way of encoding the specificity unless one tries to specify target (with an RNA central id + a position; could get messy if you are not sensitive to tRNA position numbers (which can have decimals , eg position 20, 20.1, 20.2, when the nucleotide is in a region that is variable with respect to a generic tRNA. Example: T54U60 in the TUCG loop, is often not exactly #54and 60  starting from nucleotide 1, but they are designated as always being numbered 54 and 60.
Should we discuss Thursday?

**Comment by hdrabkin** [comment]
One numbering system
https://www.researchgate.net/figure/8936097_fig1_Figure-1-Canonical-tRNA-cloverleaf-secondary-structure-and-numbering-system-Diagram
This is the system as I remember it in my time
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC327698/?page=3

**Comment by paolaroncaglia** [comment]
At the ontology call today, we resolved to assign this ticket to @hdrabkin  because he's in touch with an external expert about this type of nomenclature for residue specificity. Thanks Harold.

**Comment by paolaroncaglia** [comment]
Note that the original submitter (Janos Demeter at SGD) is not following this ticket because we moved from SourceForge to GitHub since. I don't know if Janos has a GH account, so I'm asking @srengel . Stacia, please could you check with Janos if he'd like to subscribe to this ticket? Thanks in advance.

**Comment by hdrabkin** [comment]
So the more or less official tRNA numbering is found in
l Sprinzl et al 1998, Sprinzl Vassilenko 2005 papers 
Sprinzl M, Vassilenko KS. Compilation of tRNA sequences and sequences of tRNA 
genes. Nucleic Acids Res. 2005 Jan 1;33(Database issue):D139-40. PubMed PMID:
15608164; PubMed Central PMCID: PMC539966.
and 
Sprinzl M, Horn C, Brown M, Ioudovitch A, Steinberg S. Compilation of tRNA
sequences and sequences of tRNA genes. Nucleic Acids Res. 1998 Jan
1;26(1):148-53. PubMed PMID: 9399820; PubMed Central PMCID: PMC147216.
The attached figure comes from the 1998 paper
![f1 medium](https://cloud.githubusercontent.com/assets/10440080/21275728/2eac1e32-c39c-11e6-872f-c9368fd5cf49.gif)

**Comment by hdrabkin** [comment]
From my expert: The D-loop is standard anyway; the rather confusing numbering in the variable loop tries to incorporate possible base-pairing as described in the original 1998 paper. 
HOWEVER, there are many papers out there that use the D-loop nomenclature as shown above, but indicate the variable loop as 45, 45 A, 45 B, 45 C ....... 46, 47, 48

**Comment by hdrabkin** [comment]
Update:
Investigating relationship with EC:2.1.1.34, used as def and xref
This activity is defined in EC as specific to G18; However, the GO def doesn't reflect this. 
THe EC number classifies the enzyme, not the reaction as far as I understand this, 
I am seeing that some enzymes that are defined by EC with a specific site are actually used for other RNAS (like rRNAs), so that this definition of specificity is  too tight for the enzyme.  I need to see if this one maps to more than just tRNA substrates.

**Comment by hdrabkin** [comment]
Starting to sort this out.

BRENDA reports that EC 2.1.1.34 is supposed to be named tRNA (guanosine18-2'-O)-methyltransferase.
However, the same EC in GO is used for tRNA (cytosine-2'-O-)-methyltransferase activity; this is wrong.
At EC there are three tRNA site-specific entries
2.1.1.33     tRNA (guanine(46)-N(7))-methyltransferase EC not used in GO
2.1.1.34     tRNA (guanosine(18)-2'-O)-methyltransferase
2.1.1.35     tRNA (uracil(54)-C(5))-methyltransferase; ec not used in GO

I will remove 2.1.1.34 from the cytosine-2' O,.
Then add the other activities.

**Comment by hdrabkin** [comment]
have removed incorrect ec usage for cytosine-2'0
Added new term as child for cytosinne-2'0

**Comment by ValWood** [comment]
Hi Harold, is this still current? It was opened in 2013 ;)

**Comment by ValWood** [comment]
It can probably be closed, it seems there was some action taken?

**Comment by hdrabkin** [comment]
Yes; I'll add the activities that aren't there and I just also see that 2.1.1.34 is being used for 2'O U also. Then I'll close

**Comment by pgaudet** [comment]
@hdrabkin Is this ready to be closed ?

**Comment by hdrabkin** [comment]
will look in a bit to refresh what I have done; am in the middle of closing another. I'll close this once I look.

**Comment by hdrabkin** [comment]
Done.

**Comment by pgaudet** [comment]
Thanks !
