### ISSUE TITLE
General Ras GTPase terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10621]
Afraid this is a rather general point that covers a lot of terms. I think that the terms related to Ras GTPases might benefit from some renaming and new terms to help define the Ras subfamily. The Ras superfamily major subfamilies are Ras, Rab, Rho, Ran, Arf. Currently most Ras process/function terms have the Ras parent term which applies to the superfamily and the children referring to the specific subfamilies (e.g. Rho, Arf). The child terms do not include the Ras subfamily itself (although there are some Ras sub-sub families like Ral & Rap).

e.g. Parent: GO:0005099 Ras GTPase activator activity
     Children: GO:0005097 Rab GTPase activator activity
               GO:0005098 Ran GTPase activator activity
               GO:0005100 Rho GTPase activator activity
               GO:0017123 Ral GTPase activator activity
               GO:0046582 Rap GTPase activator activity

The same is true of other Ras superfamily relationships, e.g.
GO:0032856 activation of Ras GTPase activity
GO:0017016 Ras GTPase binding
GO:0046579 positive regulation of Ras protein signal transduction
GO:0034261 negative regulation of Ras GTPase activity
GO:0005088 Ras guanyl-nucleotide exchange factor activity

I'm not sure what the best approach is: requesting new Ras sub-family-specific GOs would result in a very similar name to the parent term.

This may also be an issue for other families with sub-families that share the same name e.g. Rho family with Rho and Rac subfamilies.

Reported by: hattrill

Original Ticket: [geneontology/ontology-requests/10426](https://sourceforge.net/p/geneontology/ontology-requests/10426)

**Comment by tberardini** [comment]
@hattrill - finally can close this issue.  We will not be creating any new protein family binding terms.
---------------------

This issue was discussed at the DC GOC meeting that just concluded.

Decision: protein family binding terms will be removed from GO. Annotations will be to ‘protein binding’ and the ‘with’ column (or, preferably, col. 16 using the has_input relation) will be required. If desired, an external protein classification can be used to create virtual protein family binding terms for grouping gene products for, e.g. enrichment analysis
