### ISSUE TITLE
Cilia: new terms and links - cellular component branch

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10740]
We are in contact with John van Dam, Toby Gibson and colleagues to add/revise terms related to cilia (CC and BP). Here is a first list of suggested edits from John:

"...In the end I've removed a lot of terms from my list because I found out they already existed as part of the axoneme term, which itself was not connected to the cilium. I've missed these terms using the graphical viewer in OBO-edit. Please find attached an excel file with the new terms, a short definition, reference data and relationships. I've also added some new connections for existing terms as well as identified some issues that need some rewiring of the terms.
I am sure that in terms of is_a and part_of relationships there are more issues to solve. I will try and figure those out this December, as well as figure out the biological processes part. One of these things is the fact that some terms define areas through which other components cross, like "ciliary transition zone" and "axoneme", in the excel file I've made "axoneme" part_of "ciliary transition zone", but I'm not quite sure if it is the way to go."

The excel file is called "New GO terms - Nov2013" and is attached.

Paola

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/10553](https://sourceforge.net/p/geneontology/ontology-requests/10553)

**Comment by paolaroncaglia** [comment]
Wrapping up pending to-do items:
1) added links: 
ciliary base has_part ciliary transition zone
ciliary base has_part ciliary transition fiber
ciliary shaft has_part axoneme
axonemal central pair part_of axonemal central apparatus
axonemal outer doublet has_part A axonemal microtubule
axonemal outer doublet has_part B axonemal microtubule
axonemal central pair has_part C1 axonemal microtubule
axonemal central pair has_part C2 axonemal microtubule
2) removed (now) redundant has_part links from axonemal central pair and axonemal outer doublet
3) changed radial spokehead into radial spoke head
4) changed nexin complex into axonemal nexin link

**Comment by paolaroncaglia** [comment]
Dear @JohnvanDam and @krchristie,

This ticket was the first one containing John’s initial suggestions for ciliary component edits, and where we started discussion with Karen too. I went over it again in detail, and made sure that every suggestion we agreed on was implemented. (So you may ignore all of the previous comments in this ticket.) There are only two pending points. One is about types of cilia (I’ll create a separate ticket for that, so let’s leave these aside for now). The other is about a link that John suggested. Could you please provide feedback on the following:

In his initial set of suggestions, John mentioned this one:
GO:0034464	BBSome		part_of	intraflagellar transport particle (GO:0030990)
Note that GO:0030990 has since been renamed intraciliary transport particle.
Based on the current definitions of the two terms
BBSome = A protein complex that associates with the primary cilium and is involved in cilium biogenesis; consists of seven conserved proteins: BBS1, BBS2, BBS4, BBS5, BBS7, BBS8 and BBS9. 
intraciliary transport particle = A nonmembrane-bound oligomeric protein complex that participates in bidirectional transport of molecules (cargo) along axonemal microtubules. 
John’s suggested link sounds a bit weird to me. Do you agree that we should drop this?

Note for self: once this is resolved, I can close this ticket.

**Comment by JohnvanDam** [comment]
Hi Paola,

The BBSome definition appears to be outdated, hence the confusion.

PMID: 26498262
"The BBSome, a complex comprising eight BBS proteins, moves in association with IFT trains through cilia (Figure 2) 11, 20, 21, 22 and 23."
"The BBSome, comprising at least seven Bardet–-Biedl syndrome (BBS) proteins and BBIP10, appears to be a substoichiometric component of IFT trains."

But reading a little more it appears to become a bit muddled. 

Blacque at al. show that the BBSome is required for IFT-A and IFT-B integrity (http://genesdev.cshlp.org/content/18/13/1630)
But this does not necessarily mean it is "part of", though highly suggestive.

Williams et al. find it is an integral part of IFT in mammalian olfactory neurons. (doi:10.1038/ncomms6813)

But Lechtreck et al. describe the BBSome in Chlamydomonas reinhardtii as "IFT cargo required for export of specific signalling proteins" (J. Cell Biol., 187 (2009), pp. 1117–1132).
I think that the description of the BBSome as "cargo to carry other cargo" is a bit weird. The complex might not directly provide the directional locomotion, but I think that as an consistent constituent of the IFT train it is therefore "part_of". 

I'll do a little more digging later this week (also to make that NPHP def) once I send my paper out (again). Sorry for the hold up.

Cheers,
John

**Comment by paolaroncaglia** [comment]
OK, thanks @JohnvanDam , I'll wait before adding the link.

**Comment by krchristie** [comment]
Hi Paola and John,

Coincidentally, the IFT complex and the BBSome complexes are both things where I have annotated the mouse genes fairly completely, so I understand this somewhat well, though my impression is that there are still some open questions about exactly how the BBSome functions.

Anyway, my impression is that the BBSome has several roles, one of which is as a cargo adaptor for IFT trains. However, it is not the only cargo adapter, and the other cargo adaptors, e.g. Tulp proteins, that I know of are considered to be part of IFT. 

This paper:
Avidor-Reiss T, Leroux MR. Shared and Distinct Mechanisms of Compartmentalized and Cytosolic Ciliogenesis. Curr Biol. 2015 Dec 7;25(23):R1143-50. doi:10.1016/j.cub.2015.11.001. Review. PubMed PMID: 26654377
says:
"Comparative genomics therefore affords tremendous predictive power when contrasting highly divergent or closely related organisms that display cellular and morphological differences. It is within this framework that we consider how different macromolecular complexes, that is, the transition zone (TZ) and the core intraflagellar transport (IFT) machinery with its associated Bardet-Biedl syndrome complex (BBSome), are differentially employed to support two distinct categories of ciliogenesis — compartmentalized and cytosolic — and the different types of cilia present across diverse eukaryotes."

This seems consistent with the way I have seen the IFT machinery described, as being composed of IFT-A and IFT-B, and then IFT associates with many various cargo adaptors, of which BBSome is one.

So, at the moment, I am not in favor of adding 
 GO:0034464 BBSome part_of intraflagellar transport particle (GO:0030990)

-Karen

**Comment by JohnvanDam** [comment]
Since the uncertainty in literature I am inclined to agree with Karen on not adding the link at this point, until the literature will become more definitive on this point. Just to gouge some perspective from others I've asked one of my collaborators who has worked on IFT and BBSome for his opinion. I will take into account that his view may be not be representative, but I hope his reply will have some leads to interpret/search for additional literature.

The BBSome term definition is outdated however, so we might as well try to fix/update that a little. More on this in a hour or so.

**Comment by JohnvanDam** [comment]
From Oliver Blacque:

> Hi John
>
>The BBSome is not considered an intergral 'core' part of IFT. The BBSome complex absolutely >associates with IFT complexes in some way (as an IFT-A/B adaptor or cargo of sort), but they are >biochemically and functionally distinct.
>
>Cheers
>Ollie

This still leaves papers like PMID: 2550414 which state: "We identify Bardet-Biedl syndrome proteins (BBSome) as bona fide constituents of IFT in olfactory sensory neurons, and show that they exist in 1:1 stoichiometry with IFT particles." But I think it is better to err on the side of caution and let the scientist battle this out a little more before (and if!) we make the connection in GO.

**Comment by paolaroncaglia** [comment]
Thanks @krchristie  and @JohnvanDam  (and Oliver), 

Summing up, I will *not* add the part_of link GO:0034464 BBSome part_of intraflagellar transport particle (GO:0030990).
Instead, I updated the def of GO:0034464 BBSome, and added a part_of link to ‘cilium’. The revised stanza is below for reference. Closing now.

[Term]
id: GO:0034464
name: BBSome
namespace: cellular_component
def: "A ciliary protein complex involved in cilium biogenesis. It consists of at least seven Bardet–-Biedl syndrome (BBS) proteins and BBIP10. It moves in association with IFT trains through cilia (likely as an IFT-A/B adaptor or cargo), and is required for the integrity of IFT-A and IFT-B." [GOC:BHF, GOC:cilia, PMID:15231740, PMID:17574030, PMID:26498262]
synonym: "Bardet-Biedl syndrome complex" EXACT []
is_a: GO:0043234 ! protein complex
relationship: part_of GO:0005929 ! cilium
