### ISSUE TITLE
discuss: part_of annotation for protein complexes with different functions in different locations/supercomplexes (e.g. GO:1990328 RNA polymerase II, RPB4-RPB7 subcomplex)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#10931]
Hi everyone,

This is following up from ticket #10717 request

GO:1990328 RNA polymerase II, RPB4-RPB7 subcomplex:
- part_of GO:0005665 DNA-directed RNA polymerase II, core complex AND
- part_of GO:0000932 cytoplasmic mRNA processing body

Tanya pointed out that multiple part_of relationships are NOT allowed if they don't happen simultaneously. In the above example the complex has two functions in two different compartments independent from each other (as far as I can tell - see UniProt annotation!). At present, we cannot capture this but I would like to do it in some form (apart from the def).

Let's hear your thoughts :)

Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/10745](https://sourceforge.net/p/geneontology/ontology-requests/10745)

**Comment by dosumis** [comment]
@bmeldal - A good example to discuss in the Protein complex working group?

Issues:
1. Do we allow for complexes to be part of other complexes, if so, when?
Note - this potentially violates the semantics of part_of: It should apply at all times.
2. When should we allow for capable_of_part_of links to processes?  I'd say only when definitional - otherwise just capture in the annotation.

**Comment by bmeldal** [comment]
>Issues:
>1. Do we allow for complexes to be part of other complexes, if so, when?
>Note - this potentially violates the semantics of part_of: It should apply at all times.
Yes, we should allow 'subcomplex A' part_of 'holocomplex B', e.g. 
GO:0009360 DNA polymerase III complex - has 3 subcomplexes that assemble together, then dissociate again in a controlled order. The subcomplexes don't have any function other than when part_of the holocomplex.

>2. When should we allow for capable_of_part_of links to processes? I'd say only when definitional - >otherwise just capture in the annotation.
Oh, I can see what you mean, for promiscuous complexes the list could be long... For many complexes there are only one or two possible links and I was under the impression it helps "cross-connectivity" of the ontology.

Birgit

**Comment by bmeldal** [comment]
Added to my list of examples.

**Comment by bmeldal** [comment]
Hi @dosumis,

Turns out the 2 side-questions that came up yesterday both came from this ticket!
So, is Jane's suggested solution valid or do we just have one term with its dual role described in the def?

Birgit

**Comment by bmeldal** [comment]
The polymerase complex I mentioned yesterday is GO:0009360 DNA polymerase III complex and its subcomplexes have relationships part_of which was pointed out is wrong [should be has_part]. Should I make a ticket to fix this now or leave til later? I made a note.

**Comment by bmeldal** [comment]
From Cambridge GOC mtg: Could this be resolved if we can use different qualifiers for part_of CC?

**Comment by ukemi** [comment]
At this meeting, the relations were discussed at the level of annotation, not in the ontology itself. So we would not capture these in the ontology, but at the level of annotations.

**Comment by bmeldal** [comment]
Got ya! If we can refine our annotation output from the CP then that would be a good start! We need that chat with the developers before everyone flies home.

**Comment by dosumis** [comment]
Note - you still need to be careful with part relations in GO-CAM.  Where part relationships shift / entities move, you need separate entities - otherwise we hit the same inference problems.

**Comment by bmeldal** [comment]
To be discussed as part of https://github.com/geneontology/go-ontology/issues/14374

**Comment by bmeldal** [comment]
We discussed this on the WG call yesterday (30/11/17):

We think we only need the RPB4-RPB7 complex term, then use annotations to indicate where it functions in a given context.

It appears we, at the CP, requested this term in the first place as it has no other annotations.

Action:
- [ ] rather than obsoleting, change the name and relax the def:
Name: RPB4-RPB7 complex
Def: A protein complexes that cycles between the nucleus where it is part of the RNA polymerase II and the cytoplasmic mRNA processing body where it mediates the two major cytoplasmic mRNA decay pathways.

is_a GO:0043234 protein complex
part_of GO:0005623 cell

- [ ] change annotation in the CP to include
part_of GO:0005665 DNA-directed RNA polymerase II, core complex AND
part_of GO:0000932 cytoplasmic mRNA processing body

**Comment by bmeldal** [comment]
https://github.com/geneontology/go-ontology/issues/14691
is another example of this type.

**Comment by pgaudet** [comment]
Fixed the term as follows:

**Comment by pgaudet** [comment]
-name: RNA polymerase II, RPB4-RPB7 subcomplex
+name: RPB4-RPB7 complex
 namespace: cellular_component
-def: "A protein complexes that mediates transcription and the two major cytoplasmic mRNA decay pathways and is required for efficient translation initiation in association with RNA polymerase II (Pol II)." [GOC:bhm, PMID:15591044]
+def: "A protein complex that cycles between the nucleus where it is part of the RNA polymerase II and the cytoplasmic mRNA processing body where it mediates the two major cytoplasmic mRNA decay pathways." [GOC:bhm, PMID:15591044]
+synonym: "RNA polymerase II, RPB4-RPB7 subcomplex" NARROW []
 xref: IntAct:EBI-2945755
 is_a: GO:0032991 ! protein-containing complex
+relationship: part_of GO:0005622 ! intracellular
