### ISSUE TITLE
OTR: GO:0044650_!_adhesion_of_symbiont_to_host_cell

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11008]
GO:0044650  adhesion_of_symbiont_to_host_cell is a sibling of GO:0019062 ! virion attachment to host cell suggesting that the former refers to cellular symbionts. While I suppose you could have an example of a multicellular organism or substructure adhering at the cellular level, it seems to me that this term should be renamed cell-cell_adhesion_of_symbiont_to_host_cell and should be made a child of GO:0016337_!_cell-cell_adhesion.

Reported by: jimhu

Original Ticket: [geneontology/ontology-requests/10823](https://sourceforge.net/p/geneontology/ontology-requests/10823)

**Comment by pgaudet** [comment]
Hi @jimhu-tamu 
I agree that we should rename 'cell-cell_adhesion_of_symbiont_to_host_cell' 
however it cannot go under 'cell cell adhesion' as we are now separating host processes ('normal processes') and viral processes (normal processes from the symbiont's point of view). 

OK?

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @jimhu-tamu
In fact 'virion attachment to host cell' is a child of 'adhesion of symbiont to host cell' (there has been no change to this term since at least 2014). 

Since virus is not a cell, I dont think we can make the change you propose. I'm closing this, pleaae re-open if needed. 

Thanks, Pascale
