### ISSUE TITLE
GO:0003729 mRNA binding is currently child of poly(A) RNA binding

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11022]
I _just_ noticed this; this is a problem for prokaryotes.  Many prokaryotic mRNAs are not polyadenylated.  I don't know why the poly(A) RNA binding term is in the ontology here, anyway - as far as I can see, it only has the "mRNA binding" child term.  

Thanks,
Ingrid

Reported by: imk07

Original Ticket: [geneontology/ontology-requests/10837](https://sourceforge.net/p/geneontology/ontology-requests/10837)

**Comment by paolaroncaglia** [comment]
(Asking @krchristie  for feedback as she originally commented on this ticket)

Summing up issues and comments in this ticket:

1) ‘mRNA binding’ should not be is_a ‘poly(A) RNA binding’, because many prokaryotic mRNAs are not polyadenylated, and even in eukaryotes not all mRNAs are polyadenylated (e.g. histone mRNAs may have some alternative method of 3' end formation that does not include polyadenylation). Also, types of RNAs other than mRNA can be polyadenylated.

2) ‘poly(A) RNA binding’ currently has a comment specifying that it should be used only for binding to the non-tail portion of a poly(A) RNA (for binding to the poly(A) tail, ‘poly(A) binding’ should be used. But there may be cases where it’s not possible to know where the binding occurs. On a related note, last year Alain Gateau (SIB) suggested:
“Poly(A) RNAs are mRNAs and not the other way around.
Some mRNA binding proteins are Poly(A) RNA binding, when they bind to the PolyA tail of the mRNAs.
The bulk of protein annotated with GO:0044822 [poly(A) RNA binding] comes from two large-scale papers (PMIDs 22658674 and 22681889) [where] the PolyA tail was used for affinity to enrich authentic mRNAs, but there is no data whatsoever telling that the proteins where bound specifically to the PolyA tail.
Looking for GO:0003729 (mRNA binding) in human proteins gives a ridiculous 115 entries, whether GO:0044822 (Poly(A) RNA binding) has 1143 matches!
I suggest to rename 'Poly(A) RNA binding' to 'Poly(A) mRNA binding', to make it a child of GO:0003729, or even a child of GO:0003730 (mRNA 3'-UTR binding), and to transfer annotation from the two papers to GO:0003729.”
Looking at annotations to GO:0044822 ‘poly(A) RNA binding’ today, this is still the case - the term has 1649 direct manual experimental annotations, and only 5 are from papers other than the 2 above. I lean towards following Alain’s suggestion. My only concern is if among those many annotations, any could be to polyadenylated non-coding RNAs rather than mRNAs, since the leading author on one of the two papers wrote 
“Because polyadenylated RNAs are a complex population that includes mRNAs and other RNAs, it should be a direct child of the GO-term RNA-binding” and “Introduce a new GO-term "poly(A) RNA binding" with the definition: 
"Interacting non-covalently with a sequence of residues
in an polyadenylated RNA molecule."
Annotate the proteins from our and from Landthaler's paper with this new term.” [https://sourceforge.net/p/geneontology/ontology-requests/10616/]

Therefore, I suggest to 
- [ ] move ‘mRNA binding’ from under ‘poly(A) RNA binding’ to ‘RNA binding’
- [ ] do not rename nor reposition ‘poly(A) RNA binding’, nor rehouse its annotations, but edit it as follows: 
modify the definition comment from: 
“Note that this term is to be used for the annotation of proteins that bind to any part of a polyadenylated RNA molecule except the poly(A) tail. For annotation of proteins that specifically bind the poly(A) tail, use 'poly(A) binding ; GO:0008143’.”
to:
“Note that this term should only be used when it’s not possible to discriminate if the binding occurs on the poly(A) tail or on other parts of a polyadenylated RNA molecule. To annotate proteins that specifically bind the poly(A) tail, use 'poly(A) binding ; GO:0008143’. Also, consider co-annotating to GO:0003729 ‘mRNA binding’ where appropriate.”

@krchristie would you agree?
I will also follow up with Alain separately by email as I don't know his GH username.

**Comment by krchristie** [comment]
Hi,

I've just reread through this thread, and noticed with great interest this comment Paola made:

"The bulk of protein annotated with GO:0044822 [poly(A) RNA binding] comes from two large-scale papers (PMIDs 22658674 and 22681889) [where] the PolyA tail was used for affinity to enrich authentic mRNAs, but there is no data whatsoever telling that the proteins where bound specifically to the PolyA tail."

I have done quite a lot of PAINT curation of Panther families for proteins that are part of the the 90S-preribosome or the SSU-processome, both involved in the processing of the initial rRNA transcript into the 18S, 25S, and 5.8S rRNAs. A very large number of these ribosome biogenesis genes were annotated with "poly(A) RNA binding" from one of these two papers you mention here, and I am not aware that ribosomal rRNAs are polyadenylated.

Anyway, at this point in time, I am wondering what the value is of a term where the name sounds like it would be binding to the poly(A) tail, but the comment explicitly says it is for use for "proteins that bind to any part of a polyadenylated RNA molecule, except the poly(A) tail."
**How is this different or more useful than just saying "RNA binding".**

Thus, I would be in favor of getting rid of the term "poly(A) RNA binding" (GO:0044822) because I think that at best it is not informative, and that in reality, it is a misleading term. Whether by obsoleting or merging into the term "RNA binding" (GO:0003723) as you think best Paola, though personally, I think the merge would be fine. Certainly, I would not have objected to seeing the term "RNA binding" for the many ribosome biogenesis proteins I have annotated.

-Karen

**Comment by paolaroncaglia** [comment]
Thanks @krchristie for your useful feedback. So the proposal now becomes:

- [ ] move ‘mRNA binding’ from under ‘poly(A) RNA binding’ to ‘RNA binding’
- [ ] merge ‘poly(A) RNA binding’ into ‘RNA binding’

However, we should consider the fate of those annotations (PMID:22658674 and PMID:22681889) one last time. The annotation of those papers, and to a term more specific than ‘RNA binding’, was requested directly by Matthias Hentze (Director of EMBL) 3 years ago (https://sourceforge.net/p/geneontology/ontology-requests/10616/). Jane took care of the ontology edits and @rachhuntley, then at UniProt-GOA, did the annotations (I’m nearly sure, but @krchristie perhaps you could check via Protein2GO please). I’m aware that there is an ongoing discussion about annotating high-throughput papers, but we may still wish to be careful before removing specificity where it was explicitly requested. I may not have full expertise to evaluate the methods from those papers, so let’s see if @rachhuntley remembers about annotating those. If not, I’ll contact Matthias with the proposal above. 
Note that we should probably also email the GOA helpdesk (if those annotations are indeed from GOA staff) to inform them if we do rehouse those annotations.

**Comment by rachhuntley** [comment]
Hi Paola,
I do recall making these annotations, and we did this with extensive review of the papers and discussion with Matthias. We do not make high-throughput annotations lightly, so I'm sure we thoroughly checked these would be appropriate to add - I added a comment in P2GO that they are HTP in lieu of a GOC tag for this.

However, I strongly suggest that you contact Matthias with this proposal as he has the expertise here, I only have what it is the papers and my dim memory to call on.

Thanks.

**Comment by krchristie** [comment]
I looked at the SourceForge item you indicated and understand that they specifically asked for this term.

I also see in that Matthias Hentze clearly indicated in that SourceForge item that **"Because polyadenylated RNAs are a complex population that includes mRNAs and other RNAs, it should be a direct child of the GO-term RNA-binding (GO:0003723)."**

However, considering what the term really means, i.e. binds somewhere in some RNA in a population of RNAs that were selected for binding to oligo(dT), and especially considering what Matthias said about the fact that this is a mixed population of mRNA and other RNAs, it doesn't seem that this is really providing much specificity about what type of RNA binding is occurring. It seems to me that this term really represents an experimental technique more than a biologically relevant population of RNAs.

I also think that the term is easily misinterpreted, both because people less familiar with the technique than he is frequently assume that "poly(A) RNA" is mRNA without realizing that other RNAs are present as well.

**Comment by paolaroncaglia** [comment]
Thanks @rachhuntley and @krchristie for your feedback. I have just emailed Prof. Matthias Hentze to summarise our concerns with the term 'poly(A) RNA binding and to suggest our proposal as above (https://github.com/geneontology/go-ontology/issues/11022#issuecomment-268271255).

**Comment by paolaroncaglia** [comment]
Note for self: emailed Prof. Hentze again today (both him personally and his assistant too, this time).

**Comment by paolaroncaglia** [comment]
Prof. Hentze replied:

"Dear Paola,

No problem! I have not forgotten your email from last week. In fact, I have immediately contacted my colleagues whom I consider “relevant” for their views. As soon as I have these, I will reply. I set myself a deadline of the end of this month, and I hope that this fits with your expectations.

With kind regards.
Matthias"

**Comment by paolaroncaglia** [comment]
Prof. Hentze confirmed today that our plan is good with him and his colleagues:

"Dear Paola,

I understand the issues that you raise and I think that, all things considered, your proposal may well represent the best solution. (My co-authors and) I approve.

Thank you for your efforts - I appreciate them.
Matthias"

**Comment by paolaroncaglia** [comment]
So now the plan is to:

- [ ] Contact InterPro about their mapping: PAB-dependent poly(A)-specific ribonuclease subunit PAN3 (IPR030844) maps to GO:0044822 poly(A) RNA binding; suggest to move it to GO:0008143 poly (A) binding (“Interacting selectively and non-covalently with a sequence of adenylyl residues in an RNA molecule, such as the poly(A) tail, a sequence of adenylyl residues at the 3' end of eukaryotic mRNA.”)

- [ ] Move ‘mRNA binding’ from under ‘poly(A) RNA binding’ to ‘RNA binding’ 

- [ ] Merge ‘poly(A) RNA binding’ into ‘RNA binding’ (make sure the definition comment is removed)

- [ ] Inform relevant databases of the merge above (attach spreadsheet of annotations).

**Comment by paolaroncaglia** [comment]
@asangrador @almitchell @happy-lorna @ndrawlings @EBI-Hsinyu
Following extensive discussion with some GOC members, we resolved to merge GO:0044822 ‘poly(A) RNA binding’ into its parent GO:0003723 ‘RNA binding’. This will affect InterPro in that ‘PAB-dependent poly(A)-specific ribonuclease subunit PAN3’ (IPR030844) maps to GO:0044822 ‘poly(A) RNA binding’. I’d suggest to move the mapping to GO:0008143 ‘poly (A) binding’ (“Interacting selectively and non-covalently with a sequence of adenylyl residues in an RNA molecule, such as the poly(A) tail, a sequence of adenylyl residues at the 3' end of eukaryotic mRNA.”). Thanks in advance!
Paola

**Comment by paolaroncaglia** [comment]
[polyARNAbinding_annotations.xlsx](https://github.com/geneontology/go-ontology/files/726551/polyARNAbinding_annotations.xlsx)

**Comment by paolaroncaglia** [comment]
@slaulederkind
@srengel 
This is just to inform you that, following extensive discussion with some GOC members, we resolved to merge GO:0044822 ‘poly(A) RNA binding’ into its parent GO:0003723 ‘RNA binding’. This will affect 2 RGD and 2 SGD annotations; they will be automatically moved to GO:0003723 ‘RNA binding’. You don’t need to do anything, unless you disagree and wish to recurate your annotations to a different term, or to an additional one such as GO:0008143 ‘poly (A) binding’ (“Interacting selectively and non-covalently with a sequence of adenylyl residues in an RNA molecule, such as the poly(A) tail, a sequence of adenylyl residues at the 3' end of eukaryotic mRNA.”). The affected annotations are attached for your reference (tabs ‘RGD annotations’ and ‘SGD annotations’ in the spreadsheet ‘polyARNAbinding_annotations’). Thanks!

**Comment by paolaroncaglia** [comment]
Emailed help (at) uniprot (dot) org about their annotations. Closing now.

**Comment by srengel** [comment]
Hi Paola,
thanks for the heads-up.  i'm just going to let those 2 SGD annotations get automatically moved to 3723.  i will also add additional annotations to 8143 (thanks for that suggestion).

stacia

**Comment by paolaroncaglia** [comment]
Thank you, @srengel .

**Comment by paolaroncaglia** [comment]
For completeness, copying the reply email from UniProt below: 

"Dear Paola,

I am fine with it, although we might also consider that poly-RNA is part of the
3'UTR and might be merged with 3'UTR

Concerning the 2 high-throughput articles which were curated with authors, my
opinion is that we should not have curated these papers because they generate a
lot of false positives.

I raised this problem several times during GO consortium meetings: I am not
against curating high-throughput studies, but a different evidence code should
be used.

Thanks

Sylvain"
