### ISSUE TITLE
obsolete GO:0009405 pathogenesis ?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11057]
GO:0009405 pathogenesis
Has the comment: note that this term should not be used to annotate gene products that are involved in the host response to pathogenesis. It should only be used to annotate those gene products involved in the generation of pathogenesis by the pathogen itself.

In line with this, I would like the following taxon constraint rules added -
GO:0009405 pathogenesis never_in_taxon 7742 Vertebrata
GO:0009405 pathogenesis never_in_taxon 33090 Viridiplantae

Thanks.

Reported by: fmccarthy

Original Ticket: [geneontology/ontology-requests/10872](https://sourceforge.net/p/geneontology/ontology-requests/10872)

**Comment by dosumis** [comment]
> In line with this, I would like the following taxon constraint rules added -
> GO:0009405 pathogenesis never_in_taxon 7742 Vertebrata
> GO:0009405 pathogenesis never_in_taxon 33090 Viridiplantae

So vertebrates and plants can never be pathogens?

**Comment by dosumis** [comment]
(Anyone know if fmccarthy is on GitHub? Really need her to respond)

**Comment by ValWood** [comment]
The way that pathogenesis is defined in GO
The set of specific processes that generate the ability of an organism to induce an abnormal, generally detrimental state in another organism.

to be a normal process, I think that would exclude vertebrates and plants.
So why not go ahead and add the suggested  taxon constraint, it can be relaxed if there is a use case?

**Comment by deustp01** [comment]
That works for me. As defined and commented, the two edge cases I was fretting about are cleanly out of the scope of GO annotation.

**Comment by ValWood** [comment]
@pgaudet  add taxon constriant

**Comment by pgaudet** [comment]
Is this term really within the scope of GO ? from the symbiont's perspective, they are just surviving. 

WRT @deustp01 's comment

> a host cell receptor co-opted by a virus to mediate its uptake into the host cell
we have now created a term 'hijacked molecular function' that describes that this is not a normal function for the protein. 

Thoughts ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Personally I don't think it does belong in GO.

This would be a suitable process parent for the children instead
GO:0044003    modification by symbiont of host morphology or physiology

There are only 2 children and one already has this parent....

**Comment by ValWood** [comment]
It has a lot of direct annotations though, so I would merge it into 

GO:0044003 modification by symbiont of host morphology or physiology
and make it a related synonym

**Comment by ValWood** [comment]
This has been open since 2014 and we are accumulating annotations. Any objections to the obsoletion of "pathogenesis" from GO?

**Comment by ValWood** [comment]
pathogenesis
- the manner of development of a disease.
- Pathogenesis is the process by which virus infection leads to disease
- Pathogenesis refers both to the mechanism of infection and to the mechanism by which disease develops
-pathogenesis is the origin and development of a disease while 

We can't really have this in GO because pathogensis is not always the outcome of "pathogenic process" that is dependent on the environment and genotype.

Hence, it's only child is "GO:0098676    modulation of host virulence by virus" (I'll get to virulence later)
this  term (GO:0098676) could  be moved under the parent "interaction between species" for now.

EXP  annotation 908 (total 189,000 in QuickGO) and here is another problem. Because pathogenesis is usually very specific to the genotype  and strain of the host and the  'pathogen or symbiont"  it really should not be transferred between species. At all.

A single amino acid variant can often make a difference between pathogenicity and 


(394) | CGD
-- | --
+ | − | (175) | UniProt
+ | − | (92) | MTBBASE
+ | − | (60) | CACAO
+ | − | (56) | PseudoCAP
+ | − | (50) | ASAP
+ | − | (39) | AspGD
+ | − | (12) | GeneDB
+ | − | (8) | CAFA
+ | − | (5) | AgBase
+ | − | (4) | PAMGO_MGG
+ | − | (3) | PAMGO_VMD
+ | − | (3) | TIGR
+ | − | (2) | WB
+ | − | (1) | EcoliWiki
+ | − | (1) | MGI
+ | − | (1) | ParkinsonsUK-UCL
+ | − | (1) | TAIR
+ | − | (1) | UniProtKB

can we merge into "GO:0051701  interaction with host
Definition (GO:0051701 GONUTS page)
An interaction between two organisms living together in more or less intimate association. The term host is used for the larger (macro) of the two members of a symbiosis; the various forms of symbiosis include parasitism, commensalism and mutualism.

OR
GO:0044003    modification by symbiont of host morphology or physiology
(since pathogenesis relies entirely on subverting the machinery of the host)

with pathogenesis as a related synonym?

**Comment by pgaudet** [comment]
Decision @mgiglio99 @ValWood @dsiegele 

1. Review and move annotations of 'Metazoa' to 'pathogenesis' 
2. merge 'pathogenesis' into 'symbiotic process'. 

Pascale

**Comment by pgaudet** [comment]
Annotation review ticket: https://docs.google.com/spreadsheets/d/1v5W2rmYkYriY8U23XC7IdI1wRRfUdlNqIXMDZCfnvCY/edit#gid=0

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0009405 pathogenesis. The reason for obsoletion is that this is not a normal process; it is not a process at all, it's a relation between 2 organisms (one organism can be a pathogen of a different organism). There are nearly 1000 annotations to this term. The annotation review ticket is here: 
https://github.com/geneontology/go-annotation/issues/3452

Contributor  |  (Assigned by)
--|--
AgBase | 5
ASAP | 50
AspGD | 39
CACAO | 60
CAFA | 8
CGD | 400
EcoliWiki | 1
GeneDB | 11
MGI | 1
MTBBASE | 92
PAMGO_MGG | 4
PAMGO_VMD | 3
ParkinsonsUK-UCL | 1
PseudoCAP | 56
TAIR | 1
TIGR | 3
UniProt | 184
WB | 2


The term is in 4 subsets: 
goslim_aspergillus
goslim_candida
goslim_chembl
goslim_metagenomics

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/11057


Since there are many annotations, we propose to do the obsoletion on November 15th, 2020. If you need more time please do let us know. 

Thanks, Pascale

**Comment by bmeldal** [comment]
One CP removed (wasn't exported to GO yet).

**Comment by marekskrzypek** [comment]
This is a pretty radical change for CGD, which deals with several Candida species, pathogens, and where pathogenesis is the main focus of research. Replacing this term with "biological process involved in interspecies interaction between organisms" may be ontologically correct, but few people will understand what it means. I am afraid this will greatly diminish the usefulness of GO for Candida research.

**Comment by ValWood** [comment]
Hi Marek,

I hope you are well!

This  change isn't really about the "ontological correctness' of the term name for "pathogen". The main point is that pathogenesis is clearly outside of the scope of GO. GO is about normal evolved processes. Pathogenesis isn't a process, it's an outcome. An individual  gene is not involved in 'pathogenesis', as pathogenicity  is a property of the organism, not a process.

With GO annotation what we really want to capture are the processes underlying a 'pathogenesis' outcome.
For example "entry into host" or "suppression of host immune system" etc. These will be far more useful than applying a pathogenesis label. We also need to be mindful that we are not just  applying the "interspecies interaction" terms to gene products which are required for an organism to survive, but not for the interaction with the host. These are important distinctions that biologists will require precision in the description of going forwards.

So, ideally when you reannotate these genes you will apply a more specific term in the pathogen-host interaction branch describing the role of the gene product.

Note  also that this decision has been in the pipeline for many years and is fully endorsed by GO members i.e. @mgiglio99  and @dsiegele who provide the microbial phenotype ontology, by @CuzickA  and colleagues at PHI-base, and the rest of the microbial working group.

We are also not saying the pathogenesis isn't something you would want to capture. For this, you can consider ontologies that focus on phenotypes and phenotypic  outcomes (e.g. MPO and PHIPO).

We know this is a pain to deal with, but better now than  further into the future, because it  absolutely needs to be done at some point.

Best,

Val

**Comment by addiehl** [comment]
Any chance "pathogenesis" can be added as a narrow or related synonym to GO:0044003 'modulation by symbiont of host process'.  That would at least give people querying the GO and GO annotators a starting point for finding more appropriate term.

**Comment by ValWood** [comment]
This would  be a better place for the synonym. However, the annotations should still be reviewed because many of the existing annotations are not involved in 
 GO:0044003 'modulation by symbiont of host process'

many are just pathogen gene products that affect virulence when deleted. these range through every process (DNA repair, vesicle-mediated transport, transcription, purine biosynthesis, septation, etc. Many of these affect normal growth and so would have a corresponding effect in virulence but are not involved in the pathogen-host interactions per se.

**Comment by addiehl** [comment]
I agree that the existing annotations need to be reviewed, not just transferred.

**Comment by marekskrzypek** [comment]
Reviewing the existing annotations will not be sufficient in very many cases, since there is no data to make more precise annotations.

**Comment by paolaroncaglia** [comment]
Hi, I agree that GO:0009405 ’pathogenesis’ is a problematic term. In addition to comments already made by others (esp. re: adding ‘pathogenesis’ as a synonym elsewhere in GO), please consider that the term is used by several other ontologies. It’d be really useful for the community if GO could liaise with (at least some of) those, so that they’re aware and they can best address whatever representation need they have. I know it’s usually left to external ontologies to pick up on obsolete terms, but perhaps consider reaching out to at least MP and uPheno. Also, you can’t see this in Ontobee but you can in OLS (https://www.ebi.ac.uk/ols/), the GO term is used in a couple more ontologies related to COVID-19, so quite “current”. (We're using the term in COVOC developed at EBI and I'm unsure what term we should replace it with, from either GO or other ontologies.)

Interestingly, ‘pathogenesis’ is an annotation property in Mondo, used in http://www.ontobee.org/ontology/MONDO?iri=http://purl.obolibrary.org/obo/MONDO_0010626 but possibly not elsewhere - @cmungall?

Thanks,
Paola

**Comment by mgiglio99** [comment]
Hi,
We had planned back in May to merge 'pathogenesis' into "symbiotic process" and make it a narrow synonym. I still favor that plan. That way people looking for pathogenesis will find the symbiotic process set of terms and hopefully will be able find something more specific to annotate to. If they don't, then they can use 'symbiotic process'.

To me the issue is not that there are not evolved processes that pathogens use to cause disease, because there are such processes. The problem is that many (or maybe most) of these same processes are used in situations by microbes that do not cause disease. And in fact the same pathogenic microbe might cause disease in one individual but not another while engaging in all the same processes. Thus that brings us to Val's point about pathogenesis being an outcome. The processes are the same whether or not disease results. So, we should focus on annotating the more specific processes - but if that  is not possible, then there is always 'symbiotic process' if nothing more specific is known. 

I'm sorry I don't remember why the merge option changed to an obsoletion. (Someone please remind me.) Can we do the merge/narrow synonym instead?

**Comment by ValWood** [comment]
> I'm sorry I don't remember why the merge option changed to an obsoletion. (Someone please remind me.)

I think there were 2 reasons why Pascale and I  veered towards obsoletion when we discussed the other day:
1) @cmungall  doesn't like obsoletions ;)
2) Pascale and I looked through the annotation and many were not really involved in  the symbiotic processes. Often they were only a growth phenotype, indicating increased or decreased virulence, but sometimes only affecting the organism's fitness. We need to get a bit fussier about this (and I am hearing the same from people who work in this area). We therefore decided that obsoletion was better because  it forces reconsideration of the original annotation.

Should we reconsider this?  My issue here is that unless these are addressed now, then when? We need to think about the end users and not the burden on curators. If it needs doing, it needs doing....otherwise we leave ourselves open to more of the "GO is useless" type of moans that are periodically popping up on twitter and in publications.

**Comment by mgiglio99** [comment]
Thanks Val - makes sense.
I agree the annotations should be reviewed. 
But even if the term is obsoleted - we could still add the narrow synonym to 'symbiotic process' - correct?

**Comment by ValWood** [comment]
I think so, but it should be "related"

**Comment by ValWood** [comment]
@paolaroncaglia

not also that PATO has the term 'pathogenicity'
The ability of a pathogen to produce an infectious disease or disorder in an another organism. 
Which we planned to use for logical defs in FYPO.
This might be useful for you?

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
 
> note also that PATO has the term 'pathogenicity'
> The ability of a pathogen to produce an infectious disease or disorder in an another organism.
> Which we planned to use for logical defs in FYPO.
> This might be useful for you?

It'd be ok for me, but it wasn't a perfect fit for the users who requested 'pathogenesis' in COVOC. However, if GO 'pathogenesis' is revised (which I agree with), I'll make 'pathogenesis' a synonym of PATO 'pathogenicity' in COVOC. Thanks.

**Comment by vanaukenk** [comment]
WB annotations have been removed.

**Comment by cmungall** [comment]
> Interestingly, ‘pathogenesis’ is an annotation property in Mondo, used in http://www.ontobee.org/ontology/MONDO?iri=http://purl.obolibrary.org/obo/MONDO_0010626 but possibly not elsewhere

I think this is a mistake, the intent was perhaps to have an annotation that describes the patho*physiology* @nicolevasilevsky not urgent but let's fix in mondo

**Comment by cmungall** [comment]
Note also that kw2go has:

UniProtKB-KW:KW-0843 Virulence > GO:pathogenesis ; GO:0009405

We get a lot of annotations from this

and a few more from:

UniProtKB-KW:KW-0260 Enterotoxin > GO:pathogenesis ; GO:0009405

**Comment by pgaudet** [comment]
@sylvainpoux is supposed to change the keywords - or is it someone from GOA that needs to change the keyword mappings ?

**Comment by sylvainpoux** [comment]
Hi @pgaudet. GOA will remove the (@alexsign) mapping.

Don't you think it would be a good ides to resurrect the GO term virulence? It is not a phenotype, but the way viruses act. Having this GO terms allows annotating virulence proteins.

Sylvain

**Comment by ValWood** [comment]
Hi @sylvainpoux ,

Virulence also doesn't belong in GO.  Virulence refers to the severity or harmfulness of a disease, so it is;'t describing  a biological process  
Usually virulence is described in terms of an increase or decrease (so that the effect of engineered or natural variants on virulence can be captured).

 If you are describing virulence at the level of a gene product it isn't so useful unless the underlying variant is also captured.
If you want to describe  virulence it is better to use the phenotype ontologies (MPO  or PHIPO).

In PATO, virulence is described as an organismal quality:
A quality inhering in a bearer by virtue of the severity of infectious disease caused by the bearer in a target organism.

https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0002146

**Comment by mah11** [comment]
correction:

> note also that PATO has the term 'pathogenicity'
> ...
> Which we planned to use for logical defs in FYPO.

This probably refers to [PHIPO](https://github.com/PHI-base/phipo); it's certainly not true for FYPO (we have no need to define diseases in fission yeast).

**Comment by ValWood** [comment]
corrected above

**Comment by pgaudet** [comment]
Dear all, 

The multiorganism working group would like to go ahead with the obsoletion of 'pathogenesis' 


InterPro:IPR002061
InterPro:IPR005639
InterPro:IPR008872
InterPro:IPR009896
InterPro:IPR012553
InterPro:IPR012624
InterPro:IPR027018


See spreadsheet: https://docs.google.com/spreadsheets/d/1v5W2rmYkYriY8U23XC7IdI1wRRfUdlNqIXMDZCfnvCY/edit#gid=1325213023

Group | Number of annotations
-- | --
AgBase | 5
ASAP | 51
AspGD | 39
CACAO | 60
EcoliWiki | 1
GeneDB | 15
GOC | 1
JCVI | 3
MTBBASE | 90
PAMGO_GAT | 6
PAMGO_MGG | 8
PAMGO_VMD | 2
PseudoCAP | 56
RGD | 1
TAIR | 1
TIGR | 98
UniProt | 119
WB | 2
TOTAL | 558

**Comment by gthayman** [comment]
RGD annotation removed.

**Comment by pgaudet** [comment]
@sarach06 @EBI-Hsinyu I just noticed nobody from InterPro was tagged - can you please address this?

**Comment by pgaudet** [comment]
* InterPro:IPR002061 -> consider GO:0044063 modulation by symbiont of host nervous system process (although a more specific child would be nice); GO should also consider restoring 'neurotoxin activity'
* InterPro:IPR005639 -> consider GO:0001897 cytolysis by symbiont of host cells; GO should also consider restoring channel-forming toxin activity
* InterPro:IPR008872 -> consider MF GO:0090729 toxin activity; remove BP (nice newer review: PMC4280536)
* InterPro:IPR009896 -> consider GO:0044650 adhesion of symbiont to host cell & remove  GO:0007157 
heterophilic cell-cell adhesion via plasma membrane cell adhesion molecules (not intended for interspecies interactions)

I'll add suggestions for other later: 

* InterPro:IPR012553
* InterPro:IPR012624
* InterPro:IPR027018

**Comment by sarach06** [comment]
Hi Pascale,
Many thanks for tagging us here. I've made the changes you mentioned, which will be visible in the next InterPro release (85.0). In the case of IPR002061, which includes plant defensins, I think GO:0044063 would be wrong for those proteins in this entry, let me know if you agree. However, I added GO:0044063 to IPR018218 (Scorpion long chain toxin) and deleted pathogenesis.

Best,
Sara

**Comment by pgaudet** [comment]
Dear all, 

The obsoletion of 'GO:0009405 pathogenesis' will take place shortly. Again, the reason for this obsoletion is that pathogenesis does not describe a single, normal biological process; rather it is the effect of an interaction between two organisms, under specific conditions. 

There are multiple other terms that can be used, and that describe better symbiont/pathogen effect on the host, including 
GO:0044003 modulation by symbiont of host process
GO:0052031 modulation by symbiont of host defense response
GO:0001907 killing by symbiont of host cells

and their descendant. 

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/11057

Thanks, Pascale
