### ISSUE TITLE
OBS: GO:0022405 ! hair cycle process and GO:0022404 ! molting cycle process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11123]
This terms adds no new information, as we have part_ofs for the entire cycle.

Seems like they were added for isa completeness?

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/10940](https://sourceforge.net/p/geneontology/ontology-requests/10940)

**Comment by paolaroncaglia** [comment]
Summing up:

- Edit the following class labels to read ‘regulation of timing of x’ instead of ‘regulation of x’, e.g. 'regulation of timing of anagen' instead of 'regulation of anagen’:
regulation of anagen (+ pos and neg children)
regulation of catagen (+ pos and neg children)
regulation of exogen (+ pos and neg children)

- Edit def accordingly

- Add GOC:pr

- Close.
