### ISSUE TITLE
parentage of GO:0016533 cyclin-dependent protein kinase 5 holoenzyme complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11146]
Hi,

I think this term's relationships need adjusting:
At least in human, the CDK5 (Q00535) complexes have both cytoplasmic and nuclear relationships, depending on the isoform of the activator: p35 (CDK5R1, Q15078) and p39 (CDK5R2, Q13319) localise CDK5 to the cytoplasmic side of the plasma membrane while the proteolytic p25 (CDK5R1, PRO_0000004795) localises the complex to the nucleus (PMID: 18507738).

The other issue is that it is not cyclin-dependent even though that's what the name says. It's named because of sequence homology to other CDKs but has it's own activator molecules (see above). Although, parent term GO:0000307 cyclin-dependent protein kinase holoenzyme complex does not contain cyclin as the activator in the def so it should be fine. 

Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/10963](https://sourceforge.net/p/geneontology/ontology-requests/10963)

**Comment by pgaudet** [comment]
@bmeldal 

What needs to be done exactly ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
- [x] Subcellular location: no action as it can't have part_of relationship to cytoplasm AND nucleus.

Fix GO:0016533 cyclin-dependent protein kinase 5 holoenzyme complex:
Main problem: CDK5 is **NOT** cyclin-activated but has its own activators: CDK5R1 or CDK5R2. This needs to be fixed in the following term names and defs:

- [ ] Re-name to GO:0016533 ~~cyclin-dependent~~ protein kinase 5 holoenzyme complex

- [ ] delete "holo" in "holoenzyme" as the complex always consists of the kinase CDK5 + activator subunit? There are no children that have different enzymes.

- [ ] fix def of GO:0016533 ~~cyclin-dependent~~ protein kinase 5 holoenzyme complex: 

- A protein complex that activates cyclin-dependent kinase 5; composed of regulatory and catalytic subunits.
+ A protein complex that has protein serine/threonine kinase activity; in mammals composed of catalytic subunit CDK5 and regulatory subunits CDK5R1 or CDK5R2. Contrary to its gene symbol, CDK5 is not cyclin-dependent.

- [ ] is_a Parentage: should be is_a GO:1902554 serine/threonine protein kinase complex NOT GO:0150005 enzyme activator complex

- [ ] capable_of relationship: replace GO:0016534 cyclin-dependent protein kinase 5 activator activity (which applies to the activator subunit of the complex, not the complex itself) with GO:0004674 protein serine/threonine kinase activity (which it should inherit from new is_a parent anyway)

I think that's it - famous last words...

Birgit
