### ISSUE TITLE
ergothioneine biosynthesis BP query

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11163]
This is another request related to PMID:24828577 community curation. Our intrepid user communicated this:

"Note: there is a slight mess in the child terms of 0052699.

Child term G0:0052704 describes ergothioneine biosynthesis via trimethyl-histidine. But it also says that trimethyl histidine is bound to gamma-glutamyl-cysteine, which is the case in bacteria but not in eukaryotes. In eukaryotes (including S.pombe) trimethyl-histidine is bound to cysteine.

Chile term GO:0052711 describes ergothioneine biosynthesis from hercynine. However, in many eukaryotes hercynine is not really an important intermediate in the pathway, as a single gene (egt1 in S.pombe) converts histidine directly to hercynylcysteine sulfoxide. 

I think the child terms G0:0052704 and GO:0052711 should be completely removed, and we should only keep GO:0052699 for ergothioneine biosynthesis as a biological process."

Even if you don't want to merge or obsolete the child terms, it sounds like the definitions might need a review, and maybe some taxon restrictions would help.

Reported by: mah11

Original Ticket: [geneontology/ontology-requests/10980](https://sourceforge.net/p/geneontology/ontology-requests/10980)

**Comment by ukemi** [comment]
#11657

**Comment by ukemi** [comment]
Val,

Can you have a look at the other one that is above? I think this might be done if you can give me some taxon restrictions.

-D

**Comment by ValWood** [comment]
@mah11 is this resolved for us?

David says
I think this might be done if you can give me some taxon restrictions.

**Comment by mah11** [comment]
It's been a loooong time since I last thought about this!

If (possibly big _if_) I understand the PMID:24828577 introduction and Tomas' comments correctly, there are two possible routes from histidine to ergothioneine, one found in bacteria and the other in fungi (blue vs. green arrows in PMID:24828577 Figure 1A, DOI http://dx.doi.org/10.1371/journal.pone.0097774.g001).

I'm getting the impression that one of the problems with the GO terms is that GO:0052704 and GO:0052711 don't actually correspond to those two alternative routes, but instead make a non-useful distinction. It's like GO:0052704 represents the bacterial pathway, and GO:0052711 represents most of the same pathway, minus the first step.

Maybe GO:0052711 should go obsolete.

I guess GO:0052704 should be taxon-restricted to bacteria, and renamed to say 'via gamma-glutamyl-hercynylcysteine sulfoxide' (CHEBI:82703, I think), because N-alpha,N-alpha,N-alpha-trimethyl-L-histidine is in both pathways.

I don't see a term for the fungal pathway, so I guess one should be added and restricted to fungi. I'm not sure how to name it, because its distinguishing feature is that it doesn't go via the gamma-glutamyl-hercynylcysteine sulfoxide intermediate. It does use the other intermediates (including N-alpha,N-alpha,N-alpha-trimethyl-L-histidine, aka hercynine, aka histidine betaine, so I'm not sure why Tomas said "in many eukaryotes hercynine is not really an important intermediate in the pathway"; maybe he meant that it doesn't accumulate).

**Comment by ValWood** [comment]
Hi @ukemi  do you need any further information from us to complet this?

Val

**Comment by ukemi** [comment]
It would be nice to have the specific terms, definitions and references that are needed and need to be obsoleted.

**Comment by mah11** [comment]
Well. It's been quite a while since I looked at or thought about this stuff, but I'll see if I can help at all. Be warned that this contains some guesswork:

GO:0052704:
- Rename to "ergothioneine biosynthesis from histidine via gamma-glutamyl-hercynylcysteine sulfoxide".
- Edit def to something more like "A biosynthetic process that results in the formation of ergothioneine from histidine via a set of steps in which gamma-glutamyl-hercynylcysteine sulfoxide is formed as an intermediate." Keep as much or as little of the rest as you want, I guess.
- Use PMID:24828577 and PMID:20420449 (DOI:10.1021/ja101721e is PMID:20420449) as def dbxrefs. I don't know if the other two PMIDs are also useful, so check if you're feeling motivated. I do think the EC and Wikipedia xrefs can be dropped from this def.
- Add taxon restriction only in Bacteria.
- I think this can have has_part GO:0044875.

GO:0052711:
- Make this obsolete. Its definition isn't very enlightening, and doesn't adequately distinguish it from its parent or from GO:0052704 (because that trimethyl-His yada is in both pathways).

Add a new term for the pathway found in (some) fungi. The term name is something I've jsut made up on the spot; I don't particularly like it, but it does say exactly what the distinguishing feature is. Change it if you think of anything better (same goes for the def).

id: GO:new
name: ergothioneine biosynthesis from histidine via hercynylcysteine sulfoxide synthase
def: A biosynthetic process that results in the formation of ergothioneine from histidine via a set of steps including the hercynylcysteine sulfoxide synthase reaction, which converts N-alpha,N-alpha,N-alpha-trimethyl-L-histidine directly to hercynylcysteine sulfoxide. [PMID:24828577, PMID:22209968]
is_a: GO:0052699
has_part GO:0061686
taxon restriction only in Fungi

p.s. I just noticed that the name for GO:0061686 is missing the word "activity".

**Comment by deustp01** [comment]
Nothing to add from here to the expert discussion of alternative biochemical pathways above.

**Comment by mah11** [comment]
ping! Any reason the changes described [here](https://github.com/geneontology/go-ontology/issues/11163#issuecomment-327263006) can't or shouldn't be done?

**Comment by ukemi** [comment]
I just looked at this one the other day, so do you want me to implement your suggestions above?

**Comment by mah11** [comment]
sure; thanks!

**Comment by ValWood** [comment]
Hi @ukemi  any progress?
cheers
Val

**Comment by ValWood** [comment]
Hi,  @ukemi can this one be closed? has been open since 2014, but has a fairly clearly documented solution, just needs implementing....
thanks!

**Comment by ukemi** [comment]
@pgaudet, would you mind taking this one?

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0052711 ergothioneine biosynthesis from N-alpha,N-alpha,N-alpha-trimethyl-L-histidine. The reason for obsoletion is that this term does not provide a useful distinction from its parent, GO:0052704 (because that trimethyl-His yada is present in both pathways). There are no annotations to this term. There is an incorrect mapping to a KEGG reaction, https://www.genome.jp/dbget-bin/www_bget?rn:R04878. This reaction has the comment "incomplete reaction”; at this point it will not be mapped to another reaction (unless someone has a suggestion). This term is not present in any subsets. 

Any comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/11163


Thanks, Pascale

**Comment by pgaudet** [comment]
- [x] obsoleted GO:0052711 ergothioneine biosynthesis from N-alpha,N-alpha,N-alpha-trimethyl-L-histidine
**GO:0052704:** 
- [x] changed label GO:0052704 to ergothioneine biosynthesis from histidine via gamma-glutamyl-hercynylcysteine sulfoxide
- [x] Removed doi and EC def xref, and moved wikipedia def xref to xrefs

GO:0044875 gamma-glutamyl hercynylcysteine sulfoxide synthase
- [x] Update xref EC:1.14.99 -> EC:1.14.99.50 and add xref and def xref RHEA:42672
- [x] add 'activity' to term label
- [x]  add 'part of' some 
GO:0061686
- [x] add activity to term label
- [x] removed wrong reference PMID:28577

**Comment by pgaudet** [comment]
Added taxon constraints
GO:0052704	ergothioneine biosynthesis from histidine via gamma-glutamyl-hercynylcysteine sulfoxide	NCBITaxon:2	Bacteria
GO:0140479	ergothioneine biosynthesis from histidine via hercynylcysteine sulfoxide synthase	NCBITaxon:4751	Fungi
