### ISSUE TITLE
locations of "protein homodimerization activity" vs "protein homotetramerization

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11269]
Hi,

I was curating a paper about complexes of the retinoid X receptors (citation below) and found the BP term "protein homotetramerization". I was surprised that this was in process, since I already knew that "protein homodimerization activity" and "protein heterodimerization activity" are MF terms.

It seems logically inconsistent that we are representing "protein dimerization activity" in MF, but we are representing tetramerization ability in BP. 

-Karen

Chen H, Privalsky ML. Cooperative formation of high-order oligomers by
retinoid X receptors: an unexpected mode of DNA recognition. Proc Natl Acad Sci U
S A. 1995 Jan 17;92(2):422-6. PubMed PMID: 7831303

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/11087](https://sourceforge.net/p/geneontology/ontology-requests/11087)

**Comment by paolaroncaglia** [comment]
Note for self: related tickets:
https://github.com/geneontology/go-ontology/issues/11748
https://github.com/geneontology/go-ontology/issues/11094

**Comment by paolaroncaglia** [comment]
Work on this branch is still planned, but parked for now due to other priorities.
Plan to come back to this in the second half of 2016.

**Comment by RLovering** [comment]
Hi All

the problem with BP and MF and CC terms wrt oligomerization materialised again in one of the UCL team meetings. 

It does seem like several people agreed with the following concepts:

BP term for protein complex assembly (and removing the BP oligomerization terms) to enable more consistent annotation to this term, with the proteins facilitating the assembly annotated to this term (but not proteins which are assembled). Around 1000 annotations would need to be reviewed but in many cases this might not take too long as it should be obvious if the protein is a target (in which case the annotation needs to be changed to the appropriate MF term) or facilitator.

MF terms expanded to include oligomerization activity etc then the IPI evidence code could be used with enables the inclusion of an ID in the WITH field. 

Specific complex CC terms are being created but the general feeling seemed to be that the general term 'oligomer' etc should not be created. 

An alternative is to leave the situation as it is, and assume that if a protein self-assembles into an oligomer that it is involved in the process of oligomerization, because no other proteins are required to facilitate this. In which case add a comment to this record to encourage curators to use this term only for the targets of oligomerization if no other proteins involved in the process (which, as previously mentioned in several other tickets, does sort of imply this is a function not a process).

Ruth
@rachhuntley @BarbaraCzub @NancyCampbell

**Comment by paolaroncaglia** [comment]
@RLovering 
Thanks for your thoughts on this. If I don't have time to work on this again, your summary could be used as a starting point to outline future work.

**Comment by dosumis** [comment]
@thomaspd: Given our recent discussions, where do you stand on MFs for dimerization, homodimerization, oligomerization etc?  

> MF terms expanded to include oligomerization activity etc then the IPI evidence code could be used with enables the inclusion of an ID in the WITH field.
 
For formalization, we really need ID of binding partners in has_input.

**Comment by paolaroncaglia** [comment]
I opened a new ticket to collect previous discussions on this topic (protein dimerization/oligomerization), and hopefully aid towards a future resolution.
I’m closing this one. Please monitor https://github.com/geneontology/go-ontology/issues/13036 instead. Thanks!
