### ISSUE TITLE
non-membrane spanning protein tyrosine kinase activity query

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11305]
1.
Do we need this term? It seems odd to describe an activity by wht it isn't.
If we do need it

```
histone tyrosine kinase activity
```

should be a child

2.
receptor signaling protein tyrosine kinase activity
Seems to combine function and process information

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11127](https://sourceforge.net/p/geneontology/ontology-requests/11127)

**Comment by ValWood** [comment]
This one seemed to have a solution?

**Comment by dosumis** [comment]
Fixed the def: 
non-membrane spanning protein tyrosine kinase activity : "Catalysis of the reaction: ATP + protein L-tyrosine = ADP + protein L-tyrosine phosphate by a non-membrane spanning protein."^^xsd:string

+ moved 'histone tyrosine kinase activity' underneath.  Otherwise left as-is.  Agree it's an odd class, but it is well used, and does reflect EC.
