### ISSUE TITLE
telomeric heterochromtin ve subtelomeric heterochromatin

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11429]
We have a component term  "telomeric heterochromatin", and various process terms containing this string.

which makes the logic here slightly incorrect:
telomeric region
--telomeric heterochromatin (this is in the subtelomere)
--nuclear telomere cap complex (this is at the telomere proper)

The telomeric/subtelomeric  heterochromatin isn't really part of the telomere per se, it is adjacent to the telomere (the region of repetative DNA where the cap complex resides). A fix for this would be to rename/define all "telomeric heterochromatin" as "subtelomeric heterochromatin"

This would then mirror the SO arrangement which has 2 disjoint terms:
telomere (the chromosome end i.e. telomeric repeats, where the capping complex localizes)
and
subtelomere (adjacent to the telomere, where the heterochromatin resides)

The grouping term "telomeric region" needs to be defined to include the telomeric cap and the subtelomeric heterochromatin  (at present it isn't).
There could probably be a better label for "telomeric region" (esentially includes the telomere and the subtelomere), but I can't think of one.

I'll assign this to David as it is closely aligned to the recent rearrangements of the centromere terms.
Also, Ruth  &Co should take a look first and see if they approve as they are working in this area.

VAl

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11254](https://sourceforge.net/p/geneontology/ontology-requests/11254)

**Comment by NancyCampbell** [comment]
@NancyCampbell

**Comment by ukemi** [comment]
@ValWood @mah11 
Should I go ahead and make the three regions?
-D

**Comment by ValWood** [comment]
I think we need input on this one! I'm still unsure what the technical definitions of the telomeres and subtelomeres.

**Comment by RLovering** [comment]
Hi Val

there are a few github tickets that need to be considered here, https://sourceforge.net/p/geneontology/ontology-requests/10526
https://github.com/geneontology/go-ontology/issues/2537 

Also I think some of these discussions arise from the difference between human and pombi telomeres. The human telomere contains a very long repeat region, because there is no telomerase in many mitotic cells and therefore the telomere gradually shortens with each replication. In contrast, from what I can remember from previous discussions, in pombi the sequences is very short and the telomere is literally the last few bp of the chromosome, because telomerase is always present and therefore there is no telomere shortening. See previous discussions re subtelomere etc.

However, I can't see any problems with having the 3 terms:
telomeric region
>part_of child term: telomere 
>part_of child term: subtelomere 

if that is what is being suggested.

I can ask the people here who have been annotating telomeres specific questions if you would like me to, but I can't work out from above what the specific question is. 

best

Ruth

**Comment by pgaudet** [comment]
@ValWood  I think this can be closed ?

**Comment by pgaudet** [comment]
Redundant with #19086

**Comment by ValWood** [comment]
Yes,  we now have the solution I requested in 2014 ;)  At the time it was never completed because we got bogged down in the spin-off discussion.
