### ISSUE TITLE
GO and vesicle nomenclature

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11504]
Copying most recent email from Kei-Hoi Cheung (key.cheung@yale.edu):

“Dear GO team,

At our recent Extracellular RNA Communication Consortium (ERCC) 3rd Investigators' Meeting, we have reached a consensus on the proposal of the modified GO structure to include new exRNA-related terms/synonyms.  This version (attached) incorporates feedback from the International Society for Extracellular Vesicles (ISEV) and American Society for Exosomes and Microvesicles (ASEMV) boards and the metadata/data working group for the ERCC as well as input from the wider extracellular vesicle (EV) community. 

Thank you for your patience and input. Please feel free to let us know if you have any questions.

Best,

-Kei”

See attachment.
Email thread is “GO and vesicle nomenclature” and go-ontology is cc’d.
I’ll get back to the group with suggestions/clarifications. Then once the proposal is complete, I’ll email around goc@ for input.

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/11330](https://sourceforge.net/p/geneontology/ontology-requests/11330)

**Comment by paolaroncaglia** [comment]
Attaching doc quoted in first comment, as this wasn't copied over in the SF-to-GH migration.
[EV_NOMENCLATURE_OPTION_2_GO.pptx](https://github.com/geneontology/go-ontology/files/38949/EV_NOMENCLATURE_OPTION_2_GO.pptx)

**Comment by paolaroncaglia** [comment]
Completed edits requested by collaborators.

Left to do, stemming from work above:
- clarifying in the ontology that all vesicles are membrane-bounded
- adding has_part links between GO ribonucleoprotein terms and CHEBI (ribonucleoprotein complex has_part protein, has_part RNA)
- making sure that all existing plasma lipoprotein particle-related terms in the biological process branch refer to the appropriate term (plasma lipoprotein particle rather than lipoprotein particle)

**Comment by paolaroncaglia** [comment]
Working on "clarifying in the ontology that all vesicles are membrane-bounded". Next to do for this task: 
- merge 'cytoplasmic, membrane-bounded vesicle' with 'cytoplasmic vesicle' (place all its children appropriately first)
- merge 'membrane-bounded vesicle' with 'vesicle'

**Comment by paolaroncaglia** [comment]
Working on 
- [ ] making sure that all existing plasma lipoprotein particle-related terms in the biological process branch refer to the appropriate term (plasma lipoprotein particle rather than lipoprotein particle)
A search for ‘plasma lipoprotein particle’ highlighted problematic terms. I made a couple of quick fixes today. Still need to work on the following:

lipoprotein particle binding (has_input ‘plasma lipoprotein particle’, but the def is general, and the manual experimental annotations are to mouse, human, Drosophila, Neosartorya fumigata (Aspergillus) and trout. Should replace has_input with ‘lipoprotein particle. Check if the CHEBI dbxref is correct.)

plasma lipoprotein particle oxidation + reg. terms - I still need to look at these 

plasma lipoprotein particle organization + children - I still need to look at these

plasma lipoprotein particle clearance + children - I still need to look at these

**Comment by paolaroncaglia** [comment]
Left to do for this ticket:

- [ ] Edit ‘lipoprotein particle binding’ so it has_input ‘lipoprotein particle’ rather than ’plasma lipoprotein particle’

- [ ] Edit ‘plasma lipoprotein particle oxidation’ so the primary name is ‘plasma lipoprotein oxidation’ (currently an exact synonym), and ‘plasma lipoprotein particle oxidation’ stays as a related synonym

- [ ] Edit ‘regulation of plasma lipoprotein particle oxidation’ so the primary name is ‘regulation of plasma lipoprotein oxidation’ (currently an exact synonym), and ‘regulation of plasma lipoprotein particle oxidation’ stays as a related synonym

- [ ] Similarly for neg reg term

- [ ] Look at ‘plasma lipoprotein particle organization’ + children, and edit if/where needed

- [ ] Look at ‘plasma lipoprotein particle clearance’ + children, and edit if/where needed

**Comment by paolaroncaglia** [comment]
Cleaning up. Outlined remaining tasks in new GH ticket:
https://github.com/geneontology/go-ontology/issues/13037
Closing this one now.

**Comment by RLovering** [comment]
Hi Paola
sorry to arrive late in this discussion. I am not convinced that we should remove the plasma lipoprotein particle name. It makes sense to group HDL, LDL, VLDL, chylomicron etc under a common parent, there is a correlation between the levels of these proteins. Or have I missed something. It seems like there going to be lipoprotein particles which are not plasma lipoprotein particles grouped with HDL, LDL, VLDL, chylomicron. The proteins associated with processes associated with the individual types of plasma lipoprotein particles (only 19 annotated to the assembly term) may not have a role in other lipoprotein particle processes, but the numbers of proteins associated with the individual subtypes of plasma lipoprotein particles are much lower (currently between 2 and 10). Consequently, the revision will mean that HTP functional analysis is unlikely to detect enrichment of the assembly term for subtypes of plasma lipoprotein particles because of the low number of proteins annotated to these processes, and would be unlikely to detect enrichment of lipoprotein particle assembly because of the large number of proteins which are involved in the assembly of non-plasma lipoprotein particles. 

Please confirm whether or not the proposal will leave subtypes of plasma lipoprotein particles grouped with very unrelated particles.

Thanks

Ruth

**Comment by paolaroncaglia** [comment]
Hi @RLovering ,
My proposal is not a definitive resolution, rather a reminder that work is needed to make representation of these terms more consistent, now that we also have non-plasma-specific terms. Whoever picks up this task in the future should keep your concerns in mind, so I'll copy your comment on to the new GH ticket (and will mention you there so you'll receive notifications). Thanks!
