### ISSUE TITLE
naming and hierarchy of SNARE complexes

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11606]
Hi,

I'm curating a bunch of SNARE complexes, many new to GO. I would like to name them consistently. At the moment, GO names are simply <Prot1-Prot2-Prot3-Prot4> complex without indication of the location and all are simple children of GO:0031201 SNARE complex.

I was wondering if we can indicate the compartment in the name, e.g.

Golgi SNARE <Prot1-Prot2-Prot3-Prot4> complex, or
<Prot1-Prot2-Prot3-Prot4> complex (Golgi)

However, there are some SNAREs that are found in multiple compartments, such as ER-to-Golgi vesicles AND cis-Golgi cisternae. In such cases, the location-in-brackets option above would work, e.g.:
<Prot1-Prot2-Prot3-Prot4> complex (ER-to-Golgi vesicle / Golgi)

As for the hierarchy, would it work to add location-related parents, e.g. 'Golgi SNARE complexes', 'endosome SNARE complexes' etc? Again, if a SNARE occurs in several compartments, could we have two is_a relationships? They would occur sequentially, i.e. move from the ER to the Golgi via the ER-to-Golgi vesicle...

Any comments?

Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/11435](https://sourceforge.net/p/geneontology/ontology-requests/11435)

**Comment by ukemi** [comment]
@bmeldal 

I see there are a bunch of SNARE complexes in the ontology now. Is there something we need to do with them to close this ticket?

-D

**Comment by bmeldal** [comment]
Hi David,

The existing SNARE complexes are really old (2009). At first glance they are all just defined as "A SNARE complex that contains <list of members>".

My original idea was to introduce some hierarchy when I was going to create the new SNARE complex terms. However, I got bogged down and overwhelmed with the number of SNAREs that exist and their lack of IPI evidence! In the end, I created a few in the CP and carried on with something else more pressing at the time!

The original question, however, is still valid: It there any way we can group SNAREs by more than their composition, a strategy we have since decided was only going to inflate the ontology? On the other hand, there are so many SNAREs, curators and users would like to be more precises when annotating their proteins than just using "SNARE complex"... Their function is always the same so that's no longer a distinguishing factors at this level.

Maybe @dosumis can comment?

Birgit

**Comment by pgaudet** [comment]
This is what SNAREs look like right now
<img width="569" alt="image" src="https://user-images.githubusercontent.com/4782928/186353189-67cfac6e-c8e2-4ded-8580-a6c983335766.png">



If someone from IntAct/ComplexPortal wants to help with this, please reopen. 

@sandraorchard
