### ISSUE TITLE
relabel GO:0060021 'palate development' to 'secondary palate development'

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11680]
I tried to create the term "secondary palate development' via GO TermGenie but had this message:

Failed to create the term secondary palate development with the logical definition: "'anatomical structure development' and 'results in development of' some UBERON_0001716" The term GO:0060021 'palate development' with the same logic definition already exists

I have created a similar term for primary palate via TermGenie:
GO:1903929 Label: primary palate development

Reported by: cindyJax

Original Ticket: [geneontology/ontology-requests/11510](https://sourceforge.net/p/geneontology/ontology-requests/11510)

**Comment by ValWood** [comment]
@cindyJax can you  confirm ?

**Comment by pgaudet** [comment]
@cindyJax or someone at MGI (@ukemi ) can you please have a look ? 
If we don't have a response I'll close this in the upcoming days. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ukemi pinging you to get a response from MGI. 

Thanks, Pascale

**Comment by ukemi** [comment]
I think the relabeling is the correct way to go here, but we should review the annotations that are made directly to palate development to be sure that they always refer to the secondary palate. If I am not mistaken, the phenotype of a cleft palate is due to defects in the secondary palate. I have checked a few MGI annotations and they all seem to refer to secondary palate.

**Comment by sabrinatoro** [comment]
We would need to have a separate “palate development” term, which does not refer to primary or secondary palate.
The adult palate in zebrafish is different enough in bone composition and structure I would be concerned about using the mammalian palate terms.
Zebrafish embryonic cartilage (which is a good model of palate development) changes locations entirely in the adult. Most of GO annotations are based on phenotypes observed in the embryos, and therefore we do not know for sure which palate development is affected: the primary, secondary, or both.

**Comment by sabrinatoro** [comment]
After discussion with David H, and discussion with Ceri, here is the ZFIN suggestion: 
- It is not possible to distinguish in zebrafish which part correspond to the primary palate and the secondary palate, and especially at the developmental stages at which the experiments (and the GO annotations based on these experiments) are done. Therefore we need a more general term.
- The Uberon term “roof of mouth” (UBERON:0007375) would be appropriate to refer to the zebrafish palate. 
- From a usage point of view, it would be better to have the term “palate” instead of “roof of mouth”. 

Suggestion: 
New term called “palate development”
This term has “roof of mouth” (UBERON:0007375) in the logical definition. 
Synonym: roof of mouth development
Notes: this term should be used when the distinction between the primary and secondary palate cannot be made, for example in zebrafish larvae.

**Comment by cmungall** [comment]
[Roof of mouth](http://purl.obolibrary.org/obo/UBERON_0007375) in uberon encompasses structurally different entities in different species.

Def: _A multi-tissue structure consisting of bone and soft tissue that forms a part of the roof of the oral cavity. In mammals this is the combination of the primary palate (premaxilla) and the secondary palate. In early tetrapods it consists of the vomer, pterygoid, parasphenoid, palatine and ectopterygoid bones_ (my definition)

Uberon has a more specific class "primitive palate" [UBERON:0012316](http://purl.obolibrary.org/obo/UBERON_0012316)

_Roof of the buccal cavity, formed from the fusion of vomer, pterygoid, parasphenoid, palatine, ectopterygoid_ (definition from Kardong)

This is the class that is mapped to  ZFA:0005509 ! palate

graph:

![image](https://user-images.githubusercontent.com/50745/35254045-708eb7e0-ff9d-11e7-883b-f47aba62b3d9.png)

I'm always vary of annotating directly to developmental processes that group structurally different entities. How we feel about making a more specific GO class for the development of the primitive palate? We can also have development of roof of mouth as a grouping, if that is important.

**Comment by cmungall** [comment]
caveat: it's been a while since I looked at this, and I was never fully satisfied with the vertebrate skull representation in uberon

**Comment by pgaudet** [comment]
Aren't the other comments here? https://github.com/geneontology/go-ontology/issues/11680

**Comment by ukemi** [comment]
Proposal:

Rename 'palate development' to 'secondary palate development' and keep the logical definition the same.

Create a new term 'primitive palate development'  using the UBERON term and have ZFIN curators move their annotations to this term.

**Comment by sbello** [comment]
I don't know that this fixes the issue for the MP. We have the terms:
abnormal palate development (MP:0009653) currently uses GO:0060021 in the logical definition
   abnormal primary palate development (MP:0009654) 
   abnormal secondary palate development (MP:0009655)
If you change GO:0060021 I can create a logical definition for MP:0009655 but now I can't use this for MP:0009653 and I don't think that the term primitive palate development would be correct for the MP example. I think we really want a grouping term for palate development that encompasses any type of palate. The UBERON term 'roof of mouth' does seem like the best fit.

**Comment by ukemi** [comment]
OK. This is getting a bit confusing. It looks like palate development in GO already had its logical definition changed since this ticket was opened:

'anatomical structure development'
 and ('results in development of' some 'roof of mouth')

The textual definition is:
The biological process whose specific outcome is the progression of the palate from an initial condition to its mature state. This process begins with the formation of the structure and ends with the mature structure. The palate is the partition that separates the nasal and oral cavities.

It looks to me like these are consistent. 

So the new proposal would be to change this term to 'roof of mouth development', modify the definition and create two new terms, one for the 'primitive palate' and one for the 'secondary palate'. This will require reannotation of the exisiting annotations already checked in https://github.com/geneontology/go-annotation/issues/1746.

I'm not sure what you would use in the MP term other than roof of mouth. It needs to chain to an anatomical structure in some way.

**Comment by sbello** [comment]
The MP uses the GO term in the logical definitions. I'll add the definition for abnormal secondary palate development once this term is in.
