### ISSUE TITLE
GO:0007126 meiosis merged with meiotic nuclear division? 

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11709]
Hello, 

It looks like the term GO:0007126 meiosis was renamed meiotic nuclear division ? Isn't that too narrow ? ie terms formerly annotated to meiosis might now better belong in 'GO:0051321  meiotic cell cycle ' ? 

Thanks, 

Pascale

Reported by: pgaudet

Original Ticket: [geneontology/ontology-requests/11539](https://sourceforge.net/p/geneontology/ontology-requests/11539)

**Comment by ukemi** [comment]
Edited terms as Val suggested. Made 'regulation of transcription involved in meiotic cell cycle' instead of during based on the part of relation. Val, if this isn't correct, let me know.

**Comment by ValWood** [comment]
I'm not sure which term you mean?

The terms I was questioning were the ones under "meiotic nuclear division"
This one, and the descendants.
 GO:0100023 regulation of meiotic nuclear division by transcription from RNA polymerase II promoter
I don't think these should be added as there is no evidence that "meiotic nuclear division" is regulated transcriptionally (like mitosis 'meiotic nuclear division' it is regulated post translationally).
These terms have no annotations.

when these terms were added I think they were meant to represent
GO:0100023 regulation of meiotic cell cycle by transcription from RNA polymerase II promoter
but we have terms for this already

**Comment by ukemi** [comment]
Heads-up was given on the annotation call on April 26 that people should reexamine their annotations.

**Comment by ukemi** [comment]
Hi Val and Pascale.

I'm looking back at ancient history items and have done some detective work on this one. It seems that the work on this part of the ontology was never completed because meiosis I and meiosis II, although defined by their nuclear division, have not been disambiguated and renamed. meiosis I nuclear division and meiosis II nuclear division. Female meiosis looks like it was renamed female meiotic division. It probably should have been female meiotic nuclear division and it looks like nothing was done with male meiosis. The terms that were not renamed were never really disambiguated because some of them still have cytokinesis as parts. Val, I think we need to sit down and go over this together at some point. We need to have a strategy to name the terms correctly and then move the incorrect children to the appropriate 'meiotic cell cycle' (a misnomer in and of itself) parent. When the dust settles, we need to figure out a strategy for people to correct their annotations. 

I am mentinoing @vanaukenk here because this is one of the great examples of how we need to coordinate ontology development with annotation.

**Comment by ValWood** [comment]
Hi,

I  had a look, and I think there is a fairly simple strategy to fix these:

1. Rename
“meiosis I” to
“meiosis I nuclear division”
to clarify

2.  meiotic G2/MI transition
Definition	The cell cycle process in which a cell progresses from meiotic prophase to metaphase I. 

This appears to be incorrectly defined?
G2/M is not equivalent to prophase/metaphase i
If it does refer to G2/M it should not have the “meiosis I parent  but only the meiotic cell cycle which was added  24-4-2015
(Moving this would not be a problem as the new parent is broader, but the  because of incorrect def may require absolution)

3. Male meiosis I and female meiosis 1 should be OK to move to the correct parent
GO:1903046 meiotic cell cycle process
(this is broader, so all annotations here will be OK)
and rename to 
male meiotic cell cycle
and
female meiotic cell cycle

4. “regulation of meiosis I”
Is defined as “regulation of meiotic cell cycle process”
It has only 42 EXP annotations, and most of these are to regulation kids which would live correctly under 
“regulation of meiosis I (nuclear division)” if it was defined to match  its parent
So, really the only the small number of  annotations directly to the existing regulation terms need to be addressed.

5. meiosis I cytokinesis 
Should be under “meiotic cell cycle” not the existing “meiosis I”
This move will be OK for annotation, as the  new parent is broader

I can run through these with you if you like. Some might even be in open tickets...

**Comment by ValWood** [comment]
Male and female meiosis are mentioned int his ticket, but they are a bit buried....
https://github.com/geneontology/go-ontology/issues/11709

**Comment by pgaudet** [comment]
Hi David, 

My point back in Feb 2015 (as far as I can recall) was that the name change for GO:0007126 meiosis to meiotic nuclear division was significant enough that it invalidated some of our annotations. 

Pascale

**Comment by ValWood** [comment]
Hi Pascale,

The name change was only a clarification... the definition
has always historically referred to
"A cell cycle process comprising the steps by which a cell progresses through the nuclear division phase of a meiotic cell cycle"
so annotations should not be affected. The name change was purely a clarification.

If the annotations are incorrect, they presumably were made incorrectly in the first instance. An e-mail was sent to the mailing list about the need to check annotation in case the terms had been used incorrectly.....

I can't find the announcement on the GO list but I know there was one...maybe it was on the annotation tracker....

**Comment by ValWood** [comment]
but it is also documented here (and tickets linked therein)
https://github.com/geneontology/go-ontology/issues/11709

**Comment by ukemi** [comment]
Hi Pascale,

We suspected that this was going to be the case, especially for curators who annotated to the term. I suspect we will be doing further work in this part of the graph. I will warn gene annotators again as this happens. 

-David

**Comment by pgaudet** [comment]
When I look at the change log on quick GO I see

2014-03-07
<http://www.ebi.ac.uk/QuickGO/GHistory?from=2014-03-07&to=2014-03-07>
Updated TERM meiotic nuclear division

2014-03-07
<http://www.ebi.ac.uk/QuickGO/GHistory?from=2014-03-07&to=2014-03-07> Added
DEFINITION One of the two nuclear divisions that occur as part of the
meiotic cell cycle.

The previous definition was:

2011-11-05
<http://www.ebi.ac.uk/QuickGO/GHistory?from=2011-11-05&to=2011-11-05> Added
DEFINITION A cell cycle process comprising the steps by which a cell
progresses through the nuclear division phase of a meiotic cell cycle. A
meiotic cell cycle is the specialized nuclear and cell division in which a
single diploid cell undergoes two nuclear divisions following a single
round of DNA replication in order to produce four daughter cells that
contain half the number of chromosomes as the diploid cell. Meiotic
division occurs during the formation of gametes from diploid organisms and
at the beginning of haplophase in those organisms that alternate between
diploid and haploid generations.


Seems like the former was much wider ??


Pascale

**Comment by ValWood** [comment]
Hmm, that depends how you interpret the old def. It was ambiguous.
But the definition  seemed to be:

A cell cycle process comprising the steps by which a cell
progresses through the nuclear division phase of a meiotic cell cycle.

So, the  old definition seems to be referring specifically to the nuclear division phase of meiosis, which is how it is defined now:
(One of the two nuclear divisions that occur as part of the meiotic cell cycle). 

The rest of the old definition is saying what a "meiotic cell cycle"  is, of which the nuclear division phase is only part. I'm not really sure why it was ever there because it isn't a differentia for the first part of the definition.....

In retrospect it probably should have been obsoleted because it was so confusing. We thought we got around that by alerting everyone to the problem (and I remember we went through this on a curation call too).  I know we (PomBase) did a lot of fixes at the time.

I don't know what the best way out of this is..... Maybe the only way is an obsoletion which will force people to check and re-annotate?

**Comment by ukemi** [comment]
Yes. The definition only refers to the nuclear division. The rest of the definition describes what happens during a meiotic cell cycle. It is a case of too much definition gloss, but many times the gloss is helpful.

**Comment by ukemi** [comment]
I don't think obsoletion is a good route because many of the annotations are good and I suspect that some groups did already check their annotations.

**Comment by pgaudet** [comment]
It seems to me a less dramatic solution would be to move the annotation that occur prior to the change to the parent, "GO:1903046 meiotic cell cycle process". 

I am not too familiar with meiosis, but I seem to recall it's not just nuclear divisions- I might be wrong (in that case we should merge meiotic cell cycle process and meiotic nuclear division?) 

-Pascale

**Comment by ValWood** [comment]
Hi Pascale,

This is precisely what this disambiguation was about.

Biologists use the term "meiosis" interchangeably to refer specifically to 
i) "meiotic nuclear division" (analogous to 'mitosis during the mitotic cell cycle"), or the 
ii)  to the entirety of meiotic growth (which we refer to as meiotic cell cycle), this includes meiotic DNA replication (which precedes the "meiotic nuclear division"), and the gap phases in between the 2 nuclear divisions), in fungi sporulation and I guess gamete formation in higher eukaryotes.

The shouldn't be merged. Both terms  have existed for ever. All we were trying to do was make it clearer precisely what these two distinct terms referred to....

I don't think any parentage changes affect this issue, but I can have a look. Which parentage change you are referring to?

Val

**Comment by pgaudet** [comment]
We should talk - can you skype ?

**Comment by ValWood** [comment]
I can Skype.

I had a look at the annotations.
There are only 120 experimental annotations directly to the term
 GO:0007126 meiosis renamed meiotic nuclear division.

This is the situation:
- The term has not changed meaning so it did not originally warrant obsoletion, however, it was misleading.
- If we want to go  ahead and obsolete this term, it won't be such a hardship for people to reannotate. I would be happy for this (PomBase don't have any annotations directly to this term...see more on this below)
- Quite a lot of the existing annotations should really move up to "meiotic cell cycle" they are not related to  meiosis/nuclear division (you can see this at a glance)
- We could go one step further and make the new/replacement (or even the existing) 
meiotic nuclear division term "not for direct annotation" . If you know for sure that a gene process is involved in meiotic nuclear division you should *always* be able to be more specific and annotate to one of the sub-processes.
(we have found this to always be the case)

So there seem to be lots of solutions, none of which are too painful....

**Comment by pgaudet** [comment]
Hi Val, 

I was suggesting doing your third option, "move existing annotations  up to "meiotic cell cycle", and if people want, use a more precise term. 

I don't think we should have any of these terms "not for direct annotation"  - I agree these terms are not very informative, but I personally prefer having a high-level annotation to an overinterpretation, which is what may happen if we over-use "not for direct annotation". 

So if we agree to  "move existing annotations  up to "meiotic cell cycle", then we can just do it and close the issue (not sure how this 'just happens' though). 

Thanks, 
Pascale

**Comment by ValWood** [comment]
I think this would involve

- [ ] merge GO:0007126 GO:0051321 meiotic cell cycle


- [ ] Create a new term
GO:NTR with same def as existing GO:0007126

Name	meiotic nuclear division
Ontology	Biological Process
Definition	One of the two nuclear divisions that occur as part of the meiotic cell cycle. 
PMID:9334324
GONUTS	GO:0007126 Wiki Page

- [ ]  recommend the all resources check existing annotations to GO:0007126
and move to the replacement term if necessary
(this will be a bit annoying for those who have already done this process, but looking at the annotations I wonder if anyone  else did...)

Sounds a good solution

**Comment by ValWood** [comment]
Note that there are other to do items above which should be done at the same time to clean this up

**Comment by pgaudet** [comment]
Works for me!  

Thanks, Pascale

**Comment by ukemi** [comment]
I will announce this on an annotation call. This works for me.

**Comment by ukemi** [comment]
#10312

**Comment by pgaudet** [comment]
Here, right? 

http://wiki.geneontology.org/index.php/Protein_and_peptidyl_amino_acid_modification_/_protein_processing
