### ISSUE TITLE
STAT signaling GO terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11773]
Hello: 

I am submitting a ticket to request new GO terms, or possibly modification of existing terms (see below). 

Term 1

Suggested name: STAT signaling pathway
Suggested definition: Any process in which a STAT protein (Signal Transducers and Activators of Transcription) conveys a signal to trigger a change in the activity or state of a cell. The STAT signaling cascade begins with activation of a STAT protein by tyrosine kinase like proteins, proceeds through dimerization and subsequent nuclear translocation of a STAT protein, and ends with regulation of target gene expression by a STAT protein. 
Suggested position in GO hierarchy: as a child of GO:0035556 intracellular signal transduction
Literature reference: PMID:24587195, Identification of the Protein Kinases Pyk3 and Phg2 as Regulators of the STATc-Mediated Response to Hyperosmolarity.
PMID:21534947, STAT signaling in Dictyostelium development.

Term 2

Suggested name: regulation of STAT signaling pathway
Suggested definition: Any process that modulates the frequency, rate or extent of the STAT signaling pathway. 
Suggested position in GO hierarchy: as a child of GO:1902531 regulation of intracellular signal transduction
Literature reference: PMID:24587195, Identification of the Protein Kinases Pyk3 and Phg2 as Regulators of the STATc-Mediated Response to Hyperosmolarity.

Term 3

Suggested name: postive regulation of STAT signaling pathway
Suggested definition: Any process that activates or increases the frequency, rate or extent of the STAT signaling pathway activity.
Suggested synonyms:     up regulation of STAT signaling pathway
    up-regulation of STAT signaling pathway
    upregulation of STAT signaling pathway
    activation of STAT signaling pathway
    stimulation of STAT signaling pathway
Suggested position in GO hierarchy: as a child of GO:1902531 regulation of intracellular signal transduction
Literature reference: PMID:24587195, Identification of the Protein Kinases Pyk3 and Phg2 as Regulators of the STATc-Mediated Response to Hyperosmolarity.

Term 4

Suggested name: negative regulation of STAT signaling pathway
Suggested definition: Any process that stops, prevents, or reduces the frequency, rate or extent of the STAT signaling pathway activity.
Suggested synonyms:     down regulation of STAT signaling pathway
    down-regulation of STAT signaling pathway
    downregulation of STAT signaling pathway
    inhibition of STAT signaling pathway
Suggested position in GO hierarchy: as a child of GO:1902531 regulation of intracellular signal transduction
Literature reference: PMID:24587195, Identification of the Protein Kinases Pyk3 and Phg2 as Regulators of the STATc-Mediated Response to Hyperosmolarity.

However, it is probably obvious that the requested terms are basically more general versions of the current GO terms relating to the JAK-STAT cascade (GO:0007259 JAK-STAT cascade). Dictyostelium discoideum lacks a JAK ortholog, so unfortunately all of the current terms are not suitable for use in dicty in their current form. It may be that the better solution is to modify the current GO terms for GO:0007259 JAK-STAT cascade and its children by removing references to JAK from the names and definitions of these terms. 

I am not sure whether it is preferable to add new terms or modify the existing ones, but please let me know if I can provide further information. 

Thanks,
Bob Dodson
dictyBase curator

Reported by: rjdodson

Original Ticket: [geneontology/ontology-requests/11606](https://sourceforge.net/p/geneontology/ontology-requests/11606)

**Comment by paolaroncaglia** [comment]
Note for self: emailed Bob Dodson today to follow up.

**Comment by rjdodson** [comment]
Hi Paola: I see these terms are still not in GO. According to my notes I replied to your email above on Aug. 7, but maybe this slipped through the cracks somehow. I can resend if you want. 
Thanks,
Bob

**Comment by rjdodson** [comment]
Hi Paola:
On second thought I should probably just include my comments here, so now adding to this ticket. This is from my Aug. 7 email with my comments included within your original text and bordered by ******

Let me know if anything is unclear or if you need more information from me. 

Thanks,
Bob
-----------------------------------
Hi Bob,

Following up on this, I asked Becky Foulger, who worked on signaling GO terms in the recent past. She’d favor my option 2) above. 

*******
Thanks for your reply. No objections from me with using option 2. Please see my responses below interspersed within your email and let me know if you have any questions. 
*******

a) The process referred to by GO:0007260 ‘tyrosine phosphorylation of STAT protein’ occurs as part of GO:NEW ‘STAT cascade’ (or however we’ll call it) (as well as as part of the existing GO:0007259 ‘JAK-STAT cascade’)

***********
Yes, this does occur as part of the “NEW STAT cascade”. I asked for this GO term while curating PMID:24587195. In this reference both single and double mutants are created for two tyrosine kinase like (TKL) enzymes: pyk3 and phg2. The authors show a reduction  in tyrosine phosphorylation of dicty STATc protein in each of the single mutants, and a further reduction in the double mutant.
***********

b) Similarly, the process GO:0007262 ‘STAT protein import into nucleus’ occurs as part of GO:NEW ‘STAT cascade’ (or however we’ll call it) (as well as as part of the existing GO:0007259 ‘JAK-STAT cascade’)

Meaning that ‘tyrosine phosphorylation of STAT protein’ and ‘STAT protein import into nucleus’ do not only occur in the context of JAK-STAT cascades, but also as part of the overall process in Dicty which does not involve JAK proteins. And that both ‘JAK-STAT cascade’ and ‘STAT cascade’ need those sub-processes to happen in order for the signaling to be complete.

*********
Yes again, and in the same reference, the authors show STATc translocation to the nucleus is delayed in each of the single mutants, and even further delayed in the double mutant.
As noted before, dicty does not have JAK proteins, but the above mentioned TKLs appear to perform an analogous role in dicty. This signaling pathway is still being elucidated, but again from the reference mentioned above, the authors show that the normal up regulation of STATc responsive genes is either reduced or eliminated in the single and double phg2 and pyk3 mutants. 

So, summing up null mutants lacking these TKLs show reduced STATc phosphorylation, delayed STATc translocation to nucleus and reduction in gene expression of genes normally activated by STATc. I think that is probably sufficient to say that the two sub-processes are needed for the signaling to be complete, but let me know if you think otherwise.  
*******

 If this is all correct, I’ll need to represent it with appropriate links in the ontology 
(note for self: might need to check with Becky about removing part_of links in favor of has_parts - without losing annotation links)

Another note for self: when creating the new term, add a definition comment to the extent that an example of this is found in Dictyostelium discoideum, and that this species lacks a JAK ortholog.

*******
Yes, I think it would be good to add this to the definition. 
********

**Comment by paolaroncaglia** [comment]
Hi Bob,

Thanks for the reminder. Yes this ticket wasn't forgotten, but I hadn't had a chance to work on it since our last exchange, sorry for the delay. I am on leave for a couple of days now, but will take care of the necessary edits asap; I'll make a note.

Thanks again for your patience, and best regards,

Paola

**Comment by rjdodson** [comment]
Hi Paola:

Thanks, no hurries. It just came to my attention today so was following up on it.

Bob

**Comment by paolaroncaglia** [comment]
Hi Bob,

I looked into this again very carefully. 
The ontology changes we resolved on in our previous email exchange would require changes to all of the terms sitting under the existing ‘JAK-STAT cascade’ (because of the considerations on ‘STAT protein import into nucleus’ and ‘tyrosine phosphorylation of STAT protein’). I am wondering if there’s any way to make ‘JAK-STAT cascade’ inclusive of non-JAK, tyrosine kinase-like proteins without losing too much specificity… I would like to discuss this with one of my fellow editors who did some work on signalling terms. Would it be acceptable to you if I came back to this early next week, so I have a chance to speak to her? Of course, if you have any suggestions, they’d be welcome!

Many thanks,
Paola

**Comment by rjdodson** [comment]
Hi Paola: 
Thanks for your comments, and fine to take additional time to consult with others before coming to a final decision. As noted in the text of my original request, I wondered if just broadening the definitions of the existing terms might be an acceptable solution. But maybe that's laborious and/or not the best way to handle this. So, I don't have any concrete suggestions, but I am OK with whatever solution you all think is best. 

Thanks,
Bob

**Comment by paolaroncaglia** [comment]
Thanks Bob! I'll keep you posted.
Paola

**Comment by paolaroncaglia** [comment]
Hi Bob,

I consulted with Rebecca Foulger, who did some ontology development work in the signalling branch in the past.
It feels like our best option is to create a parent term GO:NEW ‘STAT cascade’ (or ‘STAT signalling pathway), without JAK specificity, so that Dicty proteins could be annotated to it, and to place the existing GO:0007259 ‘JAK-STAT cascade’ as its child. Our suggestions for the new term are:

GO:NEW STAT cascade
is_a intracellular signal transduction
Definition: An intracellular signal transduction process in which STAT proteins (Signal Transducers and Activators of Transcription) convey a signal to trigger a change in the activity or state of a cell. The STAT cascade begins with activation of STAT proteins by kinases, proceeds through dimerization and subsequent nuclear translocation of STAT proteins, and ends with regulation of target gene expression by STAT proteins. 
Definition comment: In most species, STAT proteins are activated by members of the JAK (Janus Activated Kinase) family of tyrosine kinases; the term GO:0007259 ‘JAK-STAT cascade’ describes this specificity. In other cases, such as D. discoideum, no JAK orthologs are known, and STAT proteins are activated by tyrosine kinase-like proteins.
Dbxrefs: GOC:rjd, PMID:24587195, PMID:21534947
exact synonyms: STAT signalling pathway, kinase-STAT cascade, kinase activated-STAT cascade

You could then move any Dicty annotation currently sitting under ‘JAK-STAT cascade’ under this new, more generic parent.
I think this will work well for your needs, but do let me know if you have any concern.

Note for self: if this plan is implemented, I’d need to create part_of children of the general parent referring to the phosphorylation and import steps; while the corresponding, existing terms currently under ‘JAK-STAT cascade’, and their descendants, would have to be renamed (and given logical definitions).

Thanks,
Paola

**Comment by rjdodson** [comment]
Hi Paola:
Thanks for your comment and for following up on this. Your suggestion sounds fine with me. I assume my requested regulation terms will be children of your new term as well, so I think it is all good. We currently don't have any dicty annotations to JAK-STAT cascade, so we won't even need to move old ones over to the new terms. 

Thanks again!
Bob

**Comment by paolaroncaglia** [comment]
Hi Bob,

Yes, I would also create regulation children for the new term. I will comment here as soon as all terms are ready to use. Best,

Paola

**Comment by paolaroncaglia** [comment]
Hi Bob,

I created GO:0097696 STAT cascade as above,
and moved GO:0007259 ‘JAK-STAT cascade’ to be its child.
At the moment I can't add regulation children because there is a problem in the GO build process. Hopefully it will be resolved between today and tomorrow, but we can't guarantee due to some of us going on holiday soon, myself included. If you have a TermGenie account, you can add the regulation terms yourself; or let me know if you'd prefer me to do it once the build problem is fixed (I'm back on Jan 7th).

Note for self: 
other than adding regulation children for GO:0097696 STAT cascade, I'll also need to do the edits outlined in my comment dated Dec 14th.

**Comment by rjdodson** [comment]
Hi Paola:

Thanks for creating the new term I requested. I just logged into TermGenie to try and add this, but for some reason it's not working for me at the moment. (I can't open the drop-down at Step 2: Templates). Maybe the problem you mention with the GO build process is hampering TermGenie too. 

In any case, as noted before not urgent, and I'm starting to get distracted by the Holidays too. I'll try again with TermGenie after the Holidays, and if it's still not working, them maybe you can add these regulation terms. 

Thanks and have a nice Holidays!

**Comment by paolaroncaglia** [comment]
Hi Bob,

That's correct unfortunately, TermGenie is not working for anyone at the moment due to those ontology issues I mentioned. Some of us editors have been working on fixes over the last few days, but some more consistent work needs to be done and we'll need to punt that to the New Year I'm afraid. So, yes, please try again after the holidays. I'm monitoring this ticket anyway, so any problem you can let me know.

Thanks and nice holidays to you too!

Paola

**Comment by paolaroncaglia** [comment]
Hi Bob,

Happy New Year!
I created the missing regulation terms for you:

GO:1904892 Label: regulation of STAT cascade
GO:1904893 Label: negative regulation of STAT cascade
GO:1904894 Label: positive regulation of STAT cascade

So you should now have all the terms you need. Any issue, please let me know.

Note for self: 
Next, I'll need to do the edits outlined in my comment dated Dec 14th.

Paola

**Comment by rjdodson** [comment]
Hi Paola:
Thanks! I have just annotated two dicty genes to one of these terms, so all is good. 
Happy New Year,
Bob

**Comment by paolaroncaglia** [comment]
Note for self: re-opening this ticket as I still have to do the edits outlined in my comment dated Dec 14th.

**Comment by paolaroncaglia** [comment]
Wrapping up. Outlined remaining tasks in new ticket:
https://github.com/geneontology/go-ontology/issues/13038
Closing this one.
