### ISSUE TITLE
NTR - child to mitophagy and also grandchild

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11850]
child term NTR - child to GO:0098779 activation of mitophagy in response to mitochondrial depolarization

New term:
Activation of parkin-mediated mitophagy in response to mitochondrial depolarization

I'm requesting this because there appear to be parkin-independent types of mitophagy (e.g. see 
PMID: 24176932 Loss of iron triggers PINK1/Parkin-independent mitophagy
PMID: 25349190 Parkin-independent mitophagy requires Drp1 and maintains the integrity of mammalian heart and brain.
PMID: 24398127

so I would like something more specific.

The other term I wanted to request is:

involved in engulfment of mitochondria by autophagosome 

or something similar - perhaps just 
engulfment of mitochondria by autophagosome (?)

It's to use to describe part of the process of mitophagy (so child to mitophagy GO:0000422 mitochondrion degradation) as described in PMID:22020285 where human SMURF1 (Q9HCE7) is characterised as "...the C2 domain of SMURF1 is not required for its targeting to damaged mitochondria, but is **required for damaged mitochondria to be normally engulfed by autophagosomes**."
Because mitophagy is a common, complex, multi-stage process, I anticipate that this term would be used for other proteins in future. 

Thanks

Reported by: pauldenny

Original Ticket: [geneontology/ontology-requests/11687](https://sourceforge.net/p/geneontology/ontology-requests/11687)

**Comment by paolaroncaglia** [comment]
@pauldenny
@RLovering

**Comment by ukemi** [comment]
Changed name of GO:0098779 activation of mitophagy in response to mitochondrial depolarization' to 'mitophagy in response to mitochondrial depolarization' and made it an is_a child of macromitophagy and a part_of child of response to mitochondrial depolarization.
Changed definition of 'mitophagy in response to mitochondrial depolarization' to: The macromitophagy process that is triggered by a detection of the loss of mitochondrial membrane potential.

Moved mitophagy to be a direct child of autophagy since there are two types, micromitophagy and macromitophagy.

Added the following terms:

 [Term]
+id: GO:0061734
+name: parkin-mediated mitophagy in response to mitochondrial depolarization
+namespace: biological_process
+def: "The macromitophagy pathway that is triggered by mitochondrial depolarization and requires the function of a parkin-family molecule." [GOC:autophagy, GOC:dph, GOC:PARL, PMID:25349190]
+is_a: GO:0098779 ! mitophagy in response to mitochondrial depolarization
+created_by: dph
+creation_date: 2015-09-14T13:48:57Z
+
+[Term]
+id: GO:0061735
+name: dynamin-like protein-mediated mitophagy in response to mitochondrial depolarization
+namespace: biological_process
+def: "The macromitophagy pathway that is triggered by mitochondrial depolarization and requires the function of a dynamin-like molecule." [GOC:autophagy, GOC:dph, GOC:PARL, PMID:25349190]
+is_a: GO:0098779 ! mitophagy in response to mitochondrial depolarization
+created_by: dph
+creation_date: 2015-09-14T14:00:43Z
+
+[Term]
+id: GO:0061736
+name: engulfment of target by autophagosome
+namespace: biological_process
+def: "The membrane invagination process by which an autophagosomal membrane surrounds an object that will be degraded by macroautophagy." [GOC:autophagy, GOC:dph, GOC:PARL]
+is_a: GO:1902534 ! single-organism membrane invagination
+intersection_of: GO:1902534 ! single-organism membrane invagination
+intersection_of: part_of GO:0016236 ! macroautophagy
+relationship: part_of GO:0016236 ! macroautophagy
+created_by: dph
+creation_date: 2015-09-14T14:10:24Z
