### ISSUE TITLE
query about "protein autophosphorylation" term

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11882]
Isn't this term a bit strange as a separate process? The only thing which differentiates it from "protein phosphorylation" is that the substrate is itself. This doesn't make it a different process though.

Ditto any similar terms.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11720](https://sourceforge.net/p/geneontology/ontology-requests/11720)

**Comment by dosumis** [comment]
Keeping auto-phosphorylation. No harm in annotators recording this in an extension anyway.  Also worth noting that the extension can't distinguish cis from trans autophosphorylation.  We have both terms in the ontology.  I think that the ability to cis-autophosphrylate IS a property of a protein and so definitely belongs in the ontology.  The term currently has no annotations, but that appears to be due to neglect rather then biology:

e.g. see

http://stke.sciencemag.org/content/2/54/pe4
http://www.ncbi.nlm.nih.gov/pubmed/9054577
http://www.ncbi.nlm.nih.gov/pubmed/23000554
http://www.ncbi.nlm.nih.gov/pubmed/9201908
