### ISSUE TITLE
relax def for GO:1990746 HCN4 channel complex

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11897]
Hi,

Anna created the above term but there is actually a family of HCN channel complexes. In order to avoid the explosion of the ontology and in agreement with our recent meeting, I think we should relax the name & def and allow all HCN Cx to be annotated to this term, making the isoforms narrow synonyms.

ID  GO:1990746
-Name   HCN4 channel complex
+Name   HCN channel complex
Ontology    Cellular Component
-Definition     HCN4 tetramer is a hyperpolarization-activated ion channel with selectivity for potassium over sodium ions. HCN4 is the dominant form of HCN expressed in the heart, together with HCN2. HCN4 expression is particularly high in the sinoatrial node, where impulses initiate and propagate throughout the heart. There is pharmacologic and genetic evidence that the HNC4 channel complex plays a role in cardiac pacemaking and automaticity, by contributing to the native pacemaker current of the heart (If). Mutations in the C-terminus containing the C-linker and CNBD domain, which affect the expression or function of the HCN4 channel are known to cause arrhythmias or bradycardia.
+Definition     A hyperpolarization-activated ion channel with apparent selectivity for potassium over sodium ion voltage-gated channel activity. Expressed in the heart and brain where it controls pacemaker activity. Activated dually by membrane hyperpolarization and binding of cAMP to their cyclic nucleotide binding domain (CNBD).
PMID:20829353

Thanks,
Birgit

Reported by: bmeldal

Original Ticket: [geneontology/ontology-requests/11735](https://sourceforge.net/p/geneontology/ontology-requests/11735)

**Comment by bmeldal** [comment]
Ok, further additions:

HCN3 is not activated by cAMP and HCN1 only weakly activated by cAMP (it is constitually activated by basal concentrations of cAMP) so I think we need to relax the def even further:

+Definition A hyperpolarization-activated ion channel with apparent selectivity for potassium over sodium ion. All members are activated by membrane hyperpolarization and some members (HCN1, HCN2 & HCN4 isoforms) by binding of cAMP to their cyclic nucleotide binding domain (CNBD). Capable of voltage-gated potassium and sodium channel activity. Expressed in the heart and brain where it controls pacemaker activity. Homotetrameric but can have additional, regulatory subunits.

We also need a further relationship:
is_a GO:0001518 voltage-gated sodium channel complex

And NARROW synonyms for the HCN3 isoforms:
HCN3 channel complex
K/Na hyperpolarization-activated channel 3 complex
Potassium/sodium hyperpolarization-activated channel 3 complex

I also have suggestions to tidy up the related activity terms. Shall I make a new ticket for them? It would eventually require changing the capable_of relationships (which need fixing here anyway as they only point to  GO:0005249 voltage-gated potassium channel activity at the moment, via it's parent term, not directly here).

**Comment by dosumis** [comment]
> is_a GO:0001518 voltage-gated sodium channel complex

Should do this via inference using capable_of

**Comment by bmeldal** [comment]
>    is_a GO:0001518 voltage-gated sodium channel complex

>Should do this via inference using capable_of

Ok. Do you want the capable_of relationships as the ontology stands right now or do you want to make the changes to the activity terms first, then change the relationships here on the complex? 
And should I add the activity change request here or make a separate ticket?

**Comment by dosumis** [comment]
This needs mention of the composition:  

+Definition A hyperpolarization-activated ion channel with apparent selectivity for potassium over sodium ion voltage-gated channel activity. Expressed in the heart and brain where it controls pacemaker activity. Activated dually by membrane hyperpolarization and binding of cAMP to their cyclic nucleotide binding domain (CNBD).

How about:

A cation ion channel with a preference for K+ ions, which is activated by membrane hyperploarization, and consists of a tetramer of HCN family members. Some members of this family are also activated when cAMP binds to their cyclic nucleotide binding domain (CNBD).  [Channel complexes of this family have an important role in the control of pacemaker activity in the heart.]
capable_of: voltage-gated potassium channel activity

[Ispum Lorem] = optional gloss

**Comment by bmeldal** [comment]
Suggestion:

A cation ion channel with a preference for K+ over Na+ ions, which is activated by membrane hyperploarization, and consists of a tetramer of HCN family members. Some members of this family (HCN1, HCN2 and HCN4) are also activated when cAMP binds to their cyclic nucleotide binding domain (CNBD). Channel complexes of this family play an important role in the control of pacemaker activity in the heart.

Also add: 
capable_of: voltage-gated sodium channel activity

**Comment by dosumis** [comment]
Added
HCN channel complext
"A cation ion channel that consists of a tetramer of HCN family members,
has a preference for K+ over Na+ ions and is activated by membrane
hyperpolarization.  Some members of this family (HCN1, HCN2 and HCN4) are
also activated when cAMP binds to their cyclic nucleotide binding domain
(CNBD). Channel complexes of this family play an important role in the
control of pacemaker activity in the heart."

Do you have a ref for the Na+ channel activity?

Also wondering if we could better reflect what cAMP activation means.
Here's a quote from PMID: 20829353  "cNMP binding shifts the
voltage-dependent channel activation curve toward more positive potentials,
increasing the macroscopic current amplitude and making the channel
activate faster and deactivate slower."

**Comment by bmeldal** [comment]
>Do you have a ref for the Na+ channel activity?

Funny you are asking that! It's like searching for a needle in a haystack and I'm doing that right now! All papers mention K+/Na+ channel activity with preference for K+ but the papers cited 'only' describe patch clamp expts without any indication that they assessed the type of ion beyond what's in the buffers. I have never worked on this in the lab so I might just be missing something. The 3 papers that are already annotated in GO are PMID:16407510, 10228147 & 22748890. I also have 16043489 which claims a 3:1 ratio for HCN3. 

>Also wondering if we could better reflect what cAMP activation means. [...]

Do you want a longer def or a gloss comment? As I mentioned, the whole detail about how ICs are working is only starting to become clear to me. I never worked on them myself but all theses channels were submitted by ChEMBL for curation. I wonder if they have anyone who knows more about it???

**Comment by bmeldal** [comment]
Hi David,

here my suggestions for the changes to the activity terms:

HCN channels are inward rectifying K+/Na+ channels, 3 of 4 are activated by cAMP (HCN1, HCN2 & HCN4, not HCN3)

Therefore, GO:1990746 HCN channel complex can have:

capable_of 
GO:0005242 inward rectifier potassium channel activity
GO:0005248 voltage-gated sodium channel activity (or new child, see below)
GO:0005217 intracellular ligand-gated ion channel activity (do we need a ‘cation’ child term?)

As HCN3 is NOT activated by cAMP, we cannot use more specific terms for the ontology links, however, I can use such terms for the complex annotations in the CP, so I’m proposing an extension to the current terms as follows:

1)
**GO:0005222 intracellular cAMP activated cation channel activity**
Def: “Enables the transmembrane transfer of a cation by a channel that opens when intracellular cAMP has been bound by the channel complex or one of its constituent parts.”

create new children:

**GO:NEW1 intracellular cAMP activated *potassium* channel activity**
is_a GO:0005222 intracellular cAMP activated cation channel activity
Def: “Enables the transmembrane transfer of a potassium ion by a channel that opens when intracellular cAMP has been bound by the channel complex or one of its constituent parts.”

and

**GO:NEW2 intracellular cAMP activated *sodium* ion channel activity**
is_a GO:0005222 intracellular cAMP activated cation channel activity
Def: “Enables the transmembrane transfer of a sodium ion by a channel that opens when intracellular cAMP has been bound by the channel complex or one of its constituent parts.”

2)
**GO:0005242 inward rectifier potassium channel activity**
Def: “Enables the transmembrane transfer of a potassium ion by an inwardly-rectifying voltage-gated channel. An inwardly rectifying current-voltage relation is one where at any given driving force the inward flow of K+ ions exceeds the outward flow for the opposite driving force. The inward-rectification is due to a voltage-dependent block of the channel pore by a specific ligand or ligands, and as a result the macroscopic conductance depends on the difference between membrane voltage and the K+ equilibrium potential rather than on membrane voltage itself.”

Note: I see where your comment from yesterday came from! This is indeed slightly confusing. As far as I know, inward rectifying channels are activated by membrane voltage (in the case of the HCN channels reaching a certain hyperpolarisation level) rather than relative ion concentrations. I feel we might need an expert to help with the definitive def!

create child:

**GO:NEW3 GO:0015272 cAMP activated inward rectifier *potassium* channel activity **
(as there is already the equivalent “GO:0015272 ATP-activated...” child)
is_a GO:0005242 inward rectifier potassium channel activity
is_a GO:NEW1 intracellular cAMP activated potassium channel activity
Def: “Def: “Enables the transmembrane transfer of a potassium ion by an inwardly-rectifying voltage-gated channel that opens when intracellular cAMP has been bound by the channel complex or one of its constituent parts. An inwardly rectifying current-voltage relation is one where at any given driving force the inward flow of K+ ions exceeds the outward flow for the opposite driving force.”

3)
**GO:0005248 voltage-gated sodium channel activity**
Def: “Enables the transmembrane transfer of a sodium ion by a voltage-gated channel. A voltage-gated channel is a channel whose open state is dependent on the voltage across the membrane in which it is embedded.”

create child:

**GO:NEW4 inward rectifier *sodium* channel activity**
is_a GO:0005248 voltage-gated sodium channel activity
is_a GO:0015276 ligand-gated ion channel activity
Def: “Enables the transmembrane transfer of a sodium ion by an inwardly-rectifying voltage-gated channel. An inwardly rectifying current-voltage relation is one where at any given driving force the inward flow of Na+ ions exceeds the outward flow for the opposite driving force. The inward-rectification is due to a voltage-dependent block of the channel pore by a specific ligand or ligands, and as a result the macroscopic conductance depends on the difference between membrane voltage and the Na+ equilibrium potential rather than on membrane voltage itself.”
(NB1: see notes on the K+ channel above (GO:0005242) regarding clarifying the def.)
(NB2: this would be the better capable_of term as well then)

create child:

**GO:NEW5 GO:0015272 *cAMP activated* inward rectifier sodium channel activity **
is_a GO:NEW4 inward rectifier sodium channel activity
is_a GO:NEW2 intracellular cAMP activated sodium channel activity
Def: “Def: “Enables the transmembrane transfer of a sodium ion by an inwardly-rectifying voltage-gated channel that opens when intracellular cAMP has been bound by the channel complex or one of its constituent parts. An inwardly rectifying current-voltage relation is one where at any given driving force the inward flow of Na+ ions exceeds the outward flow for the opposite driving force.”

4)
**GO:0005248 voltage-gated sodium channel activity** (see pt 3) also has the child:

GO:0086006 voltage-gated sodium channel activity involved in cardiac muscle cell action potential
with child
GO:0086063 voltage-gated sodium channel activity involved in SA node cell action potential

which is, in principle, also applicable to the HCN channels. However, the HCN channels are also found in other cells (neurons). Can we use these as capable_of relations in the ontology or just annotation in the CP? In any case, we could create the K+ equivalents, as HCN channels are preferentially K+ channels (ratios reported btw 3:1 and 4:1 against Na+).

New terms would be:

**GO:NEW6 voltage-gated potassium channel activity *involved in cardiac muscle cell action potential* **
is_a GO:0005249 voltage-gated potassium channel activity
Def: “Enables the transmembrane transfer of a potassium ion by a voltage-gated channel through the plasma membrane of a cardiac muscle cell contributing to the depolarization phase of an action potential. A voltage-gated channel is a channel whose open state is dependent on the voltage across the membrane in which it is embedded.”

and

**GO:NEW7 voltage-gated potassium channel activity *involved in SA node cell action potential* **
is_a GO:NEW6 voltage-gated potassium channel activity involved in cardiac muscle cell action potential
Def: “Enables the transmembrane transfer of a potassium ion by a voltage-gated channel through the plasma membrane of an SA node cardiac muscle cell contributing to the depolarization phase of an action potential. A voltage-gated channel is a channel whose open state is dependent on the voltage across the membrane in which it is embedded.”

I think the existing cardiac terms were created for/by Ruth’s group.

**Comment by dosumis** [comment]
- [ ]  Still need to merge specific HCN complex terms into general one.

I've been working on overhauling gated ion channels as part of MF refactoring.  Will work on this further later in Jan + Feb.  May spin this aspect off into new ticket(s). Couple of thoughts
-  The inward rectifier definition in GO is wrong so need to look carefully at this bit of request
-  It is important to have accurate MF terms o use to annotated specific HCNs rather than relying on vague MFs for the general HCN term in GO  e.g. - we should have an MF to reflect cases where cAMP binding changes the profile of voltage gating: "cNMP binding shifts the voltage-dependent channel activation curve toward more positive potentials"

**Comment by bmeldal** [comment]
@dosumis do you need anything from me right now?

**Comment by pgaudet** [comment]
Hi @bmeldal 

- I merged the terms HCN2 and HCN4 into the parent. 
- I added the following synonyms: 
+synonym: "HCN1 channel complex" NARROW []
+synonym: "HCN2 channel complex" NARROW []
+synonym: "HCN3 channel complex" NARROW []
+synonym: "HCN4 channel complex" NARROW []
+synonym: "K/Na hyperpolarization-activated channel 3 complex" NARROW []
+synonym: "K/Na hyperpolarization-activated cyclic nucleotide-gated channel 1 complex" NARROW []
+synonym: "K/Na hyperpolarization-activated cyclic nucleotide-gated channel 2 complex" NARROW []
+synonym: "K/Na hyperpolarization-activated cyclic nucleotide-gated channel 4 complex" NARROW []
+synonym: "K/Na hyperpolarization-activated cyclic nucleotide-gated channel complex" EXACT []
+synonym: "potassium/sodium hyperpolarization-activated channel 3 complex" NARROW []
+synonym: "potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel 1 complex" NARROW []
+synonym: "potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel 2 complex" NARROW []
+synonym: "potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel 2 tetramer" RELATED []
+synonym: "potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel 4 complex" NARROW []
+synonym: "potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel 4 tetramer" RELATED []
+synonym: "potassium/sodium hyperpolarization-activated cyclic nucleotide-gated channel complex" EXACT []

- I fixed the definition to this: 
+def: "A cation ion channel with a preference for K+ over Na+ ions, which is activated by membrane hyperploarization, and consists of a tetramer of HCN family members. Some members of this family (HCN1, HCN2 and HCN4) are also activated when cAMP binds to their cyclic nucleotide binding domain (CNBD). Channel complexes of this family play an important role in the control of pacemaker activity in the heart." [PMID:20829353]

Is this right ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
Thanks, @pgaudet that looks good except for the spelling of "hyperploarization" ;-)

@dosumis what do you want to do abut the activity terms?

**Comment by pgaudet** [comment]
@bmeldal can this one be closed ? 
I fixed the typo.

**Comment by bmeldal** [comment]
@pgaudet please close.

@dosumis please open a new ticket if you ant to make further changes during the MF refracturing.
