### ISSUE TITLE
relationship between salvage and biosynthesis

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11890]
If biosynthesis involved the enzyme catalysed processes where simple compounds were made into more complex products,  I am wondering if "salvage" should ever be considered part of biosynthesis?

For example here:
"L-methionine salvage" via various pathways
is part of "biosynthesis"
but for all of these isn't methionine 'regenerated' from a degradation product. This doesn't seem to fit 'biosynthesis'

Maybe it depends on the type of salvage? It seems odd especially as at least  some of the definitions say "without de novo synthesis"? I can't reconcile these 2 things.... I think I expected to see 'salvage' only under metabolism.

A question for Peter D' !

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11728](https://sourceforge.net/p/geneontology/ontology-requests/11728)

**Comment by tberardini** [comment]
Some comments on 'queuosine salvage' are in #11905.

**Comment by deustp01** [comment]
Wasn’t the big insight (for me, anyway) from David’s and my discussion with Jim Hu at the GOC meeting in November, that “catabolism” and “anabolism” terms are to be used only in connection with metabolic processes whose purpose is the storage and production of energy? I know the upshot was to narrow the range of reactions that get these labels; not sure I’ve remembered the exact narrowing right.

I’m asking because the "salvage" discussion is a variant on the same one: we’re supposed to classify a reaction or a process based on its larger teleological purpose. I guess “salvage” means making something useful from molecules that can be seen as intermediates rather than true starting molecules, thereby reducing the cost / increasing the efficiency of production. Is it reliably safe to make these judgments about higher purposes? And can we do so consistently? Or we simply showing respect for the history of biochemistry and labeling processes with these terms because SSS (evidence code SSS: Stryer says so)?

**Comment by ValWood** [comment]
Agree with comment above, but wasn't it slightly more than  "storage and production of energy",
would include biosynthesis of  vitamins amino acids or nucleotides for example which don't seem to always fit?

**Comment by pgaudet** [comment]
@ukemi @deustp01 

Any further thoughts on this ? 

Seems to me this is OK as it is; biosynthetic process is defined as 'The chemical reactions and pathways resulting in the formation of substances', it's not talking about de novo vs. salvage. 

Thanks, Pascale

**Comment by ValWood** [comment]
I guess salvage does fit the definition of biosynthesis if 'something is created'. However, it might make some strange logical inferences down the line where things are salvaged via catabolic pathways, but annotated as biosynthesis  (and also it means that "anabolism" (from simpler parts)  should really be a narrow synonym of biosynthesis, not exact.

But I'm happy for this one to close, might be better to deal with it if necessary  when strange inferences occur. and I can't remember what initiated the ticket.

There are only around 50 terms with "salvage' in the term name, most in the nucleotide salvage branch.

**Comment by pgaudet** [comment]
I think we are also moving away from calling 'biosynthesis' and 'catabolism' simple interconversions of molecules, which may be another way of solving the problem you mention.

**Comment by deustp01** [comment]
Re-read the thread, but nothing to add / revise / clarify. Sorry

**Comment by ValWood** [comment]
I would just close this one...
