### ISSUE TITLE
New term request

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11936]
New term request: Leukotriene signaling

Definition: A series of molecular signals initiated by the binding of leukotrienes to leukotriene receptors (mainly G protein-coupled receptors) on the surface of a target cell, and ending with regulation of a downstream cellular process, e.g. transcription

Hierarchy: is_a GO:0007165 signal transduction

Note: This GO term is useful to annotate Leukotriene B4 receptor 1 (LTB4R), Leukotriene B4 receptor 2 (LTB4R2), Cysteinyl leukotriene receptor 2 (CYSLTR2), Cysteinyl leukotriene receptor 1 (CYSLTR1).

Reported by: pduek

Original Ticket: [geneontology/ontology-requests/11775](https://sourceforge.net/p/geneontology/ontology-requests/11775)

**Comment by ukemi** [comment]
I'm trying to do a push on these tickets. Since we already have the receptor categorized as a GPCR, I have made the signaling pathway term and made it a child of GPCR signaling. I have linked the receptor activity to it. If we find we need a non-GPCR pathway in the future, we can rename these terms and created siblings.
