### ISSUE TITLE
Changes to GO:0048102 autophagic cell death

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11964]
Currently: 

[Term]
id: GO:0048102
name: autophagic cell death
namespace: biological_process
def: "A form of programmed cell death that is accompanied by macroautophagy, which is characterized by the sequestration of cytoplasmic material within autophagosomes for bulk degradation by lysosomes. Autophagic cell death is characterized by lack of chromatin condensation, massive vacuolization of the cytoplasm, and accumulation of (double-membraned) autophagosomes, with little or no uptake by phagocytic cells." [GOC:autophagy, GOC:mah, PMID:18846107]
synonym: "autophagic death" BROAD []
synonym: "programmed cell death by autophagy" BROAD [GOC:pr]
synonym: "programmed cell death by macroautophagy" EXACT [GOC:cjm]
synonym: "type II programmed cell death" RELATED [GOC:sl]
is_a: GO:0012501 ! programmed cell death
intersection_of: GO:0012501 ! programmed cell death
intersection_of: has_part GO:0000045 ! autophagosome assembly
relationship: has_part GO:0000045 ! autophagosome assembly
relationship: only_in_taxon NCBITaxon:2759 {id="GOTAX:0000386"} ! Eukaryota

As agreed at yesterday’s autophagy call (https://docs.google.com/document/d/10vkLY-dV-oiBGVYr8hSF7q4dlowtzKUzeFC0zZbVATE/edit#), please do the following edits:

- change def to following or similar: “A form of programmed cell death that is accompanied by the formation of autophagosomes [may or may not specify nature of autophagosomes here]. Autophagic cell death is characterized by lack of chromatin condensation, massive vacuolization of the cytoplasm, [redundant? and accumulation of (double-membraned) autophagosomes], with little or no uptake by phagocytic cells.”

- add a definition comment along the lines of: “The precise nature of autophagic cell death is still being debated, and the link between autophagy and cell death unclear. As autophagy is often induced under conditions of stress that could also lead to cell death, there has been a propagation of the idea that autophagy can act as a cell death mechanism; but others argue that autophagy may simply be an attempt of dying cells to adapt to lethal stress rather than a mechanism to execute a cell death program. Further studies are required to resolve this controversy (see e.g. PMID:22082964, PMID:22052193, PMID:25236395). In the meantime, curators should carefully examine the experimental evidence presented in papers on ‘autophagic cell death’, and annotate accordingly”.

Thanks,

Paola

Reported by: paolaroncaglia

Original Ticket: [geneontology/ontology-requests/11803](https://sourceforge.net/p/geneontology/ontology-requests/11803)

**Comment by paolaroncaglia** [comment]
@pauldenny
@RLovering

**Comment by ukemi** [comment]
Made the following edits.

id: GO:0048102
 name: autophagic cell death
 namespace: biological_process
-def: "A form of programmed cell death that is accompanied by macroautophagy, which is characterized by the sequestration of cytoplasmic material within autophagosomes for bulk degradation by lysosomes. Autophagic cell death is characterized by lack of chromatin condensation, massive vacuolization of the cytoplasm, and accumulation of (double-membraned) autophagosomes, with little or no uptake by phagocytic cells." [GOC:autophagy, GOC:mah, PMID:18846107]
+def: "A form of programmed cell death that is accompanied by the formation of autophagosomes. Autophagic cell death is characterized by lack of chromatin condensation and massive vacuolization of the cytoplasm, with little or no uptake by phagocytic cells." [GOC:autophagy, GOC:mah, PMID:18846107]
+comment: The precise nature of autophagic cell death is still being debated, and the link between autophagy and cell death unclear. As autophagy is often induced under conditions of stress that could also lead to cell death, there has been a propagation of the idea that autophagy can act as a cell death mechanism; but others suggest that autophagy may simply be an attempt of dying cells to adapt to lethal stress rather than a mechanism to execute a cell death program. Further studies are required to resolve this controversy (see e.g. PMID:22082964, PMID:22052193, PMID:25236395). In the meantime, curators should carefully examine the experimental evidence presented in papers concerning autophagic cell death, and annotate accordingly.
