### ISSUE TITLE
NTR: reduced folate transmembrane transport

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11962]
Request on behalf of Hadil Alrohaif;

Can we request the term "reduced folate transmembrane transport"

As a child of GO:0055085 transmembrane transport.
The term GO:0008518 reduced folate carrier activity would be part_of the new term.

Evidence is from PMID:14609557, figures 1 and 2 where the authors show uptake of methylenene tertrahydrofolate, a reduced folate, by ARPE-19 cells (retinal pigment epithelium).

Please add GOC references;
GOC:BHF
GOC:hal

Reported by: rachhuntley

Original Ticket: [geneontology/ontology-requests/11801](https://sourceforge.net/p/geneontology/ontology-requests/11801)

**Comment by dosumis** [comment]
Hi Harold (@hdrabkin) & David (@ukemi),

Wondering if I can get some advice on biochemistry.  It would be good to link the requested term to ChEBI in order to get some useful classification rather than trying to place by hand.

The [paper](http://www.sciencedirect.com/science/article/pii/S0014483503002537) descibes the function as "transports reduced-folates, such as N5-methyltetrahydrofolate (MTF)."   The best I can do right now is to refer to 5,10-methylenetetrahydrofolic acid (CHEBI:20502), which I believe matches the chemical mentioned in the paper, but clearly the activity is broader than just transport of '5,10-methylenetetrahydrofolic acid'

From a quick look at the relevant [wikipedia entry](https://en.wikipedia.org/wiki/Folic_acid#Biochemistry_of_DNA_base_and_amino_acid_production), it looks like everything to the right of folate in this pathway could be referred to as reduced folates:

**folate → dihydrofolate → tetrahydrofolate ↔ methylene-THF → methyl-THF**

Is this correct?  This would help with the text def, but I’m also wondering if it would make sense to either ask ChEBI for a ‘reduced folates’ term ourselves, or to make a GOCHE union term for these. 

What do you think?
Cheers,
David

**Comment by dosumis** [comment]
id: GO:0098838
label "reduced folate transmembrane transport"
definition "The directed movement of reduced folate (dihydrofolate, tetrahydrofolate, methylene-tetrahydrofolate or methyl-tetrahydrofolate) across a membrane." [PMID:14609557]
namespace "biological_process"
is_a: transmembrane transport
is_a: amide transport

It would be good to add some more classification.  folic acid transport also has these classifications (some inferred from ChEBI):

'amino acid transport'
'cofactor transport'
'dicarboxylic acid transport'
'modified amino acid transport'
'vitamin transport'

'dicarboxylic acid transport' doesn't apply to reduced folates.  Do the other classifications?

**Comment by dosumis** [comment]
Closing.  Term added in July.  Think I kept this open for comments on additional classifications.   @hdrabkin @ukemi - any suggestions?
