### ISSUE TITLE
APC complexed with inhibitor

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11977]
Following on from a discussion with Tanya and Antonia....

The APC is inhibited by various CDC20/fizzy family inhibitors at various cell cycle phases (not clear cut, sometimes overlapping).

Our first question is how to represent these complexes.

1. Do we request a complex

APC-Cdc20
APC-fizzy related (there is a precedent for this, but there are various fizzy related proteins so it is difficult to establish each complex version without using the gene names
APC-Srw1 complex, APC-Mfr1 etc)

2. Alternatively as this is a complex inhibitor, we could annotate this as 
APC -complex binding.

(IN which case we would obsolete the existing APC-inhibitor complex terms)

One advantage of 2 is that we would not need to ensure that all 15 APC subunits were annotated to all complexes, and we would not have the difficulties defining the complexes which do not seem to be exactly conserved in their role between species.

However, if people would expect to see these annotated as a complex in their own right we should do 1.
If we decide to do 1. we will need a better way to describe the various permutations (I can't think of anything easily without including gene product names we would not easily be able to  distinguish the specific variations.

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11816](https://sourceforge.net/p/geneontology/ontology-requests/11816)

**Comment by bmeldal** [comment]
Or we create the specific complexes in the complex portal as children of the generic 'APC inhibitor complex' term, then you have unique IDs for annotation... Making 15 different complexes that just differ by their 'fizzy-related' protein is no big deal as long as we have some evidence for their existence :)

Looks like we already have a bunch of APC variants in the CP:
http://www.ebi.ac.uk/intact/complex/?q=apc

Birgit

**Comment by ValWood** [comment]
In this case do we need some rules how to name the organism specific variants?

For example, pombe appears to have 2 copies of the human FZR1/ cerevisiae  CDH1
which have  possibly split the roles of the orthologous complexes at different point in the cell cycle. We have an identical  problem with the  CDK-cyclin complexes.

For APC-related and Cdk-cyclin complexes the sensible way to classify them seems to be by the specific cell cycle transitions they are regulating  (i.e their functional role) rather than:

i) the 'families' they belong to seem to be somewhat 'swapped around'.
For instance a cyclin which operates at G1 in one organism, its ortholog may operate at a different transition or even cycle (mitotic vs meiotic) in another organism
or
ii) the specific substrates of the complexes (because the substrates are likely to be partly but not fully conserved between species, and you are unlikely to know all the substrates)

This way  an database would only need to request new species specific instances of these complexes if they had 2 complexes operating at the same transition and needed to make a distinction between them (for instance to make links  between their complex instance, and specific substrates)

An aside:
Maybe we could look at these  two sets of complexes as a mini-project? They are really important cellular components with a lot of literature, but not very well annotated in GO.
For example, Cdk1  has the highest centrality and connectivity of any protein in a unicellular eukaryotic network (possibly even in multicellular) but only 73 proteins experimentally annotated to the CDK complex terms in GO, and all but 13 are to the generic term!)

**Comment by bmeldal** [comment]
The variation to the role in the cell cycle adds indeed a further complication. It's no problem for the CP as we just annotate whichever process and function is applicable to the particular complex. We'd name them by subunit composition (I'd change them from using simply 'variant x' to make them distinguishable in the list of results). The only question then is: which should be the most granular GO term for these complexes? Which goes back to Val's question above. Do we make the subunit-specific complexes in GO as well or just functional complexes based on which cell cycle phase they act in with subunit composition names as narrow synonyms?

@dosumis is working on this and might want to comment.

Birgit
(copied from SF)

**Comment by tberardini** [comment]
I'm returning to this issue because I'm still struggling with what to do with a term in the TG queue:

id: GO:1990800
name: meiotic APC-fizzy-related complex
namespace: cellular_component
def: "An anaphase promoting complex bound to a \"fizzy-related family\" APC activator that regulates meiotic exit by activating the APC/C to target meiotic cyclins for destruction during meiosis." [PMID:11493649]
subset: termgenie_unvetted
is_a: GO:0005680 ! anaphase-promoting complex
created_by: al
creation_date: 2015-07-16T10:37:05Z
-------
Discussion with @ValWood and Antonia (no github acct?) wound up here:

"We wanted to change the definition and the latest incarnation of the def is:

An anaphase promoting complex that positively regulates the metaphase/anaphase transition of meiosis II by targeting meiotic cyclins for destruction.

I also wanted to make a capable of part of link between the requested term and 'meiotic cell cycle process', GO:1903046."
----------
However, now I'm having second thoughts about approving the term in the first place and am *really* liking Birgit's suggestion of "Or we create the specific complexes in the complex portal as children of the generic 'APC inhibitor complex' term, then you have unique IDs for annotation".

Can we revisit this discussion please?  I know most will be caught up in GO meeting but wanted to reactivate work on this.  Thanks.

@dosumis, you might want to chime in, esp. with recent discussion on protein complexes

**Comment by mah11** [comment]
@Antonialock

**Comment by tberardini** [comment]
Trying again to reactivate the discussion,  perhaps when we're all fresh on  Monday? 

@dosumis , @Antonialock

**Comment by Antonialock** [comment]
I realy dont know what the best way is - all I wanted was a meiosis specific term since a term specific to mitosis already exists (by the def, not ontology links).

The last thing Val said in our email discussion, before you said you'd consult Birgit was:
We either need a separate CC term for every APC-fizzy complex, OR we get rid of the APC-activator  complex terms and instead
curate them as APC complex binding.

I don't know which is the preferred option,  but it will be difficult to describe the different APC-inhibitor complexes without using gene names.......also it seems that in different species the orthologous  APC-activators might operate at different times.......
Not sure what the best solution is. Tanya what would we normally do?

**Comment by tberardini** [comment]
I would prefer to not have a separate CC term for every APC-fizzy complex and annotate using the annotation extensions to make the term specific to meiosis.  Yes, this would mean a clean up of the existing terms, including the mitosis specific (def wise) complex.  

The specificity can go into the CP with Birgit's help.  Is there a tracker for CP?  You can link to this issue from there.

Unless there are any strong objections, I'll plan to obsolete the TG term that has been sitting in the queue for a while.  There is an existing GH issue that deals with obsoletion of related 'APC-fizzy related complex activity' terms.  I'll add a note there to look at the CC terms and deal with them at the same time.

**Comment by bmeldal** [comment]
I'm with Tanya here. As a result of the GOC mtg, we are setting up a working group to look at the level of granularity we want to go to with regards of protein complexes.

Antonia, we have a JIRA tracker I can add you to if you have regular curation requests or you can send an email to intact-help@ebi.ac.uk with this specific request. We can also give you access to the curation tool and train you, then you can create complexes yourself. As you are only a few miles away, we can sit down together and I can train you (I'm always looking for excuses to spend a working day in Cambridge so I can cycle instead of jumping in the car!)

Birgit

**Comment by ValWood** [comment]
I was under a slightly different impression from the GO meeting, although to be honest the discussion ended prematurely before it was established exactly what had been decided. I thought that we would instantiate  all broadly conserved complexes? Not doing this worries me because it will be the first example of a  complex used in fission yeast annotation where you cannot retrieve the *exact* complex subunits with a GO query. 

My understanding was that we would establish the complexes in GO, but the 'instances' describing different subunit variations would be  captured by Intact. This suggestion  is slightly different as these are broadly conserved complexes (with a little bit of species variation, which would probably be Intact only). Also, they are fundamentally important complexes with different roles in chromosome segregation and other aspects of cell cycle regulation.

Using extensions like "occurs during" on complexes is useful, but I  think we still need to differentiate the actual complexes that are known to  have different functional roles......
Tanya could you bring this one up at an editorial meeting to check that we are all on the same page wrt when we request a complex term?

Birgit, Antonia isn't based in Cambridge, but we can arrange a session at some point for me, Antonia and Midori to create complexes...it might be a while as we have a few deadlines looming.

Cheers,

Val

**Comment by ValWood** [comment]
I just looked at the minutes and it isn't clear  here either.......

**Comment by bmeldal** [comment]
Thanks Val. Afaik, the GO PIs are discussing the general issue of granularity in their next call (Sandra prodded them to get the discussion started!). And yes, the minutes are vague!

I don't think we are arguing about removing the generic APC-fizzy term, but we don't want to create separate complexes for each fizzy-variant, that'll go into CP. Then you can annotate the proteins to the generic GO term and specific CP AC. Would that retrieve the subunits? I'm afraid, I don't use GO as an analysis tool so need to be educated exactly what type of searches you would run and what info you expect in return - still learning!

Birgit

**Comment by ValWood** [comment]
We would need to allow Intact complex IDs in extensions. I think this could  work. However, I think APC_fizzy is probably a bit of a borderline case. There are  broadly conserved APC variants which I think should be in GO, and species specific variants which maybe should not. The complex Antonia is requesting is one of the conserved complexes I believe, although probably not studied yet in other species.  I prefer establishing the complex with pombe gene names in the term name, but defined according to functional role. If human ends up giving this complex a different name, we are happy to change it (we often go with the cerevisiae complex names for conserved complexes with the pombe names as synonyms. Our community are not particularly imaginative with their complex names!)

I'm not fond of the name "APC fizzy related"  term I think it was chosen because APC-Cdc20 has the exact synonym APC-fizzy http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0090620, but the APC-fizzy  is only an arbitrary lumping term for  all of the APC complexes which are not APC-Cdc20. I would abolish that term and establish "APC-gene family name" for each conserved instance of APC as  they are characterized (as this is how they are referred to). We can converge on the name which becomes most commonly used (which is usually the first characterised).

To be consistent, we need the "APC-gene family name" terms, otherwise, why have APC-Cdc20? The only difference is that APC-Cdc20 is well characterized, and the others are not.

**Comment by bmeldal** [comment]
Thanks, Val.

I'll leave the naming issue to Tanya :)

I'm not familiar with the details of APC and its activators and inhibitors, just trying to advise on the general schema we can go by - but of course there are tonnes of exceptions!

And yes, we are happy to train you whether in CB or elsewhere!

**Comment by ValWood** [comment]
> And yes, we are happy to train you whether in CB or elsewhere!

Great, we'll sort something in the New Year ;)

**Comment by tberardini** [comment]
I would very much like to close this issue.  I think we can do that by:

(1) obsoleting the 'meiotic APC-fizzy-related complex' term in the TG queue.  You can annotate to 'APC-fizzy-related complex' and add an annotation extension to capture the link to meiosis.

(2) "abolish that term [APC-fizzy-related complex, GO:0090621]"

-There are currently no annotations to this term, though there is one annotation to 'regulation of APC-fizzy related complex activity'.

(3) Plan to open new GH tickets for 'APC-gene family name complex' terms for each conserved instance of APC as they become necessary.

**Comment by tberardini** [comment]
I will proceed with the plan as outlined above unless I hear any objections by Wednesday, 9/23/15.
Thanks.

**Comment by ValWood** [comment]
OK, so Antonia, you will need APC-gene complex for the meiotic complex. If the name is different in other species we can change the name later. We don't care about the name....
Was it Mfr1? I would say APC-Fzr1/Mfr1 complex because Fzr1 is the human ortholog name and its a also pombe synonym....This should make it clear *which* APC-fizzy related complex we mean

This is also a good example for the complex working group. The  protein family is conserved, but the functional role appears not to be. Do we go by evolutionary conservation or functional? The pombe complex is not present during mitosis, its a meiotic APC inhibitor. In cerevisiae, it appears to have a mitotic exit role.  Therefore function of the orthologs is NOT conserved. This information is also important for PAINT, so one option is to capture the evolutionary conservation of the complex in the GO term and refer to the functional differences in the definition? @pgaudet (@ ...can't link to Paul T!)

**Comment by bmeldal** [comment]
Ok, example captured in my WG file.

@Antonialock, please let me know if you need me to create any specific complexes in the CP :)

**Comment by Antonialock** [comment]
yes please, the one Val said 
APC-Fzr1/Mfr1 complex

**Comment by bmeldal** [comment]
Antonia,

Can you please email me at bmeldal AT ebi.ac.uk?

I need a paper with evidence that the complex exists (preferably something with purified proteins!) and if you have papers with evidence for MF and BP or at least a list of terms that are applicable that would also help. 

Let's take it out of this ticket :)

Birgit

**Comment by Antonialock** [comment]
All the information should be in the TG submission?

**Comment by bmeldal** [comment]
Ah, Tanya will create the GO term for you if we go for the specific term in GO. I can only create the CP term and I can't see TG submissions.

**Comment by Antonialock** [comment]
PMID:11493649
mfr1 will be annotated to the complex term, whatever that will be
and
positive regulation of ascospore formation
and I guess I will need to add something like positive regulation of meiosis II if the complex term cant have this link

**Comment by Antonialock** [comment]
(meiosis II and sporulation sort of overlap in pombe)

**Comment by ValWood** [comment]
The processes should be curated , because AFAIK, CC-BP links are not genrating annotations at present (please correct me if I'm wrong). Also, yes in this case it would not be possible to establish CC-BP links specific enough for PomBase.

**Comment by tberardini** [comment]
I am now thoroughly confused as to where the term/s are going to be created and what is going to happen to the term in the TG queue.  CP?  GO?  Please someone summarize for me.

Here's the term as it exists in the TG queue:

[Term]
id: GO:1990800
name: meiotic APC-fizzy-related complex
namespace: cellular_component
def: "An anaphase promoting complex bound to a \"fizzy-related family\" APC activator that regulates meiotic exit by activating the APC/C to target meiotic cyclins for destruction during meiosis." [PMID:11493649]
subset: termgenie_unvetted
is_a: GO:0005680 ! anaphase-promoting complex
created_by: al
creation_date: 2015-07-16T10:37:05Z

**Comment by tberardini** [comment]
I'm back on Github rotation and so I'm looking at this issue again.  I'll repost my last question:



I am now thoroughly confused as to where the term/s are going to be created and what is going to happen to the term in the TG queue. CP? GO? Please someone summarize for me.

Here's the term as it exists in the TG queue:

[Term]
id: GO:1990800
name: meiotic APC-fizzy-related complex
namespace: cellular_component
def: "An anaphase promoting complex bound to a \"fizzy-related family\" APC activator that regulates meiotic exit by activating the APC/C to target meiotic cyclins for destruction during meiosis." [PMID:11493649]
subset: termgenie_unvetted
is_a: GO:0005680 ! anaphase-promoting complex
created_by: al
creation_date: 2015-07-16T10:37:05Z

**Comment by bmeldal** [comment]
@dosumis could you comment, please? This is a very tricky one giving we are currently discussing the axiomisation of complexes. 

Copied from Val above:
>This is also a good example for the complex working group. The protein family is conserved, but >the functional role appears not to be. Do we go by evolutionary conservation or functional? The >pombe complex is not present during mitosis, its a meiotic APC inhibitor. In cerevisiae, it appears to >have a mitotic exit role. Therefore function of the orthologs is NOT conserved. This information is >also important for PAINT, so one option is to capture the evolutionary conservation of the complex >in the GO term and refer to the functional differences in the definition?

I would suggest the specific term goes in the CP and our AC can be used as an annotation object (just as the UCL group does already). 

However, I think they are also looking for a higher order grouping term as GO:0090621 APC-fizzy-related complex
[Definition: An anaphase promoting complex bound to the "fizzy-related family" APC activator FZR1/Cdh1/Srw1 that regulates mitotic exit by activating the APC/C to target mitotic cyclins for destruction during anaphase and telophase. Is also active during G1.]
doesn't quite fit due to the mitotic/meiotic relationship discrepancy.

Birgit

**Comment by dosumis** [comment]
If we are to retain to the species general term in GO - something that is being seriously questioned by the protein complex working group - then I think it has to be defined in terms of its components only:

"An anaphase promoting complex bound to the "fizzy-related family" APC activator FZR1/Cdh1/Srw1."

There *might* be a case for keeping some basic MF or low level process axiom in the ontology, but probably easier just to punt all function/process context to annotation - certainly the higher level processes context (meiosis/mitosis) has to be.  

Isn't there also a set of function term made for these complexes that need to be obsoleted?

**Comment by ValWood** [comment]
> If we are to retain to the species general term in GO - something that is being seriously questioned by the protein complex working group 

Why? I can see 2 big issues with losing them:
1. Most MODs are geared up for users to retrieve protein complex members using GO. We would need to change our database systems radically to handle any alternative (for  annotating, browsing, querying and display). It is not a simple issue to only change to Intact IDs we would need to change much, much more.
2.   For analysis users often get useful results looking at over/under representation of annotation of complexes. see for example:
http://www.ncbi.nlm.nih.gov/pubmed/23697806
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3866870/table/RSOB130053TB4/

What do we gain from not including general complex terms (obviously it is easier for the editors, but if this is the main issue maybe there are better ways to handle this)?

**Comment by ValWood** [comment]
![enrichemtn of complexes with specific phenotypes](https://cloud.githubusercontent.com/assets/7359272/10493560/bb1fee42-72a9-11e5-8004-9e781450d572.jpg)

**Comment by ValWood** [comment]
We identified strong correlations of  specific  phenotypes with specific  complexes. I want to be able to continue to do the above  using GO which has tools in place to do so....

**Comment by ValWood** [comment]
Also useful work like this:
http://www.ncbi.nlm.nih.gov/pubmed/?term=23242164

If you parcel complexes off somewhere you lose a lot of analytical power from GO.

**Comment by dosumis** [comment]
You should come along to a protein complex WG meeting to present this.
Nothing decided yet, and we certainly need to look into example use cases
to make sure we still have ways to support.

**Comment by tberardini** [comment]
"You should come along to a protein complex WG meeting to present this."
You = @ValWood, right?

**Comment by ValWood** [comment]
Sandra asked me to fill in the doodle poll which I have. Can't make this week though, teaching, meeting and holiday fills rest of week....

**Comment by bmeldal** [comment]
Thanks, Val. I saw your doodle choices. I hope to set a date later today as everyone has entered now.

I second David, we need the input from the annotators and users to know what level of granularity is essential and where punting off identifiers to CP would not work.

Speak to you soon,
Birgit

PS: I have no preference either way!

**Comment by tberardini** [comment]
Did you (@ValWood, @bmeldal)  ever talk about this in a protein complex WG meeting call?

**Comment by bmeldal** [comment]
We did discuss this as one of the tricky cases. @dosumis is still working on the axiomisation of complexes in GO. 

Can the APC-fizzy complexes be annotated with capable_of [activity]? If yes, they could be axomised automatically from a species-specific complexes created in CP. But in order to do that, we need precise membership of the complex. I read between the lines above that sometimes these complexes are not fully characterised...

@ValWood, as for what grouping terms might be appropriate, personally I'd go by function, not composition, for the very reason that users would use GO to find functional relationships, not necessarily strict evolutionary relationships (right?). Here we have cases (if I understand Val right) where orthologus have taken on different functions and the same function is carried out by other, still related proteins. You'd expect the user to know the phylogenetics of the proteins (established using phylogenetics tools). Going by function would then fit nicely with axioms.

@Antonialock, is the term Tanya created for you for now sufficient? If yes, I'll wait with the CP term until we have a general solution.

Sorry for being vague, but this whole topic is still in the balance. 

Sandra and I will be in Geneva for Biocuration and staying for the 1st day of the GOC meeting. We can discuss more then if we don't finding a solution here...

Birgit

**Comment by tberardini** [comment]
@bmeldal, I didn't create a term for @Antonialock.  :)

**Comment by bmeldal** [comment]
Someone added
GO:1990857 APC-Fzr1/Mfr1 complex 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990857#term=info
Def: An anaphase promoting complex bound to an activator in the Fzr1 (human)/Mfr1 (pombe) family. 
to the Ontology on 25/9/15...

This term is not fully defined (..."Fzr1 (human)/Mfr1 (pombe) **family**") so can't go into CP as it is. I need the full list of interactors or a list or alternatives to create a bunch of related terms.

This is not the meiosis-specific term @Antonialock was originally talking about. I though we nailed that one using AEs?

**Comment by tberardini** [comment]
GO:1990857 APC-Fzr1/Mfr1 complex was added by Antonia.  The GO id suggests this was a TG addition.

**Comment by ValWood** [comment]
This is the/a meiosis specific APC activator

Form a quick glance the complex is inferred because we know it binds and activates APC  (subunit apc4) during meiosis, in an analogous way to the fizzy family protein (slp1 pombe  orthologs cdc20 in human and cerevisiae), activates the APC during during mitosis.

If you prefer, in these cases we can just annotate to 
"anaphase-promoting complex binding" with the extension during  relevant meiotic cell cycle phases

As I mentioned previously I don't know if the activators and inhibitors which bind to the ABC transiently during certain phases are considered to be part of the APC complex.

For example S. cerevisiae CDC20 is annotated to both "Anaphase promoting complex", and "anaphase promoting complex binding"
http://www.yeastgenome.org/locus/YGL116W/overview#go
But it isn't *always* a member of the APC.

We need to decide whether we need the different types of APC for the different APC-activator complexes (otherwise we can't disambiguate the different APC versions because all of  different activators will be annotated to the  core APC simultaneously), or we  consider them not to be a bona-fida complex member and annotate as APC binding.

Maybe this is a  question for an annotation call. I think its too big and general an  issue to decide in a git hub ticket.

**Comment by tberardini** [comment]
@ValWood - would you be willing to present this at an annotation call?  If so, let's contact Kimberly/David and add it to the agenda for an upcoming one.

**Comment by bmeldal** [comment]
Yes, I agree, this issue is more general and should be discussed with annotators :) Happy to call into an annotation call.

Happy weekend!

**Comment by ValWood** [comment]
Yes...give me a week or two...drowning in e-mail

**Comment by tberardini** [comment]
@ValWood - would you be willing to present this at an annotation call? If so, let's contact Kimberly/David and add it to the agenda for an upcoming one.

**Comment by ValWood** [comment]
Yes. Can you make it at least two weeks from now as I will need to refresh and  we have  some crazy deadlines.

Val

**Comment by tberardini** [comment]
Emailed Kimberly to put on agenda for call four weeks from this week.

**Comment by vanaukenk** [comment]
Hi,
I am fine with putting this on the agenda for an annotation call.  @ValWood and @Antonialock  - I think presenting this in the context of an annotation consistency exercise would help everybody come up to speed on the issue.  
I can re-arrange the schedule to put PomBase on for March, if that works for you guys.  Thx.

**Comment by Antonialock** [comment]
March15 would work?

**Comment by ValWood** [comment]
I can't do 15th, I have a minor eye op.

**Comment by Antonialock** [comment]
It might have to wait until April then because we are on the group retreat March8, and then French pombeclub march22, and then it is easter and ISB conference. April 19 or 26?

**Comment by bmeldal** [comment]
I'd like to join the call as well. I can do any Tuesday except for 12th April when most of us will be at ISB anyway!

**Comment by vanaukenk** [comment]
Thanks, all.  How about the annotation call on April 26th?  Marc is listed for the consistency exercise, but I will ask him if he wouldn't mind being bumped to May or later.

**Comment by Antonialock** [comment]
It is ok with me..

On Thu, Feb 25, 2016 at 3:08 PM, vanaukenk <notifications@github.com> wrote:

> Thanks, all. How about the annotation call on April 26th? Marc is listed
> for the consistency exercise, but I will ask him if he wouldn't mind being
> bumped to May or later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geneontology/go-ontology/issues/11977#issuecomment-188827666>
> .
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by tberardini** [comment]
From linked issue, @ValWood would like to obsolete APC-Fzr1/Mfr1 complex

**Comment by tberardini** [comment]
@Antonialock , @ValWood - need to deal with the 1 Pombase annotation to APC-Fzr1/Mfr1 complex before obsoletion.  Since the term was requested by you and used only by you, I think I can go ahead with the obsoletion without giving notice to the entire GO consortium.

After the annotation call, was there any action to be taken for the complex terms?  I've finished cleaning up all the related activity/inhibitor/activator/regulation terms in another GH item.    There still is this term in the TG queue:

id: GO:1990800
name: meiotic APC-fizzy-related complex

Approve?  Obsolete?  

Unfortunately, I only caught the very tail end of the annotation call so didn't get the action items.  The meeting minutes aren't clear on what to do wrt the complex terms.

Thanks.

**Comment by ValWood** [comment]
My take is that here we would use

"APC complex binding" occurs during (meiotic cell cycle phase)
"Ubiquitin ligase activator activity"  occurs during (meiotic cell cycle phase)
(or happens during, I always forget)

But it was a bit unclear what the final  decision was.....


We'll sort the existing annotation.

Val

**Comment by dosumis** [comment]
> "APC complex binding" occurs during (meiotic cell cycle phase)
> "Ubiquitin ligase activator activity" occurs during (meiotic cell cycle phase)
> (or happens during, I always forget)

Looks good to me.  (& it's happens_during)

**Comment by tberardini** [comment]
I will obsolete both the term in the TG queue (today) and APC-Fzr1/Mfr1 complex (on Monday).

**Comment by tberardini** [comment]
Here's the current structure of 'anaphase-promoting complex' and children.  
<img width="351" alt="screen shot 2016-05-06 at 11 37 04 am" src="https://cloud.githubusercontent.com/assets/4998871/15082871/f253077a-137e-11e6-8642-59209cfebb94.png">
After I obsolete APC-Fzr1/Mfr1 complex, there will only be two children left.  My impression is that these two children are to remain.  Is that correct?

**Comment by ValWood** [comment]
Hi Tanya,

I thought we were getting rid of these too. They are also examples of the APC complexed with the activator. There is nothing special about these two. 
Cdc20 is "fizzy" in fly, everything else is "fizzy-related" so this is a somewhat  arbitrary distinction based on protein family. It was part of an attempt to follow the precedent because there was a term for one activator.

Val

**Comment by tberardini** [comment]
What do you think about just merging the lot into the parent, 'anaphase-promoting complex'?

**Comment by ValWood** [comment]
I was wondering why we didn't do that this morning, but  then I realised that as we have decided that the inhibitors and activators are not part of the complex this would result in erroneous annotations (and its mainly the inhibitors and activators which use these terms, not all of the APC complex members). I think we need to re-annotate..... It isn't a huge deal....

**Comment by ValWood** [comment]
You'll be glad when this one is over... I just noticed how long it was :)

**Comment by tberardini** [comment]
Good news.  There are no annotations to the children terms except for one non-IEA and three IEA ones to APC-Fzr1/Mfr1 complex.  I think we can obsolete without ill effects and no need to review annotations.  I will send out an obsoletion email for all three.

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990857#term=annotation

**Comment by tberardini** [comment]
Email sent:

Dear all,

The proposal has been made to obsolete the following terms:

GO:0090620 APC-Cdc20 complex
GO:0090621 APC-fizzy-related complex
GO:1990857 APC-Fzr1/Mfr1 complex


The reason for obsoletion is the terms were not considered appropriate for GO but more appropriate for IntAct and/or PRO.  The long discussion on this issue can be reviewed here:

https://github.com/geneontology/go-ontology/issues/11977

The first two terms do not have any annotations.  The last term, GO:1990857 APC-Fzr1/Mfr1 complex, has one experimental annotation (PomBase) and three IEA annotations (EnsemblFungi). 

*** Unless objections are received by May 17, 2016, we will assume that you agree to this change. ***

On behalf of the GO ontology editors,

Tanya

**Comment by tberardini** [comment]
Suggestion from Peter D'E to 'suggest' CP terms as alternatives in the 'consider' or 'replace by' field.

**Comment by tberardini** [comment]
@bmeldal - Are there 'replacement' terms in CP?  If yes, can you please put their ids in this issue and I will mention them in the obsoletion comment.  Thank you.

**Comment by tberardini** [comment]
Also suggestion from PDE to consider the parent term instead for curation and that the term is too fine-grained for GO.

**Comment by tberardini** [comment]
DONE!!!!!
