### ISSUE TITLE
missing links and relationships in the BDNF-TRKB receptor signalling pathway and parent

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11979]
Hi,

There are missing links and relationships in the Neurotrophin TRK receptor signalling pathway and Brain-derived neurotrophic factor receptor signalling pathway. I am attaching a figure of how things looks now on QuickGO.

1. Should these terms be linked?:

Process: GO:0048011 neurotrophin TRK receptor signaling pathway

A series of molecular signals initiated by the binding of a neurotrophin to a receptor on the surface of the target cell where the receptor possesses tyrosine kinase activity, and ending with regulation of a downstream cellular process, e.g. transcription.

and 

Function: GO:0005167 neurotrophin TRK receptor binding

Interacting selectively and non-covalently with a neurotrophin TRK receptor.

2. Should these terms be linked?:

Process: GO:0031547 brain-derived neurotrophic factor receptor signaling pathway

The series of molecular signals generated as a consequence of a brain-derived neurotrophic factor receptor binding to one of its physiological ligands.

and 

Function: GO:0005169 neurotrophin TRKB receptor binding

Interacting selectively and non-covalently with the neurotrophin TRKB receptor.

3. Since BDNF is a subtype of neurotrophin and TRKB is a subtype of TRK receptors, (note BDNF interacts specifically with TRKB) should 

GO:0031547 brain-derived neurotrophic factor receptor signaling pathway

be a child of:

GO:0048011 neurotrophin TRK receptor signaling pathway?

PMID:    22217452 (review - figure 2)

or better suggestions

GOC: NC
GOC: BHF

Thanks

Nancy

Reported by: noonoo25

Original Ticket: [geneontology/ontology-requests/11818](https://sourceforge.net/p/geneontology/ontology-requests/11818)

**Comment by NancyCampbell** [comment]
@NancyCampbell

**Comment by ukemi** [comment]
Hi Nancy,

Sorry to have taken so long to get back to this. Unfortunately I cannot link the binding terms directly to the pathway terms because the nature of the binding is not specified in the terms. So for example a gene product could bind a receptor as a ligand and activate the pathway, being a part of the pathway. However, a gene product might also bind to a receptor and regulate the receptors natural activity and therefore be regulating the pathway. So just by binding the receptor, we don't know the relation between the binding and the pathway itself. 

I also asked Becky about the nature of the BDNF/TRK relations because she had previously led the signaling group. Apparently BDNF can bind both TRKB and LGNF receptors, so making the structure between BDNF and TRK would not always be true.

Finally, for your last issue. The signaling group had decided to use has_part relationships to describe the various paths that the multitude of signaling pathways can take. The signaling group had done this for the GPCR pathway.  In the future, I see that the creation of these very complex pathways may not be necessary using the Noctua editing strategy. But if you would still like to see the complex pathways represented in a single term, I think we could look into those again. If so, could you open another ticket about which pathways you would specifically like to see and I will try to work them out with Becky maintaining consistency with what her group had already done?

-David
