### ISSUE TITLE
protein acetyltransferase activity grouping term

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#11976]
Could we have some structure  under:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0016407#term=children

I'd like a grouping term for protein acetyltransferases. This is primarily so that we can 
group the protein acetyltransferases so we can have a "has_substrate/has_direct_input"
prompt for an extension for these terms in our curation tool

There is a term
id: GO:0034212
name: peptide N-acetyltransferase activity
namespace: molecular_function
def: "Catalysis of the acetylation of an amino acid residue of a peptide or protein, according to the reaction: acetyl-CoA + peptide = CoA + N-acetylpeptide." [GOC:mah]

is there any reason this can't be protein in the primary term name?

All of the protein acetyltransferases need grouping under the new parent, but some (for instance the histone lysine acetyltransferases also need to be under 
id: GO:0034212
name: peptide N-acetyltransferase activity
and they are not currently.

I'm confused about some of the acetyltransferases which refer only to amino acids, are these always protein acetyltransferases, or can free amino acids be acetylated?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/11815](https://sourceforge.net/p/geneontology/ontology-requests/11815)

**Comment by ValWood** [comment]
Hi David,

Is this one easy? I am waiting on it  to add a term to one of our config files to specify when annotations extensions are required in the curation tool.
Cheers,

Val

**Comment by ukemi** [comment]
Hi Val,

I would prefer to keep the name as is because although this term is not in EC, the child peptide alpha-N-acetyltransferase activity EC:2.3.1.88 is and it uses the peptide nomenclature with the protein nomenclature as a synonym. Right now the structure we have pretty much follows EC. 

It also appears that the enzymes in the superclass can work on free amino acids. See PMID:21936773 for an example. Any reason why you can't add the annotation extension requirement to each of the appropriate terms that currently exist? I'm not sure what a new grouping term would do for us.

-D

**Comment by ValWood** [comment]
hi David,

Wouldn't it be useful to be able to find all of the acetyltransferases which are known to acetylate proteins?
Say you wanted to look for candidate acetyltransferases? 
I can do it the other way., but to indicate my problem, I don't know how to.

**Comment by ValWood** [comment]
I found the term I was asking for!
 GO:0006473	protein acetylation
ignore me!
