### ISSUE TITLE
PROBLEM WITH MEIOTIC PHASE TERMS !

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#11992]
Hi,

A while ago Jane and I did a big clean up of the phase terms as an outcome of the cell cycle content meeting. We (I thought...) made all of the phases completely disjoint from the BP term. The rationale for this is that the phases are a bit of an abstraction, and they don't really refer to  processes, but the gaps between visible landmarks providing timings when processes do occur (although some of the phase names sound a bit like the associated processes).

However, I notice that some relations exist between meiotic phases and processes. Maybe we forgot to remove these, but  it is possible they have been inferred by the reasoner.

For example, "meiosis II cell cycle phase"  and "meiosis II M-phase" have a part_of relation to meiosis II. 

An additional  problem is that the definitions of these phases don't follow the pattern we used for mitosis "A cell cycle phase during which x occurs,  and occurs as part of a x cell cycle".

For example:
GO:0098765 meiosis II cell cycle phase
Def: One of the distinct periods or stages into which meiosis II is divided. Each phase is characterized by the occurrence of specific biochemical and morphological events.

GO:0098767 meiosis II M phase
Def: M phase during meiosis II (hmmm)

But the current def should also be tweaked. It now occurs to  me that the "part of" in the def is the misleading part. Probably a more precise definition would be 
"A period of time during the x cell cycle in which x occurs,  and which occurs DURING a x cell cycle"
(the critical things are that it is a 'period'  not a 'process' and that it is 'during' something not 'part_of' anything).

We also had long (unresolved) discussions previously about what the relationship between the phases and the processes should be.  Possibly, if any are added,  the phases should have "occurs during" relationships to cell cycles, and, the processes which occur during specific phases  could also have "happens during" relationships to phases.

Finally the meiotic phase terms do not have the 
"Restrictions	This term should not be used for direct annotation. See comment below for further information."

Thanks

Val

**Comment by mah11** [comment]
I agree that these links look problematic, but I don't think the "part of" wording in the defs is a big issue, because it makes no difference to the asserted links or the reasoner (it also doesn't bother me; it makes sense to me to say "S phase is part of the cell cycle" in natural language, for example, even if the ontology relations don't formally say that).

Instead, I think the problem is that these (and other) part_of links haven't been properly reviewed in light of the clarification that "meiosis I" and "meiosis II" refer specifically to the first and second meiotic nuclear divisions, not to the whole cell cycles (or two big chunks of the whole meiotic cell cycle, if that's a better way to look at it). So we've ended up with phase part_of meiotic nuclear division links, which indeed make no sense.

What need to be done is to disambiguate the "first/second meiotic cell cycle" and "first/second meiotic nuclear division" senses of "meiosis I/II", wich will probably involve adding terms for the former and moving a lot of what are now parts of the latter.

**Comment by ValWood** [comment]
Thanks, that makes sense.

meiosis II
Definition	The second nuclear division of meiosis, in which the two chromatids in each chromosome are separated, resulting in four daughter nuclei from the two nuclei produced in meiosis II.

The first part is OK...but  this term then refers to 'produced in meiosis II'  as if it is a 'period'.
I think there is an old ticket to refine these term names to make it clear that they refer to the actual nuclear divisions.

(By the way- for all of the other partially sighted people, no Midori isn't  using Gene Simmons as her github icon, look closer, its Giles her cat).

**Comment by dosumis** [comment]
### cell cycle phases with process parts.

Part relations are logically correct here, but I believe we decided to use happens_during as a way of avoiding grouping of annotations under phase terms.

There was only one of these:  'G2 cell size control checkpoint' part_of some G2 phase

I have switched this to 'happens during'.

####  phase part_of meiotic nuclear division links ... make no sense.

Is this fixed by switching to happens_during?   Remember, this only says something about timing.

### processes with phase parts:

There were rather a lot of these (my fault) - being used to automate classification.  They shouldn't cause problems fo annotation grouping, but are actually logically incorrect.  I have switched all of them to 'happens during'

#### part relationships between phases

These are logically correct and I don't think they cause any problems.  They also give a bit of structure to the graph display of phase terms.  I have left them in.

### Definitions patterns

Not sure what's wrong with this:

> GO:0098767 meiosis II M phase
> Def: M phase during meiosis II (hmmm)

Isn't it?

###  disambiguate the "first/second meiotic cell cycle" and "first/second meiotic nuclear division" senses of "meiosis I/II"

Perhaps file a separate ticket for this with more details?

### Midori isn't using Gene Simmons as her github icon

I did a double take too.

**Comment by dosumis** [comment]
> We (I thought...) made all of the phases completely disjoint from the BP term.

They are disjoint (e.g. nothing can be a phase and a 'cell cycle process'), but this doesn't stop them sharing parts. I've added the following axioms to x-disjoint.owl, which I think do what you want:

'biological phase' DisjointWith part_of some 'cellular process'
'cellular process' disjointWith part_of some 'biological phase' <-  Bit worried about this one because I don't believe this to be true given our modelling assumptions.  Might ultimately bite someone from outside of the GO.

**Comment by dosumis** [comment]
If all of the above is good, can I close the ticket?

**Comment by mah11** [comment]
> MAH: disambiguate senses of "meiosis I" & meiosis II"
> DOS: Perhaps file a separate ticket for this with more details?

I put it in this ticket because seems like it would fix the problems Val spotted. If, upon further consideration, it still looks like it should be split off, that's fine. But read on first ...

> MAH: phase part_of meiotic nuclear division links ... make no sense
> DOS: Is this fixed by switching to happens_during?

No. The problem is that it makes no biological sense, because each meiotic nuclear division takes place during (in, as part of, etc.) one phase, namely M phase. If they stay linked, it should be the other way round (meiotic nuclear division part_of M phase, or meiotic nuclear division happens_during M phase). And there really can't be links between nuclear division and any other cell cycle phases. S phase is really not part of a nuclear division!

> Not sure what's wrong with this:

    GO:0098767 meiosis II M phase
    Def: M phase during meiosis II (hmmm)

> Isn't it?

No! At least, not if meiosis II is defined as the second meiotic nuclear division, as noted above.

If by "meiosis II" one meant the second meiotic *cell cycle*, then it would be OK. But the current "meiosis I' and "meiosis II" text definitions, and the fact that both are is_a GO:0007126 ! meiotic nuclear division make it clear that this isn't the current situation. GO doesn't have terms for "first meiotic cell cycle" or "second meiotic cell cycle" at present.

> Val: Midori isn't using Gene Simmons as her github icon
> DOS: I did a double take too.

OK, OK, I've changed the picture. Same cat, different angle.

**Comment by ValWood** [comment]
> OK, OK, I've changed the picture. Same cat, different angle.
Oh please put it back, it made me  giggle ....

**Comment by dosumis** [comment]
>> OK, OK, I've changed the picture. Same cat, different angle.
> Oh please put it back, it made me giggle ....
+1

**Comment by dosumis** [comment]
>>> MAH: phase part_of meiotic nuclear division links ... make no sense

>>DOS: Is this fixed by switching to happens_during?

> No. The problem is that it makes no biological sense, because each meiotic nuclear division takes place during (in, as part of, etc.) one phase, namely M phase. 

OK.  Got it now.

> If by "meiosis II" one meant the second meiotic cell cycle, then it would be OK. But the current "meiosis I' and "meiosis II" text definitions, and the fact that both are is_a GO:0007126 ! meiotic nuclear division make it clear that this isn't the current situation. GO doesn't have terms for "first meiotic cell cycle" or "second meiotic cell cycle" at present.

Should we just add these then? It would make formalisation -> auto maintenance of the heirarchy easier.

**Comment by mah11** [comment]
> Should we just add these then? ["first meiotic cell cycle" & "second meiotic cell cycle"]

Makes sense to me.

Gene Simmons' encore will have to wait 'til tomorrow because of which pics are ready to hand on which 'puter ...

**Comment by ValWood** [comment]
and me.

**Comment by mah11** [comment]
OK, Gene-the-cat is back. (I had no idea that pic would look so rockstar when shrunk ...)

**Comment by ValWood** [comment]
Yay, bad-ass Giles.

**Comment by dosumis** [comment]
If we add 'first meiotic cell cycle' & 'second meitotic cell cycle', then these would be parts, not subclasses, of 'meiotic cell cycle' as currently defined, : "Progression through the phases of the meiotic cell cycle, in which canonically a cell replicates to produce ***four*** offspring with half the chromosomal content of the progenitor cell via ***two nuclear divisions.***"  Worried that this would be confusing.

**Comment by mah11** [comment]
Good point. Not sure what's the best solution, although I remain convinced that we need to distinguish the "meiotic nuclear division" meaning of "meiosis I" and "meiosis II" from the parts of the greater meiotic cell cycle that include the nuclear divisions but also other cell cycle phases and events.

In other words, we do need the terms that we're provisionally referring to as "first meiotic cell cycle" and "second meiotic cell cycle", but we may need to come up with names that don't make their part_of connection to "meiotic cell cycle" confusing. I do not yet have clever suggestions for such names, but will let you know if anything comes to me in a dream.

**Comment by dosumis** [comment]
OK.  Having made an effort to get my head around the biology rather than semi-mindlessly following design patterns...

Meiotic M-phase I & II make no sense and should be obsoleted.  For the rest, we should may be able to define using other timing relations.  From this figure, looks best to define I vs II relative to cytokinesis rather than nuclear division.

![wikipedia_meiosis_fig](https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Meiosis_diagram.jpg/800px-Meiosis_diagram.jpg)

To get a release out now.  I'll probably just strip the formalisation out and assert.

**Comment by mah11** [comment]
> Meiotic M-phase I & II make no sense and should be obsoleted.

That sounds like it'll help a lot. For the rest, whatever makes the most sense ontologically and biologically is fine by me.

**Comment by dosumis** [comment]
All done except obsoletions.  Will send out notice ASAP.

**Comment by dosumis** [comment]
Fixed  - see #12242

**Comment by dosumis** [comment]
Obsoletion notice sent.  Will close once actioned:

> Dear all,
> 
> We propose to obsolete
> 
> meiosis I M phase ; GO:0098766
> meiosis II M phase ; GO:0098767
> meiotic M phase; GO:0051327
> 
> The reason for obsoletion is that these terms were added in error. See discussion here:
> https://github.com/geneontology/go-ontology/issues/11992
> 
> There are no annotations to these terms (not allowed as they are phase terms), and no usage in annotation extensions.
> The terms aren’t used in any mapping or slim subset, or cross-referenced in other ontologies.
> 
> We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete on 26th Jan 2015.
> 
> *** Unless objections are received by Jan 26th, we will assume that you agree to this change. ***
> 
> Thanks,
> 
> David
