### ISSUE TITLE
inconsistency in relations

### ISSUE THREAD

**Issue by rbalakri** [geneontology/go-ontology#12002]
HI,

the gorel.obo file contains names that sometimes have an underscore (_) between words, sometimes not?  Should 'happens_during' have an underscore? 

GOREL:0000027 in_presence_of
GOREL:0000752  has_direct_input
GOREL:0000001 happens during
BFO:0000051   has part
RO:0002502   depends on

Rama

**Comment by dosumis** [comment]
Hi Rama,

This is a historical thing.  All relations originally had underscores in the names.  I'd have preferred if we'd kept it that way, but for RO/BFO it was agreed that these should be removed.  Never happened for GOREL relations.  We could do it, although you'd continue to see the readable old-style OBO ids (AKA shorthand) in GAF/GPAD.

Interesting that happens_during still has a GOREL ID.  We should be using the one from RO.  Thought I'd cleaned all these up, but seems not.

Cheers,
David

BTW - better to put gorel issues on the [annotation extensions github](https://github.com/geneontology/annotation_extensions/issues), as the rest of them are there.




Cheers,
David

**Comment by rbalakri** [comment]
Hi David,
Thanks.
I thought there was a technical reason to keep underscore (easy for scripts to parse). You are saying the standard format should no underscores. 

Rama

**Comment by dosumis** [comment]
happens_during ID issue fixed (was OK in OWL - but stray xref gave it wrong it in OBO).

Should probably remove underscores from names in order to be consistent.  But this is low priority.

**Comment by paolaroncaglia** [comment]
Hi @dosumis and @rbalakri ,
There doesn't seem to be an easy way to transfer tickets from one tracker to the other.
If this is the case, please either make a copy on the annotation tracker (it should be linked to it anyway?), or please deal with this issue here. Let me know if I can be of any help. Thanks!
Paola

**Comment by mah11** [comment]
Following the derail rather than the original topic ... I looked into moving tickets for our PomBase trackers and found that indeed, GitHub doesn't have anything built in to do it. The feature has been requested:

https://github.com/holman/ama/issues/413

and there's apparently a third-party hack that you may want to look into:

https://github.com/google/github-issue-mover

**Comment by cmungall** [comment]
On 11 Aug 2015, at 6:43, Midori Harris wrote:


> https://github.com/google/github-issue-mover

I'v  used this, it works fine

**Comment by dosumis** [comment]
This issue was moved to geneontology/annotation_extensions#51
