### ISSUE TITLE
some "cell cycle arrest" terms which missed obsoletion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12001]
My notes slate the following terms for obsoletion:

GO:0072694 cell cycle arrest in response to caffeine
GO:0036226 cell cycle arrest in response to glucose starvation 

These were probably requested by PomBase to make logical refs for phenotype terms but not normal processes.
They have no annotations....

Add labels PomBase/cell cycle

**Comment by paolaroncaglia** [comment]
Hi Val,

There are a few more terms under 'cell cycle arrest', could we please make sure about all of them:

G1 cell cycle arrest in response to nitrogen starvation
with children/descendants 
mitotic G1 cell cycle arrest in response to nitrogen starvation
and regulation thereof

mitotic G2 cell cycle arrest in response to glucose starvation (child of GO:0036226 you mention above as slated for obsoletion) (also note it has a redundant link is_a mitotic cell cycle arrest) 

mitotic cell cycle arrest in response to nitrogen starvation 
and regulation terms
Are these ones real?
Related:
mitotic G1 cell cycle arrest in response to nitrogen starvation (and reg. children)
if the one above is real, then these ones are too, and should be made is_a the above

mitotic cell cycle arrest in response to pheromone
Looks good to me

Also, GO:0036226 is in FYPO, I presume you'll take care of that.

Thanks,

Paola

**Comment by mah11** [comment]
In Val's absence, here's what (little) I know ...

As I understand it, it's normal for fission yeast cells to arrest the cell cycle in G1 under nitrogen starvation conditions (or upon pheromone exposure), and to arrest in G2 if it's glucose starvation. Whether that makes a case for retaining GO:0071851 and GO:0036227, or any corresponding regulation terms, is one for Val and you (i.e. GO editors) to hash out; I have no preference. It does seem like the less specific parent terms (GO:0036226, GO:0030996) are superfluous, at least for fission yeast, since only G1 arrest is normal for nitrogen starvation, and only G2 arrest is normal for glucose starvation.

I also suspect that no one needs the terms that aren't specific for the mitotic cell cycle; I have no idea how much work has been done on meiotic cell cycle arrest under starvation conditions in any species.

FYPO doesn't use GO:0036226 directly. We'll continue to use GO:0036227 if it's retained, but it won't be a big deal to alter or delete the affected logical def if it goes obsolete.

GO:0072694 can definitely go obsolete; I wasn't sure it was normal back when I added it (see #9224), and in fact FYPO doesn't use it now.

other relevant tickets: #9599, #96522 #11526

**Comment by ValWood** [comment]
I agree, we probably do not need to GO below  "G1 cell cycle arrest "

**Comment by paolaroncaglia** [comment]
Hi Val and Midori,

Back on this at last. Summing up, I will propose obsoletion of:

GO:0072694 cell cycle arrest in response to caffeine
GO:0036226 cell cycle arrest in response to glucose starvation
on the grounds that these are not real processes
no annotations

GO:0036226 mitotic cell cycle arrest in response to glucose starvation
on the grounds that it is superfluous, as only its existing child ‘mitotic G2 cell cycle arrest in response to glucose starvation’ has been observed
no annotations

Based on Midori’s comment, I was also going to propose obsoleting

GO:0030996 mitotic cell cycle arrest in response to nitrogen starvation 
and its regulation children
on the grounds that they are superfluous, as only the more specific ‘mitotic G1 cell cycle arrest in response to nitrogen starvation’ has been observed

but GO:0030996 has 7 direct IMP annotations, all PomBase. Should they be moved to ‘mitotic G1 cell cycle arrest in response to nitrogen starvation’?

Cheers,
Paola

**Comment by mah11** [comment]
Hi Paola,

We can change those annotations easily, so yes, you can make GO:0030996 obsolete.

m

**Comment by ValWood** [comment]
Yep, your here already. We definitely need to rehouse.

**Comment by paolaroncaglia** [comment]
Thanks. Sending out obsoletion email now. Note that you'll also need to rehouse 4 IMP annotations to positive/negative regulation of cell cycle arrest in response to nitrogen starvation.

**Comment by paolaroncaglia** [comment]
Email sent.

**Comment by paolaroncaglia** [comment]
Obsoleted:

GO:0072694 cell cycle arrest in response to caffeine
GO:0036226 mitotic cell cycle arrest in response to glucose starvation
GO:0030996 mitotic cell cycle arrest in response to nitrogen starvation
GO:0010504 regulation of cell cycle arrest in response to nitrogen starvation
GO:0010505 positive regulation of cell cycle arrest in response to nitrogen starvation
GO:0010503 negative regulation of cell cycle arrest in response to nitrogen starvation

Thanks, closing now,
Paola
