### ISSUE TITLE
MP GO:0007062 sister chromatid cohesion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12015]
GO:0007062 sister chromatid cohesion
should move down to be a descendent of 'nuclear chromosome segregation'

**Comment by ValWood** [comment]
also
GO:0044768 NMS complex interaction involved in chromosome segregation (crazy term?)
GO:0051305 chromosome movement towards spindle pole
GO:0072766 centromere clustering at the nuclear envelope
GO:0051310 metaphase plate congression

probably others....

**Comment by mah11** [comment]
I'm not sure this will work -- chromosome segregation is defined as including several events that take place after the nuclear envelope breaks down in those species where, well, the nuclear envelope breaks down for mitosis. Can the process still be "nuclear" if part of it happens when there's no nucleus?

For the same reason, it looks dodgy for 'sister chromatid segregation' to be is_a 'nuclear chromosome segregation'.

**Comment by ValWood** [comment]
OK, in that case the "nuclear chromosome segregation" term will need to be rethought or the definition meaning tweaked. Nuclear chromosome segregation was created as a grouping term  for segregations  of eukaryotic 'nuclear' chromosomes as  opposed to mitochondrial or chloroplast  chromosome segregation and as a place holder to house old chromosome segregation annotations under 'cell cycle' without going back to the individual papers and migrating annotations to mitotic or meiotic. It probably isn't completely necessary  for annotation purposes as you should always know if the experiment is meiotic or mitotic.

**Comment by ValWood** [comment]
Actually I think its OK, the def refers to nuclear chromosomes, it does not say that the process needs to occur in the nucleus in its entirety?

**Comment by mah11** [comment]
> the def refers to nuclear chromosomes

Nuclear chromosome is defined as "A chromosome found in the nucleus of a eukaryotic cell". Can a chromosome be "nuclear" when there's no nucleus for it to be found in?

**Comment by ValWood** [comment]
Maybe it could be changed to "beginning with nuclear chromosomes" ?

The term isn't intended to  mean that the chromosomes are necessarily "nuclear chromosomes". It just means "segregation of the nuclear genome", so it is used in a slightly different context to "nuclear chromosome" in the CC ontology. It should be fine if the def is tweaked to reflect the intended meaning.

We could also tweak the term name, but I can't think of anything else to use, and the cell cycle workshop pondered over this for quite a while..

**Comment by mah11** [comment]
It's worth not just using "nuclear x" names, though, because so many terms elsewhere in both BP and CC that use the "CC x" naming convention *do* mean a BP that happens in the CC, or one CC that's found in another CC (e.g. cytoplasmic ribosome, mitochondrial translation). Sadly, people will neglect the nuances of the definitions, especially when looking at collections of annotations on GO term pages in browser, or in enrichment analysis or ...

I don't have a good suggestion off the top of my head but will let you know if inspiration strikes.

**Comment by ukemi** [comment]
nuclear-derived chromosome?

**Comment by ValWood** [comment]
That could work.

**Comment by ukemi** [comment]
Looking at this again, I think nuclear chromosome segregation might work. According to the definition of nuclear chromosome segregation, the process begins with the condensation of the chromosomes. At that point, they are nuclear and so I think what happens subsequently still counts as a process that is working on nuclear chromosomes. What do you think?

**Comment by ValWood** [comment]
I'm OK with that. I think its OK to say "nuclear chromosome segregation" and not mean always "nuclear chromosome", if its defined chromosome segregation of a nuclear genome.
v

**Comment by mah11** [comment]
I think it'll be OK if the definition of "nuclear chromosome" itself is expanded to make it clearer that it means "a chromosome that is part of the nuclear genome", and maybe also include "is present in the nucleus whenever the nucleus exists" or something to that effect. Might also be wise to make similar adjustments to the "nuclear chromosome segregation" def and possibly other "nuclear chromosome process" terms.

**Comment by ukemi** [comment]
Hi Val and Midori,

I made the changes to the defs that Midori suggested and tried to find all the terms that needed to be moved to be part of the new nuclear chromosome segregation term. Hopefully I got them all.

-David
