### ISSUE TITLE
 rename ribonucleoside-diphosphate reductase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12024]
can we name
ribonucleoside-diphosphate reductase activity, thioredoxin disulfide as acceptor
back to 
ribonucleoside-diphosphate reductase activity
because that is what everyone calls it... (well they usually call it ribonuleotide reductase, but this works)

I ask because I want to request the term
ribonucleoside-diphosphate reductase inhibitor  activity
(or even better 
and I want it to match the term name it refers to.

It also matches the GO complex name
GO:0005971 - ribonucleoside-diphosphate reductase complex

If they are not equivalent (currently these are *exact* synonyms), some more complicated solution will be required....

**Comment by deustp01** [comment]
My recollection is that ribonucleoside-diphosphate reductase comes in two forms, one that uses thioredoxin and one that uses glutaredoxin, and that there are subtle functional differences between the forms. There are also cases where the experimental data for ribonucleoside-diphosphate reductase do not allow identification of the acceptor under physiological conditions, so perhaps the best fix here would be for the term Val wants to have two is-a children, one for each acceptor. Indeed, a recent review by P Reichard, the preeminent authority, makes a case for three sub-types (only two in mammals, so I'm vague on this): PMID: 16756507.

**Comment by ukemi** [comment]
Yes, and we have both of those activities, GO:0004748 and GO:0036175. Since they have different acceptors, they fall into different subtrees of the graph. I could make a parent term, but I would think that if you know the enzyme activity, then you would know which type of acceptor was being used. So I'm not sure it would do much good to make a common parent.

-D

**Comment by ValWood** [comment]
The term I used used to be called  plain "ribonucleoside-diphosphate reductase activity", so it was made more specific by adding the thioredoxin part. Pombe RNR activity is ISS from SGD. I looked at the 2 S.c papers and I couldn't see any info in the 2 papers used for the MF annotaiton to  assign which acceptor is used... so maybe we do need the parent term?

Also, there is a  single complex term
ribonucleoside-diphosphate reductase complex
Definition	An enzyme complex composed of 2-4 or more subunits, which usually contains nonheme iron and requires ATP for catalysis. Catalyzes the for formation of 2'-deoxyribonucleoside diphosphate from ribonucleoside diphosphate, using either thioredoxin disulfide or glutaredoxin disulfide as an acceptor.

V

**Comment by ukemi** [comment]
Added:

 [Term]
+id: GO:0061731
+name: ribonucleoside-diphosphate reductase activity
+namespace: molecular_function
+def: "Catalysis of the formation of 2'-deoxyribonucleoside diphosphate from ribonucleoside diphosphate, using either thioredoxin disulfide or glutaredoxin disulfide as an acceptor." [GOC:dph, GOC:vw, PMID:16756507]
+is_a: GO:0016728 ! oxidoreductase activity, acting on CH or CH2 groups, disulfide as acceptor
+created_by: dph
+creation_date: 2015-08-24T07:25:59Z

Made two existing terms children of this one and moved the capable_of relation of the complex to this new term.

**Comment by mah11** [comment]
Val said:
> The term I used used to be called plain "ribonucleoside-diphosphate reductase activity", so it was made more specific by adding the thioredoxin part.

The GO:0004748 definition has always specified thioredoxin, so the term's specificity has not changed. The name change merely reflected the definition more precisely.

**Comment by ValWood** [comment]
OK, I was just surprised to see thioredoxin in the term name, as I knew it hadn't always been there. I will annotate pombe RNA (cdc22 and suc22) to the new term without the acceptor, as I can't see any info immediately which adds this specifity for pombe or cerevisiae. Unless anyone knows?
I'll ask Jacky H if its known too.

**Comment by ukemi** [comment]
In any case, I don't think the new term hurts anything.

**Comment by pgaudet** [comment]
Hi David, Val,

In fact there are three types of ribonucleotide reductases: 
https://en.wikipedia.org/wiki/Ribonucleotide_reductase#Function

Each organism usually has a single one (Dicty has two different types, as far as I remember, but I think it's rather an exception). 

Is the type of acceptor within the scope of GO ? This seems very mechanistic and has no impact on the biologically-relevant aspects of RNR, ie, the substrate specificity (it acts on all ribonucleotides with similar efficiency), ad its regulation. 

I would be in favor or keeping all these in a single term. There are no annotations to GO:0036175. 

Thanks, 
Pascale

**Comment by ValWood** [comment]
I'd also be happy for a single term. This would match the  GO complex which specifies using either thioredoxin disulfide or glutaredoxin disulfide as an acceptor. and would solve all my problems ;)

This would have  the added bonus that all existing annotations would be correct (I'm sure that most people will have annotated arbitrarily to this term for either acceptor when it  did not have the additional clause  about 'thioredoxin' in the term name....)

**Comment by ValWood** [comment]
For interest, Jacky Hayles asked around the cell cycle lab  about the  acceptor for pombe RNR and nobody knows....I suspect the same for most species...

**Comment by ukemi** [comment]
So we could either leave the structure as is: a parent term which is agnostic wrt glut/thio and leave the two children as is

or

I could merge the two specific children into the parent. I don't see how it hurts anything to leave the structure as it is, but I will take advice on this ticket.

**Comment by deustp01** [comment]
Reichard (mentioned before, excerpted below) distinguishes three classes based on subunit structure and the role of oxygen in the reaction, both features that are within scope for GO:

Annu Rev Biochem. 2006;75:681-706.
Ribonucleotide reductases.
Nordlund P1, Reichard P.

Ribonucleotide reductases (RNRs) transform RNA building blocks to DNA building blocks by catalyzing the substitution of the 2′OH-group of a ribonucleotide with a hydrogen by a mechanism involving protein radicals. Three classes of RNRs employ different mechanisms for the generation of the protein radical. Recent structural studies of members from each class have led to a deeper understanding of their catalytic mechanism and allosteric regulation by nucleoside triphosphates. The main emphasis of this review is on regulation of RNR at the molecular and cellular level. Conformational transitions induced by nucleotide binding determine the regulation of substrate specificity. An intricate interplay between gene activation, enzyme inhibition, and protein degradation regulates, together with the allosteric effects, enzyme activity and provides the appropriate amount of deoxynucleotides for DNA replication and repair. In spite of large differences in the amino acid sequences, basic structural features are remarkably similar and suggest a common evolutionary origin for the three classes.

INTRODUCTION
In all cellular organisms, ribonucleotide reductases (RNRs) synthesize the four deoxyribonucleoside triphosphates (dNTPs) required for DNA replication and repair by substitution of the 2′-OH of a ribonucleoside di- or triphosphate by a hydrogen atom. A common feature of all reductases is their ability to provide an appropriate balance of the four DNA building blocks. A unique allosteric regulation of their substrate specificity makes this possible. All RNRs share a common basic catalytic mechanism involving the activation of the ribonucleotide by abstraction of the 3′-hydrogen atom of the ribose by a transient thiyl radical of the enzyme.

A general overview of the occurrence, catalytic function, regulation, and evolution of RNRs is found in a review from one of us in the Annual Review of Biochemistry of 1998 (1). Since then, many reviews have appeared, usually related to specific aspects, such as radical mechanisms in general (2–5), mechanism of class I (6), class II (7) or class III (8–11) enzymes, allosteric regulation (12), physiology (13), and evolution (14–17). Major advances in recent years concern the structure and regulation of RNRs. These have led to a better understanding of the structural basis for the allosteric transitions and the interplay between allosteric and genetic regulation. The emphasis of this review is on regulation.

A SHORT CLASSIFICATION OF RNRs
RNRs can be grouped into three different classes largely on the basis of their interaction with oxygen and the way in which they generate their thiyl radical. A more detailed description of the three classes is found in Reference 1.
Class I RNRs
Class I reductases contain two subgroups (Ia, NrdAB, and Ib, NrdEF) with slightly different primary structures. Both subgroups contain two nonidentical dimeric subunits (R1 and R2) and require oxygen for the generation of a stable tyrosyl radical by a Fe-O-Fe center in the smaller R2 subunit (NrdB or NrdF). During catalysis, the radical is continuously shuttled to a cysteine of the larger R1 subunit (NrdA or NrdE) and there generates a thiyl radical required for activation of the substrate. R1 contains both the catalytic site for the reduction of the ribotide and the allosteric sites for its regulation. The required electrons are provided from redox-active cysteines of small proteins, thioredoxin or glutaredoxin for class Ia and NrdH (18) for class Ib. Class Ib enzymes also depend on an additional protein (NrdI) of unknown function (19). Originally, it was thought that a major distinction between the two subgroups was the presence in Ia of an amino-terminal ATP cone (20), which is absent from Ib, codifying the allosteric activity site of the enzyme. However, some microbial Ia enzymes also lack an ATP cone. Class Ib is better identified from the presence of nrdI and nrdH in the genome together with the nrdEF genes.
Class II RNRs
Class II RNRs are indifferent to oxygen, neither requiring it nor inhibited by it. They contain a single subunit (NrdJ) and are isolated either as monomers or as dimers. They generate their thiyl radical with the aid of adenosylcobalamin, probably via formation of a deoxyadenosyl radical. Thus adenosylcobalamin fulfills the function of R2 as a radical generator. Class II enzymes use thioredoxin or glutaredoxin as electron donors. Their allosteric regulation is similar to that of class Ib, and many, but not all, lack an ATP cone.
Class III RNRs

Class III reductases are anaerobic enzymes that are inactivated by oxygen. Two dimeric proteins are required for activity, one large catalytic protein (NrdD) and one small (NrdG), catalyzing the activation of NrdD. The activase NrdG contains a redox-active [4Fe-4S] center, which together with S-adenosyl methionine and reduced flavodoxin generate a stable but oxygen-sensitive glycyl radical at the C terminus of NrdD. This radical is the counterpart of the stable tyrosyl radical of class I and continuously generates the thiyl radical required for the activation of the substrate. Once the glycyl radical is formed, NrdD alone catalyzes the reaction. This differs from class I enzymes that require R2 continuously for radical generation. Furthermore, class III enzymes use formate as electron donor. An earlier theory postulated a class IV enzyme, with a manganese center (21) instead of a dinuclear iron center, but it was shown to be an artifact (22).

**Comment by ValWood** [comment]
Hi David,
The synonyms are now confusing. Could you  migrate all of the 'broad' and some fo the related (RNR) synonyms to  be exact or related synonyms of the new parent?
thanks
Val

**Comment by ukemi** [comment]
I moved the broad and related synonyms. I made most of them related to the generic term since they are not precisely defined.
