### ISSUE TITLE
Consider removing REACTOME xrefs from the ontology 

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12042]
REACTOME xrefs appear to be way overspecified to me, as if every child term is being xreffed to a term like GO:0004713 ! protein tyrosine kinase activity, along with multiple species-specific annotations. This strikes me as different in intent from xrefs to things like the Enzyme Commission system.

For GONUTS, listing these is overwhelming the utility of the term pages, so I am going to not show them. But this made me wonder if they should even be in the ontology.

**Comment by cmungall** [comment]
I agree completely. I'm not sure how we ended up here. We originally had xrefs to a 'generic' reactome ID, but were later told these weren't stable(?). So we replaced with one per species. This is correct if we interpret the xref as an inverse subClassOf. And it does reflect the content of reactome. But I'm not sure about the utility. Can we not instead just link to the human one?

We need to also document the provenance of these, and if they are updated or if it was a one-time import

cc @deustp01

**Comment by deustp01** [comment]
What Jim and Chris are saying sounds plausible, but I'm also lost. Could someone point me to some specific inappropriate xrefs so I can see better exactly how we are abusing them? Also, there is a major qualitative difference between our manual annotation of GO terms to human proteins and our computationally inferred, orthology-based annotations to non-human proteins, so examples of both would be useful because I'm guessing we'll want different fixes (e.g., discard all xrefs involving non-human proteins; preserve at least some involving human ones).
Thanks.
Peter

**Comment by cmungall** [comment]
```
[Term]
id: GO:0016301
name: kinase activity
namespace: molecular_function
def: "Catalysis of the transfer of a phosphate group, usually from ATP, to a substrate molecule." [ISBN:0198506732]
comment: Note that this term encompasses all activities that transfer a single phosphate group; although ATP is by far the most common phosphate donor, reactions using other phosphate donors are included in this term.
subset: goslim_chembl
subset: goslim_generic
subset: goslim_metagenomics
subset: goslim_plant
subset: goslim_yeast
subset: gosubset_prok
synonym: "phosphokinase activity" EXACT []
xref: Reactome:REACT_100073 "Activation of S6K1, Schizosaccharomyces pombe"
...
900 LINES LATER
...
xref: Reactome:REACT_99929 "Phosphorylation of beta-catenin at Ser45 by CK1 alpha, Gallus gallus"
xref: Reactome:REACT_99966 "Intermolecular autophosphorylation of ATM within dimeric ATM complexes, Schizosaccharomyces pombe"
xref: Reactome:REACT_9997 "Phosphorylation of Cx43 by c-src, Homo sapiens"
```

Just to be clear, it's not that Reactome are doing anything wrong per se, beyond what everyone else does, which is use "cross-reference" to use one of multiple different things.

In this case, it's true that all those reactome reactions represent *subclasses* or *instances* of the GO class. This conflicts with assumptions that xref means 'something close to equivalent'.

**Comment by tberardini** [comment]
Assigning to @cmungall because if something is going to be done in the ontology, it will be done programmatically and not one-by-one by a curator.

**Comment by ukemi** [comment]
For the biochemical pathways on which Peter and I have been working, I have been adding the stable reactome ID for the human pathway as a cross-reference (see 'canonical glycolysis for example). In those cases, the GO pathway and reactome pathway are the 'best-matched' pairs that we can find, but are not necessarily exactly the same with respect to reactions etc. However, I think from any biochemist's point of view it is clear that overall, we are talking about the same thing and Peter and I work hard to make sure the representations are compatible.  It would be a shame to get rid of them because I think they are very helpful. Maybe we restrict the cross-references just to the reactome human data since most of the other species representations are based on that (Peter, please correct me if I am mistaken). From there, users can link to reactome and see the other taxa. Just a thought....

**Comment by deustp01** [comment]
"Restrict to human" works really well for me, especially as the human assertions (as discussed on Monday) are backed by TAS evidence at least, while almost all assertions about other taxa are based on at least two steps of computational inference (would that be IE(IEA)?).
So an xref between Reactome glycolysis pathway (human) and GO canonical glycolysis biological process makes good sense, and indeed a user who has a use for IE(IEA) evidence can navigate onwards from the Reactome human landing page.
How do the xrefs of Reactome reaction instances to GO molecular function instances (as in Chris's kinase example) arise? As for pathway - process links, these could be reasonable / useful when derived from our human annotations but not when derived from our model organism inferences, but I expect we'd also want them to be finer grained, e.g., between a Reactome reaction instance and a specific kind of kinase activity.

**Comment by cmungall** [comment]
So it looks like the xrefs are in two forms:

 1. `xref: Reactome:REACT_116010 "Sulfide oxidation to sulfate, Homo sapiens"`
 2. `xref: Reactome:R-HSA-70171 "Glycolysis, Homo sapiens"` 

David manually added the second. I believe many of the first form were imported from Reactome automatically at some point (remember we have two sources: xrefs made by Reactome curators pointing to GO, xrefs made by GO editors pointing to reactome)

We certainly shouldn't get rid of any manual ones David made. But presumably anything that came from a mass reactome import could be ditched and is probably already stale. But we'd want to be sure we didn't get rid of any curator generated ones.

Moving forward, I would like to move away from xrefs, and instead have a manually curated OWL bridge file with SubClassOf axioms

**Comment by jimhu-tamu** [comment]
Restrict to human should help - are there cases where that would discard reactions that are in Reactome but not in humans (do you have any?).

But the kinase example has other issues.

**Comment by ukemi** [comment]
The subclassof idea is very interesting. But wouldn't this mean that the Reactome pathway would be under the constraints of the GO logical definition? It might make the mappings more rigorous and make me be a bit more formal about the relationships. For example, I recently modeled 'mitochondrial acetyl-CoA biosynthetic process from pyruvate' and gave it a cross reference to the two necessary reactions from reactome, the transport into the mitochondrion and the decarboxylation of pyruvate to acetyl-CoA (I meant to bounce this off of Peter). In this case, the cross refs to Reactome are not subclasses, which leads me to believe that I probably shouldn't have done it this way. But the reactome pathway of pyruvate metabolism encompasses much more than this. I needed the subset of the Reactome view because at some point pyruvate -> acetyl-CoA will be linked up with glycolysis, the TCA cycle, the electron transport chain and oxidative phosphorylation to describe aerobic cellular respiration from carbohydrates. Note that for the generic process, I will not use the mitochondrial subtype. In the generic process, the only thing required is the decarboxylation of pyruvate to acetyl-CoA since some beasts won't do this in the mitochondrion. But at the end of the day what ends up happening is that although all of the steps of the pathway can be aligned in GO and Reactome, we have chosen to name those as processes in GO and therefore there isn't a specified pathway in reactome that exactly aligns with the process in GO. Peter and I noted the same thing in glycolytic pathways using alternative starting points than glucose. If that pathway is used in humans, we can always trace what I have represented in GO process in Reactome, but it isn't necessarily sliced and diced in the same way because GO has to account for more than just human in its heirarchy. I hope this makes sense. 

One out of the box idea would be to make the links between the GO molecular functions and the Reactome reactions, then use the logical definitions of the GO processes to render the GO view on the human Reactome pathway. That would be pretty cool and it would be a great way to cross-check the work. It is essentially what Peter and I have been doing by hand. I'm still not convinced that subclassof would be correct though. In Reactome the identifier is a reaction whereas the GO function term is the catalysis of that reaction enabled by a gene product. This might come back and bite us in the long run. I love the idea of making the relationships between the two resources more OWL-friendly, but we need to think about exactly what we are saying.

**Comment by cmungall** [comment]
You're right, a strict logical definition may be the wrong approach here. And may ultimately be unnecessary, if we use methods like the ones you suggest. Not only could we use the top-down all-some class level axiomatization in GO, but also a bottom-up abstraction from the LEGO models. Automatic overlay and boundary checking should fall out naturally.

But in the interim, let's think about the best way to manage the xrefs coming in each direction. Scratch my bridge idea for now

**Comment by ukemi** [comment]
PS. It seems to me the issue with the kinase example is that somehow every kinase reaction in Reactome got an xref to the generic function (if it couldn't be placed elsewhere in GO?). Although correct, it is very unsatisfying and doesn't have much information value. Since Reactome isn't GO, they don't have a generic kinase reaction (at least that I can find and I can't see why they would) to collect all these and therefore have a single one to one mapping. But there is utility in using GO to find all the kinase reactions in Reactome.  It just seems that creating a ton of xrefs is not the best way to do it.  We wouldn't generate cross-refs for all Reactome reactions to GO molecular function, so how do we define an intelligent cut off and still get what we want.

**Comment by cmungall** [comment]
Right, but I don't think Reactome should stop xreffing those kinases. A generic kinase makes no sense in Reactome. They need a way of saying "this is a kinase reacion" (OK, we should be able to infer this based on inputs and outputs, but still useful as a checksum). So their xrefs serve a different purpose than the reciprocal ones we make in GO. For reactions, it's classification, and for processes it's a somewhat near equivalence (sensu species and some other factors) type assertion.

On the GO side, we're mostly interested in using xrefs for keeping near-equivalence or 1-1-ish cognate type links, so we want to leverage work done by reactome curators on processes but have a different approach for ones like the kinases.

(rushing this before going to work sorry if it's not clear...)

**Comment by ukemi** [comment]
Reactome xrefs are now handles automatically. I believe this ticket is out of date.
