### ISSUE TITLE
response to alarm substance

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#12077]
Def: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an alarm substance.  Alarm substance is a molecule or mixture of molecules released when a fish is injured or killed which elicit a stereotyped fear behavior in fish.
Synonym: response to schreckstoff

is_a GO:0009607  	response to biotic stimulus

Note: The mixture chemicals comprising alarm substance is usually called schreckstoff.  Chebi has named a specific chemical "schreckstoff" but references the paper that says the chondrotin sulfates act as  schreckstoff.  A better name for the chebi term  CHEBI:72574 would be hypoxanthine 3-N-oxide.  

Terms that are children of response to alarm substance were submitted using term genie
response to chondroitin 4'-sulfate GO:TEMP-chemicalresponseto00
response to chondroitin 6'-sulfate GO:TEMP-chemicalresponseto10
response to schreckstoff (forgot to copy the temp ID) 

@sabrinatoro @chemhack

**Comment by cerivs** [comment]
Probably should request new regulation term too.
Term: regulation of response to alarm substance
Def:Any process that modulates the frequency, rate or extent of a response to alarm substance Response to  alarm substance  is a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a stimulus. 

is_a regulation of response to stimulus
regulates response to alarm substance

**Comment by dosumis** [comment]
"Alarm substance" = substance that evokes alarm response (where an alarm response is presumably a behavior - I'm not sure you want to get in to modeling internal mental states.)

=> Expanded definition:
response to substance that evokes alarm response

Perhaps something like this would be better:

detection of chemical stimulus involved in alarm response
OR
activation of alarm response by chemical signal

**Comment by cerivs** [comment]
Yes the :"alarm substance" produces a behavioral response.  I like the change suggested from "fear response"  to alarm response.  
 Some of the chemical  components that make up "alarm substance" are known, the term genie terms listed, and there may be others.  In fish literature the "alarm substance" is also called "schreckstoff" literally, scary stuff.

There are several additional terms that could be made as David suggested.  The most basic is the one I requested, some response to the substance.  This does imply there is detention of the substance, the  signaling triggered by the substance and the behaviors elicited by the signaling. I am not sure how GO models these for other biologically relevant response to chemicals but I would not object to the related terms being added.

Also this brings up the whole subject of organism behavior and should it be in GO or a separate ontology.

**Comment by paolaroncaglia** [comment]
Hi,

There’s a lot going on in this ticket :-) here are my thoughts:

response to chondroitin 4'-sulfate/chondroitin 6'-sulfate/schreckstoff are responses to chemical compounds. You suggested ‘response to alarm substance’ as a parent for all 3. If we are looking at this parent from a chemical point of view, then no need to add it - the reasoner will give the specific children the most appropriate parentage. If we look at CHEBI:72574 - schreckstoff, this is given the biological roles ‘metabolite’ and ‘alarm pheromone’. If we are confident enough that CHEBI:72574 is only ever released from fish in a stressful situation, we could add two parents to ‘response to schreckstoff’: ‘response to pheromone’ and ‘multicellular organismal response to stress’. But we wouldn’t want to do the same for the chondroitin terms.
Or we could create a ‘response to alarm pheromone’ and link it to the CHEBI role ‘alarm pheromone’.
Or you could annotate to all appropriate terms.
I like David's suggestions, just trying to figure out if we can align to existing structures (see below for the behavioural bit).

Note that the TG terms were never submitted I’m afraid. Maybe something went wrong with TG. They’re not in the ontology nor in the TG queue. 

About changing the name of CHEBI:72574 - schreckstoff: this should go on the CHEBI tracker (https://sourceforge.net/p/chebi/curator-requests/) or, maybe better, emailed to chebi-curator@ebi.ac.uk. Ceri let me know if you’d like me to do it or if you’re already in touch with them.

For the behavioural bit: note we have ‘fear response’ and ’general adaptation syndrome’ in GO which may be useful in this case.
In fact I’m wondering if your ‘response to alarm substance’ should indeed be one of the parts of ’general adaptation syndrome’ - does the 'pituitary-endocrine' clause apply Ceri?: “General adaptation syndrome is the set of changes in various organ systems of the body, especially the pituitary-endocrine system, in response to a wide range of strong external stimuli, both physiological and psychological. It is described as having three stages: *alarm reaction, where the body detects the external stimulus*; adaptation, where the body engages defensive countermeasures against the stressor; and exhaustion, where the body begins to run out of defenses.”

I thought we resolved that further behavioural modelling would be in scope for NBO rather than GO. Chris? @cmungall 

Regulation terms (and/or further ‘response to chemical’ terms) may be requested/added once we resolve the points above.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @cerivs ,

Looks like there was no follow-up to this request. Could you please go through my latest comment above, and let me know if you'd still like to proceed and how, or if I may close this ticket instead?

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
Closing, as there was no follow-up.
