### ISSUE TITLE
GO:0004972 NMDA glutamate receptor activity - new parent

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12089]
Could 
GO:0004972 NMDA glutamate receptor activity
be
is_a GO:0005234 extracellular-glutamate-gated ion channel activity?

In fact, they may even be equivalent...
Currently they are in parallel branches of GO:0005230 extracellular ligand-gated ion channel activity.

It should also be
is_a  GO:0022843 voltage-gated cation channel activity (mainly Ca2+, but also Mg2+)

Birgit

**Comment by dosumis** [comment]
GO:0004972 NMDA glutamate receptor activity
be
is_a GO:0005234 extracellular-glutamate-gated ion channel activity?

Yep.  But they are not equivalent, as there at least to other types apart from NMDA with quite different activities.

These things are pretty complicated: 
Also lets Na+ and K+ out.  Mg2+ is an inhibitor (part of the mechanism of voltage gating).  Activation happens when Gly and hyperpolarisation co-incide.

I've actually been working on this as an example of a compound process.  Here're my notes:
https://docs.google.com/document/d/1tBhuA_-xgbeqehZD9NdZWbHy8ruM9YFnJQ2Qpcw8lmQ/edit#

**Comment by bmeldal** [comment]
That's coincidence! NMDARs are my next family! I guess you are looking at these as part of the synapse project.

You are right, I forgot about the AMPA and kainate Rs. So I guess it's actually their common parent,
GO:0004970 ionotropic glutamate receptor activity
that should be
is_a GO:0005234 extracellular-glutamate-gated ion channel activity

And why has
GO:0005234 extracellular-glutamate-gated ion channel activity
not parent
is_a  GO:0008066 glutamate receptor activity?
It is parent to 
GO:0004970 ionotropic glutamate receptor activity,
the parent of 
GO:0004972 NMDA glutamate receptor activity (and AMPA & kainate glutamate receptor activity)

I think it links to the ticket (number ?) discussion whether a ligand-gated channel is a receptor as the community/literature regards them as receptors. I think you where going to add some axioms, then the reasoner should pick that up, right?

Fascinating biology (or rather - biophysics)! I never did anything neurological and I'm learning as I'm going along. Membrane potentials are still a somewhat black box.

**Comment by dosumis** [comment]
Fixed this up some time ago as part of general work on ionotropic ion channels.  

![image](https://cloud.githubusercontent.com/assets/112839/21453309/9a517240-c905-11e6-8efa-73176ae8f8ee.png)

![Uploading image.png…]()



(Note - likely to be refined further & modeled slightly differently as part of MF refactoring in 2017)
