### ISSUE TITLE
questionable complex grouping term

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12116]
This seems an odd grouping term, It seems to be mirroring the function ontology to group *Any* complex with transferase activity which would be *a lot* of different complexes!

transferase complex, transferring phosphorus-containing groups

we already have 110 annotation to this term from completely unrelated complexes....

**Comment by ValWood** [comment]
similarly 'membrane protein complex' has 230 annotations (this one  is probably Ok as at least it is  classified  as a component.....)

**Comment by bmeldal** [comment]
It mirrors the activity GO:0016772 transferase activity, transferring phosphorus-containing groups and has capable_of relationship to it. It has been created as a grouping term to potentially strip all leaf complex nodes. I have done this a lot in preparation of the pruning exercise we are now discussing. 
@dosumis, is this going to far/unspecific? I used the template for the most specific activity I could find for the complex.

**Comment by dosumis** [comment]
Nothing logically wrong with it.  Whether it is too abstract is down to whether it will be too confusing to users - i.e. a judgement call, rather than something we can write rigorous rules for.

I think 'membrane protein complex' is clear and useful.  This term is less so and feels to me to be on the cusp of what is acceptable: A general term for complexes with transferase activity would be too far; kinase complex is probably OK.

**Comment by ValWood** [comment]
OK. I agree membrane protein complex is useful

transferase complex, transferring phosphorus-containing groups feels a bit too abstract to me .....It feels it would perhaps be better to have some CC-MF link at the leaf node at the level of the individual complex rather than making CC grouping terms for every MF?

**Comment by dosumis** [comment]
> It feels it would perhaps be better to have some CC-MF link at the leaf node at the level of the individual complex rather than making CC grouping terms for every MF?

We have these too.  They are used to automatically classify under general classes like this.

**Comment by bmeldal** [comment]
>It feels it would perhaps be better to have some CC-MF link at the leaf node at the level of the >individual complex rather than making CC grouping terms for every MF?

But the leaf notes might be going... :(

**Comment by ValWood** [comment]
Maybe my problem here is the general nature of the grouping term.

Perhaps the  functional grouping terms should be as specfic as possible
"protein kinase complex" makes more sense to me as a grouping term than 
"transferase complex, transferring phosphorus-containing groups" 

I'm guessing that this would make more sense to the average user.

**Comment by ValWood** [comment]
Another issue with functional grouping is that it needs to be  applied consistently For instance, there are many , many protein kinase complexes, and more transferase complexes  that are not currently housed under this term
In 2 minutes I spotted:
chromosome passenger complex
nuclear pre-replicative complex
holo TFIIH complex
bub1-bub3 complex
(all protein complexes with protein kinase activity)

The complications from implement might outweigh the benefits...... its not good to add grouping terms without collecting all existing child terms as descendants when they are added.....

**Comment by dosumis** [comment]
I agree. But we're a long way down this route to easily turn back. In the current model, all of this is based on auto-classification via capable_of relationships to function terms. In the proposed new model, a GAF inference job will add inferred annotations to terms like this based on manual MF annotations to complexes.

**Comment by dosumis** [comment]
Hi Val, 

I think the way forward on these might be to collect a list of cases like this.  The protein complex WG can discuss appropriate levels of generalisation for functional/location based complex grouping terms.  Need some general guidance and perhaps a mechanism for flagging 'too general' classes.  Otherwise this will be an ongoing issue and a time-sink for everyone involved.

We could start a list on the [PC-WG gihtub site](https://github.com/geneontology/protein-complex-refactor).

- David

**Comment by dosumis** [comment]
This issue was moved to geneontology/protein-complex-refactor#2
