### ISSUE TITLE
New GO Term: histone H3-K4 monomethylation

### ISSUE THREAD

**Issue by kaylamichbrown** [geneontology/go-ontology#12126]
Hello! I'm in the Texas A&M CACAO Class and I think a GO term needs to be made for histone H3-K4 monomethylation. There are child terms histone H3-K4 dimethylation and histone H3-K4 trimethylation for histone H3-K4 methylation, so in order to have a more specific GO term, a histone H3-K4 monomethylation term should be made.

**Comment by jimhu-tamu** [comment]
The terms involved are:
GO:0051568 ! histone H3-K4 methylation
GO:0044648 ! histone H3-K4 dimethylation and 
GO:0080182 ! histone H3-K4 trimethylation

The paper shows that the protein Kayla is annotating puts on all three, but this would not be clear from using GO:0051568 ! histone H3-K4 methylation alone.

**Comment by paolaroncaglia** [comment]
Hi Kayla and Jim,

Thanks. Your request makes sense, could you please provide the PMID of the paper that Kayla is annotating? 

Notes:
- we do have 'histone H4-K20 monomethylation' ("The modification of histone H4 by addition of *one* methyl group to lysine at position 20 of the histone.") so that's a precedent
- I'm thinking if the request is accepted, we should make all 'methylation' definitions less ambiguous: e.g. GO:0051568 ! histone H3-K4 methylation currently says "The modification of histone H3 by addition of *a* methyl group to lysine at position 4 of the histone."

Paola

**Comment by jimhu-tamu** [comment]
PMID:26320581

**Comment by jimhu-tamu** [comment]
Hi Paola, any update on this?

**Comment by paolaroncaglia** [comment]
Hi Jim,

I'll do this tomorrow, sorry but I was swamped last week, on leave Monday and Tuesday due to school break, and teaching all day today. Speak soon, thanks,

Paola

**Comment by paolaroncaglia** [comment]
Hi Kayla and Jim,

I added the term you need:

[Term]
id: GO:0097692
name: histone H3-K4 monomethylation
namespace: biological_process
def: "The modification of histone H3 by addition of one methyl group to lysine at position 4 of the histone." [GOC:jh2, PMID:26320581]
is_a: GO:0051568 ! histone H3-K4 methylation

I also edited the definitions of some existing 'histone x-y methylation' terms to make them less ambiguous when they had mono-, di- and/or trymethylation children
(e.g. from "The modification of histone H3 by addition of a methyl group to lysine at position 4 of the histone." to "The modification of histone H3 by addition of one or more methyl groups to lysine at position 4 of the histone.”).

Closing now. Thanks,
Paola
