### ISSUE TITLE
NTR:4 terms for NLRP1 inflammasome

### ISSUE THREAD

**Issue by aestreicher** [geneontology/go-ontology#12134]
Dear GO editors,

On the basis of terms existing for NLRP3 inflammasome, is it possible to create new terms for NLRP1 inflammasome?

1. NLRP1 inflammasome complex assembly (Process), definition: The aggregation, arrangement and bonding together of a set of components to form the NLRP1 inflammasome complex, occurring at the level of an individual cell. (analogous to GO:0044546)
2. regulation of NLRP1 inflammasome complex assembly (Process), definition: The aggregation, arrangement and bonding together of a set of components to form the NLRP1 inflammasome complex, occurring at the level of an individual cell. (analogous to GO:1900225)
3. negative regulation of NLRP1 inflammasome complex assembly (Process), definition: Any process that stops, prevents or reduces the frequency, rate or extent of NLRP1 inflammasome complex assembly. (analogous to GO:1900226)
4. positive regulation of NLRP1 inflammasome complex assembly (Process), definition: Any process that activates or increases the frequency, rate or extent of NLRP1 inflammasome complex assembly. (analogous to GO:1900227)

Best regards.

Anne

**Comment by paolaroncaglia** [comment]
Dear Anne,

Yes, we can add the terms you need. This could be done using the TermGenie templates in 2 steps:
1) add 'NLRP1 inflammasome complex assembly' using the 'cc_assembly_disassembly' template;
2) then adding regulation terms using the 'regulation: biological_process' template.
Does anyone in your group have a TermGenie account so you may add the terms yourself?
Otherwise let me know and I'll add them for you.
In either case, a PMID or other reference is needed.

Thanks,
Paola

**Comment by aestreicher** [comment]
Hi Paola,

I think I can manage and Lionel Breuza who does it on a regular basis in 
our group will help me if I have questions. If I encounter problems, 
I'll get back to you. Thanks for your help.

Anne

**Comment by paolaroncaglia** [comment]
Hi Anne,

I see that 'NLRP1 inflammasome complex assembly' is now in the ontology. The regulation terms, if needed, can also be requested via TermGenie. Therefore I'm going to close this ticket now, but if you have any problem, you'll let us know.

Thanks!

Paola
