### ISSUE TITLE
Determine if redundancy stripping happening in assert-report

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12146]

**Comment by dosumis** [comment]
The case discussed in the editor's meeting was for a protein complex defined by function and composition.  In these cases, only subclassing axioms are present.  

SubClassOf: protein complex
SubClassOf: capable_of some <enzyme activity>
SubClassOf 'catalytic complex' # is_inferred=true

The genus in these cases often ends up being deleted, turning the inferred classification into an ETINE.  I haven't been able to find a case where the genus is being deleted as part of the inference job.  But there are quite a few cases where it has been removed in the master file.  Many of these may date from when we had overly vigorous redundancy stripping running against the master file.

Here's an example:

label "H-gal-GP complex"^^string
'capable of' some 'aspartic-type peptidase activity'
'capable of' some 'metallopeptidase activity'
'catalytic complex'
'membrane protein complex'
'part of' some membrane
EXISTS, TAGGED-INFERRED, NOT-ENTAILED	GO:1990850 'H-gal-GP complex' GO:0098796 'membrane protein complex'	 ! Direct SuperClasses for GO:1990850: owl:Thing
EXISTS, TAGGED-INFERRED, NOT-ENTAILED	GO:1990850 'H-gal-GP complex' GO:1902494 'catalytic complex'	 ! Direct SuperClasses for GO:1990850: owl:Thing

Oddly, looking at the [QuickGO change log](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1990850#term=history) - I can't see where it had the genus and when it was lost.


Note - some othe proportion of protein complex classifications that are no longer entailed are due to reclassification under macromolecular complex.
