### ISSUE TITLE
Lack of inferences to GO:0098588 'bounding membrane of organelle'

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12145]
In latest
https://build.berkeleybop.org/view/GO/job/build-go-assert-inferences-report/lastSuccessfulBuild/artifact/assert-report.txt/*view*/

We see ETINEs like

EXISTS, TAGGED-INFERRED, NOT-ENTAILED	GO:0060170 'ciliary membrane' GO:0098588 'bounding membrane of organelle'	 ! Direct SuperClasses for GO:0060170: GO:0031090 'organelle membrane' GO:0044441 'ciliary part' GO:0031253 'cell projection membrane'

**Comment by dosumis** [comment]
'ciliary membrane' is fixed (once I commit my branch edits).

The others are a little trickier. 

EXISTS, TAGGED-INFERRED, NOT-ENTAILED	GO:0000139 'Golgi membrane' GO:0098588 'bounding membrane of organelle'	 ! Direct SuperClasses for GO:0000139: GO:0031090 'organelle membrane' GO:0044431 'Golgi apparatus part'
EXISTS, TAGGED-INFERRED, NOT-ENTAILED	GO:0005789 'endoplasmic reticulum membrane' GO:0098588 'bounding membrane of organelle'	 ! Direct SuperClasses for GO:0005789: GO:0044425 'membrane part' GO:0031090 'organelle membrane' GO:0044432 'endoplasmic reticulum

The problem is we need the membranes of various ER and Golgi subcompartments to be classified as Golgi membrane/ER membrane.  Maybe we should consider using partonomy in these cases, but for now I'll just switch these two SubClassOf axioms to manual.
