### ISSUE TITLE
NTR - neuronal action potential intiation / back propagation

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12143]
(Pasted from mail from @vhinard )

I'd like to annotate voltage-gated sodium channels to the following terms, that do not "exist" in GO (see definition at the end):
neuronal action potential initiation
neuronal action potential backpropagation
References: PMID 9061867

I suggest that these 2 terms would be in parallel with the GO:0019227 "neuronal action potential propagation", because there are, all of 3, processes that describe the "life" in space and time of the neuronal action potential and because there are the consequence of different types of ionic channels.

So, before to go further, I would like to know what you would suggest because you described "membrane depolarization during action potential" with the exact synonym "generation of action potential".
This is for me 2 separate concepts. The first being a part of the action potential (like repolarization is a part of it); and the second being the first step of the "life" of the action potential (followed by propagation or backpropagation).
What do you think about the idea to make a distinction between "membrane depolarization" and "initiation"? And to detail the steps of action potential "life"?
Is it within the scope of GO?

neuronal action potential initiation
Definition: The process in which a neuronal action potential is generated in the axon following depolarization of the membrane potential to a threshold level.
Synonym: neuronal action potential generation

neuronal action potential backpropagation
Definition: The process in which a neuronal action potential is propagated in a retrograde direction from the axon back to the dendritic tree, in a passive or active manner, following depolarization of the membrane potential to a threshold level.

**Comment by dosumis** [comment]
(pasted from mail from @RLovering )

The initiation process starts after membrane depolarisation crosses a threshold level, but what ‘sub-processes’ are you including here? And at what point does initiation finish, i.e. What is the last sub-process within the initiation stage?

**Comment by dosumis** [comment]
label "neuronal action potential"^^string
definition "An action potential that occurs in a neuron."^^string
EquivalentTO: 'action potential'
 and ('occurs in' some neuron)
SuClassOf: 'action potential'
'part of' some 'transmission of nerve impulse'

label "transmission of nerve impulse"^^string
definition "The neurological system process in which a signal is transmitted through the nervous system by a combination of action potential propagation and synaptic transmission."^^string


label "action potential initiation"@en
definition "The begining of an action potential, due to depolarization of the membrane across a firing threshold by some stimulus other than an action potential." 
'part of' some 'action potential'
SubClassOf: 'regulation of membrane potential'

NOTES: As Ruth says - we need a clearer statement of where this begins and ends.  Is this a full cycle through all the phases of an action potential, just happening at the site of initiation (in which case, should probably be subClassOf 'action potential')?  Or is it just the initial, depolarization phase?

**Comment by dosumis** [comment]
(Apologies to @en for accidental tagging in previous post.  This is an unfortunate side effect of the use of  [ISO_639](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) codes to tag strings in [OWL](https://en.wikipedia.org/wiki/Web_Ontology_Language). )

**Comment by vhinard** [comment]
Hi David, 

Thank you for all these definitions.

To answer your questions: 
(NOTES: As Ruth says - we need a clearer statement of where this begins and ends. Is this a full cycle through all the phases of an action potential, just happening at the site of initiation (in which case, should probably be subClassOf 'action potential')? Or is it just the initial, depolarization phase?)

My idea is that the "neuronal action potential initiation" from the literature does not represent the depolarization phase of the AP but, like you said, the full cycle through all the phases of an AP, and 
like in the definition, at a precise neuronal localization, the axon hillock or axon initial segment in vertebrate, where information captured at the dendrites and soma converge and is integrated.
Another reason is that the depolarization phase of the AP (GO:0086010 membrane depolarization during AP) occurs similarly during "neuronal action potential initiation", "neuronal action potential propagation" and "neuronal action potential back-propagation". So "neuronal action potential initiation" cannot be represented by "membrane depolarization during AP". It is another concept.

To be clearer in the statement of where this begins and ends, I suggested (in the mail sent to @RLovering) to make the starts and ends of the processes depending on their localization in the neuron and not depending on the time. So we can easily define in "space" these events: initiation starts at the axon initial segment (AIS) and stops when propagation or back-propagation start. The back-propagation starts after the AIS in direction to the soma and dendrites. The propagation starts after the AIS in direction to the axon. 

So from my side, the definitions you gave correspond perfectly to what I wanted to annotate. 
I only have doubt concerning the "action potential initiation".
definition "The beginning of an action potential, due to depolarization of the membrane across a firing threshold by some stimulus other than an action potential."

Is this corresponding to the first action potential at the postsynaptic membrane? or in other types of cell than neurons?   I am not sure to get the idea.

Thank you again for all this work.
-val

**Comment by dosumis** [comment]
Mostly redundant with #12004 

[Term]
id: GO:0099610
name: action potential initiation
namespace: biological_process
def: "The initiating cycle of an action potential. In vertebrate neurons this typically occurs at an axon hillock. Not all initiated axon potentials propagate." [ISBN:978-0071390118, PMID:19439602]
synonym: "action potential firing" EXACT []
synonym: "action potential triggering" EXACT []
is_a: GO:0001508 ! action potential

Also added these some time ago, but didn't record on ticket:

![image](https://cloud.githubusercontent.com/assets/112839/13146259/c579b290-d64c-11e5-99fa-ab8e61530c3e.png)

![image](https://cloud.githubusercontent.com/assets/112839/13146270/d2108db2-d64c-11e5-86a1-3a1d9bc5637b.png)

![image](https://cloud.githubusercontent.com/assets/112839/13146283/dc14fec4-d64c-11e5-9274-70bd81a76f89.png)

Also modified this:
![image](https://cloud.githubusercontent.com/assets/112839/13146313/f739a4b6-d64c-11e5-901c-af833031ca5e.png)
