### ISSUE TITLE
CTDK-I and pTEFb 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12151]
This is a follow on from

(which somehow did not make the migration to github, but was never closed)
 https://sourceforge.net/p/geneontology/ontology-requests/7102/

I think the proposal below addresses  my issues, those of   our expert (Damian Hermand), and those posed by Karen  and Rob 

-

Phew we are back onto this .
Antonia has been looking at it again. I now think the solution is really simple

currently we have
GO:0008024 positive transcription elongation factor complex b
A transcription elongation factor complex that facilitates the transition from abortive to productive elongation by phosphorylating the CTD domain of the large subunit of DNA-directed RNA polymerase II, holoenzyme. Contains cyclin T and a cyclin-dependent protein kinase catalytic subunit.
exact P-TEFb

with 2 descendants
GO:0070691
dimeric positive transcription elongation factor complex b
A positive transcription elongation factor complex b that comprises two subunits; an example is the budding yeast complex containing Svg1p (also called Bur1p) and Bur2p.
PMID:16721054 PMID:19328067
narrow Sgv1/Bur2 complex
narrow Bur1/Bur2 complex

and
GO:0070692
trimeric positive transcription elongation factor complex b
A positive transcription elongation factor complex b that comprises three subunits; an example is the budding yeast Ctk complex, which consists of Ctk1p, Ctk2p and Ctk3p.
PMID:16721054 PMID:19328067
related C-terminal domain kinase I complex
narrow CTDK-I complex
narrow Ctk complex

I think the problem is that the parent term has a "b" and the P-TEFb synonym
- The community do not refer to CTDK-1 complex as pTEFB. pTEFB is the name of the complex which budding yeast call 2 different names  (CTDK-1 is still a TEF complex though, its just that pTEFB does not work as the generic parent complex name)

Solution

1 rename
GO:0008024 positive transcription elongation factor complex b
to
GO:0008024 cyclin/CDK positive transcription elongation factor complex
A transcription elongation factor complex that facilitates the transition from abortive to productive elongation by phosphorylating the CTD domain of the large subunit of DNA-directed RNA polymerase II, holoenzyme. Contains a cyclin and a cyclin-dependent protein kinase catalytic subunit.

remove exact P-TEFb

2 rename
GO:0070691
dimeric positive transcription elongation factor complex b
to P-TEFb (this is the universal name for this complex)

Reword the def to
A dimeric positive transcription elongation factor complex b that a cyclin dependent kinase containing the catalytic subunit, Cdk9 and a regulatory subunit, cyclin T

This def has the same meaning but the names are almost universal (its the Cdk9 in human and drosophila where  the complex was first characterised, and in pombe)

PMID:16721054 PMID:19328067 (add more refs)
narrow Sgv1/Bur2 complex
narrow Bur1/Bur2 complex

add wiki link
https://en.wikipedia.org/wiki/P-TEFb

    rename
    GO:0070692 trimeric positive transcription elongation factor complex b
    to
    CTDK-1 complex (the universal name)

revise the def to

A positive transcription elongation factor complex that comprises the CDK kinase CTK1(budding yeast), Lsk1 (fission yeast) (Panther PTHR24056:SF39 family), a cyclin and an additional gamma subunit ( IPR024638).
(this does not change the definition meaning)

(ASK PANTHER TO NAME THIS CTK1 family after the founding member, currently is called CYCLIN DEPENDENT KINASE 12)

PMID:16721054 PMID:19328067
related C-terminal domain kinase I complex MAKE EXACT
narrow CTDK-I complex MAKE EXACT
narrow Ctk complex MAKE EXACT

**Comment by ValWood** [comment]
@cmungall  Hi Chris, any idea why the old ticket did not get transferred over?

**Comment by ValWood** [comment]
Actually all of the defs could include the  specific MF of the complex

"RNA polymerase II C-terminal domain kinase" involved in "transcription elongation"
instead of just "transcription elongation factor complex" (which could be anything)

**Comment by ValWood** [comment]
Antonia said:
it looks like p-tefb positively regulates going from translation initiation to elongation (I guess this is not a binary step, but more like making sure the polymerase doesnt fall off...maybe)
ctdk1 positively regulates elongation from then on (ie once there are a few phosphates added by p-tefb)

So this could be an additional  differentia.

**Comment by Antonialock** [comment]
I also said this seems to be the quick-read gist, please don't quote me :p

**Comment by Antonialock** [comment]
see
http://www.ncbi.nlm.nih.gov/pubmed/24879308
http://www.ncbi.nlm.nih.gov/pubmed/20952539

**Comment by tberardini** [comment]
Assigning to @paolaroncaglia, as she was the one assigned the original SF item.  Also adding @krchristie .  I'd add Rob Nash but can't find his github id.

**Comment by ValWood** [comment]
Damien Hermand read the thread and commented (below), which I belive confirms tht these changes are required:


Thanks Val. The most important is indeed to distinguish the P-TEFb complex, which is Cdk9-Pch1 (pombe), Cdk9-CylinT (higher eukaryotes), Bur1-Bur2 (cerevisiae) from the CTDK complex, which is Lsk1-Lsc1-Lsg1 (pombe), Ctk1-Ctk2-Ctk3 (cerevisiae) and Cdk12-CyclinK(no third partner) (higher eukaryotes). It is still unclear if Cdk9 phosphorylates the CTD in vivo  but it is clear that Lsk1 (or Ctk1 or cdk12) are major CTD S2 kinase in vivo.

Hope this helps
Best wishes
D.

**Comment by ValWood** [comment]
This one looks fairly straightforward, so let me know if you don't think so, or if you are waiting for something from anyone.
Val

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,

Please see the revised stanzas for these terms below. If you’d like the defs to be further revised based on your and Antonia’s latest comments, please provide full text for the proposed defs (keep in mind that Chris is much in favour of simple defs along the pattern “A [name of parent] that [differentia].”. Otherwise, please go ahead and close this ticket.

Thanks!

[Term]
id: GO:0008024
name: cyclin/CDK positive transcription elongation factor complex
namespace: cellular_component
def: "A transcription elongation factor complex that facilitates the transition from abortive to productive elongation by phosphorylating the CTD domain of the large subunit of DNA-directed RNA polymerase II, holoenzyme. Contains a cyclin and a cyclin-dependent protein kinase catalytic subunit." [GOC:bhm, GOC:vw, PMID:10766736, PMID:16721054, PMID:17079683, PMID:19328067, PMID:7759473]
comment: See also the cellular component terms 'cyclin-dependent protein kinase activating kinase holoenzyme complex ; GO:0019907' and 'DNA-directed RNA polymerase II, holoenzyme ; GO:0016591'.
synonym: "positive transcription elongation factor complex b" RELATED []
is_a: GO:0008023 ! transcription elongation factor complex
is_a: GO:0019908 ! nuclear cyclin-dependent protein kinase holoenzyme complex
is_a: GO:0032806 ! carboxy-terminal domain protein kinase complex
is_a: GO:0044428 ! nuclear part
relationship: capable_of GO:0008353 ! RNA polymerase II carboxy-terminal domain kinase activity

[Term]
id: GO:0070691
name: P-TEFb complex
namespace: cellular_component
def: "A dimeric positive transcription elongation factor complex b that comprises a cyclin-dependent kinase containing the catalytic subunit, Cdk9, and a regulatory subunit, cyclin T.” [GOC:mah, GOC:vw, PMID:16721054, PMID:19328067, http://en.wikipedia.org/wiki/P-TEFb]
synonym: "Bur1/Bur2 complex" NARROW [PMID:16721054, PMID:19328067]
synonym: "dimeric positive transcription elongation factor complex b" RELATED []
synonym: "Sgv1/Bur2 complex" NARROW [GOC:mah]
is_a: GO:0008024 ! positive transcription elongation factor complex b
created_by: midori
creation_date: 2009-06-03T03:12:56Z

[Term]
id: GO:0070692
name: CTDK-1 complex
namespace: cellular_component
def: "A positive transcription elongation factor complex that comprises the CDK kinase CTK1 (in budding yeast), Lsk1 (in fission yeast) (corresponding to the Panther PTHR24056:SF39 family), a cyclin and an additional gamma subunit (corresponding to the InterPRO entry IPR024638)." [GOC:mah, GOC:vw, PMID:16721054, PMID:19328067]
synonym: "C-terminal domain kinase I complex" EXACT [PMID:15047695, PMID:16721054, PMID:19328067]
synonym: "CTDK-I complex" EXACT [PMID:15047695, PMID:16721054, PMID:19328067]
synonym: "Ctk complex" EXACT [PMID:16721054]
synonym: "trimeric positive transcription elongation factor complex b" RELATED []
is_a: GO:0008024 ! positive transcription elongation factor complex b
created_by: midori
creation_date: 2009-06-03T03:18:04Z
