### ISSUE TITLE
TPV removal of nonhomologous ends' 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12161]
shouldn't be a child of 
GO:0007534 gene conversion at mating-type locus

needs  to be
removal of nonhomologous ends involved in gene conversion at mating-type locus etc?

Also, I'm not  totally sure that mating type switching should be considered a 'reproductive process.. mating type switching can occur independently of mating...I would need to check that with @Antonialock and @mah11

**Comment by Antonialock** [comment]
I dont know if this is a sexually reproductive process or not: it happens during asexual reproduction but the purpose is (I guess) sexual reproductive fitness

eg
Extensive studies of fission yeast established the natural DNA strand chirality at the mat1 locus as the primary basis of asymmetric cell division. The asymmetry results from a unique site- and strand-specific epigenetic "imprint" at mat1 installed in one of the two chromatids during DNA replication. The imprint is inherited by one daughter cell, maintained for one cell cycle, and is then used for initiating recombination during mat1 replication in the following cell cycle. 

PMID:26104357

**Comment by ValWood** [comment]
I have a feeling we have discussed this before Maybe M will remember....if not will assume its OK and just fix
"removal of nonhomologous ends"

**Comment by ukemi** [comment]
Hi Val, Antonia and Midori,

I have removed the part of relation. I tried to see if I could make it a pert of repair or recombination, but I think it is too generic. I am leaving this item open for the reproductive process bit. I think it is, but you guys are the experts. If you decide nothing needs to be done, go ahead and close this. Otherwise ping me and I will fix it.

-D

**Comment by mah11** [comment]
Hmm. I don't remember discussing this specific point before, but here's some fresh wittering.

It seems a bit counter-intuitive to have mating type switching as a reproductive process, but not outrageous. I guess it depends on how direct the connection to reproduction is meant to be — I don't think switching easily fits the "directly contributes to the process of producing new individuals by one or two organisms" part of the "reproductive process" definition; it seems not that direct to me. The immediate is_a link, though, is to "reproductive process in single-celled organism", which uses the woolier "involved in the reproductive function" wording in its def. It's a little easier to make that sort of apply to switching, since you don't get sexual reproduction if you don't have both mating types present (I do think it's ok to say "never mind" about asexual reproduction for this purpose - the question is whether switching is part of SOME reproduction, not whether it's part of ALL reproduction). So for me it comes down to how direct we want "involvement in making more lifeforms" to be.

Another thing - I see that mating type switching also has a path to "developmental process involved in reproduction". Are we confident that switching fits the description of "a progressive change"? (In other words, is the change that switching entails "progressive"?)

**Comment by ukemi** [comment]
It's your call. What do you think your community would expect?

**Comment by dosumis** [comment]
The formal definition of 'reproductive process' is simple a process that is
part_of (some)  reproduction  (axiom got deleted at some point.  I've added
it back in my branch, visisble soon).  So I think the important question
here is whether (all) mating type switching is part_of some reproduction.
If not, then the part_of should be deleted and the classifications up to
reproductive process will go away.  (If you decide to keep the link,
becuase it is intuitive to users even if not strictly always true, then
there should at least be a comment outlining reasons so future editors
don't need to puzzle over the choice again).

**Comment by mah11** [comment]
I'm not the best judge of what the pombe community will find most intuitive, but I don't recall encountering active demand for an explicit connection linking mating type switching to reproduction.

Organisms that do mating type switching evolved the process to facilitate sexual reproduction, by increasing the probability that one cell of one mating type would encounter another cell of a compatible (as opposed to the same) mating type. But any individual instance of switching may take place in a cell that does not go on to find an opposite-type cell, mate, form zygotes, etc. So if the latter is the criterion for part_of, then the link to reproductive process should be removed.

Note, however, that the same reasoning applies to the paths via both of the asserted is_a parents, since both lead to reproductive process. Does that add a spanner, by calling the path via "sex determination" into question? If so, I'm not sure which link(s) pose any problem.

[Term]
id: GO:0007533
name: mating type switching
[snip]
is_a: GO:0007531 ! mating type determination
is_a: GO:0022413 ! reproductive process in single-celled organism
is_a: GO:0044710 {is_inferred="true"} ! single-organism metabolic process

**Comment by ukemi** [comment]
I think the key here is to ask whether the switch happens for any other reason than reproduction. Is this analagous to something like gamete development? The purpose of that is for reproduction whether or not the animal ever mates, so by that standard it is still part of reproduction. Does that make sense?

**Comment by mah11** [comment]
Yep, it makes sense, and nope, there's no other point to mating type switching (as far as I know, anyway).

**Comment by ukemi** [comment]
OK. I will close this then. If it comes up in the future, we can revisit. Thanks Midori.
