### ISSUE TITLE
OTR: problems with GO:0031555 ! transcriptional attenuation and  GO:0031564 ! transcription antitermination

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#12178]
1) Definition problem with GO:0031555 ! transcriptional attenuation

current definition: "Regulation of transcription through variation in where transcription termination occurs"

Attenuation involves regulation of genes downstream of a terminator whose formation is controlled by alternative secondary structures. Sometimes one of these is called the antiterminator structure, but that should not be equated to the biological process of antitermination. The paradigm is the trp operon of E. coli, where the alternative RNA structures are controlled by translational pauses, but other mechanisms can be used to determine the RNA fold. Some examples are riboswitches, the _B. subtilis_ TRAP system, and the T-box system (also in _B. subtilis_) that controls expression of tRNA synthetases. Attenuation is not controlling _where_ termination occurs, it is controlling _whether_ termination occurs at the attenuator.

Following [Yanofsky (1981) Nature](http://www.ncbi.nlm.nih.gov/pubmed/7007895), with slight modification I would suggest that attenuation as a process be defined as

> the regulation of gene expression by the selective reduction of the transcription of transcription of [DNA distal to a specific transcriptional terminator]

Where I have brackets, Yanofsky wrote

> distal portions of an operon

The problem with my definition is that it would apply to termination reduces distal expression whether or not that termination was subject to regulation. But it would help with item #4 below.

2) Definition problem with GO:0031564 ! transcription antitermination
current definition: "Regulation of transcription by a mechanism that allows RNA polymerase to continue transcription beyond a termination site." [ISBN:0198577788, PMID:12456320]

Antitermination as exemplified by the N and Q dependent systems in phage lambda is processive. Once the antitermination complex forms, RNA polymerase becomes resistant to multiple terminators. In _E. coli_ this affects both rho-dependent and rho-independent termination, while attenuators are rho-independent.

**DONE** 3) GO:0031564 ! transcription antitermination should not be a child of GO:0031555 ! transcriptional attenuation.

I would make GO:0031564 ! transcription antitermination a sibling of attenuation, not a child. Yanofsky writes of attenuation occurring in lambda, but I think that's in the context of the terminators, not the antitermination.

Note that there may be at least one more form of regulation of termination. There are phage proteins that seem to act more globally by antagonizing rho. These would be more global than attenuators, but not processive. However the data on these is probably too ambiguous to create a GO term at this point.

4) Annotation to GO:0031555 ! transcriptional attenuation

a) cis vs trans: 
The existing annotations to this term include things like the _trp_ leader peptide, which strike me as problematic. Whether termination occurs at _trp_ is determined by the rate of translation through trpL, but is that a function of _trpL_? This seems different from the function of a trans-acting protein like TRAP that stabilizes one of the alternative RNA structures. As we start annotating RNAs, are attenuators and riboswitches in the domain of GO or do they belong to SO?

b) increased or decreased attenuation? 
Annotation to GO:0031555 ! transcriptional attenuation does not capture whether the product being annotated increases or decreases termination at the attenuator. It seems that child terms are needed to capture this, but I think how to do this depends on whether GO adopts my proposed definition. It also raises the question of whether the attenuation term itself could be used for annotation or if only child terms should be used.

If I have time I will try to find the papers I used to use when I taught this stuff.

**Comment by mcourtot** [comment]
Hi Jim,

Thank you for your very detailed message. This will take me a little while to process and implement, so please let me know if there is any urgency. Papers used for teaching would be a great help indeed. It was also suggested I pinged @ukemi as transcription specialist :)

Thanks,
Melanie

**Comment by mcourtot** [comment]
Hi Jim,

I have been looking at those - mostly trying to catch up on background reading, as I haven't thought about attenuation since college days :) I asked other GO editors but no one is an expert in this area either. 

I am hoping we can deal with those one at a time, and you can perhaps provide more details/pointers to help me process this ticket?

Looking at 
>2) Definition problem with GO:0031564 ! transcription antitermination
current definition: "Regulation of transcription by a mechanism that allows RNA polymerase to continue transcription beyond a termination site." [ISBN:0198577788, PMID:12456320]

>Antitermination as exemplified by the N and Q dependent systems in phage lambda is processive. Once the antitermination complex forms, RNA polymerase becomes resistant to multiple terminators. In E. coli this affects both rho-dependent and rho-independent termination, while attenuators are rho-independent.

I don't understand the issue with the definition. You explain that once the complex is formed, the RNApol becomes resistant to other terminators, so isn't it true that it continues transcription beyond a termination site? Isn't the formation of the anti termination complex a "mechanism" and the global effect is the regulation of transcription?

Cheers,
Melanie

**Comment by jimhu-tamu** [comment]
Hi Melanie,

It's been a while since I wrote this. I think the problem is with "a termination site" being too suggestive that it only works at one site.

**Comment by mcourtot** [comment]
Hi @jimhu-tamu - trying to move forward on old tickets. If you have specific suggestions on how to address the above could you please help? I'm afraid none of us GO editors have expertise in this field.

**Comment by mcourtot** [comment]
@krchristie: do you have any input on this? @ukemi mentioned you were a transcription expert.

**Comment by krchristie** [comment]
Hi,

I haven't thought about this much since the transcription overhaul that @ukemi and I did in 2010, though we did do some work on bacterial transcription then, though I thought these were OK then. However, Jim is clearly much more knowledgable on bacterial transcription than I am.

If Jim needs more specific terms, we should create them, but these the two terms "GO:0031555 transcriptional attenuation" and "GO:0031564 transcription antitermination" seem like they are meant to be very general top level terms. Jim is distinguishing between "antitermination" sites and "attenuator" sites in a way I'm not familiar with. It might be worth checking if those words are always used consistently across all the literature. If not, it might be hard to implement these very specific meanings that Jim is referring to in GO without creating misunderstandings.

For example, looking at the ontology, it seems to me that "GO:0031555 transcriptional attenuation" is currently a process term that is meant to cover a broad range of ways that transcription can be reduced between the initiation site and the distal end of the transcription unit/operon, including "transcriptional attenuation by ribosome" not just the mechanisms of recognizing terminator sites. So, if this use of the word "attenuation" is used in the literature, GO may need to reflect this too.
<pre>
GO:0031555 transcriptional attenuation
- (BP) GO:0031556 transcriptional attenuation by ribosome
- (BP) GO:0031564 transcription antitermination
</pre>

Regarding the definition of "transcription antitermination" allowing readthrough of all downstream terminator sites, could that be fixed by just changing the last word from singular "site" to a more inclusive "site(s)". 

I also see that there are a couple MF terms, which if I remember correctly were added by the 2010 transcription overhaul, to cover some specific types of antitermination factor activities.
- GO:0001073 transcription antitermination factor activity, DNA binding
- GO:0001072 transcription antitermination factor activity, RNA binding

Beyond those general comments, I'm not sure I can add much to this discussion.

**Comment by mcourtot** [comment]
Thanks @krchristie for the feedback. I did the update to site(s).

@jimhu-tamu: can you please comment on other aspects of this request? I'll otherwise will close the ticket as "Won't fix" by Thursday feb 23rd. Thanks!

**Comment by jimhu-tamu** [comment]
Hi Melanie, 

Apologies for the very slow replies. I was hoping to set aside some time to dig into the literature. I've been discussing this with Debby and looking at papers today, but it's complicated so I'm going to put my thinking in a [Google Doc](https://docs.google.com/document/d/1kO1Tu3G8gOQIPX57zY_AwWO4d9SBgZBQqAgrvS0hLjg/edit?usp=sharing)

**Comment by mcourtot** [comment]
Hi @jimhu-tamu - no problem, this is a complex topic which requires time, and I really appreciate you and others going in depth to make sure it is done right. I am trying to address my tickets before the end of the grant (end February), but @ukemi kindly agreed to take over this one if not done by then, so I'll co-assign him now anyway.

**Comment by mcourtot** [comment]
@ukemi: could you please review the google doc and below? Your name is associated to many of the original definitions. I'm specifically unsure whether we want to obsolete GO:0031555, transcriptional attenuation or just update it.

TODO:

**Updates:**

- [ ] Obsolete GO:0031555, transcriptional attenuation (or update as per NTR below)
- [ ] NTR:Name: transcriptional attenuation
Def: Regulation of gene expression in response to a metabolic signal through control of the formation of a terminator within an attenuator element (SO:0000140) upstream of regulated gene(s)
- [ ] Update  GO:0031556 ! transcriptional attenuation by ribosome to 
Name: Ribosome-mediated attenuation 
Def: Attenuation where formation of alternative RNA secondary structures is regulated by the rate of translation in the attenuator. 
Is_a: transcriptional_attenuation
- [ ] Update id: GO:0031564

Name: processive transcription antitermination
namespace: biological_process
def: "Regulation of transcription by a mechanism that allows RNA polymerase to continue transcription beyond a termination **site(s).**"


**NTRs for other forms of attenuation  (per Merino and Yanofsky, PMID:15851059):**

- [ ] Protein-mediated transcription attenuation

Def: Attenuation where formation of alternative RNA secondary structures is regulated by binding of an RNA-binding protein.
Is_a: transcriptional_attenuation
Synonym: transcriptional_antitermination[narrow]

- [ ] Aptamer-mediated transcription attenuation

Def: Attenuation where formation of alternative RNA secondary structures is regulated by stabilization of an RNA structure by binding of a ligand by the attenuator RNA.
Is_a: transcriptional_attenuation
Synonym: small-molecule-mediated transcription attenuation

- [ ] RNA-mediated transcription attenuation

Def: Attenuation where formation of alternative RNA secondary structures is regulated by RNA-RNA interaction.
Is_a: transcriptional_attenuation

- [ ] tRNA-mediated transcription attenuation

Def: Attenuation where formation of alternative RNA secondary structures is regulated by RNA-RNA interaction.
Is_a: RNA-mediated transcriptional_attenuation

- [ ] Antisense RNA-mediated transcription attenuation

Def: Attenuation where formation of alternative RNA secondary structures is regulated by RNA-RNA interaction.
Is_a: RNA-mediated transcriptional_attenuation

**Comment by mcourtot** [comment]
Talked to @ukemi who mentioned he'd like to use this for the Protege curator course and he will follow-up on this ticket with @krchristie.

**Comment by pgaudet** [comment]
See https://en.wikipedia.org/wiki/Attenuator_(genetics) for references

**Comment by pgaudet** [comment]
@amandamackie Can you help with this old request - my question is, would these terms be useful?

**Comment by amandamackie** [comment]
Transcription information in EcoCyc is curated by Julio's group at UNAM.

I don't have any expertise in the area and am hesitant to comment further. Julio are you able to help?

Amanda

**Comment by pgaudet** [comment]
Fixed definitions: 

- [ ] **GO:0031555 transcriptional attenuation** : "A regulatory mechanism by which bacteria and archae can direct RNA polymerase to prematurely terminate transcription in response to a specific metabolic signal." [PMID:12210530, PMID:15851059, PMID:7007895]
- [ ] Changed parent from is_a: GO:0031554 ! regulation of termination of DNA-templated transcription to 
+is_a: 'positive regulation of termination of DNA-templated transcription' and 
+is_a: GO:0010629 ! negative regulation of gene expression
- [ ] **GO:0031564  transcription antitermination:** Regulation of transcription by a mechanism that allows RNA polymerase to continue transcription beyond termination site(s), thus allowing expression of downstream genes under specific conditions." [ISBN:0198577788, PMID:12456320, PMID:21478900, PMID:30191803]
- [ ]  Changed parent from is_a: GO:0031554 ! regulation of termination of DNA-templated transcription
+is_a: GO:0010628 ! positive regulation of gene expression
+is_a: GO:0060567 ! negative regulation of termination of DNA-templated transcription


Thanks, Pascale
