### ISSUE TITLE
NTR: beta-catenin/TCF complex

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12173]
A suggested new protein complex term. It's a grouping term so not suitable for getting an Intact ID itself:

beta-catenin/TCF complex ; GO:NEW
—[isa]beta-catenin-TCF7L2 complex ; GO:0070369

beta-catenin/TCF complex ; GO:NEW
is_a: protein complex
part_of: nucleus
capable_of: DNA binding 
capable_of_part_of: canonical Wnt signaling pathway ; GO:0060070
Related Synonym: beta-catenin/T-cell factor complex
Related Synonym: beta-catenin/lymphoid enhancer binding factor complex [PMID: 8757136]
Narrow Synonym: beta-catenin/LEF complex [PMID: 8757136]
PMID: 8757136
PMID: 8756721
PMID: 9419974
GOC:PARL, GOC:bf
A protein complex that contains beta-catenin and a member of the T-cell factor (TCF)/lymphoid enhancer binding factor (LEF) family of transcription factors.

Could create a more specific 'beta-catenin-LEF1 complex' in Intact, if you were feeling keen @bmeldal, based on PMID: 8757136

On Github for comments before I add it in.
Thanks!

**Comment by bmeldal** [comment]
Hi Rebecca,

Yes, I can curate the complex. Interaction evidence is already in IntAct:
e.g. http://www.ebi.ac.uk/intact/interaction/EBI-8786899

The GO complex term may fall victim to future pruning of the ontology as it has no capable_of activity link (unless we allow 'binding' which we haven't included in our discussions so far).

Birgit

**Comment by bmeldal** [comment]
Hi Rebecca,

This is a TF so should have the following relationships (at a minimum, I'm now curating the complex and will add more relationships if I find them later):

is_a GO:0090575 RNA polymerase II transcription factor complex
capable_of GO:0001228 transcriptional activator activity, RNA polymerase II transcription regulatory region sequence-specific binding
capable_of_part_of GO:0045944 positive regulation of transcription from RNA polymerase II promoter

It may well still be pruned as so far it has the same relationships as many other RNA Pol II TFs and they would all be grouped together under the new proposal. The intermediate, protein family-centric complex grouping terms might go to PRO so not superfluous creating it now as it may well 'only' get moved rather than totally obsoleted! And that's all down the line anyway...

Can you wait with creating the new term until I have done the annotations, then you can add all the relationships and IntAct xrefs in one go. When you have then created the CC term, please post here, so I can xref it on the complex :)

Thanks,
Birgit

**Comment by rebeccafoulger** [comment]
Hi @bmeldal- just let me know when you're done annotating, and then I'll create the GO term with all it's relationships.

Thanks!

**Comment by bmeldal** [comment]
Hi Rebecca,

I have finished the curation:

dbxrefs:
IntAct:EBI-11424678 [human]
IntAct:EBI-11425837 [mouse]
PMID:20123964 [human complex evidence]
PMID:11751639 [human MF & BP]
PMID:21075118 [mouse complex evidence]
PMID:16936075 [mouse MF & BP]

Relationships:

is_a GO:0090575 RNA polymerase II transcription factor complex
part_of GO:0005634 nucleus

capable_of
GO:0001228 transcriptional activator activity, RNA polymerase II transcription regulatory region sequence-specific binding
GO:0000977 RNA polymerase II regulatory region sequence-specific DNA binding

capable_of_part_of
GO:0060070 canonical Wnt signaling pathway
GO:0045944 positive regulation of transcription from RNA polymerase II promoter

Ok, I think that's it.
Birgit

**Comment by rebeccafoulger** [comment]
New term:
beta-catenin-TCF complex ; GO:1990907

Thanks for everyone's input!

**Comment by bmeldal** [comment]
Thanks, xref added to complexes!
