### ISSUE TITLE
comment on GO:0004843 refers to an obsolete term

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12181]
The comment on GO:0004843 (and child terms) refers to an obsolete term
Note that this term is distinguished from 'ubiquitin thiolesterase activity ; GO:0004221' in that it encompasses hydrolysis of a peptide bond formed between ubiquitin and another protein.

**Comment by mcourtot** [comment]
Hi Antonia - thanks for the report; I'll look into it. I'm away this week but will aim at addressing following one. Do you know what is the policy in this case? Is it expected to remove the comment, or just mention that the term has been obsoleted? I'll also check with the other editors.

**Comment by Antonialock** [comment]
Thanks Melanie. I don't know what GO normally does.

**Comment by mcourtot** [comment]
dear @paolaroncaglia - do you know what is the proper fix for this? I would think we'd keep the comment mentioning the term has been obsoleted, but is there an official policy?

**Comment by paolaroncaglia** [comment]
Hi Melanie (and Antonia),

The obsoletion comment to 'ubiquitin thiolesterase activity ; GO:0004221' says that “This term was made obsolete because this molecular function does not exist.”, and there are ‘consider’ suggestions for GO:0004843 ‘ubiquitin-specific protease activity’ itself and another term. I would remove the definition comment of GO:0004843, and would expand its definition to be totally unambiguous, something like “Catalysis of the thiol-dependent hydrolysis of a peptide bond formed by the C-terminal glycine of ubiquitin and another protein.”. As far as I know there isn’t an official policy on comments referring to obsolete terms (first time I see one ;-)), but I think my suggestion should work well. 

Cheers,

Paola

**Comment by mcourtot** [comment]
Done revision 30360.
