### ISSUE TITLE
 GO:0004843 parentage problem?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12182]
GO:0004843 ubiquitin-specific protease activity
is_a  GO:0008234 cysteine-type peptidase activity

The enzyme I am annotating (sst2 pombe, ortholog STAMBP in human) is a ubiquitin-specific protease, but also a zinc-specific metalloprotease.
I suppose the is_a  GO:0008234 cysteine-type peptidase activity link is wrong in this case?

I wonder if   GO:0004843 ubiquitin-specific protease activity should instead have this parent:
is_a GO:0070122 isopeptidase activity
Catalysis of the hydrolysis of an isopeptide bond. An isopeptide bond is an amide linkage between a carboxyl group of one amino acid and an amino group of another amino acid in which at least one of these groups is not on the a-carbon of one of the amino acids (for example, the link between an epsilon-amino group of a lysine molecule to a carboxyl group on a second amino acid is an isopeptide bond). 

Note, I've just requested GO:1990908 Label: Lys63-specific zinc metallopeptidase deubiquitinase activity via TG from PMID:26368668

**Comment by mcourtot** [comment]
Hi Antonia, Thanks for the note. Let me look at this with the TermGenie request and come back to you.

**Comment by mcourtot** [comment]
I'm not sure I understand fully. We currently have "GO:0004843, ubiquitin-specific protease activity, def = Catalysis of the thiol-dependent hydrolysis of a peptide bond formed by the C-terminal glycine of ubiquitin and another protein."
I am not an expert, but based on http://www.nature.com/cdd/journal/v17/n1/images/cdd2009168f2.jpg and the description at https://en.wikipedia.org/wiki/Ubiquitin#Ubiquitination at least E1 and E2 involve come cysteine-peptidase activity.
If that's correct, could you explain why is the link to GO:0008234 cysteine-type peptidase activity wrong?

**Comment by ukemi** [comment]
Hi Antonia,

I agree with Melanie. Why can't it be both and annotated to both terms?

-D

**Comment by mah11** [comment]
I think the problem is that the enzyme Antonia is annotating is NOT a cysteine-type peptidase. It's a ubiquitin-specific protease (i.e. a DUB, not E1 or E2) that works by a zinc metalloprotease mechanism instead of a cysteine-type mechanism. So GO has a previously unsuspected TPV. (That's if I'm interpreting the paper intro correctly -- "DUBs are grouped into five categories based on the structure of their catalytic domains: ... The first four groups are cysteine proteases, whereas the JAMM members are zinc metalloproteases, containing a catalytic zinc and sharing mechanistic similarities with the well-known zinc protease thermolysin.")

hope that helps,
m

**Comment by ukemi** [comment]
If that's true, then you are right and there is a TPV. Thanks Midori.

**Comment by ValWood** [comment]
I think Antonia mentioned this because we find it odd to  represent a single molecular activity using 2 terms, so we always try to find a term which encompasses all aspects of the activity.

That said, at the LEGO meeting I was discussing with  Paul Thomas (Can't find his github ID!)
about some of these types of terms, where we were wondering if we were over-complicating things. This seems like a good example of trying to represent aspects of the mechanistic detail which do not affect the 'output' and are could be considered too granular for GO?
Do we need to know that its a metalloprotease or cysteine-type protease to describe the function adequately?

**Comment by ValWood** [comment]
Or what Midori said.

**Comment by mah11** [comment]
well, Val's comment and mine aren't mutually exclusive ;)

**Comment by Antonialock** [comment]
Yes I meant that this link:
GO:0004843 ubiquitin-specific protease activity
is_a GO:0008234 cysteine-type peptidase activity

is wrong. Thanks Midori.

**Comment by mcourtot** [comment]
Thanks for all the additional explanations, this is very helpful.

The term is currently defined as: "GO:0004843, ubiquitin-specific protease activity, def = Catalysis of the thiol-dependent hydrolysis of a peptide bond formed by the C-terminal glycine of ubiquitin and another protein."

If this is not a cystein-type peptidase activity, is it still correct to say that the hydrolysis is thiol-dependent? I would think that the thiol implies thioesters formed by E1 and/or E2, which doesn't seem to be the case here. 

If the above is correct, should we relabel ubiquitin-specific protease activity to thiol-dependent ubiquitin-specific protease activity and create a new term for the metalloproteases DUBs?

**Comment by Antonialock** [comment]
I'm not sure about any other suitable parentage. At the time I seem to have thought that "GO:0070122 isopeptidase activity" would be a suitable parent instead, but I am not a peptidase expert so I don't know for sure what's correct.

**Comment by mah11** [comment]
> If this is not a cystein-type peptidase activity, is it still correct to say that the hydrolysis is thiol-dependent?

No, because here the thiol (aka sulfhydryl) group is part of the cysteine-type peptidase's active site, not the substrate.

The simplest solution would be to delete "thiol-dependent" from the GO:0004843 definition, because then the term would apply to both the cysteine-type and zinc metalloprotease DUBs (and would keep it simple as Val suggested). But I don't really mind if you want to make a new generic term as a superclass for a renamed GO:0004846 (I'd use "cysteine-type ubiquitin-specific protease activity" for consistency with existing grouping terms) and a new term for the zinc metallopeptidase activity.

**Comment by mah11** [comment]
oh, and move GO:0004843 to is_a peptidase activity, or maybe endopeptidase activity

**Comment by mcourtot** [comment]
We probably need to go one level up, as the current parent "ubiquitinyl hydrolase activity" is also defined as "thiol-dependent"

Could we just remove the thiol-dependent bit in both, and then just remove the is_a "'ubiquitin-like protein-specific protease activity'"? It would still remain under "ubiquitinyl hydrolase activity". I'm also all for keeping things simple :)


<img width="878" alt="screen shot 2016-01-25 at 15 24 36" src="https://cloud.githubusercontent.com/assets/2214135/12555195/e3d697ae-c377-11e5-8d0a-1eab9543ae41.png">

**Comment by mah11** [comment]
Sorry, I didn't pay enough attention to both links!

Yes, I agree that "thiol-dependent" should also be removed from the GO:0036459 definition. I don't know if that clashes with the EC:3.4.19.12 xref, but the MEROPS guys assured me that peptidases are a mess in EC.

I do not see any reason to remove the is_a GO:0019783 link, because ubiquitin is, well, a ubiquitin-like protein. Instead, GO:0019783 should itself be moved to is_a peptidase activity; its text definition doesn't even mention a mechanism, and now we know that not all activities that fit the definition also act via a cysteine-type mechanism.

**Comment by ValWood** [comment]
As an aside, even when this is closed I told @thomaspd I would flag these terms. Added a lablel "discuss_term_specificity" to collect them.

**Comment by mcourtot** [comment]
Sounds great to me, thanks for the extra discussion/information!

@rebeccafoulger: for the term "ubiquitinyl hydrolase activity" which is currently mapped to EC:3.4.19.12, do you foresee any issue wrt the mapping if we update the definition from "Catalysis of the thiol-dependent hydrolysis of an ester, thioester, amide, peptide or isopeptide bond formed by the C-terminal glycine of ubiquitin." to "Catalysis of the hydrolysis of an ester, thioester, amide, peptide or isopeptide bond formed by the C-terminal glycine of ubiquitin." (i.e., removing the "thiol-dependent" bit). The EC very much specifies cysteine involvement, but i don't know if there is a generic EC for ubiquitination which would cover both cysteine proteases and metalloproteases.

**Comment by rebeccafoulger** [comment]
There are 0 manual annotations directly to 'ubiquitinyl hydrolase activity ; GO:0036459'- all annotations come from InterPro and HAMAP mappings. So after a chat with Melanie, we think it makes most sense to:
1. Create a new generic ubiquitinyl hydrolase activity term.
2. Rename GO:0036459 to thiol-dependent ubiquitinyl hydrolase activity.
3. Add in an EC:GO mapping to GO:0036459 for EC:3.4.19.12 (currently the EC number is just in the definition field, so doesn't make it into mapping files).

**Comment by mcourtot** [comment]
Note to self: discussion of merging at editors call: http://wiki.geneontology.org/index.php/Ontology_meeting_2016-01-28#Merging_of_terms
In short we keep merging for now, round-tripping done automatically with OWLAPI

**Comment by mcourtot** [comment]
Implemented as described by Becky.

**Comment by Antonialock** [comment]
Should all the changes be visible in TG? 

 GO:0061578 Lys63-specific deubiquitinase activity
Hydrolysis of Lys63-Linked ubiquitin unit(s) from a ubiquitinated protein.

still has the parent
GO:0008234 cysteine-type peptidase activity
Catalysis of the hydrolysis of peptide bonds in a polypeptide chain by a mechanism in which the sulfhydryl group of a cysteine residue at the active center acts as a nucleophile.

**Comment by Antonialock** [comment]
I can't reopen this ticket so I made a new one: https://github.com/geneontology/go-ontology/issues/12275
