### ISSUE TITLE
revision/refinement suggestions for periplasmic terms

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12196]
After creating a new term yesterday I was getting increasingly confused about the definition of the periplasmic side of membranes and the periplasmic space. I admit, I had to look up the structure of bacterial cell membranes/walls! 

1)
GO:0042597 periplasmic space
Def = The region between the inner (cytoplasmic) and outer membrane (Gram-negative Bacteria) or cytoplasmic membrane and cell wall (Fungi and Gram-positive Bacteria).
- I agree.

2)
GO:0030288 outer membrane-bounded periplasmic space
Def = The region between the inner (cytoplasmic or plasma) membrane and outer membrane of organisms with two membranes such as Gram negative bacteria. These periplasmic spaces are relatively thick and contain a thin cell wall.
- This def does not clearly separate it from the above parent (GO:0042597 periplasmic space). The difference is that the peptidoglycan layer (PGL) (= bacterial cell wall) in gram neg bacs is thin and divides the periplasmic space into two parts and in gram pos bacs very thick and constitutes the outermost layer of the bac. Therefore, the "outer membrane-bounded periplasmic space" should be btw the outer membrane and the PGL and we'd need another term for the "GO:NEW1 inner membrane-bounded periplasmic space" btw the inner/plasma membrane and the PGL (where my complex of interest is located).

Further...
3)
GO:0044462 external encapsulating structure part
needs a comment to explain that it includes the periplasmic space, outer membrane and so on...

and
4)
GO:0042597 periplasmic space
should have parent
is_a GO:0030312 external encapsulating structure
part_of GO:0044462 external encapsulating structure part
(I hope I got the relationships right!)

from which would follow that
5)
GO:0098567 periplasmic side of plasma membrane
GO:0031241 periplasmic side of cell outer membrane
GO:0031236 extrinsic component of periplasmic side of plasma membrane
GO:0031237 intrinsic component of periplasmic side of plasma membrane
GO:0031245 extrinsic component of periplasmic side of cell outer membrane
GO:0031246 intrinsic component of periplasmic side of cell outer membrane
should all be
part_of GO:0042597 periplasmic space

Does any of this make sense? I have spend ages trying to understanding this simply because I hadn't realised the periplasm was defined as being "external"! To me it's part of the bacterial cell membrane structure but GO defines everything outside the PLASMA membrane as "external"...

Birgit

**Comment by bmeldal** [comment]
related to issues #12194

**Comment by tberardini** [comment]
@dosumis Again, if you can provide feedback, I can do the work.  Thanks.

**Comment by dosumis** [comment]
> GO:0098567 periplasmic side of plasma membrane
> GO:0031241 periplasmic side of cell outer membrane
> GO:0031236 extrinsic component of periplasmic side of plasma membrane
> GO:0031237 intrinsic component of periplasmic side of plasma membrane
> GO:0031245 extrinsic component of periplasmic side of cell outer membrane
> GO:0031246 intrinsic component of periplasmic side of cell outer membrane
> should all be
> part_of GO:0042597 periplasmic space

Nope.  The side of the membrane that all these components are part of is defined as adjacent_to the periplasm.  They can't also be part of it.  We could use adjacent_to to further formalise the periplasmic space definitions.

### Suggested quick fix for relationship to 'external encapsulating structure'

name: periplasmic space
\+ relationship: part_of 'external encapsulating structure'

But this term is a bit flaky:

"external encapsulating structure": "A structure that lies outside the plasma membrane and surrounds the entire cell."

Periplasm seems to fit the definition, but it is odd to talk about a space as encapsulating something.
Outer membrane also fits the definition, but is currently classified as an external encapsulating structure part, rather than an 'external encapsulating structure' (although it is not clear what external encapsulating structure it is meant to be a part of). It looks to me that 'external encapsulating structure' is intended for non-membranous encapsulating structures such as cell walls.  Might want to modify the definition to make that clear.

### confusion over types of periplasm

I think this definition is fine:

GO:0030288 outer membrane-bounded periplasmic space
"The region between the inner (cytoplasmic or plasma) membrane and outer membrane of organisms with two membranes such as Gram negative bacteria. These periplasmic spaces are relatively thick and contain a thin cell wall."

The periplasm in this case is the whole region between the two membranes, *including* the PGL (referred to here as 'thin cell wall') so it *is* bounded by 'outer cell membrane'.  This could be further formalised as:
intersection_of: periplasmic space
intersection_of: adjacent_to outer-cell membrane
intersection_of: adjacent_to plasma membrane

I suspect your confusion comes from the definition of the sister class, which reads as if it could apply to the inner region of gram negative periplasmic space, but is clearly not intended to:

"cell wall-bounded periplasmic space": "The region between the plasma membrane and the cell wall, as found in organisms such as yeast and Gram positive bacteria. The region is thinner than the equivalent in Gram negative bacteria."

How about: "The region between the plasma membrane and the cell wall in organisms lacking an outer cell membrane such as yeast and Gram positive bacteria. The region is thinner than the equivalent in Gram negative bacteria."
(NOTE - An equivalent class expression in terms of adjacency would work here, for the same reason that the old definition confused you)

If you really need them you could have new terms for inner and outer regions of periplasm, divided by PGL.

inner region of outer membrane-bounded periplasmic space: "The region of an outer membrane-bounded between the plasma membrane and the cell wall (peptidoglycan layer)."

outer region of outer membrane-bounded periplasmic space: "The region of an outer membrane-bounded between cell wall (peptidoglycan layer) and the plasma membrane.'

For both of this you could have:
is_a: 'external encapsulating structure'  # not a very satisfactory classification, but no worse than many related terms

**Comment by bmeldal** [comment]
Thanks, David.

#### periplasmic side of x membrane terms: ####
- Thanks for clearing up my mistake. I'm not fussed about the adjacent_to relationship. It depends if it helps anywhere else. It's not something I can see in the ontology anyway...

#### Suggested quick fix for relationship to 'external encapsulating structure' ####

>Periplasm seems to fit the definition, but it is odd to talk about a space as encapsulating something.
Outer membrane also fits the definition, but is currently classified as an external encapsulating structure part, rather than an 'external encapsulating structure' (although it is not clear what external encapsulating structure it is meant to be a part of). It looks to me that 'external encapsulating structure' is intended for non-membranous encapsulating structures such as cell walls. Might want to modify the definition to make that clear.

Yes, a better def might help here. I am also not quite clear about the difference between "external encapsulating structure" and "external encapsulating structure part"... I'm no expert and don't know what the legacy is with regards to the origin of these terms.

#### confusion over types of periplasm ####

>I suspect your confusion comes from the definition of the sister class, which reads as if it could apply to the inner region of gram negative periplasmic space, but is clearly not intended to:

I hadn't even looked at the def of this term. My confusion came from the fact that the names of the two types of periplasmic spaces were defined by its outer bound. Looking at it now after doing my research the terms make sense but they just weren't intuitive without looking at the structure. And even then I missed the point... I guess that came from the fact I was checking one of Sandra's complexes and she's asked me to make the new GO term and I hadn't looked at ecoli in detail for a while. My knowledge was rusty and I got confused... 

I definitely don't need the child terms now that I understand that "GO:0030288 outer membrane-bounded periplasmic space" defines the space I need.

My gut feeling is that these three terms periplasmic space terms should stay as they are as there won't be too many curators as rusty in bacterial membrane knowledge as I was. I shall never ever forget it again!

Apologies for wasting your time unpicking my brain! trust me, I wasted even more time! But if we can fix the "external encapsulating structure (part)" terms that would be helpful!

Birgit

**Comment by tberardini** [comment]
I'll wait for you two to come to agreement and then can implement any changes.

**Comment by tberardini** [comment]
Following up, @dosumis and @bmeldal, for actions that I should take.  Thanks.

**Comment by bmeldal** [comment]
I think we only need to fix the defs for 'external encapsulating structure (part)' now. And I'm not the person to do this as I can't tell where the original, flaky defs came from and what the best def would be. May consult one of the basc/yeasty experts?

@dosumis?

David cleared up my misunderstanding on the other points :)

**Comment by dosumis** [comment]
> I think we only need to fix the defs for 'external encapsulating structure (part)' now.

'external encapsulating structure': "A structure that lies outside the plasma membrane and surrounds the entire cell."

Options:
1. Make periplasm a subclass of external encapsulation structure
2. Modify external the def of 'external encapsulation structure' so that it excludes periplasm. 

I'm easy with either.

I think it's also worth making my suggested edits to the periplasm terms.

**Comment by tberardini** [comment]
Are these the edits? I vote for modifying the def of ext. encap. structure to exclude the periplasm.

1. change def of 'external encapsulating structure' to exclude periplasm.  "A structure that lies outside the plasma membrane and surrounds the entire cell.  This does not include the periplasmic space."

2. For good measure, update 'external encapsulating structure part' as  well to "Any constituent part of an external encapsulating structure, a structure that lies outside the plasma membrane and surrounds the entire cell. This does not include the periplasmic space."

3. change def of "cell wall-bounded periplasmic space" to: "The region between the plasma membrane and the cell wall in organisms lacking an outer cell membrane such as yeast and Gram positive bacteria. The region is thinner than the equivalent in Gram negative bacteria."

4. remove is_a relationship between 'outer membrane bounded periplasmic space' and 'external encapsulating structure part'

**Comment by bmeldal** [comment]
As David pointed out, we also need to add a comment to the **external encapsulating structure terms** regarding the membership of the outer membrane / cell wall:

>But this term is a bit flaky:

>"external encapsulating structure": "A structure that lies outside the plasma membrane and surrounds the entire cell."

>Periplasm seems to fit the definition, but it is odd to talk about a space as encapsulating something.
Outer membrane also fits the definition, but is currently classified as an external encapsulating structure part, rather than an 'external encapsulating structure' (although it is not clear what external encapsulating structure it is meant to be a part of). It looks to me that 'external encapsulating structure' is intended for non-membranous encapsulating structures such as cell walls. Might want to modify the definition to make that clear.

So I guess we need to:
>1. change def of *GO:0030312 external encapsulating structure* to exclude periplasm. "A structure that lies outside the plasma membrane and surrounds the entire cell. This does not include the periplasmic space."
**and add a comment: "The outer membrane (of gram negative bacteria) or cell wall (of yeast or Gram positive bacteria) are defined as parts of this structure, see 'external encapsulating structure part'."**

and

>2. change def of *GO:0044462 'external encapsulating structure part* to "Any constituent part of an external encapsulating structure, a structure that lies outside the plasma membrane and surrounds the entire cell. This does not include the periplasmic space
**add: but does include the outer membrane (of gram negative bacteria) or cell wall (of yeast or Gram positive bacteria)."**


Changes to **periplasmic space terms**:

1. change def of GO:0030288 outer membrane-bounded periplasmic space to "The region between the inner (cytoplasmic or plasma) membrane and outer membrane of organisms with two membranes such as Gram negative bacteria. These periplasmic spaces are relatively thick and contain **a thin peptidoglycan layer (PGL), also referred to as** a thin cell wall."

2. and add
>intersection_of: periplasmic space
>intersection_of: adjacent_to outer-cell membrane
>intersection_of: adjacent_to plasma membrane

3. change def of GO:0030287 cell wall-bounded periplasmic space to:
>"The region between the plasma membrane and the cell wall in organisms lacking an outer cell membrane such as yeast and Gram positive bacteria. The region is thinner than the equivalent in Gram negative bacteria."
>(NOTE - An equivalent class expression in terms of adjacency would NOT work here, for the same reason that the old definition confused you)

Hope this makes it clear :)

**Comment by tberardini** [comment]
Done. Plus this:

remove is_a relationship between 'outer membrane bounded periplasmic space' and 'external encapsulating structure part'
