### ISSUE TITLE
NTR - NAADP-mediated calcium signaling

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12190]
Many hormones and neurotransmitters evoke changes in cytosolic calcium through production of calcium-mobilizing messengers that, in turn, mobilize intracellular calcium stores.
A crucial role for nicotinic acid adenine dinucleotide phosphate (NAADP) has recently been identified. See reviews:

PMID: 18984909
PMID: 20303271

There is a related MF in GO:
GO:0072345	NAADP-sensitive calcium-release channel activity
but the only related BP is a quite general parent term:
GO:0070588 calcium ion transmembrane transport
I think that we should have a more specific BP, based on the reviews above, something like: 
NAADP-mediated calcium signaling
where the GO:0070588 MF would be part_of this new BP. I think this new BP term would also be child to:
GO:0035584 calcium-mediated signaling using intracellular calcium source
because the calcium mobilised seems to be released from ER and / or lysosomes and other acidic CC such as endosomes.
I would use this term to annotate 
TPCN2 (Q8NHX9)
NB this protein is described in UniprotKB as:
“Nicotinic acid adenine dinucleotide phosphate (NAADP) receptor that may function as one of the major voltage-gated Ca2+ channels (VDCC) across the lysosomal membrane.” 

GOC:PARL
GOC:pad

**Comment by dosumis** [comment]
Hi Paul,

Working on closely related terms for synapse project.  Agree that MF terms need to be partially defined by BP context indicating release from IC source.  Important to co-ordinate fix with fix for this.

cheers,
David

**Comment by Pauldenny** [comment]
Great - thanks David.

**Comment by tberardini** [comment]
reassigning to you, DavidOS

**Comment by dosumis** [comment]
I've worked on this part of the ontology since this request was made.  We now have:

release of sequestered calcium ion into cytosol
.  <- part_of calcium release channel activity
.  . <- is_a NAADP-sensitive calcium-release channel activity

I have my doubts about this term: "calcium-mediated signaling using intracellular calcium source" as the signalling is the same irrespective of source.  However this is now a link to this term:

release of sequestered calcium ion into cytosol
. <- starts_with calcium-mediated signaling using intracellular calcium source

starts_with is a subproperty of has_part

cf: #7999
