### ISSUE TITLE
protein anchor, protein binding, bridging

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12204]
I am annotating a protein anchor
GO:0043495 - protein anchor 
Definition: "Interacting selectively and non-covalently with both a protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific location on the membrane." [GOC:go_curators]

 GO:0060090 binding, bridging
The binding activity of a molecule that brings together two or more molecules through a selective, non-covalent, often stoichiometric interaction, permitting those molecules to function in a coordinated way.

well, i'm not sure. This does not specify that one of the molecules can be a macromolecule, biut the descendent term
GO:0030674
Name	protein binding, bridging

does.....

**Comment by paolaroncaglia** [comment]
Hi Val,

I don’t really see any major problem with GO:0030674 ‘protein binding, bridging’ being an is_a child of GO:0060090 ‘binding, bridging’. We could extend the def of the latter to be extra-clear and read “The binding activity of a molecule that brings together two or more molecules (including macromolecules)…”, if you think that would help. Rather, I see a problem with GO:0043495 ‘protein anchor’ being is_a ‘protein binding’. The former is defined as “Interacting selectively and non-covalently with both a protein or protein complex *and* a membrane, in order to maintain the localization of the protein at a specific location on the membrane.”. Therefore, the link should be ‘protein anchor’ has_part ‘protein binding’! (and has_part ‘membrane binding’ if this existed.)

This is also related to your freeform TG request:

[Term]
id: GO:1990919
name: nuclear membrane proteasome adaptor
namespace: molecular_function
def: "Interacting selectively and non-covalently with a proteasome complex and a nuclear inner membrane, in order to maintain the nuclear membrane localization of the proteasome." [PMID:16096059]
subset: termgenie_unvetted
synonym: "nuclear membrane proteasome anchor" RELATED []
synonym: "tethering factor for nuclear proteasome" RELATED []
is_a: GO:0043495 ! protein anchor
relationship: part_of GO:0060090 ! binding, bridging
created_by: vw
creation_date: 2015-12-14T14:01:45Z

Looking at existing ‘adaptor’ terms, living under ‘protein binding, bridging’, I’d suggest to rename your term as ‘nuclear membrane proteasome adaptor activity’ (keeping ‘nuclear membrane proteasome adaptor’ as a related synonym). As for the part_of link to ‘binding, bridging’, I don’t think that’s necessarily true if you look at this bit in the def of ‘binding, bridging’: “…permitting those molecules to function in a coordinated way”. I guess the proteasome *needs* to be anchored to the nuclear membrane in order to carry out its functions accurately, but the nuclear membrane function/role will not benefit particularly from the membrane being ‘coordinated’ (connected) with the proteasome, right?

Is this opening a can of worms by any chance? :-(

Paola

**Comment by ValWood** [comment]
Hi Paola,
You are right. Scrub all the part about the bridging connection.

I think the protein binding bridging terms are describing "adaptors"

This isn't really an adaptor, its just an anchor.
So a better term name would be
"nuclear membrane proteasome anchor"

Does that make sense?

**Comment by paolaroncaglia** [comment]
OK, thanks. I'm committing your term as below, and will now close this ticket. Cheers!

id: GO:1990919
name: nuclear membrane proteasome anchor
namespace: molecular_function
def: "Interacting selectively and non-covalently with a proteasome complex and a nuclear inner membrane, in order to maintain the nuclear membrane localization of the proteasome." [PMID:16096059]
synonym: "nuclear membrane proteasome adaptor" RELATED []
synonym: "tethering factor for nuclear proteasome" RELATED []
is_a: GO:0043495 ! protein anchor
