### ISSUE TITLE
ovule development label

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12247]
Hi Tanya,

I saw this new term and was wondering if it would make sense to rename to "plant ovule development"?
Same for ovule morphogenesis, ovule primordium and specification of ovule identity. Assigning to you, but if it helps I'm happy doing the edits.

Cheers,
Melanie

**Comment by tberardini** [comment]
Which new term?  'ovule development'? It's been around since 2004!  In any case, I don't think it's necessary to prefix the terms with the word 'plant', unless you can find other uses in the literature where ovule does not refer to a plant structure.

Thanks for checking in,

Tanya

**Comment by paolaroncaglia** [comment]
Hi Tanya,

I share Melanie's concern because, in non-anglosaxon languages, the word to indicate the *mammalian* egg cell is indeed 'ovule', same as for plants in English. (I believe it is exactly 'ovule' in French; 'ovulo' in Italian). Possibly for this reason, that is to disambiguate, the UBERON term that GO 'ovule development' links to is called 'plant ovule' (http://purl.obolibrary.org/obo/PO_0020003).
Yes, 'ovule development' is an old term :-) I think Melanie was referring to having just noticed it in one of the latest assert reports.

Hope this helps, thanks,
Paola

**Comment by cmungall** [comment]
GO labels implicitly have "@en" on them. Would love to support other languages in the future. When we do, I think the rule should be that labels are exact syns are unique *within* a language.

To me "ovule" is clearly plant, we don't have this as a label or syn in the (metazoan) CL or Uberon, 

Seems to only return plant papers:
http://europepmc.org/search?query="ovule+development"

PO isn't very consistent about where it prefixes terms, I've argued against some the prefixes in the past, and there are cases where prefixes are required for disambiguation, e.g. [PO:0005679](http://purl.obolibrary.org/obo/PO_0005679) ! epidermis

I'm sympathetic to getting tripped up by this due to shared etymology with latin in Romance languages. But isn't this a huge problem all over? So much of biology is latin terms named for analogy to something else. I suppose context helps a lot. You wouldn't expect to find "knee tumors", "horse sea monsters" or "spider mothers" in the brain (geniculate ganglion, hippocampus and arachnoid mater), outside of a bad nightmare. But there must be lots of other cases where the analgous term is close enough to trip us over. I'm too ignorant of other languages to know, but am interested in addressing this if it's a systematic problem.

**Comment by paolaroncaglia** [comment]
Ah, languages… I don’t think there is a big systematic ambiguity problem in GO. Possibly, exactly because most anatomical terms share the same Latin root. Personally I find ‘ovule’ terms confusing at first but I’d have no trouble leaving them as are provided that the necessary taxon constraints are in place. That should make it immediately clear to curators how to use or not to use the term. But at the moment, there is no ‘only in plants’ for ‘ovule development’ or ‘ovule morphogenesis’. Upstream, the PO terms ‘plant ovule’ and ‘ovule primordium’ don’t have taxon rules themselves… but even if they had, I believe we wouldn’t inherit them. Looks like a compromise fix would be to add the taxon rule to GO ‘ovule development’ and ‘ovule morphogenesis’ (‘specification of ovule identity’ would inherit it from the latter).

Thanks,
Paola

**Comment by mcourtot** [comment]
Thanks all for the very useful feedback; I did not expect quite such enthusiasm on adding or not prefixes to labels :)

I do agree that the prefix 'plant' in this case is unambiguous in english, but it wouldn't be such a huge addition and could be helpful to curators: we did spend quite a bit of time at the last annotation call discussing non-english papers and annotations, and our community is clearly multi-language.

We should at a minimum make the use within GO consistent, as we also have existing terms for 'plant ovule micropyle' and 'plant ovule'.

**Comment by cmungall** [comment]
> Looks like a compromise fix would be to add the taxon rule to GO 
> ‘ovule development’ and ‘ovule morphogenesis’ 
> (‘specification of ovule identity’ would inherit it from the 
> latter).

+1

**Comment by tberardini** [comment]
I added the taxon constraints for the two terms *and* added the word 'plant' in front of ovule to reflect the PO term which also is 'plant ovule', as someone mentioned before.  Should be all good now.
