### ISSUE TITLE
phase relationship has been deleted? mitotic anaphase part_of mitotic M-phase 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12242]
2015-10-30	Deleted	RELATION	part of GO:0000087 (mitotic M phase)

**Comment by ValWood** [comment]
also
 GO:0000089 mitotic metaphase
 GO:0000093 mitotic telophase
GO:0051329 mitotic interphase
 GO:0000236 mitotic prometaphase

**Comment by dosumis** [comment]
Hmmm. I have a horrible feeling we're going round in circles on this.

**Comment by mah11** [comment]
in some of the OBO files they've been changed to happens_during, but that relation isn't written out to the simpler versions ... I don't know which version QuickGO loads ...

**Comment by mah11** [comment]
e.g. go.obo has

[Term]
id: GO:0000090
[snip]
is_a: GO:0051322 ! anaphase
is_a: GO:0098763 ! mitotic cell cycle phase
relationship: happens_during GO:0000087 ! mitotic M phase

**Comment by ValWood** [comment]
could also be part of. These are smaller phases which are part of larger phases.

The important thing is not to get part_of links between phases and processes.....

**Comment by dosumis** [comment]
The change to happens_during was discussed here:

https://github.com/geneontology/go-ontology/issues/11992 (Ticket all done except for the obsoletion of '**Meiotic** M-phase I & II')

Related issue: https://github.com/geneontology/go-ontology/issues/12120

This has the comment: "Following discussion in email: I'll switch back to PO between phases so that relationships between phases are displayed in QuickGO/Amigo. Meiotic phase I and II classification will need to be asserted, but this is no big deal. I'll manually remove is_inferred tags."

I'm not sure what email that refers to, but it's no big deal to change them back to part of.  I've scrapped most of the timing based reasoning that I added these for in the first place.  I guess the original concern was over part_of links between phase and process terms. On that topic, some part relationships seem to have crept back in.  

![image](https://cloud.githubusercontent.com/assets/112839/12422292/1446137e-bebe-11e5-9e35-54ad5e0573e7.png)
Will fix.
No sign of the disjointness axiom I added to prevent this.  Will try to add again now.

**Comment by dosumis** [comment]
* Switched back phase:phase relationships to part of.  
* Removed inferred flag on meiosis I and II sub-phases
* Fixed phase:process po link by changing to happens_during:
![image](https://cloud.githubusercontent.com/assets/112839/12422865/d7006778-bec0-11e5-828c-930fd35958f0.png)
* Added GCI: 'cell cycle process' disjoint_with 'part of' some 'cell cycle phase'
* Working on obsoletion notice (see #11992 for any follow up).
