### ISSUE TITLE
how far do we want to go in terms of specificity to represent activity classes?

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12257]
Prompted by original discussion from @ValWood at https://github.com/geneontology/go-ontology/issues/12184
@thomaspd commented that "An activity should not be named after a gene product, as a gene product could potentially have multiple molecular functions and not just the one it's named after. Also, protein phosphatase inhibitor means "directly [i.e. via direct physical interaction] inhibits some protein phosphatase activity", not "directly inhibits some protein named protein phosphatase 2A"-- properly speaking you don't inhibit a protein, you inhibit the activity of a protein."

This was discussed briefly during the GO editors call: http://wiki.geneontology.org/index.php/Ontology_meeting_2016-01-28#TermGenie_review_queue

While attendees were in general in agreement with the above, @tberardini pointed to cases in which we may want to keep the specificity, such as http://amigo.geneontology.org/amigo/term/GO:0018024#display-lineage-tab

@thomaspd, do you want to take a stab at writing some guidance, perhaps in a google doc, and we can then collect cases and hopefully reach consensus? There are multiple places where this appears, e.g. deubiquitinases etc, so it would be useful to have clear guidelines before doing any major refactoring.

**Comment by ValWood** [comment]
I was going to say that histone modifications should be a special case because of the histone code. Possibly the  RNA polymerase II CTD phosphatase, but this is trickier as not conserved across species in the same way and is a heptad repeat, so possibly not....

I would *love* to get rid of many of these terms as it makes community curation confusing.... people can never be sure if they are supposed to request new terms  or not.

Also, the  gene pages look a mess, (although I'm probably overly fussy about this too....)
You can describe cdc2 as
cyclin-dependent protein kinase activity
protein kinase activity
protein serine/threonine kinase activity
protein serine/threonine phosphatase inhibitor activity

but it really describing the same activity
http://www.pombase.org/spombe/result/SPBC11B10.09#go-molecular_function
What you gain by the additional detail (which we capture, when known on the modified molecule), just makes the annotation look way more confusing than it needs to.

Also its good to have a way to capture dependencies, but is the GO term the best way to do this?

I'd by happy to collate a list of 'types' that should be considered getting rid of for consideration.....
It might be useful to see if this overlaps with Paul's function overhaul.

**Comment by tberardini** [comment]
Wdrt the histone methyltransferases, it appears that there are indeed differences in specificities of the different enzymes so that some methylate K or R and very specific K or R residues.  So the activities and mechanisms appear to be distinct, which, I think warrants having the separate terms.

 http://dx.doi.org/10.1016/S1097-2765(03)00479-9

**Comment by ValWood** [comment]
Yes you are right. That should be the  criteria .Many existing  terms are to capture an absence of knowledge (we don’t know which family member so we’ll create a “gene family term”. This doesn’t help, the function and process is so context-dependent, if you aren’t assaying the correct thing in the correct organism, you can’t say anything useful more specific than “protein phosphatase activity anyway”. We need accurate specificities, not fuzzy generalisations.

That said for the cases where the protein assayed is from a different species, but it is intended to represent the same protein in the species being studied there should be a  way to capture this  with an evidence code (inferred from interaction with  endogenous protein, or such like) OR, if its the same species but you don’t know which actual gene product, a PRO ID. There should be a way to do it if it’s required, but not  using a GO term.

**Comment by paolaroncaglia** [comment]
Hi Melanie,

I'll assign this ticket to you if that's ok? So it doesn't get lost. Thanks,

Paola

**Comment by mcourtot** [comment]
Can't seem to assign to @thomaspd. This may be worth discussing at the upcoming GO meeting?

**Comment by ValWood** [comment]
@pgaudet  since this is in hand should we close this ticket?

**Comment by pgaudet** [comment]
Yes :)
