### ISSUE TITLE
GO to EC links - should they always be there?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12263]
I'm curating the VPS4 complex [e.g. Q9UN37 (VPS4A_HUMAN), O75351 (VPS4B_HUMAN)] which has 

GO:0016887 ATPase activity, probably even GO:0042623 ATPase activity, coupled.
(It dissociates the ESCRT-III complex at the end of membrane fission to facilitate recycling of its components)

It is also annotated to EC 3.6.4.6 Vesicle-fusing ATPase in UniProt and I agree this is correct.
(Def: A large family of ATP-hydrolysing enzymes involved in the heterotypic fusion of membrane vesicles with target membranes and the homotypic fusion of various membrane compartments. They belong to the AAA-type (ATPase associated with a variety of cell activities) ATPase superfamily.)

But there is no link between the GO and the EC term. Should I create a new GO child to match EC 3.6.4.6 Vesicle-fusing ATPase?

Thanks,
Birgit

**Comment by paolaroncaglia** [comment]
Aha: searching the ontology with the string '3.6.4.6' retrieves this:

[Term]
id: GO:0008576
name: obsolete vesicle-fusing ATPase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the reaction: ATP + H2O = ADP + phosphate. The hydrolysis of ATP by an AAA-ATPase, involved in the heterotypic fusion of membrane vesicles with target membranes and the homotypic fusion of various membrane compartments." [EC:3.6.4.6]
comment: This term was made obsolete because it incorporates process information.
synonym: "vesicle-fusing ATPase activity" EXACT []
is_obsolete: true
replaced_by: GO:0042623
consider: GO:0016192
consider: GO:0061025

So the obsoleted term was replaced by 'ATPase activity, coupled'. The way EC:3.6.4.6 is phrased makes it out of scope for representation in GO, but I could add a RELATED synonym to 'ATPase activity, coupled' for "vesicle-fusing ATPase activity" with xref EC:3.6.4.6. How's that?

**Comment by bmeldal** [comment]
I saw the obsoleted term. A related synonym would at least tie them together, that would work.

**Comment by paolaroncaglia** [comment]
Done.
