### ISSUE TITLE
receptor agonist activity ; GO:0048018

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12272]
The term 'receptor agonist activity ; GO:0048018' seems under-used. It's currently a child of 'receptor binding' but I wonder if it should also be linked up to some of the other 'activity' terms under 'receptor binding': 

cytokine activity ; GO:0005125
growth factor activity ; GO:0008083
hormone activity ; GO:0005179
pheromone activity ; GO:0005186

Are all cytokines, GFs, hormones and pheromones agonists (or do some act as antagonists)? If we can't move them under GO:0048018, I think we should at least add a comment under these terms to consider also annotating to GO:0048018.

Thanks.

**Comment by rebeccafoulger** [comment]
For now: added a comment to consider annotating to 'receptor agonist activity' to:
cytokine activity ; GO:0005125
growth factor activity ; GO:0008083
hormone activity ; GO:0005179
pheromone activity ; GO:0005186
receptor binding ; GO:0005102
chemokine activity ; GO:0008009

**Comment by vanaukenk** [comment]
Reopening this ticket as it is relevant to the upcoming signaling workshop.

**Comment by RLovering** [comment]
good plan 
Ruth

**Comment by hattrill** [comment]
morphogen activity GO:0016015 should probably go under receptor agonist activity as well.
see  doi: 10.1242/dev.01043 Morphogens, their identification and regulation for description.

**Comment by hattrill** [comment]
Are receptor agonist activity child_of receptor activator activity

Are these equivalent or are they distinct?

GO:0030546 receptor activator activity
Definition: The function of interacting (directly or indirectly) with receptors  such that the proportion of receptors in the active form is increased.

GO:0048018 receptor agonist activity
Interacts with receptors such that the proportion of receptors in the active form is increased. 


-receptor activator activity
--acetylcholine receptor activator activity
--receptor agonist activity
---death receptor agonist activity
--thyroid hormone receptor activator activity
---thyroid hormone receptor coactivator activity
--transmembrane receptor protein tyrosine kinase activator activity
--vitamin D receptor activator activity

Most exp annotations to children of receptor activator activity are EC ligands.

receptor activator activity is_a positive regulation of receptor activity
and
receptor agonist activity is_a GO:0004871 signal transducer activity

Therefore ligands annotated with "receptor agonist activity" are regulating the pathway they are in and have signal transducer activity, both of which are at odds with the current guidelines.

**Comment by pgaudet** [comment]
Hi @hattrill 

It does sound like these 2 terms are equivalent, although I can imagine that a receptor activator could be another regulator (for example by a PTM). But since it has not been used this way, we could merge the term and think about how to deal with other types of activators as we come across examples.  

We should also remove the link between "receptor agonist activity" and positive regulation of receptor activity'. To be clear we could also add to the definition 'The function of interacting (directly or indirectly) with receptors such that the proportion of receptors in the active form is increased.' something like, "thus initiating the signaling pathway", and even a comment such as "for receptor-dependent signaling pathways, ligand binding to its receptor is considered the first step of the pathway. 

What do you think ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Hi Pascale,
Sorry was away the last couple of days -

What I will do is go through all the examples where agonist/activator has been used (thankfully, not that many) and check that the broad assumption is true and highlight any outliers.
Agree with changing the definition to something that clearer, less pharmological and includes that the activation of a recrptor = signaling. 
I will check out a few a questions regarding this: 1. should the binding be direct (not sure whether indirect agonists exist)?; 2. can all biological agonists be decsribed as "ligands"?

**Comment by hattrill** [comment]
Had a look at experimental annotations to "receptor agonist activity" (and children of) and "receptor activator activity" (and children of, excluding agonist branch). 
see: https://docs.google.com/spreadsheets/d/15HcC6LFgOhA-BdQHvKMRjk3e-uIaGvitD5xH8Qzdkpk/edit#gid=0

Everything annotated with "receptor agonist activity" is either in a class expected to acts act or does act as an extracellular ligand for a cell surface receptor. Looks like where this term has been used, it has been used correctly and consistently, just not very often! 

"receptor activator activity": a pretty mixed bunch:
-A lot of nuclear receptor coactivators - a lot look like transcriptional coactivators/regulators
- some receptor regulators: direct and indirect
-allosteric effectors
-receptor agonists

So, looks like it is not possible to merge these terms.

**Comment by pgaudet** [comment]
Thanks for looking into this @hattrill 
It looks like the 'agonist' meant ligand and the 'activator' also includes other types of activations, is this correct ? 

We could probably improve the definitions to make that clearer? 

Pascale

**Comment by hattrill** [comment]
Yes. I think improving the definitions would be a good start and encouraging people to move the genuine ligand-receptor interactions to agonist. We need some discussion in the GOC about what constitutes an activator and what is a positive regulator and whether the distinction is valid.

Whoever claims the nuclear hormone signaling pathways should take a look at whether coactivators in this context should be receptor activators/regulators or transcription factor coactivators.

**Comment by ukemi** [comment]
"ligand' was always a bit controversial back in the early days, that is why there is no specific term for it. Too many people equated it with any type of binding. That's is why generally it is a synonym of the various binding terms without specificity as to the action of the binding. If I recall correctly, you are correct that the agonist terms were meant to be the physiological signals that activated receptors by binding to them. I think part of the issue here is that curators search on 'blah ligand' and return the binding terms and stop there without looking for the agonist activity. Maybe adding the 'ligand' terms as broad synonyms would help in annotation?

I would say that an agonist is more specific than an activator. I bet we can come up with examples of activators that enhance the activity of a receptor, but are not 'ligands' in the signaling sense. Also looking at the definitions of some of the activator terms, they use the either directly or indirectly phrasing. So activators seem to include anything that can positively regulate a receptor, even a few steps away.

**Comment by hattrill** [comment]
"Maybe adding the 'ligand' terms as broad synonyms would help in annotation?" - yes, think that we need to have it spelt out somewhere.

As for activator: yes, it has been used to describe a variety of activities - from allosteric activators to proteins that regulate the expression of the receptor itself. It has also been used for agonists. (examples in google doc linked above). IMO it causing too much mischief!

**Comment by ukemi** [comment]
But then how do we capture stuff like this? PMID:26303340

**Comment by hattrill** [comment]
Use a GO-CAM ;)

....I guess we need to get down in the weeds, especially wrt allosteric activators/regulators. If we want to keep "activator", then we need to make some distinction between an activator and a positive regulator.

**Comment by pgarmiri** [comment]
Hi All,

I would be very interested in the outcome of this discussion. In particular, in suggestions how to capture the effect of a ligand (annotated with  GO:0048018  receptor agonist activity) to the downstream steps of a process of  a different cell/ organism in Protein2GO.

    Would regulation terms be suitable or the binding to the receptor is considered the first step of the process and thus annotations to downstream steps redundant? Wouldn't we missing pathway related information is this case?

    Could annotation extensions be used to clarify that this is 'happening_during' a particular pathway and 'occur_in' the cell/organism that the signalling effect is seen?

This is related to my comment in Obsoletion ticket for 'multi-organism signaling' (https://github.com/geneontology/go-ontology/issues/14021 ) and my example is ZP3.

"ZP3 is an membrane protein of the oocyte that binds to a sperm receptor and regulates processes in sperm like the acrosome reaction. Below are some figures that display the signaling events.

http://www.cellsignallingbiology.org/csb/008/csb008fig8_ZP3_induced_Ca_signals.htm

http://www.nature.com/ncb/journal/v3/n2/fig_tab/ncb0201_e59_F3.html "
Annotations to 'GO:0060046 regulation of acrosome reaction' have been acceptable so far, but what about the effect on other steps occurring in the sperm, such as phosphatidylinositol biosynthetic process, calcium ion import and manganese ion transport?

I hope I don't divert the topic too much.

Thanks,

Penelope

**Comment by ValWood** [comment]
I think this can close?
All of the term Becky mentioned are under
GO:0048018    receptor ligand activity
related synonym "receptor agonist activity"

If anyone wanted anything else out of this ticket (I scanned it but I could not see anything), please open a new ticket and refer it back to this one.
This one is too long to read.
