### ISSUE TITLE
TPV  SRP-dependent cotranslational protein targeting to membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12285]
Gene products annotated to 
 SRP-dependent cotranslational protein targeting to membrane
are also annotated to membrane organization becasue of this parentage:

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006614#term=ancchart

(some proteins are transferred into the ER lumen and these do not affect membrane organization)

I'm not sure what the fix is, I guess not all protein localization to membrane is membrane organization.
Although the problem *could be* the "protein localization to membrane" term.

**Comment by tberardini** [comment]
Val, I think that the problem may be in the annotations, not in the ontology structure.  Can you check please?   From the way the terms are defined, it seems clear to me that the protein targeting/localization to the membrane means that they stay there.  Otherwise, I'd expect a targeting/localization term to the lumen/cytoplasm/other cellular component on the other side of the membrane.

**Comment by ValWood** [comment]
Hmm, I think its the wording of the term. I'm sure we discussed this before and came to the opposite decision. The SRP receptor targets the ribosome to the ER membrane so that the translated proteins can be delivered to the membrane or the lumen?
I think this is part of a more general issue with the term 'targeting' (lots of tickets about this)

I'll see if I can find the old SRP tickets where this was discussed.....

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/11908
duplicate ;)
