### ISSUE TITLE
NTR:intermicrovillus adhesion/organisation

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#12284]
Dear GO editors,
this paper PubMed=24725409, describes the role of CDHR5 and CDHR2 in brush border differentiation. Both proteins make heteromeric inter-microvillar bridges that control microvilli clustering and length. I could find the GO term microvillus organization/GO:0032528 but I am not sure it can be applied to a process that involves an interplay between several microvilli. I would suggest to create the terms intermicrovillar adhesion and brush border differentiation but I am not sure.
Could you please help me.
Thanks,
Lionel

**Comment by tberardini** [comment]
Hi Lionel,

I agree that 'microvillus organization' is not the right term because it only refers to one, while the paper talks about the assembly of many microvilli.  I created this term for you:

[Term]
id: GO:1904970
name: brush border assembly
namespace: biological_process
def: "The aggregation, arrangement and bonding together of adjacent microvilli through the formation of Ca(2+)-dependent adhesion links between them, forming a brush border." [GO_REF:0000079, GOC:lb, GOC:TermGenie, PMID:24725409]
synonym: "brush border formation" EXACT [GOC:TermGenie]
is_a: GO:0022607 {is_inferred="true"} ! cellular component assembly
intersection_of: GO:0022607 ! cellular component assembly
intersection_of: results_in_assembly_of GO:0005903 ! brush border
relationship: results_in_assembly_of GO:0005903 {is_inferred="true"} ! brush border
created_by: tb
creation_date: 2016-02-17T00:58:30Z

Do you think you still need the additional term 'intermicrovillar adhesion' or is this sufficient?

**Comment by lbreuza** [comment]
Hi Tania,
thanks a lot for the new term, it will be very useful. However, I still would like to express the fact that those proteins are involved in an intracellular/intraorganelle/intracompartment "adhesion".  When on think of adhesion it is more intercellular or cell-substrate adhesion and this mechanism seems very original. I was thinking of a term similar to cell adhesion.
I do not know if it makes sense to you.
Thanks for your help,
Lionel

**Comment by lbreuza** [comment]
Hi Tania,
That sounds reasonable.
Thanks.

**Comment by dosumis** [comment]
Rather than broaden this to apply to any sub-cellular component, can we instead constrain it to refer to _intracellular_ attachment between membranes.

**Comment by tberardini** [comment]
Please suggest a better def.  Reading the current one, it doesn't clearly apply to cell-cell adhesion, which is a descendant term.  

"The attachment of a cell or organism to a substrate or other organism." 

Maybe:

"The attachment of a cell or organism to a substrate, another cell, or other organism or intracellular attachment between membranes or membrane parts." 

Bleh.  Needs help.

**Comment by dosumis** [comment]
"intracellular attachment between membrane regions" ?

**Comment by tberardini** [comment]
The attachment of a cell or organism to a substrate, another cell, or other organism. Biological adhesion includes intracellular attachment between membrane regions.

**Comment by lbreuza** [comment]
Hi Tania,

the same group (PubMed=26812018) and other PubMed=26812017, characterize a new complex IMAC intermicrovillar adhesion complex composed of ANKS4B, MYO7B, USH1C and CDHR2 or CDHR5 in the brush border which is involved in brush border assembly.
Maybe one could also create a GO term for that complex. Additional proteins are probably still to be identified.

Thanks for your help.
Lionel

**Comment by tberardini** [comment]
I've modified the definition of biological adhesion as discussed and added the following term:

As for your request for a new protein complex term for IMAC (intermicrovillar adhesion complex), please see the guidelines for creating new complex terms:

http://wiki.geneontology.org/index.php/Guidelines_on_'protein_complex'_terms

Thanks,

Tanya

**Comment by lbreuza** [comment]
Thanks Tania,
I have annotated the 2 protocadherin with GO:0090675 intermicrovillar adhesion and the protein binding their cytoplasmic part and required for BB assembly with GO:1904970 brush border assembly.

For the IMAC complex, I have read the documentation and understood that there is not yet sufficient evidences to create it. Maybe in the future but I guess it will be difficult to purify such a complex.
Thanks for your help

**Comment by tberardini** [comment]
You're welcome, Lionel.  I will close this ticket now.
