### ISSUE TITLE
CVT (cytoplasm-to-vacuole targeting) to become a child of autophagy

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12289]
GO:0032258 CVT pathway
In discussions with 
@marcfeuermann
@ukemi 
@RLovering 
@paolaroncaglia 
and based on expert advice and also PMID: 20146925 
we agreed that CVT (cytoplasm-to-vacuole targeting) should become a child of autophagy
GO:0006914 autophagy

GOC:pad
GOC:PARL

**Comment by ValWood** [comment]
This parentage  doesn't fit the current def

CVT pathway
Definition	A constitutive biosynthetic process that occurs under nutrient-rich conditions, in which two resident vacuolar hydrolases, aminopeptidase I and alpha-mannosidase, are sequestered into vesicles; these vesicles are transported to, and then fuse with, the vacuole. This pathway is mostly observed in yeast. 
PMID:12865942 PMID:15659643

because autophagy isn't constitutive. 

If this  pathway is not relevant for other  types of vacuolar targeting the def needs to be revised (I previously thought this part of the autophagy pathway was shared with cvt targetting, rather than being a 'part' of it. Although the part_of relationship is consistent with our existing annotations (all genes annotated to GO:0032258 for pombe are also annotated to autophagy).

**Comment by ukemi** [comment]
Hi Val,

I think we need to discuss this on the autophagy call again. It is ok if all the gene products are annotated to both if their function is shared in both processes. 
-D

**Comment by ValWood** [comment]
I was thinking about this some more. I don't think the relationship is OK.

Yes, all genes involved in the CVT pathway  are also involved in autophagy.
However, I'm pretty sure that this pathway is used for other modes of CVT (cytoplasm to vacuole targeting), other than for autophagy. Its just that this part of the pathway is *shared* with autophagy.
I don't know much about this pathway so I'll ask SGD to comment

**Comment by ValWood** [comment]
OK lets get into the time machine....
https://github.com/geneontology/go-ontology/issues/3453

**Comment by ValWood** [comment]
Now not so sure, this was later,
https://github.com/geneontology/go-ontology/issues/5058

**Comment by ukemi** [comment]
In the ontology as it stands, autophagy has_part cellular catabolic process. This relation would have to be removed if the CVT pathway becomes a type of autophagy. 

-D

**Comment by Pauldenny** [comment]
Klionsky in PMID: 20146925 says "The Cvt pathway ... [uses] much of the same machinery as autophagy". This review doesn't mention last stage, after fusion of autophagosome with lysosome, of degradation of cargoes in the vacuole / lysosome, except to mention that Atg15 in yeast is probably a lipase. So "cellular catabolic process" isn't mentioned. However, in a review on macroautophagy from same group ("The machinery of macroautophagy" PMID: 24366339 , 2014) abstract states: "Autophagy is a primarily **degradative** pathway that takes place in all eukaryotic cells" and also "Following delivery to the vacuole or lysosome, the cargo is **degraded** and the resulting macromolecules are released back into the cytosol for reuse". SO, perhaps, although Klionsky likes to call CVT a type of selective autophagy, as Val says, we need to keep CVT as being distinctive and NOT become a child of autophagy?

**Comment by ukemi** [comment]
I second this. Most of the articles I have seen say it is autophagy-like, but seem to be careful about going any further. I think Val is correct that they processes share machinery, but are distinct processes.

**Comment by ukemi** [comment]
Since we already have a specific CVT vesicle term in the ontology, it doesn't make sense to entangle this with the autophagosome. I think that this means that we CAN specify that all autophagosomal processes are part of macroautophagy and that macroautophagy is distinguished by the presence of autophagosomes. Makes things cleaner in the long run but will require co annotation of components that are shared in the macroautophagy and CVT pathways.

**Comment by Pauldenny** [comment]
Based on 3 reviews (from different authors) PMID: 20146925
"The Cvt pathway has only been characterized in yeast, specifically S. cerevisiae and P. pastoris, and is **not evolutionarily conserved** [95]. Even in fungi, there are certain differences, in that P. pastoris uses the two proteins PpAtg26 and PpAtg28 [96]; S. cerevisiae Atg26 is not involved in autophagy, and there is no ortholog of PpAtg28."
and Fig 5 in review PMID: 21189453
"Selective autophagy in yeast. (A) Atg19 is acting as a cargo receptor in the Cvt pathway."
and 
PMID: 18362514
"The cytoplasm to vacuole targeting (Cvt) pathway is an
autophagy-like pathway specific to yeast. "
I think GO:0032258	CVT pathway should be taxon restricted to yeasts. 
GOC:PARL
GOC:pad

**Comment by ukemi** [comment]
+relationship: only_in_taxon NCBITaxon:147537 ! Saccharomycotina

Sorry Paul. No xrefs on taxon constraints.

**Comment by Pauldenny** [comment]
I didn't think there were, but just trying to get the habit engrained!

Best,
Paul
On 3 May 2016, at 21:42, David Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


+relationship: only_in_taxon NCBITaxon:147537 ! Saccharomycotina

Sorry Paul. No xrefs on taxon constraints.

-

**Comment by ValWood** [comment]
One of our community has just mentioned that pombe does not have CVT pathway, and we have annotations (based on orthologs).
I guess we will get alerts soon because of the newly applied taxon restriction.

However, I'm a little confused by some of this.

Maybe the def could be improved:
A constitutive biosynthetic process that occurs under nutrient-rich conditions, in which two resident vacuolar hydrolases, aminopeptidase I and alpha-mannosidase, are sequestered into vesicles; these vesicles are transported to, and then fuse with, the vacuole. This pathway is mostly observed in yeast. 
PMID:12865942 PMID:15659643

1.
maybe should say
"A constitutive saccharomytina specific  process"
remove mostly in yeast (is ONLY in SOME yeast)

2.  why is it biosynthetic pathway? presumably its degradative?

3. Are the mentioned targets the only targets, whenever this pathway occurs (if not strange to make the target genes part of the def?)

4 exact synonyms
exact	cytoplasm to vacuole targeting
exact	cytoplasm-to-vacuole targeting
should these be "related"  because presumably cytoplasm to vacuole targeting occurs in other contexts in other species. In fact I think the term name needs to be clearer about what the differentia is for  this 'taxon restricted" version of  "targeting of cytoplasmic proteins to the vacuole"

It seems that the definition captures specificities about the process like the conditions it occurs under in  certain species and the targets.

Reopening...will also ask someone from SGD to enlighten us....
