### ISSUE TITLE
short-term synaptic potentiation

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12299]
From TermGenie Freeform request:

[Term]
id: GO:1990926
name: short-term synaptic potentiation
namespace: biological_process
def: "A process that modulates synaptic plasticity at synapses with a low initial release probability and is caused by influx of Ca(2+) into the axon terminal after spike generation, increasing the release probability of neurotransmitters." [PMID:11826273, PMID:26738595]
subset: termgenie_unvetted
synonym: "synaptic facilitation" EXACT []
is_a: GO:0048167 ! regulation of synaptic plasticity
created_by: sp
creation_date: 2016-02-12T13:17:18Z

A reasonable term and a couple of good refs, but definition needs some work.

CC @vhinard

**Comment by dosumis** [comment]
Some notes:

* We need a simpler description of activity-dependent increase in synaptic strength ('modulating synaptic plasticity' might work for insiders, but for everyone else, it obfuscates a relatively simple story).
* The definition needs some mention of the timescale, to distinguish it from LTP.
* We need to be careful about overloading the definition with mechanistic details that may still be controversial  ( residual calcium vs increased sensitivity to

**Comment by vhinard** [comment]
Hi David, 
Do you suggest this term "short-term synaptic potentiation" in regard to my request of "neuronal excitability" that became "regulation of synaptic strength" as a substitute?

If this is not the case, please, tell me how I can help you, and forget the rest of the message.

But, if this is the case, I realize that the suggestions are going in a different direction of what I wanted to capture. My apologies for giving a bad suggestion with "synaptic strength".

I only wanted to capture the concept of "neuronal excitability" due to changes in intrinsic neuronal factors such as voltage-gated sodium or potassium channels. What they also called "intrinsic plasticity" or "non-synaptic plasticity". 

A reference of this notion can be found in the introduction chapter of this recent paper: PMID     25697160.
"... less attention has been directed towards **'intrinsic' membrane properties: non-synaptic factors,** which directly affect the probability that a neuron will fire an action potential in response to excitatory synaptic inputs. Upon the generation of the action potential at the axon initial segment, the signal continues to be strongly modulated by these intrinsic factors until it reaches the axon terminals, where it triggers the release of neurotransmitters..."

What do you think? Are we talking about the same concept?
Val

**Comment by dosumis** [comment]
Added this ages ago.  Not sure why I didn't paste in and close ticket:

rdfs:label "short-term synaptic potentiation"^^xsd:string
id "GO:1990926"^^xsd:string
has_obo_namespace "biological_process"^^xsd:string
definition "The process by which synaptic transmission, induced by the arrival of a spike (action potential) at a synapse, acts to increase the amount of neurotransmitter released in response to the arrival of subsequent spikes.  This effect is seen when a train of closely space spikes arrives at a synapse with a low initial release probability.  It occurs in a timeframe of tens to hundreds of milliseconds."^^xsd:string
rdfs:comment "The mechanism of short term potentiation is thought to be either increased influx of calcium into the presynapse (Zucker and Regeh, 2002 PMID:11826273) increased sensitivity to calcium (Jackman et al., 2016 PMID:26738595) or both."^^xsd:string
has_exact_synonym "synaptic facilitation"^^xsd:string
created_by "sp"^^xsd:string
creation_date "2016-02-12T13:17:18Z"^^xsd:string
