### ISSUE TITLE
transcription factor term

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12311]
This is the term I have used for DNA binding sequence specific TF's:

GO:0000982 transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding
Interacting selectively and non-covalently with a sequence of DNA that is in cis with and relatively close to a core promoter for RNA polymerase II (RNAP II) in order to modulate transcription by RNAP II.

and it seems correct.

However, I wasn't sure if 
GO:0001074
transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding involved in preinitiation complex assembly

should be a descendant?

the parent term seems to be about gene specific regulation, the preinitiation complex assembly presumably precedes this?

**Comment by krchristie** [comment]
I think that having 

GO:0001074 - transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding involved in preinitiation complex assembly

as an is_a child of

- GO:0000982 - transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding

seems fine. These are both MF terms, and it seems to me that the GO:0000982 term should encompass all of the types of binding that occur at this location.

With respect to regulation, for RNAP II, preinitiation complex (PIC) formation often is a regulated step that determines gene specific regulation. Sometimes there are regulated steps that occur later, such as at the transition from the PIC to an elongating complex, though that's more common for E. coli than for RNAP II. Thus the more specific term GO:0001074 is as much about gene specific regulation as its parent term GO:0000982.

I think this relationship is correct as is.

thanks,

-Karen





Summary: I think it's fine since regulation of PIC formation is part of the regulation of gene expression and also because I think

**Comment by ValWood** [comment]
Hi Karen,

I still don't fully understand what the term
GO:0001074 - transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding involved in preinitiation complex assembly
would be used for. Do you have an example of a gene product that you would annotate using this term. I think that would help me. Currently it doesn't have a single annotation. If it meant what I *thought* it meant, I think it would have been used for something?

Val

**Comment by krchristie** [comment]
Hi Val,

I suspect that quite a lot of the binding that occurs in the core promoter proximal region is involved in formation of the PIC since quite a lot of the regulation of RNAP II transcription occurs by deciding where RNAP II should bind, i.e. form PIC's. If the binding of a protein is involved in the process of recruiting GTFs or RNAPII to form the PIC, then this term would apply. However, I think the majority of the experiments that show binding don't go much further to show exactly what a given protein is doing. 

I don't have a specific example because it's been years since I worked on this area and haven't been reading it recently. 

I can't comment on what you thought it meant, unless you want to explain what that is.

-Karen

**Comment by ukemi** [comment]
GO:0001074 already is a child of GO:0000982. So I think this one is ok.

**Comment by ValWood** [comment]
GO:0000982 transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding
Interacting selectively and non-covalently with a sequence of DNA that is in cis with and relatively close to a core promoter for RNA polymerase II (RNAP II) in order to modulate transcription by RNAP II.

This is the term I have been using for  sequence specific DNA binding transcription factors. We really need a term  to represent these   in GO because our users often ask us for a list of DNA binding sequence specific TFS.
I also base my interpretation on this paper
http://www.ncbi.nlm.nih.gov/pubmed/23981286
Which describes in detail the terms to use for these gene products. 

To me the term
GO:0001074 - transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding involved in preinitiation complex assembly
sounds as though it isn't referring to a more specific term to describe  sequence-specific  DNA binding transcription factors (or if it does, I don't know which ones you mean).

If I had an example of which sequence specific transcription factors you thought you would use this term for when you created it, that would be really useful.

Can I also confirm that the phrase "core promoter proximal region" is referring to sequence-specific  a regulatory region close to, but not coincident with the promoter  (I though this would rule out  an involvement in preinitiation complex assembly, which occurs at the promoter.

**Comment by ValWood** [comment]
I guess I could phrase the question another way. Which term should I use for ss DNA binding TFs which does not mingle them with   other terms which do not describe these gene products?

(not to self, may need to revise FAQ)
http://www.pombase.org/faq#t6n340

**Comment by ukemi** [comment]
I think, if you don't know that is involved in preinitiation complex assembly, then annotate with GO:0000982.

**Comment by krchristie** [comment]
I agree with David that "if you don't know that is involved in preinitiation complex assembly, then annotate with GO:0000982.". While I think that there are many sequence-specific DNA binding TFs that are involved in PIC formation, I don't think that many published experiments show this directly. Mechanism of transcription researchers are more likely to be interested in this than researchers who are just interested in which txn factors regulate their gene of interest.

Val asked: 
"Can I also confirm that the phrase "core promoter proximal region" is referring to sequence-specific a regulatory region close to, but not coincident with the promoter (I though this would rule out an involvement in preinitiation complex assembly, which occurs at the **promoter.**"

- Yes, the  "core promoter proximal region" is referring to sequence-specific a regulatory region close to, but not coincident with the _core_ promoter.

- However binding there does NOT rule out being involved in PIC formation. There are quite a number of txn factors that bind to a regulatory region and also bind to some other txn factor in order to recruit it to the site within the core promoter where that other txn factor binds. There are lots of bridging interactions within PIC formation where txn factors bound to one regulatory region (to enhancers as well as to the core-promoter proximal region) bind to factors that bind to different regulatory regions and this is thought to be a significant way in which these regulatory regions work, by helping to bring the appropriate factors together at the core promoter.

Sorry I do not have an example. I just do not have time to go through this literature again to track down specific examples.

-Karen
