### ISSUE TITLE
obsolete intermembrane transport ?

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12329]
id: GO_0046909
label "intermembrane transport"^^string
comment "Examples of intermembrane transport are the transfer of glycolipids from the endoplasmic reticulum to other cellular membrane structures in which they reside, and the movement of proteins between regions of the plasma membrane (where one region could be the ciliary membrane)."^^string
definition "The directed movement of substances between any membrane of a cell, including the plasma membrane and its regions."^^string

Has [hardly any direct annotation with exptl evidence](https://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0046909&termUse=ancestor&relType=%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal).

Has only one subclass: "protein transport from ciliary membrane to plasma membrane".  If it is kept, it should probably have many more.  These will almost certainly need to be added by hand but logical defs  may be unsafe because we can't encode that start and end membranes are different from each other. e.g. this returns 'phosopholipid translocation': 
- transport that 'has target start location' some membrane and 'has target end location' some membrane

Above query doesn't find many other classes, but this may be because we model the relevant terms as transport between membrane-bound organelles.

So - perhaps safest just to obsolete.  It may be too abstract to be useful anyway.

**Comment by dosumis** [comment]
@paolaroncaglia - Any opinions on this one?  Looks like you may have worked on it.

I think we can reclassify 'protein transport from ciliary membrane to plasma membrane' under 'transport within lipid bilayer'  ('cillary membrane' is part of 'plasma membrane')

**Comment by paolaroncaglia** [comment]
Hi David (and Karen @krchristie),

‘protein transport from ciliary membrane to plasma membrane’ was requested by Karen via TG. I probably approved it.
I added the def comment to ’intermembrane transport’ but the term was already there. I can’t find a mention of that edit in the ontology tracker, but I’m quite sure it was agreed with Karen.
‘protein transport from ciliary membrane to plasma membrane’ was recently discussed here, as you may recall: https://github.com/geneontology/go-ontology/issues/12327
Karen noted that in ciliary research it is important to capture the process of transporting proteins from the ciliary membrane to the 'rest' of the plasma membrane. I’m not sure if moving ‘protein transport from ciliary membrane to plasma membrane’ under ‘protein transport within lipid bilayer’ (is_a intracellular transport) would clash with that concern. Karen, may I ask for your opinion?

Thanks,

Paola

**Comment by dosumis** [comment]
We agreed in #12327 that, while the 'plasm' of cillia is not part of the cytoplasm, the membrane is part of the 'plasma membrane'. The proposed new classification is consistent with this.

**Comment by paolaroncaglia** [comment]
Fine with me then. Karen?

**Comment by krchristie** [comment]
works for me.

**Comment by krchristie** [comment]
Rereading through this thread, it seems the summary of this thread is to 

1. classify GO:1903445 "protein transport from ciliary membrane to plasma membrane" as a type of GO:0032594 "protein transport within lipid bilayer"
2. obsolete GO:0046909 "intermembrane transport"

Looking at the ontology now, it looks to me like #1 might not require any action as GO:1903445 as it already has inferred classification as "protein transport within lipid bilayer". 

So, then for #2, we'll need to send out the obsoletion email for GO:0046909 "intermembrane transport".

@ukemi and @dosumis, can you confirm this is correct, and also point me to instructions for obsoletions, please.

thanks,

-Karen

**Comment by krchristie** [comment]
Thinking it through, it seems that the currently inferred "SubClass Of" relationships might go away when “intermembrane transport” is removed.

So, I'm not sure what to do about the parentage of GO:1903445 "protein transport from ciliary membrane to plasma membrane”. One option is to directly assert “protein transport within lipid bilayer” as the new is_a parent. 

Alternatively, we could see if we can create an equivalence axiom.

The current equivalence axion of the proposed new is_a parent "protein transport within lipid bilayer" is:
<pre>'protein transport' and ('occurs in' some membrane)</pre>

Would it be possible to create an equivalence axion that specifies movement from the "ciliary membrane" to the "plasma membrane"? Though maybe that's a problem since "ciliary membrane" is considered to be 
<pre>'part of' some 'plasma membrane'</pre>

-Karen

**Comment by ukemi** [comment]
I think the former suggestion would be the safest way to go, without the axioms for the reasons DOS points out above. They would not be necessary and sufficient. It makes sense to me to keep all the asserted superclasses and to add the additional classification of is_a 'transport within lipid bilayer'

**Comment by krchristie** [comment]
I took a look at the paper cited in the definition of "intermembrane transport", PMID:10671554 (Cloning and expression of glycolipid transfer protein from bovine and porcine brain) and I think that this term is valid, but poorly placed, named, and defined. I think it should be renamed something like "intermembrane lipid transfer" and placed under or defined with respect to this term:

<pre>id: GO:0097035
name: regulation of membrane lipid distribution
namespace: biological_process
def: "Any process that modulates the proportions or spatial arrangement of lipids in a cellular 
membrane." [GOC:mah, PMID:18441123, PMID:20823909]
is_a: GO:0044802 ! single-organism membrane organization
is_a: GO:0065008 ! regulation of biological quality
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates OBA:0000098 ! membrane lipid distribution
</pre>

I'm still working on how to clearly define "intermembrane lipid transport"

The current child term 'protein transport from ciliary membrane to plasma membrane' is clearly misplaced and belongs under the term David OS suggested, so I will go ahead and move that as already discussed with David H.

**Comment by krchristie** [comment]
The term I listed above, "**regulation of membrane lipid distribution**", is defined as "in **a** cellular membrane.", but one of the papers (PMID:20823909) cited clearly talks about the movement of lipids between intracellular membranes, so I think this definition is inappropriately narrow, and that this term should still be an appropriate parent for  "intramembrane lipid transfer" (aka "intermembrane transport")

**PMID:20823909** -  "The movement of lipids within and between intracellular membranes is mediated by different lipid transport mechanisms"

**Comment by krchristie** [comment]
changed parentage of GO:1903445 "protein transport from ciliary membrane to plasma membrane" as a type of GO:0032594 

-is_a: GO:0046909 ! intermembrane transport
+is_a: GO:0032594 ! protein transport within lipid bilayer

**Comment by krchristie** [comment]
Here are the 5 existing experimental annotations (as of 3/3/2017), two of which are actually to the child term:

<pre>
Database        Gene Product ID Symbol  Qualifier       GO Identifier   GO Term Name    Aspect  Evidence        Reference       With    Taxon   Date    Assigned By     Product Form ID
UniProtKB       O88848  Arl6    GO:0046909      intermembrane transport P       IMP     PMID:22139371   MGI:MGI:5310744 10090   20140911        MGI
UniProtKB       Q01112  cdc42   GO:0046909      intermembrane transport P       IMP     PMID:23060961   284812  20131105        PomBase
UniProtKB       Q8BWP5  PERP    GO:0046909      intermembrane transport P       IDA     PMID:23599266   10090   20130529        UniProt
UniProtKB       Q99LE1  Rilpl2  GO:1903445      protein transport from ciliary membrane to plasma membrane      P       IMP     PMID:23264467   10090   20150417        UniProt
UniProtKB       Q9JJC6  Rilpl1  GO:1903445      protein transport from ciliary membrane to plasma membrane      P       IMP     PMID:23264467   10090   20150417        UniProt</pre>

I have moved the MGI one for Arl6 to the child term for transport from the ciliary membrane. The S. pombe one for cdc42 looks like the wrong term; should be something related to "regulation of vesicular transport" instead. The one for Rilpl2 is good. 

The lack of experimental annotations to this term seems to be more related to this area being one that has made lots of recent progress.

**Comment by ValWood** [comment]
Hi Karen,
Isn't this the same as lipid translocation?
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0045332#term=ancchart

**Comment by krchristie** [comment]
Hi Val,

I intially thought it might mean that, but from the paper cited in the dbxref, this term seems like it represents something entirely novel not currently represented in GO and that it should actually be called "intramembrane lipid transfer" (what I've see the most) or "LTP-mediated transfer" as it's called in Figure 1 of this review:

http://www.nature.com/nrm/journal/v11/n10/fig_tab/nrm2971_F1.html

The fact that the term is poorly annotated is probably partly due to the fact that most of the work has been done within the last 10 years, so it's relatively new science. The fact that the term seems to be named incorrectly and definition is way too vague probably doesn't help.

I've been putting info about what the biology should be and what I've done so far into the ontology ticket:
https://github.com/geneontology/go-ontology/issues/12329#event-985322493

-Karen

**Comment by ValWood** [comment]
OK got it, this is different!

**Comment by krchristie** [comment]
Here's a proposal for terms I think we should have to represent this area. @ukemi, I need some feedback from you on some ontology questions. 

**Existing BP term:**

Here is what I think the "intermembrane transport" term should be:

Term: intermembrane lipid transfer
Namespace: BP
Def: The transport of lipids between membranes in which a lipid molecule is transported through an aqueous phase from the outer leaflet of a donor membrane to the outer leaflet of an acceptor
membrane. This process does not require metabolic energy and can be either spontaneous or mediated by lipid transfer proteins (LTPs).
Def dbxrefs: GOC:krc, PMID:20823909, PMID:25797198
is_a: GO:0097035 - regulation of membrane lipid distribution 
synonym (exact): lipid transfer protein mediated lipid transfer
synonym (??)  LTP-mediated lipid transfer (**Question:** Should be related since it contains an acronym, though it isn't entirely an acronym?)

- [ ] **Question**: @ukemi Can we just change the existing term "GO:0046909 - intermembrane transport" into what I think it should have been based on the fact the def dbxref cites PMID:10671554. Or is the incredibly vague definition a reason to obsolete and replace with a new term? There is only one annotation in AmiGO (the one for PERP) that will be affected; the other four have/will be moved appropriately.

- [ ] - **Note**: I've indicated an is_a parent, but it might be possible to do this as a logical definition when I'm working in Protege, haven't worked that out yet.

- [ ] - It seems to me there would be use for more specific terms also, at least for the three main branches: phospholipids, sterols, & sphingolipids. They seem consistent with the level we've done lots of other process terms. **Question**: any objections to more specific BP terms?

**New MF terms**
I also think we should make some MF terms to represent the specific biological activities that are known. Again, I've indicated asserted parents, but I think these might be possible to define logically, depending on what I see when I'm actually working in Protege. 

Term: intermembrane lipid transfer activity
Namespace: MF
Def: Enables the removal of a lipid from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane.
Def dbxrefs: GOC:krc, PMID:20823909, PMID:25797198
is_a: lipid transporter activity (GO:0005319)
has_part: lipid binding (GO:0008289)

Term: intermembrane phospholipid transfer activity
Namespace: MF
Def: Enables the removal of a phospholipid from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane.
Def dbxrefs: GOC:krc, PMID:20823909, PMID:25797198
is_a: intermembrane lipid transfer activity
has_part: phospholipid binding (GO:0005543)

- I think we should probably make more specific terms also, e.g. for phosphotidylinositol, phosphotidylcholine


Term: intermembrane sterol transfer activity
Namespace: MF
Def: Enables the removal of a sterol from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane.
Def dbxrefs: GOC:krc, PMID:20823909, PMID:25797198
is_a: intermembrane lipid transfer activity
has_part: sterol binding (GO:0032934)

- I think we should probably make more specific terms also, e.g. terms for cholesterol, oxysterol


Term: intermembrane sphingolipid transfer activity
Namespace: MF
Def: Enables the removal of a sphingolipid from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane.
Def dbxrefs: GOC:krc, PMID:20823909, PMID:25797198
is_a: intermembrane lipid transfer activity
has_part: sphingolipid binding (GO:0046625)
- I think we should probably make more specific terms also, e.g. terms for glycosphingolipid, ceramide, e.g.:

Term: intermembrane ceramide transfer activity
Namespace: MF
Def: Enables the removal of a ceramide from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane.
Def dbxrefs: GOC:krc, PMID:20823909, PMID:25797198
is_a: intermembrane sphingolipid lipid transfer activity
has_part: ceramide binding (GO:0097001)

**Sources:** 
1. Malinina et al. 2015 (PMID:25797198) - has a lot of information but is a little overwhelming.
2. Lev 2010 review (PMID:20823909)

This section of the Lev review is a particularly compact summary of the biology here.
<Pre>LTPs carry a lipid monomer in their hydrophobic pocket and show specificity for one or 
more lipid types. Nonspecific LTP (NSLTP; also known as SCP2), for example, transfers all 
common diacyl phospholipids, glycolipids and cholesterol19, 38, whereas ceramide-transfer 
protein (CERT) displays high specificity towards natural ceramide with C14–C20 but not longer 
acyl chains (42), thus showing specificity to both the lipid headgroup and the backbone.

According to their lipid-binding specificity and transfer capability, LTPs can be grouped into three
main classes: phospholipid-, sterol-, sphingolipid-transfer proteins (Fig. 3a).

In mammals, PtdCho-transfer protein (PCTP), phosphatidylinositol (PtdIns)-transfer protein (PITP)
and NSLTP are the three main classes of phospholipid-transfer proteins. Steroidogenic acute 
regulatory protein (STAR) is an example of a cholesterol-transfer protein (43), and oxysterol-
binding protein (OSBP) and OSBP-related proteins (ORPs) are considered to be either sterol-
sensing and/or sterol-transfer proteins. Examples of sphingolipid-transfer proteins include CERT 
and FAPP2 (also known as PLEKHA8; 44).</pre>

**Comment by krchristie** [comment]
This review is good also, so will probably add it to the def dbxrefs:
PMID: 24220498 - Tuuf J, Mattjus P. Membranes and mammalian glycolipid transferring proteins.

**Comment by krchristie** [comment]
@ukemi and I think it is best to obsolete the current term "intermembrane transport" due to the fact that it is incorrectly named, defined, and placed in the ontology. Also, the single valid annotation currently made to the term is recent enough that it should be easy to get the relevant SwissProt curator to update to the replacement term.

**Comment by krchristie** [comment]
new terms:

 [Term]
+id: GO:0120009
+name: intermembrane lipid transfer
+namespace: biological_process
+def: "The transport of lipids between membranes in which a lipid molecule is transported through an aqueous phase from the outer leaflet of a donor membrane to the outer leaflet of an acceptor membrane. This process does not require metabolic energy and can be either spontaneous or mediated by lipid transfer proteins (LTPs)." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+is_a: GO:0006869 ! lipid transport
+created_by: kchris
+creation_date: 2017-03-16T20:30:42Z
+
+[Term]
+id: GO:0120010
+name: intermembrane phospholipid transfer
+namespace: biological_process
+def: "The transport of phospholipids between membranes in which a phospholipid molecule is transported through an aqueous phase from the outer leaflet of a donor membrane to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120009 ! intermembrane lipid transfer
+intersection_of: transports_or_maintains_localization_of CHEBI:16247 ! phospholipid
+created_by: kchris
+creation_date: 2017-03-16T20:56:03Z
+
+[Term]
+id: GO:0120011
+name: intermembrane sterol transfer
+namespace: biological_process
+def: "The transport of sterols between membranes in which a sterol molecule is transported through an aqueous phase from the outer leaflet of a donor membrane to the outer leaflet of an acceptor membrane. This process does not require metabolic energy and can be either spontaneous or mediated by lipid transfer proteins (LTPs)." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120009 ! intermembrane lipid transfer
+intersection_of: transports_or_maintains_localization_of CHEBI:15889 ! sterol
+created_by: kchris
+creation_date: 2017-03-16T22:15:40Z
+
+[Term]
+id: GO:0120012
+name: intermembrane sphingolipid transfer
+namespace: biological_process
+def: "The transport of sphingolipids between membranes in which a sphingolipid molecule is transported through an aqueous phase from the outer leaflet of a donor membrane to the outer leaflet of an acceptor membrane. This process does not require metabolic energy and can be either spontaneous or mediated by lipid transfer proteins (LTPs)." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120009 ! intermembrane lipid transfer
+intersection_of: transports_or_maintains_localization_of CHEBI:26739 ! sphingolipid
+created_by: kchris
+creation_date: 2017-03-16T22:20:45Z
+
+[Term]
+id: GO:0120013
+name: intermembrane lipid transfer activity
+namespace: molecular_function
+def: "Enables the removal of a lipid from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+is_a: GO:0005319 ! lipid transporter activity
+relationship: has_part GO:0008289 ! lipid binding
+created_by: kchris
+creation_date: 2017-03-17T03:17:29Z
+
+[Term]
+id: GO:0120014
+name: intermembrane phospholipid transfer activity
+namespace: molecular_function
+def: "Enables the removal of a phospholipid from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120013 ! intermembrane lipid transfer activity
+intersection_of: transports_or_maintains_localization_of CHEBI:16247 ! phospholipid
+relationship: has_part GO:0005543 ! phospholipid binding
+created_by: kchris
+creation_date: 2017-03-17T03:34:17Z
+
+[Term]
+id: GO:0120015
+name: intermembrane sterol transfer activity
+namespace: molecular_function
+def: "Enables the removal of a sterol from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+is_a: GO:0120013 ! intermembrane lipid transfer activity
+intersection_of: GO:0120013 ! intermembrane lipid transfer activity
+intersection_of: transports_or_maintains_localization_of CHEBI:15889 ! sterol
+relationship: has_part GO:0032934 ! sterol binding
+created_by: kchris
+creation_date: 2017-03-17T03:46:28Z
+
+[Term]
+id: GO:0120016
+name: intermembrane sphingolipid transfer activity
+namespace: molecular_function
+def: "Enables the removal of a sphingolipid from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120013 ! intermembrane lipid transfer activity
+intersection_of: transports_or_maintains_localization_of CHEBI:26739 ! sphingolipid
+relationship: has_part GO:0046625 ! sphingolipid binding
+created_by: kchris
+creation_date: 2017-03-17T03:52:30Z
+
+[Term]
+id: GO:0120017
+name: intermembrane ceramide transfer activity
+namespace: molecular_function
+def: "Enables the removal of a ceramide from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120016 ! intermembrane sphingolipid transfer activity
+intersection_of: transports_or_maintains_localization_of CHEBI:17761 ! ceramide
+relationship: has_part GO:0097001 ! ceramide binding
+created_by: kchris
+creation_date: 2017-03-17T04:00:12Z
+
+[Term]
+id: GO:0120018
+name: intermembrane phosphotidylinositol transfer activity
+namespace: molecular_function
+def: "Enables the removal of a phosphotidylinositol from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120014 ! intermembrane phospholipid transfer activity
+intersection_of: transports_or_maintains_localization_of CHEBI:28874 ! phosphatidylinositol
+relationship: has_part GO:0035091 ! phosphatidylinositol binding
+created_by: kchris
+creation_date: 2017-03-17T04:22:47Z
+
+[Term]
+id: GO:0120019
+name: intermembrane phosphotidylcholine transfer activity
+namespace: molecular_function
+def: "Enables the removal of a phosphotidylcholine from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120014 ! intermembrane phospholipid transfer activity
+intersection_of: transports_or_maintains_localization_of CHEBI:64482 ! phosphatidylcholine
+relationship: has_part GO:0031210 ! phosphatidylcholine binding
+created_by: kchris
+creation_date: 2017-03-17T04:22:47Z
+
+[Term]
+id: GO:0120020
+name: intermembrane cholesterol transfer activity
+namespace: molecular_function
+def: "Enables the removal of a cholesterol from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120015 ! intermembrane sterol transfer activity
+intersection_of: transports_or_maintains_localization_of CHEBI:16113 ! cholesterol
+relationship: has_part GO:0015485 ! cholesterol binding
+created_by: kchris
+creation_date: 2017-03-17T04:46:12Z
+
+[Term]
+id: GO:0120021
+name: intermembrane oxysterol transfer activity
+namespace: molecular_function
+def: "Enables the removal of a oxysterol from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
+intersection_of: GO:0120015 ! intermembrane sterol transfer activity
+intersection_of: transports_or_maintains_localization_of CHEBI:53030 ! oxysterol
+relationship: has_part GO:0008142 ! oxysterol binding
+created_by: kchris
+creation_date: 2017-03-17T04:50:30Z

**Comment by krchristie** [comment]
added part of links between appropriate MF and BP terms:

@@ -476971,6 +476971,7 @@ namespace: molecular_function
 def: "Enables the removal of a lipid from the outer leaflet of a donor membrane, transports it through the aqueous phase while protected in a hydrophobic pocket, and brings it to the outer leaflet of an acceptor membrane." [GOC:krc, PMID:20823909, PMID:24220498, PMID:25797198]
 is_a: GO:0005319 ! lipid transporter activity
 relationship: has_part GO:0008289 ! lipid binding
+relationship: part_of GO:0120009 ! intermembrane lipid transfer
 created_by: kchris
 creation_date: 2017-03-17T03:17:29Z
 
@@ -476982,6 +476983,7 @@ def: "Enables the removal of a phospholipid from the outer leaflet of a donor me
 intersection_of: GO:0120013 ! intermembrane lipid transfer activity
 intersection_of: transports_or_maintains_localization_of CHEBI:16247 ! phospholipid
 relationship: has_part GO:0005543 ! phospholipid binding
+relationship: part_of GO:0120010 ! intermembrane phospholipid transfer
 created_by: kchris
 creation_date: 2017-03-17T03:34:17Z
 
@@ -476994,6 +476996,7 @@ is_a: GO:0120013 ! intermembrane lipid transfer activity
 intersection_of: GO:0120013 ! intermembrane lipid transfer activity
 intersection_of: transports_or_maintains_localization_of CHEBI:15889 ! sterol
 relationship: has_part GO:0032934 ! sterol binding
+relationship: part_of GO:0120011 ! intermembrane sterol transfer
 created_by: kchris
 creation_date: 2017-03-17T03:46:28Z
 
@@ -477005,6 +477008,7 @@ def: "Enables the removal of a sphingolipid from the outer leaflet of a donor me
 intersection_of: GO:0120013 ! intermembrane lipid transfer activity
 intersection_of: transports_or_maintains_localization_of CHEBI:26739 ! sphingolipid
 relationship: has_part GO:0046625 ! sphingolipid binding
+relationship: part_of GO:0120012 ! intermembrane sphingolipid transfer
 created_by: kchris
 creation_date: 2017-03-17T03:52:30Z

**Comment by krchristie** [comment]
Annotations to check listed here: https://github.com/geneontology/go-annotation/issues/1564

**Comment by krchristie** [comment]
Obsoletion proposal for **'intermembrane transport' (GO:0046909)** mailed out June 7th, with deadline for comments on June 14, and obsoletion to proceed on June 15.
