### ISSUE TITLE
protein transport from ciliary membrane to plasma membrane

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12327]
Should the ciliary membrane be considered a plasma membrane region?

It is currently classified in this way (via 'cell projection membrane'):

![image](https://cloud.githubusercontent.com/assets/112839/13567191/bff5f758-e451-11e5-8a5c-3a0f226ef8d4.png)

But we also have this - which suggests 

![image](https://cloud.githubusercontent.com/assets/112839/13567214/e59fae72-e451-11e5-9d28-d6d857820e66.png)

- I think it makes most sense to think of it as a plasma membrane region - however specialised in may be.

(Think there's been some related discussion/tickets on this).

@paolaroncaglia

**Comment by paolaroncaglia** [comment]
Hi David,

You're probably thinking about this other ticket https://github.com/geneontology/go-ontology/issues/11830

The relevant bits from Karen say

(some time ago) “Although I previously said I was leaning towards classifying the cilium as a cytoplasmic structure that is bounded by the ciliary membrane and which protrudes through the plasma membrane, David has reminded me that the ciliary membrane contains transmembrane receptors that we do not want to classify as "cytoplasmic" in GO. Therefore, we will make the "ciliary membrane" a specialized part of the "plasma membrane" and then the rest of the cilium will be cytoplasmic, but the entire cilium will not be classified as "cytoplasmic”.”

(more recently) "Regarding whether or not the "ciliary cytoplasm" should be considered part of the "cytoplasm". I am inclined to agree with Helen that this is not correct, despite the fact that we agreed to make it part of the cytoplasm when we discussed this with several ciliary researchers. At the FASEB Cilia and Flagella meeting I attended this summer, there were several talks about the fact that the composition of the both the plasm and the membrane of the cilium is detectably different from that in the non-ciliary cytosol and plasma membrane, e.g. calcium ion concentration, membrane lipid composition, more. By analogy with the "nucleoplasm" which is excluded from "cytoplasm", the cilium is gated by a structure that is basically the same structure as a nuclear pore, so it seems equally valid to exclude the ciliary plasm from the cytoplasm."

In ciliary research it is important to capture the process of transporting proteins from the ciliary membrane to the 'rest' of the plasma membrane - the one excluding the plasma membrane region constituting the ciliary membrane. Not sure about how to best capture this. The more recent considerations from Karen above seem to point towards severing the link between ciliary and plasma membrane but of course the ciliary membrane is still a membrane region. Can we do that? (i.e. is_a 'membrane region' rather than is_a 'plasma membrane region' but we'd have to work around the link to cell projection similarly to what we did for the cytoplasmic terms...) 

Karen, could you please comment on the biology? @krchristie

Thanks,
Paola

**Comment by dosumis** [comment]
Thanks Paola.  Looks like we decided just to change the 'plasm' term but not the membrane.  I think this means that there is no safe logical definition for  'protein transport from ciliary membrane to plasma membrane' unless we make a term for all bits of plasma membrane that are not ciliary membrane, or extend our use of OWL outside of EL so we can refer to parts of PM not part of 'ciliary membrane'.  Neither seems a good idea, so I'll just relax the Equivalent class axiom to subclassof axioms.

**Comment by krchristie** [comment]
Paola, you copied in an accurate statement of my view of the biology.

If David is satisfied that the axioms work, that's good for me.

-Karen

**Comment by paolaroncaglia** [comment]
Thanks Karen,

Paola
