### ISSUE TITLE
mitochondrial fragmentation query

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12331]
I have a gene product ATP13A2 that inhibits mitochondrial fragmentation in assays (i.e. probably neuroprotective). Looking at which term to annotate to, it looks odd to have 'mitochondrial fragmentation involved in apoptotic process ; GO:0043653' as an is_a child of mitochondrial fission.

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0043653#term=ancchart

@Pauldenny pointed me to this ticket https://github.com/geneontology/go-ontology/issues/11652. Scrolling down to the bottom, it sounds like it's agreed that fragmentation is a failure of mitochondrial fusion and mitochondrial homeostasis, rather than being a type of fission. 

Have I understood this correctly? If so, chould GO:0043653 be removed from 'mitochondrial fission'?

Thanks!

**Comment by ValWood** [comment]
Hi Becky,
 wouldn't it seem odd to have 'mitochondrial fragmentation involved in apoptotic process' 
as a normal process for ATP13A2? Isn't that like one of  @pgaudet 's experimental readout examples
(i.e.  the cell death just a by product of something else, like abnormal zinc homeostasis or ATP production,  rather than a normal function of ATP13A2?).
Val

(The parentage might be wrong though)

**Comment by rebeccafoulger** [comment]
Hi @ValWood - ATP13A2 protects against the fragmentation in the assays, so I've not annotated to the fragmentation term (I'm looking instead at neuroprotection terms). I just noticed GO:0043653 when I was browsing the node, looking for an appropriate term.

**Comment by ValWood** [comment]
Ah right, ignore!

**Comment by ukemi** [comment]
Hi Becky,
I deleted the term and the incorrect logical definition.
-D

**Comment by rebeccafoulger** [comment]
Thanks David!

**Comment by ukemi** [comment]
I should say I deleted the relationship, not the term.
