### ISSUE TITLE
cell-type specific apoptotic process

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12338]
"cell-type specific apoptotic process" is a 'meta-term' - impossible to define logically: all apoptosis occurs in some specific cell type.  I'd favour getting rid of it.  

More immediately, this is a problem for classification of classes of the form 'X cell apoptotic process'. Many terms that should do not sit under this node:

![image](https://cloud.githubusercontent.com/assets/112839/13675832/4cb38b70-e6db-11e5-93a9-52c66619371a.png)

These generally have logical definitions in which the genus is 'apoptotic process'
![image](https://cloud.githubusercontent.com/assets/112839/13675869/712b8b1a-e6db-11e5-895f-292ef5114116.png)

Others use the more specific term as the genus:

![image](https://cloud.githubusercontent.com/assets/112839/13675914/998a401a-e6db-11e5-8911-6da700b0be41.png)

As a result, we have quite a number of ETINES for these terms and their regulation equivalents:

e.g. GO:2000352	negative regulation of endothelial cell apoptotic process	GO:1904036	negative regulation of epithelial cell apoptotic process														

Whether or not 'cell-type specific apoptotic process' is obsoleted, the same genus needs to be used in all cases for these.

**Comment by RLovering** [comment]
I guess the question is, do all cell types use the same proteins for apoptosis, or at least to 'regulate' apoptosis? My gut reaction is no, specifically for the T and B cells apoptosis is triggered to remove any cells which are auto-antigenic. With more diseases being recognised as auto-immune related I would request some caution before deleting all of these terms.

**Comment by paolaroncaglia** [comment]
Hi @RLovering ,
I’m afraid there may have been some confusion. David is not suggesting to get rid of *all* cell-type specific apoptosis terms (e.g. T cell apoptotic process). Rather, he’s concerned about the generic parent, the structure of the node and the logical definitions. I’ll get to that shortly.

**Comment by paolaroncaglia** [comment]
Hi @dosumis ,
Thanks for spotting these. They need fixing, and I’ll get to that next, but first let me dig into the term archeology. Back in 2012 I suggested to create ‘cell-type specific apoptotic process’ because, without it, all of the 36 terms shown in your first screenshot would sit directly under ‘apoptotic process’. The node was very cluttered because of that.  I do realise that this may seem less of an issue in the logical world of OWL :-) but most GO curators refer to browsers that display nodes as ‘flat’ lists and if there are too many terms, it is less straightforward to spot the ones they may really need (think about all the work we did to describe sub-processes of signalling, execution etc.). So I suggested to clean up the node by creating a generic parent term ‘cell-type specific apoptotic process’ to act as un umbrella, with appropriate caveats:

Def: Any apoptotic process in a specific cell type.
Comment: This term was created as a generic parent to group terms indicating occurrences of apoptotic process in specific cell types. The process of apoptosis may not vary, but the cell type does. Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select a child term or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation QC. Alternatively, you may annotate to the parent term GO:0006915 apoptotic process.

At the time, this was well received. I think the rationale behind having this term still holds, and I favour keeping it. (As I said, the node still needs cleaning, I’ll do that.)
Before I dig into why 2 different logical definitions cropped up in time (sneak preview: it’s got to do with how we designed the TG template), please let me know if keeping ‘cell-type specific apoptotic process’ would be acceptable to you. 

Thanks!

**Comment by dosumis** [comment]
> Let me know if keeping ‘cell-type specific apoptotic process’ would be acceptable to you.

I think it comes down to whether you think keeping it is sustainable.  There are a few scenarios where an editor or curator might perfectly reasonably use the pattern "'apoptotic process' that occurs in some { cell type }" and expect the results to classify correctly:
* Anyone using a term genie template with a generic BP occurs_in CL pattern
* A curator extending apoptotic process or one of its subclasses with 'occurs in{cell type}
* An editor extending some existing apoptotic process subclass with the restriction: 'occurs in' some { cell type }

Classification/folding in all of these cases will fail if we keep "cell-type specific apoptotic process".  If we allow the general principal of adding meta-logical classes like this for the purposes of tidiness, the sustainability problem can increase non-linearly through compounding.  I see the tidiness/browse-ability issue as more of an interface problem.

**Comment by paolaroncaglia** [comment]
Thanks, I see your point (and I forgot to add, there's still the problem of making specific cell type terms available for MODs that don't use AEs, but that's not the main subject of discussion here; mentioning just for completeness). My main concern is with

"I see the tidiness/browse-ability issue as more of an interface problem."

I'm afraid that is there to stay for many curators. I know that @ValWood  is often concerned about ease of visualisation for community curators - the cell apoptosis terms wouldn't apply to Pombe of course, but maybe she could comment on the tidiness/browse-ability issue please?

**Comment by ValWood** [comment]
My concern is usually when there are lots of terms which would be out of scope for our current guidelines (like protein family specific binding terms, and  gene product specific terms). The confusion is less about browsing per se, and more about which terms are appropriate. The  community curators can see these terms, and then think that it is appropriate to request new terms like this, because they are trying to annotate specifically, and they can see other terms of this type. For this reason, I think it would be nice to accelerate the merging of the terms which we would consider out of scope for future, because it saves time for us, and our users (and helps users more generally to understand what GO terms represent).

This issue seems slightly different. If there are completely different signalling pathways involved in the regulation of apoptosis  in different cells types then there is a case for making the the terms. However, presumably a number of cell types would share the same alternative pathways, so making terms for each cell type could result in redundancy when describing the same pathway in different cells.
I guess it really depends how much is known about the pathways. Maybe they could be
x signalling involved in regulation of apoptosis (occurs in cell type).

Before making a decision is there an easy way to see how many gene products are annotated to these cell-type specific apoptotic processes which are not "general apoptotic genes", and how many 'cell types' they are annotated in? That might help to come to the best solution.

(btw who still can't use extensions?)

**Comment by RLovering** [comment]
Hi Val

my understanding is that if an extension is used a lot for the same cell type then the editors will consider creating a new GO term (but maybe that is no longer true).
In addition, there are currently no functional analysis tools that use extension data, so currently putting everything in the extension field when it maybe of use if the information is captured within a GO term does not make sense.

But I agree it would be interesting to see how many gene products are annotated to these cell-type specific apoptotic processes which are not "general apoptotic genes", and how many 'cell types' they are annotated in. Unfortunately, this might not be as clear cut to interpret, there maybe some cells that are used more often to study apoptosis but that doesn't mean the proteins involved are specific to that cell type. Plus proteins annotated to 'general' processes are not necessary present in 'all' cell types.

**Comment by paolaroncaglia** [comment]
Right. There’s nothing like apoptosis to stir a good conversation…
Summing up: 

- The issue of tidiness/browse-ability is sort of postponed pending decision on keeping cell-type specific terms. (Just to mention this somewhere: GO:0006915 apoptotic process currently has 20 direct descendants among is_a, part_of and regulates. That is without the cell-type specific terms.)

- Do different cell types follow different pathways to apoptose? Presumably some of them do, others don’t. The real problem is that *I think* that typically, papers showing cell death in a given cell type or tissue don’t go deep into the details of the (signaling) processes. This info is more easily found in studies on cell lines or in vitro. @RLovering  may confirm this. In absence of this certainty, it’s hard to decide if cell-type specific apoptosis terms belong in GO or not. Suppose there is evidence to say that e.g. neurons die differently than hepatocytes (which I believe is the case, lots of oxygen- and iron-related processes are relevant in brain degeneration). Then ‘neuron apoptosis’ has a reason to exist beyond simply wanting to capture a frequently-used cell type. Should we disallow any cell-type specific apoptosis terms unless details of the pathway are provided? Fine with me, but that’s not going to be a quick fix. 

- Looking at cell-type specific apoptotic genes and cell types - interesting but afraid not easily or quickly done. 

- Which MODs are still not using annotation extensions - I used to have a list, I’ll ask @mcourtot  or Tony to respond please.

- AFAIK, it still holds that if the same annotation extension is used often associated with a process, then we’d create the specific term.

- Having term enrichment tools that look at extensions too: I think @cmungall  had a plan. I’d expect that, in many cases, only ‘apoptotic process’ would be enriched, but the cell type specific terms could potentially aid a lot in discovery. So, ideally, we’d want the cell type captured, one way or another. If an appropriate tool can be in place within a reasonable time frame, then we don’t care how the cell type is captured. If not, our users would benefit from cell-type specific terms being precomposed.

**Comment by ValWood** [comment]
Just to throw something else into the discussion. There are Total: 1640 human proteins annotated to apoptotic process, which seems super-high to me..._really?????_

**Comment by ukemi** [comment]
But I think that is closing over regulates. So it's not as bad as you think.

**Comment by dosumis** [comment]
Rather a lot going on now in this ticket. All good, but can we focus on the initial request - as we need a fix for ETINE issues ASAP?

All terms of the form 'X cell apoptotic process' need a logical def with the same genus.  Your call whether you keep 'cell-type specific apoptotic process'  and use this as the genus or obsolete it and use 'apoptotic process'.

> There are Total: 1640 human proteins annotated to apoptotic process, which seems super-high to me...really?????

I have a strong suspicion that most of the cell-type specific annotations are for developmental regulation of apoptosis.  These could be useful if annotated to the reg term - but even then, many coming from IMPs are likely to be indirect (change almost anything in development and the level of apoptosis of some cell type will change).

**Comment by dosumis** [comment]
> But I think that is closing over regulates.

Ahhh - never thought this was a good idea.

**Comment by ukemi** [comment]
You can filter it out in AmiGO2. Then there are 361 genes left.

**Comment by ukemi** [comment]
apoptotic process
   programmed cell death (has_part some apoptotic signaling pathway) and (ends_with some execution phase of apoptosis)

cell-type specific apoptotic process 
  apoptotic process (occurs_in some cell)

I know it's a bit weird because apoptosis always occurs in a cell, but I think this might work. Whether the cell-type term is useful........

**Comment by paolaroncaglia** [comment]
Yes of course @dosumis , going back to the initial issue, i.e. whether to use ‘apoptotic process’ or ‘cell-type specific apoptotic process’ as the genus in the logical def. 
As far as I understand, the rule of thumb should be to use the most generic genus and the most specific differentia, so the genus should be ‘apoptotic process’. And that’s how we set up the TermGenie template to start with. But then, curators noted that newly created terms were not children of ‘cell-type specific apoptotic process’ (see https://sourceforge.net/p/geneontology/ontology-requests/10669/). And I asked Heiko to change the template. I see now that the best route should have been to leave the template as was and add the ‘cell-type specific apoptotic process’ parentage by hand… which wouldn’t be maintainable. 
I’d keep ‘cell-type specific apoptotic process’ as the genus for the time being, if it weren’t for 1) most terms have the other genus at present and 2) if we end up obsoleting it, it’ll be even more work.
Vote? Or go for David H's solution?

**Comment by dosumis** [comment]
> know it's a bit weird because apoptosis always occurs in a cell

That's the fundamental point - and I don't think we can or should try to hack around it.  'cell-type specific apoptotic process' is not a class that makes any sense logically.  If we choose to keep it for the sake of tidiness then we need to commit to manually maintain classification under it.

**Comment by ukemi** [comment]
What about cases in cell lines where the experiments are done simply for the purpose of studying the apoptotic mechanism, and the cell type would not necessarily be captured or important?

If we go with the solution I propose, cell is from the cell ontology not GO, I think this will all work out and users can navigate through the cell-type specific term when it is something they care about.

**Comment by dosumis** [comment]
"As far as I understand, the rule of thumb should be to use the most generic genus and the most specific differentia, so the genus should be ‘apoptotic process’."  The rule of thumb should be to use logical definition patterns that work.  Choosing the more general class doesn't work if you have a class with no logical def in between.  David's pattern would cause equivalence if any parent class of apoptotic process ever gets the axiom (or inference) 'occurs in' some cell.

**Comment by ValWood** [comment]
I'll bet my bottom dollar these are not 'regulating apoptosis'

TAF9B
RPS3A
SOX9
FMN2
RPS27A
COL4A3
LIG4
etc.....

re:
>But I think that is closing over regulates.
>>Ahhh - never thought this was a good idea.

It depends if you use 'regulates' strictly to mean 'a biological mechanism regulating a process' and not just 'affects the rate of a process'.

**Comment by ukemi** [comment]
But wouldn't those parents use the GO cell and not the cell type cell?

**Comment by dosumis** [comment]
> But wouldn't those parents use the GO cell and not the cell type cell?

In that case I think you want http://purl.obolibrary.org/obo/CL_0000003 'native cell': A cell that is found in a natural setting, which includes multicellular organism cells 'in vivo' (i.e. part of an organism), and unicellular organisms 'in environment' (i.e. part of a natural environment).

It's still a hack though.

**Comment by ukemi** [comment]
If what we care about is the type of cell, then I don't think it is a hack. It is a meaningful differentia. CL:0000003 works.

**Comment by paolaroncaglia** [comment]
I'll let you guys decide. Would be nice to hear what @cmungall thinks too. I can propose obsoletion of 'cell-type specific apoptotic process' if it doesn't make sense to keep it and if we'd have to manually maintain classification. 

@ValWood , please feel free to relay doubtful apoptosis annotations to the pertinent MODs :-)

**Comment by ValWood** [comment]
Too many....

**Comment by cmungall** [comment]
I don't think it does. Generic apoptosis always happens to a CL:0000003, 
so the fake class would be equivalent to the parent.

I think it's clear - obsolete the fake class. It doesn't work 
computationally/logically, and I don't see a major biological use case.

I can see it's sort of nice to be able to have some guidance when 
drilling down the hierarchy, but this applies all over the ontology. For 
example, when drilling down in metabolism, to see subclasses by process 
type (catab/biosynth) vs chemical type. But making metaclasses classes 
is not a workable solution, we should file an amigo ticket for this.

**Comment by paolaroncaglia** [comment]
OK. So (my) action items are:

- Current children of 'cell-type specific apoptotic process’: move parentage to is_a ‘apoptotic process’

- Obsolete 'cell-type specific apoptotic process'

(These combined should take care of all relevant ETINEs I think)

- Ask Heiko to change TG template back to is_a ‘apoptotic process’ (by opening a ticket on the TG GH tracker)

Anything else? I think we should keep the cell type-specific terms themselves (neuron apoptosis, etc), so I suggest we leave that discussion aside. 

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
Fixed parentage and intersections of cell-type specific terms.

**Comment by paolaroncaglia** [comment]
Asked Heiko to fix the TG template.

**Comment by paolaroncaglia** [comment]
Sent obsoletion email.

**Comment by paolaroncaglia** [comment]
I'll label this ticket as 'pending', and will close it when 'cell-type specific apoptotic process’ is obsoleted.

**Comment by paolaroncaglia** [comment]
TG template modified as requested.

**Comment by paolaroncaglia** [comment]
Obsoleted GO:0097285 cell-type specific apoptotic process.
