### ISSUE TITLE
'developmental process involved in reproduction'  & 'reproductive structure development'

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12332]
These two terms sound very similar. Should they be merged?

label "reproductive structure development"^^string
definition "The reproductive developmental process whose specific outcome is the progression of structures that will be used in the process of creating new individuals from one or more parents, from their formation to the mature structures."^^string
EquivalentTo: 'anatomical structure development' and ('results in development of' some 'reproductive structure')

label "developmental process involved in reproduction"^^string
definition "A developmental process in which a progressive change in the state of some part of an organism specifically contributes to its ability to form offspring."^^string
EquivalentTo: 'developmental process' and ('part of' some reproduction)

For the second one, the EC def doesn't match the textual def. This needs to be fixed whether or not the terms are merged.

**Comment by ukemi** [comment]
One of the synonyms of the latter term is puberty. If this is valid, it encompasses more than just the development of a reproductive structure.

**Comment by cmungall** [comment]
Should we treat puberty as a phase?

Or as a coordinated sum of parts of reproductive structure developments?

**Comment by ukemi** [comment]
What about something like sex determination?

**Comment by dosumis** [comment]
> One of the synonyms of the latter term is puberty. If this is valid, it encompasses more than just the development of a reproductive structure.

OK. Makes sense in that it encompasses 'development of secondary sexual characteristics' (!= 'reproductive structure').

Also noticed that 'developmental process involved in reproduction' covers plant strucs, whereas 'reproductive structure development' is defined using an Uberon term for parts of a reproductive system and so doesn't cover plants.

BUT 'developmental process involved in reproduction' feels like a misleading name for this.  Following normal GO naming conventions, this sounds like developmental processes that are part of reproduction, but it may be more accurate to say that this covers development of structures which are (capable of being) used in reproduction (in a broad sense - secondary sexual characteristics being important for mating which is part of GO:reproduction).

Perhaps - 'development of structures involved in reproduction'.  This would be a parent class to 'reproductive structure development'.  I can't see a straighforward way to formalise, do I think classification under it would have to be done manually - at least for now.

Not sure we can

**Comment by dosumis** [comment]
BTW - just realised that if I delete the logical def, the number of ETINES will *increase*.  Maybe best to wait until after we switch to fully automated pipeline.

**Comment by pgaudet** [comment]
Any objection to the merge of 'developmental process involved in reproduction' into 'reproductive structure development'? 

https://docs.google.com/spreadsheets/d/1g4P58qVelvKRZOi9eNqJmrJBYzLB2rNQC08ozE5QAXM/edit#gid=0


Number of annotations: 

Contributor   | (Assigned by)
--
AgBase | 1
BHF-UCL | 2
RGD | 6
MGI | 3
TAIR | 7
UniProt | 1

**Comment by RLovering** [comment]
sounds good to me

**Comment by tberardini** [comment]
Yes, that's fine.  Our annotations will transfer to the replacement term when the change is implemented.  I will mark the annotations in the spreadsheet as 'changed' even though that won't happen until the ontology change is made and trickles through.

**Comment by raymond91125** [comment]
@pgaudet execute merge?

**Comment by pgaudet** [comment]
I had a few questions about that branch. 
- I would propose merging into 'reproductive structure development' since this is probably more commonly used than 'developmental process involved in reproduction. 
- The merge ends up putting some terms under 'reproductive structure development' that don't seem to belong, for example: 
- - acquisition of desiccation tolerance in seed -> this currently is indirectly part_of  'reproductive structure development', it would become is_a
- - anterior/posterior axis specification, follicular epithelium, right now is_a developmental process involved in reproduction
- etc. so, all the terms's parentage would need to be reviewed. 

- Also, I think there is an issue with 'GO:0022414 reproductive process' , defined as "A biological process that **directly** contributes to the process of producing new individuals by one or two organisms. The new individuals inherit some proportion of their genetic material from the parent or parents."
Many of the children of 'reproductive structure development' end up with the 'GO:0022414 reproductive process' ; however I would think any developmental process is indirectly involved in reproduction (or perhaps, required for reproduciton to take place) , not directly - for eg 
* seed dormancy process is_a 'multicellular organismal reproductive process' 
* eggshell chorion assembly is_a 'cellular process involved in reproduction in multicellular organism' - this may be required to form the egg, but is it part_of reproduction?
* menstrual cycle
* longitudinal axis specification
* etc 

So, I thought all children should be checked. 

**Other easier points:** 

- I propose we remove the 'puberty' NARROW synonym. 
- The definition of 'reproductive structure development' might need tweaking, currently it is "The reproductive developmental process whose specific outcome is the progression of structures that will be used in the process of creating new individuals from one or more parents, from their formation to the mature structures. "; We could perhaps simplify to "The (A?) developmental process whose specific outcome is the progression of structures that will be used in reproduction, from their formation to the mature structures. " (If needed we can add another sentence with the definition of 'reproduction', "the process of creating new individuals from one or more parents", although I would prefer not, because if the other term's definition is updated we dont always remember to update all definitions to match)

How do you want to proceed? I'm happy to help. 

I am committing my branch where I actually did the merge, so you can have a look. 

Thanks, Pascale

**Comment by raymond91125** [comment]
It appears that the merge is creating more problems than what it solves 8-(

Before merge, "reproductive structure development" is_a "developmental process involved in reproduction", and by its logical definition, "reproductive structure development" only covers the development of Uberon 'reproductive structure' which does not include any plant parts or germ cell line, whereas "developmental process involved in reproduction" does, and other stuff. Not merging makes more sense to me.

We may want to define "developmental process involved in reproduction" more clearly, perhaps "A developmental process in which a progressive change in the state of some part, *germline or somatic*, of an organism specifically contributes to its ability to form offspring." And "reproductive structure development" definition "The reproductive developmental process whose specific outcome is the progression of *somatic* structures that will be used in the process of creating new individuals from one or more parents, from their formation to the mature structures."

There are other issues brought up but I think perhaps they are of different scopes and deserve their own tickets. e.g. should we (how to) separate "reproductive process" from "developmental process involved in reproduction"?

**Comment by pgaudet** [comment]
Thanks Raymond - do you want to go ahead and 1) implement your new proposed definition for  reproductive structure development, and open any necessary tickets? 

Thanks, Pascale

**Comment by raymond91125** [comment]
Is there a way that we can logically define "reproductive structure development" that includes plant (somatic) reproductive structures? Don't we want to?

**Comment by cmungall** [comment]
i suggest making a general ticket for what to do about terms like tissue,
anatomical structure, organ, reproductive structure that span kingdoms and
are fuzzy in nature and of debatable value in grouping

**Comment by raymond91125** [comment]
OK. I take back my question. Reproduction is probably the most thorny issue of biology, as biology is reproduction.
