### ISSUE TITLE
Bridging ChEBI to Pro

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12341]
We use pro:Protein as a general way to refer to proteins in axioms.  But we also use some subclasses of ChEBI protein, e.g. glycoprotein, lipoprotein.  For full inference we need these to sit under whatever term we use for Protein.  

PRO have promised in the past to fix their references to ChEBI.  We should probably follow up on this.  In the absence of a PRO fix, we may be able to fix by adding out own bridging axiom or by switching purely to PRO.

**Comment by dosumis** [comment]
Darren has promised to fix this (even if ticket says otherwise).  But I'm not inclined to rely on this.

**Comment by dosumis** [comment]
Let's just add a bridge file for inter-ontology glue:
*  ChEBI -> SO 
 * ChEBI -> PRO

Challenges for Pro -> ChEBI link:
* Probably need to use subclassing axioms rather than equivalence in order to avoid triggering owltools/oort checks (Please confirm).
* Need to find a way to cope with clashing labels: I suggest using OBO-foundry uniquename and getting editors to change their setup to take advantage of this.
* The structure of ChEBI make a solution challenging:

 
protein polypeptide chain; CHEBI:16541
Definition	A naturally occurring polypeptide synthesized at the ribosome.
![image](https://cloud.githubusercontent.com/assets/112839/13705364/6b8d388a-e798-11e5-989d-a4f235aa1f5c.png)

protein CHEBI:36080 
A biological macromolecule minimally consisting of one polypeptide chain synthesized at the ribosome.
SubClassOf: has_part some protein polypeptide chain

![image](https://cloud.githubusercontent.com/assets/112839/13705418/aa3a110c-e798-11e5-999d-2a14478a7706.png)

Given this - we probably need ChEBI protein to be *under* Pro Protein (if we can't have equivalence).

**Comment by dosumisu** [comment]
Test

**Comment by cmungall** [comment]
> Probably need to use subclassing axioms rather than equivalence in order to avoid triggering owltools/oort checks (Please confirm)

Let's do this correctly. The equiv is more of an issue if it's to a class i the release ontology (eg GO/CL)

> Need to find a way to cope with clashing labels: I suggest using OBO-foundry uniquename and getting editors to change their setup to take advantage of this

What about OE? Does anyone every axiomatize in OE any more?

I use OFUL a lot in Protege, but when people don't have this configured it can lead to real confusion

Another option is just to rewire the label in our import module

> The structure of ChEBI make a solution challenging

It would be great if PRO and CHEBI could take the lead here and come up with a solution

**Comment by nataled** [comment]
PRO and ChEBI long ago agreed that terms such as 'glycoprotein' should live in PRO, and we do indeed have that term and others similar to it (since 2013 or so), and can certainly add more as needed. From my recollection the only reason ChEBI has them at all is because there is one user group that expects to see them there. As for that relevant PRO ticket: https://sourceforge.net/p/pro-obo/term-requests/99/ and the action I promised despite its closure, changes that relate PRO to ChEBI have indeed been implemented. The request evolved into relating PRO's protein to ChEBI in a chemical sense. I've attached an OBO file showing the relevant terms as they are today (note: I had to change the extension to 'txt' so it would upload here). For simplicity I've changed the parents for some ChEBI terms to 'molecular entity'

The changes to PRO were made in consultation with John Garavelli ("Dr. MOD") and account for the fact that proteins are not technically just chains of amino acid residues (which, by ChEBI's definition, are only peptidyl).

I'm not sure if the changes made address the peptide vs protein issue. Likely not. PRO has shied away from using the term peptide because the distinction between the two is so arbitrary, and we cannot place protein under peptide because of the issue mentioned directly above; that is, not all proteins are peptides by ChEBI's definition of peptide. Indeed, I believe this might mean that not all PRO proteins are ChEBI proteins, confusingly enough. John indicated he tried to convince ChEBI curators to change their definition at some point but they resisted.

[PRO-MOD-ChEBI.txt](https://github.com/geneontology/go-ontology/files/578791/PRO-MOD-ChEBI.txt)

**Comment by nataled** [comment]
Edit: it appears that ChEBI has decoupled protein and peptide in such a way as to no longer be a direct problem. That is, the is_a hierarchy is now a has_part (protein has part peptide, after a few steps). My understanding from John is that there was still some issue somewhere (I think with the definition of amino acid residue and the concern about modified residues found in proteins), but that the issue is resolved by the changes given in the attached file.

**Comment by dosumis** [comment]
- [ ] @dosumis to make equivalence axioms.  These live in an new separate OWL file that is only imported into OWL - not OBO (need a blank import for OBO).   This file can also house upper ontology mappings.

- [ ] @cmungall to fix build if this breaks it (we probably need to specify exceptions for the rule that bans equivalent classes).

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/21899607/bdf4ada0-d8e8-11e6-9420-f66107e8df14.png)

**Comment by mcourtot** [comment]
Hi @dosumis: is that change live yet, or...?

**Comment by dosumis** [comment]
Not live yet.  I'd rather not break the build overnight, so will try first thing tomorrow.

**Comment by dosumis** [comment]
- [ ] TODO: set up BFO import job.  @cmungall

**Comment by dosumis** [comment]
Changes are now live.  Build didn't break.  Changes to inference can be viewed here:

http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/go_inferences_difflog.txt?revision=38127

Additions look good (@ukemi  please can you check). But some lost inferences need investigating, e.g.:

 [Term]
 id: GO:0045047 ! protein targeting to ER
 is_a: GO:0006605 {is_inferred="true"} ! protein targeting
-is_a: GO:0070972 {is_inferred="true"} ! protein localization to endoplasmic reticulum

May be harmless redundancy stripping.  Checking now.

**Comment by dosumis** [comment]
From spot checking - all removed inferences appear to be harmless redundancy stripping (the relevant classifications are now on superclasses).

**Comment by dosumis** [comment]
SO->CHEBI mapping needs more work. Looks like more work needed to insure correct SO imports:

![image](https://cloud.githubusercontent.com/assets/112839/22062250/b65e5e1a-dd70-11e6-8925-4bb857f12c6f.png)


![image](https://cloud.githubusercontent.com/assets/112839/22062253/bf6596fe-dd70-11e6-915f-c552b69c3216.png)

**Comment by dosumis** [comment]
Fixed mappings from CHEBI to SO.  Effects on inference are not visible in initial commit as mostly asserted.

![image](https://cloud.githubusercontent.com/assets/112839/22064487/ba64c16a-dd7b-11e6-9eb1-99ec2f67ccb5.png)

Note there is some duplication between SO and CHEBI (messenger RNA etc in CHEBI).  The fact that the CHEBI versions are in bold here shows that they are used in GO axioms.  Either all usages should be standardised to SO, or we should add additional equivalence axioms to the bridge file.

**Comment by dosumis** [comment]
Have added equivalence axioms as this looks safer.  No need to police patterns - editors can choose either term.

![image](https://cloud.githubusercontent.com/assets/112839/22064712/98c96dac-dd7c-11e6-87db-df3374a3e6cc.png)

**Comment by dosumis** [comment]
Inference resulting from assertion of SO - CHEBI logical links can be seen here: 

http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/editors/go_inferences_difflog.txt

(There are a few other inferences on proteins, due to tweaks based on issues found with inference after equivalence between CHEBI and PRO protein added (see above). Relevant commit = -r38127.)

**Comment by dosumis** [comment]
Editor's call: we agreed to close this ticket and move the one remaining item (BFO import) to a fresh ticket.
