### ISSUE TITLE
Definition qualification for EMT

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12359]
Hi

Please could you clarify what exactly should be annotated with the GO term 
GO:0001837 epithelial to mesenchymal transition
Definition: A transition where an epithelial cell loses apical/basolateral polarity, severs intercellular adhesive junctions, degrades basement membrane components and becomes a migratory mesenchymal cell.
Should the proteins involved in the signalling pathways that lead to EMT be included or would these be regulating EMT (i.e. casually upstream of EMT). To date it has been associated with the signalling pathway proteins.

If this is the case please could you add something in the definition to clarify this

Thanks

Ruth

**Comment by ukemi** [comment]
I would think the signaling pathways would regulate the process unless they are directly involved in the transition itself. Keep in mind, many older annotations were made to parent terms when there was no distinction between regulation and a process. Those might be the ones at which you are looking. I would think that proteins responsible for specifically degrading extracellular matrices, cell adhesion molecules, and molecules responsible for cytoskeletal polarity rearrangements and migratory behavior would be the key players in the process itself. I think the definition makes that pretty clear.

**Comment by ukemi** [comment]
Maybe a comment would be more appropriate saying that the signaling pathways leading to the EMT should be annotated as regulation?

**Comment by tberardini** [comment]
Leaving this in your able hands, @ukemi :)

**Comment by RLovering** [comment]
I think a comment would be helpful. I always assume that signaling pathways are included in 'xx_development' terms because the 'process' is complex. So it would be good to clarify that this describes the event following signalling.

Ruth

**Comment by ukemi** [comment]
Hi Ruth,

But this term is a child of cell morphogenesis, which only has to do with the shape change. What if I tweak the definition to be: A morphogenetic transition where an epithelial cell loses apical/basolateral polarity, severs intercellular adhesive junctions, degrades basement membrane components and becomes a migratory mesenchymal cell.

Just as an aside, at the level of a cell signaling pathways aren't always part of the development of a cell. They might be involved in the commitment of a cell to a certain fate. When that is the case, it is part of differentiation, but not development. Development starts once an identity has been established. We needed to do this in order to avoid a chicken and egg ad infinitum scenario.

-D

**Comment by RLovering** [comment]
Hi David
Thanks for the clarification of the cell signalling pathways, I think I was thinking of tissue development (which was obviously inappropriate) where signalling is part of development. I will make sure Alex is clear on this. 
Best
Ruth
