### ISSUE TITLE
modify definition for  GO:0043112 receptor metabolic process?

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#12362]
The definition of  GO:0043112 "receptor metabolic process" is "The chemical reactions and pathways involving a receptor molecule, a macromolecule that undergoes combination with a hormone, neurotransmitter, drug or intracellular messenger to initiate a change in cell function." The clause at the end of the definition that defines receptor propagates to all the children of this term, which often is OK. It looks very odd, though, when it propagates to  GO:0032799 "low-density lipoprotein receptor particle metabolic process" because low density lipoproteins in mammals are generally viewed as nutrients, not as signaling entities, and their uptake is not generally viewed as part of a signaling process.

Possible fix: remove the clause here and on GO:0032799 and all the general receptor children; keep it on the receptor child  GO:0045213 neurotransmitter receptor metabolic process and the various grandchildren of all terms that describe signaling processes. Apologies for not providing a more detailed list.

**Comment by tberardini** [comment]
Peter - this makes me wonder whether we've stuck LDL receptor particle into the wrong branch.  Look at 'receptor activity' and its definition: "Combining with an extracellular or intracellular messenger to initiate a change in cell activity."  GO:0005041, low-density lipoprotein receptor activity, is a child of this term but based on your comment on the process term, it seems to me that it shouldn't be here.  It's the 'receptor' string that's causing the problem, no?  What would be a better home?  Something under transporter activity? This would mean that we could put the related BPs under transport.

**Comment by tberardini** [comment]
Hmmm, digging into the MF branch some more, we've got:

receptor activity
--[i] signaling receptor activity
--[i] cargo receptor activity
----[i] lipoprotein particle receptor activity

@rebeccafoulger - can you provide any guidance wrt signaling and receptors and the classification of the lipoprotein particle receptor terms in MF and BP? I know you're on Easter Break so won't expect a reply till at least Tuesday next.

**Comment by deustp01** [comment]
"Cargo receptor activity" is exactly where the lipoprotein receptor activity belongs. And it is there, but then cargo receptor activity is an is_a child of GO:0004872 receptor activity, as you noted.

**Comment by tberardini** [comment]
Peter -Yup.  Hopefully, Becky can help as she worked extensively in this area. A definition tweak for BOTH MF and BP branches may be necessary for clarity.

**Comment by tberardini** [comment]
@rebeccafoulger - bringing this to your attention after Easter break. Thanks.

**Comment by rebeccafoulger** [comment]
Hi all,
Yes- we split the receptor branch for this same reason- so the 'cargo receptors' weren't under signaling in BP. So to keep the grouping, it looks like we need to further broaden the 'receptor activity' definition and for this new definition to propagate across to any generic receptor terms. E.g:

Receiving an extracellular or intracellular entity and transmitting a signal in the cell to initiate a change in cell activity, or delivering the entity into the cell via endocytosis.

Sounds a bit clunky so any modifications welcome.

**Comment by tberardini** [comment]
@deustp01: Any better shots at phrasing?  You're usually pretty good at this. :)

**Comment by deustp01** [comment]
Another long-winded comment.

RECEPTOR - what it is vs where it is vs what it does vs what happens as a result.

What it is - typically a protein or complex with protein components. Perhpas always - can't think of protein-free receptors. If such receptors exist they're outside the scope of GO but we'd still like a definition that accommodates them.

Where it is - on the cell surface or inside cell (e.g., nuclear hormone receptors).

What it does - binds with an entity of extracellular origin. Is "entity" broad enough to include photons (as in animal phtotransduction and plant light tropisms)? Is "of extracellular origin" broad enough to allow steroid hormones from outside a cell to penetrate into the cytosol or even the nucleus to interact with their receptors, while excluding unwanted stuff (can't think of a concrete example of unwanted stuff; maybe not a concern)?

What happens as a result - is outside the scope of this definition, because this is where the bifurcation between signal transduction and cargo internalization happens.

BUT none of this solves the basic problem that signal transduction and cargo uptake are basically different processes. In both cases, a cell's specificity (what signals it can detect, what cargoes it can retrieve) is determined by interaction with a molecular complex, typically at the cell surface. Unfortunately, the complexes used for the two very different jobs of sensing the environment and cargo uptake both have the same name, "receptor". No matter how we revise the definition, in the current ontology hierarchy, if GO:0038024 "cargo receptor activity" is_a GO:0004872 "receptor activity", then it is an is_a grandchild of  GO:0060089 "molecular transducer activity" - "The molecular function that accepts an input of one form and creates an output of a different form." That seems wrong unless we're willing to say that packaging previously extracellular stuff into a clathrin-coated vesicle is a kind of transduction.

Instead, should we think about leaving molecular function terms for entities that mediate signaling alone, with the definitions they now have and with their current molecular transduction parentage, and moving all terms for entities that handle cargo to be children of GO:0005215 transporter activity?

**Comment by pgaudet** [comment]
1.	'apolipoprotein receptor activity'
Move under 'cargo receptor activity'


2.	'laminin receptor activity' 
Move under ‘cell adhesion mediator activity’ (“Any binding by a cell surface protein to a molecule external to the cell, that meditates adhesion of the cell to that external substrate.”) 


3.	'pattern recognition receptor activity'
Move under 'signaling receptor activity' 

4.	'protein-hormone receptor activity'
Move under 'signaling receptor activity' 


5.	'transmembrane receptor activity' 3 direct annotations
Merge into child ‘transmembrane signaling receptor activity’


This was under ‘receptor activity’ we’ll have two branches: 
'cargo receptor activity'
'signaling receptor activity'


Does that seem OK ? 
@deustp01 @tberardini @thomaspd @jimhu-tamu @ukemi @vanaukenk @ValWood 

Thanks, Pascale

**Comment by tberardini** [comment]
It seems to me that the original problem that @deustp01  brought up, the overly specific definition of 'receptor activity' has not yet been addressed.

**Comment by pgaudet** [comment]
Oh right ! Would everyone agree then to move 'cargo receptor activity' as a direct child of 'molecular function'? and move children as indicated above. I attach a screenshot of the proposed changes: 


<img width="519" alt="image" src="https://user-images.githubusercontent.com/4782928/36372476-7de76670-1565-11e8-8e05-786e457be8d3.png">


Thanks, Pascale
@deustp01 @tberardini @thomaspd @jimhu-tamu @ukemi @vanaukenk @ValWood

**Comment by ValWood** [comment]
I think this would be better.
It only has 16 Experimental annotations so it is  clearly quite hidden.

There is also a process term (we had used this instead of the receptor term)

GO:0090110 | cargo loading into COPII-coated vesicle

this sounds like a process term describing a MF and might be  better obsolete and use
'cargo receptor activity' instead?

**Comment by pgaudet** [comment]
Thanks @ValWood for the comments about the proposal. 

For GO:0090110 | cargo loading into COPII-coated vesicle we should probably open an annotation tickets - there are many non-receptors annotated to this terms and its regulation children.

**Comment by ValWood** [comment]
I thought I had been using something else, Also consider:

GO:0097020 COPII adaptor activity https://www.ebi.ac.uk/QuickGO/term/GO:0097020
Bringing together a cargo protein with the COPII coat complex component to allow its uptake by the COPII vesicle.

GO:0098748    endocytic adaptor activity

are these the same or different to a receptor?

**Comment by pgaudet** [comment]
@ValWood see https://github.com/geneontology/go-ontology/issues/14872
for a response to your question - but please let's stay on the definition of receptor activity.

By the way if people agree with the above changes I was going to propose to merge 'receptor activity' into 'signaling receptor activity' (although there are some annotations to cargo receptors). 

Is that OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
OK, sorry I could not remember the difference.

**Comment by tberardini** [comment]
> By the way if people agree with the above changes I was going to propose to merge 'receptor activity' into 'signaling receptor activity' (although there are some annotations to cargo receptors).
Is that OK ?

The 'although there are some annotations to cargo receptors' part is troublesome as these annotations will not be incorrect.  How would one identify such cases so that they can be updated?  Review all annotations under this branch :( ?

@deustp01 : @pgaudet is proposing this structure. What do you think?

molecular function
--[i] signaling receptor activity _('receptor activity' merged into this)_
--[i] cargo receptor activity

instead of 

molecular function
--[i]receptor activity _(with broadened definition)_
----[i] signaling receptor activity
----[i] cargo receptor activity

From reviewing this issue, it sounds like you might have been proposing something similar but more like this:

molecular function
--[i] signaling receptor activity _('receptor activity' merged into this)_
--[i] transporter activity
----[i] cargo receptor activity

Thoughts?

**Comment by pgaudet** [comment]
Hi @tberardini 

There are 135 EXP annotations directly to 'receptor activity'. I do think these need to be reviewed, although looking again it does seem that the vast majority are OK. 

----

WRT the structure of the ontology: Right now how 'transporter activity' was redefined in the MF refactoring ("... A transporter is in a fixed location in the cell and allows molecules to pass via a channel or a pore in its structure."), these receptors would not apply, but that should probably be refined and the version in which cargo receptor activity is a child of transporter activity be implemented. 

--- 

Note also that in my current branch I have 'signaling receptor activity' under 'signal transducer activity' and 'molecular transducer activity'.  
---

I could probably merge those changes already ? @deustp01 @tberardini @ukemi @vanaukenk 
----

What remain is the problem that @deustp01 raised in the first place: 
receptor metabolic process (GO_0043112)  0 EXP
(I cannot find regulation of receptor metabolic process)

receptor biosynthetic process (GO_0032800) | 3 EXP

receptor catabolic process (GO_0032801) | 17 EXP
regulation of receptor catabolic process (GO_2000644)
positive regulation of receptor catabolic process | 3 EXP
negative regulation of receptor catabolic process | 1 EXP

regulation of receptor biosynthetic process | 1 EXP
negative regulation of receptor biosynthetic process | 4 EXP 
positive regulation of receptor biosynthetic process | 10 EXP 

These certainly have annotations to both signaling and cargo receptors, and the annotation seems to describe different processes: 
- the catabolic process often refer to downregulation of signaling; one solution would be to replace by a new sibling of ' GO:0038009 regulation of signal transduction by receptor internalization', ie ' (negative) regulation of signal transduction by receptor degradation (catabolic process)'. 
- the biosynthetic process have at least some annotations the should be rehoused under 'regulation of transcription' or regulation of gene expression'. 

 @deustp01 @tberardini @ukemi @vanaukenk  @thomaspd @RLovering (since you group has the most annotations to these terms)
any thoughts before I ask for annotations to be reviewed? 

Thanks, Pascale

**Comment by deustp01** [comment]
The @pgaudet  bifurcated receptor structure as summarized by @tberardini yesterday looks good to me. It looks good as-is, and I think does a good job of making important functional distinctions and also useing standard biology vocabulary to do it. No additional suggestions from here about organization or wording of names and definitions. Thanks!

**Comment by tberardini** [comment]
If @deustp01 is good with the bifurcated receptor structure, then so am I.

**Comment by pgaudet** [comment]
Discussing with @thomaspd 
We are trying to align on TCDB to decide what is a transporter or not. 

TCDB does have cargo transporters, so I will move cargo transporter under 'transporter activity'. 

Please anyone - let me know if this seems incorrect. 

Thanks, Pascale

**Comment by ValWood** [comment]
I thought we discussed recently that a 
cargo receptor, aka transport receptor activity was not a transporter?
To me this made sense. Its a cargo receptor.

I would annotate as
MF cargo receptor involved_in  BP endocytosis  or whatever.

It isn't an *actual* transporter, because a transporter is defined as: 
"Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells. A transporter is in a fixed location in the cell and allows molecules to pass via a channel or a pore in its structure."

I don't think we should follow the TCDB classification religiously but I don't see this in TCDB anyway? Is it in the "auxiliary transport proteins" section? If so these are not necessarily transporters

**Comment by ValWood** [comment]
I'm not sure about those ;)

I think they probably are thought of as transporters. And there are transporter families in which some members are transporters and some are  flippases, I saw one the other day.
 I think this could be classed as "directed movement"

**Comment by pgaudet** [comment]
For reference this is what the branch used to look like 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/4782928/36549644-4b652440-17c1-11e8-9725-83164a75f3be.png">
