### ISSUE TITLE
protein secretion/ transport/localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12381]
from https://github.com/geneontology/go-ontology/issues/12369

In GO,
secretion has parentage to transport:

![secretion](https://cloud.githubusercontent.com/assets/7359272/14272433/f4671eee-fafa-11e5-8215-28c72a0fe37a.jpg)

This is a problem, because not all secretion is "transport"

Problem.
Secretion is defined as
The controlled release of a substance by a cell or a tissue.

This conflates two  DIFFERENT processes.
1. Secretion from a cell (i.e exocytosis)
2. Secretion from a tissue
Although secretion from a tissue INCLUDES secretion from a cell, it includes more.
The other part (presumably the secretion flows/diffuses through some gland or duct?)

So the transport parent needs to be removed from "secretion" and added instead to "secretion by cell"
 "secretion by cell" is always transport (exocytosis).

The term "protein secretion" should be renamed "protein secretion by cell"
because it is defined as
The controlled release of proteins from a cell.

However, some children  of "protein secretion"  do not fit this definition
"insulin secretion" is defined 
The regulated release of proinsulin from secretory granules (B granules) in the B cells of the pancreas; accompanied by cleavage of proinsulin to form mature insulin.
(A tissue type secretion)

but positioned as a "secretion by cell"

If you moveed everything to the correct place depending on whether it was decribing cell or tissue
I think you would end up with something like this for the tissue secreted compounds:

secretion (not for direct annotation)
--secretion by tissue
  --insulin secretion by tissue
    --insulin secretion by cell
--secretion by cell = exocytosis  (or are there other mechanisms?) (transport parent)
    -- insulin secretion by cell (insulin exocytosis)

Secretion by cell would need to work for single celled organisms so it could not have the tissue parent.

I suspect that if fully annotated everything almost will end up on "secretion by cell" as we are annotating gene products....

**Comment by ValWood** [comment]
OK,  secretion by cell may not always be "exocytosis" it can be via transmembrane transport too.
BUT whichever mechanism, "secretion by cell" must be a type of transport (directed movement).

**Comment by ValWood** [comment]
Hi,

I assigned this to Melanie. It was really only a suggestion to clear up #12369
It might not work, but it seems to solve the issues?

val

**Comment by RLovering** [comment]
Hi All
this seems very philosophical to me. 

So the definition of transport is: The directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter or pore.

All of the tissue secretion terms state 'regulated release' apart from lactation. Certainly there is regulated release of milk (lol with respect to non regulated release, although possibly some animals do not have regulation but I can't comment on this) however I wonder if there is a problem with this term. I think that GO:0060156 milk ejection a type of secretion? And I think lactation (current definition: The secretion of milk by the mammary gland.) normally refer to more than just release of milk (see wikipedia statement: Lactation describes the secretion of milk from the mammary glands and the period of time that a mother lactates to feed her young). Plus the part_of parent term for lactation is: GO:0030879 mammary gland development.

So possibly the definition for 'lactation' should be revised and should not have an is_a relation to secretion and GO:0060156 milk ejection should have a part_of relation to lactation and an is_a relation to both GO:0032941 secretion by tissue and GO:0007589 body fluid secretion. 

I think regulated release of a body fluid (secretion) should be considered a type of transport, before the release it is held in one place, after the release it is present somewhere else, but not simply because of osmosis.

Ruth

**Comment by ValWood** [comment]
yep  for lactation https://github.com/geneontology/go-ontology/issues/12382

Maybe the problems with the secretion branch will be resolved by moving the broader processes like lactation. I wasn't sure about the tissue level secretion. If it's transport what is the 'agent'

**Comment by mcourtot** [comment]
I moved lactation (remove is-a GO:0032941 secretion by tissue). 
Based on its definition "The directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells, or within a multicellular organism by means of some agent such as a transporter or pore.", the transport parent is suitable for both secretion by tissue and secretion by cell.
@ValWood: If you think there is still an issue with the insulin secretion, could you please open a distinct ticket?
