### ISSUE TITLE
body fluid secretion parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12383]
body fluid secretion
has parent
regulation of body fluid levels

This gives some craziness:

regulation of body fluid lactation
--body fluid secretion
----lactation
------regulation of lactation

doesn't that make the reasoner throw a hissy fit?

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
I'm looking at 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1903487#term=ancchart
and can't really see where the issue is. Not sure if it was fixed by other edits in the meantime. May I close this issue, or alternatively could you please attach a screenshot/point at the precise issue again? (Note that 'regulation of body fluid lactation' doesn't exist, looks like a typo.) Thanks.

**Comment by ValWood** [comment]
appears to be fixed!
