### ISSUE TITLE
2 terms for the same thing? repair of mitotic mono-orientation defects,

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12393]
GO:1990598  repair of mitotic mono-orientation defects
Definition	The mitotic cell cycle process where mono-orientation defects are corrected in order to ensure sister chromatids establish stable attachments to microtubules emanating from opposite spindle poles. 
PMID:15525536

and
GO:0098783
Name	correction of merotelic kinetochore attachment, mitotic
Definition	The cell cycle process that corrects the anomalous association of a single chromatid kinetochore with mitotic spindle microtubules emanating from both spindle poles (otherwise known as merotelic attachment to the spindle). 
PMID:21306900

I think these are the same process?. Apologies I probably requested both...

**Comment by ukemi** [comment]
Val,

Looking at the two papers, it looks like the first term refers to both sister kinetochores going to the same spindle pole and the second term refers to a single kinetochore being attached to microtubules from both spindle poles. That would make these slightly different processes. Can you have a look at the papers and confirm?

-David

**Comment by ValWood** [comment]
history
https://github.com/geneontology/go-ontology/issues/11375
https://github.com/geneontology/go-ontology/issues/11683
Will have a look shortly. Will also try to locate reference figure.

**Comment by ValWood** [comment]
OK, yes a 'mono-orientated chromosome is syntetically attached.

Perhaps a better name would be
correction of syntelic kinetochore attachment, mitotic
(it might be the same mechanism for both, not sure yet, but can merge later....)


![syntelic monotelic merotelic ampitelic](https://cloud.githubusercontent.com/assets/7359272/14470199/09af9fa2-00e0-11e6-9955-0aec366d20de.jpg)

**Comment by ukemi** [comment]
Added as an exact synonym.

**Comment by ValWood** [comment]
Reopening for a quick fix, in this case they should have the same parents (be siblings)
Not sure if this link will work:
http://www.ebi.ac.uk/QuickGO/GMultiTerm#a=64%240O7V7b%5D6&tab=chart&c=

I'm not sure whether they would both be part of biorientation (correct attachment results in' biorientation'...I think 'biorientation' is only achieved when ALL chromosomes are correctly attached).
More likely they should both be under congression,.

Anway, I ballsed this up a bit, because temporarily, biorientation is not under congression. So I suggest assigning to @dosumis  to fix once  he has rectified my mistake.
https://github.com/geneontology/go-ontology/issues/12355

**Comment by ukemi** [comment]
Reassigning as suggested.

**Comment by dosumis** [comment]
So, the choice is whether to make these 2 processes :

(a) mitotic sister chromatid biorientation
OR
(b) mitotic metaphase plate congression

GO:1990598 mitotic sister chromatid biorientation: "The mitotic cell cycle process in which sister chromatids establish stable, end-on attachments to the plus ends of microtubules emanating from opposite spindle poles, oriented such that separation can proceed. This follows metaphase plate congression."
is_a: attachment of mitotic spindle microtubules to kinetochore ; GO:0051315

GO:1990598 repair of mitotic mono-orientation defects: "The mitotic cell cycle process where mono-orientation defects are corrected in order to ensure sister chromatids establish stable attachments to microtubules emanating from opposite spindle poles."

GO:0098783 correction of merotelic kinetochore attachment, mitotic: "The cell cycle process that corrects the anomalous association of a single chromatid kinetochore with mitotic spindle microtubules emanating from both spindle poles (otherwise known as merotelic attachment to the spindle). "
relationship: regulates attachment of mitotic spindle microtubules to kinetochore ; GO:0051315

It strikes me that the correction processes are broader than just attachment, so I think it's better to just make them part of metaphase plate congression.  The regulates relationship on GO:0098783 also looks dodgy.  I'll just remove.

**Comment by dosumis** [comment]
Fixed as described in last comment.

**Comment by ValWood** [comment]
Yep...
