### ISSUE TITLE
GO:1904564 Nbp35-Cfd1 ATPase complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12391]
The CFD1-NBP35 complex is primarily an iron-sulfur cluster assembly complex (GO:1990229) (as described in PMID:17401378) but the GO term highlights the ATPase activity (from PMID:26195633).

Def:
[old]
A protein complex that in yeast consists of two subunits - Nbp35 and Cfd1 - and is capable of ATPase activity.
[new]
A iron-sulfur cluster assembly complex that is capably of weak ATPase activity. In yeast consists of two subunits - Nbp35 and Cfd1.

Relationships:
add GO:0016226 iron-sulfur cluster assembly

I guess you can't add is_a relationships to 
GO:1904949 ATPase complex AND 
GO:1990229 iron-sulfur cluster assembly complex?

[Complex Portal: EBI-11666137]

**Comment by paolaroncaglia** [comment]
Hi Birgit,

I edited GO:1904564 Nbp35-Cfd1 ATPase complex as follows:

old stanza:
[Term]
id: GO:1904564
name: Nbp35-Cfd1 ATPase complex
namespace: cellular_component
def: "A protein complex that in yeast consists of two subunits - Nbp35 and Cfd1 - and is capable of ATPase activity." [GO_REF:0000088, GOC:rb, GOC:TermGenie, PMID:26195633]
comment: An example of this is the yeast Nbp35-Cfd1 complex (IDA).
is_a: GO:0043234 ! protein complex
is_a: GO:1904949 {is_inferred="true"} ! ATPase complex
relationship: capable_of GO:0016887 {is_inferred="true"} ! ATPase activity

new stanza:
[Term]
id: GO:1904564
name: Nbp35-Cfd1 ATPase complex
namespace: cellular_component
def: "An iron-sulfur cluster assembly complex that is capable of weak ATPase activity. In yeast it consists of two subunits, Nbp35 and Cfd1." [GO_REF:0000088, GOC:bhm, GOC:rb, GOC:TermGenie, IntAct:EBI-11666137, PMID:26195633]
comment: An example of this is the yeast Nbp35-Cfd1 complex (IDA).
is_a: GO:1904949 {is_inferred="true"} ! ATPase complex
is_a: GO:1990229 ! iron-sulfur cluster assembly complex

The added parent GO:1990229 ‘iron-sulfur cluster assembly complex’ already has the link capable_of_part_of GO:0016226 ‘iron-sulfur cluster assembly’, so no need to add the same link to its child. Same for capable_of ATPase activity, this is already inherent in the parent ‘ATPase complex’ so I removed it from GO:1904564.
I also removed the redundant parent ‘protein complex’.

Closing now, thanks.

**Comment by paolaroncaglia** [comment]
Thinking again... noticing this inferred link:
is_a: GO:1904949 {is_inferred="true"} ! ATPase complex
@dosumis what's best to do in this case... add (back) the capable_of_part_of links to 'ATPase activity' and 'iron-sulfur cluster assembly' and the 'protein complex' parent and let the reasoner infer the more granular is_a parents? And keep the redundant one? GO:1904564 didn't really have a logical definition in the first place, I'm a bit confused about the strategy with which the term was added (in Aug. 2015). More likely, I'm just forgetful!

**Comment by ValWood** [comment]
@AntoniaLock (is annotating iron sulfur pathway in pombe... conserved can ISS)

**Comment by ValWood** [comment]
Actually, we already have an IEA to CIA complex for one subunit. Is that the same thing, or is the IEA incorrect?

**Comment by ValWood** [comment]
looks like a mapping problem? CIA targeting complex seems to be mms19 with Cia1p and Cia2p
...will be on @AntoniaLock  kill list so will ignore...

**Comment by paolaroncaglia** [comment]
Labeling as 'ETINE' and 'pending' while we wait for a resolution.

**Comment by bmeldal** [comment]
>is_a: GO:1904949 {is_inferred="true"} ! ATPase complex
is correct (ATPase activity is weak but present).
Or is it 'pending' to deal with the pombase conflict?

**Comment by paolaroncaglia** [comment]
Hi @bmeldal ,
'pending' while we wait for @dosumis to look into the ontology issue. Of course the link
is_a: GO:1904949 {is_inferred="true"} ! ATPase complex
is correct, but I *think* it could no longer be inferred, given that I removed the redundant link
relationship: capable_of GO:0016887 {is_inferred="true"} ! ATPase activity
The editors are currently working on a large set of inferences that were inferred long ago but can no longer be inferred now, that's why I flagged it. The PomBase issue was resolved.

**Comment by dosumis** [comment]
> @dosumis what's best to do in this case... add (back) the capable_of links to 'ATPase activity' 

Yes!  The whole point of inference is to avoid assertions of classification as far as possible.  This will be clearer when we move to the new system.  At that point, if you remove relationships because they *appear* redundant, the inferred classifications will simply be lost the next time inferred classification is recalculated.

In this case:

[Term]
id: GO:1904564
name: Nbp35-Cfd1 ATPase complex
namespace: cellular_component
def: "A protein complex that in yeast consists of two subunits - Nbp35 and Cfd1 - and is capable of ATPase activity." [GO_REF:0000088, GOC:rb, GOC:TermGenie, PMID:26195633]
comment: An example of this is the yeast Nbp35-Cfd1 complex (IDA).
is_a: GO:0043234 ! protein complex
is_a: GO:1904949 {is_inferred="true"} ! ATPase complex
relationship: capable_of GO:0016887  ! ATPase activity <-- Add this back. It is not redundant.

**Comment by paolaroncaglia** [comment]
Done, thanks.
