### ISSUE TITLE
parentage: gene expression

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12405]
Should gene expression have the parent "cellular metabolic process" added?

**Comment by tberardini** [comment]
Probably not because a child of this term is 'viral gene expression'.  Unless you consider viral gene expression to be a cellular metabolic process.  Then again, viral process traces parentage up to cellular process so it's probably ok.  Let's sit on this another day, see if anyone else chimes in.  I wonder if I can get @janelomax to comment. :)

**Comment by ValWood** [comment]
Probably there needs to be a broader discussion on what constitutes metabolism, so maybe ignore this one?

**Comment by janelomax** [comment]
Hello :-) The viral bit is fine because we decided viral processes were cell 'level' processes. But as Val says, there is a wider question of what metabolism is so I would close this one.

**Comment by tberardini** [comment]
Thanks, Val and Jane.  Going to close this.
