### ISSUE TITLE
OTR: 'comment' on GO:1904906 positive regulation of endothelial cell-matrix adhesion via fibronectin

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#12429]
Currently, GO:1904906 positive regulation of endothelial cell-matrix adhesion via fibronectin (http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:1904906#term=info) has a comment that looks unusual, almost like one of our student annotations, and I was just wondering if this comment was intentional:

comment: In paper PMID:19460962, in Figure 1D, endothelial cell binding to fibronectin is decreased, as a result of overexpression of miR-92a (URS00003768C5_9606).

Thanks for any clarification.

**Comment by dosumis** [comment]
Looks like a mistake.  @rachhuntley  - Any idea if this is deliberate?  (Thought I'd ask you given that it mentions a microRNA).

**Comment by rachhuntley** [comment]
No, this isn't intentional, this is one of Barbara's new terms created through TermGenie. I guess she put this comment in the public comment field without realising it would end up on the term page.
The comment is also on the parent regulation term (GO:1904904) and the negative regulation term (GO:1904905) that were created at the same time. Is there any chance you can delete them?

**Comment by dosumis** [comment]
Fixed
