### ISSUE TITLE
NTR: Distinguish between outer and inner membrane cytolysis CACAO

### ISSUE THREAD

**Issue by ryanwrich** [geneontology/go-ontology#12424]
I am working on bacteriophage annotations for CACAO and I would like to request a new term to improve upon the current term "GO:0044659 cytolysis by virus of host cell." This term presents a problem for Gram negative hosts, because certain viral proteins are necessary for the lysis of the inner membrane, whereas other proteins result in disruption of the outer membrane. It was long thought that lysis of the inner membrane and destruction of the peptidoglycan was sufficient for total lysis, but this has been disproven (PMID: 25870259). For example, right now SPAN1_BPT4 and SPAN2_BPT4 are assigned the term GO:0044659. Both of these proteins are spanins, and therefore necessary for disruption of the outer membrane (PMID: 17900620). There are terms to identify the proteins that cause lysis in the inner membrane, such as "GO:0044658 pore formation in membrane of host by symbiont," and even "GO:0034290 holin activity." There is also the term "GO:0039640
cytolysis by virus via suppression of host peptidoglycan biosynthetic process" to identify proteins involved in the destruction of the peptidoglycan layer. However, there are not any GO terms to identify proteins involved in outer membrane disruption. I propose that a new GO term be added such as "cytolysis by outer membrane disruption by virus of host cell" with a definition of "the lysing of a host cell by a virus which includes the disruption of the outer membrane of the host." This term could even be broken down into outer membrane and inner membrane components, as most spanins have an outer membrane protein and inner membrane protein which are both necessary for outer membrane disruption.

**Comment by jimhu-tamu** [comment]
I'm not sure I agree with this term request:

GO:0044659 cytolysis by virus of host cell is the larger process, and GO:0039640 ! cytolysis by virus via suppression of host peptidoglycan biosynthetic process is a child term based on being a more specific form of GO:0044659. This is because in some viruses (e.g. phiX), suppression of host peptidoglycan is sufficient for cytolysis.

By contrast, the holin and spanin activities are necessary in some situations but not sufficient. In cases where they are necessary, they would have part_or relationships to GO:0044659.

I would suggest Disruption by virus of host outer membrane as the NTR, as an is_a child of GO:0044662 ! disruption by virus of host cell membrane.

**Comment by tberardini** [comment]
@ryanwrich : what do you think of @jimhu-tamu's suggestion?

**Comment by ryanwrich** [comment]
I think he is correct. A child term of GO:0044662 is the best option.

**Comment by tberardini** [comment]
Ok, thanks.  Added:

+id: GO:0090680
+name: disruption by virus of host outer membrane
+namespace: biological_process
+def: "A process by which a virus has a negative effect on the functioning of a host outer membrane." [PMID:17900620]
+is_a: GO:0044662 ! disruption by virus of host cell membrane
