### ISSUE TITLE
NTR - child to GO:0015491 cation:cation antiporter activity

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#12434]
PMID: 22031603
Title: "Human gene SLC41A1 encodes for the Na+/Mg2+ exchanger"
gives evidence that SLC41A1 has MF GO:0015491 cation:cation antiporter activity
but I'd like to be more specific - their evidence shows  this protein is a Na+/Mg2+ exchanger and so I'd like to be able to use  a child term similar to:
GO:XXXXX
Name	sodium:magnesium antiporter activity
Definition: Catalysis of the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: Na+(in) + Mg2+(out) = Na+(out) + Mg2+(in).

GOC:PARL
GOC:pad

**Comment by ukemi** [comment]
Hi Paul,

I switched the term name around because looking at all the other terms, it looks like the imported entity is listed first.

 [Term]
+id: GO:0061768
+name: magnesium:sodium antiporter activity
+namespace: molecular_function
+def: "Catalysis of the reaction: Na+(in) + Mg2+(out) = Na+(out) + Mg2+(in)." [GOC:pad, GOC:PARL, PMID:22031603]
+is_a: GO:0015491 ! cation:cation antiporter activity
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: exports CHEBI:29101 ! sodium(1+)
+intersection_of: imports CHEBI:39128 ! magnesium ion
+created_by: dph
+creation_date: 2016-05-04T14:45:45Z
