### ISSUE TITLE
OTR: enzyme activities scheduled for obsoletion

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12432]
Stemming from https://github.com/geneontology/go-ontology/issues/11996
There are 12 terms in GO at the moment with a definition comment saying
“This term represents a deleted EC activity and is scheduled for obsoletion.”
and one saying
“This term represents a transferred EC activity and is scheduled for obsoletion.”.
Presumably the former 12 can be obsoleted, and the latter 1 can be merged. Need to look into details of EC entries and annotations if any.
@hdrabkin , @ukemi , is any of these covered by your current work on enzyme terms please? Here’s the list:

GO:0016719  carotene 7,8-desaturase activity  now has EC:1.3.5.6  - DONE https://github.com/geneontology/go-ontology/issues/22050
GO:0047486  chondroitin ABC lyase activity; removed EC >> to obsolete; unnecessary grouping class 
GO:0004158  dihydroorotate oxidase activity Fixed RHEA:15441, EC:Removed  >> obsoleted in #23789
GO:0004584  dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity Obsoleted in #16022
GO:0008752  FMN reductase activity EC 1.5.1.39; ok; but needs 2 RHEAS DONE IN https://github.com/geneontology/go-ontology/issues/16166
GO:0047606  hydroxynitrilase activity EC changed
GO:0046592  polyamine oxidase activity EC removed
GO:0050251  retinol isomerase activity EC removed; has rhea DONE #23669
GO:0050347  trans-octaprenyltranstransferase activity  OK 
GO:0048045  trans-pentaprenyltranstransferase activity  Obsoleted in #23202 
GO:0004810  tRNA adenylyltransferase activity  pending merge See ##19854 
GO:0016437  tRNA cytidylyltransferase activity pending merge See ##19854 

and 

GO:0030058  amine dehydrogenase activity  Ec was remaped  OK 

Thanks.

**Comment by deustp01** [comment]
Reactome has annotations of proteins to GO:0050251 retinol isomerase activity backed by publications - http://www.reactome.org/PathwayBrowser/#/R-HSA-2187338&SEL=R-HSA-2465926&PATH=R-HSA-162582 . (Don't know why these haven't propagated to GO).

**Comment by paolaroncaglia** [comment]
Thanks @deustp01 . There seem to be a couple of issues here. I’ll ask @mcourtot  and @tonysawfordebi :

1) I can’t see Reactome annotations to GO:0050251 retinol isomerase activity, neither in QuickGO nor in AmiGO. I can’t remember - have we been filtering out some particular types of Reactome annotations recently? If not, why are these invisible in both browsers?

2) The QuickGO page for GO:0050251 retinol isomerase activity says “No matching annotations” (http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0050251#term=annotation). 
While the AmiGO page for the same term shows an IDA annotation from ZFIN (http://amigo.geneontology.org/amigo/term/GO:0050251). I noticed a similar issue recently but couldn’t document it as the term we were looking at had been obsoleted. Could you please look into this discrepancy?

Thanks!

**Comment by deustp01** [comment]
Two issues here: is use of GO:0050251 to annotate an enzyme's activity still legitimate, and why are Reactome's use of this term in annotations not propagating to GO?

On the second issue, there are probably several reasons, mostly due to annotation practices on our side that lead to improper lines in our GAF. We then compound that problem by not regularly looking at Jenkins and other reports of mis-formed GAF entries. We are working on fixing this. Progress will be slow but in case like this where a specific annotation is at issue, I can try to move faster and be more responsive.

Meanwhile, on the first issue, could the term GO:0050251 not be obsoleted while we look on our side either for evidence that this remains a legitimate, distinctive molecular function (despite EC's opinion) or find an alternative term to describe this activity?

Thanks.

**Comment by mcourtot** [comment]
@tonysawfordebi had a look:
1) the Reactome GAF (http://www.geneontology.org/gene-associations/submission/gene_association.reactome.gz) doesn't contain any annotations to GO:0050251.
2) The ZFIN GAF contains one annotation to GO:0050251, but we don't import it because we don't have a mapping from the ZFIN identifier (ZDB-GENE-081104-505) to UniProt

**Comment by deustp01** [comment]
Apologies - I just looked at our actual annotation. The curator found evidence that a human protein has the molecular function described by GO:0050251 but the publication did not provide sequence data to allow the protein to be associated with a UniProt entity, so there's nothing to write in the GAF.
I'd still like to keep GO:0050251 while I check with the curator and look further to see if there's an alternative way to describe the protein's function and any way to associate the protein with a  UniProt.
Thanks.
Peter

**Comment by mcourtot** [comment]
Thanks for checking and confirming all is in order Peter, much appreciated.

**Comment by deustp01** [comment]
Looking at the Expasy record for the EC 3.1.1.64, the term that is proposed to replace EC 5.2.1.7 (http://enzyme.expasy.org/EC/3.1.1.64), there may be an assertion that all real enzymes have combined isomerase activity (what we annotated with 5.2.1.7) and also a hydrolase activity. The Expasy record also points to a human protein that may have the combined activities. Bijay Jassal, who made the annotation in the first place, is looking into this. Depending on what he finds, we should either be able to revise our annotation to include both a human UniProt record and a non-obsolete GO term or construct an argument backed by experriments that EC is wrong and that, at least in humans, there is an enzyme with isomerase-only activity so a separate GO term remains valid.

**Comment by paolaroncaglia** [comment]
Thanks all for your feedback, very useful.
@deustp01 , I won't send any obsoletion notice until you and Bijay have had a chance to look into the issue above. 

Note for self: 
Then, I will send notice for all of the 13 terms listed at the start of this ticket, including or excluding GO:0050251 based on Reactome's resolution. Nothing else is needed for this ticket.

**Comment by deustp01** [comment]
Bijay Jassal has looked at some relevant papers, finds that RPE65, the enzyme associated by Expasy with EC 3.1.1.64 (replacing EC 5.2.1.7) - http://enzyme.expasy.org/EC/3.1.1.64 - is not a good fit to the reaction he’s annotated for Reactome (http://www.reactome.org/PathwayBrowser/#/R-HSA-2187338&SEL=R-HSA-2465926) because RPE65 is localized to the wrong cells and appears to have a different substrate specificity. A better candidate, DEGS1, has the correct localization and can catalyze the right reaction, although very inefficiently (see section 5.2 of this paper - http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3858459/ - and references cited there). That leaves us wanting to keep our current annotation, of an incompletely characterized human enzyme (no UniProt reference possible) carrying out exactly the molecular function described by GO:0050251 and not the one described by EC 3.1.1.64, so we’d very much like GO to retain this term, despite the EC decision.
Apologies for dragging this out so long.
Peter

**Comment by paolaroncaglia** [comment]
Thanks Peter. I won't propose GO:0050251 for obsoletion then (and will delete its current comment "scheduled for obsoletion"). I will also remove the EC dbxref 5.2.1.7 as that entry doesn't exit anymore, but I will NOT substitute it with EC 3.1.1.64. GO:0050251 has a Rhea dbxref that is still valid (and doesn't point to EC), so I'll leave that. It'll be your call whether you wish to contact EC about their decision. Thanks!

**Comment by paolaroncaglia** [comment]
@deustp01 
Edited GO:0050251 retinol isomerase activity as above.

**Comment by paolaroncaglia** [comment]
Note for self:
What is left to do for this ticket is - look at my very first comment only (the opening one) and proceed for all those terms EXCEPT GO:0050251 retinol isomerase activity.

**Comment by paolaroncaglia** [comment]
GO:0050251 retinol isomerase activity was in a subset called 'mf_needs_review' 
("Catalytic activity terms in need of attention").
I removed the subset from GO:0050251, but a search highlighted that 23 other terms have it...
Must check overlap with original list. Here are the 23, must pay attention to their definition comments, when available:

GO:0018468	alcohol dehydrogenase (acceptor) activity
GO:0030058	amine dehydrogenase activity
GO:0045330	aspartyl esterase activity
GO:0016719	carotene 7,8-desaturase activity
GO:0047486	chondroitin ABC lyase activity
GO:0033758	clavaminate synthase activity
GO:0042242	cobyrinic acid a,c-diamide synthase activity
GO:0004158	dihydroorotate oxidase activity
GO:0043734	DNA-N1-methyladenine dioxygenase activity
GO:0004584	dolichyl-phosphate-mannose-glycolipid alpha-mannosyltransferase activity
GO:0008752	FMN reductase activity
GO:0045544	gibberellin 20-oxidase activity
GO:0050417	glutamin-(asparagin-)ase activity
GO:0047606	hydroxynitrilase activity
GO:0033751	linoleate diol synthase activity
GO:0031559	oxidosqualene cyclase activity
GO:0046592	polyamine oxidase activity
GO:0070773	protein-N-terminal glutamine amidohydrolase activity
GO:0051746	thalianol synthase activity
GO:0050347	trans-octaprenyltranstransferase activity
GO:0048045	trans-pentaprenyltranstransferase activity
GO:0004810	tRNA adenylyltransferase activity
GO:0016437	tRNA cytidylyltransferase activity 

Looks like a one-off attempt to represent EC updates in GO. But there must be so many other updates we haven't caught up with (EC updates every quarter I think).

**Comment by paolaroncaglia** [comment]
Also add: GO:0004584 because its EC entry was transferred (so GO:0004584 will have to be merged).
Initially reported in https://github.com/geneontology/go-ontology/issues/11864

**Comment by paolaroncaglia** [comment]
Note for self: if an automated strategy such as Melanie suggests below could be implemented, some or all of this work would take care of itself... https://github.com/geneontology/go-ontology/issues/12802#issuecomment-261479753

**Comment by paolaroncaglia** [comment]
Hi @hdrabkin ,
This ticket is about non-urgent work on enzyme terms. I’m wrapping up my tickets, so will unassign myself from this one and hand it over to you, but feel free to discuss with @ukemi and others if someone else should look into it instead. Thanks.

**Comment by pgaudet** [comment]
@hdrabkin I think you dealt with these in another ticket ? (but I cannot find it right now). 

Can you please check what needs to be done ? 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Yes, it's related to the slim ticket in general that you removed. I think some of these are in that ticket anyways.

**Comment by pgaudet** [comment]
GO:0047486  chondroitin ABC lyase activity  >> obsolete: unnecessary grouping class.

**Comment by pgaudet** [comment]
- [ ]  FMN reductase activity: change label to  FMN reductase (NAD(P)H activity >> can use both NAD and NADP, see https://enzyme.expasy.org/EC/1.5.1.39

**Comment by pgaudet** [comment]
- [ ] GO:0046592 polyamine oxidase activity EC removed - was mapped to EC:1.5.3.11, transferred to 
Transferred entry: [1.5.3.13](https://enzyme.expasy.org/EC/1.5.3.13)
Transferred entry: [1.5.3.14](https://enzyme.expasy.org/EC/1.5.3.14)
Transferred entry: [1.5.3.15](https://enzyme.expasy.org/EC/1.5.3.15)
Transferred entry: [1.5.3.16](https://enzyme.expasy.org/EC/1.5.3.16)
Transferred entry: [1.5.3.17](https://enzyme.expasy.org/EC/1.5.3.17)

Should we obsolete GO:0046592? Or make it a grouping class for the terms linked to the above ECs?

**Comment by pgaudet** [comment]
- [ ] GO:0050347 trans-octaprenyltranstransferase activity; update reaction to match RHEA

**Comment by sjm41** [comment]
> Should we obsolete GO:0046592? Or make it a grouping class for the terms linked to the above ECs?

Hi Pascale. I'd vote for making it a grouping class - the listed ECs/GO terms are all specific examples of polyamide oxidases, and it would be useful to put them all under this grouping class (rather than being direct children of 'GO:0016647 oxidoreductase activity, acting on the CH-NH group of donors, oxygen as acceptor')

**Comment by hdrabkin** [comment]
I would make it a grouping term
