### ISSUE TITLE
Missing parent to GO:0030544 Hsp70 protein binding?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#12449]
Hi,

Should 
GO:0030544 Hsp70 protein binding
not have the parent
GO:0051087 chaperone binding
?

Thanks

**Comment by paolaroncaglia** [comment]
A question for @hdrabkin . Would the link always hold true?
(Let's leave aside the discussion of how the target - bound - protein should be represented in GO...)

**Comment by hdrabkin** [comment]
No sure why I should know but my gut feeling is that the chaperone binding term should NOT even be in GO. The term chaperone is a description of what a variety of structurally unrelated proteins do (aid in folding, etc.). I vote get rid of GO:0051087

**Comment by ValWood** [comment]
I think this term is meant to use with "co-chaperones", proteins that assist chaperones
https://en.wikipedia.org/wiki/Co-chaperone like J domain and  GroES

At one point these terms fell out of favour with GO in place of 'protein binding' but for LEGO  where  you need to connect by function, these are quite useful to describe the function of a gene product, if correctly defined but maybe should be restricted for GO annotation purposes to the role of a co-chaperone in assisting in protein folding..... It's also useful to have an MF term for these, because it is a biological role that people will search for and understand.

Had a few conversations with @ukemi and @pdthomas  wrt LEGO about this so they may have input.
If it goes, thats fine, but if we keep it "co-chaperone" is probably a better primary name.

**Comment by hdrabkin** [comment]
To me it's like  enzyme binding. It implies a relatedness that does not exist structurally. Thus if something has enzyme binding I assume what is meant that it binds a specific protein that happens to have an enzymatic function. But what activity is that? If known, it would be annotated to that function as a separate annotation. 
The protein-protein interaction that results int he binding may be located nowhere near an active site, etc..
The term "binding" implies a recognition of a structure (and thus binding to it), not a binding to an activity

**Comment by Antonialock** [comment]
Yeah I saw this on a co-chaperone gene page (SPAC144.08), and thought it looked like they should be a parent/child

![screen shot 2016-05-16 at 09 20 17](https://cloud.githubusercontent.com/assets/12727506/15284156/97e2b7ec-1b47-11e6-9b86-c29d279af544.png)

**Comment by paolaroncaglia** [comment]
The chaperone discussion relates to https://github.com/geneontology/go-ontology/issues/12252
Will arrange discussion with @ValWood and @ukemi in June.
I'll set to pending for now, thanks.

**Comment by paolaroncaglia** [comment]
Note for self: Val suggested: "Let's leave this until later. The chaperone stuff might need broader discussion. Also I think the chaperones might have slightly different functional roles. I might be able to add some of these to the tickets based on some discussion with Antonia".

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
You mentioned that this ticket is not urgent, so I'll assign it to you. Perhaps some of the chaperone-relevant issues could connect to other existing tickets e.g. https://github.com/geneontology/go-ontology/issues/13021. Thanks.

**Comment by pgaudet** [comment]
@ValWood I dont think all HSP are chaperones: 

https://en.wikipedia.org/wiki/Heat_shock_protein#Role_as_chaperone


I would close this without action - let me know if you don't agree. 

Thanks, Pascale

**Comment by ValWood** [comment]
Could do. But I think the main problem here is that we can describe the same thing in 2  different ways, so bad for annotation consistency. 

The same MF can be described as  hsp70 binding, or as chaperone binding. The meaning is identical (hsp70 are always chaperones).

I don't know why we need "hsp70 binding", it could merge into "chaperone binding" ? It only has 90 EXP annotations and the vast majority have "with" fields so no loss of info, but greater consistency.

Then I don't know why we have "heat shock protein binding", this one is too general to be useful because it does not apply to a single function, or family. Again most annotations have with fields....

**Comment by pgaudet** [comment]
hsp70 binding has two siblings: 
* GO:0051008 Hsp27 protein binding
* GO:0051879 Hsp90 protein binding 

This seems to be consistent with our practice to have 'protein class' binding- isn't it ?

**Comment by ValWood** [comment]
I thought the longstanding idea was to get rid of protein class binding eventually if possible ?

These are crazy anyway.....

Hsp90 protein binding
"Interacting selectively and non-covalently with Hsp90 proteins, any of a group of heat shock proteins around 90kDa in size."

87 manual annotations

these are hsp90 superfamily in pombe:
https://www.pombase.org/gene_subset/interpro:IPR036890

I'm not sure how this term is useful if used consistently for all hsp90-class

**Comment by ValWood** [comment]
hsp27 binding has no annotations.

I would recommend to obsolete the unused one and merge the others   into protein binding and then only a small number without a "with" field would need to be fixed. 

Most could be classed better as ATPAse or chaperone or co-chaperone (aka co-chaperone activity)

It's inconsistent - but it isn't critical.

**Comment by RLovering** [comment]
FYI the UCL group has used the HSP90 terms to create 29 annnotations for 23 proteins. if a decision is taken to remove the HSP binding terms I would favour re-annotation of these to change them to chaperone binding or other function binding term. Information will be lost by just merging these with protein binding (around half of the annotations have no ID in the with field).

Ruth

**Comment by pgaudet** [comment]
@RLovering I would have merged to the parent 'heat shock protein binding' - would that be OK for everone ? @ValWood ?

**Comment by ValWood** [comment]
Well, you know what I'm going to say. I would like that one to go too.

Again, impossible to annotate consistently (proof, only 346 EXP annotations).
 Heat shock proteins are a heterogeneous bunch of proteins. There definition within GO is unclear. Is it only a protein expressed in response to heat-shock, or is it any member of a family  which is related to a heat-shock protein.

Most annotations have "with" fields.

Personally, I would merge all into protein binding. This would make very little reannotation, but annotations without 'with fields' would need to be evaluated.
Or, obsoletion if people want to consider better concurrent annotations like "chaperone" "co-chaperone" "ATPase" etc.....

If we went this route, this isn't urgent so it wouldn't be a big deal if it took a while, to give people chance to deal reannotate.
In these cases it would be nice to be able to implement an "annotation block" so that no new annotations are added to a term which is "on the way out'....e.xistign annotations would still be valid, but we would not accumulate new ones.

**Comment by selewis** [comment]
+1

**Comment by RLovering** [comment]
The 'heat shock protein binding'  merge would be fine with me, but I take the point that it would be better to have annotated to chaperone binding. I would be happy to start reannotation in this way but my main worry about re-annotation is that I am not convinced that the revised annotation information would be kept. It would be annoying to add annotations to chaperone binding and then find that this term is removed from the ontology. Personally I would rather people were encourage to capture PPIs with multiple terms: ie chaperone binding AND heat shock protein binding, rather than trying to force consistency by limiting term options. Tools can be developed to suggest terms that are often co-annotated to improve consistency. But I know that this is not the way we are heading.

**Comment by ValWood** [comment]
> Personally I would rather people were encourage to capture PPIs with multiple terms: ie chaperone binding AND heat shock protein binding, rather than trying to force consistency by limiting term options.

Co-annotation is fine to represent different activities, but it is really confusing for end-users to have  *the same* activity described in multiple ways. It also makes CAM-modelling impractical because  in this scenario the annotation would necessarily be interpreted as two different activities.

Maybe it is better to leave this for the time being. Chaperone binding has the same issues because again it is a heterogenous collection of proteins. Co chaperones bind to a chaperone and not the client. Includes DNAJ, and TPR for example. TPR are usually scaffold proteins. So co-chaperone or chaperone binding don't really  say anything about the molecular function.

However, the problem Antonia identified above is that some curators choose "chaperone binding" and some choose "hsp protein binding". This must be bad, and it wouldn't be practical (or useful in the long term) to tell people that they must use both (think transcription factors).

**Comment by hdrabkin** [comment]
I'm no expert on HSPs, but are they structurally related? I think the name is based on a collective phenotype or function and not a structural family? are there more than one HSP70, 27, or 90? If not then the go term represents a single gene product yes? Should remove is yes?

**Comment by RLovering** [comment]
Hi Harold
based on wikipedia:
https://en.wikipedia.org/wiki/Hsp70 structually conserved
https://en.wikipedia.org/wiki/Hsp27 Hsp27 is a member of the sHSP functional group; sHsps have some structural features in common: 
https://en.wikipedia.org/wiki/Heat_shock_protein The principal heat-shock proteins that have chaperone activity belong to five conserved classes: HSP33, HSP60, HSP70, HSP90, HSP100, and the small heat-shock proteins (sHSPs). 
does that help?
Ruth

**Comment by hdrabkin** [comment]
So the articles don't actually address whether in any one organism, there can be multiple forms of 33, 60, 70, etc.?  
To me conserved class means across different organisms, so when one is annotating for one organisms's gene, you would know it. Now in mouse, Hsp70 is a synonym for several different genes (Hspa1b, Hspa1b, Hspa4, , etc. (not sure if they are related other than they are heat-shock proteins). But if I would annotate the gene, I would know which one I am annotating for mouse.

**Comment by pgaudet** [comment]
Also, changed label 'chaperone binding' to 'protein folding chaperone binding' to match the term definition.
