### ISSUE TITLE
NTR: GTP 3'-8'-cyclase activity, and definition change for GO:0016830

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#12443]
The first couple of steps in the molybdenum cofactor biosynthesis pathway have recently been better elucidated; for a review, see PMID 25896388.  Essentially, the MoaA enzyme produces a previously unidentified intermediate that is then converted by MoaC into the cyclic pyranopterin phosphate intermediate.
Proposed definition for the new term:
Catalysis of the reaction GTP → (8S)-3',8-cyclo-7,8-dihydroguanosine 5'-triphosphate.
Should be under GO:0016872.  A new EC reaction is also in the works.

The existing term, GO:0016830, now would no longer start the reaction with GTP, but with that (8S)-3',8-cyclo-7,8-dihydroguanosine 5'-triphosphate intermediate, so I propose changing the definition of that term and moving the parentage to GO:0016849.  New EC reaction in the works for this as well.

Thanks,
Ingrid

**Comment by ukemi** [comment]
Hi Ingrid,

GO:0016830 is carbon-carbon lyase activity.
Did you mean GO:0061597 'cyclic pyranopterin monophosphate synthase activity'?
Def-Catalysis of the reaction GTP = cyclic pyranopterin phosphate + diphosphate.
New Def-  (8S)-3',8-cyclo-7,8-dihydroguanosine 5'-triphosphate = cyclic pyranopterin phosphate + diphosphate.

and a new term for the activity catalyzed by MoaA:
GTP 3'-8'-cyclase activity
GO:new
GTP= (8S)-3',8-cyclo-7,8-dihydroguanosine 5'-triphosphate

I think this would be correct. Then the biosynthetic process would start with GTP 3'-8'-cyclase activity.
Mentioning Peter here because we worked on this pathway last summer. @deustp01


-D

**Comment by deustp01** [comment]
Despite that history, the issue here involves hard-core questions of chemical mechanism that are beyond me. Ralf Stephan from Berlin (ralf@ark.in-berlin.de) did these annotations for Reactome as a free-lance contribution, working mostly with Bijay Jassal. We haven't been in touch with him for several years, but he really understood the chemistry and if he's still interested, would be a good person to discuss this with.
Peter

**Comment by keseler** [comment]
Oops, yeah, I did mean GO:0061597 'cyclic pyranopterin monophosphate synthase activity'.  Sometimes copy-paste just doesn't work... ;-)

If it helps, here are two links to the preview version of the reactions in MetaCyc; the same reactions have been created in the EC by Ron Caspi, our MetaCyc curator.
MoaA:
http://brg-preview.ai.sri.com/META/NEW-IMAGE?type=REACTION&object=RXN-8340
MoaC:
http://brg-preview.ai.sri.com/META/NEW-IMAGE?type=REACTION&object=RXN-17809
-Ingrid

**Comment by ukemi** [comment]
Hi Ingrid,

Thanks for the info. It looks like this is one of those cool cases where both activities are carried out by one gene in mammals and it is split in other organisms. I see three possibilities that I will most likely discuss with the other ontology editors: 

1. Change the definition of the existing term and add the new term. (your suggestion)
2. Keep the existing term (maybe with a rename) and make two new part_of children that each represent half of the reaction described in the existing term.
3. Obsolete the existing term and create two new terms, one with the existing name and defined by the second half of the reaction and the new term you suggest above for first half of the reaction.


-D

**Comment by ukemi** [comment]
Hi Ingrid,

The consensus was to use option #3.  I will update when I send the obsoletion notice.

-David

**Comment by ukemi** [comment]
Obsoletion e-mail sent.

**Comment by ukemi** [comment]
Hi Ingrid,

Sorry this has taken so long. I finally obsoleted the old activity and added the new ones. I guess this is what happens when I try to work while on vacation. Here are the stanzas for the new activities. I gave the parents that are specified in EC. Let me know if that's ok with you. I also made both of these activities necessary parts of Mo-molybdopterin cofactor biosynthetic process. If you spot anything wrong, let me know.

-David

 [Term]
+id: GO:0061798
+name: GTP 3',8'-cyclase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: GTP=(8S)-3',8-cyclo-7,8-dihydroguanosine 5'-triphosphate." [GOC:dph, GOC:ik, PMID:25896388]
+xref: EC:4.1.99.22
+xref: Metacyc:RXN-8340
+is_a: GO:0016830 ! carbon-carbon lyase activity
+created_by: dph
+creation_date: 2016-10-06T14:26:11Z
+
+[Term]
+id: GO:0061799
+name: cyclic pyranopterin monophosphate synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction:  (8S)-3',8-cyclo-7,8-dihydroguanosine 5'-triphosphate = cyclic pyranopterin phosphate + diphosphate." [GOC:dph, GOC:ik, PMID:25896388]
+xref: EC:4.6.1.17
+xref: Metacyc:RXN-17809
+is_a: GO:0016849 ! phosphorus-oxygen lyase activity
+created_by: dph
+creation_date: 2016-10-06T14:36:56Z
