### ISSUE TITLE
carbohydrate metabolism AND carbohydrate derivative metabolism

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12466]
There are still terms which are both carbohydrate metabolism and carbohydrate  derivative metabolism?
e.g. http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0060049#term=ancchart
Is that correct or are there some TVP’s lurking here?

**Comment by cmungall** [comment]
yes, non-redudant list follows. This may fall out of the ETINE work:

GO:0006037 ! cell wall chitin metabolic process
GO:0006096 ! glycolytic process
GO:0008653 ! lipopolysaccharide metabolic process
GO:0009255 ! Entner-Doudoroff pathway through 6-phosphogluconate
GO:0010493 ! Lewis a epitope biosynthetic process
GO:0015013 ! heparan sulfate proteoglycan biosynthetic process, linkage 
to polypeptide
GO:0018321 ! protein glucuronylation
GO:0018425 ! O3-(N-acetylglucosamine-1-phosphoryl)-L-serine biosynthetic 
process
GO:0019389 ! glucuronoside metabolic process
GO:0019488 ! ribitol catabolic process to xylulose 5-phosphate
GO:0019528 ! D-arabitol catabolic process to xylulose 5-phosphate
GO:0019569 ! L-arabinose catabolic process to xylulose 5-phosphate
GO:0019573 ! D-arabinose catabolic process to xylulose 5-phosphate
GO:0019574 ! sucrose catabolic process via 3'-ketosucrose
GO:0019590 ! L-arabitol catabolic process to xylulose 5-phosphate
GO:0019640 ! glucuronate catabolic process to xylulose 5-phosphate
GO:0019660 ! glycolytic fermentation
GO:0019697 ! L-xylitol catabolic process to xylulose 5-phosphate
GO:0030309 ! poly-N-acetyllactosamine metabolic process
GO:0036008 ! sucrose catabolic process to fructose-6-phosphate and 
glucose-6-phosphate
GO:0046375 ! K antigen metabolic process
GO:0046377 ! colanic acid metabolic process
GO:0046378 ! enterobacterial common antigen metabolic process
GO:0051071 ! 4,6-pyruvylated galactose residue metabolic process
GO:0051478 ! mannosylglycerate metabolic process
GO:0051672 ! catabolism by organism of cell wall peptidoglycan in other 
organism
GO:0052645 ! F420-0 metabolic process
GO:0061610 ! glycerol to glycerone phosphate metabolic process
GO:0061611 ! mannose to fructose-6-phosphate metabolic process
GO:0061624 ! fructose catabolic process to hydroxyacetone phosphate and 
glyceraldehyde-3-phosphate
GO:0061681 ! Entner-Doudoroff pathway through gluconate to 
D-glyceraldehyde-3-phosphate
GO:0061728 ! GDP-mannose biosynthetic process from mannose
GO:0071903 ! protein N-linked N-acetylglucosaminylation via asparagine
GO:0071904 ! protein N-linked N-acetylgalactosaminylation via asparagine
GO:0097370 ! protein O-GlcNAcylation via threonine
GO:1901269 ! lipooligosaccharide metabolic process
GO:1901369 ! cyclic 2,3-bisphospho-D-glycerate biosynthetic process

**Comment by ukemi** [comment]
In the case that Val points out, there was an asserted link to the regulation of carbohydrate metabolism term that does not parallel the root term. I have removed it and the inferred ones in the positive and negative regulation terms too. 

I will check the others and delete if appropriate.

**Comment by ukemi** [comment]
Just eyeballing these, they might not all be TPVs. In fact, now I'm not sure about the edits I just made. If the carbohydrate is the input and the derivative is the output or vice/versa and the process is a metabolic process, then it fits the metabolism definitions for both because the process has both as participants.

**Comment by ValWood** [comment]
I think the one I was looking at the problem is

regulation of protein glycosylation
Ontology	Biological Process
Definition	Any process that modulates the frequency, rate or extent of protein glycosylation. Protein glycosylation is the addition of a ***carbohydrate or carbohydrate derivative******unit to a protein amino acid, e.g. the addition of glycan chains to proteins.

So this cannot really go under  carbohydrate or carbohydrate derivative metabolism (but specific descendants can go under one, the other or both depending on the input/output combination....

**Comment by ukemi** [comment]
OK. Then the edits I made were ok. Whew!
I am now wondering if at this point, I should close this and let the ETINE pipeline run. I suspect this will clear up the majority. The glycolysis ones in the list above are ok because of the reason that I stated above, the pathways have both types of molecules as participants.

**Comment by ukemi** [comment]
The ones that are straight chemical metabolism terms will either fall out of the ETINES work or we need to contact ChEBI. For example mannosylglycerate  is classified as both in ChEBI.

**Comment by deustp01** [comment]
Some (probably tangential) thoughts.

First, as written, the the definition of carbohydrate metabolic process (GO:0005975) is directional: carbohydrate derivatives can participate as outputs of such a process but not as inputs. Carbohydrate derivative metabolic process (GO:1901135) lacks this constraint - derivatives can have any role, not just output. Is that difference intentional? An interesting consequence of this directionality and difference is that phosphorylation of a sugar to form a phospho-sugar qualifies for both carbohydrate metabolic process and carbohydrate derivative metabolic process, while dephosphorylation of that phospho-sugar is only carbohydrate derivative metabolism.

Second, for Val's specific case, protein glycosylation, the only applicable term is carbohydrate derivative metabolic process because (unless yeasts are different from mammals) the sugar moiety that gets added to the protein does not enter the process as free sugar (carbohydrate) but as UDP-sugar, a carbohydrate derivative.

Third, while looking for a different tangent, I found that GO:0042125 protein galactosylation is_a O:0044262 cellular carbohydrate metabolic process which in turn is_a  GO:0005975 carbohydrate metabolic process. If comment 2 is correct that's a TPV - only the path to carbohydrate derivative metabolism works.

**Comment by ValWood** [comment]
Re
Second, for Val's specific case, protein glycosylation, the only applicable term is carbohydrate derivative metabolic process because (unless yeasts are different from mammals) the sugar moiety that gets added to the protein does not enter the process as free sugar (carbohydrate) but as UDP-sugar, a carbohydrate derivative.


Yes, the same. So here we just remove the carbohydrate link.

thanks Peter....more issues though ;)

**Comment by ukemi** [comment]
Hi Peter and Val,

I don't see the directionality in the carbohydrate metabolic process definition:

The chemical reactions and pathways involving carbohydrates, any of a group of organic compounds based of the general formula Cx(H2O)y. Includes the formation of carbohydrate derivatives by the addition of a carbohydrate residue to another molecule.
The second sentence is just gloss. The formal definition is that it is a metabolic process that has_participant some carbohydrate.

I will remove the relation from # 2 above and a few other that are also incorrect.

**Comment by deustp01** [comment]
Okay - as long as the second sentence isn't a constraining part of the definition, no problem.

**Comment by ukemi** [comment]
Moved the parent glycosylation from a cellular carbohydrate metabolic process to just a carbohydrate metabolic process. This should take care of the TPV that Peter points out above. I don't think we can make them all carbohydrate derivative metabolic processes either.
