### ISSUE TITLE
NTRs/OTRs: types of cilia

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12462]
Dear @JohnvanDam and @krchristie,

Looking at children of GO:0005929 ‘cilium’, defined based on their general structure and characteristics (excluding the Giardia-specific terms), we currently have the following:

cilium
- motile cilium
- primary cilium
- - motile primary cilium
- - nonmotile primary cilium

In the past, we discussed this classification with John and Karen, and agreed that it needs revision. (For reference only, the old ticket is https://github.com/geneontology/go-ontology/issues/10740 - really long one.)
The idea is that, consistent with GO criteria, what really matters are primarily the structural differences (9 + 0 axoneme vs. 9 + 2), followed by characteristics of motility. Whether the cilium being annotated is the only one in the whole cell, or one of a few, or one of many, is slightly outside the scope of GO, but I’m happy to try to keep this further characteristic into account. 
To optimise time and resources, I was wondering if you could please confirm if the classification of vertebrate cilia below is accepted by the cilia community at large (let’s not worry about marginal exceptions; we need a schema here). If that looks reasonable to you, I’ll create new terms, and edit existing ones, accordingly. And I’ll check if annotations need moving (or will ask for your help with that, we’ll see). Here’s the paper, please look at figure 3:

http://www.ncbi.nlm.nih.gov/pubmed/?term=22118931 

Let’s agree on the solution first, then I can suggest term names, definitions etc.
(I’d like to keep it simple. The cell types mentioned in the blue and red boxes would end up in the definition gloss or in a def. comment.)
In an old ticket, Karen had also suggested this: “The Fisch and Dupuis-Williams 2011 review "Ultrastructure of the cilia and flagella - back to the future" [http://www.ncbi.nlm.nih.gov/pubmed/21728999] looks like it has a very useful section, subtitled "Basic axonemal structure", that may help sort out the issue of how to group cilia based on structure, either 9+0 or 9+2 with or without other structures correlated with motility.”. I only had time to skim it briefly; I still like the schematic representation in the other paper above, and that’s from 2012, so more recent (ok, just a little).

To keep in mind once we’ve agreed on a general solution:
- [x] Does this work for non-vertebrate cilia too? If not, and should we need additional, non-vertebrate terms in the future, can they be accommodated below this structure?
- [x] An example of multiple non-motile cilia is the olfactory knob (see PMID:20801626), just in case we want to capture this.
- [x] If we keep/have a term for ‘motile cilium’, add link capable_of_part_of ‘cilium movement’.

**Comment by JohnvanDam** [comment]
That Takeda paper has a nifty overview indeed. I've learned something new :-)
I still have to read most of it though. I am not sure if this is widely appreciated within the field but at face value this classification seems straightforward.

Now, assuming we leave the solitary vs multiple cilia issue for now, we could construct the following derived table:
                                  9+0                             9+2
- Motile                      Class II & IV               Class VI & VIII
- Non-motile              Class I & III                 Class V & VII

We basically get four categories.

As a solution to our problem I guess we'll need to redefine the main motile cilium and primary cilium terms to represent the four categories. Question is if we do this by first distinguishing between axoneme configuration and then by (im)motility, or by the reverse? The advantage of the first option would be that it makes more sense to link the specific axonemal parts to the 2nd level terms (e.g. "9+2 motile"), which then (more or less correctly) flow into the higher order terms (e.g. 9+2). In the reverse both motile and immotile cilia would end up with nearly all cilium parts making the distinction almost useless. 

Or alternatively, do we just create four terms at the same level? We could be more specific that way. However annotation-wise, I can see the use for more generic terms like "motile cilium" because those are the terms often used in literature... I am not sure what would be the best way to go about that. I'll drop in later this week to continue on this (I should be doing something else now actually...)

**Comment by paolaroncaglia** [comment]
Thanks @JohnvanDam . My feeling is that classifying based on structure (i.e. axonemal configuration) would be better, but I'll leave this open for more comments.

**Comment by krchristie** [comment]
That Takeda review you've pointed out Paola is an interesting perspective, very interesting so far, though I don't know if I have time to finish it.

Anyway, I would lean towards classifying on structure first, and then motile vs non-motile as subtypes within each structure, as I think the structural differences represent a substantive difference in the types. The motility of the non-motile primary cilia of the embryonic mouse node is very different than the motility of the motile cilia in epithelial cells or sperm. I also agree that we don't need to deal with single versus multiple cilia/cell in the structural classification. From what I've encountered with multiciliated epithelial cells, it seems like the main difference is the need for some extra regulation to generate lots of centrioles to become basal bodies. Then after that, the cilia are pretty standard 9+2 motile cilia.

I think we need to be careful with how we name the terms though because we don't want people to just see the term "motile cilium" and assume that any motile cilium should be annotated there. I think that has actually been a problem when people are annotating the mouse embryonic node.

The cilia meetings I have gone to have included talks about chlamydomonas and occasionally other organisms. I have also occasionally annotated some chlamy papers when I needed them for PAINT. From this, I think that the classifications that we are making for vertebrate cilia will also work for non-vertebrates. If you like, I could check with a Chlamy expert I have a good relationship with to get his opinion.

-Karen

**Comment by paolaroncaglia** [comment]
Thanks @JohnvanDam  and @krchristie . It sounds like the classification from the Takeda review would work; we’d simplify it by ‘eliminating’ the discriminating factor ‘solitary cilium vs. multiple cilia’ that we care less about. So, we’d want to have:

1) 9+0 non-motile cilia (which include authentic primary cilia, but are not limited to them), 
2) 9+0 motile cilia (which include classic nodal cilia, but are not limited to them), 
3) 9+2 non-motile cilia, 
4) 9+2 motile cilia (which include so-called flagella and conventional motile cilia).

These terms could contain the info from the various Takeda classes in their definition gloss or comments (see John’s schema above).

If we 
a) make these 4 terms is_a children of ‘cilium’, without adding any intermediate term such as ‘motile cilium’
and
b) re-house or merge these existing terms accordingly: ‘motile cilium’, ‘primary cilium’, ‘motile primary cilium’ and ‘nonmotile primary cilium’
then I think we have addressed Karen’s concern
“I think we need to be careful with how we name the terms though because we don't want people to just see the term "motile cilium" and assume that any motile cilium should be annotated there. I think that has actually been a problem when people are annotating cilia of the mouse embryonic node.”.

Would the community approve of the ‘9+x’ namings? i.e. 9+0 non-motile cilia, 9+2 motile cilia, etc?
That’s how Takeda lists them, so I’m hoping it’d be fine, because the alternative would be ‘9+0 axoneme-containing non-motile cilium’ or similar, which I don’t really fancy. If you’ve encountered this type of simplified nomenclature in the literature you’re familiar with, I think we can go for it.

Once this is settled, I’ll work out the details (new term stanzas and placement of existing terms), and then Karen may kindly check with some non-vertebrate expert if our classification would work for non-vertebrate such as Chlamydomonas too.

Let me know. Thanks!

**Comment by JohnvanDam** [comment]
Some quick examples of literal usage of these terms in literature:

"9+2 motile cilia": http://www.ncbi.nlm.nih.gov/pubmed/26506310
"9+2 non-motile cilia": http://www.nature.com/nrm/journal/v8/n11/full/nrm2278.html figure 1
This one uses three of the four (excluding 9+2 non-motile) terms: http://www.nature.com/gim/journal/v11/n7/full/gim200967a.html

You can find many more with trivial variations like "non-motile 9+2 cilium" etc.

My personal estimation would be that the community would approve of these terms since they are actually being used to make the distinction.

**Comment by paolaroncaglia** [comment]
Brilliant! Thanks @JohnvanDam .
I’d prefer to have the primary name e.g. ”9+2 non-motile cilium”, and use "non-motile 9+2 cilium" in a synonym, rather than the other way round, to reflect the fact that the primary discrimination is based on axoneme structure, and motility comes next.
I’ll give it until next week before I implement so we can hear if @krchristie  agrees too. I know she’s busy with curation week at MGI this week.

**Comment by JohnvanDam** [comment]
I agree with your preference for the same reason.

**Comment by krchristie** [comment]
Hi Paola,

This seems really good to me. I agree with the logic you've used for how to name the terms, and think your proposal addresses the concerns I brought up earlier. Like John, I've seen these terms used in papers, with the exception of "9+2 non-motile cilia". I'm not aware of that particular type of cilia in mouse.

-Karen

**Comment by paolaroncaglia** [comment]
Note for self: 
When cilia type nomenclature is finalised in GO, remember to align it across branches where necessary (e.g., in the 'protein localisation to cilium' branch).

**Comment by paolaroncaglia** [comment]
Hi @JohnvanDam and @krchristie,

Based on previous discussion in this ticket, I propose to add the following new terms as is_a children of ‘cilium’:

GO:NEW1 9+0 non-motile cilium  
A non-motile cilium where the axoneme has a ring of nine outer microtubule doublets but no central microtubules (and is therefore called a 9+0 axoneme).
comment: This type of cilia may be present in solitary (authentic primary cilia in many cell types) or in multiple copies (e.g. in Grueneberg ganglion neurons). 
GOC:cilia, PMID:22118931
exact synonym: non-motile 9+0 cilium
narrow synonym: primary cilium

GO:NEW2 9+0 motile cilium 
A motile cilium where the axoneme has a ring of nine outer microtubule doublets but no central microtubules (and is therefore called a 9+0 axoneme).
comment: This type of cilia may be present in solitary (classic nodal cilia in embryonic nodes) or in multiple copies (e.g. in the choroid plexus epitelium). 
GOC:cilia, PMID:22118931
exact synonym: motile 9+0 cilium
narrow synonym: nodal cilium

GO:NEW3 9+2 non-motile cilium 
A non-motile cilium where the axoneme has a ring of nine outer microtubule doublets plus two central microtubules (and is therefore called a 9+2 axoneme). 
comment: This type of cilia may be present in solitary (e.g. in inner hair cells) or in multiple copies (e.g. in olfactory neurons). 
GOC:cilia, PMID:22118931
exact synonym: non-motile 9+2 cilium

GO:NEW4 9+2 motile cilium 
A motile cilium where the axoneme has a ring of nine outer microtubule doublets plus two central microtubules (and is therefore called a 9+2 axoneme). 
comment: This type of cilia may be present in solitary (so-called flagella, e.g. in sperm) or in multiple copies (so-called conventional motile cilia, e.g. in tracheal epithelium, ependyma or oviduct epithelium). 
GOC:cilia, PMID:22118931
exact synonym: motile 9+2 cilium
narrow synonym: sperm flagellum
narrow synonym: conventional motile cilium

Once the new terms above are in place, we’ll have to adjust placement of existing terms ‘motile cilium’ and ‘primary cilium’ (and all their descendants!) accordingly. I’ll do this next. In the meantime, @krchristie , could you please check with your non-vertebrate-expert colleague if our classification would work for non-vertebrates such as Chlamydomonas too? If not, and should we need additional, non-vertebrate terms in the future, can they be accommodated below this structure?

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Let’s start from 

motile cilium [288 direct manual annotations, of which 126 experimental] 
- longitudinal flagellum [found in dinoflagellates, it’s a 9+2 motile cilium, no annotations] => I’ll place this as is_a 9+2 motile cilium
- sperm flagellum [9+2 motile cilium, 101 direct manual annotations, of which 58 experimental] [only has part_of children, no classification issues there] => I’ll place this as is_a 9+2 motile cilium
- transverse flagellum [found in dinoflagellates, it’s a 9+2 motile cilium, no annotations] => I’ll place this as is_a 9+2 motile cilium

The difficulty here is how to place ‘motile cilium’ per se. It’s defined as “A cilium which has a *variable* arrangement of axonemal microtubules, contains molecular motors, and beats with a characteristic whip-like pattern that promotes cell motility or transport of fluids and other cells across a cell surface. Motile cilia are typically found in multiple copies on epithelial cells that line the lumenal ducts of various tissues. Motile cilia may also function as sensory organelles.”
(Def. comment: “Note that this term should not be confused with 'motile primary cilium ; GO:0031512'. Motile cilia are distinct from motile primary cilia (GO:0031512) that are typically present during embryogenesis in a single copy per cell, affect asymmetric body plan organization, and move in a rotational manner, as opposed to a whip-like, manner.”)
So, it sounds like ‘motile cilium’, on paper, may encompass both ‘9+0 motile cilium’ and ‘9+0 motile cilium’. I guess we’d need to look at direct experimental annotations to figure out the best solution here - @JohnvanDam  and @krchristie  can you help please?

**Comment by paolaroncaglia** [comment]
@JohnvanDam and @krchristie
Let’s continue with

primary cilium
- motile primary cilium [see below]
- nonmotile primary cilium [see below]
- - [part_of] ciliary transition zone [has further part_of children, no placement issues there] => I think we resolved in the past that this should be part_of ‘cilium’, more broadly. Is this correct John and Karen?
- - kinocilium [this is a 9+0 non-motile cilium, correct John and Karen? If yes, I’ll place this as is_a ‘9+0 non-motile cilium’]
- - photoreceptor connecting cilium [9+0 structure] but see def. comment to ‘ciliary transition zone’: “Note that the connecting cilium of the photoreceptor cells is thought to be equivalent to the transition zone.” so I’ll place ‘photoreceptor connecting cilium’ as is_a ‘ciliary transition zone’, and remove the is_a link to cilium types, and add a def. comment “Note that the connecting cilium of the photoreceptor cells is thought to be equivalent to the ciliary transition zone.”
- - photoreceptor outer segment [9+0 structure] [has part_of children, no placement issues there] => I’ll place this as is_a ‘9+0 non-motile cilium’

I presume that ‘nonmotile primary cilium’ could be merged into the new term ‘9+0 non-motile cilium’, but I can’t be sure based on its definition. It has 169 direct experimental annotations. I’ll need your help with this one.
Same for its sibling ‘motile primary cilium’, I’ll need advice. This one has only 15 direct experimental annotations, so hopefully easier.
Last but not least, ‘primary cilium’ poses the same problem - and has 82 direct experimental annotations.

Thanks,
Paola

**Comment by krchristie** [comment]
My understanding was that "nonmotile primary cilium" is equivalent to "9+0 non-motile cilium" and "motile primary cilium" is equivalent to "9+0 motile cilium". I am wondering if it be better to just change the names of the existing terms, rather than create new terms and merge these into them. If you feel it's best to create new terms, I think the older terms could be merged into the new ones. 

Regarding the kinocilium, I was surprised to learn this week that the kinocilium is a 9+2 non-motile. It is currently placed in the graph as a child of "nonmotile primary cilium", which would be wrong on the thought that "nonmotile primary cilium" is synonymous with "9+0 nonmotile cilium", but I guess accurately reflects a definition of "nonmotile primary cilium" based on being a nonmotile single cilium. I think you can just move this to be a type of "9+2 nonmotile cilium" though. I don't think this will cause issues with annotations since, in my experience, when the paper is discussing "kinocilia", it is specifically mentioned by that name, so I've annotated to the specific term "kinocilium". 

Then, with respect to the annotations, at least with respect to the mouse annotations, I don't see anything obviously wrong with transferring the annotations from "nonmotile primary cilium" to "9+0 nonmotile cilium". While many of the mouse genes annotated to this term are generally present in all cilia, in the annotations here, based on the extension information the type of cilium was clearly a 9+0 nonmotile type with respect to the type of cell, so I'd be fine with just having these annotations be made to the term named "9_0 nonmotile cilium", whichever way you do the edits. I also don't think the current placement of the term "kinocilium" will affect being able to transfer the annotations from "nonmotile primary cilium" to "9+0 nonmotile cilium" since as I mentioned above, I think the kinocilium annotations have been made specifically enough to just move that term to the appropriate parent.

**Comment by paolaroncaglia** [comment]
Thanks @krchristie !
I'm on leave until August 23rd, so will follow up on this ticket after that date.

**Comment by krchristie** [comment]
This Reiter et al. paper corroborates the definition comment you pointed out: "Note that the connecting cilium of the photoreceptor cells is thought to be equivalent to the transition zone."

Thus, I agree with your suggestion to place ‘photoreceptor connecting cilium’ as is_a ‘ciliary transition zone’, and remove the is_a link to cilium types. 

Thinking this through makes me wonder though, if it is accurate to say that the "photoreceptor outer segment" is_a type of cilium either. It seems to me that if the cilium is defined as the entire structure including the transition zone, then the "photoreceptor outer segment" is also a part of a cilium rather than a type of cilium. Maybe we need a term for "photoreceptor cilium", which would then have both "photoreceptor connecting cilium" and "photoreceptor outer segment" as part_of terms.

Reiter JF, Blacque OE, Leroux MR. The base of the cilium: roles for transition fibres and the transition zone in ciliary formation, maintenance and compartmentalization. EMBO Rep. 2012 Jun 29;13(7):608-18. doi: 10.1038/embor.2012.73. Review. PubMed PMID: 22653444

**Comment by krchristie** [comment]
@paolaroncaglia Enjoy your time off

**Comment by krchristie** [comment]
Regarding annotations for ‘primary cilium’ with 82 direct experimental annotations, I don't see any way to automatically assign these annotations to one of the new terms.

**Comment by krchristie** [comment]
I sent a couple emails to Pete Lefebvre (Chlamy) and Greg Pazour to ask about this proposal. It is fine for Chlamy, but Chlamy cilia are 9+2 motile. However Greg forwarded this on to a couple other cilia researchers and they have brought up some issues.

I have cc'd @paolaroncaglia and @JohnvanDam  on the email thread and will post the email discussion here, pending consent.

**Comment by paolaroncaglia** [comment]
I replied to the email thread above. I'm copying the relevant text below:

"In her previous email below, Karen outlined some aspects of GO that drive our way of ‘classifying’ things. I think we can address your concerns (see below) and revise our proposal to accommodate some intermediate classes. In summary, 

- As Karen noted, the role of ciliary proteins in sensory vs. motility processes would be captured by annotating to relevant biological process terms - rather than embedding those processes in ‘cilium’ cellular component terms. This provides maximum flexibility and benefit, e.g. in data analysis, and makes classification of cellular components easier.  

- We appreciate the importance for researchers of the basic distinction between motile and non-motile cilia, regardless of axonemal structure. We can certainly represent this by intermediate terms in our proposed ontology structure:

- cilium
- - motile cilium
- - - 9+0 motile cilium
- - - 9+2 motile cilium
- - non-motile cilium
- - - 9+0 non-motile cilium
- - - 9+2 non-motile cilium

- GO doesn’t aim to represent with specific terms *all* possible instances, e.g. all types of axonemal structure observed in nature. At the same time, GO allows to annotate gene products that don’t conform to e.g. 9+0 or 9+2 structure by referring to a broader parent term (‘cilium’ in this case). So ‘cilium’ already covers the category ‘cilium, other’ that George kindly suggested. We’ll embed annotation guidance in ‘cilium’ (by adding a comment visible to all curators and users) so people know that they can use this term to represent e.g. insect cilia or rabbit notochord 9+4 cilia. (Unless they have evidences allowing them to use ‘motile cilium’ or ‘non-motile cilium’.) Similarly, ‘cilium’ may be used in instances where motility is unknown. 
 
- Finally, we’d be happy to better represent in GO biological processes and players that drive multiciliation in cells with multiple cilia. We already have the term GO:0032054 ‘ciliary basal body duplication’. At the moment, this has been used only for Trypanosomes and Leishmania. As curators come across recent or future literature on the details of the basal body duplication pathway in higher species, including factors that positively regulate it, this knowledge will be captured in GO. This can be done in two ways: by expanding the ontology (e.g. by adding ‘positive regulation of ciliary basal body duplication’ and/or terms to describe how the duplication proceeds and what sub-process it consists of), and by adding annotations (e.g. associating mouse or human proteins involved in the duplication with appropriate ontology terms). All this is best done when knowledge in the field has reached a certain degree of experimental confirmation and agreement, but if you have suggestions that you’d like to see incorporated at this stage already, we’ll certainly look into them!"

NOTE: going for the a revised classification with intermediate terms, as below, and adding curation guidance, would allow to address some of the experts’ concerns:

- cilium
- - motile cilium
- - - 9+0 motile cilium
- - - 9+2 motile cilium
- - non-motile cilium
- - - 9+0 non-motile cilium
- - - 9+2 non-motile cilium

where 
‘cilium’ could be used when motility is unknown
‘cilium’ (or ‘motile cilium’ or ‘non-motile cilium’) could be used for all ‘unusual’ axonemal structures (9+4 etc.)

AND 

we could keep the current term GO:0031514 ‘motile cilium’. If we don’t have resources to look at its 288 direct manual annotations, of which 126 experimental, they could still sit where they are and be correct.

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Giardia flagella terms should probably all sit under 'motile cilium'...

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Giardia flagella terms should probably all sit under 'motile cilium'... or even more specifically under one of its children if axonemal structure is known. Same for dinoflagellates longitudinal and transverse flagella.

**Comment by paolaroncaglia** [comment]
Added GO:0097728 9+0 motile cilium and GO:0097729 9+2 motile cilium.

**Comment by paolaroncaglia** [comment]
Added links:
‘9+0 motile cilium’ has_part 'axonemal outer doublet';
‘9+2 motile cilium’ has_part 'axonemal outer doublet' and has_part 'axonemal central pair'.

**Comment by paolaroncaglia** [comment]
Added 
- GO:0097730 non-motile cilium
- - GO:0097731 9+0 non-motile cilium
- - GO:0097732 9+2 non-motile cilium

**Comment by paolaroncaglia** [comment]
Moved ‘ciliary transition zone’ from part_of ‘nonmotile primary cilium’ to part_of ‘cilium’, which is more correct.

**Comment by paolaroncaglia** [comment]
Moved ‘kinocilium’ from is_a ‘nonmotile primary cilium’ to is_a ‘9+2 non-motile cilium’, as Karen suggested.

**Comment by paolaroncaglia** [comment]
Added GO:0097733 'photoreceptor cell cilium' and rearranged its parts as agreed previously.

**Comment by paolaroncaglia** [comment]
Re-reading the thread and considering that the indication of a cilium being ‘primary’ (i.e. in single copy) doesn’t really add much information, as agreed with the experts, I’ll adopt this strategy:

- [ ] merge ‘motile primary cilium’ into ‘motile cilium’

- [ ] merge ‘nonmotile primary cilium’ into ‘non-motile cilium’

- [ ] merge ‘primary cilium’ into ‘cilium’

This way, all pre-existing annotations will still be correct. Any information about cilia being involved in specific sensory processes should, as agreed, be captured via BP terms - and I expect that was done in the past too.

**Comment by paolaroncaglia** [comment]
Cleaning up and reviewing all comments in this thread:

Added to definition comment of ‘cilium’:
Also, ‘cilium’ may be used when axonemal structure and/or motility are unknown, or when axonemal structure is unusual. For all other cases, please refer to children of ‘cilium’. Finally, note that any role of ciliary proteins in sensory events should be captured by annotating to relevant biological process terms.

Added logical definition to ‘motile cilium’ (capable_of_part_of ‘cilium movement’).

Revised comment of ‘9+2 non-motile cilium’ to the correct one (“This type of cilia may be present in solitary (e.g. in inner hair cells) or in multiple copies (e.g. in olfactory neurons).”).

**Comment by paolaroncaglia** [comment]
I can't believe I'm closing this ticket. Happy weekend everyone.

**Comment by krchristie** [comment]
Great work @paolaroncaglia !!

Happy weekend to you too :)
