### ISSUE TITLE
New terms related to 'cytosylglucuronate decarboxylase'

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#12476]
Name: Gemma Holliday
E-mail: gemma.l.holliday@gmail.com
Subject: Ontology (e.g. structure, relations, subsets/slims...)
Comment or query:
Hi,

How do I add new terms based on the overall chemical transformation of the
enzyme I'm annotating – e.g. I have an enzyme "cytosylglucuronate
decarboxylase" but this doesn't yet have an EC number or an associated term
in GO. I have looked at TermGenie, but I'm not sure how to classify the term
to add it. Please can you advise as have several cases of this)

Kind regards
Gemma

**Comment by tberardini** [comment]
Discovery and characterization of BlsE, a radical S-adenosyl-L-methionine decarboxylase involved in the blasticidin S biosynthetic pathway.
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0068545

"Biochemical results showed that BlsE is a SAM-dependent radical enzyme that utilizes cytosylglucuronic acid, the accumulated intermediate metabolite in blsE mutant, as substrate and catalyzes decarboxylation at the C5 position of the glucoside residue to yield cytosylarabinopyranose."
(see Figure 1, boxed reaction)

The new term should probably be a child of 'adenosylmethionine decarboxylase activity, GO:0004014'

http://amigo.geneontology.org/amigo/term/GO:0004014

**Comment by paolaroncaglia** [comment]
For reference, here's the link to the GO helpdesk ticket: 
http://jira.geneontology.org/browse/GO-1242

**Comment by paolaroncaglia** [comment]
The enzyme doesn’t seem to be in Rhea either (http://www.rhea-db.org/home). 
Wrt the placement of the new term, I’d opt for is_a GO:0016831 carboxy-lyase activity. This is also the parent for 'adenosylmethionine decarboxylase activity, GO:0004014’. I think this broad parent might be a safer bet (the enzyme is “SAM-dependent” but acts on cytosylglucuronic acid). Also, I’d add a taxon constraint because blasticidin S is produced by bacteria (we can always relax this rule if new knowledge emerges). So here’s the new term, we can modify it if Gemma has any objection:

[Term]
id: GO:1990965
name: cytosylglucuronate decarboxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: cytosylglucuronic acid + H(+) = cytosylarabinopyranose + CO(2)." [GOC:pr, GOC:tb, PMID:23874663]
comment: This enzymatic activity was shown to be involved in the bacterial blasticidin S biosynthetic pathway.
is_a: GO:0016831 ! carboxy-lyase activity
relationship: only_in_taxon NCBITaxon:2 ! Bacteria <prokaryote>

Note that, strictly speaking, it seems to me that there’s an extra H atom in the first half of the reaction, based on the CHEBI entries that Gemma herself has submitted for cytosylglucuronic acid and cytosylarabinopyranose.

Thanks,

Paola

**Comment by GLHolliday79** [comment]
Hi all,

I commented on the JIRA ticket, but will copy here.

I am absolutely happy with the annotation suggested. I also note that there is a two domain requirement for the particular enzyme that I am trying to annotate -- I am unsure if that kind of information should also be included in the GO term? The domains are the Radical SAM and SPASM domains.

**Comment by GLHolliday79** [comment]
Am I also correct in thinking that there should be a process term blasticidin-S biosynthesis?

**Comment by paolaroncaglia** [comment]
Hi @GLHolliday79 ,

For completeness, I’m copying here your full comments from the GO helpdesk ticket, so I can close that and move all discussion here. I will then address all issues:

“Thanks for all your feedback on this one – I agree with everything said above. I would maybe add that for full activity the enzyme requires two domains Radical SAM and SPASM (PF04055 and PF13186 respectively). I don't know if that's the kind or rule based info that can be added?”
“I see the extra H, I suspect that the conjugate acid should be the substrate. Would you like me to add this molecule to ChEBI?”

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
Hi again @GLHolliday79 ,

Summing up:

1) Yes, please add the conjugate molecule to ChEBI, thanks.

2) We don’t usually record domain info at that level of detail, because that pertains more to the proteins themselves than to the molecular function they carry out. 
The domain requirement might rather be captured at the Pfam level - by mapping PF04055 and PF13186 to GO:1990965 if appropriate. That would mean that any protein containing PF04055 and/or PF13186 would be annotated to ‘cytosylglucuronate decarboxylase activity’ via the InterPro2GO mappings. Please contact the InterPro team if you wish to suggest that.

3) I created the following terms:
ID: GO:1905264 Label: blasticidin S metabolic process
ID: GO:1905265 Label: blasticidin S catabolic process
ID: GO:1905266 Label: blasticidin S biosynthetic process
I could add the link
‘cytosylglucuronate decarboxylase activity’ part_of ‘blasticidin S biosynthetic process’ 
but only if it is reasonable to assume that the related enzyme has no role in processes other than the synthesis of blasticidin S (so that the part_of would *always* be true). Could you please comment on this? 

Thanks,

Paola

**Comment by paolaroncaglia** [comment]
Hi @GLHolliday79 ,

I'll close this ticket now, but you can let me know if you have any more comments, thanks.

Paola
