### ISSUE TITLE
NTR : lipid particle exit from endoplasmic reticulum as a child of intracellular lipid particle transport

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#12473]
Dear GO editors,
the terms  GO:0032527 protein exit from endoplasmic reticulum and GO:0031887 lipid particle transport along microtubule do not allow me to describe the function of the 2 genes described in that paper PubMed=27138255. Indeed, MIA2 and MIA3 are involved in the "lipid particle exit from the endoplasmic reticulum". 

Could you please create that term that could be a child of 

"intracellular lipid particle transport"

 that does not exist either.

Thanks in advance for your help.
Lionel

**Comment by lbreuza** [comment]
I finally used GO:0042953 lipoprotein transport, and therefore I do not need "intracellular lipid particle transport". However, one could still create lipoprotein transport from the endoplasmic reticulum as a child of GO:0042953 lipoprotein transport.

**Comment by paolaroncaglia** [comment]
Hi Lionel,

There's a TermGenie template that you can use to request 'lipoprotein transport from endoplasmic reticulum to cytosol' (similar to GO:1903514 'calcium ion transport from endoplasmic reticulum to cytosol'). I can't check the name of the template because TG is being restarted at the moment, but look for transport_to_from or similar. TG will be available again in a few minutes. If not, or if you have any question, let me know. Thanks!

Paola

**Comment by lbreuza** [comment]
Hi Paola,

I do not see how I could use TG to create the equivalent of  GO:0032527 protein exit from endoplasmic reticulum for lipoprotein particle (GO:1990777) and but also for lipid particle (GO:0005811). In that case, it is not a FROM - TO that I should use since it is just exit from one compartment. I guess the next 'station' is Golgi but it is not shown in the paper.
Thanks,
Lionel

**Comment by paolaroncaglia** [comment]
Hi Lionel,

Thanks. The idea is that, if something leaves the endoplasmic reticulum, it goes into the cytosol first of all, regardless of whether it goes to Golgi then, or not, or somewhere else. Because the ER is surrounded by the cytosol. This said, I am now confused as to what term(s) you’d need: is it 

1) ’lipoprotein transport from endoplasmic reticulum (to cytosol)’ as you suggested in your previous comment (“However, one could still create lipoprotein transport from the endoplasmic reticulum as a child of GO:0042953 lipoprotein transport”), where lipoprotein refers to CHEBI:6495 lipoprotein, or 

2) ‘lipoprotein particle transport from endoplasmic reticulum (to cytosol)’ and/or ‘lipid particle transport from endoplasmic reticulum (to cytosol)’?

If it’s 1), you can create it using the TermGenie template called ‘chemical_transport_from_to’.

But if it’s 2), looking at the paper you quote, the process(es) those proteins are involved in seem upstream of the actual exit of lipoprotein/lipid particles: 
“our data indicate that TANGO1 and TALI both participate in the binding and concentration of ApoB-containing lipid particles for their subsequent export from the ER. … we suggest that TANGO1 and TALI work together to collect ApoB-containing lipid particles in the lumen of the ER” 
Therefore I’m not sure that transport terms would be precise in this case. Of course, ultimately the exit of those particles would be affected if those proteins were mutated.

Please let me know what term(s) you’d need exactly, if any :-)
Thanks!
Paola

**Comment by lbreuza** [comment]
On 09.06.2016 13:57, paolaroncaglia wrote:
>
> Hi Lionel,
>
> Thanks. The idea is that, if something leaves the endoplasmic 
> reticulum, it goes into the cytosol first of all, regardless of 
> whether it goes to Golgi then, or not, or somewhere else. Because the 
> ER is surrounded by the cytosol. This said, I am now confused as to 
> what term(s) you’d need: is it
>
Secreted proteins that are synthesized in the lumen of the endoplasmic 
reticulum, are enriched at ER exit sites (lumenal side) and then 
incorporated in the lumen of membrane-bound vesicles (generally COPII 
vesicles) that bud from the ER and will fuse with other compartments 
like the Golgi. Therefore, a protein, a lipoprotein can exit the ER 
within a membrane bound vesicle without going into the cytosol. The 
proteins I want to annotate play a role in the incorporation of lumenal 
ER lipoproteins into membrane bound structures that will allow their 
transport to other membrane boubd compartments before they reach the 
plasma membrane to be released extracellularly. Figure 8 of the paper I 
quoted will give you an idea of these mega carriers.
I cannot agree on the fact that thex first go to the cytosol and 
therfore none of proposition 1 or 2 can help me.
Thanks
Lionel
>
> 1) ’lipoprotein transport from endoplasmic reticulum (to cytosol)’ as 
> you suggested in your previous comment (“However, one could still 
> create lipoprotein transport from the endoplasmic reticulum as a child 
> of GO:0042953 lipoprotein transport”), where lipoprotein refers to 
> CHEBI:6495 lipoprotein, or
>
> 2) ‘lipoprotein particle transport from endoplasmic reticulum (to 
> cytosol)’ and/or ‘lipid  particle transport from endoplasmic reticulum 
> (to cytosol)’?
>
> If it’s 1), you can create it using the TermGenie template called 
> ‘chemical_transport_from_to’.
>
> But if it’s 2), looking at the paper you quote, the process(es) those 
> proteins are involved in seem upstream of the actual exit of 
> lipoprotein/lipid particles:
> “our data indicate that TANGO1 and TALI both participate in the 
> binding and concentration of ApoB-containing lipid particles for their 
> subsequent export from the ER. … we suggest that TANGO1 and TALI work 
> together to collect ApoB-containing lipid particles in the lumen of 
> the ER”
> Therefore I’m not sure that transport terms would be precise in this 
> case. Of course, ultimately the exit of those particles would be 
> affected if those proteins were mutated.
>
> Please let me know what term(s) you’d need exactly, if any :-)
> Thanks!
> Paola
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/12473#issuecomment-224873997>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ANhinEIw_FSTUPzQCFlufwe7tsPOh-9uks5qJ__FgaJpZM4Iu8Gh>.Web 
> Bug from 
> https://github.com/notifications/beacon/ANhinMssCG3-tuMBCdIe89mkYL_WLA7Aks5qJ__FgaJpZM4Iu8Gh.gif
>

-- 
Lionel Breuza, PhD
UniProtKB/Swiss-Prot
Chordata protein curation program

lionel.breuza@sib.swiss
SIB | Swiss Institute of Bioinformatics
CMU - 1, rue Michel Servet - CH-1211 Geneva 4 - Switzerland
tel +41 22 379 5043 - fax +41 22 379 5858


www.sib.swiss - www.uniprot.org

**Comment by paolaroncaglia** [comment]
Hi @lbreuza ,

Thanks for clarifying.
Unfortunately the EBI library subscription doesn’t grant me access to the full text of PMID:27138255, therefore I can’t see its fig 8 or read the details.
However, from what you write, it seems that one of these existing terms may be appropriate:

GO:0035459 cargo loading into vesicle
Def: “The formation of a protein complex between the coat proteins and proteins that are going to be transported by a vesicle.”
(We could probably broaden the definition to refer to transported *lipoproteins* as well as proteins)

and/or one of its children, especially

GO:0090110 cargo loading into COPII-coated vesicle
GO:1901301 regulation of cargo loading into COPII-coated vesicle
(‘positive regulation of cargo loading into COPII-coated vesicle’ doesn’t exist yet, but if that’s what you need, you could request it via TG.) 

Let me know if any of these would work for you. 
Cheers,
Paola

**Comment by paolaroncaglia** [comment]
Hi @lbreuza ,

I'll close this ticket now, but if you have any feedback based on my latest comment is this thread, please feel free to add it here and I'll re-open the ticket.

Best regards,

Paola

**Comment by lbreuza** [comment]
Hi Paola,
now I realized I probably misunderstood what the term GO:0032527 protein exit from endoplasmic reticulum describes. If it only refers to the transport from the lumen of the ER toward the cytosol, then it does not apply to what I want to describe and my request was unfounded. I will therefore use the terms you were suggesting except that it would be better if the definitions were broadened to include cargo that are not strictly protein but can also be lipoproteins as you were suggesting. Could you do that?
Thanks for your help,
Lionel

**Comment by paolaroncaglia** [comment]
Hi @lbreuza ,
Yes, I re-opened the ticket and will do those edits soon.
Thanks,
Paola.

**Comment by lbreuza** [comment]
Hi Paola,
Can I consider this has been done and close the ticket?
Thanks,
Lionel

**Comment by paolaroncaglia** [comment]
Hi @lbreuza ,
Thanks for the reminder - I'll complete the edits today or tomorrow and will then close the ticket.
Paola

**Comment by paolaroncaglia** [comment]
Hi @lbreuza ,

I edited the definition and placement of GO:0035459 ‘cargo loading into vesicle’, and of its descendants.
So now ‘cargo loading into vesicle’ is defined as “The formation of a macromolecular complex between the coat proteins and proteins and/or lipoproteins that are going to be transported by a vesicle.”, and is_a cellular macromolecular complex assembly. Closing now.

Thanks for your patience,

Paola
