### ISSUE TITLE
NTR: epidermal growth factor receptor signaling pathway involved in heart process

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12475]
Dear Editors,

I'd like to request a new term re: PMID:23069713
In this study inhibition of epidermal growth factor receptor (EGFR) was shown to promote cardiogenic differentiation of human Mesenchymal Stem Cells (hMSCs) and the transplantation of hMSCs, in which EGFR was inhibited, resulted in enhancement of heart functions. hMSCs transfected with microRNA-133a (miR-133a), which targets EGFR, expressed cardiac-specific markers and luciferase assays demonstrated that EGFR is silenced by miR-133a.

The new requested term: 'epidermal growth factor receptor signaling pathway involved in heart process'. 

I am subsequently planning to request regulation terms to create the following annotation:

hsa-miR-133a-3p   GO term: negative regulation of epidermal growth factor receptor signaling pathway involved in heart process
AE: *regulates(cardiocyte differentiation), occurs_in(mesenchymal stem cell)

Thank you,
Barbara

GOC:BHF, GOC:BHF_miRNA and GOC:bc

@rachhuntley 
@RLovering

*When available I intend to change the ‘regulates’ relation to ‘positively regulates’ (The relation has been requested by @rachhuntley).

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub ,

You can use the TermGenie template called "involved_in" to create 'epidermal growth factor receptor signaling pathway involved in heart process'. 

Thanks,
Paola

**Comment by BarbaraCzub** [comment]
Thank you, Paola!

I've done as you suggested.

Barbara

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub ,

I will approve this TG request of yours now:

id: GO:1905251
name: epidermal growth factor receptor signaling pathway involved in heart process

However, I'll have to obsolete these ones, as they were requested using the wrong template (involved_in rather than regulation of BP):

id: GO:1905252
name: regulation of epidermal growth factor receptor signaling pathway involved in heart process

id: GO:1905253
name: negative regulation of epidermal growth factor receptor signaling pathway involved in heart process

id: GO:1905254
name: positive regulation of epidermal growth factor receptor signaling pathway involved in heart process

If the term you need is 'regulation of [epidermal growth factor receptor signaling pathway involved in heart process]', you'll need to wait for 'epidermal growth factor receptor signaling pathway involved in heart process' to be committed, and then request regulation terms for it via the regulation TG template.

**Comment by paolaroncaglia** [comment]
Now committed:
id: GO:1905251
name: epidermal growth factor receptor signaling pathway involved in heart process

**Comment by BarbaraCzub** [comment]
Thank you for clarifying this!
