### ISSUE TITLE
Update Reactome xrefs in go.obo

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#12518]
Hi,

Creating a ticket here in github for the go-help email asking for updates to the namespace for Reactome xrefs in go.obo.

http://jira.geneontology.org/browse/GO-1270

Looks like the namespace was changed from, for example, Reactome:REACT_22295 to Reactome:R-SCE-449748.

Thanks,
--Kimberly

**Comment by monicacecilia** [comment]
@ukemi  Have there been any developments on this front? 

The original message from user to GO Help reads: _We use your data go.obo, but have recently found it hard to integrate all data into our results as your reactome ids are of the old format. Would it be possible for you to update the reactome ids to the R-HSA format, please?_

When ready please update the ticket here. I have pointed the person who issued the ticket to this tracker. 

Thank you!

**Comment by ukemi** [comment]
I thought Peter and I had discussed this with Chris and he was going to redo the mappings. 
@cmungall

**Comment by tberardini** [comment]
Would this mapping file do it?

http://www.reactome.org/download/current/reactome_stable_ids.txt

Head of file:

# Reactome stable IDs for release 59
Stable_ID	old_identifier(s)
R-HSA-15869	REACT_1698
R-HSA-37001	REACT_4792
R-HSA-43124	REACT_4500

**Comment by tberardini** [comment]
Follow up from @deustp01 

Hi Tanya, David,

I think you’re pointing to the right file for the mapping but, based on a developers’ conversation that I may have misunderstood yesterday, I’m not sure that we have really found and fixed all of the mis-mappings that we had in earlier versions. We’re certainly getting close. I’ve e-mailed the relevant Reactome people to ask about this and will let you know whether this one is (finally) ready for prime time.

Thanks.

Peter

AND

The person doing the last bit of clean-up says it would be best to wait. As soon as there is a definitive clean mapping file I’ll let you know.

Peter

**Comment by ukemi** [comment]
Thanks @deustp01

**Comment by cmungall** [comment]
We want to remove these from the editors file, unless anyone relies on them. xrefs maintained outside should not go in the editors file.

Is there value to patching them back in as part of release? Or should we just send people to our xrefs file (which in this case would be derived directly from reactome)

**Comment by deustp01** [comment]
No objections or alternative suggestions from here.
Peter

**Comment by ukemi** [comment]
@cmungall  From the help-desk ticket, it looks like at least one group gets these from the go.obo file. Maybe we need them both places as part of a build into go from the xrefs file?

**Comment by ukemi** [comment]
Update on this ticket. The links from AmiGO2 no longer work for xrefs to Reactome, even the ones we know are correct. We need to reconfigure the links so that they resolve correctly.

**Comment by cmungall** [comment]
It would be easy to update the ones in go-edit using the mapping file above.

Can I just check a few things first

## who is in charge of maintaining the mapping?

I assume these are maintained by reactome and were slurped into the edit file years ago, and are thus likely stale. I don't know what our SOP is for merges etc when we have these reactome IDs.

It would seem to make much more sense to get rid of these from the edit file, get the mappings from reactome and inject them into the obo/owl as part of the release

## is there a better strategy?

Are there better ways of connecting the two resources?

Look at GO:0016301. We have every reactome phosphorylation event propagated to every species (828 xrefs). Is this useful? I'm sure it is to some, just like putting all annotions in the obo file would be useful to some. But it's not the best way.

Maybe the better thing to do is to hyperlink in amigo to a reactome query for the relevant GO ID?

Or maybe we could just have xrefs for human?

**Comment by ukemi** [comment]
I think Amelia did the original mapping, but I might be mistaken. I am almost certain they are stale. Peter and I did some by hand as we worked on each of the pathways. Those are correct and are easy to spot because they have the updated identifiers. We only cross-referenced to human. I think that is the way to proceed. As for who maintains the mapping... I'm not sure. It seems liek it should be a collaborative effort.

Is there a better way? I think so. It would be ideal to have reciprocal cross-references from GO causal models to Reactome. We can talk more about this.

**Comment by RLovering** [comment]
I think this is a big task. I have recently run a functional analysis and found that some very specific signaling pathways were enriched due to the presence of ubiquitins in the pathways. These are relevant to many signaling pathways but I am not sure that these should be associated with individual specific pathways.

**Comment by goodb** [comment]
Hi all.  This issue cropped up in another issue (see https://github.com/geneontology/go-ontology/issues/14984#issuecomment-396935515 ).  Here are some updates from the Reactome team.  

Regarding xrefs to multiple species, I believe the advice from @deustp01 is to only maintain the xref to human as the others can be derived as needed.  He said 

> "Now, when human reaction R-HSA-12345 (where 12345 is the guaranteed unique integer string used as an internal ID) is successfully used to infer a mouse counterpart, the inferred mouse reaction gets the identifier R-MMU-12345 (same integer, with a new prefix to indicate the new species). As long as R-HSA-12345 persists in Reactome and the human and mouse genome builds continue to contain the relevant human proteins and their mouse counterparts, R-HSA-12345 will continue to support the inference of R-MMU-12345. However, if R-HSA-12345 becomes obsolete or if the mouse genome build changes such that the mouse proteins needed for inference are no longer present, then R-MMU-12345 will disappear so it’s not a proper stable ID. What is truly persistent in Reactome is the collection of manually curated human data."  

They have provided a new mapping file that could be used to update the xrefs to the current release.  Attaching the human one here.  (Another file with all species is also available.)   
[StId_OldStId_Mapping_Human_Reactions_v65.txt](https://github.com/geneontology/go-ontology/files/2106847/StId_OldStId_Mapping_Human_Reactions_v65.txt)

With a little handholding about the ontology update process, I could make these changes.  Would they go in [reactome2go](https://github.com/geneontology/go-ontology/blob/master/src/ontology/external2go/reactome2go) or/and in [go-edit.obo](https://github.com/geneontology/go-ontology/blob/master/src/ontology/go-edit.obo) ?  As for updates and future responsibility, I'm not sure, but getting caught up now would be a step in the right direction.

**Comment by ukemi** [comment]
Hi @goodb,
It looks like the reactome2go file is derived from the ontology and generated each day. Therefore, updating the xrefs in the ontology should automatically update this file.

**Comment by ukemi** [comment]
http://www.geneontology.org/page/download-mappings

**Comment by goodb** [comment]
Got it. I will work on the go-edit.obo file.

**Comment by ukemi** [comment]
https://github.com/geneontology/go-ontology/pull/15921

**Comment by ukemi** [comment]
I just checked the mapping file and it still hasn't been updated. The header still says:

! Generated on 2018-06-25T09:58Z from the ontology 'go' with data version: 'releases/2017-03-31'

@cmungall  Should this be part of the snapshot pipeline?

**Comment by cmungall** [comment]
@ukemi - yes it should I filed a separate ticket: https://github.com/geneontology/go-site/issues/688

**Comment by goodb** [comment]
Ping @ukemi see https://github.com/geneontology/go-ontology/tree/issue-15921

**Comment by ukemi** [comment]
QC plan for this issue:

- [ ] Examine Reactome and cross check that Reactome entities are mapping correctly to the terms in the branch file.
- [ ] Examine the branch file and be sure that the Reactome xrefs in that file go to the correct Reactome entities
- [ ] Check that no more REACT_ identifiers are in the file.

**Comment by ukemi** [comment]
Missing from GO:
R-HSA-6793661 should crossref GO:0004693, is not in the mapping file.
R-HSA-2023973 should crossref GO:0052841, is in the mapping file REACT_150371; not in the current GO.
R-HSA-1855165 should crossref GO:0052841, is in the mapping file REACT_150184; not in the current GO.
GO:0047988 refers to forward and reverse reactions in reactome: R-HSA-880002 and 880033.
R-HSA-5607745 should crossref GO:0004713,  is in the mapping file REACT_259669; not in the current GO.
R-HSA-1855193 should crossref GO:00052839, is in the mapping file REACT_150415; not in the current GO.
GO:0038143 has Reactome xrefs in the def and as xrefs, but they don't exactly match, there are more in the definition.

**Comment by goodb** [comment]
@ukemi @deustp01 I believe this branch should close the issue https://github.com/geneontology/go-ontology/tree/issue-12518 .  Previous merge problems appear to be gone.  Await your input.

**Comment by ukemi** [comment]
Hmmm. It looks different than other committed branches. We will check this one tomorrow. Let's hope it stays without conflicts.

**Comment by ukemi** [comment]
@deustp01 and I went through the new mapping file today and although the mapping worked correctly, we found many many examples of where the updated GO xrefs are out of date with Reactome. Either the xrefs had been removed (ie the GO identifier no longer corresponds to a Reactome identifier) or Reactome had added xrefs to GO terms that are not in the current GO file. Rather than create a file that is already out of date, we have decided to wait until the next Reactome release and have Reactome generate a 3-column file that reports on the GO:ID, R-HSA:ID, the Reactome label and Reactome version number. We will then use that file to replace all of the REACT_:IDs in Go with the most up-to-date Reactome mappings.

**Comment by ukemi** [comment]
Reactome has created a new file that maps GO terms to Reactome identifiers. These will now serve as the official xrefs. The plan is to have those xrefs incorporated GO as part of the pipeline. @dougli1sqrd  @kltm @cmungall @goodb , we should discuss this next week. Today @deustp01 and I will QC check the mapping file that was provided to be sure things look ok. Maybe we should do a one-off load of this file to get things up to date, but we should certainly automate this with each Reactome release.

**Comment by ukemi** [comment]
Notes on review of the new file:
R-NUL-209144	Human APC is finally phosphorylated by Murine GSK3beta	GO:0004674 : Decision is to ignore the Reactome XREFS that don't have an R-HSA prefix. Decision is that Reactome should filter them out of the file. The file should only contain R-HSA xrefs. Import script should check this and report errors.

Some mappings refer to a large number of GO terms. For example look at mappings to GO:0004674 (421 xrefs). How should we handle these? How will we display them in AmiGO2? Can we somehow make these mappings more specific? Can we automate this based on other data from the reactome reaction participants? Many of the children of GO:0004674 are differentiated by substrate.

In some cases, it looks like we can refine the Reactome annotations to more generic terms like kinase activity (77 xrefs). These might be a great test for automated refinement.

Currently there are only six xrefs to GO:0005515, protein binding. What do we want to do with these?
Peter will remove them, but we need to figure out a way to do this correctly.

Spot-checking through the file, it looks like the mapping worked fine.

**Comment by deustp01** [comment]
We've decided not to make xrefs between GO molecular function terms and Reactome reactions using those terms that have been computationally inferred for model organisms based on manually curated human data.
A user interested in such a model organism who comes to the GO information for a molecular function term and finds a Reactome xref for the human reaction can still go to the Reactome page for the human reaction and see all the model organisms for which we have computationally inferred that the same reaction. So the information is still accessible.

**Comment by ukemi** [comment]
@balhoff and @dougli1sqrd. It makes more sense to append this ticket than to create a new one since this is the same task. The Reactome group has provided us with a new file of Reactome to GO mappings. We need to incorporate those into the pipeline to generate xrefs between GO terms and Reactome identifiers. @deustp01 will give an update on this task at next week's ontology developers' call. We need to have this new load/mapping done well in advance of the Geneva meeting.

It would be nice to generate a QC report for each load:

1. Identify any reactome identifiers that are not of the R-HSA type.
2. Identify any mappings to obsolete GO terms
3. Identify any mappings to secondary GO identifiers

**Comment by balhoff** [comment]
@good here is a plan to make this happen:
- [ ] checkout go-ontology, make issue branch
- [ ] look at use of dosdp-tools in PR for taxon constraints: https://github.com/geneontology/go-ontology/blob/b393dd721541f18d5f13670dc58643c7159ecaf6/src/ontology/Makefile#L278-L285
- [ ] create YAML DOS-DP pattern containing xref template
  - you will probably need guidance on this
  - this will have just one variable: e.g. "reactome"
- [ ] edit reactome mapping file to replace "GO_Term" with "defined_class"
- [ ] add reactome mapping file to GO repo?
  - or can this be downloaded by the makefile?
- [ ] create make target to generate OWL file containing just xref axioms
- [ ] set up go-edit imports to include this file
  - need to edit go-edit as well as catalog file
- [ ] configure makefile to publish this new file
- [ ] delete existing xrefs from go-edit—probably just by using a text editor

**Comment by goodb** [comment]
@balhoff what is a good way to execute the make for testing?

**Comment by balhoff** [comment]
Install Docker on your machine, then, in the `src/ontology` directory, run `./run.sh make <target>`.

**Comment by goodb** [comment]
I'm looking at the file and seeing again the issue raised above ( https://github.com/geneontology/go-ontology/issues/12518#issuecomment-429360446 ) that in many cases Reactome maps many specific reactions to a few much more generic GO terms.  For Reactome, this seems perfectly valid, but does it really make sense to have xrefs from GO terms to all of these more specific reactions?  Apart from making long lists for displays to handle, this seems semantically questionable to me.  A lot of people, including us in the case of RHEA, assume that xref means something close to 'equivalent to'.  Most of the Reactome xrefs we would get from this file would actually mean something closer to 'superclass of' or in SKOS 'broader than'.  Is there any way we could specify the nature of these mappings more precisely?

**Comment by cmungall** [comment]
agreed, 'kinase activity' has always looked a bit silly here.

Let's stick with xrefs for backwards compatibility, we can annotate them with skos (similar to what we do for mondo).

in future, we may just have these show up directly in amigo in a go-cam view for the term (cc @kltm) directly from a biopax2gocam conversion. We'd reuse the reactome URIs?

**Comment by cmungall** [comment]
http://amigo.geneontology.org/amigo/term/GO:0016301

Click on "Mappings"...

**Comment by goodb** [comment]
Could you elaborate on: "annotate them with skos (similar to what we do for mondo)." ?  Do you use OWL2 annotations on the xref axioms?

**Comment by ukemi** [comment]
Peter and I agree too. See https://github.com/geneontology/go-ontology/issues/12518#issuecomment-429360446

**Comment by deustp01** [comment]
Chris said, "agreed, 'kinase activity' has always looked a bit silly here."
PART 1 - cases where the silliness can be fixed.
True. David and I are hoping that the reasoning tools in GO and GO-CAM will be able to look at the Reactome reactions and (almost always) discover from the input and output information there identify a more specific child term. I in turn am happy to commit us to doing the re-annotation in Reactome needed to replace the "kinase" catalyst activity instances. The only practical problem is that even if the re-annotation is done instantly, the changes will not propagate to the file used to update our xrefs until our next quarterly release, so there will at least a three-month period when GO "kinase" has 77 Reactome xrefs.
We can similarly resolve many (but not all) of our 402 serine-threonine kinase activity terms to more specific children.
PART 2 - cases where the silliness may not be fixable. SUMOylation- a single enzyme mediates the SUMOylation of a lot or target proteins and each target, in our view merits its own reaction because the reactions are parts of different pathways / processed.
Aside from the silliness, does the vast number of xrefs break things? (I can imagine workarounds if it does, but they will lose information so I wouldn't want to start there.)

**Comment by cmungall** [comment]
Just to be clear the silliness largely arises from overloading the meaning of "xref", rather from anything reactome is doing.

**Comment by goodb** [comment]
We may be able to provide many of these additional mapping types as well as improved equivalencies automatically.

**Comment by ukemi** [comment]
@deustp01 and I suspect that part of the outcome of this project will be to be able to deepen some of the Reactome mappings. We looked at a few and found this to be the case. I agree, the association of a generic GO term with many specific Reactome reactions is not wrong, but we need to brainstorm about the best way to handle them.

**Comment by ukemi** [comment]
But taking the kinase activity as an example. There will still be many reactions in Reactome that map to say serine-threonine kinase activity because the mapping is exact. What is more specific are the precise reactions that Reactome has represented in broader contexts that include participants. I guess this would be a reactome to GO broader mapping type.

**Comment by ukemi** [comment]
Just as a historical perspective, if I recall correctly this is why function and process were originally separated in GO. The same type of function can be executed in many different types of processes.

**Comment by deustp01** [comment]
Here is a tally of GO MF term usage in Reactome, to show the scope of the overloading problem:
From the table, Reactome has a total of 5427 annotations that use 1438 GO molecular function terms.
792 terms used one time
322	two times
95	three
59	four
36	five
23	six
19	seven
16	eight
7	nine
12	ten
57	more than ten times
Of course, in a formal sense even the single usage cases may not be exactly what GO means by xref.

**Comment by goodb** [comment]
@deustp01 attached is a file with mappings from reactome reactions and pathways to GO functions and processes.  Results from Reactome assertions as well as manual rules like the [protein binding rule](https://github.com/geneontology/pathways2GO/issues/15) discussed elsewhere are included in one column, with the OWL inferences generated by Arachne in another.  
[manual_plus_inferred_mapping_11-5.txt](https://github.com/geneontology/go-ontology/files/2550346/manual_plus_inferred_mapping_11-5.txt)

**Comment by deustp01** [comment]
@goodb  Thanks - only checked a few cases but the inferences so far look good. Will work more systematically and let you know.

**Comment by deustp01** [comment]
Getting the non-ascii characters out of our event names is probably do-able but would take some discussion here to persuade curators that this fix is needed and worth the effort to make it and QA it. (A while ago, we made a quite substantial effort to get all our tools and displays to handle non-ascii characters correctly.)
@goodb do you know the size of the problem - tens, hundreds, thousands of lines in the file?
@ukemi maybe an item to discuss during the Geneva section of the ontology call on Monday?

**Comment by goodb** [comment]
@deustp01 its a small number - less than 10 I think.  (but 1 is enough to break the Make)

**Comment by ukemi** [comment]
If I recall, when we checked before, it was only a few labels. You don't have to do it at source, could you just do it in the file you generate for us? That might be less controversial.

**Comment by deustp01** [comment]
@goodb For a small number w can manually patch the file for now and can probably unilaterally edit the offending event names in our central database - not an elegant durable fix but it will get us going. If you can generate a list of the offending lines in the table, I will come up with alternative names for them.

**Comment by deustp01** [comment]
@goodb This raises an ugly tangential issue - we do NOT guarantee that an event name in Reactome is unique - having two different events with the identical name attribute is rare but it does happen (and even makes sense to us when, for whatever reason, we manually create a human reaction and its exactly parallel model organism counterpart). As long as you're taking the event name only in order to make the xref human readable (and the associated R-HSA string makes it unique), that's no problem, but if you're using it as a unique identifier, we will sooner or later corrupt that.

**Comment by ukemi** [comment]
We should never use the name for anything other than display. The stable identifier should be the R-HSA-blahblahblah.

**Comment by goodb** [comment]
@deustp01 is there any chance you could have the file updated on your site?  The code assumes that that file is true, so anyone that runs the Makefile is going to get the file from there.  (The file isn't committed to this repo, but gathered dynamically from the Reactome server as part of the build.)

**Comment by deustp01** [comment]
@goodb Probably not, because the file is generated from our released data set, I can only safely edit our internal data set, and edits to internal will not propagate to release until the middle of December.

My opinion / wish: could you for now just skip these eight lines? It would be really useful to have a demonstration that this process works for Geneva, even one with eight gaps. (Or not, in which case we have a high-priority hackathon agenda item.)

**Comment by goodb** [comment]
@deustp01 the process works right now, it just deletes the offending characters.  This results in 8 labels on xrefs that might look a little weird (greek chars just missing), but nothing that breaks anything.

**Comment by deustp01** [comment]
Even as-is that looks like a really useful improvement on the xrefs available now, and I will work on a better fix from this end. Thanks

**Comment by cmungall** [comment]
We could look into relaxing the non-ascii requirement for external incoming data. However, it's always been problematic allowing arbitrary characters to be pasted in as there is no guaranteed way to tell intended non-asciis from unintended ones. Unintended ones form the majority, so we end up with lots of hyphens replaced by emdashes hindering matching etc

**Comment by ukemi** [comment]
Finally done. See
https://github.com/geneontology/go-ontology/pull/16597
