### ISSUE TITLE
Regulation of memory

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12512]
CC: @hattrill @vanaukenk 

The following terms were requested on TG for use in annotating the paper in this annotation consistency exercise:

http://wiki.geneontology.org/index.php/Annotation_Conf._Call_2016-06-28#Annotation_Consistency_Exercise

[Term]
id: GO:1905248
name: regulation of memory
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of memory." [GO_REF:0000058, GOC:TermGenie, PMID:25905804]
synonym: "modulation of memory" NARROW []
is_a: GO:0031644 {is_inferred="true"} ! regulation of neurological system process
is_a: GO:0050795 {is_inferred="true"} ! regulation of behavior
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0007613 ! memory
relationship: regulates GO:0007613 {is_inferred="true"} ! memory
created_by: ha
creation_date: 2016-06-09T13:54:38Z

[Term]
id: GO:1905249
name: negative regulation of memory
namespace: biological_process
def: "Any process that stops, prevents or reduces the frequency, rate or extent of memory." [GO_REF:0000058, GOC:TermGenie, PMID:25905804]
synonym: "inhibition of memory" NARROW [GOC:TermGenie]
synonym: "suppression of memory" EXACT []
is_a: GO:0031645 {is_inferred="true"} ! negative regulation of neurological system process
is_a: GO:0048521 {is_inferred="true"} ! negative regulation of behavior
intersection_of: GO:0065007 ! biological regulation
intersection_of: negatively_regulates GO:0007613 ! memory
relationship: negatively_regulates GO:0007613 {is_inferred="true"} ! memory
created_by: ha
creation_date: 2016-06-09T13:54:45Z

[Term]
id: GO:1905250
name: positive regulation of memory
namespace: biological_process
def: "Any process that activates or increases the frequency, rate or extent of memory." [GO_REF:0000058, GOC:TermGenie, PMID:25905804]
synonym: "enhancement of memory" NARROW []
is_a: GO:0031646 {is_inferred="true"} ! positive regulation of neurological system process
is_a: GO:0048520 {is_inferred="true"} ! positive regulation of behavior
intersection_of: GO:0065007 ! biological regulation
intersection_of: positively_regulates GO:0007613 ! memory
relationship: positively_regulates GO:0007613 {is_inferred="true"} ! memory
created_by: ha
creation_date: 2016-06-09T13:54:53Z

Following discussion on the annotation call, we provisionally agreed that terms were needed for memory retention and its negative and positive regulation (with synonyms for memory enhancement and forgetting).  positive and negative regulation of memory may not be needed or at least require further discussion.  

Use cases from other organisms would be useful to this discussion @vanaukenk agreed to provide examples for C.elegans. Some expert input would also be helpful.@dosumis agreed to ask some fly behaviour experts (VFB connections).

**Comment by bmeldal** [comment]
I'm trying to annotate the amyloid beta proteins 40 & 42 (P05067-PRO_0000000092 & P05067-PRO_0000000093) that form the main dimers and plaques driving memory loss in Alzheimer's patients. #13128

Looks like no "regulation of memory"-type terms have actually been committed yet. I'm reluctant to annotate directly to GO:0007611 learning or memory or children.

Ref: PMID:18568035

Any advice would be appreciated. David H directed me to this ticket.

Thanks,
Birgit

**Comment by hattrill** [comment]
Hi Birgit,
I did begin to look at this and then parked it. However, it is a really big area of fly research, so I am still keen to nail down some terms to accurately capture this area of biology.
For the ones I requested via TermGenie, conclusion  the GO editors came to (and I, after a think-a-pow) were that the terms '[positive/negative] regulation of memory' are not really appropriate i.e. what is being regulated? (answer: don't know!)
I think the answer is to be more specific and I think your examples in #13128 seem reasonably detailed. I toyed with the idea that sometimes these processes are active rather than regulatory - but I need to really define these as official activities with the help of an expert, as the processes described in papers are more often than not describing the assay (i.e. the phenotypic outcome).
(e.g. suppression of long term memory rather than negative regulation and forgetting/interference-induced forgetting).
(unfortunately, that's where I put it down)
Perhaps, in some cases, and I think the example I requested terms for were one, the correct approach would be to capture the specific process targeted and capture the memory aspect as in an extension.

**Comment by bmeldal** [comment]
Thanks, Helen.
The amyloid-beta complexes are requests from @BarbaraCzub and she's off to an Alzheimer's conference this month. Barbara, can you have a think about the memory issue as well or pick one of the experts brains when you are away? Then we can revisit the memory annotation. For now I won't add it to the complexes.
Birgit

**Comment by BarbaraCzub** [comment]
Noted 👍

**Comment by BarbaraCzub** [comment]
Hello, here is a summary of my discussions from the Alzheimer's Research UK conference about annotating amyloid beta complexes to the process of 'memory' vs. 'regulation of memory'. So it seems that the choice between these two annotations (assuming we had no background knowledge about amyloid beta peptides and their complexes at all) would be to use a term best represented by the experimental assay being annotated.
For instance, if a research paper described only an experiment, in which a rodent was subject to an intrahippocampal injection with protein complexes of amyloid beta and then its learning and or memory effects were evaluated using behavioural tests, e.g. a water maze, this would generally support a direct annotation to 'memory', as essentially no information about any regulatory mechanisms is revealed in such a behavioural assay. 
Although, personally, having given it some thought, due to the injection, i.e. amyloid beta complexes originating from an external source and being administered only temporarily, I would be more willing to annotate to 'regulation of memory' because I think that, if we are adding something, and then measuring/checking the effect of this addition, we are essentially modulating/interfering with a process that would have been ongoing anyway, irrespective of whether we injected the amyloid beta, or not. If however, the behavioural test was done on a transgenic animal, over-expressing Abeta precursor protein etc., then I would consider annotating directly to 'memory' because (assuming we had no prior knowledge) in this case the transgene could be directly involved in 'memory' or it could be regulating it.
In addition to the behavioural testing, if the experimental paper also described findings demonstrating that the amyloid beta complex regulates maintenance of dendritic spines and/or long-term synaptic potentiation (LTP), this evidence collectively with the behavioural tests would more strongly support annotation to 'regulation of memory' (because the author intent would have been to show that the effect on memory is relayed via regulation of LTP or dendrite structure and/or function).
Irrespective of the experimental assays, because it is well known that amyloid beta complexes have a negative effect on memory (and they are not _required_ for memory processes to occur, but rather negatively modulate them), the consensus seemed to be to annotate using a term 'regulation of memory' rather than directly 'memory'.
I am not sure whether this is helpful (?), I hope so, although I feel this area probably requires further consultations with experts and more specific guidelines to be drawn up.

**Comment by bmeldal** [comment]
Thanks, Barbara.

Let's see what Helen, Kimberly and the editors think :) I'm going to leave it open until we've made a decision.

**Comment by hattrill** [comment]
Hi Barbara,

These are good points with regard to regulation of memory. 

I agree that we could be with more input from experts, this field is tricky to get a handle on as the assays are very different to the usual. 

Over the next couple of days, I'll have a dig around the papers that I looked at bearing in mind your point about LTP, etc regulatory relationship with memory.

**Comment by ukemi** [comment]
With respect to beta-amyloid, is it the natural function to interfere with memory or is it the pathological consequence of the plaque?

**Comment by BarbaraCzub** [comment]
Beta-amyloid oligomers have been shown to affect memory-related processes (and a number of signalling events and other processes in the brain) by binding to cell surface receptors (Reviewed in: "Amyloid-β Receptors: The Good, the Bad, and the Prion Protein." PMID: 26719327 PMCID: PMC4751366 DOI: 10.1074/jbc.R115.702704).

It is an open question whether this process is natural or pathological. The reason why beta-amyloid oligomers become present in the brain in excess in the first place is due to reduced (impaired?) functionality of protein degradation and other homeostasis systems due to aging. And this imbalance in homeostasis processes typically begins already in middle-aged (rather than elderly) individuals, even if the consequences do not get manifested until a decade or so later. Is this natural, or is this pathological? This is a grey area.

The plaques are formed very late in the beta-amyloid 'lifecycle' (when the protein degradation systems are not able to cope at all anymore and the oligomers have turned into non-soluble fibrils) after changes to memory-related processes would have been occurring for years.

**Comment by hattrill** [comment]
I wonder if 'regulation of memory' is too vague as memory has many, many components: acquistion, consolidation, retrieval, short-term, long-term, etc. (that may or may not be mechanistically linked), and most experiments define the aspect of memory that they are testing. 

Perhaps it would be better to place the regulation term at a more specific level e.g. regulation of long-term memory narrows down the regulatory targets. At the moment, the memory branch has no relation to the underlying neurology - I can't help but think that trying to join up mechanism to memory by adding new terms is the way forward. Could you link terms such as LTD/LTP/plasticity to memory e.g. LTP involved in memory (formation)/ regulation of LTP involved in memory (formation)?

**Comment by pgaudet** [comment]
I agree not to create this term. Please reopen if you think we should.
