### ISSUE TITLE
Question: adding new children of GO:0035064 methylated histone binding?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12522]
We are annotating Q9Y468 (LMBL1_HUMAN) from PMID:17540172 and it is binding 4 other methylated histones compared to the 2 existing children. Should I request all specific terms (esp now that TG FF is down)? I'm happy with the generic parent but as these annotation will go onto the GOA files (eventually!) do you or the consumers want that level of specificity? 

Thanks, 
Birgit & Mila

**Comment by bmeldal** [comment]
Note to self: complexes EBI-11790939 & EBI-11792170, ready for release

**Comment by ukemi** [comment]
Hi Birgit,

Putting on my LEGO hat, I think we would only want the specific binding terms if they have separable functional consequences. In LEGO models, all binding annotations will be made in the context of a larger function or process.

-David

**Comment by bmeldal** [comment]
The ones in the current case act as 'sensors' for transcriptional repressors. That is a common function of methylated histones but I don't know if there are other functions.

Sounds like using this parent term might be enough. We could add a sentence: "Methylated histone residues often function as gene silencing markers."?

**Comment by ValWood** [comment]
This is related to one of my Friday  tickets.
I think it makes total sense to describe the MF's of histone modifications as 'sensors' of various types. 
https://github.com/geneontology/go-ontology/issues/12532

So this existing term could be a "methylated histone DNA sensor" instead of "methylated histone binding"
They can have different functional consequences (swi6 binding methylated DNA for mating type switching or heterochromatin formation at  the centromere).

As an aside I have got into the habit of making the F-P connections using the involved in relation and an extension,
so that they look like this on our gene pages:
http://www.pombase.org/spombe/result/SPBC11B10.09#go-molecular_function
otherwise I would need to request 100's  of  new terms a week for all of the F-P links we establish....

but in this instance "methylated DNA sensor" involved in process is more informative.

**Comment by bmeldal** [comment]
Thanks, Val. I was off on Friday and only catching up with terms now!

In my case, it would be 'methylated HISTONE sensor' and possibly adding 'involved in chromatin silencing'. We can't use extensions in the IntAct editor (as it was never built to do GO annotations).

It still needs to be decided whether we need the specific types of methylation as separate terms (e.g. residue and how many methyl groups are added).

**Comment by ValWood** [comment]
I would still think  of it as a "DNA sensor". I think this is what experimentalists would call it because ultimately  the histone is been used to sense a particular region of DNA. For example in this paper:
http://www.ncbi.nlm.nih.gov/pubmed/26687354
the protein which binds to the acetylated histone is called a "DNA sensor"

The methylated histone is just the adaptor between the  protein machinery which is binding to DNA and the specific DNA region.

Different degrees  of methylation  do have different functional consequences

see https://en.wikipedia.org/wiki/Histone_methylation
Different degrees of residue methylation can confer different functions, as exemplified in the methylation of the commonly studied H4K20 residue. Monomethylated H4K20 (H4K20me1) is involved in the compaction of chromatin and therefore transcriptional repression. However, H4K20me2 is vital in the repair of damaged DNA. When dimethylated, the residue provides a platform for the binding of protein 53BP1 involved in the repair of double-stranded DNA breaks. H4K20me3 is observed to be concentrated in heterochromatin and reductions in this trimethylation are observed in cancer progression. Therefore, H4K20me3 serves an additional role in chromatin repression.[7]

This level of detail would be very useful to the chromatin community, so I would do it....

**Comment by bmeldal** [comment]
Ok, so in our case, we have H4K20me1, H4K20me2, Hb1K26me1 and Hb1K26me2, all initiating chromatin compaction and looping and ultimately silencing!

**Comment by ValWood** [comment]
Lets wait to see what David thinks. 

I think there are also existing problems with some of the silencing and heterochromatin part of the ontology. 

Is it actually demonstrated that the complex is involved directly the  looping, or is it just required upstream?
(i.e. if you cannot form heterochromatin, the  subsequent  looping doesn't occur correctly?)
  
Also is the looping actually required for  transcriptional repression? Usually heterochromatin  is transcriptionally silent anyway, so is the looping definitely part of the silencing?  
Or is the connection between the different areas of DNA providing a heterochromatin boundary?

I'd avoid loading too much into connections between the terms unless the mechanism is clear.
The "methylated histone binding" involved in "heterochromatin formation" is fairly well-established
Which paper describes the "looping" activity and links it to the "silencing" process?

**Comment by bmeldal** [comment]
It's all in this paper: PMID:17540172. If you mutate or if you knock down L3MBTL1 you loose histone binding (specific for the above mentioned methylation types) of L3MBTL1 (which has been shown to be past of a complex), loose compaction and/or looping (shown by EM) and you get increased myc expression (in the expression model system).

**Comment by ValWood** [comment]
Yeah that looks fairly direct for both.

**Comment by bmeldal** [comment]
Just to keep the tickets links:
https://github.com/geneontology/go-ontology/issues/12526

**Comment by ukemi** [comment]
Hi Birgit,

We discussed this at an editors' call and have decided not to continue to add the binding to specific modified forms because it is unsustainable. We are coming up with a proposal to present at the GOC meeting in November.

**Comment by bmeldal** [comment]
Thanks, David.
That's fine by me.
I won't be at the GOC meeting so will wait to hear back from it afterwards.
