### ISSUE TITLE
FP link update  GO:0004467 long-chain fatty acid-CoA ligase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12568]
GO:0004467 long-chain fatty acid-CoA ligase activity
part of
 GO:0001676 long-chain fatty acid metabolic process

change to
GO:0035336 long-chain fatty-acyl-CoA metabolic process

note that this term 
GO:0035336 long-chain fatty-acyl-CoA metabolic process
does not have any fatty acid parentage, I don't know if it should?

https://github.com/pombase/curation/issues/936

**Comment by deustp01** [comment]
This is a process-boundary problem. Is the plain fatty acid a part of fatty-acyl-CoA metabolism, perhaps as input to the reaction that forms fatty-acyl-CoA to start the process, or is the process defined to start with fatty-acyl-CoA already in existence, in which case it's a precursor but not a part.

Three standard textbooks (Devlin, Stryer, Marks & Lieberman) deal with the issue by calling the process "fatty acid metabolism" with fatty acid activation via conjugation with CoA as its first step.

**Comment by ukemi** [comment]
Don't you think that the def of GO:0004467 should be changed to Catalysis of the reaction: ATP + a long-chain fatty acid + CoA = AMP + diphosphate + an acyl-CoA; a long-chain fatty acid is a fatty acid with a chain length between C13 and C22.
So, as we define metabolism, GO:0004467 is part of 'GO:0001676 long-chain fatty acid metabolic process' and part of 'GO:0035336 long-chain fatty-acyl-CoA metabolic process' because both participate in the function.

For this:  GO:0035336 long-chain fatty-acyl-CoA metabolic process
does not have any fatty acid parentage, I don't know if it should?

The parentage is strictly determined by the ChEBI ontology for the generic metabolism. If long-chain fatty-acyl-CoA does not have a fatty acid parent, then it won't in GO. If we want to refine things further, then we should really focus on teasing out these metabolic pathways as we have done some of the carbohydrate processes. This is on Peter's and my radar. The problem is the radar has turned out to be very long-ranged!

**Comment by deustp01** [comment]
I'm not really good at navigating and interpreting the ChEBI ontology (when I remember to look at it), but for what it's worth, I can't find an is_a relationship between fatty acid and fatty acyl CoA, only a functional_parent one, fatty acyl-CoA (CHEBI:37554) has functional parent fatty acid (CHEBI:35366).

**Comment by ValWood** [comment]
no hurry for this one for me....it's not a big problem. In fact, you can close if you want to leave it until you are ready. I was just clearing up some mappings, but it can wait, it isn't as if they are badly wrong.

**Comment by ukemi** [comment]
I think I should at least tweak the definition as I suggested above, don't you?

**Comment by ukemi** [comment]
OK. I tweaked the definition to make it all internally consistent.
