### ISSUE TITLE
NTR: Tapasin-ERp57 complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12571]
[This complex is ready for release in the complex portal]

This is a part_of child of GO:0042824 MHC class I peptide loading complex.

Def:
Subunit of the MHC class I peptide loading complex (GO:0042824) (=PLC) involved in the assembly of the heavy-chain-beta2-microglobulin dimers of the MHC class I molecules that fold with eight to ten residue peptides in the endoplasmic reticulum. Required for the inhibition of the reduction of the disulfide bonds of the heavy chains and the assembly and stabilization of the PLC, suggesting it may play a structural role rather than a catalytic one.

PMID:17603487
GOC ref: bhm
DB xref: EBI-9013963
DB xref: EBI-11896237

Also needed:
GO:0042824 MHC class I peptide loading complex
Synonyms:
peptide-loading complex [exact] - in fact, this is the more commonly know terms for this complex (I think!)
PLC [exact]

Is 
GO:0042824 MHC class I peptide loading complex.
capable_of_part_of GO:0002502 peptide antigen assembly with MHC class I protein complex?

Thanks,
Birgit

**Comment by ukemi** [comment]
I did not make PLC an exact synonym because I think it is also used for phospholipase C.

 [Term]
+id: GO:0061779
+name: Tapasin-ERp57 complex
+namespace: cellular_component
+def: "Subunit of the MHC class I peptide loading complex (GO:0042824) (=PLC) involved in the assembly of the heavy-chain-beta2-microglobulin dimers of the MHC class I molecules that fold with eight to ten residue peptides in the endoplasmic reticulum. Required for the inhibition of the reduction of the disulfide bonds of the heavy chains and the assembly and stabilization of the PLC, suggesting it may play a structural rather than a catalytic role." [GOC:bhm, GOC:dph, Intact:EBI-11896237, Intact:EBI-9013963, PMID:17603487]
+is_a: GO:0043234 ! protein complex
+relationship: part_of GO:0042824 ! MHC class I peptide loading complex
+created_by: dph
+creation_date: 2016-08-05T12:12:08Z

**Comment by bmeldal** [comment]
Thank you for the term.

The papers all refer to it as PLC. Could we add it as RELATED synonym to GO:0042824 MHC class I peptide loading complex?
