### ISSUE TITLE
 GO:0031297 replication fork processing - missing parent?

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12570]
I wonder if 
GO:0031297 replication fork processing
Def:
The process in which a DNA replication fork that has stalled (due to DNA damage, DNA secondary structure, bound proteins, dNTP shortage, or other causes) is repaired and replication is restarted.

should have parent
GO:0006281 DNA repair?

At least the def seems like GO:0031297 replication fork processing if always a type of DNA repair. Or the def needs changing.

Any thoughts?
Birgit

**Comment by ukemi** [comment]
I modified the definition to make it clearer.

-def: "The process in which a DNA replication fork that has stalled (due to DNA damage, DNA secondary structure, bound proteins, dNTP shortage, or other causes) is repaired and replication is restarted." [PMID:11459955, PMID:15367656, PMID:17660542]
+def: "The process in which a DNA replication fork that has stalled is repaired and replication is restarted. The stalling may be due to DNA damage, DNA secondary structure, bound proteins, dNTP shortage, or other causes." [PMID:11459955, PMID:15367656, PMID:17660542]

**Comment by bmeldal** [comment]
Doesn't that still sound like repair is a default part of the process? Instead of "repaired" should we call it something like "re-activated"?

Could it have a has_part relationship with DNA repair?

**Comment by mah11** [comment]
> Doesn't that still sound like repair is a default part of the process? Instead of "repaired" should we call it something like "re-activated"?

To me it's clear from the amended wording that the fork is what's repaired in this process, but in case I'm the oddball, we could use a phrasing like:

"The process in which a DNA replication fork that has stalled is restored to a competent state and replication is restarted." (or maybe "working" or "functional" would be better than "competent")

> Could it have a has_part relationship with DNA repair?

No, because not all instances of stalled forks have damaged DNA that needs DNA repair to get the fork moving again. If the fork stalls due to dNTP depletion, it just needs more dNTPs; if stalling is due to bound proteins, it needs the proteins to be removed, etc.

**Comment by bmeldal** [comment]
>"The process in which a DNA replication fork that has stalled is restored to a competent state and replication is restarted." (or maybe "working" or "functional" would be better than "competent")

I prefer that, although, with Midori's explanation, I can see how the amended syntax works. Maybe I'm the oddball!

**Comment by ukemi** [comment]
I like Midori's definition. I have changed it to hers using functional. This way it will not be confused with DNA repair.
