### ISSUE TITLE
NTR: Endosomal membrane tubulation

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12583]
Hello,

I am currently annotating paper PMID:26911690 and have been unable to capture the information about tubule formation from endosomal membranes, as shown in Figure 1C and Movies 1 and 2.

I initially considered using the term 'membrane tubulation' (GO:0097320) with endosome in the annotation extension, but I see from the definition of this GO term that it refers only to the plasma membrane.

Therefore, I would like to request a new term: Endosomal membrane tubulation, which would be a child of GO:0044802 single-organism membrane organization and GO:0010256 endomembrane system organization.

Thanks,
Barbara

DbxREFs: GOC:PARL-UCL, GOC:bc

cc: @RLovering 
cc: @rebeccafoulger 
cc: @Pauldenny

**Comment by paolaroncaglia** [comment]
Note for self: this ticket from Val may be related: 
https://github.com/geneontology/go-ontology/issues/12387

**Comment by ValWood** [comment]
See also
https://github.com/geneontology/go-ontology/issues/12387
I think we need a general term for membrane curvature encompassing  invagination, tubulation, membrane bending etc (this would be useful as there are a set of protein domains which seem to be involved in all of these, for example F-bar, clathrin and epsins.

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub ,

If we create a term for generic membrane tubulation (i.e. not specific for plasma membrane), or edit the existing one, then we can have ‘endosomal membrane tubulation’ as a child. However, we may also need to define tubulation more broadly than as a child of invagination (as @ValWood and I were discussing here https://github.com/geneontology/go-ontology/issues/12387#issuecomment-252883795), because if I get this right in endosomes the membrane protrudes to form outwardly-facing tubules, rather than tubule-shaped invaginations. Along the lines of 
membrane tubulation 
is_a membrane organization
Def: A membrane modification resulting in the formation of a tubular projection. This may face inwardly (as in tubular membrane invaginations) or outwardly (as in endosomal tubules). 
@ValWood , what do you think? As you say, the same protein families may be involved in the broader processes…
A similarly broadly defined ‘membrane tubulation’ could then has_part generic ‘membrane bending’.

**Comment by ValWood** [comment]
That all sounds good to me.
Val

**Comment by paolaroncaglia** [comment]
Thanks @ValWood . I think that Barbara is away today; I'll wait to hear from her before doing the edits for this and for your ticket.

**Comment by Pauldenny** [comment]
Hi Paola @BarbaraCzub is on leave for two weeks - I think she will be back at work October 24th

**Comment by paolaroncaglia** [comment]
Thanks @Pauldenny for letting me know.

**Comment by paolaroncaglia** [comment]
@BarbaraCzub @ValWood 
Wrapping up, for this ticket I will:

- [ ] Edit the existing GO:0097320 ‘membrane tubulation’:
rename it as ‘plasma membrane tubulation’;
redefine it as “A membrane tubulation process occurring in a plasma membrane.”;
replace its current exact synonym ‘plasma membrane tubulation’ with the broad one ‘membrane tubulation’

- [ ] Create the new term ‘membrane tubulation’
is_a membrane organization
Def: A membrane organization process resulting in the formation of a tubular projection. This may face inwardly (as in tubular membrane invaginations) or outwardly (as in endosomal tubules).
GOC:pr

- [ ] Add the following links for existing terms:
membrane invagination is_a membrane tubulation
plasma membrane invagination is_a plasma membrane tubulation

- [ ] Create the new term ‘endosome membrane tubulation’:
is_a ‘membrane tubulation’
is_a endomembrane system organization
Def: A membrane tubulation process occurring in an endosome membrane.
PMID:26911690, GOC:PARL-UCL, GOC:bc
exact synonym: endosomal membrane tubulation

- [ ] Then I will update https://github.com/geneontology/go-ontology/issues/12387 to say that I have addressed point 1 in https://github.com/geneontology/go-ontology/issues/12387#issuecomment-252883795 with edits from this ticket.

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub ,
So the term you need to annotate PMID:26911690 is GO:0097750 'endosome membrane tubulation'.
