### ISSUE TITLE
GO:0008280 cohesin core heterodimer

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12598]
Is this a functional complex?
It only has a single EXP annotation (FlyBAse). If not (I'm pretty sure it isn't), can it be merged into the main complex term? (mitotic cohesin, I think for this one?)

I ask because we are picking up InterPro mappings to it, but we wouldn't make this annotation...

**Comment by hattrill** [comment]
I see three manually assigned annotations to this in QuickGO, 2 UniProt and 1 PomBase. We removed our single one a while back.

**Comment by ValWood** [comment]
PomBase one deleted...

**Comment by paolaroncaglia** [comment]
This is an old term, and there are no PMIDs as dbxrefs. There’s only 1 manual experimental annotation (IDA, UniProt), plus 1 TAS (also UniProt) (plus the PomBase one that Val says has already been removed). Looking at the abstracts of the PMIDs supporting the UniProt annotations, I can’t tell if the cohesin core heterodimer is indeed a functional complex or not. What is a functional complex? I’m looking at the IntAct Complex Portal Rules summarised here 
http://wiki.geneontology.org/index.php/Guidelines_on_%27protein_complex%27_terms#Protein_complexes_in_GO  
The cohesin core heterodimer may fall into the following ‘exception’ category, but I don’t know: “transient interactions [that] are a critical part of the complex assembly (e.g. PDGF receptors only become 'dimeric' when linked by the dimeric ligand forming a tetramer)”.
The term has 2 InterPro mappings, IPR029683 and IPR029685: 
Structural maintenance of chromosomes protein 1A, metazoan (IPR029683)
Structural maintenance of chromosomes protein 3 (IPR029685)
Both InterPro entries include this bit:

“Besides sister chromatid cohesion function, SMC1A-SMC3 heterodimer can also found in the RC-1 complex, a mammalian protein complex that promotes repair of DNA gaps and deletions through recombination.”

Which makes me think - the cohesin core heterodimer, *if* we keep it, should not be necessarily part_of the cohesin complex, but rather
cohesin complex has_part cohesin core heterodimer

I’ll ask @bmeldal. If she agrees that GO:0008280 cohesin core heterodimer does *not* describe a functional complex, I’ll merge it into its parent, and I’ll ask InterPro to update their mapping to GO:0008278 cohesin complex. 
Otherwise (or if we can’t tell for sure), I’ll leave GO:0008280 cohesin core heterodimer as is, but I’ll edit the definition to make it less ambiguous (from current “The core heterodimer of a cohesin complex; a structure required for sister chromatid cohesion in eukaryotes.” to revised “The core heterodimer of a cohesin complex.”).

**Comment by ValWood** [comment]
More info:

The introduction to the paper I am reading now:
The cohesin complex is a central player in chromosome biology1-5. Defects in cohesin and its regulators are responsible for chromosome missegregation in human cancers and are the cause for Cornelia de Lange syndrome, a severe developmental disorder6,7. Despite notable advances8-10, our molecular understanding of cohesin function remains vague. The cohesin complex consists of a dimer of structural maintenance of chromosomes subunits, Psm1Smc1 and Psm3Smc3, long coiled coil proteins that interact at their hinge as well as their ABC-type ATPase head domains to form large proteinaceous rings11,12. The head interaction is stabilized by the kleisin subunit Rad21Scc1. Several additional subunits associate with this ring assembly, including the essential Psc3Scc3 subunit, whose function remains poorly understood12-16.

The function of cohesin is to encircle DNA,
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0061776

The complex has  other essential subunits (Rad21 , Kleisin, and the non SMC subunit psc3). I have not seen any reconstitution experiments which demonstrate any cohesin activity without all of these subunits present, and I'm not aware of any function of the dimer (although it can be isolated, presumably because it is more stable than the complete complex?)

**Comment by bmeldal** [comment]
According to Val's post above the core dimer is not a functional complex, just a sub-structure of the unit. And looking at the structure of the children, it really doesn't make sense to have the core heterodimer sitting there all 'lost' either. If anything, like Paola said, it should have has_part cohesion complex but that won't propagate to the children either.

I think there's a typo in one of the children:

ID 	GO:0034991
Name 	nuclear meiotic cohesin complex
Ontology 	Cellular Component
Definition 	A cohesin complex that mediates sister chromatid cohesion in the nucleus during meiosis; has a subunit composition distinct from that of the *meiotic* cohesin complex.
Comment 	Note that this term should be used to annotate gene products found in cohesin complexes in organisms that undergo closed *mitosis* (i. e. where the nuclear envelope does not break down, as in fungi). For organisms in which the nuclear envelope breaks down during mitosis, the parent should be used.

I think '...distinct from that of the *meiotic* cohesin complex' in the Def should say 'mitosis'?
Should 'mitosis' in the Note say 'meiosis'? I know nothing about closed mitosis or meiosis, @ValWood?

Birgit

**Comment by ValWood** [comment]
That looks like a typo.

I  mentioned at the last GO meeting that we should consider getting rid of nuclear an none nuclear versions of the same complex...they are an annotation nightmare for consistency.
I would vote to merge them all, and if  a particular annotation is  required because a complex is sometimes nuclear and sometimes cytoplasmic use an extension(occurs_in?) nucleus/cytoplasm  to capture this ....

**Comment by hattrill** [comment]
Second the merging of nuclear and non-nuclear flavours of complex. It is inline with the policy of not making every variant of a complex in GO.

**Comment by bmeldal** [comment]
Forgot this other bug:
GO:0000798 nuclear cohesin complex
capable_of GO:0007062 sister chromatid cohesion

I think that should be capable_of_part_of as it's a CC-BP link.

NB: 
GO:0008278 cohesin complex
capable_of_part_of GO:0007062 sister chromatid cohesion
so deleting the spurious link on the child term should propagate the correct parental link.

**Comment by paolaroncaglia** [comment]
Hi @ValWood, @hattrill and @bmeldal

Thank you all for your feedback. In summary, there are several issues/action items here:

1) cohesin core heterodimer vs cohesin complex
Sound like the former is not a functional complex. The only experimental annotation is by UniProt. As this is a merge and we have established that the term that will become secondary is not ‘real’, moving the annotation to its parent will not cause loss of information. So I will
- [ ] ask InterPro to update their mapping to GO:0008278 cohesin complex
- [ ] merge GO:0008280 cohesin core heterodimer into its parent GO:0008278 cohesin complex. 

2) typos in GO:0034991 nuclear meiotic cohesin complex:
- [ ] I will replace ‘meiotic’ with ‘mitotic’ in the def, and remove the comment.

3) nuclear vs. non-nuclear versions of the same complex
Val: “I mentioned at the last GO meeting that we should consider getting rid of nuclear an none nuclear versions of the exact same complex...they are an annotation nightmare for consistency.
I would vote to merge them all, and if a particular annotation is required because a complex is sometimes nuclear and sometimes cytoplasmic use an extension(occurs_in?) nucleus/cytoplasm to capture this .... (was that an action item?)”
Helen: “Second the merging of nuclear and non-nuclear flavours of complex. It is inline with the policy of not making every variant of a complex in GO.”
Personally, I agree that the distinction is out of scope for the *ontology* and should be captured via AEs. However this needs a plan for the groups that don’t use AEs. Noctua may be the answer. However, I couldn’t find mention of this particular plan, or action items, among the minutes of the Geneva meeting (https://docs.google.com/document/d/12CDf4s8YsylPMNHM3UuPis9NyVQ9WFpBpNYTFYAH7kc/edit#heading=h.e45uvzyvuaj0). I won’t be at the next GO meeting in November, so can’t bring this up myself. Val, would you like to add to the agenda? Under one of these: 
http://wiki.geneontology.org/index.php/2016_Los_Angeles_GOC_Meeting_Agenda#Protein_Complexes
http://wiki.geneontology.org/index.php/2016_Los_Angeles_GOC_Meeting_Agenda#Annotation_Issues_-_Conventional_Annotations

4) capable_of vs capable_of_part_of: 
@bmeldal wrote
“Forgot this other bug:
GO:0000798 nuclear cohesin complex
capable_of GO:0007062 sister chromatid cohesion
I think that should be capable_of_part_of as it's a CC-BP link.
NB: 
GO:0008278 cohesin complex
capable_of_part_of GO:0007062 sister chromatid cohesion
so deleting the spurious link on the child term should propagate the correct parental link.”
Actually, I checked recently, and David OS reminded me that “if a structure is capable of carrying out a *whole* BP or MF, then capable_of applies. If it’s only capable of carrying out a *part*, then capable_of_part_of applies. (The relations are not GO specific: In VFB we use capable_of an capable_of_part_of to record the functions of neurons.)”. ‘nuclear cohesin complex’ (regardless of discussion of nuclear vs non-nuclear) is defined as “A cohesin complex required for cohesion between sister chromatids that remain in the nucleus.”. So if it is capable of carrying out the whole process of sister chromatid cohesion, then the link is right.
- [ ] If this is not the case, please let me know and I’ll fix. 
- [ ] Similarly for GO:0008278 cohesin complex (“A protein complex that is *required* for sister chromatid cohesion in eukaryotes…”), sounds like this should be capable_of, so I should correct. Please confirm.

**Comment by paolaroncaglia** [comment]
@asangrador @almitchell @happy-lorna @ndrawlings @EBI-Hsinyu
GO:0008280 cohesin core heterodimer currently has 2 InterPro mappings, to IPR029683 and IPR029685.
We’re going to merge GO:0008280 into its parent GO:0008278 cohesin complex. Could you please update the InterPro mappings accordingly?
Many thanks.

**Comment by happy-lorna** [comment]
InterPro is currently frozen, and so we can't make the changes just now, but will do as soon as we are able to edit again. The corrected mappings will be visible in the following release (v61).

**Comment by paolaroncaglia** [comment]
Thanks @happy-lorna ! I'll mark this task as done on my part then.

**Comment by ValWood** [comment]
I will raise this in the protein complex discussion
val

**Comment by paolaroncaglia** [comment]
Thanks @ValWood . If any action item for editors comes up from discussing at the GO meeting, as long as it's minuted, we editors will pick it up post-meeting.

**Comment by bmeldal** [comment]
I just had a quick look at the Agenda for LA (IntAct are NOT attending). The AIs listed are from Washington mtg, not Geneva (but the link to the minutes is to Geneva). This needs changing. Who do I email (want to take it off this tracker!)?

**Comment by paolaroncaglia** [comment]
Hi @bmeldal ,
You should have permission to edit the GO wiki yourself (if not, email me). Paul Thomas is hosting the meeting, so you might email him directly, or perhaps the go-managers mailing list if you need to reach more people. Hope this helps.

**Comment by paolaroncaglia** [comment]
Hi @bmeldal ,
Could you please take a look at my questions at point 4) in https://github.com/geneontology/go-ontology/issues/12598#issuecomment-256027986, so I can go ahead and edit/close as necessary. Many thanks!

**Comment by paolaroncaglia** [comment]
Setting to 'pending' while I wait to hear from @bmeldal .

**Comment by bmeldal** [comment]
Sorry, @paolaroncaglia we were on retreat last week and I'm still catching up! Their internet was rather flaky so I didn't get to do much 'work-work' on the side.

Sounds like the relationship should be capable_of in that case. I guess I put in a few wrong relationships over time but they are too loose rather than too tight :)

**Comment by ValWood** [comment]
The original suggestion was  whether we should remove these  sub-complexes.
Do we think we should do this.
I did put this on the meeting agenda, but it was removed.... I still think we should have the discussion

re: 
i) assembly intermediates
ii) instatiating nuclear and cytoplasmic versions of the identical complex.

Maybe this could be up for discussion on a future annotation call?

**Comment by bmeldal** [comment]
Val,

I thought we agreed above that the dimeric 'core complexes' are assembly intermediates and therefore don't belong into GO (they should be in Reactome). But they could be extended to include all subunits or replaced.

I'll stay out of the cytoplasmic vs nuclear debate, that doesn't affect the CP as the components are identical.

Birgit

**Comment by ValWood** [comment]
OK, so:
 - [ ]  obsolete cohesin core heterodimer ?
 - [ ]  discuss  merging nuclear and cytoplasmic versions of the identical complex on a future call  ?

**Comment by bmeldal** [comment]
Yes, I think so.

**Comment by hattrill** [comment]
Hi Val,

Perhaps we could add another example like this to the discussion:
GO:0000445 THO complex part of transcription export complex
GO:0000446 	nucleoplasmic THO complex

THO is a complex in its own right and is a "core" of the TREX (transcription export) complex, so is slightly different to the cohesin heterodimer instance.

GO:0000347 THO complex
                     - GO:0000446 	nucleoplasmic THO complex
                      -GO:0000445 THO complex part of transcription export complex

GO:0000445 THO complex part of transcription export complex - part of - GO:0000346 transcription export complex

**Comment by paolaroncaglia** [comment]
Hi @ValWood, @bmeldal and @hattrill,

The former term GO:0008280 cohesin core heterodimer has already been merged into GO:0008278 cohesin complex, see https://github.com/geneontology/go-ontology/issues/12598#issuecomment-256027986. So, I ticked the first box in Val’s last comment.

As for “discuss merging nuclear and cytoplasmic versions of the identical complex on a future call”, I opened a new ticket (https://github.com/geneontology/go-ontology/issues/12833), and assigned it to David Hill and Kimberly so they can arrange bringing it up at an annotation call. Please add any further comment there. With that, I ticked the second box in Val’s last comment too, and am closing this ticket.
