### ISSUE TITLE
smn protein complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12595]
Do some relationships need to be added between some of these?
 
![smn](https://cloud.githubusercontent.com/assets/7359272/17835937/a7ded62a-6779-11e6-8078-240c8742018c.jpg)

**Comment by ValWood** [comment]
SMN core complex, survival motor neuron complex
Alternate IDs
None
Definition
A protein complex that contains the survival motor neuron (SMN) protein and at least eight additional integral components, including the Gemin2-8 and Unrip proteins; the complex is found in the cytoplasm and in nuclear Gems, and is involved in spliceosomal snRNP assembly in the cytoplasm and in pre-mRNA splicing in the nucleus. Source: PMID:17023415, PMID:16434402
Comment
Note that a larger complex containing Sm proteins and other subunits is also sometimes referred to as the 'SMN complex'. The larger complex is represented by 'SMN-Sm protein complex ; GO:0034719'.


So, if the 'core complex' is  SMN complex, do we need SMN-Gemin2 complex (is this a functional complex, or an assembly intermediate?)

**Comment by paolaroncaglia** [comment]
A bit of archaeology:
SMN complex was added back in 2007 https://github.com/geneontology/go-ontology/issues/3759;
SMN-Sm protein complex was added back in 2008 along with SMN-Gemin2 complex, SmD-containing SMN-Sm protein complex and Lsm-containing SMN-Sm protein complex https://github.com/geneontology/go-ontology/issues/5297;
all were created by @mah11, not sure if she also added the definition comments;
asking @bmeldal about functional complex vs. assembly intermediate.

**Comment by bmeldal** [comment]
Yes, I agree, the separate 'Gemin' complexes might only be pre-assembly complexes. There's a third one: GO:0034717 Gemin6-Gemin7-unrip complex (Def: A protein complex that contains Gemin6, Gemin7, and unrip (STRAP), and can bind to snRNAs; may play a role in snRNP assembly.)
None of these have annotations or has_part links to the SMN complex.

The 2 children of GO:0034719 SMN-Sm protein complex are defined by the set of potential Sm proteins. The Defs don't specify a difference in function, and the list of proteins is not exclusive, B/B', D3, E, F, and G appear in both Defs:

ID 	GO:0034730
Name 	SmD-containing SMN-Sm protein complex
Ontology 	Cellular Component
Definition 	An SMN-Sm protein complex formed by the association of the methylated Sm proteins B/B', D1, D2, D3, E, F, and G with the SMN complex. 

ID 	GO:0034731
Name 	Lsm-containing SMN-Sm protein complex
Ontology 	Cellular Component
Definition 	An SMN-Sm protein complex formed by the association of the methylated Sm proteins B/B', D3, E, F, and G, and Lsm10 and Lsm11, with the SMN complex. This complex forms Sm cores on U7 snRNA.
They also have no annotations.
It it debatable if these two children add any information! (Well, the second one says it binds U7snRNAs...)

Birgit

**Comment by paolaroncaglia** [comment]
Hi ValWood and @bmeldal

Thanks Birgit for your useful feedback. Summing up:

- I added the link ‘SMN-Sm protein complex’ has_part ‘SMN complex’ (note that, as far as I remember, you won’t be able to see the has_part link in QuickGO);

- The evidence that some of the SMN-related complexes might simply be pre-assembly complexes, rather than functional entities, is not conclusive (though it is a reasonable suspicion). Therefore I’d rather not obsolete them, nor create has_part links between e.g. ‘SMN-Sm protein complex’ and ‘SMN-Gemin2 complex’ (in fact, the latter has a definition gloss “*may* form the stable core of the larger SMN complex.”). 

- As for the children of GO:0034719 SMN-Sm protein complex, ‘SmD-containing SMN-Sm protein complex’ indeed has 2 manual experimental annotations. I lean towards leaving these terms as are and not obsolete them. I do agree that their usefulness may be limited, and that we may prefer not to add *new* terms solely based on their composition.

Closing this ticket now. If you find conclusive evidence in support of any further changes, please open a new ticket.

Thanks!

**Comment by bmeldal** [comment]
Thanks, Paola.
You are right, has_part does not show in the graph, it's only in the 'neighbourhood' tab in AMIGO2 (something I only recently learned!).
Birgit

**Comment by ValWood** [comment]
Looks good,

Thanks, it turned out I didn't have all the subunits so I couldn't use this anyway.
