### ISSUE TITLE
Question: no link btw TF nucleic acid binding and DNA binding

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12593]
Hi,

I'm sure there's a good reason for it but I can't find it:
Why is there no link between
GO:0001071 nucleic acid binding transcription factor activity (or any of it's children, as far as I checked those relevant for my term)
and 
GO:0003677 DNA binding (or any children of this class)?

Birgit

**Comment by mah11** [comment]
GO:0001071 encompasses GO:0001070 (RNA binding transcription factor activity) as well as DNA-binding txn factors.

GO:0001071 does have the link has_part GO:0003676 ! nucleic acid binding

**Comment by bmeldal** [comment]
But GO:0000981 RNA polymerase II transcription factor activity, sequence-specific DNA binding has no link to DNA binding either. At least not visible in QuickGO or AMIGO2.

**Comment by mah11** [comment]
This link exists: GO:0000981 has_part GO:0000977 ! RNA polymerase II regulatory region sequence-specific DNA binding

The graphical views in AmiGO and QuickGO don't include has_part; AmiGO shows it in the "neighborhood" tab (which I find confusing generally ...).

**Comment by RLovering** [comment]
the reason there is no link is because of the regulation terms, if there was a link then if you say a protein regulates RNA polymerase II transcription factor activity, sequence-specific DNA binding then you are implying that it regulates the binding rather than the activity, and the protein is not necessarily regulating the binding to DNA, it  may be regulating protein binding.

However, I have to say that I think GO:0001071 nucleic acid binding transcription factor activity is a better term than  RNA polymerase II transcription factor activity, sequence-specific DNA binding, which I think sounds misleading and you make you think that the term relates more to the DNA binding than to the TF activity. I would prefer this term to be written like the grandparent:  sequence-specific DNA binding RNA polymerase II transcription factor activity.

**Comment by RLovering** [comment]
sorry when I say no link I mean no is_a or Part_of link, it obviously does have the has_part relation

**Comment by krchristie** [comment]
Hi Ruth,

I wanted to comment on what you said earlier, specifically this:

"the reason there is no link is because of the regulation terms, if there was a link then if you say a protein regulates RNA polymerase II transcription factor activity, sequence-specific DNA binding then you are implying that it regulates the binding rather than the activity, and the protein is not necessarily regulating the binding to DNA, it may be regulating protein binding."

This is not the reason that terms like "nucleic acid binding transcription factor activity" (GO:0001071) do not have is_a links to nucleic acid binding MF terms. I also don't think that it is true to say that having this link would automatically imply that the regulation was via regulation of the DNA binding aspect of the function.

The reason is because the GOC decided (at an Annotation Camp in Geneva) that when binding is an integral part of the activity of another MF term that it MUST be represented with a has_part link. In practice, this turns out to have some unfortunate consequences because you can't propagate up the has_part relationship since it goes in the opposite direction and the has_part relationships don't get shown in many tools.

-Karen

**Comment by bmeldal** [comment]
Thanks, everyone. You answered my question and I shall try and remember it! 

In practice, one has to annotate to the binding term separately as has_part doesn't propagate.

I'm closing the ticket.
