### ISSUE TITLE
NTR: mitotic cohesin loading

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12607]
Could we get mitotic versions of this one?
GO:0071921 cohesin loading

a) so it gets mitotic chromosme segregtion parentage
b) I don't know if meiotic cohesin is loaded differently, all of these experiments are using mitotic cohesin 

-I hope to model this at Noctua meeting
(No suitable TG template)

https://github.com/pombase/fypo/issues/2781

**Comment by ValWood** [comment]
cohesin unloading
exact DNA exit from the cohesin ring

Question, should cohesin loading/unloading be a  "positive/negative regulation of DNA binding"?

**Comment by ValWood** [comment]
GO:0061776 DNA ring activity 
narrow synonym? "mitotic cohesin ring"
narrow synonym? "meiotic cohesin ring"

**Comment by ukemi** [comment]
name: cohesin unloading
 namespace: biological_process
 def: "Negative regulation of sister chromatid cohesion by the topological unlinking of a cohesin ring to chromatin." [GOC:dph, GOC:vw, PMID:26687354]
+synonym: "DNA exit from the cohesin ring" EXACT [GOC:dph, GOC:vw]
 is_a: GO:0045875 ! negative regulation of sister chromatid cohesion
 created_by: dph
 creation_date: 2016-07-13T12:40:25Z
@@ -403484,6 +403486,18 @@
 creation_date: 2016-08-05T12:12:08Z
 
 [Term]
+id: GO:0061780
+name: mitotic cohesin loading
+namespace: biological_process
+def: "The protein localization to chromatin by which a cohesin ring complex is topologically linked to chromatin as part of the mitotic cell cycle." [GOC:dph, GOC:vw]
+is_a: GO:0071921 ! cohesin loading
+intersection_of: GO:0071921 ! cohesin loading
+intersection_of: part_of GO:0000278 ! mitotic cell cycle
+relationship: part_of GO:0034087 ! establishment of mitotic sister chromatid cohesion
+created_by: dph
+creation_date: 2016-08-23T13:00:34Z


I don't think we can add the last synonyms because they are things, not activities.

**Comment by mah11** [comment]
Hi David,

Could we also have the equivalent for the unloading term (again, for FYPO logical defs as well as annotations)?

existing:
[Term]
id: GO:0061774
name: cohesin unloading
namespace: biological_process
def: "Negative regulation of sister chromatid cohesion by the topological unlinking of a cohesin ring to chromatin." [GOC:dph, GOC:vw, PMID:26687354]
synonym: "DNA exit from the cohesin ring" EXACT [GOC:dph, GOC:vw]
is_a: GO:0045875 ! negative regulation of sister chromatid cohesion

new:
id: GO:new
name: mitotic cohesin unloading
namespace: biological_process
def: "Negative regulation of sister chromatid cohesion by the topological unlinking of a cohesin ring to chromatin as part of the mitotic cell cycle." [GOC:dph, GOC:vw]
is_a: GO:0061774 ! cohesin unloading
intersection_of: GO:0061774 ! cohesin unloading
intersection_of: part_of GO:0000278 ! mitotic cell cycle

**Comment by ukemi** [comment]
+id: GO:0061781
+name: mitotic cohesin unloading
+namespace: biological_process
+def: "Negative regulation of sister chromatid cohesion by the topological unlinking of a cohesin ring to chromatin as part of the mitotic cell cycle." [GOC:dph, GOC:mah, GOC:vw]
+is_a: GO:0061774 ! cohesin unloading
+intersection_of: GO:0061774 ! cohesin unloading
+intersection_of: part_of GO:0000278 ! mitotic cell cycle
+created_by: dph
+creation_date: 2016-08-24T09:43:07Z

**Comment by mah11** [comment]
Thank you!
