### ISSUE TITLE
NTR: spore-bearing structure development

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12605]
Fungal terms currently under "spore-bearing organ development" will be moved under this new term "spore-bearing structure development" which is is technically more accurate for fungi. The synonym is "sporophore." The scientific term "sporophore" generically refers to the spore-bearing structures of any fungal species...conidiophore, basidiocarp, ascocarp, sporangiophore, cleistothecium, perithecium, zygosporangium, etc. "Sporangium" is used for spore-bearing structure (spore sac, spore case) in both plants and fungi.

Are there guidelines for when to use "formation" versus "development?" I could see also this term as "spore-bearing structure formation." There are both formats in the lineage.

GO:0048856 anatomical structure development
GO:0048646 anatomical structure formation involved in morphogenesis

For conidia and conidiophores, the choice of formation vs. development affects the term lineage. The coniophore is composed of several different cell types, including metulae and phialides and ultimately conidia. I don't see why metula and phialide are not "formation" terms or "conidium development" is not a distinct term. Existing terms:

-conidiophore development (structure made of many cells of different cell-types)
-- metula development (a cell-type that forms part of a conidiophore)
---phialide development (a cell-type that forms part of a conidiophore)
---conidiophore stalk development (a cell-type that forms part of a conidiophore)
---conidium formation (a cell-type produced by a conidiophore)

My thought is the term development requires the structure or cell-type to at least exist in some form. An impact on development might be the failure to reach its fully mature state (spore cell walls are defective or a cell-type is missing). Examples:

conidium formation...the ability to generate conidia (existing term)
conidium development...the ability to generate a fully mature, properly assembled, viable conidium. (not a current term but perhaps should be).

I am sifting through fungal terms and one issue is that "development" is used interchangeably for actual developmental processes and in place of "formation/generation/production" and this brings in more terms that cause issues in definitions. "Differentiation" is a parent of "cell development," but the specific issues will have their own tickets.

**Comment by tberardini** [comment]
@paolaroncaglia, going to punt this to you as part of the spore-bearing organ clean-up.#12578

**Comment by tberardini** [comment]
@dianeoinglis  - can you create 'spore-bearing structure' now in FAO?

**Comment by paolaroncaglia** [comment]
Note for self - see http://wiki.geneontology.org/index.php/Ontology_meeting_2016-08-25#FAO_update

**Comment by dianeoinglis** [comment]
Hi Tanya, Has this term been created to use a GOID as xref?

https://github.com/obophenotype/fungal-anatomy-ontology/issues/2

**Comment by paolaroncaglia** [comment]
Setting to pending while we wait for @dianeoinglis to create 'spore-bearing structure' in FAO.

**Comment by dianeoinglis** [comment]
A term with the synonym "spore-bearing organ" already exists but needs to modified to match the GO term change. The GO term should probably get the synonym "sporophore" which is the primary term name for FAO:0000010. I am having an uber-admin password issue with installation of JavaSE 6 that seems to be required before OBO-edit can be installed. I 

FAO:0000010
name: sporophore
def: "A structure directly within which spores are contained or from which spores are formed." [FAO:curators]
xref: GO:0075259
synonym: "spore-bearing organ" RELATED [] ADD:-synonym: "spore-bearing structure" RELATED []
is_a: FAO:0000001 ! fungal structure

**Comment by dianeoinglis** [comment]
For each fungal development term, a "formation" term should also be created. The development term refers to the formation of a normal, fully mature structure and requires the presence of the structure in some form. The formation term is for the ability to produce the structure at all.. 

"spore-bearing structure formation"
def: The  process of generating a spore-bearing organ. A spore-bearing organ is an anatomical structure that produces new spores.

**Comment by paolaroncaglia** [comment]
Note for self: also see http://wiki.geneontology.org/index.php/Ontology_meeting_2016-09-22#FAO_update and https://github.com/obophenotype/cell-ontology/issues/447

**Comment by dianeoinglis** [comment]
Hi @paolaroncaglia 
Note, this term already exists as a synonym to FAO:0000010 'sporophore'
See https://github.com/obophenotype/fungal-anatomy-ontology/issues/11
The FAO.obo has not yet been updated but all new terms listed in the FAO issue tracker are being assigned the next available ID and the FAO will modified in the near future after I complete the addition of more modifications and terms. Thanks!

**Comment by paolaroncaglia** [comment]
Hi @dianeoinglis,
Wrapping up this ticket. I will:

- [ ] rename ”spore-bearing organ development" as “spore-bearing structure development”; revise its def to replace ‘organ’ with ‘structure’; add exact synonym "sporophore development”, and broad synonym “sporangium development”; give it the logical definition is_a anatomical structure development, results_in_development_of FAO:0000010 sporophore (it doesn’t matter if FAO:0000010 will be renamed “spore-bearing structure”)

- [ ] add the new term ”spore-bearing structure formation"
is_a developmental process
part_of spore-bearing structure development [according to the guidelines on development (and formation) terms here http://geneontology.org/page/development]
def: The process of generating a spore-bearing structure. A spore-bearing structure is an anatomical structure that produces new spores.
dbxref: GOC:di
exact synonym: sporophore formation
broad synonym: sporangium formation

Please comment here if you have any concern with the above. Otherwise, I will proceed after the holidays.
If you require additional, more specific ‘formation’ or ‘development’ terms for fungal structures, please open a new ticket, and include PubMed references etc. as outlined in https://github.com/geneontology/go-ontology/blob/master/CONTRIBUTING.md

Many thanks!
