### ISSUE TITLE
GO:0070676 intralumenal vesicle formation is_a GO:0007032 endosome organization

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#12603]
Hello,

During team discussions this morning we noticed that 'GO:0070676 intralumenal vesicle formation' and 'GO:0007032 endosome organization' are not related in GO.

'GO:0070676 intralumenal vesicle formation' is defined as 'The evagination of the endosome membrane, resulting in the formation of a vesicle.'

Based on this definition, 'GO:0070676 intralumenal vesicle formation' is involved in 'GO:0007032 endosome organization', therefore, the two terms should be linked in the ontology, using the 'is_a' relationship.

Could you please update GO to reflect this?

Thank you,
Barbara

@RLovering 
@Pauldenny

**Comment by tberardini** [comment]
@dosumis : handing to you as you just recently were working on vesicles, etc.  If you agree, reassign to me and  I'll make the edit.

**Comment by Pauldenny** [comment]
good review Endosome maturation from 2011: PMC3181477 
I think this says that GO:0005770 late endosome is broad-ish synonym for GO:0005771 multivesicular body (MVB). Also, ILV are the vesicles found inside LE - an LE at appropriate maturation stage = MVB
![image](https://cloud.githubusercontent.com/assets/12345463/17881387/d8dbe630-68fc-11e6-8e04-30205fec7070.png)

"...late endosomes (LEs) in mammalian cells... are also known as multivesicular bodies, because—although heterogeneous and variable in size and composition—most LEs have a multivesicular morphology, that is, they contain intralumenal vesicles (ILVs). "

**Comment by dosumis** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/112839/17941160/018431fe-6a2a-11e6-827c-2a0e6cf94020.png)
