### ISSUE TITLE
ntr: correction of merotelic kinetochore attachment, meiosis I

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12616]
def
The cell cycle process that corrects the anomalous association of a single chromatid kinetochore with mitotic spindle microtubules emanating from both spindle poles at meiosis I, and would, if uncorrected result in the separation of sister chromatids at meiosis I

Part_of
GO:0051316
attachment of spindle microtubules to kinetochore involved in meiotic chromosome segregation

PMID:21920317
Repositioning of Aurora B Promoted
by Chiasmata Ensures Sister Chromatid Mono-Orientation in Meiosis I

"We conclude that merotely of fused kinetochores is initially similarly prevalent in the attachment of bivalents and univalents but that efficient
correction only happens in bivalents and depends on Ark1 activity (Figure 4C)."

**Comment by tberardini** [comment]
The 'mitotic' version of this term has the following relationships:

is_a: GO:0050789 ! regulation of biological process
is_a: GO:0009987 ! cellular process
relationship: part_of GO:0000070 ! mitotic sister chromatid segregation
relationship: regulates GO:0051315 ! attachment of mitotic spindle microtubules to kinetochore

Do you wish to have similar relationships recapitulated for this new term?  That is

is_a: GO:0050789 ! regulation of biological process
is_a: GO:0009987 ! cellular process
relationship: part_of GO:0045144 ! meiotic sister chromatid segregation
relationship: regulates GO:0051316 ! attachment of spindle microtubules to kinetochore involved in meiotic chromosome segregation

Note the 'regulates' relationship to GO:0051316, instead of the 'part_of' that you originally suggested.

**Comment by ValWood** [comment]
Hi Tanya,

That sounds right, and regulation is more correct.

Val

**Comment by dosumis** [comment]
I've just removed the regulates on the mitotic version, see #12393

**Comment by ValWood** [comment]
Ah OK, so just part_of the parent congression instead?

**Comment by dosumis** [comment]
Yep. That would be consistent.

**Comment by tberardini** [comment]
Checking again.

EXISTING TERM

[Term]
id: GO:0098783
name: correction of merotelic kinetochore attachment, mitotic
namespace: biological_process
def: "The cell cycle process that corrects the anomalous association of a single chromatid kinetochore with mitotic spindle microtubules emanating from both spindle poles (otherwise known as merotelic attachment to the spindle)." [PMID:21306900]
is_a: GO:0009987 ! cellular process
relationship: part_of GO:0051310 ! metaphase plate congression

Should the term be part_of GO:0007080, **mitotic** metaphase plate congression instead?

Then the new term:

id: GO:NEW
name: correction of merotelic kinetochore attachment, meiotic
namespace: biological_process
def: The cell cycle process that corrects the anomalous association of a single chromatid kinetochore with mitotic spindle microtubules emanating from both spindle poles at meiosis I, and would, if uncorrected result in the separation of sister chromatids at meiosis I. [PMID:21920317]
is_a: GO:0009987 ! cellular process
relationship: part_of GO:0043060 ! meiotic metaphase I plate congression

Agree?

**Comment by ValWood** [comment]
Yep I think so. @dosumis could you double check?

**Comment by dosumis** [comment]
Yep.  Sorry.

**Comment by tberardini** [comment]
Changed relationship for GO:0098783

-relationship: part_of GO:0051310 ! metaphase plate congression
+relationship: part_of GO:0007080 ! mitotic metaphase plate congression

Added:

+id: GO:0090699
+name: correction of merotelic kinetochore attachment, meiosis I
+namespace: biological_process
+def: "The cell cycle process that corrects the anomalous association of a single chromatid kinetochore with mitotic spindle microtubules emanating from both spindle poles at meiosis I, and would, if uncorrected result in the separation of sister chromatids at meiosis I." [GOC:vw, PMID:21920317]
+is_a: GO:0009987 ! cellular process
+relationship: part_of GO:0043060 ! meiotic metaphase I plate congression
