### ISSUE TITLE
please swap primary term name with a synonym GO:0052858

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12628]
GO:0052858
peptidyl-lysine N-acetyltransferase activity, acting on acetyl phosphate as donor

please call it
	peptidyl-lysine acetyltransferase activity
or
t	peptidyl-lysine N(6)-acetyltransferase activity

cheers

Val

**Comment by ValWood** [comment]
Should
 GO:0004468
lysine N-acetyltransferase activity, acting on acetyl phosphate as donor

be a parent rather than a sibling?

**Comment by ukemi** [comment]
Since they are all exact synonyms, I swapped the primary name with peptidyl-lysine acetyltransferase activity.

I will not change the parentage because L-lysine and L-lysine residue do not have a subtype relationship in ChEBI. L-lysine is substituent group from L-lysine residue. I'm not certain how this relation would hold over an enzymatic reaction.

**Comment by ValWood** [comment]
I don't understand that, but I'll take your word for it!
