### ISSUE TITLE
NTR: homotypic vesicle fusion and secretory granule maturation

### ISSUE THREAD

**Issue by rebeccafoulger** [geneontology/go-ontology#12635]
Two new terms needed for annotation of Syt4 (Synaptotagmin-IV) in PMID:16618809:

homotypic vesicle fusion ; GO:NEW1
The fusion of two vesicle membranes to form a single vesicle.
GOC:bf, GOC:PARL
PMID:16618809
(Given that you’d have to have 2x ‘results_in_fusion_of: vesicle membrane’, I’m not sure I can currently create a decent logical definition for this).

secretory granule maturation ; GO:NEW2
Steps required to transform an immature secretory vesicle into a mature secretory vesicle. Typically proceeds through homotypic membrane fusion and membrane remodelling.
is_a: secretory granule organization ; GO:0033363
developmental maturation (GO:0021700) that results_in_organization_of: secretory granule ; GO:0030141
GOC:bf, GOC:PARL
PMID:16618809
is_a: child: dense core granule maturation ; GO:1990502

Note a similar logical definition could be added to dense core granule maturation ; GO:1990502
developmental maturation (GO:0021700) that results_in_organization_of: dense core granule ; GO:0031045

Thanks.

**Comment by ukemi** [comment]
Including @dosumis because I'm sure he must have thought about this with respect to synaptic vesicles.

My hesitation with any of the 'homotypic' terms including the cell-cell adhesions terms is that at what level do we define the two entities as being the same. In the case of cell adhesion if two neurons bind one another, but they are distinct subtypes of neurons, is this homotypic? I have the same concerns with this term. In the ontology there is a rich substructure under membrane-bounded vesicle. At what point to we make the cut off for what is homotypic and what is heterotypic?

For the maturation term, we have 'synaptic vesicle maturation' and 'dense core granule maturation' as is_a children of 'vesicle organization'. We also have 'secretory granule organization' as a child. It seems like there are some patterns here of which we could take advantage. 'Synaptic vesicle maturation' is defined as 'developmental maturation' results_in_organization_of SOME 'synaptic vesicle' and is asserted as a subclass of 'vesicle organization'. There is also a term for 'synaptic vesicle coating' that has no relation to the maturation term. Any insights David?

**Comment by dosumis** [comment]
I'd be reluctant to support a homotypic/heterotypic distinction if we can avoid it - for the resaons that @ukemi outlined above.

CC @Pimmelorus - General question about dense core vesicles here.  Any comments?  Could you see a need for a DCV maturation term for the Synapse work?

**Comment by rebeccafoulger** [comment]
I see the problem with the 'homotypic' wording. How about making it more explicit in the GO term? It would go alongside the more specific instances of vesicle fusion:
E.g
vesicle fusion ; GO:0006906
--[isa]vesicle fusion with vesicle ; GO:NEW
--[isa]vesicle fusion to plasma membrane ; GO:0099500
--[isa]vesicle fusion with vacuole ; GO:0051469
--[isa]vesicle fusion with endoplasmic reticulum ; GO:0048279

**Comment by dosumis** [comment]
> I see the problem with the 'homotypic' wording. How about making it more explicit in the GO term? It would go alongside the more specific instances of vesicle fusion:
> E.g
> vesicle fusion ; GO:0006906
> --[isa]vesicle fusion with vesicle ; GO:NEW
> --[isa]vesicle fusion to plasma membrane ; GO:0099500
> --[isa]vesicle fusion with vacuole ; GO:0051469
> --[isa]vesicle fusion with endoplasmic reticulum ; GO:0048279

That looks fine.  I thought you were referring to vesicles of the same type.

**Comment by ukemi** [comment]
Me too. This looks ok.
Added:

 [Term]
+id: GO:0061782
+name: vesicle fusion with vesicle
+namespace: biological_process
+def: "Fusion of the membrane of a transport vesicle with a target membrane on another vesicle." [GOC:bf, GOC:PARL, PMID:16618809]
+synonym: "vesicle to vesicle fusion" EXACT [GOC:dph]
+synonym: "vesicle-vesicle fusion" EXACT [GOC:dph]
+is_a: GO:0006906 ! vesicle fusion
+created_by: dph
+creation_date: 2016-09-06T13:29:49Z
+

**Comment by rebeccafoulger** [comment]
Thankyou! The authors were talking about two vesicles of the same type fusing, but vesicle-vesicle fusion is enough for me!

**Comment by ukemi** [comment]
Added logical def to dense core granule term and:

 [Term]
+id: GO:0061792
+name: secretory granule maturation
+namespace: biological_process
+def: "Steps required to transform an immature secretory vesicle into a mature secretory vesicle. Typically proceeds through homotypic membrane fusion and membrane remodelling." [GOC:bf, GOC:dph, GOC:PARL, PMID:16618809]
+is_a: GO:0033363 ! secretory granule organization
+intersection_of: GO:0021700 ! developmental maturation
+intersection_of: results_in_maturation_of GO:0030141 ! secretory granule
+created_by: dph
+creation_date: 2016-09-09T13:24:34Z
