### ISSUE TITLE
proposal: merge cardiovascular system and circulatory system development

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12655]
Within any given species, these are equivalent. CV is usually applied to vertebrates, or at least closed circulatory systems.

Having both in GO causes confusion as we are never sure when a word is used in a broader or more specific sense (or we weren't until we brought in uberon TCs, which revealed inconsistencies).

Currently heart-dev po CV-system-dev. "heart" is generic in GO. but Dmel dorsal vessels are not part of vertebrate-style CV systems.

**Comment by dosumis** [comment]
I think the two options are:

(a) Merge 'cardiovascular system development'  into 'circulatory system development' (the losing term becomes a narrow synonym; axiomatisation as for the winning term stays)
(b) Reflect the structure of Uberon, having 'primary circulatory organ development' (part_of 'circulatory system development')  and subclasses 'heart development' (part_of 'cardiovascular system development'),  'dorsal vessel development' etc.

The argument for (a) is that the data from Drosophila gets grouped under heart development.  The argument for (b) is that it allows more precise annotation/groupings. 

CC @ukemi

**Comment by ukemi** [comment]
It seems that (b) is more easily maintained as well as allowing for more precise grouping.

**Comment by dosumis** [comment]
> It seems that (b) is more easily maintained as well as allowing for more precise grouping.

Agreed.  I'll implement then.  First I'll briefly remove the offending part_of relationship as I'd like to use TG to add the new terms.

**Comment by cmungall** [comment]
+1

**Comment by dosumis** [comment]
Offending axioms removed from GO.  TG check now passing.

**Comment by dosumis** [comment]
Disentangling and separating out GO class hierarchy and annotations is a bit delicate.

Current state of ontology:

'heart development'  -> Uberon:'primary circulatory organ'
'heart formation' -> Uberon:heart
'heart growth' -> Uberon:heart
'heart morphogenesis' -> Uberon:heart

Some disentangling of annotations required:

There are [a couple of hundred annotations fly annotations to heart development](http://www.ebi.ac.uk/QuickGO/GAnnotation?a=&goid=GO%3A0007507&termUse=ancestor&relType=IPO%3D&customRelType=IPOR%2B-%3F%3D&evidence=IMP%2CIGI%2CIPI%2CIDA%2CIEP%2CEXP&protein=&tax=7227&qualifier=&ref=&with=&source=&q=&col=proteinDB%2CproteinID%2CproteinSymbol%2Cqualifier%2CgoID%2CgoName%2Caspect%2Cevidence%2Cref%2Cwith%2CproteinTaxon%2Cdate%2Cfrom%2Csplice&select=normal).  Only [31 of these are direct](http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007507#term=annotation) but there are a number of annotations to subclasses/subparts where disentangling is also required.

**Comment by hattrill** [comment]
I'll have a chat with Marta about this and look over some of the papers to see in what spirit some of these annotations were made.

**Comment by dosumis** [comment]
Ta.  We're leaning towards solution (b) here: https://github.com/geneontology/go-ontology/issues/12655#issuecomment-246704030 .  But would be good to get FB take on preferred solution + some assesment of FB work required if we do follow this path.

**Comment by ukemi** [comment]
Perhaps we need to discuss this on an annotation call.

**Comment by ukemi** [comment]
There are around 3000 annotations to heart development or the children. Most of them are vertebrate, so it makes sense to keep the term specific to the vertebrate structure and creating a new superclass. However as David points out, we will need to sort out the children and the fly annotations.

**Comment by hattrill** [comment]
I've had a preliminary look at this issue and skimmed a low number of papers. I have some reservations about drosophila heart development being hived off from heart development.

First, a heart is anatomically distinguishable. The dorsal vessel of drosophila can be divided into two structures, the aorta and the heart. While, in some case annotations have been made to heart development that apply to the dorsal vessel as a whole, some really apply just to the heart. Second, it shares many features of a vertebrate heart (mesodermal origin, myogenic, pacemaker). Third, many of these experiments are done in direct comparision/parallel to early vertebrate heart development and this represented in the terminology in the literature (a Pubmed search with "drosophila and dorsal vessel" yields just 102 pubs, "drosophila and heart" 1423  - I haven't looked closely to see if they are using the terms correctly or lazily).

I am away for annual FlyBase meeting/SAB over the next week. But when I get back I shall have a proper dig. Should probably look over what was done in the cardiac annotation project and ask the opinion of the BHF-UCL.

**Comment by ukemi** [comment]
As a reminder in this discussion. At the heart development workshop, the experts opinion was too include the drosophila structure in the GO term. What if we just kept heart development as is and changed the logical def to point to the more general term in UBERON?

**Comment by ukemi** [comment]
Can we deal with cardiovascular/circulatory in the same way? We would have to see how the lymphatic system fits in there.

**Comment by dosumis** [comment]
Hi Helen,

Thanks for looking in to the annotations & anatomy.  I'd forgotten about the division of the dorsal vessel. 

@ukemi wrote:
> As a reminder in this discussion. At the heart development workshop, the experts opinion was too include the drosophila structure in the GO term. What if we just kept heart development as is and changed the logical def to point to the more general term in UBERON?

It already does ('primary circulatory organ'). The problem is the relationship of development terms to those for 'cardiovascular system'.  Uberon says all cardiovascular systems have a heart as a part (true only in the narrow sense) and this was leading to inconsistencies.  This can also be fixed using option (a) - merging GO dev terms for cardiovascular system and circulatory system.

The question is: what's worse: losing a term for 'cardiovascular system development' from GO in favor of something much broader;  dropping the term 'heart' for processes that group primary circulatory organs for flies and vertebrates?

I'm still wavering to be honest.   There's definitely enough in common between vertebrate and arthropod hearts (and the molecular basis of their development) to justify grouping GO processes that refer to them.  With the proposed change this would still be possible, but Fly people would probably expect the use of the term heart and others are less likely to see the significance of grouping if we use the term 'primary circulatory organ' rather than 'heart' in GO class names. 

Another way to do this might be to change Uberon:

![image](https://cloud.githubusercontent.com/assets/112839/18550380/74f60a86-7b4b-11e6-86fa-7dccb13a1532.png)

![image](https://cloud.githubusercontent.com/assets/112839/18550481/fda7c5ea-7b4b-11e6-926f-7f4fd2c56a7c.png)


->
'primary circulatory organ'
.   .  <- is_a heart
.   .   .  <- is_a dorsal vessel heart
.   .   .  <- is_a cardiovascular system heart

'circulatory system'
.   .  <- is_a 'closed circulatory system'
.   .   .   <- part_of 'circulatory system dorsal vessel'  (classifies FBbt dorsal vessel)
.   .   .   .   <- part_of 'dorsal vessel heart' (classifies FBbt heart)
.   .   .   .   <- part_of 'dorsal vessel aorta' (classifies FBbt aorta)
.   .  <- is_a 'open circulatory system'
.   .   .   <- part_of 'cardiovascular system'
.   .   .   .   <- part_of 'cardiovascular system heart'

With this in place we could still have 'heart development' be the broad term in GO - adding two new subclasses that split the details into two branches - one for 'cardiovascular system heart', and one for 'dorsal vessel hearts' and to hook up heart development to the appropriate system development terms.  Aligning GO-Uberon terminology in this way is much less confusing than the status quo.

**Comment by dosumis** [comment]
> we have to try to work with the language used by scientists

... whilst simultaneously trying to be unambiguous.

**Comment by hattrill** [comment]
That seems more satisfactory to me, too!

**Comment by dosumis** [comment]
@cmungall - Can you comment on whether the new fix would work for Uberon?  Do you forsee any gnashing of teeth in response to adding 'cardiovascular (system?) heart' as the general term for vertebrate (chordate?) hearts?

**Comment by cmungall** [comment]
Continuing discussion on the purely anatomy ontology aspects on the linked uberon ticket

**Comment by RLovering** [comment]
Hi 
Rachael has just pointed out that currently heart development is not a child of cardiovascular system development.
As the definition of cardiovascular system development is: The process whose specific outcome is the progression of the cardiovascular system over time, from its formation to the mature structure. The cardiovascular system is the anatomical system that has as its parts the heart and blood vessels.

It looks like this relation was deleted on
2016-09-17 Deleted RELATION part of GO:0072358 (cardiovascular system development)

Please can this relation be re-instated, I think the relation is supposed to exist based on the definition and also the many comments above?

Thanks

Ruth
@rachhuntley

**Comment by ValWood** [comment]
Is this ticket finished.
Or did something need to be reverted based on @RLovering  comment?

**Comment by ValWood** [comment]
@ukemi

**Comment by RLovering** [comment]
Looking at QuickGO it looks like the parent requested by me/Rachael is present, so I am closing for you ;)
