### ISSUE TITLE
immune memory response

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#12650]
Moved from TG FF
[Term]
id: GO:1990982
name: Immune memory response
namespace: biological_process
def: "The immune response against a previously encountered antigen being quicker and quantitatively better compared with the primary response." [PMID:26831526]
subset: termgenie_unvetted
is_a: GO:0002250 ! adaptive immune response
created_by: sp
creation_date: 2016-09-01T10:57:56Z

**Comment by addiehl** [comment]
The existing GO term 'adaptive immune response' GO:0002250 (defined as "An immune response based on directed amplification of specific receptors for antigen produced through a somatic diversification process, and allowing for enhanced response to subsequent exposures to the same antigen (immunological memory).") is essentially equivalent to this proposed term.

You may add 'immune memory response' as an exact synonym.
--Alex

**Comment by ukemi** [comment]
Hi David.

I took this since I was editing anyways. Thanks Alex.

-D

**Comment by nnouspikel** [comment]
Dear GO annotators,
I am annotating the immune genes and would like to solicit your help to better define the adaptive immune response in GO. 
Specifically:

1. I would suggest updating the definition of GO:0002250 adaptive immune response so that it encompasses both the primary and the secondary immune responses of adaptive immunity. I’d suggest quoting Roitt’s textbook of immunology (http://www.roitt.com/) for the definition: “Adaptive immune response is immunity mediated by lymphocytes and characterized by antigen specificity and memory. The first encounter with antigen elicits a primary immune response that is rather slow and not of great magnitude. T and B lymphocytes selected by antigen become activated and undergo clonal expansion. A fraction of antigen-reactive lymphocytes become memory cells, whereas others differentiate into effector cells. The memory cells generated during the primary response enable a much faster and stronger secondary immune response upon antigen rechallenge’’.

2. I feel there is a need to create two GO terms that would distinguish effector functions and immune memory, which as mentioned above are two distinct elements of the adaptive immune response. This is a request from immunologists involved in our project. 
May I suggest creating the following GO terms:
GO:1990982: adaptive immune memory response (previously submitted by Sylvain).
definition: The immune response against a previously encountered antigen, being quicker and quantitatively better compared with the primary response. Quoting Zinkernagel in PMID:26831526
GO:xxx: adaptive immune effector response
definition: Cellular and humoral immune response that takes place during the effector phase of the adaptive immune response. In the case of B lymphocytes, the effector cells are the antibody-secreting plasma cells whereas for T-lymphocytes the effector cells may be T-helper cells, cytotoxic T-cells or regulatory T cells. Quoting Roitt’s textbook of immunology (http://www.roitt.com/) for the definition.

Thank you in advance for your help,

Nevila Hyka-Nouspikel
