### ISSUE TITLE
GO:0042823 pyridoxal phosphate biosynthetic process parentage query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12665]
If 
 GO:0042823 pyridoxal phosphate biosynthetic process
is
The chemical reactions and pathways resulting in the formation of pyridoxal phosphate, pyridoxal phosphorylated at the hydroxymethyl group of C-5, the active form of vitamin B6.

should it be part of

GO:0042819
Name    vitamin B6 biosynthetic process
The chemical reactions and pathways resulting in the formation of any of the vitamin B6 compounds; pyridoxal, pyridoxamine and pyridoxine and the active form, pyridoxal phosphate.

?

**Comment by ValWood** [comment]
same question for GO:0008615

**Comment by paolaroncaglia** [comment]
Hi @ValWood,

The issue here is due to this difference in GO vs ChEBI:

GO:
GO:0042823 pyridoxal phosphate biosynthetic process points to CHEBI:597326 pyridoxal 5'-phosphate(2-)
GO:0042819 vitamin B6 biosynthetic process points to CHEBI:27306 vitamin B6

ChEBI:
pyridoxal 5'-phosphate(2−) (CHEBI:597326) is conjugate base of pyridoxal 5'-phosphate (CHEBI:18405) 
pyridoxal 5'-phosphate (CHEBI:18405) is a vitamin B6 phosphate (CHEBI:36970)
vitamin B6 phosphate (CHEBI:36970) *has functional parent* vitamin B6 (CHEBI:27306) 

so vitamin B6 phosphate is a derivative of vitamin B6

Not sure how to fix this. Would you like to open a ticket with ChEBI and link it here please?

Thanks,

Paola

**Comment by ValWood** [comment]
I think that's one for the editors, I have done my bit ;)  remember I'm a literature curator not an ontology editor....  and I'm not funded by GO.....

**Comment by paolaroncaglia** [comment]
Sure @ValWood, I didn’t mean that ;-) It’s just that it looks more of an issue with ChEBI than with us, that’s why I’m not sure how to fix it. I’ll look into it some more. Cheers.

**Comment by ValWood** [comment]
Yeah I'm not sure what the issue is, only that there is a problem which is filtering through to PomBase annotation consistency. I'm only reporting an issue. I'll help where I can but  I don't really know about how GO aligns with CHEBI....or what would be correct.

**Comment by paolaroncaglia** [comment]
No worries @ValWood , I'll investigate and will post updates here.

**Comment by paolaroncaglia** [comment]
Note for self: same as GO, ChEBI defines pyridoxal 5'-phosphate as “the active form of vitamin B6”
(see https://www.ebi.ac.uk/chebi/searchId.do;jsessionid=976E8823A58FC29140E69DBD51760FAC?chebiId=CHEBI%3A18405).
Therefore, it seems to me that, in order to achieve consistency, we need to consult with ChEBI about how they’d like to fix the discrepancy between pyridoxal 5'-phosphate being called a type of vitamin B6 and its derivative at the same time. Perhaps pyridoxal 5'-phosphate needs to be textually defined as “the active derivative of vitamin B6”. If so, we’d need ChEBI to create ‘vitamin B6 derivative’ or similar (and ‘vitamin B6 phosphate’ placed under it), and then GO would need to create ‘vitamin B6 derivative metabolic process’ or similar (and ‘GO:0042823 pyridoxal phosphate biosynthetic process’ would sit under it).

**Comment by ValWood** [comment]
according to wikepedia 

Vitamin B6 refers to a group of chemically very similar compounds which can be interconverted in biological systems.

so its really a grouping term rather than a specific compound if this is true...

I think i'd expect all to  be grouped as "vitamin B6 metabolism"

**Comment by paolaroncaglia** [comment]
That would be my preferred solution too :-)

**Comment by ukemi** [comment]
Me too.

**Comment by paolaroncaglia** [comment]
Hi @ValWood , I opened a ChEBI ticket to see if they'd consider making vitamin B6 a grouping term. 
We could then fix GO accordingly.
Setting to pending while I wait to hear from them.

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
Update: I followed up with ChEBI today.

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
FYI, I followed up with ChEBI on this one by email today.

**Comment by paolaroncaglia** [comment]
Note for self: Gareth Owen from ChEBI emailed:
"I think the B6 problem is an annotation issue rather than a bug - we will try and get it sorted as soon as we can."

**Comment by paolaroncaglia** [comment]
@ValWood
Steve from ChEBI writes:
“I've changed the 'vitamin B6 phosphate (CHEBI:36970) has functional parent vitamin B6 (CHEBI:27306)'
to vitamin B6 phosphate (CHEBI:36970) is a vitamin B6 (CHEBI:27306), as the phosphates are also biologically active forms of vitamin B6. So now the term 'vitamin B6' captures the parent compounds (pyridoxal, pyridoxamine, pyridoxic acid and pyridoxine) and their phosphates as a subclass (the individual phosphates have functional parent links to the individual parents).”
The change was made on Nov 21st (see http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:36970), but we’ll have to wait for the new ChEBI release (presumably around the beginning of Dec) for the change to percolate to GO. Then the parentage of
GO:0042823 pyridoxal phosphate biosynthetic process
and
GO:0008615 pyridoxine biosynthetic process
will be fixed automatically and linked to vitamin B6. Closing now.
