### ISSUE TITLE
Query about basal TFs

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12674]
I am revising some TF annotations, and I was wondering why  there is a term

	TFIIIB-type transcription factor activity
for TFIIB, but no equivalent terms for the TFIID,F,H etc?

**Comment by krchristie** [comment]
Hi Val,

Note that the term you list is not for TF-II-B, but for TF-III-B (hyphens for clarity in number if 'I's).

TFIIIB is kind of a special case, largely because it is a RNAP III txn factor, instead of one for RNAP II. It does a very specific job that can be defined in terms of what it is binding to. From what I read when David H and I were working on this, there isn't as much variability in how RNAP III promoters work, i.e. which factors bind to the promoter recruit the RNAP. 

There is so much variability in how promoters for RNAP II work that I can't define how any of the basal factors for RNAP II work, so there are no terms like this for any of the RNAP II basal txn factors.

-Karen

**Comment by ValWood** [comment]
OK just curious, closing
