### ISSUE TITLE
NTR/OTR: multiciliation-related classes

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12672]
**SUMMARY:** 
Following email discussion with some ciliary experts, the issue was raised that we should improve representation of events leading to multiciliation (i.e. presence of multiple cilia on a cell). At this stage, we intend to provide basic classes; further development in this field could be part of some future work and/or reflect new knowledge. 

---

**Details:**

(@JohnVanDam, @krchristie, please review and let me know if you disagree with anything.)

Based on input from experts (Gregory Pazour, Peter Satir and George Witman) and on two reviews (PMID:25047614 and PMID:25291643), here are my suggestions:
- [x] Add new term: 
  blepharoplast
  is_a intracellular non-membrane-bounded organelle
  An intracellular non-membrane-bounded organelle found in multi-ciliated sperm cells of some primitive land plants, and consisting of many radially arranged ninefold symmetric cylinders. The blepharoplast is involved in de novo formation of multiple centrioles; it enlarges and then disintegrates into many procentrioles, which elongate and ultimately nucleate cilia on the surface of the sperm cell. 
  GOC:cilia, PMID: 25047614
  comment: The blepharoplast should not be confused with a basal body; rather, it acts as the precursor assembly zone for multiple basal bodies.
- [x] Add taxon constraint to ‘blepharoplast’.
  @tberardini , could you help with this please? (You may ignore the rest of this ticket) The taxon rule should be - plants that have multi-ciliated sperm cells. PMID:16736257 may help, you pointed it out on a related ticket (https://github.com/geneontology/go-ontology/issues/10905). Thanks.
- [x] Add taxon constraint to ‘deuterosome’ (only in Metazoa) and dbxrefs GOC:cilia, PMID:25047614.
- [x] Edit GO:0098535 ’de novo centriole assembly’:
  1) Make it ’de novo centriole assembly involved in multi-ciliated epithelial cell differentiation’, and revise definition and links accordingly.
  (@dosumis, tagging you FYI as you created ’de novo centriole assembly’ and ‘deuterosome’. The logic behind this change (and the ones below) is that ’de novo centriole assembly’ can occur via pathways other than the deuterosome one, see fig. 2 in PMID:25047614. The term you created, and all the annotations that it currently has, indicate that it refers strictly to the specific deuterosome-mediated de novo centriole assembly pathway that takes place during differentiation of multi-ciliated animal epithelial cells. I’ll create a generic parent term and a couple of sibling terms to reflect the known variety of mechanisms by which some cells become multiciliated rather than having a single cilium or two. This will address an important concern from ciliary experts. Feel free to ignore the rest of this ticket ;-))
  2) Add definition comment: “In most eukaryotic cells, 'centriole' (GO:0005814) and ’ciliary basal body' (GO:0036064) represent a common entity that cycles through its function in cell division, then ciliogenesis, then cell division again. However, these structures are modified extensively as they transition into each other, and may contain different proteins, specific to each component.”
  3) Add related synonyms:
  deuterosomal basal body biogenesis
  deuterosome pathway (dbxref PMID:25047614)
  deuterosome-mediated centriole biogenesis (dbxref PMID:24075808)
  multiciliation
  multiciliogenesis
  4) Add GOC:cilia
- [x] Create ’de novo centriole assembly’ as a parent for ’de novo centriole assembly involved in multi-ciliated epithelial cell differentiation’:
  de novo centriole assembly
  is_a centriole assembly
  Centriole assembly in which a centriole arises de novo, rather than by replication from an existing centriole. This process may occur via different mechanisms. Examples include the deuterosome pathway in multicilated epithelial animal cells and formation of centrioles during parthenogenesis in some insects.
  GOC:cilia, PMID:25291643, PMID:25047614
  related synonyms: 
  multiciliation
  multiciliogenesis
  de novo basal body generation
  de novo basal body biogenesis
  de novo ciliary basal body assembly
  de novo basal body assembly
  de novo basal body amplification
  de novo centriole amplification
  acentriolar basal body biogenesis
- [x] Add as child of ’de novo centriole assembly’ (and sibling to ’de novo centriole assembly involved in multi-ciliated epithelial cell differentiation’):
  de novo centriole assembly via blepharoplast 
  is_a de novo centriole assembly
  has_participant blepharoplast
  A de novo centriole assembly process observed in multi-ciliated sperm cells of some primitive land plants, and where centrioles are formed from a blepharoplast, ultimately giving rise to multiple cilia on the sperm surface. 
  GOC:cilia, PMID: 25047614
  related synonyms: 
  multiciliation
  multiciliogenesis
- [x] @cmungall, @dosumis, please confirm if taxon rules are not inherited via has_participant. If so, I’ll give ‘de novo centriole assembly via blepharoplast’ the same constraint as blepharoplast.
- [x] Examine the existing term GO:0032054 'ciliary basal body duplication', its supporting PMID and annotations, and evaluate if/how it should be linked to ’de novo centriole assembly’ . 
- [x] Future work: add term for ‘(de novo?) centriole assembly involved in ciliated olfactory receptor neuron differentiation’ (with related synonyms ‘multiciliation’ and ‘multiciliogenesis’) if/when new research clarifies this point (from  PMID:25047614): “There are other situations in which multiple centrioles form, and the relationship between these and the deuterosome pathway is not clear. One example is the olfactory sensory neurons, which are the main sensory cells in the olfactory epithelium. In these neurons, dendrites extend towards the nasal cavity, ending in a knob containing 10–30 centrioles from which cilia project to the epithelial surface. Ultrastructural studies suggested that these centrioles assemble near-simultaneously in the cell body and migrate to the dendritic knob, but whether the centrioles are nucleated from pre-existing centrioles or deuterosome-like structures is not known.”
  Will need adding via TG beforehand ‘ciliated olfactory receptor neuron differentiation’, pointing to CL:0000847 (make sure the GO term has synonyms for ciliated olfactory sensory neuron, ciliated sensory neuron)
- [x] Stemming from the above: @dosumis, shouldn’t GO:0098788 ‘dendritic knob’ (“The terminal swelling of an apical dendrite of an olfactory receptor neuron. Each knob gives rise to 5 to 20 long delicate nonmotile cilia, which extend into the mucus covering the sensory epithelium”) be part_of CL:0000847 ciliated olfactory receptor neuron? Happy to do the edit (and add ‘ciliated’ and missing period to def)
- [x] Future work: add term for ‘de novo centriole assembly involved in asexual reproduction’ (or a more specific one? without any cilia-related synonyms) to describe this (from  PMID:25047614): “Centriole number control also differs from that of somatic cycling cells in embryos in which the centrioles are not derived from the sperm. In most animals, the sperm cell has one or two centrioles that are introduced into the egg upon fertilization, then duplicated, initiating the pathway described above for cycling cells. However, in some organisms, the embryo develops parthenogenetically, without sperm, thus centrioles must be formed de novo, and number control exerted after formation. For example, in insects of the hymenoptera order, hundreds of centrioles form de novo during the late stages of oogenesis. These centrioles then recruit pericentriolar material and form microtubule asters. From these many centrosomes, only two become associated with the female pronucleus and form the mitotic spindle, whereas others degenerate, thus establishing the correct ratio of centrioles to nuclei.”.
  Maybe check with FlyBase about taxon constraints.
- [x] Related: add ‘parthenogenesis’ as a related synonym of GO:0019954 ‘asexual reproduction’ (dbxref https://en.wikipedia.org/wiki/Parthenogenesis)
- [x] Future work: polarisation of cilia, do we need it and where should it be placed? (See PMID:25291643)
- [x] Future work: how can we represent tissue level polarisation of MCCs? (See PMID:25291643) Use existing ‘establishment of tissue polarity’ (or its child ‘establishment of planar polarity’)?
- [x] Address Peter Satir's concern that "in some organisms the multiple cilia form a distinct organelle (mussel gill laterofrontal cilia, ctenphore comb plates) and this isn’t captured at all.".
- [x] Future work: it would be great if more players could be annotated to these multiciliation terms. A good starting point to find papers could be the review PMID:25291643 from 2014. Plus the 2 reviews that Karen points out below.
- [x] Future work: indeed, ideally, all PMIDs used as dbxrefs for GOC:cilia terms should be annotated, if they're not already, if they’re not review papers and if they contain info appropriate for gene product curation…

**Comment by paolaroncaglia** [comment]
Note for self: added GO:0097727 blepharoplast.

**Comment by krchristie** [comment]
Hi @paolaroncaglia 

In much of this, you have gone beyond my current knowledge of multiciliation. But everything you plan makes sense to me. It's a great start.

One possibly useful comment I have is that my understanding of tissue level polarization via the planar cell polarity (PCP) pathway is that the PCP pathway is often upstream and critical to the development of the orientation of cilia in singly ciliated cells, e.g. in the hair cells of the ear that form kinocilia and arrays of stereocilia. I can't recall coming across anything specific about any role of the PCP pathway in the development of MCC's (though this may be due to failure of my memory). However,  it wouldn't surprise me if the PCP pathway is equally important in MCC's as in singly ciliated cells.  

-Karen

**Comment by paolaroncaglia** [comment]
Thanks @krchristie .

**Comment by paolaroncaglia** [comment]
Note for self: I just requested Zygnematales, Gnetales and Coniferophyta to be added to imports_requests.obo.

**Comment by krchristie** [comment]
Just came across a new review on MCCs that looks very interesting:

Meunier A, Azimzadeh J. Multiciliated Cells in Animals. Cold Spring Harb
Perspect Biol. 2016 Aug 31. pii: a028233. doi: 10.1101/cshperspect.a028233. [Epub
ahead of print] PubMed PMID: 27580630.

**Comment by krchristie** [comment]
Another potentially interesting review:

Ohata S, Alvarez-Buylla A. Planar Organization of Multiciliated Ependymal (E1)
Cells in the Brain Ventricular Epithelium. Trends Neurosci. 2016
Aug;39(8):543-51. doi: 10.1016/j.tins.2016.05.004. Epub 2016 Jun 13. Review.
PubMed PMID: 27311928.

**Comment by paolaroncaglia** [comment]
@cmungall, @dosumis, 
I presume that taxon rules are not inherited via has_participant. Could you please confirm?
Specifically, if ‘blepharoplast’ is found only in some plants, and ‘de novo centriole assembly via blepharoplast’ is_a ‘de novo centriole assembly’ that has_participant ‘blepharoplast’, and the taxon rule is not inherited, I’ll need to add it to the assembly term myself.

**Comment by paolaroncaglia** [comment]
@dosumis, 
shouldn’t GO:0098788 ‘dendritic knob’ (“The terminal swelling of an apical dendrite of an olfactory receptor neuron. Each knob gives rise to 5 to 20 long delicate nonmotile cilia, which extend into the mucus covering the sensory epithelium”) be part_of CL:0000847 ciliated olfactory receptor neuron? Happy to do the edit (and add ‘ciliated’ and missing period to def).

**Comment by cmungall** [comment]
You should be able to see this in the property chains in Protege

**Comment by dosumis** [comment]
> @dosumis, 
shouldn’t GO:0098788 ‘dendritic knob’ (“The terminal swelling of an apical dendrite of an olfactory receptor neuron. Each knob gives rise to 5 to 20 long delicate nonmotile cilia, which extend into the mucus covering the sensory epithelium”) be part_of CL:0000847 ciliated olfactory receptor neuron? Happy to do the edit (and add ‘ciliated’ and missing period to def).

Sounds like it.

**Comment by dosumis** [comment]
> You should be able to see this in the property chains in Protege

Don't think we have this, we *could* add 

has_participant o only_in_taxon -> only_in_taxon

**Comment by cmungall** [comment]
this is like regulates - could cross-species

**Comment by dosumis** [comment]
Good point. So maybe not.

**Comment by paolaroncaglia** [comment]
Thanks @cmungall and @dosumis , I'll add the constraint myself then (in this case it would be correct to have it). And I'll fix 'dendritic knob'.

**Comment by dosumis** [comment]
> Thanks @cmungall and @dosumis , I'll add the constraint myself then (in this case it would be correct to have it). And I'll fix 'dendritic knob'.

Good solution for now.

@cmungall - longer teshouldn't this come in via taxon constraint on the term

**Comment by dosumis** [comment]
Accidentally commented.  Now deleted, please ignore if you see in your mail.

**Comment by paolaroncaglia** [comment]
Note for self: moved 'future work' here https://github.com/geneontology/go-ontology/issues/12783

**Comment by paolaroncaglia** [comment]
Note for self:
Cleaning up this ticket. Only 2 tasks left:

- [ ] Examine the existing term GO:0032054 'ciliary basal body duplication', its supporting PMID and annotations, and evaluate if/how it should be linked to ’de novo centriole assembly’.

- [ ] Add ‘parthenogenesis’ as a related synonym of GO:0019954 ‘asexual reproduction’ (dbxref https://en.wikipedia.org/wiki/Parthenogenesis).

**Comment by paolaroncaglia** [comment]
@fatimasilva (for the GeneDB annotation)
@JohnVanDam and @krchristie (for expertise on cilia)
@ValWood (for a sanity check on centrioles)

There is an old term in GO created in 2006

[Term]
id: GO:0032054
name: ciliary basal body duplication
namespace: biological_process
def: "Construction of a new ciliary basal body." [GOC:cilia, PMID:9889124]
synonym: "microtubule basal body duplication" BROAD []
is_a: GO:0032053 ! ciliary basal body organization

The PMID used as dbxref describes the role of gamma-tubulin in basal body duplication in Paramecium. 
The term has been used in 2 experimental annotations, from a single paper, for two strains of Trypanosome, by GeneDB and UniProt, to describe the role of a Tryp protein in basal body duplication. (It has also been used in 3 ISO annotations by GeneDB.)
Basal bodies and centrioles are often mentioned interchangeably in the literature. In GO we address this by saying “In most eukaryotic cells, 'ciliary basal body' (GO:0036064) and 'centriole' (GO:0005814) represent a common entity that cycles through its function in cell division, then ciliogenesis, then cell division again. However, these structures are modified extensively as they transition into each other, and may contain different proteins, specific to each component.” (this is a definition comment to 'ciliary basal body' and 'centriole’). Simplifying, I think it’s safe to say that in GO we should say ‘ciliary basal body’ when we refer to the cell component located at the base of the cilium (or on its way there, such as during cilium assembly), and use ‘centriole’ in other instances. So it’s the centriole that is duplicated (or assembled de novo) and that then cycles through to become the (ciliary) basal body. The ciliary basal body per se doesn’t duplicate - it’s the centriole that does. If this is correct, then I believe that 

- [ ] ’ciliary basal body duplication’ should be merged into ‘centriole replication’, and become a related synonym:

[Term]
id: GO:0007099
name: centriole replication
namespace: biological_process
def: "The cell cycle process in which a daughter centriole is formed perpendicular to an existing centriole. An immature centriole contains a ninefold radially symmetric array of single microtubules; mature centrioles consist of a radial array of nine microtubule triplets, doublets, or singlets depending upon the species and cell type." [GOC:kmv, ISBN:0815316194]
synonym: "centriole duplication" EXACT []
is_a: GO:0022402 ! cell cycle process
is_a: GO:0051297 ! centrosome organization
is_a: GO:0098534 ! centriole assembly
relationship: part_of GO:0051298 ! centrosome duplication

@fatimasilva the GeneDB annotations to ’ciliary basal body duplication’ would be automatically moved under ‘centriole replication’ - no need to do anything unless you disagree.
 
- [ ] Note for self - if the merge is approved, I’ll need to email the UniProt/SIB help desk to inform them of the change.

If any of you has any objections, please shout. If not, I’ll go ahead with the merge next week. Thanks!

**Comment by ValWood** [comment]
Hi Paola, these changes sound sensible to me.
v

**Comment by paolaroncaglia** [comment]
Thanks @ValWood .

**Comment by krchristie** [comment]
Seems sensible to me. 

I see that the term "centriole replication" is_a "cell cycle process", but even in the context of cilia, this makes sense to me that since presence of cilia is tied to specific stage of the cell cycle.

However, I have a question about the fact that currently the term "centriole replication" is part_of "centrosome duplication" which is defined as "The replication of a centrosome, a structure comprised of a pair of centrioles and peri-centriolar material from which a microtubule spindle apparatus is organized."

If "ciliary basal body duplication" is merged into "centriole replication", it seems like it might be a problem to say that "centriole replication" is always part_of "centrosome duplication", especially in cases where centrioles are being duplicated in order to make a multiciliated cell in a cell cycle stage where no more cell division is going to occur, as at least some types of [multi]ciliated epithelial cells are considered to be terminally differentiated.

Seems like the reverse relationship to say "centrosome duplication" has_part "centriole replication" might be true, but I think the current part_of won't be once this merge is made.

-Karen

**Comment by paolaroncaglia** [comment]
Hi @krchristie (and @ValWood for cell cycle),
Thanks for your input. Cases where centrioles are produced outside of the cell cycle would be covered by ‘de novo centriole assembly’ and children, and those terms are not linked to cell cycle ones, so we’d be fine. Do you know of any cases where centrioles are duplicated from existing centrioles, and ultimately give rise to ciliary basal bodies but the duplication step is not linked to the cell cycle? Thanks.

**Comment by ValWood** [comment]
I'm not even so familiar with centrioles as fungi don't have them.  

Until now I thought that centrile only applied to spindle associated micritubule organising centres.

It is defined
A cellular organelle, found close to the nucleus in many eukaryotic cells, consisting of a small cylinder with microtubular walls, 300-500 nm long and 150-250 nm in diameter. It contains nine short, parallel, peripheral microtubular fibrils, each fibril consisting of one complete microtubule fused to two incomplete microtubules. Cells usually have two centrioles, lying at right angles to each other. At division, each pair of centrioles generates another pair and the twin pairs form the pole of the mitotic spindle.

Isn't the ciliary basal body distinct? I.e  I presumed that organism which have this *also* have centrioles. Is this not the case?

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,
Thanks. See the definition comment for 'centriole':
"In most eukaryotic cells, 'ciliary basal body' (GO:0036064) and 'centriole' (GO:0005814) represent a common entity that cycles through its function in cell division, then ciliogenesis, then cell division again. However, these structures are modified extensively as they transition into each other, and may contain different proteins, specific to each component."
I'll ask John van Dam to weigh in as well...

**Comment by paolaroncaglia** [comment]
@JohnVanDam
Could you please comment on a specific issue in this ticket? See my comment here, and the following ones:
https://github.com/geneontology/go-ontology/issues/12672#issuecomment-261197420
Many thanks,
Paola

**Comment by JohnvanDam** [comment]
Paola's description of the cycle of the same structure between basal body and "proper" centriole is correct. I know that in most mammalian cell types which form (primary) cilia, ciliogenesis is actually required for centriole duplication. The daughter centriole forms attached to the basal body of the cilium during G1. The cilium gets resorbed in G2 and the basal body transforms into the mother centriole and the daughter centriole detaches. Inhibition of ciliogenesis in these cells also inhibits a daughter centriole from forming. I guess this is somehow not relevant in cells that do not produce cilia/flagella in G1.
During the differentiation of lung epithelial cells into multi-ciliated lung epithelial cells basal bodies are created via two distinct pathways. The centriolar and a-centriolar pathway. See this review, particularly figure 2, http://jcs.biologists.org/content/120/1/7.long. In the centriolar pathway the old centriole/basal body is used as a template, in the other centrioles form de novo without a template. The a-centriolar pathway seems to specifically produce centrioles for use as basal body.

So both ciliary basal body duplication and centriole replication occur and sometimes they are the same thing, and sometimes not. I guess for the template based duplication we could merge the terms, but the a-centriolar duplication pathway seems to belong specifically to the ciliary basal body duplication term. I am tempted to call centriole replication that which occurs in normal tissue cells that form primary cilia (since the daughter centriole will first be used as a centriole during cell devision), and use the ciliary basal body duplication for multi ciliation processes (as they will only be used as basal bodies). Does that make sense?

There are several organisms that have basal bodies and produce cilia and flagella but never utilize the structure for cell devision. Naegleria gruberi comes to mind which synthesises basal bodies de novo upon flagellation. As well as ferms and mosses which produce multiflagellated sperm cells, but use a non-centriolar MTOC for devision and do not appear to have centrioles/basal bodies in normal cells.

**Comment by ValWood** [comment]
Blimey! I guess these cells never divide again mitotically?

@paolaroncaglia  I think your existing CC terms are probably OK.

But under BP you will need to revise some terms under

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007099#term=ancchart

In this case it now seems incorrect to place "centrosome cycle"  under "cell cycle process".
Note that the terms under "cell cycle" should be involved in cell cycle progression, or a defined cell cycle processes (DNA replication, chromosome segregation, cytokinesis) not just 'occurring during a specific cell cycle stage'

Probably you will need to create terms
mitotic spindle centrosome (which will stay under cell cycle)
and 
ciliate centrosome
and duplicate the branch descendants
move the general "centrosome cycle"  out from under cell cycle

Then if you are annotating a non-cilate cell you would use the cell cycle branch
In a cilate cell you  would probably  only use the ciliate centrosome branch 

Q Would 'centrosome organization or biogenesis"  be a more standard term name  for "centrosome cycle"?

**Comment by krchristie** [comment]
Val, I'm not sure I understand the reason you feel "centrosome cycle" would need to be moved out of "cell cycle process". 

I think the idea of having a combined term for the templated centriole duplication that occurs in the context of cell cycle for the structure that is used both for the ciliary basal body and the centrosome makes a lot of sense since there is really just one duplication process. I think it is fine having this being a part of cell cycle process as the production of cilia is also cell cycle regulated. I just wonder if it's OK for this templated centriole duplication to always be "part_of" centrosome duplication.

Regarding John's suggestion to "_use the ciliary basal body duplication for multi ciliation processes (as they will only be used as basal bodies)_", I think this name could be misleading since it isn't really clear that this term would be for the specific situation where cells are multiciliated. We also already have a term for "de novo centriole assembly" with a couple child terms and I think these terms are very nicely defined. Perhaps also worth mentioning that the existing term for "_ciliary basal body duplication_" has only been used for 6 annotations (3 experimental from Trypanosoma brucei and 3 ISO from Trypanosoma or Leishmania). Perhaps worth checking what is intended in these annotations to think about what should happen to the term "_ciliary basal body duplication_". 


**PMID:19020665: Woodland & Fry 2008**
This paper has some interesting comments on the usage of centrioles in mitotic/meiotic spindles and in cilia/flagella, particularly that ciliary motility seems to be a major evolutionary pressure on maintainance of the structure of the centriole, i.e. in organisms that no longer produce any motile cilia, the structure of the centriole can diverge a lot.

**Comment by ValWood** [comment]
Being "cell cycle regulated" doesn't  automatically make a process a "cell cycle process". Unless we want to put *everything* which is cell cycle regulated under cell cycle (translation,  vesicle mediated transport etc. etc). 
All of the cell cycle processes currently are covered by regulation of transitions, replication, 
spindle assembly and segregation, chromsome segregation, cytokinesis.
To me,  ciliation terms would look very odd under  cell cycle. 

I don't know if I understood correctly, but the  same centrosome/centriole appears to be used in two different cellular contexts. It is part of the cell cycle in a cycling cell where it is required  for the spindle  events analogous to the  SPB  in fungi. In non-cycling cells  which form cilia, the centriole has an alternative role where it still duplicates, but  then forms cilia. 

If the duplication only occurs as a cell cycle process, and then subsequently in some cell types form cilia, then this current arrangement is probably fine.

**Comment by krchristie** [comment]
So, my understanding is that there are two types of centriole production in ciliated cells, at least in vertebrates. Protists could be different...

Anyway, for vertebrates, one kind of centriole production occurs in cycling cells and is the templated centriole duplication that is currently part of "centrosome duplication". This is the centriole duplication that generates the centriole that is used alternately as both the MTOC for the spindle during cell division and which then becomes the basal body of the cilium, with being the ciliary basal body probably the more ancient role. It seems to me that this term is fine as a cell cycle term, but _**possibly**_ not as always part_of "centrosome duplication". Or maybe that relationship is fine, and we could add to the definition of "centriole duplication" to indicate that these centrioles also become the ciliary basal body in cells that form cilia during G0. Certainly, it seems worth only having one term for this process because there is only one centriole duplication process that is generating these centrioles that are part of the spindle during cell division and may be part of a clium during G0.

The second type of centriole production occurs when cells differentiate to become multiciliated. This pathway is usually terminal differentiation, and I agree that this is a not cell cycle process. But we already have terms for this that are separate from the templated centriole duplication

**Comment by ValWood** [comment]
Yes in that case I think you are right, that should be fine. All of the genes which would be annotated to the centriole terms are part of the cell cycle. 
v

**Comment by paolaroncaglia** [comment]
@krchristie @ValWood @JohnVanDam
Thank you all for your feedback. I have now reviewed this thread carefully, and will go ahead with the following plan:

- [ ] merge ’ciliary basal body duplication’ into ‘centriole replication’, and keep it as a related synonym

- [ ] add to the def of ‘centriole replication’: “Duplicated centrioles also become the ciliary basal body in cells that form cilia during G0.”

- [ ] email the UniProt/SIB help desk to inform them of the change above (no re-annotation needed from them unless they disagree)
