### ISSUE TITLE
clarify term  "COP II adaptor activity"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12681]
defined
The binding activity of a molecule that brings together the COPII vesicle proteins and one or more other molecules, permitting them to function in a coordinated way.

I previously thought this term was to describe a cargo receptor, but now I am not so sure. It appears to be used for cargo receptors, but the parantage and the def do not reflect this?

**Comment by dosumis** [comment]
Would classifying additionally under cargo receptor activity fix the issue?

**Comment by ValWood** [comment]
I asked SGD about this. The 2 EXP annotation are theres. Maybe the def should be clarified too.
v

**Comment by robnash** [comment]
Hi,

Val asked SGD to comment on this issue so here are my two cents:

Erv29p is indeed a cargo receptor involved in ER-golgi transport of soluble cargo proteins. Turns out there are cargo proteins that bind directly to the COPII coat proteins such as Sec24p (complexes with Sec23p), and in this case it functions as a receptor and coat protein. The cargo proteins that bind directly to the COPII coat proteins are typically proteins that span the ER membrane so they are accessible to the cytosolic COPII coat proteins. In SGD, we have some of these (SEC24, SFB3/LST1, and SFB2/ISS1) annotated to the term:

GO:0090110	cargo loading into COPII-coated vesicle
Definition: The formation of a macromolecular complex between the COPII coat proteins and proteins and/or lipoproteins that are going to be transported by the COPII vesicle to the Golgi.

If you look at the ancestor chart there is a clear path from this term to ‘COPII vesicle budding' and in turn to 'ER-Golgi vesicle-mediated transport'. So this term and placement seem correct and make sense. 

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0090110#term=ancchart 

There is another class of cargo receptors that are indeed more like adaptors that are involved in the transport of soluble and transmembrane proteins via the COPII vesicle from ER-Golgi. Erv29p, Erv26p and Erv14p are examples of these receptors in budding yeast (see table 2 in the review PMID: 17618120 for a more complete list). Erv29p binds to a cargo encoded sorting signal, a sequence motif (ILV), leading to the recruitment of the cargo to the COPII vesicle. Some of these receptors, such as Erv14p also interact with the COPII coat proteins. For this group of proteins, there is some heterogeneity in our annotations, perhaps a reflection of the ambiguity or time frame involved, and includes:

GO:0097020	COPII adaptor activity
Definition: The binding activity of a molecule that brings together the COPII vesicle proteins and one or more other molecules, permitting them to function in a coordinated way.

as well as other to:

GO:0004872	receptor activity
Definition: Combining with an extracellular or intracellular messenger to initiate a change in cell activity.

and to

GO:0001948	glycoprotein binding
Definition: Interacting selectively and non-covalently with a glycoprotein, a protein that contains covalently bound glycose (monosaccharide) residues. These also include proteoglycans.

I agree that the current term needs to be classified as a cargo receptor, and the definition should be tweaked to be more specific. I also wonder if its placement in the ontology needs to be changed. Seems like it should have parentage of ‘ER to Golgi vesicle mediate transport’, and also to a COPII term. Currently, the COPII adaptor activity term has parent term ‘protein binding, bridging’, which seems inadequate.  So I would enhance the parentage. Alternatively, the term 'cargo loading into COPII-coated vesicle’ (GO:0090110) could be tweaked so that it could be used for both classes, although I don’t favor this as much.

The review I used to research this is a bit dated but well written:
Baines AC, Zhang B. Receptor-mediated protein transport in the early secretory
pathway. Trends Biochem Sci. 2007 Aug;32(8):381-8. Epub 2007 Jul 6. Review.
PubMed PMID: 17618120.

Hope this helps.

Cheers,
Rob

**Comment by ValWood** [comment]
I'm in the lobby if you want to do this one now....

**Comment by ValWood** [comment]
GO:0090110 cargo loading into COPII-coated vesicle
Definition: The formation of a macromolecular complex between the COPII coat proteins and proteins and/or lipoproteins that are going to be transported by the COPII vesicle to the Golgi.

is used to annotate (SGD)
SFB3
Component of the Sec23p-Sfb2p heterodimer of the COPII vesicle coat; required for cargo selection during vesicle formation in ER to Golgi transport
SEC24
Component of the Sec23p-Sec24p heterodimer of the COPII vesicle coat; required for cargo selection during vesicle formation in ER to Golgi transport
SFB2
Component of the Sec23p-Sfb2p heterodimer of the COPII vesicle coat; required for cargo selection during vesicle formation in ER to Golgi transport; 


this doesn't seem like a biological process, it appears to be a way of describing the MF of the cargo loaders?
Except here, the MF term "signal sequence binding" is used for the

**Comment by robnash** [comment]
Hi,

I guess it depends on whether binding to the targeting sequences is sufficient to define a protein as cargo? or whether there additonal steps required. If additional steps are not required maybe this could be redefined as an MF term. However, if this were changes it may have further ramifications as there is another "GO:0035652 cargo loading into clathrin-coated vesicle" also currently a process term.  If you want to check into the cargo regonition event further there is a comment in Cell:

http://www.yeastgenome.org/reference/S000074167/overview

that refes to two papers where they define the recognition event (Sec24p binding to sequences on the cargo proteins). Here they define seqeunces on the cargo proteins that are important. To further complicate things I am not sure that the current "GO:0005048 signal sequence binding" annotations for Sec24p, Sfb2p, and Sfb3p are correct, as I think this refers to the recognition event in co-translational insertion and passage of secretory proteins though the plasma membrane that involves the translocon complex as well as Sec62p and Sec63p, and summarized in this wiki page:

https://en.wikipedia.org/wiki/Signal_peptide
 
Sounds like according to the review I posted in the first response that there are some cargo proteins that bind directly to the coat proteins and some that require a receptor. Sec24p is stated to be the major component of COPII that interacts with transmembrane cargo proteins, and Sfb2p, and Sfb3p are paralogs hence the possibly incorrect ISS's to ss binding.

Of course the community contact that could straighten all of this out would be nobel prize winner Randy Schekman at Berkeley (http://mcb.berkeley.edu/labs/schekman/)

Sorry I do not have the full answer.

Cheers,
Rob

**Comment by ValWood** [comment]
action
COPII adaptor activity
COPII-associated vesicles transport proteins from the rough endoplasmic reticulum to the Golgi apparatus (anterograde transport). 

and  cargo receptor is defined
Combining selectively with an ****extracellular**** substance and delivering the substance into the cell via endocytosis

I don't know if it  should be, but based on this   COPII adaptor activity  could not have the parent I suggested.

Broaden def of Cargo receptor and add parent, or close?

**Comment by ValWood** [comment]
http://jcs.biologists.org/content/joces/124/1/1.full.pdf

**Comment by ValWood** [comment]
ERV29  FAMILY  IPR002995  Surfeit locus 4
SVP26   FAMILY  IPR007277 | Transmembrane adaptor Erv26

there does not seem to be a commonality

**Comment by ValWood** [comment]
Yeast has no annotated "cargo receptor"

**Comment by pgaudet** [comment]
probably needs a little refactoring. 
I propose creating a new term to group all vesicular transport receptors. 

See https://www.nature.com/articles/ncb2390

**Comment by pgaudet** [comment]
This terms refers to the 'adaptor', ie it's not a receptor. Its parent is 'protein binding, bridging' . 
The definition is 'The binding activity of a molecule that brings together the COPII vesicle proteins and one or more other molecules, permitting them to function in a coordinated way.' 

Probably what's missing is the fact that it binds a receptor. 

Pascale

**Comment by pgaudet** [comment]
Proposed definition: "Bringing together a cargo protein with the COPII coat complex component to allow its uptake by the COPII vesicle. " 

@ValWood does this clarify the definition ? 

Thanks, Pascale
