### ISSUE TITLE
new taxon restrictions for high level cellular component terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12690]
Add only in Plant (or organisms that do photosynthesis)
- [ ] GO:0042646    plastid nucleoid
- [ ] GO:0016028    rhabdomere 

The following have “only in cellular organisms, but should  be only in Metazoa? or even more restricted
- [ ] GO:0042151 nematocyst  (more specifically which have cnidoblast (nematoblast) 
- [ ] GO:0045170 spectrosome (more specifically  skeletal organisms)
- [ ] GO:0098593 goblet cell theca 
- [ ] GO:0098536 deuterosome  (should have same taxon restriction as centriole)
- [ ] GO:0043292 contractile fiber (is defined as a muscle fibre)
- [ ] GO:0097727 blepharoplast (or species with sperm cells)

I deleted duplicates and added check boxes to the terms below

**Comment by ValWood** [comment]
GO:0002102 podosome
I got stuck on this one, not sure which species it applies to, but it seems to be to do with
adhesion, and we don't have them in pombe or cerevisiae so I think for now we can say 

never_in_fingi (probably only_in_metazoa)?

**Comment by ValWood** [comment]
Never in Schizosaccharomyces
GO:0005933 cellular bud
GO:0000131 incipient cellular bud site

**Comment by ValWood** [comment]
The following have “only in cellular organisms, but should be 
only in Metazoa? or even more restricted?
never in fungi (definitely)

GO:0043209 myelin sheath
GO:0097223 sperm part
GO:0097458 neuron part
GO:0045178 basal part of cell
GO:0042470 melanosome
GO:0097413 Lewy body A(s defined, only in organisms with a nervous system)
GO:0097419 Pick body (sounds pathogenic)
GO:0097418 neurofibrillary tangle (sounds pathogenic ….. contain an abnormally phosphorylated form of a )

**Comment by ValWood** [comment]
Only in prokaryotes
GO:0043684 type IV secretion system complex
GO:0030256	type I protein secretion system complex	
GO:0098046	type V protein secretion system complex	
GO:0015627	type II protein secretion system complex	
GO:0033104	type VI protein secretion system complex	
GO:0030257	type III protein secretion system complex

**Comment by dosumis** [comment]
## These look like they belong in CC, will add:

Add only in Virusus
GO:0019012 virion

Add only in Prokaryotes
GO:0043590 bacterial nucleoid
GO:0009288 bacterial-type flagellum
GO:0031469 polyhedral organelle
GO:0030313 cell envelope

Add only in Giardia
GO:0097597 ventral disc

Never in Schizosaccharomyces
GO:0005933 cellular bud
GO:0000131 incipient cellular bud site

The following have “only in cellular organisms, but should be only in Metazoa? or even more restricted

GO:0098536 deuterosome (should have same taxon restriction as centriole)


Add only in plasmodium?
GO:0044312 crystalloid 
(or broader?)
Def "never in fungi"

Never in Schizosaccharomyces
GO:0044215 other organism

Add only in Prokaryotes
GO:0043590 bacterial nucleoid
GO:0009288 bacterial-type flagellum
GO:0031469 polyhedral organelle
GO:0030313 cell envelope

Add only in Giardia
GO:0097597 ventral disc

GO:0030054 cell junction

GO:0043684 type IV secretion system complex
GO:0030256 type I protein secretion system complex 
GO:0098046 type V protein secretion system complex 
GO:0015627 type II protein secretion system complex

GO:0033104 type VI protein secretion system complex

GO:0030257 type III protein secretion system complex

GO:0002102 podosome
I got stuck on this one, not sure which species it applies to, but it seems to be to do with
adhesion, and we don't have them in pombe or cerevisiae so I think for now we can say

never_in_fungi (probably only_in_metazoa)?  

### Probably can't add:

???? GO:0034357 photosynthetic membrane 

Because there is no general taxon to refer to.

### These should probably be inherited from CL or from CL->Uberon links

@cmungall  Do we have all the imports in place for this to work?


GO:0097458 neuron part
GO:0097223 sperm part  (???)

GO:0043209 myelin sheath
GO:0097223 sperm part
GO:0097458 neuron part
GO:0045178 basal part of cell
GO:0042470 melanosome
GO:0097413 Lewy body A(s defined, only in organisms with a nervous system)
GO:0097419 Pick body (sounds pathogenic)
GO:0097418 neurofibrillary tangle (sounds pathogenic ….. contain an abnormally phosphorylated form of a )
GO:0016028 rhabdomere
GO:0042151 nematocyst (more specifically which have cnidoblast (nematoblast) 
GO:0045170 spectrosome (more specifically skeletal organisms)
GO:0098593 goblet cell theca 

GO:0043292 contractile fiber (is defined as a muscle fibre ) # But should it be?
GO:0097727 blepharoplast (or species with sperm cells)

**Comment by ValWood** [comment]
GO:0034357 photosynthetic membrane
can add "never in fungi" "never in metazoa" ?

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,@dosumis, I'm confused:

"Add only in Giardia
GO:0097597 ventral disc"

This taxon constraint is already in place. Let me check the bacterial terms too...

**Comment by paolaroncaglia** [comment]
GO:0043590 bacterial nucleoid and GO:0009288 bacterial-type flagellum already are only in Bacteria.
Haven't checked the rest of the list. You might want to make sure there isn't a visualisation problem? Remember, AmiGO doesn't display taxon rules yet...

**Comment by ValWood** [comment]
I was using QuickGO to check these so not sure how I missed them. I will go back through the list now.
Val

**Comment by ValWood** [comment]
I did a clean up. I think the one with check boxes are the ones which need adding, plus the ones which should come from Uberon.

**Comment by dosumis** [comment]
Chosen mostly highly level restrictions for these:

- [x] GO:0097458 neuron part only_in_taxon Metazoa
- [x] GO:0043209 myelin sheath only_in_taxon Metazoa
- [x] GO:0097223 sperm part  - never_in_taxon Fungi Bacteria or Archea
- [x] GO:0097458 neuron part only_in_taxon Metazoa
- [x] GO:0045178 basal part of cell  - No restriction added.
- [x] GO:0042470 melanosome only_in_taxon Metazoa
- [x] GO:0097413 Lewy body A(s defined, only in organisms with a nervous system) only_in_taxon Metazoa
- [x] GO:0097419 Pick body (sounds pathogenic) only_in_taxon Metazoa (agree presence in GO is dodgy - need another general ticket on this if we want to tackle
- [x] GO:0097418 neurofibrillary tangle (sounds pathogenic ….. contain an abnormally phosphorylated form of a ) only_in_taxon Metazoa
- [x] GO:0016028 rhabdomere only_in_taxon Metazoa 
- [x] GO:0042151 nematocyst (more specifically which have cnidoblast (nematoblast) only_in_taxon Metazoa  (could probably restrict to cnidaria
- [x] GO:0045170 spectrosome (more specifically skeletal organisms) only_in_taxon Arthropoda (nothing to do with skeletons - it's a germline structure in arthropods)
- [x] GO:0098593 goblet cell theca only_in_taxon Metazoa
- [x] GO:0043292 contractile fiber (is defined as a muscle fibre ) # But should it be? - ignored this one.  Another ticket needed to discuss location of term in heirarchy.
- [x] GO:0097727 blepharoplast (or species with sperm cells) # Already has a bunch of taxon restrictions.  Have not added more.

**Comment by ValWood** [comment]
Thankyou :)

**Comment by srengel** [comment]
something went wrong with this.  we just got a ton of errors for SGD annotations now violating taxon_constraints. 

looks like these (and children) were given 'never_in_taxon Saccharomyces' by mistake:

Never in Schizosaccharomyces
 GO:0005933 cellular bud
 GO:0000131 incipient cellular bud site

**Comment by dosumis** [comment]
Ooops.  Sorry!  Was meant to be Schizosaccharomyces!  Now fixed.

**Comment by srengel** [comment]
thanks David :)

**Comment by dosumis** [comment]
Note: also removed taxon restriction on provirus.  This was causing TG failure due to an axiom coming from Uberon.  Ticket here: https://github.com/obophenotype/uberon/issues/1297  General issue for taxon restrictions referencing viruses.
