### ISSUE TITLE
presynaptic active zone assembly - missing parent?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#12697]
Hi 

Shouldn't presynaptic active zone assembly have the part_of parent GO:0099054 presynapse assembly?

BTW I think that the terms need to state more clearly what a presynaptic active zone is, in the BP terms, not just in the CC terms. for example in synapse organization it states: synapse, the junction between a neuron and a target (neuron, muscle, or secretory cell). but the presynaptic active zone organization term doesn't include the CC definition.

Thanks

Ruth 

@dosumis @geneontology/synapse

**Comment by ValWood** [comment]
This raises a question about how much of a term which is already defined should be in the definition of a term in which it is subsequently used. I can see there are cases when it is useful for curators to see, but often including other definitions in there entirety is impractical. Are there any editorial guidelines for this or does it depend on context?  Could logical definitions be leveraged more in this respect? (I have no idea, but I often feel that sometimes more info in the def  would be useful, so that I don't need to check the definitions of terms used in the definitions. Other times  there is too much gloss.

**Comment by dosumis** [comment]
> Shouldn't presynaptic active zone assembly have the part_of parent GO:0099054 presynapse assembly?

Fixed

We have a plan to infer partonomy for this branch: https://github.com/geneontology/go-ontology/issues/12658 .  Should mean we can avoid this issue in future.

> This raises a question about how much of a term which is already defined should be in the definition of a term in which it is subsequently used.

Definitely an overhead for development - especially when definitions are evolving.  I doubt most editors look up all related terms that might quote a definition when they change one, so they'll almost certainly go out of sync.  A browser that shows more relationships could help curators here - then the CC term would be one click away. 

> Could logical definitions be leveraged more in this respect?

Potentially.  If we can switch to [dynamic generation of these terms](https://github.com/geneontology/design_patterns/issues/7), we could import the CC definition into the assembly term def.

**Comment by ValWood** [comment]
That would be nice. I'm sure definition changes rarely get propagated to all of the term defs  they are represented in...
