### ISSUE TITLE
GO:0007067 mitotic nuclear division

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12698]
just spotted this def is missing something:

A cell cycle process comprising the steps by which the nucleus of a eukaryotic cell divides; the process involves condensation of chromosomal DNA into a highly compacted form. Canonically, mitosis produces two daughter nuclei whose chromosome complement is identical to that of the mother cell.

It   should be "mitotic cell cycle process"
The def is a bit strange anyway. I'm not sure why it specifically mentions  only DNA condensation?

It could say that it begins with DNA condensation? 
If so could we also add an end?  
The end needs to work for open and closed mitosis, so something like:
"When each daughter nucleus is enclosed by the  nuclear envelope"?

**Comment by ukemi** [comment]
Hi Val,

I modified the def to make is a mitotic cell cycle process, which will be inferred from the reasoner. I didn't modify the rest of the definition because it is just gloss. The new text def is necessary and sufficient:
A mitotic cell cycle process comprising the steps by which the nucleus of a eukaryotic cell divides

The condensation part of the definition is just gloss just says it is a necessary part of the process. 

-D

**Comment by ValWood** [comment]
Don't we want the "start" and "end" to replace "gloss"
