### ISSUE TITLE
GO:0071204 histone pre-mRNA 3'end processing complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12700]
This does not seem to be an indepent complex?
GO:0071204 histone pre-mRNA 3'end processing complex

Isn't it a  just a function of the  U7 snRNP?

**Comment by ukemi** [comment]
According to the paper used as the definition xref (PMID:19470752) the U7 snRNP is part of the end processing complex. I could make a has_part relation between the processing complex and the RNP. I'm not sure part of is appropriate because a quick literature search suggests that the RNP may be involved in other processes.

What do you think?

**Comment by ValWood** [comment]
OK its probably OK. I thought there was a general complex but maybe it is specific for histones. Will close.
