### ISSUE TITLE
deoxyhypusine synthesis terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12723]
Are these equivalent?
GO:0050983 - deoxyhypusine biosynthetic process from spermidine
The chemical reactions resulting in the formation of deoxyhypusine from spermidine by the enzyme [eIF-5A]-deoxyhypusine synthase. The reaction occurs in four steps: 1. spermidine + NAD+ = dehydrospermidine + NADH + H+; 2. dehydrospermidine + [enzyme]-lysine = 1,3-diaminopropane + [enzyme]-lysine-N6=CH(CH2)3NH2; 3. [enzyme]-lysine-N6=CH(CH2)3NH2 = [eIF-5A]-lysine-N6=CH(CH2)3NH2; 4. [eIF-5A]-lysine-N6=CH(CH2)3NH2 + NADH + H+ = [eIF-5A]-deoxyhypusine + NAD+."

and
GO:0008612 - peptidyl-lysine modification to peptidyl-hypusine 
The modification of peptidyl-lysine to form hypusine, peptidyl-N6-(4-amino-2-hydroxybutyl)-L-lysine."

?

They don't appear to be related, I think they probably should be if they are not equivalent?

**Comment by ValWood** [comment]
This is the function term:
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0034038

**Comment by deustp01** [comment]
Here's the biochemistry lecture, annotated by me working from detailed comments from H E Johansson, who worked out the pathway (http://www.reactome.org/PathwayBrowser/#/R-HSA-163841&SEL=R-HSA-204626&PATH=R-HSA-392499,R-HSA-597592). As far as I know, hypusine is only found as the product of a post-translational modification of a lysine residue in the eukaryotic initiation factor eIF5A. It's not made as a free small molecule (no idea whether trace amounts could be released by degradation of modified eIF5A molecules). Hypusine synthesis proceeds in two steps. In the first, molecules of eIF5A protein and spermidine react to form molecules of eIF5A with an L-deoxyhypusine replacing the lysis encoded at position 50 (human numbering) of the eIF5A protein and 1,3-diaminopropane. This reaction is reversible so in isolation it could look like it's consuming the two products to form spermidine and unmodified eIF5A. A second, physiologically irreversible reaction, the L-deoxyhypusine from of eIF5A reacts with one molecule of oxygen to convert the L-deoxyhypusine residue to a hypusine residue. The are literature references attached to the Reactome annotations for the pathway and its reactions.

If this is right, then there's no physiological process that forms the free molecule hypusine (or L-deoxyhypusine) from spermidine. Rather, hypusine goes in the same place as other covalent modifications of lysine residues in situ in proteins.

**Comment by cerivs** [comment]
Hi Val,
PMID  26299433  discusses deoxyhypusine synthase and some inhibitors.

**Comment by ValWood** [comment]
I thought so... it seems that some sort of merge  is required?

This is the other GO activity
GO:0019135 - deoxyhypusine monooxygenase activity 
so both of these could probably have part_of links to the process term?

**Comment by ValWood** [comment]
The  Reactome browser is very cool....

**Comment by mcourtot** [comment]
I checked the reference on GO:0008612 - peptidyl-lysine modification to peptidyl-hypusine, ISBN:0198547684 which is the Oxford Dictionary of biochemistry and molecular biology. The hypusine entry indeed refers to the PTM of a lysine residue of eIF-5A and doesn't mention anything else.

Would it work to add part of relationships:
GO:0050983 - deoxyhypusine biosynthetic process from spermidine
part_of GO:0050983 - deoxyhypusine biosynthetic process from spermidine.

GO:0019135 - deoxyhypusine monooxygenase activity 
part_of GO:0050983 - deoxyhypusine biosynthetic process from spermidine?

**Comment by ValWood** [comment]
The question is initially about the 2 process terms,
GO:0050983 - deoxyhypusine biosynthetic process from spermidine
GO:0008612 - peptidyl-lysine modification to peptidyl-hypusine 

and if they should be merged.
The 2 MF terms can have F-P part_of links to   the single term, or whichever is the more specific.

**Comment by ValWood** [comment]
It seems that this should use the MF term
GO:0034038 deoxyhypusine synthase activity (see above)

The BP  doesn't mean the same as the  MF whatever happens with the merge.
I think it would be good to check with Nidhi

**Comment by deustp01** [comment]
The "from spermidine" part works in the same sense that a phosphorylation process could have a "from ATP" part - it's a required input even if it's not the famous one.

**Comment by mcourtot** [comment]
Hi @deustp01, I had a talk with @ukemi, and we were wondering if the first part of the reaction, lysine + spermidine -> deoxyhypusine is ever expected to be reversible *physiologically*. In the pathway browser it seems to go both way, but is there ever the case that this happens physiologically and the process GO:0008612 - peptidyl-lysine modification to peptidyl-hypusine stops at the deoxyhypusine step?

**Comment by deustp01** [comment]
The notes provided by the outside expert who worked with us on this pathway actually did not mention a reverse reaction so I will go back to the hard-core enzymology papers we found to see what they say. It could indeed be a purely _in vitro_ phenomenon or a mis-reading. I'll let you know.

**Comment by mcourtot** [comment]
Thanks @deustp01, very much appreciated.

**Comment by ukemi** [comment]
Aside from the reversibility of DHS activity, these are the issues with respect to this ticket:

1) Although GO:0050983 is described as a multistep process, the entire reaction is carried out by a single enzyme, therefore we would define it as a molecular function. The level of deconstruction of molecular functions in GO is at the level of the gene product. Multi-step mechanisms carried out by a single enzyme in all known organisms generally do not warrant the creation of multiple MF terms. The exception to this is in the creation of LEGO models, where elemental mechanisms such as binding can be modeled as part of a process. The 'reaction/process' named in GO:0050983 is the same as the forward reaction of DHS even though the definition shows it as reversible. There are three possibilities for this term: a) Merge the process term into the enzyme term. I believe we have done this in the past but I am not sure if it breaks any of our current rules. b) Re-categorize the term as a child of the DHS activity representing the forward reaction. I'm also not sure if moving an identifier from BP to MF breaks any rules. c) Merge the term into the lysine modification process because it represents a subset of the steps in the process. 

2) Whether or not the reactions are reversible will determine how to define this pathway in the way that Peter and I have worked out and whether or not the enzyme activities can be made part_of the modification process. Melanie pointed out that this modification takes place in archae, but the DOHH enzyme is likely missing (PMID:23167813). This brings up an interesting precedence for ontology development. Since the activity that does the conversion is unknown, do we assume that it exists and is not DOHH activity?  If that is the case, we cannot make the DOHH activity a necessary part of the modification process. Does the absence of data count?

**Comment by ValWood** [comment]
I have  2 gene products annotated to
 GO:0008612 - peptidyl-lysine modification to peptidyl-hypusine 

The other one is ISS to:
http://www.yeastgenome.org/locus/S000003831/overview#go
Deoxyhypusine hydroxylase; HEAT-repeat containing metalloenzyme that catalyzes hypusine formation;

But this sounds odd, HEAT repeats don't have catalytic activity, and there doesn't seem room for any other domain?

**Comment by ValWood** [comment]
> This brings up an interesting precedence for ontology development. Since the activity that does the conversion is unknown, do we assume that it exists and is not DOHH activity? If that is the case, we cannot make the DOHH activity a necessary part of the modification process. Does the absence of data count?

I would take this to mean that the activity is likely to be  present, but they don't know which  gene product catalyses it..... They  are really only saying here that they can't identify a DOOH homolog by sequence.  I would say you could say it was necessary until biology showed otherwise....

**Comment by mcourtot** [comment]
I'm not sure. The extract reads "In Archaea, DHS homologs are widespread, suggesting the lysine residue of aIF5A is modified to a deoxyhypusine residue by an enzyme similar to eukaryotic DHS. In contrast, DOHH is an oxygen-dependent enzyme and its homologs are rare in (the often anaerobic) Archaea. Thus, generation of the hypusine-modified form of aIF5A from its deoxyhypusine precursor likely involves a second enzyme distinct from DOHH in Archaea.” The `likely` seem to take into account both the lack of homolog and the anaerobic organism.

**Comment by mcourtot** [comment]
Re structure of DOOH, I found this, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2494880/#S6title, which seems to support that deoxyhypusine hydroxylase is a HEAT-repeat protein.

**Comment by ValWood** [comment]
I think it all hinges on this paper:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1324997/
I'm not totally sure that this doesn't rule out this being the regulatory subunit  but required only for DOOH, Peter what do you think?
I can't figure out what they did completely, did they see DOOH activity from purified YJR070C
alone? The rest of the experiments are mutant phenotypes..... This is the only paper I can find with an "assay".

Does anyone know of any other HEAT repeats with enzyme activity? they often have another domain with a catalytic role, but i  haven't come across and  proteins with a catalytic activity assigned to the repeat regions in 20 years....Although of course this could of course be a special case? It's raising a red flag for me....

**Comment by ValWood** [comment]
Sorry I mean DOHH above

**Comment by ukemi** [comment]
Val,

Is this an annotation question? There is nothing about HEAT domains in the ontology. This ticket is about the structure of the ontology surrounding 'peptidyl-lysine modification to peptidyl-hypusine '.

**Comment by ValWood** [comment]
Well fundamentally it is an annotation question.  But I'm trying to figure out if there are really 2 activities encoded by 2 different gene products, or one gene encoding both activities with a regulatory subunit. It might help to answer the question about why the "presumed" DOHH is apparently absent from Archaea...which is  directly related to your comment:

> This brings up an interesting precedence for ontology development.

The single paper that I can find providing  evidence for the HEAT repeat protein encoding DOHH  could be otherwise interpreted I think. I'd be interested whether Peter agrees. In fission yeast we have 40 HEAT repeat proteins, mainly regulatory subunits or interaction modules of some description. This is the only on with a catalytic activity assigned.

I can migrate this part of the ticket to the annotation tracker.

**Comment by ukemi** [comment]
Ah ok. I see what you are getting at now.

**Comment by ValWood** [comment]
I'm not disputing whether its a HEAT repeat  protein (if that wasn't clear), I'm disputing the validity of the  MF information....BUT, it isn't completely clear to me what they did in the single  paper which assigns the DOHH activity. It's interesting....

**Comment by ValWood** [comment]
I found another paper reporting that reported DOHH *is*  GO:0019135 - deoxyhypusine monooxygenase activity, (Leishmania), 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3306375/
This isn't GO annotated..... I was looking for HEAT repeat domains with catalytic activity using PubMed, .....but again I'm not sure- if I understood correctly the experiment appears to be performed in the presence of the DHS?

Another thing I find odd, if the modification is essential, with 2 steps,  why the DOOH is non-essential in pombe and cerevisiae (the DHS is essential for both).

**Comment by deustp01** [comment]
Start with a combination of David's comment 12 Oct 8:35 PM EDT ("Aside from the reversibility of DHS activity, these are the issues with respect to this ticket ...") and Val's comment 13 Oct 8:40 AM EDT ("I think it all hinges on this paper ...").

Val's paper describes the cloning of a yeast (cerevisiae) gene and its human homolog. Each was over-expressed in E. coli (useful, as E. coli lacks EIF5A protein and enzymes capable of converting lysine residues to deoxyhypusine or hypusine). According to the methods section of the paper, the assay for activity of the recombinant enzymes used EIF5A protein containing a deoxyhypusine modified residue as substrate and monitored the appearance of hypusine in an acid hydrolysate of assay products. The results section (Figure 3) shows recovery and partial purification of recombinant proteins, both GST-tagged and untagged after thrombin treatment, and both protein preparations catalyze hypusine formation in a dose-dependent manner. I guess this result could be explained if the recombinant proteins bound to a bacterial DHS and modified its previous activity, but there's no evidence that eubacteria have DHS enzymes.

It is odd (Val's point in her last comment) that cerevisiae and pombe strains that lack DOOH activity are viable, with almost no phenotype in culture. Can yeast EIF5A carry out its function, whatever that is, with only a deoxyhypusine modification instead of a hypusine modification? And perhaps those Archaea that appear to lack DOOH?

It is also odd that the putative yeast and human DOOH enzymes have multiple HEAT domains, not a textbook feature of hydroxylase / monooxygenase enzymes, but that's still what the experimental data say, and that is certainly how the authors of Val's paper interpret the results (see also https://www.ncbi.nlm.nih.gov/pubmed/?term=16452303 for more discussion from the same group). They also clearly view hypusine formation as proceeding in two steps distinguished by the formation of a stable intermediate and by the requirement for quite distinct molecular functions to carry them out.

Reversibility of the reactions: I've dug some more and in addition to the review (PMID:1654203) cited in the previous paragraph, here's a paper with experimental data - https://www.ncbi.nlm.nih.gov/pubmed/12788913?dopt=Abstract - to show that the first step, formation of a deoxyhypusine residue on EIF5A, is reversible in vitro. These authors also make indirect arguments that the second step, from deoxyhypusine to hypusine, is irreversible. There are no arguments and no data about whether the first reaction is reversible in vivo. Who knows? Depending on the relative rates of the reverse first reaction and the forward second reaction, and the physiological concentrations of participating molecules, it may be the cae that as fast as deoxyhypusine is generated it's converted onwards to hypusine. Then again, maybe not.

**Comment by ukemi** [comment]
Hi Peter et al, 

I agree completely with your interpretation of the paper that Val referenced. We should believe a direct assay for the conversion in the presence of a cloned enzyme. I think the DOHH is definitely a valid molecular function. Its absence in archae and the fact that it is non-essential in some other organisms doesn't support that it doesn't exist. You also point out valid alternatives for the lack of requirement. 

So I think we can assume that when the activity exists, it is part of the modification process. However, the archae data shows that it is not a necessary part. The forward direction of the DHS activity is a necessary part of the activity. These are conservative assertions. 

So now we are left with what do we do with GO:0050983, merge into the function, reclassify or merge into the process?

-D

**Comment by ValWood** [comment]
Sounds good. Apologies for the wild goose chase.  This is clearly a novel iron binding HEAT repeat. As I read more about the role of HEAT repeats as regulators most mechanistic detail points to a role in HEAT repeats inducing a conformational change so it is easier to see how this could catalyse further modification the eF5A lysine.

Thanks!

**Comment by mcourtot** [comment]
I think the merge into the function makes the most sense. We don't know whether it is reversible or not, but we know it is a single gene product, so MF seems right.

**Comment by ukemi** [comment]
If it doesn't break anything making a process identifier become a secondary identifier for a function, this makes sense. @tberardini or @cmungall can you remember if we have done this in the past with no bad consequences? I seem to recall we have, but may be mistaken. For groups who still consider the ontology to be three separate ontologies, they might see an identifier disappear from process.

**Comment by tberardini** [comment]
Unfortunately, I can't find any such cases of merging a BP into an MF.  I thought that we might have merged some MFs into BPs, like  'transcription regulator activity' into 'regulation of transcription' (and 'transcription activator' into 'positive regulation of tsc') but that's not the case, we use the BP term as a consider option for the obsoleted MF term. So, I don't know if there will be bad downstream effects of a 'cross-ontology' merge.

**Comment by ukemi** [comment]
Thanks Tanya. I thought we had done cross-ontology merges too, but couldn't remember the details. I am a bit concerned it will break some peoples' tools.  Maybe it would be best to just merge the processes.

**Comment by ValWood** [comment]
There are only 10 EXP annotations (and one of those incorrect its the elongation factor). Why not obsolete so people have the opportunity to make the MF annotation if they didn't already?

(also, a lot of IBA annotations so @pgaudet  might want to remove from  or fix PAINT families)

**Comment by ukemi** [comment]
Good idea.

**Comment by ValWood** [comment]
Nothing can go wrong ;)

**Comment by mcourtot** [comment]
In summary:
- [ ] Send an obsoletion email for  GO:0050983	deoxyhypusine biosynthetic process from spermidine
- [ ] Add GO:0034038 as a consider term on this obsoleted term

**Comment by mcourtot** [comment]
Obsoletion email sent with deadline Nov 1.

**Comment by pgaudet** [comment]
For PAINT it shoudn't be a problem - if the primary annotations are removed the IBAs will be automatically removed (well, if all the scripts work). 

Thanks for bringing that up !

**Comment by mcourtot** [comment]
Obsoletion done.
