### ISSUE TITLE
possible term merge

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12734]
I'd like to suggest that we obsolete this term, or merge into its parent.

GO:0001214 RNA polymerase II transcriptional repressor activity, metal ion regulated core promoter proximal region sequence-specific binding

Only one EXP annotation form PomBase.

I don't think this term should have been requested because it includes information about the DNA-binding region with the transcription factor activity (rather than the DNA-binding term)

We don't need this term, becasue this is already captured appropriately on the DNA binding term, using extensions see:
http://www.pombase.org/spombe/result/SPAC23E2.01#go-molecular_function

Its probably better to get rid of it as it's not quite right @ukemi  do you agree?

Val

**Comment by ukemi** [comment]
@krchristie can you have a look since this is transcription-related?

**Comment by ValWood** [comment]
ACtually, my rationale was incorrect,  but we could do this in a more consistent (and specific)  way with involved in "cellular response to iron". In fact this is how we have don this for all other metal ion regulated transcription factors. It seems unnecessary functional detail to build what specifically regulates the transcription factor into the MF term?

**Comment by krchristie** [comment]
The logic at the time was to represent the distinct things we know about the mechanism of action, i.e. specific kinds of "DNA binding", certain kinds of protein binding like "transcription factor binding" or "RNA polymerase binding", or in this case "metal ion binding". Thus these terms are separate because they incorporate additional has_part relationships to terms like "metal ion binding", and more specifically "copper ion binding" or "zinc ion binding".

These are very granular terms so I don't think I'd ever expect to have a lot of annotations to them. However, I think they do capture something that is not captured with only a process annotation since the MF terms specifically indicate the requirement for the metal ion binding, not just the involvement in a "cellular response to x" term.

So that's the logic behind them.  

@ukemi - I'll leave it to you to decide if the logic of these terms is still within what's considered appropriate within the current philosophy on ontology development.

-Karen

**Comment by ukemi** [comment]
Will leave these for now.
