### ISSUE TITLE
NTR: substrate mycelium formation

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12742]
'Substrate mycelium formation' is an additional specific term, along with 'aerial mycelium formation' (#12659) and 'acquisition of mycelium reproductive competence'  (#12660) that can be used to replace the ambiguous term  'mycelium development' (#12613) which has been proposed for obsoletion.

NTR: 'substrate mycelium formation'
This process of growth occurs in some fungal species that grow as network of invasive thread-like filaments formed from chains of attached cells within a solid or semi-solid substrate.

**Comment by paolaroncaglia** [comment]
Hi @dianeoinglis ,
I added as follows, please see below for questions:

 [Term]
+id: GO:0097738
+name: substrate mycelium formation
+namespace: biological_process
+def: "The process by which, in some fungal species, hyphae grow as a network of invasive thread-like filaments formed from chains of attached cells within a solid or semi-solid substrate." [GOC:di]
+is_a: GO:0019954 ! asexual reproduction
+is_a: GO:0048856 ! anatomical structure development
+relationship: only_in_taxon NCBITaxon_Union:0000020 ! Fungi or Bacteria

Questions:

- [ ] Please provide a PMID or other reference

- [ ] Are both is_a parents correct? In particular, should ‘substrate mycelium formation’ be is_a ‘anatomical structure formation involved in morphogenesis’ instead of ‘anatomical structure development’?

- [ ] Is the taxon rule ok as is, or should it be only in Fungi? Based on your suggested definition.

Thanks.

**Comment by paolaroncaglia** [comment]
@dianeoinglis 
Lastly, when you create the FAO term for ‘substrate mycelium’, please post its ID here, and

- [ ] I will add a logical axiom to GO:0097738 ‘substrate mycelium formation’.

**Comment by fusarium** [comment]
PMID: 10021365 for  ‘substrate mycelium formation’ 

Beneath seems all correct:
+is_a: GO:0019954 ! asexual reproduction
+is_a: GO:0048856 ! anatomical structure development
+relationship: only_in_taxon NCBITaxon_Union:0000020 ! Fungi or Bacteria

**Comment by paolaroncaglia** [comment]
Thanks @fusarium

**Comment by paolaroncaglia** [comment]
Wrapping up this ticket, the only action item left to do is
- [ ] when a FAO term is created for ‘substrate mycelium’, use its ID to add a logical axiom to GO:0097738 ‘substrate mycelium formation’.

**Comment by paolaroncaglia** [comment]
Hi @ukemi,
I’ve completed my tasks for this ticket, and the only thing left to do (low priority) is to add a logical definition if/when a FAO term is created (details above). Therefore I will now unassign myself from this ticket. However, since unassigned tickets tend to fall through the cracks when they’re not recent, I will assign it to you (as main ontology editor at this stage), and you can then hand it over to others if and as appropriate. Thanks.

**Comment by ukemi** [comment]
I still don't see this term in the FAO. @dianeoinglis do you know when it will be added?

**Comment by dianeoinglis** [comment]
The FAO will undergo a major revision as soon as some basic numbering issues are resolved. Hopefully before end of March 2018.
Thanks!

**Comment by pgaudet** [comment]
@mah11 can this term added to FAO ? 

Thanks, Pascale

**Comment by mah11** [comment]
it's on the to-do list ...
https://github.com/obophenotype/fungal-anatomy-ontology/issues/12
