### ISSUE TITLE
NTR: "anatomical structure formation involved in reproduction (asexual and sexual) for conidium formation relationship

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#12745]
For some reason...sleepiness perhaps...I added this request to the FAO tracker but the GO tracker is more appropriate.

GO:0048646 "conidium formation" has is_a "anatomical structure formation involved in morphogenesis," but "morphogenesis" (change in cell shape) is not the goal of this process. Additionally, there are no cells that change shape rather this is an organismal process where a population of cells form new cells with a different shape. The new term "anatomical structure formation involved in asexual reproduction" should be created and replace the "anatomical structure formation involved in morphogenesis" term that is currently an "is_a" term for conidium formation. "Anatomical structure formation involved in sexual reproduction" should also be created as well as a parent term "anatomical structure formation involved in reproduction."

Terms requested:
"anatomical structure formation involved in reproduction" (parent)
"anatomical structure formation involved in asexual reproduction"
"anatomical structure formation involved in sexual reproduction"

**Comment by paolaroncaglia** [comment]
Hi @dianeoinglis ,
FYI, I haven’t had a chance to work on this ticket until now, and I’ll be on leave next week. Thanks for your patience.

**Comment by dianeoinglis** [comment]
One week won't cause any disasters. Have a nice time next week!

**Comment by paolaroncaglia** [comment]
Hi @dianeoinglis ,

Thanks for waiting.

I’m happy to remove the reference to ‘morphogenesis’ by deleting the link "conidium formation" is_a "anatomical structure formation involved in morphogenesis”.
However, there would be a conceptual problem with making "conidium formation" is_a "anatomical structure formation involved in asexual reproduction”, because “conidium formation” already is_a “asexual sporulation” (which itself is_a “asexual reproduction”). “asexual sporulation” is defined as “The *formation* of spores derived from the products of mitosis. Examples of this process are found in Bacterial species.”, so I think that the link “conidium formation” is_a “asexual sporulation” should stay. If we added is_a "anatomical structure formation involved in asexual reproduction”, we would be linking the same term to “asexual reproduction” via both is_a and part_of; it should be one or the other. And we wouldn’t want to reinstate “anatomical structure formation” (it was obsoleted with a comment ”The reason for obsoletion is that the term is confusing - it sounds developmental and has a developmental sounding def, but it is not a child of developmental process and its children included 'cellular component assembly'. The term was created to group together 'cellular component assembly' and 'anatomical structure formation involved in morphogenesis', but we no longer feel that this grouping is useful.”).

“conidium formation” is already linked up to “anatomical structure development” anyway. So, if you want I can delete the link "conidium formation" is_a "anatomical structure formation involved in morphogenesis”, but I’d rather not create the new terms
"anatomical structure formation involved in reproduction" (parent)
"anatomical structure formation involved in asexual reproduction"
"anatomical structure formation involved in sexual reproduction”.

**Comment by dianeoinglis** [comment]
Unlinking the "...morphogenesis" term is the key. If no new terms are needed, so be it!

**Comment by paolaroncaglia** [comment]
Note for self:
GO:0048646 ! anatomical structure formation involved in morphogenesis
is also used in the logical def of this term:
intersection_of: GO:0048646 ! anatomical structure formation involved in morphogenesis
intersection_of: results_in_formation_of CL:0000599 ! conidium
intersection_of: results_in_formation_of FAO:0000024 ! conidium
AI: see if I can replace it with another term

**Comment by paolaroncaglia** [comment]
Done (deleted link "conidium formation" is_a "anatomical structure formation involved in morphogenesis”, and relevant logical def).
