### ISSUE TITLE
OTR: GO:0045005 (DNA-dependent DNA replication maintenance of fidelity)

### ISSUE THREAD

**Issue by ethanclary143** [geneontology/go-ontology#12749]
I am a CACAO student and I noticed that some of the child terms for GO:0045005 (DNA-dependent DNA replication maintenance of fidelity) did not quite coincide with its definition, DEF: “A DNA metabolic process that prevents or corrects errors to ensure that DNA is replicated accurately. Errors can be corrected either by intrinsic DNA polymerase proofreading activity or via mismatch repair”. One such case being GO:0043111 (replication fork arrest), DEF: “Any process that stops, prevents, or reduces the frequency, rate or extent of DNA replication by impeding the progress of the DNA replication fork”. I am unsure that GO:0043111 (replication fork arrest),  always relates to maintenance of fidelity and am unsure that everything that applies to the replication fork arrest term will also apply to the maintenance of fidelity term. I would like to suggest modifying the relationship to some of the child terms of  GO:0045005 (DNA-dependent DNA replication maintenance of fidelity).

**Comment by paolaroncaglia** [comment]
Dear ethanclary143 (and @mah11 and @ValWood),

Thank you for your feedback on this branch of the ontology. Text definitions of GO terms do not always openly refer to (all of) their parents. In fact, these days we try to keep text definitions (as opposed to logical, axiomatised definitions) as simple as possible. I believe that the rationale for GO:0043111 (replication fork arrest) being is_a GO:0045005 (DNA-dependent DNA replication maintenance of fidelity) is the following: the replication fork arrest is a quality control process that ensures that DNA-dependent DNA replication occurs correctly. There are other quality control processes that contribute to the same result (as the def. of GO:0045005 mentions). ‘DNA-dependent DNA replication maintenance of fidelity’ is a quality control process itself. ‘replication fork arrest’ is short for ‘DNA replication fork arrest (during DNA-dependent DNA replication)’ and I do not know of other cases where this arrest would occur outside of cases where a replication error needs to be prevented or corrected. @mah11 and @ValWood, asking you as GO:0045005 has your initials on - could you confirm this please?
If I’m reading this correctly, then GO:0043111 (replication fork arrest) should continue to be is_a GO:0045005 (DNA-dependent DNA replication maintenance of fidelity) rather than, e.g., a part_of it. This may sound like a fine line, but I think it’s correct in this case. If you still think that this is confusing, maybe we could add a definition comment to ‘replication fork arrest’.

**Comment by mah11** [comment]
I don't know why my initials are on the GO:0045005 def, but what Paola says here makes sense to me.

**Comment by paolaroncaglia** [comment]
@mah11 Thank you for confirming.

**Comment by paolaroncaglia** [comment]
@ethanclary143 
I modified the definition of ‘replication fork arrest’ to make it clearer, as follows:

old definition:
-def: "Any process that stops, prevents, or reduces the frequency, rate or extent of DNA replication by impeding the progress of the DNA replication fork." [GOC:jl, PMID:14645529]

new definition:
+def: "Any process that stops, prevents, or reduces the frequency, rate or extent of DNA replication by impeding the progress of the DNA replication fork. Replication fork arrest is one of the 'quality control' processes ensuring that DNA-dependent DNA replication occurs correctly. DNA replication fork arrest during DNA-dependent DNA replication is not known to occur outside of cases where a replication error needs to be prevented or corrected." [GOC:jl, GOC:pr, PMID:14645529]

Closing this ticket now.
