### ISSUE TITLE
NTR: tRNA 5'-end processing / children of RNA repair? / 3′-5′ RNA polymerase activity

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#12756]
I have several papers about 4 Dicty 3′-5′ RNA polymerases that describe different functions for each. One is Dicty Thg1, which has the same tRNA guanylyltransferase activity (GO:0008193) as yeast THG1. The other 3, Tlp2-4 (Thg1- Like Proteins) also have 3′-5′ RNA polymerase activity (no such term in GO), but each acts differently (PMID:27484477, also PMID:26143376, PMID: 21307182)
- Tlp2: catalyzes a mitochondria-specific tRNAHis maturation reaction, which is distinct from the tRNAHis maturation reaction typically catalyzed by Thg1 on cytosolic tRNA.
- Tlp3: catalyzes tRNA repair during mitochondrial tRNA 5′-editing in vivo and in vitro showing 3′-5′ RNA polymerase activity of TLPs as a bona fide biological activity.
- Tlp4: cytosolic, and catalyzes robust 3′-5′ polymerase activity on non-tRNA substrates (other ncRNAs).

A) New terms:

1) tRNA 5'-end processing / mitochondrial  tRNA 5'-end processing
. . <- GO:0090646 tRNA processing
. . . <- GO:1990180 mitochondrial tRNA 3'-end processing
. . . <- **GO:New: mitochondrial tRNA 5'-end processing**

2) Children of RNA repair (suggested, can be discussed if specific 5' terms are necessary in conjunction with other terms)
. . <- GO:0042245 RNA repair
. . . <- **GO:New: tRNA repair**
. . . . <- **GO:New: mitochondrial tRNA repair**

3) 3′-5′ RNA polymerase activity  - all DNA/RNA polymerase/transcription activity by default is 3' → 5' , so not sure what parentage could be, certainly not regular transcription, RNA-templated - maybe even up to RNA metabolic process?
. . <- **GO:New: 3′-5′ RNA polymerase activity**

Thanks! 
Petra

**Comment by krchristie** [comment]
HI Petra,

For your #3, it looks like your are suggesting an MF term for "3′-5′ RNA polymerase activity", but the possible parent terms you are talking about, e.g. "transcription, RNA-templated" are BP terms.

Whether an MF term for  "3′-5′ RNA polymerase activity" can go under one of the existing MF terms (two relevant term defs included below) depends on whether it would fit within the definitions of the reactions. Here are two existing term definitions:

* "**RNA polymerase activity**" (GO:0034062) - 
Def: Catalysis of the reaction: nucleoside triphosphate + RNA(n) = diphosphate + RNA(n+1); the synthesis of RNA from ribonucleotide triphosphates in the presence of a nucleic acid template.
* "**DNA-directed RNA polymerase activity**" (GO:0003899) - 
Def: Catalysis of the reaction: nucleoside triphosphate + RNA(n) = diphosphate + RNA(n+1). Utilizes a DNA template, i.e. the catalysis of DNA-template-directed extension of the 3'-end of an RNA strand by one nucleotide at a time. Can initiate a chain 'de novo'.

The current definition of "**RNA polymerase activity**" does not appear to specify directionality of the reaction, but I don't know enough about the 3'-5' RNAP activity to be able to say if it fits into this definition. A brief skim of the Jackman et al review suggests to me that the reactions of the 5'-3' and 3'-5' RNA polymerases are largely similar, though it also mentioned that some of these 3'-5' RNA polymerases can use an "activated substrate" that has a triphosphate at the 5' end don't require an exogenous ATP. That might suggest a need to expand the definition of "RNA polymerase activity".

In contrast, the definition of "**DNA-directed RNA polymerase activity**" DOES specify extension of the 3'-end of an RNA strand. [Perhaps adding 5'-3' to the term name would be useful.]

If the current definition of "**RNA polymerase activity**" (GO:0034062) is broad enough for these 3'-5' RNAP activities, then it seems we could create your suggested new MF term under this parent. 

However, also take a look at the existing term "**tRNA nucleotidyltransferase activity**" (GO:0009022) to see if this is already pretty much what you want. It might be that we need to do is adjust the definition and parentage of this term, rather than create a new term.

-Karen


Jackman JE, Gott JM, Gray MW. Doing it in reverse: 3'-to-5' polymerization by 
the Thg1 superfamily. RNA. 2012 May;18(5):886-99. doi: 10.1261/rna.032300.112.
Epub 2012 Mar 28. Review. PubMed PMID: 22456265

**Comment by pfey03** [comment]
Hi Karen,
Thanks, and sorry that I mixed MF and BP in 3) of the long request, at the end. The current def of GO:0008193: tRNA guanylyltransferase activity is somewhat specific, but then either not specific enough or too broad to use for all these enzymes.
Def: Catalysis of the posttranscriptional addition of a guanyl residue to the 5' end of a tRNA molecule; observed for His tRNAs. 

Thg1, which is currently annotated to this term (child of term you proposed), adds a G at position -1 of tRNAHis (standard RNA numeration). PMID:27484477, also from the Jackman group, has a nice drawing of this in Fig. 5. The Jackman review you cite also talks specifically about the G-1 addition by Thg1. And this happens by Thg1 exclusively on cytosolic tRNAHis. So maybe this term needs tightening, will look more into specificity of the other enzymes.

I'm in Europe and running out of time as staying with friends. On Monday I'll fly back to US. Will add to 3) and come up with suggestions some time next week.

If the BP terms 1) and 2) are more straightforward, maybe those can be taken care off first.

Thanks,
Petra

**Comment by pfey03** [comment]
Hi Paola,

I think number 1 can be added, as the sibling for 3' is there already. Let's solve these term requests one by one:

1) tRNA 5'-end processing / mitochondrial tRNA 5'-end processing
. . <- GO:0090646 tRNA processing
. . . <- GO:1990180 mitochondrial tRNA 3'-end processing
**. . . <- GO:New: mitochondrial tRNA 5'-end processing**

Thanks!

**Comment by paolaroncaglia** [comment]
Hi @pfey03 ,

Wrt your request number 1) for GO:New: mitochondrial tRNA 5'-end processing, I will add as follows:

GO:New: mitochondrial tRNA 5'-end processing
is_a mitochondrial tRNA processing
is_a RNA 5'-end processing
The process in which the 5’ end of a pre-tRNA molecule is converted to that of a mature tRNA in the mitochondrion.
GOC:pf

Please confirm which PMID(s) I should attach to this term among the ones you indicated (i.e. PMID:27484477, PMID:26143376, PMID: 21307182).

**Comment by paolaroncaglia** [comment]
Hi again @pfey03 ,

Wrt your requests number 2) for GO:New: tRNA repair and GO:New: mitochondrial tRNA repair, are those processes really different from their parent GO:0042245 RNA repair? Do they occur differently? It sounds as if it’d be better to annotate to ‘RNA repair’ and add annotation extensions for GO ’mitochondrion’ and SO ‘tRNA’. But if those processes should indeed be represented by separate terms, please suggest definitions for both to underline the differentia, and confirm which PMID(s) I should attach to each term among the ones you indicated (i.e. PMID:27484477, PMID:26143376, PMID: 21307182).

Thanks!

**Comment by paolaroncaglia** [comment]
Finally, @pfey03 , for your request 3) GO:New: 3′-5′ RNA polymerase activity, I will wait for you to look into it further.

**Comment by paolaroncaglia** [comment]
Hello again @pfey03 ...
Having second thoughts about your request 1) based on my comment about 2). Could you please explain how is GO:New: mitochondrial tRNA 5'-end processing different from an RNA 5'-end processing that occurs on a tRNA and in the mitochondrion? (Can't remember, do you not use AEs?) Or maybe it is truly different. Thanks.

**Comment by pfey03** [comment]
Hello @paolaroncaglia
Request 1) 

I thought this is easy to add because the equivalent 3' term exists already (GO:1990180 mitochondrial tRNA 3'-end processing). 

YES, we do AE in P2GO though they are not yet imported into our current, old database. Working on new database and then it will also be exported with extensions, but will still be a little while. But therefore, I agree that 'occurs_in mitochondrion' could easily be added.

However, 3' processing and 5' processing should be differentiated as they are distinctly different processes. But the general tRNA processing terms are NOT available. So maybe we should do this:

GO:0008033 tRNA processing
**-> GO:NEW tRNA 3'-end processing
-> GO:NEW tRNA 5'-end processing**

OBSOLETE: GO:1990180 mitochondrial tRNA 3'-end processing, and annotate current entries to new parent 'tRNA 3'-end processing'

In sum, If you obsolete the the mitochondrial tRNA 3' term, I think the processes are essentially the same in the different compartemnts. Just the enzymes are typically very specific for the compartment they act on tRNAs.

Let me now if this seems a good plan for 1).

**Comment by paolaroncaglia** [comment]
Hi @pfey03 ,
I was going to say that your plan for 1) looked good to me, but I’m now not so sure based on your note that “I think the processes are essentially the same in the different compartments. *Just the enzymes are typically very specific for the compartment they act on tRNAs.*”. So those enzymes would always be coannotated to ‘mitochondrion’ and to the processing term. Based on what we’ve said at previous GO meetings, that may be ground for allowing specific mitochondrial processing terms… (whether they’d be created automatically or not.) 
So, I added your new term as follows:

 [Term]
+id: GO:0097745
+name: mitochondrial tRNA 5'-end processing
+namespace: biological_process
+def: "The process in which the 5' end of a pre-tRNA molecule is converted to that of a mature tRNA in the mitochondrion." [GOC:pf, PMID:21307182, PMID:26143376, PMID:27484477]
+is_a: GO:0000964 ! mitochondrial RNA 5'-end processing
+is_a: GO:0090646 ! mitochondrial tRNA processing

**Comment by paolaroncaglia** [comment]
@pfey03 ,

Now back to your requests number 2) for GO:New: tRNA repair and GO:New: mitochondrial tRNA repair. Are those processes really different from their parent GO:0042245 RNA repair? Do they occur differently? Or are they the same, but are there specific gene products that only act on tRNAs (i.e. not on other types of ncRNAs)? If so, are gene products involved in *mitochondrial* tRNA repair ever known to work outside of the mitochondrion? It might be better to annotate to ‘RNA repair’ and add annotation extensions for GO ’mitochondrion’ and SO ‘tRNA’. But if those processes should indeed be represented by separate terms, please suggest definitions for both to underline the differentia, and confirm which PMID(s) I should attach to each term among the ones you indicated (i.e. PMID:27484477, PMID:26143376, PMID: 21307182).

Thanks!

**Comment by paolaroncaglia** [comment]
@pfey03 , 
Finally, for your request 3) GO:New: 3′-5′ RNA polymerase activity, when you’ve had a chance to look into it further, if you’d like to suggest any additions or changes, please open a new ticket. That would be easier and quicker, rather than disentangling conversations in tickets containing multiple threads. Thanks again.

**Comment by pfey03** [comment]
Hi @paolaroncaglia,
1) Thanks for doing what I initially thought is the solution, adding the corresponding 5' term!

Will get back about 2) soon, and I'll open a new ticket for 3) once I'm up to date on it, reading some more, suggesting def and parentage etc.
Thanks for your patience!

**Comment by pfey03** [comment]
@paolaroncaglia,

2) I read a recent review (PMID:27536007) about RNA effectors and repair. It seems a lot is still unknown, and probably we leave the unspecific 'GO:0042245 RNA repair' alone for now. As it is here for me, if there are other processes and/or functions better to describe an RNA repair protein, this term might be fine as is. However, at one point with more reading and data, 'RNA repair' might not be childless forever.

Will add new issue for 3) soon!

**Comment by paolaroncaglia** [comment]
Thanks @pfey03 . Closing this one now.
