### ISSUE TITLE
OTR/NTR GO:0003959 (NADPH dehydrogenase activity)

### ISSUE THREAD

**Issue by ethanclary143** [geneontology/go-ontology#12750]
I am a CACAO student. Annotation of PMID:27694803 revealed the need for a NADPH dehydrogenase term that is non-quinone specific. The current NADPH dehydrogenase term GO:0003959 (NADPH dehydrogenase activity) states that the compound being reduced must be a quinone. The current definition is as follows : DEF: “Catalysis of the reaction: NADPH + H+ + quinone acceptor = NADP+ + hydroquinone”. I would like to request that this term’s description to be modified to read “Catalysis of the reaction: NADPH + H+ + acceptor = NADP+ + reduced acceptor” similar to description of the NADH dehydrogenase term. I also would like to request that a child term be created for this term that is quinone specific, the same way the NADH dehydrogenase term has a quinone specific child term.

**Comment by ethanclary143** [comment]
Upon further investigation I found the go term GO:0008753 (NADPH dehydrogenase (quinone) activity) which is not a child term of GO:0003959 (NADPH dehydrogenase activity) but a completely separate term. Also, the definition for GO:0008753 (NADPH dehydrogenase (quinone) activity) does not specify that the acceptor is a quinone rather the definition is as follows: DEF:"Catalysis of the reaction: NADPH + H+ + acceptor = NADP+ + reduced acceptor". I would like to request that the definitions of these terms be swapped and that GO:0008753 (NADPH dehydrogenase (quinone) activity) be made a child term of GO:0003959 (NADPH dehydrogenase activity).

**Comment by paolaroncaglia** [comment]
Hi @ethanclary143 (and @hdrabkin),

GO refers to the Enzyme Nomenclature (EC) for its enzyme activity terms. In EC, EC 1.6.5.10 ‘NADPH dehydrogenase (quinone)’ and EC 1.6.99.1 ‘NADPH dehydrogenase’ are not directly related because the former is a subclass of EC 1.6.5 (oxidoreductases, acting on NADH or NADPH, *with a quinone or similar compound as acceptor*), while the latter is a subclass of 1.6.99 (oxidoreductases, acting on NADH or NADPH, *with unknown physiological acceptors*). However, you are right in noticing that this pattern is not applied consistently with NADH dehydrogenase activity terms. I think we (ontology editors) may have run across this issue before, but I can’t remember what the resolution was. I’ll ask my colleague @hdrabkin to comment please, when he is back from the GO Consortium meeting. Thanks.

**Comment by paolaroncaglia** [comment]
Hi @ethanclary143 ,
FYI, @hdrabkin is away until wc Nov 21st, so he probably won't be able to look into this until after his return.

**Comment by ethanclary143** [comment]
Hello @paolaroncaglia ,
Thank you very much for the update and for all the assistance with my requests. Is there no way to modify the definitions for the NADPH dehydrogenase (quinone) and the NADPH dehydrogenase terms without @hdrabkin looking at them?

**Comment by hdrabkin** [comment]
Yes, the definitions should be modified. I forget where I saw this recently (maybe one of the plant enzyme activities).

**Comment by paolaroncaglia** [comment]
Thanks @hdrabkin . I will modify those definitions. But if there's anything that needs to be done to represent those activities consistently in GO (in general), could you please take care of that? Cheers.

**Comment by paolaroncaglia** [comment]
Hi @ethanclary143 and @hdrabkin ,
I corrected the defs of GO:0008753 and GO:0003959 to reflect their EC counterparts.

@hdrabkin ,
I will assign this ticket to you now please, to look into the following:

In EC, EC 1.6.5.10 ‘NADPH dehydrogenase (quinone)’ and EC 1.6.99.1 ‘NADPH dehydrogenase’ are not directly related because the former is a subclass of EC 1.6.5 (oxidoreductases, acting on NADH or NADPH, with a quinone or similar compound as acceptor), while the latter is a subclass of 1.6.99 (oxidoreductases, acting on NADH or NADPH, with unknown physiological acceptors). However, this pattern is not applied consistently with NADH dehydrogenase activity terms in GO. I think we (ontology editors) may have run across this issue before, but I can’t remember what the resolution was. 

Thanks.

**Comment by hdrabkin** [comment]
I haven't a clue as to what you want me to do? (look into... ?????).  
Should I change EC #s to reflect subclass?

**Comment by hdrabkin** [comment]
I just did a quick check in OE and as far as I can tell, there are only quinone utilizing activities associated with EC 1.6.5
However, at least one of the 1.6.99 enzymes does use quinone, so I can perhaps change that one
NADH dehydrogenase (quinone) activity (GO:0050136); should be 1.6.5. subclass

**Comment by paolaroncaglia** [comment]
Hi @hdrabkin, 

In summary: 

ethanclary asked if 
GO:0008753 (NADPH dehydrogenase (quinone) activity) (which has dbxref EC 1.6.5.10 ‘NADPH dehydrogenase (quinone)’)
should be made a child of 
GO:0003959 (NADPH dehydrogenase activity) (which has dbxref EC 1.6.99.1 NADPH dehydrogenase).

I explained that they currently aren’t because we refer to the EC classification, and the two EC entries above don’t have the same ‘parent’:
EC 1.6.5 (oxidoreductases, acting on NADH or NADPH, with a quinone or similar compound as acceptor)
versus
EC 1.6.99 (oxidoreductases, acting on NADH or NADPH, with unknown physiological acceptors).

However, I noticed that the placement of another similar term in GO is not consistent:
NADH dehydrogenase (quinone) activity (EC 1.6.99.3) is_a NADH dehydrogenase activity (EC 1.6.99.3)
Is this correct? Or should anything be changed? 

Thanks :-)
Paola

**Comment by hdrabkin** [comment]
I will look addding

**Comment by hdrabkin** [comment]
EC doesn't allow multiple parentage. 
1.6.99.3 seems to indicate unnamed substrate; 1.6.5.10 indicates a specific substrate.  Formally EC does not link the two. I don't think anything needs to be "fixed". 
We have put a hierarchy to the terms that EC does not. (ie, 1.6.5.10 is a child of 1.6.99.3).
