### ISSUE TITLE
ZFIN GO file load is failing

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12765]
@doughowe wrote:

Hi All,
The GO ontology file we are loading is failing because the current "motile cilium assembly" term is using as it's primary ID an ID that has formerly been a secondary ID for the same term. Its as if a term merge was done term 1-> term 2 and then the decision was made at a later date to instead merge term 2 -> term 1? That has the effect of creating a term (Currently GO:0044458) using an ID that was once logged as a secondary term ID, and hence it is no longer valid as a primary ID.... I've included the two term stanzas we are seeing below, one from Oct 13 and one from Oct 26.

I wanted to check in if this was an intended change or a bug or mistake? We can make updates in our database to permit this if necessary, but it does cause a failure of our GO load due to the violation of reusing a secondary ID as a primary ID.

Thanks for your input on the situation!

Doug

file on Oct 13 2016

data-version: releases/2016-10-08
date: 07:10:2016 10:10

[Term]
id: GO:1903887
name: motile cilium assembly
namespace: biological_process
alt_id: GO:0044458
def: "The aggregation, arrangement and bonding together of a set of components to form a motile cilium." [GO_REF:0000079, GOC:cilia, GOC:krc, GOC:TermGenie, PMID:19776033, PMID:21129373, ZFIN:dsf]
synonym: "motile primary cilia assembly" RELATED [GOC:TermGenie]
synonym: "motile primary cilia formation" RELATED [GOC:TermGenie]
synonym: "motile primary cilium assembly" RELATED []
synonym: "motile primary cilium formation" RELATED [GOC:TermGenie]
synonym: "nodal cilium assembly" RELATED [GOC:TermGenie]
synonym: "nodal cilium formation" RELATED [GOC:TermGenie]
is_a: GO:0042384 ! cilium assembly
created_by: krc
creation_date: 2015-02-06T17:23:23Z

file on Oct 26

data-version: releases/2016-10-26
date: 25:10:2016 17:46

[Term]
id: GO:0044458
name: motile cilium assembly
namespace: biological_process
alt_id: GO:1903887
def: "The aggregation, arrangement and bonding together of a set of components to form a motile cilium." [GO_REF:0000079, GOC:cilia, GOC:krc, GOC:TermGenie, PMID:19776033, PMID:21129373, ZFIN:dsf]
synonym: "motile primary cilia assembly" RELATED [GOC:TermGenie]
synonym: "motile primary cilia formation" RELATED [GOC:TermGenie]
synonym: "motile primary cilium assembly" RELATED []
synonym: "motile primary cilium formation" RELATED [GOC:TermGenie]
synonym: "nodal cilium assembly" RELATED [GOC:TermGenie]
synonym: "nodal cilium formation" RELATED [GOC:TermGenie]
is_a: GO:0060271 ! cilium assembly
created_by: krc
creation_date: 2015-02-06T17:23:23Z

**Comment by mcourtot** [comment]
See also https://github.com/geneontology/go-ontology/issues/12729

**Comment by mcourtot** [comment]
Hi @doughowe,

As you correctly inferred, this is all linked to a merge gone wrong. In very short, what was meant to be the secondary ID, GO:1903887, ended up as primary due to a bug in OBO edit. Unfortunately, this was not caught before @hattrill reported errors with her load, at which point a released file as already gone out. 
This was manually corrected the following day. Full details are at #12729.

As we were able to identify the source of the issue we hope this will not happen again, so if you could indeed update the DB manually that would be the best, the correct version being the latest one:
[Term]
id: GO:0044458
name: motile cilium assembly
namespace: biological_process
alt_id: GO:1903887
def: "The aggregation, arrangement and bonding together of a set of components to form a motile cilium." [GO_REF:0000079, GOC:cilia, GOC:krc, GOC:TermGenie, PMID:19776033, PMID:21129373, ZFIN:dsf]
synonym: "motile primary cilia assembly" RELATED [GOC:TermGenie]
synonym: "motile primary cilia formation" RELATED [GOC:TermGenie]
synonym: "motile primary cilium assembly" RELATED []
synonym: "motile primary cilium formation" RELATED [GOC:TermGenie]
synonym: "nodal cilium assembly" RELATED [GOC:TermGenie]
synonym: "nodal cilium formation" RELATED [GOC:TermGenie]
is_a: GO:0060271 ! cilium assembly
created_by: krc
creation_date: 2015-02-06T17:23:23Z

Please let us know whether this works or not.

Kind regards,
Melanie

**Comment by paolaroncaglia** [comment]
Hi again @doughowe ,
Please let us know if/when we can close this ticket. I'll be on leave next week, so my response time will be delayed, but @mcourtot is kindly monitoring this ticket, and more people can be involved by mentioning as necessary. Thanks.

**Comment by doughowe** [comment]
Thanks, All....this case can now be closed.
