### ISSUE TITLE
logical parent for "GO:0032536: regulation of cell projection size" missing

### ISSUE THREAD

**Issue by hbye** [geneontology/go-ontology#12762]
Hello,

I would like to create the positive and negative regulation terms for "regulation of cell projection size" (GO:0032536). However, the parent of this term is not "cell projection size" and furthermore, this does not seem to exist as a GO term. Would it be possible to look in to this?

The paper I would like to use the regulation term for is PMID:27623382.

Thanks,
Hema

**Comment by tberardini** [comment]
Cell projection size is not a biological process but rather a biological quality.  This is why the 'core' term is not present in the GO.  I will look into creation of the negative and positive children terms.  Are you sure you would not rather capture this data (changes in cell projection size) as a phenotype annotation instead?

**Comment by paolaroncaglia** [comment]
Hi @tberardini ,
@hbye  and I just had a quick in-person discussion about this, and I showed how she could capture processes more specifically (e.g. via cilium assembly terms) rather than via a generic 'size' term. She agrees that she may not need positive and negative regulation terms for "regulation of cell projection size" after all, but she's going to look into that paper further before she confirms if that's the case and if you can close this ticket. You will probably hear from her shortly. Thanks!
(@hbye, I forgot to ask: does UniProt curate phenotypes? I don't think so, but just in case.)

**Comment by hbye** [comment]
Hello, yes, after a very useful chat with @paolaroncaglia, I think the cilium assembly terms are better suited and are more appropriate to use in this instance. I won't therefore need to use the regulation terms, so no worries about creating these, and you may close the ticket. Thanks anyway!

(@paolaroncaglia, yes we do capture phenotypes in a "Disruption phenotype" comment. However, only for null mutants, but we try to make it clear if the phenotype may be a downstream affect- which is probably the case in this paper).

**Comment by tberardini** [comment]
Thank you, Paola!
