### ISSUE TITLE
Review MF term GO:0050827 'toxin receptor binding'

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#12766]
Hi,

Following on from a go-help email (http://jira.geneontology.org/browse/GO-1380), can we review the MF term GO:0050827, 'toxin receptor binding' to see if it's still considered an appropriate GO MF term?

There are currently 12 annotations to the term, only one of which has an experimental evidence code.

Thanks,
--Kimberly

**Comment by tberardini** [comment]
Added to agenda/project page for next GO Eds meeting (11/10).

**Comment by tberardini** [comment]
Three points which I've brought over from the helpdesk issue:

1. toxin receptor activity =? toxin activity

> Accession GO:0050827
Name toxin receptor binding
Ontology molecular_function
Synonyms channel-forming toxin activity, cytotoxin activity, endotoxin
activity, enterotoxin activity, exotoxin activity, lipoprotein
toxin, neurotoxin activity, pore-forming toxin activity, toxin activity
Alternate IDs None
Definition Interacting selectively and non-covalently with a toxin receptor, a
receptor for substances that cause injury to living organisms./Source:/ GOC:ai
I find the writing here a bit confusing. Isn't a molecule that performs "toxin receptor binding" a toxin?
OK, "toxin activity" is a synonym of this term, but apparently neither you nor I nor Ingrid were able to find this term in our initial searches. Perhaps this is the term I was asking for. In my view it should be stated in simpler language that this term refers to toxin activity. On the other hand, the graph view of this term shows it to be a child of protein-binding, meaning that this term would capture only those toxins that bind to proteins; presumably there are other kinds of toxins but I can't enumerate them. Are there toxins that bind to molecules other than proteins? Are there toxins whose effects are mediated throughother means than binding, e.g.,via enzymatic activity? I don't know, but if there are, there should be terms for those types of toxins as well.
Do note that this term is-a molecular-function, so does the same reasoning for GO:0015070 apply to this term? Perhaps not because this term does refer to a type of molecular interaction, namely
binding to a protein toxin receptor.

2. remove 'toxin' related synonyms for 'pathogenesis'?

>Accession GO:0009405
Name pathogenesis
Ontology biological_process
Synonyms channel-forming toxin activity, cytotoxin activity, endotoxin
activity, enterotoxin activity, exotoxin activity, lipoprotein
toxin, neurotoxin activity, pore-forming toxin activity, toxin
activity, virulence
Alternate IDs None
Definition The set of specific processes that generate the ability of an
organism to cause disease in another. /Source:/ GOC:go_curators
Comment
Note that this term should not be used to annotate gene products
that are involved in the host response to pathogenesis. It should
only be used to annotate those gene products involved in the
generation of pathogenesis by the pathogen itself.
I see pathogenesis as a much broader concept, so I am surprised to see all the toxin-related
synonyms for this term; I suggest they be removed because they generate confusion in my
opinion given the other toxin-related term just discussed.

3. clarify connection, if any, between 'pathogenesis' and 'cell killing'

>I'll also note the term http://www.ebi.ac.uk/QuickGO-Beta/term/GO:0001906 "cell killing". Perhaps this would be an appropriate place for expansion as well. It's not clear to me the relationship between pathogenesis and cell killing.

**Comment by tberardini** [comment]
Note that ChEBI has 'toxin' in its 'biological role' hierarchy.

http://www.ebi.ac.uk/chebi/searchId.do?chebiId=27026

**Comment by tberardini** [comment]
More notes:
1. all the '%toxin%' synonyms for 'toxin receptor binding' are [RELATED]
2. all the '%toxin%' synonyms for 'pathogenesis' are [RELATED]
3. there is no link between 'pathogenesis' and 'cell killing' although perhaps a connection could be made between one or more children terms of 'cell killing' and 'pathogenesis' - discuss

**Comment by pkarp111** [comment]
Let me add an additional thought:  Are "binding to toxin receptor" and
"toxin" the same concept?  I would argue no, in theory.  A molecule
could conceivably bind to a toxin receptor and prevent the toxin
from binding to the receptor, thus protecting the organism from the
effects of the toxin.  The fact that a molecule binds to a toxin
receptor doesn't tell you the biological effects of that binding.

P

**Comment by tberardini** [comment]
@pkarp111 : I mistyped in my earlier comment, I meant to write "toxin receptor **binding** =? toxin activity" instead of "toxin receptor **activity** =? toxin activity".  I have corrected that now.

**Comment by vanaukenk** [comment]
Hi,

Just checking in wrt this issue.  Did the ontology editors get a chance to discuss this on the 2016-11-10 call?

Thanks,
--Kimberly

**Comment by mcourtot** [comment]
Hi @vanaukenk, I'm afraid we didn't get the chance to discuss this yesterday.

**Comment by vanaukenk** [comment]
Thanks for the update, @mcourtot!

**Comment by mcourtot** [comment]
Discussed at editors call 2016-11-17:
AI: obsolete toxin receptor binding

**Comment by paolaroncaglia** [comment]
Related: https://github.com/geneontology/amigo/issues/290#issuecomment-216255324

**Comment by tberardini** [comment]
Nascent action items:

1. obsolete toxin receptor binding, come up with child of pathogenesis for molecules that act as toxins
2. remove confusing synonyms - explain that they are 'related' 
3. create AmiGO GH issue to display type of synonym (may exist already)
4. possibly create superclass toxin activity with heterogeneous subclasses that describe the individual mechanisms, if these are single step functions/molecular processes

**Comment by dosumis** [comment]
Re item 4:  two possibilities discussed.

1. create a toxin activity MF
2. Create a process term for toxicity process under pathogenesis. 

These are not necessarily mutually exclusive as 'toxin activity' might be logically defined as "'molecular_function that 'part of' some 'toxicity process'"  This would => a pattern for logical def of toxins with various mechanisms.  e.g. 'channel activity' that 'part of' some 'toxicity process' - or for auto-classification of toxin activity during from extended annotation or LEGO.

**Comment by tberardini** [comment]
I think we need to work out the new term/s to add first before I can propose the obsoletion.  That way there will be something to point to using the 'consider' tag.  I can proceed with the synonym removal without that happening though as they are adding to the confusion.

Further fodder for thought: With the current definition of pathogenesis being, "The set of specific processes that generate the ability of an organism to cause **disease** in another.", does what we think of as 'toxicity' (broadly, causing damage or injury) fall under 'disease'?

**Comment by ukemi** [comment]
Hi Tanya,

It seems to fit the definition of disease given in the disease ontology.

-D

**Comment by tberardini** [comment]
>It seems to fit the definition of disease given in the disease ontology.

Ok, good.  One less worry.

**Comment by cmungall** [comment]
Note also that CHEBI has a very human-centric notion of toxin, I don't 
think we gain much by axiomatizing with this class.

It sounds like there is not really a use case for this GO class. Now we 
can be more explicit when making a model, and state whether the receptor 
binding and its parent activity are causing a negative effect on 
pathogenesis, realizing some detection role, or causing harm to the 
organism (outside GO when done from the perspective of the harmed 
organism)

**Comment by pkarp111** [comment]
I see a simple use case Chris, which is querying an organism's genome 
for all genes
whose products are toxins.

P

**Comment by cmungall** [comment]
Apologies for my reply appearing out of sync. I wrote it yesterday, it was stuck i my outbox, and appeared here *after* we had sorted everything out this morning. So it's entirely superfluous. But I think still valid.

Because it's out of sync it's not clear that I'm referring to 'toxin receptor binding', which we agreed would be obsoleted.

For @pkarp111's use case, the toxin activity function mentioned by @dosumis would work. And we would define this the way @dosumis describes, rather than axiomatizing using CHEBI, which avoids the human-toxin-centric problem.

**Comment by pkarp111** [comment]
Ah, sounds good, I indeed misunderstood!

**Comment by almitchell** [comment]
We are struggling with the annotation of various venoms in InterPro at the moment. Some of 
our snake, spider and scorpion toxin entries are annotated with GO:0009405 'pathogenesis'. 
I am concerned that this is not the correct use of the term, since the definition relates
specifically to disease, and venom activity does not = disease causing, right?

The curators have discussed replacing the annotations with GO:0050827 'toxin receptor binding’,
but I am not sure this is right either, since what are toxin receptors? Most of these toxins
bind to receptors that are responsible for normal physiological actions, but lock them
into permanently activated states, etc.

Is it possible to have a term / set of terms that relate to animal / insect venoms and toxins, as well 
as more classical pathogenic microbial toxins?

**Comment by deustp01** [comment]
This sounds glib but points to a deeper issue that needs to be addressed explicitly, I think, or it will keep recurring.

From the viewpoint of the spider, snake, or scorpion, the correct GO term is something like GO:0007631 feeding behavior.

From the viewpoint of the animal that gets bitten, it should probably be a novel child of GO:0006950 response to stress, a sibling or maybe a child of GO:0009611 response to wounding. or perhaps something similar to GO:0009615 response to virus.

**Comment by almitchell** [comment]
So the issue for us is that we are annotating the collective protein family, rather than the individual protein from a given species. Perhaps it would be safer for us to remove the GO annotation completely from these entries.

**Comment by tberardini** [comment]
Removed synonyms.

Proposal for new terms: **input needed**  Remember that they will be used for annotating the gene products from the organism that produces the toxin (and bites/stings) NOT the organism that is being affected by these substances (and is bitten/stung).

MF: toxin activity
logical definition:  "'molecular_function that 'part of' some 'toxicity process'" 
BP: toxicity process
Def: **???**

>molecular_function
--[i] toxin activity

>pathogenesis, GO:0009405
--[i] toxicity process
----[p] toxin activity

OR (I am leaning towards this one.)

>interspecies interaction between organisms, GO:0044419
--[i] toxicity process
----[p] toxin activity

OR

**something else?**

Note:  Currently

>multi-organism process
--[i] pathogenesis
--[i] interspecies interaction between organisms

Should probably update this to be:

>multi-organism process
--[i] interspecies interaction between organisms
----[i] pathogenesis

**Comment by tberardini** [comment]
- [ ] create 'toxin activity'

- [ ] relationship: toxin activity part_of pathogenesis, do NOT create 'toxicity process'

- [ ] @thomaspd: come up with toxin activity definition

- [ ] move pathogenesis

>multi-organism process
--[i] interspecies interaction between organisms
----[i] pathogenesis

**Comment by deustp01** [comment]
multi-organism process
--[i] interspecies interaction between organisms
----[i] pathogenesis
Will this parentage accommodate carcinogenesis (beyond ~ due to environmental factors like tobacco smoke) or genetic disease or autoimmune disease? And does it matter if not? I guess this may be a question about the scope of GO, but it is definitely not a prelude to an argument about what that scope should be.

**Comment by almitchell** [comment]
I am still concerned about having toxin activity as a part of pathogenesis, since that term relates specifically to disease, and many toxins (conotoxins, latrotoxins, etc) would not be defined as disease causing.

**Comment by thomaspd** [comment]
First pass definition of "toxin activity":
Interacting selectively with one or more biological molecules in another organism (the "target" organism), initiating pathogenesis (leading to an abnormal, generally detrimental state) in the target organism.  The activity should refer to an evolved function of the active gene product, i.e. one that was selected for.  Examples include the activity of botulinum toxin, and snake venom. [see: https://en.wikipedia.org/wiki/Toxin].

In response to the comments above on the current definition of pathogenesis in GO, I think it might be helpful to replace the word "disease" with a more general statement like the parenthetical one I inserted in the definition of toxicity.  Then we could more clearly include conotoxin, etc. This would give the following definition:
The set of specific processes that generate the ability of an organism to induce an abnormal, generally detrimental state in another organism.

Note that this definition of pathogenesis does not include environmental causes, but rather only "biological programs" that have evolved in one organism to perturb/control processes in another organism.

One other thing: we might also want to classify the enzymes involved in producing small molecule toxins:
multi-organism process
--[i] interspecies interaction between organisms
----[i] pathogenesis
------[p] toxin activity
------[p] small molecule toxin biosynthetic process

**Comment by cmungall** [comment]
Do we know for sure that toxicity evolved for botulin?

What about other neurotoxins produced by microbes - some will be side-effects of some function the protein evolved within the native cell.

I still think it's a good def, we will just have to be sure to document well, and have guidelines for when a selective advantage is hard to demonstrate

**Comment by tberardini** [comment]
Reiterating the definition of pathogenesis and its accompanying note for consideration in this discussion.

>The set of specific processes that generate the ability of an
organism to cause disease in another. /Source:/ GOC:go_curators
**Comment**
Note that this term should not be used to annotate gene products
that are involved in the host response to pathogenesis. It should
only be used to annotate those gene products involved in the
generation of pathogenesis by the pathogen itself.

Also, here's the definition of disease in the disease ontology. (note that this is the **Human** Disease Ontology.) - is this the one you meant, @ukemi?

[Term]
id: DOID:4
name: disease
def: "A disease is a disposition (i) to undergo pathological processes that (ii) exists in an organism because of one or more disorders in that organism." [url:http\://ontology.buffalo.edu/medo/Disease_and_Diagnosis.pdf]
xref: MSH:D004194
xref: NCI:C2991
xref: SNOMEDCT_US_2016_03_01:64572001
xref: UMLS_CUI:C0012634

**Comment by ukemi** [comment]
Yes. This is the disease definitionI used for my comment. If you go to the referenced paper, it looks like it fits our needs.

**Comment by tberardini** [comment]
Thanks, @thomaspd !

Additional to-do:

- [ ] Redefine 'pathogenesis' as: The set of specific processes that generate the ability of an organism to induce an abnormal, generally detrimental state in another organism.

@deustp01 @almitchell  : How does that sit with you?  The direct use of the word 'disease' is removed which might mitigate the assumptions that go along with that word.

**Comment by almitchell** [comment]
Hi @tberardini 
That would solve the issue for me.

**Comment by tberardini** [comment]
@deustp01 : can you comment on the latest proposal please?  If ok, I will go ahead and implement the changes.

**Comment by tberardini** [comment]
**Added:**
 
[Term]
+id: GO:0090729
+name: toxin activity
+namespace: molecular_function
+def: "Interacting selectively with one or more biological molecules in another organism (the \"target\" organism), initiating pathogenesis (leading to an abnormal, generally detrimental state) in the target organism. The activity should refer to an evolved function of the active gene product, i.e. one that was selected for. Examples include the activity of botulinum toxin, and snake venom." [GOC:pt]
+xref: Wikipedia:Toxin
+is_a: GO:0003674 ! molecular_function
+relationship: part_of GO:0009405 ! pathogenesis
+created_by: tanyaberardini
+creation_date: 2016-12-19T15:23:27Z

**Edited:** 
 id: GO:0009405
 name: pathogenesis
 namespace: biological_process
-def: "The set of specific processes that generate the ability of an organism to cause disease in another." [GOC:go_curators]
+def: "The set of specific processes that generate the ability of an organism to induce an abnormal, generally detrimental state in another organism." [GOC:go_curators]
-is_a: GO:0051704 ! multi-organism process
+is_a: GO:0044419 ! interspecies interaction between organisms

**Comment by tberardini** [comment]
Last step:

Option 1: obsolete 'toxin receptor binding', consider 'toxin activity'
Option 2: obsolete 'toxin receptor binding', replaced_by 'toxin activity'
Option 3: merge 'toxin receptor binding' into 'toxin activity'

My preference is Option 3.  Other opinions?

There are currently 12 annotations to the term 'toxin receptor binding', only one of which has an experimental evidence code.

**Comment by pkarp111** [comment]
I'm fine with #3.  Thanks for adding the new toxin activity term.

P

**Comment by paolaroncaglia** [comment]
Thanks @tberardini , option 3 looks good to me too.

**Comment by tberardini** [comment]
Merge completed.  Closing this issue.

Note: Used OE to merge and it worked without a hitch.  There were no entries for 'toxin receptor binding' in the go_inferences.obo file so nothing to change there.
