### ISSUE TITLE
NTR: RNA polymerase II C-terminal domain binding

### ISSUE THREAD

**Issue by pgarmiri** [geneontology/go-ontology#12776]
Hi,
I am currently annotating PMID: 20889714 and they show that Heterochromatin protein 1 (HP1) binds to the C terminal domain (unphosphorylated and phosphorylated) of Polymerase II (figure 5) both in vivo and in vitro. Would it be possible to request a new term for "RNA polymerase II C-terminal domain binding"?
A potential definition would be: Interacting selectively and non-covalently with the C-terminal domain of RNA polymerase II. 
It could be a child of GO:0001099	basal RNA polymerase II transcription machinery binding and a parent or a sibling of GO:1990269 	RNA polymerase II C-terminal domain phosphoserine binding.
Thank you for help.
Kind regards,
Penelope

**Comment by krchristie** [comment]
Hi,

A term for "RNA polymerase II C-terminal domain binding" seems reasonable to me.

**Definition**:
The proposed definition: Interacting selectively and non-covalently with the C-terminal domain of RNA polymerase II.

is OK, though I think we could add more detail to specify what the CTD is, since for RNAP II, it is a specific portion of the largest subunit with unique conserved sequence features.

Possible expanded def: Interacting selectively and non-covalently with the C-terminal domain (CTD) of the largest subunit of RNA polymerase II. The CTD is comprised of repeats of a heptapeptide with the consensus sequence YSPTSPS. The number of repeats varies with the species and a minimum number of repeats is required for RNAP II function.

**Parentage**:
I think that the existing term "RNA polymerase II C-terminal domain phosphoserine binding" (GO:1990269) is placed incorrectly in the graph. 

Since the CTD of RNAP II is part of the core enzyme, this term should be a descendent of "RNA polymerase II core binding" (GO:0000993) more specifically than a descendent of "basal RNA polymerase II transcription machinery binding" (GO:0001099). 

So, this proposed new term should be an is_a child of "RNA polymerase II core binding" (GO:0000993). Then "RNA polymerase II C-terminal domain phosphoserine binding" (GO:1990269) should be an is_a child of the new term.

**Synonyms**:
It would be good if all of these terms:
* "RNA polymerase II core binding" (GO:0000993)
* "RNA polymerase II C-terminal domain binding" (new)
* "RNA polymerase II C-terminal domain phosphoserine binding" (GO:1990269)

had synonyms where
* "RNA polymerase II" is replaced by "RNAP II" [this is more common than "RNA Pol II"]
* "C-terminal domain" is replaced by "CTD"

-Karen

**Comment by pgarmiri** [comment]
Hi Karen,
All above sound good!
Thank you,
Penelope

**Comment by dosumis** [comment]
Added as requested:

GO:0099122

![image](https://cloud.githubusercontent.com/assets/112839/21049018/4f309b8e-be0a-11e6-90c0-ef5c9b0d6bae.png)

![image](https://cloud.githubusercontent.com/assets/112839/21049025/5441e88a-be0a-11e6-9ac1-cb13883b6bf9.png)

Thanks for all the help Karen!  Much appreciated.
