### ISSUE TITLE
Ensure we have at least one username associated with each slim/subset

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#12780]
We want to be able to automatically inform people of changes in the ontology that affects their slim

We could have one of two mechanisms:

 * people register for ownership of a slim in users.yaml
 * we have something in the slim headers that points to an unambiguous ID in users.yaml

**Comment by mcourtot** [comment]
Could we also possibly track the creation and last update dates, perhaps in the header as well?

I like the idea of having metadata in the slim header, pointing to users.ml rather than vice-versa; just seems like a more natural way to look up the information (use case "who should I contact if I have questions about the slim?", not sure there is a use case for "how many slim did user X contribute to?")

**Comment by pgaudet** [comment]
Same as #14276
