### ISSUE TITLE
Modified proteins proposal

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12787]
Relevant GH tickets:
[NTR: ubiquitinated protein binding](https://github.com/geneontology/go-ontology/issues/12582) 
[Parentage of glycoprotein binding](https://github.com/geneontology/go-ontology/issues/12580) 
[Question: adding new children of GO:0035064 methylated histone binding?](https://github.com/geneontology/go-ontology/issues/12522)

The [proposal](https://docs.google.com/document/d/17U1TD3n_QI9coCycJcOUBDa2nRf3ggPR-tKjDMa_ff8/edit )was not well received by annotators at the GO meeting. The annotators thought that these terms were too important biologically for them not to be in the ontology. We need to come up with alternatives.

Continue to add these terms by hand. Unsustainable?
Figure out a way to add these terms automatically. Use PRO?, Chebi?, PsiMod?, will this lead to annotation inconsistency. Probably.
Only add a few very high-level terms. What is the specificity cut off and what happens when annotators make a case that the very specific term that they want is important.
Have do-not-annotate' terms that are generated automatically as in #1 below and categorize gene products by the entity that is captured in binding annotations.
We discussed three possible semantic interpretations of modified protein binding terms:

https://docs.google.com/document/d/1MAnnOfs-e2LY9MnqdCZscalbxbNUDSJ9pbMZ-f2WS9U/edit#heading=h.vzsyf1ss0k8h

1. Binds a protein that happens to have a modification, but not necessarily the modification site 
2. Binds to the modified part of a protein <- Seems to be most broadly supported. 
3. Binding to some specific protein partner is dependent on the modification state of the partner even if binding is not to the modified bit.  <- Some support.   DOS objection:  this seems like annotating a property of the bound protein. Also specific to one binding interaction (whereas 2 is likely to be a general function) 

Number 2 in this list - binds to the modified part of a protein - had the most support. Example: SH2 domain confers binding to phospho-tryosine in the context of a specific peptide motif: https://en.wikipedia.org/wiki/SH2_domain

For terms like this, we could add a comment that it should only be used where there is high confidence that binding is to the modification + protein (simple dependency on phosphorylation of target is not sufficient but one that localizes the domain by deletion/mutagenesis analysis of the protein is). This still leaves the question of how detailed we should get in specifying the target (see histone binding).

**Comment by ukemi** [comment]
Darren will join us on today's meeting to present his ideas.

**Comment by nataled** [comment]
This is what I mentioned to a few attendees at the USC GOC meeting. I'll summarize first, then give the reasoning by way of example. 

Consider that "ubiquitinated protein binding" could be logically defined as something like ("protein binding to some ubiquitinated protein"). So ("ubiquitinated protein binding to some protein") is the same as ("protein binding to some ubiquitinated protein"). Given the confusion that currently holds when using these terms, this proposal provides the benefit that annotation is simplified. No information is lost, since terms like "ubiquitinated protein binding" are useful grouping terms that can be inferred 
based on the binding partner indicated.

I would suggest that "protein binding" be used as the annotate-to term. Child terms of interest (such as "glycoprotein binding") stay, and new ones minted if desirable, but be marked as do-not-annotate. 

Example:
Consider the case of USP15, a protein that binds to ubiquitinated histone H2B. This protein is annotated to GO:0061649 ("ubiquitinated histone binding"). For the moment, pretend that GO:0061649 can be a child of GO:0042393 ("histone binding") and the proposed term ("ubiquitinated protein binding"). The full hierarchy (after reasoning) would be:

protein binding
  |_ ubiquitinated protein binding
  |    |_ubiquitinated histone binding
  |_ histone binding
       |_ubiquitinated histone binding

Consider a possible history for the annotation of USP15, from two different labs. Lab one and lab two each publish that USP15 binds protein, but don't know which protein. You'd get:

Lab1: USP15 protein binding some "protein"
Lab2: USP15 protein binding some "protein"

Lab1 then finds that USP15 binds to a ubiquitinated protein, while lab2 discovers that it binds to some histone. Now the annotation becomes:

Lab1: USP15 ubiquitinated protein binding some "ubiquitinated protein"
Lab2: USP15 histone binding some "histone"

Lab1 now finds that the specific type of ubiquitinated protein bound is histone, and Lab2 finds that the histone is ubiquitinated. Revised annotation:

Lab1: USP15 ubiquitinated histone binding some "ubiquitinated histone"
Lab2: USP15 ubiquitinated histone binding some "ubiquitinated histone"

Note that each new bit of information resulted in, for each lab, a change to both the GO term & the target (column 17). That means (for each lab) a total of 4 changes beyond the initial annotation.

A better, easier, more scalable solution would be to annotate ONLY to the parent protein binding term. The other GO terms stay but only as grouping terms. Specificity is given by the target. Thus, the history (for Lab1 only) would become:

A: USP15 protein binding some "protein"
B: USP15 protein binding some "ubiquitinated protein"
C: USP15 protein binding some "ubiquitinated histone"

Only 2 changes were necessary. Pros of this approach include fewer changes, clear guidance for GO term to use, and it's sustainable to any level of target specificity ("ubiquitinated histone" becomes "ubiquitinated histone H2B" becomes "histone H2B ubiquitinated at position 120" (as opposed to "histone H2B ubiquitinated at position 122"). I can think of only one con, which is that term enrichment becomes useless for specific types of protein binding. Of course, term enrichment could still be achieved, but there would be some overhead in calculating the correct sub-function.

**Comment by mcourtot** [comment]
On the call http://wiki.geneontology.org/index.php/Ontology_meeting_2016-11-10 @nataled clarified that in the above 
```
A: USP15 protein binding to some "protein"
B: USP15 protein binding to some "ubiquitinated protein"
C: USP15 protein binding to some "ubiquitinated histone"
```
A, B and C are annotations made based on different evidence (different papers) through time, not one annotation evolving through time (though this would be possible too, provided the original paper contained the necessary information)

**Comment by dosumis** [comment]
Notes from call (http://wiki.geneontology.org/index.php/Ontology_meeting_2016-11-10)

DOS:  
1. Darren's suggested pattern in OWL:  GP (enables) 'protein binding' that has_input some PRO:'ubiquitinated protein'. 
2. This corresponds to semantic interpretation 1: binds to some protein that happens to be ubiquitinated.  Binding doesn't have to be dependent on modification.  Are we sure we want this?
3. If we have the terms with logical defs in the ontology, then annotations with extensions will also work.  Might be worthwhile if we want to allow more specific pro terms to be used in extensions. 

Action item:  We need more examples.  Ask Sylvan and Pascale to come to call to present examples.

**Comment by ValWood** [comment]
> The proposal was not well received by annotators at the GO meeting.
I'd like it to be recorded that this is not  true for PomBase curators.

I really like Darren's proposal. This is what we would do  anyway. The reason this solution was opposed was (by some) was because at the meeting it was not clear to all that  PRO could add generic 
"ubiquitinated protein" terms.

Of course, tools would also need to catch up, but at present, I would not rely on GO to provide comprehensive lists of  modified protein binding partners.  The annotation would need to catch up in tandem to be realistically useful.  So in this situation we have a good opportunity to make the annotations in a more sustainable way without compromising what users can already do.

**Comment by ValWood** [comment]
For example

GO:0051219 phosphoprotein binding
currently has
1 to 25 of 148 for 99 proteins

But I agree, @dosumis  we also need to be clear in these cases whether the binding is modification-dependent (when we make  these annotations using PRO IDs we translate has substrate into "active form" for our users

gene A protein binding "active form" PR:000045540  IPI  gene B
http://research.bioinformatics.udel.edu/pro/entry/PR%3A000045540/

(this isn't a real example, but I am sure we have done this for binding)

**Comment by pgaudet** [comment]
Hello, 
Here's a version of the proposal, reviewed by the GO-editors and by @sylvainpoux

____

**Background:**
A number of proteins are known to specifically bind a protein that is modified, while not binding the unmodified form. The binding may occur at the site of the modification, but this is not an absolute requirement for a modification-specific binding; in some cases the binding occurs at another position on the target protein but is nevertheless dependent on the PTM. 

Moreover (and very important for annotation), the information is not always complete: in some cases, the position of the binding relative to the modification is known, while in other cases, only the nature of the modification is known but not the binding site positions. 

A number of domains are also known to specifically recognize and bind modified proteins, which is extremely important for recruitment of proteins and signaling (for example chromatin or DNA repair). Note that we do not always know whether these domains/proteins bind the modified part, but we usually know that they specifically recognize modified proteins.

The existence of these GO terms is extremely important for users, because it can really guide research. Moreover, resources like InterPro can generate electronic annotation for domains that bind modified proteins. Despite the usefulness of these terms, their ambiguous definitions has led to inconsistent usage.  Some terms have been created in GO to reflect modified protein binding: GO:0051219 phosphoprotein binding, GO:0061649 ubiquitinated histone binding etc. The definition does not clearly state that the binding must be modification-dependent, so it can be interpreted as 'protein x modified protein binding' to 'a protein that has the potential of bearing the modification'. This usage of the term is clearly incorrect. 


On the other hand, other terms are missing from the ontology and curator use existing terms incorrectly to capture the information. For example, GO:0043130 ubiquitin binding could be both used for proteins that bind ubiquitinated proteins and free ubiquitin (both cases exist and are biologically important).
Proposal: 
**1.	Create a GO term**
Modification-dependent protein binding: 
Definition: Binding specifically to a protein that bears a post-translation modification. 
Note: Does not bind the protein when not modified.

**Annotation guidelines:** 
- The binding must be compared with and without the PTM in the interaction partner. If it is not shown that the binding is abolished in absence of the modification, this term cannot be used.

**2.	Create a limited number of child terms for most common PTMs (fewer than 10)**

- Phosphorylated protein binding (would replace phosphoprotein binding)
- Glycosylated protein binding (would replace glycoprotein binding)
- Ubiquitinated protein binding (would be a child of ubiquitin binding and we would specify that ubiquitin binding is both for binding free ubiquitin and ubiquitinated proteins)
- Methylated protein binding
- Acylated protein binding
- Acetylated protein binding

**3.	Other PTMs:** 
To avoid unsustainable multiplication of terms, we can use 'Modified protein binding' with an ontology term in the extension (ontology to use remains to be defined). Until we choose the ontology, the parent term “modification-dependent protein binding” should be used for annotation. 

----

Thanks, Pascale

**Comment by pgaudet** [comment]
Note: Send annotations to everyone to modify

**Comment by hdrabkin** [comment]
here is list from PRO:
acetylation
ADP-ribosylation
amidation
bromination
cleavage
glycosylation
GPI-anchor
hydroxylation
methylation
phosphorylation
prenylation
sumoylation
ubiqitination
other

**Comment by hdrabkin** [comment]
don't know how often bromination comes up, and the "cleavage"

**Comment by pgaudet** [comment]
Rename: 
GO:0050815 phosphoserine binding ->   phosphoserine residue binding 
GO:0050816 	phosphothreonine binding -> phosphothreonine residue binding 
GO:0001784 phosphotyrosine binding -> phosphotyrosine  residue binding 

On the May 9. 2017 annotation call, we agreed that the meaning of that terms was consistent with these changes.

**Comment by pgaudet** [comment]
Updated the definition to "Binding specifically to a protein dependent on the presence of a post-translation modification in the target protein. "

**Comment by pgaudet** [comment]
[Term]
+id: GO:0140030
+name: modification-dependent protein binding
+namespace: molecular_function
+def: "Binding specifically to a protein dependent on the presence of a post-translation modification in the target protein." [PMID:26060076]
+comment: This term should only be used when the binding is shown to required the post-translational modification: the interaction needs to be tested with and without the PTM. The binding does not need to be at the site of the modification. It may be that the PTM causes a conformation change that allows binding of the protein to another region; this type of modification-dependent protein binding is valid for annotation to this term.
+synonym: "modified protein binding" RELATED []
+is_a: GO:0005515 ! protein binding
+created_by: pg
+creation_date: 2017-05-17T11:50:41Z
+

**Comment by pgaudet** [comment]
Fixed ubiquitin protein binding: 

id: GO:0031593
-name: polyubiquitin binding
+name: polyubiquitin modification-dependent protein binding
 namespace: molecular_function
-def: "Interacting selectively and non-covalently with a polymer of ubiqutin." [GOC:mah]
-synonym: "multiubiquitin binding" RELATED []
-is_a: GO:0043130 ! ubiquitin binding
+def: "Interacting selectively and non-covalently with a protein upon poly-ubiquitination of the target protein." [GOC:pg]
+is_a: GO:0140030 ! modification-dependent protein binding
 

 [Term]
 id: GO:0036435
-name: K48-linked polyubiquitin binding
+name: K48-polyubiquitin modification-dependent protein binding
 namespace: molecular_function
-def: "Interacting selectively and non-covalently and non-covalently with a polymer of ubiquitin formed by linkages between lysine residues at position 48 of the ubiquitin monomers." [GOC:al, PMID:20739285]
-is_a: GO:0031593 ! polyubiquitin binding
+def: "Interacting selectively and non-covalently with a protein upon poly-ubiquitination formed by linkages between lysine residues at position 48 in the target protein." [GOC:al, PMID:20739285]
+is_a: GO:0031593 ! polyubiquitin modification-dependent protein binding
 created_by: rfoulger
 creation_date: 2013-09-18T14:51:06Z


 [Term]
 id: GO:0070530
-name: K63-linked polyubiquitin binding
+name: K63-polyubiquitin modification-dependent protein binding
 namespace: molecular_function
-def: "Interacting selectively and non-covalently and non-covalently with a polymer of ubiquitin formed by linkages between lysine residues at position 63 of the ubiquitin monomers." [GOC:mah, PMID:15556404, PMID:17525341]
-is_a: GO:0031593 ! polyubiquitin binding
+def: "Interacting selectively and non-covalently with a protein upon poly-ubiquitination formed by linkages between lysine residues at position 63 in the target protein." [GOC:mah, PMID:15556404, PMID:17525341]
+is_a: GO:0031593 ! polyubiquitin modification-dependent protein binding

 [Term]
 id: GO:0071795
-name: K11-linked polyubiquitin binding
+name: K11-polyubiquitin modification-dependent protein binding
 namespace: molecular_function
-def: "Interacting selectively and non-covalently and non-covalently with a polymer of ubiquitin formed by linkages between lysine residues at position 11 of the ubiquitin monomers." [GOC:sp, PMID:18775313]
-is_a: GO:0031593 ! polyubiquitin binding
+def: "Interacting selectively and non-covalently with a protein upon poly-ubiquitination formed by linkages between lysine residues at position 11 in the target protein." [GOC:sp, PMID:18775313]
+is_a: GO:0031593 ! polyubiquitin modification-dependent protein binding
 created_by: midori
 creation_date: 2010-09-02T02:11:41Z
 
 [Term]
 id: GO:0071796
-name: K6-linked polyubiquitin binding
+name: K6-polyubiquitin modification-dependent protein binding
 namespace: molecular_function
-def: "Interacting selectively and non-covalently and non-covalently with a polymer of ubiquitin formed by linkages between lysine residues at position 6 of the ubiquitin monomers." [GOC:sp, PMID:17525341, PMID:20351172]
-is_a: GO:0031593 ! polyubiquitin binding
+def: "Interacting selectively and non-covalently with a protein upon poly-ubiquitination formed by linkages between lysine residues at position 6 in the target protein." [GOC:sp, PMID:17525341, PMID:20351172]
+is_a: GO:0031593 ! polyubiquitin modification-dependent protein binding
 created_by: midori
 creation_date: 2010-09-02T02:13:07Z
 
@@ -587346,7 +587345,7 @@ name: linear polyubiquitin binding
 namespace: molecular_function
 def: "Interacting selectively and non-covalently with a linear polymer of ubiquitin. Linear ubiquitin polymers are formed by linking the amino-terminal methionine (M1) of one ubiquitin molecule to the carboxy-terminal glycine (G76) of the next." [GOC:bf, GOC:PARL, PMID:23453807]
 synonym: "M1-linked ubiquitin chain binding" EXACT [PMID:23453807]
-is_a: GO:0031593 ! polyubiquitin binding
+is_a: GO:0043130 ! ubiquitin binding
 created_by: bf
 creation_date: 2014-08-06T11:10:26Z

**Comment by nataled** [comment]
Was the duplication of "and non-covalently" intentional?

**Comment by pgaudet** [comment]
probably not :) thanks for pointing out

**Comment by pgaudet** [comment]
In fact it was in the old definition ! (as you can see by the '-' sign at the beginning of the line.

**Comment by nataled** [comment]
I lose. My apologies.

**Comment by pgaudet** [comment]
As discussed in 
https://github.com/geneontology/go-annotation/issues/1586
I will create 
'glycosylated region binding' (similar to 'proline-rich region binding),
Proposed def: Interacting selectively and non-covalently with a glycosylated region of a protein.
Proposed parents:
    protein binding + carbohydrate-derivative protein binding.

- Pascale

**Comment by pgaudet** [comment]
New term: 
+id: GO:0140081
+name: glycosylated region protein binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with a glycosylated region of a protein." [GOC:pg]
+is_a: GO:0005515 ! protein binding
+is_a: GO:0097367 ! carbohydrate derivative binding
+created_by: pg
+creation_date: 2017-07-25T10:58:31Z
