### ISSUE TITLE
Add check for identical definitions in ontology file?

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12815]
Hi @cmungall 

Stemming from https://github.com/geneontology/go-ontology/issues/12814
There were 2 terms in the ontology with identical definitions (likely a results of copy-paste):

[Term]
id: GO:0043946
name: positive regulation of catalytic activity in other organism involved in symbiotic interaction
namespace: biological_process
def: "Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of enzyme activity in a second organism, where the two organisms are in a symbiotic interaction." [GOC:mtg_pamgo_17jul06, GOC:tb]

[Term]
id: GO:0052199
name: negative regulation of catalytic activity in other organism involved in symbiotic interaction
namespace: biological_process
def: "Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of enzyme activity in a second organism, where the two organisms are in a symbiotic interaction." [GOC:mtg_pamgo_17jul06, GOC:tb]

I fixed GO:0043946, but I’m a bit surprised that we don’t have a check in place to detect identical definitions. Because if there are any, one of them has to be incorrect (or we need to merge terms). Similar to how we have a check for identical class labels. Thanks!

**Comment by paolaroncaglia** [comment]
@mcourtot , @ukemi 
Labeling as editors-discussion as I believe it should be fairly quick to discuss and agree on having such a check - or reporting on whether it exists already but was not working. Thanks.

**Comment by cmungall** [comment]
Someone has a thanksgiving project...

 * ERROR: duplicate-defs: GO:0046920 GO:0046921 --> Catalysis of the transfer of an L-fucosyl group from GDP-beta-L-fucose to an acceptor molecule to form an alpha-(1->6) linkage.
 * ERROR: duplicate-defs: GO:1990526 GO:1990527 --> A multiprotein complex that is involved in the transcription regulation of mating genes in the yeast S. cerevisiae.
 * ERROR: duplicate-defs: GO:0034413 GO:0071970 --> The chemical reactions and pathways resulting in the formation of (1->3)-beta-D-glucans, compounds composed of glucose residues linked by (1->3)-beta-D-glucosidic bonds, found in the walls of ascospores.
 * ERROR: duplicate-defs: GO:0003422 GO:0060536 --> The process in which the anatomical structures of cartilage are generated and organized.
 * ERROR: duplicate-defs: GO:0099622 GO:0099624 --> The process in which ions are transported across the plasma membrane of a cardiac muscle cell such that the membrane potential changes in the repolarizing direction, toward the steady state potential. For example, the repolarization during an action potential is from a positive membrane potential towards a negative resting potential.
 * ERROR: duplicate-defs: GO:0070472 GO:0070473 GO:0070474 --> Any process that modulates the frequency, rate or extent of uterine smooth muscle contraction.
 * ERROR: duplicate-defs: GO:0061001 GO:0061003 --> Any process that modulates the rate, frequency, or extent of dendritic spine morphogenesis, the process in which the anatomical structures of a dendritic spine are generated and organized. A dendritic spine is a protrusion from a dendrite and a specialized subcellular compartment involved in synaptic transmission.
 * ERROR: duplicate-defs: GO:0010767 GO:0010768 --> Any process that modulates the frequency, rate or extent of transcription from an RNA polymerase II promoter as a result of a UV damage stimulus.
 * ERROR: duplicate-defs: GO:0071530 GO:0071531 --> A process of protein complex assembly in which the arrangement and bonding together of the set of components that form the protein complex is mediated by an FHA (forkhead-associated) domain interaction.
 * ERROR: duplicate-defs: GO:0071325 GO:0071329 --> Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a sucrose stimulus.
 * ERROR: duplicate-defs: GO:0099626 GO:0099635 --> Regulation of presynaptic cytosolic calcium ion concentrations via the directed movement of calcium ions across the plasma-membrane into the cytosol via the action of a voltage-gated calcium ion channel.  This is the first step in synaptic transmission
 * ERROR: duplicate-defs: GO:0071989 GO:1990975 --> The directed movement of a protein to a specific location at the spindle pole body.
 * ERROR: duplicate-defs: GO:0001005 GO:0001157 --> The function of binding to a specific DNA sequence motif in a type 1 RNA polymerase III (Pol III) promoter in order to recruit the Pol III recruiting factor TFIIIB to the promoter. For type 1 Pol III promoters, this requires both TFIIIA and TFIIIC.
 * ERROR: duplicate-defs: GO:0010167 GO:0080033 --> Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a nitrate stimulus.
 * ERROR: duplicate-defs: GO:0071020 GO:0071021 GO:0071022 --> A spliceosomal complex that is formed following the second splicing event and contains the spliced product, the excised intron, and three snRNPs, including U5.
 * ERROR: duplicate-defs: GO:0061396 GO:0061398 --> Any process that modulates the frequency, rate or extent of transcription from an RNA polymerase II promoter in response to an copper ion stimulus.
 * ERROR: duplicate-defs: GO:0030148 GO:0090159 --> The chemical reactions and pathways resulting in the formation of sphingolipids, any of a class of lipids containing the long-chain amine diol sphingosine or a closely related base (a sphingoid).
 * ERROR: duplicate-defs: GO:0043927 GO:0070480 --> The chemical reactions and pathways resulting in the breakdown of the transcript body of a nuclear-transcribed mRNA that occurs when the ends are not protected by the 5'-cap.
 * ERROR: duplicate-defs: GO:0001119 GO:0001120 GO:0034367 --> The acquisition, loss, or modification of macromolecules within a complex, resulting in the alteration of an existing complex.
 * ERROR: duplicate-defs: GO:0010663 GO:0010664 --> Any process that increases the rate or extent of striated muscle cell apoptotic process, a form of programmed cell death induced by external or internal signals that trigger the activity of proteolytic caspases whose actions dismantle a striated muscle cell and result in its death.
 * ERROR: duplicate-defs: GO:0044618 GO:0044619 --> The process in which an organism effects a change in the relaxation of smooth muscle in the uterus of a second organism.
 * ERROR: duplicate-defs: GO:0035401 GO:0035409 --> The modification of histone H3 by the addition of a phosphate group to a tyrosine residue at position 41 of the histone.
 * ERROR: duplicate-defs: GO:0071583 GO:0071584 --> Any process that stops, prevents, or reduces the frequency, rate or extent of the directed movement of zinc ions (Zn2+) from one side of a membrane to the other.
 * ERROR: duplicate-defs: GO:0010883 GO:0010888 --> Any process that modulates the rate, frequency or extent of lipid storage. Lipid storage is the accumulation and maintenance in cells or tissues of lipids, compounds soluble in organic solvents but insoluble or sparingly soluble in aqueous solvents. Lipid reserves can be accumulated during early developmental stages for mobilization and utilization at later stages of development.
 * ERROR: duplicate-defs: GO:0010889 GO:0010891 --> Any process that modulates the rate, frequency or extent of sequestering of triglyceride. Triglyceride sequestration is the process of binding or confining any triester of glycerol such that it is separated from other components of a biological system.
 * ERROR: duplicate-defs: GO:0090216 GO:0090217 --> Any process that decreases the frequency, rate or extent of the catalysis of the reaction: ATP + 1-phosphatidyl-1D-myo-inositol 4-phosphate = ADP + 1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate.
 * ERROR: duplicate-defs: GO:0052573 GO:0052574 --> The chemical reactions and pathways involving UDP-D-galactose, a substance composed of D-galactose in glycosidic linkage with guanosine diphosphate.
 * ERROR: duplicate-defs: GO:0001113 GO:0001127 --> Any process involved in the melting of the DNA hybrid of the core promoter region within the transcriptional closed complex of an RNA polymerase II preinitiation complex (PIC) to produce an open complex where the DNA duplex around the transcription initiation site is unwound to form the transcription bubble.
 * ERROR: duplicate-defs: GO:0001131 GO:0001140 --> Interacting selectively and non-covalently with a sequence of DNA that is in cis with and relatively close to a core promoter for a bacterial-type RNA polymerase in order to modulate transcription by bacterial-type RNA polymerase. The transcription factor may or may not also interact selectively with a protein or macromolecular complex.
 * ERROR: duplicate-defs: GO:0098872 GO:0099579 --> G-protein coupled neurotransmitter receptor activity occurring in the postsynaptic membrane that is part of a GPCR signaling pathway that positively regulates ion channel activity in the postsynaptic membrane.
 * ERROR: duplicate-defs: GO:0060331 GO:0060332 --> Any process that decreases the rate, frequency or extent of a response to interferon-gamma. Response to interferon gamma is a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an interferon-gamma stimulus.
 * ERROR: duplicate-defs: GO:0034675 GO:0034676 --> An integrin complex that comprises one alpha6 subunit and one beta1 subunit.
 * ERROR: duplicate-defs: GO:0034409 GO:0071969 --> The chemical reactions and pathways involving (1->3)-beta-D-glucans, compounds composed of glucose residues linked by (1->3)-beta-D-glucosidic bonds, found in the walls of ascospores.
 * ERROR: duplicate-defs: GO:0044758 GO:0044759 --> Any process in which a symbiont organism modulates the frequency, rate or extent of synaptic transmission, communication from a neuron to a target (neuron, muscle, or secretory cell) across a synapse, in its host organism.
 * ERROR: duplicate-defs: GO:0098881 GO:0098967 --> The exocytic fusion of neurotransmitter receptor containing vesicles with a plasma-membrane resulting in the integration of NT receptors with the plasma-membrane enabling them to participate in neurotransmitter reception.  This process includes tethering and docking steps that prepare vesicles for fusion.
 * ERROR: duplicate-defs: GO:0001130 GO:0001216 GO:0001217 --> Interacting selectively and non-covalently with a specific DNA sequence in order to modulate transcription by bacterial-type RNA polymerase. The transcription factor may or may not also interact selectively with a protein or macromolecular complex.
 * ERROR: duplicate-defs: GO:0090450 GO:1990003 --> Catalysis of the reaction: IDP + H2O = IMP + phosphate.
 * ERROR: duplicate-defs: GO:0000339 GO:0098808 --> Interacting selectively and non-covalently with a 7-methylguanosine (m7G) group or derivative located at the 5' end of an RNA molecule.
 * ERROR: duplicate-defs: GO:0044866 GO:0044869 --> The process in which an organism effects a change in symbiont exo-alpha-sialidase activity, the catalysis of the hydrolysis of peptide bonds in a protein.
 * ERROR: duplicate-defs: GO:0098635 GO:0098636 --> Any protein complex that is capable of carrying out some part of the process of cell-cell adhesion.
 * ERROR: duplicate-defs: GO:0098551 GO:0098560 --> The side (leaflet) of the late endosome membrane that faces the cytoplasm.
 * ERROR: duplicate-defs: GO:0003371 GO:0003372 --> Any cellular process that results in the specification, formation or maintenance of polarized cytoskeletal structures that contribute to the cell polarity of a migrating ameboid cell.
 * ERROR: duplicate-defs: GO:0047113 GO:0047770 --> Catalysis of the reaction: an aldehyde + acceptor + H2O = a carboxylate + reduced acceptor.
 * ERROR: duplicate-defs: GO:0061046 GO:0061047 --> Any process that modulates the rate, frequency, or extent of the process in which a highly ordered sequence of patterning events generates the branched structures of the lung, consisting of reiterated combinations of bud outgrowth, elongation, and dichotomous subdivision of terminal units.
 * ERROR: duplicate-defs: GO:0006073 GO:0044042 --> The chemical reactions and pathways involving glucans, polysaccharides consisting only of glucose residues.
 * ERROR: duplicate-defs: GO:0046484 GO:0052838 --> The chemical reactions and pathways involving oxazole or thiazole, five-membered heterocyclic ring structures containing an oxygen and a sulfur, respectively, in the 1-position and a nitrogen in the 3-position.
 * ERROR: duplicate-defs: GO:0071580 GO:0071581 --> Any process that modulates the frequency, rate or extent of the directed movement of zinc ions (Zn2+) from one side of a membrane to the other.
 * ERROR: duplicate-defs: GO:0008416 GO:0051750 --> Catalysis of the isomerization of 3,5-dienoyl-CoA to 2,4-dienoyl-CoA.
 * ERROR: duplicate-defs: GO:0001116 GO:0065004 --> The aggregation, arrangement and bonding together of proteins and DNA molecules to form a protein-DNA complex.
 * ERROR: duplicate-defs: GO:0003416 GO:0098867 --> The increase in size or mass of an endochondral bone that contributes to the shaping of the bone.
 * ERROR: duplicate-defs: GO:0080072 GO:0080089 --> Catalysis of the transfer of a sinapoyl group to a nitrogen atom on the spermidine molecule.
 * ERROR: duplicate-defs: GO:0042203 GO:0046252 --> The chemical reactions and pathways resulting in the breakdown of toluene, a volatile monoaromatic hydrocarbon found in crude petroleum and petroleum products.
 * ERROR: duplicate-defs: GO:0070908 GO:0070909 --> Catalysis of the reaction: tyrosine(out) + tyramine(in) = tyrosine(in) + tyramine(out).
 * ERROR: duplicate-defs: GO:0098924 GO:0098940 --> Cell-cell signaling from postsynapse to presynapse, across the synaptic cleft, mediated by nitric oxide.
 * ERROR: duplicate-defs: GO:0002661 GO:0010932 --> Any process that modulates the frequency, rate, or extent of B cell tolerance induction.
 * ERROR: duplicate-defs: GO:0009308 GO:0044106 --> The chemical reactions and pathways involving any organic compound that is weakly basic in character and contains an amino or a substituted amino group, as carried out by individual cells. Amines are called primary, secondary, or tertiary according to whether one, two, or three carbon atoms are attached to the nitrogen atom.
 * ERROR: duplicate-defs: GO:0070454 GO:0070455 --> Any process that activates or increases the frequency, rate or extent of the chemical reactions and pathways resulting in the formation of heme.
 * ERROR: duplicate-defs: GO:1902731 GO:1902732 --> Any process that stops, prevents, or reduces the frequency, rate or extent of the multiplication or reproduction of chondrocytes by cell division, resulting in the expansion of their population. A chondrocyte is a polymorphic cell that forms cartilage.
 * ERROR: duplicate-defs: GO:0071249 GO:0071250 --> Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a nitrate stimulus.
 * ERROR: duplicate-defs: GO:0044488 GO:0044489 --> Any process in which an organism effects a change in the frequency, rate or extent of the activity of a voltage-gated sodium channel in another organism.
 * ERROR: duplicate-defs: GO:1990626 GO:1990627 --> The membrane organization process that joins two mitochondrial outer membranes to form a single membrane.
 * ERROR: duplicate-defs: GO:0060406 GO:0060407 --> Any process that increases the rate, frequency or extent of penile erection. Penile erection is the hardening, enlarging and rising of the penis which often occurs in the sexually aroused male and enables sexual intercourse. Achieved by increased inflow of blood into the vessels of erectile tissue, and decreased outflow.
 * ERROR: duplicate-defs: GO:0009744 GO:0010555 --> Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a sucrose stimulus.
 * ERROR: duplicate-defs: GO:0070631 GO:1990944 --> Any process in which a spindle pole body is transported to, or maintained in, a specific location. A spindle pole body is a type of microtubule organizing center found in fungal cells.
 * ERROR: duplicate-defs: GO:0099582 GO:0099583 --> Any neurotransmitter receptor activity that is involved in regulating the concentration of calcium in the presynaptic cytosol.
 * ERROR: duplicate-defs: GO:0016763 GO:0052636 --> Catalysis of the transfer of a pentosyl group from one compound (donor) to another (acceptor).
 * ERROR: duplicate-defs: GO:0044841 GO:0044842 --> The lumen of a gut granule, a lysosome-related organelle contained within the intestinal cells of the nematode C. elegans.
 * ERROR: duplicate-defs: GO:1990091 GO:1990092 --> The sodium-dependent hydrolysis of proteins into smaller polypeptides and/or amino acids by cleavage of their own peptide bonds.

This is over-reporting, it doesn't attempt to clump, if a definition is shared by N classes then every permutation is reported 

We should definitely have this check. I can commit this check whenever you like. I'd rather do it sooner. Obv once committed releases will be blocked until all dupes are fixed.

**Comment by mcourtot** [comment]
Put them in a spreadsheet at https://docs.google.com/spreadsheets/d/12j3dwON67zLWOhMklfeLRMWY14XAAWzdEhvNdXNpNks/edit#gid=0

If we can each do a few each time we edit we should be done quickly. Please indicate the ones that have been fixed in the last column.

**Comment by paolaroncaglia** [comment]
I made a start. We may want to split the list among us, to avoid duplication of effort...
@mcourtot @ukemi @tberardini @dosumis

**Comment by paolaroncaglia** [comment]
Done a few more.
@dosumis if that helps I've noted "DOS" in the last column for rows/terms that are in your ID range, thanks :-)

**Comment by dosumis** [comment]
Ta

**Comment by tberardini** [comment]
Ok.  Fixed everything that was left EXCEPT for the ones labeled DOS.

**Comment by paolaroncaglia** [comment]
Added Melanie, Tanya and myself as assignees for stats purposes.

**Comment by dosumis** [comment]
Fixed.

**Comment by paolaroncaglia** [comment]
Brilliant, thanks @dosumis !
Handing over to @cmungall to implement the check then.
As an aside, looking at the duplicates (and at ensuing tickets) supports the view that it's safer to have ontology requests in a tracker than via TermGenie Free Form.

**Comment by mcourtot** [comment]
There are a few tickets still one - can we wait until they're closed to implement the check? Otherwise release will break.

https://github.com/geneontology/go-ontology/issues/12825
https://github.com/geneontology/go-ontology/issues/12821

**Comment by cmungall** [comment]
I'll do as soon as #12825 is closed (the other is closed now)

**Comment by tberardini** [comment]
https://github.com/geneontology/go-ontology/issues/12825 is closed.  @cmungall, you can proceed with the check implementation.

**Comment by tberardini** [comment]
Check implemented. Caught its first duplicate too!  I'll close this issue.

**Comment by tberardini** [comment]
For the record, the dupe caught was:

ERROR: duplicate-defs: GO:0099626 GO:0099635 --> Regulation of presynaptic cytosolic calcium ion concentrations via the directed movement of calcium ions across the plasma-membrane into the cytosol via the action of a voltage-gated calcium ion channel.  This is the first step in synaptic transmission
