### ISSUE TITLE
ntr post-anaphase array, microtubule end

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12831]
post-anaphase array, microtubule end

(I dont think I can do with TG, because there is no PAA microtubule as there was for the other microtubule tip/end terms)

**Comment by ValWood** [comment]
PMID:11007487

**Comment by dosumis** [comment]
Would it be enough to make the part relation to PAA?

post-anaphase array, microtubule end
intesection_of: 'microtubule end'
intesection_of: 'part of post-anatphase microtubule array

Otherwise can be done in TG with two steps:

post-anaphase array microtubule
intesection_of: microtubule
intesection_of: 'part of post-anatphase microtubule array

post-anaphase array, microtubule end
intesection_of: 'microtubule end'
intesection_of: 'part of post-anatphase array microtubule

**Comment by ValWood** [comment]
sounds good to me

**Comment by dosumis** [comment]
Added via TG as outlined in previous comment.
