### ISSUE TITLE
NTR: proteaphagy

### ISSUE THREAD

**Issue by srengel** [geneontology/go-ontology#12839]
def: The autophagic clearance of 26S proteasomes; homeostatic mechanism within the ubiquitin system that modulates proteolytic capacity and eliminates damaged particles. 

PMID: 27477278 | PMID: 26670610

parentage: is_a child of GO:0006914 autophagy

**Comment by srengel** [comment]
note to self: CUE5, HSP42

**Comment by ukemi** [comment]
Hi Stacia,
It seems like this is a type of macroautophagy in which the target is engulfed by an autophagosome. Do you agree?
-D

**Comment by ukemi** [comment]
Hi Stacia,

I went ahead and made it as follows. I think it makes sense. I made the logical def use the most generic proteasome complex as input. If you see any issues with this, let me know and I will edit the term.
+ [Term]
+id: GO:0061816
+name: proteaphagy
+namespace: biological_process
+def: "The macroautophagy process that clears 26S proteasomes; homeostatic mechanism within the ubiquitin system that modulates proteolytic capacity and eliminates damaged particles." [GOC:dph, GOC:se, PMID:26670610, PMID:27477278]
+is_a: GO:0016236 ! macroautophagy
+intersection_of: GO:0016236 ! macroautophagy
+intersection_of: has_input GO:0000502 ! proteasome complex
+created_by: dph
+creation_date: 2016-12-01T20:21:28Z

-D

**Comment by srengel** [comment]
thanks David.  sorry i just needed more time to get to this.  happy with how you did it.

**Comment by ukemi** [comment]
No problem Stacia. It got automatically classified as a type of aggrephagy, 'selective degradation of protein aggregates by macroautophagy'. The logical definition of aggrephagy is a type of autophagy that has an input of a protein complex. Since the proteasome is a protein complex, it gets slotted here. If you think this is incorrect, I can remove the logical definition of aggrephagy, but it seems ok to me based on the refs that you provided.

-D
