### ISSUE TITLE
GO:0070651 - nonfunctional rRNA decay parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12856]
After reviewing PomBase mRNA catabolic processes  annotations at the weekend,

It seems like
GO:0070651 - nonfunctional rRNA decay (biological_process)
should be part of GO:0071027 nuclear RNA surveillance

https://github.com/pombase/curation/issues/1204
https://github.com/geneontology/go-ontology/issues/12847

@krchristie  is that correct?

**Comment by krchristie** [comment]
Since one of the two papers (PMID:19390089) cited for the def of **GO:0070651 - nonfunctional rRNA decay** says this:
"In the wild-type strain, NRD substrates were observed in both the nucleus and cytoplasm, suggesting that they are exported to the cytoplasm at least to some extent."

I don't think it would be OK to place "**nonfunctional rRNA decay**" (aka NRD) under "**_nuclear_** RNA surveillance"

**Comment by ukemi** [comment]
And it goes on to say that the gene is involved in the cytoplasmic clearance.

**Comment by krchristie** [comment]
The other paper cited in the def (PMID:17188037) says this:
"In budding yeast, conversion of 20S pre-rRNA to 18S rRNA is a wholly cytoplasmic event (Venema and Tollervey, 1999). This, in conjunction with our observation that defective mutant 18S rRNAs are found in 80S particles (Figure 2), indicates that 18S NRD must occur in the cytoplasm."

so definitely not always nuclear.
