### ISSUE TITLE
Add synonyms to ‘centriole’

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#12858]
Raised during revision of the cilia GO paper:

@JohnvanDam: “Daughter centriole is not a term in GO. Since it basically is a centriole I don't think it needs its own term. Maybe synonym of centriole?”

@krchristie : “It isn't a separate term, though I could see the utility for it since there are often differing localizations of proteins to either the mother or daughter centriole. But, I never felt motivated to request this, so I think we could have both "daughter centriole" and "mother centriole" as some sort of related or narrow synonyms to make it clear that this is the best term available.”

Therefore, I added ‘mother centriole’ and ‘daughter centriole’ as narrow synonyms of ‘centriole’.

**Comment by ValWood** [comment]
There is a precedent for this   for yeast, we do have old and new SPB
The spindle pole body that exists in a cell prior to spindle pole body duplication. An old spindle pole body segregates to the daughter cell upon mitosis, and lacks active proteins involved in signaling exit from mitosis. 
PMID:15132994

We requested this for the reasons you mentioned (differential localization of  SPB signalling proteins).
Although there may be a better way to do this because the only annotations currently are the differentially localized proteins.....

**Comment by krchristie** [comment]
I see your point @ValWood, but I think I'm fine with not being able to annotate to the granularity of mother vs daughter centriole.
