### ISSUE TITLE
Regualtion term for GO:0060378

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#12869]
Hello,

Would it be possible to add a positive and negative regulation to GO:0060378:regulation of brood size for the PMID:19575016?

Thank you
Rossana

**Comment by vanaukenk** [comment]
Hi Rossana,

I was wondering what other annotations you might be making for this paper, especially with respect to apoptotic process.

It seems that measuring brood size is a way for the authors to assess the role of CSP-2 in germ cell apoptosis.

Based on the additional biochemical experiments in the paper, do you think an annotation of CSP-2 to:

GO:2001271 (negative regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis) with annotation extensions of
occurs_in(WBbt:0006796),directly_negatively_regulates(UniProtKB:P42573)

where 
WBbt:0006796 = germ cell
UniProtKB:P42573 = CED-3

would be sufficient for capturing the biological process studied in the paper?

Thanks,
--Kimberly

**Comment by rozaru** [comment]
Hi Kimberly,

Thank you very much for your comments.

I was going to capture this biological finding by using 
GO:1990001:inhibition of cysteine-type endopeptidase activity involved 
in apoptotic process.

However, I would like also to capture the brood size phenotype that is 
shown in table 1.  In this table, they also  report that the double 
mutant of ced-9 and csp-2 is sterile which I am capturing with 
GO:1905516:positive regulation of fertilization. I think annotating both 
phenotypes would provide extra information.

I hope it makes sense.

Thank you

Rossana

**Comment by vanaukenk** [comment]
Hi Rossana,

Yes, I think that GO:1990001:inhibition of cysteine-type endopeptidase activity involved in apoptotic process would also be fine to use.

Wrt the brood size annotations, I guess I would just try to capture the underlying process rather than the phenotype.  Along those same lines, do you think that ced-9 and csp-2 play a role in the actual process of fertilization or is the sterility of the double mutant actually the combined effect of reducing activity of two negative regulators of germ line apoptosis?

Thanks,
--Kimberly

**Comment by tberardini** [comment]
Is creation of the two new requested terms still warranted?

**Comment by vanaukenk** [comment]
Hi,
In the use cases for these terms, annotating to the positive and negative regulation terms, rather than the regulation parent term (GO:0060378), makes the most sense since measurement of brood size would necessarily inform the directionality of the effect. 
However, wherever possible, I would encourage curators to annotate to a more informative BP term that illustrates how the reduced brood size phenotype comes about.

**Comment by ukemi** [comment]
+1  to @vanaukenk 
We want to encourage capturing the mechanism of the regulatory process as much as possible. This is essential to be able to 'declare' something regulatory in LEGO.

**Comment by tberardini** [comment]
Added:

 [Term]
+id: GO:0090727
+name: positive regulation of brood size
+namespace: biological_process
+def: "Any process that increases brood size. Brood size is the number of progeny that survive embryogenesis and are cared for at one time." [GOC:rz]
+is_a: GO:0060378 ! regulation of brood size
+created_by: tanyaberardini
+creation_date: 2016-12-19T15:07:32Z
+
+[Term]
+id: GO:0090728
+name: negative regulation of brood size
+namespace: biological_process
+def: "Any process that decreases brood size. Brood size is the number of progeny that survive embryogenesis and are cared for at one time." [GOC:rz]
+is_a: GO:0060378 ! regulation of brood size
+created_by: tanyaberardini
+creation_date: 2016-12-19T15:07:32Z
