### ISSUE TITLE
DNA clamp loader activity vs 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12876]
I wanted to update our Elg complex annotations based on:
https://github.com/geneontology/go-ontology/issues/12863

previously we had a MF 
DNA clamp loader activity
activity annotation (with contributes to) for complex subunits  (this will still be valid for some subunits, because some are members of the   RFC-loader)

but the unloading term is a process for some reason:
DNA clamp unloading
should it be made into a MF term?

**Comment by hattrill** [comment]
Hi Val,

I mulled this one over myself. It's a bit tricky and I came up with no answer - my D.mel examples are "at-arms-length-assays" rather than direct. In many cases the actual activity of unloading isn't really assayed, just the persistence of the clamp in the absence of an unloader. It would be good to have the corresponding MF, as in some cases this has activity has been directly assayed, but recent discussions seem to not favour this sort of MF-BP pattern.

There - that's absolutely no help at all!

**Comment by ValWood** [comment]
Lets see what David says....maybe here there is a case for both?

But if we know it is a single step process we can infer that its the function?  
Except that for cohesin loading we use process terms. 

This one will seem odd because the subunits which are part of the loader and the unloader will sometimes have a MF annotation for loading and a BP for unloading.....

**Comment by ukemi** [comment]
I though that the unloading was a process because it consisted of both getting out of the 'bracelet' and the 'safety catch'.

**Comment by ukemi** [comment]
Do you have a reference or a review that describes an unloading activity?

**Comment by ValWood** [comment]
The refs will be the same as for the unloading complex
#12863
Refs:PMID:27664980 & PMID:23499004
(I just wanted to make 
I don't know the mechanism of PCNA  (clamp) loading or unloading, other than its an ATPase....

**Comment by ValWood** [comment]
https://www.google.co.uk/search?q=PCNA+loading&espv=2&biw=1059&bih=675&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjtn7LB-oDRAhXKPRoKHeHXDbwQ_AUIBigB#tbm=isch&q=PCNA+unloading&imgrc=vPgIUKspNYkrCM%3A

**Comment by ValWood** [comment]
for PCNA  the loading is a MF in GO, but the unloading is a process?

**Comment by ukemi** [comment]
I suspect it was made a process because in PMID:23499004 it says that the unloading must take place repeatedly. Does it make sense to keep the process and then make a function 'DNA clamp unloader' activity that is part of the process?

Or is it just multiple executions of a function? There is only one IMP annotation and several IEAs to the process term. Should we obsolete and create the function, or keep the process and create the additional function?

**Comment by ValWood** [comment]
this seems to be done? maybe via another ticket
