### ISSUE TITLE
TPV protein import into nucleus, docking

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12886]
protein import into nucleus, docking

has parentage to 

cellular protein complex assembly

which seem incorrect?

**Comment by tberardini** [comment]
Seems ok from the definition:

A **protein complex assembly process that** contributes to protein import into the nucleus, and that results in the association of a cargo protein, a carrier protein such as an importin alpha/beta heterodimer, and a nucleoporin located at the periphery of the nuclear pore complex.

**Comment by ValWood** [comment]
But wouldn't this interpretation of docking make the cargo a component of the nuclear pore?
Or did I misunderstand what it means?
What is the complex here?
(the cargo is already in complex with the importin before docking)

**Comment by tberardini** [comment]
Full stanza:

[Term]
id: GO:0000059
name: protein import into nucleus, docking
namespace: biological_process
def: "A protein complex assembly process that contributes to protein import into the nucleus, and that results in the associatio\
n of a cargo protein, a carrier protein such as an importin alpha/beta heterodimer, and a nucleoporin located at the periphery o\
f the nuclear pore complex." [GOC:isa_complete, **GOC:mah**, PMID:14570049, PMID:7878057, PMID:9126736]
synonym: "protein docking during protein import into nucleus" EXACT []
synonym: "protein docking during protein transport from cytoplasm to nucleus" EXACT []
synonym: "protein docking during protein-nucleus import" EXACT []
synonym: "protein transport from cytoplasm to nucleus, docking" EXACT []
synonym: "protein-nucleus import, docking" EXACT []
is_a: GO:0043623 ! cellular protein complex assembly
relationship: part_of GO:0006606 ! protein import into nucleus

@mah11 ? Help?

**Comment by mah11** [comment]
> @mah11 ? Help?

Not convinced I can help; this isn't an area of biology I know beyond undergrad/occasional seminar level. I suspect my initials are among the def xrefs solely because I implemented some text edits, probably during the isa_complete push.

I do vaguely recall that there were some BP terms that didn't have obvious is_a links to make, so we mentally extended the concept of "complex assembly" to avoid is_a orphans. This could well have been one of those terms. I still don't know what else it could have as an is_a parent in BP; to the extent I understand, it's an interaction between two complexes that only transiently forms a bigger complex. Is there a term for that??

**Comment by ValWood** [comment]
That makes sense.
The term was added 2001. The relation was added 2008
The def was revised 2010

it has only 3 experimental annotations in  16 years. Maybe it needs to be obsoleted and represented as a protein protein interaction if it should be captured at all?

**Comment by ValWood** [comment]
I deleted the PomBase annotation which was an ISS to a SGD annotation that no longer exists....
It was violating annotation intersect rules.

**Comment by tberardini** [comment]
I'll go with obsoletion.  The three annotations are one each from RGD, Flybase, and Uniprot, vintage 2006/7.

**Comment by tberardini** [comment]
Sent today:
Dear all,

The proposal has been made to obsolete

GO:0000059  protein import into nucleus, docking


Full discussion here:
https://github.com/geneontology/go-ontology/issues/12886

There are only 3 experimental annotations to this term, one each from RGD, Flybase, and Uniprot, vintage 2006/7.

***Unless I hear of any objection, I'll obsolete the term in two weeks, on Jan. 25th 2017.***

Thanks,

Tanya

**Comment by slaulederkind** [comment]
"...bidirectional transport across the NPC proceeds by repeated docking and undocking reactions." (PMID:7736573)  I don't see the problem with this term.  Maybe the definition should indicate the temporary nature of the whole complex.

**Comment by tberardini** [comment]
From @mah11's comment: " I still don't know what else it could have as an is_a parent in BP; to the extent I understand, it's an interaction between two complexes that only transiently forms a bigger complex. Is there a term for that??"

I think the problem that @ValWood raises is that it's not really representing a 'stable' protein complex assembly process - the 'complex' is transient.

Is_a parent ideas, @slaulederkind ?

**Comment by ValWood** [comment]
Also, I don't think its "complex assembly" even if it is a complex. Its just "binding". The annotated objects  here are only binding partners. Everything which binds to something  to assemble a complex isn't involved in "protein complex assembly" per. se. only that the interaction is favourable. Otherwise, if we followed this to it's logical conclusion everything which binds to another protein to form a complex would be involved in "complex assembly". 

David proposed that we have a general discussion about this. See @ukemi comment in this ticket: https://github.com/geneontology/go-ontology/issues/12846

**Comment by slaulederkind** [comment]
Maybe a new term like "protein complex docking" needs to be the parent.

**Comment by tberardini** [comment]
What if we made it an is_a child of 'protein complex binding'?

is_a: GO:0043623 ! cellular protein complex assembly
relationship: part_of GO:0006606 ! protein import into nucleus

CHANGE to

is_a: GO:0032403 ! protein complex binding
relationship: part_of GO:0006606 ! protein import into nucleus

Then the definition would become: [_my comment_]

A protein complex **binding** [_(instead of assembly)_] process that contributes to protein import into the nucleus, and that results in the association of a cargo protein, a carrier protein such as an importin alpha/beta heterodimer, and a nucleoporin located at the periphery of the nuclear pore complex.

@ValWood , @slaulederkind : would that work?

**Comment by slaulederkind** [comment]
I'm not savvy to "cross-product" type relationships, but GO:0032403 ! "protein complex binding" is a molecular function term and GO:0000059 "protein import into nucleus, docking" is a biological process term.  Are those type of is_a relationships made these days?

**Comment by tberardini** [comment]
Argh.  You're right, Stan.  Scratch that idea. 

If we create a new BP term called 'protein complex docking', what would that term's is_a parent be and how would we define it?

**Comment by slaulederkind** [comment]
How about "single-organism cellular process" (GO:0044763) as parent of 'protein complex docking' with definition "The temporary attachment of a protein complex to a target protein or protein complex. Docking requires only that the proteins come close enough to interact and adhere."?

A second option could be using "protein targeting to nucleus" (GO:0044744) as an is_a parent for GO:0000059 "protein import into nucleus, docking".

**Comment by tberardini** [comment]
The term is already part_of  "protein targeting to nucleus" (GO:0044744). I think that's the appropriate relationship. 

@ValWood @mah, what do you think of the @slaulederkind 's suggested is_a parent new term and parentage to 'single-organism cellular process'?

**Comment by slaulederkind** [comment]
"protein import into nucleus" (GO:0006606) and "protein targeting to nucleus" (GO:0044744) are sibling terms.  Could one be a part_of parent and one be an is_a parent?

**Comment by ValWood** [comment]
I still don't see how its a process, its an molecular function- binding unless there are multiple steps......

**Comment by ValWood** [comment]
I can't find anything in PunMed of by Goole that describes a process of "docking".
Most of the things I have found which refer to docking at the nuclear pore are about viral proteins.

The wikipedia page implies the mechanism of transport through the pore is still unclear, but it likely involved a concentration gradient:

This page
http://www.ks.uiuc.edu/Research/npc/
says
This evidence is consistent with the FG-Nups forming the filaments of the NPC, to which transport complexes **may dock** in the initial and final stages of transport. Finally, the FG-Nups have been shown to be highly disordered and contain almost no secondary structure ([PNAS 100:2450]). Localization of nups in the yeast NPC ([JCB 148:635]) shows that many of the FG-Nups occupy the central pore region of the NPC, through which the transport complexes pass. All this evidence points toward intimate interactions which must take place between FG-Nups and transport receptors to make transport successful.

This implies that if docking does occur it is only binding....

**Comment by slaulederkind** [comment]
All biological processes are a series of molecular functions.  If you go deeply granular with process terms, you will end up with a function term.  If GO wants to keep MF and BP totally separate, maybe "protein import into nucleus, docking" is too granular for process.

**Comment by ValWood** [comment]
That sounds much more aligned with normal annotation conventions.

As Stan mentioned, there is an issue with

GO:0006606  protein import into nucleus GO:0044744 protein targeting to nucleus

but the current arrangement I see in QuickGO is
GO:0044744 protein targeting to nucleus
--GO:0006606 protein import into nucleus

This is incorrect because targeting is "directing proteins towards the nucleus"

I still have a problem with the targeting processes in general, but thats a larger miniproject issue:

https://github.com/geneontology/go-ontology/issues?q=is%3Aopen+is%3Aissue+label%3A%22targeting+and+transport%22

**Comment by tberardini** [comment]
@slaulederkind : in light of our discussion, do you still object to the term obsoletion or can you (re)annotate as suggested?

@ValWood : the targeting/import problem is indeed in the referenced miniproject and that clean up will be handled there and not in this issue

**Comment by slaulederkind** [comment]
I still like the term, but obsolete it if you must.  I'll reannotate to a parental term.

**Comment by hattrill** [comment]
Removed the FlyBase annotations.

**Comment by tberardini** [comment]
Term made obsolete.

 [Term]
 id: GO:0000059
-name: protein import into nucleus, docking
+name: obsolete protein import into nucleus, docking
 namespace: biological_process
-def: "A protein complex assembly process that contributes to protein import into the nucleus, and that results in the association of a cargo protein, a carrier protein such as an importin alpha/beta heterodimer, and a nucleoporin located at the periphery of the nuclear pore complex." [GOC:isa_complete, GOC:mah, PMID:14570049, PMID:7878057, PMID:9126736]
+def: "OBSOLETE. A protein complex assembly process that contributes to protein import into the nucleus, and that results in the association of a cargo protein, a carrier protein such as an importin alpha/beta heterodimer, and a nucleoporin located at the periphery of the nuclear pore complex." [GOC:isa_complete, GOC:mah, PMID:14570049, PMID:7878057, PMID:9126736]
+comment: This term was made obsolete because the transient assembly is better captured as a protein-protein association, if at all.
 synonym: "protein docking during protein import into nucleus" EXACT []
 synonym: "protein docking during protein transport from cytoplasm to nucleus" EXACT []
 synonym: "protein docking during protein-nucleus import" EXACT []
 synonym: "protein transport from cytoplasm to nucleus, docking" EXACT []
 synonym: "protein-nucleus import, docking" EXACT []
-is_a: GO:0043623 ! cellular protein complex assembly
-relationship: part_of GO:0006606 ! protein import into nucleus
+is_obsolete: true
