### ISSUE TITLE
Title of the GO file changed to "Uberon Ontology Module for GO" 

### ISSUE THREAD

**Issue by mcourtot** [geneontology/go-ontology#12900]
Reported by @sjupp:
> The dc:title in GO on Jan 5th was "Uberon Ontology Module for GO"
> http://www.ebi.ac.uk/ols/ontologies/go

I removed the lines
```
property_value: http://purl.org/dc/elements/1.1/source http://purl.obolibrary.org/obo/uberon.owl
property_value: http://purl.org/dc/elements/1.1/title "Uberon Ontology Module for GO" xsd:string
```
from the gene_ontology_write.obo file, which should propagate tomorrow 

@cmungall said those are coming in from OBO edit merging in Uberon properties and suggested to strip all metadata from imported files.

**Comment by mcourtot** [comment]
Title still "Uberon" as of Jan 9th

**Comment by cmungall** [comment]
I don't think my hypothesis about OE was correct. uberon_import.obo does not contain ontology annotations. We take care to remove all ontology annotations from the obo imports because of issues like this one with OE.

Who put it back in?

**Comment by cmungall** [comment]
> Title still "Uberon" as of Jan 9th

Are you sure?

**Comment by mcourtot** [comment]
<img width="1156" alt="screen shot 2017-01-09 at 13 55 32" src="https://cloud.githubusercontent.com/assets/2214135/21768780/5641f0cc-d673-11e6-8deb-8f7b2d0d68c0.png">

I checked the editors OBO file and the title property is not in there, so seems to be coming from somewhere during there release process?

**Comment by cmungall** [comment]
OLS stale cache?

http://www.ebi.ac.uk/ols/ontologies/go

versionIRI: http://purl.obolibrary.org/obo/go/releases/2017-01-08/go.owl

click on it - no dc:title

I assume the issue is that OLS retains the last title if no title 
present. We should really publish a new title. But may want to report a 
bug on the OLS tracker. Behavior should be first to fall back on OBO 
entry then fall back on blank or some other property.

**Comment by mcourtot** [comment]
Fixed on the OLS side. Thanks @sjupp!
