### ISSUE TITLE
urgent - missing relation telomeric heterochromatin assembly child of telomere organization?

### ISSUE THREAD

**Issue by NancyCampbell** [geneontology/go-ontology#12938]
urgent due to writing paper.

Is there a missing relationship between these two terms?

 GO:0031509 telomeric heterochromatin assembly
The assembly of chromatin into heterochromatin at the telomere.

 GO:0032200 telomere organization
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of telomeres, terminal regions of a linear chromosome that include the telomeric DNA repeats and associated proteins.

**Comment by ukemi** [comment]
Hi Nancy,

I made it a part_of telomere organization, but could make it a part of telomere assembly if you would like. You're the expert.

-David

**Comment by ValWood** [comment]
I think the reason it wasn't might be that historically we have used the term "telomeric heterochromatin" to refer to "subtelomeric heterochromatin"

(is there such a thing as telomeric heterochromatin that isn't  sub-telomeric).

 Don't we want the "telomere"  terms to refer to the telomere 'proper'

This is the outstanding ticket:

https://github.com/geneontology/go-ontology/issues/11429

I guess what we need is a good definition of the telomere and the sub-telomere. I remember asking some telomere experts and ending up  no further....I don't think they are very consistent in  their usage.....

**Comment by ValWood** [comment]
see telomere organization is defined:

GO:0032200
Name	telomere organization
Ontology	Biological Process
Definition	A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of telomeres, terminal regions of a linear chromosome that include the telomeric DNA repeats and associated proteins.

It does not include the heterochomatin  which is not  coincident with the  DNA repeats....

I don't think you can make this link?

**Comment by RLovering** [comment]
Hi Val
we have GO:1990421 subtelomeric heterochromatin which has parent GO:0000792 heterochromatin.
Definition: Heterochromatic regions of the chromosome found at the subtelomeric regions.

We also have:
GO:0031933 telomeric heterochromatin 
definition: Heterochromatic regions of the chromosome found at the telomeres.
with parents:  GO:0000792 heterochromatin and GO:0000781 chromosome, telomeric region

I don't think the definition of GO:0032200 telomere organization rules out heterochromatin.

I agree we have had this discussion before and I think the confusion arises for you because human chromosome have very long telomeres which get shorter in each mitotic cell division in most cells because most cells do not have telomerase. Whereas yeast cell all have telomerase and their telomere is considered to be just the very end of the DNA because they don't change length.

These terms exist already and we are just asking for the BP ontology to reflect the existing structure of the component ontology  

Best

Ruth

**Comment by ukemi** [comment]
The link is there now, for exactly the reason Ruth states above. If we are going to change things, we need to change component and process to be in alignment.

**Comment by NancyCampbell** [comment]
for the time being, we can update the ontology to reflect a recent review 2017 PMID 28078514

David .... yes to ....  telomeric heterochromatin assembly child of telomere assembly child of telomere organization
i.e. relation between telomeric heterochromatin assembly and telomere organization is maintained via telomere assembly

Please see a suggested tweaked definition to include histones (or better) to telomere assembly term on another thread #12940 

Suggesting a similar tweak to telomere organization also to reflect histones
current
GO:0032200 telomere organization
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of telomeres, terminal regions of a linear chromosome that include the telomeric DNA repeats and associated proteins.
new suggestion:
GO:0032200 telomere organization
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of telomeres, terminal regions of a linear chromosome that include the telomeric DNA repeats, **nucleosomal histones** and associated proteins.

PMID 28078514 author states: "Constitutive heterochromatin is formed at telomeres and their flanking subtelomeric regions to prevent homologous recombination. Subtelomeric regions also are enriched in telomeric repeat sequences, which are interspersed with some other simple repeat sequences and genes"

fig 2 in same paper
![screen shot 2017-01-19 at 13 10 05](https://cloud.githubusercontent.com/assets/12081136/22108535/7c65cd8e-de4b-11e6-8a6b-7ef9c47c495d.png)

**Comment by ValWood** [comment]
I'm confused. The image above seems to confirm that the heterochromatin is subtelomeric and is distinct from the telomere?

**Comment by ValWood** [comment]
Isn't the telomere 'proper' the region where shelterin is bound?. This is telomeric chromatin (not heterochromatin- there is no acetylation/methylation etc in this compaction).

**Comment by ukemi** [comment]
Yes, but doesn't the author say that both of the regions in the diagram are heterochromatin?

**Comment by ValWood** [comment]
It looks like imprecise use of the word heterochromatin in addition to imprecise use of the term telomere.  And probably the GO definition of heterochromtin needs tightening to include information about the histone varieties and epigenetic marks which constitute heterochromatin. 

Anyway the image and the text  are inconsistent.

I  also asked Midori to take a look too but she is away this week. Happy for the parent to be added but right now if it helps, but  I believe there is a problem here.

If you include the  heterochromatin region in the telomere term, you will never be able to separate  the gene products associated with processes and locations related to heterochromatin  from those at the "telomere proper".

I'm being picky about this because fission yeast researchers have pulled me up on referring to the heterochromatin region as "telomere", and I'm not sure that this is a fission yeast specific issue. I still think it is imprecise semantics. This is fine in a paper, but it isn't great in an ontology.

V

**Comment by ukemi** [comment]
It seems to me that we have had a lot of issues about telomeres and telomere biology in GO. Here is one that seems particularly pertinent to this discussion.
#11429 
Perhaps we need two types of heterochromatin as parts of the telomeric region, heterochromatin of the telomere proper and subtelometric heterochromatin. 
This is an important area of biology and we need to be sure to get it right for all organisms.

**Comment by RLovering** [comment]
The problem is that the yeast and human telomeres are fundamentally different. As mentioned previously. So the definition of telomere which covers both yeast and human telomeres is a problem. and you can't define the subtelomere until the telomere is defined. possibly eukaryote v prokaryote terms are required?

**Comment by hdrabkin** [comment]
From my old days: Drosp. telomeres also different ; see xhttps://www.ncbi.nlm.nih.gov/books/NBK6617/

**Comment by mah11** [comment]
Sorry, I don't think I can help with this - not enough knowledge or experience in the heterochromatin area.

The only thing I can say is that eukaryote vs. prokaryote terms will NOT help with yeast vs. metazoa - they're all eukaryotes!

**Comment by ValWood** [comment]
I was hoping you could help about the telomere definition, because I know you have had opinion on this in the past.  But I can ask some telomere experts for the fission yeast perspective. I'll ask labs who work on both fission yeast and metazoan telomeres. That should help.

**Comment by ValWood** [comment]
One of the problems is that we have a term "telomeric  region" ; that encompasses the "telomere proper" and the "telomeric/sub-telomeric  heterochromatin".  We had once had a term for telomere, it was obsoleted and the recommended replacement is "telomere cap complex". This isn't equivalent to telomere though.....

I would be happy with a  definition which represented the subtelomere and the telomere as depicted above. This seems that it would work for fission yeast and metazoa.
I asked 3 telomere experts independently for  a definition t hat would work for fission yeast and human.

**Comment by ukemi** [comment]
Keep in mind that whatever we implement, it can't only be from the fission yeast perspective. It needs to be universal. That is why I suspect that we introduced 'telomeric region'.

**Comment by ValWood** [comment]
Exactly. We should also align with SO. See the original ticket:
https://sourceforge.net/p/geneontology/ontology-requests/11254/

I think the current arrangement is nearly OK, because  we call the heterochromatin "telomeric region" IF we establish a term which refers to the  telomere proper (shelterin protected region and  tandemly repeated DNA , D-loop etc which protects the telomere from the DNA repair machinery). I am worried that if we lose this distinction of this region from the helterochromatin/subtelomeric heterochromatin parts   we will not be able to  distinguish the completely different processes and mechanisms operating in these regions. This isn't a fission yeast specific problem....it applies across organisms with telomeres.

Note:  in fission yeast recently we called the  heterochromatin region "sub telomeric heterochromatin", but based on the definition of "telomeric region" this would be included so these terms would need to merge together....

I still think we need to  consult outside experts. Probably this constitutes a mini project?

**Comment by ValWood** [comment]
This might work, its a simple solution:

https://docs.google.com/document/d/1u3UA_75ZTiEcYIK5k6abdqZ-5ibGFHyAIZ6hdtSQoVQ/edit?usp=sharing

I  will follow up with some experts...

**Comment by NancyCampbell** [comment]
I agree, and according to the definitions, how is a telomere cap complex different from the shelterin complex? is a telomere the same as a shelterin complex? or is the shelterin complex a constiutent part of the telomere (define telomere?)

does a telomere cap complex include the subtelomeric region? does it include accessory/conditionally binding proteins? if not, then does the telomere cap complex=telomere-=shelterin complex?

which begs the question: what is a telomere?

telomere cap complex
Ontology 	Cellular Component
Definition 	A complex of DNA and protein located at the end of a linear chromosome that protects and stabilizes a linear chromosome.
Comment 	Note that this term can be used in place of the obsolete cellular component term 'telomere ; GO:0005696'. Use with caution because this term refers to a specific protein complex and not a region of the chromosome.

telosome
Ontology 	Cellular Component
Definition 	A nuclear telomere cap complex that is formed by the association of telomeric ssDNA- and dsDNA-binding proteins with telomeric DNA, and is involved in telomere protection and recruitment of telomerase. The complex is known to contain TERF1, TERF2, POT1, RAP1, TINF2 and ACD in mammalian cells, and Pot1, Tpz1, Rap1, Rif1, Rif2 and Taz1 in Schizosaccharomyces. Taz1 and Rap1 (or their mammalian equivalents) form a dsDNA-binding subcomplex, Pot1 and Tpz1 form an ssDNA-binding subcomplex, and the two subcomplexes are bridged by Poz1, which acts as an effector molecule along with Ccq1.

**Comment by NancyCampbell** [comment]
Does this summarise what we have said so far (access table via link below):

[https://docs.google.com/spreadsheets/d/1q4hGj8proJnur7dsi9cCvJB-kUwFYERZAHtTlnxrhp4/edit#gid=0](url)

Here is a screenshot of the same table:
![screen shot 2017-01-24 at 11 11 11](https://cloud.githubusercontent.com/assets/12081136/22245043/e67fd1aa-e225-11e6-83dd-bb95c9976312.png)

**Comment by ValWood** [comment]
Seems to.

I think a good place to begin would be to define 
heterochromatin vs telomeric heterochromatin (these are clearly  different but how?).

Is the telomeric chromatin as highly condensed as the  heterochromatin? It seems that it can't be if the telosome/shelterin complexes act as some sort of "spacer"? I still haven't figured what it is about the telomeric chromatin that makes it "telomeric heterochromatin" rather than just "telomeric chromatin"

By contrast the  "cenp-A containing chromatin" at the centromere is not classed as "heterochromatin", but maybe this is because it contains  histone variants?

**Comment by ukemi** [comment]
I am almost certain that inactive X chromosomes are considered heterochromatic. So there certainly is a difference between generic heterochromatin and telomeric heterochromatin. I'm thinking the way we have the structure now makes sense. If we want to expand on that, it should be a separate project?

**Comment by ValWood** [comment]
The important point is that we do not have a way to distinguish between telomeric  region (including heterochromatin), and the "telomere".

**Comment by ukemi** [comment]
Yes, but currently in CC we only have telomeric region. So if we want to make the distinction, it is further ontology development than the structure that is in place. For that, it would be nice to have input from the experts.

**Comment by ValWood** [comment]
Ok that's back to the original outstanding ticket.
and future mini project.....

**Comment by ukemi** [comment]
So as far as our current structure, I think this ticket is closed. We may want to open a new mini-project ticket to expand the telomere part of the ontology. I would be very interested in this as it relates to my cancer-research interest.
