### ISSUE TITLE
EC:1.14.12 is being used as an xref in multiple enzyme activities

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#12948]
These appear to be coming in via UM-BBD_reactionIDs.
The term EC:1.14.12 appears to be a very generic term, much like a EC:1.14.12.-
There are around 30 terms with EC:1.14.12 as an xref.

There are EC:1.14.12.19, EC:1.14.12.17; these are unique. No problem. 

Concern: aren't xrefs suppose to be unique?

**Comment by hdrabkin** [comment]
I'll check these to see if EC2GO maps these to multiple terms

**Comment by hdrabkin** [comment]
So looking at the ec2go file; as expected, this is mapping to all children of EC:1.14.12
So these are just like if we did EC:1.14.12.- as an xref

EC:1.14.12 > GO:oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of two atoms of oxygen into one donor ; GO:0016708
EC:1.14.12 > GO:nitrobenzene 1,2-dioxygenase activity ; GO:0018603
EC:1.14.12 > GO:4-aminobenzoate 3,4-dioxygenase (deaminating) activity ; GO:0018604
EC:1.14.12 > GO:benzenesulfonate dioxygenase activity ; GO:0018606
EC:1.14.12 > GO:1-indanone monooxygenase activity ; GO:0018607
EC:1.14.12 > GO:1-indanone dioxygenase activity ; GO:0018608
EC:1.14.12 > GO:chlorobenzene dioxygenase activity ; GO:0018609
EC:1.14.12 > GO:dibenzofuran 4,4a-dioxygenase activity ; GO:0018610
EC:1.14.12 > GO:toluate dioxygenase activity ; GO:0018611
EC:1.14.12 > GO:dibenzothiophene dioxygenase activity ; GO:0018612
EC:1.14.12 > GO:9-fluorenone dioxygenase activity ; GO:0018613
EC:1.14.12 > GO:ethylbenzene dioxygenase activity ; GO:0018614
EC:1.14.12 > GO:2-indanone monooxygenase activity ; GO:0018615
EC:1.14.12 > GO:trihydroxytoluene dioxygenase activity ; GO:0018616
EC:1.14.12 > GO:4-aminobenzenesulfonate 3,4-dioxygenase (deaminating) activity ; GO:0018617
EC:1.14.12 > GO:1-naphthoic acid dioxygenase activity ; GO:0034521
EC:1.14.12 > GO:tetralin ring-hydroxylating dioxygenase activity ; GO:0034825
EC:1.14.12 > GO:N-isopropylaniline 1,2-dixoxygenase activity ; GO:0034906
EC:1.14.12 > GO:acetanilide 1,2-dioxygenase activity ; GO:0034907
EC:1.14.12 > GO:2-chloro-N-isopropylacetanilide 1,2-dioxygenase activity ; GO:0034908
EC:1.14.12 > GO:phthalate 3,4-dioxygenase activity ; GO:0034911
EC:1.14.12 > GO:diphenyl ether 2,3-dioxygenase activity ; GO:0034954

**Comment by hdrabkin** [comment]
We might need a rule that EC number used for xrefs MUST have 4 numbers, not three. Otherwise,  the mapping to a GO term is NOT unique

**Comment by hdrabkin** [comment]
see EC:6.5.1 (DNA and RNA ligase)
6.5.1.1 DNA ligase (ATP) 
6.5.1.2 DNA ligase (NAD(+))
 6.5.1.3 RNA ligase (ATP) 
6.5.1.4 RNA 3'-terminal-phosphate cyclase (ATP) 
6.5.1.5 RNA 3'-terminal-phosphate cyclase (GTP) 
6.5.1.6 DNA ligase (ATP or NAD(+))
 6.5.1.7 DNA ligase (ATP, ADP or GTP)

**Comment by krchristie** [comment]
Also, demonstrating what Chris mentioned, we have two GO terms that have Xrefs to EC:6.5.1, with a parent term that has an even more general Xref to EC, but we don't have a GO term that could uniquely map to EC:6.5.1

GO:0016886 - ligase activity, forming phosphoric ester bonds; Xref = EC:6.5
- is_a GO:0008452 - RNA ligase activity; Xref = EC:6.5.1
- is_a GO:0003909 - DNA ligase activity; Xref = EC:6.5.1

**Comment by hdrabkin** [comment]
This is ongoingly being fixed as many came in from plant enzyme project. Thought I got them all but some still pop up now and then and are usually covered by their individual tickets.

**Comment by hdrabkin** [comment]
These are still being looked at from long list to remove 3 digit EC from leaf terms.   Focusing on these two for this ticket.
EC:1.14.12.-
EC:6.5.1.-

**Comment by ValWood** [comment]
pinging @hdrabkin

**Comment by sjm41** [comment]
As of today, I don't see any terms with a EC:6.5.1.- xref, so that seems fixed.

But there are still 19 terms with inappropriate EC:1.14.12.- xref:

id: GO:0018603
name: nitrobenzene 1,2-dioxygenase activity

id: GO:0018604
name: 4-aminobenzoate 3,4-dioxygenase (deaminating) activity

id: GO:0018606
name: benzenesulfonate dioxygenase activity

id: GO:0018607
name: 1-indanone monooxygenase activity

id: GO:0018608
name: 1-indanone dioxygenase activity

id: GO:0018609
name: chlorobenzene dioxygenase activity

id: GO:0018611
name: toluate dioxygenase activity

id: GO:0018612
name: dibenzothiophene dioxygenase activity

id: GO:0018613
name: 9-fluorenone dioxygenase activity

id: GO:0018614
name: ethylbenzene dioxygenase activity

id: GO:0018615
name: 2-indanone monooxygenase activity

id: GO:0018617
name: 4-aminobenzenesulfonate 3,4-dioxygenase (deaminating) activity

id: GO:0034521
name: 1-naphthoic acid dioxygenase activity

id: GO:0034825
name: tetralin ring-hydroxylating dioxygenase activity

id: GO:0034906
name: N-isopropylaniline 1,2-dixoxygenase activity

id: GO:0034907
name: acetanilide 1,2-dioxygenase activity

id: GO:0034908
name: 2-chloro-N-isopropylacetanilide 1,2-dioxygenase activity

id: GO:0034911
name: phthalate 3,4-dioxygenase activity

id: GO:0034954
name: diphenyl ether 2,3-dioxygenase activity

**Comment by sjm41** [comment]
The remaining issues on this ticket were fixed as part of the recent enzyme review.

This is now the only (and correct) EC:1.14.12.- mapping:

 id: GO:0016708
name: oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of two atoms of oxygen into one donor
def: "Catalysis of an oxidation-reduction (redox) reaction in which hydrogen or electrons are transferred from NADH or NADPH and one other donor, and two atoms of oxygen are incorporated into one donor." [EC:1.14.12.-]
xref: EC:1.14.12.-

Closing.
