### ISSUE TITLE
f-P link glutathione hydrolase activity -> glutathione catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#12958]
glutathione hydrolase activity -> glutathione catabolic process

see
https://github.com/geneontology/go-annotation/issues/1514#issuecomment-274910478

**Comment by ukemi** [comment]
Since these reactions are defined as being bidirectional we can't make part_of links. So we either need to show that this reaction only ever proceeds in the forward direction, we need to make a direction-specific sub-type, or we can make a has_part relation if this enzyme activity is always part of glutathione catabolism and it is never catabolized by a pathway that excludes it.

**Comment by ukemi** [comment]
@cmungall  comments? Should we close this until the refactoring is done?

**Comment by ValWood** [comment]
Doesn't the comment on this term mean that the reaction only occurs physiologically in the peptidase direction?
See the linked thread above...

**Comment by ukemi** [comment]
I don't think so. @hdrabkin @deustp01  any input?

**Comment by ukemi** [comment]
@jimhu-tamu any input as well?

**Comment by ValWood** [comment]
We can close this it isn't  important if it isn't  a trivial question. We all normally co-annotate anyway.

**Comment by ukemi** [comment]
I think the F->P links in GO are much bigger that just this ticket. The bidirectional nature of most of the definitions that currently exist in GO create problems when we want to generate part_of links between enzymatic activities and pathways. But it sounds like the MF refactoring project has a plan for how we will handle all of this, so I will close this ticket.
