### ISSUE TITLE
NTR and relationships for ferroxidase complexes

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#12957]
I have created GO:1905862 ferroxidase complex in TG.

1. 
Please add 
GO:0033573 high-affinity iron permease complex
is_a GO:1905862 ferroxidase complex

2. 
Please create the following term:
GO:NEW high affinity iron exporter complex
Def: A protein complex which transports Fe(III) from the vacuole, the main storage component of intracellular free iron, into the cytoplasm in a low iron environment. 
Comment: An example of this is FET5 in Saccharomyces cerevisiae (P43561) in PMID:9413439 (inferred from direct assay).
Synonym: FET5-FTH1 high affinity iron exporter complex [NARROW]
Xref: IntAct:EBI-12592993, PMID:9413439, PMID:10608875
Relationships:
is_a GO:1905862 ferroxidase complex
part_of GO:0031166 integral component of vacuolar membrane
capable_of GO:0004322 ferroxidase activity
capable_of GO:0015091 ferric iron uptake transmembrane transporter activity
capable_of GO:0015683 high-affinity ferric iron transport
capable_of_part_of GO:0055072 iron ion homeostasis

Thanks, 
Birgit

**Comment by ukemi** [comment]
Hi @bmeldal ,

I have accepted the term in TG. Shouldn't GO:0033573 also be capable of
high-affinity ferric uptake transmembrane transporter activity?
Wouldn't your new term be capable of 'ferric iron transmembrane transporter activity', not 'high-affinity ferric uptake transmembrane transporter activity'?

high-affinity ferric uptake transmembrane transporter activity-Enables the transfer of Fe(III) from the outside of a cell to the inside of a cell across a membrane. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations.

I propose:
GO:NEW high affinity iron exporter complex
Def: A protein complex which transports Fe(III) from the vacuole, the main storage component of intracellular free iron, into the cytoplasm in a low iron environment.
Comment: An example of this is FET5 in Saccharomyces cerevisiae (P43561) in PMID:9413439 (inferred from direct assay).
Synonym: FET5-FTH1 high affinity iron exporter complex [NARROW]
Xref: IntAct:EBI-12592993, PMID:9413439, PMID:10608875
Relationships:
is_a GO:1905862 ferroxidase complex
part_of GO:0031166 integral component of vacuolar membrane
capable_of GO:0015091 ferric iron transmembrane transporter activity
capable_of_part_of GO:0015683 high-affinity ferric iron transport
capable_of_part_of GO:0055072 iron ion homeostasis

**Comment by bmeldal** [comment]
Thank you, David! 
I was checking someone else's entries and didn't spot the mix up of ferric and ferrous ions! they were all inverted... I fixed the annotation on the 2 complexes.

What I will need now:

1.
GO:0015683 high-affinity ferric iron transport
change name to high-affinity ferric ion **transmembrane** transport
to match the parent term and indicate that it is indeed a transmembrane transport

2.
GO:NEW1 high-affinity **ferrous** ion transmembrane transport
[akin to above sibling]
Def: The directed, high-affinity movement of ferrous iron (Fe(II) or Fe2+) ions from one side of a membrane to the other by means of some agent such as a transporter or pore. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations. 
xrefs: PMID:9413439, GOC:bhm
Synonym: high affinity ferrous ion transmembrane transport [EXACT]
is_a GO:0006827 high-affinity iron ion transmembrane transport

3.
GO:NEW2 high-affinity **ferrous** uptake transmembrane transporter activity
[akin to GO:0015092 high-affinity **ferric** uptake transmembrane transporter activity]
Def: Enables the transfer of ferrous iron (Fe(II) or Fe2+) ions from one side of a membrane to the other. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations.
xrefs: PMID:9413439, GOC:bhm
Synonym: high affinity ferrous uptake transmembrane transporter activity
is_a GO:0015639 ferrous iron uptake transmembrane transporter activity

4.
GO:0033573 high-affinity iron permease complex
[binds ferrous iron ions extracellularly, oxidises to ferric ions, then transports ferric iron ions]
please add:
Xref: IntAct:EBI-12592666
capable_of GO:0004322 ferroxidase activity
capable_of GO:0008198 ferrous iron binding
capable_of GO:0008199 ferric iron binding
capable_of GO:0015092 high-affinity ferric uptake transmembrane transporter activity [as you suggested!]
capable_of GO:0015683 high-affinity ferric iron transport
part_of GO:0005887 integral component of plasma membrane [replace part_of GO:0005886 plasma membrane]

5.
original request but this one transports **ferrous** iron ions so relationships need amending:

GO:NEW3 high affinity iron exporter complex 
Def: A protein complex which transports ferrous iron (Fe(III) or Fe3+) ions from the vacuole, the main storage component of intracellular free iron, into the cytoplasm in a low iron environment.
Comment: An example of this is FET5 in Saccharomyces cerevisiae (P43561) in PMID:9413439 (inferred from direct assay).
Synonym: FET5-FTH1 high affinity iron exporter complex [NARROW]
Xref: IntAct:EBI-12592993, PMID:9413439, PMID:10608875
Relationships:
is_a GO:1905862 ferroxidase complex
part_of GO:0031166 integral component of vacuolar membrane
capable_of GO:0004322 ferroxidase activity
capable_of GO:NEW2 high-affinity **ferrous** uptake transmembrane transporter activity
capable_of GO:0008198 ferrous iron binding
capable_of GO:NEW1 high-affinity **ferrous** ion transmembrane transport
capable_of_part_of GO:0055072 iron ion homeostasis

I hope I got it right this time.
Birgit

**Comment by ukemi** [comment]
OK @bmeldal 
I hope I got it all correct too! Below is a summary of the edits. Note that I changed the capable_of in processes to capable_of_part_of and I didn't need to make the capable _of ferroxidase activity because it will be inherited from the parent. Please let me know if you spot any errors!
-David

New Terms:

 [Term]
+id: GO:0061839
+name: high-affinity ferrous ion transmembrane transport
+namespace: biological_process
+def: "The directed, high-affinity movement of ferrous iron (Fe(II) or Fe2+) ions from one side of a membrane to the other by means of some agent such as a transporter or pore. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations." [GOC:bhm, PMID:9413439]
+synonym: "high affinity ferrous ion transmembrane transport" EXACT []
+is_a: GO:0006827 ! high-affinity iron ion transmembrane transport
+
+[Term]
+id: GO:0061840
+name: high-affinity ferrous iron uptake transmembrane transporter activity
+namespace: molecular_function
+def: "A ferrous iron uptake transmembrane transporter activity in which the transporter is able to bind the solute even if it is only present at very low concentrations." [GOC:bhm, PMID:9413439]
+synonym: "high affinity ferrous uptake transmembrane transporter activity" EXACT []
+is_a: GO:0015639 ! ferrous iron uptake transmembrane transporter activity
+
+[Term]
+id: GO:0061841
+name: high affinity iron exporter complex
+namespace: cellular_component
+def: "A protein complex which transports ferrous iron (Fe(III) or Fe3+) ions from the vacuole, the main storage component of intracellular free iron, into the cytoplasm in a low iron environment." [GOC:bhm, IntAct:EBI-12592993, PMID:10608875, PMID:9413439]
+comment: An example of this is FET5 in Saccharomyces cerevisiae (P43561) in PMID:9413439.
+synonym: "FET5-FTH1 high affinity iron exporter complex" NARROW []
+is_a: GO:0031166 ! integral component of vacuolar membrane
+is_a: GO:1905862 ! ferroxidase complex
+relationship: capable_of GO:0008198 ! ferrous iron binding
+relationship: capable_of GO:0061840 ! high-affinity ferrous iron uptake transmembrane transporter activity
+relationship: capable_of_part_of GO:0055072 ! iron ion homeostasis
+relationship: capable_of_part_of GO:0061839 ! high-affinity ferrous ion transmembrane transport

Changes:

 [Term]
 id: GO:0015092
-name: high-affinity ferric uptake transmembrane transporter activity
+name: high-affinity ferric iron uptake transmembrane transporter activity
 namespace: molecular_function
 def: "Enables the transfer of Fe(III) from the outside of a cell to the inside of a cell across a membrane. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations." [GOC:ai, TC:9.A.10.1.1]
 synonym: "high affinity ferric uptake transmembrane transporter activity" EXACT []
 is_a: GO:0015091 ! ferric iron transmembrane transporter activity
-relationship: part_of GO:0015683 ! high-affinity ferric iron transport
+relationship: part_of GO:0015683 ! high-affinity ferric iron transmembrane transport
 
 [Term]
 id: GO:0015093
@@ -141026,9 +141026,9 @@
 
 [Term]
 id: GO:0015683
-name: high-affinity ferric iron transport
+name: high-affinity ferric iron transmembrane transport
 namespace: biological_process
-def: "The directed, high-affinity movement of ferric (Fe(III) or Fe3+) ions into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations." [GOC:mah]
+def: "A process in which ferric (Fe(III) or Fe3+) ions are transported from one side of a membrane to the other by means of some agent such as a transporter or pore. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations." [GOC:mah]
 synonym: "high affinity ferric iron transport" EXACT []
 is_a: GO:0006827 ! high-affinity iron ion transmembrane transport
 is_a: GO:0015682 ! ferric iron transport
@@ -225939,10 +225939,14 @@
 id: GO:0033573
 name: high-affinity iron permease complex
 namespace: cellular_component
-def: "A protein complex composed of a multicopper ferroxidase that oxidizes Fe(II) to Fe(III), and a ferric iron permease that transports the produced Fe(III) into the cell. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations." [GOC:jp, PMID:16522632, PMID:8599111]
+def: "A protein complex composed of a multicopper ferroxidase that oxidizes Fe(II) to Fe(III), and a ferric iron permease that transports the produced Fe(III) into the cell. In high-affinity transport the transporter is able to bind the solute even if it is only present at very low concentrations." [GOC:jp, IntAct:EBI-12592666, PMID:16522632, PMID:8599111]
 synonym: "high affinity iron permease complex" EXACT []
-is_a: GO:0043234 ! protein complex
-is_a: GO:0044459 ! plasma membrane part
+is_a: GO:0005887 ! integral component of plasma membrane
+is_a: GO:1905862 ! ferroxidase complex
+relationship: capable_of GO:0008198 ! ferrous iron binding
+relationship: capable_of GO:0008199 ! ferric iron binding
+relationship: capable_of GO:0015092 ! high-affinity ferric iron uptake transmembrane transporter activity
+relationship: capable_of_part_of GO:0015683 ! high-affinity ferric iron transmembrane transport

**Comment by bmeldal** [comment]
I missed the hyphenation variants of 'high-affinity' in the new term to match them to the other high-affinity terms:

id: GO:0061841
-name: high affinity iron exporter complex
+name: **high-affinity** iron exporter complex
+synonym: high affinity iron exporter complex [EXACT]
+synonym: "FET5-FTH1 **high-affinity** iron exporter complex" NARROW []

Apologies for the late addition.
Birgit

**Comment by ukemi** [comment]
Done.
