### ISSUE TITLE
NTR: response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#12989]
Hello:

I am trying to create a new GO term: response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one

I have tried to do so with the TermGenie template "chemical_response_to", but TermGenie is not identifying this compound. I should note that I requested this term from CHEBI and they added it on Jan. 24, 2017. So maybe there is a lag synching TermGenie with CHEBI terms? 

The CHEBI term is: CHEBI:134269, and further note that this term is a companion to the current GO term: GO:1903013 and should receive the same definitions (but different PMID).

So, unless this will be possible with TermGenie soon, I would like to request the following term:

Name    response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one
Ontology    biological_process
Synonyms    DIF-2
Alternate IDs   None
Definition    Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one stimulus
Reference: PMID:3355503, PMID:19684855

Please let me know of any questions. 
Thanks,
Bob Dodson

**Comment by tberardini** [comment]
Hi Bob,

Yes, the new CHEBI term is not yet in the set accessed by TermGenie.  Can we wait a little bit longer for the term to trickle through the data pipelines?  It's much more reliable to get all the parentage right to use TG.

Thanks,

Tanya

**Comment by rjdodson** [comment]
Hi Tanya:

Sure, there is no rush on this. I'll just wait until the CHEBI term appears in TermGenie and then try to create the GO term with TG. Any rough idea how long a wait it might be...weeks, months? 

Thanks,
Bob

**Comment by tberardini** [comment]
@cmungall or @kltm : Do you know how often the CHEBI ontology used by TG is refreshed?  A term added on 1/24/17 and in the current version available for download is not yet usable within the TG application.  Thanks.

**Comment by cmungall** [comment]
CHEBI is released monthly. Latest Feb 2: 
ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/

The OBO build is meant to be triggered automatically
https://build.berkeleybop.org/job/build-chebi/configure

I triggered but I will retire this job and build chebi the normal way 
with the OBO pipeline

**Comment by tberardini** [comment]
Ok, will check tomorrow to see if term is available then.  Still not there right now.  Thanks for looking into this, @cmungall.

**Comment by rjdodson** [comment]
Checking today, but TG still not recognizing the CHEBI term: 
1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one

No rush from me, just following up on this.

**Comment by tberardini** [comment]
Still no joy on seeing TG recognize 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one

@cmungall - I don't think your manual trigger did its job.  Can you please check? Thanks.

**Comment by cmungall** [comment]
we're now using the central obo build, but this failed due to the size of the json file. We'll skip generating the json for now. Try again tomorrow, sorry.

**Comment by tberardini** [comment]
Will try again on Monday.  Still nothing today.

**Comment by tberardini** [comment]
@cmungall : Still no '1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one' in TG :(

**Comment by cmungall** [comment]
OK, should work tonight

**Comment by tberardini** [comment]
Thanks, Chris.  Fingers crossed.

**Comment by tberardini** [comment]
@cmungall : Nope :(

**Comment by tberardini** [comment]
Finally!

Added:

Status for commit #93401: Success

    ID: GO:1905960 Label: response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one

**Comment by rjdodson** [comment]
Hi Tanya:

Thanks for adding this GO term, this is most appreciated. However, I have one additional request here and with another term too. 

This GO term, GO:1905960, would be infinitely more useful with these synonyms:

Synonyms: response to DIF-2, response to DIF2

Similarly the companion GO term, GO:1903013 (response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one) would be better with the synonyms:

Synonyms: response to DIF-1, response to DIF1

As you can imagine given their long names, Dicty scientists almost exclusively refer to these compounds as DIF-1 and DIF-2 in the literature. 

Thanks,
Bob

**Comment by rjdodson** [comment]
Also, probably a good idea to add to the synonym of each the full name of DIF, that is:

response to differentiation-inducing factor 1

response to differentiation-inducing factor 2 

to each of the terms. Thanks!

**Comment by pfey03** [comment]
@tberardini , I can only stress how important the synonyms are! 
Would even go so far and do as primary terms the 'differentiation-inducing factor 1' or ..2. and putting the chemical names into synonyms.

If that's not agreeable, then yes, we need:

GO:1903013: response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one
synonyms: response to DIF-1, response to DIF1

GO:1905960, response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one
synonyms: response to DIF-2, response to DIF2

I looked for the terms and had a hard time finding all.
Thanks!

**Comment by tberardini** [comment]
@pfey03 sorry I haven't been able to add these as the editing procedure has switched to Protege (which I can do) but also to GitHub, where the documentation for how to do this isn't yet complete (I couldn't make the training session).  @ukemi - If you can find the time to add the requested synonyms and check in the changes, I and @pfey03 and @rjdodson would sure appreciate it.  Thanks.

**Comment by ukemi** [comment]
Hi Everyone,

Just getting around to this now and notice we have both 'response to' and 'cellular response to' terms for both of these. I assume we want synonyms for them all?

-D

**Comment by ukemi** [comment]
Actually my mistake. We only have the cellular version for 'response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one', same question though.

**Comment by pfey03** [comment]
Yes David, we need synonyms for all, wherever there is a chemical name for DIF1 / DIF-1 or DIF2/DIF-2. Many thanks!

**Comment by ukemi** [comment]
Hi Petra,

Since DIF1 and DIF2 are symbols for gene products in other organisms, I felt that I had to make them related synonyms. However, I did replace the chemical name with the full string 'differentiation-inducing factor 1/2. I hope this works ok for you. If you have any concerns, let me know.

Here is the diff:
 [Term]
 id: GO:1903013
-name: response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one
+name: response to differentiation-inducing factor 1
 namespace: biological_process
 def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one stimulus." [GO_REF:0000071, GOC:TermGenie, PMID:22365144]
 synonym: "DIF-1" RELATED []
+synonym: "response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one" EXACT []
+synonym: "response to DIF-1" RELATED []
+synonym: "response to DIF1" RELATED []
 intersection_of: GO:0050896 ! response to stimulus
 intersection_of: has_input CHEBI:64598 ! 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one
 created_by: rjd
@@ -530767,9 +530770,12 @@ creation_date: 2014-05-14T16:18:11Z
 
 [Term]
 id: GO:1903014
-name: cellular response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one
+name: cellular response to differentiation-inducing factor 1
 namespace: biological_process
 def: "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one stimulus." [GO_REF:0000071, GOC:TermGenie, PMID:22365144]
+synonym: "cellular response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one" EXACT []
+synonym: "cellular response to DIF-1" RELATED []
+synonym: "cellular response to DIF1" RELATED []
 synonym: "DIF-1" RELATED []
 intersection_of: GO:0070887 ! cellular response to chemical stimulus
 intersection_of: has_input CHEBI:64598 ! 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)hexan-1-one
@@ -585464,9 +585470,12 @@ creation_date: 2017-02-22T12:03:16Z
 
 [Term]
 id: GO:1905960
-name: response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one
+name: response to differentiation-inducing factor 2
 namespace: biological_process
 def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one stimulus." [GO_REF:0000071, GOC:rjd, GOC:TermGenie, PMID:19684855, PMID:3355503]
+synonym: "response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one" EXACT []
+synonym: "response to DIF-2" RELATED []
+synonym: "response to DIF2" RELATED []
 intersection_of: GO:0050896 ! response to stimulus
 intersection_of: has_input CHEBI:134269 ! 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one
 created_by: tberardini

-D

**Comment by pfey03** [comment]
Hi David,
Thanks, looks almost fine! Just 2 questions:

1) in GO:1903014, what is the extra 3rd line in: ?
+synonym: "cellular response to DIF-1" RELATED []
+synonym: "cellular response to DIF1" RELATED []
synonym: "DIF-1" RELATED []

2) Could you please add the 'cellular' corresponding term to GO:1905960 response to differentiation-inducing factor 2?
GO:NEW 
-name: cellular response to 1-(3,5-dichloro-2,6-dihydroxy-4-methoxyphenyl)pentan-1-one
+name: cellular response to differentiation-inducing factor 2

Makes more sense to be complete.

Many thanks, really appreciate all. 
Greetings from Germany!

**Comment by ukemi** [comment]
Hi Petra,

The third line is a synonym that was already there, so I didn't touch it. I'd be happy to add the cellular term as well. If you would like. 

Greetings from snowy Maine!

-D

**Comment by pfey03** [comment]
yes, please add! 

nice an sunny here, so much more spring!
