### ISSUE TITLE
NTR: replication fork processing at tRNA genes

### ISSUE THREAD

**Issue by loganmccurry** [geneontology/go-ontology#12980]
GO: replication fork processing at tRNA genes
Definition: A process that promotes the progress of the DNA replication fork at natural replication fork pausing sites within the eukaryotic tRNA transcription unit. 
Aspect: Biological Process
Child term of GO:0031297 replication fork processing. GO:0090001 replication fork arrest at tRNA locus is a similar GO term but does not state the promotion of progress with tRNA.
PMID:22426535 "The DNA helicase Pfh1 promotes fork merging at replication termination sites to ensure genome stability" specifically Fig. 2 in the organism S. pombe.

I am a CACAO student.

**Comment by tberardini** [comment]
Would 'replication fork processing at tRNA locus' work?  Similar to

replication fork processing at rDNA locus
amigo.geneontology.org/amigo/term/GO:0034065

**Comment by loganmccurry** [comment]
Yes, absolutely! Thank you for the quick response, and I appreciate the suggestion.

**Comment by ValWood** [comment]
We should aim to use annotations  extensions , if a  term represents the *exactly* same process as the parent.

Since Pfh1 promotes termination at all sites,  a better way to annotate would be:

DNA replication processing occurs_at tRNA(SO:xxxxx) or  specific termination site (SO:xxx)

We should also merge the existing term
"replication fork processing at rDNA locus"
(I think I requested this historically before I realised that it was not separate processes)
Ideally we would supply the SO ID for the replication barrier as the extension.
All of the experimental annotations for "replication fork processing at rDNA locus"
are PomBase (3), or SGD (1).

First, would also like to check with @krchristie  that this would be correct, and these are the same process occurring at different genomic locations.

@mah11 may also know....

**Comment by mah11** [comment]
> @mah11 may also know....

nope, sorry, my understanding of replication fork processing is fairly superficial

**Comment by krchristie** [comment]
can't provide much help either, my understanding of replication fork processing is also fairly superficial

**Comment by tberardini** [comment]
Hi Logan,

I don't remember what software you (CACAO) use for annotation.  Can you use annotation extensions?  If so, I'd recommend capturing the information in the paper as Val suggests since she states that the **replication fork processing** process itself is exactly the same, the target is what differs.

Tanya

@ValWood :  I'll look at merging.

@srengel : could you look at the 1 annotation of SGD to **replication fork processing at rDNA locus** please and see if it is amenable to Val's way of annotation?

**Comment by loganmccurry** [comment]
Hi, Tanya! My class format does not specify whether we can or cannot use annotation extensions, so I will contact my professor regarding the possibility. Thanks again for all of the help!

**Comment by tberardini** [comment]
Hi Logan,

Great!  Keep me posted. I hope you're enjoying the class.

**Comment by ValWood** [comment]
if you can't when the data comes through to PomBase, we can add.

Best wishes,

Val

**Comment by tberardini** [comment]
Hi @loganmccurry : any news?  Can we close this request or can we assist further? Thanks.

**Comment by loganmccurry** [comment]
Hi, Tanya! I'm so sorry about the delay. I think my professor has been out, as I have not heard back from my inquiry. I do have class tomorrow so I should have an answer by then. I'll be sure and respond to this as soon as I get the clarification.

**Comment by loganmccurry** [comment]
Finally have an update! I checked and our program does not yet allow for extensions to be used with GO terms. Thanks again for being so patient. - Logan

**Comment by tberardini** [comment]
@loganmccurry : Thanks for the update.  I suggest that you annotate as Val suggests to the term:

DNA replication processing 
or 
replication fork processing.

Val or another Pombase curator will add the necessary extensions when your annotations are incorporated into GO/Pombase.

@ValWood : I've merged 'replication fork processing at rDNA locus' into 'replication fork processing'
