### ISSUE TITLE
Proximal promoter region

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#13002]
Could we clarify the definition of GO:0000987 'core promoter proximal region sequence-specific DNA binding' with regards to how large this region is?

Maybe it could be aligned with the SO definition?

SO: proximal_promoter_element
SO_0001668
Definition: DNA segment that ranges from about -250 to -40 relative to +1 of RNA transcription start site, where sequence specific DNA-binding transcription factors binds, such as Sp1, CTF (CCAAT-binding transcription factor), and CBF (CCAAT-box binding factor). 

It’s usually quite difficult to determine from a paper if they are using the core promoter, proximal promoter or regulatory region and this will help.

Thanks.

**Comment by ukemi** [comment]
@krchristie  comments?

**Comment by krchristie** [comment]
When we created this term, I did not feel it was possible to come up with a definition of the size of the promoter proximal region that applied across all RNAP II for all relevant taxa. My recollection is that the size is quite different between cerevisiae and mammalian species.

Does the SO term cite a reference?

**Comment by ukemi** [comment]
PMID:12515390 and PMID:9679020

**Comment by krchristie** [comment]
As the parent term of both bacterial type and RNAP II type terms, this term **GO:0000987 'core promoter proximal region sequence-specific DNA binding'** is really general. I wonder if we should mark this as part of the "Do NOT manually annotate" set since it seems one should always know whether one is annotating bacterial versus eukaryotic transcription, and I think that for eukaryotic transcription, one could safely assume RNAP II for any paper talking about regulation of specific protein coding genes. Researchers of other RNA polymerases are going to specify which one they are studying, especially if it's one of the wacky exceptions like where RNAP I transcribes a few protein coding genes in Trypanosomes (if I recall the organism correctly). @ukemi - Do you have thoughts on the idea of marking this term as inappropriate for manual annotation?

**counts of direct annotations to this term and its descendants:**
- (4847)	RNA polymerase II core promoter proximal region sequence-specific DNA binding
- **(265)	core promoter proximal region sequence-specific DNA binding**
- (117)	bacterial-type RNA polymerase core promoter proximal region sequence-specific DNA binding
- (28)	RNA polymerase I upstream control element sequence-specific DNA binding
- (15)	RNA polymerase II core promoter proximal region sequence-specific DNA binding, bending

The SO term referred to "SO: proximal_promoter_element (SO_0001668)" seems to be defined specifically for RNAP II, based on both of the cited references, which may be inappropriate as I think these distances may be incorrect for bacterial transcription.

I will consider whether I can clarify the definition **RNA polymerase II core promoter proximal region sequence-specific DNA binding (GO:0000978)**, which is the term you're probably really interested in anyway.

**Comment by ValWood** [comment]
I agree that "Do NOT manually annotate"   would be useful here...
We include this on our local list:
https://curation.pombase.org/dumps/latest_build/pombe-embl/supporting_files/GO_terms_excluded_from_pombase.txt
because you *can* always make a more specific annotation.

**Comment by krchristie** [comment]
The SO definition that Rachael quoted seems odd to me. This fairly small range from -250 to -40 might be OK for for RNAP II genes in cerevisiae, though I think that even cerevisiae has proximal promoter regions that extend further upstream than this. In mammals, I my recollection is that this distance is not big enough to cover the normal range of RNAP II proximal promoters in mammals. 

> SO: proximal_promoter_element
> SO_0001668
> Definition: DNA segment that ranges from about -250 to -40 relative to +1 of RNA transcription start site, where sequence specific DNA-binding transcription factors binds, such as Sp1, CTF (CCAAT-binding transcription factor), and CBF (CCAAT-box binding factor).

**Comment by ValWood** [comment]
Could "proximal promoter" be defined in a way which is not size dependent?
For example, I presume it could be stated that it is always in the intergenic region before the adjacent protein coding gene?

**Comment by krchristie** [comment]
I don't know you could always say it's the intergenic region. Some divergently transcribed cerevisiae genes are quite close together. I'm not sure I'd want to say that the promoter elements were confined to the intergenic region.

**Comment by ValWood** [comment]
is typically in the intergenic region before the adjacent protein coding gene?

**Comment by pgaudet** [comment]
Hopefully this will be clarified with the MF refactoring... 

I am working with the GREEKC group to get expert input in the definition of these terms 
http://greekc.org/objectives/

The current version of the proposal is to define promoter regions depending on whether their activity is orientation-dependent ('proximal') or not ('enhancer'). The distance from the transcription start site does not seem as relevant as the data showed a few years back, and varies between species, so the distance should not be part of the definitions. 

One last point: GREEKC also plans to work with SO to improve the definition and the hierarchy of a few terms based on most current knowledge. 

Thanks, Pascale

**Comment by RLovering** [comment]
BTW as you might expect there will also be a parent term for promotor and enhancer - ie regulatory region - for expts where the orientation information is unknown

Ruth

**Comment by pgaudet** [comment]
Hello, 

Following discussions with the GREEKC folks (@colinlog @RLovering, Astrid and Marcio), I will merge the 'proximal', 'distal/enhancer' terms, and change the labels to 'cis regulatory region', since it's not possible to have a clear distinction. 

These are the changes I will make: 


term | # EXP annotations | merge into | # EXP annotations | new label |  
-- | -- | -- | -- | -- | --
'enhancer sequence-specific DNA binding' | 67 | 'proximal promoter sequence-specific DNA binding' | 111 | cis-regulatory region   sequence-specific DNA binding'
'bacterial-type RNA polymerase enhancer   sequence-specific DNA binding' | 5 | 'bacterial-type proximal promoter sequence-specific DNA binding' | 25 | bacterial cis-regulatory region   sequence-specific DNA binding'
RNA polymerase I enhancer   sequence-specific DNA binding' | 0 | RNA polymerase I upstream control element sequence-specific DNA binding' | 4 | RNA polymerase I cis-regulatory   region sequence-specific DNA binding'
RNA polymerase II distal enhancer   sequence-specific DNA binding' | 183 | 'RNA polymerase II proximal promoter sequence-specific DNA binding' | 935 | RNA polymerase II cis-regulatory   region sequence-specific DNA binding'
polymerase   III regulatory region sequence-specific DNA binding' | NA |   | RNA polymerase III cis-regulatory   region sequence-specific DNA binding'



Thanks, Pascale

**Comment by colinlog** [comment]
Super Pascale.

;-)

**Comment by RLovering** [comment]
Hi Pascale
I would like to have time to get the information associated with >170 specific annotations created by UCL changed to occurs_at SO annotation extensions, although I realise that the occurs_at relation is still under discussion
I guess if Alex is able to add these AEs to the current annotations then when the merge is completed the AEs will be appropriately assigned.
Thanks
Ruth
@alexsign

**Comment by pgaudet** [comment]
@RLovering @alexsign Can I go ahead with this ?

**Comment by alexsign** [comment]
@RLovering @pgaudet not really. I've checked validity of annotation extensions to update yesterday and they still failing.

**Comment by pgaudet** [comment]
@alexsign @RLovering Can you remind me what you need ? you want to state 'occurs at SO proximal region'?

**Comment by alexsign** [comment]
@RLovering @pgaudet annotations is updated in our database now, sorry for delay.

**Comment by RLovering** [comment]
yes please do
