### ISSUE TITLE
response to cholecystokinin

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13007]
I would like to see "response to cholecystokinin” and “cellular response to cholecystokinin” added to the GO ontology under the parent terms “response to peptide hormone” (GO:0043434) and “cellular response to peptide hormone stimulus (GO:0071375), respectively.  The definitions could be “Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a cholecystokinin stimulus.” and "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a cholecystokinin stimulus.” Examples can be found in PMID:14622258.  NOTE: TermGenie wanted to make the parents chemical in nature.  I think it is more appropriate to have the peptide hormone terms as parents.

**Comment by ukemi** [comment]
I added them this way:

 [Term]
+id: GO:0061847
+name: response to cholecystokinin
+namespace: biological_process
+def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a cholecystokinin stimulus." [PMID:14622258]
+is_a: GO:0043434 ! response to peptide hormone
+intersection_of: GO:0050896 ! response to stimulus
+intersection_of: has_input PR:000005110 ! cholecystokinin
+
+[Term]
+id: GO:0061848
+name: cellular response to cholecystokinin
+namespace: biological_process
+def: "Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a cholecystokinin stimulus." [PMID:14622258]
+is_a: GO:0071375 ! cellular response to peptide hormone stimulus
+intersection_of: GO:0051716 ! cellular response to stimulus
+intersection_of: has_input PR:000005110 ! cholecystokinin

Note that the logical definitions only give us partial classification because we are missing the information that the PRO classes are peptide hormones. As a result, I had to assert the relationships to the peptide hormone terms. This is still unsatisfying to me and has happened in other cases. @cmungall any comments?
