### ISSUE TITLE
 MP GO:0019564 aerobic glycerol catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13034]
GO:0019564 aerobic glycerol catabolic process
add
GO:0006091 generation of precursor metabolites and energy
?

**Comment by ukemi** [comment]
Hmmm. This term is not well defined with respect to the actual pathway it represents. Do you think the pathway always includes 'glycolytic process from glycerol' and/or 'oxidative phosphorylation'? If not, do you think it always generates ATP? I'm happy to add the parent, but since we have already started on the glycolysis stuff, I'd like to do better if we can. From looking at the web, it looks like some organisms can get there without using the glycolytic pathway, but since it is 'aerobic' maybe it always includes the latter.

@deustp01  any ideas?

**Comment by ValWood** [comment]
doh,

I just need to use the child term
http://www.ebi.ac.uk/QuickGO/term/GO:0019588

**Comment by ValWood** [comment]
I mean http://www.ebi.ac.uk/QuickGO/term/GO:0061613

**Comment by ValWood** [comment]
actually are

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0019564
and
ttp://www.ebi.ac.uk/QuickGO/term/GO:0061613
different?

**Comment by ValWood** [comment]
suggest merge
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0019564
and
ttp://www.ebi.ac.uk/QuickGO/term/GO:0061613

as this must describe the pathway whereby glycerol enters the glycolytic pathway?

**Comment by ukemi** [comment]
I'm not certain these are always equivalent. Aren't there other ways of breaking down glycerol in the presence of oxygen?

**Comment by ValWood** [comment]
OK in case there are, add GO:0061613 as a child of GO:0019564 will do until we know (unless Peter knows)

**Comment by ukemi** [comment]
?
Why would the glycolytic process always be considered aerobic? It ends with pyruvate.

**Comment by ValWood** [comment]
Yes ignore this totally! This gene should be annotated to  both in yeast (presumably) but concurrently.

**Comment by deustp01** [comment]
The way we handled molecules like fructose was to define a process "glycolytic metabolism of [x]" that comprised the molecular functions needed to convert [x] to an intermediate of core glycolysis and from there to pyruvate. Core glycolysis is not aerobic: the NAD+ can be regenerated from the NADH that is generated as a byproduct of glycolysis either through reactions specific to an aerobic environment or via fermentation reactions that can be aerobic or anaerobic.

I don't remember enough about yeast metabolism to know immediately whether glycerol can be fitted into this framework. In mammals (humans), it can, via generation of glycerol phosphate. Also in humans, the aerobic - anaerobic distinction gets weird because the kind of conditions that might deplete a cell of oxygen are probably different from the ones that would provide it with excess glycerol to metabolize. Yeast should be different in this.

**Comment by ValWood** [comment]
Ignore this one. Nothing is incorrect it's only a  yeast specifc specificity issue, which won't worry  the yeast community   right now from a GO annotation perspective, can be addressed when we do the pathway detail...
