### ISSUE TITLE
‘plasma lipoprotein particle’ vs. generic ‘lipoprotein particle’ terms

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#13037]
Stemming from https://github.com/geneontology/go-ontology/issues/11504#issuecomment-275157252 

GO:0071827 ‘plasma lipoprotein particle organization’ and children (including ‘plasma lipoprotein particle clearance’) should probably be edited to refer to generic ‘lipoprotein particle’. Most of the current manual experimental annotations are to children terms that do not have ‘plasma’ in their label anyway. Where necessary, annotation extensions to the Uberon term for ‘plasma’ could be added.

**Comment by paolaroncaglia** [comment]
When addressing this, please keep in mind @RLovering's concerns:

"I am not convinced that we should remove the plasma lipoprotein particle name. It makes sense to group HDL, LDL, VLDL, chylomicron etc under a common parent, there is a correlation between the levels of these proteins. Or have I missed something. It seems like there going to be lipoprotein particles which are not plasma lipoprotein particles grouped with HDL, LDL, VLDL, chylomicron. The proteins associated with processes associated with the individual types of plasma lipoprotein particles (only 19 annotated to the assembly term) may not have a role in other lipoprotein particle processes, but the numbers of proteins associated with the individual subtypes of plasma lipoprotein particles are much lower (currently between 2 and 10). Consequently, the revision will mean that HTP functional analysis is unlikely to detect enrichment of the assembly term for subtypes of plasma lipoprotein particles because of the low number of proteins annotated to these processes, and would be unlikely to detect enrichment of lipoprotein particle assembly because of the large number of proteins which are involved in the assembly of non-plasma lipoprotein particles.

Please confirm whether or not the proposal will leave subtypes of plasma lipoprotein particles grouped with very unrelated particles."

(My reply: "My proposal is not a definitive resolution, rather a reminder that work is needed to make representation of these terms more consistent, now that we also have non-plasma-specific terms.")

**Comment by ukemi** [comment]
I tend to agree that we need terms specifying plasma lipoprotein particles. Looking at these:

Look at ‘plasma lipoprotein particle organization’ + children, and edit if/where needed
Look at ‘plasma lipoprotein particle clearance’ + children, and edit if/where needed

it looks like they are ok and the children are all plasma lipoprotein particles. I will double-check, but clearance terms all refer to removal of the particles from the circulation, so if there are annotations that aren't to plasma particles, the annotations are incorrect. I see the same with the organization terms. Although not specified in the names (eg. high-density lipoprotein particle), the ones I have looked at so far all refer to plasma particles in the definitions.

**Comment by ukemi** [comment]
@RLovering  Do we really want to add plasma to the label of these terms? In keeping with the practice that the terms are named by the conventions that the community uses, it seems like the names given in the ontology are consistent. Can you please look and advise? I think things look ok to me. If there are errors, it is at the point of annotation.

**Comment by ukemi** [comment]
I just double-checked the terms and definitions of the children of plasma lipoprotein particle. They all refer to plasma lipoprotein particles, so I am going to close this ticket and assume this was already cleaned up at some point. I don't think we should add the plasma wording to the children because then we would not be using what appear to be the common phrases used by biologists.

**Comment by deustp01** [comment]
@RLovering 's concern, ("it seems like there going to be lipoprotein particles which are not plasma lipoprotein particles grouped with HDL, LDL, VLDL, chylomicron") I guess, was that dropping "plasma" could allow this group of functionally related extracellular particles to get lumped with unrelated lipoprotein structures that are not extracellular. But I can't think of any examples. Biologists have managed to keep cytosolic lipid droplets distinct from HDL, LDL, chylomicrons, et al. with no prefix. What other structures (or perhaps, what other taxa) am I overlooking?

The other concern, that any regrouping would obscure the interpretation of gene expression assays, seems wrong to me, for the same reason that redrawing the boundaries of a pathway to ensure that is detected i such an assay seems wrong - boundaries are already somewhat arbitrary, and consciously adjusting them in response to assay outcomes creates much bigger problems. (This is a strong reaction because I am regularly tempted that way myself.)

**Comment by ukemi** [comment]
Agreed. The definitions of these terms seem to alleviate any problems: A lipoprotein particle with a high density (typically 1.063-1.21 g/ml) and a diameter of 5-10 nm that contains APOAs and may contain APOCs and APOE; found in blood and carries lipids from body tissues to the liver as part of the reverse cholesterol transport process. 

The ontology looks correct with respect to the generic particles, the plasma particles and their children. Any issue would be at the level of an annotation ticket.
