### ISSUE TITLE
drug transporter binding

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13069]
I would like to see “drug transporter binding” added to GO under the parent term “protein binding” (GO:0005515).  The definition could be something like “Interacting selectively and non-covalently with a drug transporter protein.”  Examples: PMID:23403943

**Comment by ukemi** [comment]
Hi Stan. We have decided to no longer add these kinds of binding terms because with the new modeling paradigm and the new molecular function refactoring, all binding will only be expressed in the context of either a more global function or process that gives it context. 

I am mentioning @thomaspd here in case he has more to add.
