### ISSUE TITLE
adaptor protein binding

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13068]
I would like to see “adaptor protein binding” added to GO under the parent term “protein binding” (GO:0005515).  It would be the reciprocal relationship of “protein binding, bridging” (GO:0030674).  The definition could be something like “Interacting selectively and non-covalently with one or more specific sites on an adaptor protein.”  Synonym: “adapter protein binding” Examples: PMID:17675467, 20623582, 25586189

**Comment by ukemi** [comment]
Hi Stan. We have decided to no longer add these kinds of binding terms because with the new modeling paradigm and the new molecular function refactoring, all binding will only be expressed in the context of either a more global function or process that gives it context. 

I am mentioning @thomaspd here in case he has more to add.
