### ISSUE TITLE
MP:  many protein complexes no longer have protein complex parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13096]
anaphase-promoting complex
no longer has parentage to "protein complex"

I realise there are changes occurring in this area (I thought that macromolecular complex was going to become "protein containing complex" and "protein complex" was merging into "protein containing complex"?).

The current change means that we are not picking up many old mappings to "protein complex" which would normally be filtered as redundant...

others affected
GO:0048188 - Set1C/COMPASS complex
GO:0070772 - PAS complex

this might be because the complex changes are in progress, but while  "protein complex" exists, these should be descendants of it...

**Comment by ukemi** [comment]
After the merge, these will all become protein-containing complex. I will do this merge by the end of the week. We started to do it at the workshop, but didn't have time to finish. It is more complicated than it appears on the surface. All of the terms that use 'protein complex', like 'protein complex organization' must first be merged into terms like 'macromolecular complex organization' and then the ones that don't have macromolecular counterparts need to be renamed and redefined. It will take a while and I need to have a good chink of time because I don't want to have to do it piecemeal.

**Comment by cmungall** [comment]
When we have design patterns this kind of refactoring can be largely 
automated

**Comment by ValWood** [comment]
OK, I thought it was maybe in progress. I'll close this and open if there are any oddities when you finish...

**Comment by ukemi** [comment]
Thanks Val. I plan to do it all on Thursday. That gives me Friday to fix anything I break. :)

**Comment by hattrill** [comment]
Hi, I'm not seeing this in the ontology. Is it still being worked on?

**Comment by ukemi** [comment]
Still haven't done it. I need to have a big enough block of time.
