### ISSUE TITLE
GO:0035974 ! meiotic spindle pole body and GO:0090619 ! meiotic spindle pole

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#13106]
Should there be a part_of relationship between these?
 
How does one decide which to use during annotation?

**Comment by ValWood** [comment]
Hi Jim,

Immediately I thought there should be,  and it was until recently but 
2016-11-04	Deleted	RELATION	part of GO:0072687 (meiotic spindle)

This is because the spindle is not *always* part of the spindle (and the spindle pole is always part of the spindle). The spindle pole body exists throughout the cell cycle, and the spindle only at mitosis/meiosis. The meiotic spindle pole body specifically has different roles as it develops into the leading edge of the forespore.

The spindle pole is also slightly broader than spindle pole. It also includes the astral and polar microtubules (although this is not fully reflected in the ontology, polar microtubules *are* a descendant  of spindle pole).

For annotation purposes I have never needed to use the "spindle pole" term directly as it should always be possible to annotate more deeply.

That said, this  completely illustrates the problem with has_part. Once the  the deletion of the part_of relation filters through to PomBase,  our "spindle pole body" annotations will no longer propagate to "spindle". The only way to deal with this will be to co-annotate 200+ "spindle pole body" terms to "spindle". @cmungall is there something in the pipeline for this. I know we have talked about it periodically?

**Comment by ValWood** [comment]
Actually it isn't quite as simple as propagating, its more complicated. Components join and leave the spindle pole body throughout the cell cycle. So really, only the gene products annotated as "mitotic spindle pole body" occurs  "during mitosis" would require the "mitotic spindle"  annotation (this might seem strange but the "mitotic spindle pole body is defined as a SPB which is part of the mitotic cell cycle, not strictly mitotic).

**Comment by ukemi** [comment]
@tberardini I seem to remember the spindles in plants are different and don't have classic spindle pole bodies. Is this true? This would address the issue in this ticket as well as in the other one that is referenced.

**Comment by tberardini** [comment]
@ukemi 

" In most animals and fungal cells, spindle microtubules nucleate from centrosomes or spindle pole bodies. Plant cells lack such structured microtubule organizing centers, and some of their microtubules appear to nucleate from near the nuclear envelope, but very little is known about spindle formation in plants"

http://www.plantcell.org/content/20/10/2544.full

**Comment by ukemi** [comment]
Although in the other direction, I think based on Val's comment and the reference abopve, we cannot make links in the ontology between these terms.
