### ISSUE TITLE
NTR: amyloid-beta complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13128]
Name: amyloid-beta complex

Def: Protein complex involved in modulation of signaling and synaptic function in the brain, predominantly in the cerebral cortex and hippocampus. Forms dimers and multimers of protein 40 and protein 42 splice variants of the amyloid beta A4 protein. Mostly found in the extracellular space with a small proportion occurring as membrane-bound species. Influences synaptic plasticity through various receptors, mediates dendritic spine loss leading to decreased synapse density, inhibits long-term potentiation (LTP) and enhances long-term depression (LTD). Soluble form is the main pathogenic species linked to Alzheimer's disease. 

Comment: An example is Protein 40 of APP (P05067-PRO_0000000093) in PMID:18568035 (inferred by direct assay).

Synonyms:
[I don't know how many combinations we need to catch the way people spell "amyloid beta"!]
amyloid beta complex [EXACT]
Abeta complex [EXACT]
beta-amyloid complex [EXACT]
beta amyloid complex [EXACT]
betaA complex [EXACT]
amyloid beta dimer [NARROW]
amyloid beta trimer [NARROW]
amyloid beta oligomer [NARROW]
amyloid beta homodimer [NARROW]
amyloid beta homotrimer [NARROW]
amyloid beta homooligomer [NARROW]
homodimer of amyloid beta protein [NARROW]
homotrimer of amyloid beta protein [NARROW]
homooligomer of amyloid beta protein [NARROW]
amyloid beta heterodimer [NARROW]
amyloid beta heterotrimer [NARROW]
amyloid beta heterooligomer [NARROW]
heterodimer of amyloid beta protein [NARROW]
heterotrimer of amyloid beta protein [NARROW]
heterooligomer of amyloid beta protein [NARROW]
amyloid-beta protein 40 complex [NARROW]
amyloid-beta protein 42 complex [NARROW]
amyloid-beta protein 40/42 complex [NARROW]
Abeta-derived diffusible ligand complex [NARROW]
ADDL complex [NARROW]

Relationships:
is_a GO:0043234 protein complex
capable_of_part_of GO:0010469 regulation of receptor activity
capable_of_part_of GO:1900272 negative regulation of long-term synaptic potentiation
capable_of_part_of GO:1900454 positive regulation of long term synaptic depression
capable_of_part_of GO:1902951 negative regulation of dendritic spine maintenance

References: PMID:18568035

I hope that's it!
Birgit

**Comment by hdrabkin** [comment]
Need a little clarification: you say "Protein complex .....  Forms dimers and multimers of protein 40 and protein 42 splice variants of the amyloid beta A4 protein"; do you mean the complex is a dimer/multimere of protein 40 and protein 42 (both derived from the A4 protein)?

**Comment by bmeldal** [comment]
Yes, clanky wording I think!

What about:
"Forms dimers and multimers of protein 40 and protein 42 (splice variants of amyloid beta A4 protein)."

And I forgot the DB xrefs:
GOC:bhm
IntAct:EBI-13942506
IntAct:EBI-13943327
IntAct:EBI-13943368

**Comment by hdrabkin** [comment]
Would this be better: 
Forms dimers and m;utlimeres of protein 40 and protein 42 (the  proteolytic cleavage products of splice variants of amyloid beta A4 protein)

**Comment by bmeldal** [comment]
"Forms dimers and multimers of protein 40 and protein 42 (proteolytic cleavage products of amyloid beta A4 protein)"

There are lots more proteolytic cleavage products of A4! Proteins 40 & 42 are just 2 of them but the ones forming amyloid beta plaques.

**Comment by hdrabkin** [comment]
Yes, but the 40 and 42 are not themselves the splice variants right? There is a splice variant of the A4 that results in different 40s and 42s if I am understanding this correctly

**Comment by BarbaraCzub** [comment]
Hello, they are not splice variants though, but products of protein processing: http://www.uniprot.org/uniprot/P05067
@hdrabkin 
@bmeldal

**Comment by BarbaraCzub** [comment]
![screen shot 2017-03-07 at 16 19 33](https://cloud.githubusercontent.com/assets/16541096/23665992/f2a523e8-0351-11e7-899e-db4a3950c1c0.png)

**Comment by bmeldal** [comment]
No idea which splice variant these chains come from or if they get post-translationally cleaved from the canonical protein. UniProt has 11 sequence isoforms but none of them are missing the bit necessary for amyloid beta proteins so could come from any.

And I just saw Barbara chimed in. Yes, that's what I thought.

(These are Barbara's requests!)

**Comment by bmeldal** [comment]
Come to think of, we should take out the 'trimer' synonyms and regard them under 'oligomers' as I also found experimental evidence for tetramers, pentamers etc...

**Comment by BarbaraCzub** [comment]
Hm, what is the minimum number of Abeta subunits that will make an oligomer? Should this perhaps be specified in the definition? 
Although this review http://www.jbc.org/content/291/7/3174/T1.expansion.html uses kDa rather than 'number of '-mers'' to distinguish between different Abeta oligomers. And they also seem to differentiate between 'oligomers' and 'ADDLs'.

@bmeldal let's not include the ADDLs as synonyms for now either. I'll be at the ARUK2017 Conference next week and will do my best to clarify with experts what the differences between these actually are (my impressions from literature have been that the terms 'oligomers' and 'ADDLs' are used interchangeably, but it would seem that I was wrong). I'll relate back on Thursday or Friday next week.

**Comment by bmeldal** [comment]
I'm pretty sure the higher order structures depend on experimental conditions. Several papers have shown that oligomers can be broken down into dimers on denaturing gels and these dimers can have synaptotoxic effects when injected into rats or mice, so are the smallest active complexes. Hence why I think we should capture them separately in the Complex Portal. Then the rest are all down to experimental conditions and I would group them all as oligomers. In vivo you get plaques which a quite large. Looking at the table the kDs for oligomers and ADDL overlap so there's no differentiation by size. It might be a morphological difference or just down to interpretation as the table summarises lots of evidences from different publications. 

For GO purposes, I think they are all amyloid-beta protein complexes... We decided not to make stoichiometrically-distinct children.

We didn't mention 'fibrils' or 'plaques'. Should they also be synonyms?

In the term def I wouldn't go into too much detail of which higher order structures exists, just that they do.

And yes, please report back after your conference. The complexes won't go out before anyway so i can make the relevant changes when we have a better idea about the consensus.

**Comment by BarbaraCzub** [comment]
I seem to recall from a previous annotation call that the cellular component GO term 'fibril' is not to be used for Abeta annotation, as Abeta fibrils (and plaques) are structures representative of Alzheimer's disease pathology, whereas the GO term 'fibril' is intended for annotation of structural proteins, such as actin, or tubulin. So, although there is a thin boundary with normal aging in this context, I'd refrain from mentioning 'fibrils' or 'plaques' as the synonyms, especially, that they'd not be active / functional in the same way as oligomers. Fibrils and plaques are sedimented, so cannot 'do' much, unlike the oligomers, which 'float' around, bind to receptors, and trigger cascades of reactions (until they get too large and turn into fibrils, and then sediment into plaques).

**Comment by bmeldal** [comment]
That makes sense for GO. I wonder if I should included them in the CP entry for the oligomers, though.

**Comment by hdrabkin** [comment]
I was wondering about the normal vs disease processes coming into play here.  Shall I wait on making the requested complex term (sans a few of the synonyms)  Barabara gets back or go ahead now?

**Comment by bmeldal** [comment]
Well, they are physiological and disease-causing, the question is where's the line? Fibrils and plaques seem to be later stage disease-related while the dimers and smaller oligomers form first and then cause disease onset if they can't be dissociated by normal physiological processes. Momoners have another set of functions...

By the way, according to Wikipedia, they are produced by successive cleavages catalysed by beta- and gamma secretases.

**Comment by hdrabkin** [comment]
"Forms dimers and multimers of protein 40 and protein 42 (proteolytic cleavage products of amyloid beta A4 protein)" to replace "Forms dimers and multimers of protein 40 and protein 42 splice variants of the amyloid beta A4 protein"  Agreed? I can go ahead and start putting this in.

**Comment by hdrabkin** [comment]
Done; here's the stanza

[Term]
+id: GO:0106003
+name: amyloid-beta complex
+namespace: cellular_component
+def: "Protein complex involved in modulation of signaling and synaptic function in the brain, predominantly in the cerebral cortex and hippocampus. Forms dimers and multimers of protein 40 and protein 42 (proteolytic cleavage products of amyloid beta A4 protein).  Mostly found in the extracellular space with a small proportion occurring as membrane-bound species. Influences synaptic plasticity through various receptors, mediates dendritic spine loss leading to decreased synapse density, inhibits long-term potentiation (LTP) and enhances long-term depression (LTD). Soluble form is the main pathogenic species linked to Alzheimer's disease." [GOC: bmeldal, PMID:18568035]
+comment: An example is Protein 40 of APP (P05067-PRO_0000000093) in PMID:18568035 (inferred by direct assay).
+synonym: "Abeta complex" EXACT []
+synonym: "Abeta-derived diffusible ligand complex" NARROW []
+synonym: "ADDL complex" NARROW []
+synonym: "amyloid beta complex" EXACT []
+synonym: "amyloid beta dimer" NARROW []
+synonym: "amyloid beta heterodimer" NARROW []
+synonym: "amyloid beta heterooligomer" NARROW []
+synonym: "amyloid beta heterotrimer" NARROW []
+synonym: "amyloid beta homodimer" NARROW []
+synonym: "amyloid beta homooligomer" NARROW []
+synonym: "amyloid beta homotrimer" NARROW []
+synonym: "amyloid beta oligomer" NARROW []
+synonym: "amyloid beta trimer" NARROW []
+synonym: "amyloid-beta protein 40 complex" NARROW []
+synonym: "amyloid-beta protein 40/42 complex" NARROW []
+synonym: "amyloid-beta protein 42 complex" NARROW []
+synonym: "beta amyloid complex" EXACT []
+synonym: "beta-amyloid complex" EXACT []
+synonym: "betaA complex" EXACT []
+synonym: "heterodimer of amyloid beta protein" NARROW []
+synonym: "heterooligomer of amyloid beta protein" NARROW []
+synonym: "heterotrimer of amyloid beta protein" NARROW []
+synonym: "homodimer of amyloid beta protein" NARROW []
+synonym: "homooligomer of amyloid beta protein" NARROW []
+synonym: "homotrimer of amyloid beta protein" NARROW []
+is_a: GO:0043234 ! protein complex
+relationship: capable_of_part_of GO:0010469 ! regulation of receptor activity
+relationship: capable_of_part_of GO:1900272 ! negative regulation of long-term synaptic potentiation
+relationship: capable_of_part_of GO:1900454 ! positive regulation of long term synaptic depression
+relationship: capable_of_part_of GO:1902951 ! negative regulation of dendritic spine maintenance
+created_by: hjd
+creation_date: 2017-03-15T19:19:29Z

**Comment by BarbaraCzub** [comment]
Hello,
Thank you @hdrabkin for creating this cellular component GO term. 

Thank you @bmeldal for writing the definition for this cellular component. I would like to suggest minor changes:

+def: "Protein complex involved in modulation of signaling and synaptic function in the brain, predominantly in the cerebral cortex and hippocampus. Forms dimers and multimers of amyloid beta peptide 40 and peptide 42 (proteolytic cleavage products of amyloid beta A4 protein, also known as amyloid beta precursor protein). Mostly found in the extracellular space with a proportion occurring as membrane-bound species. Influences synaptic plasticity through various receptors, mediates dendritic spine loss leading to decreased synapse density, inhibits long-term potentiation (LTP) and enhances long-term depression (LTD). Soluble multimeric form is the main pathogenic species linked to Alzheimer's disease." [GOC: bmeldal, PMID:18568035]

The reason why I would rather refer to the cleavage products as 'peptides', and not 'proteins', is to be able to differentiate more easily between them and their precursor protein. Related to this, I would include the 'amyloid beta precursor protein' as the source of the proteolytic cleavage products, because this is the HGNC-approved name: http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=620 which some users may be more familiar with than they are with 'amyloid beta A4 protein'. In the next sentence, I'd say 'a proportion' rather than 'a small proportion' as various sources provide different evidence about how large a proportion this actually is (although I am not going to stand by this one too strongly!). And in the final sentence I would say "Soluble multimeric form" rather than only "Soluble form", because the monomers of amyloid beta are also soluble, but not pathogenic, so it is important to clearly state this and remind users that we are still talking about the amyloid beta protein complex, and not its individual components.

Please let me know whether you would be happy with these small modifications.

Thanks,
Barbara

**Comment by hdrabkin** [comment]
If @bmeldal is ok with these, I'll go ahead and tweak.

**Comment by bmeldal** [comment]
I'd say "well argued"!
Harold, please go ahead and make the changes.
Barbara, I saw your detailed email regarding all the variations of Abeta and will get to it :)

**Comment by BarbaraCzub** [comment]
Great, thank you both!

**Comment by hdrabkin** [comment]
Definition modified per request; thanks everyone.
