### ISSUE TITLE
obsoletion: GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13137]
obsoletion: GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter
and descendants

During previous changes this was re-defined as regulation of "meiotic cell division",
but the paper  which is used to define the term is not for the "regulation of meiotic division", it is 
"regulation of meiotic cell cycle"

I'm not sure that meiotic division is regulated transcriptionally...(it's causally upstream).

experimental annotations 
PomBase 5
SGD 2

these annotations should be rehoused under:
GO:0010672 regulation of transcription from RNA polymerase II promoter involved in meiotic cell cycle

**Comment by pgaudet** [comment]
OK for SGD as well: 

> Hi Pascale,

I took a look at those annotations and the publication and I agree that they should be rehoused. I moved them to child terms underneath GO:0010672 regulation of transcription from RNA polymerase II promoter involved in meiotic cell cycle as suggested. No objection here to obsolete that term.

Regards,
Edith
********************************************************************

On Mar 13, 2017, at 2:21 PM, sgd-helpdesk-bounces@lists.stanford.edu wrote:


From: Pascale Gaudet <pascale.gaudet@sib.swiss>
Subject: obsoletion: GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter
Date: March 13, 2017 at 8:24:03 AM PDT
To: <sgd-helpdesk@mailman.stanford.edu>


Dear SGD curators, 

I am working on a issue brought up by Val, in which she requests the obsoletion of GO:1900401 regulation of meiosis by regulation of transcription from RNA polymerase II promoter. The reason is that "During previous changes this was re-defined as regulation of "meiotic cell division”, but the paper which is used to define the term is not for the "regulation of meiotic division", it is "regulation of meiotic cell cycle"
I'm not sure that meiotic division is regulated transcriptionally...(it's causally upstream). 

SGD has 2 experimental annotations

these annotations should be rehoused under:
GO:0010672 regulation of transcription from RNA polymerase II promoter involved in meiotic cell cycle”. 


If it’s OK with you I’ll go ahead with the obsoletion. 

Thanks, 
Pascale

**Comment by pgaudet** [comment]
Hello, I am ready to do this. Looks like @mah11 created the term 
https://github.com/geneontology/go-ontology/issues/9370
just wanted to notify her of the obsoletion. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood @mah11 
I just noticed this term has annotated children: 
 GO:1900475 	positive regulation of meiosis by negative regulation of transcription from RNA polymerase II promoter 1 SGD/2 Pombase
Is a 	GO:1900476 	positive regulation of meiosis by positive regulation of transcription from RNA polymerase II promoter: 1 SGD/1 Pombase

I will also obsolete these two (it seems like they were included in your request since the total number of annotations corresponds to what you have there). 

Thanks, Pascale

**Comment by ValWood** [comment]
Yep we will fix if not done already....its probably just because of our current crazy long release cycle. This will be fixed soon...

**Comment by pgaudet** [comment]
Hi, 

To avoid recreating the same terms I did a merge, adding the old terms as narrow synonyms:

GO:1900475   
positive regulation of meiosis by *negative* regulation of transcription from RNA polymerase II promoter
-> merge with GO_0010674 *negative* regulation of transcription from RNA polymerase II promoter involved in meiotic cell cycle

GO:1900475   positive regulation of meiosis by *negative* regulation of transcription from RNA polymerase II promoter
-> merge with GO_0010674 *negative* regulation of transcription from RNA polymerase II promoter involved in meiotic cell cycle

GO:1900476 positive regulation of meiosis by *positive* regulation of transcription from RNA polymerase II promoter
-> merge with GO_0010673 *positive* regulation of transcription from RNA polymerase II promoter involved in meiotic cell cycle

Thanks, Pascale

**Comment by pgaudet** [comment]
Changed in the OBO file are now merged, see #13165
