### ISSUE TITLE
chromatin organization vs chromosome condensation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13147]
chromatin organization is defined
Any process that results in the specification, formation or maintenance of the physical structure of eukaryotic chromatin.

This definition refers to chromatin assembly and disassembly but excluding "chromsome condensation" which is a "higher order of compaction"

However,
sperm chromatin condensation
Definition	The progressive compaction of the spermatid chromatin so that it reaches a level of condensation that is not compatible with nuclear activities such as transcription or DNA replication

is a descendant, but it doesn't organize the physical structure of chromatin as such (as per the definition), but its spatial organization once formed.

Also "sperm chromatin condensation" is not a  descendent of:

chromosome condensation
Definition	The progressive compaction of dispersed interphase chromatin into threadlike chromosomes prior to mitotic or meiotic nuclear division, or during apoptosis, in eukaryotic cells.

One solution would be to move   and rename "sperm chromatin condensation" to" sperm chromosome condensation"

**Comment by ukemi** [comment]
Isn't it part of the maintenance of the physical structure of chromatin in a specialized cell?  It seems fine to me.

**Comment by ValWood** [comment]
I'm pretty sure that people who work on chromatin organization (assembly, dissassembly and maintenence) don't consider chromosome condensation to be part of "chromatin organization"

I also don't think condensation really fits the definition 
"Any process that results in the specification, formation or maintenance of the physical structure of eukaryotic chromatin."

If it does turn out that people are OK to call "chromosome condensation"  a type of "chromatin organization"  we would need to move "chromatin condensation" to  be a descendant  of GO:0006325

We also need a term to be able to differentiate  the level of packaging referring to the
canonical "chromatin" 30 nm fibre from "condensation"

Organization of the 30nm fibre  fits how we have used
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006325
so far.

I think I would need to ask some chromosome biologists about this....Maybe @mah11 
remembers something about the historical reason that "chromosome condensation" is not part of "chromatin organization",  because it has been like this forever. I thinks its probably because condensation is about organizing "chromosomes" rather than "chromatin".
Val

**Comment by mah11** [comment]
I am not a chromosome biologist. But a few scattered comments anyway:

> don't consider chromosome condensation to be part of "chromatin organization"

I don't see where anyone suggested making this link. At present GO has chromosome condensation is_a *chromosome* organization, and that makes sense.

When this ticket was opened, I thought the issue was that the phrase "chromatin condensation" has been used in just two term names, and that it's not clear why:

GO:0035092 sperm chromatin condensation
GO:1990892 mitotic chromosome arm chromatin condensation

(Val - GO:1990892 is one of yours)

It seems to me that if *chromatin* condensation is a thing at all, it makes sense to classify it as a type of chromatin organization. But I wouldn't conclude that chromosome condensation is part of any chromatin process; instead, I'd say chromatin condensation may be part of chromosome condensation, but I don't know if it's safe to put the link in the ontology because maybe chromatin could condense in only a relatively small region (but chromosome condensation has_part chromatin condensation might work).

The other possibility is that "chromatin condensation" doesn't make sense and the two GO terms above should be changed to use "chromosome condensation".

**Comment by ukemi** [comment]
Are you sure about that in sperm? In sperm the chromatin get repackaged in a very special way as part of the development of the cell.  PMID:10531297

**Comment by ValWood** [comment]
Certainly my term
GO:1990892 mitotic chromosome arm chromatin condensation
Should be
mitotic chromosome arm  condensation

and be part of chromosome condensation, not chromatin organization

**Comment by mah11** [comment]
I am utterly unqualified to comment on sperm or the chromatin therein!

**Comment by ValWood** [comment]
The sperm paper appears to be describing chromatin organization.


They only use the word "condensation"  in the final sentence:
"Chromatin (DNA) condensation plays a critical role in the silencing and tight packing of the genome within the sperm nucleus." but they don't really appear to be describing condensation in the review?

**Comment by ukemi** [comment]
I am going to leave the sperm terms as is. 

> Certainly my term GO:1990892 mitotic chromosome arm chromatin condensation should be mitotic chromosome arm condensation and be part of chromosome condensation, not chromatin organization
As far as I can see it is not a child of chromatin organization. I have changed the name as you suggest.
