### ISSUE TITLE
Is go.owl released as a pre-reasoned file?

### ISSUE THREAD

**Issue by addiehl** [geneontology/go-ontology#13154]
A colleague of mine is interested in understanding the structure of the GO biological process ontology.  He pointed out in AmiGO2 that if one looks under the "Browse" tab and opens up the biological_process node, that huge number of regulation-type terms are found directly under the root node.  I checked again today, and it still looks this way. http://amigo.geneontology.org/amigo/dd_browse

Furthermore, he showed me that when go.owl is loaded in Protege, the class hierarchy tab (unreasoned) shows the same structure as in the AmiGO2 browser in that these regulation terms appear as direct children of the root node biological_process.  I tried this myself today with a fresh download of go.owl, and see the same structure.  If I run the reasoner, the regulation terms are placed appropriately in the hierarchy in the class hierarchy (inferred) tab.

I was under the impression that go.owl was a public file that is intended to be released in a pre-reasoned format, and that AmiGO2 would display the GO in a pre-reasoned manner.  Is this just a production error in GO that has escaped to the wild, or is this a change in policy?

Thanks,
Alex

**Comment by cmungall** [comment]
@addiehl you are correct in your inference as to what happened, this is currently being addressed, cc @kltm https://github.com/geneontology/amigo/issues/366

**Comment by cmungall** [comment]
We think we have fixed this, see the dev server:
http://tomodachi.berkeleybop.org/

Should be in production soon.

Note that the go.owl file is fine. It is expected that you see a giant flat list when opening 'biological process' in the asserted view, even through the ontology has been pre-reasoned. This is because Protege will 'weaken' equivalence axioms to subclass axioms for display purposes. This is rectified by switching the reasoner on.
