### ISSUE TITLE
obsolete GO:0006981 activation of SoxR protein ?

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#13153]
GO:0006981 activation of SoxR protein

DEF: The conversion of the SoxR transcription factor to its active (oxidized) form. 

We just found this term and it seems much too specific, it's not even clear to us that SoxR is in all/higher organisms (?).  I also don't see any existing annotations.  Should this term remain?

Thanks

**Comment by ukemi** [comment]
Notice sent on March 14.

The proposal has been made to obsolete GO:0006981 activation of SoxR protein

The reason for obsoletion is that this term’s target is too specific. A quick search indicates that the activation of SoxR TF is due to a single enzymatic reaction.

AmiGO2 shows there are no annotations to this term.

The term is used in the prokaryotic GO slim subset.

Details can be found here:
https://github.com/geneontology/go-ontology/issues/13153


We are opening a comment period for this proposed obsoletion. We'd like
to proceed and obsolete this term on March 21, 2017

*** Unless objections are received by March 21, 2017 , we will assume that you
agree to this change. ***

Thanks,

David
