### ISSUE TITLE
Pseudohyphal growth definition is S. cerevisie-specific

### ISSUE THREAD

**Issue by dianeoinglis** [geneontology/go-ontology#13164]
This is a side issue brought up by Karen in #13157 so it should be a separate ticket.

The current definition for GO:0007124 'pseudohyphal growth' specifically describes the situation in S. cerevisiae diploid cells. Other fungi do not necessarily require nitrogen limitation and an abundant fermentable carbon source to grow pseudohyphally. These conditions are specific to S. cerevisiae diploid strains. In S. cerevisiae haploids, these same conditions stimulate "(haploid) invasive growth."' I'm not sure if S. pombe requires the same conditions/limitations. Where it states that cells become elongated, this implies a non-elongated (yeast) switches but some fungi (Candida albicans) can switch from true hyphal growth to pdeudohyphal growth. In this case, "becomes elongated" is not correct.

Both SGD and CGD have many annotations to this term and it is appropriate but the definition is too narrow and specific to S. cerevisiae. See PMID: 19347739.
This definition should be broadened to remove the S. cerevisiae-specific facts. 

"The ability of cells to grow as a chain of physically attached, elongated cells in response to an environmental stimulus or stimuli."

This broader definition is preferable because orthologs in Sc and Ca are often involved in this process and the definition should be correct for more than just S. cerevisiae. This or a similar definition for GO:0007124 and related will not cause any need for reannotation.

@mah11
@srengel

**Comment by mah11** [comment]
That's not surprising, since GO:0007124 is one of the Original Set™ of GO terms and its definition is almost as old. I have no objection to broadening the text definition to accommodate other fungi.

I think you'd need @ValWood or @Antonialock to comment on S. pombe.

**Comment by krchristie** [comment]
I think I am likely the culprit behind the cerevisiae specific definition of pseudohyphal growth (as my initials are attached to the def), but I agree that this should not be defined in a cerevisiae-specific way.

I am also a bit confused by this whole structure here and definitions that do not clearly distinguish the terms, or define them logically with respect to their placement in the structure. We seem to have a combination of terms that use words actually used in the literature (hyphal growth & pseudohyphal growth) and terms named descriptively (but not intuitively) and they don't seem well integrated.

<pre>
- filamentous growth (GO:0030447)
-- filamentous growth of a population of unicellular organisms (GO:0044182)
--- growth of unicellular organism as a thread of attached cells (GO:0070783)
---- invasive filamentous growth (GO:0036267)
---- pseudohyphal growth (GO:0007124)
-- hyphal growth (GO:0030448)</pre>

**filamentous growth of a population of unicellular organisms (GO:0044182)**
Def: The process in which a group of unicellular organisms grow in a threadlike, filamentous shape.
=> Is this def narrow enough to exclude hyphal growth, since that term is a sibling to this? 

**invasive filamentous growth (GO:0036267)**
Def: The growth of colonies in filamentous chains of cells into a substrate.
=> This def doesn't seem to really distinguish this term from its parent term, which already includes invasive growth. In addition, from the very general name, this term seems like a candidate for misuse for any kind of invasive filamentous growth, not just invasive growth of the type specified by its parent term.

**pseudohyphal growth (GO:0007124)**
Def: A pattern of cell growth that occurs in conditions of nitrogen limitation and abundant fermentable carbon source. Cells become elongated, switch to a unipolar budding pattern, remain physically attached to each other, and invade the growth substrate.
=> agreed that this def is too specific to cerevisiae

**Comment by dianeoinglis** [comment]
**Proposed new def for 'pseudohyphal growth'**
Growth of an organism as invasive chains of ekongated, attached cells that divide in an axial/unipolar or axial/bipolar pattern of cell division in response to an environmental stimulus. Cells in a pseudohyphal filament range in shape and length from slightly elongated to highly elongated filamentous cells that are distinct from the tubular, filamtous cells of true hyohae.
DOI

**Comment by dianeoinglis** [comment]
The parent of 'pseudohyphal growth"' could be GO:004482 'filamentous growth of a population of unicellular organisms.'

Second, filamentous growth'he term "threadlike" should be ommited from all 'filamentous growth' definitions as it is not a useful description. It could be replaced by the more descriptive term, "elongated."

**Comment by ValWood** [comment]
I don't think we need  population level terms, we should just be describing "filamentous growth" at the organismal level? (I realise this may include one or more cells , but if it has more than one cell it's a  "multicellular fungi". Still no need to refer to a population.

**Comment by krchristie** [comment]
Looking at the ontology in Protege, I notice that 'pseudohyphal growth' does not have any relationship to 'filamentous growth', which surprises me as the yeast labs at UC Berkeley when I was there talked about 'pseudohyphal growth' as a type of 'filamentous growth'.

This paper clearly uses the term "filamentous" growth to describe pseudohyphal growth in cerevisiae, which is consistent with my recollection.

**Song Q, Kumar A.** An Overview of Autophagy and Yeast Pseudohyphal Growth:
Integration of Signaling Pathways during Nitrogen Stress. Cells. 2012 Jul
4;1(3):263-83. PMID:24710476

>In addition, nitrogen stress can also induce morphological changes, such as filamentous growth. Filamentous growth is a morphologically distinct growth mode in many fungi wherein cells elongate and interconnect to form a multicellular “chain” [9]. In S. cerevisiae, the chain-like filaments are thought to allow yeast colonies to scavenge for nutrients under conditions of nutritional stress. This morphogenetic response has been observed in several fungal species, including at least two types of S. cerevisiae laboratory strains (e.g., Σ1278b and SK1) [10,11]; it should be noted, however, that most common laboratory strains of S. cerevisiae are non-filamentous (e.g., derivatives of S288c).

@srengel @robnash - I wanted to check in with SGD to see if you have thoughts about whether 'pseudohyphal growth' should be classified as a type of 'filamentous growth'.

**Comment by krchristie** [comment]
Reading back through the thread, I am inclined to accept the definition suggested by @dianeoinglis 

> "The ability of cells to grow as a chain of physically attached, elongated cells in response to an environmental stimulus or stimuli."

but with a minor modification to be more consistent with the definitions of other terms like that of 'cell growth':

**Proposed def:** "The process in which cells grow as a chain of physically attached, elongated cells in response to an environmental stimulus or stimuli."

**Comment by pgaudet** [comment]
@krchristie Looks like this is ready ?
