### ISSUE TITLE
NTR: mCRD-mediated mRNA stability complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13170]
This complex is related to GO:0070937 CRD-mediated mRNA stability complex but binds the **major** protein-coding-region determinant of instability (mCRD) domain rather than the CRD. Experimentally it has been shown to act on c-FOS mRNA while GO:0070937 acts on c-MYC mRNA.

Name: mCRD-mediated mRNA stability complex
Def:
A protein complex that binds to, and promotes stabilization of, mRNA molecules containing the major coding region instability determinant (mCRD) by bridging the mCRD domain and the poly(A) tail of the mRNA. In human, it consists of CSDE1, HNRPD, PABPC1, PAIP1 and SYNCRIP.
Synonym:
major coding region instability determinant-mediated mRNA stability complex
Relationships:
is_a GO:0043234 protein complex
part_of GO:0005829 cytosol
capable_of GO:0008143 poly(A) binding
capable_of GO:1990825 sequence-specific mRNA binding
capable_of_part_of GO:0070934 CRD-mediated mRNA stabilization
capable_of_part_of GO:1900152 negative regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay
capable_of_part_of GO:2000767 positive regulation of cytoplasmic translation

References: 
PMID:11051545
IntAct:EBI-13948957
IntAct:EBI-13948957
GOC:bhm

Thanks, Birgit

**Comment by bmeldal** [comment]
more Synonyms:
mCRD-poly(A)-bridging complex
major coding region instability determinant-poly(A)-bridging complex

**Comment by hdrabkin** [comment]
done; assumed you wanted all the synonyms as exact?

**Comment by bmeldal** [comment]
Thanks, Harold. 
Yes to the synonyms as EXACT - apologies. 
Please paste the stanza so I can copy the term into our editor before it trickles through to QuickGO.

**Comment by hdrabkin** [comment]
[Term]
id: GO:0106002
name: mCRD-mediated mRNA stability complex
namespace: cellular_component
def: "A protein complex that binds to, and promotes stabilization of, mRNA molecules containing the major coding region instability determinant (mCRD) by bridging the mCRD domain and the poly(A) tail of the mRNA. In human, it consists of CSDE1, HNRPD, PABPC1, PAIP1 and SYNCRIP." [GOC:bhm, IntAct:EBI-13948957, PMID:11051545]
comment: This complex is related to GO:0070937 CRD-mediated mRNA stability complex but binds the major protein-coding-region determinant of instability (mCRD) domain rather than the CRD. Experimentally it has been shown to act on c-FOS mRNA while GO:0070937 acts on c-MYC mRNA.
synonym: "major coding region instability determinant-mediated mRNA stability complex" EXACT []
synonym: "major coding region instability determinant-poly(A)-bridging complex" EXACT []
synonym: "mCRD-poly(A)-bridging complex" EXACT []
is_a: GO:0043234 ! protein complex
relationship: capable_of GO:0008143 ! poly(A) binding
relationship: capable_of GO:1990825 ! sequence-specific mRNA binding
relationship: capable_of_part_of GO:0070934 ! CRD-mediated mRNA stabilization
relationship: capable_of_part_of GO:1900152 ! negative regulation of nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay
relationship: capable_of_part_of GO:2000767 ! positive regulation of cytoplasmic translation
relationship: part_of GO:0005829 ! cytosol
property_value: created_by "hjd" xsd:string
property_value: creation_date 2017-03-14T18:13:01Z xsd:dateTime

**Comment by bmeldal** [comment]
Apologies for being a pain, but I realised we need these 2 EXACT synonyms, too:
major coding region determinant of instability-mediated mRNA stability complex
major coding-region determinant of instability - poly(A) tail-bridging complex

They can't decide whether they call it "determinant of instability" or "instability determinant"!

PS: why are you discussing the term this afternoon? Just curious as the ticket was already closed...

**Comment by ukemi** [comment]
We were going to discuss it because of the weird tags in the stanza, nothing to do with the term itself. But I think hjd found out why the tags were added, so I will remove the label.

**Comment by hdrabkin** [comment]
added the new synonyms; closing
