### ISSUE TITLE
Incorrect parent 'clathrin-dependent extracellular exosome endocytosis' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13211]
Hello,

The term 'clathrin-dependent extracellular exosome endocytosis' has parent 'extracellular transport'. This seems wrong; I suggest moving it under 'endocytosis'. 

This terms is only used by RGD, @slaulederkind is this OK with you ? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
It has three parents: 
clathrin-dependent endocytosis 
establishment of vesicle localization 
extracellular transport

**Comment by pgaudet** [comment]
Hi @slaulederkind, thanks for the precision. Just checking that you are OK with removing the 'extracellular transport' parent. The rest stays. 

Thanks, 
Pascale

**Comment by slaulederkind** [comment]
Yes, that 'extracellular transport' as a parent to 'clathrin-dependent extracellular exosome endocytosis' looks incorrect.

**Comment by vanaukenk** [comment]
Hi,

I'm looking at the parentage for this term and it looks like this parent was generated about a year and a half after the original term was created and is coming in through the logical definition that was created on 2016-11-28:

'clathrin-dependent endocytosis' and ('transports or maintains localization of' some 'extracellular exosome') 

I don't know if there's a more appropriate logical definition, perhaps something like this:

'clathrin-dependent endocytosis' and ('imports' some 'extracellular exosome')

Alternatively, I can just remove the logical definition for now.  

@ukemi  - what would you advise?

**Comment by ukemi** [comment]
You are correct. It is because 'extracellular exosome' is 'part of' the 'extracellular region' and the property chain 'transports or maintains localization of' o 'part of' resolves to 'occurs in'. Therefore the reasoner is telling you that the endocytosis is a transport that occurs_in the 'extracellular region', which is a type of 'extracellular transport'. But once the 'extrcellular exosome' is being imported, it is no longer part of the extracellular region, nor is it an extracellular exosome. I would be tempted to remove the logical definition because I think we want to keep the assertion that an extracellular exosome is a part of the extracellular region.  You might be able to add the relationship has_participant 'extracellular exosome'.
@paolaroncaglia @dosumis any comments?

**Comment by paolaroncaglia** [comment]
@ukemi uh... I don't recall adding the problematic logical def. Anyway yes I'd remove it. has_participant as you suggest sounds safer and more appropriate. Thanks!

**Comment by ukemi** [comment]
Thanks @paolaroncaglia  
I didn't mean to imply that you added the logical def, but I thought you had worked on the extracellular vesicles, so I wanted to make sure you thought what I suggested made sense.

**Comment by vanaukenk** [comment]
Following up with some notes after conversation with @ukemi 
The original suggestion to add the has_participant relationship referred to adding this to the SubClass Of relationships, not the logical definition.
@dosumis if there is a new logical definition that would be consistent with other patterns for transport but not result in the 'extracellular transport' parentage, I'd be happy to update that, as needed.
