### ISSUE TITLE
ntr: osmosensory signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13252]
negative regulation of osmolarity signalling pathway

**Comment by krchristie** [comment]
@ukemi 

I am making the generic 'regulation of osmolarity signalling pathway' in order to appropriately define 'negative regulation of osmolarity signalling pathway', which is the the term Val requested. 

I was wondering if I need to directly assert a subclass with the 'regulates' relationship. I see terms with and without the asserted subclass, so it's not completely clear to me what the appropriate pattern to follow should be. 

**'regulation of Kit signaling pathway'**:
**Equivalent To:** biological_process and (regulates some 'Kit signaling pathway')
**Asserted SubClass Of:** regulates some 'Kit signaling pathway'

**'regulation of Fas signaling pathway'**
**Equivalent To:** biological_process and (regulates some 'Fas signaling pathway')

**Comment by krchristie** [comment]
Currently, I haven't put those in, and the stanzas look like this presently:

 [Term]
+id: GO:0120027
+name: regulation of osmosensory signaling pathway
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of osmosensory signaling pathway." [GOC:vw]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: regulates GO:0007231 ! osmosensory signaling pathway
+created_by: kchris
+creation_date: 2017-03-31T14:45:01Z
+
+[Term]
+id: GO:0120028
+name: negative regulation of osmosensory signaling pathway
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of osmosensory signaling pathway." [GOC:vw]
+intersection_of: GO:0008150 ! biological_process
+intersection_of: negatively_regulates GO:0007231 ! osmosensory signaling pathway
+created_by: kchris
+creation_date: 2017-03-31T15:00:28Z

**Comment by ukemi** [comment]
We need to talk about this on the call today. It appears that it is inconsistent. I think they should be asserted.

**Comment by krchristie** [comment]
@cmungall advised that it should not be necessary to manually assert SubClass Of relationships of the form:
regulates some 'Kit signaling pathway'

The equivalence axiom of the form:
 Equivalent To: biological_process and (regulates some 'Kit signaling pathway')

is sufficient to generate the appropriate regulation relationship in the fully reasoned file (though note that we won't see it in Protege or in the obo stanza of the working file).

Thus for these terms, I will make the equivalence axiom but not the asserted subclass.

**Comment by krchristie** [comment]
Ticket to computationally remove unnessecary asserted regulation relationships: https://github.com/geneontology/go-ontology/issues/13275
