### ISSUE TITLE
ntr: 	tRNA ( guanine-N7)-methylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13266]
descendant of 
GO:0036265	RNA ( guanine-N7)-methylation

standard def

PMID: 17382321

**Comment by hdrabkin** [comment]
Please supply def

**Comment by ValWood** [comment]
The standard def for the other terms appears to be:

The process whereby a guanine in a RNA is methylated at the N7 position of guanine.

**Comment by hdrabkin** [comment]
Thanks; but what I meant was a PMID for it, not the def.  I'm still jet lagged

**Comment by ValWood** [comment]
PMID: 17382321 ;)

**Comment by hdrabkin** [comment]
I see a problem here unrelated to the actual term: 
GO:0036265 RNA ( guanine-N7)-methylation is part of 7-methyl G RNA capping. Because of this the child terms rRNA and tRNA  guanine-N7)-methylation get the same part of. 
I think the part_of  to 7-methyl G RNA capping needs to be removed from RNA ( guanine-N7)-methylation

**Comment by cmungall** [comment]
Do we have a methylation DP yet?

**Comment by hdrabkin** [comment]
DP?

**Comment by hdrabkin** [comment]
The capping would have_part N7 G methylation

**Comment by hdrabkin** [comment]
I could make the tRNA ( guanine-N7)-methylation (NTR) a child of tRNA methylation instead.

**Comment by hdrabkin** [comment]
Made new term RNA 5'cap (guanine N7) methylation  in addition and fixed parentage, in addition to adding your tRNA term.
Closed.
