### ISSUE TITLE
Move design patterns into main go-ontology repository

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13273]

**Comment by cmungall** [comment]
is this about the location of the yaml design patterns?

**Comment by dosumis** [comment]
Do you mean design pattern docs?

**Comment by cmungall** [comment]
I modified the title; yes, this is about moving https://github.com/geneontology/design_patterns into this repo.

It would make it easier for editors to find. I think it also makes sense to have a single tracker since the DPs are so integrally part of what we do on go-ontology. Also for CI checks like travis etc it's slightly simpler to have everything in one place.

Would moving be OK with you @dosumis? I suggest src/patterns. We could use the GH issue mover to move the existing tickets.

After that we can set up some additional jenkins jobs. For example, here is a job we use for the pheno ontologies: https://build.berkeleybop.org/job/query-pheno-patterns/lastStableBuild/ - this shows all terms that match each pattern

**Comment by dosumis** [comment]
Makes sense for tickets to be integrated. 

But the advantage of a separate repo is that we can hook it up to a simple, separate travis job (with badge and emails warnings) that checks and reports when editors get them wrong and updates them when lable change. Simple checks are running now & I have some more in the works (although may be superceded by Jim’s Scala code). 

I’d like to have a standard recepe for pattern repos, just as you have for ontology repos - with travis pulling some standard checking code.

Ot - can see a way to do this cleanly within the ontology repo?

**Comment by cmungall** [comment]
Looks like I lost my comments here.

We of course still want to run the travis checks over the DPs. Having in the same repo will also allow us to check for things such as modifying a DP having implications for the ontology

**Comment by cmungall** [comment]
Decided on http://wiki.geneontology.org/index.php/Ontology_meeting_2017-04-21

We will first check that we will still get fast travis feedback on any edits to the DPs, and if this is OK, move to src/patterns

**Comment by dougli1sqrd** [comment]
https://github.com/geneontology/go-ontology/pull/13486

**Comment by dosumis** [comment]
So - the files have been moved, but no sign of integrating into travis yet.  It looks like simply specifying another travis step with is not a good idea due to lack of support for multiple languages in one .travis.yml, so this should probably be incorporated into the makefile.  Also the badges are still linking back to the travis job on the old repo...  

I'm actively editing patterns and would like to have checking in place while I do so.

**Comment by cmungall** [comment]
Giving up for now, @dougli1sqrd can you take a look at my WIP PR above?

**Comment by cmungall** [comment]
@dosumis - maybe we should do this all using dosdp-tools? The current checks don't check the OWL expressions. The first one i tested in validated/ has:

```
  text: "'molecular_function that 'directly positively regulates' some %s"
```

(missing close quotes)

**Comment by dosumis** [comment]
Maybe both?  AFAIK, dosdp tools (just renamed?) doesn't work dynamically from the JSON spec.

**Comment by pgaudet** [comment]
@cmungall I think this is done ? 
Can this be closed ? 
Should we remove/obsolete the old repo to avoid confusion ? (although some documentation there should be moved). 

Thanks, Pascale
