### ISSUE TITLE
Taxon constraint for GO:0055036 virion membrane

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#13332]
I just got our regular taxon constraint violation email. It has several that are

> GO:0005623 only_in_taxon cellular organisms 

It seems to me that by definition, a virion membrane is never in cellular organisms, not only_in

**Comment by pgaudet** [comment]
I added taxon constraints: 
 virion part (the parent of virion membrane, virion and  viral occlusion body)
 never in cellular organisms

But what causes the problem is that membrane is now a 'cell part'. I will create a separate issue for this. 

Pascale

**Comment by jimhu-tamu** [comment]
Hi Pascale,

When you create the other issue, note that moving membrane up to a child of the component root would also solve problems beyond enveloped viruses, such as for GO:1903561 ! extracellular vesicle and its children.

**Comment by cmungall** [comment]
I'm not following this ticket. It seemed @jimhu-tamu was asking for a relaxation of some rule, but I don't know which without seeing what the original annotation was.

The new TC seems good, but I don't understand how adding a TC changes any part_of inferences for membrane

**Comment by pgaudet** [comment]
Hi @cmungall , you are right, these are unrelated.

**Comment by pgaudet** [comment]
Hello, 

I dealt with this request (adding taxon constrains to viral terms), but it will not fix the taxon violation problem which comes from 'membrane' now being asserted as a 'cell part', and since viruses are not cells, according to this relation viruses do not have membranes. I created a separate issue for that : 
https://github.com/geneontology/go-ontology/issues/13338

Thanks, Pascale
