### ISSUE TITLE
NTR: Occlusion body budding

### ISSUE THREAD

**Issue by mcgu2014** [geneontology/go-ontology#13376]
Occlusion body budding
Definition: A viral process by which enveloped viruses acquire a host-derived membrane enriched in viral proteins to form a crystalline protein matrix which surrounds the nucleocapsids of some insect viruses (baculoviridae, entomopoxvirinae, cypovirus). The process starts when nucleocapsids, assembled or in the process of being built, induce formation of a membrane curvature in the host plasma or organelle membrane and wrap up in the forming bud. The process ends when the bud is eventually pinched off by membrane scission to release the enveloped particle into the lumenal or extracellular space.
Aspect: Biological Process
Relationships: Parent Term is viral budding GO:0046755, Produces Component viral occlusion body GO:0039679
Paper Reference: Referred to in PMID:19393701

**Comment by pgaudet** [comment]
Dear @mcgu2014

Looking at the paper, it seems like ac109 is involved in 'nuclear capsid assembly'. Would that work ? 

Thanks, Pascale

**Comment by mcgu2014** [comment]
That term is associated with ac109, but while the protein was involved with capsid assembly, the standard virion capsid is not the same as a Baculovirus's occlusion body.


On Apr 19, 2017, at 03:23, pgaudet <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear @mcgu2014<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcgu2014&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=OcjAxyXZb769Mk6PvAyea-L_MIn_8me_4SRS4zxnCds&m=9BYldAF_Wj2yGHON0OwhALzuaEGOf8fFyfwjO2x1d4Q&s=K9pDmrHtZ_p7rWWVVsRmTfdi2YmYPQrR_OP9JAguSlE&e=>

Looking at the paper, it seems like ac109 is involved in 'nuclear capsid assembly'. Would that work ?

Thanks, Pascale

**Comment by pgaudet** [comment]
Hello, 

I would like the input of the ViralZone people before going ahead with the creation of this term. @pmasson55 , can you please comment ? 

Thanks, Pascale

**Comment by pmasson55** [comment]
Hello

I don't think this term is appropriate since there is no budding with viral occlusion bodies.  Two types of virions exist : budded virus (BV) and occlusion-derived virus (ODV). BVs and ODVs are identical in nucleocapsid structure and genetic information, but the composition of their envelopes is different. 
(text taken from the publication you cited).
BVs have a single nucleocapsid enveloped in a membrane that is derived by budding from the host cell plasma membrane, whereas in ODVs, one or multiple nucleocapsids are enveloped in a membrane derived from the host cell nuclear envelope. From Pubmed: 28031365 (paper from 2017)

So in conclusion, it's unclear how occlusion derived virions acquire their membrane (that seems to be nuclear derived)  but it doesn't seem to be through budding. Microvesicles are formed in the host nucleus and then the nucleocapsid gets into these vesicles.
https://www.ncbi.nlm.nih.gov/books/NBK138305/figure/ch03.F8/

So the definition "The process starts when nucleocapsids, assembled or in the process of being built, induce formation of a membrane curvature in the host plasma or organelle membrane and wrap up in the forming bud. The process ends when the bud is eventually pinched off by membrane scission to release the enveloped particle into the lumenal or extracellular space." seems incorrect.

Hope this helps.
Regards,
Patrick.

**Comment by mcgu2014** [comment]
Thank you! i must have missed that portion!

On Apr 20, 2017, at 06:44, pmasson55 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello

I don't think this term is appropriate since there is no budding with viral occlusion bodies. Two types of virions exist : budded virus (BV) and occlusion-derived virus (ODV). BVs and ODVs are identical in nucleocapsid structure and genetic information, but the composition of their envelopes is different.
(text taken from the publication you cited).
BVs have a single nucleocapsid enveloped in a membrane that is derived by budding from the host cell plasma membrane, whereas in ODVs, one or multiple nucleocapsids are enveloped in a membrane derived from the host cell nuclear envelope. From Pubmed: 28031365 (paper from 2017)

So in conclusion, it's unclear how occlusion derived virions acquire their membrane (that seems to be nuclear derived) but it doesn't seem to be through budding. Microvesicles are formed in the host nucleus and then the nucleocapsid gets into these vesicles.
https://www.ncbi.nlm.nih.gov/books/NBK138305/figure/ch03.F8/<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.ncbi.nlm.nih.gov_books_NBK138305_figure_ch03.F8_&d=DwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=OcjAxyXZb769Mk6PvAyea-L_MIn_8me_4SRS4zxnCds&m=J4yN9pjXUSvmDWhwS1mzzca75BWYc_FBUvJOpS0U8HQ&s=QbQO01-KhabUybx2Su1MJTZkf8Po8aTO3ega2jgBXXk&e=>

So the definition "The process starts when nucleocapsids, assembled or in the process of being built, induce formation of a membrane curvature in the host plasma or organelle membrane and wrap up in the forming bud. The process ends when the bud is eventually pinched off by membrane scission to release the enveloped particle into the lumenal or extracellular space." seems incorrect.

Hope this helps.
Regards,
Patrick.

**Comment by pgaudet** [comment]
I can close this then ? 

Thanks, Pascale

**Comment by mcgu2014** [comment]
Yes. Thank you!


On Apr 20, 2017, at 07:01, pgaudet <notifications@github.com<mailto:notifications@github.com>> wrote:


I can close this then ?

Thanks, Pascale
