### ISSUE TITLE
GO:0090688 & GO:0090689 defs backwards

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#13389]
GO:0090688 ! cleavage furrow rim has a definition that makes sense for  GO:0090689 ! cleavage furrow leading edge and vice versa. They should be:

id: GO:0090688
name: cleavage furrow rim
def: "The part of the cleavage furrow closest to the cell surface." [GOC:vw, PMID:27082518]

id: GO:0090689
name: cleavage furrow leading edge
def: "The 'trough' of the cleavage furrow. This is the part of the cleavage furrow closest to the contractile ring." [GOC:vw, PMID:27082518]

See Fig. 10E in the cited paper.

(they were the wrong way round as initially listed in #12556; I happened to notice en route to checking something else ...)

**Comment by ValWood** [comment]
Hmm, I  suspect my annotations will be the wrong way around too...

**Comment by pgaudet** [comment]
I made the changes, so please review the annotations. I didn't check if
there were non - pombe annotations.

Thanks, Pascale

Le 24 avr. 2017 10:28 PM, "Val Wood" <notifications@github.com> a écrit :

Hmm, I suspect my annotations will be the wrong way around too...

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/geneontology/go-ontology/issues/13389#issuecomment-296812460>,
or mute the thread

**Comment by ValWood** [comment]
all good...

**Comment by pgaudet** [comment]
Great !
