### ISSUE TITLE
OTR: children of GO:0003906_!_DNA-(apurinic_or_apyrimidinic_site)_lyase_activity

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#13409]
The flip side of #10725

GO:0003906 has these direct children
Is a	 GO:0000703	oxidized pyrimidine nucleobase lesion DNA N-glycosylase activity
Is a	 GO:0000704	pyrimidine dimer DNA N-glycosylase activity
Is a	 GO:0008534	oxidized purine nucleobase lesion DNA N-glycosylase activity

These are all incorrect. First, a DNA N-glycosylase is not the same as the endonuclease that cleaves the backbone. Second, the damaged bases are not abasic. These activities create the substrate for the APE, but they are not APEs themselves.

**Comment by pgaudet** [comment]
Hi @jimhu-tamu , 

I removed the parent 'GO:0003906_!_DNA-(apurinic_or_apyrimidinic_site)_lyase_activity'. The remaining parent is " GO:0000702 oxidized base lesion DNA N-glycosylase activity". 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @jimhu-tamu 

One other question about this: 
do you know if it's OK that GO:0003906 DNA-(apurinic or apyrimidinic site) lyase activity is a child of both 
-  GO:0016835 carbon-oxygen lyase activity
- and indirectly ot GO:0016788 hydrolase activity, acting on ester bonds (via nuclease activity)? 

Either these two reactions are synonymous, or the enzyme catalyzes two reactions - or one of the reactions is wrong.  

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
@pgaudet per wikipedia, there are four classes that use different chemistry and that cleave in different places.

https://en.wikipedia.org/wiki/AP_endonuclease

> There are four types of AP endonucleases that have been classified according to their mechanism and site of incision. Class I AP endonucleases cleave 3' to AP sites by a β-lyase mechanism, leaving an unsaturated aldehyde, termed a 3'-(4-hydroxy-5-phospho-2-pentenal) residue, and a 5'-phosphate. Class II AP endonucleases incise DNA 5' to AP sites by a hydrolytic mechanism, leaving a 3'-hydroxyl and a 5'-deoxyribose phosphate residue.[2] Class III and class IV AP endonucleases also cleave DNA at the phosphate groups 3´ and 5´to the baseless site, but they generate a 3´-phosphate and a 5´-OH.[3]

I think the current term definition applies to only to Class I. It seems to me that there should be an umbrella term for AP endo activity independent of mechanism, with children for the classes. Based on the wikipedia article, it may turn out that most of the annotation to this term is incorrect wrt lyase vs nuclease.

**Comment by pgaudet** [comment]
Hi again, 

I thought it was outside the scope of GO to capture reaction mechanisms. I am happy to create new terms if needed. I will bring that up at the next editors call. 

Pascale

**Comment by pgaudet** [comment]
I checked a number of proteins annotated to  GO:0003906_!_DNA-(apurinic_or_apyrimidinic_site)_lyase_activity to see how they were annotated in UniProt. UniProt has a note on all the ones I checked that says “The C-O-P bond 3' to the apurinic or apyrimidinic site in DNA is broken by a beta-elimination reaction, leaving a 3'-terminal unsaturated sugar and a product with a terminal 5'-phosphate.” This refers to the  ‘ClassI’, mechanism, but there also Class 2 in that list (at least P87175), see: https://en.wikipedia.org/wiki/AP_endonuclease

Kristian Axelen from UniProt is looking into this. 

@hdrabkin 

Thanks, Pascale





A8JR14	CG6171
B9DFZ0	NTH2
G5EBR7	exo-3
G5EBR7	exo-3
O35980	Nthl1
P04418	
P05523	mutM
P05523	mutM
P05750	RPS3
P0AB83	nth
P0AB83	nth
P17096	HMGA1
P17096	HMGA1
P19889	RpLP0
P22936	APN1
P22936	APN1
P22936	APN1
P23396	RPS3
P23396	RPS3
P23396	RPS3
P23396	RPS3
P23396	RPS3
P27695	APEX1
P27695	APEX1
P27695	APEX1
P27695	APEX1
P27695	APEX1
P27864	Rrp1
P31378	NTG1
P38207	APN2
P45951	ARP
P50465	nei
P50465	nei
P52926	HMGA2
P62908	Rps3
P78549	NTHL1
P87175	apn2
P9WNB9	nei1
Q06559	RpS3
Q06559	RpS3
Q08214	NTG2
Q10002	apn-1
Q13686	ALKBH1
Q564V5	exo-3
Q564V5	exo-3
Q8IW19	APLF
Q8K203	Neil3
Q8LK56	DME
Q8TAT5	NEIL3
Q9SIC4	NTH1

**Comment by pgaudet** [comment]
The decision from the GO editors discussion is to represent all different activities.

**Comment by jimhu-tamu** [comment]
Hi Pascale, not sure I understand which way the discussion went. One term to represent different activities or all activities represented by their own terms? I'm OK with either as long as the definitions are consistent.

**Comment by pgaudet** [comment]
It would be different terms, since they need to have different parents. If you have suggestions for name and definitions those would be welcome ! 

Thanks, Pascale

**Comment by pgaudet** [comment]
Created 3 new terms: 
 [Term]
+id: GO:0140078
+name: class I DNA-(apurinic or apyrimidinic site) lyase activity
+namespace: molecular_function
+def: "Catalysis of the cleavage of an AP site 3' of the baseless site by a beta-lyase mechanism, leaving an unsaturated aldehyde, termed a 3'-(4-hydroxy-5-phospho-2-pentenal) residue, and a 5'-phosphate." [PMID:1698278, Wikipedia:AP_endonuclease]
+synonym: "AP endonuclease class I activity" RELATED []
+xref: EC:4.2.99.18
+xref: MetaCyc:4.2.99.18-RXN
+is_a: GO:0003906 ! DNA-(apurinic or apyrimidinic site) lyase activity
+created_by: pg
+creation_date: 2017-07-24T11:33:34Z
+
+[Term]
+id: GO:0140079
+name: class II DNA-(apurinic or apyrimidinic site) lyase activity
+namespace: molecular_function
+def: "Catalysis of the cleavage of an AP site 5' of the baseless site, by a hydrolytic mechanism, leaving a 3'-hydroxyl and a 5'-deoxyribose phosphate residue." [PMID:1698278, Wikipedia:AP_endonuclease]
+is_a: GO:0003906 ! DNA-(apurinic or apyrimidinic site) lyase activity
+is_a: GO:0004518 ! nuclease activity
+created_by: pg
+creation_date: 2017-07-24T11:46:03Z
+
+[Term]
+id: GO:0140080
+name: class III/IV DNA-(apurinic or apyrimidinic site) lyase activity
+namespace: molecular_function
+def: "Catalysis of the cleavage of an AP site 3' and 5' of the baseless site, generating a 3´-phosphate and a 5´-OH." [PMID:2519777, Wikipedia:AP_endonuclease]
+synonym: "endonuclease III" RELATED []
+synonym: "endonuclease IV" RELATED []
+xref: EC:4.2.99.18
+xref: MetaCyc:4.2.99.18-RXN
+is_a: GO:0003906 ! DNA-(apurinic or apyrimidinic site) lyase activity
+created_by: pg
+creation_date: 2017-07-24T11:48:18Z


==== 

Modified the parent of GO:0003906_!_DNA-(apurinic_or_apyrimidinic_site)_lyase_activity because it's not classified as a nuclease (ie, an hydrolyze) by EC, except for Class II. 
-is_a: GO:0004520 ! endodeoxyribonuclease activity

=== 

Added cross ref EC:4.2.99.18 to Class I and III, but not Class II because that's the enzyme with the hydrolytic mechanism. However EC lists APEX2_HUMAN as one member of the EC:4.2.99.18 class - I don't know why EC doesn't distinguish the different classes. 

Pascale

**Comment by pgaudet** [comment]
Terms are in the ontology, I am waiting for feedback from K. Axelen before closing.

**Comment by pgaudet** [comment]
Message to Kristian Axelen:  
Hello, 

 There are 3 types en endonucleases, Class I, II and III (see 
 https://en.wikipedia.org/wiki/AP_endonuclease
 http://pubs.acs.org/doi/pdfplus/10.1021/cr980321h

 According to wikipedia human APE1 (P27695) is a Class II. I wonder if its current EC number is correct, which refers to Class I (and possibly Class III ) reactions. 

 I am trying to fix the corresponding GO terms; and input would be much appreciated ! 

 Thanks, Pascale
----
Reply: 
Hi Pascale,

You are right, APE1 is a class II AP endonuclease, and no EC 4.2.99.18 cannot be used as it only covers the class I enzymes. It took me a little while to understand the subject since also the wikipedia article was misleading by citing the EC number (as BRENDA 4.2.99.18) just after the name AP endonuclease. I have now corrected this error in wikipedia.

Next, it complicates matters that only the class I enzymes have a unique EC number. There are at least two EC numbers associated with class II enzymes, Exodeoxyribonuclease III (EX3_ECOLI), to which APE1 is similar, is covered by EC 3.1.11.2, while Endonuclease 4 (END4_ECOLI) to which APN1_YEAST (P22936) is covered by EC 3.1.21.2.

So, while I can quite easily correct the EC errors concerning APE1 and APN1, it will be a much larger task to verify the annotation of the 626 other Swiss-Prot entries annotated as EC 4.2.99.18 enzymes.

I will keep you updated when I more progress to report.

Cheers,

Kristian

**Comment by pgaudet** [comment]
This ticket is closed as far as GO is concerned. @kaxelsen : I am notifying you that I am closing this. 

Thanks, Pascale
