### ISSUE TITLE
GO:0030663 COPI-coated vesicle membrane parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13410]
Why is that?

2017-04-06	Deleted	RELATION	part of GO:0030137 (COPI-coated vesicle)

v

**Comment by ValWood** [comment]
GO:0030127 COPII vesicle coat also does not have the  COPII-coated vesicle, but tat does not have the membrane term parent either
 COPII-coated vesicle membrane  (this does not seem to exist, so its a bit inconsistent)

**Comment by ukemi** [comment]
Where are you seeing this? I see this relationship in the ontology.

**Comment by ValWood** [comment]
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0030663#term=ancchart

**Comment by ukemi** [comment]
Odd... Here is the obo-stanza from my most recent copy of the ontology. In fact this shouldn't even need to be asserted since bounding_layer_of is a type of part_of and it should be added in the release if it was missing.

@cmungall any ideas?

[Term]
id: GO:0030663
name: COPI-coated vesicle membrane
namespace: cellular_component
def: "The lipid bilayer surrounding a COPI-coated vesicle." [GOC:mah]
synonym: "COPI coated vesicle membrane" EXACT [GOC:sl]
intersection_of: GO:0098805 ! whole membrane
intersection_of: bounding_layer_of GO:0030137 ! COPI-coated vesicle
relationship: part_of GO:0030137 ! COPI-coated vesicle

**Comment by cmungall** [comment]
Yes, I see what is going on:

As part of reasoning, we trivially infer

```
[1] relationship: bounding_layer_of GO:0030137 ! COPI-coated vesicle
```

We then make a reduced graph that has all redundancies eliminated, which gets rid of

```
[2] relationship: part_of GO:0030137 ! COPI-coated vesicle
```

(since it's redundant via SubPropertyOf)

Then, when we make go.obo we apply a relation filter, and retain part_of etc but not bounding_layer_of.

Clearly this is not good.

This was a misconfiguration on my part. When performing the filtering step, I didn't configure a reasoner. I will do this, which means that rather than filtering blindly it will roll up to the most specific relation in the filter (part-of in this case).

Once done, i can quantify the scale of the problem.

apologies..

**Comment by cmungall** [comment]
OK, the commit above ensures that the rollup to part_of is done. I will check the fix percolates through tomorrow.

**Comment by ukemi** [comment]
Thanks @cmungall  once you have checked, you can close this ticket.

**Comment by ukemi** [comment]
@cmungall. I am not seeing this on any of the public browsers.

**Comment by ukemi** [comment]
Looks like this is fixed.
