### ISSUE TITLE
ntr:mitotic spindle midzone asymmetry

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#13427]
@ukemi and @ValWood
As you guys are the experts in cell cycle and spindle-things, could you help me out here:

I am looking at asymmetric distribution of sara positive endosomes in asymmetric cell division. This asymmetry is believed to arise by the generation of asymmetry at the spindle midzone by biased MT depolymerization (PMID:26659188).

I think that the term name/def below works - but I am not so confident on where it should sit in the GO:
Perhaps
Is_a GO:0051256 mitotic spindle midzone assembly
But is doesn't seem quite right and I am wondering whether a intermediate term such as "mitotic spindle midzone organisation" as a child of GO:0007052 mitotic spindle organization is a better solution.

Name:mitotic spindle midzone asymmetry
Def:The generation of asymmetry at the spindle midzone during mitotic anaphase due to unequal microtubule depolymerization rates.
Ref:PMID:26659188

**Comment by ValWood** [comment]
Hmm I'm not sure.

Even though the process  originates at the spindle midzone, the entire spindle is asymmetric. I think I would call the process
 "establishment of mitotic spindle asmmetry"

then it can sit under
GO:0007052 mitotic spindle organization

I wonder if we need to change the parent 

GO:0140014 mitotic nuclear division
of
GO:0090307 mitotic spindle assembly
to has part.
because this role, isn't part of nuclear division, even though when it occurs it is always part of mitosis.

I'd like to know  little more about the process before we make major changes though.
A lot of  asymmetry arises from the spindle. The old and new spindle pole body result in the asymetric localization of signalling networks, and I believe these are somehow involved in  asymmetry in animal cells.  

Can you outline how the process is thought to work?
-Presumably  this particular asymmetry does not determine the asymetric cell division itself (I'm assuming that is defined when the contractile ring is localized), but it determines the asymmetric distribution of sara positive endosomes

How do they demonstrate that these are spindle microtubules?
- Similar asymmetry occurs in fission yeast, but via interphase microtubules.....way out of my comfort zone. ....right now I'm thinking why are these flies trying to localize their endosomes while they are doing mitosis? At what point in the cell cycle does this process occur?

So glad I work on a simple system
I will have a look at the paper later.

**Comment by hattrill** [comment]
"Can you outline how the process is thought to work?
-Presumably this particular asymmetry does not determine the asymetric cell division itself (I'm assuming that is defined when the contractile ring is localized), but it determines the asymmetric distribution of sara positive endosomes"
So the asymmetry they refer to here is wrt the distribution of cell fate determinants rather than the location of the cleavage plane. Here's a long-winded digest:
The model is of asymmetric cell fate assignation through asymmetric Notch signalling in sensory organ precursor (SOP) division. SOPs divide into pIIa and pIIb daughter cells. Sara endosomes which contain endocytosed Notch and Delta segregate to the pIIa daughter, but not the pIIb.

The asymmetry measured is defined with respective to region marked by pavarotti - the central region where the spindles overlap in an antiparallel fashion. The model is that klp98A (+ve end directed kinesin) links the sara endosomes to the MTs. When the central region is symmetric, the net movement is symmetric as they just move back and forth between antiparallel spindle MTs. The central spindle “becomes” asymmetric in that microtubule density and the minus end marker Patronin are higher on the pIIb side. This asymmetry occurs in anaphase and is most pronounced in late anaphase. It appears that this is because MT depolymerization (mediated by Klp10A) is faster on the PIIa side as MTs are protected (by Patronin) on the pIIb side. Because there are less MTs to return to the center on on the pIIa side the sara endosomes have a net shift to that side and are released into the pIIa cytoplasm. (plus they propose that the central region is a diffusion barrier that contributes to/maintains this).

"How do they demonstrate that these are spindle microtubules?"
It's one of those super resolution imaging papers: lots of labeling with MT binding proteins! 

This:
"establishment of mitotic spindle asmmetry" under GO:0007052 mitotic spindle organization seems a good fit to me.

This:
"GO:0140014 mitotic nuclear division
of
GO:0090307 mitotic spindle assembly
to has part"
I really don't know. GO:0140014 mitotic nuclear division seems fairly broadly defined.

**Comment by ValWood** [comment]
OK in that case I think
"establishment of mitotic spindle asmmetry" under GO:0007052 mitotic spindle organization 
is fine.

Interesting. So far the only things I have come across moving on the spindle are things which need to localize to the spindle pole body or kinetochore.....so it can also transport vesicles so they are in the right daughter cell...neat...

**Comment by hattrill** [comment]
It is pretty neat (and it's been on my desk for a while as it looked tricky - so thanks for looking at this).

**Comment by ukemi** [comment]
We also have 'establishment of mitotic spindle localization' and 'asymmetric protein localization involved in cell fate determination'. I'm thinking one of these may be a better parent? I am reluctant to create 'asymmetric protein localization involved in cell fate determination by establishment of mitotic spindle localization' though. You're right. It is very cool.

**Comment by hattrill** [comment]
I think for this particular subprocess - the trimming or lack of trimming I prefer this:
establishment of mitotic spindle asmmetry under GO:0007052 mitotic spindle organization
as "establishment of mitotic spindle localization" seems to decribe a more global effect.

and I think that 'asymmetric protein localization involved in cell fate determination' pefectly describes the bit that happens after the 'establishment of mitotic spindle asmmetry'.

(you can keep the 14-worder - I'm not that crazy!)

I am also having a side discussion on sara endosomes which is drifting into process terms now - I always knew this would be a sticky one!  #13421

**Comment by ukemi** [comment]
[Term]
+id: GO:0061867
+name: establishment of mitotic spindle asymmetry
+namespace: biological_process
+def: "The mitotic spindle organization process by which a mitotic spindle becomes asymmetric either in position or structure." [PMID:26659188]
+is_a: GO:0007052 ! mitotic spindle organization
+created_by: dph
+creation_date: 2017-04-28T12:39:13Z
