### ISSUE TITLE
mitochondria-associated membrane?

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#13450]
Dear all,
we have the term "mitochondria-associated membrane" as location for enzyme 2.7.8.2 in our database. Do you think this is a new term? Could it be a synonym of: GO:0036266
name: Cdc48p-Npl4p-Vms1p AAA ATPase complex?

https://biologydictionary.net/rough-endoplasmic-reticulum/: BiP, CNX/CRT and other chaperones are enriched in regions of the ER that interact closely with mitochondria. This section of the ER is called MAM, or mitochondria-associated membrane. The MAM is emerging as an important signaling hub within the cell that integrates signals from the ER and plays a role in calcium homeostasis, autophagy, apoptosis and mitochondrial function.

**Comment by krchristie** [comment]
Hi,

I don't think it would be appropriate for MAM to be a synonym of GO:0036266 since that term represents a complex, and MAM is a location where that complex can be localized to. However, it turns out we already have a term for what you are looking for:

GO:0044233 - ER-mitochondrion membrane contact site

To aid in finding this term, I have added these synonyms:

exact synonym: mitochondria-associated ER membrane 
exact synonym: mitochondria-associated membrane 
related synonym: MAM

-Karen
