### ISSUE TITLE
OTR remove parent 'multi-organism cellular process' from 'viral process'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13467]
Hello, 

After discussion with the ViralZone group, we propose to remove the parent 'multi-organism cellular process' from 'viral process'; this way viral processes are not cellular (which is consistent with the fact that viruses are not cells). 

Any comments/objections ? @jimhu-tamu 
(not sure who else to tag). 

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
I don't object to removing that parent, but not for that reason (see below). The definition of multi-organism cellular process  is "Any process that is carried out at the cellular level which involves another organism of the same or different species". To me, that only requires that the process in question happen at the cellular level, not that it involve two cellular organisms, or even that the main interacting organisms be cellular (e.g. GO:0098669 superinfection exclusion).  If both have to be at the cellular level, it's not clear to me how the virus infection processes are different from things like GO:0035915 pore formation in membrane of other organism.

I think viral process should not be an is_a child of multi-organism cellular process because I think that viral processes are not all at the cellular level. For example: There are viruses that use host extracellular proteases for their maturation (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4328142/). I believe that the protease doesn't gave to originate from the infected cell, but rather from the tissue being infected.

**Comment by pgaudet** [comment]
@pmasson55 : any comment ?

**Comment by pmasson55** [comment]
I guess it's fine if we all agree that this branch should be removed.

**Comment by pgaudet** [comment]
Hi @jimhu-tamu , 

just so I am clear: you do agree that no viral process should be a child of 'multi-organism *cellular* process' ? I am starting to remove all connections that cause this link as well. See also 
https://github.com/geneontology/go-ontology/issues/13468

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
@pgaudet 

I think you're not clear about what I'm saying because it's not clear in my own mind! 

I do not agree that no viral process should be a child of 'multi-organism cellular process'. Clearly, some viral processes occur in host cells.  However, the example was to illustrate that _some_ viral processes are extracellular.

I think that means I would remove the multi-organism cellular process parentage as you proposed, some but not all of the child terms for viral process should be reconnected to multi-organism cellular process either directly or via an NTR for one or more intermediate umbrella terms. 

I think that how to do that is beyond the scope of this tracker item

**Comment by pgaudet** [comment]
Hi Jim, 

The issue is with *cellular*. In GO (and elsewhere) "cell" is defined as "The basic structural and functional unit of all organisms. Includes the plasma membrane and any external encapsulating structures such as the cell wall and cell envelope.", which excludes viruses. Moreover, "virion" is a sibling of "cell". 

GO has a concept "host cell" to represent processes that occur in the host's cellular environment. So, since in CC the virion is disjoint from the cell, to be consistent this should also be the case in BP (see attached diagram of a few examples of relevant terms). 
![image](https://cloud.githubusercontent.com/assets/4782928/25796394/a3866e6c-33d9-11e7-94ec-001fec2272e7.png)


Does that clarify my point ? 

Thanks, Pascale

**Comment by jimhu-tamu** [comment]
I'm afraid I'm still confused. While it seems to me that there is clearly an issue with cellular, I'm not sure how it relates to the posted image. Are you saying that a process that occurs in a host cell is not cellular because it is occurring in a component in the host cell branch and not in the cell branch? So there should be a distinction between _cellular_ and _host cellular_?

I would think that GO would not want to replicate the parallel host cell structure from CC to BP. There's a note on GO:0044215 ! other organism that talks about plans to obsolete that term.  But independent of the note, one of the things that is pushing us toward trying to be more LEGO/GO-CAF compliant for CACAO is how the host cell stuff leads toward an internal duplication in the CC tree. I'm thinking it makes more sense to collapse to a single concept of cell and use some kind of occurs_in added info to distinguish host from symbiont.

**Comment by pgaudet** [comment]
Hi @jimhu-tamu , 

What I am saying is that right now there *is* a distinction between cellular and host cellular, so the changes I am proposing are consistent with this structure. 

Also, since viruses are not cells, they cannot have cellular processes without breaking the logic of the ontology. 

There is another issue discussing cellular processes: https://github.com/geneontology/go-ontology/issues/12849
We can make further modifications according to decisions there. 

Makes more sense ? 

Thanks, 
Pascale

**Comment by pgaudet** [comment]
testing notifications
