### ISSUE TITLE
Obsoletion of GO:0003840 gamma-glutamyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13571]
Hello, 

Following up from
https://github.com/geneontology/go-annotation/issues/1514
The term's comment states that this is NOT a physiological reaction. This term will therefore be obsoleted. 

"The gene family commonly referred to as gamma-glutamyl transferases (GGT) catalyze hydrolysis of gamma-glutamyl bonds in gamma-glutamyl compounds such as glutathione. In a test tube one can set up conditions in which the enzyme will transfer the gamma-glutamyl portion of the substrate to an acceptor molecule, but this requires non-physiologic conditions, including millmolar concentrations of an acceptor such as glygly. This reaction is used in assays to detect the presence of the enzyme, but is not a physiological function of members of the GGT family (PMC4388159), which should be annotated to a suitable hydrolysis term instead (e.g. glutathione hydrolase activity)."

Thanks, 
Pascale

**Comment by pgaudet** [comment]
Hi Val, 

I was getting started to do this but it seems like this term is legitimate: there are several papers (for eg PMID:16618936,  PMID:6118826, also there is an EC number. 

When I read the comment more carefully, it seems like the enzymes does hydrolyze glutathione. The non-physiological part seems to be the transfer the gamma-glutamyl portion of the substrate to an acceptor molecule. 

What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Hi Pascale,

I re read the comment, and I still think that what the comment is saying is  that

a) gamma-glutamyltransferase activity is not physiologically relevant , at least for GGTase family because the transferase part of the reaction does not happen

b) the correct term to describe this reaction is "glutathione hydrolase activity"

I looked at this many times to re-explain it to people. The EC number exists because the reaction is possible, and therefore legitimate (and it is possible that it exists for another enzyme? but as yet we do not have any examples).

It is possible that I completely reinterpreted the whole thing, in which case we should make alternative revisions and I will tell everyone to reinstate the old annotations.

@deustp01  didn't look yet Peter, does  my interpretation make sense?

**Comment by deustp01** [comment]
Specifically about EC, my understanding is that, yes, existence of a number means that enzymologist experts agree that the reaction can happen, but that can include reactions only definitively studied in vitro. Indeed, didn't some of the earlier discussion get at exactly this point: the transferase reaction happens - in fact is exploited for a useful in vitro clinical assay - but only when reactants are present in amounts far different from ones ever found (so far) in any living system. So (keeping in mind that I don't know anything about this specific piece of biochemistry) points a and b in Val's comment look right.
