### ISSUE TITLE
gastric terms

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13607]
I would like to see "intestinal motility" added under "digestive system process" (GO:0022600) and "small intestinal transit" added as child of "intestinal motility".  It would also be nice to have “regulation of…, positive regulation of…, and negative regulation of…” child terms under "small intestinal transit".  I would also like to see “regulation of…, positive regulation of…, and negative regulation of…” child terms added under "gastric emptying (GO:0035483)".   PMID:15890336

I would like to see “stomach smooth muscle contraction” (synonym: gastric smooth muscle contraction) added to GO in between the parent term “gastro-intestinal system smooth muscle contraction” (GO:0014831) and the children terms “distal stomach smooth muscle contraction” (GO:0014828) and “proximal stomach smooth muscle contraction” (GO:0014847).  I would also like to see “stomach pylorus smooth muscle contraction” as child of “distal stomach smooth muscle contraction” (GO:0014828).  In addition “pyloric antrum smooth muscle contraction” (synonym: “antrum smooth muscle contraction”), “pyloric canal smooth muscle contraction”, and “pyloric sphincter smooth muscle contraction” would be appropriate children for “stomach pylorus smooth muscle contraction”. PMID:15890336

**Comment by slaulederkind** [comment]
I would also like to see “regulation of…, positive regulation of…, and negative regulation of…” child terms added under "stomach fundus smooth muscle contraction" (GO:0014825) and under "pyloric antrum smooth muscle contraction” (requested above).  Thanks.

**Comment by krchristie** [comment]
Hi Stan,

Very dense request!! I've broken it out in a different format to make sure I catch it all, and also because I need more info for some of these. Here's the info I need from you:
* for the new terms, please suggest definitions.
* Is PMID:15890336 an appropriate definition reference for all of these new terms?
* Please consider the question about whether there should be other terms under 'intestinal motility'.

thanks,

Karen

- [ ] _Under 'digestive system process'_
* intestinal motility 
-- **Please suggest a definition**
-- **Question**: Should there be any other terms under 'intestinal motility'? It seems odd to have only a single child term under 'intestinal motility'
* small intestinal transit 
-- **Please suggest a definition**
* 3 reg terms of 'small intestinal transit' (**fine once you define the base term**)



- [ ] _3 regulation terms under 'gastric emptying'_
These seem straight forward: “regulation of…, positive regulation of…, and negative regulation of…” child terms added under "gastric emptying (GO:0035483)"

- [ ]  _new term request_ (seems fine, should be able to extrapolate a def from existing terms)
“gastro-intestinal system smooth muscle contraction” (GO:0014831) 
-- “stomach smooth muscle contraction” GO:new (synonym: gastric smooth muscle contraction) 
--- “distal stomach smooth muscle contraction” (GO:0014828) 
--- “proximal stomach smooth muscle contraction” (GO:0014847)


- [ ] _stomach pylorus related new term requests_
**Please provide definitions for all four of these new term request.**
--“stomach pylorus smooth muscle contraction”
--- “pyloric antrum smooth muscle contraction” (synonym: “antrum smooth muscle contraction”)
--- “pyloric canal smooth muscle contraction”
--- “pyloric sphincter smooth muscle contraction” 


- [ ] _more regulation terms_
-- all three regulation terms added 
--- under "stomach fundus smooth muscle contraction" (GO:0014825)  
--- under "pyloric antrum smooth muscle contraction” (requested above, **fine once you define the base term**)

**Comment by slaulederkind** [comment]
"intestinal motility": Contractions of the intestinal tract that include peristalsis (moving contents onward) and non-peristaltic movement (moving contents back and forth).

"small intestinal transit": Migration of ingested material along the length of the small intestine. Synonyms: small bowel transit, small intestine transit

"large intestinal transit": Migration of ingested material along the length of the large intestine.  Synonyms: colonic transit, large intestine transit, large bowel transit, colon transit  PMID:28157109 

"stomach smooth muscle contraction": A process in which force is generated within gastric smooth muscle tissue, resulting in a change in muscle geometry. This process occurs throughout the length of the stomach. 

“stomach pylorus smooth muscle contraction": A process in which force is generated within gastric smooth muscle tissue, resulting in a change in muscle geometry. This process occurs in the most distal part of the stomach. 

“pyloric antrum smooth muscle contraction": A process in which force is generated within gastric smooth muscle tissue, resulting in a change in muscle geometry. This process occurs in the widest part of the pylorus that is continuous with the body of the stomach. (synonym: “antrum smooth muscle contraction”)

“pyloric canal smooth muscle contraction”: A process in which force is generated within gastric smooth muscle tissue, resulting in a change in muscle geometry. This process occurs in the widest part of the pylorus that is continuous with the body of the stomach.

“pyloric sphincter smooth muscle contraction": A process in which force is generated within gastric smooth muscle tissue, resulting in a change in muscle geometry. This process occurs in the narrowest part of the pylorus that separates the stomach from the duodenum.

**Comment by krchristie** [comment]
Thanks for all these defs Stan. I'm going to assume that the PMID you gave in the intitial request and your curator reference (assuming that is GOC:sl) are appropriate for the def dbxrefs for all of these new terms. If it should be otherwise, let me know.

**Comment by slaulederkind** [comment]
The only difference in PMID dbxref should be:
"large intestinal transit": Migration of ingested material along the length of the large intestine. Synonyms: colonic transit, large intestine transit, large bowel transit, colon transit PMID:28157109

**Comment by krchristie** [comment]
Great. Thanks Stan :)

**Comment by krchristie** [comment]
Hey Stan,

The two defs seem identical. Please let me know which term this is the correct def for and provide the update for the other one.

“pyloric antrum smooth muscle contraction": A process in which force is generated within gastric smooth muscle tissue, resulting in a change in muscle geometry. This process occurs in the widest part of the pylorus that is continuous with the body of the stomach. (synonym: “antrum smooth muscle contraction”)

“pyloric canal smooth muscle contraction”: A process in which force is generated within gastric smooth muscle tissue, resulting in a change in muscle geometry. This process occurs in the widest part of the pylorus that is continuous with the body of the stomach.

thanks,

Karen

**Comment by slaulederkind** [comment]
Oops, I didn't complete the third part of copy/paste/edit.  
“pyloric canal smooth muscle contraction”: A process in which force is generated within gastric smooth muscle tissue, resulting in a change in muscle geometry. This process occurs in the distal part of the pylorus between the pyloric antrum and the pyloric sphincter.

**Comment by krchristie** [comment]
Thanks for that last definition Stan. I did everything else yesterday, so I've commited it all now. You can see all the new terms and IDs here: 
https://github.com/geneontology/go-ontology/pull/13652/files

**Comment by cmungall** [comment]
note we also have this

```
[Term]
id: GO:0035482
name: gastric motility
namespace: biological_process
def: "The spontaneous peristaltic movements of the stomach that aid in 
digestion, moving food through the stomach and out through the pyloric 
sphincter into the duodenum." [GOC:cy, ISBN:9781416032458, 
PMID:16139031]
is_a: GO:0022600 ! digestive system process
created_by: rfoulger
creation_date: 2010-04-23T10:44:59Z
```

it's not intestinal but seems to make sense to have a more specific 
grouping like 'digestive tract motility'.

This grouping might even encompass:

```
[Term]
id: GO:0043050
name: pharyngeal pumping
namespace: biological_process
def: "The contraction and relaxation movements of the pharyngeal muscle 
that mediate feeding in nematodes." [GOC:cab1, PMID:2181052]
synonym: "pumping behavior" RELATED []
is_a: GO:0042755 ! eating behavior
```

**Comment by cmungall** [comment]
Should there be some connection or common grouping between intestinal 
motility and peristalsis?
