### ISSUE TITLE
methylglyoxal catabolic process (for slimming)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13611]
could this have the parent GO:1990748 cellular detoxification
(methylglyoxol is a toxic by-product of glycolysis)

 GO:0051596 methylglyoxal catabolic process

**Comment by pgaudet** [comment]
Hi Val, 

If this is always the case then I am tempted to rename the term 'cellular detoxification of methylglyoxal'. In this case 'catabolic process' seems to refer to the MF rather than to a biologically meaningful process. 

There are about 30-40 EXP annotations; as far as I can tell these are all involved in the removal of methylglyoxal. 
Groups with annotations: 
ecocyc 
TAIR @tberardini 
uniprot 
CGD 
SGD

If it's OK with everyone I'll rename the term and change the definition to 
"The chemical reactions and pathways resulting in the breakdown of methylglyoxal, CH3-CO-CHO, the aldehyde of pyruvic acid, to reduce or remove its toxicity." 

Thanks, Pascale

**Comment by ValWood** [comment]
I agree, I was going to suggest something along these lines.

There are a number of  "detoxification" pathways where the annotations do not map to  the slims ('catabolism' and  plain 'metabolism'  are too general to be useful as slim classifiers where the aim is to group into biologically relevant categories, they include too many disparate processes).

We included "detoxification" in the PomBase slim fairly recently  to pull  in a number of unslimmed gene products.
http://preview.pombase.org/browse-curation/fission-yeast-go-slim-terms

 we still have 123 fission genes which do not slim, but are biological process are annotated. A number of these are in detoxification pathways. There are indications that many of the "unknown" process genes will also be "detoxification".

I guess the danger is that some of these metabolites turn out to have a role in some species,  but I agree that "catabolism" is really only describing the  function in a process-y way. I don't see any reason not to rename/redefine if it fits the existing annotation and others agree.

**Comment by ValWood** [comment]
although we probably still want these processes classified as "catabolism" for other purposes.

I have used catabolism and anabolism/biosynthesis  come up in enrichments if you are looking at intersections with  viable or inviable  phenotypes and other orhtogonal classifiers which could be biologically useful, so I think maybe they still need a catabolism parentage...

**Comment by pgaudet** [comment]
Hello again, 

I will create a new term 'cellular detoxification of methylglyoxal' as a child of 'methylglyoxal catabolic process' then. People can move their annotations to the more precise term if they want. 

OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
yep!

**Comment by tberardini** [comment]
Since the original term, 'methylglyoxal catabolic process', was left in place, I did not move the TAIR annotation.
