### ISSUE TITLE
GO:0009407 toxin catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13617]
add parent
cellular detoxification
or just detoxification if this is not possible.

**Comment by krchristie** [comment]
Hi Val, 

It seems there could be situations where a degradative enzyme is secreted from the cell to detoxify the offending substance outside of the cell, perhaps in a way that wouldn't be 'cellular', so I'm not sure I'm comfortable using 'cellular detoxification' as the parent.

There's also some discussion of eliminating the distinction between "x process" and "cellular x process". @ukemi - Do you have any thoughts on Val's request?

-Karen

**Comment by ukemi** [comment]
I agree. Although I can't think of an example off the top of my head, I would think that toxins could be catabolized at a level other than cellular. I also assume that in this case the role of toxin is contextually assigned in the organism that is carrying out the process, so it would always be detoxification?

**Comment by krchristie** [comment]
GO already has terms for both 'toxin metabolic process' and 'detoxification', so I was going to assume that we've taken your point into account that "the role of toxin is contextually assigned in the organism that is carrying out the process". If we're going to completely revisit the "toxin" debate, that's one thing (that I was going to avoid...)

However, since these terms already exist in GO, I agree with Val, that 'detoxification' should be a parent of 'toxin catabolic process'.

**Comment by ValWood** [comment]
The parent could be just "detoxification" . Detoxification is the term we put in our slim because it would be difficult to call all "detoxification" cellular.

I'd also be happy for "toxin" terms not to exist.

This one came up because
"mycotoxin catabolic process" has the parent  "toxin catabolic process"
but for obvious reasons 
http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0009407#term=ancchart
does not slim, the parents are just too general.



There are only  12 EXP to  "toxin catabolic process" total.
The children  could be just "detoxification" with no intermediate "toxin catabolic process" term.....

**Comment by krchristie** [comment]
Regarding:
<pre>The children could be just "detoxification" with no intermediate "toxin catabolic process" term.....</pre>

Unless we're going to open the box of getting rid of toxin terms, and I don't really want to open it, I'd rather just keep 'toxin catabolic process' since 'detoxification' can occur without catabolism, e.g. just transporting it out of the cell.

So, I've just added the 'detoxification' parent to 'toxin catabolic process'.

change shown here:
https://github.com/geneontology/go-ontology/pull/13650/files

**Comment by ValWood** [comment]
Thanks Karen, I agree, that's best for another day, it isn't critical.  Good point also about the efflux, I forgot about that. Toxin and drug terms are problematic but we have lived with them for a while without major problems...
