### ISSUE TITLE
GO:0005472 FAD carrier activity obsolete?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13651]
Is not defined as a transmembrane transporter 

Its def is:
"Catalysis of the transfer of flavin adenine dinucleotide from one side of a membrane to the other, "

although it is a child of transmembrane transporter ?

transmembrane transporter def is:
"Enables the directed movement of x  across a membrane into, out of or within a cell, or between cells."

(I think "from one side of a membrane to the other" is usually used for "translocation" isn't it?)

Anyway since this has no annotations, and is confusing, obsolete?

**Comment by hdrabkin** [comment]
I can find no reason for this term being created (ie, no PMID, etc. 
As you say, appears no one has used this for annotation, so I will put out the Obsoletion notice today

**Comment by hdrabkin** [comment]
Sent to GO-consortium and GO-friends

The proposal has been made to obsolete: GO:0005472 FAD carrier activity
 
There are no annotations to this term. The reason for obsoleting is that the definition deemed confusion. It is a child of transmembrane transporter but it’s definition does not designate it as one (Catalysis of the transfer of Flavin adenine dinucleotide from one side of a membrane to the other); no literature reference was used.
Comments can be made here: 
https://github.com/geneontology/go-ontology/issues/13651
 

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on September 20.
*** Unless objections are received by Septermeber 20 , we will assume that you agree to this change. ***

**Comment by hdrabkin** [comment]
Can @mah11 please comment? The term appears to have been made by you (GOC:MAH). Do you possibly remember why/when?

**Comment by mah11** [comment]
I did not create this term; its ID indicates that it predates created_by and creation_date tags, and was part of the original set of GO terms whose provenance can best be summarized as "Michael Ashburner brain dump".

I also don't remember precisely how the current definition came to be, although I must have plugged it in (that would be the actual reason the _def dbxref_ is my initials). Without doing a lot of potentially fruitless digging, my best guess now is that GO editors got hold of a definition for "carrier activity" that we/they thought would do generally, and I applied it to FAD. Certainly a lot of the text looks pasted in rather than individually crafted & researched.

I will not miss the term if it goes away, and have no preference whether it's made obsolete or merged into something more clearly defined and useful.

**Comment by hdrabkin** [comment]
Ok thanks Midori.

**Comment by hdrabkin** [comment]
Hi @ValWood 
I was hesitant to do this but  Pascale suggested merging with
GO:0015230 FAD transmembrane transporter activity. What do you think?

**Comment by ValWood** [comment]
Hi Harold,
A merge is totally fine.
1. Its def and position implied transmembrane transport (even though the def did not match properly a TM transporter, I don't think it would be used for anything else).
2. Has no annotations.
3. Anyone  searching on FAD carrier is most likely looking for a FAD TM transporter term

I don't know if "FAD carrier" will be used in other contexts in the "carrier branch"  but  a "related" synonym might be best ?

**Comment by hdrabkin** [comment]
Merged; done.
