### ISSUE TITLE
NTR vascular anastomosis

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#13690]
PMID: 	28264837 

NTR vascular anastomosis- The connection of angiogenic sprouts to another vessel or sprout during the formation of vascular networks by sprouting angiogenesis.
PMID: 	28264837 
part of  GO:0002040 sprouting angiogenesis
NTR vascular anastomosis has_part 
NTR cell adhesion involved in vascular anastomosis - The attachment of a cell, either to another cell or to an underlying substrate such as the extracellular matrix, via cell adhesion molecules that contributes to the formation of a vascular network.
is_a 	GO:0007155 cell adhesion

NTR vascular anastomosis has_part 
NTR 	endothelial tip cell filopodium assembly-The assembly of a filopodium, a thin, stiff protrusion extended by the endothelial tip cell of a vascular sprout.
is_a GO:0046847 filopodium assembly

**Comment by dosumis** [comment]
Anastomosis sometimes used to refer to structure, rather than the process of fusion (for e.g. see Drosophila tracheal system terms in FBbt).  Might be worth adding a disambiguation comment on this.

**Comment by krchristie** [comment]
Hi Ceri,

Before making these terms, I have a couple comments/questions.

1. Based on David OS's comment, I did some searching in both Google and PubMed, and am inclined to agree that it could be a problem to use the word "anastomosis" to refer to the process of creating the fused vessel structure as well as the structure itself. I also see papers that use the simpler phrase "blood vessel fusion". Thus, it seems it might be clearer to use the phrase "blood vessel fusion" in the term names, and to use the word "anastomosis" in synonyms. Any objections to this idea to use blood vessel fusion in the primary term names?

2. I'm wondering if the synonyms should be related or exact. Based on the logic that acronyms are always made as "related" synonyms due to possible additional meanings, I'm inclined to make the anastomosis names "related" also, due to the additional meanings of "anastomosis" to refer to the structure as well as the process of generating the structure. @ukemi - thoughts on the synonym question?

3. You indicate wanting has_part relationships between "blood vessel fusion" and the other two new terms you request. However, has_part relationships don't allow mapping up from the more specific term to the more general term. For the term I labelled GO:new2 below, it seems that this part_of relationship would also be true: 
**"GO:new2 - cell adhesion involved in blood vessel fusion" part_of "GO:new1 - blood vessel fusion"**
If you agree, I'll put this in too.

4. For the definition dbxref, I usually credit a curator when they provide a suggested def. Is GO:cvs the correct GO dbxref for you?

thanks, Karen

Here are the three terms written out again, with my suggested modifications included.

GO:new1 - blood vessel fusion
Def: The connection of angiogenic sprouts to another vessel or sprout during the formation of vascular networks by sprouting angiogenesis. [PMID:28264837, GOC:cvs]
synonym (**type? EXACT? or RELATED?**) vascular anastomosis
part_of GO:0002040 sprouting angiogenesis
**has_part** "cell adhesion involved in vascular anastomosis"
**has_part** "endothelial tip cell filopodium assembly"

GO:new2 - cell adhesion involved in blood vessel fusion
Def: The attachment of a cell, either to another cell or to an underlying substrate such as the extracellular matrix, via cell adhesion molecules that contributes to the formation of a vascular network.
is_a GO:0007155 cell adhesion
synonym (type?) - cell adhesion involved in vascular anastomosis 
**additional relationship?** part_of "blood vessel fusion (GO:new1)"

GO:new3 - endothelial tip cell filopodium assembly
Def: The assembly of a filopodium, a thin, stiff protrusion extended by the endothelial tip cell of a vascular sprout.
is_a GO:0046847 filopodium assembly

**Comment by cerivs** [comment]
Hi Karen,
The suggestions sound good to me. Anastomosises are formed by anastomosis;  biologist do like their tautologies.   I would say vascular anastomosis  is a related synonym and  blood vessel anastomosis is an exact synonym.  Because I believe GO defines sprouting angiogenesis as a blood vessel function and vascular refers to both lymph and blood vessels.  
  A review focusing on these processes is http://dev.biologists.org/content/143/13/2249.long

**Comment by krchristie** [comment]
Hi Ceri,

I've added the first two terms (viewable, but not committed yet). You can view what I've done so far by clicking on the link in the commit comment above.

However, looking at the third term, I am reluctant to add a term that is specific to a cell type. It seems that this would be better dealt with by putting the cell type into the extension field. @ukemi Do you have thoughts on this?

**Comment by cerivs** [comment]
I don't have the ability to use that field  for annotations right now.


I just realized the change you made to the term names are problematic since the  cells haven't tublulated when the fusion occurs.   Biology is complicated.  How about term name changes to  GO:new2 "cell adhesion involved in sprouting angiogenisis " GO:new1 - angiogenic sprout fusion.  In the stanza below I changed vasculature (blood and lymph tubes) to blood vessel network.    I am also concerned that "cell adhesion involved in blood vessel fusion" would upon first glance reside up the tree from the sprouting  	angiogenesis terms, and only restricted by relationships.  


GO:new2 - cell adhesion involved in sprouting angiogenisis
Def: The attachment of a cell, either to another cell or to an underlying substrate such as the extracellular matrix, via cell adhesion molecules that contributes to the formation of a blood vessel network.
is_a GO:0007155 cell adhesion
synonym (type?) - cell adhesion involved in vascular anastomosis
additional relationship? part_of " angiogenic sprout fusion (GO:new1)"

**Comment by cerivs** [comment]
The blood vessel fusion terms may be appropriate to add further up the tree probably under  	blood vessel morphogenesis GO:0048514.

**Comment by krchristie** [comment]
Hi Ceri,

We're going to discuss the issue of the cell type specific term at tomorrow's ontology editors call (June 30th).

I'll look into the other issues a little more and see what I think, but I'm leaning towards your original term name 'cell adhesion involved in vascular anastomosis' since that seems to better distinguish the fusion side from the sprouting side.

-Karen

**Comment by cerivs** [comment]
Thanks Karen. Sorry these terms have been such a pain.

**Comment by cerivs** [comment]
Thanks Karen. Sorry these terms have been such a pain.

**Comment by krchristie** [comment]
We discussed this on June 30th and decided that in this case we will go ahead and make the cell type specific term. However, we would prefer to do this with extensions, so we will come up with a time frame to stop making this kind of term.

**Comment by krchristie** [comment]
Hi Ceri,

I used the term names you suggested using angiogenesis in the name since we had already made both related and exact synonyms using anastomosis, so it just seemed simplest to use your new term name suggestions. Let me know if you see any issues with the terms.

thanks,

-Karen
