### ISSUE TITLE
membrane tethering terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13696]
This is sort of a follow on from
https://github.com/geneontology/go-ontology/issues/12855
and
https://github.com/geneontology/go-ontology/issues/13657

![lam6](https://user-images.githubusercontent.com/7359272/27391516-0f9989ce-569c-11e7-8e12-7b2c0970ca34.jpg)

In GO we have

GO:1990456 mitochondrion-ER tethering
The attachment of the mitochondrion to specific sites on the endoplasmic reticulum, which may facilitate exchange of metabolites between the organelles.

for ER-mitochondrion membrane contact site

1. - [ ] suggest rename to 
GO:1990456 mitochondrion-ER membrane tethering

we don't appear to have 

2. - [ ] NTR vacuole-mitochondria membrane tethering

for vacuole-mitochondrion membrane contact site

3. - [ ] GO:0071562 nucleus-vacuole junction assembly
is also possibly describing a membrane tethering process.

4.  - [ ] Add NTR  "membrane tethering"  as a grouping term to group   (appear to be common mechanisms)

5.  - [ ] Include  GO:0061817	endoplasmic reticulum-plasma membrane tethering
as a child of NTR  "membrane tethering" 

6.  - [ ]  Standardise defs to mention that attachment is via membrane Suggest :The attachment of the mitochondrial *membrane*  to  specific sites in the  ER *membrane*
which may facilitate exchange of metabolites between the organelles. 

7. - [ ]  I notice that these have a localization parent, but I'm not sure that the tethers are always  involved in localization? other than the ER-PM one? The new is_a "membrane tethering" parent could resolve this

CC edwong57  who is looking at the cell paper. Edith does this look correct ?

**Comment by edwong57** [comment]
That looks correct to me. The only thing I noticed -- should GO:1990854 vacuole-ER tethering also be renamed to 'vauole-ER membrane tethering' and made a child of NTR 'membrane tethering'?

**Comment by ValWood** [comment]
Yep!

**Comment by ValWood** [comment]
Timely new paper:
Dev Cell. 2016 Nov 21;39(4):395-409. doi: 10.1016/j.devcel.2016.10.022.
A Tether Is a Tether Is a Tether: Tethering at Membrane Contact Sites.

Eisenberg-Bord M1, Shai N1, Schuldiner M2, Bohnert M3.

Membrane contact sites enable interorganelle communication by positioning organelles in close proximity using molecular "tethers." With a growing understanding of the importance of contact sites, the hunt for new contact sites and their tethers is in full swing. Determining just what is a tether has proven challenging. Here, we aim to delineate guidelines that define the prerequisites for categorizing a protein as a tether. Setting this gold standard now, while groups from different disciplines are beginning to explore membrane contact sites, will enable efficient cooperation in the growing field and help to realize a great collaborative opportunity to boost its development.


KEYWORDS:
E-Syt; ERMES; NVJ; OSBP; VAP; contact site; lipid transfer protein; membrane fusion; molecular tether; vCLAMP
PMID: 27875684

**Comment by pgaudet** [comment]
Hi Val, 

For ( 1), here are the changes.  
 id: GO:1990456
-name: mitochondrion-ER tethering
+name: mitochondrion-ER membrane tethering
 namespace: biological_process
-def: "The attachment of the mitochondrion to specific sites on the endoplasmic reticulum, which may facilitate exchange of metabolites between the organelles." [PMID:19556461]
+def: "The attachment of the mitochondrion to specific sites on the endoplasmic reticulum, which may facilitate exchange of metabolites between the organelles." [PMID:19556461, PMID:27875684]
 synonym: "mitochondrion-endoplasmic reticulum attachment" EXACT []
 synonym: "mitochondrion-endoplasmic reticulum tethering" EXACT []
 synonym: "mitochondrion-ER attachment" EXACT []
+synonym: "mitochondrion-ER tethering" EXACT []
 is_a: GO:0051659 ! maintenance of mitochondrion location

For (2) 
 
 [Term]
+id: GO:0140046
+name: vacuole-mitochondria membrane tethering
+namespace: biological_process
+def: "The attachment of a lytic vacuole membrane to specific sites in the mitochondrial membrane which may facilitate exchange of metabolites between the organelles." [PMID:25026035]
+is_a: GO:1990849 ! maintenance of vacuolar location
+created_by: pg
+creation_date: 2017-06-23T11:18:16Z

@ValWood 
please check that the def is as you wanted.

**Comment by pgaudet** [comment]
@ValWood WRT to point 7: 

> I notice that these have a localization parent, but I'm not sure that the tethers are always involved in localization? other than the ER-PM one? The new is_a "membrane tethering" parent could resolve this
In fact these are under 'maintenance of localization'. I am not sure this is OK either. Let me know which is the best parent in your opinion. 

'Localization' refers to both establishment and maintenance of localization, which seems appropriate. 

Let me know and I'll keep working on this. 

Pascale

**Comment by ValWood** [comment]
Hi Pascale.

I think both (all tethering)  defs should explicitly state membrane.

I.e.
The attachment of the mitochondrial *membrane* to specific sites in the ER *membrane*
which may facilitate exchange of metabolites between the organelles.

 This is more precise, and organelle-organelle attachment is implicit.

and yes, you are right,  probably localization is probably OK... certainly  the ER/plasma membrane attachment is part of ER localization. I wasn't sure about the others, but one would expect  this process to impact on localization to some degree....

**Comment by pgaudet** [comment]
Hi @ValWood @edwong57 

With respect to the new term 'membrane tethering', is this the same concept as 'membrane to membrane docking' (GO:0022614), definition: The initial attachment of a membrane to a target membrane, mediated by proteins protruding from the two membranes. Docking requires only that the membranes come close enough for the proteins to interact and adhere.

This term has a single child, 'nucleus-vacuole junction assembly', defined as 'The aggregation, arrangement and bonding together of a set of components to form a nucleus-vacuole junction, which are membrane contact sites formed between the vacuole membrane and the outer nuclear membrane. In S. cerevisiae these contacts are mediated through direct physical interaction between Vac8p and Nvj1p.' 

Both sound like tethering to me, what do you think ? 

If you agree I will add synonyms. 

Also, based on the descriptions I can find, for example in PMID:25343031, there is mention of 'initial docking', suggesting 'localization'.  I removed the maintenance of localization parents. Let me know if that doesn't seem OK. 

Thanks, Pascale

**Comment by ValWood** [comment]
It does sound the same. I think "tethering" is the more generally preferred term here. Can that be the primary name?
I would never search on "membrane to membrane docking", and membrane tethering is the term used in all recent reviews.


"membrane to membrane docking" About 15,000 results (mainly  GO derived, so overinflated)
"membrane tethering" About 29,200 results

For the localization I'm not sure....localization is very broad concept and  tethering presumably affects localization.... I'd tend towards just "localization" and avoid the specific "establishment" or "maintenance" which are tricky until we know more...

**Comment by edwong57** [comment]
I agree with Val. Although docking and tethering sound similar, to me, 'docking' is seems more specific, and 'tethering' is a more general term.

Using just 'localization' seems fine to me, too.

**Comment by pgaudet** [comment]
Great, thanks @edwong57 and @ValWood , I'll make the. changes according to these comments.

**Comment by pgaudet** [comment]
Hi @edwong57 
Just checking: you write 

> Although docking and tethering sound similar, to me, 'docking' is seems more specific, and 'tethering' is a more general term.

I was planning on merging the terms ('membrane tethering' and 'membrane to membrane docking'), renaming 'membrane tethering'; is this what you meant? Or do you think one should be a child of the other?

**Comment by ValWood** [comment]
Good point Edith about the docking term.

I think they are probably referring to the same process, and agree to the merge . Docking is quite a specific concept, but I don't think we necessarily know this process in enough detail to be precise about the 'docking part'. Also, we should consider what we mean by the phrase "docking".
We have discussed this before in the context of nucleocytoplasmic transport.

I think of the "docking" as a protein protein interaction (i.e MF term).

So I would suggest a merge, and make the  docking term "narrow".

Then, if we really can infer docking it would be

MF protein binding 
involved in
BP membrane tethering

(unless of course it is a more complicated multi-step process)

**Comment by pgaudet** [comment]
He're what I did (I also deleted an older comment since I started over): 

STANDARD DEFINITION 2 organelles: The attachment of a [x] to a [Y] via molecular tethers that physically bridge their respective membranes and attach them to each other. The tethering may facilitate exchange of metabolites between the organelles.

STANDARD DEFINITION 1 organelle + PM: The attachment of the [x] to the plasma membrane via molecular tethers. 




1. New term: organelle localization by membrane tethering
+id: GO:0140056
+name: organelle localization by membrane tethering
+namespace: biological_process
+def: "The process by which an organelle membrane interacts with another membrane via molecular tethers that physically bridge the two membranes and attach them to each other." [PMID:27875684]
+is_a: GO:0022406 ! membrane docking
+is_a: GO:0051640 ! organelle localization
+created_by: pg
+creation_date: 2017-06-27T09:58:51Z


2. GO:1990456  mitochondrion-ER tethering
2.1 renamed mitochondrion-ER tethering -> mitochondrion-endoplasmic reticulum membrane tethering [x]
2.2.Changed SubClass Of: 
- maintenance of mitochondrial location [x]
+ organelle localization by membrane tethering [x]
2.3 Fixed definition: 
The attachment of a mitochondrion and an endoplasmic reticulum via molecular tethers that physically bridge their respective membranes and attach them to each other. The tethering may facilitate exchange of metabolites between the organelles.


3. Added new term vacuole-mitochondria membrane tethering  [x]

+[Term]
+id: GO:0140057
+name: vacuole-mitochondria membrane tethering
+namespace: biological_process
+def: "The attachment of a mitochondrial membrane to a vacuolar membrane via molecular tethers that physically bridge their respective membranes and attach them to each other. The tethering may facilitate exchange of metabolites between the organelles." [PMID:27875684]
+is_a: GO:0140056 ! organelle localization by membrane tethering
+created_by: pg
+creation_date: 2017-06-27T10:31:12Z


4. GO:0061817 endoplasmic reticulum-plasma membrane tethering
4.1 Added SubClass Of: 
+ organelle localization by membrane tethering [x]
4.2 Changed definition
- The attachment of a the endoplasmic reticulum to the plasma membrane.
+ The attachment of an endoplasmic reticulum membrane to the plasma membrane via molecular tethers.

5. GO:0010381 peroxosime-chloroplast tethering
5.1 Renamed  peroxisome-chloroplast membrane tethering [x]
5.2 added synonym 'attachment of peroxisome to chloroplast'  [x]
5.3 Changed SubClass Of: 
- organelle localization
+ organelle localization by membrane tethering [x]
5.4 Changed definition
- The process in which a peroxisome is transported to, and/or maintained in, a location adjacent to the chloroplast.
+ The attachment of a peroxisome to a chloroplast via molecular tethers that physically bridge their respective membranes and attach them to each other. The tethering may facilitate exchange of metabolites between the organelles.
5.5 checked EXP annotations [x]


6. ciliary basal body docking
6.1 Renamed 'ciliary basal body-plasma membrane docking'
6.2  Changed Subclass Of
- 'membrane tethering'
+ 'organelle localization by membrane tethering'

7. GO:0071562 nucleus-vacuole junction assembly
7.1 Changed logical definition
- 
+ 'organelle localization by membrane tethering'
7.2 removed subclasses
- 'cellular component assembly'
- 'membrane to membrane docking'
7.3 checked EXP annotations [x]



8. GO:0016240 autophagosome docking
8.1 Renamed autophagosome membrane docking
8.2  Changed Subclass Of
- 'membrane tethering'
+ 'organelle localization by membrane tethering'

CURRENT HIERARCHY: 
'membrane docking'
- 'membrane to membrane docking'
- 'organelle localization by membrane tethering'
-- 'autophagosome membrane docking'
-- 'ciliary basal body-plasma membrane docking'
-- 'endoplasmic reticulum-plasma membrane tethering'
-- 'mitochondrion-endoplasmic reticulum membrane tethering'
-- 'nucleus-vacuole junction assembly'
-- 'peroxisome-chloroplast membrane tethering'
-- 'vacuole-mitochondria membrane tethering'
- 'protein to membrane docking'
- 'vesicle docking'


Thanks, Pascale
