### ISSUE TITLE
term merge? lipoatemdashprotein ligase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13720]
lipoatemdashprotein ligase activity

appears to be  a gene product specific version of 
of 	lipoate-protein ligase activity ?

If so can they be merged  (lipoatemdashprotein ligase activity=narrow synonym)

**Comment by krchristie** [comment]
Based on dissimilar EC numbers, it seems unlikely that merging these two terms is the appropriate solution. However, the name of GO:0102315 "lipoatemdashprotein ligase activity" looks like it contains some sort of copy/paste error.

GO:0016979 - lipoate-protein ligase activity
Def: Catalysis of the formation of carbon-nitrogen bonds between lipoate (5-(1,2-dithiolan-3-yl)pentanoate) and a protein.
Dbxref: EC:6.3.4
Term added: 2001-04-03
Last modified: 2016-10-03; removal of '.-' from end of Dbxref
**Note: Despite the fact that this is the older term, it is not clear to me why this should be called "lipoate-protein ligase activity" since the IUBMB page for this EC # says "EC 6.3.4 = Other Carbon—Nitrogen Ligases"**


GO:0102315 - lipoatemdashprotein ligase activity
Def: Catalysis of the reaction: lipoyl-AMP + [glycine cleavage system lipoyl-carrier protein]-L-lysine <=> AMP + 2 H+ + a [glycine-cleavage complex H protein] N6-lipoyl-L-lysine
Dbxref: EC:2.7.7.63
Term added: 2016-10-03
Annotations: 0
**Note: This appears to be the term that should actually be called "lipoate—protein ligase [activity]" based on IUBMB nomenclature: 
http://www.chem.qmul.ac.uk/iubmb/enzyme/EC2/7/7/63.html
=  Transferred entry: lipoate—protein ligase, now EC EC 6.3.1.20, lipoate—protein ligase.** 

Also note that you've opened another ticket on this same EC number (EC:2.7.7.63):
https://github.com/geneontology/go-ontology/issues/13721 (assigned to @ukemi) 

Perhaps also worth getting feedback from @hdrabkin

**Comment by ValWood** [comment]
You are right it does seem like a type. But then would the term names be identical with different meanings?

val

**Comment by ukemi** [comment]
@hdrabkin should be able to shed light on this. It does look like a typo on the name of GO:0102315 and that entry should be corrected/ updated and perhaps merged with GO:0016979. GO:0102315 is one of the enzymes added by @hdrabkin as part of the large addition of plant enzymes.

**Comment by ukemi** [comment]
PS. When you have resolved this, please close the other ticket.

**Comment by hdrabkin** [comment]
yep; term merge and fix the funny activity name

**Comment by hdrabkin** [comment]
I just emailed Pefen Zhang to help resolve, as she had a different metacyc id from the older term. Hope to hear later today.

**Comment by hdrabkin** [comment]
I'm betting a merge because

Note: for newer term, comment in Metacyc record RXN-13039

Sub-reaction of:  "6.3.1.20: [glycine cleavage system lipoyl-carrier protein]-L-lysine + ATP + (R)-lipoate → AMP + a [glycine-cleavage complex H protein] N6-lipoyl-L-lysine + diphosphate + H+" 

For older term, the metacyc xref  :RXN-8654 has 
Sub-reaction of:
6.3.1.20: [glycine cleavage system lipoyl-carrier protein]-L-lysine + ATP + (R)-lipoate → AMP + a [glycine-cleavage complex H protein] N6-lipoyl-L-lysine + diphosphate + H+ ,
6.3.1.20: a [lipoyl-carrier protein]-L-lysine + ATP + (R)-lipoate → a [lipoyl-carrier protein]-N6-lipoyl-L-lysine + AMP + diphosphate + H+

**Comment by hdrabkin** [comment]
Looking at the figures Metacyc supplies

RXN-13039
uses lipoyl-adenylate made from RXN-8654
       
RXN-8654 
Makes the lipoyl-adenylate   (Product of the rxn

The older term def appears to be describing the two steps combined?

**Comment by hdrabkin** [comment]
Peifen responds

GO:0102315 - lipoatemdashprotein ligase activity <<<<<
Def: Catalysis of the reaction: lipoyl-AMP + [glycine cleavage system lipoyl-carrier protein]-L-lysine <=> AMP + 2 H+ + a [glycine-cleavage complex H protein] N6-lipoyl-L-lysine
Dbxref: EC:2.7.7.63
Term added: 2016-10-03
Annotations: 0
MetaCyc:RXN-13039


This is a more specific case of lipoate-protein ligase. The protein in the reaction equation is the glycine cleavage complex. However, the def and the xref to metacyc only indicated one of the two steps of the ligase. The overall reaction in metacyc is RXN0-1141. I would suggest you update the term to:

Name: lipoate-protein ligase activity (lipoylation of glycine cleavage complex)
Def: Catalysis of the lipoylation of the glycine cleavage protein complex in two steps:
1) (R)-lipoate + ATP + H+ → lipoyl-AMP + diphosphate
2) lipoyl-AMP + [glycine cleavage system lipoyl-carrier protein]-L-lysine <=> AMP + 2 H+ + a [glycine-cleavage complex H protein] N6-lipoyl-L-lysine
DBxref: [EC 2.7.7.63 is replaced by EC 6.3.1.20. However EC 6.3.1.20 is not as specific. So you could remove the EC xref.]
MetaCyc: RXN0-1141

**Comment by hdrabkin** [comment]
fixed closed
