### ISSUE TITLE
	 octanoyltransferase  question http://www.uniprot.org/uniprot/A6NK58

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13722]
Lip2 is described variously as 

lipoyl(octanoyl) transferase activity Source: Reactome
octanoyltransferase activity Source: InterPro

but these terms do not have a paretn child relationship.

Lip2 appears to be 
lipoyl(octanoyl) transferase activity 
as per  Reactome.

Should 
lipoyl(octanoyl) transferase activity
be a descendant of
octanoyltransferase activity

or, should  InterpRo mapping be fixed from 
octanoyltransferase activity to lipoyl(octanoyl) transferase activity?

val

**Comment by deustp01** [comment]
Hmm. Reactome has only one annotation for human LIPT2 (UniProt A6NK58 - http://www.uniprot.org/uniprot/A6NK58): "LIPT2 transfers octanoyl group to GCSH" (http://www.reactome.org/PathwayBrowser/#/R-HSA-389661&SEL=R-HSA-6793590). That reaction appears to be an instance of lipoyl(octanoyl)transferase as described in Wikipedia (https://en.wikipedia.org/wiki/Lipoyl(octanoyl)_transferase) even though (annoying technical oddity) we've annotated the donor protein as a complex of protein and lipid rather than as a protein covalently modified with a lipid moiety. We applied GO:0033819 "lipoyl(octanoyl) transferase activity" to describe the catalysis occurring in that reaction.

We also have one annotation for human LIPT1 (UniProt Q9Y234 - http://www.uniprot.org/uniprot/Q9Y234): "LIPT1 transfers lipoyl group from lipoyl-GCSH to DHs" (http://www.reactome.org/PathwayBrowser/#/R-HSA-389661&SEL=R-HSA-6792572&PATH=R-HSA-1430728,R-HSA-71291). This reaction likewise fits the Wikipedia description above and here we've applied GO:0016746 "transferase activity, transferring acyl groups" to describe the catalysis.

That difference in molecular function looks correct. In the LIPT1 reaction, an 8-carbon acyl group (octanoyl) is transferred (CHEBI:78809 - http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:78809). In an intervening reaction, that octanoyl group is converted to a lipoyl group (ChEBI:83099 - http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:83099), which is then transferred in the reaction mediated by LIPT2.

Both ChEBI 78809 and 83099 are children of L-alpha-aminoacid residue, so it looks like they see both groups as sibling variants of amino acid residues. So that means the MF terms should be siblings as well? @ukemi?

**Comment by ValWood** [comment]
Yes I think the mapping to IPR020605 should probably be lipoyl(octanoyl) transferase activity.

The 2 terms are already siblings so is that correct?

**Comment by asangrador** [comment]
Hi Val,
The database is frozen for our next release, but the term will be changed to lipoyl(octanoyl) transferase when its over.

Amaia

**Comment by ukemi** [comment]
It they are siblings in ChEBI, then they should be siblings in GO.
