### ISSUE TITLE
ntr: process for D-erythroascorbic acid, biosynthesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13738]
I'm trying to annotate the pombe ortholog of this:
https://www.ncbi.nlm.nih.gov/pubmed/7957197
D-Arabinono-1,4-lactone oxidase, which catalyses the final step in the biosynthesis of D-erythroascorbic acid,

which should be a type of co-factor biosynthesis according to
the cerevisiae UniProt entry
	
Pathwayi: D-erythroascorbate biosynthesis
This protein is involved in step 2 of the subpathway that synthesizes dehydro-D-arabinono-1,4-lactone from D-arabinose.
Proteins known to be involved in the 2 steps of the subpathway in this organism are:
no protein annotated in this organism
D-arabinono-1,4-lactone oxidase (alo1)
This subpathway is part of the pathway D-erythroascorbate biosynthesis, which is itself part of Cofactor biosynthesis.

**Comment by ValWood** [comment]
- cofactor biosynthesis 
---D-erythroascorbate biosynthesis
---dehydro-D-arabinono-1,4-lactone biosynthetic process


def
The chemical reactions and pathways resulting in the formation of D-erythroascorbate.

**Comment by ukemi** [comment]
Let's try to make this term with the necessary function parts.

**Comment by ValWood** [comment]
I'm looking for more info now....

The problem is with 
dehydro-D-arabinono-1,4-lactone biosynthetic process

is that it doesn't slim to anywhere useful...

**Comment by ValWood** [comment]
so far only found this
https://www.ncbi.nlm.nih.gov/pubmed/11153268

and is it a vitamin, not a cofactor?
ascorbic acid is a vitamin....

**Comment by ukemi** [comment]
Any type of chemical classification will be via ChEBI.

**Comment by ukemi** [comment]
and is it a vitamin, not a cofactor?
ascorbic acid is a vitamin....

It is both depending on context, thus the problem with roles.

**Comment by ukemi** [comment]
The problem is with
dehydro-D-arabinono-1,4-lactone biosynthetic process

is that it doesn't slim to anywhere useful...

If that is the issue, then this new term won't fix it. The chemical is is quite high in the ChEBI ontology.

**Comment by deustp01** [comment]
From Marks' Basic Medical Biochemistry 4th ed, page 121 - "Coenzymes (cofactors) are complex nonprotein organic molecules that participate in catalysis by providing functional groups ... . In the human, they are usually (but not always) synthesized from vitamins."

So that's aggravating the problem here. In us auxotrophs, vitamins are cofactor precursors, like prodrugs that need a step or two of metabolism to become active and it seems equally legitimate to name that bit of metabolism "cofactor ~" or "vitamin ~". But does this distinction mean the same thing in prototrophic yeast that can make everything from a simple sugar, an inorganic nitrogen compound, and some minerals?

**Comment by ukemi** [comment]
Do you know if dehydro-D-arabinono-1,4-lactone is only an intermediate in the synthesis of D-erythroascorbate? PMID:8841374 has a nice diagram of the pathway in figure 4. If the only reason for having dehydro-D-arabinono-1,4-lactone is to synthesize D-erythroascorbate then the enzymes to make it from D-arabinose can be made part of D-erythroascorbate biosynthetic process. Otherwise we have to go the has-part route if this is the only pathway that can make D-erythroascorbate.

**Comment by ukemi** [comment]
Turns out it looks like worms can make ascorbate. PMID:25668719
As I said, this is the issue with roles, they are context dependent.

**Comment by ValWood** [comment]
> If that is the issue, then this new term won't fix it. The chemical is is quite high in the ChEBI ontology.

If properly placed it would slim to vitamin or cofactor metabolism. These are terms in yeast slims. At present it doesn't slim at all.

**Comment by ValWood** [comment]
Is it worth having some sort of fudge in GO so  that there is a single term
"vitamin and/or cofactor metabolism?
since it  is organism dependent?

**Comment by ukemi** [comment]
I don't think that is a good route.

**Comment by ValWood** [comment]
At present we use the path of least resistance and call things a vitamin if they are a vitamin in human.
Nobody has complained....

**Comment by ukemi** [comment]
We have GO:0070485 (dehydro-D-arabinono-1,4-lactone biosynthetic process). According to ChEBI, this is the name for D-erythroascorbic acid. I will add a synonym. 

As near as I can tell, this is not a vitamin in humans but it is used as a food preservative.

**Comment by ukemi** [comment]
It looks like if we are going to make this a cofactor biosynthesis (I don't think vitamin is a good idea), it would be best to do it via ChEBI and get the classification through their roles. I have put this as a discussion point for the editors.

**Comment by ValWood** [comment]
Thanks! that would work.

val

**Comment by ukemi** [comment]
Hi @ValWood 

Can you make this request at ChEBI? Then I think we can close this.

**Comment by ValWood** [comment]
https://github.com/ebi-chebi/ChEBI/issues/3356
