### ISSUE TITLE
Targeting versus localization and import

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13754]
Hello, 

This arises from 
https://github.com/geneontology/go-ontology/issues/13675

I wonder if there are any proteins that mediate an kind of cellular localization *targeting*. As far as I know proteins have a targeting/localization sequence that targets them to some organelle or the membrane. The definitions are as follows: 

 GO:0006605 protein targeting
The process of targeting specific proteins to particular regions of the cell, typically membrane-bounded subcellular organelles. Usually requires an organelle specific protein sequence motif.
---> that process of 'targeting' is hence performed by the signal contained in the protein being targeted

 GO:0034613 cellular protein localization
Any process in which a protein is transported to, and/or maintained in, a specific location at the level of a cell. Localization at the cellular level encompasses movement within the cell, from within the cell to the cell surface, or from one location to another at the surface of a cell.

I propose to merge the targeting/localization term pairs: 
- protein targeting to nucleus /protein localization to nucleus
- protein localization to membrane/protein localization to membrane

@ValWood @krchristie @marcfeuermann and anyone else: feedback is welcome !

Thanks, Pascale

**Comment by marcfeuermann** [comment]
Hi Pascale and all,
I know at least one case where proteins mediate localization of other proteins to an organelle: chaperone-mediated autophagy (CMA) where a cytosolic chaperone recognizes specifically a CMA-targeting motif (KFERQ) of proteins to target them to the lysosome. 
The difference between "protein targeting..."  and "protein localization to...", are really subtle and I do not think that curators make the difference (or even authors). So I would agree to merge these terms (and probably update the definition). 
Regards,
Marc

**Comment by pgaudet** [comment]
Hi @marcfeuermann 
In this case I would suggest annotating to 'protein localization', would that work ? 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
For me it seems okay :-)

**Comment by ValWood** [comment]
I'm not sure. It would be good to get an expert input on this.

Targeting is more specific than transport, so if  a merge is warranted maybe it should merge to transport  rather than localization?

The targeting terms  are still valid for targeting to organelles based on signal sequence (or binding to another protein with a signal sequence).
For example, proteins are targeted to the  ER by the SRP,  but then other processes imports the sequence into the membrane, or the lumen and this is the broader process of transport to the ER.

I don't know about targeting to the membrane. I haven't used it. Everything I have come across is either either  microtubule or vesicle mediated (trafficking) and not based on a signal (at least it would be targeted to the ER, and then trafficked to the plasma membrane". It is sorted into the vesicle based on the modification (prenylation) of the CAAX box.  This is called a targeting motif, but this is different from the original meaning of targeting.


There are a lot  of tickets related to this problem. I submitted one this morning!
https://github.com/geneontology/go-ontology/labels/targeting%20and%20transport

I think historically targeting was strictly binding with some sort of "diffusable" receptor   (like SRP, or a keryopherin) based on a signal in the sequence (or in the  sequence of a partner molecule), for delivery to an organelle  (membrane) from where it is imported.

Some certainly seem to be "localization"
GO:0099613 protein targeting to cell wall (only has 2 annotations)
I think you could definitely change that one to localization.

We need to keep the ones  where there is a  known system for recognition and delivery...

**Comment by pgaudet** [comment]
Hi @ValWood 

I agree that GO:0006614 SRP-dependent cotranslational protein targeting to membrane is different from the organelle targeting. But right now it's under  GO:0070972 protein localization to endoplasmic reticulum

<img width="763" alt="image" src="https://user-images.githubusercontent.com/4782928/27639055-7262d37a-5c15-11e7-8131-bab611e72f20.png">

Shouldn't it be under protein biosynthesis ? or at least targeting to the secretory pathway ? 

Pascale

**Comment by ValWood** [comment]
For nucleocytoplasmic transport this one is a localization, 
GO:0036228 protein targeting to nuclear inner membrane
because things are not "targeted" to the inner membrane. They are only targeted to the nuclear pore.

**Comment by pgaudet** [comment]
@ValWood 

I agree with 

> For nucleocytoplasmic transport this one is a localization,
GO:0036228 protein targeting to nuclear inner membrane
because things are not "targeted" to the inner membrane. They are only targeted to the nuclear pore.

**Comment by ValWood** [comment]
>shouldn't it be under protein biosynthesis ? or at least targeting to the secretory pathway ?

I don't think so. Protein biosynthesis just happens to occur at the same time but they are different processes.
Protein synthesis is halted.
Targeting to ER occurs.
Protein synthesis resumes.

I don't think it should be targeting to the secretory pathway either. The targeting is only about the initial delivery to an organelle based on the 'postcode/signal sequence' . What happens subsequently  in the secretory system depends on other things, modifications etc. 
The proteins which are delivered to the ER may  not even enter the secretory system, they can be resident ER proteins.

Tanya was looking at this at one point:
https://github.com/geneontology/go-ontology/issues/11908
might be a good place to pick up from for the ER stuff.

**Comment by ukemi** [comment]
Originally targeting was only meant to be the process that is used to make sure that things go to the right place, not actually getting them there. In any case, if the targeting terms are retained, I still think that the logical defs are incorrect.

**Comment by ValWood** [comment]
A better definition of targeting might be helpful.
The current def is quite vague

I think this is missing some critical details:
The process of targeting specific proteins to particular regions of the cell, typically membrane-bounded subcellular organelles. Usually requires an organelle specific protein sequence motif.

**Comment by ValWood** [comment]
yes @ukemi

**Comment by ValWood** [comment]
> Shouldn't it be under protein biosynthesis ? or at least targeting to the secretory pathway ?

For this it's because there are 2 targeting mechanisms (siblings), co-translational and post translational. The co-translational part is a bit of a 'red herring' it has nothing to do with translation (other than, I think the mechanism also independently negatively regulates translation)

**Comment by pgaudet** [comment]
What is left from this issue is the ER targeting. I'll create a separate issue for that.
