### ISSUE TITLE
smooth endoplasmic reticulum cysterna

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#13781]
I would like to see "smooth endoplasmic reticulum cysterna" added under "endoplasmic reticulum cisternal network" (GO:0071781). Definition could be “An expansion of the smooth endoplasmic reticulum lumen into a flattened, disc-shaped cavity.”  PMID:12112448

**Comment by krchristie** [comment]
Hi Stan,

I'm not really seeing how this new term is distinguished from the existing parent term you are suggesting, with the existing term here:

endoplasmic reticulum cisternal network - GO:0071781
Def: A subcompartment of the endoplasmic reticulum consisting of flattened, disc-shaped domains known as cisternae.  These are typically found close to the nucleus and are generally more prominent in secretory cells.

It seems to me that the existing term is also for the cisternae, and this term is for a single cysterna. But how would this proposed new term be used differently in annotation from the existing term?

**Comment by slaulederkind** [comment]
The distinction is in what type of ER the structure resides.  This term refers to smooth ER cisternae versus rough ER cisternae (PMID:6757417).

**Comment by krchristie** [comment]
Could you suggest a modified definition, and preferably also additional parentage, that fully describes what you need please.

**Comment by slaulederkind** [comment]
Additional parent could be "smooth endoplasmic reticulum part" (GO:0097425).  An alternative definition could be "A subcompartment of the smooth endoplasmic reticulum consisting of lumenal expansion into a flattened, disc-shaped cavity."  The parallel term of "rough endoplasmic reticulum cisterna" could also be added.

**Comment by krchristie** [comment]
Hey @ukemi 

I was adding the term Stan requested, 'smooth endoplasmic reticulum cisterna', and the parallel term he also suggested 'rough endoplasmic reticulum cisterna'. (currently stalled by the failure of the Travis checks due to the Service Unavailable error).

**Question 1**: In the course of figuring out an appropriate is_a parent, I noticed that we have a term for '**smooth endoplasmic reticulum part (GO:0097425)**',  but not a parallel term for  **rough endoplasmic reticulum part**. Thus, for the new term for 'rough endoplasmic reticulum cisterna', I have currently given it the is_a parent of 'endoplasmic reticulum part', as you can see here: https://github.com/geneontology/go-ontology/commit/d9abcdff52c16c46cc670fc094244d7084c865be.  **Do you think it's worth having a term for 'rough endoplasmic reticulum part'?** 

**Question 2**: I also noticed that the term 'smooth endoplasmic reticulum part (GO:0097425) has two terms under it: 'hypolemmal cisterna' and 'subrhabdomeral cisterna'. It seems like that these should be moved under the new term 'smooth endoplasmic reticulum cisterna' as each is a more specific type of smooth ER cisterna. **Any objections to moving these two terms under this new parent term?**
