### ISSUE TITLE
"microtubule polymerization based movement is_a intracellular transport?

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#13797]
This was brought up in #9189

@ValWood writes:
> we have used child terms like
"microtubule polymerization based movement"
As these terms are directed movement, I think they should probably be a type of transport?

I think you refer to 
	
GO:0098863 	nuclear migration by microtubule mediated pushing forces
GO:0034640 	establishment of mitochondrion localization by microtubule attachment
GO:0099112  microtubule polymerization based protein transport

What do you propose to do with those ? 

Thanks, Pascale

**Comment by ValWood** [comment]
GO:0098863 nuclear migration by microtubule mediated pushing forces
This can stay as localization. I don't think it has a transport parent anyway?
This is probably not classified as transport, because although the process positions the nucleus precisely, this is partly due to the confines of the cell. Really it is "movement", so its more than just localization, but it isn't transport.

GO:0034640 establishment of mitochondrion localization by microtubule attachment
-> localization

-> GO:0099112 microtubule polymerization based protein transport
This is transport. Microtubules can polymerize and transport proteins to the end of the cell/cell cortex. That said, I haven't fully been able to establish  the mechanisms, so we might need to review this later. This seems to be some transport that is purely polymerization based and no kinesins are involved.

**Comment by pgaudet** [comment]
Hi @ValWood   
GO:0099112 microtubule polymerization based protein transport
is a child of 
 GO:0006886 intracellular protein transport
Does this address your query ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think that's OK, yes sorted
