### ISSUE TITLE
edit and release OBO files don't open in OBO-Edit

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#13813]
This seems to be because they lack a date tag in the header.

**Comment by cmungall** [comment]
Hmm, I can round trip fine through oboedit obo2obo. Maybe this is a 
setting in OE? Do we care about OE support any more?

**Comment by ukemi** [comment]
It's nice to use for generating figures. I can't load the editors' version either, but I can load the one from the GO ontology page.

**Comment by dosumis** [comment]
Was working on a figure to illustrate an argument in a ticket.

**Comment by krchristie** [comment]
I agree that OBO-Edit is still very useful for certain uses, such as visualizing relationships and making figures. I also use it as a browser for annotation terms, partly for the visualization and also since I can load multiple ontologies all at the same time to search them all simultaneously.

Thus, if it's a simple fix, such as putting a date tag in the header of the ontology files, I agree with David OS that it would be worth doing. I recognize that complicated fixes aren't worth it, and understand that no one is going to fiddle with the actual OBO-Edit code.

**Comment by pgaudet** [comment]
@dosumis will investigate (editors meeting 2017-07-07)

**Comment by ukemi** [comment]
We will do this from the release versions on the web site.
