### ISSUE TITLE
is there a problem, did some terms disappear?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13873]
We are getting a message in curation sessions

isp3 | GO:0042244 | [UNKNOWN TERM]

even though I can still see this term in  QuickGO and AmiGO.

Is this a GO issue, or do we have a problem at our end?

**Comment by pgaudet** [comment]
I can see the term fine the the editors' version of the ontology. 

- Pascale

**Comment by ValWood** [comment]
Kim spotted that it now has:

In the OBO file for GO:0042244 it has:
subset: gosubset_prok

**Comment by ValWood** [comment]
I don't  see this taxon restirction in QuickGO, but the fungal terms 


GO:0030476 | ascospore wall assembly

are under here....

**Comment by pgaudet** [comment]
As far as I can tell the term has not changed since 2015.

**Comment by ValWood** [comment]
Actually, that isn't a taxon restiction is it. It's a subset, so its a slim. Although I don't see this. 
I'm not sure what is causing our problem. Will see if @mah11  has any ideas....

**Comment by mah11** [comment]
I don't think GO:0042244 has any taxon restrictions, and it shouldn't - it's (correctly) the superclass/parent for ascospore wall assembly (GO:0030476) and a few other terms, some of which can be used for prokaryotic spores.

gosubset_prok is indeed a subset, not a taxon restriction. IIRC, it predates the actual taxon restrictions, and means essentially the same thing as NOT having a never-in-prokaryotes or only-in-eukaryotes restriction - i.e., it's not inherently wrong to apply the term to a prokaryote. GO may not really need the gosubset_prok subset these days, although I'm not volunteering to explore that particular rabbit hole ;)

Anyway, I strongly suspect that our problem is on our end, because GO:0042244 looks fine everywhere except PomBase Canto.

**Comment by ValWood** [comment]
OK tks...
