### ISSUE TITLE
 GO:0070603 SWI/SNF superfamily-type complex - new relationships

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#13905]
please add:

is_a GO:1904949 ATPase complex
part_of GO:0000790 nuclear chromatin
capable_of GO:0003690 double-stranded DNA binding
capable_of GO:0005524 ATP binding
capable_of GO:0042624 ATPase activity, uncoupled
capable_of GO:0043044 ATP-dependent chromatin remodeling

PMID:10078207

capable_of_part_of GO:0006357 regulation of transcription from RNA polymerase II promoter
PMID:10778858

I would also add GO:NEW chromatin remodeling complex but that's been obsoleted.

Thanks,
Birgit

**Comment by krchristie** [comment]
Hi Birgit,

Tanya and I did quite a lot of work on the structure of this area a few years ago. Our discussion is in this ticket: https://github.com/geneontology/go-ontology/issues/10098 

> is_a GO:1904949 ATPase complex
> part_of GO:0000790 nuclear chromatin
> capable_of GO:0005524 ATP binding

I am fine with adding these three relationships.

> capable_of GO:0003690 double-stranded DNA binding

Is it true that ALL SWI/SNF superfamily-type complexes bind double strand DNA? Do you have a reference to this effect? Is it always DS DNA, or sometimes SS? Just want to check that we can say something this strong as it's been awhile since I worked in this area.

> capable_of GO:0042624 ATPase activity, uncoupled

Perhaps this is due to my lack of understanding of exactly what 'ATPase activity, uncoupled', but I don't recall having seen anything about these being uncoupled, versus coupled, so I'm wondering if you have a source indicating this is always an uncoupled reaction.

> capable_of GO:0043044 ATP-dependent chromatin remodeling
> PMID:10078207

I don't think we can say this because some of these complexes are involved in assembly, not remodeling (see ticket referred to above).
 
> capable_of_part_of GO:0006357 regulation of transcription from RNA polymerase II promoter
> PMID:10778858

No, I don't think it is OK to say that all SWI/SNF superfamily complexes are capable of regulation of txn from RNAP II promoters. See this review, specifically on mammalian ISWI complexes, not all of which are involved in regulation of transcription from RNAP II promoters, and which are themselves only a subset of complexes within the superfamily:
- PMID:21810179 - review on mammalian ISWI (Erdel & Rippe 2011); see Figure 1

> I would also add GO:NEW chromatin remodeling complex but that's been obsoleted.

Please read the ticket previously referred to the for reasons this term was obsoleted.

Thanks,

Karen

**Comment by bmeldal** [comment]
Hi Karen,

Thanks for flagging the issues, you are right. The questioned relationships are only relevant to the GO:0090544 BAF-type complex term, which is the set of complexes I'm currently working on (I'm predicting 31 tissue-, lineage- and composition-specific variants in the CP for human, plus mouse orthologues! Check our Twitter account for the picture of what this family of complexes has reduced me too: https://twitter.com/complexportal/status/885064981603115008 - curation-by-post-its... although, as of yesterday, the first entry is complete; now I just have to clone and edit all the variants...).

Please add:
capable_of GO:0016887 ATPase activity (rather than GO:0042624 ATPase activity, uncoupled)
to GO:0070603 SWI/SNF superfamily-type complex

And add
capable_of GO:0003690 double-stranded DNA binding
capable_of GO:0043044 ATP-dependent chromatin remodeling
capable_of_part_of GO:0006357 regulation of transcription from RNA polymerase II promoter
to GO:0090544 BAF-type complex

The ticket you referred to was a highly informative discussion!
Thanks,
Birgit

**Comment by krchristie** [comment]
Regarding new relationships for 'SWI/SNF superfamily-type complex' 
- is_a GO:1904949 ATPase complex
-: @ukemi - In acting on Birgit's request to make 'SWI/SNF superfamily-type complex' an is_a child of 'ATPase complex', I have removed the direct is_a relationship to 'protein complex' since it seems to me that having 'SWI/SNF superfamily-type complex' be an is_a child of 'ATPase complex' is the better parentage, and that having 'protein complex' doesn't really add anything useful. However, I notice that 'ATPase complex' is defined with the logical def `'macromolecular complex' and ('capable of' some 'ATPase activity')` so this moves the term 'SWI/SNF superfamily-type complex' up to being a type of 'macromolecular complex' rather than a type of 'protein complex'. I also notice that the term 'ATPase complex' is defined as `A protein complex which is capable of ATPase activity.`, which is inconsistent with its logical def as a 'macromolecular complex'. I know you were/are working on the area of 'protein complex' versus 'macromolecular complex' but I can't find the appropriate ticket, so I've just put this comment here. It seems to me that the remaining issue here is to resolve the discrepancy between the definition and the equivalence axiom for the term 'ATPase complex', but if you think I should add back the 'protein complex' parentage, let me know.

- capable_of GO:0016887 ATPase activity (rather than GO:0042624 ATPase activity, uncoupled)
-: This gets inherited by making 'SWI/SNF superfamily-type complex' a type of 'ATPase complex', so done.

- capable_of GO:0005524 ATP binding
-: Birgit, having just made the term 'SWI/SNF superfamily-type complex' is_a child of 'ATPase complex', it seems that the appropriate place to make the `capable_of GO:0005524 ATP binding` relationship would be at the higher level term 'ATPase complex', so that all child terms of 'ATPase complex' would inherit this. Any thoughts @ukemi, would it be appropriate to add `capable_of GO:0005524 ATP binding` to the term 'ATPase complex'?

- part_of GO:0000790 nuclear chromatin
-: Birgit, we can only make this relationship if these complexes are ALWAYS part_of nuclear chromatin, and it occurred to me that if these complexes exist in solution even when not located on chromatin, that it might not be OK to add this relationship. Thoughts?

**Comment by ukemi** [comment]
protein complex is going to be merged into macromolecular complex. We will do that as part of Barbara's training.

#12782
#13931

**Comment by ukemi** [comment]
> capable_of GO:0005524 ATP binding
-: Birgit, having just made the term 'SWI/SNF superfamily-type complex' is_a child of 'ATPase complex', it seems that the appropriate place to make the capable_of GO:0005524 ATP binding relationship would be at the higher level term 'ATPase complex', so that all child terms of 'ATPase complex' would inherit this. Any thoughts @ukemi, would it be appropriate to add capable_of GO:0005524 ATP binding to the term 'ATPase complex'?

Long ago we decided not to make these kind of links, but that was way before logical defs. We might need to revisit this.

**Comment by krchristie** [comment]
That's what I thought was going to happen with respect to 'protein complex', so I think what I've done to the is_a parentage of the term 'SWI/SNF superfamily-type complex' is fine.

**Comment by krchristie** [comment]
Birgit would also like me to 

> add
> capable_of GO:0003690 double-stranded DNA binding
> capable_of GO:0043044 ATP-dependent chromatin remodeling
> capable_of_part_of GO:0006357 regulation of transcription from RNA polymerase II promoter
> to GO:0090544 BAF-type complex

Should we discuss all of these requested capable of links on the call on Friday @ukemi?

**Comment by krchristie** [comment]
Hi Birgit,

We discussed this on 8/4/17 in the ontology developers call:
- We are NOT going to add the 'capable of' 'ATP binding' relationship to any complex term. There is significant history with this, specifically prior decisions to NOT put the relationship 'has_part' 'ATP binding' on MF terms for enzymes that have 'ATPase activity', so putting it on this complex is inconsistent with current practice. It may be that the MF refactoring will revisit that practice, but that is up to @thomaspd and @dosumis.  
- We are OK with adding the relationships you suggested specifically for the BAF-type complex. (However, I am on vacation for the rest of today and all next week, so I won't get to this for a couple weeks.)

**Comment by dosumis** [comment]
For complexes with ATPase activity "'capable of' ATPase activity" should be sufficient.  'ATP binding' should only be used where for cases of stable/prolonged binding (e.g. where ATP acts as a ligand).

**Comment by bmeldal** [comment]
Hi all,
Apologies for the late reply, I was on holiday!
All sounds good to me.

- poor @BarbaraCzub having to make that massive merge! I'll be on hand of any queries.
- part_of nuclear chromatin - yes, always, at it assembles on the chromatin :)
- ATP binding: ok, I have always added it as an annotation when it's been shown experimentally. Is that wrong? I can remove them all if needed.

Birgit

**Comment by BarbaraCzub** [comment]
Thank you @bmeldal !

**Comment by krchristie** [comment]
You can see the relationships I added in one of the links above.
