### ISSUE TITLE
NTR: positive/negative child terms of 'GO:0097494 regulation of vesicle size'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#13906]
Figure 1 in PMID:25898166 shows that knock down of PICALM Q13492 in cultured cells results in an increase in size of clathrin-coated vesicles.

I would like to annotate this as 'negative GO:0097494 regulation of vesicle size'. Could we please have the new positive and negative regulation terms for this?

> GO:0097494 regulation of vesicle size
>> NTR1 positive regulation of vesicle size
>> NTR2 negative regulation of vesicle size

Please use refs.: GOC:aruk and GOC:bc.

Thanks,
Barbara

**Comment by ValWood** [comment]
Is this real regulation though if its only a phenotype? It could be an indirect consequence of the problem caused by the mutant blocking some step in  transport., not a real control mechanism...

This is a bit analogous to annotating "regulation of cell size" just because cells are small or large. ....but most phenotypes are not caused by real regulation (over 95%of pombe genes with large cell phenotype are not part of the regulation of cell size....).

**Comment by BarbaraCzub** [comment]
Hi @ValWood . Based on PMID:25898166 my understanding is that this regulation is direct, because PICALM is required for membrane bending, and when it is lacking, the membrane does not get bent sufficiently, so the overall vesicle size is larger, when it finally closes.

**Comment by BarbaraCzub** [comment]
#13907

**Comment by ValWood** [comment]
I don't think that is regulating size though? The size change is a problem, it is an indirect consequence of the  previous problem caused by the inability to bend the membrane. It's not really regulation of size..... a change in size is  what you see (a phenotype), not a normal process.

**Comment by ValWood** [comment]
Your process  sounds in that case as though it should be "membrane bending" not regulation of vesicle size.

The purpose of PICALM is not to regulate vesicle size in a normal situation. When things go wrong  with the assembly the vesicle  size increases because of the problem, but it isn't regulation of size.

By analogy to cell size....over 700 pombe genes cause cell size *problems*, the vast majority of these are indirect. There are only a small handful that are regulatory. They somehow sense the size (and this is a prequisite for a size regulator)  and then switch the cell from growth to division accordingly ( lots of people annotate to "regulation of cell size when they shouldn't).

A vesicle size regulator would need to be able to sense the size of the vesicle, and *adjust* the size accordingly. This is quite different from a vesicle getting bigger because of assembly issues that cannot be corrected.

**Comment by BarbaraCzub** [comment]
I agree the phenotype shows what happens when things go wrong, which in this case results in inability to bend the membrane and form vesicles of normal size. But because we see this phenotype, this allows us to infer that when normal amount of PICALM is present, then PICALM is able to perform its function of membrane bending, which results in a specific (normal) vesicle size. Without the correct membrane bending, the system is out of balance and vesicle size changes, due to lack of control, or regulation. The process of 'GO:0097494 regulation of vesicle size' is defined as 'Any process that modulates the size of a vesicle,' which does not suggest that a regulator needs to be a sensor and be able to make adjustments. I'll discuss this with @RLovering and see how similar findings have been annotated in human.

**Comment by ValWood** [comment]
Yes unfortunately the definition of regulation is lacking in GO....I have been banging on about this for ages. @ukemi  @pgaudet 


For the cell size def its a bit circular because "modulates" is really a weaker word for "regulates". Regulation needs to include " a mechanism to control" or similar.

I'm probably not explaining very well, but this is a phenotype. I think you say this here:

"when normal amount of PICALM is present, then PICALM is able to perform its function of membrane bending, which results in a specific (normal) vesicle size"

what you are seeing is a problem caused by an abnormal process, not regulation (control)....

You can ignore the part about the sensor, it isn't necessary for the point I am making. But if you are regulating size, logically you must have a way to measure size. ....otherwise you can't be regulating it....

**Comment by BarbaraCzub** [comment]
Hi @vanaukenk 
I have just discussed this with @RLovering and we decided that I should make the annotation using the existing term 'GO:0097494 regulation of vesicle size' without indicating directionality of this regulation. Please disregard my request for the positive and negative regulation terms. 
Thanks,
Barbara

**Comment by ValWood** [comment]
I didn't know that the regulation term existed, and I still think this is a phenotype and isn't size regulation.
......It's just a consequence of  a problem caused my a mutant.

There are only 2 EXP annotation to this term, and the same probably applies to those (although they are GTPases, so they are actually good candidates for size regulators, so maybe there really are regulating vesicle size).
