### ISSUE TITLE
NTR: rDNA spacer replication fork barrier binding, bending 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#13913]
NTR: rDNA spacer replication fork barrier binding, bending 
is_a GO:0043110 rDNA spacer replication fork barrier binding 
is_a GO:0044374 sequence-specific DNA binding, bending
PMID:27035982

cheers

**Comment by vanaukenk** [comment]
@Antonialock - Could you supply a definition for the new term?  
Many thanks.

**Comment by ValWood** [comment]
Antonia isn't  working at PomBase until later in the wee, but I'd suggest
based on the parent and sibling terms:

The activity of binding selectively an rDNA  spacer in a sequence-specific manner and distorting the original structure of DNA, typically a straight helix, into a bend, or increasing the bend if the original structure was intrinsically bent due to its sequence.

v

**Comment by Antonialock** [comment]
Cheers Val. 

Is there a problem Kimberley? It seemed like the term def should be straight forward, based on the parents that I spedified?

**Comment by vanaukenk** [comment]
Thanks, @ValWood.  
No problems with the term, Antonia; we just always appreciate it if curators can provide a suggested definition when they request a term.  I'll add it in now.  Thx.

**Comment by vanaukenk** [comment]
Hi @ValWood and @Antonialock 

How about this for a slightly modified def:

The activity of binding selectively, and in a sequence-specific manner, a replication fork barrier found in rDNA spacers, and distorting the original structure of DNA, typically a straight helix, into a bend, or increasing the bend if the original structure was intrinsically bent due to its sequence.

**Comment by ValWood** [comment]
Looks good. I never know how much of the parent def to put in the descendant.

**Comment by ValWood** [comment]
Oh I missed out the rDNA spacer part totally!
