### ISSUE TITLE
MP cell surface receptor signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13912]
GO:0007166 - cell surface receptor signaling pathway

should this have parent
GO:0035556 intracellular signal transduction

**Comment by krchristie** [comment]
The prefix '**intra**' means within, while the term for 'cell surface receptor signaling pathway (GO:0007166)' clearly refers to '**extracellular**' so I do not think this makes sense.

**cell surface receptor signaling pathway (GO:0007166)**
**Def**: A series of molecular signals initiated by activation of a receptor on the surface of a cell. The pathway begins with binding of an **extracellular ligand to a cell surface receptor**, or for receptors that signal in the absence of a ligand, by ligand-withdrawal or the activity of a constitutively active receptor. The pathway ends with regulation of a downstream cellular process, e.g. transcription.

**intracellular signal transduction (GO:0035556)**
Def: The process in which a signal is passed on to downstream components **within the cell**, which become activated themselves to further propagate the signal and finally trigger a change in the function or state of the cell.

**Comment by ValWood** [comment]
I'm a bit confused by this.

Even though a signalling pathway originates at a cell surface receptor it is still "intracellular signal transduction"  isn't it? If it wasn't what would it be called instead. That would make the 
signalling steps initiated by the receptor  "intracellular signal transduction", even though it is activated by an extracellular ligand?

 or are there signalling pathways which activate a cell surface receptor, and then transmit a signal between cells?

Does anyone else  know?
@Antonialock  
@RLovering  your group does a lot of signalling annotation in multicellular?

**Comment by ValWood** [comment]
Oh I think I get it.

So intracellular signal transduction (GO:0035556) is a term that can be used to annotate any part of a signalling pathway excluding receptor. If so that seems a bit  of a strange "grouping" term.

I always though this term was to distinguish from extracellular signalling, like circulating growth factors etc....

**Comment by Antonialock** [comment]
I guess cell surface receptor signaling pathway applies to receptors that span the plasma membrane? Not all receptors do...lipids (cholesterol), hormones (estrogen, cortisol) and small uncharged stuff (CO2, O2, NO) can diffuse freely can cross the PM without the needs for an extracellular receptor sensing them, .

I think** all "cell surface receptor signaling pathway (GO:0007166)" would have an "intracellular signal transduction" component, but not all intracellular signalling have an extracellular component.

** I don't know if there are exceptions....for example consider apoptosis...I guess some apoptosis might be due to extracellular cues to die (e.g. in development) but some apoptosis must be due to intracellular cues (ageing cells....build up of buggered mitochondria, intracellular ROS...)
Also  there might be odd stuff going on in the immune system mechanisms. How does directed chemotaxis work?

**Comment by Antonialock** [comment]
extracellular signaling sounds a bit weird...how about signals that are sent by one cell and then internalized by other cells? Wouldn't it make more sense to annotate e.g. growth factors, peptide hormones etc to the BP "cell-cell signaling" + the MF "Extracellular signal" (sort of similar to the MF "protein tag"?)

**Comment by Antonialock** [comment]
(ah, there is actually no term for "extracellular signal transduction")

**Comment by ValWood** [comment]
So what I am trying to establish is, in yeast we would annotate everything signalling somewhere under "intracellular signal transduction" (because this is true, whether the signal originates inside or outside the cell). But we would not annotate any of the cell surface receptors to "intracellular signal transduction"  (according to the above).

However, because   when annotating individual pathways, we include the receptor (e.g. the git  GPCR  adenylate cyclase pathway includes the GPCR),  This means that effectively these intracellular pathways which originate from a GPCR cannot be placed under "intracellular signal transduction" because one component (the receptor) is on the cell surface. So somehow the logic seems flawed.....

**Comment by Antonialock** [comment]
I don't understand Val, 
e.g. a GPCR has both an extracellular component (senses ligand) and an intracellular component (binds Gprotein)

**Comment by ValWood** [comment]
Yes but it has an extracellular component. So you could not place the 

http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0007186#term=ancchart
(for instance)
under intracellular signalling.

So, I'm trying to establish the purpose of the term "intracellular signalling"

if GO:0007166 - cell surface receptor signaling pathway cannot be part of it.

I think part of the problem is due to attempts to represent all of the functions as processes.

There are lots of them, like:

GO:0010578 | regulation of adenylate cyclase activity involved in G-protein coupled receptor signaling pathway
(which is another way of describing the GPCR)


I think this is an issue to discuss at the signalling meeting.

**Comment by ukemi** [comment]
Hi @krchristie 
I had the same issue in #13903. Finally I made the suggested changes.

**Comment by ukemi** [comment]
Someone should claim one of these pathways for the signaling meeting.

**Comment by ValWood** [comment]
Well we already claimed 

adenylate cyclase-activating glucose-activated G-protein coupled receptor signaling pathway

which is  a
GO:0007166 - cell surface receptor signaling pathway
and a
GO:0035556 intracellular signal transduction

which is what causes us the problem....

**Comment by ValWood** [comment]
that's this pathway
https://github.com/pombase/curation/issues/1582

**Comment by ukemi** [comment]
I think I should undo the edits that I did on #13903. I think that the idea of intracellular signal transduction was introduced so that we could represent the conserved downstream modules of signaling pathways, whether those pathways were downstream (or part of) of cell surface receptor signaling pathways or not. That is why I was very reluctant to make the edits that you wanted in the other ticket. So for example in the pathway I have claimed (MAPK cascade), as currently represented (but not necessarily annotated) the cascade lies downstream of many different upstream bits of signaling that activate it.

**Comment by pgaudet** [comment]
Hi @ukemi 

Can you explain what other types of ' GO:0007165 signal transduction' would exist in addition to 'intracellular signal transduction' ? Not 'extracellular signal transduction', I suppose. Looks like the other main class is 'cell surface receptor signaling pathway' ? 

The siblings seem mostly intracellular signaling pathways, such as 'ER-nucleus signaling pathway'. Perhaps this branch needs some cleaning up ? 

Thanks, 

Pascale

**Comment by ValWood** [comment]
Closing as "out of date"
