### ISSUE TITLE
GO:0030154 cell differentiation add parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#13938]
GO:0030154
--
Name | cell differentiation

the way it's defined this looks as though it could have "multicellular organismal process".

This would hide this branch for yeast users.

**Comment by ukemi** [comment]
I am pretty sure that cialiates are thought to differentiate.

**Comment by ValWood** [comment]
I think at least  "never in yeast" would be OK with the current def of differentiation.
Yeast people sometimes say entry into G0 is a model for differentiation, but it isn't "real" differentiation, and it doesn't fit the GO def, so better to hide it.

**Comment by ValWood** [comment]
Hmm Actually maybe entry into G0 could fit this def, it's quite broad @mah11 @Antonialock

**Comment by ukemi** [comment]
It was meant to be broad to include models. I would think the mating type switches would also fit. I originally learned about them as models of differentiation.

**Comment by mah11** [comment]
I already didn't have a big problem with thinking of mating and sporulation stuff as yeast "differentiation". Then since Val flagged me here, I've had a quick look and found out about things that look even more like differentiation, such as the colony stratification described in PMID:22560924 (https://doi.org/10.1016/j.molcel.2012.04.001) and other stuff reviewed in PMID:27084693.

**Comment by ValWood** [comment]
OK lets close. We could add taxon restrictions to children alter. The problem I was encountering where the differentiation terms were swamping my  query, was actually a configuration issue at our end, so it doesn't actually cause us a problem right now....
