### ISSUE TITLE
Obsolete 'multi-organism signaling' ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14021]
Hello, 

Should 'multi-organism signaling' be in GO? ('The transfer of information between living organisms.'), but there are no subclasses, and there is a single manual annotation (under dispute). 

Thanks, Pascale

**Comment by ukemi** [comment]
If we don't ever think we will annotate genes to things like pheromone signaling, signaling in social insects or schooling fish, then I think it would be ok to obsolete. If we decide to obsolete it, maybe we can add it to @BarbaraCzub 's training ticket. We don't have an obsoletion yet.

**Comment by pgaudet** [comment]
Good point. @doughowe @srengel how do you capture that type of information? 
Perhaps this should be a grouping term but the children have not been put at the proper place ? 

Pascale

**Comment by srengel** [comment]
we capture pheromone signaling variously using these terms (is this what you are asking @pgaudet ?):

GOID | GO term | no. of annotations

GO:0000750 | pheromone-dependent signal transduction involved in conjugation with cellular fusion | 39
GO:0000321 | re-entry into mitotic cell cycle after pheromone arrest | 34
GO:0019236 | response to pheromone | 31
GO:0000754 | adaptation of signaling pathway by response to pheromone involved in conjugation with cellular fusion | 25
GO:0000749 | response to pheromone involved in conjugation with cellular fusion | 21
GO:0046020 | negative regulation of transcription from RNA polymerase II promoter by   pheromones | 15
GO:0071432 | peptide mating pheromone maturation involved in conjugation with cellular   fusion | 14
GO:0007329 | positive regulation of transcription from RNA polymerase II promoter by   pheromones | 14
GO:0000772 | mating pheromone activity | 10
GO:0004934 | mating-type alpha-factor pheromone receptor activity | 7
GO:0007323 | peptide pheromone maturation | 5
GO:1902353 | positive regulation of induction of conjugation with cellular fusion by   negative regulation of transcription from RNA polymerase II promoter by   pheromones | 5
GO:0005186 | pheromone activity | 4
GO:0000751 | mitotic cell cycle G1 arrest in response to pheromone | 3
GO:0010969 | regulation of pheromone-dependent signal transduction involved in   conjugation with cellular fusion | 3
GO:0004933 | mating-type a-factor pheromone receptor activity | 2
GO:0004932 | mating-type factor pheromone receptor activity | 2
GO:0090029 | negative regulation of pheromone-dependent signal transduction involved   in conjugation with cellular fusion | 2
GO:0000770 | peptide pheromone export | 2
GO:0005550 | pheromone binding | 1

**Comment by doughowe** [comment]
WRT pheromone signaling, we only have a very small collection of annotations to pheromone terms.  We've used:

pheromone receptor activity | 4 annotations - 2 from pubs, 2 from interpro2go
detection of pheromone | 1 annotation from interpro2go
response to pheromone | 1 annotation from interpro2go
pheromone binding | 1 annotation from a publication

What do you think @sabrinatoro ?  

I'm not aware of much multi organism signaling occurring in zebrafish, but  I would be shocked if it weren't occurring.   Heres an example of pheromone signaling from female to male zebrafish involved in courtship.  https://www.sciencedaily.com/releases/2016/05/160530115540.htm

And, surely other organisms have gene products having a normal function involving sending or receiving multi-organism pheromone signals?  I don't think we should get rid of those type of terms, but perhaps some ontology organization is needed?

**Comment by cmungall** [comment]
Parent "signaling":

"The entirety of a process in which information is transmitted within a 
biological system"

biological system is not defined, but for this to be a superclass of 
multi-organism signaling, a "biological system" must incorporate 
groupings of individuals.

Note the parent def is all-encompassing w.r.t. start/end: "*entirety* of 
a process"

In contrast, the child "multi-organism signaling" def says "The transfer 
of information between living organisms"

This places the emphasis on the transfer, i.e. the one doing the 
signaling? This is possibly why the large variety of classes involved in 
detecting and responding to signals from other organisms have not been 
placed as part-children. Even so, I would have expected many classes in 
GO that are concerned with the initiation of multi-organism signals.

I think we first need to be crystal clear about start and end, this will 
help with placing children.

**Comment by ValWood** [comment]
This would be very tricky.
Take the pheromone signalling pathway in fission yeast. This pathway can be activated by starvation conditions so it isn't exclusively "multi-organismal". If other signalling pathways in other species are similarly shared, the only gene product that could be annotated to "extracellular signalling" is the pheromone itself.
Otherwise we would need different versions of the same pathway.
@Antonialock 


Rather than describe "multi-organism signalling"
presumably there is always a "broader" multi-organism process  that is being regulated
http://www.ebi.ac.uk/QuickGO-Old/GTerm?id=GO:0000754#term=ancchart
so the multi organism part can come from this
(for example conjugation with cellular fusion/sexual reproduction in the above example).

For simplicity I would get rid of  'multi-organism signaling'. If the signal is pheromone-dependent, you know it originated externally. I'm not so sure  it is so important to have a concept of multi-organism signalling  wired into the ontology. 

Also, If you think about it, the production of the pheromone  and dispersal, is really quite separate from the  detection and response. It isn't a single pathway connecting 2 organisms.  the detection of the pheromone is a "chance" event to some degree.

**Comment by ukemi** [comment]
If it isn't activated by a pheromone, is it a pheromone signaling pathway?

**Comment by ValWood** [comment]
No  but the same pathway is used (It's one of the MAP kinase pathway and its the same pathway whether pheromone activated or not).

so take this gene product for eg
http://preview.pombase.org/gene/SPAC1D4.13

currently to capture things downstream of the pheromone we would do

MAPK cascade  involved in positive regulation of conjugation with cellular fusion
( we haven't asked for a named pathway as they are named differently in different species)



This is an instance of the same pathway regulating the same thing in a different way. 
So, exactly the same pathway does

MAPK cascade involved in positive regulation of conjugation with cellular fusion ( in response to pheromone)
MAPK cascade involved in positive regulation of conjugation with cellular fusion  (in response to nitrogen limitation)
(its just a different input activating the pathway)

I suspect you don't want to precompose every possible input for every signalling pathway....

Sometimes this  *Specific* pathway  (Byr2 MAPKKK)  is regulated by pheromone and sometimes not.
I don't know how you could  capture this  with a multicellular organismal parent.

Incidentally the same pathway also regulates different things too (sporulation)

**Comment by pgaudet** [comment]
Hi @srengel @doughowe 
Thank you for your input. Would you expect the terms you use to be under 'multi-organism signaling' ? Right now pheromone signaling is under cell communication (Any process that mediates interactions between a cell and its surroundings. Encompasses interactions such as signaling or attachment between one cell and another cell, between a cell and an extracellular matrix, or between a cell and any other aspect of its environment), which seems appropriate. 

If there are no objections I'll go ahead and send the obsoletion notice. 

Thanks, Pascale

**Comment by srengel** [comment]
no objections here.

**Comment by doughowe** [comment]
?cell communication includes by definition interactions between a cell and "...any other aspect of its environment".  That seems to cover it.


--
Doug Howe, Ph.D.
ZFIN Data Curation Manager
Zebrafish Model Organism Database
University of Oregon
541-346-2355

________________________________

**Comment by pgaudet** [comment]
Obsoletion notice sent
Dear all, 

The proposal has been made to obsolete: GO:0035636 'multi-organism signaling'. The reason for obsoletion is that the term is hardly used and has no subclasses. The term ‘cell communication’ (Any process that mediates interactions between a cell and its surroundings. Encompasses interactions such as signaling or attachment between one cell and another cell, between a cell and an extracellular matrix, or between a cell and any other aspect of its environment), or a child, is more appropriate for annotation. 


There is 1 experimental annotation to this term and 0 InterPro2GO mappings. Any comments can be added to the issue: [link to GitHub ticket]. We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on August 17, 2017. 


*** Unless objections are received by August 17, 2017, we will assume that you agree to this change. ***

Best regards, 

Pascale

**Comment by RLovering** [comment]
annotation is from UniProt

**Comment by pgarmiri** [comment]
Hi,
 I just noticed this ticket due to the obsoletion notice that was sent earlier. 

I did this annotation in an attempt to keep the information about the ZP3 involvement in the signaling pathway that occurs in the sperm which, I think, is biologically relevant. Karen had suggested to delete the original annotation to 'signal transduction' and the topic for the appropriate annotation for this is still under discussion with Kimberly and David H that it could be continued here, I suppose.

ZP3 is an membrane protein of the oocyte that binds to a sperm receptor and regulates processes in sperm like the acrosome reaction. Below are some figures that display the signaling events.

http://www.cellsignallingbiology.org/csb/008/csb008fig8_ZP3_induced_Ca_signals.htm

http://www.nature.com/ncb/journal/v3/n2/fig_tab/ncb0201_e59_F3.html


Is the current ontology for 'signal transduction' representative or a new term under the 'multi-organism' branch would be more appropriate?  Would the suggested term  ‘cell communication’ cover this aspect better?
However, both the 'signal transduction' and ‘cell communication’ are only under the 'single organism' branch. Would interactions/signalling events happening between the female oocyte and male sperm be under those? 

Also, ZP3 is already annotated to "GO:0060046 regulation of acrosome reaction" which according to the figures above it's one of the late events in the cascade. Would annotation to regulation of the other indeterminate events be okay, even though they are happening in sperm? 

Thanks,
Penelope

**Comment by pgaudet** [comment]
Hi pgarmiri, 

ZP3 is a ligand, so you should annotate it to 'GO:0048018 receptor agonist activity', which is indirectly part of cell communication. The other aspects including acrosome reaction should be captured in a CAM model. Does that work for you ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
I have added the ticket to Barbara's training set of tickets. Note that the obsoletion notice has been sent so the term can be obsoleted at any time. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @hattrill 
I noticed I didn't copy you here; do you want to comment from the fly perspective ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Thanks, Pascale. I asked the flies and they say that they I don't think that I will miss multi-organism signaling. So no objection here.

**Comment by pgarmiri** [comment]
Hi Pascale,
Thanks for the suggestion. Yes, I think,  'GO:0048018 receptor agonist activity' will work in this case.

 I guess a CAM model could be useful to capture the other aspects but I am mainly using Protein2GO. How would that be done there? Would annotation to 'regulation of..' acrosome reaction etc with an extension Occurs_in sperm cover that?  
Thanks,
Penelope

**Comment by pgaudet** [comment]
Hi @pgarmiri 

In the CAM model you can indeed capture the entire biological pathway of the ligand - regulation of..' acrosome reaction in sperm', etc. This is outside the scope of this issue but let me know if you need help. 

best regards, 
Pascale
