### ISSUE TITLE
small molecules, vitamins and co factors

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14047]
I notice that vitamin metabolic process is_a "small molecule metabolic process" but "cofactor metabolic process" is not.
Should they both have this parentage?

**Comment by ukemi** [comment]
@deustp01 ?

**Comment by pgaudet** [comment]
@ValWood 
I think this is a question for ChEBI - we normally use their hierarchy (of course we can do differently but that creates a lot of maintenance on our end and it's error-prone). 

Can you submit this to the ChEBI tracker ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Before I submit it would be useful to hear @deustp01  thoughts,   I recall some recent discussion, but I don't think it makes sense to treat vitamin and co-factor differently in this respect.

Will  open a ticket  if it makes sense to....

**Comment by deustp01** [comment]
Textbook view
A cofactor is a  small molecule or ions required by by a protein for its function. Enzymes are the commonest examples, but the heme moiety in myoglobin and hemoglobin also is taken to be a cofactor. All living organisms, so far as I know, use cofactors and in many cases the identical ones for the identical molecular function. For cofactors, Monod and Ashburner - Botstein are right: an elephant is the same as E. coli.
Now, where do cofactors come from? For organisms that can live on diets of inorganic entities plus perhaps a simple carbon source (yeast, E. coli, some plants), they are synthesized de novo. Humans and many other multicellular organisms can't synthesize these molecules de novo but instead must take them or their immediate precursors up from the environment. These required nutritional supplements are called vitamins. Metabolically, they are cofactors and cofactor precursors. Different species have different vitamin requirements, e.g., only humans and guinea pigs among mammals that have been studied cannot synthesize vitamin C. so here the Monod - Botstein - Ashburner worldview doesn't work as well.
I guess that while cofactor could fit OK into a slim, getting vitamin in would be tricky.

ChEBI view
ChEBI starts out fine:
ChEBI 23357 cofactor. "n organic molecule or ion (usually a metal ion) that is required by an enzyme for its activity. It may be attached either loosely (coenzyme) or tightly (prosthetic group)."
ChEBI 33229 vitamin. An organic substance that is distributed in foodstuffs, is distinct from the main organic components of food (protein, carbohydrate and fat) and is needed for the normal nutrition of the organism in question.
Maybe "normal nutrition" could be replaced by a phrase to indicate that some, maybe all, vitamins are cofactor precursors, but those two definitions are consistent with textbook chemistry and physiology. The problem comes in the ChEBI ontology. The two terms are only placed in the roles ontology: cofactor is_a biochemical role is_a biological role; vitamin is_a food component is_a physiological role is_a biological role. The biochemical role of vitamins as a group is missing and the close relationships between individual vitamins and cofactors are probably annotated in a way that is inaccessible to the GO reasoner, and anyway is different for each chemically distinct vitamin. I guess that if one digs through the ChEBI annotations for each individual vitamin and cofactor, it's clear that each vitamin metabolic process is_a small molecule metabolic process. (I haven't dug systematically, hence the "guess".)

**Comment by pgaudet** [comment]
Hi @deustp01 
Thank you for the explanation. What I am reading is that a vitamin is not a vitamin in every species, depending on whether the species synthesizes the cofactor or gets it in its diet; is this correct ? 

If this is the case 'vitamin biosynthetic process' should be deleted (or merged with co-factor biosynthetic process), since the organisms that absorb them as vitamins do not synthesize them, and for the organisms that synthesize them, these compounds are co-factors and not vitamins. 

Pascale

**Comment by pgaudet** [comment]
@ValWood 
to come back to your original question: 

> I notice that vitamin metabolic process is_a "small molecule metabolic process" but "cofactor metabolic process" is not.
Should they both have this parentage?

Co-factors also include ions (like ion), I think this is why the parents are different between "small molecule metabolic process" and "cofactor metabolic process". 

Pascale

**Comment by ValWood** [comment]
Peter's comment implies it is some reason related to the  CHEBI classification.
I don't think co-factors including ions would make it small moleculte metabolism, and vitamin not.

I'll open a CHEBI ticket to see if additional classification of vitamin and a "biochemical_role" will fix the parenetage via reasoning. Will keep this tickets as pending and have a re-think if that doesn't work.

v

**Comment by ValWood** [comment]
Actually realingment in chebi isn't going to help here

vitamin (CHEBI:33229) is a biochemical role (CHEBI:52206) 
vitamin (CHEBI:33229) is a micronutrient (CHEBI:27027)
cofactor is_a  a biochemical role (CHEBI:52206) 

presumably GO aligns CHEBI micronutrient with "small molecule metabolism" in some way.

Cofactor can't be classed as a micronutrient in chebi.
So GO will need to  align CHEBI cofactor directly with "small molecule metabolism" to get this parentage?

**Comment by pgaudet** [comment]
CheBI doesn't have the concept of 'small molecule', as far as I can tell. 

In any case: 
- according to wikipedia, small molecules are limited to organic molecules, so the exclude ions (https://en.wikipedia.org/wiki/Small_molecule)
- some cofactors are ions

What are you trying to group ? 

Maybe @ukemi knows more about the high level organization of this area of the ontology? 

Thanks, Pascale

**Comment by ValWood** [comment]
trying to make sure that  vitamin and cofactor have the same "small molecule metabolism" parentage. I think in GO this must come from "micronutrient" for vitamin. Clearly a cofactor isn't a 'micronutrient'  which is why it is absent and cannot be inferred from Chebi alignment.

**Comment by pgaudet** [comment]
See my previous comment - cofactor cannot be under small molecules since cofactors also include ions.

**Comment by ukemi** [comment]
Historically, these have all been problematic. How small is a small molecule?

**Comment by pgaudet** [comment]
right - it's tempting to remove it ;)

**Comment by ValWood** [comment]
Its a really, really, useful term for  metabolic modelling community. In fact I just co-authored a paper on network analysis which totally relies on this term to retrieve GO small molecule metabolic process annotations to build a network of metabolism.  

Historially we have always found it really tricky to  create a term  what  people who work on metabolism  refer to as "general metabolism" but this is now the term they use. It is the closest thing we have.

It is difficult be we need something for this grouping,  using this ID, if people can come up with a better differentia then "small molecule" I would happily change it, but we need the concept.


Isn't an ion small?

**Comment by ValWood** [comment]
Ah right and just an ion can be a co-factor, hmm....

Here is some of the history around this
https://sourceforge.net/p/geneontology/ontology-requests/10200/
(and tickets linked from here).

We know it is unsatisfactory...

**Comment by deustp01** [comment]
"ion" versus "molecule" - sometimes: "An ion is an atom, or a molecule, in which the total number of electrons is not equal to the total number of protons, giving the atom or molecule a net positive or negative electrical charge." (Wikipedia) but, Wikipedia again, "A cofactor is a non-protein chemical compound or metallic ion that is required for a protein's biological activity to happen." 

So in the Wikipedia worldview, the ions relevant to this discussion are indeed metal atoms that have lost electrons to gain a positive charge. Phooey.

At the very beginning of things, Michael Ashburner made the distinction between "encoded" molecules and "unencoded" ones, and, with "entity" swapped for molecule in his comment that is exactly the distinction we need here. As good as the idea is, no one has ever been able to capture it in the ontology structures of either GO or ChEBI.

**Comment by mah11** [comment]
The SF ticket Val linked to is #10400 here in GitHub. It actually goes at least as far back as #5410 ...

**Comment by ValWood** [comment]
This ticket describes a different reason for the term  (or some incarnation of it) to exist.

**Comment by ValWood** [comment]
Ah so @deustp01  we could use the "other" wikipedia definition if  the co factors always "molecular ions"?

Early on when  trying to resolve this I asked the metabolic modellers  and metabolomics people in exasperation "but what do you call it"  they  would look at me strangely and say "metabolism"?

**Comment by pgaudet** [comment]
Hi @ValWood 
Chris fixed something with respect to inferences relative to roles; can you check whether this improves the vitamins and co factors assertions ?

**Comment by ValWood** [comment]
Well, it didn't appear to fix the problem I reported here, which was that "not all cofactor metabolism" is "small molecule metabolism.

I was not completely sure that it should be, but it seemed to be the case. I still get this:

![intersects](https://user-images.githubusercontent.com/7359272/33493517-360eafde-d6b8-11e7-926f-bdca1ef2e715.jpg)

and some do appear to fit "small molecule metabolism"

**Comment by ValWood** [comment]
e.g.


GO:0070485 - dehydro-D-arabinono-1,4-lactone biosynthetic process
GO:0006783 - heme biosynthetic process

**Comment by krchristie** [comment]
@ValWood @ukemi - The key issue in this ticket seems to be about the small molecule issue.  

With respect to ChEBI, the cofactor role grouping terms have already been obsoleted, and I think that it is likely that the vitamin grouping terms will go the same way. 

Since small molecule isn't a ChEBI role, I think this ticket is potentially out of scope for the ChEBI roles project.

**Comment by ValWood** [comment]
This ticket becomes obsolete now since cofactor metabolic  process no longer exists. My issue was the inconsistency between the vitamin and cofactor branches.
