### ISSUE TITLE
New term request

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#14115]
New cellular component term request

TOC-TIC supercomplex I
The protein transport machinery of the chloroplast membrane that interacts with the precursor proteins and contains components of both the outer membrane and inner membrane complexes containing at least Toc75, Toc159, Toc34 and Tic110.

PMID:28745032

This would be part of chloroplast membrane
GO:0031969

**Comment by ukemi** [comment]
Hi @lreiser ,

Here is the new term:

 [Term]
+id: GO:0061927
+name: TOC-TIC supercomplex I
+namespace: cellular_component
+def: "The protein transport macromolecular complex of the chloroplast membrane that interacts with the precursor proteins and contains components of both the outer membrane and inner membrane complexes containing at least Toc75, Toc159, Toc34 and Tic110." [PMID:28745032]
+is_a: GO:0032991 ! macromolecular complex
+relationship: capable_of_part_of GO:0072598 ! protein localization to chloroplast
+relationship: part_of GO:0009507 ! chloroplast
+created_by: dph
+creation_date: 2017-08-28T13:18:20Z

Note that I made it part of chloroplast rather than chloroplast membrane because it spans both the inner and outer membranes, so it is not part of a type of chloroplast membrane. I also made it capable of part of localization to chloroplast. Please let me know if these changes are not ok.

-David

**Comment by lreiser** [comment]
Perfect, thank you.
