### ISSUE TITLE
Odd inferences from transport to organization

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#14117]
![image](https://user-images.githubusercontent.com/112839/29719917-fea16ee2-89af-11e7-87f4-80dee391808d.png)

Breaking down the problem:

X part_of Y in the ontology means that X is part of Y at all times.    But we fudge a bit in the case of complexes, by saying we allow part relations to be used to the location where that complex is active.  Hence 'NTR complex part_of some plasma membrane'

Given this, inferring that a transport process occurs in a particular location from the location of the thing being transported should be safe (hence the chain 'transports or maintains localization of' o 'part of' -> 'occurs in'

But in this case, the ontology records a process by which a complex gets to the location where it is active => clashing inference that its transport must occur where it is active.  I think this is a good a proper use of GO:  Processes which regulate the levels of NTR at the postsynaptic membrane are critical to regulation of synaptic transmission and so are a major aim for annotation in the synapse project.

Proposed solution:  

Remove this property chain: 'transports or maintains localization of' o 'part of' -> 'occurs in'

Additional reason to remove this: Inference across it may not be safe at the individual level - where we can record location as a snapshot.  We may want to reconsider/review any other similar property chains.

**Comment by dosumis** [comment]
Related ticket: geneontology/synapse#154'

**Comment by cmungall** [comment]
I agree with your analysis

here's a simple explanation for the unusual axiom:

![image](https://user-images.githubusercontent.com/50745/29721687-0b11be62-8973-11e7-9173-36c59e0260a1.png)

I agree that removing the property chain is probably the most pragmatic thing for now, but...

as you point out, the part-of in CC is the real culprit here. Not pragmatic to remove now but this is going to bite us. If we really want to say the receptor complex SubClassOf part-of some membrane, and it doesn't get assembled there, then it forces us to say that the thing being transported is something else, an "immature complex". While this sounds awkward it's not something the average user would see.

I also note the combo of hidden GCI and isa-overloading:

![image](https://user-images.githubusercontent.com/50745/29721914-a82bad34-8973-11e7-8fcb-076cc55c53b0.png)


I think this should be part-of (but this doesn't solve the issue)

**Comment by cmungall** [comment]
btw, another reason to be careful allowing CC annotations of the form M part-of C. If someone makes a statement [a X-receptor] part-of [a cytoplasm] arachne will flag as inconsistency, due to spatial disjoints

**Comment by pgaudet** [comment]
@ukemi 
was this ever discussed at an editors call? I dont remember - nor the resolution. Ideally this should be assigned to someone :) 

Thanks, Pascale

**Comment by balhoff** [comment]
`'transports or maintains localization of' o 'part of' -> 'occurs in'` is not in GO nor in RO at the present time. David's ticket at RO is still open but probably should be closed: https://github.com/oborel/obo-relations/issues/200

**Comment by pgaudet** [comment]
Thanks!
