### ISSUE TITLE
NTR: protein targeting to the basolateral/apical plasma membrane

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#14168]
Dear editors,
this paper PubMed=11802162, describes the function of AP4M1 in localization of several proteins to the basolateral membrane of epithelial cells. Moreover, it suggests it is signal-mediated. Could you please create the terms indicating the signal-mediated targeting of proteins to the apical and basolateral membrane, a child of GO:0006605 protein targeting.
Thanks,
Lionel

**Comment by krchristie** [comment]
Hi Lionel,

I've taken a quick look at the paper you cite, and also the Mellman review cited therein that I quote below. I am inclined to agree with you that localization of proteins to the apical or basolateral membranes of epithelial cells is signal-mediated.

I see that we already have this term:

**protein localization to basolateral plasma membrane (GO:1903361)**
Def: A process in which a protein is transported to, or maintained in, a location within a basolateral plasma membrane.
is_a: 'protein localization'

This term does not specify that the localization is signal mediated, but after reading the Mellman review, I was wondering if this kind of localization occurs any other way. Do you know of any such localization or targeting that is NOT mediated by a signal?

thanks,

-Karen

**Mellman I. Endocytosis and molecular sorting. Annu Rev Cell Dev Biol. 1996;12:575-625. Review. PubMed PMID: 8970738**:
> TARGETING SIGNALS CONTROL RECEPTOR RECYCLING IN POLARIZED EPITHELIAL CELLS
> 
> In polarized epithelial cells, receptors internalized at one plasma membrane domain typically recycle back to that domain. This has been clearly demonstrated in Madin-Darby canine kidney (MDCK) cells in which Tfn receptor and LDL receptor, both proteins restricted to the basolateral surface, are continuously internalized and recycled basolaterally with a high degree of fidelity (Mellman et al 1993b). Transport across the cell to the apical domain (transcytosis) is possible as well, although this normally occurs only in the case of specialized transcytotic receptors such as the polymeric Ig receptor (Mostov 1994). It is obvious from the study of epithelial cells that receptor recycling cannot be a default process, but must be governed by one or more targeting signals.

**Comment by lbreuza** [comment]
Hi Karen,
I do not know of such example but this does not preclude the existence of such mechanisms. In that case we clearly know it is signal-mediated but what should we do when there is no evidence of such targeting signals. That is why I thought to introduce such granularity would help. Moreover, the definition includes retention in the basolateral membrane of some proteins and it may include some non signal-mediated processes.
Hope it helps,
Lionel
Th

**Comment by ValWood** [comment]
@pgaudet  has recently been overhauling so that 'targeting' terms were merged into localization because of the difficulties associated with 'targeting'

I think the plan was that targeting would be represented as
MF signal-sequence_binding involved_in   process,
which here might be:

MF signal-sequence_binding involved_in 
GO:0099638    endosome to plasma membrane protein transport has_substrate (gene x)

if this is describing transport (active movement)  rather than merely 'localization' (which includes transport).

**Comment by krchristie** [comment]
Based on the way the definition of the existing term is written, it looks to me like it is a "standard" definition that was written a long time ago, not necessarily based on much understanding of the biology.

> protein localization to basolateral plasma membrane (GO:1903361)
> Def: A process in which a protein is transported to, or maintained in, a location within a basolateral plasma membrane.

From the reviews I took a quick look at yesterday, it looks to me like the protein targeting to the basolateral/apical plasma membrane that occurs in epithelial cells is a specialized process that occurs in these polarized cells. Whichever parentage is appropriate, we definitely do need to have a parallel term for the apical targeting, which we don't have at all, and I think the definitions could be improved. So far, I'm not sure that we need a separate term for signal mediated since it seems that all of it is signal mediated. Perhaps I'll check with some of the review authors.

@ValWood - Thanks for tagging @pgaudet on this, I was planning to get her input. From what I've read so far, this is definitely an active targeting, both for the original localization to the appropriate membrane and also during endocytic recycling.

**Comment by pgaudet** [comment]
Hello, 

@lbreuza Look like the paper you are annotating is from 2002; is there more recent data on this? That might help us create the terms correctly. AP4M1 is involved in clathrin-coated vesicles transport; don't you think this is the likely mechanism here ? Is there any data linking clathrin-coated vesicle transport to protein localization to basolateral plasma membrane? 

We also have 'regulation' of these terms (for eg 'regulation of protein localization to basolateral plasma membrane'). I don't think this is optimal but it could be a solution for now. Otherwise it might be relevant to create 'signaling involved in protein localization ...' but without the molecular evidence that seems unjustified. 

@krchristie 
indeed the plan was something along what you write: 
MF signal-sequence_binding involved_in
GO:0099638 endosome to plasma membrane protein transport has_substrate (gene x)

Thanks, Pascale

**Comment by lbreuza** [comment]
@pgaudet AP4M1  is involved in vesicle transport (but not clathrin-dependent); also, the paper clearly shows that AP4M1 is specifically involved in targeting of proteins to the basolateral plasma membrane, ie by recognition of a targeting motif on transported proteins.

**Comment by pgaudet** [comment]
@krchristie 
after discussion with Lionel I suggest you create the term 'protein targeting to the basolateral/apical plasma membrane' for now (until we have time to fix the branch). 

Thanks, Pascale

**Comment by krchristie** [comment]
@pgaudet 
Having scanned through a number of the papers used for annotation, as well as a few reviews, I think that there is only one process going on for sorting/recycling to apical or basolateral plasma membrane. Many of the annotated genes are vertebrate proteins with polarized epithelium, but even looking at the Aspergillus and Arabidopsis proteins annotated to 'apical protein localization', this seems like a conserved process for targeting to specific regions of membrane.

Considering that you are proposing to merge some of the existing basolateral terms in https://github.com/geneontology/go-ontology/issues/14233, I really don't see why we would want to create any more terms to represent processes we already represent. To me it seems best to use existing terms and fix them to more clearly represent what we are already using them for. These two seem to be the main terms:

GO:0045176 - apical protein localization (164 annotations)
GO:1903361 protein localization to basolateral plasma membrane (165 annotations)

**Comment by krchristie** [comment]
I don't think there's anything left to be done here, so I'm going to close this.
