### ISSUE TITLE
OTR: move smoothened binding under G-protein coupled receptor binding

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#14182]
Move GO:0005119 smoothened binding from under  ‘GO:0005109 frizzled binding’  to under ‘GO:0001664 G-protein coupled receptor binding’

smoothened (hedgehog pathway), although related to frizzled receptors, acts in a completely different manner to the frizzled receptors (wnt pathway). As its mechanism and biology are so divergent, it is not a frizzled receptor in any meaningful sense. GO:0005119 	smoothened binding should be moved from under GO:0005109 frizzled binding and made a child of GO:0001664 G-protein coupled receptor binding to reflect this.

**Comment by vanaukenk** [comment]
The placement of GO:0005119 'smoothened binding' under GO:0005109 'frizzled binding' is coming from the logical def of 'frizzled binding':

binding
 and ('has input' some 'frizzled-like G-protein coupled receptor')

Since PRO classifies 'smoothened' as a 'frizzled-like G-protein coupled receptor', 'smoothened binding' is being classified in GO as an is_a child of 'frizzled binding'.

PRO does not seem to have an entry for 'frizzled', but instead has the various frizzled and smoothened receptors as siblings with the common parent 'frizzled-like G-protein coupled receptor'.

Since we seem to be moving away from adding terms like 'frizzled 2 binding' or 'frizzled 9 binding', etc., I'm not sure it makes sense to have a grouping term for 'frizzled-like G-protein coupled receptor binding' in GO.

For now, I will remove the logical def for 'frizzled binding' and make sure the asserted parentage for 'smoothened binding' is still good.

**Comment by vanaukenk** [comment]
Note: will also follow up with PRO to see what they think about adding an entry for the 'frizzled' family.
