### ISSUE TITLE
NTR: c-di-GMP-mediated signaling and related others

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#14180]
Hello:

I recently submitted two NTRs for "response to c-di-GMP" and "cellular response to c-di-GMP". On looking into this further, I now think we need additional GO terms to more fully describe this process. c-di-mediated signaling is a significant signaling pathway in bacteria and has been recently identified in Dictyostelium, and I'm now starting to encounter papers fleshing out some of the actors involved. So I would like to request 4 new GO terms:

c-di-GMP-mediated signaling
regulation of c-di-GMP-mediated signaling
positive regulation of c-di-GMP-mediated signaling
negative regulation of c-di-GMP-mediated signaling

I am including here only the definition and information for the first term, c-di-GMP-mediated signaling, as I assume it is straightforward for you to create the remaining 3 as children of this term as found in numerous other signal transduction terms. But of course let me know if you would like me to provide further information. 

Thanks,
Bob Dodson

Name: c-di-GMP-mediated signaling
Ontology: biological_process
Synonyms: cyclic diguanylate-mediated signaling; 3',5'-cyclic di-GMP-mediated signaling; cyclic di-(3':5')-guanosine monophosphate-mediated signaling; cyclic di-GMP-mediated signaling

Alternate IDs: None
Child of:  GO:0019935: cyclic-nucleotide-mediated signaling
Definition: Any intracellular signal transduction in which the signal is passed on within the cell via cyclic di-GMP (c-di-GMP). Includes production of c-di-GMP, and downstream effectors that further transmit the signal within the cell. 

References:
PMID: 23471616	Cyclic di-GMP: the first 25 years of a universal bacterial second messenger.

PMID: 22864416	The prokaryote messenger c-di-GMP triggers stalk cell differentiation in Dictyostelium.

PMID:28057864   Adenylate cyclase A acting on PKA mediates induction of stalk formation by cyclic diguanylate at the Dictyostelium organizer.

**Comment by ukemi** [comment]
Hi Bob,

I think we do need this term. Looking over the paper, I'm not sure that it fits as a child of cyclic-nucleotide signaling because that process is necessarily intracellular. From the paper, it seems that the c-di-GMP signaling is a a true signaling cascade where the c-di-GMP is the signal that acts on some type of receptor. The c-di-GMP signaling then activates cAMP-mediated signaling (on already existing adenylate cyclase) and in turn activates PKA signaling.  

> I was planning to curate the genes: dgcA, ACA, and PKA, shown in Fig. 7 with "c-di-GMP-mediated signaling" as I interpret these as being the genes actively involved in signaling. Fig. 7 also includes "stalk genes" and these are the genes mentioned in the previous paragraph (staC, etc.) which I interpret as being a downstream effect of the signaling process.

I'm not sure about this. dgcA is the enzyme that generates the c-di-GMP, so it is upstream of the signaling. Then depending on where you slice the signaling pathway (where it ends), ACA and PKA could either be a part of the signaling or downstream of it. I'm pinging @pgaudet here because she is working on the GPCR signaling pathways as part of the signaling project and I'm not sure how the cAMP stuff fits in with her current thoughts. But whatever we decide to do, it should be parallel. Do you have any idea whether the c-di-GMP activates a GPCR?

**Comment by rjdodson** [comment]
Hi David:

Thanks for your response. Agreed that dgcA should not be included, that is, should not be annotated with c-di-GMP-mediated signaling, as it generates the signaling molecule. 
And I was also wrong about the nature of this signaling and the correct parent for this term. dgcA is found in the cytosol, so I was assuming that this was an intracellular signaling cascade, but on checking again it is clearly noted that c-di-GMP is a secreted signal. As for a receptor, there are only two relevant papers (that I'm aware of at least): this one, PMID:28057864 and PMID: 22864416, and neither has results or even speculation on a possible receptor, and no mention of a GPCR. 

Hope we can get Pascale's input as well, both for the dicty biology and her recent work on signaling. 

Thanks,
Bob

**Comment by ukemi** [comment]
OK. My model is getting really complicated, so we might want to go over it together at some point. I'm bringing in the specification, determination, commitment and development aspects of cell differentiation. It might be fun to discuss this with @vanaukenk when she gets back. She and I have had looooong discussions about the nature of the cell fate commitment terms. This might be a nice example. The terms are based on classical experiments in developmental biology and we have discussed how those translate into molecular mechanisms.

**Comment by rjdodson** [comment]
OK, I see the model. And yes, it is getting complicated...this would have taken me days or longer to flesh out! It's getting late here (Madrid), so I'm not prepared to wade into this right now, but I'll have a look in the next few days and see if I can offer any constructive feedback. 

Petra is coming here after the London GO meeting and it might be good to discuss this along with her as well, as her knowledge of dicty Biology is more extensive than mine. Problem is I'll be out a bit in late October, so our overlap time won't be so extensive. How about if we pencil in early October, right after the meeting and try to schedule a time to discuss? Or even during the meeting. I won't be there, but could Skype with you, Kimberly and Petra then if that works.

**Comment by ukemi** [comment]
Hi Bob,

Yes. I'm sorry that the model is so complicated. Maybe we should make a simpler one, but I went down the path of thinking about how all of this relates to the big picture of developmental biology in GO. I tend to do that a lot in GO-CAM models. Maybe we should make a more basic model to try to get out the core annotations that you would have made conventionally. Do you want to try to do that?
I'd love to discuss this because it is something that I have been thinking about for years.

In the meantime, I will create the signaling term and the regulation terms. Since there has been no receptor identified, perhaps I should go a level up for the parent? Then we can move it as the pathway is further elucidated.

-D

**Comment by rjdodson** [comment]
Hi David:

I took a look at your model today and have just a couple of comments, one specific and one general. 

Specifically, the adenylate cyclase activity in this paper is enabled by dicty gene acaA, which is UniProt:Q03100. I tried to add it, but it didn't show up as a selection choice. Not sure why not.  

More generally, we typically don't use the three GO process terms: GO:0045165 cell fate commitment, GO:0001708 cell fate specification or GO:0001709 cell fate determination in curating dicty genes at dictyBase, although your use of them here certainly seems intuitively correct. There are a just a handful of dicty genes curated with these GO terms, but w/o having checked into them I suspect they are wrong-or at least contrary to our practice. 
 
We typically use the GO process terms: GO:0031149 sorocarp stalk cell differentiation and GO:0031150 sorocarp stalk development. And when I select the graph or inferred tree views of these two terms, neither of the 3 above GO terms show up in the displayed results. Note that the GO term GO:0030154 cell differentiation does, and is a parent of these two.

So if these 3 terms are not related to our sorocarp stalk terms, then maybe they should not be used in the model? Or maybe that doesn't matter at all, and you did after all specifically want to bring them in here. Anyway, this is all just a suggestion for what it's worth, at this point I'm not sure what's best. I guess input from Kimberly, Pascale and Petra would help. 

Thanks,
Bob

**Comment by rjdodson** [comment]
Hi David: 

Sorry, we crossed messages here. I was looking at the model and had this page open, and responded w/o refreshing the page, so I didn't see your latest response. 

In that case, then yes, I'll try to make a more basic model based on your template, and using some of the suggestions that I just made. I'll start from scratch so as not to mess up your model. Won't be quick-I'm new at this and it takes me longer to think it through and just deal with the mechanics of LEGO. But I'll let you know when I've "finished" or am at least ready for you to review it. 
Thanks,
Bob

**Comment by ukemi** [comment]
OK. I made this term and the regulation ones to help you in making the GO-CAM model.

+id: GO:0061939
+name: c-di-GMP-signaling
+namespace: biological_process
+def: "Any process that mediates the transfer of information from one cell to another using c-d-GMP as the signal." [PMID:22864416, PMID:28057864]
+synonym: "3',5'-cyclic di-GMP signaling" EXACT []
+synonym: "cyclic di-(3':5')-guanosine monophosphate signaling" EXACT []
+synonym: "cyclic di-GMP signaling" EXACT []
+synonym: "cyclic diguanylate signaling" EXACT []
+is_a: GO:0007267 ! cell-cell signaling
+created_by: dph
+creation_date: 2017-09-14T18:59:04Z

I am very tempted to make is a child of 'cell cell signaling involved in cell fate commitment', but if we add the commitment term in the model it should be generated automatically. Let me know if what I have done isn't isn't ok with you

**Comment by ukemi** [comment]
Also see #14175

**Comment by rjdodson** [comment]
Hi David:

I've worked a bit on a simpler c-di-GMP signaling model over the last few days and am probably ready for feedback from you. It's here:

http://noctua.berkeleybop.org/editor/graph/gomodel:59bee34700000000?barista_token=4ma3kza1t1if3mpows5g#

I have a number of questions, but a couple of quick things to note here:

-this is one of my first models, so I'm pretty new at this; this model is probably how I'd do it, but that doesn't really count for much-especially given the potential breadth and complexity of this model
-many of my questions are about the proper relationships (including correct directionality) between annotons, so any suggestions there, or more documentation in the Curation Documentation would be welcome.
-I've now dropped my previous objection to the use of cell fate commitment, cell fate determination, etc. GO terms, and now agree that these are what ties this in with broader developmental biology. That said, I'm not so familiar with these terms and which are best to use here.  

Anyway, let's start there and we can discuss further on this ticket, or on a call if you'd prefer. 

Thanks,
Bob

**Comment by ukemi** [comment]
Hi Bob,

Two quick questions/comments. 

1. Why didn't you use the new signaling term?
2. The cell differentiation part_of stalk cell differentiation is puzzling to me. 

I think we should try to have a look at this together on a call. Hopefully with @vanaukenk 
It might not happen until after the meeting.

**Comment by rjdodson** [comment]
Hi David:

1) I didn't use the new term because I didn't see it as available through the tool. And I still don't. I tried searching both for text and the GO term id, but not seeing it. Am I missing something? 

2) I guess this reveals my ignorance. How would you suggest to relate these two? Or would you simply not use these two BPs in this way at all? As noted previously, when curating dicty in protein2GO I typically just use GO:0030587 sorocarp development and it's children so my experience is limited with these broader terms. 

I'm happy to discuss with you and Kimberly whenever convenient. As noted, if after the meeting Petra will be here so might be better to do then anyway as her knowledge of dicty biology is much more extensive than mine. 

Thanks,
Bob

**Comment by pfey03** [comment]
@ukemi  did you get our email to discuss the larger issues here?
We suggest early next week either 
Monday 10/16 before and/or ending at 11 AM EDT or
Tuesday 10/17 before and /or ending at 10 AM EDT
Thanks!

**Comment by rjdodson** [comment]
Hi David:

Just requesting a simple revision to the definition here. 
+def: "Any process that mediates the transfer of information from one cell to another using c-d-GMP as the signal." 

Should be: "c-di-GMP" instead of "c-d-GMP"

Thanks,
Bob

**Comment by pfey03** [comment]
@ukemi 
I discussed the extracellular presence and action of c-di-GMP with the person who is working on this and published.

She said the strongest evidence that c-di-GMP acts extracellularly currently comes from the fact that the dgca- phenotype is non cell autonomous and can be rescued by mixing with wild-type and by adding c-di-GMP. They are still hunting for receptor and we also discussed that Dicty has a ton of ABC reporters to export from the cell.

That said, I sent her the term (GO:0061939) you added and she approved of the term and definition.

Bob and I updated our CAM model quite a bit and used some different relationships consulting the RO. Maybe you can look at that at your convenience
http://noctua.berkeleybop.org/editor/graph/gomodel:59bee34700000000?barista_token=atdltkzmcjdzpgn1byyr

Also, since there seems no real evidence for c-di-GMP signaling in higher organism, and the expert who is also an evolutionary biologist said (and published) that from phylogenetic evidence it seems obvious that DgcA entered Dictyostelia by horizontal gene transfer from bacteria (but then no other bacterial components are present in Dictyostelia).

So for now at least, maybe we cannot tie this into a larger, general pathway. Let's wait for more publications down the road and revisit. 

Unless we made big mistakes in our model, we don't need to discuss this further at this point.

Thanks!
cc
@rjdodson

**Comment by ukemi** [comment]
Thanks all. Sorry it took so long to get back to you. I was swamped all last week. I fixed the typo and am closing this issue. We might want to discuss this model on a call at some point.
