### ISSUE TITLE
NTR: procentriole replication complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#14187]
name: procentriole replication complex
def: A protein complex that acts as a chaperone or scaffold for centriolal proteins during the maturation of the procentriole. Some of its members may become integrated into the growing centriole. Examples are the CPAP(CENPJ)-STIL complex, CEP192-PLK4 complex or CEP152-PLK4 complex in vertebrates.
xref: 
PMID:24997597, 21059844, 21059844
GOC:bhm
IntAct:EBI-15188467
IntAct:EBI-15316456
IntAct:EBI-15189349

relationships:
is_a GO:0043234 protein complex
part_of GO:0005813 centrosome
capable_of GO:0007099 centriole replication

Have I missed anything? Then argue away ;-)

Thanks, Birgit

**Comment by ukemi** [comment]
Typo in the def, so don't cut and paste. Caperone should be chaperone.

**Comment by bmeldal** [comment]
Thanks, @ukemi . Typo fixed :)

**Comment by krchristie** [comment]
Hi Birgit,

I have some comments and questions.

1. In the definition, I plan to change 'centriola**L**' to 'centriola**R**' as searching for the former in PubMed produces this comment: 

> Showing results for centriolar. Your search for centriolal retrieved no results.


2. I'm not sure that we can say that this complex is 'part_of' centrosome

It seems to go against the definition of '**centrosome**' to say that the '**procentriole replication complex**', a structure that is involved in duplicating a second centriole in order to regenerate a centrosome is part_of the '**centrosome**', a structure defined in GO as having two centrioles and which is not yet built when this complex is associated with a mother centriole. 

The fact that you say that "**Some** of its members may become integrated into the growing centriole" also seems to argue that it is not part_of a structure that has not yet been built. Similarly, I do not consider the 90S preribosome, a structure involved in assembly of the 18S ribosomal subunit to be 'part_of' the 18S ribosomal subunit.


3. PMID:24997597, 21059844, 21059844 - You have listed the same PMID twice in this list. Did you mean to list a third instead?


4. @ukemi - Just wanted to check with you on Birgit's requested use of 'capable of', i.e. that it is OK to say that a complex is capable of a process. Most of the usages I see for "capable_of" link a complex to a MF.

**Comment by ukemi** [comment]
Good catch! I think the relation should be capable_of_part_of.

**Comment by bmeldal** [comment]
Hi Karen,

> 1. In the definition, I plan to change 'centriolaL' to 'centriolaR' 

Absolutely, I got that wrong (did I make it up or was it a typo, who knows!).

> 2. I'm not sure that we can say that this complex is 'part_of' centrosome

This one bothered me, too. It's not part of the centriole but of the pericentriolar material (PCM) where it brings components of the procentriole (term not in GO). According to GO, pericentriolar material is part_of the centrosome. Some definitions define the centrosome as the organelle containing the 2 centrioles and other include the pericentriolar material.

Curiously, centriole has no relationship to centrosome in GO.

As these complexes act on the pericentrioles in the PCM I thought centrosome was the more conservative annotation.

> 3. PMID:24997597, 21059844, 21059844 - You have listed the same PMID twice in this list. Did you mean to list a third instead?

Please add: 22020124, 18207742, 17576815

> 4. Just wanted to check with you on Birgit's requested use of 'capable of', i.e. that it is OK to say that a complex is capable of a process. Most of the usages I see for "capable_of" link a complex to a MF.

I remember someone, @dosumis ?, saying if the complex is directly involved in the BP it could be capable_of rather than capable_of_part_of. Happy with either.

Thanks!

**Comment by krchristie** [comment]
> This one bothered me, too. It's not part of the centriole but of the pericentriolar material (PCM) where it brings components of the procentriole (term not in GO). According to GO, pericentriolar material is part_of the centrosome. Some definitions define the centrosome as the organelle containing the 2 centrioles and other include the pericentriolar material.

> As these complexes act on the pericentrioles in the PCM I thought centrosome was the more conservative annotation.

Either way you define the centrosome, with or without PCM (and it's with in the GO definition), it seems to me that the stage of building a second centriole is an intermediate stage between a centriole and a centrosome that isn't part_of either.
 
> Curiously, centriole has no relationship to centrosome in GO.

I'm don't think that centriole should have a relationship to centrosome because when it's a single centriole it isn't part of a centrosome. Seems to me that it would be OK to add the converse relationship, i.e. that centrosome has_part centriole.


> I remember someone, @dosumis ?, saying if the complex is directly involved in the BP it could be capable_of rather than capable_of_part_of. Happy with either.

I don't mind either way, just wanted to make sure I understand what is acceptable. @ukemi should we discuss this at the ontology dev meeting?

**Comment by ukemi** [comment]
There isn't that much on the agenda, so go ahead and add it on the projects page.

**Comment by bmeldal** [comment]
> Either way you define the centrosome, with or without PCM (and it's with in the GO definition), it seems to me that the stage of building a second centriole is an intermediate stage between a centriole and a centrosome that isn't part_of either.

Hmmm, I interpreted it that the centrosome persists during the cell cycle but its components change. Also, it's defined as being composed of the 2 centrioles, with or without PCM. Why can't centrioles have part_of centrosome then?

If centrosome was defined as persisting during the cell cycle then there won't be an issue with these complexes acting during the intermediate step between the mature, interphase centrosome and the mitotic centrosome.

Will await ontologist's call result :)
(I know, my complexes are a pain in the backsite!)

**Comment by krchristie** [comment]
I was under the impression that it's only called a centrosome when it's the paired structure. The centriole also becomes the basal body of the cilium and it's not called a centrosome then.

**Comment by bmeldal** [comment]
It's a fluid process. I just remember I used to work next to a centrosome function group! I'll ping the postdoc (then PhD student who's still working on it)!

**Comment by krchristie** [comment]
@ukemi - I've added the editors-discussion tag, but I don't know know to add it to the projects page.

**Comment by bmeldal** [comment]
I've had a conversation with my former colleague who works on centrosomal proteins. This is what she says:

"Centrioles template the growth of new centrioles, that is the daughter grows out of the mother. So procentriole formation does take part "in" the centrosome. In fact, without centrioles, there is not centrosome. I would argue that you should annotate them as part of the centrosome. The same way as a lagging strand of DNA is still part of DNA for example. Does this help? Happy to answer more questions. Also (couldn't help noticing) there is a typo - PKL4 should be PLK4. [typo fixed]

Procentrioles could have their own GO term. 

And the procentriole is also part of the centrosome. It grows off the base of the mother centriole and is surrounded by the pericentriolar material so it couldn't be more part of the centrosome if it tried!"

Action points:

- [ ] Make centriole part_of centrosome - Basal body has it's own term (GO:0036064) so doesn't infringe on it.

- [ ] Question: what does this mean in the def of centriole: "At division, each pair of centrioles generates another pair and the twin pairs form the pole of the mitotic spindle." - wouldn't that make 4 poles? Shouldn't it be "At division, **the pair of centrioles** generates another pair and the twin pairs form the pole of the mitotic spindle."

- [ ] Create new term for procentriole
name: procentriole
def: A cellular organelle, representing the growing daughter centrioles during cell division. Before DNA replication, cells contain two centrioles. The older of the two centrioles is termed the mother centriole, the other the daughter. During the cell division cycle, a procentriole grows at the proximal end of both mother and daughter centrioles. In the newly divided cells, the original mother and daughter centrioles become mother centrioles while the procentrioles becomes the new daughter centrioles.
Relationships: 
as centriole
part_of centrosome

- [ ] procentriole replication complex part_of centrosome as some might be part_of procentriole but not all. Those annotation will go on the specific complex entries in the CP.

**Comment by ValWood** [comment]
I think the problem is  for GO that centrioles are not *always* part of the centrioles.
Although centrosomes always have centrioles as a part.

**Comment by krchristie** [comment]
> Make centriole part_of centrosome - Basal body has it's own term (GO:0036064) so doesn't infringe on it.

I don't think we can do this. The issue is that the centriole cycles between being in the centrosome and being the basal body, so we can not say either that it is **always** part_of the centrosome or **always** part_of the basal body.

I agree with Val that we can say that centrosomes always have centrioles as a part.

**Comment by krchristie** [comment]
At ontology editors call on Friday 9/15/17, 
- it was agreed that capable_of_part_of is the correct relationship to use between a complex and a BP term. 
- this would be good to add to the documentation
- Eric said it would be possible to make a SPARQL query to check for correct usage
- There was some discussion about whether we should still be encoding these types of relationships in the ontology, but it was felt that a larger discussion would be required to make a change in current practice.

**Comment by krchristie** [comment]
> Question: what does this mean in the def of centriole: "At division, each pair of centrioles generates another pair and the twin pairs form the pole of the mitotic spindle." - wouldn't that make 4 poles? Shouldn't it be "At division, each centriole generates another centriole and the twin pairs form the pole of the mitotic spindle."

Good catch about that sentence. It is terrible!!! I like your suggestions and would like to add to them. What about:

"At cell division, the two centrioles separate from each other, each centriole generates another centriole at right angles to itself (with the pair being referred to as a centrosome during this phase of the cell cycle), and each centriole pair forms a pole of the mitotic or meiotic spindle."

**Comment by bmeldal** [comment]
>it was agreed that capable_of_part_of is the correct relationship to use between a complex and a BP term.
> this would be good to add to the documentation

I agree, I never know when it might be capable_of so making all BP links capable)of_part)of is easier and consistent.

> "At cell division, the two centrioles separate from each other, each centriole generates another centriole at right angles to itself (with the pair being referred to as a centrosome during this phase of the cell cycle), and each centriole pair forms a pole of the mitotic or meiotic spindle."

The centrosome is more than the 2 centrioles, it includes the PCM. So it should read:

"At cell division, the two centrioles separate from each other, each generating another centriole at its proximal end at right angles to itself, and each new centriole pair forming a pole of the mitotic or meiotic spindle."

@krchristie did you mean to close this ticket?

**Comment by krchristie** [comment]
@bmeldal Thanks for reopening. For some reason, I keep clicking "Close and comment" instead of just "comment"....

I don't object to your request to create new term for procentriole, but there are several issues to work out first. A quote from this review explains one of the main ones:

**Strnad P, Gönczy P. Mechanisms of procentriole formation. Trends Cell Biol.
2008 Aug;18(8):389-96.  Review. PMID: 18620859.**

> Besides assembling through the canonical pathway, procentrioles can also assemble through an alternative pathway in which they do not form in association with pre-existing centrioles. This de novo pathway is active during ciliogenesis, for instance in vertebrate epithelial cells of the oviduct or the trachea, where many procentrioles emerge in a single cell from electron-dense areas called fibrous granules and deuterosomes [16–18]. 

1. Relationships:
**as centriole** `What do you mean here? I don't think this can be is_a centriole since it isn't a centriole until it's assembled, thus I'm not sure what it's parent should be. I don't think it can be an organelle either, for the same logic that it's not a functional structure yet, and once it's complete and functional, it's a centriole, not a procentriole anymore.`
**part_of centrosome** `Can not be part_of centrosome, due to possibility of forming during alternative de novo pathway`

2. Definition. Your proposed definition

> def: A cellular organelle, representing the growing daughter centrioles during cell division. Before DNA replication, cells contain two centrioles. The older of the two centrioles is termed the mother centriole, the other the daughter. During the cell division cycle, a procentriole grows at the proximal end of both mother and daughter centrioles. In the newly divided cells, the original mother and daughter centrioles become mother centrioles while the procentrioles become the new daughter centrioles.

has several issues. 
- One is the fact that not all procentrioles form during cell division, as they can also occur during the alternative, de novo pathway which is active during ciliogenesis in multiciliated cells.
- Another is that I don't think we can call it an organelle, as I commented above.

Here's a proposed new definition. I'm still trying to figure out what parentage this term should get though...
name: procentriole
def: A cellular structure that is the site of a developing centriole, which will become a microtubule organizing center. During the "canonical" pathway of centriole duplication that occurs during the cell division cycle, procentrioles grow at the proximal ends of both mother and daughter centrioles. In the newly divided cells, the original mother and daughter centrioles become mother centrioles while the procentrioles become the new daughter centrioles. Procentrioles can also arise from de novo pathways that occur in multiciliated cells. In ciliated epithelial cells, numerous procentrioles arise form electron dense material referred to as fibrous granules and deuterosomes. The pathway of procentriole formation in multiciliated protists appears to be similar to that in mammalian multiciliated epithelium. In sperm of primative land plants, multiple procentrioles are formed from a blepharoplast giving rise to multicilated sperm cells.
Def dbxrefs: GOC:krc, GOC:bm, PMID:18620859, PMID:21289083, PMID:25047614
is_a: ???

**Comment by krchristie** [comment]
Trying to finalize this term too. I have a couple remaining questions for you @bmeldal 

name: procentriole replication complex
def: A protein complex that acts as a chaperone or scaffold for centriolar proteins during the maturation of the procentriole. Some of its members may become integrated into the growing centriole. Examples are the CPAP(CENPJ)-STIL complex, CEP192-PLK4 complex or CEP152-PLK4 complex in vertebrates.
xref:
`[Just checking you want all 5 references?]` PMID:24997597, 21059844, 22020124, 18207742, 17576815  
GOC:bhm
`[Should these be references for the definition, or cross-references between the GO term and the IntAct objects?]`
IntAct:EBI-15188467
IntAct:EBI-15316456
IntAct:EBI-15189349

relationships:
is_a GO:0043234 protein complex
`[not appropriate to add]` part_of GO:0005813 centrosome
capable_of_part_of GO:0007099 centriole replication

**Comment by krchristie** [comment]
@bmeldal - Are you satisfied with current working proposals in previous two comments for two new CC terms:
- name: procentriole replication complex
- name: procentriole

**Comment by bmeldal** [comment]
Sorry, @krchristie I was waiting for the experts to get back to me. The main person is travelling but I got this comment for her former postoc:

"I always think of the centrosome as a dynamic organelle, both in terms of its structure and composition, comprising centriole(s) + PCM (+ satellite proteins), that changes through the cell cycle. As you probably know, some centrosomal proteins are both centriolar and PCM proteins, and their localisation or absence/presence within the centrosome can also be cell cycle-dependent. As for your comment on ‘the centrosome always contains more proteins (the PCM) than just the centrioles’, I would agree with you. The proximal ends of the centrioles would have some PCM associated with it, albeit in different quantities, throughout the cell cycle."

None of the 2 people I spoke to mentioned the alternative pathway. I guess they just didn't work on it as they concentrated on the role during cell division.

To answer your specific comments:

- [ ] Yes, the defs sound ok, thanks for digging the info out about the alternative pathway.

It's disappointing that we can't add part_of centrosome but I guess it's got to be part_of cytoplasm (both terms).

- [ ] procentriole part_of??? Is it just part_of cell then?

procentriole replication complex:
- [ ] Yes to all 5 PMIDs as they cover the complex composition and function.

- [ ] The Intact xrefs were dbrefs in TG. They also get imported as refs from our GPAD. They show up under "protein complexes" in the term view in QuickGO. @dosumis @tonysawfordebi do I still need to bother adding complex xrefs to term requests as examples when they will come in via the GDAP anyway?

**Comment by krchristie** [comment]
> procentriole part_of??? Is it just part_of cell then?

I put the 'procentriole' term in as is_a 'cell part' [Terms must have an is_a parent; part_of parentage is optional.]

> The Intact xrefs were dbrefs in TG. They also get imported as refs from our GPAD. They show up under "protein complexes" in the term view in QuickGO. @dosumis @tonysawfordebi do I still need to bother adding complex xrefs to term requests as examples when they will come in via the GDAP anyway?

I don't think it's bad to have these IntAct xrefs, I just think it is weird that they are definition xrefs, instead of general xrefs. Searching for "IntAct:EBI" in Protege, it doesn't seem to be entirely consistent:

Terms with "IntAct:EBI" in a definition dbxref:
- ANPR-A receptor complex
- ATF1-ATF4 transcription factor complex
- ATF4-CREB1 transcription factor complex
- ATG1/ULK1 kinase complex
- BID-BCL-xl complex
- BRE1 E3 ubiquitin ligase complex
- Beta-catenin-ICAT complex


Terms with "IntAct:EBI" in a database_cross_reference:
- B-WICH complex

I've put them in as definition dbxrefs, but I'll open a ticket about the lack of consistency in the location of these.

**Comment by bmeldal** [comment]
Thanks, Karen.
