### ISSUE TITLE
Improve definition of 'cohesin ATPase activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14205]
Hello, 

The definition of 'GO:0061775 cohesin ATPase activity' is not very informative: 'Catalysis of the reaction: ATP + H2O = ADP + phosphate; this reaction drives the topological linking or unlinking of chromatin from a cohesin ring complex.' 

@ValWood , can you please help improve this ? Specifically it'd be good to know what the subtrate of this ATPase is. 

Thanks, Pascale

**Comment by ValWood** [comment]
The substrate is the ring and the DNA. The ATPase induces a conformational change to close the ring around the DNA. 
Or a dissociation of rad21 (kleisin) from psc3.
I think I wanted 2 terms for DNA protein loading  and one for unloading. This is both.

https://www.google.co.uk/search?dcr=0&biw=975&bih=751&tbm=isch&sa=1&q=cohesin+unloading&oq=cohesin+unloading&gs_l=psy-ab.3...34631.39437.0.39829.17.17.0.0.0.0.140.995.15j2.17.0....0...1.1.64.psy-ab..0.2.100...0j0i30k1.A9WxWf60LTI#imgrc=56bv4vlczB08BM:

It's quite different from any other reaction we have in GO. The cohesin is a ring around the DNA (one strand initially and then both after  full loading). So the catalytic activity forms a ring to connect 2 DNA strands together, or release them. I will dig out the history later today.  I had a lot of discussion with the author of the Cell paper where they did lots  of in vitro assays to dissect this.

**Comment by ValWood** [comment]
So I wasn't totally satisfied with this at the time.

I favoured 2 different ATPase terms:

https://github.com/geneontology/go-ontology/issues/12530
cohesin ring-loading ATPase,
(or a more generic SMC-type topological DNA ring loading ATPase activity)

descendant of
GO:0033170 protein-DNA loading ATPase activity


and an unloading ATPase (which appears to be more of a  protein "dis-association")
https://github.com/geneontology/go-ontology/issues/12608

because the mechanisms for loading and unloading  are clearly different.
However, we decided there was not enough information right now for a MF term to represent  this the way I would have liked. I was hoping to revisit and tidy when we could add mechanism, but I still think there is probably enough to create  individual, less confusing  terms now and refine later.

This is the activity that the ring has when it is loaded (its a very particular  type of DNA binding):
GO:0061776 - topological DNA entrapment activity
Definition 
The DNA binding activity by which a protein complex interacts selectively and non-covalently with more than one DNA duplex to encircle the DNA molecules with a loose fitting ring.


How you handle this ticket  also depends on 
https://github.com/geneontology/go-ontology/issues/14161

How do you intend to handle ATPases more generally?

There appear  to be branches where ATPases are being "decomposed" into 
ATPase and transport (for example)

Personally, I don't think they should be (see my comments in 14161)
You would need to decompose everything (helicases, translocases, motors etc).  I'm not sure that this is useful for biologists, because these are intrinsically coupled and don't make sense on their own.

**Comment by ukemi** [comment]
Proposed new def:
'Catalysis of the reaction: ATP + H2O = ADP + phosphate, coupled to the topological linking or unlinking of a cohesin ring complex around chromatin.'

Then the loader and the unloader activities can become children of this once we are sure about them. This ticket can then be closed as the question about the ATPase is a more general issue about how to handle ATPase coupled activities in the MF refactor.

**Comment by ValWood** [comment]
Sounds good. Or even around a DNA duplex, sister chromatids, or homologous chromosomes.
