### ISSUE TITLE
ntr: establishment protein of localization to plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14219]
"establishment" and "maintenance" terms should be paired sibling descendants of localization (mostly they are)

However 
protein localization to plasma membrane
has "establishment of localization to plasma membrane" as a related synonym rather than a descendant.

Could the synonym be removed and a descendant term be created?

**Comment by ukemi** [comment]
Can you give me quick reference for the def. I assume you are annotating.

**Comment by mah11** [comment]
Sigh. We used to have exactly this term, and then it got merged into the general localization-to-PM term:

    [Term]
    id: GO:0072659
    name: protein localization to plasma membrane
    namespace: biological_process
    alt_id: GO:0072661
    alt_id: GO:0090002
    def: "A process in which a protein is transported to, or maintained in, a specific location in the plasma membrane." [GOC:mah]
    synonym: "establishment of protein localisation in plasma membrane" RELATED [GOC:mah]
    synonym: "establishment of protein localization in plasma membrane" RELATED [GOC:curators]
    synonym: "establishment of protein localization to plasma membrane" RELATED []

GO:0090002 was establishment of protein localization to plasma membrane. I haven't tracked down a ticket explaining the merge.

**Comment by pgaudet** [comment]
hi @ValWood 
I did a number of those merges (for eg https://github.com/geneontology/go-ontology/pull/13889/commits/6d645cf16e34f43151ec14ba72f6d644d91adc0b) but it's hard to tell when this happened.

I thought I had merged localization and targeting. This must be an error, sorry ! 

Pascale

**Comment by ukemi** [comment]
I currently have a branch with this added as a new term. I am just waiting for a PMID. I think it would be better to just create a new term rather than trying to unmerge, don't you. We need an SOP for this process just in case we want to resurrect merged terms in the future as well.

**Comment by ValWood** [comment]
Oh I see they were moved up.
We should check our annotations pre- 2017-07-13 and see which need to move back to "establishment" or "maintenance"

**Comment by mah11** [comment]
What I said was that _establishment of_ protein localization to plasma membrane used to be a separate term, with ID GO:0090002,

**Comment by ukemi** [comment]
OK. I'm confused now. I thought the issue here was that 'establishment of protein localization to plasma membrane' was inadvertently merged into 'protein localization to plasma membrane'. When this happened, the establishment... terms became synonyms of the localization term. @ValWood would like to see the return of the establishment term.

I propose that rather than try to unmerge or bring the original term back from the dead, we simply create a new 'establishment of protein localization to plasma membrane' term. This is certainly the easier thing to do editing-wise. @cmungall is there any bad consequences of creating a new term with the same name as a previously merged term that I am not considering? Or should we try to bring back the merged/obsoleted term?

**Comment by ValWood** [comment]
PomBase are happy for whichever is easiest for you. Midori mentioned  recently that she could track down the annotations that were merged  for this term in an old GAF.
Others might want to know though  in this case.

**Comment by ukemi** [comment]
I spoke with @cmungall tonight. It is fine to take the route of just adding it as a new term. That will be our SOP for accidentally merged or obsoleted terms.
