### ISSUE TITLE
MF refactor - molecular carrier activity

### ISSUE THREAD

**Issue by thomaspd** [geneontology/go-ontology#14221]
Add new class under molecular role.
Definition: Directly either binding to a specific ion or molecule, or carrying an electron, and delivering it to a specific location/molecule.
Children: see image below.
![screen shot 2017-09-17 at 9 53 08 am](https://user-images.githubusercontent.com/11966328/30523006-18e9ac16-9b8e-11e7-9421-b565d8bea6f5.png)

Note that "transmembrane electron transfer carrier" can be a child of electon carrier.

Also, please rename "ACP phosphopantetheine attachment site binding involved in fatty acid biosynthetic process" to "acyl carrier activity" (we just need to swap the label and synonym).

**Comment by thomaspd** [comment]
Also, let's rename "oxygen transporter activity" to "oxygen carrier activity" as it refers to globins, and are not transporters in the strict sense that we use elsewhere.

**Comment by ValWood** [comment]
This one isn't a carrier in the same sense (i.e not  a transporter)

Also, please rename "ACP phosphopantetheine attachment site binding involved in fatty acid biosynthetic process" to "acyl carrier activity" (we just need to swap the label and synonym).


https://github.com/geneontology/go-ontology/issues/9416
It holds the molecule on an extended arm to reduce "diffusion". There is no directed movement.

**Comment by ValWood** [comment]
Although that might be OK....these won't have "transporter" parentage. It's not so different. Ignore.


Although that might be OK

So would this also include
GO:0005049    nuclear export signal receptor activity etc.
Fits this def.

**Comment by pgaudet** [comment]
@thomaspd how about having 'carrier activity' under 'transporter activity' ? "Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells."

or definitions need to be clarified.

**Comment by ValWood** [comment]
You also need to make "carrier activity" terms "related synonyms" for all transmembrane type transporters which are often referred to as carriers, to remove confusion.

**Comment by ValWood** [comment]
So   "carrier activity" has multiple biological used.

we need to 
1.  make "carrier activity" terms "related synonyms" for all transmembrane type transporters which are often referred to as "carriers", to remove confusion.

2. If I understand correctly, The grouping suggested by Paul above are not "transporters"
An oxygen carrier is not a "transporter" in the way that it is responsible for directed movement.
The directed is  provided by the circulatory system oxygen transporters are just "carrying"
(like suitcase in a car. The suitcase is not the transporter)
MAybe the definition is binds a molecule, enabling it to be transported by X.
 So it is part_of the transport process, but is not itself a transporter.

3. I'm not sure of the difference between
"transmembrane electron transfer carrier"
and
"electron carrier activity"

4. I don't know if the metallochaperones are always carriers in the same sense (or even ever referred to as 'carriers'. These are involved (sometimes) in  delivery of a metal into an enzyme. I thought of this as a "metal insertion" step in enzyme  maturation. I'm not sure that it is anything to do with transport.

**Comment by ValWood** [comment]
@Antonialock 
Are these types of chaperone involved in 'transport'  of the metal or just "insertion"
http://preview.pombase.org/term/GO:0016532
http://preview.pombase.org/term/GO:0016531

**Comment by Antonialock** [comment]
Typically, three distinct domains compose the copper carrier CCS (39). Domain I at the N terminus functions in copper binding under conditions of copper deprivation. Domain II is required for appropriate docking between CCS and SOD1. Domain III, which is highly conserved among CCS molecules across different species, binds copper and participates in the interaction with SOD1 during the process of copper transfer

**Comment by Antonialock** [comment]
(http://www.jbc.org/content/279/27/28744.long)

**Comment by pgaudet** [comment]
- I proposed to obsolete 'transmembrane electron transfer carrier' and children, see https://github.com/geneontology/go-ontology/issues/14234

**Comment by pgaudet** [comment]
@thomaspd are you sure about 'oxidative phosphorylation uncoupler activity' belonging in this group ? It seems to be a real transmembrane transporter, see http://www.uniprot.org/uniprot/P25874

Pascale

**Comment by pgaudet** [comment]
@ValWood but these are not under carriers, they are under transporters; isn't that confusing as well? 

If you have a list I will add them. 

Thanks, Pascale

**Comment by ValWood** [comment]
Which ones?  The ones in point 1.? There are transmembrane transporters which are called "carriers". This is unfortunate but  we need to negociate this.  Some people will use this for searching. I suggest just to make sure that none of the "transmembrane transport type carriers" have "carrier" in their term name, but make this a "related synonym" maybe? I don't think we can easily ignore its widespread use in this context....I guess we could try....

**Comment by ValWood** [comment]
The nucleocytoplasmic transporter issue is easiest to deal with so I made a ticket for that.
https://github.com/geneontology/go-ontology/issues/14336

**Comment by pgaudet** [comment]
Just realized I did not add synonyms as requested-

**Comment by pgaudet** [comment]
Added synonyms: 
* GO:0005471 ATP:ADP antiporter activity -> added synonym ADP/ATP carrier protein 
* GO:0015367 oxoglutarate:malate antiporter activity ->added synonym  2-oxoglutarate/malate carrier protein

**Comment by pgaudet** [comment]
Update definition based on @pedruzzi feedback
 id: GO:0000036
 name: acyl carrier activity
 namespace: molecular_function
-def: "Presenting an acyl group for processing or offloading to a cognate enzyme by covalently binding the acyl group via a phosphopantetheine prosthetic group and mediating protein-protein interactions with of the enzyme. The acyl carrier protein (ACP) presents substrates to enzymes involved in fatty acid biosynthesis." [CHEBI:22221, GOC:jl, GOC:vw]
+def: "Binding an acyl group and presenting it for processing or offloading to a cognate enzyme. Covalently binds the acyl group via a phosphopantetheine prosthetic group and mediates protein-protein interactions with the enzyme conferring specificity. The acyl carrier protein (ACP) presents substrates to enzymes involved in fatty acid biosynthesis or in polyketide secondary metabolite biosynthesis." [CHEBI:22221, GOC:jl, GOC:vw]
 comment: Note that this term was moved from transporter to binding because we decided that ACP is not a true transporter, but instead tethers the growing entity that is acted on to make the fatty acid, so binding is the more correct parent. July 2012.
 subset: gosubset_prok
 synonym: "ACP phosphopantetheine attachment site binding involved in fatty acid biosynthetic process" EXACT []
@@ -254684,7 +254684,7 @@ creation_date: 2012-10-05T10:53:55Z
 id: GO:0036370
 name: D-alanyl carrier activity
 namespace: molecular_function
-def: "Presenting a D-alanine for processing or offloading to a cognate enzyme by covalently binding the D-alanine via a phosphopantetheine prosthetic group and mediating protein-protein interactions with of the enzyme. Activated D-alanine is transferred onto a teichoic acid acceptor molecule. The carrier protein provides an essential link between the D-alanine-D-alanyl carrier protein ligase and the incorporation of D-alanine into the substrate." [GOC:crds, PMID:11222605, PMID:22750871, PMID:8682792]
+def: "Binding a D-alanine and presenting it for processing or offloading to a cognate enzyme. Covalently binds the D-alanine via a phosphopantetheine prosthetic group and mediates protein-protein interactions with the enzyme conferring specificity. The carrier protein provides an essential link between the D-alanine-D-alanyl carrier protein ligase and the incorporation of D-alanine into lipoteichoic acid by transferring activated D-alanine to cell membrane phosphatidylglycerol (PG)." [GOC:crds, PMID:11222605, PMID:22750871, PMID:8682792]
 synonym: "D-alanyl carrier protein" RELATED [GOC:crds, PMID:11222605]
 intersection_of: GO:0000036 ! acyl carrier activity
 intersection_of: part_of GO:0070400 ! teichoic acid D-alanylation
@@ -549565,7 +549565,7 @@ creation_date: 2015-03-26T10:16:27Z
 id: GO:1904091
 name: peptidyl carrier protein activity
 namespace: molecular_function
-def: "Presenting an oligopeptide for processing or offloading to a cognate enzyme by covalently binding the acyl group via a phosphopantetheine prosthetic group and mediating protein-protein interactions with of the enzyme. Peptidyl carrier protein is involved in nonribosomal peptide biosynthetic process." [GO_REF:0000061, GOC:pr, GOC:TermGenie, GOC:vw, PMID:17502372]
+def: "Binding an amino-acid derived peptidyl group and presenting it for processing or offloading to a cognate enzyme. Covalently binds the peptidyl group via a phosphopantetheine prosthetic group and mediates protein-protein interactions with the enzyme conferring specificity. Peptidyl carrier protein (PCP) is involved in nonribosomal peptide biosynthetic process." [GO_REF:0000061, GOC:pr, GOC:TermGenie, GOC:vw, PMID:17502372]
