### ISSUE TITLE
Obsolete 'signal transducer' [was: why is Noctua inferring an MF from the process the gene is annotated to]

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#14232]
_From @krchristie on September 18, 2017 22:18_

I was wondering why Noctua is creating an MF that seems to be inferred from the BP the gene is annotated to.

See:
ID - gomodel:59b38c1100000155 
Name - TEST: assuming ND evidence, F-P link directionality - KRC 
http://noctua.berkeleybop.org/editor/graph/gomodel:59b38c1100000155

In the model section using the Ift172 gene, I have only associated Ift172 with an anonymous MF that is part_of the BP term 'smoothened signaling pathway'. However, in the annotation preview, the MF annotation for this gene is for 'signal transducer activity':

**Ift172 Mmus | enables | signal transducer activity** 
Ift172 Mmus | involved_in | smoothened signaling pathway 
Ift172 Mmus | involved_in | cardiac septum morphogenesis 

I don't want this MF annotation. I also don't understand how it can be assumed that all MFs that are part of 'smoothened signaling pathway' are automatically 'signal transducer activity'.

@ukemi suggested that we should get input from @dosumis on this.

_Copied from original issue: geneontology/noctua-models#45_

**Comment by cmungall** [comment]
_From @balhoff on September 19, 2017 1:28_

'signal transducer activity' ==  molecular_function and (part_of some 'signal transduction')
'cell surface receptor signaling pathway' is_a 'signal transduction'
'smoothened signaling pathway' is_a 'cell surface receptor signaling pathway'

**Comment by cmungall** [comment]
_From @ValWood on September 19, 2017 5:43_

not all parts of signalling pathways are signal transducers. Many molecules are scaffolds, for example.

**Comment by cmungall** [comment]
_From @dosumis on September 19, 2017 6:9_

IIRC, this axiom has been in GO since before I arrived:

'signal transducer activity' == molecular_function and (part_of some 'signal transduction')

> not all parts of signalling pathways are signal transducers. Many molecules are scaffolds, for example.

Can you give some more criteria about what makes something a signal transducer in addition to being part of an ST pathway?  With this we may be able to tighten the def.

Isn't it possible to perform a scaffolding (protein binding bridging?) function in ST and still be considered a signal transducer?

e.g, wouldn't axin and dsh both be considered signal transducers here:

![image](https://user-images.githubusercontent.com/112839/30577961-52be4704-9d09-11e7-9630-9019f6fa3f68.png)

**Comment by cmungall** [comment]
_From @ValWood on September 19, 2017 6:46_

I have never been sure. It was one of my questions for the signalling meeting.

For example ahk1
http://preview.pombase.org/gene/SPAC7D4.03c
http://preview.pombase.org/gene/SPCC1739.11c
http://preview.pombase.org/gene/SPBC32H8.07

are signalling complex scaffolds. They have no catalytic activity? (often WD repeat proteins)

**Comment by cmungall** [comment]
_From @ValWood on September 19, 2017 7:0_


I have a bit of a problem with the term "signal transducer"
It gives us multiple ways of describing the same  molecular function.

GTPase + signal transducer
protein kinase + signal transducer
Therefore we all have lots of 'signal transducers" that aren't described as signal transducers.

I wonder if it is a term we could manage without. 
Or if it should be a parent of all "signal transducers". No point in having concurrent terms to describe the same activity.

BUT, not all GTPAses are signalling transducers, so  you would need
"signal transducing GTPase activity"

**Comment by cmungall** [comment]
_From @dosumis on September 19, 2017 8:59_

> For example ahk1
> http://preview.pombase.org/gene/SPAC7D4.03c
> http://preview.pombase.org/gene/SPCC1739.11c
> http://preview.pombase.org/gene/SPBC32H8.07

> are signalling complex scaffolds. They have no catalytic activity? (often WD repeat proteins)

So catalytic activity is important (necessary) to being a signal transducer?  We classify receptors as signal transducers and some of those (frizzled) have no known catalytic activity.

> I have a bit of a problem with the term "signal transducer" It gives us multiple ways of describing the same molecular function.

We have multi-inheritance classification throughout GO and including in MF. I don't see a problem here if we can pin down a logical def.

> BUT, not all GTPAses are signalling transducers, so you would need
"signal transducing GTPase activity"

Not necessarily. If all GTPases that are part of ST pathways are signal transducers, we can infer classification under signal transducer activity, in fact we would right now from:

'signal transducer activity' == molecular_function and (part_of some 'signal transduction')

I've been playing with formal definitions of 'molecular transducer activity'.  We may be able to tighten up the definition to:

'signal transducer activity' == 'molecular transducer activity' and (part_of some 'signal transduction')

**Comment by ValWood** [comment]
> So catalytic activity is important (necessary) to being a signal transducer? 

No but I don't know what the criteria are.  I assume that the molecule needs to actually "transduce the signal" a receptor would be included.

>Not necessarily. If all GTPases that are part of ST pathways are signal transducers, we can infer classification under signal transducer activity, in fact we would right now from:

Yes but we have LOTS of annotations. Over 300 unique annotations for some GPs. So we really want a single way to describe a single function. Not two. It leads to lots of redundancy on gene pages.

**Comment by dosumis** [comment]
> So we really want a single way to describe a single function. Not two. It leads to lots of redundancy on gene pages.

This is kind of fundamental to how inference works with GO-CAM.  These equivalent class definitions have been doing work in the ontology for years (automating classification).  They also result in inferences from GO-CAM models.  These should result in new inferred annotations where they are not redundant.

**Comment by ValWood** [comment]
But that's the point. At the end of the day biologists have to consume these annotations on gene pages.
If an assay shows that a gene product is a "signal transducing GTPase" you only want a single annotation for this, not two.

Extrapolating this to cdc2.
Cdc2 is a signal transducer. It is also a  cyclin-dependent  kinase.

We would not want to *generate* an explicit "signal transducer activity" for every annotation to "cyclin dependent kinase" (lots of redundant and  therefore uninformative annotation). This should however be inferable  from the ontology structure. 
A cyclin-dependent protein kinase is_a 'signal transducer activity'  (if we decide this is a useful grouping term, at the moment it seems that it does not mean anything other than 'signal transduction')

Currently "cyclin dependent protein kinase and signal-transducer' need to be made as separate annotations,  because there is no relation. But not always. For instance MAP kinase  *is* a descendant of signal transducer activity. Some terms are, some terms aren't. Inconsistent. ...


1. we should decide if "signal transducer activity' is a meaningful function term.

2. If it is, it should be a grouping term for all signal transducers. If it isn't we get too many redundant annotations which are not useful for end-users.

3.  We need a single  specific annotation to describe a single molecular function. Its easier  for curators, and its easier for the end users.

**Comment by ValWood** [comment]
I don't remember the exact history of "signal transducer activity" but if it covers receptors, kinases, GTPases etc, it isn't really a MF grouping term at all it's a  collection of different functions =BP term in the MF  ontology.
Why do we need it ?

**Comment by ValWood** [comment]
PomBase has only 27 “signal transducer” annotations

7 signalling receptor
3 MAP kinase
4 Map kinase kinase kinase
3 MAP kinase kinase
2 phosphorelay response regulator
1 histidine phosphotransferase
1 signal transducer, downstream of receptor, with serine/threonine kinase activity (I have a problem with this anyway as aren’t all protein kinases signal transducers?)

7 FP SPKW mappings https://github.com/pombase/curation/issues/1690

**Comment by vanaukenk** [comment]
Also relevant to this issue is the inference we get from GO-CAM models that ligands, e.g. WNT3, annotated to 'receptor ligand activity' and also part_of a signaling pathway, e.g. canonical Wnt signaling pathway, are inferred to have 'signal transducer activity'.  

This is in contrast to the term usage comments we currently have for 'receptor ligand activity':
Comment:  Ligands do NOT have the molecular function 'signal transducer activity'.

I am also wondering what we really gain by having 'signal transducer activity' in the MF ontology.

It looks like there are currently only 126 experimentally supported direct annotations to this term, and the gene products cover quite a range of other MFs.  

Perhaps one of the AIs from the signaling workshop could be to review experimental annotations to this term and see if there are any gene products for which we think there is *not* another sufficiently descriptive MF annotation.  If there are, then we could see if any of those GPs would be better described by a different, or new, MF term.

**Comment by ukemi** [comment]
The issue with this is that the pathways are all classified as signal transduction and signal transducer has a logical def of anything that is part of a signal transduction process. We need to change one or the other.

**Comment by dosumis** [comment]
The inference to 'signal transducer activity' is a side-effect of an issue with BP.

BP options:

Option1: make 'receptor ligand activity' part_of 'signal transduction', allowing users to make part_of links from 'receptor ligand activity' to types of 'signal transduction', e.g. 'canonical Wnt signaling pathway'.   

Option2: ST starts with activity of the receptor.  It does not include the activity of the ligand.  Terms like 'canonical Wnt signalling pathway' (pathway defined by ligand) stay under ST.

Option3:  ST starts with activity of the receptor.  It does not include the activity of the ligand.  Terms like 'canonical Wnt signalling pathway' (pathway defined by ligand) are no longer under ST.

It seems that option1 smells bad to everyone. It's really the same as saying that ligands are signal transducers.   We should therefore go with option 2 or 3

If we go with option 2, how do we define terms like 'canonical Wnt signalling pathway'?  This can work if we have terms for receptor activity defined by ligand type - which we mostly do already.  

So, we could say:

```
'cannonical wnt signaling pathway'
SubClassOf **starts with**\* some 'wnt receptor activity'

'wnt receptor activity EquivalentTo: receptor activity that **has ligand* some wnt
```

\* this is a sub-relation of has_part - already used in the ontology. 

Issue: how do we prevent GO-CAM curators from making the link from  receptor ligand activity.

I could add an axiom to make models that have this link inconsistent:

```
'signal transduction pathway' disjoint_with has_part some 'ligand receptor activity'
```

If we go with option 3, we can allow GO-CAM curators to make a part_of link from ligand to 'pathway defined by ligand' terms, but we need a new classification for 'pathway defined by ligand' - NOT 'signal transduction'.  I'm not sure what to call this.  

I'm agnostic about whether we go with 2 or 3, but 3 is probably easiest for GOCAM as we don't need to worry about preventing curators from adding part_of relationships between ligand activity and pathway terms.

**Comment by pgaudet** [comment]
Discussing @thomaspd 
- We can remove 'signal transducer activity' 
- We want to keep 'molecular transducer activity (at least for now), because it corresponds to compound functions. Let's see later if 'compound functions' are a useful grouping term.

**Comment by pgaudet** [comment]
Email sent out March 29th: 
Dear all, 

The proposal has been made to obsolete GO:0004871 signal transducer activity and children:  

GO:0005057 signal transducer activity, downstream of receptor
GO:0004716 signal transducer, downstream of receptor, with protein tyrosine kinase activity
GO:0004702 signal transducer, downstream of receptor, with serine/threonine kinase activity
GO:0004728 signal transducer, downstream of receptor, with protein tyrosine phosphatase activity
GO:0009400 signal transducer, downstream of receptor, with serine/threonine phosphatase activity

The reason for obsoletion is that in the Molecular Refactoring project we have noticed that this term was not clearly defined and it was not providing a useful grouping. 
    
There are many annotations and mapping to these terms; all groups should loook at the annotation review ticket:
https://github.com/geneontology/go-annotation/issues/1899

The good news is that most of the gene products are also annotated to other molecular functions, so that choosing a better term should be relatively straignt forward.      
    
Any comments can be added to this issue: https://github.com/geneontology/go-ontology/issues/1899
    
We are opening a comment period for this proposed obsoletion. I’ll leave tis open for longer than usual to give people some time to review annotations. 
    
Thanks,

Pascale

**Comment by pgaudet** [comment]
Note to self: remember to close #15615 when I merge this.
