### ISSUE TITLE
MF refactoring: electron carrier activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14267]
Under the current version of the MF refactoring, 'electron carrier activity' is under the new class 'molecular carrier activity', see scrrenshot. 
<img width="274" alt="image" src="https://user-images.githubusercontent.com/4782928/30951976-fced7952-a425-11e7-9932-0186ddd0782b.png">

@ukemi points out that electron 'carriers' do not work as described in the definition of 'molecular carrier activity'. 
'molecular carrier activity' is defined as: "Directly either binding to a specific ion or molecule, or carrying an electron, and delivering it to a specific location/molecule."

However 'electron carriers' do not move any one electron, but the chained reactions result in the net movement of an electron. The definition is relatively clear: 'Any molecular entity that serves as an electron acceptor and electron donor in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient.'

**To do**
We have to decide whether to 
(a) make electron carrier activity a direct child of molecular function
(b) widen the definition of molecular carrier activity. A suggestion is: 
"Directly either binding to a specific ion or molecule, or contributing to the movement of an electron via an oxidoreduction reaction, resulting in the net movement of the ion/molecule to a specific location/molecule."
(c) something else?

Do you have feedback @ukemi @deustp01 @thomaspd ? 

Thanks, Pascale

**Comment by ValWood** [comment]
You should move electron carrier out. It is another fundamentally different use of 
"carrier".

The molecular activities   of  "molecular carrier" are still very mixed.

There are: 
"molecular transport chaperones" bind a molecule and allow it to be moved by some transport system.  ( oxygen carriers, karyopherins and the like)

"metallo-complex assembly chaperones" bind a molecule and  somehow enable it to be inserted into a protein during assembly

"acyl carriers" are different again. We have long discussions about these on the tracker. They bind a molecule and keep it in close proximity to the active site. The do not do transport (no directed movement here).

I don't think that grouping these  together under "molecular carrier" is helpful  to curators (they are totally different uses of the word carrier, almost as different in function as the "transmembrane solute  carriers", the only real commonality is "binding").

The problem is that "delivering" in the definition is too vague (and is not a defined  biological process!). If you define in terms of  the mechanisms & processes  of the types of carriers (transporting, metal insertion, complex assembly), these would separate  naturally.

I listed some of the differences in one of the recent  tickets. I will try to find it.

**Comment by pgaudet** [comment]
Hello @ValWood @dosumis & anyone interested in this issue: 

Let me reformulate the issue: 
would it be desirable, from either a biological perspective, or from a usability view (for example, to help user and curators find terms), to group these 'molecule movers' activities? 
ie 
- transmembrane transporter
- electron transfer
- acyl carrier and related 
-metallochaperone ? 

Alternatively, should they all be directly under the root ? 

Thanks, 

Pascale

**Comment by ValWood** [comment]
I'm just not sure if it is useful to group transporter type carriers, electron carriers and other types of carrier.
For me it seems a like this is against the principle  of GO- to disambiguate different uses of the same word.

Firstly, anywhere there is an alternative word to use instead of carrier, we should use it.

molecular carrier
This def isn't great:
Directly either binding to a specific ion or molecule, or carrying an electron, and delivering it to a specific location/molecule.

because it does not exclude  "transmembrane carriers".
...and I thought that you wanted to do that.
Also I don't see why this new term as it stands would not be under binding?

Beginning with a much more precise top level definition would help to determine precisely what we mean by this term, and if things really belong under, it or are different enough to be a  top level term in their own right.

**Comment by pgaudet** [comment]
OK. I will
1. Move electron carrier activity out (and under oxidoreductase) 
2. Rename it electron transfer activity
3. Check definitions of 'electron carrier activity ' and of the parent 'molecular carrier activity'

**Comment by pgaudet** [comment]
4. I will also remove all protein-specific synonyms: 
chlorophyll electron transport system
2Fe-2S electron transfer carrier
3Fe-4S/4Fe-4S electron transfer carrier
adrenodoxin-type ferredoxin
amicyanin
azurin
bacterial-type ferredoxin
chloroplast-type ferredoxin
copper electron carrier
dicluster bacterial-type ferredoxin
electron transfer flavoprotein
electron transfer flavoprotein
group I
electron transfer flavoprotein
group II
high-potential iron-sulfur carrier
iron-sulfur electron transfer carrier
monocluster bacterial-type ferredoxin
mononuclear iron electron carrier
polyferredoxin
redox-active disulfide bond electron carrier
rubredoxin
small blue copper electron carrier
thioredoxin-like 2Fe-2S ferredoxin 


(and keep those: 
electron transporter activity
electron carrier
electron acceptor activity
electron donor activity).

Thanks, Pascale

**Comment by pgaudet** [comment]
Moved 'electron transfer (carrier) activity' out of molecular carrier activity. 
Did not close yet - I would like to somehow put this under the correct process in the logical definition. 
- Pascale

**Comment by ValWood** [comment]
probably the parent should be this term

electron transport chain
https://www.ebi.ac.uk/QuickGO/term/GO:0022900

electron transport chain isn't part_of transport   (it would has_part transport, for the hydrogen transport part?)

https://en.wikipedia.org/wiki/Electron_transport_chain
An electron transport chain (ETC) is a series of complexes that transfer electrons from electron donors to electron acceptors via redox (both reduction and oxidation occurring simultaneously) reactions, and couples this electron transfer with the transfer of protons (H+ ions) across a membrane.


but it seems odd that anything which has has_part "transport" could be considered to be a "transporter"? This is not always true?

**Comment by pgaudet** [comment]
Hi @ValWood 
Thanks for the feedback. This was discussed several years ago with @jimhu-tamu and Debbie- although the term used in the literature is 'transport', the aim of the process is to create an energy gradient, and not to transport protons. So this seems OK to me. 

I'm adding the parent and closing this one. 
Thanks, Pascale
