### ISSUE TITLE
MF refactoring: top level classes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14266]
Hello, 

In an earlier version of the MF refactoring, there were 3 top level classes: 

-  **system component function /  molecular role**
Meant to give a more 'biological' view of MF 
Definition by Paul T and Pascale: The function that a molecule carries out by virtue of its elemental molecular activities. The molecular role of a gene product desribes its function as a part of a larger biological process." [GOC:pdt]
 is_a: GO:0003674 ! molecular_function
See screenshot for children
![image](https://user-images.githubusercontent.com/4782928/30951715-ada44840-a424-11e7-813b-e8c9ac139042.png)

- **biochemical activity / elemental molecular activity**
Meant to represent mechanism of protein functions. 
Definition by Paul T and Pascale: The physico-chemical mechanism by which a molecular role is carried out." [GOC:pdt]
+comment: Note that elemental molecular activities may not necessarily contribute to a molecular role.  For example, a gene product might bind another molecule but have no functional effect on that other molecule.
Children:
- binding
- catalytic activity

- **compound function**
From @dosumis 

These terms have been excluded from the current version of the MF refactoring (https://github.com/geneontology/go-ontology/pull/14226) 
because the class labels were not clear, and the groupings they provided were not critical (at last for now). 

I am opening this issue so that we can recapitulate the creation of these terms if we decide to do so later. 

Pascale

**Comment by dosumis** [comment]
The first two came from Paul's original refactoring suggestions.   The defs above are Paul's original ones rather than mine (for mine see earlier commits or the refactoring doc (below).   The third is the general class for the main thrust of my work on refactoring.  

The MF [refactoring doc](https://docs.google.com/document/d/18VQaVHvTmNvJuRczlnmJnjLtd2WxvfGafXoU1LFEQ2c/edit) has background and explanation for the terms.  I agree that none of these terms are useful for grouping annotations, but they can help to organise and potentially provide useful genus terms for logical defs.

**Comment by pgaudet** [comment]
@thomaspd and I have decided not to implement this. 

The only 'outlier' in molecular_function right now is 'binding', ie knowing what a protein binds to is never sufficient to specify a protein's function. Binding is a mechanism. 

All proteins with a real function are expected to slim up to a class *other* than binding.

**Comment by pgaudet** [comment]
Added to the wiki: http://wiki.geneontology.org/index.php/Guidelines_for_equivalence_axioms
