### ISSUE TITLE
Rename and move RNA binding transcription factor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14334]
2 EXP annotations, usage does not match the definition, and the cited reference (PMID:83322119) does not describe what RNA binding transcription factor activity is.

**Comment by krchristie** [comment]
It seems to me that the reference by the definition of this term, PMID:8332211, does indeed provide an example of this activity, in bold below. I'm not as familiar with the Tat protein from HIV, but my understanding is that Tat protein also "Interact[s] selectively and non-covalently with an RNA sequence in order to modulate transcription.

1. Nature. 1993 Jul 29;364(6436):401-6.
Transcriptional antitermination.
Greenblatt J(1), Nodwell JR, Mason SW.

Antiterminator proteins control gene expression by recognizing control signals
near the promoter and preventing transcriptional termination which would
otherwise occur at sites that may be a long way downstream. **The N protein of
bacteriophage lambda recognizes a sequence in the nascent RNA, and modifies RNA
polymerase by catalysing the formation of a stable ribonucleoprotein complex on
its surface,** whereas the lambda Q protein recognizes a sequence in the DNA. These
mechanisms of antitermination in lambda provide models for analysing
antitermination in viruses such as HIV-1 and in eukaryotic genes.

PMID: 8332211  [Indexed for MEDLINE]

**Comment by ValWood** [comment]
But  is the RNA binding part critical for  the TF role? If a TF needs to bind DNA or RNA polymerase (this binds RNA pol I presume?). It also binds to RNA but this is not part of its TF role (By analogy, RNA polymerase also binds RNA, would you call that and RNA binding TF?).

**Comment by pgaudet** [comment]
Hi @krchristie 
isn't antitermination different from transcription? 
I think the problem is there are multiple types of regulation of transcription: 
1. Go/no-go given by DNA binding activators/repressors and co-activators/co-repressors
2. Regulation of the trasncription process itself. Is anti-termination gene specific ? Or does it just help stabilize the nascent transcript ? 

These two types of regulation are very different from each other. 

Thanks, Pascale

**Comment by krchristie** [comment]
@ValWood 
- Yes, the RNA binding part is critical for the role of proteins like N and NusA to exert their TF role. Not sure what you are referring to with respect to RNA pol I. N and NusA work on bacterial RNAP.

No, I would not call any part of RNA polymerase an RNA binding TF.

**Comment by ValWood** [comment]
Scrub that.

But it must be possible to define a transcription factor to exclude this anti-termination factor  (especially since it's an exogenous protein)? If we define a  sequence specific -transcription factor as  DNA binding and regulating transcription initiation would would not need to include  edge case (which isn't really what people think of as a TF).

Here we seem to be identifying anything with a  role in transcription, and expanding the definition  of TF to include them, rather than  defining a TF to include the things a biologist would expect to find.

We would not go far wrong if we used the wikipedia definition of a transcription factor:
https://en.wikipedia.org/wiki/Transcription_factor

**Comment by krchristie** [comment]
@ValWood I agree that there are **some** groups of people who only ever think of the Wikipedia definition, though even that Wikipedia definition you cited qualified itself to specify: "sequence-specific DNA-binding factor". There is a large group of people who only think of transcription in terms of how it affects the expression of their favorite eukaryotic protein coding gene, so most of those people only think of "sequence-specific DNA-binding TFs for RNAP II".

However, in my experience, there are definitely other groups of people who have a broader view of the full range of things that are called transcription factors in the literature. Having done my PhD in a joint lab that studied both bacterial and eukaryotic transcription, I was trained with a broader view. During the time David H and I were working on the reorganization of transcription, I had a lot of contact with Jim Hu and my impression was that he was in agreement with how we did it.

I think it would be very unwise to cherry pick your favorite subset of the Venn diagram of transcription factors and say we're only going to use the phrase "transcription factor" for this subset. Also, if you want to define "transcription factor" in such a way as to require sequence specific DNA binding, you will exclude some of the "general transcription factors" of RNAP II that do NOT bind DNA.

**Comment by pgaudet** [comment]
Hello, 

to be consistent with the new representation of transcription factors, the term 'RNA binding transcription factor activity' will be renamed 'RNA binding transcription regulator activity' and move it as a direct child of the new term 'transcription regulator activity' created in #13588 

Thanks, Pascale

**Comment by ValWood** [comment]
That works for me! Your new transcription regulator activity seems to fit the  very broadest use of "transcription factor". Thats what I was trying to say above in a very long-winded way.

**Comment by pgaudet** [comment]
OK good :) 
I'll create new issues for the further changes.
