### ISSUE TITLE
NTR: regulation of 'GO:0034454 microtubule anchoring at centrosome'

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14360]
Figure 2 in PMID:17139249 demonstrates the involvement of GSK3beta (P49841) in regulation of microtubule anchoring at centrosome.

NTR: regulation of 'GO:0034454 microtubule anchoring at centrosome'.

Refs: 
PMID:17139249
GOC:aruk
GOC:bc

**Comment by BarbaraCzub** [comment]
I have just had a discussion with @RLovering and the issue with this request is that the definition for 'GO:0034454 microtubule anchoring at centrosome' does not specify the boundaries of this processes. Where does it start and where does it end?
In the paper itself the authors introduce the subject by citing the role of GSK3beta in _regulation of_ microtubule dynamics, in _regulation of_ binding of MAPs (microtubule-associated proteins) to microtubules, and _regulation of_ microtubule stability. On the other hand in the results section, the authors describe the _involvement of_ GSK3beta in the anchoring of microtubules to centrosome. So which one should be used for annotation? Where does the processes of microtubule anchoring start and end? Is GSK3beta kinase activity a part of this process, or does it regulate it? Some of the proteins associated with 'GO:0034454 microtubule anchoring at centrosome' so far include molecular motor proteins; the role of kinases would be very different. The term definition should be revised to include boundaries of the processes.

**Comment by ValWood** [comment]
This is a little bit like
GO:0051315 - attachment of mitotic spindle microtubules to kinetochore
(albeit at the other end of the spindle)
https://www.pombase.org/term/GO:0051315

Various phosphorylation events regulate the execution of the processes (mainly by enabling or disabling physical interactions).  In my opinion the phosphorylation events are *always* regulating the processes in some way.... We annotate these to "regulation of process x"  because they are  definite regulators.

Many of these processes do not have starts and ends, because we don't know when they begin and end. However, this does not prevent something from being a  known regulator of a process (or a sub process).

Gene products can regulate a process external to the process  start (upstream signalling to activate the process), or as part of  the process

GO does not distinguish between these 2 types of regulation, and I'm not sure that GO-CAMs help here...we still have a problem in distinguishing upstream regulation from within process regulation....

**Comment by BarbaraCzub** [comment]
Thanks @ValWood for this comment. I suppose in GO-CAM we are expected to use the relation _causally_upstream_of_or_within_ if we do not know whether the kinase activity regulates the specific process x, or a process upstream of it.. So in this context knowing where process x begins and ends would help decide whether this should be _regulates_ or _causally_upstream_of_. However, I agree that phosphorylation and dephosphorylation are in general regulatory events. 
In this specific case, the paper overall shows that GSK3beta phosphorylates BICD1, which regulates the interaction of BICD1 with dynein intermediate chains (DIC). And this in turn regulates microtubule anchoring at the centrosome. So it is the binding of BICD1 to DIC, which is being _directly regulated_ by GSK3beta phosphorylation. This BICD1 to DIC binding then affects microtubule anchoring at centrosome, so the regulation of microtubule anchoring at centrosome is not _direct_. So do we say that GSK3beta _regulates_ microtubule anchoring at centrosome , or is _causally_upstream_of_ microtubule anchoring at centrosome, or is _involved in_ microtubule anchoring at centrosome (which is how the authors phrased it in context of the relevant experiments, here specifically Figure 2)? @RLovering do you have any further comments?

**Comment by BarbaraCzub** [comment]
#14361

**Comment by ValWood** [comment]
This is precisely why I don't understand "causally upstream". It is too vague,  it just means "affects"

A gene product can be causally upstream and regulating, or causally upstream and not regulating.   
A gene product can be regulating upstream of a process, or regulating within a process.   
- upstream regulation can be 
1  "direct" i.e signalling pathway *directly regulates process a* - or
 2 *indirect* regulates process a which is  causally upstream of process b. (I think this is  what is meant by causally upstream, but I am not sure...)

You can be  "regulation" part is critical but we can't distinguish  real upstream regulation (signalling)  from within pathway regulation.
Within pathway regulation is regulating the process but also also part_of the process

**Comment by BarbaraCzub** [comment]
Following Pascale's advice (https://github.com/geneontology/noctua-models/issues/50#issuecomment-483654050) and discussions with Ruth, I am going to add the regulation term.
cc @pgaudet @RLovering
