### ISSUE TITLE
Restore 'transcription elongation regulator activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14398]
Edited title 2018-07-12

**Initial ticket:** 
(Hello, 
To address 
https://github.com/geneontology/go-annotation/issues/1641

we seem to be missing a concept to describe the role of proteins involved in processivity of transcription, for example Yeast SPT4, SPT5, SPT6, as well as 
https://www.ebi.ac.uk/interpro/entry/IPR023459

The definition would be similar to that of 'An enzyme regulator activity that increases the processivity of polymerization by RNA polymerase, by allowing the polymerase to catalyze the elongation of the nascent transcript or move past template-encoded arresting sites.' 

Thanks, Pascale)

**Comment by krchristie** [comment]
@pgaudet - My recollection of the word "processive" and how it applies to polymerases is that you absolutely cannot use it for RNA polymerases.

One of my UC Berkeley professors, and the PI of the other half of my joint lab, lectured at great length about how it is not appropriate it use the word "processivity" for RNAP's because it has a very specific meaning about how many nucleotides a DNAP links together in a single visit to the template before it falls off. DNAP's can come on and off the DNA template many times. In contrast, once an RNAP comes off the template, it does not get back on. Therefore the term "processivity" is irrelevant.

**Comment by krchristie** [comment]
It may be that my professor was railing against a misuse of a term that is now out of the barn.

However, if you put "processivity factor" into PubMed, that specific phrase seems to only be used for some DNA polymerase factors. 

While I do see quotes like this from Patrick Cramer's lab (PMID:21386817):

> The core function of NusG and Spt4/5 is to stimulate transcription elongation and RNAP processivity, and this function resides in the conserved NGN domain

So, though Spt4/5 is described as affecting processivity (i.e. making it fully processive so that it does not fall off), I still do not see anyone calling factors like Spt4/5 a "processivity factor". I'm not sure we should be inventing terminology that we are not seeing in the literature. In the Cramer lab paper I quoted above, Spt4/5 is called a "transcription elongation factor".

Then, for Spt6, here are what it is called in 3 papers that come up near the top of a PubMed search:
Wang AH, Juan AH, Ko KD, Tsai PF, Zare H, Dell'Orso S, Sartorelli V. The
**Elongation Factor Spt6** Maintains ESC Pluripotency by Controlling Super-Enhancers
and Counteracting Polycomb Proteins. Mol Cell. 2017 Oct 19;68(2):398-413.e6. doi:
10.1016/j.molcel.2017.09.016. Epub 2017 Oct 12. PubMed PMID: 29033324.

Jeronimo C, Robert F. **Histone chaperones FACT and Spt6** prevent histone
variants from turning into histone deviants. Bioessays. 2016 May;38(5):420-6.
doi: 10.1002/bies.201500122. Epub 2016 Mar 15. PubMed PMID: 26990181.

Jeronimo C, Watanabe S, Kaplan CD, Peterson CL, Robert F. The **Histone
Chaperones FACT and Spt6** Restrict H2A.Z from Intragenic Locations. Mol Cell. 2015
Jun 18;58(6):1113-23. doi: 10.1016/j.molcel.2015.03.030. Epub 2015 May 7. PubMed
PMID: 25959393; PubMed Central PMCID: PMC4475440.

Again, I would not call use the term "processivity factor" for things that are called "transcription elongation factors" in the literature.

**Comment by thomaspd** [comment]
I would suggest resurrecting an obsoleted term: transcription elongation regulator activity to cover this, and rename it to transcription elongation factor activity to be consistent with the GO macromolecular complex term.

**Comment by pgaudet** [comment]
Definition: "A molecular function that regulates transcriptional elongation, by enabling the transition from transcription initiation to elongation. Elongation regulators stimulates precursor-mRNA capping by recruiting of the mRNA capping enzymes, and enables promoter-proximal pausing of the RNA polymerase." 
I will get that checked by Colin, Astrid and Marcio.

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/16058

**Comment by krchristie** [comment]
I think this definition is not broad enough. Enabling the transition from initiation to elongation is the function of some elongation factors, but not all. There are elongation factors that affect the elongation properties of the enzyme only during the elongation phase, e.g. to help the enzyme get past things that can cause it to pause. 

Something like this would be more inclusive:
A molecular function that regulates transcriptional elongation by enabling the transition from transcription initiation to elongation or by altering the elongation properties of the enzyme during the elongation phase of transcription.

This sentence needs some help. 
> Elongation regulators stimulates precursor-mRNA capping by recruiting of the mRNA capping enzymes, and enables promoter-proximal pausing of the RNA polymerase."

As written, it seems to be implying that all elongation regulators do this which I think is not what you mean. There is also a plural subject/singular verb mismatch (regulators stimulates). I also wonder if recruiting the mRNA capping enzymes is really a **regulation** of elongation, or a step that when it fails causes a defect in elongation because a mandatory, but unregulated step, was missed in the initiation/elongation transition.

Could you please provide the source references for this def.

**Comment by pgaudet** [comment]
Hi @krchristie 
Thanks for the feedback. After discussion with Colin, I used the sentence you proposed and I removed the second part about the capping - Colin agrees that this is too narrow. 

Thanks, Pascale

**Comment by pgaudet** [comment]
After discussion with @ValWood and @colinlog 

- [ ] change term label from 'transcription elongation regulator activity' to 'transcription elongation factor activity'
- [ ] Change def from "A molecular function that regulates transcriptional elongation by enabling the transition from transcription initiation to elongation or by altering the elongation properties of the enzyme during the elongation phase of transcription."
 to 
"A molecular function that stimulates the elongation properties of the RNA polymerase during the elongation phase of transcription. A subclass of transcription elongation factors enable the transition from transcription initiation to elongation, while another class rescue stalled RNA polymerases."


Thanks, Pascale

**Comment by pgaudet** [comment]
and change parent from 'regulation of transcription, DNA-templated' to part of 'DNA-templated transcription, elongation'
