### ISSUE TITLE
telomere tethering/clustering updates

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14409]
GO:new mitotic telomere clustering at the mitotic nuclear envelope
proposed def
The process in which  the telomeres are gathered together to a small number of  foci per chromosome (usually one per chromosome or fewer) , and moved to and tethered at the nuclear periphery, as part of a mitotic cell cycle.
---GO:New mitotic telomere clustering during interphase
The process whereby the mitotic telomeres are gathered together  during, or prior to 
attachment to the nuclear envelope. 
COMMENT It is likely that both intra chromosome  telomere clustering and inter-chromosome occur because a single foci is sometimes observed, although this has yet to be proven).
---GO:0044820 mitotic telomere tethering at nuclear periphery

PMID:25778919 can be added to old and new terms

**Comment by ukemi** [comment]
Can we get a publication that supports these changes?

**Comment by ValWood** [comment]
The existing publications should do it.
Its really a missing piece of information ....

**Comment by ValWood** [comment]
Only used by PomBase so far. The telomeres are "clustered together" and "tethered" but most people call it "clustering".

The existing "tethering" name should be  a synonym.

**Comment by ValWood** [comment]
The new mitotic def is more closely aligned with hte meiotic def. It doesn't change the meaning but it is a bit more detail about the process.

**Comment by ValWood** [comment]
Actually it is a bit more complicated. It seems to be a 2-step process

For  the entire process "clustering" the  the individual letomeres are associated with each other AND the resulting clusters are 'tehtered" to the nuclear envelope.

We have papers which specifically dissect the "tethering " step  and the dissociation step 
for example cdc2 phosphorylation of rap1  promotes dissociation (-ve reg of tethering)
e.g.
Telomere-nuclear envelope dissociation promoted by Rap1 phosphorylation ensures faithful chromosome segregation.  PMID:22959349

The clustering together is also likely multistep because there is the clustering of non-homologous chromosomes and the clustering of sister chromatids (cohesin dependent).

These seem to be separable processes, because telomeres can remain attached to the nuclear envelope but unclustered in some mutants.

Here is a very nice fig from the paper I am reading: 
PMID:25778919
Aurora B prevents chromosome arm separation defects by promoting telomere dispersion and disjunction.

![illustrated](https://user-images.githubusercontent.com/7359272/31909869-72a7e1a2-b833-11e7-8e45-105d645a5bae.jpg)


So, keep the existing terms, but please instead make the term
GO:0044820 mitotic telomere clustering at nuclear periphery
The process in which * the telomeres are gathered together and tethered at the nuclear periphery*, as part of a mitotic cell cycle.

and add the telomere organization  parent to this term instead.

Also still add the telomere organization terms to the similar meiotic telomere clustering parent.

and add this ref to the new term.

Sorry about that!

**Comment by ValWood** [comment]
I revised the original request. I hope this is clear!

Thanks

Val

**Comment by krchristie** [comment]
I'm find this thread a bit difficult to follow @ValWood.  Below is what I think you are asking for, along with places where I have comments or questions:

_**Proposed new terms:**_
**Term**: mitotic telomere clustering at the ~~mitotic~~ nuclear envelope (GO:new) 
`1. I assume second use of "mitotic" from term name is unnecessary`
`2. Can we use the phrase "nuclear periphery", like all of the existing terms, instead of "nuclear envelope"?`
**Def**: The process in which the telomeres are gathered together to a small number of foci per chromosome (usually one per chromosome or fewer), and moved to and tethered at the nuclear periphery, as part of a mitotic cell cycle.
**def dbxref:** PMID:25778919
**is_a:** ??? `seen note 1 below`

**Term**: mitotic telomere clustering during interphase (GO:new)
**Def**: The process whereby the mitotic telomeres are gathered together during, or prior to
attachment to the nuclear envelope.
**def dbxref:** PMID:25778919
**Comment**: It is likely that both intra chromosome telomere clustering and inter-chromosome occur because a single foci is sometimes observed, although this has yet to be proven.
**is_a:** ??? `seen note 1 below`

**Note 1**  `It looks like might be good to have a grouping term for "telomere clustering" to be the parent of both of these two terms, thoughts?`

_**Edits to existing terms:**_
**Term**: mitotic telomere tethering at nuclear periphery (GO:0044820)
**Add def dbxref:** PMID:25778919 can be added to old and new terms

**_Further questions:_**

Here's the current structure:
<pre>
- telomere localization
-- meiotic telomere clustering [GO:0045141]
--- meiotic telomere tethering at nuclear periphery [GO:0044821]
</pre>
**Question 1:** If I'm understanding what you've put in this ticket, it seems you are saying that clustering and tethering are independent of each other. Thus, I am wondering if tethering is really a type of clustering, i.e. should GO:0044821 be an is_a child of GO:0045141?
**Question 2**: Considering the def specifies that this occurs at the nuclear envelope, should GO:0045141 be called "meiotic telomere clustering **_at nuclear periphery_**" like all the other terms in this area?

**Comment by ValWood** [comment]
> 1. I assume second use of "mitotic" from term name is unnecessary
Yes, better
> 2. Can we use the phrase "nuclear periphery", like all of the existing terms, instead of "nuclear envelope"?
Yes, better


> Note 1 It looks like might be good to have a grouping term for "telomere clustering" to be the parent of both of these two terms, thoughts?

GO:NEW1 mitotic telomere clustering at nuclear periphery
parent of 


—GO:New2 mitotic telomere clustering during interphase (part_of GO:NEW1, is_a telomere localisation)  
- GO:0044820 mitotic telomere tethering at nuclear periphery (part_of GO:NEW1 is_a telomere localisation)

It is a bit clunky, but currently I can't find a phrase  which means "telomere clustering and tethering at  the nuclear periphery) which is what is covered by  GO:NEW1 
(maybe we need to be this explicit?)

Unfortunately in the literature some people call the entire process "clustering" and some "tethering", now partially dissected there seem to be a number of things going on simultaneously, but they are separable in mutants where you can see one and not the other...

so the relationship of  GO:New2 and  GO:0044820 to GO NEW1 is part_of


Does that help.

Sorry it was so confusing, I had to piece together in stages...

**Comment by krchristie** [comment]
Thanks @ValWood - Now that I think I understand what you'd like, I do think it is clearer if the grouping term name includes "clustering and tethering. In the stanzas that I've written out below with what I plan to put in, I've highlighted that possible addition, but let me know if you disagree. Please let me know if I've misunderstood anything.

_**Proposed new terms:**_
**Term**: mitotic telomere clustering `and tethering??` at the nuclear periphery (GO:new1) 
**Def**: The process in which the telomeres are gathered together to a small number of foci per chromosome (usually one per chromosome or fewer), and moved to and tethered at the nuclear periphery, as part of a mitotic cell cycle.
**def dbxref:** PMID:25778919
**is_a:** telomere localisation

**Term**: mitotic telomere clustering during interphase (GO:new2)
**Def**: The process whereby the mitotic telomeres are gathered together during, or prior to
attachment to the nuclear envelope.
**def dbxref:** PMID:25778919
**Comment**: It is likely that both intra chromosome telomere clustering and inter-chromosome occur because a single foci is sometimes observed, although this has yet to be proven.
**is_a:** telomere localisation
**part_of:** mitotic telomere clustering `and tethering??` at the nuclear periphery (GO:new1)

_**Edits to existing terms:**_
**Term**: mitotic telomere tethering at nuclear periphery (GO:0044820)
**Add def dbxref:** PMID:25778919 can be added to old and new terms
**Add part_of:** mitotic telomere clustering `and tethering??` at the nuclear periphery (GO:new1)

**Comment by krchristie** [comment]
Also, looking at this new structure for the mitotic telomere clustering, I was wondering if the terms for "meiotic telomere clustering" should be follow a similar structure (which would require a new term).

**Comment by ValWood** [comment]
Hi Karen, 
That's perfect. 

I think we could leave  "meiotic telomere clustering" for now. I was thinking about this but it is quite different. Although the telomeres cluster close to the nuclear envelope in meiotic prophase I, I don't think they can be attached  to the nuclear envelope, but rather to the spindle pole body. In pombe the spindle pole body oscillates rapidly from on side of the cell to the other and   the chromosomes follow (horsetail movement).
I'll be doing more papers in this area at some point so I can clarify then...

**Comment by krchristie** [comment]
Hi @ValWood 
Sounds good. I'll put in the two new terms and term edit as I indicated above (with the "clustering and tethering" phrase in the new1 term name.

We'll leave any changes in the meiotic telomere clustering for the time being.
