### ISSUE TITLE
Wrong parent/child relationship for GO:0001190 - transcriptional activator activity, RNA polymerase II transcription factor binding

### ISSUE THREAD

**Issue by ggeorghiou** [geneontology/go-ontology#14412]
Hi all,

While curating a paper yesterday I stumbled across this rather interesting relationship for GO:0001190 - transcriptional activator activity, RNA polymerase II transcription factor binding where it is the direct child of GO:0098811 - transcriptional repressor activity, RNA polymerase II activating transcription factor binding (https://www.ebi.ac.uk/QuickGO/term/GO:0001190). Looking at the history of changes of the term, the relationships to this term were changed back in 2015. Any chance someone can take a look and fix this?

Best,

George

**Comment by dosumis** [comment]
This appears to be asserted, rather than inferred, but there are also mistakes in the formal def of this and related terms that could cause some nasty wrong inference around this term:

This formal definition makes no mention of positive regulation:

![image](https://user-images.githubusercontent.com/112839/31936192-cbabe2ce-b8a8-11e7-98cd-246f58d51351.png)

Repressor term looks better but uses a different pattern:

![image](https://user-images.githubusercontent.com/112839/31936240-eaae2538-b8a8-11e7-9fc5-ddf448710bef.png)

Patterns need to be made consistent throughout this branch (see my branch edit for how this could work).  For now I'd suggest using a formal def for this term that parallels the formal def of the repressor term.

**Comment by pgaudet** [comment]
Hi @dosumis 
When I remove the asserted Subclass 'is_a: GO:0098811 ! transcriptional repressor activity, RNA polymerase II activating transcription factor binding' this incorrect relation seem to go away. 

Hopefully that worked. 

Thanks, Pascale

**Comment by dosumis** [comment]
You really should correct the logical def too.  It is wrong and as it is likely to cause incorrect inference at some point.

I'd just use this - changing to part of  some 'positive regulation of transcription...'

https://user-images.githubusercontent.com/112839/31936240-eaae2538-b8a8-11e7-9fc5-ddf448710bef.png

**Comment by pgaudet** [comment]
-intersection_of: regulates GO:0006366 ! transcription from RNA polymerase II promoter
+intersection_of: part_of GO:0045944 ! positive regulation of transcription from RNA polymerase II promoter

Is that OK @dosumis ? 

Thanks, Pascale
