### ISSUE TITLE
ntr: protein localization by the NVT pathway/ author request

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14453]
The author has requested the following term:

PMID:26365378
--
Title | ESCRTs Cooperate with a Selective Autophagy Receptor to Mediate Vacuolar Targeting of Soluble Cargos.

new GO process term
protein localization by the NVT pathway
Definition:
A pathway targeting soluble cytosolic proteins to the vacuole lumen. It uses a selective autophagy receptor protein Nbr1, which is an ortholog of mammalian NBR1, and is remotely related to S. cerevisiae Cvt pathway receptor protein Atg19. Similar to the Cvt pathway, the cargos transported by this pathway are hydrolases, which presumably contribute to the hydrolytic activities in the vacuole lumen. Different from the Cvt pathway, this pathway does not require the macroautophagy machinery, but instead relies on the ESCRT machinery for cargo sequestration. This pathway is observed in the fission yeast S. pombe. PMID:26365378

This is analogous to GO:0032258 (protein localization by the Cvt pathway). Like GO:0032258, it should be a child term of GO:0072665 and GO:0061919

**Comment by ValWood** [comment]
This might not be allowed but hopefully the autophagy working group can tell me what the term should be. I can see the author has requested this because human and pombe Nbr1 appear to be orthologs of the CVT receptor ATG19?

seems reasonable looking at current children:
https://www.ebi.ac.uk/QuickGO/term/GO:0072665

**Comment by krchristie** [comment]
@ukemi - As you've worked on autophagy, do you have any objections to Val's term request?

@ValWood - Since the term name is using something that appears to be an acronym, i.e. NVT, could you provide a synonym which expands this out.

**Comment by ValWood** [comment]
Nbr1-mediated vacuolar targeting (NVT)

I'm guessing that part of the issue was that 

cytoplasm-to-vacuole targeting
is an exact synonym of
GO:0032258    protein localization by the Cvt pathway

and this term is clearly not appropriate for non cerevisiae.

(I don't  know if we want to call it  "transport"......  that would seem to be more precise than "localization" based on the definitions)


GO:0032258  CVT: Atg11 binds to Atg9 and **transports** the Cvt complex to the pre-autophagosome 

and above "Similar to the Cvt pathway, the cargos transported by this pathway are hydrolases,"

**Comment by ukemi** [comment]
I don't have any objection, but it seems that this pathway is not related to autophagy. So it should have different parentage.

**Comment by krchristie** [comment]
@ukemi - It is true that the authors say that the NVT:
 `pathway does not require the macroautophagy machinery, but instead relies on the ESCRT machinery for cargo sequestration`. 
However, they also say that: 
`uses a selective autophagy receptor protein Nbr1, which is an ortholog of mammalian NBR1, and is remotely related to S. cerevisiae Cvt pathway receptor protein Atg19`
Do you feel that usage of a selective autophagy receptor is NOT sufficient to use the parentage of:
**GO:0061919 - process utilizing autophagic mechanism**


**Term**: protein localization by the NVT pathway
**Definition**: A pathway targeting soluble cytosolic proteins to the vacuole lumen. It uses a selective autophagy receptor protein Nbr1, which is an ortholog of mammalian NBR1, and is remotely related to S. cerevisiae Cvt pathway receptor protein Atg19. Similar to the Cvt pathway, the cargos transported by this pathway are hydrolases, which presumably contribute to the hydrolytic activities in the vacuole lumen. Different from the Cvt pathway, this pathway does not require the macroautophagy machinery, but instead relies on the ESCRT machinery for cargo sequestration. This pathway is observed in the fission yeast S. pombe. 
**Def dbxref**: PMID:26365378
**Exact synonym**: protein localization by the Nbr1-mediated vacuolar targeting pathway
`proposed` **Broad synonym**: cytoplasm to vacuole targeting
`proposed` **Broad synonym**: cytoplasm-to-vacuole targeting 
**is_a**: GO:0072665 - protein localization to vacuole
`TBD` **?? is_a**: GO:0061919 - process utilizing autophagic mechanism **??** 

It also seems like the two existing **EXACT** synonyms of "protein localization by the Cvt pathway":
- cytoplasm to vacuole targeting
- cytoplasm-to-vacuole targeting

should become **BROAD** since they are equally appropriate to the NVT pathway, and also be added to the Nvt pathway term.

**Comment by ValWood** [comment]
I think that using the same receptor  doesn't make it a process utilizing autophagic mechanism.

**Comment by krchristie** [comment]
Works for me. I think this is settled then, so I'll put in this stanza with everything else and also change the synonym type for the two existing synonyms of the Cvt pathway term.

**Comment by ukemi** [comment]
I agree. I think the mechanism would be more than just the receptor. If at some point the community would like us to reclassify, we will.
