### ISSUE TITLE
Fix logical definition of symporters

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14570]
Symporters transport two substances in the same direction, so the current logical definition is incorrect: 

'symporter activity'
 and (imports some  %s)
 and (exports some %s)

**Comment by pgaudet** [comment]
According to https://en.wikipedia.org/wiki/Symporter
Symporters cotransport two substances across a membrane; but we cannot easily use import/export because we first need to know for each transporter if they import or export. 

Also if some are not on the plasma membrane then the use of import and export becomes very ambiguous. 

@thomaspd @amandamackie - or anyone else .. Do you have suggestions about this one? 

Thanks, Pascale

**Comment by amandamackie** [comment]
I'm not familiar with the syntax of the logical def for symporters so don't fully understand the problem you have raised but can I add the following: 
symporters use ion gradients to energize transport and so can act as importers and/or exporters; the 'substrate:H+ symporters' in bacteria are typically importers because the H+ gradient is directed inwards but there are 'sugar:H+ symporters' in plants that export sugar from the vacuole where the H+ gradient is directed out;
membranes define compartments so import/export refers to movement into or out of the compartment respectively.

**Comment by pgaudet** [comment]
Thanks @amandamackie, this is very helpful.

**Comment by pgaudet** [comment]
We need to be able to describe cases where both substances start from the same side of the membrane (symport) versus when they start from opposite sides (antiport). 

Right now the use of 'import' and 'export' in the logical definitions is misleading because it implies that we know the directionality; but we don't, we only know that substances are co-transported (or not). 

Pascale

**Comment by pgaudet** [comment]
Editors discussion Feb 5, 2018: 

Try this: 
'symporter activity'
and ('transports or maintains location of' some %s)
and ('transports or maintains location of'  some %s)

**Comment by pgaudet** [comment]
* GO:0022820 potassium ion symporter activity-> only used for potassium:chloride ion symporter activity; rename and add logical definition
