### ISSUE TITLE
Obsolete GO:0005430 synaptic vesicle amine transmembrane transporter activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14584]
Dear all, 

The proposal has been made to obsolete  'GO:0005430 synaptic vesicle amine transmembrane transporter activity ’. 

The reason for obsoletion is that this the cellular location of a function should not be part of the term name. We propose replacing the annotations by the parent 'GO:0005275 amine transmembrane transporter activity’- 

There are 4 EXP annotations by FlyBase. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on Nov 23, 2017. Unless objections are received by Nov 23, 2017, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@hattrill

**Comment by BarbaraCzub** [comment]
Hi @pgaudet 

I am not sure about this. What if the curvature of the synaptic vesicle membrane is necessary for the  'GO:0005430 synaptic vesicle amine transmembrane transporter activity’ to be able to occur? 

Then, if you expressed a protein, which has this specific activity, in a membrane, which is not curved (or not to such a degree as the synaptic vesicle membrane is), then you would lose this activity. 

This is _purely hypothetical_, but I think the type of environment that is necessary for an activity to happen should not be disregarded. There are proteins, which preferentially bind to curved membranes (e.g. #13916), so I think we should not exclude the possibility that there will be proteins, which will be active only in curved membranes. I do not know whether this is true for the proteins annotate by Flybase, but it may as well be.

So I would be very reluctant to obsolete this and lose the extra specificity that the 'synaptic vesicle' part of this term adds.

Thanks,
Barbara

**Comment by thomaspd** [comment]
We can't make terms based on hypothetical functions, only ones that have been experimentally supported.

If we want to specify that a function occurs in the synaptic vesicle membrane, that's what CC annotations are for.  To express the combination of function and location, the ontology can't support all possible combinations.  But you can combine them in an annotation, either with a simple GO-CAM annotation, or using extensions.

**Comment by hattrill** [comment]
All knocked back to parent MF. There is a BP that covers this aspect sufficiently for me.

**Comment by BarbaraCzub** [comment]
Hi @thomaspd , I agree we cannot make terms based on hypothetical functions. I meant that my comment was only hypothetical, because I was not familiar with the experimental details supporting the current  annotations to this term (now previous, since @hattrill moved them). I was just thinking that if an activity was shown to occur in a curved membrane, but not a flattened one (or the opposite), this might be an important distinction to keep. But of course only if there was experimental evidence for this distinction. And then I suppose it would not be the case of a parent-child relation between the terms, but they would probably be more like 'siblings'.
