### ISSUE TITLE
query part_of links for epsilon DNA polymerase complex

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#14691]
id: GO:0008622
name: epsilon DNA polymerase complex
relationship: part_of GO:0000109 ! nucleotide-excision repair complex
relationship: part_of GO:0043601 ! nuclear replisome

I don't think both part_of links can qualify as always true.

Any instance of a DNA pol epsilon complex that is located in a replisome, and carrying out DNA replication (mainly leading strand synthesis) is not engaged in DNA repair, and is not part of a repair complex. I don't know as much about the NER complex(es) that contain pol epsilon and how they relate to the replisome, but the part_of nuclear replisome may also need to be reviewed.

I think it would be safe to say nuclear replisome has_part epsilon DNA polymerase complex.

(this may have been flagged way back in #1577, but the ticket was closed as out of date)

**Comment by krchristie** [comment]
I am inclined to agree with @mah11 that it is unlikely that both part_of relationships can always be true.

I was initially thinking that I agreed with Midori that `it would be safe to say nuclear replisome has_part epsilon DNA polymerase complex.`
- but now I am not so sure as the more recent of the two reviews cited in the def of the term (Garg & Burgers. 2005. DNA polymerases that propagate the eukaryotic DNA replication fork. Crit Rev Biochem Mol Biol. PMID:15814431) indicates uncertainty about whether DNA pol epsilon is ALWAYS part of the replication fork. 
- Even looking at a more recent review (Burgers & Kunkel. 2017. Eukaryotic DNA Replication Fork. Annu Rev Biochem. PMID: 28301743) which says this: `Collectively, these results strongly suggest that in undamaged yeast cells, the leading strand is **primarily** replicated by Pol ε,` I am a little hesitant to make the has_part relationship.

Regarding the other term that "epsilon DNA polymerase complex" currently has a part_of relationship to, i.e. GO:0000109 ! nucleotide-excision repair complex, I see two problems with making the has_part relationship:
- The term `GO:0000109 ! nucleotide-excision repair complex` is a grouping term for a number of specific nucleotide-excision repair complexes. I doubt we would want to say that ALL nucleotide-excision repair complexes have DNA pol epsilon as a part.
- I'm not even sure we want to make any relationship between nucleotide-excision repair complexes and DNA pol epsilon. I just skimmed through this very recent paper from April 2017 (https://www.ncbi.nlm.nih.gov/pubmed/28265089) and it doesn't seem that we really know exactly what the involvement of of DNA pol epsilon in excision repair is, nevermind whether it is a part of some specific nucleotide-excision repair complex.

Thus, I question whether either the part_of or has_part relationships are always true. @ukemi thoughts?

**Comment by ukemi** [comment]
If you use either has_part or part_of, they always have to be true. So if A part_of B, then any time there is an instance of A it has to be a part of some instance of B. If A has_part B, then any time there is an instance of A, it has to have a part that is B. 
Reading your comments above, it seems that if you want some type of relationship between DNA pol epsilon and the other terms, the safest route would be to create specific type of DNA pol epsilon. This would only be worthwhile if you felt a need to distinguish them in the ontology at the class level. It is always possible to put those relationships in a model and get the complete annotations as output.

**Comment by krchristie** [comment]
Yes, I do understand that use of either has_part or part_of means they always have to be true, and I have my doubts that this is the case.

I utterly despise making specific type terms for when a complex is in one "macrocomplex" versus another. I also do not, personally, feel a need to distinguish DNA pol epsilon when it is present in a nuclear replisome versus when it is involved in DNA repair, where what complex it might be part of is not clear from my reading so far, which makes it hard to even make a term for the complex it would be part of during this role.

@mah11 - would you be satisfied with with just removing the offending part_of relationships and NOT replacing them with any has_part relationships?

**Comment by cmungall** [comment]
A general point, sorry if it's a bit tangential

Historically we might have done something like make a new class "epsilon DNA polymerase complex in nuclear replisome" or more generally "P and part-of some W" when we are not confident to make a P SubClassOf part-of some W. But this is really just a named proxy for a some-some relationship. We didn't have another way of doing some-some. I still maintain the has-part is useful but not as generally useful for typical GO user.

Now we have Noctua and can make at least a minimal gocam where we describe the existence of a eDpc that is part of a nr, and potentially describe what it is doing while it is there

**Comment by krchristie** [comment]
@cmungall - Yes, we have made those types of terms a few times, but I do not think we have been consistent about always making these types of terms. I am not keen to make more of them because as an annotator I find them terrible. I think they could produce more clutter than utility if you end up annotating all of the gene products of a "core" complex to both of the "and part_of some W" terms. 

Looking at an example I am familiar with, these three terms:
-- core TFIIH complex (GO:0000439)
--- core TFIIH complex portion of the holo TFIIH complex (GO:0000438)
--- core TFIIH complex portion of the NEF3 complex (GO:0000440)
It doesn't seem like use of these "portion of" terms have been very popular. 
Of the 20 experimental annotations, only 3 are to the "portion of the holo TFIIH complex" term, while the remaining 17 are to the more general term "core TFIIH complex". Of the four groups that have made experimental annotations, only UniProt has chosen the "portion of the holo TFIIH complex" term, based on AmiGO: http://amigo.geneontology.org/amigo/term/GO:0000439 

While I was definitely involved in coming up with this "solution" for the TFIIH core complex, and am probably the person who put these two "portion of" terms in, I just do not think that this is a good solution. The core TFIIH complex is exactly the same regardless of which situation it is present in, so "complete" annotation of the gene products present in the core would mean double annotating every gene with both terms. I don't think these terms are intuitive for biologists or annotators. I am not in favor of making more of them.

**Comment by mah11** [comment]
quoth @ukemi
> If you use either has_part or part_of, they always have to be true.

Like Karen, I have long understood this. It's on the biology where we sought input.

quoth @krchristie 
> @mah11 - would you be satisfied with with just removing the offending part_of relationships and NOT replacing them with any has_part relationships?

Yes. I wasn't aware of the exception, i.e. the reports of instances of nuclear replisomes that don't include pol epsilon. In light of their existence, that has_part link is no good.

I didn't and wouldn't ever suggest adding the link nucleotide-excision repair complex has_part pol epsilon, because I was aware of at least some of the points Karen makes.

I'm hereby opting out of the tangent on complexes, subtypes of complexes, and GO-CAMs ;)

**Comment by krchristie** [comment]
removed part_of relationships without any replacement relationships
