### ISSUE TITLE
Rename 'transcription factor activity, core RNA polymerase I binding' to 'RNA polymerase I transcription initiation factor activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14736]
Rename 'GO:0001181 transcription factor activity, core RNA polymerase I binding' 
-> general RNA polymerase I cofactor activity

and move under transcription cofactor activity. 
- Single EXP annotation to RRN3 : RRN3 is the functional equivalent of 'Mediator' for pol1, see https://www.yeastgenome.org/reference/S000146964
- 2 IC annotations: yeast SPT4 and SPT5 (to be reviewed)

Thanks, Pascale

**Comment by pgaudet** [comment]
Definition as agreed with Colin Logie from GREEKC: 
Integrator of signals between enhancers and the RNA polymerase I general transcriptional machinery that assembles at promoters as the preinitiation complex (PIC) to control transcription initiation. General cofactors are required by most genes for efficient transcription initiation.

**Comment by pgaudet** [comment]
Discussed at Dec 18 ontology editors's call: suggestion to make the definition more 'function-like': 

How about: 
Bridging promoter cis-regulatory elements with the RNA polymerase I general transcriptional machinery that assembles at promoters as the preinitiation complex (PIC) to control transcription initiation. General cofactors are required by most genes for efficient transcription initiation. The most common general cofactor for RNA polymerase II is the mediator complex. 

@krchristie 
@tberardini 
@thomaspd 
@ukemi 
@hdrabkin 

Hoes does that sound ? 

Thanks, Pascale

**Comment by krchristie** [comment]
I am concerned that use of the word "general transcription factor" in the context of RNAP I is artificial and will be confusing since I have never seen the word "general transcription factor" used for anything other than RNAP II. Unless the literature has changed significantly, and the word "general" is now used in the literature for RNAP I, I am against artificially applying this word to RNAP I.

I think that trying to standardize use of the word "general transcription factor" in this way is similar to what we were recently talking about with respect to "biogenesis" where Midori tried to standardize "biogenesis" versus "assembly", but in retrospect, it turned out to be confusing because the GO use of the words were inconsistent with usage in the literature.

**Comment by pgaudet** [comment]
Hi @krchristie 

I think this terminology is pretty standard, see 
https://en.wikipedia.org/wiki/General_transcription_factor
PMID:25693126
PMID: 27816209

Would it be clearer if we phrased it as 'general transcription initiation factor activity'?

Thanks, Pascale

**Comment by pgaudet** [comment]
This is the name of the protein (at least as annotated in UniProt for human) - http://www.uniprot.org/uniprot/Q9NYV6
RNA polymerase I-specific transcription initiation factor RRN3

Thanks, Pascale

**Comment by krchristie** [comment]
Both of the PMIDs you cite are specific to RNAP II:

- PMID:27816209: Zabidi MA, Stark A. Regulatory Enhancer-Core-Promoter Communication via
Transcription Factors and Cofactors. Trends Genet. 2016 Dec;32(12):801-814.  Review.  
- PMID:25693126: Sainsbury S, Bernecky C, Cramer P. Structural basis of transcription
initiation by RNA polymerase II. Nat Rev Mol Cell Biol. 2015 Mar;16(3):129-43.
doi: 10.1038/nrm3952. Epub 2015 Feb 18. Review.

The Wiki page you cite is also almost entirely about RNAP II, with a brief mention of bacteria, and while it is true that the [unknown] wiki author refers to sigma as a GTF, I have never seen any bacterial transcription researchers refer to sigma as a GTF.

The name of the RNAP I transcription factor that you are trying to rename also does NOT call it a "general transcription factor".

I do not think any of the things you have cited support the contention that the use of the word "general" is appropriate for anything except RNAP II.

**Comment by ValWood** [comment]
just call it "RNA polymerase I cofactor activity"?

**Comment by krchristie** [comment]
or drop the gene name RRN3 off of UniProt's name for RRN3 and call it something like "RNA polymerase I-specific transcription initiation factor"

**Comment by pgaudet** [comment]
How about "RNA polymerase I promoter selection activity"? This is how we named the parent of sigma factors, so it would be consistent with that. 

Thanks, Pascale

**Comment by krchristie** [comment]
It doesn't seem like RRN3 is comparable to sigma factors since it doesn't seem to recognize the DNA itself, nor is this nomenclature used in the RNAP I literature, so misappropriating this bacterial terminology for RNAP I seems contrary to your goal of using term names more comprehensible for curators & users.

**from intro of**: Sadian Y, et al. **Structural insights into transcription initiation by yeast RNA polymerase I**. EMBO J. 2017 Sep 15;36(18):2698-2709. PMID: 28739580

For initiating rRNA synthesis, yeast Pol I uses a unique set of transcription factors: Upstream Activating Factor (UAF), TATA‐binding protein (TBP), Core Factor (CF), and Rrn3 (Keener et al, 1998). 
- UAF and TBP bind to the upstream promoter and have only a stimulatory effect in vitro (Keener et al, 1998), 
- while CF, composed of Rrn7, Rrn6, and Rrn11, binds to the core promoter element (−38 to +5; Kulkens et al, 1991; Meier & Thoma, 2005) and is essential for the basal level of transcription (Keener et al, 1998).  [snip details of CF subunits]
- **Rrn3 stabilizes the monomeric form of Pol I and interacts with CF to position Pol I on the rDNA promoter thereby promoting the formation of a productive Pol I PIC** (Bedwell et al, 2012). 
- Altogether, the minimal Pol I PIC (comprised of Pol I, Rrn3, and CF) is equipped with the necessary elements for promoter‐dependent transcription, namely start site selection, DNA melting, and promoter escape.

**Comment by pgaudet** [comment]
**Changed label:** 
OLD name: transcription factor activity, core RNA polymerase I binding
NEW name: RNA polymerase I transcription initiation factor

**Changed definition:** 
OLD def: "Interacting selectively and non-covalently with an RNA polymerase I (RNAP I) complex, typically composed of fourteen subunits, in order to modulate transcription. A protein binding transcription factor may or may not also interact with the template nucleic acid (either DNA or RNA) as well." [GOC:txnOH]
NEW def: "Interacting selectively and non-covalently with an RNA polymerase I (RNAP I) complex and stabilizing it in an active form. The active form of RNAP I, also bound to the core factor (CF), intiates transcription." [GOC:txnOH-2018, PMID:28340337, PMID:28842442]

**ADDED comment: **
In yeast and mammalian cells, this activity is mediated by the RRN3 protein. 

**Changed synonym types to BROAD**
As the Core Factor also binds the polymerase
 synonym: "core RNA polymerase I binding transcription factor activity" BROAD []
synonym: "transcription factor activity, core RNA polymerase I binding" BROAD []

**Comment by pgaudet** [comment]
Still need to change parent to 'general transcription factor activity' - depends on merge of #15706
