### ISSUE TITLE
ntr: regulation terms for ubiquitin-dependent protein catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14746]
for

GO:0006511 | ubiquitin-dependent protein catabolic process

(i'm sure they existed?, maybe not...)

**Comment by pgaudet** [comment]
Hi @ValWood 
We discussed something related in here #14030 

The closest term we have right now is 
'GO:2000058 regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process'

This term is a compound term of a molecular function and a single-step process (ie essentially two MF described as BP). So if we have the combination of regulation we end up with many terms. I would prefer if we had the regulation of the individual activities. I am not sure what the BP should be. 

Thanks, Pascale

**Comment by ValWood** [comment]
I thought this was going to change to remove the  "protein ubiquitination" part ?

so 
'GO:2000058 regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process'

would become
'GO:2000058 regulation of  ubiquitin-dependent protein catabolic process'

Didn't the none regulation terms get revised?

**Comment by pgaudet** [comment]
Guess not. It was closed as more or less equivalent of #14137
I must have lost track (sorry!) 

We should be careful not to create too many redundant tickets; what would be nice is to merge the discussion and the decision. I need to get back to it, I forgot the conclusion now. 

Pascale

**Comment by vanaukenk** [comment]
@pgaudet 
Let me know if there's anything you'd like me to do here or if I should re-assign the ticket to you.  Thx.

**Comment by pgaudet** [comment]
@vanaukenk I can take the ticket if it's not urgent (I'd do it after xmas). 

Pascale

**Comment by ValWood** [comment]
Not urgent for me...

**Comment by pgaudet** [comment]
Val and I noticed that 'GO:2000058 regulation of protein ubiquitination involved in ubiquitin-dependent protein catabolic process is a child of protein modification, which is incorrect (modification does not include degradation). 

The solution is to 
 [] Merge GO:0042787 protein ubiquitination involved in ubiquitin-dependent protein catabolic process' into 'GO:0006511 ubiquitin-dependent protein catabolic process' 
 [] Rename the respective regulation terms

**Comment by hattrill** [comment]
Hi

**Comment by hattrill** [comment]
@pgaudet 

Rather than a new term, I think groups should have been able to review this before the merge was made. 

Groups may not have made independent annotations to "protein ubiquitination", instead used the parentage of "protein ubiquitination involved in ubiquitin-dependent protein catabolic process", as defined.

**Comment by ValWood** [comment]
Hi @hattrill 

"ubiquitin-dependent protein catabolic process"
was a parent of 
"protein ubiquitination involved in ubiquitin-dependent protein catabolic process"

"protein ubiquitination involved in ubiquitin-dependent protein catabolic process"
describes a MF (ubiquitination), so  "ubiquitin-dependent protein catabolic process" should be all you need? (with the corresponding MF term "ubiquitin ligase" or whatever).

If it is a ubiquitin ligase, it would have the corresponding MF term, and this  has a parent to "protein ubiquitination" so you would already have this "process" (although really "protein ubiquitination" is describing a function, so it isn't really an informative process annotation).

For example, would you annotate a protein kinase as

"phosphorylation involved in  blah"

this is  part of the effort to pull some embedded MF terms out of the process ontology, but  it should not make any annotations less informative?

Do you have an example of annotation loss?

**Comment by hattrill** [comment]
It is not the spirit of the merge that I am debating, but that we probably needed to check our annotations to make sure what the intent was when they were made and to ensure that we'd had a chance to fill any gaps.

**Comment by ValWood** [comment]
In AmiGO, 
http://amigo.geneontology.org/amigo/term/GO:0006511
filter on drosophila,   view only direct annotations  to GO:0006511,  filter IEA and IBA,
you only have 17 annotations to check ;)

**Comment by ValWood** [comment]
You would need to do the same for "regulation" too.

@a heads up for merges would be good though...

**Comment by pgaudet** [comment]
Hi @hattrill 

Apologies if the merge was not sufficiently announced. I was going to respond the same as Val: since we merge into the parent there cannot be any annotation loss. The term was essentially in MF involved in BP perhaps you wanted to check that the MF was also annotated ? 

Do you think we should announce merges on the go-consortium list like we do for obsoletions ? 

Thanks, Pascale

**Comment by ValWood** [comment]
personally I think announcements for term merges would be useful. I always like to double check .

**Comment by hattrill** [comment]
I have none to "change" as the merge was done automatically - AmiGO is just behind.

When there is a substantial change e.g. a link with a branch has gone, or a change to the meaning, we do need to know.
It also helps as we can go back and look at the older annotations to see if they  are a bit rubbish, especially if the change has been made due to a change in thinking/practice.

I keep track of daily digest of tickets, but the titles often don't distinguish minor changes to revisions in the ontology.

So heads-up for merges would be good. Normally a quick glance is all that is needed to decide what we need to do.

**Comment by pgaudet** [comment]
@hattrill I have been trying to save the annotations before such changes to allow to check annotation retroactively if needed, but in this case I haven't done. 

All I can do is to apologize, and propose to change the procedure for announcements. If that's good enough for you please close the ticket ;) 

Cheers, 

Pascale

**Comment by hattrill** [comment]
There's always time for one more moan in the GOC!

Consider it closed!

**Comment by ValWood** [comment]
> I have none to "change" as the merge was done automatically - AmiGO is just behind.

you can still check changes by scanning the annotations to the term now (or did these changes not make it to Amigo yet, that would be odd? 8 days?

**Comment by hattrill** [comment]
I misunderstood the AmiGO pointer -they have been updated.
(I grep'ed them from my last gaf anyhoo)
