### ISSUE TITLE
MP GO:0042026	protein refolding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14752]
should 
GO:0042026	protein refolding

be related to
GO:0071218	cellular response to misfolded protein
(Or does it happen in any other context?)

**Comment by vanaukenk** [comment]
@ValWood 

I don't know if this happens in any other context in vivo, e.g. a properly folded protein is unfolded and then refolded.

The current term definition, however, refers to both unfolded and misfolded proteins:

"The process carried out by a cell that restores the biological activity of an unfolded or misfolded protein, using helper proteins such as chaperones. Source: GOC:mb"

Perhaps this is due to the in vitro assay used to measure the activity of chaperone-type proteins whereby proteins are denatured, by heat, for example, and then refolded in the presence/absence of the chaperone?

GO:0042026 protein refolding does not currently have a relationship to GO:0034620 cellular response to unfolded protein, either.

**Comment by ukemi** [comment]
PMID:29153394

**Comment by ValWood** [comment]
OK not to worry can close, can post compose if required.

**Comment by pgaudet** [comment]
Also - I was looking at this and while proteins do get folded and refolded, the same proteins are involved in both processes (except for the co-translational folding), so the distinction is really related to the assay rather than to the protein's function. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
Okay; I am closing this ticket.  Please re-open if there's anything to do here.
