### ISSUE TITLE
NTR: extracellular digestion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14761]
could we have a term "extracellular digestion"
as a child of digestion?

We would need to lift the taxon constraints, and remove the parentage, so there may need to be a 
split (with the multicellular parentage added to "digestive system".

I have been trying to find a way to group these  processes in fungi and it seems that this is the correct term:
https://en.wikipedia.org/wiki/Extracellular_digestion

**Comment by cmungall** [comment]
Digestion is such a broad term covering such a wide variety of mechanisms that we should always be annotating to more specific terms. But we have a lot of direct annotations to it already which is unfortunate.

It looks like we have a ton of IBAs direct to "digestion" propagated across tetrapods emanating from http://amigo.geneontology.org/amigo/gene_product/RGD:620707 annotation to "maintenance of gastrointestinal epithelium". This just seems weird. Either you make the call that the function of the gene is preserved and use the same term, or don't propagate...?

There are some manual annotations too, e.g IEPs

![image](https://user-images.githubusercontent.com/50745/33853013-4c245a7e-de71-11e7-9d75-a8b1d799a2aa.png)

Surely if you have expression data you should be able to tell more than just "digestion", a term that in a vertebrate encompasses everything from mastication through intestinal absorption.

E.g. in the first ZFIN one https://www.ncbi.nlm.nih.gov/pubmed/15614773 mtp was expressed in enterocytes of the anterior intestine after feeding. I think either we should make a specific annotation to something like intestinal absorption or not make an annotation, but 'digestion' seems too vague to be useful.

back to your request...

Given digestion is already so vague, I don't see a particular problem with putting extracellular digestion under it. But this term is already a bit vague, encompassing one mechanism in saprobionts, another in sea anenomies. And what about venus fly traps. Flies also carry out a portion of the digestive process externally...

Maybe we can come down on a more specific term that is more cellular, e.g. secretion of digestive enzymes through cell membrane?

**Comment by ukemi** [comment]
In mammals digestion is a system process, where different nutrients are broken down in different parts of the system and those nutrients are absorbed in the intestines. For example, starches are partially catabolized by saliva while food is being chewed. Chewing is a part of digestion, although we probably wouldn't annotate a gene product to it. I think a physiologist would also consider moving the food along the digestive tract part of digestion. In mammals, the breakdown is also extracellular. 

I'm not sure how the requested term differs from extracellular 'x' catabolic process. However, if we go that route, we add another complete axis to the catabolism branch. That seems like a bit of a rabbit hole to me. 

I agree with @cmungall, it would be much better to annotate to a more specific term for these kinds of annotations.

**Comment by ValWood** [comment]
I'll explain...I need a term to group all of the extracellular digestive enzymes.

> "Maybe we can come down on a more specific term that is more cellular, e.g. secretion of digestive enzymes through cell membrane?"

...this wouldn't work. The secretory system ( general exocytosis) is causally upstream of the molecules which are secreted, the digestive enzymes are only cargo.

So, the reason I need this is that a lot of gene products are secreted and seem to have a role in this process (proteases, lipases,  amylases,  etc). We have information for some which distinguishes those involved in nutrient assimilation/digestive pathways, and others which are involved in degrading the cell wall after cell separation.  Extracellular catabolic process could work, but we would not be able to distinguish degrading septum, cell wall (during karyogamy for example) or spore wall breakdown from  the "module" which  specifically breaks down nutrients. I think this is a pretty fundamental biological distinction to capture. 

I'm doing a quick exercise where I  look a the processes which are signatures for each cellular component, and for "cell surface/extracellular" we have a  no way to capture the nutrient assimilation "module".

CELL SURFACE 77
9/9			cell-cell adhesion involved in flocculation (GO:0043689)
8/9			ascospore wall (spore assembly/disassembly)
24/25		anchored component of external side of plasma membrane (GO:0031362)
?/?			agglutination involved in conjugation with cellular fusion (GO:0000752)
21/37		fungal-type cell wall (GO:0009277)
3/?			cell septum surface (GO:0043187) (septum degradation)
18/?			extracellular region  (mainly nutrient digestion)
18 to sort


It's necessary because its a neglected area  of biology, and annotation. This is probably  because the gene families are  often rapidly evolving as they don't have the same evolutionary constraints (few interactors), and many  appear to be  conditionally expressed during stress (nutrient limitation), and are never required in glucose fed organisms. A lot of uncharacterised proteins in microbes appear to belong to this genes set.

 So, I think it would be a useful grouping terms for microbes. I'd be happy for an alternative suggestion, but "general  extracellular nutrient catabolism"  or even  "extracellular nutrient aquizition"   is the process I'm trying to represent.
 (extracellular nutrient aquizition would maybe work better because it would allow me to group nutrient sensors under here too) . I could just use digestion, but I'd rather not, it's a bit sub-optimal.

**Comment by krchristie** [comment]
@ValWood - Do you think that "extracellular digestion" is specific enough. The wiki page you cite includes most of the human digestive system as "extracellular digestion" also.

> I have been trying to find a way to group these processes in fungi and it seems that this is the correct term:
> https://en.wikipedia.org/wiki/Extracellular_digestion

**Comment by ValWood** [comment]
I would be very happy with that term, it would be perfect for what I am trying to group!

Val

**Comment by ValWood** [comment]
I was going to group as "digestion" as a stop gap.
However, digestion is defined
The whole of the physical, chemical, and biochemical processes carried out by multicellular organisms to break down ingested nutrients into components that may be easily absorbed and directed into metabolism.

and has taxon constraints.

I guess there should be a species agnostic term which would be the equivalent of what I am requesting above, to represent "catabolism that occurs outside of cells"

The existing terms
lipid digestion
polysaccharide digestion
protein digestion
need a bit of rejigging because they also apply to non-multicellular species

I also need a term for "nucleobase-containing compound digestion"

**Comment by deustp01** [comment]
There are processes in which large molecules are broken down in extracellular spaces within large multicellular organisms - dissolution of fibrin clots, connective tissue remodeling - that fit the differentia above but don't conventionally get labeled as digestive processes.

Maybe more taxon constraints could work here to create an extracellular digestion process that occurs only_in_monocellular_organisms? Or maybe this doesn't help - see Val's comment from 12 Dec - because monocellular organisms also carry out some extracellular processes that involve degrading macromolecules but that are not classified as digestion

**Comment by ValWood** [comment]
Hmm good points.
This is going to become more complicated than I envisaged!

Also need to deal with "systems level digestive processes"  like chewing, peristalsis (although I wonder how many of these broader organism level processes will  accumulate GO annotation in the near future!?).

At present the digestion term appears to be geared towards  the molecular level of "nutrient catabolism  prior to absorption into cell".

**Comment by ukemi** [comment]
My 2 cents. I always considered digestion a physiological process that occurs in multicellular organisms.

**Comment by pgaudet** [comment]
Hi @ValWood 
How about creating 'extracellular catabolic process' as a child of 'catabolic process'? I think Peter is right that 'digestion' would not be very appropriate for unicellulars: 
https://en.wikipedia.org/wiki/Digestion

This may lead to another question - we have a couple of terms, such as 'extracellular polysaccharide biosynthetic/catabolic process'; that mean 'the synthesis/degradation of a polysaccharide that is normally extracellular'; but since these terms have not been used (at least the catabolic process version), we can use it to mean 'extracellular digestion'. 

Would that work ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Well the yeast community does use the term "digestion" but  not a lot, ...so I guess it could continue to be defined in a multicellular specific way in GO and  we could use "extracellular catabolic process".

**Comment by deustp01** [comment]
The problem is that the word digestion has two meanings, one applicable to unicellular organisms and one to multicellular that overlap at the level of role - nutrient acquisition from the external environment - but differ in almost all of their function and process specifics. It's analogous to "respiration", which a general physiologist will tell you means breathing and related processes, and a biochemist will tell you means processes that generate ATP from reduced end-products of catabolism.

**Comment by krchristie** [comment]
I am quite hesitant to just add a term for "extracellular digestion" because this also occurs in multicellular organisms and is therefore not the distinguishing feature that separates digestion in single and multicellular organisms. The wiki page @ValWood linked above describes a subtantial portion of the digestion that occurs in multicellular organisms as extracellular, i.e. almost everything that occurs in the digestive system from the mouth to the stomach to the intestines, there is a whole system of digestion in multicellular organisms that is within the organism but external to its cells, i.e. extracellular. I would really rather avoid this axis of classification of digestion since if GO has a general term for "extracellular digestion", it would imply that we would need to classify which parts of digestion in multicellular organisms occur extracellularly. This seems really hard to do, and I'd rather not go in this direction.


Then, looking at the existing term structure (both part_of and is_a relationships*):
-- **digestion** [defined as specific to **_multicellular_** organisms]
--- [part_of] **digestive system process** [defined wrt **_living_** organisms]
--- [is_a] **lipid digestion** [defined wrt **_living_** organisms]
---- [part_of] **multicellular organismal lipid catabolic process**
--- [is_a] **polysaccharide digestion** [defined wrt **_living_** organisms]
---- [part_of] **multicellular organismal polysaccharide catabolic process**
--- [is_a] **protein digestion** [defined wrt **_living_** organisms]
---- [part_of] **multicellular organismal protein catabolic process**

Although the term "digestion" is currently defined with respect to "multicellular" organisms, the is_a terms below it are defined in terms of "living" organisms. In addition, each of these three "x digestion" terms (where x is a major class of biological molecule) has a more specific term for  "multicellular organismal x catabolic process" below it via a part_of relationship. It seems these wouldn't have been added if people were really thinking of "digestion" as already restricted to multicellular organisms. In this structure, it seems that the inconsistency is the narrow definition of the top level term "digestion" to apply only to multicellular organisms.

Thus, it seems to me that the definition of "digestion" should probably just be broadened from "multicellular" to "living" organisms, as it is a parent term of things that are defined more generally as applicable to "living" organisms.

> **Definition of "digestion"**: The whole of the physical, chemical, and biochemical processes carried out by multicellular organisms to break down ingested nutrients into components that may be easily absorbed and directed into metabolism.



@ValWood - Would just broadening the definition of "digestion" to "living" organisms to be consistent with its child terms make this term sufficient for your use?

**Comment by ValWood** [comment]
yes I think so.

It seems that 

https://www.ebi.ac.uk/QuickGO/term/GO:0022600
digestive system process

is incorrectly defined though (it isn't defined as a system  process, and when it is, it will not sit comfortably under here?)

**Comment by krchristie** [comment]
Going back to an earlier comment in this thread by @cmungall , I am inclined to agree that we might want to consider disallowing annotations directly to the term "digestion". Here are the counts of annotations directly to the term "digestion" by Contributor and Evidence Code as of 2/15/18:

![20180215-digestion-counts-byevcode](https://user-images.githubusercontent.com/10533218/36689483-620b9dca-1ae4-11e8-906e-a0d35b8deca3.jpg)

I have examined both of the MGI ones and was able to annotate to more specific terms. 

In addition, I have examined all of the PINC ones and in many cases was able to annotate the paper experimentally. In other cases, I did not find the annotation to "digestion" to be supported by anything other than very general comments in the abstract or introduction; these I have deleted. Papers which described only cloning and perhaps also tissue level expression patterns have been marked as unsuitable for annotation in Protein2GO. 

I will make an annotation ticket to have the remaining annotations examined by the appropriate groups, but I have a critical deadline on a manuscript revision coming up, so probably won't get to much else on this ticket today.

**Comment by krchristie** [comment]
"digestive system process" is already correctly defined as part_of digestion

![20180215-digestion-childterms](https://user-images.githubusercontent.com/10533218/36689809-60a87f92-1ae5-11e8-8043-86016f2ecc9c.jpg)

**Comment by ValWood** [comment]
Thank's Karen. No huge urgency, I can work around for my stuff. I think it will be useful going forward as this seems to be one of the areas where a number of the "unknowns" will fall.

**Comment by ValWood** [comment]
> "digestive system process" is already correctly defined as part_of digestion

yes but:

digestive system process id defined:
A physical, chemical, or biochemical process carried out by living organisms to break down ingested nutrients into components that may be easily absorbed and directed into metabolism.

system process
A multicellular organismal process carried out by any of the organs or tissues in an organ system. An organ system is a regularly interacting or interdependent group of organs or tissues that work together to carry out a biological objective.


It is  *positioned* correctly but it is defined as a biochemical process not a system level process?

**Comment by krchristie** [comment]
Would you like to propose a new definition

**Comment by ValWood** [comment]
Isn't there a boiler plate definitions for system level processes?

by definition this should be along the lines:
A multicellular organismal process carried out by any of the organs or tissues *of the digestive system* system to carry out (...biological objective)

...and the objective is more than the breakdown of ingested nutrients that's for sure....(motility, secretion, absorption, mastication, excretion). I'm way out of my comfort zone here. It just seems very insufficient as is.

**Comment by ValWood** [comment]
related in 
https://github.com/geneontology/go-ontology/issues/16108
It would be useful to  revise the cell wall catabolism branch to handle specifically 
"disgestion of cell wall compounds like chitin" by mammalia
and
"degradation of cell wall resulting in cytolysis" as part of host defense response.

I envisage that eventually we can force the appropriate  specificity at annotation time by blocking the high-level terms and forcing the more precise taxon relevant annotation.

**Comment by ValWood** [comment]
We can close this. I can use catabolism + occurs_in extracellular space  + during cellular response to nutrient.

I will open a ticket to make "digestion" a do not annotate as more specific annotation should be possible (that seemed to be a suggestion)
