### ISSUE TITLE
MP: mitochondrial RNA 5' end processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14796]
has the parent 
gene expression, but does not have the parent "mitochondrial gene expression"

![mp](https://user-images.githubusercontent.com/7359272/34117973-4b9b93d4-e415-11e7-87f1-ad3732bd066c.jpg)

**Comment by krchristie** [comment]
@ukemi & @cmungall - I was wondering what needs to be done here. It seems this should be handled logically, rather than by directly instantiating a relationship.

mitochondrial gene expression (GO:0140053)
= 'gene expression' and ('occurs in' some mitochondrion)

RNA 5'-end processing (GO:0000966) 
-- has an anonymous subclass 'part of' some 'gene expression'

mitochondrial RNA 5'-end processing (GO:0000964)
= 'RNA 5'-end processing' and ('occurs in' some mitochondrion)

**Comment by ukemi** [comment]
Unfortunately, I think you need to instantiate the part of relationships. If it were a subclass, it would be reasoned.

**Comment by ValWood** [comment]
I think it is just positioned incorrectly? Its a sibling of

GO:0000963 mitochondrial RNA processing
rather than a child...

anyway I'll close this as I just realised it is now a duplicate

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/14873
