### ISSUE TITLE
MP GO:0000935     division septum

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14794]
should

GO:0000935    division septum
def
A cell septum which functions in the compartmentalization of a cell into two daughter cells at division. A division septum spans a cell and does not allow exchange of organelles or cytoplasm between compartments.

 have the parent
GO:0032153   cell division site

Definition (GO:0032153 )
The eventual plane of cell division (also known as cell cleavage or cytokinesis) in a dividing cell

since
GO:0005826    actomyosin contractile ring
etc are parts, and it is in the division plane?

**Comment by ukemi** [comment]
I don't think so. I think the cell division site is the place where the cells will divide, and the septum is the physical barrier that forms in some organisms. The contractile rings sets up at the site of division and is one of the things that delineates the site. Since the contractile ring exists in organisms that don't have a septum, it can't be a part of the septum.

**Comment by ValWood** [comment]
I don't think the contractile ring should be part of the septum, but  that the septum is part of the "division site"
(division site is a broad term encompassing everything in the division plane, it seems).

I took
"The eventual plane of cell division..."

To mean "any structure which is part of the eventual plane of cell division"
 The septum is assembled in the plane of cell division, so I assumed it to be part of the cell division site. 

I thought it was a grouping terms for all of the structures of interest to the cytokinesis community. Historically we have used "cell division site" when we did not have enough info to pin down to one of these sub structures. Possible septum components would be annotated here.

**Comment by ValWood** [comment]
I guess it depends, if the "cell division site" ONLY exists prior to division, or also during and after division.  The current def is ambiguous in this regard.
I think it is used for all 3. You can have a "cell division site" in a divided cell.

**Comment by ukemi** [comment]
In the bigger modeling picture, I think that we would want to represent the division site as the place where something happens. Would you want the gene products that are part of the mature septum to be grouped with those that are acting at the divisions site? I don't know enough about septa to judge, but that would seem strange to me.

**Comment by ValWood** [comment]
I requested the term originally as a grouping term, because when we got our early localization dataset we could not distinguish between septa, cytokenetic ring etc, so we wanted a broader term to encompass all stuctures at the division plane.
Maybe it is no longer interpreted this way?  I'm happy if it is refined but we would need to fix things.... obsoletion might be best though...

**Comment by ukemi** [comment]
I'm not sure how it is currently interpreted. Certainly your broader interpretation wouldn't make any annotations incorrect. If you really want, I can make the septum part of the division site.

**Comment by ValWood** [comment]
I would prefer broader but maybe a better name like
"cell division site apparatus"  would work better 
to encompass any of the cell division machinery and features which  occur in the division plane?

**Comment by ukemi** [comment]
I think that name is more confusing. I think I'd rather stick with the current name and make division septum part of the cell division site. It seems to fit with all of the other structures that are listed.

**Comment by ValWood** [comment]
I'm worried that I'm using it differently to everyone else! Would like input from @mah11  @Antonialock

**Comment by Antonialock** [comment]
I have used "cell division site" as a catch all term for anything that localizes to the division plane at any point, but the paper isn't fine-grained enough to say to what exact structure, or at what particular point, the gene product acts. I agree that the def "The _eventual_ plane of cell division" is not appropriate for this usage (since we use it for anything that is at the eventual site of cell division + at the site of cell division).

I agree it is useful to have a "catch all term" for things going to this site, but we cannot annotate to BP "cytokinesis", or other more fine grained cytokinesis structures because the paper doesn't provide enough information. 

I don't think that "cell division site" is a very useful term as it is currently defined (sounds a bit wishy washy? - if you know this then you can probably annotate to a more specific term anyway?)....personally I think it could be redefined to also include during and after division.

**Comment by ValWood** [comment]
yes that was certainly the intent when the term was created.....

**Comment by ukemi** [comment]
Then let's go ahead and relax the definition.

**Comment by ValWood** [comment]
unfortunately I'll  be working this week... if anyone wants to do tickets with me...glad I decided to fetch my laptop...

I'll be ![20171231_112607](https://user-images.githubusercontent.com/7359272/34467145-ae8e0e38-eee0-11e7-96ff-80efbfeab3ac.jpeg)

**Comment by jimhu-tamu** [comment]
I should have been paying more attention to this item. Sorry! cc'ing @dsiegele.

**Comment by bmeldal** [comment]
Happy New Year and speedy recovery, Val!
(I'm working again as of this morning...)

**Comment by mah11** [comment]
Relaxing the def sounds fine to me. From what (perhaps little) I remember, the important thing is/was to include the future site of division in a not-yet-dividing cell. I don't think the actual site of ongoing division was meant to be excluded; I suspect it just ended up looking that way after we got overzealous making sure the future-site angle was covered.

**Comment by dsiegele** [comment]
I already think of the 'cell division site' as either the site where division will occur when the cell next divides or the site where division is in the process of happening. Relaxing the definition so that it also includes the site after division is completed sounds OK to me, too.

**Comment by ukemi** [comment]
OK. I took a look at the definition again and it looks like the division site definition is ok. I modified the definition of the division septum to specify that is is part of the division site. I also created a logical definition to say that is it a cell septum that is part of the division site. This seems necessary and sufficient and gives the inferences we want. I am going to commit and close this ticket. If these edits don't look ok, open the ticket again after it is closed.
