### ISSUE TITLE
MF refactor - transcription factor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14790]
Hello, 

I attach the proposal for the next part of the MF refactoring of transcription. I have a branch that I could merge if we agree. 

https://github.com/geneontology/go-ontology/pull/14788

Updated ppt Dec 20 
[Tx_2017-12-20.pptx](https://github.com/geneontology/go-ontology/files/1575592/Tx_2017-12-20.pptx)

@ukemi @thomaspd I'd like to discuss this on the next ontology editors call. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

this is an amazing summary of the refactoring work you are doing. 

I have a few concerns about the slides however.
1. for GO:0000990 transcription factor activity, core RNA polymerase binding there are actually over 50 annotations which include this exact term to consider, rather than just 2. the majority of these are ICs, with 'contributes to' qualifiers. I haven't looked at the papers but I think these annotations need to be considered as often ICs are a reflection of author knowledge. However, it seem likely that these can be associated with a more specific term? For TP53 this is unlikely to be a correct annotation.

2. For slide 17 GO:0000991 transcription factor activity, core RNA polymerase II binding (and child). Are there any proteins that directly interact with POL II that are not  general transcription co-factors?  Also, I was under the impression that the action of general transcription co-factors was going to be considered as part of 'transcription' rather than 'regulating transcription'. Is this the decision? If so I think the definition needs to clarify this 

I think we could be much more helpful to the curators by improving this definition. Perhaps something along the lines of:
Interacting selectively and non-covalently with an RNA polymerase II (Pol II) complex, typically composed of twelve subunits (eg POLR2A-POLR2K). The majority of Pol II, interacting proteins are general transcription co-factors (TFIIA, B, D, F, H, etc). Pol II transcription requires the activity of general transcription co-factors. 

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 
Thanks for the feedback. You are right that I should also have considered the ICs, since the guidelines for transcription really promoted the use of IC. 

1. For GO:0000990 transcription factor activity, core RNA polymerase binding I find 26 non-IEA/non-IBA/non-ISS: https://docs.google.com/spreadsheets/d/1c97sGCZJ0THUi2wNLY1WV0Sec_DG1Mtr3dkyrpztc6U/edit#gid=0

Most proteins are known to be general transcription factors (TFIID, TFIIE, etc). There is also a SWI/SNF, a nucleosome remodeling complex, mediator subunits, which are defined as general co-factors in the proposal here. 

So in any case it's better to obsolete and re-annotated these (note that all proteins are also annotated to many other terms - for example S000001083 /SRB2 (a mediator subunit):


-         RNA polymerase II transcription coactivator activity involved in preinitiation complex assembly (IDA)
-         RNA polymerase II transcription factor activity, TBP-class protein binding, involved in preinitiation complex assembly (IDA)
-         transcription factor activity, core RNA polymerase II binding (IDA, IGI)
-         transcription factor activity, RNA polymerase II transcription factor recruiting (IMP)


(now looking at the 2nd point)
Pascale

**Comment by pgaudet** [comment]
> GO:0000991 transcription factor activity, core RNA polymerase II binding (and child). Are there any proteins that directly interact with POL II that are not general transcription co-factors? 

There are at least two classes of protein that bind PolII, the general **factors** (TFIIA, B, etc), and **co-factors** (some mediator subunits) (see also Slide 5 in the power point)
There are also interactions with elongation factors, see PMC4273853

> Also, I was under the impression that the action of general transcription co-factors was going to be considered as part of 'transcription' rather than 'regulating transcription'. Is this the decision? If so I think the definition needs to clarify this

Yes, it should be 'transcription', not regulation. Thanks for the feedback on the definition. 

Pascale

**Comment by ValWood** [comment]
I agree, a great summary. The paucity of annotations to the old terms  shows that  the existing terms are difficult to interpret, and are leading to inconsistency.

Personally, I would go even further and have no MF’s specific for pol I,II or II but have simple MF terms and allow the processes to be differentiated at the process level

i.e.
“transcription factor activity, polymerase binding” part_of  “transcription from RNA polymerase I promoter”

(similar to how we no longer encode direction or location into the TM transporter activity,  capture this in process,  but hey, baby steps….so far so good….)

**Comment by pgaudet** [comment]
Hi @ValWood 
This may be the way to take - right now I am trying to remove unnecessary terms, and once we see more clearly it should be easier to see which terms should be MF and which should be BP. Right now even the redundancy is hard to see. 

Pascale

**Comment by pgaudet** [comment]
Hi, 

To go back on @RLovering 's comment, I have reviewed all terms I proposed to change in this update on the ontology, looking for IC annotations, and updated the power point accordingly. The desicions are unchanged. 

Thanks, Pascale

**Comment by ValWood** [comment]
> Right now even the redundancy is hard to see.

agreed...

**Comment by bmeldal** [comment]
I assume (I know dangerous this to do!) Astrid in the loop for this one as we've been discussing what terms are currently in use and whether they are still correct but @pgaudet wasn't on those TCs.

Disclaimer: I haven't started revising/rechecking the CP annotations and looks like I should wait til you have finalised the terms. Otherwise I'll end up doing it twice!

**Comment by pgaudet** [comment]
Hi @bmeldal yes all GREKC (Astrid, Martin, and Marcio) and Colin Logie contributed to this (this current proposal was done together with him). 

Thanks, Pascale

**Comment by ukemi** [comment]
It is on today's agenda. It will be the second half of the call.

**Comment by pgaudet** [comment]
@krchristie here's the ticket - the ppt is in the description of the ticket at the very top. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Superseded by other tickets.
