### ISSUE TITLE
comments useful for curators

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14818]
Is it useful to add a comment  giving an example of an annotation to a term?
For instance
![does this help](https://user-images.githubusercontent.com/7359272/34307997-da7264b8-e742-11e7-928c-e2d8ca4fc249.jpg)

is it useful for a curator to see an example in the comment?
This seems a bit unnecessary? (we could just look in AmiGO or QuickGO)
What happens if the annotation  is later removed (happens a LOT!)
It seems quite unmaintainable?

**Comment by ukemi** [comment]
This is actually quite puzzling to me. I think it is a good idea to have examples of how terms are used for annotation. It is worrying that those annotations would be removed since the ones that are used as examples are the ones for which the term is created. It seems to me that if they are removed, then it reflects misuse of the term in subsequent annotations.
@vanaukenk ?

**Comment by ValWood** [comment]
It just seems a bit redundant with the xref. If you have the associated xref used to create the term, its easy to see which annotations use that ref (if required)? Reading the string on it's own doesn't tell you anything about how to annotate, you would still need to go to the paper to interpret the comment?

**Comment by ukemi** [comment]
Yup, you are right. My initial reaction was that I always go back to the original reference whenever there is a question about a term. It worries me that annotations based on those references might be deemed incorrect. But I still think it is worthwhile to have examples of how terms are used to annotate. It's just that this might not be the best way to do it. 

We will discuss this on a call. My tendency is to agree with you and no longer add these as comments to terms, but I want to see what Kimberly thinks since this directly impinges on annotation practice/guidelines. Whether we will go back and remove those already there is another question.

Happy New Year!

**Comment by ValWood** [comment]
Yes I think in principle, it is useful to have an example that  we know is the correct usage...these could even be "auto-populated", but I don't think the comment is the best place, and it probably does not need to be prominent. 
Actually, presumably the "founding" reference annotations are  rarely incorrect ....
It just seems slightly odd to see a comment saying an example of this is x from y.  Curators can look  at the paper, and it isn't very useful for users when all the annotations are right below....

Happy New Year....

**Comment by bmeldal** [comment]
It's a field that was part of the TG templates so I dutifully added it while using TG but stopped sometime after we moved to GH as I forgot the syntax of the comment...

**Comment by ukemi** [comment]
We discussed this today on the ontology developers' call. Although we agree that having examples of 'approved' annotation usage of terms is a good idea, having these as textual comments attached to a term is not ideal. For now, we will not add new comments like this to terms, but we will keep the ones that are there in place, so they can be mined in the future.
