### ISSUE TITLE
NTR: spindle pole body anchor complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#14829]
Can you please add the following two terms?
thanks a lot
Livia

Term 1:
Name: spindle pole body anchor complex
Ontology: cellular_component
Def: A protein complex capable of interacting with the spindle pole body and the nuclear envelope, in order to embed the spindle pole body in the nuclear envelope at fusion sites of the inner and outer nuclear membrane.
References:
GOC:lnp

PMID:28356353
Relationships:
is_a GO:NEW nuclear membrane protein complex (Term2)
part_of GO:0005816 spindle pole body
part_of GO:0016021 integral component of membrane
part_of GO:0005635 nuclear envelope
capable_of_part_of GO:0071789 spindle pole body localization to nuclear envelope
capable_of_part_of GO:0071988 protein localization to spindle pole body
DB xref:
IntAct:EBI-16412392

Term 2:
Name: nuclear membrane protein complex
Ontology: cellular_component
Def: Any protein complex that is part of the nuclear membrane.
References:
GOC:lnp

PMID:28356353
Relationships:
is_a GO:0098796 membrane protein complex 
part_of GO:0031224 intrinsic component of membrane
part_of GO:0005635 nuclear envelope

**Comment by hdrabkin** [comment]
nuclear membrane protein complex GO:0106083
 spindle pole body anchor complex GO:0106084

**Comment by liviap** [comment]
thanks a lot :)

**Comment by ValWood** [comment]
I'm not sure that all of this works completely......

1.
Is the "spindle pole body anchor complex" really part of 
capable_of_part_of GO:0071988 protein localization to spindle pole body
if so which proteins is it localizing to the spindle pole body?

Do you mean "localization *OF* the spindle pole body, rather than localization of proteins *TO* the  spindle pole body?)

2.
Is nuclear membrane protein complex a necessary term (is so it encompasses lots and lots of existing complexes"

3. Can you be more precise about what you mean by 

"Name: spindle pole body anchor complex"

We have existing complexes which fit this def :
GO:0034993 - LINC complex
Definition 
A protein complex that spans the nuclear outer and inner membranes, thereby linking the major cytoplasmic cytoskeleton elements to the nuclear lumen; the complex is conserved in eukaryotes and contains proteins with SUN and KASH domains.

I agree this could be better defined!

 is the new complex equivalent to the  the KASH/SUN domain nuclear envelope bridge? or 
 is it something else?)

We need to make sure that the complexes work across all species.

![spb linkers](https://user-images.githubusercontent.com/7359272/34648484-ccadb142-f391-11e7-9e92-e18c33b20c4b.jpg)

The major components of the anchor are conserved, but 
there are some differences in SPB localization for S. cerevisiae. So is this complex involved in "insertion" rather than the subsequent anchoring?

from
http://jcs.biologists.org/content/joces/122/5/577.full.pdf

**Comment by liviap** [comment]
Hi! thanks a lot for the comment, and sorry for my delayed answer. Please find below my reply:
1. I agree with you, capable_of_part_of GO:0071988 doesn't fit with the function of the complex, it should be removed.
2. It has been reported to me that we created the new parent term nuclear membrane protein complex akin to GO:0098797 plasma membrane protein complex. It was a decision made with @dosumis a few years back. David made a number of membrane specific complex terms but somehow nuclear membrane protein complex got missed.

Yes, of course, there are lots of other complexes that should have this parentage. That's why we need the logical definitions when we create new terms - because no-one has time to find them all manually...
for this specific case, we can eventually replace it with is_a GO:0034992  'microtubule organizing center attachment site',  but it seems to me a temporary rather than resolving solution.

3. I've carefully tried to analyse whether the LINC complex might fit with the SPB anchor complex and I think it doesn't. First, the SPB anchor complex proteins appear not to have SUN and KASH domains. secondly, spb anchor complexes are **embedded into the nuclear envelope at the fusion site of the inner and outer membranes and anchor the central plaque of the spb to the nuclear envelope. They do not span either membrane and have no cytoplasmic or nucleoplasmic regions**, as described in http://jcs.biologists.org/content/joces/122/5/577.full.pdf. 

For further info:
http://www.jbc.org/content/292/20/8447.long

**Comment by bmeldal** [comment]
>for this specific case, we can eventually replace it with is_a GO:0034992 'microtubule organizing center attachment site', but it seems to me a temporary rather than resolving solution.

Thanks, Livia (and for info, I'm Livia's "secret source" with regards to the creation of membrane specific complexes ;-) )

I have one comment to add: 
We created nuclear membrane protein complex GO:0106083 to have a parent term in the macromolecule complex class. GO:0034992 microtubule organizing center attachment site is a subcellular location that has no parentage to complexes so wouldn't help here.

**Comment by ValWood** [comment]
Hi Livia,

What is the db_xref for 
Name: spindle pole body anchor complex?
and what are it's individual members. 

That might establish how it is related to the figure above.
Also is it anchoring the meiotic or the mitotic spindle pole body?

Part of my confusion is that the def  says that the complex is involved in
 embed the spindle pole body in the nuclear envelope at fusion sites of the inner and outer nuclear membrane

The def does not mention attachment? The attachment part is becoming reasonably well characterised, so I'm trying to work out where this fits.
Is "attachment" the process (or is lack of attachment a phenotype resulting from  a defect in insertion? (i.e. indirect)

**Comment by liviap** [comment]
Hi again! sorry for missing pieces of info, 
DB xref:
IntAct:EBI-16412392;
Name: 'spindle pole body anchor complex';
component: Q12365 (Bbp1) and P53159 (Mps2);
I couldn't find a precise annotation on whether it is anchoring the meiotic or the mitotic spindle pole body. So I guess it anchors both.
I'm sorry if I confused you: actually the complex resides at the fusion sites of the inner and outer nuclear membrane thus embedding at these sites the spindle pole body in the nuclear envelope.
I've attached a figure that I hope clarifies it better.

![image](https://user-images.githubusercontent.com/33870012/34873286-64a9bd58-f78c-11e7-8065-abd9d59a7524.png)
ref: https://www.sciencedirect.com/science/article/pii/S0960982213008476

**Comment by ValWood** [comment]
Is this the original reference for the complex?
https://www.ncbi.nlm.nih.gov/pubmed/20139001

**Comment by liviap** [comment]
no, the reference is http://www.jbc.org/content/292/20/8447.long (28356353)

**Comment by hdrabkin** [comment]
So thus far, I will remove "capable_of_part_of GO:0071988"

**Comment by liviap** [comment]
in my opinion, yes

**Comment by ValWood** [comment]
spindle pole body anchor complex GO:0106084
is described as a ternary complex

mps2,YGL075C
bbp1,YPL255W  
spc29, YPL124W


I think the pombe equivalent of this is probably  kms2-? in D  of the figure above
We don't have  data for this yet,  and ortholog detection  has been difficult for spindle proteins.
I now think that S.c  Mps2p is probably the ortholog of pombe  S.p Kms2 (because Mps2 and Csm4 are paralogs in cervisiae, trying to mail this down now).

So we know what is what, I suggest the following revisions:
Rename from
spindle pole body anchor complex
to
nuclear membrane mitotic spindle pole body linking complex

This will be clearer because at present it sounds very generic (the spindle itself is often described as "anchoring")

Add 
Comment: In S. cerevisae Mps2-Bpb1 is the membrane anchor sub complex and Spc29 is the spindle pole body linker molecule

Add synonym
Mps2-Bbp1-Spc29 complex (narrow)

GO:0034993 - LINC complex 
rename to
 "meiotic nuclear membrane microtubule linking complex"
make LINC complex exact synonym
refine definition to
A nuclear membrane  protein complex  which connects the nuclear outer and inner membranes together, and links thereby links the nuclear lumen to cytoplasmic microtubules. 
(spans the nuclear outer and inner membranes is  misleading)

Make  GO:0034993 - LINC complex 
a child of 
nuclear membrane protein complex GO:0106083

This way, if we need more variants in the future it will be clearer  exactly what we  have now refers to. I suspect we have incomplete  but partially overlapping info from pombe and cerevisiae here...in pombe we know more about the Mps3 equivalent sad1.

Does that sound OK?

**Comment by ValWood** [comment]
this older paper
https://www.researchgate.net/publication/6864017_The_Sad1-UNC-84_homology_domain_in_Mps3_interacts_with_Mps2_to_connect_the_spindle_pole_body_with_the_nuclear_envelope

shows that mps3 comments to mps2, so this probably is the S. cerevisiae counterpart of the pombe D above

![mps2-mps3](https://user-images.githubusercontent.com/7359272/34883898-f0c16f72-f7b2-11e7-8d94-f29a1dce01f5.jpg)

**Comment by ValWood** [comment]
This was useful, new paper from Jaspersen lab:
Molecular model of fission yeast centrosome assembly determined by superresolution imaging

Also identifies  kms2 as  mps2  (KASH domain) equivalent

![ticket](https://user-images.githubusercontent.com/7359272/35110076-e154fc40-fc6f-11e7-8873-782061d696c5.jpg)

and produces a nice model

![fig](https://user-images.githubusercontent.com/7359272/35110108-f4ada6ca-fc6f-11e7-8cdc-83b57b14699a.jpg)

**Comment by liviap** [comment]
Hi All,
sorry for my super late reply; I'll speak just about the fission yeast complex since I don't know enough about the pombe one...
Everything that Val has pointed out sounds good to me, The term "meiotic nuclear membrane microtubule linking complex" to include both pombe and fission complexes is fine to me. However, as far I know, spc29 is not part of the complex we are discussing, and shouldn't be included.
Livia

**Comment by bmeldal** [comment]
Hi @ValWood and @hdrabkin 

Acc to the info we have from Sandra who is curating the whole spindle pole bode system in S. cerevisae we thin the membrane anchor complex only contains Mps2-Bpb1 and that Spc29 is part of the inner/central plaque.

Naming:
>Rename from
spindle pole body anchor complex
to
nuclear membrane mitotic spindle pole body linking complex

>This will be clearer because at present it sounds very generic (the spindle itself is often described as "anchoring")

"spindle pole body anchor complex" seems to be the name given in the literature, otherwise Sandra wouldn't have chosen it as recommended name. We can add the other as synonym but we don't know if this complex is restricted to mitosis either.

**Comment by ValWood** [comment]
fission yeast is pombe
budding yeast is cerevisiae

The papers I was citing above were cerevisiae (the ones you are curating), NOT pombe papers.

The problem is, that in GO we  sometimes need to disambiguate author names.  However, the paper that you cited  above the authors didn't use the name "spindle pole body anchor complex"  they used the names Mps2-Bbp1 complex and ternary Mps2-Bbp1-Spc29 complex
https://www.ncbi.nlm.nih.gov/pubmed/28356353
which is why I added as synonyms.

Hence
Comment: In S. cerevisae Mps2-Bpb1 is the membrane anchor sub complex and Spc29 is the spindle pole body linker molecule
(this is from the paper you are curating)

So although spc29 may not be a component of this complex, I'm not sure from the assembly order whether  of the SPB Mps2-Bbp1 ever exists when it is not connected to Spc29 and how you define the complex is a bit arbitrary. I can change this synonym to "related", or we can remove this synonym. The comment will be useful though.

I'm trying to  future proof this, because the mitotic and meiotic components are very similar but slightly different, and appear to be conserved across species (see the first figure above), and there are gaps in our knowledge (from both yeast).   Form comparing the  knowledge from the two yeast  it is clear we are talking about the  functional  and compositional equivalents here. The figure I posted last is from a laboratory who work on both yeasts (a Nov 2017 paper).
This confirms that we are talking about equivalent complexes (albeit at undetectable levels of  orthology).

**Comment by bmeldal** [comment]
I'm asking Sandra to look at this as she's spent ages deconstructing the SPB into its constituent complexes and I'd rather not repeat the exercise ;-)

**Comment by ValWood** [comment]
I think its fine to exclude the linker, but we need to make sure that somebody does not then request the same complex with the spc29 linker, and if they are looking for it, they find this one! related synonym would work for this.

I have recently curated over 100 papers on spindle and spindle pole which is why I am being particularly picky! It's also not as simple as it seems, and the distinction between the layers and the membrane part connecting part is not completely resolved. There are still a number of slightly overlapping models....

**Comment by bmeldal** [comment]
>related synonym would work for this.

I can live with that :)

>I have recently curated over 100 papers on spindle and spindle pole which is why I am being particularly picky! 

Picky is good and always appreciated!

>It's also not as simple as it seems, and the distinction between the layers and the membrane part connecting part is not completely resolved. There are still a number of slightly overlapping models...

I know, that's what Sandra said as well. I've emailed here, waiting to hear back. Livia is doing the checking and I'm just advising as she's new to this how GOA malaky ;-)

**Comment by ValWood** [comment]
Woah in at the deep end with the SPB...

The main thing is to try to prevent  the same complex for identical entities, especially as  authors want to claim specific "complexes".

**Comment by bmeldal** [comment]
>Woah in at the deep end with the SPB...

Not the first complex she's checked but the first that needed a new term. The easy ones are already there...

>The main thing is to try to prevent the same complex for identical entities, especially as authors want to claim specific "complexes".

Absolutely.

**Comment by sandraorchard** [comment]
Hi
Where to put SPC29 was as much a judgement call as a fact based on hard evidence, so I agree, not easy. I'm happy with the related synonyms option. Hopefully is we can get people (or at least editors) into the habit of looking what complexes we have already created, even if only for related species, before creating new terms, we can get round the problem of overlapping terms, but I accept that is going to take time.

**Comment by bmeldal** [comment]
The editors usually give me a shout before they create another complex term.
But yes, you lovely editors, can have a look at the CP directly as well :)

**Comment by ValWood** [comment]
actually I think "tethering" might be a better word to use here

term:
synonym: nuclear membrane mitotic spindle pole body tethering complex

this reflects more closely how we have  represented SUN/KASH domain related processes.

**Comment by ValWood** [comment]
also this ticket needs to be handled taking into account the existing term

GO:0034992    microtubule organizing center attachment site

which is a parent for the GO:0034993    LINC complex
and would also work as a parent for this complex.

I think we could merge this existing term into one of the new proposed terms as "related"...I don't think we need to model the attachment site  per se now we know more...

**Comment by ValWood** [comment]
Harold do you want me to summarize ;)

**Comment by hdrabkin** [comment]
@ValWood  yes please.. Too many cooks here.

**Comment by ValWood** [comment]
1. - [ ]

**Comment by hdrabkin** [comment]
Val; I am working on this now;

**Comment by ValWood** [comment]
OK done the list... time for dinner

**Comment by hdrabkin** [comment]
I put first chunk in ; will have to wait for 9 and 10

**Comment by ValWood** [comment]
I changed the numbers mid way so double check... 5 got inserted later

**Comment by hdrabkin** [comment]
5.  - [ ] create a new term    <<<<<<<<<< defintion, references!!!!!! 
 nuclear membrane microtubule tethering complex    
as a parent to the mitotic and meiotic versions

**Comment by hdrabkin** [comment]
if not done already remove "capable_of_part_of GO:0071988"
From GO:0034992 ?

**Comment by bmeldal** [comment]
The new def for pt 4 has a typo:
>A nuclear membrane protein complex which connects the nuclear outer and inner membranes together, and links thereby links the nuclear lumen to cytoplasmic microtubules.

should be
"A nuclear membrane protein complex which connects the nuclear outer and inner membranes together, and **~~links~~** thereby links the nuclear lumen to cytoplasmic microtubules."

**Comment by hdrabkin** [comment]
Hi @bmeldal ; fixed typo as it went in yesterday.

**Comment by ValWood** [comment]
5  is just a grouping term for the functionally similar
meiotic nuclear membrane microtubule tethering complex
and
mitotic nuclear membrane microtubule tethering complex

so the definition would just be the genus which is
A nuclear membrane protein complex which connects the nuclear outer and inner membranes together, and links thereby links the nuclear lumen to cytoplasmic microtubules.

I made a mistake in the 
meiotic nuclear membrane microtubule tethering complex
definition, it needs  "during meiosis" adding 

the parent will be "nuclear membrane protein complex GO:0106083"

**Comment by hdrabkin** [comment]
@ValWood do you have a PMID for #5

**Comment by ValWood** [comment]
you can use any of the ids on the children?

**Comment by ValWood** [comment]
Actually use this nice review  describes a few of the complexes, the first figure is from this
PMID: 19225124

**Comment by hdrabkin** [comment]
@ValWood 
I  made the new term nuclear membrane microtubule tethering complex and made it a parent of the meiotic version, but I cannot find 'mitotic nuclear membrane microtubule tethering complex; I found the 'meiotic nuclear membrane microtubule tethering complex'

**Comment by hdrabkin** [comment]
@ValWood 
is this the term you mean
nuclear membrane mitotic spindle pole body tethering complex ? should this be renamed ?

**Comment by ValWood** [comment]
Hi HArold, I think this was 99% don, is anything outstanding?

**Comment by pgaudet** [comment]
Fixed term label from 
-name: nuclear membrane mitotic spindle pole body tethering complex
to 
-name: mitotic nuclear membrane microtubule tethering complex

Added the more specific parent for mitotic nuclear membrane microtubule tethering complex

from : GO:0106083 ! nuclear membrane protein complex
to: GO:0106094 ! nuclear membrane microtubule tethering complex

I think that finishes the work needed for this ticket. 

Thanks, Pascale
