### ISSUE TITLE
NTR response to L-carnitine

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#14879]
Response to L-carnitine
Def Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an L-carnitiene stimulus.

Is a GO:0043200 response to amino acid

**Comment by cerivs** [comment]
**

 CHEBI:16347  I'm curating PMID:28102299.   There are lots of pubs about "L-carnitine" supplementation at PubMed, some human based others based on farm animals or MOs. 





**

**Comment by ukemi** [comment]
Thanks. I made the primary term 'response to (R)-carnitine so that it will be consistent with the ChEBI definition. I added L-carnitine as a synonym. Note that this term is automatically classified with respect to ChEBI. In ChEBI, carnitine is and amino-acid betaine, not an amino acid. We do not have a response term for amino-acid betaine in GO. If we eventually create that term, this new term will be autoclassified.
