### ISSUE TITLE
taxon restriction: replicative senescence, add 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14881]
never in fungi (or only in multicellular)

https://www.ebi.ac.uk/QuickGO/term/GO:0090399

to prevent mappings

tks

**Comment by vanaukenk** [comment]
@ValWood 

There are currently three experimental annotations to this term from SGD.  I've asked for a review:

https://github.com/geneontology/go-annotation/issues/1777

I also found these old tickets about this in the annotation tracker:

https://github.com/geneontology/go-annotation/issues/1360
https://github.com/geneontology/go-annotation/issues/1092

**Comment by ValWood** [comment]
Yeast don't do senescence do they (at least pombe do quiesence which is similar but different)
 
The ref above abstract  geneontology/go-annotation#1092 now I read it says:

Here, we use telomerase-defective strains of budding yeast to probe whether replicative senescence can be attenuated or accelerated by defects in factors previously implicated in handling of DNA termini. ......... It is likely that telomere shortening in telomerase-depleted human cells is similarly under a complex pattern of genetic control; mechanistic understanding of this process should provide crucial information regarding how human tissues age in response to telomere erosion.

I think this means that they used yeast cells to probe human senesence. Not that yeast do senesence....

**Comment by ValWood** [comment]
Hmm I'm not sure now. I still don't think its a process for yeast ...it's not a mechanism of cell death but a cessation of division so it seems a bit different to metazoa...
I'll ask my ageing expert.

**Comment by ValWood** [comment]
see also
https://github.com/geneontology/go-ontology/issues/12174

**Comment by mah11** [comment]
Caveat: I don't know this area very well. I just happened on this ticket because of some phenotype requests on a closely related topic.

IIRC, budding yeast have both types of cell aging, although SGD curators have mostly tended to use GO:0001302 rather than GO:0090399 to annotate the replicative type. It's not clear to me whether GO:0001302 and GO:0090399 should be merged (or, if not, what the difference is).

PMID:28139976 reports that wild type S. pombe does not undergo replicative aging. So GO could have a "never in Schizosaccharomyces" restriction, but not "never in fungi".

Aside 1: It's chronological cell aging, not replicative, that's connected with cell quiescence/G0.

Aside 2: Fission yeast telomerase mutants do have replicative aging/senescence (e.g. PMID:29167439, PMID:18157149), although that wouldn't affect a GO taxon restriction.

**Comment by ValWood** [comment]
But are these *processes* ? or the outcomes of processes?

**Comment by mah11** [comment]
For that I'm gonna have to refer you back to the first sentence of my comment ;)

**Comment by ValWood** [comment]
I don't know the answer  either. I think for now a taxon restriction and closing is a way to keep the lid on this can :)

**Comment by pgaudet** [comment]
Fungi annotations to replicative senescence have been removed, so I added the taxon constraint. 
https://github.com/geneontology/go-annotation/issues/1777

Pascale
