### ISSUE TITLE
definition of biological process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#14899]
Is  the definition of biological process missing something fundamental?

Any process specifically pertinent to the functioning of integrated living units: cells, tissues, organs, and organisms. A process is a collection of molecular events with a defined beginning and end.

Should it not include  that  the process needs to be "encoded by an organism" to specifically  distinguish 
a "biological process" from non-biological process that occur in a biological context (some aspects of ageing, deterioration etc, and other chemical processes that can happen *to* an organism?)

**Comment by cmungall** [comment]
I think the def of MF and BP may be due an overhaul. I don't think this is completely outside the scope of the docathon next week @vanaukenk @ukemi @pgaudet. We'd like the GO to be as self-documenting as possible. The top level is a good opportunity to impart upon people the way GO models things.

strawman

 * MF: __An activity that is executed by a gene product or macromolecular complex__
 * BP: __A coordinated set of causally connected activities, each executed by a gene product or macromolecular complex__

These are nowhere near good enough - we need to account for compound functions and for the encoded by organism aspect. But there are some properties I think are good for the top level defs.

It avoids fuzzy weasely language like the current defs. While fuzzy language has the advantage of reaching consensus as it doesn't really say anything, it's a wasted opportunity. We're not charged with writing a dictionary definition here, we're defining our model of biology. The language in the strawman defs is consistent with how we model things (we could say *enabled by* rather than *executed* to be more consistent with the name of the relation we use, but @dosumis has long argued for a change in the RO label, for now it's better to use a biologist friendly synonym in the definition).

We could embed more of the GOCAM model here, e.g

_An activity that is executed by a gene product or macromolecular complex that occurs in a cell part or a region around a cell_

But this gets a bit awkward since cell_component is hard to define sensibly. And it should be implicit, as activities have to occur somewhere.

we could get some of the causal aspects in:

_An activity that is executed by a gene product or macromolecular complex that regulates or affects other such activities as a part of a biological process_

The wording is undoubtedly awkward here but could potentially be refined. I think it's important to communicate the wider context of a molecular function at this upper level. It shouldn't be taken to be read that MF *annotations* can't exist in isolation, but it's an important feature of the GOCAM model that _in reality_ the MF instances are always causally connected.

The proposed BP definition repeats some of the MF definition rather than simply referring to molecular_function but that's good as molecular_function is a slightly legacy term that we can't get rid of.

I'm confident we can arrive at something that is biologist-friendly, coherent with the modeling in GOCAMs and in the ontology, and serves a vital elucidation role to help people think the 'right' GO way. 

cc @thomaspd (and @dosumis if he has time and inclination)

**Comment by cmungall** [comment]
Also consider event rather than activity

**Comment by ValWood** [comment]
This sounds a great plan. Keep me posted. ...and if you have time "biological regulation" is on my wish list. I constantly run up against issues explaining  (badly) why  something is not regulation, because the observed change  is just the result of a "pathological problem".  The current definition does not help because it often fits what people are describing.

The  word "modulate" is not strong enough to exclude any old change/alteration its weakest form).  The change needs to be more "deterministic" although that also is not the correct word. 

v

**Comment by thomaspd** [comment]
Yes, we can work on these.  From my chapter in the GO Handbook:

a molecular function is a process that can be carried out by the action of a single macromolecular machine, via direct physical interactions with other molecular entities. Function in this sense denotes an action, or activity, that a gene product performs. These actions are described from the two distinct but related perspectives commonly employed by biologists: (1) biochemical activity, and (2) role as a component in a larger system/process.

A cellular component is a location, relative to cellular compartments and structures, occupied by a macromolecular machine when it carries out a molecular function. There are two ways in which biologists describe locations of gene products: (1) relative to cellular structures (e.g., cytoplasmic side of plasma membrane) or compartments (e.g., mitochondrion), and (2) the stable macromolecular complexes of which they are parts (e.g., the ribosome).

a biological process represents a specific objective that the organism is genetically “programmed” to achieve. Each biological process is often described by its outcome or ending state, e.g., the biological process of cell division results in the creation of two daughter cells (a divided cell) from a single parent cell. A biological process is accomplished by a particular set of molecular processes carried out by specific gene products, often in a highly regulated manner and in a particular temporal sequence.

**Comment by ValWood** [comment]
Nice!

I like the inclusion of results_in (has_output?) but begins_with and ends_with are more important  where possible (I realise that these are often not known, so we say what we see ;)

I really, really like the inclusion of something  along the lines of "genetically programmed” 
too. This is the point which is often missed by curators. 

v

**Comment by ValWood** [comment]
@cmungall  @pgaudet  or anyone. Do you have any good  general documentation on the GO site for creating text definitions (we have a meeting tomorrow with a collaborator who is converting their controlled vocabulary for describing  host pathogen interaction phenotypes into a formal ontology).

val

**Comment by pgaudet** [comment]
As far as I know the documentation is here: 
http://geneontology.org/page/ontology-documentation
Some types of GO terms have standard definitions. Is that what you were looking for ? 

Pascale

**Comment by pgaudet** [comment]
Final version: 
molecular_function: 
"A molecular process that can be carried out by the action of a single macromolecular machine, usually via direct physical interactions with other molecular entities. Function in this sense denotes an action, or activity, that a gene product (or a complex) performs. These actions are described from two distinct but related perspectives: (1) biochemical activity, and (2) role as a component in a larger system/process." [GOC:pdt]


biological_process:
"A biological process represents a specific objective that the organism is genetically “programmed” to achieve. Biological processes are often described by their outcome or ending state, e.g., the biological process of cell division results in the creation of two daughter cells (a divided cell) from a single parent cell. A biological process is accomplished by a particular set of molecular functions carried out by specific gene products (or macromolecular complexes), often in a highly regulated manner and in a particular temporal sequence." [GOC:pdt]



cellular_component: 
"A location, relative to cellular compartments and structures, occupied by a macromolecular machine when it carries out a molecular function. There are two ways in which the gene ontology describe locations of gene products: (1) relative to cellular structures (e.g., cytoplasmic side of plasma membrane) or compartments (e.g., mitochondrion), and (2) the stable macromolecular complexes of which they are parts (e.g., the ribosome)." [GOC:pdt, NIF_Subcellular:sao-1337158144]
