### ISSUE TITLE
NTRs: (positive/negative) regulation of "(tubulin) deacetylase activity"

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#14950]
Experiments shown in PMID:19457097 demonstrate that tau increases tubulin acetylation.

Figure 5 on its own shows that tau inhibits the deacetylase activity of HDAC6, providing evidence for the following new GO term:
"negative regulation of 'GO:0019213 deacetylase activity'"

Figures 2-4 ("GO:1904428 negative regulation of tubulin deacetylation") and Figure 5 (NTR: "negative regulation of 'GO:0019213 deacetylase activity'"), collectively provide evidence for the following new term:
"negative regulation of 'GO:0042903 tubulin deacetylase activity'"

New terms:
GO:0019213 deacetylase activity
> New1: regulation of 'GO:0019213 deacetylase activity'
> New2: negative regulation of 'GO:0019213 deacetylase activity'
> New3: positive regulation of 'GO:0019213 deacetylase activity'
> GO:0042903 tubulin deacetylase activity
>> New4: regulation of 'GO:0042903 tubulin deacetylase activity'
>> New5: negative regulation of 'GO:0042903 tubulin deacetylase activity'
>> New6: positive regulation of 'GO:0042903 tubulin deacetylase activity'

Definitions: Any process that modulates/stops or reduces/activates or increases the rate of (tubulin) deacetylase activity.

Refs: PMID:19457097, GOC:aruk, GOC:bc

cc:
@RLovering 
@paolaroncaglia

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub,

I agree with your suggestion to create
New1: regulation of 'GO:0019213 deacetylase activity'
New2: negative regulation of 'GO:0019213 deacetylase activity'
New3: positive regulation of 'GO:0019213 deacetylase activity'
(Strictly speaking, the positive regulation term is not required, but unless you have reasons to believe that it is biologically unlikely/not meaningful, it’s nice to have the complete regulation triad; I’ll leave that to your judgment.)

I have, however, a small concern about the creation of 
New4: regulation of 'GO:0042903 tubulin deacetylase activity'
New5: negative regulation of 'GO:0042903 tubulin deacetylase activity'
New6: positive regulation of 'GO:0042903 tubulin deacetylase activity'
not because of what you’re annotating, but because of the term GO:0042903 ‘tubulin deacetylase activity’ itself. Looking at GO:0042903 ‘tubulin deacetylase activity’ and at its parent GO:0033558 ‘protein deacetylase activity’, I can’t really see a differentia in GO speak other than the substrate that is being deacetylated. I have a vague memory that we agreed to keep such terms when the substrate is an abundant or important protein (see histone-related terms in GO). But I’m not sure if the GOC still agrees to those guidelines. If yes, no objection to adding those regulation terms. If not, I’d lean against exploding the GO by adding regulation terms when the target can be captured by an annotation extension. @ukemi, any opinion on this please?

On a minor note, the definition of GO:0090043 ‘regulation of tubulin deacetylation’ (“Any process that modulates the frequency, rate or extent of tubulin deacetylation. Tubulin deacetylation is the removal of an acetyl group from a protein amino acid.”) could be made less generic by changing it to “…Tubulin deacetylation is the removal of an acetyl group from tubulin.”, otherwise there’s little differentia from its parent GO:0090311 ‘regulation of protein deacetylation’ (“Any process that modulates the rate, frequency, or extent of protein deacetylation, the removal of an acetyl group from a protein amino acid. An acetyl group is CH3CO-, derived from acetic [ethanoic] acid.”).

Thanks!

Paola

**Comment by BarbaraCzub** [comment]
Hi @paolaroncaglia 
Thanks for your thoughts re: 'GO:0042903 tubulin deacetylase activity'. @ukemi could you please advise wrt this term, and its parent 'GO:0033558 protein deacetylase activity'?
@paolaroncaglia I'll remember about your suggestion to make the definition more specific (if the terms can get created). 
Thanks,
Barbara

**Comment by ukemi** [comment]
Since we do not have a way to distinguish among the different tubulins in most cases, we had always thought that the creation of terms was justified. So things related to actins, histones, tubulins etc. were allowed in the ontology. @thomaspd  any thoughts?

**Comment by ValWood** [comment]
I was thinking we could do this with an extension but I'm not sure if this is how we would couple the substrate of an inhibitor to its downstream target:

 deacetylase inhibitor activity has_substrate(HDAC6),has_regulation_target(tubulin)

**Comment by ukemi** [comment]
Originally, we decided that for generic proteins there was nothing to put in an extension, and for large gene families, we often didn't know which gene was the one being studied. I can't find the  meeting minutes from the very old meeting where we decided this, but here is a snippet from a much later discussion about binding.

http://wiki.geneontology.org/index.php/2010_GO_camp_binding_documentation_issues
Suggestion to obsolete gene specific terms such as P53 binding, a lot of debate about this. In general it was agreed that 'family' binding terms were useful, such as actin binding, but there was no agreement about the usefulness of binding terms such as P53 binding. Harold pointed out how the current system makes it hard for users to find all 'actin binding' proteins as some will be annotated to 'protein binding' IPI WITH actin protein ID, whereas others are annotated to 'actin binding'. Emily pointed out that QCs could be created to pick up these inconsitancies, eg adding 'actin binding' to any proteins binding an 'actin protein ID'. It was agreed that this issue would be discussed at another binding call with GO editors present to explain the rational here.

**Comment by paolaroncaglia** [comment]
@ukemi Thanks for your feedback. The snippet above is from 2010 :-D I remember we had a similar discussion in more recent years, @hdrabkin might remember. 

(@BarbaraCzub Sorry, we managed to turn an innocent-looking request into a discussion on protein binding... but the regulation of deacetylase activity terms are fine to add, I'm sure.)

**Comment by BarbaraCzub** [comment]
Thank you all for these comments. @paolaroncaglia I'll make the new terms, following your suggestion to make the definitions less generic. Thank you!

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
Just to make sure there are no misunderstandings :-) the terms I meant would be fine to add are:
New1: regulation of 'GO:0019213 deacetylase activity'
New2: negative regulation of 'GO:0019213 deacetylase activity'
New3: positive regulation of 'GO:0019213 deacetylase activity'
(Strictly speaking, the positive regulation term is not required, but unless you have reasons to believe that it is biologically unlikely/not meaningful, it’s nice to have the complete regulation triad; I’ll leave that to your judgment.)

For these terms, instead, please wait for a resolution:
New4: regulation of 'GO:0042903 tubulin deacetylase activity'
New5: negative regulation of 'GO:0042903 tubulin deacetylase activity'
New6: positive regulation of 'GO:0042903 tubulin deacetylase activity'

Thanks and sorry if there was any confusion.
Paola

**Comment by BarbaraCzub** [comment]
- [ ] add New1: regulation of 'GO:0019213 deacetylase activity'

- [ ] add New2: negative regulation of 'GO:0019213 deacetylase activity'

- [ ] add relation - make GO:0090045 'positive regulation of deacetylase activity' a child term of New1: regulation of 'GO:0019213 deacetylase activity'

**Comment by BarbaraCzub** [comment]
- [ ]  add the '(positive/negative) regulation of tubulin deacetylase activity' terms, as discussed and agreed during today's Ontology Developers' Call.
