### ISSUE TITLE
Obsoletion notice for GO:0002330 pre-B cell receptor expression

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14973]

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete ' GO:0002330 pre-B cell receptor expression’.  The reason for obsoletion is that there is no specific process to express pre B-cell receptors. 

There are no annotations or mappings to this term. Any comments can be added to this issue: https://github.com/geneontology/go-ontology/issues/14973

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on Feb 6, 2018. Unless objections are received by  Feb 6, 2018  we will assume that you agree to this change. 


Thanks, Pascale

**Comment by addiehl** [comment]
I strongly object to this obsoletion, and find the statement "there is no specific process to express pre B-cell receptors" reflects ignorance of the field rather than an actual attempt to research the topic.  

"PAX5 promotes pre-B cell proliferation by regulating the expression of pre-B cell receptor and its downstream signaling." https://www.ncbi.nlm.nih.gov/pubmed/27016671

"The survival and differentiation of pro-B and pre-B cells in the bone marrow is dependent on IL-7Rα Tyr449." https://www.ncbi.nlm.nih.gov/pubmed/25143441

"EBF and E47 collaborate to induce expression of the endogenous immunoglobulin surrogate light chain genes." https://www.ncbi.nlm.nih.gov/pubmed/9252117

and many other papers...

The fact that this GO term has never been used in annotation reflects a shortfall of GO annotation efforts in the area of immunology rather than some defect in the formation of the term itself.  MGI should go ahead and annotate to this term based on these papers.

-- Alex

**Comment by RLovering** [comment]
I have to agree with Alex, I have tried on many occasions to get funding for immune system annotation, I guess this provides a good example of why this is needed

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering @addiehl 
OK, I'll close this. 

Just a comment: while I completely agree that the B cell receptor is expressed, and that is biologically meaningful, the papers cited seem to describe various different pathway that converge on the B cell receptor being expressed. It's not really about the B-cell receptor, but the gene expression branch is either useless or vastly underpopulated

<img width="518" alt="image" src="https://user-images.githubusercontent.com/4782928/36317561-b265234e-133d-11e8-9e84-18fc7fff4ce8.png">


It seemed what you were trying to capture with that term would be more appropriate elsewhere, but since I have no suggestion to make I'll close this. 

Thanks for the feedback, Pascale

**Comment by addiehl** [comment]
Hi Pascale,

Thanks.  The reason this term was created is because expression of the pre-B cell receptor (and note the pre-B cell receptor is _not_ the same as the B cell receptor) is a major checkpoint in normal B cell development.  Unless the pre-B cell receptor assembles correctly, is displayed on the surface, and provides appropriate signaling, further development of the pre-B cell to mature naive B cell is stopped and apoptosis is induced.  Mice and humans which are genetically deficient in proteins required to express the pre-B cell receptor are prevented from producing mature B cells and obviously, producing antibodies, and consequently have a serious form of immunodeficiency.

Of related interest is that mechanisms lead to blockage of expression of the pre-B cell receptor can lead to development of B-cell precursor acute lymphoblastic leukaemia (BCP-ALL) (PMID:25943180).

My interest in creating this term was to provide a way to annotate gene products involved in the process of expression of the pre-B cell receptor, so that researchers working in areas such as understanding immunodeficiencies or cancer development, as well as understanding normal B cell development would be able to rely on the Gene Ontology and GO annotations as a valuable source of information for their work.  It's not like it was completely random that I created this term, though it may appear to be so from the perspective of a non-immunologist.  I didn't created a bunch of random "expression of X protein" or "expression of X protein complex" terms, but rather wanted to capture this very important process in the development of the immune system across much of the range of vertebrate species so that the GO would be more useful to biologists who study complex biological systems such as the immune system and more useful to people for medically related research.

Given that "gene expression" and its child terms have 379420 total annotations, including 29199 experimental annotations, I would suggest the gene expression branch is in fact useful to somebody.

-- Alex
