### ISSUE TITLE
Transcription versus regulation of transcription - second proposal 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#14998]
Hello, 

I git a little carried away in the previous proposal ( #14935 ). What I wanted to capture is that for **transcription**, the types of transcripts produced are not relevant; the process is the same. 
For *regulation of transcription** this is different. 

So the proposal is this: 

GO ID | term label | EXP | Merge into |  
-- | -- | -- | -- | --
GO:0042792 | rRNA transcription from   mitochondrial promoter | 0 | GO:0006390 | transcription from mitochondrial   promoter
GO:0042794 | rRNA transcription from plastid   promoter | 1 | GO:0042793 | transcription from plastid   promoter
GO:0042790 | transcription of nuclear large   rRNA transcript from RNA polymerase I promoter | 44 | GO:0006360 | transcription from RNA polymerase   I promoter
GO:0042789 | mRNA transcription from RNA   polymerase II promoter | 23 | GO:0006366 | transcription from RNA polymerase   II promoter
GO:0061614 | pri-miRNA transcription from RNA   polymerase II promoter | 10 | GO:0006366 | transcription from RNA polymerase   II promoter
GO:0001015 | snoRNA transcription from an RNA   polymerase II promoter | 6 | GO:0006366 | transcription from RNA polymerase   II promoter
GO:0042795 | snRNA transcription from RNA   polymerase II promoter | 22 | GO:0006366 | transcription from RNA polymerase   II promoter
GO:0097394 | telomeric repeat-containing RNA   transcription from RNA pol II promoter | 2 | GO:0006366 | transcription from RNA polymerase   II promoter
GO:0042796 | snRNA transcription from RNA   polymerase III promoter | 14 | GO:0006383 | transcription from RNA polymerase   III promoter
GO:0042797 | tRNA transcription from RNA   polymerase III promoter | 31 | GO:0006383 | transcription from RNA polymerase   III promoter

- The 'regulation of transcription' should remain (and be made findable so that the terms get used). 
- The only problem with this proposal is that the regulation terms have the following equivalence axioms: for eg GO:0042795 | snRNA transcription from RNA polymerase II promoter

> biological_process
> and (regulates some 'snRNA transcription by RNA polymerase II')

but if that latter term is not available anymore we'll need to change that. I see two options: 
A. remove the logical definition, so that these terms are just "is_a regulation of transcription by RNA polymerase II"
B. Make the terms in the above list 'do not annotate', so that the terms exist just to create the logical definitions. 

@cmungall @ukemi @thomaspd 
I suppose that our best practices mean that we should use option B? 

Thanks, Pascale

**Comment by pgaudet** [comment]
New proposal coming soon

**Comment by rachhuntley** [comment]
I see why you want to do this, but in the previous proposal didn't Karen say that curators were not encouraged to assume that all mRNA transcription is via PolII and that there are exceptions? In this proposal curators would be forced to choose PolII.

Additionally I worry about how users can currently, easily, pull out e.g. all proteins that regulate pri-miRNA transcription since most people are unaware of the annotation extensions where this detail would be kept and it is difficult in existing tools to access this information. On this point as well, curators would have to not only add to the extension the identifier of the gene that is transcribed but also an SO term describing the type of product. In our case we use Ensembl gene identifiers for a miRNA gene, so the user would have to do further processing of the data to find out what type of product this is, if we don't add the SO term.

As an aside, the term pri-miRNA transcription from RNA polymerase II promoter has only been used 10 times but all of these are since 2016, reflecting the fact that this is a new area of research and miRNA-related annotations have only recently started to be curated (the term was only created in 2014) - so I don't think you can cite number of uses as a reason to remove a GO term.
