### ISSUE TITLE
GO:0031261 definition modification

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15018]
Hi ,
I am struggling with the GO:0031261 DNA replication preinitiation complex.
Indeed I've found in literature many definitions of the complex in terms of components, find below few examples, so I was wondering whether you can consider to make the definition a bit broader, as such I suggest the following modification (in bold) of the definition:

A protein-DNA complex assembled at eukaryotic DNA replication origins immediately prior to the initiation of DNA replication. The preinitiation complex is formed by the assembly of additional proteins onto an existing prereplicative complex. In budding yeast, the additional proteins **might** include Cdc45p, Sld2p, Sld3p, Dpb11p, DNA polymerases, and others; in fission yeast the GINS complex is present. PMID:12694535 PMID:15194812

GOC:lnp

References:

Using a directed approach, we have shown that **Sld2 and Sld3** are the minimal set of essential S-CDK substrates required for DNA replication in budding yeast (17167417).
After assembly of these proteins at replication origins, **Cdc45p, Sld2p, Sld3p, Dpb11p, DNA polymerases and other replication proteins** are recruited to the replication origins to initiate DNA synthesis (12694535)
In 1992, a report by Li and Alberts1 appeared in these pages to comment on a seminal discovery2 — the identification of the protein factors from the budding yeast Saccharomyces cerevisiae that recognize the spots on DNA for initiating the DNA-replication phase of the cell cycle. Finding this 'origin-recognition complex' was one task, however; identifying the participants in the actual switch that starts DNA synthesis is another. This latter achievement is now described in papers by Zegerman and Diffley3, and by Tanaka et al.4, on pages 281 and 328 of this issue. At the heart of this intricate process is the phosphorylation — and thus activation — of two proteins known as **Sld3 and Sld2, and the involvement of a third named Dpb11** (17230184).

**Comment by krchristie** [comment]
I agree this seems too specific. I've done the edits but there is an issue with the checking pipeline now, so it will go in as soon as that is back up.

**Comment by deustp01** [comment]
Apologies for jumping in so late. Why does the definition specify a eukaryotic complex? Bacteria and archaea also assembly complexes on their DNA that undergo orderly modification as the time for initiation of DNA replication nears - see e.g. PMID:28209641, a paper that I think @ukemi pointed out on a related ticket earlier this week. Or else, since order of assembly and functions of the complexes at each stage do differ among these taxa, maybe three terms (sibs of this current one) with taxon restraints are needed?

**Comment by krchristie** [comment]
@deustp01 - No worries Peter. Thanks for jumping in with a very good point. How about if I just make this term very generic so that it's appropriate for everything. I was wondering even as I did it if I should just delete the subunit info as too specific for the top level term.

I'll take a quick look at the annotations to the term too.

**Comment by krchristie** [comment]
So David Hill just a related ticket:  `DNA replication initiation - improve def` #9913 and pointed out a nice recent review: https://www.ncbi.nlm.nih.gov/pubmed/?term=28209641 

Having 
- read through the ticket mentioned above
- scanned through the PMID mentioned above
- noticed that the existing GO term "DNA replication preinitiation complex assembly" (GO:0071163) is `'part of' some 'nuclear DNA replication'`

I think that this term "DNA replication preinitiation complex" is not relevant to bacterial DNA replication and Archaeal is different from Eukaryotic as well. Since it looks to me like it has been carefully considered where it belongs, I am going to leave this as is, with the only slightly more general definition Birgit suggested.
