### ISSUE TITLE
Review parentage of "malonyl-CoA synthetase activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15051]
I think "malonyl-CoA synthetase activity" GO:0090409 should (also) be a child of "CoA-ligase activity" (GO:0016405).

 **GO:0090409 - malonyl-CoA synthetase activity**
 Catalysis of the reaction: malonate + ATP + coenzyme A = malonyl-CoA + AMP + diphosphate. 

 **GO:0016405 - CoA-ligase activity**
Catalysis of the reaction: substrate + ATP + CoASH = AMP + diphosphate + substrate-CoA.

**Comment by ukemi** [comment]
Looks like lots of the acid-thiol ligases are missing this parent. I will add it to them systematically.

**Comment by ukemi** [comment]
Added all that hydrolyze ATP to AMP as children of CoA-ligase activity. @deustp01  in our definition of CoA ligase, we specify ATP--->AMP. This means that technically things like succinate-CoA ligase do not classify as CoA ligases becasue they don't fit this definition, it makes ADP or GDP. Do you think this is misleading and should we relax the definition of CoA ligase?

**Comment by sjm41** [comment]
Thanks!  Can I check what will happen to the various 'fatty acid ligase' terms (GO:0015645 and children) as part of this fix?  Will they all become children of '"CoA-ligase activity"?
(The last comment on ticket  #14783 is also relevant to this.)

**Comment by ukemi** [comment]
Ah. No, they won't but it looks like all of the x-chain fatty acid-COA ligases should because they fit the definition of a CoA ligase. The long-chain fatty acid [acyl-carrier-protein] ligase activity won't. But I think all the fatty acid ligases be children of acid-thiol ligase activity? It looks to me like it they should unless you know of some that aren't in GO yet, but are not. :

CoA ligase activity= Catalysis of the reaction: substrate + ATP + CoASH = AMP + diphosphate + substrate-CoA. If you agree we should open another ticket for these additional changes and assing it to me.

**Comment by ukemi** [comment]
Ah. I see that the other ticket already asks/suggests some of the things I questioned above, so ne need to make yet another ticket. I think @hdrabkin and I should work on this together next week at the ontology workshop. I am wondering if there isn't a way to formally incorporate the chemicals into the terms descriptions to get automatic classification. A couple questions, since you sound like you have looked into this a lot:

Do you think we should relax the definition of CoA ligase activity to be: Catalysis of the reaction: substrate + nucleotide-triphosphate + CoASH = hydrolyzed nucleotide-triphosphate + phosphate + substrate-CoA?  I'm not sure how we would represent a 'hydrolyzed nucleotide-triphosphate' and the diphosphate in logical definitions. That might become probelmatic down the road when we try to tackle the cross references with ChEBI. 

If we do this, all CoA ligase activity terms should become children of acid-thiol ligase activity. At least all the ones that currently exist. I went through all of them by hand yesterday and I think that would be correct.

**Comment by deustp01** [comment]
@ukemi according to the authorities, "Ligases are enzymes that catalyze the joining of two molecules or two parts of a molecule with concomitant hydrolysis of the diphosphate bond in ATP or a similar triphosphate. Ligase is often used for the common name but in a few cases synthase[sic*] or carboxylase is used. Synthetase may be used in place of synthase for enzymes in this class." (http://www.brenda-enzymes.org/ecexplorer.php?browser=1&f[nodes]=&f[action]=open&f[change]=286 - mouse over a class name to see a tooltip with its definition)
*My Ochoa trained colleagues disagree - synthetase is correct; synthase is not - the latter term should be reserved for bond formation not accompanied by nucleotide triphosphate hydrolysis.
I guess that cleavage of ATP to AMP + PPi fits this definition, as well as cleavage to ADP + Pi.
The general dictionary definition of "ligase" deviates from this. I think we go with the biochemists here (ignoring the syn(the)tase issue and ignore the general, which is (Wikipedia):

> In biochemistry, a ligase is an enzyme that can catalyze the joining of two large molecules by forming a new chemical bond, usually with accompanying hydrolysis of a small pendant chemical group on one of the larger molecules or the enzyme catalyzing the linking together of two compounds, e.g., enzymes that catalyze joining of C-O, C-S, C-N, etc. In general, a ligase catalyzes the following reaction:

    Ab + C → A–C + b

or sometimes

    Ab + cD → A–D + b + c + d + e + f

where the lowercase letters signify the small, dependent groups. Ligase can join two complementary fragments of nucleic acid and repair single stranded breaks that arise in double stranded DNA during replication.

**Comment by deustp01** [comment]
If N is already OK to indicate A OR G OR C OR T (and if it isn't it probably should be because it''s a real parent-child relationship and useful) "hydrolyzed nucleotide triphosphate" would be NDP or NMP, whichever is generated by the molecular function that is being described. The broad ligase class does both, but any one kind of ligase does only one or the other - I don't know of any enzyme that can make a bond at the cost of one phosphate but that can make a superbond at the cost of two. The CoA-charging enzymes for example all do it at a cost of two.

**Comment by ukemi** [comment]
Thanks @deustp01! I really appreciate the input. From this it looks like we have indeed been too restrictive on our definition of 'CoA ligase activity' by specifying the ATP-->AMP + diphosphate. If we relax the definition, then all CoA ligase activities will become subtypes of acid-thiol ligase activities and I can just move the aren't and essentially undo all the children that I did yesterday. But your last sentence leads me to question the placement of terms like 'succinate-CoA ligase (ADP-forming) activity'. Seems that it does it at a cost of one, right? Ontology development, it's so simple!

**Comment by ukemi** [comment]
'The broad ligase class does both'. That's the hard part, I'm not sure how we would represent the class or NMP or NDP. The ones that are specific are easy.

**Comment by deustp01** [comment]
But each subclass does one or the other, so can you omit this element of the logical definition for the parent and (tediously, with many possibilities for manual error) supply the correct one for the logical definition of each subclass? For the parent, can you have something consumption of NTP input and not specify what the output is, so you get at least some connection between the logic for the parent and child classes?

**Comment by ukemi** [comment]
Yup, exactly! But not being able to formally define the parent is unsatisfying.

**Comment by hdrabkin** [comment]
Just catching up: Agree that synthase should NOT be lumped in here. 
In tRNA land, the amino acyl-tRNA synthetases are often called ligases. Somewhere in my head attic, I seem to remember a distinction about whether an enzyme-AMP intermediate is formed with ligases. I know DNA ligase does this, but the aa-tRNA synthetases do not.

**Comment by sjm41** [comment]
Thanks all!
WRT these:
>all of the x-chain fatty acid-COA ligases should become children of "CoA-ligase activity"
>I think all the fatty acid ligases be children of acid-thiol ligase activity?
>Do you think we should relax the definition of CoA ligase activity - all CoA ligase activity terms should become children of acid-thiol ligase activity

I'm no biochemist, but these proposals make sense to me based on what I've read and staring at the current GO.
I found this paper useful wrt to fatty acid ligases/acyl-CoA synthetases: PMID:17762044

(FYI: My interest in this is that we have a project within FlyBase to review the D.melanogaster enzyme classes, so using GO annotations and EC classifications as part of this.   Started with ligases, now working on isomerases, lyases next....)

**Comment by ukemi** [comment]
Hmmm. But looking at the definitions, it looks like the 
GO:0090409 - malonyl-CoA synthetase activity
Catalysis of the reaction: malonate + ATP + coenzyme A = malonyl-CoA + AMP + diphosphate.

is indeed a 

GO:0016405 - CoA-ligase activity
Catalysis of the reaction: substrate + ATP + CoASH = AMP + diphosphate + substrate-CoA.

**Comment by ukemi** [comment]
I'm going to leave this as is for the moment. If we decide to relax the definition of the CoA ligase activity, we can open it in a future ticket.
