### ISSUE TITLE
GO:0008153 - para-aminobenzoic acid biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15081]
should this term exist?
It seems to be just an intermediate in folic acid biosynthesis.

seems to only be used for
Para-aminobenzoate (PABA) synthase
(only 7 EXP annotations)

**Comment by pgaudet** [comment]
@amorgat 
@deustp01 

Do you know of any case where this is an end-product ? 
Otherwise do you have any objection to the obsoletion?

**Comment by deustp01** [comment]
Mammals don't make pABA at all; bacteria do and then metabolize it further to synthesize folate, so compounds that inhibit pABA biosynthesis (sulfanilamides) are effective anti-bacterial drugs in humans. That of course makes inhibition of pABA synthesis clinically interesting (hence, probably, the GO term) but doesn't make it an end product. As it's natively a bacterial process, perhaps Jim Hu (jimhu@tamu.edu) might be a better person to answer your question, rather than evading it.

**Comment by amorgat** [comment]
Sorry for the late reply @pgaudet 
It's always a nightmare to define pathways boundaries...

MetaCyc considers Pathway: 4-aminobenzoate biosynthesis
see http://metacyc.ai.sri.com/META/NEW-IMAGE?type=PATHWAY&object=PWY-6543&detail-level=3

Note that para-aminobenzoic acid == 4-aminobenzoic acid
Normalized compounds: para-aminobenzoate  == 4-aminobenzoate

Even this is a short pathway, IMHO, I would keep this GO term
Cheers, Anne

**Comment by pgaudet** [comment]
@ValWood I suggest I just add the link to metacyc and we can close this.

**Comment by ValWood** [comment]
Go ahead!
