### ISSUE TITLE
GO:0045499 chemorepellent activity

### ISSUE THREAD

**Issue by sandyl27** [geneontology/go-ontology#15094]
Should anything with chemorepellent activity also be GO:0090023 positive regulation of neutrophil chemotaxis?

PMCID: PMC3756559
Dipeptidyl Peptidase IV Is a Human and Murine Neutrophil Chemorepellent

CACAO

@jimhu-tamu

**Comment by vanaukenk** [comment]
@sandyl27 

If you look at the existing experimental annotations to GO:0045499 chemorepellent activity, you can see that there are gene products annotated to this term whose activity is not part of the process of GO:0090023 positive regulation of neutrophil chemotaxis.

http://amigo.geneontology.org/amigo/term/GO:0045499

Therefore, we would not want to say that anything with chemorepellent activity should also be annotated to the process of positive regulation of neutrophil chemotaxis.

**Comment by jimhu-tamu** [comment]
Sandy put this in for CACAO and it probably should have gone into the annotation tracker instead of the ontology tracker. But looking at existing experimental annotations isn't very satisfying, since it avoids the issue of whether or not chemorepellents and chemoattractants are part of the process of regulating chemotaxis more generally. This could be an annotation consistency problem.

It seems to me that there are two possibilities:

- The terms should have a relationship that would auto-propagate annotations to regulation
-  There is a distinction between attractants and repellents that regulate the activity and those that don't that we need to understand in order to provide annotation guidance.

When I look more generally at exp annotations to different flavors of regulation of chemotaxis I see things like interleukins being annotated.

**Comment by vanaukenk** [comment]
Hi @jimhu-tamu 
In the ontology, the current relationship between the MF terms 'chemoattractant activity' and 'chemorepellent activity' and the BP chemotaxis is that they are part_of 'positive chemotaxis' and 'negative chemotaxis', respectively.  
It does look like there is inconsistency in how attractants and repellents have been annotated, though, so I agree that this is an issue that should go in the annotation tracker for further review.
Sound okay?
