### ISSUE TITLE
which term for "targeting to plasma membrane"?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15116]
I want to annotate genes involved in palmitoylation to their role in "localization to the plasma membrane"

Currently  we have these are annotated to 
GO:0061951    establishment of protein localization to plasma membrane

this is defined as 
The directed movement of a protein to a specific location in a plasma membrane.
so I don't think this is the correct term to use?

"directed movement" is the standard definition for "transport" so anything which has this definition should be   a "transport" term, not an "establishment of localization" term?

In fact, if you follow the ontology up to the definition of "establishment of localization" 
the definition is *much* broader
Any process that localizes a substance or cellular component. This may occur via movement, tethering or selective degradation.

 This is a more correct definition for establishment (not sure about  selective degradation? but presumably there is an example)....in fact this should probably also include 'targeting' too?

**Comment by pgaudet** [comment]
Hi @ValWood 
'Targeting' was defined at the signal - ie it mostly refers to the protein *bearing* the tag, so in that sense it's not a great term since we don't annotate targets. 

For the palmitoylation, how about 'regulation of plasma membrane localization'? 

Pascale

(see also related ticket #14219)

**Comment by krchristie** [comment]
This seems like more of an annotation question than an ontology question, so I'm going to close the ticket as I don't see any ontology work here. 

I will also say that this seems like something best done with a GO-CAM model since the palmitoylation is required for membrane association, but is not necessarily the step that is regulating membrane association or determining which membrane is associated with. @ukemi - any other comments on how to annotate this situation?

Ray A et al. Lipidated proteins: Spotlight on protein-membrane  binding interfaces. Prog Biophys Mol Biol. 2017 Sep;128:74-84. doi:10.1016/j.pbiomolbio.2017.01.002. Epub 2017 Feb 3. Review.  PMID:28167047

> 4.3. Differential membrane localization
> 
> While all lipidated proteins share membrane-binding property, they differ strikingly in their plasma membrane and subcellular membrane localization. This differential membrane association implies a more complex regulatory role for the protein's biological activity.
