### ISSUE TITLE
cardiac muscle cell death

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15189]
I would like to see "cardiac muscle cell death” added to the GO ontology under the parent term "cell death” (GO:0008219).  The definition could be "The process of cell death in a cardiac muscle cell.”  Example can be found in PMID:26593335.

**Comment by ukemi** [comment]
apoptosis?

**Comment by slaulederkind** [comment]
The data in this reference isn't apoptosis-specific.  If you decide to add this term, we need the "regulation of ..." terms also.  Thanks.

**Comment by hdrabkin** [comment]
Hi Stan
I'd like to look at this paper, but the "Connection refused by linkinghub.elsevier.com, please try again later. ", which means elsevier is having issues with our proxy. Can you attach or email me the pdf? Thanks

**Comment by ValWood** [comment]
Out of scope? Should be some PCD term + cell type?

**Comment by hdrabkin** [comment]
cardiac muscle cell death: can this be put into extension during annotation? go term cell death + extention CL cardiac muscle cell?

**Comment by pgaudet** [comment]
Hi @slaulederkind 

We looked at the paper and this does not seem to be a normal process. 'Cell death' in itself is not convincingly defined as a normal process, but that's another issue maybe. 

However we dont want to create a specific term for cell death in specific cell types, because there is no evidence that this is a separate process in itself. 

Thanks, Pascale
