### ISSUE TITLE
protein homohexamerization

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#15211]
I would like to see "protein homohexamerization” added to the GO ontology under the parent terms "protein homooligomerization” (GO:0051260) and “protein hexamerization” (GO:0034214).  The definition could be "The formation of a protein homohexamer, a macromolecular structure consisting of six noncovalently associated identical subunits.”  Example can be found in PMID:20161783.

**Comment by ukemi** [comment]
Do we really want to continue down this route of activities? We discussed this a little last week.

**Comment by pgaudet** [comment]
I really thing these are components. If this is really important to capture, we could add to 'protein containing complex': 
- protein dimer
 -protein trimer
- protein tetramer
(and even the homo and hetero version of those). 

Would that be a solution ? 

Thanks, Pascale

**Comment by slaulederkind** [comment]
Definitely sounds good.  I've long thought that dimer, trimer, etc belonged in cellular component.

**Comment by bmeldal** [comment]
Links to this old and still undecided ticket:
https://github.com/geneontology/go-ontology/issues/11094

**Comment by pgaudet** [comment]
@ukemi Can we put this on the top of the list for the next editors call ?

**Comment by ValWood** [comment]
Personally I would prefer not to represent stoichiometry in GO. 
It seems out of scope. We already have a simple  independent system to capture this , but to me it isn't really a cellular component or localization either.

**Comment by bmeldal** [comment]
We capture stoichiometry in the CP directly (and for each participant of the complex), not by using GO annotations. And we don't really annotate the assemblers beyond "complex assembly/scaffolding" etc terms.

**Comment by RLovering** [comment]
Hi

I am fine with MF: homodimerization being CC homodimer.

However, can we keep MF: GO:0042802 identical protein binding

And change the parent of GO:0043496 regulation of protein homodimerization activity
This has 29 manual expt annotations.

To > regulation child of GO:0042802 identical protein binding

Ruth

**Comment by RLovering** [comment]
Also Val
please would you explain how PomBase captures this in a 'simple independent system' and why PomBase feels it is necessary to capture this data. 

Thanks

Ruth

**Comment by ValWood** [comment]
Well we have always captured it if it is reported,  because it is there, but we didn't ask to put it into GO because it seems out of scope. So we just record it in a separate table. I don't really want to convert it all to GO annotation as it doesn't really seem  to be a good fit?

Its something I'm not even sure it is much used by our community. 

I thought we had discussed many times over the years to move this out of GO ....it just seems to be orthogonal  info to F,P and C to me....

**Comment by ValWood** [comment]
Our system basically involves  recording
monomeric
homomeric(2)
homomeric(4)
heteromeric(2)
heteromeric(10)

(we need to add a number to capture the stoichiometry)

We display this in a separate section of the gene page. It doesn't really link to the information captured by GO annotation.

**Comment by hdrabkin** [comment]
I've always thought that IF (big if) the dimer/etc. is self-assembling, it is an important point. However, I also realize that there could be other factors that could influence the rate of an assembly so we have self-assembly processes that could be regulated (say by phosphorylation/dephosphorylation). 
If not 'self-assembling' then  doesn't protein complex assembly already suffice?

Anyways, if we wanted to scratch these and move them to cc, I would not object.

**Comment by pgaudet** [comment]
Hi all, 

I see @ValWood 's point but if people find it convenient I think these are fine as CC. 

WRT assembly - would it not be sufficient to just have 'GO:0065003 protein-containing complex assembly'? is it really a different process to assemble a dimer versus a trimer, etc ? 

Pascale

**Comment by hdrabkin** [comment]
What was the resolution to this?

**Comment by krchristie** [comment]
My recollection was that there was general agreement that biological process terms of this type are NOT appropriate since there are not general processes involved in dimerization, homoheximerization, etc.

I am not clear on whether or not there was agreement that having component terms to represent these types of terms would be appropriate.

**Comment by hdrabkin** [comment]
So, I would
1. decline this request, which would close this ticket but
2. DO we OBSOLETE all terms under GO:0042802 identical protein binding (there appears to be just  one, homodimerization (or merge it into 42802)
3. the process terms are a mess
   Protein protein homooligomerization,

**Comment by ValWood** [comment]
> the process terms are a mess
Protein protein homooligomerization,

Agreed, and the annotations for most of these are just  "things that  form oligomers"
absolutely no indication  that these are involved in the process of "homooligomerization"
I'd obsolete them all.....
We agreed to get rid of these lots of times. I'm sure it is in the minutes of more than one consortium meeting....

**Comment by ValWood** [comment]
First one I looked at:
http://www.uniprot.org/citations/22486860
In support of this model we demonstrated that TgCactin is present in a protein complex and can oligomerize.

**Comment by hdrabkin** [comment]
I just accidentally deleted my thread with the scope; #!!$#; @ValWood  you replied to my  partial response that I accidentally saved and then lost. Friday; I'm getting too old for this. 
Basically, I was going to suggest that they are all protein complex assembly (because the parent for all of them is GO:0051259, protein complex oligomerization (strangely there is no link between this term and protein complex assembly).

**Comment by ValWood** [comment]
Harold you said this:

So, I would

    decline this request, which would close this ticket but
    DO we OBSOLETE all terms under GO:0042802 identical protein binding (there appears to be just one, homodimerization (or merge it into 42802)
    the process terms are a mess
    Protein protein homooligomerization,


I thought you just changed your mind; )

**Comment by hdrabkin** [comment]
No @ValWood , there was actually more following the "Protein protein homooligomerization.

And a weird one is protein heximerization, a child of protein heterooliogomerization,; it's def says either identical or non-identical subunits; that was I flag as a draw and quarter (beyond just kill)!

**Comment by hdrabkin** [comment]
Definitely not changing mind

**Comment by pgaudet** [comment]
I think we should obsolete. I don't think that merging into 'protein complex assembly' would be correct since many annotations represent that the protein is *part of* the complex (including the complex Stan was proposing to annotate, as far as I can tell - @slaulederkind please correct me if this is wrong. 

I think some people have objections because they want to capture the stoichiometry of complexes (or perhaps other reasons?)

Would anyone that have objections please explain the reasoning? (should we email go-consortium to get a wider response ?) 

Thanks, Pascale

**Comment by ValWood** [comment]
It was discussed lots of times, but in most detail at the Barcelona meeting
It is not clear from the minutes or the actions precisely what the decision was (there ia an action item but it is rather vague):

https://docs.google.com/document/d/1NonH97s8xEpDdx6DfonKPKI_RdHbbG-yft85UZtUmF0/edit#

but I thought the action was to get rid of the process terms, which are largely  used correctly to represent 'binding' rather than assembly.

Perhaps it just wasn't implemented? Maybe @paolaroncaglia  remembers (you presented on the issue at this meeting?)

**Comment by paolaroncaglia** [comment]
Hi @ValWood et al,
Here's the ticket I created just before leaving a year ago, it collects links to discussions and proposals, including what were the latest ones at that time:
https://github.com/geneontology/go-ontology/issues/13036
Good luck :-)
Paola

**Comment by ValWood** [comment]
@paolaroncaglia Thank you!
