### ISSUE TITLE
NTR cell adhesion receptor activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#15237]
Hi

please can we revisit the fact that some (not sure if this is all) adhesion molecules have receptor activity. In that they activate intracellular pathways that lead to changes in transcription and potentially differentiation of the cell. 
https://www.ncbi.nlm.nih.gov/pubmed/?term=29415483 (Integrins)
https://www.ncbi.nlm.nih.gov/pubmed/?term=29413845 (cadherins)

Ideally I would like the editors to consider reinstating the term: GO:0004895 cell adhesion receptor activity.  

Another option might be to create the term:
GO:0098631 cell adhesion mediator activity
> is_a Child new term: cell adhesion mediator receptor activity
GO:0004888 transmembrane signaling receptor activity
> is_a Child new term: cell adhesion mediator receptor activity

Note that this issue came to light with the annotation github ticket (https://github.com/geneontology/go-annotation/issues/1827) when Helen identified that several fly adhesion proteins were annotated to the GO term receptor activity.

Thanks

Ruth

@hattrill @pgaudet

**Comment by pgaudet** [comment]
@RLovering 
I thought you wanted something like 'cell adhesion signaling receptor activity'... ?

**Comment by RLovering** [comment]
yes please, I was trying to keep the name short but with the parent GO:0004888 transmembrane signaling receptor activity I assumed this would be implied.

**Comment by pgaudet** [comment]
xref: https://www.ncbi.nlm.nih.gov/books/NBK6259/

**Comment by pgaudet** [comment]
Hi @ukemi @rachhuntley 

- Since you are working on ECM I wanted to run these changes in definitions by you two. (I know that these terms were reviewed not too long ago but I could not find the ticket. I hope the proposed changes are not just reverting some other changes - if you know where that other ticket is please link it here)

- I noticed some inconsistencies in the definitions of the parent term: 
GO:0098631 cell adhesion mediator activity
Definition
    Any binding by a cell surface protein to a molecule external to the cell, that meditates adhesion of the cell to that external substrate. 
    -> 'external substrate' is WRONG

**- PROPOSED CHANGES
REINSTATE** 
-- GO:0004895 cell adhesion receptor activity
Definition
	The binding by a cell-adhesion protein on the cell surface to an extracellular molecule, to meditate adhesion of the cell to the external substrate or to another cell and to initiate intracellular signaling. Cell adhesion receptors include integrins and cadherins.  
	cross ref:  Wikipedia:Cell_adhesion


**GO:0098631 cell adhesion mediator activity: NEW DEFINITION**
Definition
	The binding by a cell-adhesion protein on the cell surface to an extracellular molecule, to meditate adhesion of the cell to the external substrate or to another cell. 
	cross ref:  Wikipedia:Cell_adhesion


**GO:0098632 cell-cell adhesion mediator activity: NEW DEFINITION**
Definition
   The binding by a cell-adhesion protein on the cell surface to an extracellular molecule, to meditate adhesion of the cell to another cell. 
   cross ref:  Wikipedia:Cell_adhesion


**-- GO:0098634 cell-matrix adhesion mediator activity : NEW DEFINITION**
Definition
    The binding by a cell-adhesion protein on the cell surface to an extracellular molecule, to meditate adhesion of the cell to the extracellular matrix.
    cross ref:  Wikipedia:Cell_adhesion






This seems relevant to the ECM project (please include the ticket in the project if appropriate).

**Comment by rachhuntley** [comment]
Hi Pascale,
Is this the ticket you were referring to: https://github.com/geneontology/go-ontology/issues/5555

The only thing that I have a question about is 'cell-matrix adhesion mediator activity'. The current definition "Any binding by a cell surface protein to an extracellular matrix molecule that meditates adhesion of the cell to the matrix." is clear what type of extracellular protein is involved, whereas the new definition is less clear - is this on purpose? Is the "extracellular molecule" always an extracellular matrix protein?

**Comment by pgaudet** [comment]
@rachhuntley 
Good question! 

I was trying to reflect the idea that perhaps the binding to the EMC is via a molecule that is something else than a protein, but maybe this never occurs? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Updated definition to 'extracellular matrix component' rather than 'extracellular molecule' for now. 

@rachhuntley will have another look to check if it's OK. 

Pascale

**Comment by rachhuntley** [comment]
Having looked at the terms and definitions again, I think this is fine now with the updated definition.
But make sure you change 'meditate' to 'mediate' in all these definitions :)

**Comment by pgaudet** [comment]
Good catch ;)

**Comment by RLovering** [comment]
;)
