### ISSUE TITLE
Query nucleobase-containing small molecule metabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15250]
Hi @ValWood 

It looks like you are the one who requested 'nucleobase-containing small molecule metabolic process'. It seems to have been intended as a grouping term for nucleobases, a nucleosides, and nucleotides; right ? 

Just wondering because (1) I am trying to add logical definitions but I dont think ChEBI has the equivalent process, right? 
(2) the respective 'metabolic' and 'catabolic ' children don't have any children; I suppose you also want the grouping at that level ? 

Thanks, Pascale

**Comment by ValWood** [comment]
That correct. 

This grouping is a really useful slim module...
https://www.pombase.org/term_genes/GO:0055086
It has 199 pombe annotations all involved in "nuclotide/side/bas metabolism". There is overlap between these processes.

If you move up to the parent 
GO:0006139 - nucleobase-containing compound metabolic process
(so for pombe this has pombe 1494 annotations) so  is way too broad. 
It has nucleic acid metabolic process (DNA metabolism, transcription, translation)  and lots of other stuff. GO:0098501    polynucleotide dephosphorylation!

 I'm not even sure what is in there ... but it isn't useful because it has such unrelated stuff.....

**Comment by pgaudet** [comment]
So I should add correct children to the biosynthetic/catabolic processes then?

**Comment by ValWood** [comment]
Oh yes they should be there!

**Comment by deustp01** [comment]
And I guess Val wants to exclude metabolism of nucleotide sugars - a standard biochemistry distinction not made by ChEBI. Indeed, that looks like an important part of the problem here - the ChEBI classification scheme clashes with the GO functional classification. Comments, @ukemi ?

**Comment by ValWood** [comment]
Yes for sure!

**Comment by deustp01** [comment]
Expand on the cryptic request to @ukemi - when we were thinking about glycolysis, didn't we decide that the logic required us to allow something like glycolysis is_a nucleotide metabolism because ATP is_a nucleotide. Val clearly wants to be less tolerant and inclusive, and this kind of problem is going to recur (for example because ATP usage is fairly widespread). Any thoughts about a general strategy?

**Comment by ukemi** [comment]
Yes. But I think that is a different question than the one being considered here. Based on our definition of metabolic processes, we had decided this was ok because any process that used a molecule was a type of metabolism of that molecule. 

I think the issue here is the creation of a grouping class that includes only nucleobases, nucleosides and nucleotides. This class appears not to exist in ChEBI. It seems that this class isn't really based on chemical structure, but is more of a custom made class that represents a hand-picked set of processes. Perhaps this is a good argument for asserted subclasses.

**Comment by alanbridge** [comment]
Might GO consider classifying reactions based on their "main pairs" (a concept borrowed from KEGG) - as these might fit more closely with the biological aim - and set aside more common "hub" metabolites - that generally serve the same role in many reactions?

So for a reaction like this: 

a cholesterol ester + H2O = a fatty acid + cholesterol + H(+)

(http://www.rhea-db.org/reaction?id=36403)

the main pairs might be: 

a cholesterol ester - cholesterol 
a cholesterol ester - a fatty acid

So this is an example of cholesterol, cholesterol ester, and fatty acid metabolism. The function of the enzyme is to regulate the levels of these metabolites rather than water (although H2O is essential in this hydrolase of class EC 3.1.1.13). 

This issue of "hub" metabolites is one that is often considered in the context of metabolic networks; people might make connections between reactions only through main pairs. Might this be of use in reaction (function) classification as well as connection?

**Comment by ValWood** [comment]
I like this grouping term for slimming because the 3 processes have a  large number of genes in common. Some of the sub processes are more closely biologically connected to each other between processes than within, which makes it a sensible module to include in a slim set.

![grouping](https://user-images.githubusercontent.com/7359272/36603105-ab613faa-18b1-11e8-82ee-44d929d5fca5.jpg)

Alan's suggestion sounds interesting.

**Comment by ValWood** [comment]
Actually this just cropped up again for a figure I am trying to prepare:

nucleobase-containing compound catabolic process (GO:0034655)

should be a child of "small molecule catabolic process"

currently it isn't. Could that be added too?

**Comment by ValWood** [comment]
updated comment above thus:

I like this grouping term for slimming because these 3 processes have a  large number of genes in common. Some of the sub-processes of the second descendant (grand children) are more closely biologically connected to each other than those  of the first descendant (children), which makes it a sensible module to include in a slim set.

**Comment by pgaudet** [comment]
Hi @alanbridge 
as far as I understood your comment, GO is already doing that with logical definitions, any participating molecule should inherit x metabolic process; isn't it already the case ? @ukemi is this right ?

**Comment by ukemi** [comment]
Yes and No. We don't have many logical definitions for functions. But if it is a participant in a metabolic process it is reasoned to be a type of that metabolism. There are nuances that get very tricky. We should discuss strategies in NYC.
