### ISSUE TITLE
block  BP term  "GO:0065009    regulation of molecular function" for direct annotation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15263]
This term  isn't informative about a biological process-  if it is the only annotation that can be made. BP ND is better.

Currently we are picking up  MF-BP links to this term.
SPAC21E11.06.1 GO:0065009 regulation of molecular function GOC
SPAC24H6.09.1 GO:0065009 regulation of molecular function GOC
SPAC343.14c.1 GO:0065009 regulation of molecular function GOC
SPAC4D7.09.1 GO:0065009 regulation of molecular function GOC
SPBC19G7.08c.1 GO:0065009 regulation of molecular function GOC

At present PomBase don't have an active  MF-BP pipeline, 
we are waiting for https://github.com/geneontology/go-site/issues/524

~so I think we are getting these from GOA?~
actually we are currently importing via the old pipeline

**Comment by ValWood** [comment]
@cmungall 
@pgaudet

**Comment by pgaudet** [comment]
According to QuickGO, this comes from 
GO:0005089  guanyl-nucleotide exchange factor activity 
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/4782928/36671946-7b1b2baa-1acb-11e8-8291-e77a0cf7e0bf.png">

Since there are already annotations to 'protein binding', I agree that the inferences should not go higher than the experimentals. Also, we should anyway avoid making assertions to the roots. 

@cmungall I suppose the script needs to be changed ? 

Thanks, Pascale

**Comment by ValWood** [comment]
> I agree that the inferences should not go higher than the experimentals

This is in
https://github.com/geneontology/go-site/issues/524#issuecomment-364637813

**Comment by ValWood** [comment]
> Also, we should anyway avoid making assertions to the roots

I think it might be difficult not to have the relationships, if they are true. This should just be blocked for direct annotation....

**Comment by pgaudet** [comment]
@cmungall 
Do you have an idea of how to address this ? We can't just put a 'do not annotate' tag on the root, since that term is otherwise allowed. (I think this ticket should be assigned to a software developer). 

Thanks, Pascale

**Comment by ValWood** [comment]
It isn't the root, it's 
GO:0065009 regulation of molecular function
v

**Comment by cmungall** [comment]
Put  GO:0065009 in the do_not_annotate subset and all should hopefully be good
