### ISSUE TITLE
Updates to biofilm matrix (GO:0097311)

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15299]
Biofilm matrix (GO:0097311) needs taxon constraint: only_in_bacteria*. 

Add synonyms: EPS matrix, exopolysaccharide matrix. 

Update definition: ‘...and the biofilm matrix is the envelope of polymeric substances that surrounds the bacteria’ 
to '...and the biofilm matrix consists of polymeric substances, proteins, lipids and nucleic acids that surrounds the bacteria.'
(PMID:20676145)

*But do fungi have an ECM – is it the same as the biofilm matrix? Currently 73 proteins (mostly Candida albicans) annotated to biofilm matrix, only one protein annotated to extracellular matrix from Coprinopsis cinerea (Q06100 Galectin-1). @ValWood @srengel ?

**Comment by ValWood** [comment]
Googling "fungal extracellular matrix" it seems that some fungi do have and extracellular matrix that is distinct from the cell wall.... I didn't know that....

**Comment by rachhuntley** [comment]
So this paper describes the componenets of the C. albicans biofilm matrix, which looks fairly similar to the description of the bacterial biofilm matrix.
[C_albicans_biofilm_matrix.pdf](https://github.com/geneontology/go-ontology/files/1775135/C_albicans_biofilm_matrix.pdf)

Based on this, could this term be expanded to include both bacterial and fungal biofilm matrices?

**Comment by deustp01** [comment]
A priori (i.e. with zero knowledge of the chemistry and physiology) it seems risky to lump these two kinds of biofilm together given all the differences between the two taxa in when and how the films form and what the functional consequences are. If indeed these differences exist, maybe split the existing term with differentia from the chemical differences between the two kinds of film? (E.g., maybe fungal films lack lipopolysaccharide?)

**Comment by rachhuntley** [comment]
I also have zero knowledge of the chemistry and physiology...which is why I'm hoping someone can weigh in on this. I agree that if they are sufficiently different in composition or function there should be distinct terms.

Strangely though, the term is defined for bacteria, but it has mostly been used for annotating fungal proteins.

Here is another reference comparing fungal and bacterial biofilm matrices:
http://www.jbc.org/content/291/24/12529.full

There appear to be many similarities in composition and function but also some differences - whether they are different enough to warrant two terms, I can't say.

Here are some quotes from the paper:
"These fungal biofilms share many similarities with those of bacteria, including the presence of secreted exopolysaccharides as core components of the extracellular matrix."

"Despite a lack of sequence homology with bacterial exopolysaccharide biosynthetic enzymes, there are striking similarities in the function and organization of these fungal exopolysaccharide biosynthetic proteins and the role of the resulting glycans in biofilm formation, drug resistance, and immune evasion."

**Comment by srengel** [comment]
fungi definitely make biofilms, but i don't know much off the top of my head about the molecular differences between fungal and bacterial biofilms.  just to complicate things, i do know biofilms can be made up of a mix of organism_types.

that said, i agree that fungal proteins should not be annotated to GO:0097311 because the definition is specific to bacteria.

**Comment by dianeoinglis** [comment]
I've worked directly with Candida biofilms and curated most of the Candida biofilm matrix proteins. I think we ignored the bacteria-specific definition I partly because we thought it was inadvertant. Bacterial biofilms have been studied for longer than fungal biofilms and fungi are often overlooked. The similarities in function of bacterial and fungal matrices are significant. @srengel made a good point about multiple species biofilms which are common and a good result would be to have a general "microbial" term as the parent to taxon-specific child terms, NTR: 'bacteria biofilm matrix' and NTR: fungal biofilm matrix.' CGD has 74 annotations to 'biofilm matrix'' that would need review.

**Comment by pgaudet** [comment]
Hi @rachhuntley 
Sorry, late question here: why are the two terms needed ? I can see if there was an issue with respect to parentage; is this the case ? Otherwise, what's the risk of confusion here, to annotate multiple species to the same term if the structure is analogous enough ? 

Thanks, Pascale

**Comment by rachhuntley** [comment]
HI Pascale,
We were guided by the comments above, which suggested two terms would be preferable.
Rachael.

**Comment by ValWood** [comment]
I'm not convinced that this is a cellular component, at least for fungi.

The linked paper describes a biofilm as a "conglomeration of self-produced exopolymeric material" it isn't part of an organism in which case  it doesn't belong in GO CC.

Biofilm formation would be OK as a process to make a biofilm....

**Comment by rachhuntley** [comment]
Hopefully @dianeoinglis can weigh in here, since she mentioned she had created most of the Candida biofilm matrix proteins.

**Comment by marekskrzypek** [comment]
I am with Val on this. To me, biofilm is a way individual cells position themselves in relation to other cells, environment (surfaces), and cells of other species. It's sort of like a colony. It is not GO CC.
But obviously biofilm formation is an important process and belongs to GO BP.

**Comment by rachhuntley** [comment]
Note, there is an annotation review ticket open to address the annotations, that Marek will deal with.
https://github.com/geneontology/go-annotation/issues/1964

**Comment by ukemi** [comment]
But the GOC policy was and as far as I know has always been that the term is represented by the definition, not the label. If we want to discuss changing that policy, then we should. But in this case, to be consistent with policy we had to choices, to obsolete the term or to change the label and ask to re-annotate. Either way would have required re-annotation.

**Comment by rachhuntley** [comment]
The annotation review for this is now complete, so all annotations are on the correct terms. Were there any more concerns over these terms?

**Comment by ukemi** [comment]
Closing this one. If we need to discriminate, we will open another ticket.
