### ISSUE TITLE
Typo in def of "amine-lyase activity"?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#15291]
**amine-lyase activity ; GO:0016843**
Def: Catalysis of the release of amides by the cleavage of a carbon-nitrogen bond or the reverse reaction with an amine as a substrate. (EC: 4.3.3.-)

Should "release of amides" be changed to "release of amines"?

Compare to:
**amidine-lyase activity ; GO:0016842**
Def:  Catalysis of the release of amides or amidines by the cleavage of a carbon-nitrogen bond or the reverse reaction with an amide or amidine as a substrate. (EC: 4.3.2.-)

**Comment by krchristie** [comment]
Seems reasonable based on the page for EC 4.3, http://www.sbcs.qmul.ac.uk/iubmb/enzyme/EC4/3/  which says: 

> This subclass contains the enzymes that release ammonia or one of its derivatives, with the formation of a double bond or ring. Some catalyse the actual elimination of the ammonia, amine or amide, e.g. [snipped rest since structures won't paste well]

@hdrabkin - Does this suggestion look OK to you?

Also, I wanted to check about the fact that these two terms have database cross-references to incomplete EC numbers, though in the format of EC:4.3.2, rather than the EC:4.3.2.- format which
if I remember correctly, you were trying to get rid of. Or are you OK with these ones that are explicitly the grouping terms that match the EC grouping terms?

**Comment by hdrabkin** [comment]
a  .- will be spit out in Travis at the moment; if  a grouping term but in as EC:4.3.2 as an xref; you could use a .- in the definition reference I think, but have not tried it with a new term.

**Comment by krchristie** [comment]
@hdrabkin - I'm not sure my questions were clear. I'll rephrase.

1. Do you agree with the submitter's suggestion to change the definition of 
amine-lyase activity (GO:0016843) from 
"Catalysis of the release of **amides**" to "release of **amines**"

2. I am asking about **existing** EC dbxrefs in the form of EC:1.2.3, rather than EC:1.2.3.-, i.e. EC numbers that only have 3 digits, but do NOT include the dash. Are you trying to remove these?

**Comment by hdrabkin** [comment]
yes, am removing 3 digits but not from grouping terms; only the children (more specific) of the grouping terms.

**Comment by krchristie** [comment]
Thanks @hdrabkin !!

**Comment by sjm41** [comment]
Thanks Karen!

**Comment by krchristie** [comment]
@sjm41 - Thanks for pointing out the typo! Sorry so slow to fix it.
