### ISSUE TITLE
Plant extracellular matrix

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15306]
Do plants have an ECM? This GitHub ticket suggests we should not use ECM for plants (https://github.com/geneontology/go-ontology/issues/12508).

But there are two child terms of extracellular matrix component that refer to plant structures
(There is also 'middle lamella' but I've commented about this in GitHub #15305)

1. pollen coat (GO:0070505) is described as an ECM: "A layer of extracellular matrix deposited onto the surface of the pollen wall..."  
If pollen coat is actually a type of ECM then it should be is_a ECM, not is_a ECM component (which I am proposing to obsolete in #15294).

2. pollen wall (GO:0043667). Should this be is_a cell wall or part_of extracellular region instead of is_a ECM component? Also, the comment accompanying this term refers to an obsolete GO term GO:0048196.

@tberardini any thoughts?

**Comment by tberardini** [comment]
1. pollen coat - I agree, @rachhuntley , this should be is_a ECM
2. pollen wall - the curator who added/requested this is GOC:fz (Felipe Zapata from Plant Ontology project, at some point in time) - let's ask @cooperl09 for advice

**Comment by rachhuntley** [comment]
See also my comment on #15307 regarding the ontology under GO:0030312 external encapsulating structure.

**Comment by cooperl09** [comment]
Plants definitely have an extracellular matrix- I agree with @rachhuntley's  and @tberardini's comment above that pollen coat (GO:0070505) should be an is_a extracellular matrix (GO:0031012)
Here a good reference for background: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5217362/

re: "pollen wall (GO:0043667). Should this be **is_a cell wall** or **part_of extracellular region** instead of is_a ECM component? "

The pollen wall (GO:0043677) consists of the intine (GO:0043678) and exine (GO:0043668) layers- both are children of GO:0044420 extracellular matrix component. This is not a cell wall per se as it encapsulates more than 1 cell.  
I don't think that making it part_of 'extracellular region' is appropriate (what would the is_a parent be?)

 Perhaps it would be best as a sibling of cell wall- an " external encapsulating structure (GO:0030312)", although that def'n would need to be tweaked slightly to include one or more cells. 
And it should be part_of the pollen (PO:0025281).

The GO hierarchy is confusing around the ECM, the extracellular region' and the 'encapsulating structure'- I probably need to study it a bit more.

**Comment by rachhuntley** [comment]
Thanks Tanya @tberardini and Laurel @cooperl09 for your comments. Based on your comments, I propose the following changes:

1. Pollen coat (GO:0070505)
- Change pollen coat to is_a extracellular matrix. Remove relation is_a ECM component

2. Pollen wall (GO:0043667)
- Change definition of external encapsulating structure GO:0030312 to encompass more than one cell, i.e. "A structure that lies outside the plasma membrane and surrounds the entire cell **or cells**. This does not include the periplasmic space.” 

- Make pollen wall is_a external encapsulating structure GO:0030312

- Remove relation is_a ECM component from pollen wall

- Add relation to PO: part_of pollen (PO:0025281)

- Remove the comment associated with pollen wall as this refers to an obsolete GO term (Comment: Note that this term is a child of 'extracellular matrix part ; GO:0044420' rather than the more specific middle lamella-containing extracellular matrix ; GO:0048196', because unlike the usual plant cell wall, the pollen wall does not contain a middle lamella, as specified in the definition of 'middle lamella-containing extracellular matrix ; GO:0048196'.)  

- Update definition of pollen wall to “The wall surrounding a mature pollen grain; a multilayered structure consisting of a pectocellulosic intine surrounded by a sporopollenin-based exine, which itself contains two layers, the inner nexine and the outer sexine”.  Ref: PMID:15131249. 

Does this sound acceptable to everyone?

Thanks,
Rachael.

**Comment by cooperl09** [comment]
This sounds good to me, thanks for getting it straightened out.
