### ISSUE TITLE
Ubisch body parentage

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15307]
Ubisch body (GO:0070645): is this part of the pollen coat? Is currently is_a extracellular matrix component.
See also #15306

@tberardini

**Comment by tberardini** [comment]
From the articles linked as references for this term (added by Emily Dimmer and Midori Harris?), it looks like Ubisch bodies are part of the tapetum, " a metabolically active sporophytic cell layer that surrounds the sporogenous cells. " (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC283618/)  Also, "They arise as pro-orbicules in the tapetum and are extruded to the locular side where they acquire a sporopollenin coat and remain attached to the peritapetal wall (17)."

This suggests that they are not part of the pollen coat but proximal to it.  @rachhuntley - I trust you to decide where this belongs. Without reading many more papers, it looks like some people have found it in the pollen coat and many in the tapetum.  Coin toss?

**Comment by rachhuntley** [comment]
I think this will hinge on whether we decide if plants have an ECM or not. Just looking around some of the terms for plant sexual structures, the ontology is inconsistent. The term 'egg coat' (which I guess is equivalent to 'pollen coat') has 'external encapsulating structure' as a parent.
There is also the term 'sexual spore wall', which has no child terms, but I would expect 'pollen wall' to be an is_a child.

Would it work if we went with the idea that plants do not have an ECM and then have this ontology structure (most of this is from Wikipedia, so would need input from an expert @cooperl09 ?):

GO:0030312 external encapsulating structure
- is_a GO:NEW sporangium
-- part_of GO:NEW megaspore (produces egg cell)
--- part_of GO:0035805 egg coat
-- part_of GO:NEW microspore (produces pollen)
--- part_of GO:0070505 pollen coat
--- part_of GO:0043667 pollen wall
--- part_of GO:NEW tapetum
--- part_of GO:0070645 Ubisch body
(I'm not sure this is accurate as the pollen coat and wall are part of the pollen, which is produced by the microspore?)

As the Ubisch body is found in both the tapetum and pollen coat, then it can have 'microspore' as parent. (Although in the PO there is a tapetum for microspore and megaspore)

Then also have:
GO:0097514 sexual spore wall
- is_a GO:0043667 pollen wall

**Comment by rachhuntley** [comment]
Note: GO:0043076 megasporocyte nucleus would also have a part_of parent, GO:NEW megaspore.

**Comment by cooperl09** [comment]
RE: plant extracellular matrix - see my comments on #15306 

Note that some of the terms you are proposing are existing PO terms:
**sporangium (PO:0025094)**: A plant organ (PO:0009008) in which plant spores (PO:0025017) are produced.
**microspore (PO:0020048)**: The smaller, in general, of the two kinds of spores produced after meiosis in the life cycle of a heterosporous plant, and on germination giving rise to the male gametophyte. 
**megaspore (PO:0020019)**: "The larger, in general, of the two kinds of spores produced after meiosis in the life cycle of a heterosporous plant, and on germination giving rise to the female gametophyte (embryo sac)."
**tapetum (PO:0025313)**: A portion of ground tissue (PO:0025059) that is the inner-most layer of a sporangium wall (PO:0025306).

RE: ubisch body (GO:0070645): "A small, granular structure that is found in the extracellular matrix of cell of the secretory tapetal layer that surrounds developing pollen grains. Ubisch bodies have a sporopollenin coat, are attached to the peritapetal wall, and may play a role in pollen development."
is_a  GO:0044420 extracellular matrix component- I think this is fine

**Comment by tberardini** [comment]
@cooperl09 points out correctly that some of the new terms you have suggested are existing PO terms and belong in that ontology, not GO.

**Comment by tberardini** [comment]
You can use the existing PO anatomy terms as references without the need to create parallel GO ones.   For example:
>[Term]
id: GO:0043076
name: megasporocyte nucleus
namespace: cellular_component
def: "The nucleus of a megasporocyte, a diploid cell that undergoes meiosis to produce four megaspores, and its descendents." [GOC:jl, ISBN:0618254153]
synonym: "megaspore mother cell nucleus" EXACT []
is_a: GO:0005634 ! nucleus
**intersection_of: GO:0005634 ! nucleus
intersection_of: part_of PO:0000431 ! megasporocyte**

or 

> [Term]
id: GO:0043667
name: pollen wall
namespace: cellular_component
def: "The complex wall surrounding a pollen grain." [GOC:fz]
comment: Note that this term is a child of 'extracellular matrix part ; GO:0044420' rather than the more specific middle lamella-containing extracellular matrix ; GO:0048196', because unlike the usual plant cell wall, the pollen wall does not contain a middle lamella, as specified in the definition of 'middle lamella-containing extracellular matrix ; GO:0048196'.
synonym: "microspore wall" EXACT []
**is_a: GO:0044420 ! extracellular matrix component
relationship: part_of PO:0025281 ! pollen**

I know we're discussing 'pollen wall' parentage but the above is what's currently in the ontology and illustrates dual GO-PO usage.

**Comment by rachhuntley** [comment]
OK, will leave this as is_a extracellular matrix component.
