### ISSUE TITLE
mitotic spindle pole body separation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15304]
please rename

~mitotic~ spindle pole body separation ->mitotic spindle pole body separation

The 8 existing EXP annotations are for mitotic, we can rename the existing term.
You could add a do not annotate parent  "spindle pole body separation". We can leave the meiotic term for now as we have no data.

Note , I create these mitosis/meiosis specific terms for SPB processes because a lot of the biology (genes) for the spindle pole bodies is different in the  yeast for meiosis and mitosis. I have several examples where I needed to go back and split later. It is therefore better to capture this info first off...

**Comment by vanaukenk** [comment]
@ValWood   Here's a summary:

1) Rename GO:0000073 spindle pole body separation to GO:0000073 mitotic spindle pole body separation.

2) I see 10 EXP annotations to GO:0000073 in AmiGO, two from AspGD, eight from SGD.

3) Create a new parent, GO:new spindle pole body separation with a 'do not manually annotate' flag.

4) Update definition for GO:0000073 (see #13461)

5) Make regulation child terms mitotic as well?

**Comment by ValWood** [comment]
Yes, that's it, thanks.

Val

**Comment by vanaukenk** [comment]
@ValWood 

Trying to work on the updated definition for GO:0000073

The current definition is:

A largely uncharacterized process involving the release of duplicated spindle pole bodies (SPBs) and their migration away from each other within the nuclear membrane. Duplicated SPBs are connected by a bridge structure that may be severed in order to release the SPBs from one another. Following liberation, SPBs diffuse through the nuclear membrane until they are across from each other. SPB separation must take place in order for a bipolar mitotic spindle to assemble.

In #13461, you added this:

begins with the nucleation of microtubules from each SPB within the nucleus, leading to V-shaped spindle microtubules. Interpolar microtubules that elongate from each pole are interconnected, forming overlapping microtubules. Capturing and antiparallel sliding apart of microtubules promotes the initial separation of the SPB.

So does this new combined def make sense?

The release of duplicated mitotic spindle pole bodies (SPBs) that begins with the nucleation of microtubules from each SPB within the nucleus, leading to V-shaped spindle microtubules. Interpolar microtubules that elongate from each pole are interconnected, forming overlapping microtubules. Capturing and antiparallel sliding apart of microtubules promotes the initial separation of the SPB. Following liberation, SPBs diffuse through the nuclear membrane until they are across from each other. SPB separation must take place in order for a bipolar mitotic spindle to assemble.

**Comment by ValWood** [comment]
Sorry, I forgot about the other open ticket, this is a partial duplicate.

A few tweaks:
The release of duplicated mitotic spindle pole bodies (SPBs) that begins with the nucleation of microtubules from each SPB within the nucleus, leading to V-shaped spindle microtubules. Interpolar microtubules elongate from each pole forming overlapping microtubules. Capture and antiparallel sliding apart promotes  initial  SPB separation. Following liberation (severing of the half-bridge), SPBs diffuse through the nuclear membrane until they are opposite each other. SPB separation must take place in order for a bipolar mitotic spindle to assemble.

Like so:
![spb cycle](https://user-images.githubusercontent.com/7359272/37006598-fd948fbc-20d0-11e8-8cd5-92bbfbfd57b4.jpg)
