### ISSUE TITLE
 intra/extracellular ribonucleoprotein complex, merge?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15303]
do we need?

GO:1990903    extracellular ribonucleoprotein complex | is_a
GO:0030529    intracellular ribonucleoprotein complex

extracellular has no annotations....

**Comment by pgaudet** [comment]
How about 
* obsolete 'GO:1990903    extracellular ribonucleoprotein complex' 
* merge GO:0030529    intracellular ribonucleoprotein complex into parent 'GO:1990904 ribonucleoprotein complex'?

**Comment by ValWood** [comment]
That works.

**Comment by bmeldal** [comment]
+1
no annotation to GO:1990903 in CP either

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:1990903 extracellular ribonucleoprotein complex’. The reason for obsoletion is that there are no known extracellular ribonucleoprotein complexes. 

There are no annotations or mappings to this term. Any comments can be added to this issue: https://github.com/geneontology/go-ontology/issues/15303

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on March 16, 2018. Unless objections are received by March 16, 2018  we will assume that you agree to this change. 


Thanks, Pascale

**Comment by pgaudet** [comment]
- [ ] obsolete 'GO:1990903 extracellular ribonucleoprotein complex'
 - [ ]   merge GO:0030529 intracellular ribonucleoprotein complex into parent 'GO:1990904 ribonucleoprotein complex'

**Comment by paolaroncaglia** [comment]
@pgaudet 
This was part of the extracellular vesicles work. Could you please hold on to this while I check, I am drowning in other tasks at the moment and in meetings all day. I only saw this ticket now and did not realise that you were already merging terms... I'll comment by the weekend (possibly the plan is good to go but I'd really like to have time to check).
Thanks.
Paola

**Comment by ValWood** [comment]
ribonucleoprotein complex (or specific child)  occurs_in(extracellular vesicle)?

**Comment by paolaroncaglia** [comment]
@ValWood @pgaudet @bmeldal 

GO:1990903 ‘extracellular ribonucleoprotein complex’ was added in 2015 as part of the extracellular vesicles/exRNA project. The project resulted in a publication (https://www.ncbi.nlm.nih.gov/pubmed/27076901). I’m not sure why a reference was not provided by the experts at the time I was adding the terms, but figure 1 in our paper points to PMID:21383194 for ‘extracellular ribonucleoprotein complex’. I had a brief look and that sounds quite sensible. What’s more, GO:1990903 ‘extracellular ribonucleoprotein complex’ is explicitly shown in figure 2 (“The list of exRNA-related terms, synonyms and relationships that have been added to GO”). The paper is less than 2 years old; we should probably keep that term. 
In summary, I’d suggest to
- [ ] add PMID:21383194 as a dbxref to GO:1990903 ‘extracellular ribonucleoprotein complex’
- [ ] do not obsolete GO:1990903 ‘extracellular ribonucleoprotein complex’
- [ ] de-merge GO:0030529 ‘intracellular ribonucleoprotein complex’ from its parent 'GO:1990904 ribonucleoprotein complex’
optionally,
- [ ] someone might look into the possibility of annotating PMID:21383194 (sorry, I really don't have time to do that).

Lastly, a general comment. The fact that that term was created as part of a focused ontology project is visible from its dbxref ‘GOC:vesicle’. In similar cases, when feasible, I’d suggest checking directly with the editor(s) who was/were responsible for the specific project. I don’t look at all GO GitHub tickets anymore for obvious reasons, so it was only the obsoletion email that drew my attention. If my suggestions above end up being accepted, I could have saved Pascale some time. 

Thanks, and a nice weekend to all :-)

**Comment by ggeorghiou** [comment]
I will also chime in here. The collaboration with GOA and ExoCarta/Vesiclepedia is still ongoing. Seeing as this is an active collaboration, I think we should keep the term.

**Comment by pgaudet** [comment]
Hi @ggeorghiou @paolaroncaglia 

Thanks for the feedback. ‘extracellular ribonucleoprotein complex’ is odd in that there is no equivalent term for extracellular protein complex. All I could find is 'GO:1990563 extracellular exosome complex', which is a direct child of extracellular space. 

So if this miRNA-protein complex is important, I could rename the term 'GO:1990903 ‘extracellular ribonucleoprotein complex’ as such and add the reference. 

Would that be an acceptable compromise? It seems to me that the grouping term (extracellular ribonucleoprotein complex) is unnecessary and inconsistent with the current structure of the ontology. 

Thanks, Pascale

**Comment by paolaroncaglia** [comment]
Hi @pgaudet ,

I’d still prefer to keep the general term ‘extracellular ribonucleoprotein complex’, on the grounds that the extracellular RNA community considered it important to have as such in the ontology. Our paper describes the process that many members of that community went through to find consensus on terms they wished to be in GO, so it’s not like one single person asked for the term without thinking too much about it. I can relate to the dislike of not having a ’symmetrical’ ‘extracellular protein complex’ term ;-), but clearly the presence of ‘extracellular ribonucleoprotein complex' reflects the wish of one particular community we serve, rather than the broader way we try to have regular patterns in GO. Also, an implication of what @ggeorghiou wrote is that ExoCarta/Vesiclepedia are still in the process of getting their annotations in shape for submission to GO. I’m no longer involved in that, but I suspect that they may well be using/have used ‘extracellular ribonucleoprotein complex’ already.

Thanks,
Paola

**Comment by ValWood** [comment]
But we only add complexes to GO if there is functional information, and there is not functional information in PMID:21383194, so we would not annotate that paper?

The authors say quite clearly in the abstract
"In addition, identification of extracellular Ago2-miRNA complexes in plasma raises the possibility that cells release a functional miRNA-induced silencing complex into the circulation."

So, we  should wait for evidence for such a role, otherwise it will make much work for later...There is enough to do (and too much to fix), already.

v

**Comment by paolaroncaglia** [comment]
@ValWood @pgaudet
Thanks for looking into that paper. I ticked the last box in one of my previous comments to show that someone has looked into annotating it. My concern about not depriving the exRNA community of a general term that they asked for is still valid, though. I’ll contact some of my coauthors on the exRNA paper and ask them for examples of extracellular ribonucleoprotein complexes other than the Ago2-miRNA from PMID:21383194. Please keep this ticket open until I hear back from them. Thanks.

**Comment by paolaroncaglia** [comment]
For the records: I emailed Kei-Hoi Cheung, Louise Laurent and Shivakumar Keerthikumar today.

**Comment by pgaudet** [comment]
Question for editors: the pattern 'organelle x complex' is not widely used; most of the instances I found are when a complex type exists in two different organelles, for example 'mitochondrial DNA-directed RNA polymerase complex', under 'mitochondrial protein complex' (there is no equivalent 'nuclear protein complex grouping term, but there is a term 'nuclear DNA-directed RNA polymerase complex'). 

In which direction do we want to go? It seems difficult to classify complexes based on where they are located. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Good question, Pascale.
I assume things like mitochondrial and nuclear transcription processes differ in detail but the principles of transcription should be the same so the complexes have essentially the same function.
The locations should then be captured with an extension, right?

**Comment by ValWood** [comment]
My opinion is point 2 here ;)
https://github.com/geneontology/go-ontology/issues/12418

I don't think we need a grouping term for  'mitochondrial protein complex' 
it has it's own term
mitochondrial DNA-directed RNA polymerase complex (GO:0034245)
and is a  "mitochondrial part". 

I also think we should get rid of organelle specific instances of *identical* complexes (i.e nuclear proteasome, cytosolic proteasome), and use extensions.

**Comment by pgaudet** [comment]
@ValWood The alternative (keeping organelle-specific grouping terms) seems unmaintainable.

**Comment by ValWood** [comment]
...and unnecessary.
If a complex is organelle specific, it has a part_of parent  to the organelle.

If the same complex is found in multiple locations, an occurs_in extension works best ( and a co-annotation to the location, but this could be inferred longer term...)

**Comment by paolaroncaglia** [comment]
@ValWood @pgaudet @bmeldal 
Here's a reply from Louise Laurent (UCSD):
"This paper immunoprecipitated using an anti-AGO2 antibody from detergent-free biofluid, and concluded that extracellular miRNA was associated with non-EV AGO2-containing RNPs: PMID:21609964."
And here's my reply to her:
"...I will point my GO colleagues to the paper below. However, as that is only one example of an extracellular, vesicle-free miRNA-protein complex, and it was published in 2011, it would be really helpful if you could please provide additional, and possibly more recent, examples of extracellular complexes of RNAs (can be other than miRNAs) and proteins that are not bounded by vesicles. ...".
If I do receive more examples, I'll paste them here. Cheers.

**Comment by ValWood** [comment]
Hi paola,

The point was that there was no evidence for functional significance of this particular association at present which is a pre-requisite for a  complex in GO....

This abstract says:
We hypothesize that extracellular miRNAs are in the most part by-products of dead cells that remain in extracellular space due to the high stability of the Ago2 protein and Ago2-miRNA complex.

Could you ask about functional significance?

**Comment by paolaroncaglia** [comment]
Hi @ValWood,
I thought long and hard about how to reply in a polite and friendly manner :-) but I’m afraid that the answer is “no, I can’t ask about functional significance”. I’ve already asked for more (and more recent) examples, which implies that I’m looking for as good an experimental evidence as we can get, and to me that also implies indication of actual roles for those complexes. It should mean the same to them, too. I emailed 3 of them and the above is the only reply I got so far. Feel free to obsolete the term if you really want to, and if you don’t mind that a term slated for obsoletion is explicitly shown in a figure in a recent paper authored by GOC members. 
Thanks,
Paola

**Comment by ValWood** [comment]
Hi @paolaroncaglia,

I'm only trying to establish if there is any additional evidence to provide biological justification for keeping the term (i.e any other RNA complex, or publication that we overlooked).

So far, we have only established that  none of the papers supplied so far describe the existence of an ‘extracellular ribonucleoprotein complex’ with a biological role, so there does not seem to be, based on the current data.

It does not even appear to be part of the extracellular exosome according to the authors who clearly state in the abstract:
"We hypothesize that extracellular miRNAs are in the most part by-products of dead cells that remain in extracellular space due to the high stability of the Ago2 protein and Ago2-miRNA complex."

This term does not fit normal design pattern (see above).

GO is  not a static resource, so inclusion in a paper (GOC or not) does not seem to be a valid reason to keep a term which is not biologically meaningful, and would not be used in annotation? I'm sure we all have publications with obsoleted terms by now ;)

**Comment by ggeorghiou** [comment]
Hi @ValWood 

As I mentioned before, we have an ongoing collaboration with Vesiclepedia/ExoCarta. I am still waiting to hear back from them regarding how their GO annotations are progressing, but given the deadline for deciding what to do with these terms, I am going to have a look at a previous GPAD they have sent us to see how the term has been used and where it has been referenced. Seeing as they do not have the opportunity to hear about changes to the GO unless we feed it back to them, I ask for a bit of time to allow them to update us and see if this term is still useful to them. There may be annotations that support this term being kept and I would hate for them to not have their say.

**Comment by paolaroncaglia** [comment]
Hi @ValWood,
Thanks. I share @ggeorghiou’s concerns; hopefully there will be useful functional information in the GPAD file he has. If not, it might take some time to get feedback from its authors - we gather there’s been some changes in management overseeing the practical aspects of the resources; both George and I have emailed the PI at Exocarta/Vesiclepedia in the last few days but no reply yet. Other than that, I accept your point of view on that term and leave it to you and others involved to decide of its fate. I’ll be honest though, while I understand and second the discussion about not wanting to explode the GO with ‘extracellular’ and ‘intracellular’ terms where the location can be better captured otherwise, a quick search for ‘extracellular’ returns >140 terms and if the GOC wishes to gradually get rid of them all, this (and similar changes) should be communicated to our users. I know that the question is a bit more complex, but it seems that the outside world is not really being made aware of the changes in GO - not the trivial ontology changes that are healthy in a dynamic resource, but the overarching changes in strategy. 
My 2 cents. Cheers,
Paola

**Comment by pgaudet** [comment]
Hello, 

I see at least two issues being discussed here: 
1. how to group 'protein complex' terms
2. rules for creating complex terms: does the complex need to have a known activity or not ? 
I think the Complex WG is addressing the second point (right @bmeldal ?)

WRT the first point: in GO we have only two grouping terms by organelle for protein complexes, 'extracellular ribonucleoprotein' and 'mitochondrial protein complex'. 

@paolaroncaglia 
I was not disputing terms like 'extracellular ferritin complex'. 'Extracellular miRNA-protein complex' seems OK as well. However I do think we need to remove the grouping terms because these are very incomplete and will confuse users. 

So, are you OK with renaming ''extracellular ribonucleoprotein' to extracellular miRNA-protein complex', and adding the reference you mentioned ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
>I see at least two issues being discussed here:
1. how to group 'protein complex' terms
2. rules for creating complex terms: does the complex need to have a known activity or not ?
    I think the Complex WG is addressing the second point (right @bmeldal ?)

Yes, we said we need to have at least some idea of its function to curate a complex. In many cases we know it exists and which process it affects but don't know its actual MF so we just annotate to BP. But we can say something about its role.

>WRT the first point: in GO we have only two grouping terms by organelle for protein complexes, 'extracellular ribonucleoprotein' and 'mitochondrial protein complex'.

There are more, like GO:0098796 membrane protein complex. They were introduced by David OS for grouping and logical defs.
We might have to reconsider this strategy.

We have a call in a little over an hour!

Birgit

**Comment by pgaudet** [comment]
Thanks @bmeldal, this is useful. 

We didn't manage to discuss this at the last call - I would still like to get clarification from the editors about what GO captures WRT complexes: from #12782 I thought we wanted to have as little overhead as possible in managing protein complexes, which is why I merged 'protein complex' into 'macromolecular complex'. To be consistent with that logic we should NOT classify complexes by organelle/localization either. 
@ukemi 
@cmungall 
@thomaspd 
Can you please comment ? 

Thanks, Pascale

**Comment by ukemi** [comment]
As I have said before. I am always concerned when we make changes or remove terms that have resulted from consulting experts in a field.

**Comment by thomaspd** [comment]
I agree David, but this case is a bit different, as these terms were not proposed by experts for functional annotation but for experiment metadata annotation.  Are the exosome terms labeled in the ontology?  Maybe we need a GO-function-slim to support our major use case, that would exclude the exosome terms unless they've been demonstrated to be functionally relevant.

**Comment by ValWood** [comment]
From the papers supplied for this particular term, the authors say that is likely a result of 
"in the most part by-products of dead cells that remain in extracellular space due to the high stability of the Ago2 " so this isn't exosome.
It seems strange to include these....

**Comment by pgaudet** [comment]
Editors discussion March 19: 
- Annotation should be made to both 'ribonucleoprotein complex' AND 'extracellular' (note that without a GO-CAM model these would not be linked). 
- For specific complexes, we can add a 'part_of' assertion in the logical definition, like we do for 
chloroplast isoamylase complex : 
'isoamylase complex'
 and ('part of' some chloroplast)

**Comment by pgaudet** [comment]
So @paolaroncaglia : since you already published the ID I can merge the term 'extracellular ribonucleoprotein complex' into the parent 'ribonucleoprotein complex', or rename it 'extracellular miRNA-Ago2 complex' (@bmeldal would that be a valid term?) 

Thanks, Pascale

**Comment by paolaroncaglia** [comment]
Hi all, in reply to some of your questions:
 
@pgaudet wrote 
“I was not disputing terms like 'extracellular ferritin complex'. 'Extracellular miRNA-protein complex' seems OK as well. However I do think we need to remove the grouping terms because these are very incomplete and will confuse users.
So, are you OK with renaming 'extracellular ribonucleoprotein [complex]’ to ‘extracellular miRNA-protein complex', and adding the reference you mentioned?”
and 
“since you already published the ID I can merge the term 'extracellular ribonucleoprotein complex' into the parent 'ribonucleoprotein complex', or rename it 'extracellular miRNA-Ago2 complex’”
and 
“Also - I am not disputing the term, but the impact on the ontology structure. I would expect the experts did not take that into account when proposing terms - right?”

Actually, looking at figures 1 and 2 in https://www.ncbi.nlm.nih.gov/pubmed/27076901, they did put some thought into the ontology structure. Sure, you may still consider them less ‘ontology conscious’ than professional GO editors. See below for other comments please.

@thomaspd wrote
“I agree David [@ukemi, re. “I am always concerned when we make changes or remove terms that have resulted from consulting experts in a field”], but this case is a bit different, as these terms were not proposed by experts for functional annotation but for experiment metadata annotation. Are the exosome terms labeled in the ontology? Maybe we need a GO-function-slim to support our major use case, that would exclude the exosome terms unless they've been demonstrated to be functionally relevant.”

GO:0070062 ‘extracellular exosome’ is not labeled not-for-annotation, but the whole point of exosome research from the past few years is exactly that (at least some) extracellular vesicles seem to play roles in cancer and other diseases… How to differentiate functionally relevant exosomes from ones that aren’t, in the ontology, is a complex discussion that I’m not going into now :-) I agree that the miRNA-Ago2 complex doesn’t come with good functional evidence in the 2 papers we know of (in response to @ValWood “From the papers supplied for this particular term, the authors say that is likely a result of "in the most part by-products of dead cells that remain in extracellular space due to the high stability of the Ago2" so this isn't exosome.”).

So ok with merging 'extracellular ribonucleoprotein complex' into its parent 'ribonucleoprotein complex’. 

Paola
