### ISSUE TITLE
NTR: PSTB phospholipid transfer acceptor membrane complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15338]
Hi,
I've a new complex term to request...
thanks a lot!
Livia

Name: PSTB lipid transfer acceptor membrane complex
Def: Lipid transfer complex that is responsible for the non-vesicular transport of phospholipids, such as phosphatidylserine, from the endoplasmic reticulum to the endosome. It resides in the endosomal (acceptor) membrane and binds to specific lipids on the donor membrane at the ER-endosome contact site.

References:
GOC:lnp
PMID:
20016005, 24366873
Relationships:
is_a GO:0098796 membrane protein complex
capable_of GO:0001786 phosphatidylserine binding
capable_of GO:0005543 phospholipid binding
capable_of GO:0120014 intermembrane phospholipid transfer activity
part_of GO:0010008 endosome membrane
capable_of_part_of GO:0120010 intermembrane phospholipid transfer

DB xref:EBI-16421832
[in S. cerevisiae it is composed by PstB2p (or Pdr17) and Psd2p (or Psd2)]

**Comment by liviap** [comment]
Sorry to bother...Any update on it?

Livia

**Comment by vanaukenk** [comment]
Hi @liviap 
No worries; I will try to get to all of your complex request terms after the GOC meeting finishes next week.  Apologies for the delays.

**Comment by vanaukenk** [comment]
@liviap 
I'm reviewing this new term request and have a couple of questions for you.  I'm also looping in SGD (@suzialeksander) to get their thoughts on the best name for this complex and to make sure that the individual annotations for the complex members are consistent with how we represent the complex in the ontology.

1.  I noticed in SGD that the PDR17 gene report page does not list PstB2 as an alias, so I'm wondering if a complex name that contains PSTB is the best choice for the budding yeast community; perhaps something more generic like, 'ER-to-endosome phospholipid transfer complex'?  I'm open to other suggestions.

2. We should make sure that, in this case, the localization of the complex and the respective members are consistently represented.  From the same reference, SGD has curated 'endosome' for PDR17 and PSD2, but the protein complex of PDR17-PSD2 is annotated to 'endosome membrane'.  The experiments seem to suggest 'endosome membrane' for both, but could SGD take another look and see if they agree?
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2814789/

3. Two of the suggested capable_of links to MF terms represent a parent and child.  Is the parent term suggested because we are missing a more specific child term?  If so, we can add that more specific child term; otherwise, I will only include the link to the more granular 'phosphatidylserine binding'.
capable_of GO:0001786 phosphatidylserine binding
capable_of GO:0005543 phospholipid binding
  
Thx.

**Comment by liviap** [comment]
Hi @vanaukenk, 
thanks for taking care of it!
1) 'ER-to-endosome phospholipid transfer complex' it's fine
2) ok
3) yes, the problem is the lack of specific terms for other phospholipids (in particular PtdOH, as shown in     24366873), I agree is non-sense to annotate both parent and child term, but I didn't have time to create another ticket... sorry for that.
Livia
