### ISSUE TITLE
missing parent: pheromone-dependent signal transduction involved in conjugation with cellular fusion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15337]
shouldn't
GO:0000750 | pheromone-dependent signal transduction involved in conjugation with cellular fusion

be a descendant of "

GO:0007267 cell-cell signalling"?

@Antonialock ?

**Comment by Antonialock** [comment]
but GO:0000750 is part of GO:0000749 ?

**Comment by ukemi** [comment]
Yes, but neither one is part of (GO:0007267) cell-cell signaling. We should always try to make the links with the most general terms. Making relationships to specific children when a more general term is appropriate leads to incompleteness and inconsistencies. I'm not sure if I'm right in this case, but it looks reasonable.

**Comment by ValWood** [comment]
I spotted it because we display cell-cell signalling here. I would have expected that to be hidden by default  by being a parent of  pheromone-dependent signal transduction involved in conjugation with cellular fusion
https://www.pombase.org/gene/SPAPB8E5.05

**Comment by krchristie** [comment]
* turquoise (Val's suggestion) - pheromone-dependent signal transduction involved in conjugation with cellular fusion (GO:0000750)
* orange (David's suggestion) - response to pheromone triggering conjugation with cellular fusion (GO:0000749)
* purple (Karen's suggestion) - signal transduction involved in positive regulation of conjugation with cellular fusion (GO:0032005)

In the picture I've taken from OBO-Edit, below, Val proposed that the turquoise term should have parentage under cell-cell signaling and David proposed that the orange term should have this parentage instead.

I think that the orange term can NOT have the parentage cell-cell signaling because it has part_of children like agglutination that are not part of signaling.

Val's term would be OK, but I think it's parent term: "**signal transduction involved in positive regulation of conjugation with cellular fusion**" (GO:0032005) is a better choice since this also a signal transduction term that is specific to conjugation with cellular fusion.

Thus, I propose to add the cell-cell signaling parentage to the term "**signal transduction involved in positive regulation of conjugation with cellular fusion**" (GO:0032005).

@ValWood @ukemi - thoughts? objections?

![2080322-pheromonesignaling](https://user-images.githubusercontent.com/10533218/37805093-5144297a-2df5-11e8-9167-7093b7c28b0f.jpg)



OBO-Edit to the rescue!!!

**Comment by ValWood** [comment]
> purple (Karen's suggestion) - signal transduction involved in positive regulation of conjugation with cellular fusion (GO:0032005)

@Antonialock  will be the best person to comment on this one.

I think we need to specify "pheromone dependent" because  G-protein coupled signalling regulating conjugation can be pheromone dependent or pheromone independent . Is that correct?

**Comment by krchristie** [comment]
I understand that you are interested in having the turquoise phermone-dependent term be classified as cell-cell signaling, but David H has also stated in this ticket that the parentage should be given to the most general term for which it is accurate.

If we add the cell-cell signaling parentage to the purple term, then the turquoise term will inherit it.

**Comment by ValWood** [comment]
OK, I misunderstood!

@Antonialock  does this seem OK to you?

**Comment by ValWood** [comment]
1. 
One point I don't understand it why " response to pheromone triggering conjugation with cellular fusion" is a child of "positive regulation of conjugation with cellular fusion"? That would cause the agglutination term, and the  G1 arrest term to become "positive regulation of conjugation with cellular fusion" which would be incorrect.

2. The term attributed to me?

 pheromone-dependent signal transduction involved in conjugation with cellular fusion

should really be named
"pheromone-dependent signal transduction involved in positive regulation of  conjugation" with cellular fusion shouldn't it?

When this process occurs it is always to "positively regulate conjugation with cellular fusion"

no?

3. I don't know why we are using "triggering"  is there a reason?
Is the term necessary?

"response to pheromone involved in conjugation with cellular fusion"


4. whatever the outcome of 3
agglutination involved in conjugation with cellular fusion

negative regulation of pheromone-dependent signal transduction involved in conjugation with cellular fusion  isn't a response to pheromone, it is upstream of the pheromone response ?

I'm a bit confused by the current arrangement @Antonialock  is PomBase expert here though...

**Comment by krchristie** [comment]
Note that the yellow arrows indicate part_of, while the blue ones indicate is_a relationships in the diagram.

**Comment by krchristie** [comment]
@ValWood - How much of a priority is it for you or @Antonialock to spend time researching these new questions? I have lots of other tickets that are more generally applicable to many organisms, and this one isn't relevant to human/mammalian biology at all. Thus, I am not inclined to spend much more of my time to do further research for this ticket. 

For this ticket, perhaps we could keep it simple at just deciding the appropriate term for adding the cell-cell signaling parentage. Then if you and @Antonialock have additional suggestions and also get appropriate feedback from SGD, please submit another ticket with any further suggestions.

**Comment by ValWood** [comment]
I agree, it seems as though this might need major revisions when the pathway is curated. 
I can't make sense of it....

**Comment by Antonialock** [comment]
yeah it probably would be very helpful to draw this process out on paper, and then assign annotation so that it is consistent and clear. It will be quite a big job though. I can do it once other things quieten down a bit. Thanks for your input Karen.

**Comment by ValWood** [comment]
yep... definitely backburner for us...i thought it was a simple missing parent but it looks a bit messy ;)

**Comment by Antonialock** [comment]
I know! It's been at the back of my mind for a long while - I poke it back to the far back of my mind with a long stick every now and then when it sticks its nose out :-)

**Comment by Antonialock** [comment]
I think part of the problem is doing non-focussed annotation over years without a "big picture" in mind, coupled to a lot of indirect IMP evidence from old papers - oh look, we knocked this gene out and cells stop doing X (lots of old papers in the literature corpus....newer papers are so much clearer about biology in general unsurprisingly)

**Comment by Antonialock** [comment]
and evolving practices ofc

**Comment by krchristie** [comment]
I'm still OK with adding the cell-cell signaling to the purple term. I think that's reasonable now and will probably still be true even if/when you get around to rearranging the leaf nodes.

**Comment by Antonialock** [comment]
I think it would be ok to add it to the turquoise term. 

in order to commit to "conjugation with cellular fusion" a number of intracellular signalling pathways first need to converge before the cell will commit to mating. This is not cell-cell signalling.

**Comment by Antonialock** [comment]
(i.e. the gene products that tell the cell to "make lots of pheromones and lots of pheromone receptors" when conditions are bad should be annotated to "signal transduction involved in +ve reg of conj with cellular fusion" but not directly to cell-cell signalling?)

**Comment by krchristie** [comment]
It seems to me that it would be more appropriate to add the cell-cell signaling parentage to the purple term which is an is_a parent of the turquoise term because it is also a signal transduction term that is specific to conjugation with cellular fusion. You will still get the inheritance you want for the turquoise term since it will inherit it through the purple term.

Is there a reason that cell-cell signaling would NOT be a correct parent for the purple term?

**Comment by Antonialock** [comment]
yes, it think there is signaling that positively regulate mating, that is not cell-cell signaling.

for example:
I think it would be correct to annotate pombe rst2 to
purple term: "signal transduction involved in positive regulation of con..."
but NOT cell-cell signaling

rst2 is a transcription factor. When there is plenty of glucose around rst2 inactivated via PKA. When glucose is scarce, PKA is turned off, rst2 is release from inhibition and directly activates the transcription of the "master" sexual differentiation transcription factor Ste11. Ste11 controls a multitude of pathways relevant to sexual differentiation, including cell-cell signaling and allowing the cell to switch to a meiotic cell cycle (cells can be "tricked" into going meiotic without mating by removing the inhibitory kinase pat1)

**Comment by krchristie** [comment]
So, is it appropriate to annotate a transcription factor to a signal transduction term? I know I'm not completely up on GO practices for signal transduction pathways and could be completely wrong, but I thought the signal transduction was upstream of the transcription factor.

And to follow on from that, if it is appropriate to annotate a transcription factor to the purple term, it seems it could be equally appropriate to annotate a transcription factor to the turquoise term.

Anyway, I don't see how the argument that you could annotate a transcription factor to the purple term has any impact on the parentage since this seems equally true for the turquoise term. Let me know what the difference is.

- purple - **signal transduction involved in positive regulation of conjugation with cellular fusion** (GO:0032005)
- turquoise  - **pheromone-dependent signal transduction involved in conjugation with cellular fusion** (GO:0000750)

**Comment by Antonialock** [comment]
there are other signaling pathways converge to get ste11 expression levels up to a level sufficient to trigger the mating response. 

e.g. when a cell is starved of nitrogen (the "main" mating response stress trigger), the stress kinase sty1 phosphorylates the CTDK-1 kinase lsk1, lsk1 when active phosphorylates RNA PolII, which then transcribes more ste11

lsk1 is annotated to "positive regulation of induction of conjugation with cellular fusion" but I guess this should be corrected to "signal transduction involved in positive regulation of conjugation with cellular fusion" (or maybe nonexisting "signal transduction involved in positive regulation of induction of conjugation with cellular fusion" - I don't have my head around all these terms but I do realy believe that that there is signal transduction that is NOT cell-cell signalling, that positively regulate the mating response. The cells don't really mate unless they have to, and before they cell-cell signal, they have to make the internal decision to go through with it)

**Comment by ValWood** [comment]
Let's close this. I don't think we lose much  annotation wise by not having the connection to cell-cell  signalling. This is the sort of detail logical defs should fix eventually.
