### ISSUE TITLE
NTR: asparagine-type endopeptidase activity

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#15347]
### NTR: asparagine-type endopeptidase activity

Figure 6 in PMID:9065484 shows that legumain has endopeptidase activity and it cleaves specifically at asparaginyl bonds (-Asn-|-Xaa-) (EC 3.4.22.34) (https://enzyme.expasy.org/EC/3.4.22.34).

--> GO_New: asparagine-type endopeptidase activity 

Work with peptidase inhibitors additionally shows that legumain is a cysteine-type peptidase (Tables III and IV in PMID:9065484).

--> GO:0004197 cysteine-type endopeptidase activity
Definition: 
"Catalysis of the hydrolysis of internal, alpha-peptide bonds in a polypeptide chain by a mechanism in which the sulfhydryl group of a cysteine residue at the active center acts as a nucleophile."
(EC 3.4.22) (https://enzyme.expasy.org/EC/3.4.22.-)

According to the ExPASy ENZYME classes 'asparagine-type endopeptidase activity' is a child of 'cysteine-type peptidase':
EC 3.4.22: Cysteine endopeptidases
> EC 3.4.22.34: Legumain (Asparaginyl endopeptidase)

The same parentage can be followed in GO:

GO:0004197 cysteine-type endopeptidase activity
> GO_New: asparagine-type endopeptidase activity (is_a)

And the new term can be defined as: 
"Catalysis of the hydrolysis of internal asparaginyl bonds (-Asn-|-Xaa-) in a polypeptide chain by a mechanism in which the sulfhydryl group of a cysteine residue at the active center acts as a nucleophile." (PMID:12860980, GOC:aruk, GOC:bc)

@paolaroncaglia @RLovering @ukemi could you please check that you agree with the suggested hierarchy and definition before I add this new term?

**Comment by paolaroncaglia** [comment]
Hi @BarbaraCzub ,

Thanks. In this case, GO should not mirror the EC hierarchy, because in GO aminoacids are considered as siblings, unless a whole aminoacid family is referred to (see e.g. https://www.ebi.ac.uk/QuickGO/term/GO:0009066). In the present case, we’d want GO_New: asparagine-type endopeptidase activity to be a child of GO:0004175 endopeptidase activity and a sibling of GO:0004197 cysteine-type endopeptidase activity (and of GO:0004190 aspartic-type endopeptidase activity). The definition should be:

Catalysis of the hydrolysis of internal asparaginyl bonds (-Asn-|-Xaa-) in a polypeptide chain by a mechanism in which the … ” (PMID:12860980, GOC:aruk, GOC:bc, EC:3.4.22.34) 

You’d have to fill in the blanks (there are no sulfhydryl groups in asparagine). If you are unsure, you could probably leave the definition at “Catalysis of the hydrolysis of internal asparaginyl bonds (-Asn-|-Xaa-) in a polypeptide chain.” for the time being.

Thanks,
Paola

**Comment by ukemi** [comment]
Hi @paolaroncaglia . Are you sure. In the case of cysteine and aspartate peptidases, the cysteine and the aspartate are in the active site of the enzyme. I think the case that @BarbaraCzub is describing is a cysteine-type peptidase that cleaves next to asparagine, so it would be ok to be a cysteine-type endopeptidase, but maybe should be called asparaginyl-specific cysteine-type endopeptidase activity. @BarbaraCzub you should also try to go back and find the notes of the protease working group on the wiki. They might have discussed inclusion/exclusion of the substrate-specific terms.

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
Here are the notes that @ukemi referred to: 
http://wiki.geneontology.org/index.php/Proteases

**Comment by BarbaraCzub** [comment]
Hi @paolaroncaglia and @ukemi Thanks for your comments and referring me to the proteases documentation. @ukemi is right that legumains are cysteine-type peptidases that cleave next to asparagine. But although this is their primary target (which is why they've been classified like this in EC), they are also able to cleave next to aspartic acid, e.g. during self-activation/self-proteolysis (Table 1 with Figures 1 and 2 in PMID:9821970), which would require another substrate-specific child term... This is what the documentation advises against, so I'll close this ticket now, and use GO:0004197 cysteine-type endopeptidase activity for annotation. Thank you for your help!
