### ISSUE TITLE
MP GO:0000212 - meiotic spindle organization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15348]
should be part_of
GO:0140013 - meiotic nuclear division

@Antonialock  do you agree?

**Comment by ukemi** [comment]
The mitotic one isn't either. It this true though? The organization of the spindles also dictates where cytokinesis will occur. Is that part of nuclear division?

**Comment by ValWood** [comment]
I don't think the organization of the spindles determines where cytokinesis occurs. A  signalling pathway emenating from the SPB/centrosome determines where/when cytokinesis occurs.

**Comment by Antonialock** [comment]
so endomeiosis might be a thing in parthogenically developing eggs..
https://www.tandfonline.com/doi/pdf/10.1080/11250009309355818

**Comment by ValWood** [comment]
but does that affect that the meiotic spindle   would only exist in M-phase (as in mitosis)?

(I don't understand what it is!)

**Comment by Antonialock** [comment]
the point was that those organisms seem to do meiosis without nuclear division? It is probably a very obscure example, and very old.

**Comment by krchristie** [comment]
I'm a little hesitant to make changes in this area since I know that people with more knowledge than I have about meiosis & mitosis have worked in this area. Eurie Hong did her PhD in a meiosis lab.

I will point out that the term "meiotic spindle organization" has a child term of "spindle assembly involved in meiosis" which is already a  _part_of_ "meiotic nuclear division".

-- meiotic spindle organization
--- _is_a_ meiotic spindle disassembly
--- _part_of_ meiotic spindle elongation
--- _part_of_ meiotic spindle pole body organization
--- _is_a_ **spindle assembly involved in meiosis**

-- meiotic nuclear division
--- _part_of_ meiotic chromosome segregation
--- _part_of_ meiotic spindle midzone assembly
--- _part_of_ **spindle assembly involved in meiosis**

Also note that the term "meiotic spindle organization" has "meiotic spindle disassembly" as an _is_a_ child term.

Thus, I am inclined so say that this has already been carefully considered and should not be changed in the way you suggest.

**Comment by ValWood** [comment]
Hi Karen,


It might not be  correct because the meiotic spindle  is also involved in forsepore membrane formation.

However, most of the mitotic spindle terms have been completely overhauled since Eurie left (mainly by feedback from input from spindle experts).  This is the final open ticket:
https://github.com/geneontology/go-ontology/issues/13461

For mitotic spindle organization, the  spindle  does not form until  mitotic prophase (i.e. is  part of mitotic nuclear division), and is desassembly at the end of nuclear division.
I therefore think that   "mitotic spindle organization" should be part of "mitotic nuclear division" (currently it isn't).  So  I think that could be added, but it  doesn't really matter as the term is not much used for direct annotation.

I noted it here in case it comes up again. No action required though.

Val
