### ISSUE TITLE
GO:0017144 drug metabolic process -valid term?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#15379]
I came across the term GO:0017144 drug metabolic process
The chemical reactions and pathways involving a drug, a substance used in the diagnosis, treatment or prevention of a disease.

with children:

GO:0070178                D-serine metabolic process | is_a
GO:1901125                candicidin metabolic process | is_a
GO:0019415                acetate biosynthetic process from carbon monoxide | is_a
GO:0042448                progesterone metabolic process | is_a
GO:1902136                (-)-secoisolariciresinol metabolic process | is_a
GO:0036378                calcitriol biosynthetic process from calciol | is_a
GO:0000255                allantoin metabolic process | is_a
GO:1900603                tensidol A metabolic process | is_a
GO:0046209                nitric oxide metabolic process | is_a
GO:0006558                L-phenylalanine metabolic process | is_a
GO:0018954                pentaerythritol tetranitrate metabolic process | is_a
GO:0018931                naphthalene metabolic process | is_a
GO:1902084                fumagillin metabolic process | is_a
GO:0018977                1,1,1-trichloro-2,2-bis-(4-chlorophenyl)ethane metabolic process | is_a
GO:1901867                ecgonine methyl ester metabolic process | is_a
GO:0046278                3,4-dihydroxybenzoate metabolic process | is_a
GO:0036241                glutamate catabolic process to 4-hydroxybutyrate | is_a
GO:0052653                3',5'-cyclic diguanylic acid metabolic process | is_a
GO:0019386                methanogenesis, from carbon dioxide | is_a
GO:0006769                nicotinamide metabolic process | is_a
GO:0033517                myo-inositol hexakisphosphate metabolic process | is_a
GO:0072592                oxygen metabolic process | is_a
GO:0042836                D-glucarate metabolic process | is_a
GO:1901761                oxytetracycline metabolic process | is_a
GO:0008215                spermine metabolic process | is_a
GO:0006054                N-acetylneuraminate metabolic process | is_a
GO:0018895                dibenzothiophene metabolic process | is_a
GO:0006105                succinate metabolic process | is_a
GO:1901704                L-glutamine biosynthetic process | is_a
GO:0030205                dermatan sulfate metabolic process | is_a
GO:0030417                nicotianamine metabolic process | is_a
GO:0036039                curcumin metabolic process | is_a
GO:0002936                bradykinin biosynthetic process | is_a
GO:0046469                platelet activating factor metabolic process | is_a
GO:1900989                scopolamine metabolic process | is_a
GO:0046085                adenosine metabolic process | is_a
GO:0019860                uracil metabolic process | is_a
GO:0046033                AMP metabolic process | is_a
GO:0008291                acetylcholine metabolic process | is_a
GO:0034650                cortisol metabolic process | is_a
GO:1901732                quercetin metabolic process | is_a
GO:0046146                tetrahydrobiopterin metabolic process | is_a
GO:0010023                proanthocyanidin biosynthetic process | is_a
GO:1900552                asperfuranone metabolic process | is_a
GO:0070813                hydrogen sulfide metabolic process | is_a
GO:0009696                salicylic acid metabolic process | is_a
GO:0042723                thiamine-containing compound metabolic process | is_a
GO:0010391                glucomannan metabolic process | is_a
GO:1901107                granaticin metabolic process | is_a
GO:0042417                dopamine metabolic process | is_a
GO:0006768                biotin metabolic process | is_a
GO:1902124                (+)-pinoresinol metabolic process | is_a
GO:0018907                dimethyl sulfoxide metabolic process | is_a
GO:0006030                chitin metabolic process | is_a
GO:1901728                monensin A metabolic process | is_a
GO:2001291                codeine metabolic process | is_a
GO:1901153                paromomycin metabolic process | is_a
GO:0033494                ferulate metabolic process | is_a
GO:0042905                9-cis-retinoic acid metabolic process | is_a
GO:0046034                ATP metabolic process | is_a
GO:1901775                mitomycin C metabolic process | is_a
GO:0019541                propionate metabolic process | is_a
GO:0046343                streptomycin metabolic process | is_a
GO:0018937                nitroglycerin metabolic process | is_a
GO:0006067                ethanol metabolic process | is_a
GO:0006771                riboflavin metabolic process | is_a
GO:0046874                quinolinate metabolic process | is_a
GO:0018918                gallate metabolic process | is_a
GO:0050783                cocaine metabolic process | is_a
GO:0009235                cobalamin metabolic process | is_a
GO:0033049                clavulanic acid metabolic process | is_a
GO:0042743                hydrogen peroxide metabolic process | is_a
GO:1902048                neosartoricin metabolic process | is_a
GO:0018933                nicotine metabolic process | is_a
GO:0018979                trichloroethylene metabolic process | is_a
GO:0018982                vanillin metabolic process | is_a
GO:0044597                daunorubicin metabolic process | is_a
GO:0018874                benzoate metabolic process | is_a
GO:0046500                S-adenosylmethionine metabolic process | is_a
GO:0006544                glycine metabolic process | is_a
GO:0031524                menthol metabolic process | is_a
GO:0034275                kynurenic acid metabolic process | is_a
GO:1901748                leukotriene D4 metabolic process | is_a
GO:0072390                phenol metabolic process | is_a
GO:0016999                antibiotic metabolic process | is_a
GO:1901150                vistamycin metabolic process | is_a
GO:0070639                vitamin D2 metabolic process | is_a
GO:0006600                creatine metabolic process | is_a
GO:0046440                L-lysine metabolic process | is_a
GO:0015942                formate metabolic process | is_a
GO:1900794                terrequinone A metabolic process | is_a
GO:0006653                1,2-diacyl-sn-glycero-3-phosphocholine metabolic process | is_a
GO:0035498                carnosine metabolic process | is_a
GO:0071265                L-methionine biosynthetic process | is_a
GO:1901813                astaxanthin metabolic process | is_a
GO:0036109                alpha-linolenic acid metabolic process | is_a
GO:1902384                glycyrrhetinate metabolic process | is_a
GO:0018970                toluene metabolic process | is_a
GO:0055129                L-proline biosynthetic process | is_a
GO:0042616                paclitaxel metabolic process | is_a
GO:0045488                pectin metabolic process | is_a
GO:1901049                atropine metabolic process | is_a
GO:1902179                verruculogen metabolic process | is_a
GO:0042816                vitamin B6 metabolic process | is_a
GO:0018917                fluorene metabolic process | is_a
GO:0009441                glycolate metabolic process | is_a
GO:0018955                phenanthrene metabolic process | is_a
GO:1900573                emodin metabolic process | is_a
GO:0033510                luteolin metabolic process | is_a
GO:0033306                phytol metabolic process | is_a
GO:0033329                kaempferol O-glucoside metabolic process | is_a
GO:1901847                nicotinate metabolic process | is_a
GO:0071272                morphine metabolic process | is_a
GO:0030186                melatonin metabolic process | is_a
GO:0070982                L-asparagine metabolic process | is_a
GO:2001308                gliotoxin metabolic process | is_a
GO:0097054                L-glutamate biosynthetic process | is_a
GO:0042737                drug catabolic process | is_a
GO:2001134                methane biosynthetic process from carbon monoxide | is_a
GO:0042120                alginic acid metabolic process | is_a
GO:1900797                cordyol C metabolic process | is_a
GO:1902224                ketone body metabolic process | is_a
GO:0046655                folic acid metabolic process | is_a
GO:1903184                L-dopa metabolic process

is this a useful term? Looks a bit like a grab bag

**Comment by pgaudet** [comment]
This is due to ChEBI roles being used to infer relations. We are planning to remove them. This ticket is redundant with #14626

Pascale

**Comment by cmungall** [comment]
I'm OK with keeping this ticket open to discuss the drug terms specifically. I think we are trying to discuss too much in #14626, we will have different strategies for different kinds of roles.

For drugs, I think we should be driven by use cases. I don't think there are pure/basic biological use cases here, since drug is not a biological or chemical classification. However, it is clearly of use to some consumers of GO. We can sketch out some basic use cases: a pharma person wants to build a gene list of drug transporters or drug metabolizers to see if they can be targeted (we would be better to ask someone in this area to do this..).

For these use cases, I think the list above is too inclusive __but it would be good to probe further to determine exactly what the criteria are for the use case__. And perhaps for this use case, being inclusive is OK, the user would prefer to get more and then filter themselves.

But given that we are not happy with the list as is, the options are I laid out in #14626 are

 1. obsolete the grouping
 2. make our own drug classification
 3. ask chebi to fix

I would only do 2 __as an absolute last resort__ for drugs. Obviously there are other role branches in CHEBI where we want to ignore CHEBI and go with our own classification - the biological role branch for example. We are the experts here.

We should at least try 3. I suggested this in the other ticket on Feb 1, I guess no one has had a chance to reach out (OBO hat on: it's super-important that we communicate with other OBO ontologies if we find things we need to change. We all get frustrated when people complain about GO but expect us to read their minds, it's the same for other ontologies! By being in OBO, CHEBI is committed to working with us an other ontologies).

I created a ticket here: https://github.com/ebi-chebi/ChEBI/issues/3442

In the interim I suggest simply putting a comment on the term.

It would also help if people could propose operational definitions on the CHEBI ticket

**Comment by deustp01** [comment]
This should be an agenda item for the May GOC meeting. Reactome is feeling its way into annotating drugs - there is a lot to discuss both about classifying physical entities that can play the role of drug (easier for us because we only have one focus species; harder for a group whose scope includes fungi, bacteria, and humans), and finding reference resources that can support useful drug classifications (IUPHAR looks better to us than ChEBI. Not that ChEBI is set aside for small molecules, but a small molecule drug is an entity with a ChEBI reference for its chemistry and an IUPHAR reference for its pharmacology).

I'm an in terested party two ways here, both because of Reactome and because I'm promoting the MAy meeting, but I think this comment is valid - it's a complex issue with diverse downstream consequences; a full discussion face to face will do a lot to sort things out.

**Comment by ukemi** [comment]
The simplest solution here would be to pursue the co-annotation route. It is easily done with GO-CAM models where the contextual information can be captured. This way we can avoid the problems with class relations that aren't always correct. The main issue is what do we do with the existing annotations and as Peter points out, when we are making annotations to chemicals that are acting as drugs, is ChEBI the best cross reference?

**Comment by ukemi** [comment]
Proposal is to merge the terms with the string 'drug' in them into their chemical parents. Then to add the specific chemicals as inputs. We need to announce this and in particular contact ChEBI to be sure they are not using the 'drug' terms and if they are, if this will be ok.

**Comment by krchristie** [comment]
As discussed in the ticket: **handling terms for xenobiotic role and removing drug role** #19460, we have decided on these actions. For more detail about specific terms, go the the ticket linked above.
* MF terms ("drug binding" & 2 xenobiotic transporter activity terms) - will be made OBSOLETE as it doesn't make sense to describe a molecular function based on the context a chemical is being used in. Annotations will need to be reviewed and transferred to an appropriate MF term based on chemical specificity if possible.
* BP terms (transport terms, metabolic terms, response terms) - "drug" terms will be merged into the corresponding "xenobiotic" terms if one exists, or renamed from "drug" to "xenobiotic" if not.  
* regulation BP terms - There only a few of these all variations of "regulation of response to drug", so we will request for these to be reviewed and then decide if they should be converted to "xenobiotic" terms or Obsoleted.

As the new ticket comprehensively covers the plan for all of the drug and xenobiotic terms, I'm going to close this ticket.
