### ISSUE TITLE
Change name of GO:0008518 reduced folate carrier activity?

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#15461]
Related to the carrier vs. transporter discussion in #14336, the term GO:0008518 reduced folate carrier activity is correctly under transmembrane transporter activity but the term name now is confusing. Could it be renamed reduced folate transporter activity?
It's referred to in the definition as a transporter.

Thanks,
Rachael.

**Comment by pgaudet** [comment]
Right - I didn't touch the 'secondary active transmembrane transporter activity' yet (because I need to read more about it). For the reduced folate carrier, am I not clear whether the name should just be 'reduced folate transmembrane transporter activity' or 'reduced folate secondary active transmembrane transporter activity' - what do you think ? 
(that being said, I cannot find any information as to why it's classified as a secondary active transporter.) 

Also, as far as I understand secondary transporters should be either symporters or antiporters: 
https://www.wikilectures.eu/w/Secondary_Active_Transport
Any idea which one is the folate carrier ? Maybe it's an antiporter ? 
https://www.researchgate.net/figure/A-Chemical-structure-of-pralatrexate-and-methotrexate-B-Internalization-and-retention_fig1_236255401

Thanks, Pascale

**Comment by rachhuntley** [comment]
Hi Pascale,

Yes, I think it's an antiporter.

So from the paper linked to GO:secondary active transmembrane transporter activity (http://europepmc.org/articles/PMC98997), it says "It is considered to be a secondary active transporter if a secondary source of energy (i.e., an ion electrochemical gradient, termed the proton motive force [PMF] in the case of protons or the sodium motive force [SMF] in the case of sodium ions), generated at the expense of a primary energy source, is coupled to the process."

Looking for information on the reduced folate carrier, it looks like it is a secondary active transporter based on information in a couple of places:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3806226/ :
"For reduced folate carrier (RFC), as noted above, this is driven by extrusion of anions down a large (intra- to extracellular) concentration gradient."

https://en.wikipedia.org/wiki/Reduced_folate_carrier_family:
"The RFC members appear to transport reduced folate by an energy-dependent, pH-dependent, Na+-independent mechanism. Folate:H+ symport, folate:OH−antiport and folate:anion antiport mechanisms have been proposed. Intracellular anions are able to promote folate derivative uptake. A bidirectional anion antiport mechanism for RFC family members is favored."

and the description of the RFC antiport mechanism in Fig 8 of this paper "Augmentation of Reduced Folate Carrier-Mediated Folate/Antifolate Transport through an Antiport Mechanism with 5-Aminoimidazole-4-Carboxamide Riboside Monophosphate" (http://molpharm.aspetjournals.org/content/82/2/209)

I hope that helps (I've learnt something new, at least!)
Rachael.

**Comment by pgaudet** [comment]
I can rename the term 'folic acid antiporter activity'; however there are 3 EXP annotations - none of which are consistent with an antiporter: 
* UniProt: F1N2M7 BHF : " the transport mechanism is likely to be either folate/H(+) co-transport or folate/OH(-) exchange. " PMID: 10787414
* RGD:3695 PMID:  11600421 "two distinct transport activities." -> should be annotated to     GO:0008517  BHF  folic acid transmembrane transporter activity -> it doesn't look like at mechanisms here. 

I am tempted to merge GO:0008518 folate transmembrane transporter activity

What do you think ? 

Pascale

**Comment by rachhuntley** [comment]
I thought the question was whether to rename the carrier term to 'reduced folate transmembrane transporter activity' or 'reduced folate secondary active transmembrane transporter activity' (rather than a more specific antiporter term)?

So the three annotations are all for the same protein, SLC19A1/RFC1 "folate transporter 1" (from cow, human and rat), this belongs to the reduced folate carrier family (http://tcdb.org/search/result.php?tc=2.A.48), which are in the MFS superfamily (secondary transporters: http://tcdb.org/superfamily.php?id=3)

Secondary active transporters couple movement of an ion to movement of another molecule or ion, so the statement for the first annotation "The transport mechanism is likely to be either folate/H(+) co-transport or folate/OH(-) exchange" seems to fit with this.

However, folic acid can be transported in two different ways, either by a solute carrier (e.g. RFC1) or by a folate receptor. So we have these four terms that aren't related to each other:
GO:0008518 reduced folate carrier activity
GO:0061714 folic acid receptor activity
GO:0106063 G-protein coupled folate receptor activity
GO:0008517 folic acid transmembrane transporter activity

I would have expected GO:0008517 folic acid transmembrane transporter activity to be a parent (unless you don't class receptors as transporters?), but at least a parent of GO:0008518 reduced folate carrier activity?

For the RFC1 annotations where there is no evidence of the mechanism, these should probably be annotated using GO:0008517 folic acid transmembrane transporter activity.

**Comment by pgaudet** [comment]
Hi @rachhuntley 
Thanks for looking into this, it's really helpful. 

This is what I did: (lines with a "+" are new, lines with a "-" are deleted)

 id: GO:0008518
-name: reduced folate carrier activity
+name: reduced folate transmembrane transporter activity
 namespace: molecular_function
-def: "Enables the transfer of reduced folate from one side of a membrane to the other, up its concentration gradient. The transporter binds the solute and undergoes a series of conformational changes. Transport works equally well in either direction and is driven by a chemiosmotic source of energy. Secondary active transporters include symporters and antiporters." [GOC:mtg_transport]
+def: "Enables the transfer of reduced folate from one side of a membrane to the other." [GOC:mtg_transport, PMID:21568705]
+comment: Changed term label see https://github.com/geneontology/go-ontology/issues/15461.
+synonym: "reduced folate carrier activity" NARROW []
 synonym: "reduced folate transporter" BROAD []
 xref: TC:2.A.48
-is_a: GO:0015291 ! secondary active transmembrane transporter activity
+is_a: GO:0022857 ! transmembrane transporter activity
+relationship: part_of GO:0098838 ! reduced folate transmembrane transport
 
Hopefully that resolved the issue. 
---
To answer your question: no, receptors are not transporters according to the MF refactoring. 
-> GO:0061714 folic acid receptor activity -> endocytosis
-> GO:0106063 G-protein coupled folate receptor activity -> signaling

I don't know if we want to create 'folic acid import into cell by endocytosis' -otherwise please open a new ticket. I think we can leave it as-is for now. 

Thanks, Pascale

**Comment by rachhuntley** [comment]
Hi Pascale,
I think this works.

So for folate receptors, presumably we shouldn't be annotating them to folic acid transport? A better term would be GO:1904447 folic acid import across plasma membrane.

If so, I will contact InterPro as they have the folate receptor family mapped to folic acid transport and folic acid transmembrane transporter activity (http://www.ebi.ac.uk/interpro/entry/IPR032935).
They may well have other receptor families mapped to transport terms.

Thanks,
Rachael.

**Comment by pgaudet** [comment]
* GO:0008518 reduced folate carrier activity: RFC; SLC19A1), a ubiquitously expressed organic anion antiporter that exchanges folate with other inorganic or organic anions (Hinken et al., 2011) (from PMID 29571151)
* GO:0008517 folic acid transmembrane transporter activity may represent proton coupled folate transporter (PCFT; SLC46A1), an H+ gradient transporter, whose mRNA is expressed to a lesser extent in the brain than in the periphery (Zhao et al., 2011). (from PMID 29571151 )

**Comment by rachhuntley** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3885234/
states RFC is an antiporter and PCFT is a symporter.

There is also a mitochondrial folate transporter (MFT; SLC25A32; UniProt:Q9H2D1) http://www.jbc.org/content/286/36/31480.full

**Comment by pgaudet** [comment]
Here's what I did: 
* changed term label reduced folate carrier -> folate antiporter activity, updated definition, parents and x-references
* Created a new symporter term: 
+id: GO:0140211
+name: folic acid:proton symporter activity
+namespace: biological_process
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: folic acid(out) + H+(out) = folic acid(in) + H+(in). The main folic acid symporter is the Proton-Coupled Folate Transporter (PCFT/SLC46A1), which has similar affinity for transport of reduced folates (5-methyl THF, 5-formyl THF) and folic acid." [PMID:24745983]
+xref: TC:2.A.1.50.1
+intersection_of: GO:0015293 ! symporter activity
+intersection_of: transports_or_maintains_localization_of CHEBI:24636 ! proton
+intersection_of: transports_or_maintains_localization_of CHEBI:27470 ! folic acid

**Comment by pgaudet** [comment]
Also: I checked the annotations, and except for two InterPro everything is OK, although some annotations could be moved to the more specific new term (folic acid:proton symporter activity for SLC46A1 family members). I attach the annotations to the ticket. 

Thanks, Pascale
