### ISSUE TITLE
mRNA cleavage and polyadenylation specificity factor complex assembly

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#15478]
May we have a term for assembly of the complex represented by GO:0005847?

id: GO:new
name: mRNA cleavage and polyadenylation specificity factor complex assembly
namespace: biological_process
def: "The aggregation, arrangement and bonding together of a set of components to form the mRNA cleavage and polyadenylation specificity factor complex." [PMID:27401558]
*is_a: GO:0022618 ! ribonucleoprotein complex assembly
part_of: RNA 3'-end processing ! GO:0031123

optional: include gloss with definition to say the complex forms cotranscriptionally, and/or to include more details from the definition of the complex itself

*RNP seems implied by RNA binding noted in GO:0005847 def, and by cotranscriptional assembly (per cited paper intro), but GO:0005847 is not is_a GO:1990904 ! ribonucleoprotein complex. For the new term, use GO:0034622 ! cellular protein-containing complex assembly if GO:0022618 wouldn't work well.

**Comment by vanaukenk** [comment]
@mah11 
Looking at a few papers on the CPSF, it seems that the complex is described as a protein-containing complex that interacts with pre-mRNA, so I would be inclined to use GO:0034622 ! cellular protein-containing complex assembly for the is_a parent rather than GO:1990904 ! ribonucleoprotein complex.
I'm happy to include a more detailed definition, but could you please add the exact text you'd like to this ticket and then I'll go ahead and create the term.  
Thx.

**Comment by mah11** [comment]
> I would be inclined to use GO:0034622 ... for the is_a parent rather than GO:1990904

fine; thanks for investigating

> I'm happy to include a more detailed definition, but could you please add the exact text you'd like

I have no requirement or preference for text beyond the standard phrasing I put in the original summary; I merely noted what content might go into a gloss if anyone on the GO-editorial end thought it advisable.
