### ISSUE TITLE
amyloid precursor protein metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15494]
https://www.ebi.ac.uk/QuickGO/term/GO:0042982
seems an odd term (isn't it just protein maturation?)

if it is required, shouldn't it be a child of this?
https://www.ebi.ac.uk/QuickGO/term/GO:0051604
@RLovering

**Comment by BarbaraCzub** [comment]
The parent term 'GO:0019538 protein metabolic process' has some other odd child terms of similar nature, e.g. 'GO:0050757 thymidylate synthase biosynthetic process', 'GO:1901142 insulin metabolic process', 'GO:0045558 TRAIL receptor 1 biosynthetic process', etc., as well as 'GO:0051604 protein maturation', and others.

So even if I shuffle the amyloid terms around, this whole branch requires tidying up, which will likely turn into a mini-project.

@ukemi should I make the edits involving the amyloid protein, and close this ticket? Or should I add the label 'mini-project' to address the need for revision of other terms in this branch (and un-assign myself)?

**Comment by ValWood** [comment]
Hi
 
@BarbaraCzub , to me the others seem OK here because they do not  explicitly mention a precursor. amyloid *precursor* protein metabolic implies maturation.

GO:0051604 protein maturation is correctly placed under here.

For the others  I'm not sure that they should exist:
thymidylate synthase biosynthetic process (has no annotations) @pgaudet  obsolete?
TRAIL receptor 1 biosynthetic process' (has no annotations)  @pgaudet  obsolete?

but is out of scope for this ticket.

So I think just adding the missing parent is good for now.
I can open a new ticket if @pgaudet  thinks oboletion is appropriate for those...

**Comment by ValWood** [comment]
"Insulin  metabolic process" is OK for example, because it's useful and is split into processing, and catabolism. The processing part is already linked to maturation.

**Comment by ukemi** [comment]
Hi @BarbaraCzub, 
It would be best to address the specific issue in this ticket and close it. It we feel that there are other issues, we should open tickets to address those specifically.

**Comment by BarbaraCzub** [comment]
'Amyloid precursor protein' (or APP) is a protein name (https://www.uniprot.org/uniprot/P05067#names_and_taxonomy). The name has the word _precursor_ in it, because it had been initially identified as a precursor of amyloid-beta, before other roles of APP started being explored and identified.
Therefore, the GO term name 'amyloid precursor protein (P05067) metabolic process' does not technically differ from 'insulin (P01308) metabolic process'.

If 'amyloid precursor protein metabolic process' becomes a child of 'GO:0051604 protein maturation', then 'GO:0042987 amyloid precursor protein catabolic process' (exact synonym: 'amyloid precursor protein degradation') can no longer be a child of 'amyloid precursor protein metabolic process', can it?(Degradation and maturation should be mutually exclusive). @ValWood @ukemi Do you have any suggestions on how to address this?

**Comment by BarbaraCzub** [comment]
@ValWood I agree that 'GO:0051604 protein maturation' is correctly placed under 'GO:0019538 protein metabolic process'.

**Comment by BarbaraCzub** [comment]
Hi @ValWood, yes, at least my understanding is that it is a gene product description in this GO term name.

**Comment by BarbaraCzub** [comment]
Hi @ukemi both our statements are in agreement. APP is a precursor of amyloid-beta, which contribute to formation of amyloid-beta fibrils, which ultimately deposit in the brain forming amyloid plaques/lesions. We're definitely keeping the metabolism term, we were just discussing its correct parentage (and then the consequences for the catabolism child term).

**Comment by ValWood** [comment]
Although
GO:0042983   amyloid precursor protein biosynthetic process
is defined
The chemical reactions and pathways resulting in the formation of amyloid precursor protein (APP), the precursor of amyloid-beta, a glycoprotein associated with Alzheimer's disease.

which implies that this *is* the maturation term

because there are separate terms for 
GO:0050435 amyloid-beta metabolic process

does 
GO:0042983   amyloid precursor protein biosynthetic process
include anything other than processing?

**Comment by BarbaraCzub** [comment]
> "I thought it was referring to metabolism of the precursor!"
@ValWood APP (amyloid precursor protein) is the precursor...

**Comment by BarbaraCzub** [comment]
'GO:0042983 amyloid precursor protein biosynthetic process' will include processing (in different cellular compartments, as the protein is being delivered to the cell surface) and likely also some post-translational modifications (I'd need to look this up).

**Comment by ukemi** [comment]
It is certainly glycosylated.

**Comment by BarbaraCzub** [comment]
Yes, it is a glycoprotein for sure.

**Comment by BarbaraCzub** [comment]
But if we place 'amyloid precursor protein metabolic process' under 'protein maturation', then what happens to its child term 'amyloid precursor protein catabolic process'?

**Comment by ukemi** [comment]
I think you have made a good argument that metabolism is more than just maturation.

**Comment by ValWood** [comment]
Maybe not, anyway you can close for me, I'll just include the *metabolism* term...

**Comment by deustp01** [comment]
I wonder if the right action here is amputation, citing the GO principle that GO terms refer to functions and processes, that are used to annotate specific proteins like amyloid precursor protein, insulin, etc. So terms for post- and co-translational modifications are fine, and terms that assign teleological purpose like "maturation" and "catabolism" are OK, but not terms for APP catabolism. See the discussion from, what, 10 years ago, that replaced an extensive array of protease terms like "trypsin activity" sith a limited set that distinguished proteases on the basis of reaction mechanism (serine, metallo, etc) and site of action on the target polypeptide )(endo, N-terminal, C-terminal). @mah11 am I remembering correctly?

**Comment by mah11** [comment]
re @deustp01 

> replaced an extensive array of protease terms ... am I remembering correctly?

It's certainly correct that we purged the peptidase activity branch of many terms of varying degrees of substrate specificity. In that case much of the rationale consisted of two poinsts: 1) that the obsolete terms did not reflect any mechanisms not covered by the smaller set we retained; and 2) it was so difficult to create and maintain adequate definitions for the substrate specificites (especially for the enzymes with broad specificity or loose target site requirements) that the experts even regretted attempting to include substrate-specific entries in EC, let alone GO MF.

I'll leave it to the current GO editors to decide how good a precedent that sets for metabolism terms in BP, but I have no objection to streamlining, especially now that we have the extensions available to specify protein substrates (which we didn't way back when).

**Comment by deustp01** [comment]
Hmmm. No argument about the value of cleaning up and reorganizing terms for protein metabolism that are agnostic as to the identity of the protein metabolized, and then getting those terms accurately applied to APP. But it's harder to see the justification, in terms of GO logic and consistent granularity, for making protein-specific children even for especially interesting proteins.

**Comment by BarbaraCzub** [comment]
I agree that the definition suggests that the term 'amyloid precursor protein biosynthetic process' actually refers to maturation of APP, as it mentions APP is a glycoprotein.
There are only 8 manual experimental annotations to '_positive/negative regulation of_ amyloid precursor protein biosynthetic process' (I found no direct annotations to 'amyloid precursor protein biosynthetic process').

<img width="1136" alt="screen shot 2018-04-11 at 14 21 07" src="https://user-images.githubusercontent.com/16541096/38619240-a17d2006-3d93-11e8-9b3d-5df01c5894a6.png">

I'll revise these annotations and make sure that they'll still be correct, if 'amyloid precursor protein biosynthetic process' is renamed as 'amyloid precursor protein maturation' (and the regulation child terms are renamed accordingly). 

If the existing 8 annotations appear to be based on regulation of APP maturation (rather than biosynthesis of the APP peptide chain), then I'll rename 'amyloid precursor protein biosynthetic process' as 'amyloid precursor protein maturation', and I'll make it a child of 'protein maturation'. 

@ukemi do you agree this is the right approach?

cc @RLovering

**Comment by BarbaraCzub** [comment]
Hi @ValWood,

I discussed this ticket with @RLovering last week and she agreed I should take a look at the existing annotations as I previously suggested. 

I have just looked at the summary of results in abstracts of 10 papers for which manual experimental annotations currently exit (relevant abstract fragments are pasted in here further below). My first impressions are that for most of these annotations the correct GO term(s) would have been "(positive/negative regulation of) amyloid precursor protein **metabolic** process", and _NOT_ "biosynthetic process" or "maturation". (I have not looked at any experimental figures at this stage).

### Reasoning:
1. All of the abstracts referred to below describe regulation of amyloid-beta generation (among other processes).
2. Amyloid precursor protein (APP) biosynthesis needs to occur first in order for amyloid-beta generation to be able to occur.
   _Relevant Definitions:
- GO:0042983 amyloid precursor protein biosynthetic process: "The chemical reactions and pathways resulting in the formation of amyloid precursor protein (APP), the precursor of amyloid-beta, a glycoprotein associated with Alzheimer's disease."
- GO:0034205 amyloid-beta formation: "The generation of amyloid-beta by cleavage of the amyloid precursor protein (APP)."_
3. There is no conclusive evidence in the literature that amyloid-beta generation is required for amyloid precursor protein (APP) maturation, because: 
   (a) the role(s) of APP itself is/are still ambiguous, so it cannot be precisely determined when it can be considered 'mature', or when it has attained its "full functional capacity"; and 
   (b) APP can be processed via two major routes: non-amyloidogenic (involves cleavage by alpha and gamma secretases) and amyloidogenic (involves cleavage by beta and gamma secretases) (please see Figure 2 in: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3174086/); only the latter results in formation of amyloid-beta. PMID: 19225519 shows that growth factor deprivation is important in triggering cleavage by the beta secretase.
   _Relevant Definition:
- GO:0051604 protein maturation: "Any process leading to the attainment of the full functional capacity of a protein."_
4. With the exception of PMID: 16027166, the papers for which the GO term(s) (positive/negative regulation of) amyloid precursor protein biosynthetic process" were used do not seem to provide evidence for amyloid precursor protein synthesis (defined as "The chemical reactions and pathways resulting in the formation of amyloid precursor protein (APP), the precursor of amyloid-beta, a glycoprotein associated with Alzheimer's disease."). On the contrary: the abstracts suggest APP metabolism was studied, and not its biosynthesis (please see relevant phrases which I marked in bold in the abstract fragments below). I should re-emphasise that my reasoning is based only on information provided in abstracts, and I have not looked at the actual experimental figures in each paper.

### Conclusion:
Based on the reasons outlined above I suggest that groups, which contributed these [10 annotations](https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in,regulates&goId=GO:0042983&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants) should probably revise them to check whether they are correct, based on the GO definitions; however, I do not think the term "amyloid precursor protein biosynthetic process" needs to be changed to "amyloid precursor protein maturation".

If you have any further comments or questions, I suggest that an annotation review ticket in the annotation tracker would probably be more appropriate at this stage prior to deciding what changes should be made in the ontology.
cc @ukemi 

Thanks,
Barbara

### Relevant fragments from abstracts of papers for which the GO term(s) (positive/negative regulation of) amyloid precursor protein biosynthetic process" were used:

PMID: 10833507 --> "The protein **XB51 inhibited the association of X11L with amyloid precursor protein** through a non-competitive mechanism and **abolished the suppression of beta-amyloid production** by X11L. (...) These observations suggest that XB51, together with X11L, plays an important role in the regulatory system of amyloid precursor protein metabolism and beta-amyloid generation."

PMID: 12801932 --> "**Selective inactivation of BACE1 by RNA interference results in decreased beta-cleaved secreted APP and A beta peptide secretion** from cells, as expected. Selective inactivation of BACE2 by RNAi results in increased beta-cleaved secreted APP and A beta peptide secretion from cells. Simultaneous targeting of both enzymes by RNA interference does not have any net effect on A beta released from cells. Our observations of changes in **APP metabolism** and **A beta** are consistent with a role of BACE2 in suppressing A beta production in cells that co-express both enzymes."

PMID: 14627703 --> "Overexpression of Par-4 significantly **increased production of Aβ-(1-42)** after initiation of apoptotic cascades, indicating factors regulating apoptotic pathways may also affect processing of β-amyloid precursor protein (APP)."

PMID: 16027166 --> "The presence of BRI2 had a modulatory effect on APP processing, specifically **increasing the levels of cellular APP** as well as **beta-secretase-generated COOH-terminal** fragments while decreasing the levels of alpha-secretase-generated COOH-terminal fragments as well as the secretion of total APP and Abeta peptides."
_[Barbara's comment: Based on this abstract this paper does probably show regulation of APP biosynthesis ("**increasing the levels of cellular APP**") in addition to amyloid-beta formation later on]_.

PMID: 17412327 —-> "Here we report that ACAT-1 RNAi reduced cellular ACAT-1 protein by approximately 50% and cholesteryl ester levels by 22% while causing a slight increase in the free cholesterol content of ER membranes. This correlated with **reduced proteolytic processing of APP and 40% decrease in Abeta secretion**. These data show that even a modest decrease in ACAT activity can have robust suppressive effects on Abeta generation."

PMID: 18201567 --> "Here, nicastrin mutants containing targeting signals to the endoplasmic reticulum, trans-Golgi network, lysosomes, or plasma membrane have been shown to yield active gamma-secretase complexes with different activities and specificities: wild-type and plasma membrane nicastrin complexes **yielded the highest amounts of secreted amyloid-beta peptide (Abeta), predominantly Abeta40, whereas intracellular targeted mutants produced intracellular Abeta, with a comparatively higher amount of Abeta42. These results suggest that compartmental microenvironments play a role in gamma-secretase activity and specificity.**"

PMID: 18429932 --> "ABCA7 also significantly **inhibited Abeta secretion** from Chinese hamster ovary cells stably expressing human amyloid precursor protein (APP) or APP containing the Swedish K670M671-->N670L671 mutations when compared with mock-transfected cells. Studies with fluorogenic substrates indicated that ABCA7 had no impact on alpha-, beta-, or gamma-secretase activities. Live cell imaging of Chinese hamster ovary cells expressing APP-GFP indicated **an apparent retention of APP in a perinuclear location** in ABCA7 co-transfected cells."

PMID: 18524908 --> "Unexpectedly, we also find that expression of wild-type human BRI2 **reduces cerebral Abeta deposition** in an AD mouse model. Additional data indicate that the 23 aa peptide, Bri23, released from BRI2 by normal processing, is present in human CSF, **inhibits Abeta aggregation** in vitro and mediates its anti-amyloidogenic effect in vivo. These studies demonstrate that BRI2 is a novel mediator of Abeta deposition in vivo."

PMID: 23826707 --> "Inactivation of nctsn r**esulted in substantial accumulation of APP-CTFs** and altered PS1 expression. These results reveal a key role for ncstn in **modulating Aβ production** and amyloid plaque formation in vivo and suggest ncstn as a target in AD therapeutics."
