### ISSUE TITLE
peptide-cross linking

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15492]
This seems to be a strange term to exist since
actin cross linking was obsoleted
This term was made obsolete because it represents a combination of molecular functions.
https://www.ebi.ac.uk/QuickGO/term/GO:0003780

and presumably "protein binding, bridging" would be more appropriate (or other function terms?)

It's not really clear what the context is from the annotations (various I think), and some are "cross-linked proteins" rather than  "cross linking"

**Comment by krchristie** [comment]
The actin cross linking term had a vague definition that included binding:

> Definition (GO:0003780 GONUTS page)
> OBSOLETE. Interacting selectively with two actin filaments to anchor them together.
> Comments: This term was made obsolete because it represents a combination of molecular functions.

The peptide-cross linking term does not look comparable to the actin cross linking term that was obsoleted, because it is specifically defined as:
> The formation of a covalent cross-link between or within protein chains.

and it has many specific child terms that look like they have been put in systematically, several of which have been used:

Row Labels | Total
-- | --
isopeptide cross-linking | 9
isopeptide cross-linking   via N6-(L-isoglutamyl)-L-lysine | 11
peptide cross-linking | 566
peptide cross-linking via   chondroitin 4-sulfate glycosaminoglycan | 44
peptide cross-linking via   L-cystine | 1
Grand Total | 631

Summary: I think this term and its children are fine; no action required.

**Comment by ValWood** [comment]
Aren't these  describing molecular functions though? not biological processes (that's what originally alerted me to the term), only has 61 manual annotations (term or children).... so does not seem to be very used.
