### ISSUE TITLE
MP GO:0032963    collagen metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15500]
should  have some "multicellular parentage"
GO:0032963    collagen metabolic process

**Comment by pgaudet** [comment]
No. Bacteria can degrade it.

**Comment by rachhuntley** [comment]
They occur from sponges to humans, i.e. metazoa, according to this paper https://onlinelibrary.wiley.com/doi/abs/10.1002/ar.10162

So maybe annotations to bacteria should be to "collagen catabolic process in other organism"?

**Comment by pgaudet** [comment]
Bacteria and some unicellular fungi digest collagen and other molecules (food) that they encounter, not necessarily in the context of an interaction with 'another organism' - or am I missing your point ? 

Pascale

**Comment by ValWood** [comment]
A good point. But do we represent every single molecule that organisms digest?

I prefer some "extracellular digestion terms" for broad nutritional component categories (carbohydrate, nucleic acid, protein, lipid), for usefulness, interpretation and sustainability?
https://github.com/geneontology/go-ontology/issues/14761

then we could always add a has_substrate using CHEBI, or a protein ID or whatever....

**Comment by ValWood** [comment]
collagen is even in chebi
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:3815

**Comment by ValWood** [comment]
.....although not classified as a protein ;)

**Comment by pgaudet** [comment]
@ValWood 
> But do we represent every single molecule that organisms digest?
That I dont know but it seems correct to have 'x catabolic process' for an exogenous molecule. 

@ukemi @thomaspd 
anyone else wants to weigh in? 

Thanks, Pascale

**Comment by ukemi** [comment]
> A good point. But do we represent every single molecule that organisms digest?

No, but I would think digestion of collagen is pretty important biologically. @thomaspd

**Comment by RLovering** [comment]
collagen metabolism is a key aspect of extracellular matrix deposition and restructuring. This is the main reason we apply this term. I guess adding collagen to AE field (or noctua models) would state the same thing, but only if tools were using the AE field.

Would it be possible to point out to curators that this term will be removed once the AE/Noctua field is being used in analysis tools, so that people can start creating AEs to capture this data now.

**Comment by deustp01** [comment]
Maybe we can generalize away from collagens to the whole collection of proteins required for the formation of extracellular matrix, exactly as Ruth says.

**Comment by ValWood** [comment]
I'm not disputing "collagen metabolism" as a term.... but rather how to describe it's digestion by other species.....

**Comment by deustp01** [comment]
I can't think of a case in which digestion of collagen or extracellular matrix by another species occurs except as part of a disease process - think gangrene - so is this in scope for GO? Maybe fungi and bacteria growing on carrion?

**Comment by ValWood** [comment]
Maybe this isn't  worth worrying about for now? I thought the parent could be added when I was looking at slimming to identify "unknowns", but  it seems more complicated. can close for me.....

**Comment by pgaudet** [comment]
Isn't gangrene the other perspective, ie 'feeding', when you're the bacteria? 

This issue seems to touch on the question of 'what is metabolism' - certainly degrading molecules as a source of food is different from other types of 'catabolic processes'. It may be useful to leave this open to have examples of different 'types' of catabolism?

**Comment by ukemi** [comment]
PMID:26150451
