### ISSUE TITLE
NTR: lipid sulfatide binding term request

### ISSUE THREAD

**Issue by hbye** [geneontology/go-ontology#15501]
Hello,

Please could the term lipid sulfatide binding (possible synonyms: 3-O-sulfogalactosylceramide, SM4, sulfated galactocerebroside, sulfated glycolipids, galactosyl ceramide-I3-sulfate) be added to the ontology as a child of GO:0051861: glycolipid binding? Interaction assays in PMID:29497057 demonstrate that human MANF and C.elegans manf-1 bind to lipid sulfatides. Other publications such as PMIDs: 3549017, 22977233, 22619219 and 21525289 may also support the validity of this new term and provide data indicating the importance of lipid sulfatides in a range of biological processes. Please let me know if more information is required.

Thank you very much,
Hema

**Comment by krchristie** [comment]
In looking quickly at the papers you listed, as well as a couple other sources, it seemed that the  commonly used name is just "sulfatide" not "lipid sulfatide" so I just used "sulfatide binding" as the term name.

In addition to the PMIDs you list, I included PMID:23574804, and also the Wikipedia paper for sulfatide (https://en.wikipedia.org/wiki/Sulfatide), which was very helpful.

I have included most of the synonyms you suggest, three as EXACT since they were listed in the Wikipedia page (which seemed well referenced)
+synonym: "3-O-sulfogalactosylceramide binding" EXACT []
+synonym: "SM4 binding" EXACT []
+synonym: "sulfated galactocerebroside binding" EXACT []

but not "galactosyl ceramide-I3-sulfate binding" since PMID:3486185 indicates that `Rat kidney lipids contain 5 characterized sulfated glycolipids`, which makes it clear that it is a sulfoglycolipid, but not necessarily a sulfatide.

and not the one for "sulfated glycolipid" since sulfatide is not the only sulfated glycolipid, or sulfoglygolipid. The PMID I added also discusses seminolipid as the other major sulfoglycolipid in mammals. I would be fine with "sulfated glycolipid binding" as an EXACT synonym of a term for "sulfoglycolipid binding", but would rather not attach it here where it could potentially be misleading, even as a BROAD synonym.
