### ISSUE TITLE
Merge  GO:0001133 RNA polymerase II transcription factor activity, sequence-specific transcription regulatory region DNA binding into     GO:0000981 RNA polymerase II transcription factor activity, sequence-specific DNA binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15530]
Hello, 

I am going to merge 
Merge  GO:0001133 RNA polymerase II transcription factor activity, sequence-specific transcription regulatory region DNA binding 
into     
GO:0000981 RNA polymerase II transcription factor activity, sequence-specific DNA binding

The two terms are essentially the same and GO:0001133 only has only 29 annotations from 2011 an 2012. 

@krchristie @ValWood @RLovering 
Any feedback ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I would be happy to have a single term to represent this activity, but bear in mind that the 2 terms have different meanings.

GO:0001133 RNA polymerase II transcription factor activity, sequence-specific transcription regulatory region DNA binding
is descibing the  "transcription factor activity" i.e.e  "regulation of transcription"

and
GO:0000981 RNA polymerase II transcription factor activity, sequence-specific DNA binding
is describing the DNA binding activity.

I  would prefer a single MF term for "DNA binding transcription factor" which could be coupled to the process of "transcription" or "regulation of transcription" (because this is really what 'factor' means-  a factor involved in a process)....this would be much, much simpler.....

but a straight up merge might be problematic, because we will lose the  differences where the "DNA binding activity" has been assayed, or whether "transcription" has been assayed ( DNA binding often comes form similarity in these cases, but this allows a TF activity term to be used).

difficult.....

**Comment by pgaudet** [comment]
Hi @ValWood 
Thanks for the feedback, this shows that this is still not clear. 
For the DNA binding we should use the terms under binding, such as 'GO:0044212 transcription regulatory region DNA binding'

One suggestion for 'GO:0000981 RNA polymerase II transcription factor activity, sequence-specific DNA binding' was to change the label to 'RNA polymerase II _specific_ transcription factor activity' , to distinguish it from the general transcription factors (and to avoid the confusion as to whether we are looking at DNA binding or at the transcription factor activity).

Would that help ? 

Thanks, Pascale

**Comment by ValWood** [comment]
OK I was confused. Neither of these are a "DNA binding" term.

The difference between these 2 terms is that one is an activator and one isn't (it covers activators and repressors). Although the parents are odd...

**Comment by ValWood** [comment]
Hi @pgaudet  can you confirm the change from this ticket, it wasn't clear to me.

**Comment by pgaudet** [comment]
**I merged** 
GO:0001133 RNA polymerase II transcription factor activity, sequence-specific transcription regulatory region DNA binding
**into**
GO:0000981 RNA polymerase II transcription factor activity, sequence-specific DNA binding

OK ?

**Comment by ValWood** [comment]
Yes actually we didn't use GO:0001133 no prob

**Comment by RLovering** [comment]
sounds good to me
