### ISSUE TITLE
NTR- filamentous growth MAPK cascade

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15545]
As per the proposal in ticket #14676, I proposed we make a new term under stress response MAPK cascade. 

filamentous growth MAPK cascade
is_a: stress-activated MAPK cascade
def: The MAPK cascade which is activated as a result of partial nutrient deprivation and which results in filamentous growth.
ref:PMID:17604854

@ValWood  and @robnash, any comments?

**Comment by robnash** [comment]
This makes sense to me. The 'stress-activated MAPK cascade' term, has a child term, 'MAPK cascade in response to starvation', and since two mechanisms can drive filamentous growth: a glucose starvation pathway and a nitrogen starvation pathway, I wonder if it should looks like this:

filamentous growth MAPK cascade
is_a: MAPK cascade in response to starvation

Just an idea, but I agree with the idea for the term.

Cheers,
Rob

**Comment by ValWood** [comment]
I got a bit confused by all of this since I didn't look at it for a while. @Antonialock worked on this pathway so she will know better.

How does
GO:0000161    MAPK cascade involved in osmosensory signaling pathway
fit? that is also a stress pathway, but not under
GO:0051403    stress-activated MAPK cascade?

aren't all fungal  except  "pheromone MAP kinase pathways" stress pathways" of some sort?
(i.e osmolarity, cell wall, starvation) 

Are we using  "stress-activated MAPK cascade" as just a specific pathway name, or as a general process label ?

@Antonialock ....all I remember is we resolved everything correctly into 3 pathways  using the general MAPK cascade term, and response to extensions, and we were waiting to switch to the final  term labels.....

**Comment by ValWood** [comment]
OK, then that as good, I just can't remember since I didn't look at it for ages.
Antonia just arrived at my house so I asked her to take a look now.... but from this it looks fine...

**Comment by robnash** [comment]
Yeah, the 'MAPK cascade involved in osmosensory signaling' to be renamed 'osmosensory signaling MAPK cascade' is_a 'stress-activated MAPK cascade'. The only one I was unclear of now that you brought this up is the 'MAPK cascade involved in cell wall organization and biosynthesis' to be renamed 'cell wall integrity MAPK cascade'. This is also stress activated. From the review you provided (PMID: 17604854):

"The MAPK Slt2/Mpk1 becomes activated under a number of different conditions that stress the structure and function of the yeast cell wall, including hypotonic medium, treatment of cells with glucanases (e.g Zymolyase), exposure to chitin-binding agents (e.g. Calcofluor White and Congo Red), as well as oxidative stress, depolarization of the actin cytoskeleton, and pheromone-induced morphogenesis"

So this is also stress activated.

Cheers,
Rob

**Comment by ukemi** [comment]
Thanks @robnash, it is an easy fix to move the 'cell wall integrity cascade' to be a stress-activated cascade.  So the only yeast one that is not stress-activated is the pheromone response.

**Comment by robnash** [comment]
Sounds great! Thanks.

**Comment by Antonialock** [comment]
The osmosensory module in pombe is activated in response to a range of stresses (there's a whole phosphorelay system feeding into it for H2O2 sensing for example)

**Comment by vanaukenk** [comment]
I'm a bit confused by what MAPK cascade terms we are including in the ontology. 
For example, should the 'MAPK cascade involved in axon regeneration' that we used for WB annotation instead now be a child of p38MAPK cascade called 'axon regeneration MAPK cascade' or 'axon regeneration p38MAPK cascade'?
I'm reading a paper right now that describes a specific JNK cascade involved in synapse formation; should there then be a 'synapse formation JNK cascade'?

**Comment by ukemi** [comment]
Hi @vanaukenk,

This would be art of this ticket. #14323

The proposal (that I think was approved) here is that we will obsolete these terms. So the ones that are not in the proposal above are slated for either obsoletion or merging. @pgaudet, is this correct? I may reassign #14323 back to you once my edits are done here.

**Comment by ukemi** [comment]
I'm still not sure about the ascospore term. Any of the yeast folks want to weigh in on that one?

**Comment by ukemi** [comment]
term:MAPK cascade involved in ascospore formation
def: Any MAPK cascade that is involved in ascospore formation.

**Comment by vanaukenk** [comment]
Okay, so just to be clear, the reason we are keeping terms like 'osmosensory signaling MAPK cascade' then has more to do with how the pathways are named, or referred to, in yeast rather than that we are keeping some terms that include the overall process that the MAPK cascade is involved in?

**Comment by ukemi** [comment]
Yes. This is just the handle by which these are distinguished and grouped by members of the yeast community. The review has nice figures about why each of these pathways are grouped the way they are based on the players that are in the pathway and what triggers the pathway. It does a very nice job of discussing them as different types of MAPK pathways. For the other 'involved in' terms, I am reasonably sure that they represent one of these types of fundamental pathway that is executed in a different context. So the fundamental pathway is the same and the only difference is the context.

**Comment by robnash** [comment]
I think the 'MAPK cascade involved in ascospore formation' term is just another name for the 'spore wall assembly MAPK cascade' or spore wall morphogenesis MAPK cascade/pathway, although not really used in the literature. Mutations in SMK1, the MAPK, have spore wall defects, with cell wall layers missing, extranumerary, or improperly ordered. The term ascospore refers to a spore in an ascus, which in budding yeast is the tetrad. So this term could probably be merged, or obsoleted and a synonym added for the 'spore wall assembly MAPK cascade'. This is the least characterized of the five MAPK pathways in yeast, and its still possible that this is not a canonical pathway as to my knowledge no MAPKK or MAPKKKs have been identified, as mentioned in this 2007 review:

Chen RE, Thorner J. Function and regulation in MAPK signaling pathways:
lessons learned from the yeast Saccharomyces cerevisiae. Biochim Biophys Acta.
2007 Aug;1773(8):1311-40. Epub 2007 May 22. Review. PubMed PMID: 17604854; PubMed
Central PMCID: PMC2031910.

It appears to be activated by a novel mechanisms including these mentioned in this paper as well as autophosphorylation:

Tio CW, Omerza G, Phillips T, Lou HJ, Turk BE, Winter E. Ssp2 Binding
Activates the Smk1 Mitogen-Activated Protein Kinase. Mol Cell Biol. 2017 May
2;37(10). pii: e00607-16. doi: 10.1128/MCB.00607-16. Print 2017 May 15. PubMed
PMID: 28223369; PubMed Central PMCID: PMC5477552.

Original paper describing SMK1: 
Krisak L, Strich R, Winters RS, Hall JP, Mallory MJ, Kreitzer D, Tuan RS,
Winter E. SMK1, a developmentally regulated MAP kinase, is required for spore
wall assembly in Saccharomyces cerevisiae. Genes Dev. 1994 Sep 15;8(18):2151-61. 
PubMed PMID: 7958885.

A reference to spore wall morphogenesis:
Gustin MC, Albertyn J, Alexander M, Davenport K. MAP kinase pathways in the
yeast Saccharomyces cerevisiae. Microbiol Mol Biol Rev. 1998 Dec;62(4):1264-300. 
Review. PubMed PMID: 9841672; PubMed Central PMCID: PMC98946.

Additional reviews:
Huang LS, Doherty HK, Herskowitz I. The Smk1p MAP kinase negatively regulates 
Gsc2p, a 1,3-beta-glucan synthase, during spore wall morphogenesis in
Saccharomyces cerevisiae. Proc Natl Acad Sci U S A. 2005 Aug 30;102(35):12431-6. 
Epub 2005 Aug 22. PubMed PMID: 16116083; PubMed Central PMCID: PMC1194906.

Neiman AM. Ascospore formation in the yeast Saccharomyces cerevisiae.
Microbiol Mol Biol Rev. 2005 Dec;69(4):565-84. Review. PubMed PMID: 16339736;
PubMed Central PMCID: PMC1306807.

**Comment by ValWood** [comment]
Kimberley reminded me that there are really labels for specific modules, so
I’m still a bit confused by the stress-activated cascade part.

I would like to scrub my  previous suggestions that the other modules are given the  “stress-activated MAPK cascade” parentage.

If these are just labels, then only one module is referred to as the “stress activated MAPK cascade”  Im not sure that we need “osmosensory signaling MAPK cascade' Hog” because as I understand it, this is a  sub ranch of the same pathway/module.

For example, in fission yeast the same MAPK module (Sty1 cascade) , is used for 
oxidative stress and osmo stresses (an heat stress I think?), but with slightly different inputs and outputs. 
 “osmosensory signaling MAPK cascade” is a specific implementation of the “hog1/Sty1 stress-activated MAPK cascade” module.
Presumably we don’t want to replicate this particular module to represent every stress that it deals with? 


Does that make sense?
For this I would have used 
stress-activated MAPK cascade “involved in” response to GO:0006970    response to osmotic stress

stress-activated MAPK cascade “involved in” response to GO:0006970    response to oxidative stress

to annotate the different “wiring” of this module.

Otherwise it looks good.

**Comment by robnash** [comment]
I thought we had agreed upon the proposed structure and terms? Again, I am concerned about the user and how they would identify this vs what was proposed which was clear.

**Comment by robnash** [comment]
Cannot comment on all instances but the vast majority of experiments are carried out with osmostress via the addition NaCl or sorbitol. I would personally consider this a label for the module but perhaps David can make a call based on his experience. For me, its most important that the placement is intuitive to our users and correctly represents the biology.

**Comment by ukemi** [comment]
@ValWood 

Maybe I confused you. For this
----MAPK cascade involved in osmosensory signaling (RENAME 'osmosensory signaling MAPK cascade' Hog1)PMID:17604854

The new term is 'osmosensory signaling MAPK cascade', the Hog1 part is just there to keep me straight with what was in the review and for you guys to easily figure out which one I was talking about. The terms are within the quotes.

**Comment by ValWood** [comment]
No, my problem is that  the  'osmosensory signaling MAPK module' responds to multiple stresses (oxidative, heat, osmolarity)

If the point is to have a single label for this module, I would prefer that it did not mention "osmolarity sensing".

https://en.wikipedia.org/wiki/Mitogen-activated_protein_kinase
Fungi also have a pathway reminiscent of mammalian JNK/p38 signaling. This is the Hog1 pathway: activated by high osmolarity (in Saccharomyces cerevisiae) or a number of other abiotic stresses (in Schizosaccharomyces pombe). The MAP2 kinase of this pathway is called Pbs2 (related to mammalian MKK3/4/6/7), the dedicated MAP3 kinases involved in activation are Ssk2 and SSk22. The system in S. cerevisiae is activated by a sophisticated osmosensing module consisting of the Sho1 and Sln1 proteins, but it is yet unclear how other stimuli can elicit activation of Hog1.

Isn't this a general stress response module, with osmolarity being the most studied stress?

I would like to annotate Pombe Sty1 MapK pathway to the same term as budding yeast HOG1.

osmosensory signaling MAPK cascade would be OK, if you think it is warranted, but it would be useful to say  make it clear that this  MAPK is not ONLY for osmolarity  sensing (and not have response to osmolarity parentage, as we will eventually want to model inputs and outputs for different stresses *without*  pulling in osmolarity by default).

**Comment by ValWood** [comment]
we can use
"osmosensory signaling MAPK module" but it might look odd when modelling other stesses.

I guess it does not matter if it is defined to be specific stress agnostic?
i.e.
A series of molecular signals in which a stress-activated protein kinase (SAPK) cascade relays one or more of the signals, containing at least a Hog1/Sty1 family MAPK, a Pbs2/Wis1 family MAPKK and a  Ssk2/Win1 family MAP3K.
(mirroring the other defs)

a possible alternative
"Hog1/Sty1 stress-activated MAPK" 
(mirroring the other term names)
