### ISSUE TITLE
new GO term request: host cell centrosome

### ISSUE THREAD

**Issue by djow2019** [geneontology/go-ontology#15548]
Name: host cell centrosome

Definition: as taken from centrosome (GO:0005813): "A structure comprised of a core structure (in most organisms, a pair of centrioles) and peripheral material from which a microtubule-based structure, such as a spindle apparatus, is organized. Centrosomes occur close to the nucleus during interphase in many eukaryotic cells, though in animal cells it changes continually during the cell-division cycle."

Position in Hierarchy:  child of host cytoskeleton (GO:0044163)

Synonyms: host centrosome

Other notes: Maybe add another term: host actin cytoskeleton, child of host cytoskeleton, and then make host cell centrosome child of host actin cytoskeleton

**Comment by pgaudet** [comment]
Hi Derek, 

Do you have a reference (PMID) for this term ? 

Thanks, Pascale

**Comment by djow2019** [comment]
Will ISBN:0198547684 work?

**Comment by krchristie** [comment]
Hi Derek,

Yes, using the same ISBN reference already cited for the 'centrosome' term is fine. Do you have a personal reference for definitions you have contributed to? For example, mine is GOC:krc. I think it would be good to also reference you in this definition in the way that GOC:mah is also referenced for the definition of the existing 'centrosome' term. If you don't have one, let me know what initials you would want to use and I'll find out how to add you.

Regarding adding additional terms under 'host cell', we are currently adding only the terms specifically requested for annotation. Eventually we are hoping that there is a better way to do annotations in host cells so that we don't end up duplicating all of the Cellular Component ontology under 'host cell'. You can see some previous discussion of this issue in this ticket: https://github.com/geneontology/go-ontology/issues/13201 

-Karen
