### ISSUE TITLE
Use of GO:0018307     enzyme active site formation

### ISSUE THREAD

**Issue by jimhu-tamu** [geneontology/go-ontology#15594]
#1181 describes creation of this set of terms from TermGenie several years ago. We have a CACAO student trying to use this term. 

As I understand the notes on that issue, this is something that has to happen in trans. Should the parent be do not annotate? cc: @sandyl27

**Comment by hdrabkin** [comment]
@jimhu-tamu, it looks like the issue was closed with my question answered. There was no action item attached.

**Comment by pgaudet** [comment]
I agree with @hdrabkin , this is out of scope.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0018307 enzyme active site formation’ and its children: 

GO:0045427 enzyme active site formation via (phospho-5'-guanosine)-L-histidine
GO:0051113 enzyme active site formation via 1'-(phospho-5'-adenosine)-L-histidine
GO:0051115 enzyme active site formation via 1'-(phospho-5'-uridine)-L-histidine
GO:0018327 enzyme active site formation via 1'-phospho-L-histidine
GO:0018328 enzyme active site formation via 3'-phospho-L-histidine
GO:0018192 enzyme active site formation via cysteine modification to L-cysteine persulfide
GO:0018443 enzyme active site formation via L-aspartic 4-phosphoric anhydride
GO:0018324 enzyme active site formation via L-cysteine sulfenic acid
GO:0018323 enzyme active site formation via L-cysteine sulfinic acid
GO:0018329 enzyme active site formation via N6-(phospho-5'-adenosine)-L-lysine
GO:0018330 enzyme active site formation via N6-(phospho-5'-guanosine)-L-lysine
GO:0018332 enzyme active site formation via O-(phospho-5'-adenosine)-L-threonine
GO:0018331 enzyme active site formation via O-phospho-L-serine
GO:0018333 enzyme active site formation via O-phospho-L-threonine
GO:0050987 enzyme active site formation via O-sulfo-L-serine
GO:0050991 enzyme active site formation via O-sulfo-L-threonine
GO:0018334 enzyme active site formation via O4'-phospho-L-tyrosine
GO:0018248 enzyme active site formation via peptidyl cysteine sulfation
GO:0018326 enzyme active site formation via S-acetyl-L-cysteine
GO:0046894 enzyme active site formation via S-amidino-L-cysteine
GO:0018320 enzyme active site formation via S-methyl-L-cysteine
GO:0018325 enzyme active site formation via S-phospho-L-cysteine 

The reason for obsoletion is that this is outside the scope of GO. There are 11 manual annotations this term, see https://github.com/geneontology/go-annotation/issues/3511 by PIR, BHF and EcoCyc.

GO:0018307 is mapped to IPR012406, already mapped to protein folding, so it probably just needs to be removed. Otherwise the terms are no mapped, nor present in any subsets. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on November 18th, 2020. Unless objections are received by November 18th, 2020, we will assume that you agree to this change. You can add comments to the ticket: https://github.com/geneontology/go-ontology/issues/15594



Thanks, Pascale
