### ISSUE TITLE
NTR: rRNA pseudouridine synthase activity

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#15632]
For some reason, the only children of GO:0009982 are tRNA and snRNA pseudouridine synthase activities.  Could you please add the corresponding rRNA term?  Proposed analogous definition:
Catalysis of the reaction: rRNA uridine = rRNA pseudouridine. Conversion of uridine in a tRNA molecule to pseudouridine by rotation of the C1'-N-1 glycosidic bond of uridine in RNA to a C1'-C5.

EC numbers for these enzymes are 5.4.99.16 through 5.4.99.24.

Also, for some reason the "general" GO:0009982 has all those tRNA-related synonyms; maybe those should be moved to the tRNA-specific term, GO:0106029?

**Comment by krchristie** [comment]
Regarding relevant EC #'s for pseudouridine synthase activities, using both of these websites, I see these pseudouridine synthase activities:
- http://www.sbcs.qmul.ac.uk/iubmb/enzyme/EC5/cont5a.html
- https://enzyme.expasy.org/cgi-bin/enzyme/enzyme-search-ec

**5.4.99.12 - tRNA pseudouridine(38-40) synthase**
5.4.99.25 - tRNA pseudouridine(55) synthase
5.4.99.26 - tRNA pseudouridine(65) synthase
5.4.99.27 - tRNA pseudouridine(13) synthase
5.4.99.28 - tRNA pseudouridine(32) synthase
5.4.99.42 - tRNA pseudouridine(31) synthase
5.4.99.45 - tRNA pseudouridine(38/39) synthase

5.4.99.44 - Mitochondrial tRNA pseudouridine(27/28) synthase

5.4.99.19 - 16S rRNA pseudouridine(516) synthase

5.4.99.20 - 23S rRNA pseudouridine(2457) synthase
5.4.99.21 - 23S rRNA pseudouridine(2604) synthase
5.4.99.22 - 23S rRNA pseudouridine(2605) synthase
5.4.99.23 - 23S rRNA pseudouridine(1911/1915/1917) synthase
5.4.99.24 - 23S rRNA pseudouridine(955/2504/2580) synthase
5.4.99.29 - 23S rRNA pseudouridine(746) synthase

5.4.99.43 - 21S rRNA pseudouridine(2819) synthase

Only the 5.4.99.12 # (bolded above) is referred to in GO MF terms for pseudouridine synthase activities, and as @keseler pointed out, this EC # was attached to the general term for "pseudouridine synthase activity" (GO:0009982), rather than to the term specific to "tRNA pseudouridine synthase activity". It is clearly inappropriate to have all these tRNA specific references attached to the general term. Thus, I have moved all of the NARROW synonyms and the tRNA-specific xrefs (in bold below) from GO:0009982 to GO:0106029. However, the citation of this same EC number (in italics below), I have just not removed from GO:0009982 and NOT added to GO:0106029.

> [Term]
> id: GO:0009982
> name: pseudouridine synthase activity
> namespace: molecular_function
> alt_id: GO:0016439
> def: "Catalysis of the reaction: RNA uridine = RNA pseudouridine. Conversion of uridine in an RNA molecule to pseudouridine by rotation of the C1'-N-1 glycosidic bond of uridine in RNA to a C1'-C5." [**_EC:5.4.99.12_**, GOC:mah]
> comment: Note that this term should not be confused with 'pseudouridylate synthase activity ; GO:0004730', which refers to the formation of free pseudouridine from uracil and ribose-5-phosphate.
> subset: gosubset_prok
> **synonym: "transfer ribonucleate pseudouridine synthetase activity" NARROW [EC:5.4.99.12]
> synonym: "transfer RNA pseudouridine synthetase activity" NARROW [EC:5.4.99.12]
> synonym: "tRNA pseudouridylate synthase I activity" NARROW [EC:5.4.99.12]
> synonym: "tRNA-pseudouridine synthase activity" NARROW []
> synonym: "tRNA-pseudouridine synthase I activity" NARROW []
> synonym: "tRNA-uridine isomerase activity" NARROW [EC:5.4.99.12]
> synonym: "tRNA-uridine uracilmutase activity" NARROW [EC:5.4.99.12]
> xref: EC:5.4.99.12
> xref: MetaCyc:TRNA-PSEUDOURIDINE-SYNTHASE-I-RXN**
> is_a: GO:0016866 ! intramolecular transferase activity

**Comment by krchristie** [comment]
@hdrabkin - I took a quick look at all of the EC #s I listed above and most are very specific to a single or small number of target sites; many refer directly to protein only enzymes that catalyze 
the reaction. Thus, these EC numbers are narrrower than our GO terms since we have not instantiated terms for different substrates. Is it OK to attach all of the relevant tRNA, or rRNA, EC #s to our general terms?

**Comment by hdrabkin** [comment]
This is also related to an old ticket of adding site-specific tRNA methylations, etc. We could do that. 
So apparently EC does not have a non-specific term (no individual site terms). I would not use any as an xref for the general term; I think they are ok as narrow synonyms unless we make the specific terms as needed.
I had wanted many  years of bench work with my friend, 5.4.99.25 - tRNA pseudouridine(55) synthase!

**Comment by krchristie** [comment]
So @hdrabkin - These synonyms from 5.4.99.12, are just alternate ways to phrase the name of the term. I should probably remove the EC reference to a single EC term from these synonyms since none of these synonyms seem specific to the .12 enzyme, but rather seem generally appropriate as synonyms of this term name.

The real question I'm trying to get at is would it be OK to add additional xrefs to EC terms? We cannot label xrefs as NARROW. Is there any issue with adding multiple EC numbers that are narrower than the term, so that if people are searching on an EC number, they find the best term? It seems best to me, but wanted to run it by you.

**Comment by hdrabkin** [comment]
I think you can add the name of the ec as a narrow synonym with the EC id as a reference.

**Comment by krchristie** [comment]
@hdrabkin - Thanks for the input. I've put in all the different EC #'s for the tRNA and rRNA specific EC #'s as both synonyms and xrefs to make sure it's clear that each of these terms encompasses a number of narrower EC #'s. I've tagged you as a reviewer on my ticket, and have one additional question for you below.

For the existing synonyms of this term:

> [Term]
> id: GO:0009982
> name: pseudouridine synthase activity
> namespace: molecular_function

These ones, I changed from NARROW to EXACT and removed the reference to 5.4.99.12 (if present):
> synonym: "transfer ribonucleate pseudouridine synthetase activity" NARROW [EC:5.4.99.12]
> synonym: "transfer RNA pseudouridine synthetase activity" NARROW [EC:5.4.99.12]
> synonym: "tRNA-pseudouridine synthase activity" NARROW []
> synonym: "tRNA-uridine uracilmutase activity" NARROW [EC:5.4.99.12]

These ones, I kept as narrow with 5.4.99.12 as the reference since synthase I is a name for the .12 activity:
> synonym: "tRNA pseudouridylate synthase I activity" NARROW [EC:5.4.99.12]
> synonym: "tRNA-pseudouridine synthase I activity" NARROW [EC:5.4.99.12]

This one, I removed the EC reference since it doesn't seem to come from the .12 enzyme. I have currently left it as NARROW, but suspect that possibly, it should be EXACT. @hdrabkin - do you know?
> synonym: "tRNA-uridine isomerase activity" NARROW [EC:5.4.99.12]

**Comment by hdrabkin** [comment]
the reaction does fit 'isomerase' ; I'd say exact.
It can also be referred to as a mutase
https://en.wikipedia.org/wiki/TRNA-pseudouridine_synthase_I

**Comment by krchristie** [comment]
We discussed this at the GO editors call on 7/15/19
- confirmed that it is standard practice to list multiple EC numbers for a single GO term when EC has multiple more specific EC terms for something that GO has chosen to represent in a single term. => `This part is already complete.`
- Karen said she would check if there are Rhea xrefs for these terms. Searching for **'pseudouridine synthase activity'** produces 17 results, all of which are too specific for any of our terms, so I can not add any Rhea xrefs to any of our terms. Here are the search results as of 7/15/19:


Accession | Equation / Hits details | Other directions
-- | -- | --
RHEA:42564 | tRNA uridine(38/39) = tRNA pseudouridine(38/39) 					   		Citation: ...Chen J, Patton JR (2000)Pseudouridine synthase 3 from mouse modifies the anticodon loop of tRNA...... protein Deg1 as pseudouridine synthase (Pus3) catalyzing the formation of psi 38 and psi 39 in tRNA... | RHEA:42565 				   			 					   			RHEA:42567 				   			 					   			RHEA:42566
RHEA:42536 | tRNA uridine(65) = tRNA pseudouridine(65) 					   		Citation: ... are 10 known putative pseudouridine synthase genes in Escherichia coli. The products of six have... | RHEA:42537 				   			 					   			RHEA:42539 				   			 					   			RHEA:42538
RHEA:42964 | uridine(54-55) in tRNA = pseudouridine(54-55) in tRNA 					   		Citation: ... conserved pseudouridine at position 55 in archaeal tRNA.Nucleic acids research 34, 4293-4301...... synthase activity of M. jannaschii protein is robust, while the same activity of P. furiosus protein is... | RHEA:42965 				   			 					   			RHEA:42967 				   			 					   			RHEA:42966
RHEA:38871 | 23S rRNA uridine(2457) = 23S rRNA psi-uridine(2457) 					   		Citation: ... are 10 known putative pseudouridine synthase genes in Escherichia coli. The products of six have...... synthase RluE.Journal of molecular biology 367, 1459-1470 [17320904]Pseudouridine synthase RluE... | RHEA:38872 				   			 					   			RHEA:38874 				   			 					   			RHEA:38873
RHEA:57876 | uridine(54) in tRNA = pseudouridine(54) in tRNA 					   		Citation: ... synthase activity of M. jannaschii protein is robust, while the same activity of P. furiosus protein is... | RHEA:57877 				   			 					   			RHEA:57879 				   			 					   			RHEA:57878
RHEA:38875 | 23S rRNA uridine(2604) = 23S rRNA psi-uridine(2604) 					   		Citation: ... are 10 known putative pseudouridine synthase genes in Escherichia coli. The products of six have...... crystal structure of the catalytic domain of E.coli RluF, a pseudouridine synthase that acts on 23S rRNA.......Journal of molecular biology 388, 785-800 [19298824]Escherichia coli pseudouridine synthase RluF is... | RHEA:38876 				   			 					   			RHEA:38878 				   			 					   			RHEA:38877
RHEA:42520 | 23S rRNA uridine(2605) = 23S rRNA pseudouridine(2605) 					   		Citation: ... are 10 known putative pseudouridine synthase genes in Escherichia coli. The products of six have......, additional ribosome assembly factors, such as helicases, GTPases, pseudouridine synthetases, and... | RHEA:42521 				   			 					   			RHEA:42523 				   			 					   			RHEA:42522
RHEA:42540 | uridine(13) in tRNA = pseudouridine(13) in tRNA 					   		Citation: ...Kaya Y, Ofengand J (2003)A novel unanticipated type of pseudouridine synthase with homologs in...... snRNA:pseudouridine-synthase Pus7p is a novel multisite-multisubstrate RNA:Psi-synthase also acting......Ericsson UB, Nordlund P, Hallberg BM (2004)X-ray structure of tRNA pseudouridine synthase TruD......}-synthase Pus7p.The Journal of biological chemistry 284, 5845-5858 [19114708]The RNA:pseudouridine (Psi...... family of pseudouridine synthases.Archives of biochemistry and biophysics 489, 15-19 [19664587... | RHEA:42541 				   			 					   			RHEA:42543 				   			 					   			RHEA:42542
RHEA:47036 | uridine in 5S rRNA = pseudouridine in 5S rRNA 					   		Citation: ... snRNA:pseudouridine-synthase Pus7p is a novel multisite-multisubstrate RNA:Psi-synthase also acting... | RHEA:47037 				   			 					   			RHEA:47039 				   			 					   			RHEA:47038
RHEA:51124 | uridine in snRNA = pseudouridine in snRNA 					   		Citation: ... snRNA:pseudouridine-synthase Pus7p is a novel multisite-multisubstrate RNA:Psi-synthase also acting... | RHEA:51125 				   			 					   			RHEA:51127 				   			 					   			RHEA:51126
RHEA:38867 | uridine(516) in 16S rRNA = pseudouridine(516) in 16S rRNA 					   		Citation: ...Conrad J, Niu L, Rudd K, Lane BG, Ofengand J (1999)16S ribosomal RNA pseudouridine synthase RsuA...... the 16S RNA pseudouridine 516 synthase from Escherichia coli.Biochemistry 34, 8904-8913 [7612632... | RHEA:38868 				   			 					   			RHEA:38870 				   			 					   			RHEA:38869
RHEA:42544 | uridine(32) in tRNA = pseudouridine(32) in tRNA 					   		Citation: ... contain several pseudouridylation sites, and the tRNA:Psi-synthase acting at position 32 had not...... structure of pseudouridine synthase RluA: indirect sequence readout through protein-induced RNA...... Escherichia coli pseudouridine (psi) synthase, which forms both psi 746 in E. coli 23S ribosomal RNA and... | RHEA:42545 				   			 					   			RHEA:42547 				   			 					   			RHEA:42546
RHEA:42552 | tRNA uridine(31) = tRNA pseudouridine(31) 					   		Citation: ...:pseudouridine (Psi)-synthase encoded by the Saccharomyces cerevisiae open reading frame (ORF) YGR169c, the... | RHEA:42553 				   			 					   			RHEA:42555 				   			 					   			RHEA:42554
RHEA:42532 | uridine(55) in tRNA = pseudouridine(55) in tRNA 					   		Citation: ... pseudouridine 55 (psi 55) synthase, the enzyme that is specific for the conversion of U55 to psi 55 in...... known yeast pseudouridine synthase (Pus1) of broad specificity, no other uridines in tRNA molecules... | RHEA:42533 				   			 					   			RHEA:42535 				   			 					   			RHEA:42534
RHEA:16873 | (6R)-5,10-methylene-5,6,7,8-tetrahydrofolate + FADH2 +  uridine(54) in tRNA = (6S)-5,6,7,8-tetrahydrofolate +  5-methyluridine(54) in tRNA + FAD + H(+) 					   		Citation: ... activity.  Our TrmFO-tRNA docking model, in combination with mutational analyses,  suggests a catalytic...... enzymatic formation of ribothymidine and pseudouridine in the T psi-loop of yeast tRNAs.Journal of... | RHEA:16874 				   			 					   			RHEA:16876 				   			 					   			RHEA:16875
RHEA:42916 | adenosine(2503) in 23S rRNA + 2 reduced  [2Fe-2S]-[ferredoxin] + 2 S-adenosyl-L-methionine =  2-methyladenosine(2503) in 23S rRNA + 5'-deoxyadenosine + L-methionine +  2 oxidized [2Fe-2S]-[ferredoxin] + S-adenosyl-L-homocysteine 					   		Citation: ... methyl synthase activity......., and only one rRNA/tRNA dual-specificity enzyme, pseudouridine synthase RluA, has been identified to...... synthase RlmN trapped by mutagenesis.Journal of the American Chemical Society 134, 18074-18081... | RHEA:42917 				   			 					   			RHEA:42919 				   			 					   			RHEA:42918
RHEA:43332 | adenosine(37) in tRNA + 2 reduced [2Fe-2S]-[ferredoxin] +  2 S-adenosyl-L-methionine = 2-methyladenosine(37) in tRNA +  5'-deoxyadenosine + L-methionine + 2 oxidized [2Fe-2S]-[ferredoxin] +  S-adenosyl-L-homocysteine 					   		Citation: ... methyl synthase activity......., and only one rRNA/tRNA dual-specificity enzyme, pseudouridine synthase RluA, has been identified to...... synthase RlmN trapped by mutagenesis.Journal of the American Chemical Society 134, 18074-18081... | RHEA:43333 				   			 					   			RHEA:43335 				   			 					   			RHEA:43334
