### ISSUE TITLE
E3 ubiquitin protein ligase activity

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#15663]
Hi,

I will raise a can of worms regarding E3 ubiquitin protein ligase activity (GO:0061630 ubiquitin protein ligase activity).

Until recently there were 3 different reaction for E3 ligases:
(1) EC=2.3.2.27; RING-type E3 ubiquitin transferase.
RING class recruit E2-Ub via their RING domain and then mediate direct transfer of ubiquitin to substrates.

(2) EC=2.3.2.26; HECT-type E3 ubiquitin transferase.
HECT E3 ligases undergo a catalytic cysteine-dependent transthiolation reaction with E2-Ub, forming a covalent E3-Ub intermediate. 

(3) EC=2.3.2.31 RBR-type E3 ubiquitin transferase.
RBR E3 ligases have a canonical RING domain that is linked to an ancillary domain. This ancillary domain contains a catalytic cysteine that enables a hybrid RING-HECT mechanism.

A paper was just publishes describing a fourth category of E3: PMID:29643511
(4) RCR-type E3 ubiquitin transferase (No EC number for the moment, I just requested it)
E3 ligase with esterification activity and intrinsic selectivity for threonine over serine (They ubiquitinate Thr residues instead of Lys). RCR-type E3 ubiquitin transferase contains two essential catalytic cysteine residues that relay ubiquitin to its substrate via thioester intermediates.

My questions are: 
1) should we create child terms to reflect the different existing mechanisms/reactions? 
4) And create a fourth term for the new family that ubiquitinates Thr (and Ser)?  PMID:29643511

Thanks

Sylvain

**Comment by ukemi** [comment]
Hi Sylvain,

Fascinating. An even more fundamental question would be whether the fourth category is a child of the current parent or whether we need to set it off because of the Thr linkage rather than Lys. If we decide that the new class should be a type of GO:0061630 (ubiquitin protein ligase activity), we will need to modify the definition. I guess from a GO perspective, we need to ask whether or not the distinction in the mechanisms differentiates the activities with respect to the overall biology of the system. With the integration of functions and processes in GO-CAM models, we are beginning to look to distinguishing functions (and processes) in a more holisitc way. For example if a specific mechanism is used exclusively to contribute to a certain kind of biological outcome, it would be a strong argument to include the distinct mechanistic functions. @thomaspd this is directly related to this morning's discussion on the editors' call.

-D

**Comment by ukemi** [comment]
Hi @sylvainpoux,

I just read this paper and I am tempted to leave the E3 as the grouping term that currently exists. Do you know if there has been any work done on categorizing the RCR-type  E3 physiologically? I'm not sure that we are ready to add it without a physiological relevance. Are these reactions described in Rhea?

**Comment by sylvainpoux** [comment]
Hi @ukemi 

No, there is no Rhea to describe this reaction. It is the exception that makes the rule as we say in French. Rhea is currently not able to describe ubiquitin conjugation, as ubiquitin protein is really a big molecule. For these, we still use the EC numbers. Note that I requested a new EC number for this reaction but it is not yet available.

Thanks

Sylvain

**Comment by deustp01** [comment]
When a protein undergoes hydroxylation or phosphorylation Rhea has gotten around the large size of the substrate by creating a reaction on which a phosphate or hydroxyl moiety is added to an amino acid residue. Could that be extended here to create a reaction in which an aminoacyl residue of a histone reactions with a threonyl residue of a protein?

**Comment by ukemi** [comment]
Hi Sylvain,

I think we will just leave this at the level of the grouping term for now. If we find that we need the more specific MFs to describe the various mechanisms as we move forward with GO-CAM models, we can create them at that point in time.
