### ISSUE TITLE
Axon homeostasis

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#15664]
Would it be possible to create a new GO term for Axon homeostasis.

I know we do not create terms related to diseases, but it looks like some protein coding genes are specifically required to 1) prevent axon destruction (NMNAT2), while another protein, MYCBP2, is specifically required to degrade NMNAT2 to promote axon degradation/degeneration

After discussing with Pascale, we thought that creating 'Axon homeostasis' would be helpful

Thanks

Sylvain

PMID:20126265;
PMID:23082226;
PMID:23665224;
PMID:23610559;

**Comment by RLovering** [comment]
response from SynGO

Hi,

We're mostly focussed on synapses atm so I have not really thought about ontology models for dendrites and axons. In general, I do not favor using terms that describe phenotypes/diseases.

In SynGO we use very generic terms for such cases, something like 'axon maintenance' following https://www.ncbi.nlm.nih.gov/pubmed/20126265 (SynGO maintenance terms; GO:0099559, GO:0098880, GO:0048790, GO:0099562). We're currently short on experts and annotation coverage for synapse organization and synaptogenesis terms. Although I hope we can expand to this a bit in the near future, I cannot contribute a structural solution for annotating synapse/axon/dendrite organization mechanisms that is widely applicable.

Best,
Frank

**Comment by ukemi** [comment]
We have neuron projection maintenance. Do we want to make an axon child? Are the mechanisms different enough?

**Comment by sylvainpoux** [comment]
Hi Ruth and David, 
I was not aware of neuron projection maintenance. As I'm not very familiar with this topic and that the process described in my papers are not well defined, I would say that using neuron projection maintenance is fine for the moment.
However, as said, I'm not familiar with such processes
Thanks a lot for your help
Sylvain

**Comment by BarbaraCzub** [comment]
Hi @ukemi I do not think there is any evidence in literature for different mechanics... (or at least not yet). The term 'neuron projection maintenance' is intended to cover both axons and dendrites, so any neuron projections, generally referred to as 'neurites' in literature. 

In fact the results sections in the papers cited by @sylvainpoux also describe mostly 'neurites' rather than specifically axons (unless animal work is presented). So 'neuron projection maintenance' is definitely applicable in these studies and I would not use a more specific term, if the experimental evidence comes from cell culture-based work. 

For the studies done in adult animals (e.g. Figure 1 in PMID: 23665224) I would be happy to use a more specific term 'axon maintenance', as here there is no ambiguity about whether or not the described neurite is indeed an axon.

So with regard to GO term specificity, I would only go as far as I would be able to infer from the experimental assay. 
Here: cell work --> neurite, animal work --> axon. 
(But The mechanics of the neurite process in the cell culture may as well be more or less the same as for the axon process in the animal).

@ukemi based on the above, would you add 'axon maintenance' as a child term of 'neuron projection maintenance'? Or would you perhaps make it a _**broad**_ synonym of 'neuron projection maintenance'? @paolaroncaglia what would be your recommendation?

* Side note: the second paper cited by @sylvainpoux (PMID:23082226) can be a little tricky to annotate. These studies were done in embryos and the authors themselves state in the abstract "Our observations suggest that during embryogenesis, Nmnat2 plays an important role in _**axonal growth or maintenance**_." Figure 7 does not exactly show that axonal homeostasis/maintenance is affected: "Because NF+ axons are present in both wild-type and mutant limbs at E13.5 (Figure 7C, D), innervation appears to be initiated but then regresses by E18.5 in Nmnat2blad/blad embryos." So, without knowledge about Nmnat2 in adult animals (e.g. PMID: 23665224 mentioned above), I would most probably infer here that Nmnat2 is probably required for a step in the developmental cascade (rather than maintenance) and capture this with 'GO:0031175 neuron projection development'... (And both annotations could be correct; the protein could have a role in axonal development as well as its maintenance).

cc: @RLovering

**Comment by ukemi** [comment]
Hi @BarbaraCzub. Unless we want to specifically distinguish the maintenance of axons versus dendrites, then I would not make new terms. I would make narrow synonyms because axon is narrower than neuron projection. It is probably possible to make the distinction using annotation extensions.

**Comment by BarbaraCzub** [comment]
Hi @ukemi, yes, it is possible to capture the axon vs. dendrite in the annotation extensions. I'll 'axon maintenance' as a narrow synonym then. Thank you!

**Comment by BarbaraCzub** [comment]
Hm... I wonder whether this should actually be a related synonym? (Is there any documentation that I could refer to?)

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
‘axon’ is_a ‘neuron projection’, so to me ‘axon maintenance’ should be a narrow synonym of ‘neuron projection maintenance’. Yes, related synonyms are always safe when in doubt. Some guidance is here: http://geneontology.org/page/ontology-structure#extras

**Comment by ukemi** [comment]
http://wiki.geneontology.org/index.php/Curator_Guide:_General_Conventions#Synonyms

**Comment by BarbaraCzub** [comment]
Thank you @paolaroncaglia and @ukemi for the guidance notes!
I added 'axon maintenance' and 'axon homeostasis' as related synonyms, because 'neurite maintenance' had been previously added as a narrow synonym:
<img width="463" alt="screen shot 2018-05-02 at 15 10 00" src="https://user-images.githubusercontent.com/16541096/39528122-27e70dfe-4e1b-11e8-8ecd-883cd8f4334e.png">
And 'neurite' is also a narrow synonym of a 'neuron projection' (https://www.ebi.ac.uk/QuickGO/term/GO:0043005).

But based on the guidelines in the above links, which you both shared (thank you!), it looks like 'neurite...' should be exact, and 'axon...' should be narrow synonyms, respectively. @ukemi can you think of a reason why 'neurite' had been added as a narrow synonym previously? Based on my understanding of the literature a 'neurite' is an exactly the same structure as a 'neuron projection'. Although the latter is actually very rarely used in literature (usually researchers use the shorter term 'neurite').

Having read the guidance notes, I think the synonyms should be as follows:
### 'GO:0043005 neuron projection' 
--> 'neurite' [exact] 
### 'GO:1990535 neuron projection maintenance' 
--> 'neurite maintenance' [exact]
--> 'neurite homeostasis' [exact]
--> 'neuron projection homeostasis' [exact]
--> 'neuronal cell projection homeostasis' [exact]
--> 'neuron process homeostasis' [exact]
--> 'neuron protrusion homeostasis' [exact]
--> 'axon maintenance' _[narrow]_
--> 'axon homeostasis' _[narrow]_

But there are many more 'neuron projection...' terms in the ontology for which 'neurite' had been added as a 'narrow' synonym, and not exact. And e.g. 'neurite morphogenesis' is a _related_ synonym of 'GO:0048812 neuron projection morphogenesis', and not even narrow... 

The guidance notes also say that the main purpose of the synonyms is to help with searches, so I am not going to address these synonym issues now. But perhaps in the future, we should consider whether we even have a need for synonym _types_?

**Comment by ukemi** [comment]
Unless there are neuron projections that are not neurites. Seems possible.

**Comment by BarbaraCzub** [comment]
There are certainly neuron types, which have a primary cilium. (But in the ontology a cilium is a descendant of cell projection rather than the more specific neuron projection). But, yes, a cilium would be a neuron projection other than a neurite. I did not consider this. Thank you!

**Comment by paolaroncaglia** [comment]
@BarbaraCzub 
In reply to your note
“perhaps in the future, we should consider whether we even have a need for synonym types?”
A couple of quick thoughts here. One is that it is important to differentiate exact synonyms from all others, because an exact synonym is to all extents equivalent to the primary name (the latter is usually chosen on the basis of usage and/or clarity). This has practical implications, so it’s important that exact synonyms are really exact (e.g. ‘signalling’ and ‘signalling’ are the same, but ‘ciliary transition zone’ and ‘CTZ’ are not, as the latter may also refer to ‘chemoreceptive trigger zone’ - CTZ should be related, not exact).
Another thought is that, among biomedical ontologies, GO is one of the few (to my knowledge) that has this richness of variety in synonym types which ultimately adds to knowledge content and quality. Sure, it is not the most essential aspect of GO, but I like to think that it can help curators if applied thoughtfully throughout. 
This said, i agree that this ticket is resolved :-)
