### ISSUE TITLE
New definition GO:0003700 DNA binding transcription factor

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15704]
Hello, 

Following discussion with Astrid Laegrid, Marico, Acensio, Colin Logie, @RLovering and @ValWood 
we propose 

 - [ ]   change the definition for GO:0003700  DNA binding transcription factor: 

Proposed new: A protein or a member of a complex that interacts selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a gene in order to modulate transcription. Regulatory regions include promoters (proximal and distal) and enhancers. Genes are transcriptional units, and include bacterial operons.

(current definition: Interacting selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a gene in order to modulate transcription. ) 

 - [ ]   add synonym 'gene-specific transcription factor' 

@krchristie @ValWood @RLovering @thomaspd 
Is this OK for you ? 

Thanks, Pascale

**Comment by RLovering** [comment]
I am happy with this. Listening to some of the discussions I anticipate that one concern might be that some 'general/basic' TF are not used at every promoter (ie are potentially gene specific). Plus some gene specific TFs regulate >500 genes. Thinking of TP53 I can imagine this sitting a bit on the boundaries of one or other type of TF. 

However, I do think that transcription researchers have some expectations about how to classify the different nuclear proteins. Your term and definition meets these expectations. This is a big move forward and I wonder if we could, at this point, add/agree some guidance for curators. ie This term should be associated with classic DNA binding transcription factors and complexes such as TP53, SP1, NF-kappaB, GATA4, many proteins of the ZNF family (plus other examples...). This term should not be associated with those proteins which are known to be subunits of the PIC. Many of the PIC subunits have some tissue/cell/(gene?) specificity, however these subunits should be annotated to the term ??? or it's child terms.

Sorry this is probably not the best text to include and a figure associated with this would be helpful. I guess I just think it will be useful to write the guidelines as we go, rather than getting to the end and having to put this together. Therefore, considering the information Astrid and Karen compiled for expt data that could be used as evidence to support association of this term with a gp could also be included. I realise that that information is available in a paper, but if there is an annotation guidance wiki/webpage then this could provide a summary of the paper, rather than expecting people to read the paper each time they want to create an transcription annotation (which is unrealistic for curators only annotating a TF a couple of times a year).

**Comment by RLovering** [comment]
sorry, yes I didn't mean if the TF regulates more than 500 genes then we shouldn't include annotated it to this term. I was more just pointing out that I was aware that 'gene-specific' is potentially a relative term. I like the idea of just compiling the list of 'general' TFs. If we got these annotated (maybe IBA and Compara could cover this?) then we could suggest that if someone wants to apply this term to a TF already listed as a general TF then they should discuss with the GOC!
