### ISSUE TITLE
NTR:  Polarity complex

### ISSUE THREAD

**Issue by liviap** [geneontology/go-ontology#15715]
Hi,
can you add this new term?
Cheers,
Livia

Name: Polarity complex
 Def: A protein kinase complex that is required for the establishment of a cell polarity axis during the cell division cycle. Binds directly to activated CDC42 GTPase and is required for orchestrating a cellular gradient of CDC42. 
 References: 
GOC:lnp
 PMID:
 18005931, 19013066, 11113154, 22500799 and 28682236 
Relationships:
 is_a GO:1902911 protein kinase complex
 capable_of GO:0004674 protein serine/threonine kinase activity
 capable_of_part_of GO:0035023 regulation of Rho protein signal transduction

[in yeast components are: BEM1, CDC24 and CLA4 ; from 18005931 ref : 'This tripartite complex named PAR6/PAR3/aPKC is conserved from worms to vertebrates']
DB xref:
complexportal: CPX-3462
synonyms:
BEM1-CDC24-CLA4 complex [NARROW]
PAR6-PAR3-aPKC [NARROW]

**Comment by bmeldal** [comment]
Probably add Synonyms:
BEM1-CDC24-CLA4 complex [NARROW]
PAR6-PAR3-aPKC [NARROW]

I think the source DB is "complexportal" - all small letters and one word.

And start the def with "A protein kinase complex that..." - that will make the activity clear in the definition. We discussed that last night on the call to make the text definition as reflective of the logical definitions (LDs) as possible and expand it with the info that can't be captured with the LDs.

**Comment by bmeldal** [comment]
I’ve added it to groups.yaml but maybe the Syntax is wrong. In one place it’s “Complex Portal” and the other “ComplexPortal” but I don’t know where the build takes it from and if it’s case sensitive.

**Comment by ValWood** [comment]
You also need a more specific term name. Many many complexes are involved in polarity so this name will be confusing to use for a specific complex.

even the more specific
GEF-PAK polarity complex
would not be unique to this particular tripartite complex

Otherwise the "Cdc42p GEF-PAK complex" referred to in the title of 
https://www.ncbi.nlm.nih.gov/pubmed/?term=19013066
(one of your refs above) would fit this  proposed term and def


You also need to delineate the specific  subunits in the def  to refer to this specific complex:

(i.e a conserved tripartite complex with a   SH3 domain phospholipid binding protein, a PAK family kinase and a Cdc42-GEF).

Otherwise, there is no way possible to disambiguate this from other related complexes without knowing precisely the 3 members...

**Comment by liviap** [comment]
@ValWood  and @krchristie ,
I have searched PubMed by using the string 'polarity complex' AND review.
I obtained 18 results; the vast majority points to this complex with little ambiguity: in ref 24499799 I've found: "Epithelial cell polarity is maintained by three well-conserved polarity complexes, namely, PAR, Crumbs and SCRIB". So I agree with @ValWood  we cannot call it just 'polarity complex'. The problem about the name remains because there is not name in the list of possible synonyms I've found (pasted below) that is fine for yeast and vertebrates. 

The only one that could be fine is 'Cdc42 GEF-PAK complex' even if nobody, in the community, call it in this way. 

 I have re-edited the ticket a bit, adding synonyms and info on the composition in the definition:

 References: 
GOC:lnp
 PMID:
 18005931, 19013066, 11113154, 22500799 and 28682236 
Relationships:
 is_a GO:1902911 protein kinase complex
 capable_of GO:0004674 protein serine/threonine kinase activity
 capable_of_part_of GO:0035023 regulation of Rho protein signal transduction

DB xref:
complexportal: CPX-3462

synonyms:
BEM1-CDC24-CLA4 complex [NARROW]
PAR6-PAR3-aPKC [NARROW]
PAR polarity complex
Apical polarity complex
PAR3/PAR6/aPKC
PAR3-PAR6-atypical PKC
Cdc42p GEF-PAK complex

**Comment by srengel** [comment]
i agree in general with @krchristie about it being ok to put the yeast name in the synonyms.

however, i find this combo of proposed name and definition to be confusing (if these are indeed the proposed name and def):
Name: 'Cdc42 GEF-PAK polarity complex'
 Def: A protein kinase complex that is required for the establishment of a cell polarity axis during the cell division cycle. Binds directly to activated CDC42 GTPase and is required for orchestrating a cellular gradient of CDC42. In S. cerevisiae components are: BEM1, CDC24 and CLA4; from worms to vertebrates it contains a PAR6 protein, PAR3 protein and an atypical PKC.

what seems confusing is having Cdc42 in the name, and listed in the components, but then having the def say 'binds directly to activated CDC42...' because that phrase makes it sound like CDC42 is not part of the complex.

**Comment by ValWood** [comment]
I agree, Cdc42 should not be in the term name. I also thought this was confusing.

**Comment by krchristie** [comment]
@liviap - from the responses from @srengel and @ValWood , I think that the summary is you can pick the most common mammalian name, even if it is different from what is used in yeast, i.e. if the mammalian name is rarely or never used by yeast researchers. To use a commonly used mammalian name is fine, often best choice; picking a name that no community uses is not good practice. However, if either the cerevisiae or pombe communities use a name that is different from the most common mammalian name, please also request the yeast community/ies name(s) as NARROW synonyms.

So, with that in mind, let me know what would you pick as the best name of the term.

**Comment by srengel** [comment]
what i'm objecting to is the phrase "Binds directly to activated CDC42 GTPase" in the definition.  Cdc42 can't be part of the complex and also be bound by the complex.  

either it's a constituent of the complex or it's a substrate/subject/boundee of the complex.

sounds like it's a part of the complex, so let's please not say that it's bound by the complex.

**Comment by krchristie** [comment]
@srengel - Thanks for your input. It's very helpful.

**Comment by liviap** [comment]
Hi @krchristie  @srengel and @ValWood, thanks a lot for your comments. I'll try to reply to all of you..
1) I don't know the naming rule on it... if you think the mammalian name is fine (+the yeast one as synonym), then it's fine to me too: I would go for 'PAR polarity complex'
2) cdc42 has to be in the definition, since it is the target of the complex... indeed the conserved function of this complex is to create a gradient of cdc42 in the cell and in order to do that the complex has to physically interact with it. However, cdc42 is not part itself of the complex (it is not in the list of the components). I cannot see the point of having this sentence in the definition...

**Comment by srengel** [comment]
oh you know what, i was reading CDC24 as CDC42 in this phrase: "In S. cerevisiae components are: BEM1, CDC24 and CLA4" - apologies!

**Comment by liviap** [comment]
ooooh, now I see your point!! :-D
well, everything sorted out, then
Thanks again!!
Livia

**Comment by ValWood** [comment]
I still prefer to have the complex function in the term name
PAR protein kinase complex

but are we completely sure that this complex does not contain cdc42?

Until this discussion, I previously thought the PAK family kinase  as a subunit of a larger  Cdc42 complex.

Remember we do not want  to  instantiate every  'sub-complex' that can be isolated, only the 'functional unit'  I previously  used this term:
https://www.pombase.org/term/GO:0071521
from this paper, which describes a "ternary complex"
https://www.pombase.org/reference/PMID:8943016
and to me this is more correct.

This is a similar organization to the septation in initiation signalling network:

![complex](https://user-images.githubusercontent.com/7359272/40059725-c1683030-584c-11e8-8744-e2dd8ac92f6e.jpg)
tiation signalling network

We don't  need to represent  all of the sub complexes in GO, only the scaffold + GTPase/kinase 
but not  individual Sid2//mob1 or Sid1/Cdc14 (we can do these with interactions).

Otherwise we have too much proliferation and inconsistency.

**Comment by liviap** [comment]
@ValWood please find my reply:
_I still prefer to have the complex function in the term name
PAR protein kinase complex_
- I disagree the community doesn't call it in this way, but with any of the synonyms provided:
BEM1-CDC24-CLA4 complex [NARROW]
PAR6-PAR3-aPKC [NARROW]
PAR polarity complex
Apical polarity complex
PAR3/PAR6/aPKC
PAR3-PAR6-atypical PKC
Cdc42p GEF-PAK complex
so why should we call it in this way?

_but are we completely sure that this complex does not contain cdc42?_
Yes, I am pretty much convinced:
**ref 28682236**:  'In budding yeast, polarization is associated with a focus of Cdc42•GTP which is thought to self sustain by recruiting a complex containing Cla4, a Cdc42-binding effector, Bem1, a scaffold, and Cdc24, a Cdc42 GEF. ';
**ref 19013066**: Here we show that Bem1p promotes symmetry breaking by assembling a complex in which both a Cdc42p-directed guanine nucleotide exchange factor (GEF) and a Cdc42p effector p21-activated kinase (PAK) associate with Bem1p.
**ref 18005931**: In this review, we focus on apical polarity complexes, namely the PAR3/PAR6/aPKC complex 
**ref  29696344**: Protein complexes, including the PAR3-PAR6-aPKC complex, have conserved roles in establishing polarity across a number of eukaryotic cell types. 
**ref  25128813**: Polarity proteins translate such internal and external cues to drive polarization. In this review we will focus on the role of the polarity complex aPKC/Par3/Par6 in the regulation of division orientation and cell fate
There are many other...
Said that, I'm sure we can find also contradicting paper, I think we will never be sure enough...

I hope I've convinced you...
;-)
Livia

**Comment by krchristie** [comment]
@liviap - This discussion has gotten rather strung out and I am finding it hard to find the conclusions. Could you please add a new comment with a summary of the new term stanza this discussion has settled on, with preferred term name, def, various types of synonyms.

Thanks!

**Comment by ValWood** [comment]
But the GEF needs to be associated  with cdc42 to be functional?

I'm not disputing the existance to the tripartiait complex, but I'm not sure this belongs in GO.

I would only put the ternary complex:

![complex](https://user-images.githubusercontent.com/7359272/40082430-e1ad1f4a-5888-11e8-8f01-a26d32bd9bd3.jpg)

**Comment by liviap** [comment]
@krchristie please find below the ticket.

 Name: 'PAR polarity complex'
 Def: A protein kinase complex that is required for the establishment of a cell polarity axis during the cell division cycle. Binds directly to activated CDC42 GTPase and is required for orchestrating a cellular gradient of CDC42. In S. cerevisiae components are: BEM1, CDC24 and CLA4; from worms to vertebrates it contains a PAR6 protein, PAR3 protein and an atypical PKC.

 References: 
GOC:lnp
 PMID:
 18005931, 19013066, 11113154, 22500799 and 28682236 
Relationships:
 is_a GO:1902911 protein kinase complex
 capable_of GO:0004674 protein serine/threonine kinase activity
 capable_of_part_of GO:0035023 regulation of Rho protein signal transduction

DB xref:
complexportal: CPX-3462

synonyms:
BEM1-CDC24-CLA4 complex [NARROW]
PAR6-PAR3-aPKC [NARROW]
PAR polarity complex
Apical polarity complex
PAR3/PAR6/aPKC
PAR3-PAR6-atypical PKC
Cdc42p GEF-PAK complex

**Comment by krchristie** [comment]
@liviap @bmeldal @cmungall - Can you please let me know what the correct ID space for complex portal IDs is supposed to be. I cannot add the ID for this term until this is sorted out.

**Comment by bmeldal** [comment]
The stanza in groups.yaml is

  label: Complex Portal
  id: https://www.ebi.ac.uk/complexportal
  shorthand: ComplexPortal

But I have no idea where the name space gets the ID from.

**Comment by krchristie** [comment]
Hi @bmeldal - We discussed this today at the ontology editors meeting and I am under the impression that the ID check for dbxrefs comes from this file:
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

where the relevant stanza is this:
```
- database: ComplexPortal
  name: Complex Portal database of macromolecular complexes
  generic_urls:
    - https://www.ebi.ac.uk/complexportal
  entity_types:
    - type_name: macromolecular complex
      type_id: GO:0032991
      id_syntax: CPX-[0-9]+
      url_syntax: https://www.ebi.ac.uk/complexportal/complex/[example_id]
      example_id: ComplexPortal:CPX-2158
example_url: https://www.ebi.ac.uk/complexportal/complex/CPX-2158
```

So, the info for the ComplexPortal in the db-xrefs.yaml file looks consistent with what is in the groups.yaml file with capital C and P, rather than all lowercase.

What syntax is appropriate? if the partially capitalized form is OK, I'll try adding the ComplexPortal ID with that syntax. If it needs to be the fully lowercase version, than it looks like edits to the groups.yaml and db-xrefs.yaml files need to be edited. Let me know which syntax is correct, and if you can do these edits, or need me to do it.

thanks,

-Karen

**Comment by bmeldal** [comment]
I'm happy with ComplexPortal, I just didn't know where the info was stored as Tony must have added it to the db-xrefs.yaml file.

So it's a "go ahead, please" from me :)

**Comment by bmeldal** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0120157
