### ISSUE TITLE
Question on [isocitrate dehydrogenase (NADP+)] kinase activity and phosphatase

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15750]
Hi, 

Should these two terms be merged ? It's a bi-functional enzyme with a single EC number. 

GO:0008772  [isocitrate dehydrogenase (NADP+)] kinase activity
Catalysis of the reaction: ATP + (isocitrate dehydrogenase (NADP)) = ADP + (isocitrate dehydrogenase (NADP)) phosphate.

GO:0101014 [isocitrate dehydrogenase (NADP+)] phosphatase activity
Catalysis of the reaction: [isocitrate dehydrogenase] phosphate + H2O = [isocitrate dehydrogenase] + phosphate.

@hdrabkin what do we do in these cases ? 

(This came up while fixing exact synonyms in #13667). 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Hi @pgaudet 
I have another instance of this that I am dealing with but at least in that case EC lists two reactions.
In this ticket, EC does not list both reactions.

it only has ATP + [isocitrate dehydrogenase (NADP(+))] <=> ADP + [isocitrate dehydrogenase (NADP(+))] phosphate, for the kinase.

If you think about it, the 101014 activiy DOES have a difference in substrate/products  (no ATP/ADP
Even the metacyc id for 8772 only references the kinase activity
EC does have some synonyms that have "kinase/phosphatase', but it is not clear to me that the same enzyme does both. 
I will need to as Peifen about 101014 to see if there is a pub where it is clear that this is a bifunctional enzyme. If it is then we can merge. Otherwise, I think the EC for 101014 is wrong, but to keep the term I then need some other evidence 
As a short term fix, we can just change the exact synonym of 101014 to related 
When EC lists two reactions, should we be making two separate GO terms or only one?
In at least two cases where I know there are multiple steps or where multiple steps can be listed, but EC does not and in those cases, I think only one GO id should exist
Example
tRNA CCA addtion enyzme; can put the C, then the C, then A, but can also just put A if the CC is already there. This has ONE EC number (I have an old ticket that I now remember that I want to merge our three terms for these because only ONE organism as two separate enzymes (one for the CC, another for the A, and in THAT case two activites are warranted but neither can be assigned the EC id.
The other case is ANY aminoacylt-tRNA synthetase: occurs in two steps 
AA + ATP  -> AA-AMP + PPi
AA-AMP + tRNA -> AA-TRNA + AMP
Each of these can be assayed separately.
Overal AA + ATP + tRNA -> AA-tRNA+ AMP + PPi.
Pick amino acid of your choise.
None of these have 4 digit EC numbers anyways;

Do we want to make a rule that IF EC list two reactions (which in this ticket case, EC does not) we make both activites, But the would they both get the same EC for an xref? 

Sorry this is long-winded. Meanwhile, I'll contact Peifen.
So

**Comment by pgaudet** [comment]
Thanks @hdrabkin 
It seems that two terms for two reactions is reasonable, but I don't really mind what the decision is; I just wanted to know what the guidelines are. 

I made the synonyms that referred to both activities ( kinase/phosphatase ) 'broad' , so perhaps this ticket can be closed with no action needed.

Thanks, Pascale

**Comment by deustp01** [comment]
The forward direction (target + ATPare converted to phospho-target + ADP) and backward direction (phospho-target + H2O are converted to target + phosphate) are chemically different reactions with different mechanisms mediated by different catalytic mechanisms. Regardless of how EC handles this case, we need to keep them separate and maybe a paper that shows that protein X is either a kinase or a phosphatase but the authors can't figure out which does not meet the minimum threshhold for GO annotation.

Snippy scholarly note. Unlike reactions that generate free phosphate, reactions in which ATP is converted to AMP + diphosphate (pyrophosphate) are freely reversible. Under physiological conditions they are almost always driven in the direction of diphosphate formation by a second enzyme, the ubiquitous pyrophosphatase that catalyzes the fast and irreversible hydrolysis of diphosphate to form two molecules of phosphate.

**Comment by hdrabkin** [comment]
I'm fine with keeping them separate but in this case the EC entry at Expasy does not show both so I think the EC id should be removed from the phosphatase yes?

**Comment by pgaudet** [comment]
Thanks to everyone for the feedback! 

Looking at the UniProt entry for the E. coli gene, yes I would say we should remove the EC from the phosphatase, they have EC:3.1.3.-

Pascale

**Comment by hdrabkin** [comment]
We made a decision NOT to use the 3 digit ecs as xrefs for anything other than classes (grouping terms).

**Comment by hdrabkin** [comment]
Peifen suggests to remove the EC fxref rom 1014 and add this as an xref
Metacyc:ICITDEHASE-KIN-PHOSPHA
and add this reference to1014 as a def ref.
PMID:6292732

**Comment by hdrabkin** [comment]
done
