### ISSUE TITLE
Merge terms under 'GO:0000991	transcription factor activity, core RNA polymerase II binding' and children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15798]
**This ticket is replaced by https://github.com/geneontology/go-ontology/issues/16053**

 - [ ] **GO:0000989**  transcription factor activity,   transcription factor binding -> merge into 	 GO:0008134  transcription factor binding (28 manual annotations, excluding ISS) 
**BHF-UCL
MGI 
~~SGD~~
UniProt**

 - [ ]  **GO:0000990**	transcription factor activity, core RNA polymerase binding	-> merge into 	  GO:0000993	RNA polymerase II core binding (21 manual annotations, excluding ISS) 
**CACAO, CAFA, FlyBase, ~~SGD~~**

 - [ ]  **GO:0000991**	 transcription factor activity, core RNA polymerase II binding -> merge into 	GO:0000993	RNA polymerase II core binding (26 manual annotations, excluding ISS) **pombase ~~SGD~~**

 - [ ]  ~~GO:0000995	transcription factor activity, core RNA polymerase III binding	-> merge into GO:0000994	RNA polymerase III core binding (5 manual annotations, excluding ISS) pombase~~

 - [ ]  **GO:0001076**	transcription factor activity, RNA polymerase II transcription factor binding	-> merge into 	GO:0001085	RNA polymerase II transcription factor binding (19 manual annotations, excluding ISS) 
**BHF-UCL
ComplexPortal
MGI
ParkinsonsUK-UCL
SGD
TAIR
UniProt
WB**

 - [ ]  **GO:0001132**	RNA polymerase II transcription factor activity, TBP-class protein binding -> merge into 	GO:0017025	TBP-class protein binding (6 manual annotations, excluding ISS) **SGD**

 - [ ]  **GO:0001181**	transcription factor activity, core RNA polymerase I binding	-> merge into  GO:0001042	core RNA polymerase I binding (9 manual annotations, excluding ISS) **SGD**

 - [ ]  **GO:0001190**	transcriptional activator activity, RNA polymerase II transcription factor binding	-> merge into  GO:0001085	RNA polymerase II transcription factor binding
**BHF-UCL
CAFA
MGI
PomBase
SGD
TAIR
WB**

 - [ ]  **GO:0001191**	transcriptional repressor activity, RNA polymerase II transcription factor binding	 (44 manual annotations, excluding ISS) 
-> merge into  GO:0001085	RNA polymerase II transcription factor binding
**BHF-UCL
CAFA
ComplexPortal
FlyBase
MGI
SGD
UniProt**

 - [ ]  **GO:0038049** | transcription factor activity,   ligand-activated RNA polymerase II transcription factor binding -> merge into   GO:0035257 nuclear hormone receptor binding (1 manual annotations, excluding ISS)  **UniProt**

Manual (non-ISS) annotations are here: 
https://docs.google.com/spreadsheets/d/1Apv6MiftFCXKHKHVY_ebkZG8PH49PL1HlPsAFW-8LK4/edit#gid=0

**There is no action needed if we merge, this is just to check that the merge is OK.**

**Comment by pgaudet** [comment]
@krchristie @ValWood @RLovering  Can you please have a look before I implement ? 

Thanks, Pascale

**Comment by hattrill** [comment]
A quick glance at the FlyBase ones, I can see that they were probably made in a slightly different spirit - more aimed at capturing that they are regulating transcription but not DNA-binding TFs, I think. Will need a bit of time to review and re-house.

**Comment by ValWood** [comment]
1 
I would obsolete
GO:0000989 transcription factor activity, transcription factor binding 
and
GO:0008134 transcription factor binding (28 manual annotations, excluding ISS)

and suggest using protein binding terms instead if appropriate, but also checking that they have the correct "general transcription initiation factor activity" or "cofactor activity" (since this is what most seem to be?

 If we move them now we will probably need to move them again later. Better to just get them to their final home?

2 GO:0000993	RNA polymerase II core binding

Again, do we need this term. Why not just "protein binding" if demonstrated  with the 
the correct "general transcription initiation factor activity" or "cofactor activity"


3. Birgit is correct
GO:0000990	transcription factor activity, core RNA polymerase binding
is a polymerase independent term. It should not merge into 
GO:0000993	RNA polymerase II core binding

but again, I  think it is confusing to have both the "general/cofactor" term AND a  RNA polymerase or TF  binding term to describe the same activities. This is why we all got confused in the first place.....


Personally I would obsolete or merge the binding branch into the cognate  term in the non binding branch....

**Comment by ValWood** [comment]
4. so here:
https://github.com/geneontology/go-annotation/issues/1734
I propose to merge these 4 terms into 'GO:0000995' (to be renamed "general RNA polymerase III transcription factor activity", see geneontology/go-ontology#14790

so I  just moved  all of these this week  to GO:0000995  as the new “general RNA polymerase III transcription factor activity”


but here you are saying
GO:0000995	transcription factor activity, core RNA polymerase III binding	-> merge into GO:0000994	RNA polymerase III core binding (5 manual annotations, excluding ISS) pombase

I think we need the “GO:0000995  general RNA polymerase III transcription factor activity”

**Comment by ValWood** [comment]
So, I thought we would be getting rid of "transcription factor binding" terms and try to just use the simplified terms relating to your schema ?
If this is the case we don't want to migrate step-wise up the "transcription factor binding" branch.

But if you can unambigously map to the other branch, that would be useful?

**Comment by ValWood** [comment]
Arghh I'm so confused ;!!! ;)

**Comment by pgaudet** [comment]
@bmeldal 

>>     GO:0000990 transcription factor activity, core RNA polymerase binding -> merge into GO:0000993 RNA polymerase II core binding

> Isn't that merging a more general term into a specific child? Are we sure all GO:0000990 annotations were meant to be for RNAPII?

yes, I checked.

**Comment by pgaudet** [comment]
@ValWood I corrected https://github.com/geneontology/go-annotation/issues/1734 
In the end I just renamed GO:0000995 from transcription factor activity, core RNA polymerase III binding -> to  RNA polymerase III general initiation factor activity (and doidn't merge the other terms in).

**Comment by pgaudet** [comment]
@ValWood 
> I think we need the “GO:0000995 general RNA polymerase III transcription factor activity”
This is done, it should trickle through shortly.

**Comment by pgaudet** [comment]
You are right about the final home. For sure that protein binding branch is not really a solution. 

First: we don't have a term 'transcription factor activity', so it's really odd to have a precision on that. 
What we have is: 
- DNA binding tx factor activity
- coregulator activity
- general transcription factor activity. 

So if we want to describe what types of protein a protein binds to, it should be to one of the 3. So anyways these will need to be reviewed (this is why I wanted to 'park' them there for now).

I don't know if all the proteins in that list (see Google doc above) can have a home now. I think we're missing the elongation factor. (I can rescue that from the obsoletes). Can you spot anything else missing ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I'm still confused

GO:0000995	transcription factor activity, core RNA polymerase III binding	-> merge into GO:0000994	RNA polymerase III core binding (5 manual annotations, excluding ISS) pombase

but  yesterday:
https://github.com/pombase/curation/issues/2011

Which term do I need (ID) for 
"RNA polymerase III general transcription initiation factor activity" ?

**Comment by pgaudet** [comment]
Hi @ValWood 
My bad !!! GO:0000995 = will become RNA polymerase III general transcription initiation factor activity

so the merge I propose above is irrelevant. 

Thanks for picking that up ! 


Pascale

**Comment by pgaudet** [comment]
@ValWood 
For GO:0008134 transcription factor binding (28 manual annotations, excluding ISS)
I see 797 direct EXP annotations - are you sure about the 28 ? Also, there are many children to this term, we need to also look at those before obsoleting the parent.

**Comment by ValWood** [comment]
Did I say 28?

**Comment by ValWood** [comment]
I see 251 in QuickGO...

**Comment by pgaudet** [comment]
For GO:0008134 transcription factor binding ? 

I see 943 EXP in QuickGO

**Comment by RLovering** [comment]
Hi Pascale

I think merging would be great as this will reduce the our annotation workload. However, I also think that as suggested getting the transcription regulator terms available so that people can try to create additional GO terms based on the transcriptional activities would be great, so that people can go through the spreadsheet. 

Ruth

**Comment by ValWood** [comment]
should
 GO:0001190	transcriptional activator activity, RNA polymerase II transcription factor binding	-> merge into GO:0001085	RNA polymerase II transcription factor binding (47 manual annotations, including ISS)

(and repressor term)
merge into 

https://www.ebi.ac.uk/QuickGO/term/GO:0003713
transcription coactivator activity
Molecular Function
Definition (GO:0003713 GONUTS page)
A protein or a member of a complex that interacts specifically and non-covalently with a DNA-binding transcription factor to activate the transcription of specific genes. Coregulators often act by altering chromatin structure and modifications. The Mediator complex, which bridges transcription factors and RNA polymerase, is also a transcription coactivator. PMID:10213677 PMID:16858867

It seems to fit the definition?

(Rather than the binding term?, or is this for something else?

**Comment by ValWood** [comment]
For example Rep2,  is a co-activator for MBF transcription factor complex
https://www.ncbi.nlm.nih.gov/pubmed/7588609

with the current proposal there is a loss of repressor/activator specificty

**Comment by pgaudet** [comment]
@ValWood how are you trying to annotate Rep2?

**Comment by ValWood** [comment]
Actually it isn't a coactivator, it's part of a DNA binding TF complex

but it also binds to  another RNA pol II TF as part of the complex. I'm not so bothered about the binding term (we'll capture that with protein binding)

GO ahead with the merge , but when I finish I don't plan to have anything annotated to 
"GO:0001085	RNA polymerase II transcription factor binding".....

**Comment by suzialeksander** [comment]
I'm verifying these merges won't be an issue, I think we're waiting until the dust settles to re-annotate because it looks like the terms are still a little in flux.  I'm almost done, but:

In the 7th section, it says 
"GO:0001181	transcription factor activity, core RNA polymerase I binding -> merge into GO:0001042 core RNA polymerase I binding (9 manual annotations, excluding ISS) SGD"

This means  GO:0000991 transcription factor activity, core RNA polymerase II binding correct? not 
  GO:0001181 RNA polymerase I general transcription initiation factor activity?

**Comment by pgaudet** [comment]
Annotation guidelines presented at today's annotation call are here: 
https://drive.google.com/drive/folders/11KY9lO9gFHa72B3OzWAfHRhVEH6Tbdon
