### ISSUE TITLE
MP:	protein import into mitochondrial outer membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15800]
protein import into mitochondrial outer membrane
is defined

Definition | Parents

The process comprising the insertion of proteins from outside the organelle into the mitochondrial outer membrane, mediated by large outer membrane translocase complexes.

should this be "mitochondrial outer membrane organization"?

**Comment by pgaudet** [comment]
Makes sense to me.

**Comment by vanaukenk** [comment]
I added the missing parentage but have a question for @pgaudet about the logical definitions for protein import into outer mitochondrial membrane vs protein import into inner mitochondrial membrane:

protein import into outer mitochondrial membrane:

transport
 and ('occurs in' some cytoplasm)
 and ('has target end location' some 'mitochondrial outer membrane')
 and (imports some protein)

protein import into inner mitochondrial membrane

transport
 and ('has target start location' some cytosol)
 and ('has target end location' some 'mitochondrial inner membrane')
 and (imports some protein)
 and ('results in transport across' some 'mitochondrial outer membrane')

The definition for import into the outer membrane does not have a 'has target start location' in the logical def, but rather an 'occurs in' relation to the cytoplasm.  Is that intended?

**Comment by ValWood** [comment]
pinging @pgaudet

**Comment by pgaudet** [comment]
Thanks for the reminder. 

Note that "protein import into mitochondrial outer membrane" has been renamed "protein insertion into mitochondrial outer membrane".

There is no start location because the protein can technically come from the mitochondrial inner membrane OR from the cytoplasm. I think we had looked at this together. The paper cited shows nice diagrams: 
https://www.sciencedirect.com/science/article/pii/S0167488908002474?via%3Dihub

If I recall correctly some proteins are imported from the cytoplasms into the intermembrane space, and then inserted into the outer membrane, while others are inserted directly. 

However if all proteins are encoded in the nucleus, I think the logical definition would be OK with 'has start location = cytosol' even if the protein the transits through the intermembrane space. 

Pascale

**Comment by ValWood** [comment]
OK!

**Comment by pgaudet** [comment]
I dont know that all mitochondrial outer membrane proteins are encoded in the nucleus in all species, so I would prefer to leave the logical definition as it is, unless you think it should be changed ?

**Comment by ValWood** [comment]
I'm pretty sure that they are. The mitochondrial geneome complement appears to be fairly constant (yeast to human), ~13 proteins  and only encoded etc components and an endonuclease.
So I think you could change it...

**Comment by ValWood** [comment]
etc =electron transport chain

**Comment by pgaudet** [comment]
I thought some species had about 40 genes? 

I'll add the relation, if it's causing problems we'll hear.

**Comment by ValWood** [comment]
Yeah but I'm  with Steve and he says not (he did a lot of work on mitochondria  in the past)

I think the 40 would include rRNA and tRNA...

**Comment by pgaudet** [comment]
ok perfect then !

**Comment by pgaudet** [comment]
Also added 

protein insertion into mitochondrial membrane
transport
 and ('has target start location' some cytosol)
 and ('transports or maintains localization of' some protein)
 and ('has target end location' some 'mitochondrial membrane')

And changed the regulation terms to be consistent: 
-name: regulation of protein import into mitochondrial outer membrane
+name: regulation of protein insertion into mitochondrial outer membrane
(plus the positive and negative regulation terms)

Thanks, Pascale
