### ISSUE TITLE
Relationships between GO terms should not be imported via import of other ontologies

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#15857]

**Comment by ukemi** [comment]
Does it make sense to also exclude external-to-GO axioms? This has become problematic with respect to some recent obsoletions. For example: #15652

I think this will trigger a release failure due to one of obsoleted terms being referenced in the UBERON import. This also happened recently with a ChEBI term. It seems that we should be able to edit GO and not be dependent on changes or release cycles of external ontologies.

**Comment by ukemi** [comment]
@balhoff I like your proposal outlined above, but I'm not sure that it completely addresses the inverse issue that we are having at the moment. In this case, GO is 'ahead' of the other ontologies. Would we suppress the GO release until the others catch up? Specifically in this case, would we suppress the GO release until UBERON editors remove the obsolete GO term in logical definition or obsolete the primary term? I think your proposal works for one master obo release of all the ontologies once they are all compatible, where the dependencies are to version IRIs. Am I missing something?

**Comment by balhoff** [comment]
I see what you're saying. To be honest, I think we should just relax the check so that if we make an extract from Uberon, and one of the axioms that is pulled in is a logical definition for an Uberon term that references an obsolete GO term, we should just live with it and ask Uberon to change. But it doesn't need to hold up a GO release.

**Comment by ukemi** [comment]
Good idea. @dougli1sqrd can you do this?

**Comment by pgaudet** [comment]
Where does this stand ?

**Comment by balhoff** [comment]
@cmungall shouldn't this (relationships between GO terms) be already handled by these lines?

https://github.com/geneontology/go-ontology/blob/75022120a40858f191a8a832dd6e755739d370db/src/ontology/Makefile#L384-L388

**Comment by balhoff** [comment]
I don't see any such relations in the current Uberon import.

**Comment by cmungall** [comment]
Yes, they should be

>

**Comment by balhoff** [comment]
I think this is fixed, but if we see more of these axioms at some point, we can open a ticket for that specific problem.
