### ISSUE TITLE
remove torso signaling pathway-regulation of transcription by RNA polymerase II link

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#15860]
For consistency across RTK signaling pathways/signaling review discussions, please could you remove regulation of transcription by RNA polymerase II parentage for torso signaling pathway. 

GO:0008293	torso signaling pathway
is_a
GO:0006357	regulation of transcription by RNA polymerase II

![screen shot 2018-06-05 at 12 41 23](https://user-images.githubusercontent.com/11865746/40973965-01843eda-68be-11e8-8b0a-ebbbeac24ccf.png)

**Comment by vanaukenk** [comment]
@hattrill - I will remove this parentage, but it looks like there are other examples of this in the ontology that may also need to be addressed.

The BMP signaling pathways, in particular, have this parentage.

For example:

GO:0006357 regulation of transcription by RNA polymerase II
is_a GO:0030509 BMP signaling pathway
is_a GO:0030510 regulation of BMP signaling pathway
is_a GO:1900145 regulation of nodal signaling pathway involved in determination of left/right asymmetry

OR

GO:1900094 regulation of transcription from RNA polymerase II promoter involved in determination of left/right symmetry
is_a GO:0003154 BMP signaling pathway involved in determination of left/right symmetry
is_a GO:0003155 BMP signaling pathway involved in determination of lateral mesoderm left/right asymmetry
GO:0003303 BMP signaling pathway involved in heart jogging

OR

GO:1901213 regulation of transcription from RNA polymerase II promoter involved in heart development
GO:0061312 BMP signaling pathway involved in heart development

However, other signaling pathways involved in heart development or processes, including the TGFbeta and activin signaling pathways, don't have this parentage, for example:

GO:0003302 transforming growth factor beta receptor signaling pathway involved in heart jogging

Nor does the EGF signaling pathway involved in heart process, for example:

GO:1905251 epidermal growth factor receptor signaling pathway involved in heart process

@ukemi @RLovering  Is there a reason to specifically keep the regulation of transcription parentage for the BMP signaling terms?

**Comment by ukemi** [comment]
Traditionally, if it was the only consequence of the pathway, then the regulation relationship was added to the ontology as a class-level relationship. For pathways that resulted in more than one consequence, then these asserted class-level relationships couldn't be added. Originally we had proposed that all signaling pathways should regulate some type of cellular process.

**Comment by hattrill** [comment]
I think that we should remove all transcriptional reg relationships at the pathway level, many pathways have multiple targets, as well as transcription, that have been teased out later.

**Comment by RLovering** [comment]
Hi Helen
I agree that this is inconsistent and there is always the worry that BMP signalling might lead to changes  without reg of transcription, which have not yet been identified ;)
However, I know that there is a push to not annotate signalling (sorry GitHub keeps changing this to UK spelling) pathways gene products to regulating transcription or gene expression. This is an area that did not get discussed at the signalling workshop. I would really like to see terms created that recognise the downstream impact of singling. I realise that this can be done with GO-CAM using the causally upstream of (or would it be positively regulates) relation. But I am not sure how this is translating into GPAD format.

I liked how apoptosis ontology represents the 2 different areas, signalling and execution. I think many cellular processes have these two phases, and it would be useful to be able to group proteins based on their role in these different phases. There again maybe it is too difficult to tease out these phases, for example cytoskeletal reorganisation in response to a signal, it might be difficult to decide where the signal stops and the execution phase starts.  

I guess I think it would be OK not to have very specific terms but I would ideally like to see something like:

Regulation of gene expression
>Regulation of gene expression via receptor-mediated signalling pathway
>>Regulation of transcription via receptor-mediated signalling pathway
>>Regulation of translation via receptor-mediated signalling pathway
>>Regulation of splicing via receptor-mediated signalling pathway (?)

>Regulation of transcription mediated by transcription regulator activity
>Regulation of translation mediated by translational regulator activity
>Regulation of splicing mediated by splicing regulator activity

I guess this is very child like, I just can't work out a process term name that could be associated with a specific transcription factor which would distinguish a ligand's regulation of transcription versus a specific transcription factor regulation of transcription.

Anyway, yes moving the few signalling terms that are child terms of reg of transcription is fine, however please notify us first because we will want to change or add annotations so that this information is not lost, especially if there is data in the AE field which will not be appropriate when the terms are moved to the signalling branch.

Ruth

@pgaudet

**Comment by pgaudet** [comment]
I will remove the link, since it has been done for BMP signaling, see #19366.

**Comment by pgaudet** [comment]
This is somehow done, I cannot find the ticket/PR.
