### ISSUE TITLE
NTR: stress-induced homeostatically regulated protein degradation pathway

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#15869]
Hi,

I would like to request the following term: 'stress-induced homeostatically regulated protein degradation pathway' be added to the process ontology. The parentage should include: cellular response to stress (GO:0033554), and probably proteasome-mediated ubiquitin-dependent protein catabolic process (GO:0043161), based on the finding that its involved in both stress induced degradation of misfolded proteins, as well as native proteins in both the ER and cytosol

GO:XXXXXXX	stress-induced homeostatically regulated protein degradation pathway
Definition: 	A stress-inducible pathway that accelerates the degradation of misfolded and native proteins at the ER membrane and in the cytosol by reprogramming the specificity of a component of the protein quality control machinery

Synonyms:	SHRED pathway

Reference:
PMID: 29861160

**Comment by RLovering** [comment]
please also check ontology structure around GO:0036503  ERAD pathway as there seems to be some similarity between these terms.

**Comment by robnash** [comment]
I am not sure the final story is in with regards to whether this is completely independent of ERAD or the cytoplasmic unfolded protein response (UPR). I think what may make this unique is the fact that it works not only on stress induced ER substrates, but also cytosolic proteins and native proteins. To my recollection ERAD does not impact native proteins (not sure about cytosolic). 

They rule out the unfolded protein response by noting that degradation of their reporter Rtn1Pho8*-GFP upon tunicamycin treatment did not require Ire1 or Hac1, ruling out the UPR as the relevant signaling pathway.

They also comment on ER stress-upregulated ERAD experimentally using the human cystic fibrosis transmembrane conductance regulator (CFTR) as substrate. CFTR is constitutively degraded by ubiquitin ligases, Hrd1 and Doa10 (ERAD components). They assess SHRED in degradation of CFTR in a hrd1 doa10 null background and find that tunicamycin (stress) still accelerated CFTR degradation in this
background, which required Ubr1, Ynm3, and Roq1 (SHRED components). This implies they are unique.

In the discussion they state "Hence, SHRED appears to be similar to the induction of
ERAD by the UPR and the augmentation of proteasome biogenesis by Hsf1 and Rpn4 (Hahn et al., 2006; Travers
et al., 2000). SHRED, however, tunes the quality control machinery at the post-translational level. Interestingly, SHRED is also activated by nutrient scarcity, which is unlikely to cause
widespread protein misfolding. SHRED may, therefore, additionally function in protein degradation for regulatory purposes, in line with the identification of native, folding-competent
proteins as SHRED substrates."

So I think they are suggesting these are unique pathways, but I could always ask the author more on this if needed.

**Comment by RLovering** [comment]
Hi Rob

I think these terms still need more work. The GO term definitions need to clearly state what the difference is between these terms so that there is no misannotation in the future. For example you can also add comments to direct curators, such as those in GO:0034620 cellular response to unfolded protein: Comments: Note that this term should not be confused with 'unfolded protein response ; GO:0030968', which refers to the signaling pathways that respond to the presence of unfolded proteins in the ER.

Also if you look at the GO term GO:0036503 ERAD pathway (see below a comparison of the 2 terms) you will see that it lists the start and end of the process. Your definition doesn't have this information and this is likely to lead to problems in the future. 

Also looking at the placement of SHRED and ERAD in the ontology and reading the ERAD definition I wonder if ERAD should have some of the same parent terms as SHRED. ERAD has the parent GO:0010498 proteasomal protein catabolic process, whereas SHRED has GO:0043161 proteasome-mediated ubiquitin-dependent protein catabolic process. Although the definition for ERAD has e.g. ubiquitination, so maybe ERAD does not always use ubiquitination to target proteins for degradation, which would explain why has not got the same parent as SHRED.

If there are key proteins that mark ERAD v SHRED then it might help to list these in both entries?

GO:0120174 stress-induced homeostatically regulated protein degradation pathway
Definition: A stress-inducible pathway that accelerates the degradation of misfolded and native proteins at the ER membrane and in the cytosol by reprogramming the specificity of a component of the protein quality control machinery. PMID:29861160

GO:0036503 ERAD pathway
Definition The protein catabolic pathway which targets endoplasmic reticulum (ER)-resident proteins for degradation by the cytoplasmic proteasome. It begins with recognition of the ER-resident protein, includes retrotranslocation (dislocation) of the protein from the ER to the cytosol, protein modifications necessary for correct substrate transfer (e.g. ubiquitination), transport of the protein to the proteasome, and ends with degradation of the protein by the cytoplasmic proteasome. PMID:20940304 PMID:21969857

**Comment by krchristie** [comment]
@robnash & @RLovering - If you guys come to agreement on specific action items for this ticket, please list them in this ticket. At the moment, I do not see any clear action items.

**Comment by RLovering** [comment]
Hi Rob

sorry for adding to your work load, but it is better to make it clear now than in 2 years time when there are lots of misannotations.

I have suggested a start and end point to the pathway in your definition,  (below) what do you think?

GO:0120174	stress-induced homeostatically regulated protein degradation pathway

Definition: A stress-inducible protein catabolic pathway that promotes protein quality control by accelerating the degradation of misfolded ER membrane and cytosolic proteins, as well as native proteins. The pathway starts with the activation, by stress, of the Nma111p/Ynm3p serine protease, which cleaves the stress-induced hydrophilin Roq1p, resulting in the generation of a Roq1p cleavage product that selectively interacts with Ubr1p, an E3 ubiquitin ligase. Interaction with the Ubr1p type-1 substrate binding site reprograms the substrate specificity of this ubiquitin ligase resulting in the selective proteasome-mediated degradation of misfolded and native proteins. The pathway ends with degradation of the protein by the cytoplasmic proteasome. Currently, NMA111, ROQ1, UBR1, RAD6, and CDC48 are considered to be involved in this quality control pathway.

**Comment by robnash** [comment]
@RLovering @krchristie  This looks great! Thanks for the edits.

**Comment by RLovering** [comment]
Hi Karen

please could you use my revised version of Robs definition for GO:0120174	stress-induced homeostatically regulated protein degradation pathway and then add Rob's comments to the two records (GO:0120174	stress-induced homeostatically regulated protein degradation pathway and ERAD pathway GO:0036503) as he has described.
Thanks
Ruth

**Comment by krchristie** [comment]
Thanks @RLovering and @robnash for resolution on these changes.

I've commited Rob's comments, and Ruth's modified definition. For the definition, I wanted to credit Ruth as well so guessed that GOC:rl is her citation. If this is incorrect please provide the correct one and I will fix it. Thanks!
