### ISSUE TITLE
transcriptional preinitiation complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15870]
transcriptional preinitiation complex
A protein-DNA complex composed of proteins binding promoter DNA to form the transcriptional preinitiation complex (PIC), the formation of which is a prerequisite for transcription. PMID:22751016

has no children and only 704 annotations in total (10 experimental SGD and CAFA)

SGD annotations are  SUA7 (TFIIB), TFA1 (TFIIE), TFA2 (TFIIE), SSL2 (TFIIH)

There must be an issue with the definition/placement (should it have children? should it exist?)

**Comment by pgaudet** [comment]
I wonder if it's the same as 
- 'DNA-directed RNA polymerase II, core complex' or  DNA-directed RNA polymerase II, holoenzyme ? 
(should we have these two terms anyway? I think this is sort of a purification artifact and probably only the holoenzyme is active; I don't know if the core enzyme has a function. 

@krchristie 

Thanks, Pascale

**Comment by ukemi** [comment]
#10556

**Comment by bmeldal** [comment]
Without looking into the details, it sounds like one of those situations where the core FUNCTION is conserved but dep on taxon, tissue, cellular circumstances etc the composition is variable. We have curated the yeast complex:
https://www.ebi.ac.uk/complexportal/complex/CPX-2662
and annotated to GO:0005665 DNA-directed RNA polymerase II, core complex
https://www.ebi.ac.uk/QuickGO/term/GO:0005665

while a lot of the general TFs and core mediator (in several species) are annotated to:
GO:0016591 DNA-directed RNA polymerase II, holoenzyme
https://www.ebi.ac.uk/QuickGO/term/GO:0016591

We have no annotations to 
GO:0097550 transcriptional preinitiation complex
https://www.ebi.ac.uk/QuickGO/term/GO:0097550

The yeast RNAPII refers to the PIC in the description

>During a transcription cycle, Pol II, general transcription factors and the mediator complex (CPX-3226) assemble as the preinitiation complex (PIC) at the promoter.

but we didn't curate the PIC itself because it is difficult to define as RNAPII, general TFs and core mediator come and go during transcription initiation.

**Comment by ValWood** [comment]
There are only 10 EXP annotations total to 
GO:0097550 transcriptional preinitiation complex
5 CAFA
4 SGD
1 uniprot.
It seems sensible to get rid of this ....

**Comment by pgaudet** [comment]
OK

**Comment by bmeldal** [comment]
>while a lot of the general TFs and core mediator (in several species) are annotated to:
GO:0016591 DNA-directed RNA polymerase II, holoenzyme
https://www.ebi.ac.uk/QuickGO/term/GO:0016591

Sorry, they are annotated to the specific CHILDREN of this term! e.g. TFIIIB complex, core mediator complex...

**Comment by pgaudet** [comment]
According to wikipedia: 
https://en.wikipedia.org/wiki/Transcription_preinitiation_complex
is like the holoenzyme (GO:0016591)? 
The definition is "A nuclear DNA-directed RNA polymerase complex containing an RNA polymerase II core enzyme as well as additional proteins and transcription factor complexes, that are capable of promoter recognition and transcription initiation from an RNA polymerase II promoter in vivo. These additional components may include general transcription factor complexes TFIIA, TFIID, TFIIE, TFIIF, or TFIIH, as well as Mediator, SWI/SNF, GCN5, or SRBs and confer the ability to recognize promoters."

**Comment by bmeldal** [comment]
That does sound like the holoenzyme and PIC are regarded as the same thing. In which case it's a grouping term for the specific TFs, Pols and mediator etc.

**Comment by ValWood** [comment]
Thant sounds sensible if Karen agrees.

**Comment by pgaudet** [comment]
Another question: The term has subclasses: 

'protein-containing complex'
 and ('capable of' some 'DNA-directed 5'-3' RNA polymerase activity')

however the definition really talks about 'transcription initiation', so I think these relations should go. 

@ValWood @krchristie what do you think ?

**Comment by pgaudet** [comment]
A second question: 
DNA-directed RNA polymerase II, holoenzyme
is a subclass of 'nucleoplasm'; that also seems wrong, given that its a complex with the DNA. 

Should it be part of chromatin ? 

Thanks, Pascale

**Comment by krchristie** [comment]
"DNA-directed RNA polymerase II, holoenzyme" is NOT necessarily bound to DNA. In fact it has been purified as a large protein complex not attached to DNA many, many different times. There have also been models that propose that the holoenzyme preassembles before binding to DNA, so, unless you have new evidence that disproves that idea, I think that it is not OK to specify that the RNAP II holoenzyme is bound to DNA.

Also worth being aware that there is a long-standing issue about the fact that the composition of "the" holoenzyme appears to be incredibly variable. Thus, it is not a single complex, but rather any of a number of complexes that contain RNAP II and some number of other factors that are required to bring it to the promoter.

> Based on the definitions, the 'DNA-directed RNA polymerase II, core complex' should have the 'capable of' some 'DNA-directed 5'-3' RNA polymerase activity' ("... Although the core is competent to mediate ribonucleic acid synthesis, it requires additional factors to select the appropriate template.")

I'm inclined to agree that 
- the 'DNA-directed RNA polymerase II, core complex' should have the 'capable of' some 'DNA-directed 5'-3' RNA polymerase activity'
- while the holoenzyme could possibly be considered to be competant for transcription initiation

**Comment by ValWood** [comment]
> "DNA-directed RNA polymerase II, holoenzyme" is NOT necessarily bound to DNA. 

The same is true for many complexes,  but we building location of activity into GO seems fine to me? I  don't have a problem with any nuclear transcription factor complexes being a child of  "chromatin".

**Comment by ukemi** [comment]
I think this is very dangerous. The ontology is meant to represent universals. It seems part of is not the right relationship for what you want. It is universally true that the complex is always part of the nucleoplasm.

**Comment by ValWood** [comment]
Is that what we always do though?

**Comment by ValWood** [comment]
Maybe we do. Nearly. There are no complexes under chromatin, except "nucleosome"

**Comment by ukemi** [comment]
Because nucleosomes are always part of chromatin.

**Comment by ValWood** [comment]
So there are no free nucleosomes? OK...
Makes sense...

**Comment by ukemi** [comment]
Nucleosome: A complex comprised of DNA wound around a multisubunit core and associated proteins, which forms the primary packing unit of DNA into higher order structures.

**Comment by krchristie** [comment]
I was about to say the same thing as @ukemi

**Comment by ValWood** [comment]
OK!

**Comment by pgaudet** [comment]
'nuclear transcription factor complex' is 'part of' some nucleus'.

We should do the same with the others (GTFs), I think.

**Comment by pgaudet** [comment]
Well - DNA-directed pol II and IV complexes are 'part of the nucleoplasm', which excludes the chromosomes. Is this right ? 

Isn't it the case that these proteins are *active* at the chromatin but can also be found in free form? Aren't we capturing the active form ? 

(Safest seems to be 'nuclear' for all). 

Pascale

**Comment by pgaudet** [comment]
Current structure is: 
'nuclear DNA-directed RNA polymerase complex'
- 'alpha DNA polymerase:primase complex'
- 'DNA-directed RNA polymerase I complex'
- 'DNA-directed RNA polymerase II, core complex'
- 'DNA-directed RNA polymerase II, holoenzyme'
- 'DNA-directed RNA polymerase III complex'
- 'DNA-directed RNA polymerase IV complex'
- 'DNA-directed RNA polymerase V complex'

If I move alpha DNA polymerase:primase complex' I can add 'capable of' some 'DNA-directed 5'-3' RNA polymerase activity' to the parent 'nuclear DNA-directed RNA polymerase complex' (and since the core complex is part_of the holoenzyme, the core complex anyways inherits the activity). 

Pascale

**Comment by bmeldal** [comment]
>Safest seems to be 'nuclear' for all.

I think so.

>If I move alpha DNA polymerase:primase complex' I can add 'capable of' some 'DNA-directed 5'-3' RNA polymerase activity' to the parent 'nuclear DNA-directed RNA polymerase complex' 

GO:0055029 nuclear DNA-directed RNA polymerase complex
"A protein complex, located in the nucleus, that possesses DNA-directed RNA polymerase activity." 

That holds true for 'alpha DNA polymerase:primase complex' so can't move unless you make the def of 'nuclear DNA-directed RNA polymerase complex' stricter and exclude synthesis of short RNA strand.

>and since the core complex is part_of the holoenzyme, the core complex anyway inherits the activity.

Aren't we merging them? Or just holoenzyme and PIC? I don't like the core vs holo- distinction as it has a fluid boundary and is used mainly by experimentalists to distinguish between persistently-found proteins and those that come and go dep on the cellular circumstances. Often you don't find the core complex on it's own, at least not as the functional unit.

**Comment by pgaudet** [comment]
These labels should be simplified: 

'RNA polymerase I complex'
'RNA polymerase II, core complex'
'RNA polymerase II, holoenzyme'
'RNA polymerase III complex'
'RNA polymerase IV complex'
'RNA polymerase V complex'
(since the RNA-directed RNA polymerases are called 'RNA-directed RNA polymerases', and not I, II, III, IV, V, there is no risk of confusion)

**Comment by pgaudet** [comment]
@bmeldal 
So you suggest I do a 3-way merge between PIC, core and holenzyme ? 
(that works for me)

**Comment by bmeldal** [comment]
It's safer as it reflects biology better, I don't know that the others thinks???

(I've come across quite a few examples of that "behaviour' when curating poorly-defined epigenetic complexes. They seem to be poorly defined as they are a) difficult to purify and b) vary dep on cellular circumstances. And then there are the technical artifacts to consider - just because you don't see one of the proteins one day doesn't mean it's not there, it just didn't get pulled down under the conditions. Change the conditions and you get a slightly different complex... And then you get the complexes defined on what has been detected on a Western based on **expected** members! No effort to identify ALL potential members but drawing some strong conclusions about the complex composition. Nightmare!!!)

**Comment by pgaudet** [comment]
Reflecting the biology is great !!

**Comment by bmeldal** [comment]
>Reflecting the biology is great !!

Isn't that our job?

**Comment by pgaudet** [comment]
OK, 3-way merge it is, and the label will be 'DNA-directed RNA polymerase II'. 
Let me know if that's not right.

**Comment by pgaudet** [comment]
In fact I think the holoenzyme should be obsoleted (as @ukemi also suggested in #10556). We cannot be sure of whether the proteins annotated to the holoenzyme are part of PolII. 

There are 


(9)	PomBase @ValWood 
(9)	SGD @krchristie  @suzialeksander 
(9)	UniProt @ggeorghiou @sylvainpoux 
(1)	TAIR @tberardini 

Let me know if a merge would be OK. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I thin mediator needs to be moved out from RNA pol II complex, see #15979

**Comment by ValWood** [comment]
This  is what I would prefer

keep 

DNA-directed RNA polymerase II, core complex
https://www.pombase.org/term/GO:0005665

mediator
https://www.pombase.org/term/GO:0016592
(I don't see this as part of any polymerase term)

get rid of
 DNA-directed RNA polymerase II, holoenzyme (GO:0016591)
https://www.pombase.org/term/GO:0016591

**Comment by bmeldal** [comment]
"DNA-directed RNA polymerase II, core complex" --> "DNA-directed RNA polymerase II" (remove "core")

Mediator and integrator complexes are not a type of RNAPII, they interact with it: https://github.com/geneontology/go-ontology/issues/15979

**Comment by ValWood** [comment]
> "DNA-directed RNA polymerase II, core complex" --> "DNA-directed RNA polymerase II" (remove "core")

is only used for the polymerase itself. There shouldn't be any mediator subunits annotated to this term.

I don't think you can merge 
DNA-directed RNA polymerase II, holoenzyme (GO:0016591)
into any existing term.

Most of our annotations to this term would not fit the existing subcomplexes. I  will fix them. I think everyone should check, it's been used somewhat loosely....

https://github.com/pombase/curation/issues/2067

**Comment by bmeldal** [comment]
>I don't think you can merge
DNA-directed RNA polymerase II, holoenzyme (GO:0016591)
into any existing term.

>Most of our annotations to this term would not fit the existing subcomplexes. I will fix them. I think everyone should check, it's been used somewhat loosely....

>pombase/curation#2067

Ok, I guess it needs an annotation revision ticket, @pgaudet

**Comment by krchristie** [comment]
Core RNAP II versus holoenzyme does not have a fluid boundary. Core is very simply defined as the 12 subunit enzyme. It is definitely NOT equivalent to either the PIC or the holoenzyme. I think it would be a truly bad idea to merge core and holoeyzme. The core term has a very useful role of definining the composition of the RNAP II enzyme itself. 

Holoeyzme has multiple different compositions, which all include RNAP II core, as well as a varying composition of other transcription complexes. I have proposed obsoleting it previously due to the inability to define it precisely. However, this has been strenuously objected to by multiple people because the phrase "holoenzyme" is used frequently in the literature. @RLovering may have an opinion on this.

I would think that incorrect annotations to a term would be justification for fixing the annotations, not necessarily for obsoleting the term.

**Comment by bmeldal** [comment]
Just because experimentalists call things core and holo doesn't mean it reflects biology. In epigenetic complexes they call the catalytic core components "core" as they are always there and necessary but they never act on their own in the cell (they may be functional on their own in vitro). 

We should describe what's happening in the cell.

The mediator is different, the CDK subcomplex does come and go and gives the mediator a different function.

**Comment by bmeldal** [comment]
>Core RNAP II versus holoenzyme does not have a fluid boundary. Core is very simply defined as the 12 subunit enzyme.

Not according to the GO def:
" RNA polymerase II, one of three nuclear DNA-directed RNA polymerases found in all eukaryotes, is a multisubunit complex; typically it produces mRNAs, snoRNAs, and some of the snRNAs. Two large subunits comprise the most conserved portion including the catalytic site and share similarity with other eukaryotic and bacterial multisubunit RNA polymerases. The largest subunit of RNA polymerase II contains an essential carboxyl-terminal domain (CTD) composed of a variable number of heptapeptide repeats (YSPTSPS). The **remainder of the complex is composed of smaller subunits (generally ten or more)**, some of which are also found in RNA polymerases I and III. **Although the core is competent to mediate ribonucleic acid synthesis, it requires additional factors to select the appropriate template.**"

No list of core subunits (in bold) and a clear comment that it required additional subunit for its full activity (in bold).

Therefore, "holoenzyme" subunits can be annotated to this term. 

And PIC is very badly defined:

GO:0097550 transcriptional preinitiation complex
"A protein-DNA complex composed of proteins binding promoter DNA to form the transcriptional preinitiation complex (PIC), the formation of which is a prerequisite for transcription."

As mentioned above, we didn't curate the PIC as it's impossible to define.

**Comment by krchristie** [comment]
That sentence you have highlighted in the definition above does NOT mean that holoenzyme components should be annotated to the term for core RNAP II. 

It refers to the fact that RNAP II is competent for the FUNCTION of the enzyme activity, but that other things are required for the PROCESS of transcription. 

It becomes very problematic to have all the things that have been annotated to holoenzyme start get annotated to something that is 'capable of' RNA polymerase activity, because NONE of these other things are capable of this activity, nor do they contribute to the activity. Rather, they act to bring the enzyme to the correct place.

**Comment by pgaudet** [comment]
What I proposed in the end is to 
- obsolete PIC
- obsolete holoenzyme (see #10556 )
- rename core -> RNA polymerase II complex

As the exchange shows, PIC and holoenzyme are not clear complexes. I read the definition for core the same as @krchristie , but if you have suggestions to clarify the meaning @bmeldal , please send them (perhaps the sentence in bold is actually more confusing than helpful).

Thanks, Pascale

**Comment by pgaudet** [comment]
Emailed Colin, Astrid, Marcio, Ruth and Val.

**Comment by bmeldal** [comment]
"Although the core is competent to mediate ribonucleic acid synthesis, it requires additional factors to select the appropriate template."

>It refers to the fact that RNAP II is competent for the FUNCTION of the enzyme activity, but that other things are required for the PROCESS of transcription.

>As the exchange shows, PIC and holoenzyme are not clear complexes. I read the definition for core the same as @krchristie , but if you have suggestions to clarify the meaning @bmeldal , please send them (perhaps the sentence in bold is actually more confusing than helpful).

As read it as referring to the COMPOSITION as we are discussing the COMPONENT term. Where did I get it wrong?

>It becomes very problematic to have all the things that have been annotated to holoenzyme start get annotated to something that is 'capable of' RNA polymerase activity, because NONE of these other things are capable of this activity, nor do they contribute to the activity. Rather, they act to bring the enzyme to the correct place.

I would never suggest to annotate the non-catalytic components to RNAP ACTIVITY but we are discussing the COMPONENT term here. Which complex COMPONENT term will you annotate the old holoenzyme and PIC components to now? If they are chaperones etc they should never have been annotated to a complex term anyway. But how do you annotate components that are truly part of the RNAPII complex but not part of the conserved core and not a chaperone? @ValWood?

**Comment by ValWood** [comment]
> Which complex COMPONENT term will you annotate the old holoenzyme and PIC components to now? If they are chaperones etc they should never have been annotated to a complex term anyway. But how do you annotate components that are truly part of the RNAPII complex but not part of the conserved core and not a chaperone?

I don't currently have any examples which  would not be annotated to  one of the subcomplexes, with the exception of the CTD phosphatase  fcp1. I would be happy for this not to have a holoenzyme annotation since it is connected via substrate "rpb1". This phosphatase may  be more promiscuous (I don't know, but it relocalizes to the cytosol during hypoxia).

I'm a bit ambivalent whether we keep the term or not if people think we should have it as a grouping term, I'm happy for it to stay....but we need to be precise about what would be annotated to it.....

**Comment by ValWood** [comment]
This is what I have
https://www.pombase.org/term/GO:0016591

**Comment by ValWood** [comment]
It might be useful to know what would not be annotated without the "holoenzyme" term. Then we would know if we needed it.

**Comment by bmeldal** [comment]
Ok, this looks suspiciously like the spliceosome situation. Many small complexes come and go during the process but all are referred to as "spliceosome". We curated the individual, functional complexes and then annotated them to spliceosome. But that's effectively a compositional grouping term, too, just without the core and holo- distinctions.

These grouping terms are no longer grouping the same functional complexes but complexes in the same process. In principle, we decided that that would open a can of worms, but terms like RNAP holoenzyme and spliceosome are very old terms that people expected to see. It's more of a philosophical dilemma than a biological one as we know so much more about these compositions and functions now.

I know I'm branching out but we need to look at the big picture: There are case like
GO:0000307 cyclin-dependent protein kinase holoenzyme complex
"Cyclin-dependent protein kinases (CDKs) are enzyme complexes that contain a kinase catalytic subunit associated with a regulatory cyclin partner."

This one is not a holoezyme in the sense that its members come and go, the child terms are all the different CDKs. Here, the usage of "holoenzyme" is entirely wrong (I'm sure I've pointed it out before). It should be plainly removed form the term name. 

This is why I very much dislike "holoenzyme or holocomplex" - as it gets used in completely different contexts in the ontology. It seem to be a lazy way of grouping stuff.

**Comment by pgaudet** [comment]
Here's an idea to perhaps resolve this (or make it worse;) 
we have a term 'basal transcription machinery binding' (0 annotations) and a child, 'RNA polymerase II basal transcription factor binding' (2 EXP). Perhaps these are the grouping terms we are looking for ? 

ie if we create a term 'general transcription initiation factor complex', to match the term in the new version of the MF, this could replace the holoenzyme as the parent class for the current children of the holoenzyme:
* GO:0016593 Cdc73/Paf1 complex
* GO:0005665 DNA-directed RNA polymerase II, core complex
* GO:0005675 holo TFIIH complex
*  GO:0034740 TFIIIC-TOP1-SUB1 complex
*  GO:0005672 transcription factor TFIIA complex
* GO:0005669 transcription factor TFIID complex
* GO:0005673 transcription factor TFIIE complex
*  GO:0005674 transcription factor TFIIF complex
* GO:0070264 transcription factor TFIIIE complex
*  GO:0033276 transcription factor TFTC complex 

(and the MF basal transcription machinery binding should be renamed 'general transcription initiation factor complex binding'. 

Would that help ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I have no objection if others think it would be useful.
I'm never so fussed about grouping terms for complexes though. 
one caveat, I don't think you can include 
GO:0005665 DNA-directed RNA polymerase II, core complex
or even some of the others in this grouping if they are also involved in elongation?

**Comment by pgaudet** [comment]
> one caveat, I don't think you can include GO:0005665 DNA-directed RNA polymerase II, core complex or even some of the others in this grouping if they are also involved in elongation?

I agree

**Comment by bmeldal** [comment]
and there's the wrap... grouping terms without functional homology just don't work.
(and yes, I learned that the hard way myself)

**Comment by RLovering** [comment]
Hi sorry to be late in this discussion. Just to be clear, I thought that large complexes (not just involved in transcription) often have 'fluid' components so that to decide to not have the PIC because the components are not consistent from cell to cell, time to time seems a bit odd. However, I also appreciate that the ontology structure would mean having to co-annotate to this term as well as the other more specific terms, so sounds like a good plan. 

Will the resulting ontology mean that every protein involved in transcription (at the DNA level) can be annotated with a cellular component term? Or is this no longer a goal of the project? I don't really mind either way but the answer may help make the decision about these terms more straightforward.

Ruth

**Comment by bmeldal** [comment]
>Will the resulting ontology mean that every protein involved in transcription (at the DNA level) can be annotated with a cellular component term?

I would hope so, but double annotations to 2 terms that are overlapping don't sound great (as opposed to moonlighting proteins that are part of different complexes). That's why I asked about proteins that were annotated to the holoenzyme term and where they would go if we'd obsolete the term. In pombe it doesn't seem to be a big issue, what about mammalians?

NB: I had to create a bunch of complex term that have direct parent protein-containing complex as their precise function is not yet known and we decided not to create "processy" grouping terms. But the components can be nicely annotated to these complex terms as the complexes themselves are well defined.

**Comment by pgaudet** [comment]
Colin, Astrid and Marcio emailed back in favor of obsoletion.

**Comment by bmeldal** [comment]
Obsoletion for holoenzyme and PIC?

**Comment by ValWood** [comment]
There are 28 EXP  direct annotations to holoenzyme.

These are:
IWR1 SGD (7 by IPI, sombody really wanted to get this one in there)... it's a nucleocytoplasmic transport factor 

ASK10 SGD  Regulator of the Fps1p glycerol channel (colocalizes with) 
ABD1 | Methyltransferase | colocalizes_with | DNA-directed RNA polymerase II, holoenzyme


rpb4 PomBase DNA-directed RNA polymerase II complex subunit Rpb4  (will remove today- not required)
rpb7 PomBase DNA-directed RNA polymerase II complex subunit Rpb4  (will remove today- not required)
rpb3 PomBase DNA-directed RNA polymerase II complex subunit Rpb4  (will remove today- not required)
rpb9 PomBase DNA-directed RNA polymerase II complex subunit Rpb4  (will remove today- not required)
rpb11 PomBase DNA-directed RNA polymerase II complex subunit Rpb4  (will remove today- not required)
rpb8 PomBase DNA-directed RNA polymerase II complex subunit Rpb4  (will remove today- not required)

set2 PomBase removed yesterday (incorrect)
fcp1  (x2) PomBase   removed yesterday appropriate   DNA-directed RNA polymerase II subunits captured as targets


RPRD2 | Regulation of nuclear pre-mRNA domain-containing protein 2
MYO6 | Unconventional myosin-VI
RPRD1B | Regulation of nuclear pre-mRNA domain-containing protein 1B
RPRD1A | Regulation of nuclear pre-mRNA domain-containing protein 1A
RPAP2  (2) | Putative RNA polymerase II subunit B1 CTD phosphatase RPAP2
POLR2M | DNA-directed RNA polymerase II subunit GRINL1A
RECQL5 | ATP-dependent DNA helicase Q5
ERCC5 | DNA repair protein complementing XP-G cells


so very little to check....

they won't be without a CC annotation... chromatin, chromosome, nucleus are options

**Comment by pgaudet** [comment]
The list of annotations is here: 
https://docs.google.com/spreadsheets/d/1WoXVuIr5VDSlhbCVY6EXvGtII2XQeiTbyDinKPI7n0U/edit#gid=0

**Comment by ValWood** [comment]
IMHO we don't really really need the holoenzyme for modelling.
This is really a grouping term/ construct for referring to the "transcription initiation machinery".

We don't really need this construct because we have a process term (transcription initiation), and we know the subcomponents.

We don't absolutely need to use every label that humans have invented in GO...especially labels that refer to an entity that is difficult to pin down because it  represents multiple entities in a process that change over  time.

**Comment by pgaudet** [comment]
Obsoletion notice sent: 
Dear all,

The proposal has been made to obsolete GO:0097550 'transcriptional preinitiation complex. The reason for obsoletion is that 


There are 10 experimental SGD (4), CAFA (5) and UniProt (1) and 1 ISS by FlyBase. 

There are no InterPro2GO mappings. 

Comments can be added to the ticket: https://github.com/geneontology/go-ontology/issues/15870

We are opening a comment period for this proposed obsoletion. We'd like to proceed and obsolete this term on July 11, 2018. Unless objections are received by July 11  2018, we will assume that you agree to this change.

Thanks,

Pascale

**Comment by tberardini** [comment]
Checked TAIR annotations, moved to child term, GO:0005665.

**Comment by krchristie** [comment]
@tberardini - Can I ask what genes were annotated to PIC that you moved to GO:0005665, the term for the core complex? I feel strongly that this core term should only be used for annotation of the subunits of the actual enzyme.

**Comment by tberardini** [comment]
@krchristie : Annotations for two of the Arabidopsis homologs of two yeast genes that are annotated to the core term in SGD were moved.

**Comment by krchristie** [comment]
I've been thinking about this a lot, but wanted to take a little time to check if current thinking has changed significantly since the last time I spent much time in this area. A very quick PubMed search turned up papers discussing both the holoenzyme and the PIC, largely consistently with my memory, i.e. the holoenzyme is pre-assembled RNAP II plus varous initiation factors that is NOT bound to DNA, while the PIC is the complex of RNAP II and initiation factors assembled onto the DNA. The terms do not appear to be used synonymously.

Here are three very recent papers that showed up in my search:
- Tsai et al. Mediator structure and rearrangements required for holoenzyme formation. Nature. 2017 Apr 13;544(7649):196-201.  PMID: 28241144
- Montes et al. RNA polymerase II components and Rrn7 form a preinitiation complex on the HomolD box to promote ribosomal protein gene expression in Schizosaccharomyces pombe. FEBS J. 2017 Feb;284(4):615-633.  PMID:28060464
- Sato et al.  Role for the MED21-MED7 Hinge in Assembly of the Mediator-RNA Polymerase II
Holoenzyme. J Biol Chem. 2016 Dec 23;291(52):26886-26898. PMID:27821593

What I see in this recent PubMed search is consistent with an older review that is very well regarded. I have included a useful quote from it:

Thomas MC, Chiang CM. The general transcription machinery and general cofactors.  Crit Rev
Biochem Mol Biol. 2006 May-Jun; 41(3):105-78. Review. PMID:16858867

> However, whether eukaryotic pol II indeed exists as a holoenzyme complex in the cell or is
recruited in a stepwise manner as a separate entity, along with individual GTFs, to the
promoter region remains to be elucidated. It is likely that both assembly pathways exist in
vivo, and, depending on specific signaling molecules involved and the promoter context, either
pathway may be employed in responding to environmental cues.  Indeed, evidence supporting both models has been reported for different regulatory systems (Orphanides et al., 1996; Hampsey, 1998; Parvin and Young, 1998; Lee and Young, 2000; Lemon and Tjian, 2000).

Similarly, the WikiPedia page Pascale cited says this:

> An alternative hypothesis of PIC assembly postulates the recruitment of a pre-assembled "RNA
Polymerase II holoenzyme" directly to the promoter (composed of all, or nearly all GTFs and RNA
polymerase II and regulatory complexes), in a manner similar to the bacterial RNA polymerase
(RNAP).

Numerous questions have been raised in this ticket. Here are my thoughts on some of them.

**1. Are these three terms the same thing?**
- 'DNA-directed RNA polymerase II, core complex'
- 'DNA-directed RNA polymerase II, holoenzyme'
- 'transcriptional preinitiation complex'

No, they are not the same or synonymous with each other. The core term is very specifically the 12 subunit RNAP II enzyme. The holoenzyme is the term for the RNAP II enzyme plus some set of
initiation factors when they have assembled prior to binding to the promoter. The third term is for
a transcription complex assembed on the promoter, but do note that the definition of this term is
not specific to RNAP II (though the single reference for this term is a RNAP II specific paper,
PMID:22751016). In my opinion these terms do not mean close enough to the same thing to merge any of them with any others of these three terms.

**2. Why are there so few annotations to the PIC term?**
Possibly because it wasn't created until 2014 (I did not look for a ticket to see why Paola created
the term). Since the majority of RNA polymerase subunits and general transcription factors for most of the RNA polymerases have been fairly well annotated for years, it doesn't seem that surprising that the term hasn't been used much since these genes aren't going to be on lists of genes lacking annotation.

**3. Why does the PIC term not have any children?**
Good question. To be consistent with the way we have done the process terms, e.g. terms like 'RNA polymerase II transcriptional preinitiation complex assembly', it would make more sense if there were PIC terms for each of most of the different RNA polymerases, at least the eukaryotic nuclear RNAPs I, II, III, IV, & V, as well as the bacterial enzyme, and possibly also the mitochondrial and plastid enzymes.

**4. Is it OK for the PIC and the RNAP II holoenzyme terms to be "grouping terms"
for a number of similar complex with slightly differing composition?**
I don't really see a problem with this. We do already have other complex terms in CC that are also
grouping terms for a number of different complexes. To take an example that I have been looking at again lately, e.g. 'box C/D snoRNP complex', if you go look at the SGD page (since I know SGD has completely annotated all of its box C/D snoRNAs) for this GO term
(https://www.yeastgenome.org/go/GO:0031428), you will see annotations to 53 genes, 47 of which are snoRNA genes (count from YeastMine). One could mistakenly think this was a complex containing all 47 of these snoRNA genes in the same complex, rather than 47 different snoRNA complexes, each containing a single box C/D snoRNA. We have opted not to represent each different snoRNA complex separately because they mostly do similar things and because there isn't really good nomenclature for each of them individually, though in this case it's also an issue that the number of snoRNAs and their names aren't that well conserved from yeast to mammals, so you would end up with a pretty large number of terms for different box C/D snoRNP complexes some of which are species specific. It just doesn't seem necessary or reasonable to make individual terms for each specific complex.

I don't see how having terms for RNAP II holoenzyme or PIC is really that different. Yes, there is
variation in different holoenzymes and PIC's, and there is no nomenclature that would allow you to make separate complexes even if you wanted to. I would submit that we would not want to make all possible PIC or holoenzyme complexes even if we could. That seems like going to a level of granularity that is not practical or useful.

However, it is NECESSARY to remove the part_of relationships between the holoenzyme term and the various other transcription factor complexes because these part_of relationships are definitely not ALWAYS true.

**5. Should we get rid of the holoenzyme and PIC terms and create a term 'general transcription
initiation factor complex' instead?**
Well, I think this would be MORE confusing than the existing terms because holoenzyme and PIC are the terms that are used in the literature. In contrast, the idea to make a term for 'general
transcription initiation factor complex' with these child terms:

- GO:0016593 Cdc73/Paf1 complex - NOT strictly an initation cmoplex
- GO:0005665 DNA-directed RNA polymerase II, core complex - NOT an initation complex
- GO:0005675 holo TFIIH complex
- GO:0034740 TFIIIC-TOP1-SUB1 complex - NOT a RNAP II complex at all
- GO:0005672 transcription factor TFIIA complex
- GO:0005669 transcription factor TFIID complex
- GO:0005673 transcription factor TFIIE complex
- GO:0005674 transcription factor TFIIF complex
- GO:0070264 transcription factor TFIIIE complex
- GO:0033276 transcription factor TFTC complex

is problematic for several reasons. One is that some of the things here shouldn't be described as initiation factors.  It also seems that it would probably be confusing to put the TFIIIC complex that you've added (that I do not currently see under the RNAP II holoenzyme term anyway) here with the RNAP II factors. In addition, a term specific to initiation factors is not really a good replacement for either the holoenzyme or PIC, as both of these macrocomplexes include things that are not described as "initiation factors", e.g. mediator is more often called a coactivator. 

**6. Annotation issues: What should be annotated to these terms?**
As Ruth pointed out, to use either the holoeyzme or PIC term would often involve
co-annotation. Eventually GO-CAM models seem like a great way to be able to use these terms in
annotation, so that if a curator has chosen to annotate a paper that characterizes a holoenzyme or PIC complex, they can put it in the context of in this specific situation, this holoenzyme or PIC
was observed, and for the PIC term, that context might even be able to include the specific gene
promoter that the PIC is assembled on.

While it is true that Noctua does not yet really allow this currently, I think it is not useful to
make arguments about appropriate annotation based on what Noctua can do NOW, as Noctua is still in very early stages and does not yet do all the things we want it to do.



**SUMMARY**:  I am with Ruth, I think these terms are fine and serve useful purposes.

I actually think that having the PIC and holoenzyme terms present in the ontology can be helpful to curators so that if they search for these names, which remain in common use in the transcription literature, they find them and see what they are, and how they are different from the RNAP II core term. We really don't want all the initiation factors and coactivators present in either holoenzyme or the PIC to end up being annotated to the RNAP II core term, because that's definitely not true.

**Comment by krchristie** [comment]
In future, it would be good if obsoletion notices are not sent while there is still active discussion on a ticket, so that people don't do reannotation work before it is agreed that a term will be obsoleted.

**Comment by pgaudet** [comment]
The suggestion by the transcription group is to merge holoenzyme into PIC (see also #10556). 

- Pascale

**Comment by ValWood** [comment]
Is this ticket out of date, 
and the #10556 2013 ticket?

**Comment by pgaudet** [comment]
See action points in #10556
