### ISSUE TITLE
RNA-binding transcription regulator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15872]
RNA-binding transcription regulator activity
has no experimental annotation (but lots of IEA's)

What is this term for? The PMID is
http://europepmc.org/abstract/MED/1756726

It isn't clear  what it would be used for. Should it have organism restrictions?

**Comment by pgaudet** [comment]
@ValWood I dont see that paper as a reference for 'RNA-binding transcription regulator activity' 


<img width="624" alt="image" src="https://user-images.githubusercontent.com/4782928/41035118-abcbdd3a-6959-11e8-9b15-3bd0c4851658.png">


There was quite some discussion about this term here: #14334

Pascale

**Comment by ValWood** [comment]
Ah OK the reference is PMID:8332211

This is describing a viral protein modulating host transcription in some way?

Could this have a "only in virus" taxon restriction  (this could be changed if others are identified).

I still think it seems odd to position this under "transcription regulator"  (not every single  protein that regulates transcription needs to be under here. My understanding was that this was to group the  canonical txn factors that  work with the polymerase. any  other things that   regulate  transcription  are not under here (for example chromatin remodellers, RNAi etc).

This could easily be annotated as
"mRNA binding" part_of "negative regulation of transcription"

**Comment by pgaudet** [comment]
- Added taxon restriction (Viruses) 
- Updated definition to "Interacting selectively and non-covalently with an RNA sequence in order to modulate transcription. This function is known to occus in phages and viruses, for example the lambda  N and the HIV tat proteins are necessary to allow RNA polymerase to read through terminator sequences. " 
- Did no move the term (yet) - it seems to be a legit regulator of transcription... ?
