### ISSUE TITLE
Why there are changes to obsolete terms?

### ISSUE THREAD

**Issue by pengyubio** [geneontology/go-ontology#15895]
I am wondering what is the meaning of "obsolete" in GO.

https://www.ebi.ac.uk/QuickGO/term/GO:1901574

It was noted as "obsolete" on 2012-11-10. There are multiple changes added on or after that date, including adding synonyms. Since "obsolete" means "no longer produced or used; out of date" according a English dictionary, why are there still synonyms added to such obsolete terms?

**Comment by ukemi** [comment]
Hi @pengyubio 

Obsolete means that we have determined that the term definition is incorrect because either it has been shown to not be true  biologically, because the definition is unclear/ambiguous and the term has been misused, or for some other reason such as not adhering to current ontology development guidelines. Obsolete terms should not be used for annotation and annotations to obsolete terms should be moved to more appropriate terms or removed. To guide gene annotators we sometimes add replaced_by or consider tags to obsolete terms. Those tags point to terms that either replace the incorrect/inaccurate obsolete term of are terms that can be considered for reannotation.  

For your example, most of these synonyms were associated with the original term request from TermGenie and were not removed when the term did not make the cut at the gatekeeper stage of term approval. In 2015 we did a programmatic change to the names of the obsolete terms adding the string obsolete to the front of the term name. It looks like the original string was retained as a synonym of the term. 

Please note that there have been occasions when a term has been obsoleted by, reassessed and then reinstated. This doesn't happen very often, but it happens. We try very hard not to do this.

I hope this helps.
