### ISSUE TITLE
Make sure new relations for Rhea alignment are documented and solidified

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#15933]
As part of the Rhea alignment project, we have created new relations to group reactants on either side of the reaction equation. We need to be sure that those relations are well-defined and documented so that ontology editors can refer to the documentation if questions arise. We should also look to see how they fit into RO and how they would chain with other valid relations.

**Comment by goodb** [comment]
This issue is tied directly to the decision about the pattern for axiomitizing the MF terms based on the rhea reactions.  As things stand today, my understanding is that the preferred pattern is the one known as ['ultra intersection' with a version and its consequences (circa June 2018) listed on the other issue](https://github.com/geneontology/go-ontology/issues/14984#issuecomment-404613355).  Below is an example of the OWL definition for GO: 'dimethylallylcistransferase activity' from RHEA:11331 reaction - 
dimethylallyl diphosphate + isopentenyl diphosphate = diphosphate + neryl diphosphate

This pattern requires the **new** Object Property **'has_directed_reaction'** and the **new** Data Property **'has_stoichiometry'**.  It re-uses existing RO Object Properties: has_input, has_output, has_member.  And it adds one new class called 'SubstanceSet'.  (For more information about how we arrived at this structure, see [this thread](https://github.com/liveontologies/elk-reasoner/issues/54).  The challenge is to represent the reactions as being bi-directional while keeping the groups of reactants on either side intact without using the UnionOf construct).

```
'catalytic activity'
 and (has_directed_reaction some 
    ((('has input' some 
        (SubstanceSet
         and (('has member' some 
            ('isopentenyl diphosphate(3-)'
             and (has_stoichiometry value "1"^^xsd:string)))
         and ('has member' some 
            ('prenyl diphosphate(3-)'
             and (has_stoichiometry value "1"^^xsd:string)))))))
     and (('has output' some 
        (SubstanceSet
         and (('has member' some 
            ('diphosphate(3-)'
             and (has_stoichiometry value "1"^^xsd:string)))
         and ('has member' some 
            ('neryl diphosphate(3-)'
             and (has_stoichiometry value "1"^^xsd:string)))))))))
 and (has_directed_reaction some 
    ((('has input' some 
        (SubstanceSet
         and (('has member' some 
            ('diphosphate(3-)'
             and (has_stoichiometry value "1"^^xsd:string)))
         and ('has member' some 
            ('neryl diphosphate(3-)'
             and (has_stoichiometry value "1"^^xsd:string)))))))
     and (('has output' some 
        (SubstanceSet
         and (('has member' some 
            ('isopentenyl diphosphate(3-)'
             and (has_stoichiometry value "1"^^xsd:string)))
         and ('has member' some 
            ('prenyl diphosphate(3-)'
             and (has_stoichiometry value "1"^^xsd:string)))))))))
```

Note that the other pattern that is still on the table (the use of [General Class Inclusion axioms](url
https://github.com/geneontology/go-ontology/issues/14984#issuecomment-403959765) for instance classification) only re-uses has_input and has_output and does not require any new relations.

**Comment by balhoff** [comment]
At this point I think the only new term we will need is a data property for `has_stoichiometry`. Should we just give this a GO id?

**Comment by ValWood** [comment]
@pgaudet  is this one still in date?

**Comment by pgaudet** [comment]
We have not implemented this.
