### ISSUE TITLE
MP sperm motility missing parents

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15945]
GO:0097722    sperm motility
should be is_a 

GO:0060285    cilium-dependent cell motility

it might be different? but  cilium-dependent cell motility has
microtubule-based flagellar cell motility | exact

![sperm motility](https://user-images.githubusercontent.com/7359272/41833964-5f662586-784a-11e8-8727-1c2d24b17f09.jpg)

**Comment by ValWood** [comment]
"sperm motility" also missing
need GO:0032501 multicellular organismal process parent

**Comment by ukemi** [comment]
Nope. C. elegans sperm are amebae.

**Comment by ValWood** [comment]
OK
There is no flagellum in C. elegans sperm, only a foot (the cone), which sperm use the foot to crawl onto oocytes in amoebae fashion. 

But in this case it would be better to make "sperm motility" not for direct annotation, and 
force annotation to 
GO:0030317   flagellated sperm motility
or
GO:0097723    amoeboid sperm motility

also the multicellular organism parent should still be added ( or is the C. elegans sperm classed as an organism???)

**Comment by cmungall** [comment]
+1

Also would be good if we could better auto-classify here. cilium-dependent cell motility and flagellated sperm motility should have OWL definitions

**Comment by ukemi** [comment]
Yes, but that may be trickier than it appears on the surface. Fibroblasts have a cilium, but they are ameboid. Maybe we could do it somehow using motile cilium.

**Comment by krchristie** [comment]
Seems like a good idea to make the term "sperm motility" not for direct annotation.

If we are going to make a logical definition for flagellated sperm motility, it would clearly need to  specifically utilize the "motile cilium" term since, as David pointed out, the term "cilium" does not necessarily correspond to a motile structure.

@cmungall - By "OWL definition", do you mean equivalence axiom? If you mean something else, please clarify.

**Comment by cmungall** [comment]
Yes, OWL def = equivalence axiom between named class and class expression, sorry for the terminology

we have this at the moment, I don't think it's right:

```
id: GO:0030317
name: flagellated sperm motility
intersection_of: GO:0006928 ! movement of cell or subcellular component
intersection_of: has_input CL:0000019 ! sperm
```

should be

 * flagellated sperm motility = sperm motility and has_part some 'sperm flagellum movement'
 * cilium-dependent cell motility = cell motility and has_part some 'cilium movement'

**Comment by ukemi** [comment]
+1
The existing def must have been made by someone who never worked on nematodes.

**Comment by krchristie** [comment]
The term for 'sperm motility' was created by Paola and myself when we also created the term for 'amoeboid sperm motility' term to make the distinction between that and 'flagellated sperm motility'. If I recall correctly, the existing term for flagellated sperm motility was originally named just 'sperm motility', but was defined such that it was clearly flagellum-dependent, so we opted to keep it as the specific term, consistent with its definition. 

My recollection of the logical def is that the existing CL term for 'sperm' specifies a flagellated sperm, so it seemed sufficient for this definition. I think we discussed whether the CL term for sperm should be changed, but I have vague recollections that we were told CL focuses on mammalian cells, so we didn't attempt to get that changed.

Here is the CL term for 'sperm':
http://bioportal.bioontology.org/ontologies/CL?p=classes&conceptid=CL%3A0000019

**Comment by pgaudet** [comment]
sperm motility is under 'reproductive process'. 

@ValWood Does anything else need to be done for this ticket ? 

Thanks, Pascale

**Comment by ValWood** [comment]
does  
GO:0030317  flagellated sperm motility 
still need
GO:0060285 cilium-dependent cell motility

I got a bit confused in the comments.
Also should "sperm motility" be mad not for direct annotation now we have the child term.

**Comment by krchristie** [comment]
@ValWood - I'm not sure what you mean by this comment:

> does
> GO:0030317 flagellated sperm motility
> still need
> GO:0060285 cilium-dependent cell motility
> I got a bit confused in the comments.

but these two terms are definitely not equivalent. Amongst other things, not all ciliated motile eukaryotic cells are sperm. There are many different types of motile ciliated protozoa.

I think it would be true to add this relationship:
 
-- GO:0060285 cilium-dependent cell motility
--- is_a GO:0030317 flagellated sperm motility

because any type of "flagellated sperm motility" is a type of "cilium-dependent cell motility". I can't however think of a good reason to have a term specific for cilium-dependent motility of non-sperm cells though, since the parent term seems sufficient to annotate the cilium-dependent motility of protists. I'm not sure if it would be a problem to have "flagellated sperm motility" be the sole child of "cilium-dependent cell motility". Thoughts? @ukemi  

> Also should "sperm motility" be mad not for direct annotation now we have the child term.

The term 'sperm motility' is already in the **gocheck_do_not_annotate** subset.

@pgaudet - You can give this ticket back to me if you like.

**Comment by pgaudet** [comment]
Yes, thanks @krchristie !

**Comment by ValWood** [comment]
Hi Karen, sorry, I missed a word!

GO:0030317 flagellated sperm motility
still need
GO:0060285 cilium-dependent cell motility
*parent*

cheers
Val
