### ISSUE TITLE
MP missing parent in "synapse" branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15944]
need  GO:0032501    multicellular organismal process parent

GO:0050808	biological_process	synapse organization
GO:0097120	biological_process	receptor localization to synapse

**Comment by ukemi** [comment]
part_of? Seems like these are cellular processes.

**Comment by BarbaraCzub** [comment]
'GO:0032501 multicellular organismal process' has no part_of child terms at all atm. But in these cases, yes, I think it would have to be part_of. But surely this would be true for all cellular processes, wouldn't it?

**Comment by ukemi** [comment]
Not all, but this may lead to a quagmire.

**Comment by ukemi** [comment]
I fear that this will always be incomplete.

**Comment by ukemi** [comment]
This points out the continuing issue concerning cellular processes, organismal processes and multicellular organismal processes. Multicellular organismal processes are supposed to be ones that occur at the level of a multicellular organism, however fuzzy that expression is. I think the above processes would be considered to be at the level of a cell, cellular processes.

**Comment by BarbaraCzub** [comment]
'Synapse organisation' certainly involves forming a junction between two cells, so I suppose this would qualify as 'multicellular'.

**Comment by BarbaraCzub** [comment]
But 'receptor localization to synapse' will only occur within one cell, even though the synapse as a structure will consist of parts of two cells...

**Comment by ukemi** [comment]
Yes, but would a biologist consider it cellular? That's where the concepts get a bit fuzzy. Cell-cell signaling is a cellular process.

**Comment by BarbaraCzub** [comment]
Well, I am happy to leave this parentage out, as I agree this is fuzzy.

**Comment by BarbaraCzub** [comment]
But looking at the ontology now, I noticed that 'receptor localization to synapse' is not even a descendant of 'cellular process'. It appears there is a missing relationship between 'cellular process' and 'cellular localization' (a grandparent of 'receptor localization to synapse'). 
![screen shot 2018-06-25 at 15 00 07](https://user-images.githubusercontent.com/16541096/41854593-7f4f9998-7888-11e8-9435-d682535169d5.png)
So, I'll add this missing relationship, unless there is a reason why it was left out?

**Comment by ukemi** [comment]
I think this might be due to the fact that in this case, the term refers to a process that localizes something to a cell or within a cell. If we assume that the localization process is always done at the level of a cell then this is a cellular process, but we would need to check all of the children.

**Comment by cmungall** [comment]
Related unresolved ticket from Val #12796 "cellular processes missing cellular process parent"

My proposal to radically simplify, and to remove the X / cellular-X shadowing:

https://gist.github.com/cmungall/4ed28123c3db832a7d99cbdd8e8a5920

**Comment by ukemi** [comment]
Yes. I remember your proposal, we just need the resources to carry it out.

**Comment by BarbaraCzub** [comment]
There appears to be one child of 'cellular localization' that does not exactly 'fit' the 'cellular process' i.e. 'the multi-organism cellular localization'. The definition is rather vague ('A cellular localization which involves another organism.'), and although most of the manual annotations involve viruses (so not cells), there are a two, where the multi-organism process involves a bacterium, so another cell. But this would be fine, because 'cellular process' is defined as: 'Any process that is carried out at the cellular level, _but not necessarily restricted to a single cell_.' So, I think 'cellular localization' should be a child of 'cellular process'. (After all there is the 'GO:0051179 localization' GO term for 'non-cellular' localization processes).

**Comment by ValWood** [comment]
OK, I'm not so worried about this.  The proposal sounds good. This only arose because these genes were not slimming with our detailed cellular processes, and a catch-all for  "multicellular organismal processes, which I'm not so interested in but I have to acknowledge;)

We can just include the synapse organization term. This makes sense. I think I was getting a bit confused anyway.

**Comment by BarbaraCzub** [comment]
Hi @ValWood I'm not convinced about making 'synapse organization' a part_of 'multicellular organismal processes' after all, because as @ukemi pointed out a 'cellular process' does not have to be limited to just one cell (e.g. 'Cell-cell signaling is a cellular process.'). And my impression from the existing child terms of 'multicellular organismal process' is that these process terms tend to involve whole organs, or tissues (e.g. 'organ growth', 'muscle attachment', 'keratinization') rather than individual cells. So, if this is not a 'must', I'll leave this, as it is.

**Comment by ValWood** [comment]
> And my impression from the existing child terms of 'multicellular organismal process' 

Yes you are right!
I was having a brain fart.

**Comment by pgaudet** [comment]
I'd like a clarification please, @ukemi : 
You write that 'Multicellular organismal processes are supposed to be ones that occur at the level of a multicellular organism' and also, the definition of 'multicellular organismal process' is 'Any biological process, occurring at the level of a multicellular organism, pertinent to its function.' 

The was I understood this is that any process (even cellular) that occurs *in* a multicellular organism was a 'multicellular organismal process'. If that's not the case (ie, if the 'organism' has nothing to do with it), shouldn't we rename the term 'multi-cellular process'? 

Thanks in advance for your help ! 

Pascale

**Comment by ukemi** [comment]
The original intent really meant 'at the level of', so the process is carried out by a 'whole' multicellular organism.
