### ISSUE TITLE
taxon restriction  "plant organ formation"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#15969]
"plant organ formation"
https://www.ebi.ac.uk/QuickGO/term/GO:1905393

never in metazoa
never in fungi
only in plants

**Comment by krchristie** [comment]
I have added this taxon restriction:
`only_in_taxon some Viridiplantae`
to the suggested term. 

@tberardini - I picked the most general plant taxon that we appear to be using in GO, but please let me know if something else is more appropriate.

However, it seems redundant to add a bunch of never in restrictions, when we are adding an only in restriction. In addition, if we are going to add never in restrictions, these don't seem to cover the full range since bacteria are also not plants. So, first question, do we need to add never in restrictions, when we have already added an only in restriction that seems sufficient to fully describe appropriate usage of this term? @cmungall @ukemi

**Comment by ValWood** [comment]
Yes I wasn't sure whether we  would add explicit 'never in'

I added belt and braces  because of:
https://github.com/owlcollab/owltools/issues/165

**Comment by tberardini** [comment]
only_in_taxon some Viridiplantae

is appropriate, in my opinion.

**Comment by krchristie** [comment]
@tberardini - Thanks for confirming appropriate taxon 👍 

We discussed this during 7/2/18 ontology editors call. The conclusion is that in this case using only the only in restriction is sufficient because the never in constraints you suggested are redundant and do not add additional info. 

However, if there is a situation where you wanted to say something like only in plants, but not in this specific subgroup, then it would be appropriate to add never in constraints as well as the only in constraint.

I am closing this as I have already added the only in constraint that we agreed at today's call was the only taxon constraint needed.
