### ISSUE TITLE
Should 'transport vesicle' be restricted to 'constitutive secretory pathway'?

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/go-ontology#15989]
Re: comments in : https://github.com/geneontology/go-ontology/issues/14540

**Comment by ValWood** [comment]
No. Transport vesicles   are involved in all vesicle mediated transport processes.

Also I'm not really sure we should have the term "constitutive secretory pathway"

(secretory pathway is broader than exocytosis so it is mispositioned).

Terms under "secretion by cell" have always been a problem, because it restricts "secretion by cell" to the exocytosis part of the pathway.

**Comment by ValWood** [comment]
closing?
