### ISSUE TITLE
negative and postive regulation required for GO:1905634

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16012]
GO:1905634 | regulation of protein localization to chromatin

tks

**Comment by pgaudet** [comment]
reference ?

**Comment by ValWood** [comment]
I didn't think we needed another since we have the regulation term already ;)  but I'm curating


PMID:29899453
Title | A Cdk9-PP1 switch regulates the elongation-termination transition of RNA polymerase II.
Authors | Parua PK, Booth GT, Sansó M, Benjamin B, Tanny JC, Lis JT, Fisher RP

**Comment by krchristie** [comment]
@ValWood - If by this:

> I didn't think we needed another since we have the regulation term already ;) but I'm curating

you meant you didn't think you need to specify the reference because it was already on the regulation term, please ALWAYS specify the reference so that the editor who works on your ticket doesn't have to guess what is appropriate. It makes it easier & faster for us to do your ticket. If Pascale hadn't already asked for the reference, I wouldn't have done this ticket today.
