### ISSUE TITLE
OTR: Typo in term name GO:0034897

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#16051]
GO:0034897 4-(1-ethyl-1,4-dimethyl-pentyl)phenol monoxygenase activity

I think it should be monooxygenase not monoxygenase. This is consistent with other child terms of GO:0016705.

Also, the cross-reference to EC on GO:0034897 and GO:0016705 (and maybe others) goes to a non-existent page (1.14). Should this instead be 1.14.-.- (https://enzyme.expasy.org/EC/1.14.-.-) ?

Thanks.

**Comment by hdrabkin** [comment]
Hi 
I can fix the typo.
At this time, due to the way the EC2GO file is generated, we have removed 3 digit ecs with a -.- from xrefs because if they were assigned to a specific enzyme, the EC2GO file got the mapping of GO:0034897 would get all of the enzymes that fell under EC 1.14
So all of the enzymes on https://enzyme.expasy.org/EC/1.14.-.- would map go  GO:0034897

In fact, you cannot add a 3 digit with -.- ; Travis Checks will flag it. 
I am in the process of removing all three digit ecs from anything other than grouping terms where they make more sense, and replacing them with a 4 digit EC if available. 
Does this make sense?

**Comment by rachhuntley** [comment]
Yes, I think so. Thanks Harold.

**Comment by hdrabkin** [comment]
Hi again
I may have garbled this a bit, but also when we had EC:x.x.-.-
MGI (and Zfin that I know of) pick up UniProt records to map to our genes. For these we get interpro domains and EC numbers. . If the UniProt record has an EC:x.x.-.- (which it might if either there as no better EC (4 digit), or not fully curated (ie, Trembl records) , then what happens is that when we then run an EC2GO script, a gene was getting any GO id that had an EC that mapped under the EC:x.x.-.-; this resulted in many incorrect GO assignments based on EC number.
I can fish out the original ticket, which might have actually be an old sourceforge thread.

**Comment by hdrabkin** [comment]
Fixed misspelling and removed 3 digit EC xref
