### ISSUE TITLE
GOrel.obo subset edits

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/go-ontology#16052]
The three relations regulates_expression_of, regulates_translation_of and regulates_transcription_of appear to have been assigned the wrong AE subset, i.e. subset: AE_sequence_feature. It should instead be subset: AE_sequence_or_complex as they are used in conjunction with gene, transcript or protein identifiers.

Also, the property_value: local_range for each of these relations only contains SO:0000704 (gene), so I think this should be expanded as follows:

property_value: local_range PR:000000001 (protein) SO:0000673 (transcript) SO:0000704 (gene)

Finally, the range for each of the relations is SO:0000704, but I'm wondering whether this should be BFO:0000002 to be consistent with has_regulation_target?

Thanks.

**Comment by ukemi** [comment]
Chris and Jim, what is the future of this file? Will these be kept separate or merged into RO?

**Comment by cmungall** [comment]
If it's specific to AEs then these will end up going away

If they are generally useful, e.g. as inferred relationships from a GO-CAM then there is a case for adding to RO.

RO doesn't have local_range or local_domain, these aren't used in noctua

**Comment by ukemi** [comment]
So what do we need to do to resolve this ticket?

**Comment by RLovering** [comment]
@vanaukenk 
Hi Kimberly I just noticed that you recently edited the GOREL file https://github.com/geneontology/go-ontology/pull/15947 please could you implement the changes Rachael has requested at the top of this ticket.
Thanks
Ruth

**Comment by RLovering** [comment]
Please could the GOREL file future be included on the GOC agenda?

**Comment by tonysawfordebi** [comment]
@vanaukenk I do make extensive use of the local_domain and local_range information from gorel.obo in order to validate annotation extensions, not just in P2G, but also those we import from other groups. Indeed, **all** tools that create extensions **should** use this information in order to determine whether what a curator has supplied as an extension is plausible or not.

Now, I know that Noctua doesn't deal in annotation extensions per se (except when it exports to GPAD), but where does it get its rules from about what relations are valid where, and what they can refer to? Or does it allow users to use any relation anywhere with any target (i.e., no domain/range checking)?

**Comment by rachhuntley** [comment]
@vanaukenk Yes Kimberley, we've been meaning to do this for a while. I think it would make a good template. I will look out for a suitable paper (not too complicated).

**Comment by balhoff** [comment]
@tonysawfordebi the Noctua reasoner uses domains and ranges that are defined in RO. It doesn't currently use the `local_range` annotations for anything. One issue for the Noctua reasoner is that the values for `local_range` that I have seen are unions, which don't do much in the logic employed by that reasoner. They could potentially be applied as some kind of closed-world query in a post-reasoning QC step.

**Comment by tonysawfordebi** [comment]
@balhoff OK, I see that. But I think that we need to find a way to allow the GO-CAM and classic annotation worlds to peacefully co-exist, and I don't think that deprecating gorel.obo is the way to bring that about...
