### ISSUE TITLE
Inconsistencies TFIIx-class transcription factor binding

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16061]
(Splitting issues reported in #14916) 

- There are 9 terms with the pattern: TFIIx-class transcription factor binding

'TFIIA-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001092>
'TFIIB-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001093>
'TFIID-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001094>
'TFIIE-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001095>
'TFIIF-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001096>
'TFIIH-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001097>
'TFIIIA-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001155>
'TFIIIB-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001154>
'TFIIIC-class transcription factor binding' <http://purl.obolibrary.org/obo/GO_0001156>

However under CC, some of these are complexes: 
'transcription factor TFIIA complex'
'transcription factor TFIIE complex'
'transcription factor TFIID complex'
'transcription factor TFIIF complex'

1. I think the corresponding MF binding should be renamed 'transcription factor TFIIA complex binding' 

2. I need to check if others are omissions of if they are single subunits, in which case they should be obsoleted or merged into a parent class. 

@bmeldal 
@krchristie 
@ValWood @RLovering 

Your input would be much appreciated. 

Pascale

**Comment by krchristie** [comment]
My recollection is that not all of these are complexes. TFIIB for example is a single gene product. However in mammalian species there are multiple variants of TFIIB that differ in the developmental and cell type regulation.

**Comment by bmeldal** [comment]
A quick scan through Complex Portal and Uniprot suggests:

TFIIA - complex
TFIIB - monomer across all taxa
TFIID - complex
TFIIE - complex
TFIIF - complex
TFIIH - complex
TFIIK - subcomplex of TFIIH (curated in yeast but with comment that it may not have a unique function when not part of H)

TFIIIA - monomer across all taxa
TFIIIB - complex
TFIIIC - complex

All yeast ones are curated in CP and for human/mouse we have A, D and F so far.

That means the binding terms are correct as the TFs exist and the term only says TF, not TF complex.

The outright complex terms also exist in GO, I don't know why you didn't list TFIIH, TFIIIB & TFIIIC.

There's also GO:0070264 transcription factor TFIIIE complex but I've not come across it before, it has no hits in UniProt and no annotations in GO. Created in 2009 and has a PMID for yeast but Sandra didn't curate it in the CP which means there is no strong evidence for it's unique existence.

**Comment:**
TFIIH:
has a "core" (GO:0000439) and "holo-" (GO:0005675 TFIIH + TFIIK [GO:0070985]) complex term in GO. "core" shares (in yeast) 7 components with GO:0000112 nucleotide-excision repair factor 3 complex but both need additional, unique subunits to make a respective functional TF or excision repair complex. "core" is a non-functional subcomplex.

Since "core TFIIH" is non-functional (and maybe doesn't assemble on it's own - I haven't dug that deep yet) it's questionable if it should be a term in it's own right.
