### ISSUE TITLE
GO:0072588     box H/ACA RNP complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16085]
GO:0072588     box H/ACA RNP complex

I have used this historically for the  "box H/ACA RNP complex"

I.e the   pseudouridylate synthase and snRNA containing complex.

At some point it changed meaning and the  pseudouridylase complex is now represented by 

GO:0031429    box H/ACA snoRNP complex
box H/ACA snoRNP pseudouridylase complex

it took me a while to figure this out, so can 
the synonym "box H/ACA snoRNP pseudouridylase complex" be made the term name.

Also for all these terms, the nomenclature used  is yeast  nomenclature not human. Human used Yeast nomenclature. These complexes were first identified in yeast. You can call it universal nomenclature  if you like.... but not human

**Comment by ValWood** [comment]
Also, the def doesn't mention pseudouridylate synthase the activity it performs...

the def is:
A box H/ACA RNP complex that is located in the nucleolus.

**Comment by hdrabkin** [comment]
@krchristie  can you comment on this; you are more up on this I think

**Comment by krchristie** [comment]
Actually, based on the term creation dates (and I think I've even looked at the older versions of the GO:0031429 term in an older file when I was researching this ticket: https://github.com/geneontology/go-ontology/issues/11686) the term: `GO:0031429 box H/ACA snoRNP complex` is the original term, which originally was appropriate for annotation of ANY box H/ACA snoRNP complex. 

In February 2011, these two terms were created
`GO:0072588 box H/ACA RNP complex`
`GO:0072589 box H/ACA scaRNP complex`

Several years ater, in Sept 2015, this term was created:
`GO:0090661 box H/ACA telomerase RNP complex`

It may have been a mistake to make the `GO:0031429 box H/ACA snoRNP complex` specific to the nucleolar complexes because I think it may have made some of the original annotations incorrect. However, it's been so long now that I think it needs to stay as what it is now.

However, it would be incorrect to change the name of `GO:0031429 box H/ACA snoRNP complex` because not ALL of the nucleolar box H/ACA snoRNP complexes are pseudouridylation complexes. Some are RNA cleavage guides that do not guide any pseudouridylation at all. 

In the box C/D ticket I spent quite a bit of time looking into (https://github.com/geneontology/go-ontology/issues/11686), I was proposing a structure like this. A similar structure would be equally appropriate for the box H/ACA RNP complexes.
-- box C/D RNP complex (GO:new)
--- box C/D methylation guide RNP complex (GO:new) [for Archaea, euk of unknown location]
---- box C/D methylation guide scaRNP complex (GO:new)
---- box C/D methylation guide snoRNP complex (GO:0031428)
--- box C/D pre-rRNA cleavage RNP complex (GO:new) [appropriate for U3, U8, U13 RNPs]

**_Term Stanzas:_**

**[Term]**
**id**: GO:0031429
**name**: box H/ACA snoRNP complex
**namespace**: cellular_component
**def**: "A box H/ACA RNP complex that is located in the nucleolus." [GOC:vw, ISBN:0879695897, PMID:17284456, PMID:20227365]
**synonym**: "box H/ACA small nucleolar ribonucleoprotein complex" EXACT [GOC:cjm]
**synonym**: "box H/ACA snoRNP pseudouridylase complex" EXACT [GOC:mah, GOC:vw, PMID:17284456]
**is_a**: GO:0044452 ! nucleolar part
**is_a:** GO:0072588 ! box H/ACA RNP complex
**relationship**: capable_of GO:0009982 ! pseudouridine synthase activity

**[Term]**
**id**: GO:0072588
**name**: box H/ACA RNP complex
**namespace**: cellular_component
**def**: "A ribonucleoprotein complex that contains an RNA of the box H/ACA type and the four core proteins dyskerin, NOP10, NHP2, and GAR1 (human protein nomenclature). RNA pseudouridylation (isomerization of uridine to pseudouridine) is the major, and most likely the ancestral, function of H/ACA RNPs. Pseudouridylation targets include both large and small ribosomal RNAs (rRNAs), and small nuclear RNA (U2 snRNA). In addition to these catalytic H/ACA RNPs, a less abundant but more diverse class of structural H/ACA RNPs exists, which does not have pseudouridylation activity. These include the vertebrate telomerase RNP complex." [GOC:BHF, GOC:BHF_telomerase, GOC:jbu, GOC:mah, GOC:vw, PMID:17284456, PMID:20227365]
**synonym**: "box H/ACA snoRNP pseudouridylase complex" RELATED [GOC:mah]
**synonym**: "sRNP complex" NARROW [GOC:mah, PMID:17284456, PMID:20227365]
**is_a**: GO:0005732 ! small nucleolar ribonucleoprotein complex
**created_by**: midori
**creation_date**: 2011-02-10T01:43:37Z

**[Term]**
**id**: GO:0072589
**name**: box H/ACA scaRNP complex
**namespace**: cellular_component
**def**: "A box H/ACA RNP complex that is located in the Cajal body of the nucleoplasm. In highereukaryotes, box H/ACA RNP located in Cajal bodies mediate pseudouridylation of spliceosomal snRNAs." [GOC:mah, PMID:17284456, PMID:20227365]
**synonym**: "nucleoplasmic box H/ACA RNP pseudouridylase complex" EXACT [GOC:mah, GOC:vw, PMID:20227365]
**is_a**: GO:0044451 ! nucleoplasm part
**is_a**: GO:0072588 ! box H/ACA RNP complex
**relationship**: capable_of GO:0009982 ! pseudouridine synthase activity
**relationship**: part_of GO:0015030 ! Cajal body
**created_by**: midori
**creation_date**: 2011-02-10T02:47:17Z

**[Term]**
**id**: GO:0090661
**name**: box H/ACA telomerase RNP complex
**namespace**: cellular_component
**def**: "A box H/ACA ribonucleoprotein complex that contains the RNA component of vertebrate
telomerase, the enzyme essential for the replication of chromosome termini in most eukaryotes. This ribonucleoprotein complex is a structural box H/ACA RNP, which does not have the catalytic pseudouridylation function shared by the majority of H/ACA RNPs present in the cell." [GOC:BHF, GOC:BHF_telomere, GOC:jbu, PMID:22527283]
**is_a**: GO:0072588 ! box H/ACA RNP complex
**relationship**: capable_of_part_of GO:0032212 ! positive regulation of telomere maintenance via telomerase
**relationship**: part_of GO:0005697 ! telomerase holoenzyme complex
**created_by**: tanyaberardini
**creation_date**: 2015-09-21T14:46:16Z

**Comment by krchristie** [comment]
I am going to close this ticket because I think this suggestion can not be implemented as is, and this ticket is somewhat redundant with other previously opened tickets.

If you have any other comments on this, please add them to one of the other open tickets:
- your previous ticket:  GO:0072588 box H/ACA RNP complex #15918 
- my box C/D ticket:  NTR & issues with GO:0031428 "box C/D snoRNP complex" #11686
