### ISSUE TITLE
Rename occluding junction to tight junction

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#16125]
At KPMP meeting with @addiehl 

We think the label should be changed, keep occluding as syn

Also: add taxon constraint to septate junction, text def says inverts

```
id: GO:0005918
name: septate junction
namespace: cellular_component
def: "A cell-cell junction that forms a continuous band around each cell in an epithelium; within the septate junction the membranes of adjacent cells maintain a constant distance of approximately 15 nm; found in invertebrates." [ISBN:0815332181, PMID:11700298]
synonym: "septate desmosome" RELATED []
xref: NIF_Subcellular:sao427941916
is_a: GO:0070160 ! occluding junction
relationship: part_of GO:0043296 ! apical junction complex
```

**Comment by krchristie** [comment]
In addition to this term:
GO:0070160 - occluding junction

I also made the same changes in these terms:
GO:1905071 - occluding junction disassembly
GO:1905073 - regulation of occluding junction disassembly
GO:1905074 - negative regulation of occluding junction disassembly
GO:1905075 - positive regulation of occluding junction disassembly
GO:0098864 - modification by symbiont of host occluding cell-cell junction

I changed the word "occluding" to "tight" in term names, definitions, and also made the reverse change in some synonyms when necessary to avoid having a synonym that duplicated that term name.

**Comment by krchristie** [comment]
For some reason, the link from the pull request didn't show up here, so here it is:
https://github.com/geneontology/go-ontology/pull/16172/files

**Comment by krchristie** [comment]
While it is true that the definition used the word invertebrates, the paper cited in the definition only talked about Drosophila:
> Tepass U, Tanentzapf G, Ward R, Fehon R. Epithelial cell polarity and cell junctions in Drosophila. Annu Rev Genet. 2001;35:747-84. Review. PubMed PMID:11700298.

 I could not identify a taxon that corresponded to "invertebrates" and also looked at this Wiki page for "invertebrate", https://en.wikipedia.org/wiki/Invertebrate, which says this:
> Some of the so-called invertebrates, such as the Tunicata and Cephalochordata are more closely related to the vertebrates than to other invertebrates. This makes the invertebrates paraphyletic, so the term has little meaning in taxonomy. 

Then the Wiki page for septate junctions (https://en.wikipedia.org/wiki/Septate_junctions) also says that says `Septate junctions are intercellular junctions found in invertebrate epithelial cells`, but then cites only a single reference that only talks about tight junctions in insects: 
> Matter K, Balda MS. Signalling to and from tight junctions. Nat Rev Mol Cell Biol. 2003 Mar;4(3):225-36. Review. PubMed PMID: 12612641.

I also checked if septate junctions were broader than just insects, and checked for if they are present in Arthropods, resulting in these two papers:

> 1: Furuse M, Izumi Y. Molecular dissection of smooth septate junctions: understanding their roles in arthropod physiology. Ann N Y Acad Sci. 2017 Jun;1397(1):17-24. doi: 10.1111/nyas.13366. Review. PubMed PMID: 28636800.
> 2: Noirot-Timothee C, Noirot C. Septate and scalariform junctions in arthropods.  Int Rev Cytol. 1980;63:97-140. PubMed PMID: 20795303.

Therefore, I have changed the definition to specify arthropods, cited all 3 of the additional references I cited, and added the constraint:
`only_in_taxon some Arthropoda`

If you feel the taxon constraint should be otherwise, please reopen the ticket, indicate exactly which NCBITaxon ID you think is more appropriate, and suggest a corresponding modification to the definition.

**Comment by RLovering** [comment]
This is great, and means the CC ontology is reflected partially in the BP ontology.

But it can be difficult to decide if a protein is involved (or regulating) tricellular or bicellular junction assembly therefore please could you also create the following parent term:

New term: Tight junction assembly
is_a Child terms
>GO:1904274 tricellular tight junction assembly 
>GO:0070830 bicellular tight junction assembly

And New regulation terms for New term: Tight junction assembly
with appropriate placement of the child terms:

GO:2000810                regulation of bicellular tight junction assembly 
GO:1903347                negative regulation of bicellular tight junction assembly 
GO:1903348                positive regulation of bicellular tight junction assembly

Thanks

Ruth

**Comment by krchristie** [comment]
@RLovering - For work tracking purposes, instead of reopening this ticket, please create a new ticket with your new requests. I am going to leave that for you to do so that it has your name on in instead of mine.
