### ISSUE TITLE
New parent term (tight junction organization, tight junction assembly)

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16187]
Hi Karen
 
to partially mirror other cell junction terms (eg  GO:0002934 desmosome organization)
please could you create the following terms and structure:

 GO:0045216 cell-cell junction organization
> Is_a Child New term: tight junction organization
>> is a child term GO:1905071 tight junction disassembly (previously occluding junction disassembly)
>> is_a Child term New term: tight junction assembly
>>> is_a Child term GO:1904274 tricellular tight junction assembly (remove cell-cell assembly parent)
>>> is_a Child term GO:0070830 bicellular tight junction assembly (remove cell-cell assembly parent)

>  GO:0007043 cell-cell junction assembly
>> is_a Child term New term: tight junction assembly

Definitions:
New term: tight junction organization
A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a cell-cell junction. A tight junction seals cells together in an epithelium in a way that prevents even small molecules from leaking from one side of the sheet to the other.  

New term: tight junction assembly
The aggregation, arrangement and bonding together of a set of components to form a tight junction. A tight junction seals cells together in an epithelium in a way that prevents even small molecules from leaking from one side of the sheet to the other.  

Exact Synonyms:
New term: tight junction organization
occluding cell junction organization
occluding junction organization

New term: tight junction assembly
occluding cell junction assembly
occluding junction assembly

And New positive reg, negative reg and regulation terms for both new terms (sorry there seem to be a lot of missing terms, but I do think these are needed as it is not always possible to know if the regulation is assembly or disassembly: 

GO:0034330 cell junction organization
> regulation child New term: regulation of cell junction organization

GO:0045216 cell-cell junction organization
> is a regulation child New term: regulation of cell-cell junction organization
>> is a child New term: positive regulation of cell-cell junction organization
>> is a child New term: negative regulation of cell-cell junction organization

 GO:0045216 cell-cell junction organization
>New term: tight junction organization
>>regulation New term: regulation of tight junction organization

GO:0007043 cell-cell junction assembly
> Is_a child New term: tight junction assembly
>> is a child New term: regulation of tight junction assembly

GO:0051128 regulation of cellular component organization
> is a child New term: regulation of cell junction organization
>>is a child GO:1903391 regulation of adherens junction organization
>> is a child GO:1901888 regulation of cell junction assembly
>> is a child New term: regulation of cell junction disassembly

GO:0051128 regulation of cellular component organization
> is a child New term: regulation of cell junction organization
>> is a child New term: regulation of cell-cell junction organization
>>> is a child New term: regulation of cell-cell junction assembly
>>> is a child New term: regulation of cell-cell junction disassembly
>>> Is_a child New term: regulation of tight junction organization

GO:0051128 regulation of cellular component organization
> is a child New term: regulation of cell junction organization
>> is a child New term: regulation of cell-cell junction organization
>>> Is_a child New term: regulation of tight junction organization
>>>> is a child GO:1905073: regulation of tight junction disassembly (previously regulation of occluding junction disassembly)
>>>> is a child New term: regulation of tight junction assembly
>>>>> is a child GO:2000810 regulation of bicellular tight junction assembly
>>>>>> is a childGO:1903347 negative regulation of bicellular tight junction assembly
>>>>>> is a childGO:1903348 positive regulation of bicellular tight junction assembly

I have a feeling I have probably missed some other junction assembly/disassembly/organization terms that could be better placed within this ontology. Sorry the above is a bit repetitive I was trying to make it less confusing :(

Sorry for editing the previous ticket #16125 

Thanks

Ruth

**Comment by krchristie** [comment]
No worries @RLovering Thanks for putting this in as a new ticket. It helps manage the work flow and accounting a bit better when it goes in as a new ticket.

**Comment by krchristie** [comment]
@RLovering - I've put in the two non-regulation terms you requested (stanzas below) to fill out the tight junction terms, and the logical defs I put in do some nice organization of existing assembly and disassembly terms of the subtypes of tight junctions. If I missed something let me know.

However, before I instantiate so many regulation terms, let me ask if you really need them currently for annotation. If you don't have current need, I'm reluctant to put them in now. If you do have a current need, please just list the non-regulation terms for which you need the regulation terms, indicating whether you need general, positive, and/or negative terms (or just all 3). I'm not really following which terms you want out of your hierarchy structure above and it's not really necessary to indicate parentage for regulation terms since we put them in using logical defs to place them.

Also, for future reference, I find it easier to get everything you want in a single term if you list all the things for a single term together, pretty much like they come out in the obo format diffs like this one here:

 [Term]
+id: GO:0120192
+name: tight junction assembly
+namespace: biological_process
+def: "A cellular process that results in the aggregation, arrangement and bonding together of a set of components to form a tight junction. A tight junction seals cells together in an epithelium in a way that prevents even small molecules from leaking from one side of the sheet to the other." [GOC:rl]
+synonym: "occluding cell junction assembly" EXACT [GOC:rl]
+synonym: "occluding junction assembly" EXACT [GOC:rl]
+is_a: GO:0007043 ! cell-cell junction assembly

+[Term]
+id: GO:0120193
+name: tight junction organization
+namespace: biological_process
+def: "A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a tight junction. A tight junction seals cells together in an epithelium in a way that prevents even small molecules from leaking from one side of the sheet to the other." [GOC:krc, GOC:rl]
+synonym: "occluding cell junction organization" EXACT [GOC:rl]
+synonym: "occluding junction organization" EXACT []
+is_a: GO:0045216 ! cell-cell junction organization

**Comment by RLovering** [comment]
Hi

please could I have the following regulation term:

Positive regulation of GO:0070830 bicellular tight junction assembly
For the annotation of P29317 EPHA2  PMID:27815408

I think this is the only annotation I can see I need to do, please close this ticket when this regulation term is created.

Thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering These terms already exist since 2011/2014

[Current term] GO:2000810 regulation of bicellular tight junction assembly
                         [is_a relation] GO:1903347 negative regulation of bicellular tight junction assembly
                         [is_a relation] GO:1903348 positive regulation of bicellular tight junction assembly

**Comment by RLovering** [comment]
well that is embarrassing - sorry

Ruth
