### ISSUE TITLE
Why is there both detoxification GO:0098754 and cellular detoxification GO:1990748

### ISSUE THREAD

**Issue by selewis** [geneontology/go-ontology#16189]
Well of course the answer would be because there could be detoxification at the organismal level - that would make sense.

But the siblings of cellular detoxification all appear to be defined in cellular terms.

Plus the logical partner of cellular detoxification would be system or organismal detoxification. A grouping term that would be logically parallel.

Explanation?

![image](https://user-images.githubusercontent.com/1519120/43660349-952efce6-9713-11e8-8012-53c806c4506e.png)

**Comment by cmungall** [comment]
all of the cellular-X suffer the same issues. I have a proposal to simplify, I presented at a previous GOC meeting, will post later

**Comment by pgaudet** [comment]
We should merge.

**Comment by ValWood** [comment]
This structure was to cover  tissue level detoxification processes like excretion and urination (although I don't know if these would be much used in gene level annotation, since they do not yet exist in GO so happy if you want to  merge...).  Just be aware that all of the processes I have been annotating to this are cell level.

**Comment by ValWood** [comment]
Yes I guess so !
I think there is no problem to merge (especially for yeast)

**Comment by ukemi** [comment]
Is the process of chemical detoxification through the liver and subsequent elimination of detoxified products a cellular process?

**Comment by pgaudet** [comment]
Do you have a paper ? It's hard to imagine that this occurs outside hepatocytes.

**Comment by ukemi** [comment]
PMID:25836352. See figure 6.

**Comment by pgaudet** [comment]
I don't see what you mean. Fig 6 shows the pathway at the organ level, so we cannot tell that it's cellular (or that it's not cellular). However the protein that seem to be doing the detoxification is CYP3A4, which as far as I can tell is intracellular (http://amigo.geneontology.org/amigo/gene_product/UniProtKB:P08684: no evidence that it's extracellular). 

Pascale

**Comment by ukemi** [comment]
I think we are confusing issue in this ticket. I would argue that figure 6 indicated that the process does not entirely occur at the level of a cell. It is systemic. But the next ontology developers workshop will focus on the cellular issues, so I am closing this because it should be addressed more globally.
