### ISSUE TITLE
taxon constaints laminin

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16184]
GO:0005055    laminin receptor activity
GO:0098638    laminin binding involved in cell-matrix adhesion
GO:0043256    laminin complex

never in fungi
relationship: never_in_taxon NCBITaxon:4751 ! Fungi

**Comment by krchristie** [comment]
I added this constraint to 2 of these terms, but not to this one:
- GO:0098638 laminin binding involved in cell-matrix adhesion
since it should inherit this constraint from its parent term GO:0043236 laminin binding

@ukemi - Please mark me on your spreadsheet for this ticket. It made sense to just do this since I did a bunch of other never_in_taxon NCBITaxon:4751 ! Fungi constraints this morning.
