### ISSUE TITLE
miscellaneous taxon constraint issues

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#16192]
1. Does this term really need a never_in_taxon constraint for birds, when it already has an only_in_constraint for Mammalia? Perhaps we should drop the Aves constraint and also change the definition from "in animals" to "in mammals"

> [Term]
> id: GO:0042633
> name: hair cycle
> namespace: biological_process
> def: "The cyclical phases of growth (anagen), regression (catagen), quiescence (telogen), and shedding (exogen) in the life of a hair; one of the collection or mass of filaments growing from the skin of an animal, and forming a covering for a part of the head or for any part or the whole of the body." [GOC:go_curators, PMID:12230507]
> is_a: GO:0042303 ! molting cycle
> relationship: never_in_taxon NCBITaxon:8782 {id="GOTAX:0010070"} ! Aves
> relationship: only_in_taxon NCBITaxon:40674 {id="GOTAX:0000011"} ! Mammalia

2. In this term, is this really the right taxon constraint? It seems oddly specific and is the only time in the entire go-edit.obo file that we use "NCBITaxon:9606 ! Homo sapiens" as a taxon constraint.

> GO:0090632 - N-glycolylneuraminic acid (Neu5Gc) cytidylyltransferase activity (MF)
> Def: Catalysis of the reaction: CTP + Neu5Gc   = diphosphate + CMP-Neu5Gc.
> relationship: never_in_taxon   NCBITaxon:9606 ! Homo sapiens

3. For this term, 
- @ValWood - it seems that the never_in_taxon NCBITaxon:4895 ! Schizosaccharomyces should not be needed since it is marked as only_in_taxon NCBITaxon:33208 ! Metazoa
- @vanaukenk - Then, regarding the NCBITaxon:6237 {source="GOC:kmv"} ! Caenorhabditis , I was wondering if it should be more general, perhaps NCBITaxon:6231 ! Nematoda or higher?

> [Term]
> id: GO:0042470
> name: melanosome
> namespace: cellular_component
> def: "A tissue-specific, membrane-bounded cytoplasmic organelle within which melanin pigments are synthesized and stored. Melanosomes are synthesized in melanocyte cells." [GOC:jl, PMID:11584301]
> xref: Wikipedia:Melanosome
> is_a: GO:0048770 ! pigment granule
> relationship: never_in_taxon NCBITaxon:4895 ! Schizosaccharomyces
> relationship: never_in_taxon NCBITaxon:6237 {source="GOC:kmv"} ! Caenorhabditis
> relationship: only_in_taxon NCBITaxon:33208 ! Metazoa
> relationship: part_of CL:0000148 ! melanocyte

**Comment by cmungall** [comment]
For 1:

Yes, the avian constraint is redundant

In fact hair cycle should have an axiom
 
 * subClassOf has-participant some [strand of hair](http://purl.obolibrary.org/obo/UBERON_0001037)

From which it will inherit only-in mammals.

It's not a terrible idea to have some redundancy if it's in grey areas and each axiom can be annotated with evidence (no different from gene annotations). In this case we're fairly clear that hair is a mammalian innovation though.

For 2:

it would be useful to annotate these axioms with a PMID or note

e.g. https://www.ncbi.nlm.nih.gov/pubmed/11786991

For 3:

seems we can definitely generalize this

currently GO says all melanosomes are part_of CL:melanocytes. We should probably have a broader CL constraint

But this is a tricky area terminologically since different communities use melanocyte with different degrees of generality

https://books.google.com/books?id=VKlWjdOkiMwC&pg=PA180&lpg=PA180&dq=melanocyte+invertebrate&source=bl&ots=Kh0gY3n8IR&sig=ZJR2uRDKtqXRzEzJsM_86_osxX8&hl=en&sa=X&ved=2ahUKEwiD-LXqxNTcAhWKCXwKHXKCBpwQ6AEwBXoECAUQAQ#v=onepage&q=melanocyte%20invertebrate&f=false

In fact CL uses melanocyte in a restricted fashion - it says all melanocytes derive from NC which is a strictly vertebrate innovation. So if all the imports are in place, GO melanosome *should* already be restricted to vertebrates.

Is that too strict?

Exploring species distribution of http://amigo.geneontology.org/amigo/term/GO:0042470

Looks like all non-vertebrate annotations are IBA

This paper
https://www.ncbi.nlm.nih.gov/pubmed/18817437

Says "Melanosomes are organelles found in a wide variety of tissues throughout the __animal__ kingdom"

But it may be using the term in a more general sense that might be better captured by a new grouping term "melanin granule" (intermediate between melanosome and pigment granule).

@ANiknejad do you want to include GO cell components in the Bgee homology table? It would be useful to have entries for things like melanosomes.

**Comment by ANiknejad** [comment]
Hi @cmungall , actually we already annotated homology relationships for some cell types (about 40 cell types so far), and we are looking for annotating more cell types for homology, specially because we are looking to use ScRNA-seq expression data in future Bgee releases.

**Comment by ValWood** [comment]
@pgaudet  this can probably close?
