### ISSUE TITLE
many inconsistancies in choice of taxa for fungal never_in_taxon constraints

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#16193]
The never_in_taxon constraints that @ValWood recently requested led me to look at this, in part to determine what the appropriate constraint should be. We have used many, different, inconsistent ways to keep things out of Val's interface. If we are going to use never_in_taxon constraints to keep things out of Val's interface, we should come up with a consistent procedure.

However, more importantly I think we need to consider appropriate use, and choice of taxa, when we make taxon constraints, and perhaps also whether we need to develop some guidelines for selecting appropriate guidelines for adding taxon constraints. Many of these terms might be better labelled with an appropriate only_in_taxon to indicate that these terms are only in metazoa (or perhaps something more specific).  @cmungall @ukemi 

There are 133 GO terms that have some form of a never_in_taxon constraint that is for Fungi or more specific, sometimes two different fungal taxons with one for a Schizo... and one for a Saccharo... (and there are at least three levels of specificity for these combinations). Of the terms using the most general taxon for "Fungi", about 45-50 are ones that I added for Val yesterday.

![useoffungalneverinconstraints](https://user-images.githubusercontent.com/10533218/43671525-91b68ce0-9750-11e8-8e5a-d843cfd449d5.jpg)

**Comment by krchristie** [comment]
Here's a spreadsheet with the 133 terms with some form of a never_in_taxon constraint that is for Fungi or for one or more specific fungal taxons.

[useOfFungalTaxaInNeverInConstraints.xlsx](https://github.com/geneontology/go-ontology/files/2259151/useOfFungalTaxaInNeverInConstraints.xlsx)

**Comment by cmungall** [comment]
In general I don't think it's always horrible to have some level of redundancy in axioms if those axioms are annotated with evidence - just like an annotations.

Use case:

 1. paper1 says foo originated in chordates
 2. paper2 comes out later and says foo originated in vertebrates
 3. we toss out 1 because it is redundant with 2
 4. we later realize that when paper2 was talking about foos, it was talking about a foo in a more restricted sense than what we meant
 5. we take out the TC that derived from 2
 6. foo suddenly looks like it originated at the base of life (or maybe in metazoa or something, inherited from another class)

By keeping both 1 and 2 we insulate ourselves against these changes.

redundancy can be filtered at the release stage, but it's not a bad idea to keep it for taxon constraints as these may be useful for some users (a bit moot for amigo since we don't show them at all)

**Comment by ValWood** [comment]
I request 'never in Schizosaccharomyces' if I don't know. Sometimes I request never in Saccharomyces too. If I know they are in neither yeast but they are present in some multicellular fungi/mushrooms etc. My natural history of the fungi is not good enough to be more precise.
I think "never in" sit comfortably  alongside "only in", and buffer against later removal of only_in.

**Comment by ValWood** [comment]
Is this OK as is?

**Comment by cmungall** [comment]
I think we can close this as an over-arching ticket. More precise constraints always welcome, but I think the procedure Val describes is efficient and correct.
