### ISSUE TITLE
Proposal to add 'DNA binding' parent to 'GO:0003700 DNA-binding transcription factor activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16214]
From discussion in #16152 (and in many other places). 
Summary: 
* PROs: This would make annotation easier, since the term DNA-binding transcription factor activity implies DNA binding. 

* CONs: 1) In the MF refactoring, it had been proposed to use the relation 'has necessary component activity' for compound functions. However, discussions with @thomaspd lead to the (rough) conclusion that all MF, except for binding, are compound functions, and to question how useful this weaker relation is, in practice. 
* 2) I had proposed to change the term label of 'GO:0003700 DNA-binding transcription factor activity' to 'gene-specific transcription factor activity', since there are transcription factors that don't bind DNA directly but that are not considered co-activators, as they are quite gene-specific as well. For these, Ruth, Colin and I made this proposal: #16132 but that seems to be a little complicated. 

@ValWood @hattrill @krchristie @rachhuntley @thomaspd please comment. 

Thanks, Pascale

**Comment by ValWood** [comment]
I would like this to happen.

Re ii)

But if a gene product does not bind DNA then it isn't a 
GO:0003700 DNA-binding transcription factor activity'  according to the GO def.

It might be *associated* with a GO:0003700 as part of a complex , and if it contributes to the DNA binding (motif selection or whatever) ,  this could be annotated  to GO:0003700 using contributes_to.

Otherwise I think these should be annotated based on their  activity  (transcription regulator + the specific transcription factor complex might be fine if you can't be more specific)

Do we have examples?

I'm sure we could come up with a term that would cover these once we know what they are...

**Comment by ValWood** [comment]
"since there are transcription factors that don't bind DNA directly but that are not considered co-activators, as they are quite gene-specific as well."

I think this solution:
https://github.com/geneontology/go-ontology/issues/16132
or similar seems fine for these GPs:

This IS the problem. Biologist refer to any factor involved in transcription as a 'transcription factor" at some point.....
We are  working around this by bringing precision to the meaning of 
GO:0003700 DNA-binding transcription factor activity'
if we relax this we are back to square 1

I would be happy for the label to change but not the definition (which includes the fact that it binds to DNA)

I'd also be happy for it to be 

gene-specific DNA-binding transcription factor activity

**Comment by bmeldal** [comment]
Lots of examples: 

all "TFs" that bind a DNA-binding TF in a stable complex. Here's one (the one I just fixed):
YAP1-TEAD1 complex
https://www.ebi.ac.uk/complexportal/complex/CPX-256 - human (EBI-11173119)
https://www.ebi.ac.uk/complexportal/complex/CPX-394 - mouse (EBI-11684155)

TEAD proteins (there are 4 of them) bind DNA but YAP1 doesn't: [PMID:11358867](http://europepmc.org/articles/PMC313800?fromSearch=singleResult&fromQuery=11358867) for evidence in mouse

**Comment by ValWood** [comment]
I don't  find YAP1 with a search on that PMID, did you mean YAP65?

If so
TEAD-binding domain at the amino terminus of YAP65, a powerful **transcriptional coactivator**

**Comment by bmeldal** [comment]
YAP1 was YAP65 (see UniProt) - PMID is old...

Ok, bad example, but proves the point that it's bloody confusing!

I think we do need an example of a "transcription factor regulator" as you said:

>Otherwise I think these should be annotated based on their activity (**transcription regulator** + the specific **transcription factor complex** might be fine if you can't be more specific)

which implies the transcription factor regulator is part of a TF complex. If it's part of a TF complex I would think its has coactivator/corepressor activity which makes it a transcription coactivator/corepressor rather than a FT regulator. 

Something that regulates a TF without having TF activity would be something that modulates the TF, like a kinase. In that case, the regulator-TF relationship is a molecular interaction of a enzyme with its substrate and not a stable complex. No Tx activity needed for the regulator but possibly a BP of the pos reg of transcription kind.

If you wouldn't annotate a transcription factor regulator with a TF complex or activity term we don't need this discussion as it would be covered by the newly proposed branch and I went off on a dead-end tangent ;-)

Confused? I am!

**Comment by ValWood** [comment]
Yes but this makes the point that we should be able to create a high-level term that is really clear for the ones which don't fit the currently available term, once we know precisely what the orphan gene products are.....

**Comment by RLovering** [comment]
If you add 'DNA binding' parent to 'GO:0003700 DNA-binding transcription factor activity' then if you say you a protein regulates DNA-binding transcription factor activity then you are saying that the protein regulates DNA binding. Which is not always true.

This is why we should NOT add 'DNA binding' parent to 'GO:0003700 DNA-binding transcription factor activity'

**Comment by bmeldal** [comment]
@ValWood 

>create a high-level term

If you don't know if it's a TF, a TF regulator or a Tx coactivator or repressor what would you know? 
If it binds to DNA you can still annotate to DNA binding or higher level children without annotating to the Tx-specific children or activity. 
If it regulates Tx (by unknown means) just annotate to "regulation of Tx".
If you know it's a TF but don't know if it binds DNA, use the higher level Tx activity terms that are DNA-binding independent.

But I guess it's not that easy in practice. We need examples to see where it doesn't work.

**Comment by ValWood** [comment]
From
https://github.com/geneontology/go-ontology/issues/16152



I would say if you annotated a protein to

regulates DNA-binding transcription factor activity"
then you ARE saying that protein regulates DNA binding.

there is no MF "DNA-binding transcription factor activity regulator"
but if there was this is what it would mean.

The process terms
GO:0051090 regulation of DNA-binding transcription factor activity
would imply that binding is regulated in some way, directly or indirectly.

but maybe we shouldn't be annotating these as a process anyways?

Most of these appear to be describing the TF at the end of a signalling pathway?

" x signalling" has_regulation target(specific transcription factor)

would seem to be the correct way to do this?

a lot of the annotation here don't make sense in terms of "DNA binding transcription factors".

For example:

KDM5A | Lysine-specific demethylase 5A |   | regulation of DNA-binding transcription factor activity | has_direct_input UniProtKB:P25440 | CAFA
but the input UniProtKB:P25440 is not a DNA binding TF.

Many others have "general" terms but do not specify which TF is regulated so are not really useful.

A lot are co-repressors etc

Lots of inconsistency here too.....

AND

[PomBase] had 7 annotations to this term and descendants. They are easy to rehouse
pombase/curation#2137

"regulation of DNA binding transcription factor activity" is really an example of a function term in the process ontology.

All of ours could be described as" function" has substrate "involved in process"
Some will be more complicated as they will be "has_regulation_target" of a signalling pathway
(i.e not direct substrate)

**Comment by ValWood** [comment]
From
#16152

Ruth, I don't know what else  you mean by 

"regulation of DNA binding TF activity"


Do you have a specific example of where you are regulating the "trancription factor activty" but  you are not regulating the binding?


DNA-binding transcription factor activity (GO:0003700)
A protein or a member of a complex that interacts selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a gene to modulate transcription.

The first part of this def is the DNA binding activity. The second part is the process that is regulated by the binding.

So what can you be regulating apart from the DNA binding here?

**Comment by RLovering** [comment]
I misremembered my original issue. See #6349 where I requested the parent GO:0051101 regulation of DNA binding to be removed from GO:0051090 regulation of transcription factor activity.

Maybe there are things listed in this ticket which will help with this new proposal

;)

**Comment by ValWood** [comment]
It is a good point though that we  need to think about what we mean by "regulation of transcription factor activity"

I'm not sure that that term is required based on  existing annotations at PomBase:
https://github.com/pombase/curation/issues/2137

and this proposal to make "DNA binding" a parent DNA-binding transcription factor activity (GO:0003700)  of will only work if we are very  rigorous about the definition of this term, and any  regulation terms that  are related to it.

**Comment by krchristie** [comment]
One of the reasons we never wanted to add the 'DNA binding' parent to 'GO:0003700 DNA-binding transcription factor activity' in previous discussions is that if we do this, then ALL subunits annotated to 'GO:0003700 DNA-binding transcription factor activity' will be annotated to 'DNA binding', even the subunits that do NOT bind DNA.

**Comment by bmeldal** [comment]
But the definition of GO:0003700 DNA-binding transcription factor activity is
"A protein or a member of a complex **that interacts selectively and non-covalently with a specific DNA sequence** (sometimes referred to as a motif) within the regulatory region of a gene to modulate transcription."

This def clearly says that the GP **must** have DNA-binding activity in order to use this term. What am I missing?

And that still holds true for a complexes: If a complex binds DNA it doesn't mean all subunits bind DNA as we annotate to the whole unit. We wouldn't extrapolate a binding annotation to all complex subunits.

**Comment by ValWood** [comment]
I have to admit that I had  not read the   OR  "member of a complex" part of this definition,  to mena *Any complex member* even though I had read it many times.
I thought this term was purely  to annotate the "DNA-binding transcription factors", those which 'read' the DNA.  I presumed that the  OR  "member of a complex"  was only there to 
 make it clear that leucine zippers and other coiled-coil DNA binding TFS which would not bind DNA alone would get annotated to the term (with contributes_to).

I didn't consider that I would annotate all of the complex members to this term.
If a GP binds to a  "DNA-binding transcription factor activity" and alters transcription in some way I would annotate it as a "transcription corepressor activity" "transcription coactivator activity", or "transcription coregulator activity"?

Why do we need to annotate gene products which do not bind to DNA as DNA-binding TFs?

**Comment by ValWood** [comment]
Also, we don't say for *any* other molecular function term "or member of a complex" so why do this for "DNA binding transcription factor?" def?

**Comment by RLovering** [comment]
FYI the reason DNA binding cannot at present be made a parent to DNA binding TF activity is because if you do this then if you make the statement that a protein regulates the activity of a DNA binding TF the ontology will imply that the protein regulates the DNA binding activity of the TF which is not necessarily true. Until this sort of assertion does not happen in the ontology for this, and other MF terms DNA binding cannot be made a parent to DNA binding TF activity

**Comment by ValWood** [comment]
The term
GO:0003700    DNA-binding transcription factor activity
A protein or a member of a complex that interacts selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a gene to modulate transcription. Regulatory regions include promoters (proximal and distal) and enhancers. Genes are transcriptional units, and include bacterial operons.

is defined exclusively by it's ability to bind DNA.

The regulation term should, therefore, be revised to say (probably needs obsoleting, because it  does not curretnyl say this)
"Any process that activates or increases the frequency, rate or extent of *activity* of a 
DNA-binding transcription factor.

and I would expect this term to only be used for annotations where "DNA binding activity" is regulated in some way.

If the "DNA-binding activity" is not regulated  (directly or indirectly) the correct annotation would presumably be:
"GO:0006357    regulation of transcription by RNA polymerase II" with has_regulation_target(specific transcription factor), 

because all you can say is that the process of transcription (which  occurs via this particular transcription factor) is regulated in some way,  (i.e. by increased degradation of the transcription factor), not that the 'activity' of the transcription factor is itself regulated.

This term is about "regulation of the activity" not about "regulation of process" more generally.

That said, this is one of those "regulation of MF" in the BP ontology terms, which should really be removed IMHO. I won't go there today......

I know we do have inheritance issues between "regulation terms" and some compound functions (although I think there are simple solutions for these too), but this particular term does not seem to be in this class.

**Comment by RLovering** [comment]
Ok for example  GO:0001228 DNA-binding transcription activator activity, RNA polymerase II-specific has the definition: A protein or a member of a complex that interacts selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a RNA polymerase II-transcribed gene to activate or increase transcription. Regulatory regions include promoters (proximal and distal) and enhancers. Genes are transcriptional units.

If another protein stops this DNA-binding transcription activator activity, from pos reg transcription because it prevents it from binding to the mediator but the DNA-binding transcription activator is still bound to the DNA what function would you give to the repressing protein? 
I thought this would negatively regulate the DNA-binding transcription activator activity.

**Comment by pgaudet** [comment]
@RLovering I though we'd leave regulation out of it for now. 
We will only add the parent if the inference is not made (ie: regulation of DNA binding tx factor activity should NOT be a regulation of DNA binding).

@ others: WRT the complex, if we add the terms proposed here: https://github.com/geneontology/go-ontology/issues/16132 

Then the mention of the 'complex' is not needed anymore. There just wasn't a way to annotate a 'gene-specific (non-DNA binding) tx factor'. 

Would that resolve the issue? 

Thanks, Pasale

**Comment by ValWood** [comment]
I would not use 
"negatively regulate the DNA-binding transcription activator activity"
but as I said I don't think these types of process terms should exist. They are more about the function than the process. The process here is "negative regulation of transcription".

This types of terms were added before the concept of  LEGO, and are used if you know something is upstream of an activity but you don't know exactly where. I have discussed these and their ilk with @pgaudet  and we  think they would (almost universally)  be better described as 

"negative regulation of process x, has_regulation_target(y)...... because this is really all you know.

In your example here, you know more I would say this was  a "protein binding inhibitor" at the molecular level.
If it is bound to the DNA-binding txn factor directly and inhibiting binding to the mediator it would be a "transcription corepressor activity"

Def
A protein or a member of a complex that interacts specifically and non-covalently with a DNA-bound DNA-binding transcription factor to repress the transcription of specific genes. Corepressors often act by ........ A third class occludes DNA-binding transcription factor protein-protein interaction domains. 

That said I think we desperately need a molecular function to describe "binding inhibition" more generally....

**Comment by ValWood** [comment]
AS far as I see TFIIC binds DNA but it does not bind to a specific regulatory motif like the gene-specific TFs? So it does not fit 
DNA-binding transcription factor activity

I never used  "DNA-binding transcription factor activity" for the general TFs even before the recent changes. I did not realize that was intended use even previously. The annotations to the general TFs were reviewed globally so there shouldn't be any existing annotations of the  general TFs to the DNA-binding trancription factor terms.

**Comment by krchristie** [comment]
Hopefully TFIIIC is not classified as RNA polymerase II general transcription initiation factor activity and TFIIIC absolutely does bind a specific sequence. However, it can also be recruited by TFIIIA, in which case TFIIIA is the sequence specific factor, and TFIIIC is acting as a bridging agent between TFIIIA and TFIIIB.

Honestly, I think the old name (pre-2010 transcription overhaul) of 'regulatory transcription factor' was better than using such a general name like "DNA-binding transcription factor activity" for only a subset of the transcription factors that bind DNA. I find it difficult to see how using a name that is so broad for only a subset of the transcription factors that bind DNA is going to improve annotation consistency.

**Comment by pgaudet** [comment]
@krchristie Val is right, with the new organisation of the tx branch this is not an issue anymore.

**Comment by pgaudet** [comment]
@krchristie TFIIIC is not in the MF; there are only some binding terms and CC terms.

**Comment by krchristie** [comment]
While TFIIIC may not be covered by this term anymore, there are other examples of multisubunit transcription factors where only one subunit binds DNA. 

I think it is quite odd that you have defined the GO:0003700 term such that you are saying that a single subunit of a complex has this function. 
> Def: A protein or a member of a complex that interacts selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a gene to modulate transcription. Regulatory regions include promoters (proximal and distal) and enhancers. Genes are transcriptional units, and include bacterial operons.

I have always thought that GO defined the functions without respect to the entity performing it. Thus the functional unit is the transcription factor complex, not the DNA binding member of a complex that has transcription factor activity. It seems very odd, and against the principles we have been using for years to define functions, to make this provision that you can annotate one subunit of a complex to this term, without being able to annotate the other member of this complex to this term. 

@ukemi - thoughts?

**Comment by bmeldal** [comment]
So, is this wrong then:

If a GP that has been shown to bind DNA is annotated to "DNA binding" or children.
If a complex that has been shown to bind DNA is annotated to "DNA binding" or children.
A complex member that has been shown to bind DNA is annotated to "DNA binding" or children.
A complex member that has NOT been shown to bind DNA is NOT annotated to "DNA binding" or children. But it could be annotated to "protein binding" or children.

If you have a TF you simply use the relevant TF activity child term that either defines the function as DNA binding or protein binding (I doubt there are any TFs that don't bind either DNA nor a protein) or possibly both.

If you have a GP that binds a TF but not DNA you use the relevant protein binding term.

Now, at the moment, GO:0140110 transcription regulator activity and children have no links to DNA binding or protein binding but anything affecting transcription must either bind DNA and/or proteins (I would like to find a TF or a TF modulator that doesn't bind another protein...). Hence, for now, we have to annotate with 2 MFs, one from the "binding" branch and one from the "transcription regulator activity" branch even though a lot of the "transcription regulator activity" terms are in fact DNA binding children. If we can give the children of "transcription regulator activity" its relevant binding parents we don't have to worry about its separate binding annotations any more. If there are inconsistencies in the "transcription regulator activity" branch with regards to what they bind we should fix those rather than not adding a logical parent.

I think that was Val's original idea, too, or I'm just barking mad for thinking this is much more simple than what you make it out to be - that's a possibility, too :)

**Comment by bmeldal** [comment]
Sorry, what I meant with 

>even though a lot of the "transcription regulator activity" terms are in fact DNA binding children.

was that their def effectively makes them children of DNA binding, of course they don't have the parentage (yet).

**Comment by ValWood** [comment]
I don't know about others, but I always  interpreted  GO:0003700 DNA-binding transcription factor activity as the 'entity' that binds to the DNA in order to decode it to transcribe specific genes. In this instance I always assume "specific DNA sequence (sometimes referred to as a motif)" to be a specific DNA-binding motif. This is *usually*  short  (consensus usually 5-16 bases) and bound by a single molecule (except of course for bipartite TFs, where you need both/two, with contributes_to).

Maybe this is an over-simplification, but it has always worked for us, and  importantly it seems to mirror the list that our users require when they ask us for all of the DNA-binding transcription factors. We know there are other uses of the phrase "transcription factor" and that some of these also bind DNA (but not to these type of regulatory motif), but I always believed this is what we were trying to capture here. 

We aren't trying to model every biological eventuality in the ontology (w.r.t what binds to what), we can do that at annotation time. 

This does not prevent us from using "DNA-binding" with any other gene product, which binds to DNA, or contributes_to DNA-binding in some way, and is involved in transcription, but does not fit the more restricted definition above.

MAybe we need to be even more precise in the definition, about the type of DNA-binding? Although to me it is reasonably clear right now...

**Comment by ValWood** [comment]
I agree that the term def should not mention "protein or member of a complex"

**Comment by pgaudet** [comment]
> I agree that the term def should not mention "protein or member of a complex"

Yes, I should remove that.

**Comment by pgaudet** [comment]
Fixed logical definition to 
   'transcription regulator activity'
   and 'has part' some 'transcription regulatory region sequence-specific DNA binding'
   and 'part of' some 'regulation of transcription, DNA-templated'


@hattrill @ValWood I think this is consistent with what we discussed on the compound function calls. If this is right Ill do the same logical definitions to children. 

Thanks, Pascale

**Comment by hattrill** [comment]
I probably need a bit of an ontology speak help here - Doesn't 'transcription regulator activity' apply to non-DNA binding factors as well? Is that what the "some" bit conveys?

**Comment by ValWood** [comment]
Yup, co-repressors, mediator etc.

**Comment by bmeldal** [comment]
> I probably need a bit of an ontology speak help here - Doesn't 'transcription regulator activity' apply to non-DNA binding factors as well? Is that what the "some" bit conveys?

> Yup, co-repressors, mediator etc. (are not DNA binding)

Yes, that's currently being written up by Colin Logie, myself etc. - and another paper on the dbTFs by Ruth et al

**Comment by pgaudet** [comment]
Hi @hattrill @bmeldal @ValWood 

> Doesn't 'transcription regulator activity' apply to non-DNA binding factors as well?

Indeed, 'transcription regulator activity' also includes coTFs. BUT what I was describing is a dbTF: 

it *is* a 'transcription regulator activity'

that has two additional characteristics: 
and 'has part' some 'transcription regulatory region sequence-specific DNA binding'
and 'part of' some 'regulation of transcription, DNA-templated'

The idea is that the coTF does not bind a 'transcription regulatory region in a sequence-specific manner, so that distinguishes the two activities (ie if you have a coTF and you annotate it to 
- 'transcription regulator activity'
and 'has part' some 'transcription regulatory region sequence-specific DNA binding'
and 'part of' some 'regulation of transcription, DNA-templated', you will get the inference that it's a dbTF. 

> Is that what the "some" bit conveys?

No, the 'some' means always at the instance level - it's more of a 'grammatical connector' between the relation (predicate) 'has part/part of' and the other GO term. 


Let me know if you would like to set up a call to sort this out, this is important, we need to be on the same page. 

Thanks, Pascale

**Comment by hattrill** [comment]
If it just applies to dbTFs, then I have no issue. All good.

**Comment by ValWood** [comment]
Sorry I didn't re-read the thread ;)

**Comment by bmeldal** [comment]
Ah, got it.
