### ISSUE TITLE
CNBH domain intrinsic ligand binding

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#16275]
The  Cyclic Nucleotide-Binding Homology Domain (CNBHD) interacting selectivity with a cyclic nucleotide mimicking protein motif that is part of the same protein.   The  CNBHD is a domain on KCNH channels that creates a binding pocket on the KCNH channel that resembles the cyclic nucleotide- binding domain on other ion channels.  It  binds to a peptide motif that is part of the same protein rather than a cyclic nucleotide.  
is_a GO:000551 protein binding
PMID: 29567795
PMID:27025590

Note:
It is unclear if the motif bound by CNBHD is a specific motif or just a beta sheet with the appropriate amino acids.

**Comment by hdrabkin** [comment]
Hi @cerivs .
Can you please clarify the proposed definition? 
Interacting selectively and non-covalently with....
Thanks ...

**Comment by cerivs** [comment]
The Cyclic Nucleotide-Binding Homology Domain (CNBHD) interacting selectivity and noncovalently with a cyclic nucleotide mimicking protein motif that is part of the same protein. The CNBHD is a domain on KCNH channels that creates a binding pocket on the KCNH channel that resembles the cyclic nucleotide- binding domain on other ion channels. It binds to a peptide motif that is part of the same protein rather than a cyclic nucleotide.
is_a GO:000551 protein binding
PMID: 29567795
PMID:27025590

Note:

**Comment by hdrabkin** [comment]
term: CNBH domain intrinsic ligand binding
Def: Interacting selectivity and noncovalently with a cyclic nucleotide mimicking protein motif that is part of the same protein. The CNBHD is a domain on KCNH channels that creates a binding pocket on the KCNH channel that resembles the cyclic nucleotide- binding domain on other ion channels. It binds to a peptide motif that is part of the same protein rather than a cyclic nucleotide.

Right?

**Comment by hdrabkin** [comment]
id: GO:0106151
name: CNBH domain intrinsic ligand binding
