### ISSUE TITLE
remove comma in description of GO:0007187

### ISSUE THREAD

**Issue by lenov** [geneontology/go-ontology#16283]
Hello,

In the term:

GO:0007187
G-protein coupled receptor signaling pathway, coupled to cyclic nucleotide second messenger

The comma is annoying (there should never be commas in OBO ontology's term description IMHO). When removed, we uncover the problem. A coupled to B coupled to C. The first "coupled" comes from a typo. The correct spelling should be "G Protein-coupled receptor". Cf https://en.wikipedia.org/wiki/G_protein%E2%80%93coupled_receptor

But a better definition would be something along the lines:
"G-protein coupled receptor signaling pathway regulating cyclic nucleotide second messengers"
(Note the S at the end of messengers).
Because a "pathway" cannot be coupled to a "second messenger". A G protein can be coupled to a receptor because they are both molecules.

Best regards

**Comment by pgaudet** [comment]
Thanks for the feedback @lenov ! 

I see what you mean about the label being not very elegant, although I dont know if 'regulation' is the best term, given that we have such a hard time defining it in GO. Would 'involved in' be OK? 

@pfey03 @vanaukenk @ukemi What do you think ? 

Thanks, Pascale

**Comment by deustp01** [comment]
Maybe the issue of "regulating" with all its conceptual baggage and "coupling" with its difficulties can be evaded here. It looks like the point of the definition is to distinguish signaling processes initiated by G protein-coupled receptors that involve cyclic nucleotide second messengers from signaling processes that involve direct effects on ion channels from ones that involve activation of phospholipases. The different signaling processes can be distinguished according to the immediate effect of activating the receptor, without having to specify whether the interaction counts as regulation or coupling or something else.

**Comment by pgaudet** [comment]
@deustp01 What are you suggesting? 


Do you think G-protein-coupled receptor signaling pathway involved in cyclic nucleotide signaling' would work ?

**Comment by deustp01** [comment]
It looks like GO:0007186 "G-protein coupled receptor signaling pathway" has a group of children (GO:0007187 "G-protein coupled receptor signaling pathway, coupled to cyclic nucleotide second messenger") is one of them, that are intended to differentiate various G protein-coupled receptor signaling processes according to the immediate effect of receptor activation, so any word that links the "G-protein-coupled receptor signaling pathway" part of the GO term name to the part that differentiates the process subtypes, and that does it without falling into semantic traps, ought to be OK.

Here, "involving" might be better - "involved in" implies that the G protein-coupled receptor signaling process somehow mediates a separate cyclic nucleotide signaling process which (I think) is different from a G protein-coupled receptor signaling process that makes use of cyclic nucleotides (or ion channels or phospholipases or ...). I think the second is what we're trying to say, in order to classify the various G protein-coupled receptor signaling processes into subgroups according to what molecular mechanism is used to convey the signal from the activated G protein-coupled receptor.
