### ISSUE TITLE
taxon restrictions, only in plant

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16309]
chloroplast RNA processing  31425
peroxisome-chloroplast membrane tethering  GO:0010381

**Comment by ukemi** [comment]
Euglena have chloroplasts too. So I am using the taxon union. However, chloroplast is not characterized this way. It uses several never_in restrictions. I think this is the kind of inconsistency that @krchristie was recently pointing out.

**Comment by ukemi** [comment]
Argh. But algae have chloroplasts too. Maybe this is better the way chloroplast is restricted. I will re-edit to make the restrictions like the one on chloropast. We really need to think carefully about these taxon constraints. I thought I had remembered looking at green paramecia at some point in my career, but it turns out those are symbiotic with algae.
