### ISSUE TITLE
GMP synthase activity terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#16424]
ID: GO:0003922
Term: GMP synthase (glutamine-hydrolyzing) activity
Def: Catalysis of the reaction: ATP + xanthosine 5'-phosphate + L-glutamine + H2O = AMP + diphosphate + GMP + L-glutamate.
EC xref: 6.3.5.2
===
ID: GO:0003921
Term: GMP synthase activity
Def: Catalysis of the reaction: ATP + xanthosine 5'-phosphate + NH3 = AMP + diphosphate + GMP.
EC xef: 6.3.4.1
===

According the EC, 6.3.4.1 has been transferred to 6.3.5.2.
https://enzyme.expasy.org/EC/6.3.4.1

So I think the two GO terms be merged, retaining the xref to 6.3.5.2.
Actually, the relationships between the two current GO terms doesn't look right (see attachment), so some sort of edit does look necessary.
<img width="843" alt="screen shot 2018-09-25 at 15 09 26" src="https://user-images.githubusercontent.com/16306861/46038187-6aad2080-c0d8-11e8-84ec-fcdf327da75e.png">

**Comment by sjm41** [comment]
Tagging @hattrill

**Comment by ukemi** [comment]
@deustp01 A Reactome query shows  R-HSA-56085 --> GO:0003922 and GO:0003921, R-HSA-73792 --> GO:0003921 and --> Rhea:11681.

**Comment by deustp01** [comment]
This looks like a simple curation mistake in Reactome. The reaction we have annotated, R-HSA-73792, is XMP + L-Glutamine + ATP + H2O => GMP + L-Glutamate + AMP + pyrophosphate, which corresponds to GO molecular function GO:0003922 GMP synthase (glutamine-hydrolyzing) activity "Catalysis of the reaction: ATP + xanthosine 5'-phosphate + L-glutamine + H2O = AMP + diphosphate + GMP + L-glutamate." (RHEA:11680).

The use of GO:0003921 GMP synthase activity "Catalysis of the reaction: ATP + xanthosine 5'-phosphate + NH3 = AMP + diphosphate + GMP." (RHEA:18301) to annotate R-HSA-73792 is wrong. It's fixed in the internal database and will propagate to the public site with our next release in December.

**Comment by ukemi** [comment]
Thanks @deustp01. In an ideal world the new alignment project would be able to spot these kinds of inconsistencies and flag them for review. @goodb just as a heads up for you to think about.

**Comment by pgaudet** [comment]
We can go ahead and merge.

**Comment by ukemi** [comment]
Looking at this again and based on discussions from last week. To leverage from the Rhea reactions we should:

GO:0003921- remove the EC xrefs (they aren't in Rhea), and tweak the definition to match Rhea exactly. Make this term a part_of GO:0003992 to match the Rhea structure. 

GO:0003992- Retain the EC xref to 6.3.5.2 as it is in Rhea and tweak the definition to match Rhea.

**Comment by sjm41** [comment]
This sounds good, thanks David.
