### ISSUE TITLE
NTR: carbon-nitrogen ligase activity on lipid II

### ISSUE THREAD

**Issue by vanessadoan** [geneontology/go-ontology#16422]
New Term: carbon-nitrogen ligase activity on lipid II
Definition: Catalysis of the transfer of the amide nitrogen of glutamine to a variety of substrates. GATases catalyze two separate reactions at two active sites, which are located either on a single polypeptide chain or on different subunits. In the glutaminase reaction, glutamine is hydrolyzed to glutamate and ammonia, which is added to an acceptor substrate in the synthase reaction. To amidate lipid II
Aspect: Function
Relationships: child of GO:0016884 carbon-nitrogen ligase activity, with glutamine as amido-N-donor
References: PMID 22291598
@sandyl27

**Comment by ukemi** [comment]
Not sure about this one.

**Comment by sandyl27** [comment]
@jimhu-tamu

**Comment by pgaudet** [comment]
@ukemi Why don't you like it ? Because it's mentioning the substrate ?

**Comment by ukemi** [comment]
Yes. We need to determine if we can define it in terms of ChEBI and get a Rhea cross ref for it.

**Comment by jimhu-tamu** [comment]
Are we talking about tweaking the definition or something else?

This activity is also hydrolyzes ATP, presumably to make a phosphorylated intermediate (hypothesized but not demonstrated in the paper). In vitro the enzyme works on multiple substrates - lipid I, lipid II, and lipid II-gly5, but the authors assert evidence that the in vivo substrate is the lipid II-gly5.

lipid ii is CHEBI:27692. What's kind of weird at ChEBI is that the only annotated biological role is as a signal for innate immunity in mice. There's nothing for peptidoglycan biosynthesis.

**Comment by pgaudet** [comment]
@amorgat Is there a Rhea reaction for this ?

**Comment by jimhu-tamu** [comment]
@pgaudet 
1. No. That entry is for E. coli MurG. The [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3266927/) is for the S. aureus GatD/MurT complex. This has related domains but the reaction is different. MurG attaches GlcNac to MurNac in the sugar part of the peptidoglycan. GatD/MurT amidates the D-Glu in the pentapeptide.

So, while I'm not sure, I think the lipid II part is OK. Based on looking at some BRENDA pages, I'm thinking:
undecaprenyldiphospho-N-acetyl-(N-acetylglucosaminyl)muramoyl pentapeptide amidotransferase (glutamine-hydrolyzing) activity.

This is consistent, I think, with GO:0004088  carbamoyl-phosphate synthase (glutamine-hydrolyzing) activity, but since I am not calling it a synthase, that might not be appropriate. 

2. We debated 1 vs 2 activities based on the enzyme based on the [molecular function ontology documentation](http://www.geneontology.org/page/molecular-function-ontology-guidelines#gran)

> If the intermediates are known to be released and used in other biological processes, function terms should be added to represent the steps of the reaction, and a biological process term added to represent the sum of these functions. If the separate activities generating and acting on the molecular intermediates can be associated with different subunits of the enzyme, two or more functions should probably be made. If neither of these conditions holds, a single function term can be made.

Here, if I'm reading the paper correctly, the intermediate is not released but the activities are on separate subunits. "probably" leaves wiggle room, so we looked at GO:0004088 - carbamoyl-phosphate synthase (glutamine-hydrolyzing) activity, which I view as a paradigm for this class of enzymes, including the intermediate tunneling. 

I believe this is a single activity term where subunits have separate active sites.

**Comment by pgaudet** [comment]
Can we improve the definition ? "Catalysis of the transfer of the amide nitrogen of glutamine to a variety of substrates. GATases catalyze two separate reactions at two active sites, which are located either on a single polypeptide chain or on different subunits. In the glutaminase reaction, glutamine is hydrolyzed to glutamate and ammonia, which is added to an acceptor substrate in the synthase reaction. To amidate lipid II" 

1. "amide nitrogen of glutamine to a variety of substrates" is pretty vague - can we specify something about these substrates  ? 
2. The last sentence ends abruptly. 

Thanks, Pascale

**Comment by ukemi** [comment]
It is ok, but whenever we create a new enzyme reaction we should be coordinating with EC, Rhea and ChEBI.

**Comment by pgaudet** [comment]
Thanks @ukemi 

I have done very little with enzymes. Do we have instructions for that ?

**Comment by ukemi** [comment]
As you know, the coordination of enzymes with eternal resources is an ongoing project that we will address at the Geneva ontology developers' meeting. One of the in things we should accomplish there is to create a standard data flow. One thing we know for sure is that reactome will be the gatekeeper for reactome xrefs. 
Here is the existing documentation, but it will need review as we proceed:
http://wiki.geneontology.org/index.php/Enzymes_and_EC_mappings
http://wiki.geneontology.org/index.php/Curator_Guide:_Enzymes_and_Reactions

**Comment by pgaudet** [comment]
OK - having another look at this. 

The paper cites the following SwissProt AC: 
- SA1707 (designated GatD; UniProtKB: Q7A4R4) -> replaced by A0A0H3JN63
- Mur ligase homologue SA1708 (designated MurT; UniProtKB: Q7A4R3) -> replaced by A0A0H3JUU7.

**Comment by pgaudet** [comment]
@jimhu-tamu Can you tell me the EC, or the Branda entry?

**Comment by jimhu-tamu** [comment]
I couldn't find an EC for this activity.  What I mentioned above was to look at activities with similar chemistry and activities that work on lipid II to suggest possible names. But getting feedback from EC sounds like a good thing.

**Comment by kaxelsen** [comment]
Several things:
You write: 'GATases catalyze two separate reactions at two active sites'. This is wrong. GATase (aka glutamine amidotransferase [this name is misleading since the subunit is not a transferase]) is the name of the glutaminase subunit, so it is not the complex that is called GATase. This subunit is GatD (SA1707)
CHEBI: The precise molecule shown in Fig. 2 of PMID 22291598 is not present in ChEBI. The closest is CHEBI:60033 (The charged version of chebi:27692) but there are differences in the amino acid chain.
Rhea: We do not have this reaction in Rhea.
EC: There is no EC number for this activity. A simple name could be: Lipid II amidase

**Comment by pgaudet** [comment]
Definition for GO:0016884 carbon-nitrogen ligase activity, with glutamine as amido-N-donor

Current: Catalysis of the transfer of the amide nitrogen of glutamine to a variety of substrates. GATases catalyze two separate reactions at two active sites, which are located either on a single polypeptide chain or on different subunits. In the glutaminase reaction, glutamine is hydrolyzed to glutamate and ammonia, which is added to an acceptor substrate in the synthase reaction.

Proposed by @kaxelsen : Catalysis of the transfer of the amide nitrogen of glutamine to a variety of substrates. Usually composed of two subunits or domains, one that first hydrolyzes glutamine, and then transfers the resulting ammonia to the second subunit (or domain), where it acts as a source of nitrogen.

**Comment by pgaudet** [comment]
New definition GO:0140282: Catalysis of the transfer of the amide nitrogen of glutamine to lipid II.

**Comment by pgaudet** [comment]
Now we're only missing EC number. 
@kaxelsen let us know when it is ready :)

**Comment by kaxelsen** [comment]
The EC number is now available as EC 6.3.5.13. The associated Rhea reaction is RHEA:57928.
RHEA:57928 is a multi-step reaction composed of three parts: RHEA:15889 + RHEA:59488 + RHEA:57932
