### ISSUE TITLE
ELK 0.5 shows GO has a large number of logical incompatibilities with property ranges

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#16524]
The latest (unreleased) ELK snapshot (obtained from https://github.com/liveontologies/elk-reasoner/wiki/GettingElk) provides reasoning on object property ranges. Classifying go-plus with ELK 0.5 shows thousands of unsatisfiable classes. Lots of these are caused by [Uberon](https://github.com/obophenotype/uberon/issues/1455), but if you delete the Uberon import you can see ~2000 remaining problems.

A quick look suggests that many of these involve regulation of qualities, e.g. [regulation of biological quality](http://purl.obolibrary.org/obo/GO_0065008). The object of 'regulates' needs to be an 'occurrent', while qualities are 'continuants'.

**Comment by cmungall** [comment]
I think we need to press on ASAP with a solution, either generalizing range to a union or adding the RoQ relations

**Comment by ukemi** [comment]
What these terms really mean is that we are regulating a process that results in the 'expression' of the biological quality.

**Comment by ukemi** [comment]
for homeostasis we have regulates_levels_of, a sibling of regulates. Perhaps this is a route to investigate?

**Comment by cmungall** [comment]
See also https://docs.google.com/document/d/1xdFtvn5Gxege4KWBrF-gwbihytY2j8qVH2CZ6_0Yluo/edit "Defining GO relations using PATO, bridging to phenotypes and LEGO"

**Comment by vanaukenk** [comment]
From an annotation POV, I wonder how many annotations to 'regulation of biology quality' terms reflect phenotypes described in the paper without detailed understanding of the mechanism by which that phenotype arises.
In such cases, if we want to keep the annotations, would we be better off using a top-level relation like 'acts upstream of or within' and a BP term that represents the underlying process, even if that is a high-level term?
An example that comes to mind is 'regulation of brood size' that perhaps could instead be annotated as GP 'acts upstream of or within, positive (or negative) effect' 'reproduction'. 
We are trying to move towards an annotation practice where use of a 'regulation' term implies that the mechanism is known.  In light of that, maybe some of the higher level terms under 'regulation of biological quality' should have a 'Do Not Annotate' flag on them so that we stay focused on annotating to the underlying processes that influence that quality.

**Comment by ukemi** [comment]
But something like regulation blood pressure strikes me being a bonafide process and a legitimate grouping term.

**Comment by dosumis** [comment]
'regulation of membrane potential' is too

**Comment by vanaukenk** [comment]
That's why I was careful to say _some_ of the higher level terms might warrant a 'Do Not Annotate' flag :-)

There may definitely be some terms that represent bona fide processes and legitimate grouping terms, but I suspect some annotation clean-up is warranted in this part of the ontology.  I'd have to do more investigating to see what the scope might be, though.

**Comment by ukemi** [comment]
But even adding the tag or deleting the annotations doesn't solve the fundamental ontology problem. I think we should explore:
regulation of biological quality= biological_process and (regulates some (biological_process and (related_via_dependence_to some biological_attribute)))  or something like this.

**Comment by vanaukenk** [comment]
@ukemi  Yes, that's definitely true.  And perhaps exploring the logical def further would help us decide which terms would be good to keep and which might be problematic.

**Comment by dosumis** [comment]
@ukemi - I'm sure I remember seeing a more recent suggestion from you on regulation of biological quality but can't seem to find it.  Is there another ticket on this?

**Comment by ukemi** [comment]
Using the regulates relation between a process and a quality violates the definition of regulates:
Process(P1) regulates
  process(P2) iff: P1 results in the initiation or termination
  of P2 OR affects the frequency of its initiation or termination
  OR affects the magnitude or rate of output of P2.

I think we need a new causal relation between a process and a quality.

**Comment by balhoff** [comment]
@dosumis suggested 'results_in_change_in' above, which sounds pretty good. However it sounds a little weaker than 'regulates'. Could be 'regulates_change_in'.

**Comment by ukemi** [comment]
What about just calling it what it is 'regulates biological attribute' or more generic 'regulates quality'. A child of functionally related to? and 'regulates levels of' would be child of it?
@dosumis?

**Comment by ukemi** [comment]
How would we define it?

**Comment by ukemi** [comment]
Explore how this would result in GO-CAM inferences.

**Comment by cmungall** [comment]
It's over 2 years since Jim reported this. I think we need to start with the simplest thing: extending the range of the relations, since that is how we are using them. We can then iterate on whether the better longer term solution is separate relations

**Comment by dosumis** [comment]
OK with broadening as temp fix, but also easy to add 'regulates biological quality' - defined as any process that results in a change in a quality - and adding a bunch of examples from GO (regulation of membrane potential', 'regulation of blood pressure'.  We can worry about wiring it up and axiomatising it later.  @ukemi - do you want to have a go at adding and making a PR?

**Comment by ukemi** [comment]
@pgaudet ?

**Comment by ValWood** [comment]
Is this ticket related?
https://github.com/geneontology/go-ontology/issues/11794
Add axioms for regulation of biological quality #11794
opened this issue on 13 Apr 2015

**Comment by balhoff** [comment]
@pgaudet @krchristie @thomaspd @cmungall here is the classification diff resulting from removing the OBA (Ontology of Biological Attributes) import. You can see it is pretty small, so I would say we're not depending that much on outside hierarchy provided by OBA. This isn't the complete picture of getting rid of "regulation of quality"; there is some (maybe a lot of) hardcoded hierarchy that tracks OBA—for example 'regulation of cellular component size' SubClassOf 'regulation of anatomical structure size'.

### cell volume homeostasis `http://purl.obolibrary.org/obo/GO_0006884`
#### Removed
- [cell volume homeostasis](http://purl.obolibrary.org/obo/GO_0006884) SubClassOf [regulation of cell size](http://purl.obolibrary.org/obo/GO_0008361) 



### intracellular pH elevation `http://purl.obolibrary.org/obo/GO_0051454`
#### Removed
- [intracellular pH elevation](http://purl.obolibrary.org/obo/GO_0051454) SubClassOf [pH elevation](http://purl.obolibrary.org/obo/GO_0045852) 



### intracellular pH reduction `http://purl.obolibrary.org/obo/GO_0051452`
#### Removed
- [intracellular pH reduction](http://purl.obolibrary.org/obo/GO_0051452) SubClassOf [pH reduction](http://purl.obolibrary.org/obo/GO_0045851) 



### regulation of follicle cell microvillus length `http://purl.obolibrary.org/obo/GO_0032533`
#### Removed
- [regulation of follicle cell microvillus length](http://purl.obolibrary.org/obo/GO_0032533) SubClassOf [regulation of cell size](http://purl.obolibrary.org/obo/GO_0008361) 



### regulation of myofibril size `http://purl.obolibrary.org/obo/GO_0014881`
#### Removed
- [regulation of myofibril size](http://purl.obolibrary.org/obo/GO_0014881) SubClassOf [regulation of cellular component size](http://purl.obolibrary.org/obo/GO_0032535) 

#### Added
- [regulation of myofibril size](http://purl.obolibrary.org/obo/GO_0014881) SubClassOf [regulation of anatomical structure size](http://purl.obolibrary.org/obo/GO_0090066) 


### regulation of tube diameter, open tracheal system `http://purl.obolibrary.org/obo/GO_0035158`
#### Removed
- [regulation of tube diameter, open tracheal system](http://purl.obolibrary.org/obo/GO_0035158) SubClassOf [regulation of tube length, open tracheal system](http://purl.obolibrary.org/obo/GO_0035159) 

#### Added
- [regulation of tube diameter, open tracheal system](http://purl.obolibrary.org/obo/GO_0035158) SubClassOf [regulation of tube size, open tracheal system](http://purl.obolibrary.org/obo/GO_0035151)

**Comment by pgaudet** [comment]
Looks great! Can you please merge that?

**Comment by dosumis** [comment]
> there is some (maybe a lot of) hardcoded hierarchy that tracks OBA

That's because the OBA hierarchy in question was, at least in part, created by Chris to split out the biological attribute ontology already implicit in GO.   (@cmungall - can you give more details on the history?)

Bit surprised that the diff is so small. I added a bunch of terms defined with reference to OBA:membrane potential.  Thought I'd see some of those in here.  I assume that the effect is small right now because the switch to dynamic classification based on this has not been made for most of this part of GO

I'm worried that removing reference to OBA is a step backwards - increasing the need for asserted multi inheritance in GO and reducing its cross-OBO integration.  This is at a point where we have resources available to curate traits/attributes and are beginning an effort to do so.  

I'd favour fixing ASAP by broadening the range of regulates (as a temp fix), but considering moving to a relation for regulation of quality in future. Maybe we should also have a meeting to review the relationship between GO and OBA?  I suspect we could come up with a quick semi-automated way to make this branch properly dynamic.

**Comment by pgaudet** [comment]
In GO, many 'regulation of quality' terms have other parents, or represent phynotypes that can be captured with other terms. See all direct children of 'regulation of biological quality' here:, with number of annotations and suggested action: 
https://docs.google.com/spreadsheets/d/1kIU37hIQcnMy_HBfelmkEUcBu-IUXbdQZvJlRBGx18s/edit#gid=0

I'll put that on an ontology call discussion. Meanwhile if you think RO definition of regulates needs to be widen, please go ahead. 

Thanks, Pascale
