### ISSUE TITLE
location of 'phagocytosis' in the ontology

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#16576]
Hi
Looking at the definitions of the following related terms I think that their relationship needs to be revised:
 GO:0006897 endocytosis
A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a small region of the plasma membrane to form a new membrane-bounded vesicle. 
>is_a GO:0006909 phagocytosis
An endocytosis process that results in the engulfment of external particulate material by phagocytes. The particles are initially contained within phagocytic vacuoles (phagosomes), which then fuse with primary lysosomes to effect digestion of the particles. 

The term GO:0006909 phagocytosis describes the process of fusion with lysosomes which is not an 'endocytic' process.

I think that  GO:0006911 phagocytosis, engulfment should be an is_a child of GO:0006897 endocytosis, rather than a grandchild (which is what it is currently). As well as remaining a_part_of GO:0006909 phagocytosis.

I think that  GO:0044248 cellular catabolic process should be the new is_a parent to GO:0006909 phagocytosis.

Thanks

Ruth

**Comment by ukemi** [comment]
Hi @RLovering, 

I'm doing a bit of background reading to be sure that this is the way protists work too, but I think that eventually all phagocytic vesicles fuse with lysosomes. Most of the papers I have looked at say that phagocytosis is a type of endocytosis, but then they do go on to describe what happens to the phagosome after it is formed. So I guess the big question is do all types of endocytosis end with the formation of the endocytic vesicle or can the process extend? I don't think our definition of endocytosis excludes the other steps of phagocytosis, because it is classified as a vesicle-mediated transport process. This seems do have been done purposefully since the subsequent fusion steps are part of phagocytosis. If we agree with this, then phagocytosis is a legitimate type of endocytosis. This seems to be the view of the community. I do think there needs to be some work on this part of the ontology. It seems that there are relationships missing.

**Comment by RLovering** [comment]
OK if that is how you feel. I just think that endocytosis starts with the engulfment step, and ends when the plasma membrane is separated to form a vesicle. 

The problem with including the fusion of this vesicle with a lysosome is that you might then want to include receptor recycling. At present  GO:0001881 receptor recycling does not have a relation to endocytosis or vesicle mediated transport. But this is a mess too we have: GO:0038019 Wnt receptor recycling definition: The process that results in the return of a Wnt receptor to an active state at the plasma membrane. An active state is when the receptor is ready to receive a Wnt signal. Internalized Wnt receptors can be recycled to the plasma membrane or sorted to lysosomes for protein degradation. 
So potentially Wnt receptor recycling can be the equivalent of phagocytosis, but it does not have a transport parent.
I guess this needs to be added to the ontology revision list. 
Too much to fix on a Friday afternoon
Have a good weekend
Ruth
