### ISSUE TITLE
'response to chemical' parentage?

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#16572]
Right now, **response to chemical** is a direct child of **response to stimulus**.

![image](https://user-images.githubusercontent.com/4998871/48035482-03dc4780-e119-11e8-8888-b84e61bf00e4.png)

@lreiser and I think that it could make sense to move the parentage down one so that **response to chemical** is a direct child of  **response to abiotic stimulus**.  

![image](https://user-images.githubusercontent.com/4998871/48035507-2ff7c880-e119-11e8-91d5-b2acb2d03c27.png)

http://amigo.geneontology.org/amigo/term/GO:0050896#display-lineage-tab

The definitions of the biotic/abiotic stimulus terms follow.

> Def of 'response to abiotic stimulus': Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an abiotic (non-living) stimulus.

All chemicals are non-living. Makes sense to place them here. (Water, oxygen are already here.)

> Def of 'response to biotic stimulus': Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a biotic stimulus, a stimulus caused or produced by a living organism.

Many chemicals are produced by living organisms.  Makes sense for some chemicals to be here.

These two definitions are not mutually exclusive.  Can someone clarify please?  It could be that 'response to abiotic stimulus' needs to be more tightly defined. I tried digging into old GH and SF tickets but couldn't zero in on the decision to split out 'response to chemicals' but I suspect it might have something to do with the chemical split above.

**Comment by ukemi** [comment]
It seems that there are many axes of classification here: biotic versus abiotic, endogenous versus exogenous, etc. Amelia brought up issues with this long ago and these terms have always been a bit problematic (in my opinion). I have always gone the route of co-annotation for these terms, but I must admit I don't like to use them unless I know an exact mechanism.

**Comment by ukemi** [comment]
I think the response to chemicals was probably a result of the cross-product work that we did long ago. They are easy to factor out based on ChEBI.

**Comment by pgaudet** [comment]
Are these grouping terms necessary ? We could probably obsolete '(cellular) response to biotic stimulus' (272 EXP, mostly IMP by CGD) and (cellular) response to abiotic stimulus' (7 EXP annotations). 

I dont think these add much structure to the ontology.

**Comment by deustp01** [comment]
Estrogens are chemicals synthesized by cells in response to biotic stimuli. Where do they go in the new scheme? This looks like a good example in support of Pascale's suggestion just now - trying to divide stimuli cleanly and intuitively into two classes is really hard and we don't get much for it.

**Comment by ukemi** [comment]
There is really no new scheme. Amelia had the same issue with proteins or peptides that are receptor ligands. I think one of her questions was whether or not all signaling pathways should be housed here.

**Comment by srengel** [comment]
i agree that it is problematic to put response to chemicals under response to abiotic (def = not made by living organism) stimulus because some chemicals are made by living organisms (Peter's estrogen example) so by definition are not 'abiotic'.

we don't annotate to response to chemicals at SGD.  we put all that stuff in phenotypes.

**Comment by tberardini** [comment]
@srengel 
> i agree that it is problematic to put response to chemicals under response to abiotic (def = not made by living organism) stimulus because some chemicals are made by living organisms (Peter's estrogen example) so by definition are not 'abiotic'.

The definition of 'response to abiotic stimulus' does not explicitly say "_not made by living organism_".  The current definition ends with "..._as a result of an abiotic (non-living) stimulus._"  This is why I suggested that 'response to abiotic stimulus' needs to be more tightly defined. (see above)

A more explicit def of 'response to abiotic stimulus' would clarify why 'response to chemical' is not a child of that term.

**Comment by srengel** [comment]
Hi @tberardini i wasn't talking about the definition of the term, but rather the definition of the word 'abiotic', which is 'not made by a living organism'.  i thought you suggested making response to chemical a child of response to abiotic stimulus.  perhaps i misunderstood.  i agree with you that a more explicit def of 'response to abiotic stimulus' would be good.

**Comment by tberardini** [comment]
@srengel Ah yes. Got it.  Thanks.  

I suggest "...as a result of an abiotic (not derived from living organisms) stimulus."

Actually, do **response to oxygen stimulus** and **response to water** (better as **response to water stimulus**, currently a synonym) belong under '**response to abiotic stimulus'** then? They are by-products of photosynthesis.

**Comment by pgaudet** [comment]
Let's get rid of these terms?  They seem to create confusion more than anything.

**Comment by tberardini** [comment]
> Let's get rid of these terms? 

Which ones?

**Comment by pgaudet** [comment]
See my comment avove: 

> We could probably obsolete '(cellular) response to biotic stimulus' (272 EXP, mostly IMP by CGD) and (cellular) response to abiotic stimulus' (7 EXP annotations).

**Comment by tberardini** [comment]
@pgaudet : Checking:  just the cellular versions or all four? Note that both non-cellular versions are used as slim terms.  They are also marked as 'do_not_manually_annotate'. We (plant) find them useful as slim terms and would like to keep them.

subset: goslim_metagenomics
subset: goslim_plant

**Comment by pgaudet** [comment]
Hi Tanya, 

I just checked the annotations to plant genes to these terms. 

**RESPONSE TO ABIOTIC STIMULUS**
ALL EVIDENCE CODES
(3592)	response to external biotic stimulus
(3592)	response to external stimulus
(3586)	response to other organism
(2838)	defense response
(2827)	defense response to other organism


EXP ONLY
(1819)	response to external biotic stimulus
(1813)	response to other organism

cellular response to biotic stimulus (only EXP available)
(7)	cellular response to molecule of bacterial origin
(3)	cellular response to external biotic stimulus
(2)	positive regulation of autophagy in response to ER overload
(1)	ER overload response
(1)	lipopolysaccharide-mediated signaling pathway


**RESPONSE TO ABIOTIC STIMULUS**
They fall in two general classes (see annotations here: https://docs.google.com/spreadsheets/d/1XvZ60fCi0Q30Vi2IxsouTCoShY3PkgSa1q7LNL_OpbI/edit?usp=sharing - note there are multiple sheets) 
- response to stress
- response to light stimulus
Wouldn't it be better to have two slim terms rather than lumping these rather unrelated processes together? 

Note that 'response to stress' is also in the plant slim. Response to stress includes both biotic stress and abiotic stress, so it must contain almost the same annotation as 'response to biotic stimulus' + response to abiotic stimulus'

----
Personally I would put the plant slims to these terms:
- GO:0006950 response to stress (already there)
- GO:0009416 response to light stimulus. 
These two classes mostly don't overlap (see matrix screenshot below - limited to Viriplantae) 

The most useful class under response to biotic stimulus is 'GO:0051707 response to other organism', but most annotations are already under 'response to stress', via 'defense response to other organism', so I don't know if that's useful or not. 

@valwood may have some insights to add about useful slimming classes. 

Thanks, Pascale


<img width="738" alt="image" src="https://user-images.githubusercontent.com/4782928/48112559-40ae5880-e257-11e8-8c48-7a3d62385967.png">

**Comment by ValWood** [comment]
I agree with your suggestion. I would avoid "response to bioltic stimulus" particularly as is is an ancestor of response to stress.


I try to avoid "response to" terms in slims because they are used very badly for general chemical sensitivities when nothing is known.

At PomBase we now only use in extensions to  *extend* the real process.

So we would do 
GO:0051403    stress-activated MAPK cascade part_of response to oxidates stress
or
GO:0043556    regulation of translation in response to oxidative stress (which we could post compose)

We try to nail down the process, so we don't have "response to stress" in the  general, or Pombase slim except for 

"response to toxic substance". I plan to remove this term when  the gene products it currently pulls in are annotated  correctly to aspects of    "detoxification".

Sorry this isn't much help. I think you are correct that  is is better to split these rather than lump because they are quite different.

@tberardini  do you find that a lot of things do not slim at all if you leave out "response to stress"?

**Comment by selewis** [comment]
@cmungall - couldn't "stresses" (or stressing or causes_stress) be consider a relationship type between some external environmental factor (i.e. from EnvO or ChEBI or some external ontology). It does seem like we're handling this incorrectly and it would perhaps be wise to step back and consider another way of handling responses to various types of stress. I'm thinking back to Scott Gilbert's book on development.

**Comment by tberardini** [comment]
@ValWood - Thanks for the suggestions. I was confused by this:

> I agree with your suggestion. I would avoid "response to bioltic stimulus" particularly as is is an ancestor of response to stress.

This is the current relationship that I see:

![image](https://user-images.githubusercontent.com/4998871/48295924-95afc180-e445-11e8-940f-c5b66888d7f5.png)

It would be great to continue discussion good slimming practices :) outside of this GH ticket.  I'll email you.

**Comment by tberardini** [comment]
I think, then, that the only immediate action necessary from my perspective is to expand the definition of 'response to abiotic stimulus' to be:

> Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an abiotic (not derived from living organisms) stimulus.

With that done, we could close this issue. Thanks, everyone, for your suggestions on slimming.
