### ISSUE TITLE
transcriptional activation by chromatin promoter-enhancer looping 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16617]
Following on from #16603 I would like to request:

1. chromatin looping
is_a ds_DNA loop formation
is_a chromatin remodelling

2. transcriptional activation by chromatin promoter-enhancer looping 

Also, GO:0071733 transcriptional activation by promoter-enhancer looping is_a GO:0090202 Gene looping - but enhancers can be located both upstream and downstream of the TSS?

PMID:28934464

**Comment by pgaudet** [comment]
Is looping really a process ? Or is it something mechanical that happens when all the proteins come together ? 
Also, the paper you cite mentions binding to a loop (the structure, which would be a CC term), rather than how gene products form loops. ("Our study demonstrates that the formation of a local genome loop plays a critical role in regulating the binding distribution of Rst2, a C2H2 zinc-finger TF, in the fbp1 promoter region during transcriptional activation. ") 

What genes would you annotate to that process?

**Comment by Antonialock** [comment]
hmm...it might be something mechanical that happens? I'm not sure what the difference is between a mechanical thing and a process...?...excuse the ignorance.. 

This is their model:

Model for the regulation of Rst2-binding via UAS loop formation. (A) In glucose-rich conditions, the fbp1 promoter region is packaged in closed chromatin. (B) After glucose starvation, Atf1 activates a cascade of mlonRNA transcriptions, thereby inducing chromatin-configuration change into an open state around UAS1 and UAS2. Rst2 might stabilize Atf1 binding to UAS1. (C) Rst2 and Php2–5 can bind to fbp1 UAS1 and UAS2, respectively. However, Rst2 binding to UAS2 is suppressed by the Tup11/12 corepressors. (D) Php2–5 binding at UAS2 induces local-chromatin remodeling into an open configuration around the TATA box, inducing the formation of a UAS loop. (E) Through the UAS loop, Rst2 bound to UAS1 associates with UAS2.

<img width="492" alt="screen shot 2018-11-14 at 16 16 31" src="https://user-images.githubusercontent.com/12727506/48496035-0fbabe80-e829-11e8-8841-2741b057c849.png">

If this is not a process then could 
 transcriptional activation by chromatin remodelling

be created? 

if it is worth it distinguishing different flavours of remodelling (I don't know) then could you create or  transcriptional activation by chromatin looping (just a child to chromatin remodelling - no separate term for chromatin looping)

**Comment by pgaudet** [comment]
Interesting ... We have 

'chromatin organization involved in regulation of transcription'
'chromatin organization involved in negative regulation of transcription'
'chromatin-mediated maintenance of transcription'
but no positive regulation!

**Comment by Antonialock** [comment]
is DNA bending a la GO:0044377 RNA polymerase II proximal promoter sequence-specific DNA binding, bending
in eukaryotes

regarded as a 'Dynamic structural changes to eukaryotic chromatin" ?

**Comment by pgaudet** [comment]
I think so

**Comment by Antonialock** [comment]
so presumably those transcription factors that positively regulate transcription by DNA bending could also be annotated to  transcriptional activation by chromatin remodelling ? @ValWood

**Comment by Antonialock** [comment]
how do biologists think of 'chromatin remodelling"? I wouldn't really think to annotate a TF to this term....but it fits the def in some cases? 
(when I think of chromosome remodelling I think of moving nucleosomes around, or packaging DNA more or less tightly)

**Comment by Antonialock** [comment]
(php2,5,rst2... are all TFs. If chromatin remodelling is not what is happening in the above diagram then how should it be described?)

**Comment by ValWood** [comment]
Presumably...but maybe they all do this? I don't know....

**Comment by ValWood** [comment]
> when I think of chromatin remodelling I think of moving nucleosomes around, or packaging DNA more or less tightly

yes me too.

@pgaudet  @RLovering  maybe we can ask  Colin & Co about this tomorrow on the txn call...

**Comment by ValWood** [comment]
You already did...

**Comment by ValWood** [comment]
Transcription group don't think 
GO:0071733  transcriptional activation by promoter-enhancer looping
should exist, since  rather than being a process, this is a *consequence* of the  DNA binding transcription factors and co-factors binding to DNA and to each other, and ortholgoanl tot he terms and processes normally used to  curate these events.
(ALso in this context the looped out region will be naked DNA not chromatin)
This term will be obsoleted, (11 EXP annotations)

Personally, I don't think it really makes sense to have the process term 
GO:0090579   dsDNA loop formation
The formation and maintenance of DNA loops that juxtapose separated regions on the same dsDNA molecule. PMID:15950878

without processual  context....

There are only 17 EXP annotations to this  (which include the 11 above).
Suggest to obsolete this too, unless it is required for chromatin looping during condensation, which  should be more specifically defined.

**Comment by mah11** [comment]
history of GO:0071733 is in #7293; I don't mind if it goes obsolete

**Comment by pgaudet** [comment]
The points raised here will be addressed in #20204
