### ISSUE TITLE
NTR negative regulation of viral RNA binding

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#16639]
negative regulation of viral RNA binding
standard def
is_a GO:1905215
PMID:21233210

<img width="726" alt="screen shot 2018-11-15 at 16 51 15" src="https://user-images.githubusercontent.com/12727506/48568195-b620c580-e8f6-11e8-85d2-362f6f32e86a.png">

**Comment by Antonialock** [comment]
Not sure if this is a useful annotation to have in addition to 
negative regulation of RIG-I signaling pathway

**Comment by hdrabkin** [comment]
NTR seems broader?

**Comment by Antonialock** [comment]
yeah....I meant to capture
ARL16 binds RIG-I
which prevents RIG1-I binding to viral RNA
to negatively regulate RIG-I signaling

but it doesn't really say that does it

**Comment by Antonialock** [comment]
Are there any MF terms that are suitable?
receptor antagonist activity ? or is that an odd choice?

**Comment by hdrabkin** [comment]
Not really my field; 
def of 'negative regulation of RIG-I signaling pathway"  has 
'as a consequence of the cytoplasmic pattern recognition receptor (PRR) RIG-1 (also known as DDX58) binding to viral RNA" so it's implicit?

**Comment by Antonialock** [comment]
Yes you are right. Thanks!

**Comment by Antonialock** [comment]
@ValWood 

just checking...do you think there is an MF term I can use here? Protein binding feels unsatisfactory (from a curator-wanting-to-make-annotations point of view  :-)  maybe it is sufficient with the BP)

**Comment by ValWood** [comment]
ARL16 protein binding RIG-I part_of 'negative regulation of RIG-I signaling pathway
would work.

OR

GO:0098772    molecular function regulator has_direct_input RIG-I part_of 'negative regulation of RIG-I signaling pathway
maybe?

I don't think you need to capture:
"NTR negative regulation of viral RNA binding"  its really  a MF in the process ontology...

if you know that ARL16 is directly inhibiting RIG-I 
https://www.ebi.ac.uk/QuickGO/term/GO:0039529
it's a given from  what RIG-1 does that you are inhibiting virus detection/binding.

Otherwise, it's a minefield:
https://www.uniprot.org/uniprot/O95786

Since it's  inhibiting the "sensor activity" (which is a MF type of binding )
It would be nice if the BP term "detection of virus"  was a "molecular function" instead
"RNA virus sensor" would say exactly what it did .....
(I strongly believe sensors should be MF terms)...but we aren't going to solve this one today....

Then you could do
GO:0098772    molecular sensor inhibitor has_direct_input RIG-I part_of 'negative regulation of RIG-I signaling pathway

Which would capture everything....

but as it is I think "binding" + "process"  is fine...

**Comment by ValWood** [comment]
which is the "unknown" here ;)

**Comment by Antonialock** [comment]
ok, "binding" + "process" sounds good.

cheers, happy with "binding" + "process"
