### ISSUE TITLE
NTR: Positive Regulation of Glucose Catabolic Process

### ISSUE THREAD

**Issue by mayursst** [geneontology/go-ontology#16652]
**Potential Go Term Name** — Positive Regulation of Glucose Catabolic Process
**Definition** — The positive regulation of the chemical reactions and pathways resulting in the breakdown of glucose, the aldohexose glucose-hexose.
**Aspect** — Biological Process
**Relationships**: Child term of 'glucose catabolic process (G0:0006007)' OR
Suggested parent term — 'Regulation of glucose catabolic process ';
Suggested Sibling Terms — 'Negative Regulation of Glucose Catabolic Process'
**References** — PMID:14677856, See Figure 1

**Comment by mayursst** [comment]
@sandyl27 @jimhu-tamu

**Comment by pgaudet** [comment]
Add a synonym to GO:0045821 positive regulation of glycolytic process ?

**Comment by ukemi** [comment]
I would prefer to use a more precise term. We are trying to avoid using regulation terms for annotation unless we know the mechanism of regulation. Otherwise, we don't really know if it is regulatory, upstream or part of a process. So in this case, can you use a finer grained term for annotation?

**Comment by jimhu-tamu** [comment]
IIRC, this is a case where a more precise term would not be appropriate because the readout is labelled CO2 release from glucose. We don't know from the data what metabolic steps are regulated. We should look at the paper again but it may be more appropriate to use something related to GO:0046626  regulation of insulin receptor signaling pathway

**Comment by ValWood** [comment]
closing?
