### ISSUE TITLE
ntr: protein localization to prospore septin ring

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#16695]
modeled on GO:1902935; to use to define phenotypes for PMID:20123972

[Term]
id: GO:new
name: protein localization to mating projection septin ring
namespace: biological_process
def: "A process in which a protein is transported to, or maintained in, a location within the prospore septin ring." [PMID:20123972]
synonym: "protein localisation in prospore septin ring" EXACT []
synonym: "protein localisation to prospore septin ring" EXACT []
synonym: "protein localization in prospore septin ring" EXACT []
synonym: "protein localization to forespore septin ring" EXACT []
is_a: GO:1902935 ! protein localization to septin ring

the destination CC is GO:0032169

**Comment by mah11** [comment]
EDITED to change to prospore ring

**Comment by srengel** [comment]
is this a fundamentally distinct process from other protein localization?  can't/shouldn't the destination be specified in the annotation_extension?  surely we don't want protein localization terms from every possible cellular place that a protein could go.  am i missing something?

**Comment by mah11** [comment]
As in many other cases, it would be exactly semantically equivalent to do a GO annotation with extensions. I've requested a precomposed term mainly because there is already a LOT of precedent for "protein localization to $CC" terms in the ontology (and secondarily because what I actually want to do is point a phenotype logical definition to a GO term, and it's a bit easier to use a precomposed GO term for that).

**Comment by vanaukenk** [comment]
@mah11  - there is certainly precedent for having these terms in the ontology, however, judging from the number of IMP annotations associates with them, I worry a bit that they are often used to capture phenotypes rather than distinct mechanisms for localizing gene products.  
In this particular case, would you also use the term for GO annotation or just for the phenotype term's logical def?

**Comment by ValWood** [comment]
I have been wondering about this too.

@mah11 could we precompose these terms using GO but localization + component?
This way we do not instantiate terms in GO that would never be used for GO annotation, and this would prevent curators using these terms to describe phenotypes.

A lot of localization is "autonomous", but we see "localization phenotypes" that we want to capture (localization dependencies are an important first step in reconstructing pathways). I agree that we don't really want  GO terms for localization to every component (probably even the ones which are not only 'phenotypes' longer term, but especially these). However,  we DO need a way to capture specific localizations in the context of the process that the act in.

General thoughts from discussions with @pgaudet - (mainly from the perspective of the  transcription refactoring and kinetochore assembly processes): 

Cellular localization in GO is broadly 2  things
i) transport
ii) recruitment
(sometimes with elements of both, transport system moves things somewhere, recruitment factor maintains localization)

Here we are concerned with 'recruitment'  which is really a molecular function, but historically we have captured it in biological process with 
"protein localization to x"

Obviously "recruitment to chromatin" is "localization" but this isn't really the process we are trying to capture. More often it's assembly (i.e of the replisome, transcription initiation complex, heterochromatin formation etc). Clearly, localization happens but there are better ways to capture this. For example, the localisation to the kinetochore as part of “kinetochore assembly” would be:

MF “molecular adaptor” XXXX part_of kinetochore assembly
MF “molecular adaptor” XXXX part_of chromatin assembly

Even better, if there was a specific "molecular adaptor" term for "recruitment". This term could have a MF-BP link to "localization", so the localization would implicitly be captured "behind the scenes".

To do this  we need a more explicit "adaptor" type MF term to describe "recruitment"
eg. MF “recruitment adaptor” part_of  BP "kinetochore assembly"
captures the context in a way that "protein localization" insert_relationship "kinetochore"  doesn't.

We could then retire terms like
"protein localization to kinetochore involved in kinetochore assembly"
and possibly even
"protein localization to kinetochore"

because we could still do
“recruitment adaptor” XXXX part_of  "process localization is required for"
