### ISSUE TITLE
New term: small molecular sensor activity? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#16747]
I am looking into creating a new grouping term to group 

* GO:0035991 nitric oxide sensor activity: def: Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of nitric oxide (NO).
* GO:0019826 oxygen sensor activity: Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of oxygen (O2).
* calcium sensor activity
* sterol sensor activity
* etc 

New term would be: 
'small molecule sensor activity' : 
Binding to a small molecule and eliciting a change in the protein's activity in response to the intracellular level of that small molecule. 
Comment: This does not include signalin

Child of molecular transducer activity. 

~Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of a molecule.~

**Issues:** 
* This sounds awfully like a BP 'response to' - we should redefine or consider obsoleting. 
* GO:0035991 nitric oxide sensor activity has 0 annotations, but cites PMID:21491957, that talks about GC being regulated by nitric oxide. 
* GO:0019826 oxygen sensor activity has a few annotations. Interestingly, all are converging to signaling by cAMP or cGMP in response to NO or O2. 

Oxygen sensing seems to be more of a process than a function: 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4556828/figure/F1/

@ValWood 
Any thoughts ?

**Comment by ValWood** [comment]
I still think we need it. I thought there was an open ticket about this but I can't find it.

The sensor term needs to be much more specific

 Interacting selectively and non-covalently with  a molecule, often a chemical element in order to ****detect (changes in?)  the cellular level of a molecule**** and initiate processes in response these changes. 

I don't think we need to mention "conformational change" this is usually what happens, but it's mechanism.
Detection needs to be in there if we have it.

The process is usually, but not always  signalling, but how would you describe the thing that "detects" the molecule, just binding? I guess we could use "receptor"  but some sensors aren't really receptors. For example some transcription factors are themselves sensors. There seem to be quite a few "sensors" feeding into signalling.

It's quite different from "response to"  which is so general, even broader then signalling.

**Comment by ValWood** [comment]
Found this:
https://github.com/geneontology/go-ontology/issues/12891

**Comment by pgaudet** [comment]
Hi @ValWood 
I discussed this with @thomaspd . He was planning to add molecular sensor in his version of the MF refactor. However his proposal was quite a bit more complex than what we have started to implement. He had divided every function into what we now call 'molecular activity' (and that he was referring to as 'role'), and 'mechanism'. In the end, every function also had a mechanism, and these were to be part of molecular activities with the relation 'has necessary component'. 

Sensor was supposed to be such a mechanism - sensing is binding to something and eliciting some response. The sensing aspect (mechanistic) is a type binding. (In the end we didn't implement all these compound functions, we are trying to keep everything more simple. )

So, to create that new term I looked at how it has been used, to make sure I placed it correctly in the ontology. I found two sensing mechanisms: 

1. small molecule-dependent enzyme activation: 
* GO:0035991 nitric oxide sensor activity has 0 annotations, but cites PMID:21491957. The abstract nicely summarizes the process: "Eukaryotic nitric oxide (NO) signaling involves modulation of cyclic GMP (cGMP) levels through activation of the soluble isoform of guanylate cyclase (sGC)" 
that talks about guanylate cyclase being regulated by nitric oxide. One could conceivably annotate guanylate cyclase to **(GONEW) nitic-oxide-dependent guanylate cyclase activity**, which would be part of "response to intracellular nitric oxide levels" (or maybe we can have a more precise term, but from the paper I cannot tell anything else). 
* GO:0019826 oxygen sensor activity has annotations to different sensing mechanisms: 
** one is via guanylate cyclase activation (PMID:19323996), for which we could create a new term **(GONEW) oxygen-dependent guanylate cyclase activity**
** there is also adenylate cyclase activation (PMID:24082109) 
** another is via oxygen sensor histidine kinase response regulator (see for eg PMID:19463006) - again we could create a new term 
** oxygen-sensing diguanylate cyclase and phosphodiesterase (PMID:19764732)

2. small molecule-dependent transcription factor activation - for example PMID:11595184
GO:NEW oxygen-dependent transcription factor activity

That would probably involve restoring some of the transcription factor terms that I merged, such as 'RNA polymerase II transcription factor activity, zinc ion regulated core promoter proximal region sequence-specific DNA binding' (that would be simplified to zinc-dependent/responsive DNA-binding transcription factor activity), but at the same time, it would make it clear that the corresponding BP terms really mean 'response to x': 
I mean, an annotation to "regulation of iron ion transport by transcription from RNA polymerase II promoter" could be replaced by "iron-dependent/responsive DNA-binding transcription factor activity" and "response to iron levels" 

What do you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't know the best way to handle sensors. 
However  here are some thoughts.

1.  include 

~GO:0000155 phosphorelay sensor kinase activity~
GO:0000156    phosphorelay response regulator activity

in the list of existing terms

although I'm not sure if the kinase is "strictly" the sensor ? 
![sensor](https://user-images.githubusercontent.com/7359272/49741181-be69e780-fc8d-11e8-8361-6b44186ea57b.jpg)

I guess that really depends how we define the sensor. I was thinking we needed something for "detection" of "levels" which could be plugged with any of the activities it was activating or inhibiting.

2. The list above is only the tip of the iceberg. Sensors exist in many proteins (for example many catalytic enzymes act as sensors. Some have moonlighting functions as a result of the "sensor activity". For example a catalytic enzyme can become a transciptional activator/ or repressor

or here: where tdh1 https://www.pombase.org/reference/PMID:18406331
acts as an oxygen sensor and activates oxidative stress pathway.

"In response to H2O2 stress, Cys-152 of the Tdh1 GAPDH is transiently oxidized, which enhances the association of Tdh1 with Mcs4." This is the type of thing I want to capture with "sensor activity". Is this too mechanistic? I just have an urge to capture this in some way. It feels really useful.

because of the absence of "sensor activity" this is currently very  crudely annotated to 

GO:0070994 | detection of oxidative stress
(this term is defined like an activity

defined
The series of events in which a stimulus indicating oxidative stress is received and converted into a molecular signal.

i.e  "oxygen sensor" would be detection of oxygen levels and *conversion* into a molecular signal  (this is usually  a conformational change but..we would not need to say this, this is the mechanistic detail).

3.  You could *precompose* all of the sensor activities as 

oxygen-activation  phosphorelay sensor kinase activity

BUT  it doesn't feel very sustainable.... for example some  phosphorelay systems detect oxygen to inhibit phosphorelay systems regulating nitrogen fixation. The terms would get very convoluted.

In fission yeast one mechanism for monitoring  hypoxia involved detecting ergosterol levels
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2837984/

" In that system, the alpha subunit of HIF is negatively regulated under normoxic conditions by the members of the 2-oxoglutarate Fe(II) dioxygenase prolyl hydroxylase (PHD) family of enzymes. PHDs bind directly to oxygen and catalyze the hydroxylation of HIF alpha, resulting in its ubiquitinylation and proteasomal degradation. When oxygen levels are low, PHDs can no longer catalyze this reaction and HIF is stabilized and activates the transcriptional response under low-oxygen conditions. Similarly, S. pombe Ofd1 negatively regulates Sre1N stability in an oxygen-dependent manner (Fig. 2A) (20)."


again I guess
oxygen-activated peptidyl-proline dioxygenase activity
works....


4. We should separate acting as a sensor activity (actual detection) from  the more general use of the word "sensing" as in "oxygen sensing" to represent the entire pathway.


I'm happy to either have a "sensor activity" 
or request 
x-activated y activity

**Comment by ValWood** [comment]
oxygen sensing seems to be a general role for 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3337712/
dioxygenase prolyl hydroxylase (PHD)

**Comment by pgaudet** [comment]
So, as the first step, I added this term: 

[Term]
id: GO:0140299
name: small molecule sensor activity
namespace: biological_process
def: "Binding to a small molecule and eliciting a change in the protein's activity in response to the intracellular level of that small molecule." [PMID:26328879]
synonym: "small molecular sensor activity" EXACT []
is_a: GO:0003674 ! molecular_function


with the following children: 
* 'cadmium ion sensor activity'
* 'calcium ion sensor activity'
* 'carbon monoxide sensor activity'
* 'copper ion sensor activity'
* 'nitric oxide sensor activity'
* 'osmosensor activity'
** 'osmolarity-sensing cation channel activity'
* 'oxygen sensor activity'
* 'phosphorelay sensor kinase activity'
* 'sterol sensor activity'

@ValWood , why do you say that the phosphorelay response regulator activity is the sensor ? 
The 'sensor kinase' transfers the phosphate group to the response regulator - but presumably the sensor does the sensing ? 

Let me know if this part is OK. 
Thanks, Pascale
