### ISSUE TITLE
add taxon constraints for cilium and related terms (exclude Angiosperms)

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#16767]
In the process of reviewing some other annotations I noticed that some Arabidopsis proteins have been annotated to cilium terms from PAINT curation.
For example
http://amigo.geneontology.org/amigo/gene_product/TAIR:locus:2009610
is annotated to 

GO:0061512 (protein localization to cilium)
and
GO:0005929 (cilium)
Looking at taxon constraints 
cilium is limited to eukaryotes 
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0005929#term=history
and GO:0061512 (protein localization to cilium)
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0061512#term=history

I am pretty sure that we can include Angiosperms as a taxon constraint for this. There are some basal Gymnosperms with flagellated sperm tho.

**Comment by vanaukenk** [comment]
@lreiser 
Can I get your input on exactly which NCBI taxon ID I should use for the restriction?  I'm looking at this branch and want to make sure I select the correct one:
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=58023&lvl=3&lin=f&keep=1&srchmode=1&unlock

Thanks.

**Comment by vanaukenk** [comment]
Thanks @lreiser 
The following taxon constraints for GO:0005929 'cilium' already exist:

![image](https://user-images.githubusercontent.com/1730534/50606851-2bd7f500-0e95-11e9-88cc-ceef121bf0aa.png)

I can add the same taxon constraints for GO:0061512 'protein localization to cilium'.

In the meantime, I'd suggest also adding a ticket to go-annotation so that the PANTHER family annotations can be reviewed.

There has been a lot of discussion about incorporating taxon constraints into PAINT curation, but I don't know the current status of that work, and these PAINT annotations are still coming through in  the various pre- and post-processed PAINT annotations that I can see on the snapshot release.

**Comment by lreiser** [comment]
@vanaukenk 
Oh interesting. I thought I checked on the constraints for cilium. Well that sounds good. I will open a ticket on annotation thread. Thank you.

**Comment by ukemi** [comment]
@balhoff  should we have 'results in transport to from or in' o 'never_in_taxon -> 'never in taxon'?

**Comment by cmungall** [comment]
might there be some host-pathogen exceptions?

**Comment by vanaukenk** [comment]
Added taxon constraints for 'protein localization to cilium'.  I'll close this ticket for now.
If we want to continue the discussion of property chains, perhaps a new ticket would be best.
@ukemi @cmungall
