### ISSUE TITLE
recent ontology changes make  previously used terms unavaiable

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#16776]
Reported here

https://user-images.githubusercontent.com/12727506/49687772-cdbb2a80-faff-11e8-8637-951a4f0a643b.png

https://github.com/pombase/canto/issues/1710

and here:
https://github.com/geneontology/go-ontology/issues/16687

These terms have "only in" taxon restrictions. But these restrictions should not restrict fungi?

**Comment by balhoff** [comment]
@ValWood I looked at the first two terms in the current ontology snapshots and I don't see anything unusual. Both are restricted to only Fungi. I don't know much about how your filtered ontology is made. Are the terms being removed by owltools? If so, maybe @kimrutherford can send me the command being used.

**Comment by balhoff** [comment]
Thanks @kimrutherford, I see what is causing the problem now, but not sure yet how to fix it. There are some additional axioms recently added in go-plus, for example when class `C` is subclass of `'only in taxon' some Fungi`, there is another axiom `C` subclass of `'in taxon' only Fungi`. For some reason this is confusing owltools, although it really shouldn't interfere. I will talk with @cmungall about what owltools is doing. When I created a version of go-plus with these lines filtered out, the correct output was generated. The problem is in owltools.

**Comment by ValWood** [comment]
@cmungall any workaround you can think of for this? It makes any "only in" taxon unavailable to us. This is many, many terms.
v

**Comment by balhoff** [comment]
I'm working on an update to owltools.

**Comment by balhoff** [comment]
@kimrutherford could you please test the latest owltools master branch? I made an update adding an option that you will need to use (`--perform-macro-expansion false`). So it would be like:

`owltools /tmp/go-plus.owl --reasoner elk --make-species-subset -t NCBITaxon:4896 --perform-macro-expansion false -o -f obo /tmp/go-plus-pombe-only.obo`

Would you be able to update your production owltools?

**Comment by ValWood** [comment]
Sorry for causing you pain. Kim will likely test tomorrow now  as he is in New Zealand...

**Comment by balhoff** [comment]
Sounds good, not painful at all. :-)

**Comment by kimrutherford** [comment]
> could you please test the latest owltools master branch?

Thanks!  That looks good.  The terms are back in the output when I run owltools manually with `--perform-macro-expansion false`.

We'll change our ontology updating to use the master owltools.

I think this can be closed.

Thanks for the quick fix Jim.

**Comment by balhoff** [comment]
Good!

**Comment by ValWood** [comment]
Hmm, something has gone really wrong. It might not be to do wit this but this seems a good place to begin.


Many of our annotated GO terms now don't slim to anything.
https://www.pombase.org/gene_subset/non_go_slim_with_bp_annotation
This list now has  586 entries. On a normal day it has fewer than 20.....


here is an example
https://www.pombase.org/gene/SPBC713.06
should slims to DNA repair

https://www.pombase.org/gene/SPAC7D4.03c
should slim to signalling

etc

**Comment by ValWood** [comment]
owl tools now possibly ignoring part_of relationships?

**Comment by balhoff** [comment]
Hi Val, which ontology file do you use for that (and what is its date)? Which tool do you use to make your slim?

**Comment by balhoff** [comment]
The part_ofs seem to  be there in the file; maybe Kim will have some ideas for figuring this out. I will be traveling all day tomorrow—will check back when I am back home.

**Comment by balhoff** [comment]
Thanks for figuring this out @kimrutherford! I have not changed anything in owltools related to that, so I'm not sure why the output is different in the newer version. This is stuff that @cmungall is much more familiar with; hopefully he will have an idea about what the source of this change is.

**Comment by kimrutherford** [comment]
Thanks Jim.  We were running quite an old owltools so the change from relation term name to ID in the output could have happened ages ago and we wouldn't have noticed.

**Comment by cmungall** [comment]
There hasn't been any change to that code since 2013: https://github.com/owlcollab/owltools/blob/master/OWLTools-Core/src/main/java/owltools/io/ChadoGraphClosureRenderer.java

It was always the intent that the field was populated by an ID, so it may be that you were always relying on buggy behavior, possibly fixed by #247 7 months ago. It would be easy to add an option to show both ID and shorthand form

**Comment by kimrutherford** [comment]
> It would be easy to add an option to show both ID and shorthand form

Thanks Chris.  It's a quick fix for us to cope with the ID instead so we shouldn't need an extra option.

**Comment by ValWood** [comment]
thanks all, closing again.

**Comment by ValWood** [comment]
Hi,
I  have the same issue again.
This term
https://www.ebi.ac.uk/QuickGO/term/GO:0033573

is no longer available in Canto, but should be?
![term](https://user-images.githubusercontent.com/7359272/50169748-189a2680-02e6-11e9-8317-6371f812b566.jpg)

**Comment by kimrutherford** [comment]
I've just run owltools manually with `--perform-macro-expansion false` and GO:0033573 is missing from the output.  QuickGO has "cellular organisms" as the only taxon restriction for GO:0033573 so I think it should be there.

My command line was:

```
(cd /tmp/; wget -N http://purl.obolibrary.org/obo/go/extensions/go-plus.owl) 
cd go-svn/ontology/extensions
owltools /tmp/go-plus.owl --reasoner elk --make-species-subset --perform-macro-expansion false \
    -t NCBITaxon:4896 -o -f obo /tmp/go-plus-pombe-only.obo
```

**Comment by balhoff** [comment]
Sorry for the slow reply! This one is due to an actual taxon constraint:

- 'high-affinity iron permease complex' SubClassOf 'capable of' some 'high-affinity ferric iron transmembrane transporter activity'
- 'high-affinity ferric iron transmembrane transporter activity' SubClassOf 'part of' some 'iron ion import across cell outer membrane'
- 'iron ion import across cell outer membrane' SubClassOf 'only in taxon' some Bacteria

**Comment by ValWood** [comment]
OK, closing this will open a ticket for the taxon restricton fix.
Thanks

v

**Comment by ValWood** [comment]
Hi,

This term is still unavaiable. Should thi
