### ISSUE TITLE
Definition of 'symbiont process' is circular

### ISSUE THREAD

**Issue by dillerm** [geneontology/go-ontology#16909]
The definition states that a symbiont process is “A process carried out by symbiont gene products that enables a _symbiotic interaction_ with a host organism….” (emphasis added), while also having ‘symbiotic interaction’ as a related synonym. Thus you have essentially said that a symbiotic interaction is a process ... that enables a symbiotic interaction.

**Comment by ValWood** [comment]
I agree that the definition is bad.

Also all of this 
The various forms of symbiosis include parasitism, in which the association is disadvantageous or destructive to one of the organisms; mutualism, in which the association is advantageous, or often necessary to one or both and not harmful to either; and commensalism, in which one member of the association benefits while the other is not affected. However, mutualism, parasitism, and commensalism are often not discrete categories of interactions and should rather be perceived as a continuum of interaction ranging from parasitism to mutualism. In fact, the direction of a symbiotic interaction can change during the lifetime of the symbionts due to developmental changes as well as changes in the biotic/abiotic environment in which the interaction occurs. Microscopic symbionts are often referred to as endosymbionts.

should move to a comment. It is "definition  gloss".


The def is also  bit odd because  in this situation the 'host' is a symbiont.

maybe
as process resulting from a (mutually beneficial?)  interaction between two species. ?

**Comment by cmungall** [comment]
ccing @diatomsRcool @pbuttigieg who are working on definitions in the https://github.com/EcologicalSemantics/ecocore ontology

**Comment by diatomsRcool** [comment]
I agree that a symbiotic interaction should include parasitism to mutualism. I think the definition should specify a "close association" between two organisms. The ecocore definitions also emphasize that food and energy are being obtained via the relationship. I'm not sure GO wants to be that specific?
Would GO define symbiotic interaction and then stop there? Perhaps rely on ecocore for the subclasses?
I propose "process resulting from a close association between two individuals of different species."

**Comment by ValWood** [comment]
Hi 
@diatomsRcool @pbuttigieg it would be great if you could help in resolving the high-level terms in this area.

Personally (not sure what @cmungall thinks here!), and I'm not an expert, but  I'm thinking that it would make sense in GO if we didn't encode different types of "symbiotic interaction" based on pathogenicity and mutualism etc,  below "symbiosis" but concentrated on the actual  "molecular functions" and "biological processes".

We could then encode processes like
GO:0051828    entry into other organism involved in symbiotic interaction
simply as
"entry into other organism"  no need to disambiguate the type of interaction (which is  a phenotype/trait?)

but not necessarily try to capture whether an organism is a   (which is often strain/genotype dependent, rather than species dependent). 

It is really difficult to classify these continually variable concepts like pathogenicity/mutualism/symbiosis in GO. There are already existing tickets (somewhere)  suggesting the removal of  "pathogenicity"  because it's essentially a phenotype, not a process. 

We really, really need to get all of the stakeholders in this area together to resolve the high-level GO terms, ( and GO needs to decide what does, and what doesn't, belong in GO). At the moment it's pretty impossible to annotate gene products involved in pathogenic processes optimally. In fact, so far, I haven't managed to identify a single term GO where we could optimally describe the GO MFs and BPs for the test paper I was curating.....

**Comment by diatomsRcool** [comment]
> We could then encode processes like
GO:0051828 entry into other organism involved in symbiotic interaction
simply as
"entry into other organism" no need to disambiguate the type of interaction (which is a phenotype/trait?)

I think that sounds like a good idea. Leave the symbiosis stuff to ecocore and go focuses on the molecular.

**Comment by dillerm** [comment]
Thanks for the feedback, everyone. Putting the symbiosis classes in ecocore sounds like a great idea. We've defined several related classes in Apollo-SV that they might also want to consider taking (e.g., 'mutualism', 'parasitism', etc.) if they do decide to take 'symbiosis'.

As far as the definition goes, I actually like the old definition, which was "An interaction between two organisms living together in more or less intimate association."

**Comment by diatomsRcool** [comment]
> As far as the definition goes, I actually like the old definition, which was "An interaction between two organisms living together in more or less intimate association."

I like that one too

**Comment by pgaudet** [comment]
@diatomsRcool @dillerm 
The old definition was changed (admittedly to a poor definition) to indicate that GO 's scope is gene products, not organisms. 

A alternative proposal could be 

"A process carried out by symbiont gene products that enables the interaction between two organisms living together in more or less intimate association." - something along those lines ? Improvements are welcome ! 

Thanks, Pascale

**Comment by pgaudet** [comment]
I fixed the definition as I suggested. Please reopen if you have a different proposal to make.

**Comment by pgaudet** [comment]
@ukemi you added editors discussion - why ?

**Comment by ukemi** [comment]
I forgot to remove it. I wanted to query the group about who had the expertise to address these. Looks like you are the one.

**Comment by dillerm** [comment]
Hi @pgaudet , sorry for the inactivity on this. I think the process that your definition is referring to is separate from the symbiotic interaction itself. It may end up being better to move this class to another more appropriate ontology, after all.

**Comment by pgaudet** [comment]
Could be ! In GO it's a grouping class for all symbiont processes, but it does not describe the interactions between the two organisms.

**Comment by dillerm** [comment]
I noticed that the definition for 'symbiotic process' was recently revised, however the circularity still exists.

One proposal that I think a lot of people in this issue thread liked was the following:

> A process carried out by gene products in an organism that enables the interaction between two organisms living together in more or less intimate association.

However, I think a better, more concise definition exists, which is:

> An interspecies interaction between two or more organisms in intimate association.

I think this definition has the benefit of properly reflecting what its parent class is and of being more true to the nature of symbiotic interactions (e.g., lichen are a composite organism consisting of 3 organisms in a mutualistic interaction). I also think that there are some symbiotic interactions that are not carried out by gene products, for example a wasp laying its eggs in a caterpillar. I understand that GO's developers are concerned with ensuring that the ontology classes do not fall outside of the domain of gene products, but I think an argument can be made for not limiting this class to symbioses that are carried out by gene products. Namely, because this class serves as an important bridge for a wide variety of biological processes involving microorganisms and/or host organisms, all of which easily fall within the purview of GO, the use of a less restrictive definition that covers all instances of symbiotic interactions is justified. This would also allow for people who want to model symbiotic interactions that are not carried out by gene products to reuse the class, thus enabling orthogonality between their ontology and GO.
