### ISSUE TITLE
Aerobic glycolysis

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#16901]
Hi, I would need a GO term for aerobic glycolysis

Thanks 

Sylvain

Category: Process
Definition: aerobic enzymatic chemical reactions resulting in the breakdown of glucose to lactate in the presence of oxygen.

Note that in anaerobic glycolysis (see GO:0019659), glucose is converted to lactate in absence of oxygen.

I'm unsure about parent terms. One possibility would be
GO:0006007 glucose catabolic process

PMID:26029212
PMID:30700909

**Comment by ukemi** [comment]
In GO, canonical glycolysis begins with glucose being converted to Glucoes-6-phosphate and ends with pyruvate kinase forming pyruvate. The reactions in the pathway are the same whether oxygen is present or not. The fate of the pyruvate varies as you can see in figure 1 of the review that you cite. Although it is important whether or not glycolysis is taking place in the presence or absence of oxygen, the pathway is the same as far as its molecular functions. At one point we considered trying to incorporate the presence/versus absence of oxygen distinction, but it doesn't differ with respect to the core reactions. I think the distinction made is with respect to how glycolysis is regulated in aerobic versus anaerobic conditions and the fate of some of the intermediate molecules. Pinging @deustp01 because he and I have thought a lot about modeling glycolysis. PMID:27589964

**Comment by sylvainpoux** [comment]
Thanks David! I will use the canonical glycolysis term then

**Comment by ValWood** [comment]
Hi @sylvainpoux  
you can also use 
occurs_during GO:0036294    cellular response to decreased oxygen levels
as an extension to capture this.

**Comment by sylvainpoux** [comment]
Hi Val,
we don't use extensions and I don't think that we can associate aerobic glycolysis with decreased oxygen.  It is more an adaptation of metabolism to various changes, such as starvation.
Aerobic glycolysis is found in cancers, but not only

**Comment by sylvainpoux** [comment]
I will however use upstream_of canonical glycolysis as my paper concerns FOXK1 and FOXK2, 2 transcription factors that act upstream of glycolysis

**Comment by ukemi** [comment]
Yes. Normally glycolysis is negatively regulated when conditions are good. ATP and some other downstream products repress the pathway, while ADP stimulates it. In cancer cells, glycolysis was shown to run rampant, presumably as one of the way the cells cope with their need to have the energy to divide rapidly. This was known as the Warburg effect. It turns out that normal cells also undergo glycolysis in aerobic conditions, which is what Sylvain is trying to annotate.

**Comment by ValWood** [comment]
Ah OK!

**Comment by deustp01** [comment]
It looks like exactly the GO term that Sylvain is requesting already exists:  GO:0019661 glucose catabolic process to lactate via pyruvate def: The anaerobic enzymatic chemical reactions and pathways resulting in the breakdown of glucose to lactate, via canonical glycolysis, yielding energy in the form of adenosine triphosphate (ATP). The term is an is_a child of  GO:0019660 glycolytic fermentation

If I understand right, it is "anaerobic" in the definition because no oxygen is consumed, not because no oxygen can be present.

Though it would surely confuse people, would it be appropriate to add "aerobic glycolysis" with PMIDs as an exact synonym for GO:0019661?

**Comment by cmungall** [comment]
editors, we can use PATO in the logical def here

>

**Comment by ukemi** [comment]
I don't think we want to do that. I think the point is that the process is the same whether it is in the presence or absence of oxygen. The difference is in the regulation of the process under aerobic or anaerobic conditions. I think @deustp01 and I should reexamine the textual defs. As he said, they might be misleading.
