### ISSUE TITLE
Similar classes of GO:0022838 and GO:0015267

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#16935]
Hello,

What is the difference between GO:0022838 substrate-specific channel activity and GO:0015267 
channel activity?  They have same definition

**Comment by ValWood** [comment]
You are correct. I think this was intended to group substrate-specific terms, as opposed to transporters with a  broad specificity. However, this would be practically impossible, because not all subtrates are tested, and we have put "ion channel activity" under here which covers a broad range of substrates. It isn't really appropriate information to encode in the ontology. I suggest a merge @pgaudet ?

**Comment by pgaudet** [comment]
Right, I will merge GO:0022838 substrate-specific channel activity (42 annotations/4 EXP) and GO:0015267 channel activity (many annotations)
