### ISSUE TITLE
RO version of 'results in organization of' *not* available for editing, but GOREL version is

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#16992]
I was creating a logical definition for 'flagellum attachment zone organization' today and didn't get the expected inferred parentage.

@ukemi and I looked at this and realized that in the editing window for creating the logical def, only the GOREL version of 'results in organization of' was available for use in the autocomplete.  The RO version of the relation was not there, even though existing terms in the ontology use it in their logical defs.

Eventually, we worked around it by adding the RO relation using its IRI, but we're unclear as to why the RO version isn't available for editing.

**Comment by balhoff** [comment]
This sounds like a Protege UI issue. You may have not encountered this in the recent past because for a while there was an issue with the IRI of the ro_pending file, so it wasn't getting loaded correctly. ro_pending is where the GOREL version is coming from. Since this is now in RO, shouldn't the relation be obsoleted in GOREL, and its sub properties be moved under the RO relation?

**Comment by ukemi** [comment]
Yes. It sounds like the merge of the GOREL property into the RO property is what we want. Are the sub properties appropriate for RO?

**Comment by balhoff** [comment]
@ukemi the conservative change would be to just obsolete the GOREL 'results in organization of' and make it the superproperty of those others within GOREL. We can separately look at whether the rest belong in RO.

**Comment by ukemi** [comment]
@balhoff this actually sounds like a good plan. I have my concerns about some of the relations in GO-REL and whether or not we should keep them. But, we need to look into this in the context of outputting conventional annotations from GO-CAM models and whether or not we can capture the relevant information in GO-CAM using the RO-sanctioned relations. If you obsolete the GOREL relations, I assume the RO one will then become available to ontology editors.

**Comment by balhoff** [comment]
Now I am a bit confused about `ro_pending.owl` vs. `gorel.owl`. This GOREL term ('results in organization of') and its children are not even in `gorel.owl`, obsoleted or otherwise. On the other hand, there is a real RO term for 'results in organization of' as well as 3 out of the 4 children seen in `ro_pending.owl`. Should they be obsoleted in `ro_pending.owl`?

**Comment by balhoff** [comment]
Btw, `ro_pending.owl` is the one being imported into GO.

**Comment by ukemi** [comment]
Maybe we should look at this together and @vanaukenk and I could show you the issue we had.

**Comment by balhoff** [comment]
Okay, I'm wondering if we could just delete `ro_pending.owl`. :-) Due to a technical issue it wasn't even being loaded into GO for a while anyway.
