### ISSUE TITLE
rename:negative regulation by organism of innate immune response in other organism involved in symbiotic interaction

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17012]
It takes a human quite a while to parse this term name.

Can it be exchanged for the exact synonym
"negative regulation of innate immune response of other organism"

(most of the stuff in the existing term name doesn't need to be there, it is implicit and and is covered by the definition)

And the same for any similar term in this area.

**Comment by pgaudet** [comment]
This term is odd. The immune response is always in the host, isn't it ? So this term should be merged into ' GO:0052170 negative regulation by symbiont of host innate immune response', shouldn't it ? 

I think A LOT Of merging could be done in this branch, since there is only one possible direction here. 


@mgiglio99 @jimhu-tamu  what d you think ? 

Thanks, Pascale

**Comment by ValWood** [comment]
The pathogen can regulate the host immune response (effector triggered immune supression). However we are finding that this "process' is represented in several places.

I would rename so this is easier to find/read, but I will also be suggesting merges once I relocate the other terms which have the same meaning.

**Comment by pgaudet** [comment]
OK. 

@mgiglio @jimhu-tamu do you agree with the merge ?

**Comment by ValWood** [comment]
do you mean rename. 

I just had a look, and I can't find anything with the same meaning...

**Comment by pgaudet** [comment]
I thought 
'GO:0052170 negative regulation by symbiont of host innate immune response'
and 'GO:0052309 negative regulation by organism of innate immune response in other organism involved in symbiotic interaction'
were equivalent (ie while GO:0052309 is more general, I don't think the opposite case exists:  'negative regulation by host of symbiont innate immune response' 
so one of the two terms is not needed. 

Pascale

**Comment by ValWood** [comment]
Yes @CuzickA and I agree these appear to be the same thing.

Parent
GO:0052170
negative regulation by symbiont of host innate immune response
Definition (GO:0052170 GONUTS page)
Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of the innate immune response of the host organism, the host's first line of defense against infection. The host is defined as the larger of the organisms involved in a symbiotic interaction.

GO:0052309    
negative regulation by organism of innate immune response in other organism involved in symbiotic interaction
Definition (GO:0052309 GONUTS page)
Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of the innate immune response of a second organism, where the two organisms are in a symbiotic interaction.

So merge. But rename to  my suggestion
"negative regulation of innate immune response of other organism"
but instead of
"negative regulation of innate immune response of host"

OK!  sounds good

**Comment by ValWood** [comment]
add a taxon restriction, never in Metazoa

**Comment by mgiglio99** [comment]
Hi, I know this issue is closed - sorry I didn't get a chance to comment on it sooner.
I just want to try to clarify why these terms originally existed.

Pascale said:
> I thought
> 'GO:0052170 negative regulation by symbiont of host innate immune response'
> and 'GO:0052309 negative regulation by organism of innate immune response in other organism involved in symbiotic interaction'
> were equivalent (ie while GO:0052309 is more general,
I know this structure seems redundant. However, when these terms were originally put in during the PAMGO time, the structure was meant to be able to encompass both symbiotic interactions when there was a host/hostee relationship and symbiotic interactions when the two organisms are equal players (e.g. lichen). The "...by other organism..." structure was for equal partnerships. The "...by host..." structure was meant to indicate things done by the host in a host/hostee relationship. The "...by symbiont..." structure was meant to indicate things done by the hostee, generally a microbe, in host/hostee interactions. Sadly, the word "symbiont" is also generally used for any member of a symbiotic interaction, although in PAMGO it was used for the more restricted "hostee" - this has caused confusion. 

Some of the mergers/changes that have been done have fundamentally changed this structure in some places but not others - which I think has led to more confusion. I totally understand if the decision is not to keep this structure. I see how confusing it can be. But I do think there needs to be some provision in the GO for non host/hostee symbiotic relationships. Perhaps not in the terms merged in this issue (as I don't off the top of my head have an example of an equal relationship involving negative regulation of innate immunity), but in general.
