### ISSUE TITLE
Query 'GO:0052308 pathogen-associated molecular pattern dependent modulation by organism of innate immune response in other organism involved in symbiotic interaction' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17040]
Hello, 

'GO:0052308 pathogen-associated molecular pattern dependent modulation by organism of innate immune response in other organism involved in symbiotic interaction' is defined as 
"Any process that involves recognition of a pathogen-associated molecular pattern, and by which an organism modulates the frequency, rate or extent of the innate immune response, the first line of defense against infection, of a second organism, where the two organisms are in a symbiotic interaction."

I take it to mean that symbiont gene products should be annotated, but all annotations are to host gene products: https://docs.google.com/spreadsheets/d/1EwF_QPEXzfMxkxUuRCipwzmpaGeTb2VfcDacoKkOPGA/edit#gid=0

1. We do have a term that seems appropriate for the host response: "GO:0002752 cell surface pattern recognition receptor signaling pathway", which is a child of 'innate immune response'. 

I think annotations should be moved to GO:0002752 
@tberardini @sabrinatoro @milarolo 

2. Are there cases of this process that should be annotated to the host ? (if not we can merge pairs of terms such as 
- GO:0052308 pathogen-associated molecular pattern dependent modulation by organism of innate immune response in other organism involved in symbiotic interaction
- GO:0052169 pathogen-associated molecular pattern dependent modulation by symbiont of host innate immune response 

What do you recommend 
@jimhu-tamu @mgiglio99 @cmungall @pmasson55 @nsuvarnaiari @jrr-cpt? 

Thanks, Pascale

**Comment by ValWood** [comment]
Based on the definition
"Any process that involves recognition of a pathogen-associated molecular pattern, and by which an organism modulates the frequency, rate or extent of the innate immune response, the first line of defense against infection, of a second organism, where the two organisms are in a symbiotic interaction."

it sounds as though this term was meant for the host genes involved in this pathway, but the term name sounds as though it applies to the pathogen.


There is also this term, describing the same process:

pattern recognition receptor signaling pathway
Biological Process
GO:0002221 
Definition 
Any series of molecular signals generated as a consequence of a pattern recognition receptor (PRR) binding to one of its physiological ligands. PRRs bind pathogen-associated molecular pattern (PAMPs), structures conserved among microbial species, or damage-associated molecular pattern (DAMPs), endogenous molecules released from damaged cells. PMID:15199967

and, I think I have seen others....

**Comment by ValWood** [comment]
You said that. I agree that is the correct  branch to annotate the host genes to.

**Comment by pgaudet** [comment]
>  I agree that is the correct branch to annotate the host genes to.
Do you mean 'pattern recognition receptor signaling pathway'?

**Comment by ValWood** [comment]
yep

**Comment by pgaudet** [comment]
OK, so annotations should be moved. I'll open an annotation ticket.

**Comment by mgiglio99** [comment]
pathogen-associated molecular patterns (or PAMPs)  occur in microbes that I think would only be the symbionts and this would not occur in the hosts. So the proposed merge would likely be ok in this case - although I'm hesitant about making these merges since I'm not an expert on the biology in this area. I'll see if I can track down any PAMGO people who have this expertise.

One thing we might want to consider is either changing this to microbe-associated molecular pattern (MAMP), or making a new MAMP term,  that would be able to be used with non-pathogens who can also elicit the same response.

**Comment by pmasson55** [comment]
Hello,

Concerning your first point Pascale, the  term GO:0002752 cell surface pattern recognition receptor signaling pathway", is too restrictive since there are plenty of PAMP receptors that are cytoplasmic such as RIG-I or MDA-5, even if they are termed receptors, they are never found on the cell surface...So, as Val said  the term GO:0002221 "pattern recognition receptor signaling pathway" is better for host proteins involved in the pathway.
Concerning the pathogens, we have two different parts:
1- Do we want to capture the PAMP themselves (can be dsDNA ssRNA or bacterial proteins for example):
2- Do we want to capture the proteins from the pathogens that actually modulate the PAMP receptor pathway (mostly inhibition). For example we have several terms for viruses such as:
GO:0039722: suppression by virus of host toll-like receptor signaling pathway
 GO:0039538 : suppression by virus of host RIG-I signaling pathway which are PAMPs.
In that case we should have more general terms such as "modulation by pathogens of host pattern recognition receptor signaling pathway"
The two GO terms Pascale mentioned  are quite misleading GO:0052308 and GO:0052169, I don't see what they want to capture.
Patrick.

**Comment by ValWood** [comment]
Hi Patrick,

1- Do we want to capture the PAMP themselves (can be dsDNA ssRNA or bacterial proteins for example):

Here my immediate thought was no, because this isn't the 'purpose' of the PAMP from the pathogen perspective? (although you might want to capture the type of PAMP in an extension (i.e chitin fragment  for a yeast, or RNA, protein etc, also presumably it isn't the entire molecule).

2- Do we want to capture the proteins from the pathogens that actually modulate the PAMP receptor pathway (mostly inhibition). For example we have several terms for viruses such as:
GO:0039722: suppression by virus of host toll-like receptor signaling pathway
GO:0039538 : suppression by virus of host RIG-I signaling pathway which are PAMPs.
In that case we should have more general terms such as "modulation by pathogens of host pattern recognition receptor signaling pathway"

Here I think yes because this is an "evolved" function.
But because it gets so complicated I wondered here
https://github.com/geneontology/go-ontology/issues/16909
If it is better to keep the concepts like 
pathogenicity/mutualism/symbiosis out of  GO.
It might even be better to keep virus,fungi,oomycete out too (maybe even an extension could capture the species). This would prevent the explosion of terms and make it much easier to find things.

**Comment by pmasson55** [comment]
Yes sure, 
We could have just "modulation of pattern recognition receptor signaling pathway" and mention somewhere else if it's viral or bacterial or else. We had this discussion for GO-CAM for models with different species. Instead of using terms such as "inhibition by virus" we would just put a molecular function for the viral protein and put somewhere the context ( Ex Model in the context of a viral infected cell for example) and we could get rid of these terms . Jim Hu suggested this kind of approach.

**Comment by ValWood** [comment]
I really, really like that plan. I'm lost in these terms!

**Comment by pgaudet** [comment]
I like @pmasson55 's  suggestion as well - and it's consistent with the other terms you mention. Right now we have two parallel ways of describing how the symbiont affects the host.

**Comment by pgaudet** [comment]
So, it seems like all 4 terms should be obsoleted, since they have been misused, and new terms created when we have proteins to annotate ? 

(The 4 terms being: 
'pathogen-associated molecular pattern dependent modulation by organism of innate immune response in other organism involved in symbiotic interaction'

'pathogen-associated molecular pattern dependent induction by organism of innate immune response of other organism involved in symbiotic interaction'

'pathogen-associated molecular pattern dependent induction by symbiont of host innate immune response'
'pathogen-associated molecular pattern dependent modulation by symbiont of host innate immune response'
) 



Thanks, Pascale

**Comment by pgaudet** [comment]
Obsoletion of GO:0052308 pathogen-associated molecular pattern dependent modulation by organism of innate immune response in other organism involved in symbiotic interaction and children

Dear all, 

The proposal has been made to obsolete: 

'GO:0052308 pathogen-associated molecular pattern dependent modulation by organism of innate immune response in other organism involved in symbiotic interaction’ 0 annotations

'GO:0052257 pathogen-associated molecular pattern dependent induction by organism of innate immune response of other organism involved in symbiotic interaction’ 0 annotations

'GO:0052033 pathogen-associated molecular pattern dependent induction by symbiont of host innate immune response’ 13 annotations

'GO:0052169 pathogen-associated molecular pattern dependent modulation by symbiont of host innate immune response’ 2 annotations


The reason for obsoletion is that the terms have been misused (and are being fixed, see https://github.com/geneontology/go-annotation/issues/2296) 
The terms 'GO:0002221 pattern recognition receptor signaling pathway' or 'GO:0002752 cell surface pattern recognition receptor signaling pathway’ are more appropriate for annotation of host proteins. 

Symbiont protein can be potentially be annotated to 'GO:0052034 negative regulation by symbiont of microbe-associated molecular pattern-induced host innate immune response’ 

These terms are not part of any slims (subsets). There are no mappings to these terms. 

Any comments can be added to the issue: #17040

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 25th, 2019. Unless objections are received by March 25th, 2019. we will assume that you agree to this change.

Thanks, Pascale

**Comment by mgiglio99** [comment]
Hi,
Couple questions - 
1. Is there a plan to make the term Patrick suggested -  'modulation of pattern recognition receptor signaling pathway'? Or rather stick with the existing term 'modulation by symbiont of microbe-associated molecular pattern-induced host innate immune response'?
2. For the microbe proteins that are the actual PAMPs,  is the thought to annotate to 'pattern recognition receptor signaling pathway' in a GO-CAM and somehow indicate this is in the host? Or would that information not be captured?

**Comment by pgaudet** [comment]
> Is there a plan to make the term Patrick suggested - 'modulation of pattern recognition receptor signaling pathway'? Or rather stick with the existing term 'modulation by symbiont of microbe-associated molecular pattern-induced host innate immune response'?

I'd like to create the term, however I'd like an example (ie, a paper to cite in the new term). Right now we only have host proteins annotated. 

> For the microbe proteins that are the actual PAMPs, is the thought to annotate to 'pattern recognition receptor signaling pathway' in a GO-CAM and somehow indicate this is in the host? Or would that information not be captured?

We could annotate to 'modulation of **host** pattern recognition receptor signaling pathway'; would that work ? 
I would like to ask though - what are we really trying to capture ? As far as I understand the PAMPs are a protein family that are recognized by the host, which triggers a defense response. Certainly the microbe is NOT trying to alert the host to its presence, so in that sense this is quite similar to a 'hijacked' function of the symbiont protein by the host. 
 
But I suppose that the use case here is to find all pathogen proteins that can elicit an immune response, is this correct ? Can we think of a more direct way to express that ? 
Thinking out loud: how about 'induction by symbiont of host pattern recognition receptor signaling pathway' ? 

And then proteins could also be annotated to the MF 'signaling receptor binding'.  

What do you think ? 

Pascale

**Comment by ValWood** [comment]
> Certainly the microbe is NOT trying to alert the host to its presence, so in that sense this is quite similar to a 'hijacked' function of the symbiont protein by the host.

I thought the same 
See Kim-Hammond Cosaks comment in another ticket. ( not to self update with ticket will try to locate)

Sometimes the pathogen intentionally activates this pathway to kill host tissue if it  has a necrotic lifestyle.

**Comment by ValWood** [comment]
@CuzickA I can't locate the ticket? was it on this tracker?

**Comment by CuzickA** [comment]
rename :effector dependent induction by symbiont of host immune response TO effector-triggered immunity #17014 
This is the ticket that Kim Hammond-Kosack commented on

**Comment by ValWood** [comment]
Oh sorry, getting confused. That is in the hypersensitive cell death pathway (2nd response). It might not apply to PRR signalling. I don't know. Anyone?

**Comment by mgiglio99** [comment]
This is where I need someone with more knowledge of these processes. I've contacted Alan and Candace Collmer - two PAMGO people - I'm hoping they will be able to help out with some of these questions.

**Comment by pgaudet** [comment]
@mgiglio99 Any news ?

**Comment by ValWood** [comment]
Re>
For the microbe proteins that are the actual PAMPs, is the thought to annotate to 'pattern recognition receptor signaling pathway' in a GO-CAM and somehow indicate this is in the host? Or would that information not be captured?

 we have annotated there to terms like
GO:0052552    modulation by organism of immune response of other organism involved in symbiotic interaction
for effectors, 

I don't think the viral terms should be annotated directly to the host pathways. Or at least right now  we should clean up the existing first  so we make sure we aren't duplicating.


Can we go ahead with the main part of this one and put any outstanding in new tickets? Action seems to be clear?

**Comment by ValWood** [comment]
It seesm that when the pathogen proteisn have been annotated they all follow the [attern

modulation by symbiont of host blah
for example
modulation by symbiont of defense-related host jasmonic acid-mediated signal transduction pathway

I don't know if this is the most efficient way to do this. We might consider using  extensions for this? but  it shouldn't impact the changes in this ticket.

**Comment by pgaudet** [comment]
Obsoletions: 
'GO:0052308 pathogen-associated molecular pattern dependent modulation by organism of innate immune response in other organism involved in symbiotic interaction’ 0 annotations

- [ ] 'GO:0052257 pathogen-associated molecular pattern dependent induction by organism of innate immune response of other organism involved in symbiotic interaction’ 0 annotations

- [ ] 'GO:0052033 pathogen-associated molecular pattern dependent induction by symbiont of host innate immune response’ 13 annotations

- [ ] 'GO:0052169 pathogen-associated molecular pattern dependent modulation by symbiont of host innate immune response’ 2 annotations

**Comment by pgaudet** [comment]
This term was obsoleted because it has been misused.

Consider:
GO:0002221 
GO:0002752
GO:0052034

**Comment by pgaudet** [comment]
I am obsoleting the 4 terms. @mgiglio99 @ValWood Can you open new tickets for whatever other tasks need to be done ?

**Comment by pgaudet** [comment]
WRT to the proposed new term 'modulation of pattern recognition receptor signaling pathway'  - right now we have in the ontology    
- GO:0039531  regulation of viral-induced cytoplasmic pattern recognition receptor signaling pathway
- GO:0039532 negative regulation of viral-induced cytoplasmic pattern recognition receptor signaling pathway

Do we need other terms ? Please open a new ticket if we do 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't think we need to add new terms right now -there are still too many terms;).

I'm pretty sure that this branch is covered in other tickets and will be adressed in due course.
Val
