### ISSUE TITLE
Query protoporphyrinogen IX biosynthetic process from glutamate

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17053]
Hello, 

This arises from https://github.com/geneontology/go-annotation/issues/2183

**protoporphyrinogen IX biosynthetic process from glutamate**
has equivalence axiom : 
'biosynthetic process'
 and ('has primary output' some protoporphyrinogen)
 and ('has primary input' some 'glutamate(2-)')

**glutamate metabolic process**  has equivalence axiom : 
'metabolic process'
 and ('has primary input or output' some 'glutamate(2-)')

Is it possible that for protoporphyrinogen IX biosynthetic process from glutamate, glutamate is not a 'primary input'? 

@ukemi @deustp01 
@ValWood 

Thanks, Pascale

**Comment by ukemi** [comment]
If you do not consider it a metabolism of glutamate, then we can remove the primary input status. That's the nice thing about the new relations.

**Comment by ukemi** [comment]
Let me know if you want me to do this.

**Comment by pgaudet** [comment]
Right - I dont think it's a metabolism of glutamate; glutamate is just the starting materials. 

I would like to make sure @deustp01 also agrees with this ! 

Thanks, Pascale

**Comment by deustp01** [comment]
The usual textbooks do not spell out the pathway for human heme biosynthesis in the kind of detail they provide for, say, glycolysis, but they show no role for glutamate at any point in the process. The [Reactome pathway](https://reactome.org/PathwayBrowser/#/R-HSA-189445&SEL=R-HSA-189451&PATH=R-HSA-1430728) (full disclosure - I did the annotation, but got one of the hard core biochemists who worked on the pathway to review it) shows no role for glutamate anywhere. The specific reaction that set off this ticket, the conversion of coproporphyrinogen III to protoporphyrinogen IX is an oxidation - reduction reaction with no involvement of glutamate. [Reactome](https://reactome.org/PathwayBrowser/#/R-HSA-189445&SEL=R-HSA-189421&PATH=R-HSA-1430728) and [Rhea](https://www.rhea-db.org/reaction?id=RHEA:18257) disagree on the ionization states of the input and output (Rhea is right) but otherwise agree on the reaction participants.

At least for humans (mammals?), glutamate has no direct role in heme biosynthesis. The canonical pathway starts with the reaction of succinyl-CoA and glycine to form delta-aminolevulinate (the committed / regulated step of the pathway) but otherwise no amino acids are involved at all. Glutamate has an indirect role, as it does in almost every biosynthesis involving amino groups, because of its central role in swapping amino groups between various small molecules.

A Google search for "heme metabolism in fungi" turned up [Franken et al.](https://www.ncbi.nlm.nih.gov/pubmed/21687966), describing a pathway identical to the human one except that a heme variant is made by means of a methylation reaction involving S-adenosylmethionine - still no glutamate.

**Comment by ValWood** [comment]
Even better, an obsoletion!

**Comment by ukemi** [comment]
PMID:20506125?

**Comment by deustp01** [comment]
We forgot plants - MetaCyc has a [pathway for tetrapyrrole biosynthesis from glutamate](https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-5188), which feeds directly into porphyrin biosynthesis. Haven't dug into it, but it appears to be based on data from Arabidopsis (which in turn appear to have been picked up in PAINT to make 123 IBA annotations to all sorts of taxa, looking at the annotations associated with  GO:0019353 protoporphyrinogen IX biosynthetic process from glutamate in [QuickGO](https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0019353)).

**Comment by deustp01** [comment]
Yes - the @ukemi reference shows the alternative pathway starting from glutamate-charged tRNA. Maybe the fix here is a taxon constraint.

**Comment by ValWood** [comment]
The 2 existing EXP annotations were from e. coli.

**Comment by ukemi** [comment]
The reference says, plants, archae and most bacteria.

**Comment by pgaudet** [comment]
+ add a reference
+ figure out if action is needed for 'protoporphyrinogen IX biosynthetic process from glycine' 
++ Do we need a taxon constraint? 
++ Can we add a reference? 

Thanks, Pascale

**Comment by ukemi** [comment]
I can add the reference. What would you like as a taxon constraint?

**Comment by tberardini** [comment]
Re: tetrapyrrole biosynthesis from glutamate, see this 2015 review (open):
Regulation and function of tetrapyrrole biosynthesis in plants and algae
[https://www.sciencedirect.com/science/article/pii/S0005272815000882?via%3Dihub]()
(Fig. 1 is quite good)

**Comment by ukemi** [comment]
Thanks @tberardini. I now have references I can add, but am still not confident about which taxon restrictions are appropriate.

**Comment by dsiegele** [comment]
tetrapyrrole biosynthesis from glutamate occurs in most bacteria and has also been found in the archaea

tetrapyrrole biosynthesis from glycine is found in the alpha-proteobacteria, including Rhodospirillum rubrum, Rhodobacter sphaeroides, and Paracoccus denitrificans.

Avissar, Y. J., J. G. Ormerod, and S. I. Beale. 1989. Distribution of d-aminolevulinic acid biosynthetic pathways among phototrophic bacterial groups. Arch. Microbiol. 151:513-519.
PMID: 2789025

Oh-hama, T., N.J. Stolowich, and A.I. Scott. 1993. 5-Aminolevulinic acid biosynthesis in
Propionibacterium shermanii and Halobacterium salinarium. Distribution of the two pathways of 5-
aminolevulinic acid biosynthesis in prokaryotes. J. Gen. Appl. Microbiol. 39:513-519.
DOI: https://doi.org/10.2323/jgam.39.513

**Comment by ukemi** [comment]
So just never in fungi, never in metazoa?

**Comment by ukemi** [comment]
We also have 'viridiplantae or archae or bacteria'. Maybe we should have an only in restriction to that class.

**Comment by ukemi** [comment]
Any suggestions on the taxon restriction here? I'd like to close this one.

**Comment by deustp01** [comment]
Here's a summary from a 2010 review (PMID: 20506125)

> 5-Aminolevulinic acid (ALA) is synthesized in nature by two different, unrelated biosynthetic routes. The first one, discovered by Shemin, involves the condensation of glycine and succinyl-CoA by 5-aminolevulinic acid synthase (ALAS) and occurs in mammals, fungi, and a-proteobacteria. In plants, archaea and most bacteria the alternative course, termed ‘‘C5-pathway,’’ builds ALA from tRNA-bound glutamate in two steps.

I think this list is consistent with the discussion above. So, "never in metazoa or fungi or a-proteobacteria" (if the last one is a meaningful taxon for GO). That leaves the process term available for plants, archaea, and all other life forms which is probably too broad but maybe the best that can be done given gaps in knowledge (probably not feasible to group bacteria systematically and correctly).

**Comment by ukemi** [comment]
Not going to worry about the bacterial term. Will add the others.

**Comment by pgaudet** [comment]
Added reference PMID:32976912 (there was no reference)
