### ISSUE TITLE
Question abut ubiquitin ligase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17065]
Hi David,

I have a user query. Our user wants all of the E3s. 
I remember we don't have a  GO term specific for E3s, biut I was going to send them the list of all ubiquitin lagaes (i.e transferases).

So, I am using
ubiquitin protein ligase activity (GO:0061630)

However, this has the definition
Catalysis of the transfer of ubiquitin to a substrate protein via the reaction X-ubiquitin + S -> X + S-ubiquitin, where X is either an E2 or E3 enzyme, the X-ubiquitin linkage is a thioester bond, and the S-ubiquitin linkage is an amide bond: an isopeptide bond between the C-terminal glycine of ubiquitin and the epsilon-amino group of lysine residues in the substrate or, in the linear extension of ubiquitin chains, a peptide bond the between the C-terminal glycine and N-terminal methionine of ubiquitin residues.

but I also have an E4 annotated to this child term:
ubiquitin-ubiquitin ligase activity 
https://www.pombase.org/term/GO:0034450

should the def of the parent be extended to include E4?

Thanks
Val

**Comment by ValWood** [comment]
Also, I'm a bit confused  here (again)

Why does the def refer to E2s? E2 are conjugating enzymes so they  would be annoted to the sibling term. Why does  ubiquitin protein ligase activity (GO:0061630) mention E2?

does 
GO:0061631    ubiquitin conjugating enzyme activity
need to be moved under here?

current:

![ubiquitin](https://user-images.githubusercontent.com/7359272/54884061-5b7b1580-4e64-11e9-8d42-1205d80d0752.jpg)
at

**Comment by ukemi** [comment]
Hi @ValWood ,

It's been a while since we worked with the BioGRID group on this, but if I remember correctly the ubiquitin ligase actvity can act as a transferase on either an E3 or an E2 molecule. That's why we refer to both in the definition as the SUBSTRATES. However the E2, E3 nomenclature is a bit confused in that the HECT E3 molecule can enable ubiquitin conjugating activity and is thus a related synonym. 

Since ubiquitin-ubiquitin ligase activity is a subclass of ubiquitin ligase activity, do we need to extend the definition? It seems correct that you would have the protein called an E4 annotated to this based on the synonym, as long as it catalyzes the described molecular function. 

I think that you want the GPs annotated with ubiquitin ligase activity for the 'E3's.

**Comment by ukemi** [comment]
Just to be clear, the X-ubiquitin above is what I mean as the substrate in my comment, so the ligase activity can transfer from either an E2-ubiquitin or an E3-ubiquitin to an S.

**Comment by ValWood** [comment]
but look at the image above.
E2s are conjugating enzymes. 61631.
61631 is a sibling of  61630.
61630 metions E2's.
There is a logic issue here?

**Comment by ukemi** [comment]
No. If I remember correctly, the activity is catalyzed by a ligase, but in some cases, the transfer can be from an E2 that is conjugated to ubiquitin. The participants in the reaction are not necessarily the enzyme that is catalyzing the reaction.

**Comment by ValWood** [comment]
Durr, Midori just explained this to me.


Copying this here in case I ask again:
I do understand what David is saying: GO:0061630 is not the activity OF an E2, but it's an activity that may ACT ON an E2 or some other substrate. 

Sorry!
