### ISSUE TITLE
NTR protein transport chaperone

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17073]
Hello, 

While working on #17071, I came across some annotations that I was unable to figure out how to rehouse (see https://docs.google.com/spreadsheets/d/1wOfGUMUcckFPeD1Gr_HG5s6b0zXmOH7M5RBgotRpjlc/edit#gid=0). 

I would like to propose a new term, transport chaperone' to annotate  proteins such as SGD:S000003413 (TIM13), described as "Mitochondrial intermembrane space protein; forms a complex with Tim8p that delivers a subset of hydrophobic proteins to the TIM22 complex for insertion into the inner membrane" . 

Any improvement to the term label is welcome ! I know how confusing 'chaperone' is. 

Thanks, Pascale

**Comment by ValWood** [comment]
Aren't  these are "folding chaperones" they bind to the substrate  and prevent it folding  (or aggregating, I guess) until it is fed into the membrane.

"Tim23 to chaperone the hydrophobic Tim23 across the aqueous intermembrane space."
https://www.ncbi.nlm.nih.gov/pubmed/18706423

(The function similarly to the small Tim complex
https://en.wikipedia.org/wiki/Tim9-Tim10_complex

As long as it is clear that this is not a transporter, and is not 'actively' transporting, but is preventing aggregation during delivery.

Will it be under "molecular  carrier activity"?

Also should
protein folding chaperone
which is similar but related to folding rather than delivery to  be  a sibling?

**Comment by pgaudet** [comment]
I'm going over the literature and perhaps this function can be called 'protein carrier activity' , see 
'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2651516/ 
> The substrates of the TIM22 translocation system include the **mitochondrial carrier proteins** and import components Tim17, Tim22, and Tim23. 

I think this is clearer. 

Thoughts ?

**Comment by pgaudet** [comment]
Proposed definition: "Directly binding to a specific protein and delivering it either to a cellular location."

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140318
+name: protein carrier activity
+namespace: molecular_function
+def: "Directly binding to a specific protein and delivering it either to a cellular location." [PMID:18706423]
+is_a: GO:0140104 ! molecular carrier activity
+created_by: pg
+creation_date: 2019-04-01T10:41:38Z

**Comment by ValWood** [comment]
I think we need to check with somebody who knows more about this.

These  gene products might be carriers:
Definition (GO:0140104 GONUTS page)
Directly binding to a specific ion or molecule and delivering it either to an acceptor molecule or to a specific location.

But I'm not really convinced that they are.


For "chaperone" currently we have:
GO:0044183    JSON
protein folding chaperone
Definition (GO:0044183 GONUTS page)
Interacting selectively and non-covalently with any protein or protein complex (a complex of two or more proteins that may include other nonprotein molecules) that contributes to the process of protein folding.

I think this should be broadened to "just" chaperone

and the definition would be something like
Interacting selectively and non-covalently with any protein or protein complex that prevents a protein from misfolding  or aggregating  or missassembly  during assembly, disaasembly or delivery  to its final location. The chaperone is not part of the final complex.

I think that is what the chaperone wikepedia page is trying to say (badly , so I won't link to it)

If this is true the "delivery chaperone" is not a "carrier", it's a chaperone operating  during the import process. 

(I think these are necessary in the intermembrane space because it's a highly reducing environment?)

Is that clearer?

**Comment by pgaudet** [comment]
Hi @ValWood 
Are you sure we can rename 'protein folding chaperone' just rename 'chaperone', this caused a lot of confusion before - but I don't remember where that confusion was coming from; do you ? 

I decided on 'protein carrier activity' because of PMC2651516, that says:
> The substrates of the TIM22 translocation system include the mitochondrial carrier proteins and import components Tim17, Tim22, and Tim23. These substrates cross the TOM complex as a loop in an unfolded state. The small Tim complexes, Tim8–Tim13 or Tim9–Tim10, then bind to the substrates to facilitate transport across the intermembrane space. Because the intermembrane space is an aqueous compartment and the substrate is unfolded, the small Tim proteins act as chaperones to maintain the hydrophobic substrates in an import-competent state, akin to the cytosolic chaperones. 

So I was under the impression that the small Tim complex was actually _carrying_ the substrates.

**Comment by ValWood** [comment]
I'm copying @RLovering (as a co-advocate of the term in the past)  and @mah11 (for historical perspective)  in here.

From a historical perspective, the problem IIRC was that in the past  we just didn't represent activities such as "chaperone"  becauise they were considered to be out -of scope for the MF ontology (in the same way that we did not represent  activities  like sequestering, or protein tag, or antioxidant). Basically we could not figure out how to define them other than "binding involved in x".

Also, we struggled with the fact that "chaperone" seemed to be describing multiple activities (similarly to  antioxidant). However,  after learning more, I think we were probably misdefining the chaperone by restricting it to protein folding. 

It seems that really a "chaperone activity" is to maintain a protein in a specific state until something else can occur. Whether that  be folding or import into the membrane is kind of orthogonal, the common activity is to "maintain the protein or complex in a competent state for x to occur (where x is delivery/assembly/or folding).

We could keep the protein folding chaperone (it's probably useful), as a  descendant but this really seems to be encoding chaperone + process into the MF ontology. 

I'm not sure they are carrying the substrates (they are a caliper or crutch rather than a bicycle!).

**Comment by ValWood** [comment]
I might be wrong but this would align with the comment:


"The small Tim complexes, Tim8–Tim13 or Tim9–Tim10, then bind to the substrates to facilitate transport across the intermembrane space. Because the intermembrane space is an aqueous compartment and the substrate is unfolded, the small Tim proteins act as chaperones to maintain the hydrophobic substrates in an import-competent state, akin to the cytosolic chaperones."

Maintaining import competency isn't = carrier. To me, a carrier is the thing which contains some information about the location, or 'directs' the transport in some way (nucleocytoplasmic carrier, for example), and presumably the small molecule carriers must also  do this. I'm not sure this is the case for "small Tim"


@bmeldal  might know about this, presumably Intact  have come across this issue?

**Comment by bmeldal** [comment]
TIM9-TIM10: https://www.ebi.ac.uk/complexportal/complex/CPX-2268 (with links to other TIM complexes).

Sandra also called it a "chaperone complex" in the function definition.

I agree, these complexes aren't carriers as they don't have an activity to aid the transport from A to B.

**Comment by pgaudet** [comment]
OK - so I will remove this new term and widen the definition of chaperone activity as suggested by @ValWood

**Comment by pgaudet** [comment]
WRT BAG3 @RLovering 
Looking at the Uniprot entry, it's a co-chaperone; I remember we were going to see how to improve that branch. Do you think it's a protein carrier ?

**Comment by RLovering** [comment]
HI Pascale

just looking at BAG3 I am removing my protein carrier annotations based on review statements: https://kopernio.com/viewer?doi=10.4161/auto.7.7.15844&route=7 BAG3   is   not   only   a   powerful   trigger    of   macroautophagy,   but   rather   is   also    involved  in  the  active  transport  of  protein  substrates  inside  the  cell.  ..... we were now able  to show that BAG3 directly associates with the microtubule motor dynein and mediates  the  selective  transport  of  misfolded   proteins  to  the  aggresome.13   Binding  of   BAG3  to  dynein  is  mediated  by  its  PxxP  domain. 13 Based on these findings, we propose the following scenario: BAG3 acts as  a  nucleotide-exchange  factor  and  directly  stimulates substrate transfer from HSP70  to  the  dynein  motor  complex.

**Comment by pgaudet** [comment]
@RLovering Can you paste the PMID ? I don't have access to the link you have there. 

Looks like this can be closed ?
