### ISSUE TITLE
Obsolete sequestering processes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17075]
Hello, 

Following up on #16157 

It was proposed to obsolete 
GO:0051220 cytoplasmic sequestering of protein and children: 
-- GO:0043004 cytoplasmic sequestering of CFTR protein
--  GO:1905482 cytoplasmic sequestering of protein involved in G2 DNA damage checkpoint
--  GO:1905481 cytoplasmic sequestering of protein involved in mitotic DNA replication checkpoint
-- GO:0042994 cytoplasmic sequestering of transcription factor 
---GO:0007253 cytoplasmic sequestering of NF-kappaB

- GO:0042989 biological process sequestering of actin monomers 

TO BE COMPLETED: annotations, mappings, and suggestions for rehousing annotations later

**Comment by ValWood** [comment]
should these be dealt with too?

GO:0042137    sequestering of neurotransmitter | 39 annotations
GO:0051238    sequestering of metal ion | 719 annotations
GO:0042989    sequestering of actin monomers | 545 annotations
GO:1990659    sequestering of manganese ion |  
GO:0097577    sequestering of iron ion | 610 annotations
GO:0097578    sequestering of copper ion |  
GO:0030730    sequestering of triglyceride | 254 annotations
GO:0039582   obsolete suppression by virus of host PKR activity by positive regulation of PKR 
GO:0006880    intracellular sequestering of iron ion | 563 annotations
GO:0006881    extracellular sequestering of iron ion

**Comment by pgaudet** [comment]
I was just looking into that ! The main problem I see is how to handle their regulation. Perhaps it. just just be 'regulation of calcium levels' regulation of cytoplasmic calcium levels', etc ? What do you think ?

**Comment by pgaudet** [comment]
Example of terms hat would be left without parent if we move sequestering to MF: 
* negative regulation of release of sequestered calcium ion into cytosol
* regulation of cardiac muscle contraction by regulation of the release of sequestered calcium ion

**Comment by ValWood** [comment]
I was just writing how to deal with the regulation:
https://github.com/pombase/curation/issues/2354

I think the processes should be "localization"

I would only use the "sequester activity" for the things which physically sequester (usually by binding and localizing the 'modified' substrate. The problem was we had nothing to represent the activity of  things like "14-3-3 proteins" which do actually  'sequester' as their MF

sequestering as  process== localization.

**Comment by ValWood** [comment]
I think these terms are fine
negative regulation of release of sequestered calcium ion into cytosol
regulation of cardiac muscle contraction by regulation of the release of sequestered calcium ion

these are "release of a chemical from storage"
which is a bit  different.

Also lipid storage, sometimes we call it 
positive regulation of lipid storage,
and other times
GO:0030730    sequestering of triglyceride
we just need to use a common language for these.

**Comment by ValWood** [comment]
for example
cholesterol storage
cholesterol sequestration | narrow
sequestration of cholesterol | narrow

so for  metabolites  we could 
use storage/release from storage
Or
sequestration
release from sequestration

for proteins, maintenance of localization sounds more "natural"

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 

'GO:1905482 cytoplasmic sequestering of protein involved in G2 DNA damage checkpoint' 
'GO:1905481 cytoplasmic sequestering of protein involved in mitotic DNA replication checkpoint' 
'GO:1905507 cytoplasmic sequestering of protein involved in mitotic G2 DNA damage checkpoint' 

The reason for obsoletion is that these represent GO-CAM models. The terms have only been used by PomBase. They are no mappings to this term. This term is not in any subset. 

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/17075
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on May 10th. Unless objections are received by May 10th, we will assume that you agree to this change.

Thanks, Pascale

**Comment by ValWood** [comment]
Could we add an annotation block for these terms?

**Comment by ValWood** [comment]
In the short term  will add "do not annotate" to 
<img width="621" alt="Screenshot 2024-10-15 at 21 53 17" src="https://github.com/user-attachments/assets/1456eeaa-d676-44a6-9225-4a1023064247">
(it is not so bad there are only 32 EXP, and there are no regulation terms here, most of the annotation are TreeGrafter)

In fact, I noticed that there are 7 annotations from Disprot  and at least one isn't  describing sequestering (only zinc ion binding), (I spotted it because it's CDC25).

The text in the paper says"
The C-terminal part of Arath;CDC25 contains a zinc-binding loop and is, as such, different from the human CDC25A and CDC25B (37). This zinc-binding loop could play a role of protein stabilization because the recombinant Arath;CDC25 protein containing only serines instead of the cysteines in its C-terminal part could not be produced in E. coli. However, the zinc-binding loop could equally be involved in substrate recognition because the zing fingers are well known interaction modules that bind to a variety of substrates, including protein or DNA (37). It would be functionally similar to the 17 final C-terminal residues of human CDC25B that were shown to confer substrate specificity and mediate protein substrate recognition (6, 38)."

@victorianugnes, could you reannotate this one to "zinc binding activity" and review the other Disprot annotation? If they really are "sequestering" metals (i.e., confining ions or atoms such that they are separated from sensitive components of a biological system), for example, Metallothioneins, then use instead the corresponding molecular function term GO:0140487 metal ion sequestering activity or one of its children.

thanks
v

**Comment by pgaudet** [comment]
> In the short term will add "do not annotate" 

I suggest you use 'gocheck_obsoletion_candidate'

**Comment by victorianugnes** [comment]
All ion sequestering terms had been handled. You'll keep seeing them in DisProt until our next December release, but they are all gone now. Thanks for pointing them out!

**Comment by ValWood** [comment]
Thanks!

**Comment by pgaudet** [comment]
@edwong57 Can you please take this one?

**Comment by edwong57** [comment]
I just want to make sure I understand what needs to be done. It looks to me like it is just the final step. The announcement and review have already been made, so I just need to obsolete GO:0051238 and all the children. They are not being replaced by anything, correct? Did I miss anything?

**Comment by edwong57** [comment]
Current annotation counts -

GO:0006881 | extracellular sequestering of iron ion | 15
GO:0007253 | cytoplasmic sequestering of NF-kappaB | 36
GO:0010891 | negative regulation of sequestering of triglyceride | 11
GO:0010890 | positive regulation of sequestering of triglyceride | 10
GO:0030730 | sequestering of triglyceride | 11
GO:0010889 | regulation of sequestering of triglyceride | 1
GO:0042137 | sequestering of neurotransmitter | 2
GO:0042989 | sequestering of actin monomers | 24
GO:0042994 | cytoplasmic sequestering of transcription factor | 18
GO:0051220 | cytoplasmic sequestering of protein | 23
GO:0032119 | sequestering of zinc ion | 5
GO:0051238 | sequestering of metal ion | 6
GO:0097578 | sequestering of copper ion | 2
GO:0097577 | sequestering of iron ion | 4

**Comment by edwong57** [comment]
Obsoleted these terms:

> GO:0032119 | sequestering of zinc ion | 5
> GO:0051238 | sequestering of metal ion | 6
> GO:0097578 | sequestering of copper ion | 2 (and child terms)
> GO:0097577 | sequestering of iron ion | 4 
> GO:1990659 sequestering of manganese ion|0
> GO:0042137 | sequestering of neurotransmitter | 2
> GO:0042989 | sequestering of actin monomers | 24
> GO:0006880 | intracellular sequestering of iron ion | 39
> GO:0006881 | extracellular sequestering of iron ion | 15
> GO:0007253 | cytoplasmic sequestering of NF-kappaB | 36
> GO:0042994 | cytoplasmic sequestering of transcription factor | 18
> GO:0051220 | cytoplasmic sequestering of protein | 23
> GO:0050788| sequestering of mercury | 0

Remaining:
GO:0010891 | negative regulation of sequestering of triglyceride | 11
GO:0010890 | positive regulation of sequestering of triglyceride | 10
GO:0030730 | sequestering of triglyceride | 11
GO:0010889 | regulation of sequestering of triglyceride | 1

**Comment by pgaudet** [comment]
Ontology editors call: 

Actions: 
- rename 'triglyceride storage' to match parent (including regulation children)
- create grouping class 'nutrient storage', as a child of 'cellular process'? unless you have a better idea

**Comment by edwong57** [comment]
I have renamed the triglyceride terms. Still looking into the grouping class name.

**Comment by pgaudet** [comment]
We can talk about it again at the next ontology call, but 'nutrient storage' seems a good compromise. 

We can base on the [wikipedia](https://en.wikipedia.org/wiki/Nutrient) definition : 
"a chemical substance used by an organism to survive, grow and reproduce, for example protein, vitamins, and minerals" 

(might be worth it to ask CheBI to improve their definition)

**Comment by pgaudet** [comment]
storage of biological reserves?

**Comment by pgaudet** [comment]
Ontology editors call: let's not link to CHEBI here, since the meaning is too different. 

- 'nutrient storage' should do directly under 'cellular process'

**Comment by pgaudet** [comment]
Fixed definiton to: 

> The accumulation and maintenance in cells or tissues of a nutrient, a substance that is used by an organism to survive, to grow, and to reproduce; such as proteins, vitamins, and minerals. Nutrient reserves can be accumulated for mobilization and utilization when needed.

(the definition was only the definition of 'nutrient' 
> A substance that is used by an organism to survive, to grow, and to reproduce; such as proteins, vitamins, and minerals.
