### ISSUE TITLE
NTR: positive regulation of imaginal disc-derived wing size

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17205]
Could I request:

'positive regulation of imaginal disc-derived wing size'

as a child of: GO:0044719 regulation of imaginal disc-derived wing size

The negative regulation term already exists.

Ref: PIMD:23485686

GOC:ha

**Comment by krchristie** [comment]
Hi @hattrill 

Since the neg reg term had a definition slightly different than the standard def, but that made more sense for a term specifically talking about size:

> Any process that reduces the size of an imaginal disc-derived wing.

I made a parallel def for the pos reg term, just changing the word 'reduces' to 'increases', but let me know if you feel any modifications to these defs need to be made.

I also added the equivalency axiom to the neg reg term to reflect the pre-existing equivalency axiom of the plain regulation term.

-Karen

**Comment by hattrill** [comment]
That sounds all good! Thanks, Karen!
