### ISSUE TITLE
3 new terms for magnetosomes

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#17209]
Hello,
I'd like 3 new GO terms in Cellular component for (bacterial) magnetosomes please; Magnetosome, and its components Magnetosome lumen and Magnetosome membrane. I'm going to make the subcellular locations and keywords in UniProtKB and it seems logical to make the GO terms right away.
This is my suggested definition for Magnetosome, I based it on this review and informtion therein, PMID 27620945; 
"A membrane-bound organelle that envelops particles of magnetic iron minerals in magnetotactic bacteria. Magnetosomes align along the cellular motility axis and function in bacterial navigation along the Earth's magnetic field. They are formed by invagination of the cell inner membrane; in some species they remain connected to the inner membrane, in others they pinch off to form independent intracellular vesicles."
I think GO:0044424 is the correct parent (GO:0043229 looks too eukaryotic to me, so is inappropriate for bacteria).
For Magnetosome lumen I suggest: "The volume enclosed by the magnetosome membrane."
For Magnetosome membrane I suggest: "The membrane of the magnetosome." 
Thanks,
Andrea Auchincloss

**Comment by AndreaAuchincloss** [comment]
I need a slight modification to the second sentence...
A membrane-bound organelle that envelops particles of magnetic iron minerals in magnetotactic bacteria. Magnetosomes form linear chains that align along the cellular motility axis at midcell and function in bacterial navigation along the Earth's magnetic field. They are formed by invagination of the cell inner membrane; in some species they remain connected to the inner membrane, in others they pinch off to form independent intracellular vesicles.

**Comment by ValWood** [comment]
wow, how cool!

**Comment by vanaukenk** [comment]
@AndreaAuchincloss 

This is an interesting classification question.  In the reference you cite above and another one I looked at (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2944366/), magnetosomes are definitely referred to as organelles, although as you point out, sometimes they remain connected to the inner cell membrane as invaginations and in other cases they seem to exist as independent vesicles.

It seems like we're losing something if we don't classify these as organelles in the ontology, but the remaining attachment to the plasma membrane in some cases may be a complicating factor.

@ukemi - any thoughts?

**Comment by krchristie** [comment]
Hi @vanaukenk - I happened to notice this ticket and have some thoughts that may be helpful.

We classify the 'cilium' as an organelle even though the ciliary membrane is contiguous with the plasma membrane. You can see that the term 'cilium' is directly under the term 'organelle' rather than under either 'extracellular organelle' or 'intracellular organelle', or under either 'membrane-bounded organelle' or 'non-membrane-bounded organelle' due to it's relatively unusual membrane situation.

Another thought that may be helpful is that I am currently working with Peter D'Eustachio on #17217 to create some terms for the photoreceptor outer segments for rods or cones specifically since they differ in whether or not the membrane discs do or do not remain contiguous with the ciliary membrane. I haven't merged the pull request in yet, but the file diff is linked below, and I copied in one of the key changes. You can see that we changed the parentage of the term 'photoreceptor disc membrane', and then we have made two child terms for the rod and cone specifc disc membranes, each of which have different more specific membrane parents as appropriate to each. This model may be useful if specific terms are needed based on whether or not the remain connected to the inner cell membrane or not.

```
- def: "Ovally-shaped membranous stack located inside the photoreceptor outer segment, and containing densely packed molecules of the photoreceptor protein rhodopsin that traverse the lipid bilayer. Disc membranes are apparently derived from the plasma membrane in the region of the cilium that connects the photoreceptor outer segment to the inner segment." [GOC:bj, PMID:11826267, PMID:2537204, PMID:7507907]
- is_a: GO:0060170 ! ciliary membrane
+ def: "Stack of disc membranes located inside a photoreceptor outer segment, and containing densely packed molecules of photoreceptor proteins that traverse the lipid bilayer. Disc membranes arise as evaginations of the ciliary membrane during the development of the outer segment and may or may not remain contiguous with the ciliary membrane." [GOC:bj, GOC:krc, GOC:pde, PMID:11826267, PMID:19501669, PMID:2537204, PMID:26574505, PMID:6771304, PMID:7507907]
+ is_a: GO:0016020 ! membrane
```

https://github.com/geneontology/go-ontology/pull/17250/files

**Comment by vanaukenk** [comment]
Thanks @krchristie - the comparison to cilium is helpful.

@AndreaAuchincloss - I think in this case we could then go with 'organelle' as an is_a parent unless you think there was good reason to split the two types of magnetosomes (i.e. attached to plasma membrane or independent) into separate CC terms.

**Comment by AndreaAuchincloss** [comment]
Thanks @krchristie and @vanaukenk for all the comments. No, I don't think there is a reason to make 2 kinds of magnetosome, as far as I know there are only 2 bacteria where it is known if the organelle remains connected to the cell's inner membrane or not. There are other magnetotactic bacteria and for some/most of them we may never know the relationship of magnetosomes to the cell inner membrane as it requires some pretty intense (and I imagine expensive) electron-microscopic observation.

Cyanobacterial thylakoids (GO:0030075) are in an identical classification situation, and I used their Ancestor chart as inspiration. And yes @ValWood , these are really cool!

**Comment by AndreaAuchincloss** [comment]
@vanaukenk 
Is this enough information to make the terms then? I'm ready to annotate a considerable number of entries to magnetosome membrane.
Thanks

**Comment by AndreaAuchincloss** [comment]
@vanaukenk 
Hello, I'm still waiting for my terms...

**Comment by vanaukenk** [comment]
@AndreaAuchincloss - the magnetosome terms have been added now.  Apologies for the delay.
