### ISSUE TITLE
Obsolete 'lipopolysaccharide exporter activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17202]
Hello, 

The proposal has been made to obsolete 'GO:0015634 lipopolysaccharide exporter activity'. The reason for obsoletion is that 'export' represents a process, not a function.

There are no annotations to this term, no mappings, this term is not in any subsets. 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/17202
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on May 6th, 2019.
Unless objections are received by May 6th, 2019, we will assume that you agree to this change.

Thanks, Pascale

**Comment by genegodbold** [comment]
The reason for obsolescence makes sense. I'm a bit surprised no one has *tried* to attach any LPS efflux machinery to it.

**Comment by pgaudet** [comment]
I think these have been annotated to the process: 
GO:0015921  lipopolysaccharide export
http://amigo.geneontology.org/amigo/term/GO:0015921

Thanks, Pascale

**Comment by genegodbold** [comment]
Thanks; I see. It's weird that it's only 12 entries over two bugs, though (B. anthracis and P. aeruginosa). There are nearly 800 annotations from what looks like, uh, hundreds of bacteria for GO:0009103 (lipopolysaccharide biosynthetic process). On the catabolism side, there are just five entries from four mammals (GO:0009104). What about LPS modification *after* biosynthesis? Does this count as part of biosynthesis? LpxD from B. bronchiseptica; NaxD, LpxD1 and LpxF from F. tularensis; and AlmG from V. cholera all alter the chain length of bacterial lipopolysaccharide to (presumably, since I'm speaking teleologically) make it less immunogenic/detectable by host TLR4. I don't see them listed yet, though.

**Comment by colinlog** [comment]
There may be a general mechanism for cells to 'get rid of' stuff that ends up in (auto)phagosomes, namely transient 'burps' whereby the (auto)phagosomes open up to the extracellular space. This was called 'eructosis' by Robin Yates (Calgary) at a GRC meeting in 2015. I emailed him yesterday and he said the paper is still not published but will be this year most likely. I thought I'd mention this here as it is peripherally related to 'cellular export of compounds synthesised by another organism' which is how I initially read  'lipopolysaccharide export'

Guess the new term (eructosis or eructophagy) can only be requested after publication though...
