### ISSUE TITLE
Obsolete GO:0005395 eye pigment precursor transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17214]
Hi @hattrill 

I have a question about 
GO:0005395 eye pigment precursor transporter activity
(and the BP transport) -

Looks like the precursors are nucleotides; is this term needed? 

Thanks, Pascale

**Comment by hattrill** [comment]
....from memory this is a tough one to pin-down, even though involves some of our most famous markers.....I'll have a look this week and get back to you.

**Comment by hattrill** [comment]
turns out that it wasn't so tough - one substrate was nucleotide, the other an amino acid. I've changed it - feel free to obsolete.

**Comment by pgaudet** [comment]
OK I will obsolete, thanks.

**Comment by pgaudet** [comment]
@hattrill Shoudl I also obsolete     GO:0006856 eye pigment precursor transport ? 
You have 7 TAS, 2 IEP to this term. 

Thanks, Pascale

**Comment by hattrill** [comment]
For now, I'd like to keep this process term, as the substrate may be an intermediate (which, if we had good biochemical data could be covered by modified aa transporter activity - but we don't!)

**Comment by pgaudet** [comment]
Very good, thanks.

**Comment by pgaudet** [comment]
obsoeltion notice sent.

**Comment by deustp01** [comment]
Reactome instances R-HSA-1467466, R-HSA-2466749 (which actually describe GO:0034632 retinol transmembrane transport) have been edited to use that term instead.

**Comment by pgaudet** [comment]
@kltm 

I obsoleted this 2 weeks ago, should it NOT be in the new AmiGO release ? (June 1) ???

Thanks, Pascale

**Comment by kltm** [comment]
Something is up, see later comments in https://github.com/geneontology/pipeline/issues/95

**Comment by cmungall** [comment]
The linked ticket has a lot of extraneous information to do with neo/noctua that is not relevant here

As a reminder:

 * go-plus is the complete GO plus imports from subontologies
 * go-gaf combines go-plus with gorel (for extensions not in RO) and taxslim. This is loaded into AmiGO

We recently changed go-gaf from being an importer to being merged in the pipeline. This is handled by the Makefile in this repo. The merge is performed by ROBOT.

Obviously the two are intended to be in sync

Currently:

 * GO:0005395 is correctly obsoleted in (release) go-plus.owl 
 * GO:0005395 is not obsoleted in (release) go-gaf.owl
 * Both have 2019-06-01 in the header

This is not intended. I can't figure out how this would happen because:

 * go-gaf is made in this Makefile using go-plus as a dependency (so will be made first)
 * it's made by ROBOT
 * ROBOT uses the catalog, and go-plus is in the catalog

**Comment by pgaudet** [comment]
What is go-gaf.owl?

**Comment by balhoff** [comment]
@pgaudet it is go-plus with some additional content (gorel, some of CL, some NCBI taxon). @cmungall figured out that ROBOT has not been loading the ontology catalog file (the file that tells it where to find imports) exactly as documented. This was fine until the changes I made to the go-gaf build hit the issue. I could never see the issue locally due to another facet of the same bug. I made a change to the makefile in #17451 which should fix this.
