### ISSUE TITLE
editors makefile versus release makefile; they are different

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17211]
Yesterday we noticed that the xrefs to Reactome in the editors' ontology file still have a lower case 'r', but on the snapshot release this has been corrected to an uppercase 'R'. This indicates that the build that the editors is using isn't in complete synch with the one that the public is seeing. Shouldn't the snapshot release mirror the editors' file as long as the pipeline has run correctly?

Assigning @balhoff. Please reassign if you are not the right person Jim.

**Comment by ukemi** [comment]
Perhaps related to #16981

**Comment by balhoff** [comment]
When the makefile runs in the snapshot release, the reactome xref import is built and gets the correct capitalization. But the reactome file that is committed in github is out of date. This import is a little different than the others, since it gets updated every time anything changes. The version committed to GitHub is kind of just a convenience so something is there when you open go-edit in Protege. I'll commit an updated file.

**Comment by balhoff** [comment]
The committed reactome import is updated now; it has capitalized Reactome. One remaining issue is as you say:

> This indicates that the build that the editors is using isn't in complete synch with the one that the public is seeing. Shouldn't the snapshot release mirror the editors' file as long as the pipeline has run correctly?

The way it is set up now the snapshot will be generally more up to date than what the editors see.

**Comment by balhoff** [comment]
I'm pretty sure this was all resolved a while back.
