### ISSUE TITLE
NTR - terms related to GO:0097381 photoreceptor disc membrane

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#17217]
Mammalian rod cells contain stacks of structures called "membrane discs". There is some controversy about how they form that affects conclusions about the spatial relationships of components of nascent discs to other rod cell structures and the surrounding extracellular space, but once the "membrane disc" is formed there appears to be a consensus backed by evidence from several sources that the disc is a flattened cytoplasmic vesicle contained within the rod cell cytosol and separate from the rod cell plasma membrane. This disc vesicle has three parts distinguishable by origin, morphology and protein content: (1) a disc membrane that comprises the flattened faces of the disc formed by evagination of the photoreceptor ciliary membrane, (2) a disc rim membrane that forms separately from the cilium with a distinct content of membrane-associated proteins and that joins the disc membranes, and (3) the disc lumen enclosed by this membrane structure (PMID:19582864 for a review with clear diagrams; PMID:6771304, PMID: 1730772, and PMID:4100753 for experimental evidence).

Cone cells likewise have discs but they are not fully closed and remain accessible to the extracellular space (PMID:19582864).

Most annotations involving these discs (including ones from Reactome) locate entities and activities to the membrane components of discs. However, as part of our own work to try to sort out spatial relations among intracellular components we now need to locate things with respect to the disc lumen.

Does it make sense to create a new term GO:new1 photoreceptor disc with definition and parentage like that for a cytosolic vesicle, make GO:0097381 photoreceptor disc membrane a part_of child of this new term, and give it siblings GO:new2 photoreceptor disc rim membrane and GO:new3 photoreceptor disc lumen, again with standard vesicle-part definitions and relationships?

Is a rod cell - cone cell distinction needed, and how would we make it?

Expert ontology-editorial advice is needed here, and any advice from someone with real expertise in the structure and function of mammalian photoreceptor cells would be a bonus.

I can fill in the missing details of term names and definitions once the editorial issues are sorted out.

**Comment by krchristie** [comment]
@ukemi - I think it makes sense for me to work with @deustp01 on this one, so I claimed it, but if you disagree, you can reassign it.

**Comment by krchristie** [comment]
These two more recent reviews may also be useful:

Morshedian A, Fain GL.
The evolution of rod photoreceptors.
Philos Trans R Soc Lond B Biol Sci. 2017 Apr 5;372(1717).
PMID:28193819

Ingram NT, Sampath AP, Fain GL.
Why are rods more sensitive than cones?
J Physiol. 2016 Oct 1;594(19):5415-26.
PMID:27218707

It's a good question about whether we should distinguish between rod and cone cells. In looking at the lovely comparision diagram from PMID:27218707, see:
https://wol-prod-cdn.literatumonline.com/cms/attachment/858ebc68-961e-4a00-8d57-ba61513b0539/tjp7341-gra-0001-m.jpg

it seems that we should at least have different terms for the outer segments of rod cells versus cones cells since they have different structures as well as different constituents, but I notice that our existing definition for this term has a rod specific definition:

**Term**: photoreceptor outer segment
**Def**: The outer segment of a vertebrate photoreceptor that contains discs of photoreceptive membranes.

It might actually make sense to have different terms for other parts of rod and cone cells since they seem to differ significantly in what gene products are present in each type of cell.

@deustp01 - perhaps it would make sense to set up a time to skype.

**Comment by deustp01** [comment]
@krchristie  Thanks! I'll read the papers then let's talk. Sometime Friday?

**Comment by krchristie** [comment]
@deustp01 - Friday, I have commitments from 9:30 am to about 1:30 pm Pacific time. Otherwise, I am available and can be online by about 7:30 am Pacific. Let me know when would work for you.

**Comment by krchristie** [comment]
I've been looking at some of our existing photoreceptor cell terms and we have quite a variety. This comment deals only with BP terms. In some places in BP we have a very fleshed out structure of both camera-type eyes and compound eyes, as well as ocelli. In other places we have a high level term with no child terms. In a few places, we have the high level term and an inconsistent selection of the possible child terms.

These BP terms are very general and encompass both camera-type eyes and compound eyes, as well as ocelli. There are varying levels of detail of hierarchy below.

These two terms have full structure of terms for ocellus and 2 types of eyes:
- **BP photoreceptor cell differentiation (GO:0046530)** - general, has ocellus term & two layer child term hierarchy for camera-type & compound eyes:
                               -- 'camera-type eye photoreceptor cell differentiation'
                                       --- 'retinal cone cell differentiation'
                                       --- 'retinal rod cell differentiation'

- **BP photoreceptor cell fate commitment (GO:0046552)** - general, has ocellus term & two layer child term hierarchy for camera-type & compound eyes:
                               -- 'camera-type eye photoreceptor cell commitment'
                                       --- 'retinal cone cell commitment'
                                       --- 'retinal rod cell commitment'

This term is missing grouping term for camera-type eye though the 2 relevant child terms exist
- **BP photoreceptor cell development (GO:0042461)** - very general, already have ocellus term, 5 children of compound eye dev & two specific vertebrate terms, but not camera-type eye grouping term:
                               -- 'retinal rod cell development'
                               -- 'retinal cone cell development'


These 2 terms have a cone cell term but not a rod cell term; only 1 of these has a compound-eye	specific term, but none	of the grouping level terms exist:
- **BP photoreceptor cell fate determination (GO:0043703)** - general, has cone specific child term, but not rod term; no compound eye terms; only child term is:
                               -- 'retinal cone cell fate determination'

- **BP photoreceptor cell fate specification (GO:0043704)** - general, has cone specific child term, but not rod term; also only has 1 of 5 compound eye specific terms:
                               -- 'retinal cone cell fate specification'
                               -- 'R8 cell fate specification'


These terms have no child terms
- **BP photoreceptor cell maintenance (GO:0045494)** - general, no child terms

- **BP photoreceptor cell morphogenesis (GO:0008594)** - very general with Drosophila example, no child terms (might be better to modify def to mention appropriate for compound & camera-type eyes)

- **BP photoreceptor cell axon guidance (GO:0072499)** - general, no child terms (single	PMID def dbxref is for Drosophila)



These BP terms have no child terms
- BP protein localization to photoreceptor outer segment (GO:1903546) - general, no child terms
- BP protein localization to photoreceptor connecting cilium (GO:1903621) - general, no child terms
- BP photoreceptor cell outer segment organization (GO:0035845) - general, no child terms; consider need to split for rods & cones

**Comment by krchristie** [comment]
These are the CC terms I've found that relate to photoreceptor cilia. None have specific child terms. Defs of some have been written as if the rod cell is the only type. This quote may explain why these terms seem rod cell centric, even though they are supposed to be general terms.

Quote from PMID:11826267 Ann Rev Physio 2002 (used in def of 'photoreceptor disc membrane')
> This review focuses on recent developments in the understanding of two quantitative features of G protein signaling in phototransduction: signal amplification and response timing. It also focuses entirely on rods, which are the more abundant photoreceptors in the retinas of most vertebrates, with the consequence that the quantitative aspects of G protein signaling have been studied in much greater detail in rods than in cones.

- CC photoreceptor cell cilium (GO:0097733) - no child terms
- CC photoreceptor connecting cilium (GO:0032391) - no child terms

- CC photoreceptor inner segment (GO:0001917) - no child terms
- CC photoreceptor inner segment membrane (GO:0060342) - no child terms

- CC photoreceptor outer segment (GO:0001750) - def is apparently specific to rod cell structure while not mentioning rod cells specifically (Peter and	I think that this should become the general term because the annotations clearly involve both rod and cone cells
- CC photoreceptor outer segment membrane (GO:0042622) - no child terms
- CC photoreceptor disc membrane (GO:0097381) - Although Peter and I thought that this def seemed apparently specific to rod cell structure though it doesn't mention rod cells specifically (3 refs, most recent is 2002), we found that the phrase "disc membranes" is also used for cyrptochrome containing cone cells (PMID:21647441).


- CC photoreceptor ribbon synapse (GO:0098684) - no child terms; paper cited in def gives differences in this structure for rod vs cone cells
- CC photoreceptor cell terminal bouton (GO:1990796) - general, no child terms
- CC accessory outer segment (GO:1990906) - term is written generally, but from reference (about Zebrafish) this structure may be cone specific

**Comment by krchristie** [comment]
@deustp01 (please correct or add anything I missed) and I talked this morning and are both in agreement that due to both the difference in structure and the specific gene products present, as well as the differences in use in color vision versus night vision, that there is good reason to split out terms for rod and cone cells.

Regarding the CC terms, all of our existing terms are named generally and the ones we checked have clearly been used for annotating both rod and cone gene products, so we feel the existing terms should remain general and we'd like to create rod and cone specific child terms.

Regarding the BP terms, I think it would make sense to make some child terms under the cell development-type terms that don't already have them, but feedback from @ukemi might be useful.

**Comment by deustp01** [comment]
**Relationships of photoreceptor cell inner (GO:0001917), connecting (GO:?), and outer segments (GO:0001750) to photoreceptor cilium (GO:0097733)**

Question: is the photoreceptor connecting cilium (GO:0032391) meant to include the plasma membrane that surrounds it? If so then this term is identical to photoreceptor cell connecting segment. However, for consistency with the definition of GO:0097733 photoreceptor cell cilium (“A specialised 9+0 non-motile cilium found in photoreceptor cells. A ciliary transition zone called 'photoreceptor connecting cilium' links the photoreceptor outer segment to the inner segment”), the connecting cilium term should refer only to the region of the 9+0 non-motile cilium that spans the connecting segment of the photoreceptor cell and not to the plasma membrane that surrounds this segment of the photoreceptor. 

In that case, we need a new cell component term and child:

GO:new photoreceptor connecting segment. Definition The segment of a vertebrate photoreceptor that connects its inner and outer segments, spanned by the photoreceptor connecting cilium.

GO:new photoreceptor connecting segment membrane. Definition The membrane surrounding the connecting segment of a vertebrate photoreceptor. [part_of photoreceptor connecting segment]

Question – what is the relationship of the photoreceptor connecting cilium (GO:0032391) to the inner, connecting, and outer segments of the photoreceptor cell? As shown in the diagram from PMID 19582864 figure 2, its basal body is within the inner segment, it spans the connecting segment, and extends some distance into the outer segment. These relationships are explicitly shown for rod cells, and partly shown, partly implied for cone cells. Does this give the cilium a part_of relationship to all three segments?
<img width="512" alt="Screen Shot 2019-05-05 at 1 16 27 PM" src="https://user-images.githubusercontent.com/12737623/57197980-86fd1f80-6f3b-11e9-810a-7d87b7b679db.png">

**Comment by deustp01** [comment]
**CC photoreceptor disc membrane (GO:0097381) - possible new rod vs cone-agnostic name and definition.**

Name: photoreceptor outer segment membrane stack [or structure or pile or ...?]

Definition was: Ovally-shaped membranous stack located inside the photoreceptor outer segment, and containing densely packed molecules of the photoreceptor protein rhodopsin that traverse the lipid bilayer. Disc membranes are apparently derived from the plasma membrane in the region of the cilium that connects the photoreceptor outer segment to the inner segment.

change to: Ovally-shaped membranous stack located inside the photoreceptor outer segment, and containing densely packed molecules of the photoreceptor proteins opsins or rhodopsin that traverse the lipid bilayer. These membranes are derived from the plasma membrane in the region of the cilium that connects the photoreceptor outer segment to the inner segment. They may be sealed to form discs, cytoplasmic structures with the topology of cytoplasmic vesicles or may remain open to the extracellular space, forming lamellae with the toplogy of cell projections.

The diagram attached to the previous comment (PMID 19582864 figure 2) is useful here too.

**Comment by deustp01** [comment]
**Proposed terms for photoreceptor cell parts, with definitions and parentages**

PMID 19582864

GO:0001750 Photoreceptor outer segment. The outer segment of a vertebrate photoreceptor that contains discs stacks of photoreceptive membranes
     GO:new Rod cell outer segment. The outer segment of a vertebrate rod cell photoreceptor that contains a stack of photoreceptive membranes in the form of closed cytoplasmic vesicles. [Should rhodopsin be part of the definition?]
     GO:new Cone cell outer segment. The outer segment of a vertebrate cone cell photoreceptor that contains a stack of photoreceptive membranes in the form of lamellae open to the extracellular space. [Should opsin be part of the definition?]

GO:new Rod cell disc stack. Oval-shaped membranous stack located inside the rod cell outer segment, and containing densely packed molecules of the photoreceptor rhodopsin protein. These membranes are derived from the plasma membrane in the region of the cilium that connects the photoreceptor outer segment to the inner segment. They are sealed to form discs, cytoplasmic structures with the topology of cytoplasmic vesicles.
[is_a Photoreceptor outer segment membrane stack (GO:0097381)]
[part_of Rod cell outer segment (GO:new)]
     GO:new Rod cell disc. An individual closed flattened cytoplasmic vesicle bounded by a lipid bilayer membrane contained within the outer segment of a vertebrate rod cell. The disc is derived from the rod cell plasma membrane and contains densely packed molecules of the photoreceptor rhodopsin protein.
[is_a cytoplasmic vesicle (GO:0031410)]
               GO:new Rod cell disc membrane. The lipid bilayer surrounding a rod cell disc. [Should rhodopsin be part of the definition?]
               GO:new Rod cell disc lumen. The volume enclosed by the membrane of a rod cell disc membrane.

GO:new Cone cell lamellar stack. Oval-shaped membranous stack located in the cone cell outer segment, and containing densely packed molecules of photoreceptor opsin proteins. These membranes form as invaginations of the plasma membrane in the region of the cilium that connects the photoreceptor outer segment to the inner segment. They remain open to the extracellular space.
[is_a Photoreceptor outer segment membrane stack (GO:0097381)]
[part_of Cone cell outer segment (GO:new)]
     GO:new Cone cell lamella. An individual plasma membrane invagination contained within the outer segment of a vertebrate cone cell. The lamella contains densely packed molecules of photoreceptor opsin proteins.
[is_a plasma membrane part (GO:0044459)]

**Comment by krchristie** [comment]
**Regarding: Relationships of photoreceptor cell inner (GO:0001917), connecting (GO:?), and outer segments (GO:0001750) to photoreceptor cilium (GO:0097733)**
> 
> Question: is the photoreceptor connecting cilium (GO:0032391) meant to include the plasma membrane that surrounds it? 

That is an interesting question. The membrane is very tricky for an organelle whose bounding membrane is contiguous with the plasma membrane. I'll refrain from duplicating the extensive debates on that subject here. To be sure what an expert thinks, I found a review with Jeremy Reiter, a transition zone expert, as a co-author, and the diagram in that paper would suggest yes.

```
Garcia-Gonzalo FR, Reiter JF. Open Sesame: How Transition Fibers and the
Transition Zone Control Ciliary Composition. Cold Spring Harb Perspect Biol. 2017
Feb 1;9(2). Review. PubMed PMID:27770015
```
![GarciaGonzalo-27770015](https://user-images.githubusercontent.com/10533218/57259470-9f8d3880-7014-11e9-950a-2efd40849d7c.jpg)

> If so then this term is identical to photoreceptor cell connecting segment. 

Yes, I would agree that 'photoreceptor connecting cilium' is meant to be synonymous with 'photoreceptor cell connecting segment'. That is certainly what Paola and I intended.

> However, for consistency with the definition of GO:0097733 photoreceptor cell cilium (“A specialised 9+0 non-motile cilium found in photoreceptor cells. A ciliary transition zone called 'photoreceptor connecting cilium' links the photoreceptor outer segment to the inner segment”), the connecting cilium term should refer only to the region of the 9+0 non-motile cilium that spans the connecting segment of the photoreceptor cell and not to the plasma membrane that surrounds this segment of the photoreceptor.

I don't follow your logic that this definition means that the connecting cilium term should not encompass the membrane surrounding this region. As I said above, the cilium is definitely tricky with respect to the ciliary membrane, but I think that the existing term should encompass the entire connecting cilium/transition zone including the membrane.

Regarding whether we need child terms to encompass the membrane and internal region separately, do you have an annotation need to distinguish the membrane region from the internal region of the connecting cilium? I'm fine with making these new child terms if they are needed for annotation, but otherwise think they may be unnecessary. I do not think I have ever needed to annotate to the membrane versus the internal region of the connecting cilium separately.
 
> In that case, we need a new cell component term and child:
> 
> GO:new photoreceptor connecting segment. Definition The segment of a vertebrate photoreceptor that connects its inner and outer segments, spanned by the photoreceptor connecting cilium.

If we do need the child terms, I don't understand how your definition of 'photoreceptor connecting segment' is distinguished from the definition of the existing term:

**photoreceptor connecting cilium (GO:0097733)**
The portion of the photoreceptor cell cilium linking the photoreceptor inner and outer segments. It's considered to be equivalent to the ciliary transition zone.
 
> GO:new photoreceptor connecting segment membrane. Definition The membrane surrounding the connecting segment of a vertebrate photoreceptor. [part_of photoreceptor connecting segment]




> Question – what is the relationship of the photoreceptor connecting cilium (GO:0032391) to the inner, connecting, and outer segments of the photoreceptor cell? As shown in the diagram from PMID 19582864 figure 2, its basal body is within the inner segment, it spans the connecting segment, and extends some distance into the outer segment. These relationships are explicitly shown for rod cells, and partly shown, partly implied for cone cells. Does this give the cilium a part_of relationship to all three segments?

The 'photoreceptor connecting cilium' is another phrase for what you have been referring to as the 'connecting segment'. The large number of papers I have encountered have just called it the 'connecting cilium', but Paola and I thought that it was better as a term name to include the word 'photoreceptor' to eliminate potential confusion with any other areas of biology that may use the same or similar phrase for something different.

The 'photoreceptor cell cilium' is the entire cilium, which has its base in the cell body, aka inner segment, and then the connecting segment and outer segments are parts of the cilium.

**Comment by deustp01** [comment]
Difficulty following logic - I was trying to list various possibilities and variant outcomes according to which possibility was correct. The new reference looks like it addresses the variants, so the next step for me is to read it and see if I can simplify the logic.

**Comment by krchristie** [comment]
Maybe just address the simpler question: Do you need to be able to distinguish the membrane of the connecting cilium from the internal portion for annotation purposes? If not, then there is no need for additional terms here.

**Comment by krchristie** [comment]
**Regarding: CC photoreceptor disc membrane (GO:0097381) - possible new rod-cone-agnostic name and definition.**
 
> Name: photoreceptor outer segment membrane stack [or structure or pile or ...?]

Based on the papers we looked at together on Friday 5/3, and others I've looked at today, the word 'disc' is already agnostic to cones versus rods. Despite still being connected to the ciliary membrane the structures in cones are referred to as discs in many papers, including this recent review with a sample quote:

Mustafi D, Engel AH, Palczewski K. Structure of cone photoreceptors. Prog Retin Eye Res. 2009 Jul;28(4):289-302.  Review.  PMID:19501669

`The disc is an important structural component in this step, and in the cone, the disc shape and composition is a critical determinant of its extended activity in light, as contrasted to rods. In cones, the protein molecules of the biochemical cascade are similar to those of rods, but they are located for the most part on open discs that are continuous with the plasma membrane, rather than on discrete disc membranes (Figure 3).`

and these two papers from 40-ish years ago:

- Steinberg RH, Fisher SK, Anderson DH. Disc morphogenesis in vertebrate photoreceptors. J Comp Neurol. 1980 Apr 1;190(3):501-8. PMID:6771304.
- Anderson DH, Fisher SK, Steinberg RH. Mammalian cones: disc shedding, phagocytosis, and renewal. Invest Ophthalmol Vis Sci. 1978 Feb;17(2):117-33. PMID:415019.

Considering that 'disc' is the standard word used for both cones and rods, I would prefer to keep this terminology rather than come up with something different, but not widely used in the literature.
 
> Definition was: Ovally-shaped membranous stack located inside the photoreceptor outer segment, and containing densely packed molecules of the photoreceptor protein rhodopsin that traverse the lipid bilayer. Disc membranes are apparently derived from the plasma membrane in the region of the cilium that connects the photoreceptor outer segment to the inner segment.

I agree the existing definition could use some improvement...
 
> change to: Oval-shaped membranous stack located inside the photoreceptor outer segment, and containing densely packed molecules of the photoreceptor opsin or rhodopsin proteins that traverse the lipid bilayer. These membranes are derived from the plasma membrane in the region of the cilium that connects the photoreceptor outer segment to the inner segment. They may be sealed to form discs, cytoplasmic structures with the topology of cytoplasmic vesicles or may remain open to the extracellular space, forming lamellae with the toplogy of cell projections.
> 
> The diagram attached to the previous comment (PMID 19582864 figure 2) is useful here too.

I think that your definition is an improvement, and I have some additional suggestions & questions:

**[delete: Oval-shaped - do not see any mention of 'oval' in any of three references cited in this definition and listed below]** Membranous stack located inside the photoreceptor outer segment, and containing densely packed molecules of the photoreceptor opsin or rhodopsin proteins that traverse the lipid bilayer. These membranes are derived from the plasma membrane in the region of the cilium that connects the photoreceptor outer segment to the inner segment **[should this say to the connecting cilium instead of the inner segment?, since the outer and inner segments are not directly adjacent, but instead each are adjacent to the connecting cilium..]**. They may be sealed to form discrete discs, cytoplasmic structures with the topology of cytoplasmic vesicles or may remain open to the **cytoplasmic (I do not see how they are open to the extracellular space...)** space, forming lamellae with the toplogy of cell projections.



Arshavsky VY, Lamb TD, Pugh EN Jr. G proteins and phototransduction. Annu Rev  Physiol. 2002;64:153-87. Review.  PMID:11826267.

Yau KW. Phototransduction mechanism in retinal rods and cones. The Friedenwald Lecture. Invest Ophthalmol Vis Sci. 1994 Jan;35(1):9-32.  PMID:7507907.

Chabre M, Deterre P. Molecular mechanism of visual transduction. Eur J Biochem. 1989 Feb 1;179(2):255-66. Review.  PMID:2537204.

Add this reference to def: 
Mustafi D, Engel AH, Palczewski K. Structure of cone photoreceptors. Prog Retin Eye Res. 2009 Jul;28(4):289-302. Review.  PMID:19501669

**Comment by deustp01** [comment]
Back to the connecting region.

> 
> Yes, I would agree that 'photoreceptor connecting cilium' is meant to be synonymous with 'photoreceptor cell connecting segment'. That is certainly what Paola and I intended.
> 
>     However, for consistency with the definition of GO:0097733 photoreceptor cell cilium (“A specialised 9+0 non-motile cilium found in photoreceptor cells. A ciliary transition zone called 'photoreceptor connecting cilium' links the photoreceptor outer segment to the inner segment”), the connecting cilium term should refer only to the region of the 9+0 non-motile cilium that spans the connecting segment of the photoreceptor cell and not to the plasma membrane that surrounds this segment of the photoreceptor.
> 
> I don't follow your logic that this definition means that the connecting cilium term should not encompass the membrane surrounding this region. As I said above, the cilium is definitely tricky with respect to the ciliary membrane, but I think that the existing term should encompass the entire connecting cilium/transition zone including the membrane.

The connecting segment of a photoreceptor cell is bounded by a lipid bilayer membrane. What I'm fussing about is only whether the definition is meant to include that part. If it does, nothing more is needed exactly as you say in your following comment.

**Comment by deustp01** [comment]
Now your comments / revisions to the proposed terms and definitions.

Disc versus lamellae. If people used different words to describe rod and cone structures, we could follow that usage and avoid ambiguity. They don't so we can't - discs everywhere.

What are the lamellae open to? "Open to extracellular space" is my interpretation of the various micrographs and diagrams, like this bit of Figure 1 from Mustafi et al. (PMID: 19501669):
<img width="72" alt="Screen Shot 2019-05-07 at 4 06 31 PM" src="https://user-images.githubusercontent.com/12737623/57329639-33790600-70e2-11e9-93c1-ee09c61f984a.png">
But I am definitely not an expert, so whatever topology fits the real expert consensus is the one I was aiming for.

Inner segment - connecting segment - yes, as you say.

**Comment by krchristie** [comment]
** Regarding what lamellae are open to:** The reason why the cone lamellae are not open to the extracellular space is that on the extracellular  side the membrane completely encloses the disk. The place where the membrane of the disc is open is adjacent to the cilium. Thus, the lamellae are open to the 'cilary cytoplasm'.

**Regarding transition zones:** My interpretation of both the existing GO definitions and the diagrams I've seen, both the one I included above as well as another review, is that the transition zone includes the membrane in that region. If you feel it would be helpful, we could add to the definition to be explicit about this.

**Comment by krchristie** [comment]
Actually, thinking more about cone discs, I'm not sure it makes sense to talk about what they are open to. I am not seeing that kind of language in the literature. Rather, researchers talk about the fact that the membrane is contiguous with the ciliary membrane. This type of phrase is used both in the paper you cite and the review I found: 

Kennedy B, Malicki J. What drives cell morphogenesis: a look inside the vertebrate photoreceptor. Dev Dyn. 2009 Sep;238(9):2115-38. PMID:19582864

Mustafi D, Engel AH, Palczewski K. Structure of cone photoreceptors. Prog Retin Eye Res. 2009 Jul;28(4):289-302. doi: 10.1016/j.preteyeres.2009.05.003. PMID:19501669

**Comment by deustp01** [comment]
Transition zone - the definition hasn't bothered anyone except me; let's leave it as-is.
What the cone discs/lamellae open to - "contiguous with ciliary membrane" sounds good.

**Comment by krchristie** [comment]
**Regarding: Proposed terms for photoreceptor cell parts, with definitions and parentages**

> PMID 19582864
>
> GO:0001750 Photoreceptor outer segment. The outer segment of a vertebrate photoreceptor that contains discs stacks of photoreceptive membranes

> This term has two is_a children:
> GO:new Rod cell outer segment. The outer segment of a vertebrate rod cell photoreceptor that contains a stack of photoreceptive membranes in the form of closed cytoplasmic vesicles. [Should rhodopsin be part of the definition?]
> GO:new Cone cell outer segment. The outer segment of a vertebrate cone cell photoreceptor that contains a stack of photoreceptive membranes in the form of lamellae open to the extracellular space. [Should opsin be part of the definition?]

I am in agreement that we need rod and cone specific terms for outer segments. It would be helpful to annotators to have rhodopsin and opsin mentioned somewhere, but perhaps most appropriate in the membrane child terms.


The existing term **photoreceptor disc membrane (GO:0097381)** is a membrane term, currently
`is_a: ciliary membrane`

While this `is_a: ciliary membrane` is problematic for the rod disc membrane as it is no longer
contiguous with the ciliary membrane, I don't think we can convert this term from being a membrane term to being a term for the whole stack. To handle the difference in topology between the discs in rod and cone cells, we will need to change the parentage of this general term, and then the rod and cone specific terms will need the distict appropriate parentage for each.

Another major issue for me is I don't see an annotation need to have separate terms for the stacks
versus individual discs. Unlike the Golgi stack, I don't think there is any evidence for
differential localization of any gene products to distal versus proximal discs in photoreceptor disc
stacks. When we talked last week, we talked about the need to represent the difference in structure of the rod and cone disc stacks, and then you also need a rod disc lumen term. I don't see any annotation need for specific terms for either discs or stacks. Below is what I think we need, in context with a few of the existing terms.

```
- photoreceptor outer segment (GO:0001750)
-- cone photoreceptor outer segment (**GO:new**)
-- rod photoreceptor outer segment (**GO:new**)

- photoreceptor disc membrane (GO:0097381)
    [change parentage from is_a 'ciliary membrane' to is_a 'membrane'
-- cone photoreceptor disc membrane  (**GO:new**)
    [is_a 'ciliary membrane'; this parent term is already a child of 'cell projection membrane']
    [part_of cone photoreceptor outer segment (GO:new)]
    [synonym (EXACT): cone photoreceptor lamella membrane]
-- rod photoreceptor disc membrane (**GO:new**)
    [is_a 'cytoplasmic vesicle membrane']
    [part_of rod photoreceptor outer segment (GO:new)]

-- rod photoreceptor disc lumen (**GO:new**)
    [is_a 'membane enclosed lumen']
    [part_of rod photoreceptor outer segment (GO:new)]
```

**Comment by deustp01** [comment]
Parentage. If I read right, you have it sorted out - no concerns or suggestions here.
Terms for individual discs versus the whole stack. The only need that I know of is that we want to be able to refer to the rod disc lumen and I couldn't think of a way to refer to that lumen except as a part_of an individual disc. If you're OK with the idea that a disc stack can have a lumen then there's no need at all for individual discs.

**Comment by krchristie** [comment]
Well, 'a' disc stack does not have 'a' lumen, but we won't have a term for disc stack anyway, only membrane terms and the rod disc lumen term. I realize it isn't a full representation of the structure, but I think it meets annotations needs without creating a bunch of terms that I can't seen any utility for with respect to annotation.

**Comment by deustp01** [comment]
That sounds fine!

**Comment by krchristie** [comment]
What initials do you use for your definition dbxref, GOC:pd?

**Comment by deustp01** [comment]
I don't know. I think I've never been credited with an ontology term @ukemi?

**Comment by krchristie** [comment]
GOC:pd does not seem to be used in the entire entology, while GOC:pde had been used 96 times.

It would be really useful if the list of curators & abbreviations was available to editors somewhere, not necessarily somewhere public. @ukemi @cmungall

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-site/blob/master/metadata/users.yaml

**Comment by krchristie** [comment]
@deustp01 - You are represented by GOC:pde, and are credited in 96 term definitions.

Here is a diff showing 5 new terms related to photoreceptor outer segments, as well as modifications to the definitions of two existing terms: 
- photoreceptor outer segment
- photoreceptor disc membrane

https://github.com/geneontology/go-ontology/pull/17250/files

Take a look and see if you are OK with these new terms and definitions.

Note: ignore the fact that I wasn't paying attention and set the namespace of these new terms as CC. I've already fixed my version, but don't want to push the fix yet since I can't remember if you'll still be able to see this diff once I push the namespace fix.

**Comment by krchristie** [comment]
@deustp01 - I'm thinking that perhaps just these 5 new terms is enough. It covers what you need, and covers the area of the photoreceptor outer segments that are topologically different. Perhaps all the rest can be handled with existing terms and extensions/GO-CAM models for cell types.

Let me know if you think the defs I've put in look OK to you.

**Comment by deustp01** [comment]
@krchristie  The five terms cover everything needed now - both the specific lumen term we wanted, and related terms created to distinguish rod- and cone-specific cell_compartments.
The defs look fine.

**Comment by krchristie** [comment]
@deustp01 - Thanks for checking. I've committed these terms now.
