### ISSUE TITLE
Add taxon constraints GO:0047077 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17320]
Please add only in: 

Lampyridae NCBITaxon:7049 
Phengodidae NCBITaxon: 94777
Rhagophthalmidae: NCBITaxon: 71489
Elateridae: NCBITaxon: 30009

(I have not done these with the new system; so if someone else can do it that's be great ! ) 

Thanks, Pascale

**Comment by ukemi** [comment]
Does it make logical sense to add only in to more than one taxon? Doesn't it mean only in?

**Comment by balhoff** [comment]
@ukemi you are correct it wouldn't work. Could either use the common superclass of all these, or create a taxon union in go-taxon-groupings, if it is a grouping worth naming (probably not?).

**Comment by photocyte** [comment]
Hi there, I'm the original reporter (tfallon@mit.edu).  The superfamily Elateroidea (NCBITaxon 71193 ) holds each of these 4 families, so should be a sufficient solution if the individual families aren't possible.

It is worth mentioning, there are quite a few engineered luciferases, that can accurately hav ethe GO:0047077 GO term. Although they are all derived from the native luciferases of the above families, I'm not sure what their resulting taxon would be considered in sequence databases.

**Comment by balhoff** [comment]
@photocyte the assertion would be that this activity is found within Elateroidea and nowhere else in life. I'm not sure that there is any issue with engineered luciferases—@ukemi?

**Comment by ukemi** [comment]
The engineered ones wouldn't fall in the scope of GO, so I think we are ok.

**Comment by hdrabkin** [comment]
So using Elateroidea (NCBITaxon 71193 )  would be safe?

**Comment by krchristie** [comment]
I understand that luciferases evolved independently many times, so is this superfamily taxon sufficient to encompass all the luciferases that should be described with this GO term?

**Comment by photocyte** [comment]
Luciferases did evolve independently many times, and use several different substrates.  But, for this particular GO term, which is Photinus luciferin monooxygenation activity specifically, all the specialized Photinus luciferin luciferases are within the beetle families in the Elateroidea.  

There was a report that an unrelated fly (Arachnocampa) used Photinus luciferin to produce light, but that hasn't really panned out.  If you look carefully, you can find Photinus luciferase activity in non-luciferase acyl-CoA ligases, found in species outside the Elateroidea e.g.:
Viviani VR, Scorsato V, Prado RA, Pereira JGC, Niwa K, Ohmiya Y, Barbosa JARG. 2010. The origin of luciferase activity in Zophobas mealworm AMP/CoA-ligase (protoluciferase): luciferin stereoselectivity as a switch for the oxygenase activity. Photochemical & Photobiological Sciences 9:1111. doi:10.1039/c0pp00080a . 

But that is kind of a special case, interpreted as a sort of background or promiscuous activity, rather than a selected luciferase.  There are probably only 2 or 3 non Elateroidea acyl CoA ligases superfamily enzymes which would have experimentally demonstrated Photinus luciferin monooxygenation activity.  Are they "luciferases", or should they have the GO term, are sort of subtle points.  The majority of the issues this change would fix are when people annotate all the acyl-CoA ligases in their new genome as luciferases, in the absence of any evidence to do so besides distant sequence similarity to actual luciferases.

**Comment by hdrabkin** [comment]
Ok; so adding the suggested single constraint so I can close?

**Comment by hdrabkin** [comment]
Added
