### ISSUE TITLE
GO:0044215 'other organism' looks like it's in the wrong branch of the ontology

### ISSUE THREAD

**Issue by dillerm** [geneontology/go-ontology#17355]
The parent class of 'other organism' is 'cellular_component'. Now, there is a comment that mentions that this branch will be obsoleted in the future, but I figured I'd bring this to your attention just in case plans to obsolete it have changed.

**Comment by pgaudet** [comment]
There are no annotations to either GO:0044215 'other organism' or its child 'GO:0018995 host' . 
I think these can be obsoleted without any impact. 

Related terms
----
- 'host' is used as a subclass of GO:0043655 extracellular space of host (5 EXP annotations), which itself has 2 children: 
-- GO:0085040 extra-invasive hyphal space: no annotations -> OBSOLETE
-- GO:0085036 extrahaustorial matrix : no annotations -> OBSOLETE

-- GO:0044216     other organism cell 4 EXP annotations (not very informative??) -> OBSOLETE

--  'host cell' 42 EXP -> Merge with GO:0033643 host cell part or obsolete and reannotate
-- GO:0019035 'viral integration complex' -> Move under 'host cell part' 


Does that seem OK ? 
Also @pmasson55 @ValWood @mgiglio99 @jimhu-tamu if you have thoughts about this one, please do comment. 

Thanks, Pascale

**Comment by pmasson55** [comment]
Sounds good to me
:)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0044215 other organism' and 'GO:0018995 host'. The reason for obsoletion is that these represent organisms, which is not in the scope of GO. There is one annotation to 'host (disputed in Protein2GO) and no mappings to these terms. These terms are not in any subsets (slims). 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/17355

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on May 31st, 2019. Unless objections are received by May 31st, 2019, we will assume that you agree to this change.

Thanks, Pascale

**Comment by mgiglio99** [comment]
Hi Pascale,
Under the Related terms section above you have notes about obsoleting 'host cell' - but will that be discussed in a different thread? Or should that be discussed now/here?
Michelle

**Comment by genegodbold** [comment]
A host cell can only be considered a host in the context of the presence of a parasite. The designation of a parasite requires the designation of a particular organism as a "host". I've been working on categorizing the relations of host and parasite (mostly microbial parasites: viral, bacterial, protozoan; a few multicellular eukaryotes) with regard to the protein factors they employ and the (host) pathways they affect.

**Comment by pgaudet** [comment]
@mgiglio99 

> you have notes about obsoleting 'host cell' - but will that be discussed in a different thread? Or should that be discussed now/here?

I think we should discuss elsewhere. I'll open a ticket.

**Comment by pgaudet** [comment]
@genegodbold 

Thanks for your comment - I am not clear what exactly is your suggestion, can you provide more details? 

Thanks, Pascale

**Comment by mgiglio99** [comment]
Regarding the proposed obsoletions, I'm concerned about getting rid of 'host'. I imagine there will be times you know a gene product is put into the host, but not exactly where in the host it is . And currently host is a useful grouping term. I know there are plans to get rid of this branch and capture this info in some other way,  but until we have that way, I'm hesitant to get rid of it.

I think I'm ok with getting rid of 'other organism'. 
But thinking about this term made me think of something else related to this term, how would one annotate toxins produced by things like jellyfish and snakes? I remember this being discussed in the past, and I think 'other organism' was how PAMGO thought this would be handled.  I totally understand that 'other organism' is not a cellular component, but then how do we annotate the location of those gene products?  Sorry if I'm asking about something that has already been dealt with.

**Comment by genegodbold** [comment]
Some folks at the Johns Hopkins APL under Jody Proescher are working on instantiating/improving a pathogen gene ontology (PathGO). I haven't spoken with them since January. They're going to have to deal with some of these issues. They were about to hire an ontologist the last time I heard from them, but they were rather short-handed microbiologically (and immunologically). 

Michele, would "target organism" be a way to designate where a toxin (or any other biological product) is being vectored? I guess it's six of one...

Pascale, I'm not sure I was providing an "answer" as much as raising a question. Uniprot is adorned with parasite proteins that do not specify the host species in which they operate. There are no generic parasite proteins capable of functioning as such in *any* host. So to keep track of which ones are "dangerous" to human civilization--my present concern--one must overlay a host-pathogen database over the top of it keyed to the origin of the parasite protein. (Otherwise, one might be annotating bacteriophage proteins as worrisome.)

**Comment by pgaudet** [comment]
Hi @mgiglio99 

I was thinking the appropriate term was 'host cell part', if the exact location is not know. Would that work ?

**Comment by mgiglio99** [comment]
Hi @pgaudet 
But wouldn't 'host cell part' imply it was in the cell? Would that include when it's extracellular but still in the host? And I somehow had in my head that we weren't supposed to use the '...part' terms for direct annotations - but I could be confused on that.

**Comment by ValWood** [comment]
@genegodbold do you know the scope of the proposed PathGO? is it the same scope as GO? (function/process/component?)

**Comment by genegodbold** [comment]
Hey @mgiglio99,
Would the use of the adjective "heterologous" be helpful for a gene product being directed elsewhere?

**Comment by genegodbold** [comment]
Hey @ValWood, I am not privy to the precise scope of what APL is doing for IARPA (the sponsor) on Fun GCAT. My understanding is that they are supposed to expand PathGO.

**Comment by pgaudet** [comment]
@mgiglio99 

Right now 'extracellular space of host' is an 'extracellular region part' (I guess it could be an 'extracellular region). 

<img width="154" alt="image" src="https://user-images.githubusercontent.com/4782928/58486459-35286d80-8166-11e9-82e1-a5f306af2054.png">


Does not having the link to 'part of host' cause a problem ? (I had removed it as a first step to doing this ticket). 

Thanks, Pascale

**Comment by ValWood** [comment]
OK I don't see  PathGO in obo or OLS....

**Comment by genegodbold** [comment]
The APL folks are busy, but I'm really hoping this doesn't fall of their radar.

**Comment by jimhu-tamu** [comment]
@genegodbold I hope we can get your friends working on PathGO to interact with those of us in the working group working on representation of multiorganism functions in GO. Would be a shame if there was duplicated effort that led to incompatible practices.

**Comment by mgiglio99** [comment]
> Does not having the link to 'part of host' cause a problem ? (I had removed it as a first step to doing this ticket).

I think it would be best to have the 'part of host' link. Otherwise it will be harder to slim up things that go into hosts. And harder for people to find relevant host terms for annotation.

**Comment by mgiglio99** [comment]
> Would the use of the adjective "heterologous" be helpful for a gene product being directed elsewhere?

That to me has the connotation of something going where it normally doesn't go, while these proteins have evolved for entering the host and doing things. So, I'm not sure that will solve it.

**Comment by genegodbold** [comment]
Hey @jimhu-tamu, 
Oh, I agree--and I'm sure they would, too. I think their deliberateness in how they are proceeding is to avoid making mistakes. The project is trying to conceive of what enables pathogenicity **in general** and across parasites and hosts: primates, livestock (mammals and avian) and crop plants. They've got the harder job: trying to represent it with text. What makes a good bug bad? What can make a bad bug worse? It's easier to "see" it when looking at the literature.

**Comment by mgiglio99** [comment]
> A host cell can only be considered a host in the context of the presence of a parasite.

There doesn't have to be a parasite. There are many host-symbiont relationships that are not parasitic. The interactions of humans and their microbiomes being one example.

**Comment by genegodbold** [comment]
Dear Michele @mgiglio99,
Of course you're right. My biodefense bias is showing. When you're worried about evil bioengineering, every commensal is a potential parasite.

Your argument against "heterologous" is convincing as well. 

Anecdote: Lactococcus lactis has been used as a vehicle for heterologous expression to study virulence factors. It can thereby be made pathogenic for mice.

**Comment by ValWood** [comment]
@genegodbold PomBase's collaboration    PHI-BAse might be useful to your colleagues.
Basically, we are curating the molecular changes and phenotypes in pathogen-host interactions using the concept of a "multi-species genotype"

At present, we are curating a range  of test papers for common experiment types, for example: 
https://canto.phi-base.org//curs/f41d30e250b8f9b0/ro/
(A really great example where single amino acid changes in the interacting pair in the  pathogen or the host can alter pathogenicity):
and
https://canto.phi-base.org//curs/bd02fdb6831712ca/ro/

It's going slowly because we are building the pathogen-host interaction phenotype ontology as we go (seeded by the PHIbase core concepts like "increased virulence" but extended to include pathogenicity related observations). Because this development is critically dependent on GO it raises many questions surrounding the existing GO structure in the pathogenicity branch(s). 

Our particular focus is *mainly* crop plants, although I believe branching into fungal-human  pathogen-host interactions is part of PHI-Base's new grant.

The curation tool we developed at PomBase (Canto)  is generic and can be configured be used with any ontologies/species/strains. If suitable ontologies already exist for any part, we will use them.

**Comment by pgaudet** [comment]
Hi @mgiglio99 I've added back the link between 'extracellular space of host' and host. 

A few points: 
- We have an issue with annotation consistency: 'extracellular space of host' and 'extracellular space' are used interchangeably, as far as I can tell (see QuickGO, this is especially ovbious for viruses)
- Let's discuss whether we should also merge the following terms, since there are no 'symbiont' equivalent: 
-- 'other organism part' ->  'host cell part'
-- other organism cell -> 'host cell' 
-- 'other organism membrane' (no 'host' equivalent)
-- 'other organism cell membrane' -> 'host cell membrane'
--'other organism postsynaptic membrane' (no 'host' equivalent) **
--'other organism presynaptic membrane' -> 'host cell presynaptic membrane' **

**surely these 2 can only be 'host'??? 

Thanks, Pascale

**Comment by genegodbold** [comment]
@ValWood 
We might should take this offline. I sent you an invitation on LinkedIn. Strangely enough, I spent last week figuring out how we might employ PHI-Base.

I think "virulence", "pathogenicity", and cognates of "toxic" are words almost too slippery to be useful when one is trying to understand (and describe) the mechanism for what are commonly called virulence factors. They are terms to which one must resort when dealing with the organism as a whole and not when one is looking at the cellular/molecular level. Ideally, the host molecular target is identified specifically but if you can't do that, then the host pathway should be specified.

I think it is more helpful to use terms like adherence, invasion, secretion (effector), and specify which host system is being affected (transcription, translation, apoptosis, cytoskeleton, or endomembrane). Then we've been trying to provide some assessment of the effects on the host (active immune evasion, ECM destruction/tissue permeabilization, cytotoxicity/cell permeabilization, disable host organ). Perhaps the largest single category for describing virulence factors involves how they manipulate the host immune system. There is also something we're calling passive immune evasion where the VF modifies parasite proteins so they aren't as susceptible to host detection.

FWIW, we're planning to publish this stuff this year.

**Comment by pgaudet** [comment]
- [x] obsolete 'other organism' GO:0044215
- [ ] merge 'other organism part'  into-> 'host cell part'
- [ ]  other organism cell -> 'host cell'
- [ ] 'other organism membrane' (no 'host' equivalent)
- [ ]  'other organism cell membrane' -> 'host cell membrane'
- [ ] 'other organism postsynaptic membrane' (no 'host' equivalent) **
- [ ] 'other organism presynaptic membrane' -> 'host cell presynaptic membrane' **

**Comment by pgaudet** [comment]
add back relation 'host cell' 'part of' some host:
https://github.com/geneontology/go-ontology/pull/17456/commits/47fc86d7501e4cae2a1cd65abb3ffd183d30d195

**Comment by mgiglio99** [comment]
@pgaudet 
I think we decided to keep "host" as a term but I know it's problematic because it refers to a whole organism. I was wondering if we were to change "host" to "host cellular component" would that be better? Then it parallels the regular GO structure, but still keeps a way to group all host related terms.

**Comment by pgaudet** [comment]
Sound good, thanks

**Comment by pgaudet** [comment]
Changed host -> host cellular component
and made a few changes in the organisation of the CC for host and other organisms (on call with @mgiglio99 and @ValWood ). Changes can be viewed in the PR: https://github.com/geneontology/go-ontology/commit/6d7939a286b95e7128e8c7a25a1875c314b9621b

Pascale
