### ISSUE TITLE
Split and change labels ABC transporters and P-types transporters (was ABC transporters and P-types transporters? )

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17373]
Hello, 

For the MF refactoring of transporters: 
We have two groups of terms that represent the same function, ATPase-coupled transporter activity, but with slightly different mechanisms: describe ABC transporters and others P-types transporters ('phosphorylative mechanism'). 

Is this distinction necessary ? 
This seems to group protein families rather than different functions. 

@thomaspd @amandamackie

Thanks, Pascale

**Comment by deustp01** [comment]
The two families have quite distinct structures and accomplish the transport and energy consumption by quite different mechanisms - Alberts, Molecular Biology of the Cell, 5th ed, pp 654-5, 659-666.

**Comment by pgaudet** [comment]
I know the mechanism is different, but I thought that was not in the scope of GO. That being said, I dont mind having them in. (especially, they are all correctly annotated!) 

The next question would then be, can we go ahead and call them 'P-type ATPase transporters'? rather than 'ATPase activity, coupled to transmembrane movement of ions, phosphorylative mechanism' (or is this clear what it is ? 

Next-next question would be to have a similar grouping term for ABC transporters - right now they are all directly under the parent 

![image](https://user-images.githubusercontent.com/4782928/58266873-d12b3100-7d82-11e9-9f6c-7f9de819cffa.png)


I think there was a decision in the past NOT to use 'ABC transporter', but could we use 'ABC-type transporter activity? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Looks like Rhea merged ABC transporters and P-types, see for eg https://www.rhea-db.org/reaction.xhtml?id=14633

Is this right @annemorgat?

**Comment by deustp01** [comment]
@amorgat And could you say a bit about the rationale for the merge, if so? The Alberts Molecular Biology of the Cell textbook makes a big point about the distinct molecular properties of the ABC and P-type transporters, so I'm curious as it's not an area I really know (but we should all annotate it consistently).
Thanks

**Comment by amorgat** [comment]
@deustp01 and @pgaudet. To give you a proper feed-back, I need to wait Kristian Axelsen (@kaxelsen) who is in vacation this week. Kristian will be back the June 3. Sorry for the delayed answer!

**Comment by pgaudet** [comment]
Just for the record: This is what the branch looked like before I stated the work on this. ABC transporters are named 'ATPase-coupled x transporter' or 'x ABC transporter activity'
and P-type usually 'x-transporting ATPase' (although some ABC transporter are also called like that). The only way to know is to look at synonyms. 

So I will create two grouping terms 'ABC-type transmembrane transporter activity' and 'P-type transmembrane transporter activity', and rename all children with this pattern. 

(Note that I don't intend to do this for flippases and floppases, although some are ABC family and some are P-type 4 family). 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/4782928/58536815-d90b2b00-81f1-11e9-8f74-717a41f3c850.png">


OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
It does seem strange to use protein family names to group. If we need to keep them to distinguish the mechanism, it somehow feels more correct to have the mechanism in the term name (also prevent other such 'family' terms).

**Comment by pgaudet** [comment]
I agree, but the alternative is not pretty. 

Both P-type ATPases and ABC transporter act by inducing a conformational change (see 
https://en.wikipedia.org/wiki/P-type_ATPase#Mechanism and 
https://en.wikipedia.org/wiki/ATP-binding_cassette_transporter#Mechanism_of_transport)

Two differences: 
-  P-types undergo autophosphorylation
- P-types hydrolyse a single ATP, ABC's usually hydrolyse 2 ATPs (there are exceptions, see PMC4338842 - at least CFTR and SUR; ABCC8/9)

Adding this information in the term label seems tricky! Doyou have suggestions?

**Comment by ValWood** [comment]
OK, agreed.

**Comment by dsiegele** [comment]
I don't know if this is helpful, but I often refer to the Transporter Classification Database (www.tcdb.org) when I have questions about transporters. The TCDB classifies membrane transporter systems using both functional and phylogenetic information. 

TCDB classifies ATP-binding cassette transporters and P-type ATPase transporters into two superfamilies.
     http://www.tcdb.org/search/result.php?tc=3.A.1  The ATP-binding Cassette (ABC) Superfamily
     http://www.tcdb.org/search/result.php?tc=3.A.3  The P-type ATPase (P-ATPase) Superfamily

The subclasses of GO:0042626 ATPase-coupled transmembrane transporter activity seem to be based on the substrate being transported. The majority of P-type ATPase transporters in prokaryotes and eukaryotes catalyze cation uptake and/or efflux driven by ATP hydrolysis, but some have been shown to transport lipids, for example PMID:21454556. Would there need to be a separate branches for 'P-type ATPase transporter activity, coupled to movement of ions' and 'P-type ATPase transporter activity, coupled to movement of lipids'?

The ABC-type transporters catalyze uptake and/or efflux of a variety of substrates, including cations, anions, sugars, amino acids, glycolipids, siderophores, etc.

**Comment by kaxelsen** [comment]
@deustp0
Rhea only covers chemical transformations, it does not take the protein performing this transformation into account.  So in line with this, the mechanism is not taken into account either. This means that when a P-type ATPase and and an ABC ATPase performs the same overall reaction, it will be covered by the same Rhea ID.

**Comment by deustp01** [comment]
From @kaxelsen 's comment, all peptidases should map to a single Rhea reaction in which a molecule of water is incorporated lysing a peptide bond, but that is consistent with maintaining multiple GO MF terms that classify these peptidases further by location of the cleavage site (endo- and exopeptidases) and also by cleavage mechanism (serine peptidases, metallopeptidases, ...), so for molecular function terms (not process terms, as above) the fact that more than one GO term maps to a single Rhea reaction family doesn't look like an obstacle.
@pgaudet from @dsiegele 's comment, it looks like there are compact, widely-used names for the two functional kinds of ATP-consuming transporters, so why not use them? For definition purposes, if I understand right, in both cases a conformational change in the transporter causes a ligand binding site initially exposed on one side of a membrane to become exposed on the other side, so that ligand bound on the first side can be discharged on the second. In the case of P type transporters, phosphorylation of the transporter at the cost of an ATP drives the conformational change. In the case of ABC transporters, ATP binding drives the change and unbinding requires ATP hydrolysis so again tyransport happens at the cost of ATP.

**Comment by pgaudet** [comment]
OK we'll keep both P-type and ABC-type transporters. 
They will link to the same RHEA ID. 

Thanks, Pascale

**Comment by ukemi** [comment]
If they link to the same Rhea ID, they will have the same definition.

**Comment by pgaudet** [comment]
you mean textual definitions?

**Comment by ukemi** [comment]
The plan is to use the Rhea reactions to define GO-MFs, so if two different GO terms point to the same Rhea identifier, they will become equivalent terms.

**Comment by pgaudet** [comment]
OK - is this what we want to do ? That means GO cannot have different guidelines from Rhea for deciding when a catalytic activity exists - is this what was decided? 

Alternatively - we could allow 1:n mappings between Rhea and GO terms and only use Rhea to populate our definitions for 1:1 cases?

**Comment by deustp01** [comment]
Existence of catalytic activity - I'm confused - thought Rhea annotated descriptions of the chemical changes that happen in a reaction, not whether those changes are spontaneous or accelerated by a gene product acting as a catalyst.

If it is GO policy that if a Rhea reaction (family) has been annotated then there shall be exactly one GO MF term for enabling that reaction, then all Rhea:GO mappings must be one:one and all MF terms involving chemical reactions map to one Rhea reaction (family) either because it already exists or because GO people work with Rhea people to get the Rhea reaction (family) created.

That logic all looks straightforward, and now that David mentions it, yes, that was a decision from the December Geneva meeting.

Thinking about it now, I wonder if we want it uniformly - do we want all the distinct ways that ATP consumption can be coupled to transport against a concentration gradient, or all the ways that a peptide bond can be hydrolyzed to collapse into single MF terms? That, however, is a question of biologist usability (and maybe of slim uniformity, but that's not my headache), not of logic.

**Comment by pgaudet** [comment]
Do we want to revisit this decision ? 
If not I will merge....

**Comment by pgaudet** [comment]
A few edits I can already do: 

GOID | Term label | Number of direct annotations   (non-IEA, non-IBA, non-ISO) | Family | EC | MetaCyc | Rhea | Other mapping | Notes | Action
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
GO:0102022 | ATPase-coupled L-arginine   transmembrane transporter activity' | 4 | ABC-type | EC:7.4.2.1 | ABC-4-RXN | 29879 |   | All annot are ISS TIGR | Merge into 'ATPase-coupled polar   amino acid-transporter activity'; same EC
GO:0042961 | ATPase-coupled antimonite   transmembrane transporter activity' | 0 | Neither - see https://www.ebi.ac.uk/interpro/entry/IPR025723 | EC:3.6.3.16 | NA | NA | NA |   | Merge into 'GO:0015446    ATPase-coupled arsenite transmembrane transporter activity' + change   label (transports both arsenite and antimonite)
GO:0015612 | L-arabinose-importing ATPase activity' | 0 |   | EC:3.6.3.17 - remove, too general | ABC-2-RXN |   | TC:3.A.1 (general ABC transporter) |   | Merge into GO:0015147 L-arabinose transmembrane transporter activity'
GO:0015608 | carbohydrate-importing ATPase activity' | 6 | ABC transporter |   |   |   | All ISS TIGR/JCVI | Merge into GO:0043211 ATPase-coupled carbohydrate transmembrane   transporter activity
GO:0015610 | glycerol phosphate-importing ATPase activity' | 0 |   | NA | NA | NA | TC:3.A.1 (general ABC transporter) | Merge into GO:0015430 glycerol-3-phosphate-transporting ATPase   activity
GO:0015609 | maltooligosaccharide-importing ATPase activity' | 0 |   | NA | NA | NA | TC:3.A.1 (general ABC transporter) | Merge into GO:0015422 ATPase-coupled oligosaccharide transmembrane   transporter activity

**Comment by pgaudet** [comment]
Create 2 subfamilies, ABC transporter and P-types: 

 - [x]  Merged GO:0015450 P-P-bond-hydrolysis-driven protein transmembrane transporter activity into GO:0015405 ATPase-coupled transmembrane transporter activity
