### ISSUE TITLE
GO:0044689 maps to deprecated EC

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17408]
Reported by @Artoria2e5 in https://github.com/geneontology/go-annotation/issues/2372

GO:0044689 currently maps to EC 2.5.1.77, a deprecated entry now split into EC 2.5.1.147 and EC 4.3.1.32, entries representing the two steps of reactions catalyzed by CofG and CofH subunits of the heterodimeric FO synthetase complex [PMID 25781338]. 

There does not seem to be examples of any of these subunits working in the absence of the other in vivo, so a new GO term is not urgently necessary. However, the lack of mappings for the new EC numbers is clearly breaking GO results for proteins annotated using these numbers (e.g. UniProt:P9WP76). It's probably a good idea to add these new EC mappings somehow.

* * *

There should probably be a hunt for all the deprecated EC numbers in the entire set of GO terms some day.

**Comment by Artoria2e5** [comment]
A quick tangential about the hunt: the best way to find those transfer events I have found so far is via the "hist" table of the [ExploreEnz](http://www.enzyme-database.org/) database. To find if an entry has been transferred:
* do a `SELECT * FROM hist WHERE ec_num="x.x.x.x" AND action="transferred"` to see if there is a record
* do a regex match on the "note" column to find the new ECs

**Comment by hdrabkin** [comment]
This is interesting in that the two EC numbers are under non-overlapping  EC function/mechanism classes (2.5 and 4.3); 
Right now the is_a parent is 'GO:0016765 transferase activity, transferring alkyl or aryl (other than methyl) groups' which is class 2.5.1

If I remove the Ec and add the two others, a second is_a parent is needed for the 4.3. (carbon-nitrogen lyase activity, GO:0016840 

However, I cannot add two different RHEA; 
EC 2.5.1.147  RHEA:55200
EC 4.3.1.32 RHEA:55204

**Comment by sjm41** [comment]
Looks like this got fixed in #25983. The two terms are shown below. Closing.

id: GO:0044689
name: 7,8-didemethyl-8-hydroxy-5-deazariboflavin synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: 5-amino-5-(4-hydroxybenzyl)-6-(D-ribitylimino)-5,6-dihydrouracil + S-adenosyl-L-methionine = 5'-deoxyadenosine + 7,8-didemethyl-8-hydroxy-5-deazariboflavin + H+ + L-methionine + NH4+." [PMID:14593448, RHEA:55204]
synonym: "FO synthase" EXACT []
xref: EC:4.3.1.32
xref: MetaCyc:RXN-19230
xref: RHEA:55204
is_a: GO:0016841 ! ammonia-lyase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25983" xsd:anyURI
created_by: jl
creation_date: 2012-08-15T14:33:17Z


id: GO:0141093
name: 5-amino-6-(D-ribitylamino)uracil--L-tyrosine 4-hydroxyphenyl transferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 5-amino-6-(D-ribitylamino)uracil + L-tyrosine + S-adenosyl-L-methionine = 2-iminoacetate + 5'-deoxyadenosine + 5-amino-5-(4-hydroxybenzyl)-6-(D-ribitylimino)-5,6-dihydrouracil + H+ + L-methionine." [PMID:11948155, PMID:23072415, PMID:25781338, RHEA:55200]
xref: EC:2.5.1.147
xref: MetaCyc:RXN-19229
xref: RHEA:55200
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25983" xsd:anyURI
created_by: pg
creation_date: 2023-09-07T11:46:06Z
