### ISSUE TITLE
NTR symbiont/pathogen effector activity (MF grouping term)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17437]
Moved from https://github.com/geneontology/go-annotation/issues/2376

The decision is to create this term, since it will be a useful grouping term to link together heterogeneous activities and there is a precedent for other activities (toxin, antioxidant, etc)

See
geneontology/go-ontology#17243 (comment)

~@CuzickA - I think you and Kim H_K worked on a definition for such a term a while back? Could you supply this as a starting point.~ see below

Also we need to identify existing pathogen effector functions to add as descendants.
We can make a list on Monday....

CC @mgiglio99 @pgaudet

**Comment by pgaudet** [comment]
We need a clear definition for this. 

Pascale

**Comment by ValWood** [comment]
A molecular function performed a factor derived from a pathogenic or non-pathogenic species that activates of suppresses host defenses or other host responses.

**Comment by ValWood** [comment]
We will provide a list of differnet effector functions that we know of for protein effectors, but note that not all effectors are protein coding. Some are secondary metabolites, cell wall  components (chitin and LPS)

**Comment by pgaudet** [comment]
Add bacterial effector protein as a synonym
see https://en.wikipedia.org/wiki/Bacterial_effector_protein

**Comment by ValWood** [comment]
this was @mgiglio99 's def from 
https://github.com/geneontology/go-ontology/issues/17243


"a symbiont protein, often from a pathogen, that enables the symbiont to invade host tissue, suppress or evade host immune systems, or otherwise help the symbiont to survive and replicate in the host."

**Comment by ValWood** [comment]
Would it be possible to call this term"pathogenic effector activity"
It is appropriate for pathogens or symbionts (because sometimes there is no interaction phenotype, i.e virulence). However, it is ALWAYS referred to as a "pathogen effector"

"pathogen effector Google About 38,000 results
"pathogenic effector" Google About 53,000 results
"symbiont effector" Google About 41 results

(It could be defined as a "symbiont effector" but we should use the language the community understands in the term names)

**Comment by ValWood** [comment]
further on I noted

Actually, I wonder if this definition is now too broad ...

"or otherwise survive and replicate in the host" could include lots of activities in addition to effectors...i.e any process which helps the pathogen to replicate in the host. For a fungi this could even cover the fungal replication machinery, of the biogenesis of the penetration machinery, but these are not effectors.

Is the effector always secreted by the pathogen? Or are there any other restricting criteria

@CuzickA ?

**Comment by ValWood** [comment]
Our collaborator Kim Hammond-Kosack @pgaudet KEHammond

has provided a useful review of fungal pathoggen effectors.

She will also provide a list of the  main fungal pathogen effector activities to kick-start the children.

Here are the first two:

activity | example  (Organism/gene | publication
ds-DNA binding | Colletotrichum graminicola EP1  |

**Comment by ValWood** [comment]
Our collaborator Kim Hammond-Kosack @pgaudet KEHammond

has provided a useful review of fungal pathogen effectors.
https://www.sciencedirect.com/science/article/pii/S1369526614000570

She will also provide a list of the  main fungal pathogen effector activities to kick-start the children.

Here are the first two:

MF |   role |Example  (Organism/gene) | Publication | URL
--- | ---|  --- | --- | ---
ds-DNA binding pathogen effector activity| prevents recognitions by plant and induction of defense mechanisms |  Colletotrichum graminicola EPI1  | PMID: 26554735 |https://apsjournals.apsnet.org/doi/10.1094/MPMI-09-15-0209-R
 chitin oligomer sequestering pathogen effector activity | unknown | Cladosporium fulvum ECP6 | PMID: 21467214 | http://www.plantphysiol.org/content/156/2/756.long


Notes
Not all effectors are protein coding, or RNA. Some are secondary metabolites, cell wall components (chitin and LPS)

**Comment by 123seher** [comment]
Eliminate abnormality and subjects

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ValWood** [comment]
Hi @pgaudet  we are waiting to do PHIbase phenotype curation on some papers characterizing effectors,  so it would be useful to have this term. Can it be added or is there any further discussion required?

**Comment by mgiglio99** [comment]
Sorry to be chiming in late. I think this is a fine term to have, no objection to making it. However, I am concerned about using "pathogen" in the name. Something being a pathogen or acting in a pathogenic way is extremely context dependent. Same strain in two individuals of the same host species may cause disease in one but not the other. That is why PAMGO decided not to make pathogen-specific terms in this way. Could we just make 'pathogen effector activity' a synonym?

Also a bit worried about some of the proposed child terms - but that can be for another day.

**Comment by pgaudet** [comment]
Hi @ValWood 

I am not clear about the children - and even the parent: the terms you propose would all fit under 'active evasion of host immune response' (GO:0042783)'; perhaps we should use 'pathogen activity' as a synonym for all the terms instead ? or use double parentage for some of them (see comments below): 

- 'double-stranded DNA binding pathogen effector activity': The paper states: "These residues may be important for DNA target specificity or they may play roles in avoiding detection by the plant immune system. "; is this really an effector activity ? 

- 'chitin oligomer sequestering pathogen effector activity'; the paper you cite mentions "Both proteins bind chitin; however, only Mg3LysM blocked the elicitation of chitin-induced plant defenses. In contrast to C. fulvum Ecp6, both Mg1LysM and Mg3LysM also protected fungal hyphae against plant-derived hydrolytic enzyme" 

-  'protease inhibitor pathogen effector activity' is the same as 'GO:0052054 negative regulation by symbiont of host peptidase activity'; isn't it ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Val, I suppose you mean: 

GONEW proposed def
The action by a plant or animal **symbiont** of establishing itself in a host by manipulation of host immune responses. GLOSS These processes are mediated by effectors secreted by the pathogen into the host.

?

**Comment by ValWood** [comment]
whoops yes, updated

**Comment by mgiglio99** [comment]
Just making sure I'm clear on the plan - there will be a new term for effectors, but it won't have children - is that right?
Comments on proposed name and def: For the name, could we just call it 'effector-mediated evasion or tolerance of host immune response'? I'm concerned about the word virulence, because again that implies pathogenesis/disease when that won't always be the case. 
For the def - I don't know what "GLOSS" means in this - but if the text after GLOSS is included then we need to say symbiont rather than pathogen.

**Comment by ValWood** [comment]
The term will be a process term not a MF term (it might eventually have children, but at present  for the examples  we have I think the  existing MF combined with GONEW
and the annotations to   GONEW should all be effectors (effectors generally perform a single step process  based on an interaction with a host protein or a pathogen PAMP, at least the ones I have come across).

Yes the primary term name should be
 GONEW effector-mediated evasion or tolerance of host immune response
(virulence -effector" can be another related synonym

Edited pthogen->symbiont above

**Comment by ValWood** [comment]
The first part of the definition is necessary and sufficient. The gloss is additional/helpful but isn't really required. In this case I think it is useful to provide the additional information about criteria for effectors.

**Comment by mgiglio99** [comment]
Ok, sounds good, thanks.

**Comment by ValWood** [comment]
I just spoke with @CuzickA  and these terms are OK.


One comment re the defintions

GO:0030682 evasion or tolerance of host defense response
Definition
Any process, either active or passive, by which an organism avoids or tolerates the effects of its host organism's defense response. The host defense response is mounted by the host in response to the presence of the organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

and
GONEW virulence effector-mediated evasion or tolerance of host immune response
GONEW proposed def
~The action  by which  a plant or animal symbiont ~of establishing~ establishes itself in a host by manipulation of host immune responses. GLOSS These processes are mediated by effectors secreted by the pathogen symbiont into the host.
related synonym “pathogen effector-mediated immune evasion”


Note that we  used  "by manipulation of host immune responses" in the def rather than 
"avoids or tolerates" . "Avoids" would be  always suppressing the host immune system, but sometimes in the case of necrotroph the effector" activates" the immune system

So  we need to either  
i) broaden the def of the parents, to include any immune system manipulation (not just tolerance or avoidance)
ii) Move the new term up to  be a child of a manipulation term
or
iii) Create a new term to cover necrotrophs  (it is rather hijacking the immune system, by killing cells )

We prefer i) or ii) so we can easily find the "effector" term in GO

**Comment by pgaudet** [comment]
Moved the actual things to do in a new ticket: 
https://github.com/geneontology/go-ontology/issues/17905

**Comment by pgaudet** [comment]
Wont fix - see new ticket.
