### ISSUE TITLE
MP: fix in pathogen host branch missing parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17442]
![tmep](https://user-images.githubusercontent.com/7359272/58831118-de2e0700-8643-11e9-86b9-7def8548b92b.jpg)

GO:0044055    modulation by symbiont of host system process

has these descendants

GO:0044061    modulation by symbiont of host excretion | is_a
-- | --
GO:0044064    modulation by symbiont of host respiratory system process | is_a
GO:0044063    modulation by symbiont of host neurological system process | is_a
GO:0044056    modulation by symbiont of host digestive system process | is_a
GO:0044059    modulation by symbiont of host endocrine process | is_a

but other 'system processes' (immune system for example) are in a different branch
(highlighted this above).

Do we need to distinghuish different level of process like this ? (makes terms difficult to find), or could they all be under host process

**Comment by pgaudet** [comment]
In the non-multispecies branch of GO, immune 


Children of GO:0003008 system process are:
*  GO:0003013 circulatory system process
*  GO:0022600 digestive system process
*  GO:0050886 endocrine process
*  GO:0007588 excretion
*  GO:0061007 hepaticobiliary system process
*  GO:0003012 muscle system process
*  GO:0050877 nervous system process
*   GO:0003014 renal system process
*  GO:0003016 respiratory system process 


I think the reason is that these are also children of 'GO:0032501 multicellular organismal process' , and  immune responses can occur in unicellular organisms. 

I think one solution would be to remove the grouping term 'GO:0044055 modulation by symbiont of host system process'. We could have logical definitions that link to the correct host processes, but at least in the symbiont branch the hierarchy would be simpler. 

Does that work ? 

(Note that there are no annotations to this term or any of the children: 
'modulation by symbiont of host cholinergic synaptic transmission'
'modulation by symbiont of host digestive system process'
'modulation by symbiont of host endocrine process'
'modulation by symbiont of host excretion'
'modulation by symbiont of host neurological system process'
'modulation by symbiont of host neurotransmitter secretion'
'modulation by symbiont of host respiratory system process'
'modulation by symbiont of host synaptic transmission'
'negative regulation by symbiont of host cholinergic synaptic transmission'
'negative regulation by symbiont of host neurotransmitter secretion'
'negative regulation by symbiont of host synaptic transmission')
Just FYI

Thanks, Pascale

**Comment by ValWood** [comment]
I'm not sure, I think we should revisit what we mean by "immune sytem process" in GO.
To me "immune system" is a system level term,it isn't clear to me from looking at the terms currently what constitutes an immune system.

There are many problem annotations also. I envisaged that  all pathogens using the"immune system" terms to annotate their effect on host immune responses would use terms below

induction/supression of host immune response by symbiont.  However thsi is not the case.

There are many fungal annotations (mainly CGD) to  "complement activation" and "regulation of immune response" etc.

It might be much better to separate what the symbiont does to the host immune system from the  host immune processes totally in GO? Maybe they could be connected by a "special relationship"

These are the terms used  (mainly by bacteria and fungi) after filtering metazoan and plant annotations.  There are only 208 non-IEA so it isn't so bad.

This is most of the culprit terms
![annotations](https://user-images.githubusercontent.com/7359272/59143676-3a3ab780-89c5-11e9-83bd-5a05ccd93d69.jpg)

Some of the terms, like "defense response to virus" may not be correctly placed under immune system, as it  does not stipulate that the defense response is part of the immune system. Yeast can have a "defense response to virus" but don't have an "immune system"

**Comment by ValWood** [comment]
we can look at some of these to demonstrate the issues. One  interim solution would be to apply some taxon restrctions.


![taxon restrictions](https://user-images.githubusercontent.com/7359272/59144227-7ae9ff00-89cc-11e9-84d7-2f3195db74fd.jpg)

**Comment by pgaudet** [comment]
I dont know what you mean. In this case Candida is the symbiont, isn't it ?

**Comment by ValWood** [comment]
These terms are misleading though.

GO:0052559    JSON
induction by symbiont of host immune response
Biological Process

Definition (GO:0052559 GONUTS page)
Any process in which an organism activates the immune response of the host organism; the immune response is any immune system process that functions in the calibrated response of an organism to a potential internal or invasive threat. The host is defined as the larger of the organisms involved in a symbiotic interaction.

annotating candid to this term is not correct. The candida does not  *intentionally* activate the hoist immune system., It attempts to evade it.  Activation of the immune system is a host process after detection of a  pathogen/.symbiont. .

Some fungi (necrotrophic) Do intentionally activate the hose immune system, but we should have a more precise term for this when required.


We need to clearly  separate what the symbiont does to the host immune system from the host immune processes.

Here the candida should be annotated to the processes of  invasion, or whatever the real processes are. 
There should be a cautionary comment for any term which would allow a symbiont to me annotated to induction of the host immune system that it is only used for intentional induction of the host immune system.

**Comment by ValWood** [comment]
Can probably close as redundant?

**Comment by addiehl** [comment]
Yes
