### ISSUE TITLE
Change label and definition GO:0051819 induction by symbiont of nodulation, tumor or growth in host

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17510]
- indicate that these are NOT nitrogen fixing nodules - they are formed by the symbiont to get the host to make cells in which the symbiont can grow 

- to complete

**Comment by pgaudet** [comment]
See previous changes here: https://github.com/geneontology/go-ontology/issues/8201

@mgiglio99 @jimhu-tamu

**Comment by pgaudet** [comment]
I have changed the term label to remove 'nodule', removed the ink to nodulation, and updated the definition as follows: "The process in which a symbiont causes the formation of a mass of cells in a host organism. While these growths are often called nodules, they are not formed as nitrogen-fixing structures, but rather to provide an environment for the symbiont to grow. In this sense they are parasitic structures rather than symbiotic."

@mgiglio99 @jimhu-tamu @ValWood let me know if you have changes to propose. 

Pascale

**Comment by mgiglio99** [comment]
Hi @pgaudet ,
I was looking over closed multispecies issues and noticed one thing about the definition above - the last word should be "mutualistic" rather than "symbiotic". Symbiotic relationships cover both harmful and beneficial interactions so that term shouldn't be used to indicate beneficial as it is here.

**Comment by pgaudet** [comment]
Fixed
