### ISSUE TITLE
OTR: 'GO:0000387 spliceosomal snRNP assembly' parent term 'GO:0000398 mRNA splicing, via spliceosome'

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#17538]
Hopefully quick question: is the relationship 'GO:0000387 spliceosomal snRNP assembly' _part_of_  'GO:0000398 mRNA splicing, via spliceosome' correct, especially keeping in mind https://github.com/geneontology/go-annotation/issues/2213 "Review annotations to 'protein-containing complex assembly' by IMP"?

I'm looking at a paper that shows a subunit of the U4/U6 snRNP complex is needed for assembly/stability via IMP, but I'm not entirely comfortable with 'assembly' as it's a known subunit (PRP3).

**Comment by krchristie** [comment]
> Hopefully quick question: is the relationship 'GO:0000387 spliceosomal snRNP assembly' part_of 'GO:0000398 mRNA splicing, via spliceosome' correct, 

I think this is correct because the cycle of splicing includes assembling the spliceosomal snRNPs, inserting them into "the" spliceosome, and disassembling the splicosome. This process ends up separating the U4 and U6 snRNPs, so for every cycle of splicing, you have to [re]assemble the U4/U6 snRNP.


> I'm looking at a paper that shows a subunit of the U4/U6 snRNP complex is needed for assembly/stability via IMP, but I'm not entirely comfortable with 'assembly' as it's a known subunit (PRP3).

It seems to me though that this question is unrelated to your first question. This question seems to be only an annotation question whether you want to a given gene product that is part of U4/U6 to assembly of that same complex. It does not seem to me that the answer to this annotation issue depends upon whether the relationship you asked about is correct.

**Comment by suzialeksander** [comment]
@krchristie thanks for the reply.  OK, sounds good, we weren't sure if the assembly term was rightfully a parent of splicing- the example I gave wasn't entirely related, just a case for the 'review annotations to assembly' ticket.

**Comment by krchristie** [comment]
@vanaukenk - I commented since these are terms I am pretty familiar with. I have unassigned you and assigned myself since @suzialeksander closed this on the basis of my comment. @ukemi - You can put this ticket in the rota for me.
