### ISSUE TITLE
obsolete term GO:0104005 used in taxon constraint

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#17548]
@ukemi could you check on what to do with this? I am enhancing the makefile to catch these, so they shouldn't be lurking in the future.

**Comment by ukemi** [comment]
@balhoff, part of the editors' standard procedure when obsoleting a term should be to check the taxon constraints and either remove them or change them as appropriate. Of course this gets a bit clunky since we will have to manually rebuild the taxon import before we can obsolete the term. We really need to streamline the import generation procedure in some way.

**Comment by ukemi** [comment]
It looks like this term was obsoleted with no replacement. It should just be removed from the constraints.

**Comment by ukemi** [comment]
Removed obsolete term and tested with ontobot.
