### ISSUE TITLE
cargo adaptor missing parent

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17553]
should be under 
"molecular adaptor activity" somewhere

**Comment by vanaukenk** [comment]
@ValWood 

It seems  'cargo adaptor activity' could be an is_a child or 'protein binding, bridging'.

On a related note, there are two existing child terms of 'protein binding, bridging', GO:0035656 and GO:0019895,  that have no annotations:

![image](https://user-images.githubusercontent.com/1730534/60440692-58ba5a00-9be3-11e9-9442-7ae4e1dd5a8f.png)

![image](https://user-images.githubusercontent.com/1730534/60440732-6c65c080-9be3-11e9-9e7c-02ca0433419d.png)

I propose that we add 'cargo adaptor activity' under 'protein binding, bridging' and obsolete the two kinesin-related terms above since they could be captured with the parent term and 'has input' for the molecules and organelles being bridged.  What do you think?

**Comment by ValWood** [comment]
I agree. I don't think the fact that these are "kinesin" is the important part functionally. If they connect microtubules to membranes (just guessing here)  they could use a cytoskeletal adaptor child...or something else based on function rather than family with has_input

**Comment by vanaukenk** [comment]
Actually looking at this now in Protege, 'cargo adaptor activity' has_part some 'molecular adaptor activity'.

@pgaudet - can you comment on why this is a 'has part' relation rather than 'is a' ?

**Comment by pgaudet** [comment]
@vanaukenk the idea was to have 'cargo adaptor activity' as a direct child of MF, but that was probably not necessary. I think you can change the relationship to 'is a'. 

Pascale
