### ISSUE TITLE
low-densitiy lipoprotein receptor complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#17554]
Term name: low-densitiy lipoprotein receptor complex
Def: A transmembrane protein complex that combines with a low-density lipoprotein particle or xenobiotic toxins and delivers them into the cell via endocytosis. While most substrates get degraded via the endosome the receptor is recycled to the plasma membrane. May also act as a transducer of intracellular signal pathways. Often acts in corporation with other cell-surface receptors.

Logical definitions:
GO:0098802 plasma membrane receptor complex
GO:0005887 integral component of plasma membrane
GO:0005041 low-density lipoprotein particle receptor activity
GO:0004888 transmembrane signaling receptor activity

Reference:
PMID:26005850

GOCID:bhm

I hope I didn't miss anything!

Note to self: CPX-4310 / EBI-21448232

**Comment by deustp01** [comment]
Fussy bit of terminology: "While most substrates get degraded ...". Would "ligand" be better here? (Enzymes act on substrates; receptors act on ligands?)

**Comment by bmeldal** [comment]
Yes, indeed, should be 'ligand'.
Thanks.

**Comment by ukemi** [comment]
Hi @bmeldal. I'm having a bit of a conundrum with respect to the 'or xenobiotic toxins' part of the definition because I'd like to relate this term to the GO:0005041 low-density lipoprotein particle receptor activity, which always has an input of an LDL particle. It would be nice if we could make this receptor specific for the LDL and perhaps make another receptor for the toxin function. So the logical def would be: protein-containing complex and capable_of some low-density lipoprotein particle receptor activity. 

Also a quick question for @RLovering. Right now the LDL receptor activity is a cargo receptor activity and is linked to endocytosis. I think this is ok, but there is no indication that the receptor is in the plasma membrane. Was this done on purpose because it gets internalized and would still be considered a receptor even after it leaves the plasma membrane? Also a question for @pgaudet.

**Comment by bmeldal** [comment]
Ok. All LDL receptors bind LDLs (by definition!) but some also bind toxins for degradation. It's the same receptor molecule. As we are trying to remove multiple "protein complex" children annotations from any given complex term we need to be careful here. We can't add "GO:0019534 toxin transmembrane transporter activity" (I guess that would be the activity unless we create a more specific toxin internalisation/clearance term) as logical definition (LD) to the generic LDLR term as not all LDLRs clear toxins. I could create new child terms for those LDLRs that do and then have specific LDs for them. I guess that would still fit our policy as the function of the generic LDLR term and its more specific children will be differently defined. 

I guess it's a good show case!

**Comment by bmeldal** [comment]
Locations:

It functions as a receptor in the plasma membrane, after that it's just passively transported though the endocytic pathway and recycled to the plasma membrane. However, it can also acts intracellularly in signalling pathways but those specific function are still being investigated...

**Comment by ukemi** [comment]
Since the same complex can serve more than one purpose, it limits the class relations I can make in the ontology. You are correct, this is a good showcase for an example of where despite the name, the complex can serve multiple functions. The instances of these functions will need to be captured in GO-CAM models. The same goes for a location. If the locations doesn't always hold, I can't make the class relationship in the ontology.

**Comment by bmeldal** [comment]
We could have LDLR as the grouping term with LDL activity and a child for LRP family complex with additional toxin clearance activity. It was suggested in the Cambridge meeting to make more granular terms where the function slightly changes.

It won't solve the location issue, except the main function we use for the LD is linked to its location in the PM.

The problem will occur when we discover its actual function in signalling! But that knowledge is still emerging so we'll cross that bridge when it comes to it.

**Comment by ukemi** [comment]
I just sent two edits to a pull request, but my build checks seem to be failing. I just made the simple term as a child of membrane protein complex and didn't relate it to any activity. I'm not sure what you mean by having the LDL activity as a grouping term with the activity. As soon as I relate it to the activity it will restrict it to always having that activity. I was tempted to make it a child of cargo receptor activity, but then I was concerned about its signaling function. We could make this one capable of cargo receptor activity and then make a new term 'low-density lipoprotein signaling receptor activity' at a later date. I can do that now in this pull request before I merge, since the checks are failing anyways. What do you think?

**Comment by bmeldal** [comment]
I would go for 

GO:0062136 low-density* lipoprotein receptor complex

Logical definitions:
is_a GO:0098802 plasma membrane receptor complex
capable_of GO:0005041 low-density lipoprotein particle receptor activity

* notice typo in my original request (densitiy)!

And, of course, I forgot the synonyms:
LDL receptor complex [EXACT]
LDLR complex [EXACT]

**Comment by ukemi** [comment]
OK. I will fix now including the cut and pasted typo. If I make this logical def, I should modify the def to be 'A transmembrane protein complex capable of low-density lipoprotein particle receptor activity, but may also bind xenobiotic toxins and deliver them into the cell via endocytosis. While most substrates get degraded via the endosome the receptor is recycled to the plasma membrane. May also act as a transducer of intracellular signal pathways. Often acts in corporation with other cell-surface receptors.'

I think this will be valid because regardless, it is always capable of the LDL receptor activity.

**Comment by bmeldal** [comment]
GO:0038024 cargo receptor activity is a parent of GO:0005041 low-density lipoprotein particle receptor activity

I think GO:0005041 low-density lipoprotein particle receptor activity is fine, we don't have to go less granular.

I think, even when the receptor is involved in signaling, it interacts with an LDL to activate it.

**Comment by bmeldal** [comment]
Sorry, we were writing simultaneously!

**Comment by ukemi** [comment]
OK. I'll push a new commit. We can always change it later if I ever get to merge it.

**Comment by bmeldal** [comment]
I just noticed that you linked it to 
intersection_of: GO:0098797 ! plasma membrane protein complex

instead of 
intersection_of: GO:0098802 ! plasma membrane **receptor** complex

Any reason?

**Comment by ukemi** [comment]
Hi @bmeldal. Yes, this was intentional . It is because the LDL receptor activity is a cargo receptor activity and plasma membrane receptor complexes are restricted to signaling receptors.

**Comment by deustp01** [comment]
Out of curiosity, is this an argument for a parental grouping term that is agnostic with respect to that restriction? Brown and Goldstein would be surprised to learn that they made a mistake in naming their discovery a receptor, and (more legitimate argument) it does make sense to think that all membrane-associated entities that bind soluble stuff and then do something in response can be classed as receptors, regardless of what that something is.

**Comment by ValWood** [comment]
To clarify and help curators 
GO:0098802 ! plasma membrane receptor complex
should be renamed to 
GO:0098802 ! plasma membrane signaling receptor complex

**Comment by pgaudet** [comment]
Makes sense to me.

**Comment by ukemi** [comment]
I don't think the naming was a mistake. I think cargo receptors are legit. I will rename as @valwood suggests.

**Comment by bmeldal** [comment]
I'm confused, but maybe it's the heat - we are not used to prolonged good weather ;-)

GO:0098802 plasma membrane receptor complex has no restriction to signalling in its def.
GO:0098797 plasma membrane protein complex is broader than "receptor complex" as it includes cell-cell and cell-ECM adhesion complexes..
Do we need need a new term for "plasma membrane **signaling** receptor complex"?

**Comment by bmeldal** [comment]
And a parallel a term for "plasma membrane **cargo** receptor complex"? LDLRs could be children of both.

**Comment by ukemi** [comment]
The logical definition of GO:0098802 plasma membrane receptor complex is: 'protein-containing complex' and ('part of' some 'plasma membrane') and ('capable of' some 'signaling receptor activity'), so it is restricted. So I renamed it as @ValWood suggested. Do you think we need the grouping term for the cargo receptor complexes? What would it buy us? Also, cargo receptors are not restricted to the plasma membrane: cargo receptor activity = Binding specifically to a substance (cargo) to deliver it to a transport vesicle. Cargo receptors span a membrane (either the plasma membrane or a vesicle membrane), binding simultaneously to cargo molecules and coat adaptors, to efficiently recruit soluble proteins to nascent vesicles.

**Comment by RLovering** [comment]
I like the idea of a cargo receptor complex grouping term and plasma membrane signaling receptor complex. However I still have some concerns about how to tell a signaling receptor from a cargo receptor. See https://www.ncbi.nlm.nih.gov/pubmed/9609114 for example, insulin signals through a receptor (IRK/INSR) and both are then internalised. This is important, as the insulin needs to be removed from the circulation. So IRK/INSR is both a signaling receptor and a cargo receptor. But not many papers will demonstrate that a signaling receptor (eg  GO:0005009 insulin-activated receptor activity or GO:0005899 insulin receptor complex) is also a cargo receptor, so having signaling and cargo receptor for these terms may lead to the term not being used because the curator may not see expt evidence for both. Or would you just annotate this as a signaling receptor? In which case the cargo receptor GO group will be under populated?

Thanks

Ruth

**Comment by ukemi** [comment]
@pgaudet, I believe this distinction was made as part of the MF refactoring. Can you shed any light on this discussion?

**Comment by pgaudet** [comment]
I think signaling receptors and cargo receptors need to be split in CC as they have been in MF. 
@RLovering we need to look at the downregulation of signaling more closely, I wonder if it really is a cargo receptor, in the sense that the cargo is brought in to be degraded. We probablydon't want to group that with cargo the cell is trying to move around or import. 

What do you think ? 

Thanks, Pascale

**Comment by ukemi** [comment]
Easy enough. I will add a general class of cargo receptor complexes. The children should self-classify (famous last words)

**Comment by RLovering** [comment]
it is difficult though to make the distinction, I don't think insulin is released back to circulation again, but I may be wrong

**Comment by ukemi** [comment]
This ticket will close once the generic cargo receptor complex is added. If there is still discussion about the distinction between cargo receptors and signaling receptors, perhaps we should open a ticket on the annotation tracker? It seems like the resolution will come down to the level of the annotations. If we decide that an ontology change is necessary, we should open a new ticket about what needs to be done.

**Comment by RLovering** [comment]
good idea

**Comment by ukemi** [comment]
Maybe the insulin receptor is both and should be co-annotated.

**Comment by RLovering** [comment]
I think that is the best way to go
