### ISSUE TITLE
NTR: Membrane lipid binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17581]
could we have a term 
NTR: membrane binding
—NTR: Membrane lipid binding
and position membrane lipids under here.

I’m annotating
phosphatidylinositol-4-phosphate binding
phosphatidylinositol-4,5-bisphosphate binding

as far as I know these are  always membrane lipids but this would need to be confirmed. However some phospholipids are found in free form so they can’t all go under membrane lipid binding without adding a membrane specific term.

It would be really useful to add this context.

**Comment by ValWood** [comment]
Hi, can this term be added?
I'd like to review our membrane adaptors this week or next week, if possible and I could do this  update at the same time

**Comment by hdrabkin** [comment]
Hi @ValWood 
Do you have a suggested parent?
Also PMID refs for your 2 terms?

**Comment by krchristie** [comment]
I'm wondering if this type of term for "membrane lipid binding" will get us into trouble, both because
- it requires confirmation that a specific lipid is ALWAYS in the membrane
- lipids that are always in the membrane either can only have a "membrane specific term" added under 'membrane lipid binding'. This kinds of specific sub terms tend not to get used by curators.

It seems to me that membrane lipid binding might be better represented as a GO-CAM.

**Comment by ValWood** [comment]
OK, I can do
phosphatidylinositol-4-phosphate binding occurs_at "plasma membrane"
