### ISSUE TITLE
NTR: matrilin complex

### ISSUE THREAD

**Issue by bmeldal** [geneontology/go-ontology#17598]
Term name: matrilin complex

Def: 
A cartilage extracellular matrix complex that mediates interactions between major components of the extracellular matrix such as collagens and proteoglycans and contributes to their fibrillar network. Exists as an obligate homotrimer. 

References:
PMID:9699631
PMID:10367731
PMID:15075323

Logical definitions:
is_a  GO:0032991 protein-containing complex
part_of GO:0062023 collagen-containing extracellular matrix
enables GO:0005201 extracellular matrix structural constituent
enables GO:0005509 calcium ion binding
involved_in GO:0030198 extracellular matrix organization

Synonyms:
matrilin family complex [RELATED]
matrilin-1 complex [NARROW]
matrilin-2 complex [NARROW]
matrilin-3 complex [NARROW]
matrilin-4 complex [NARROW]

GOCID:bhm

Note to self: EBI-21465188 / CPX-4423

**Comment by bmeldal** [comment]
Hi @krchristie 

I think the "relationships" should be intersections as they are logical defs. We agreed this year to use LDs rather than hard-coded relationships so we can work on automatically defining complexes. (We still need to change legacy relationships...)

**Comment by krchristie** [comment]
Hi @bmeldal - By logical definition, do you mean the "equivalence axiom", where all the relationships are put into one statement together, instead of individual "subclass" relationships? In your request, you labelled it with plural "definitions", so it looked like a list of relationships, so I just put them in the way I used to.

Also, when I tried to put these in yesterday, two of the relationships come up with errors:
` :: ERROR: Undeclared relation: RO:0002331`
`  :: ERROR: Undeclared relation: RO:0002327`

RO:0002331 = involved in
RO:0002327 = enables  

I seem to recall when I was putting in complexes for you last year, that we would use 'cabable of' rather than 'enables', but I don't know what to suggest for 'involved in'. @ukemi - Do you know what relationship is allowed in an equivalence axiom for what Birgit wants to say with 'involved in'?


Also regarding your note to self regarding IDs from other databases, we do normally put these into GO as DB xrefs, but we require the prefix to put them in correctly. I had to go back to old complex tickets I had done to find the correct prefixes. If you remember, it would be helpful to list the relevant IDs as DB xrefs with the appropriate prefixes and _without_ spaces, e.g. like these IDs I copy/pasted from other tickets: 
`IntAct:EBI-16411729`
`ComplexPortal:CPX-3462`

**Comment by ukemi** [comment]
capable_of for function, capable_of_part_of for process

**Comment by bmeldal** [comment]
Sorry, Karen, I misremembered the relationships after we decided to only add them as LDs. Thanks, David, for clarifying.

As for the refs to Complex Portal, we decided at/after the Cambridge meeting to no longer add them manually, they are now supposed to come in via a still-to-be-created mapping file from us (like the Reactome xrefs)! That way we always have a complete list. I'm still waiting for some magic developer time at my end ;-) I only added the comment for myself so I know where to add the terms once they are created as sometimes it's not as fast as you guys are this week!

We have done a lot of work to update and standardise complex annotation and term creation procedures while you were on leave but the documentations are still only in the GOC mtg minutes from Cambridge in April as, again, I have to find some magic time! I apologise for making your life harder than it should be :(

**Comment by krchristie** [comment]
OK, I won't put in the Intact or CP xrefs.

Another comment about making this an equivalence axiom. I can only do that if this combination of relationships is both "necessary and sufficient", which means that this is everything that is needed to define its role, as well as enough to completely distinguish it from all other complexes. So, if there are any other `protein-containing complexes that are calcium-binding structural constituents of the collagen-containing extracellular matrix involved_in extracellular matrix organization`, this definition might not be sufficient as a logical definition. If it's not sufficient, then it's probably better to leave it as individual relationships.

**Comment by bmeldal** [comment]
I know, but unfortunately I don't know how to run the test if the LDs are necessary and sufficient at my end so you need to tell me and we can take it from there ;-)

**Comment by krchristie** [comment]
I don't know how to test this either, but I'm a little wary of making this an equivalence axiom since it seems to me that it might not be sufficient. @ukemi - Do you have any thoughts on whether it is OK to put this in as an equivalence axiom, or if it's better to put in a set of subclass relationships for the relationships Birgit requested (copied from above and not edited to used correct relationships):

Logical definitions:
`is_a GO:0032991 protein-containing complex`
`part_of GO:0062023 collagen-containing extracellular matrix`
`enables GO:0005201 extracellular matrix structural constituent`
`enables GO:0005509 calcium ion binding`
`involved_in GO:0030198 extracellular matrix organization`

**Comment by ukemi** [comment]
Seems to me that there are complexes other than matrilin complexes that would satisfy these axioms, so this definition would not be sufficient. I don't know for sure without doing the legwork.

**Comment by krchristie** [comment]
@ukemi - That's my thought too, that this seems unlikely to be specific enough. 

@bmeldal - How about I put in the relationships you've indicated as SubClass relationships. Would that work for you?

**Comment by bmeldal** [comment]
Ok, this is another example then where we can't define a complex logically based in GO terms only. I guess that would be the case for many ECM complexes as they don't have distinguishable catalytic functions (they 'just bind stuff', they aren't enzymes, for the most part).

**Comment by krchristie** [comment]
OK, I put this term in with all the relationships you requested (with the modifications David indicated). I did not include the IntAct or CP dbxrefs. Let me know if I missed anything.
