### ISSUE TITLE
spermatogenesis should be a cell development or differentiation

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17637]
Currently oogenesis is a cell development, but spermatogenesis is not. Investigate why this might have been the case and add the appropriate parent if it should be added.

**Comment by ukemi** [comment]
Interestingly, this process includes all of the steps involved in generating sperm, which as parts include all of the cell types that give rise to the mature gamete. So the suggestion in the title of this ticket will not work. However, this should still be classified as a developmental process.

**Comment by ukemi** [comment]
https://github.com/obophenotype/cell-ontology/issues/574

**Comment by ukemi** [comment]
spermatogenesis- The developmental process by which male germ line stem cells self renew or give rise to successive cell types resulting in the development of a spermatocyte (mature sperm?).

Still needs a bit of work, but it's a start. @vanaukenk or @hattrill any suggestions? We want to include the C. elegans biology here as well as the germ-line cyst biology of the fly.

**Comment by ukemi** [comment]
https://github.com/obophenotype/cell-ontology/issues/575

**Comment by hattrill** [comment]
Hi David,
Yes for sure bring it under developmental process. Interesting that stem cell renewal included, but is consistent with structure and oogenesis.
So, for us, the "mature sperm" is the end point.
Mushing some decriptions together, particularly from PMID:24798812:
Germline stem cells divide asymmetrically to produce two cells: one cell maintains stem cell characteristics, while the other daughter cell (a gonialblast) initiates differentiation. Gonialblasts undergo 4 rounds of mitosis with incomplete cytokinesis to generate a cyst of 16 spermatogonia. Spermatogonia initiate terminal differentiation as spermatocytes, which undergo 2 meiotic divisions with incomplete cytokinesis to generate 64 haploid spermatids. Within the syncytial cyst, elongation and maturation of the spermatids, spermiogenesis, is the final stage of spermatogenesis, after which the sperm is transported to the seminal vesicle.

**Comment by vanaukenk** [comment]
@ukemi  - Yes, as we discussed, 'spermatogenesis' should definitely be a developmental process.

The new definition above should work for C. elegans, but do we want spermatogenesis to end in formation of mature spermatozoa (mature sperm) rather than spermatocytes?

Here's a nice summary statement from a recent C. elegans paper:

"Spermatogenesis is a conserved multistep process that involves mitotic proliferation of spermatogonia, meiotic division of spermatocytes, and differentiation of haploid spermatids into
mature spermatozoa."

https://www.ncbi.nlm.nih.gov/pubmed/30990821

Interestingly, we have terms for 'spermatid development' and 'spermatid differentiation' but not 'spermatozoa development' or 'spermatozoa differentiation'.    

I should review the C. elegans annotations to the spermatid terms to make sure they're still okay.

Note: also updating the definition of 'pseudocleavage' since it happens in spermatids as well as embryonic cells.

**Comment by hattrill** [comment]
This paper defines spermatogenesis as ending with the mature spermatozoa as well:
https://www.ncbi.nlm.nih.gov/pubmed/28073824

**Comment by ukemi** [comment]
It should certainly end with the mature sperm. My mistake above.
