### ISSUE TITLE
external2go updates

### ISSUE THREAD

**Issue by SamuelBrinker** [geneontology/go-ontology#17630]
Hi,
Just want to ask about how current the kegg2go and other external2go files on the official site are. I know there is a time stamp at the top of the file, but there is only 1 GO term logged for the kegg2go file, which doesn't feel right. Any place I can find the most up to date info?

**Comment by SamuelBrinker** [comment]
I would also love to know / be pointed in the direction of how you generate your kegg2go files

**Comment by ValWood** [comment]
Did anyone reply?

**Comment by SamuelBrinker** [comment]
They did not. It's been a while since I worked with the system either, so I'm a bit fuzzy on what I did

**Comment by ValWood** [comment]
The information about mappings is here
http://geneontology.org/docs/download-mappings/
These files are created manually by GO editors.

I suspect there was a glitch with the file KEGG  when you accessed because the  KEGG mapping looks better:
http://current.geneontology.org/ontology/external2go/kegg_reaction2go

Apologies for the delay -this probably isn't useful to you now.
