### ISSUE TITLE
peptidoglycan recognition protein signaling pathway 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#17636]
GO:0061057 | peptidoglycan recognition protein signaling pathway is defined as a cell surface receptor signaling pathway, but it can also be mediated by an intracellular receptor (PMID:24706930). 

In terms of the definition, I think that just removing  "on the surface of the target cell", should be sufficient:
"A series of molecular signals initiated by binding of peptidoglycan to a receptor **on the surface of the target cell** and ending with regulation of a downstream cellular process. The main outcome of the Imd signaling is the production of antimicrobial peptides. 

The position in GO should be changed from:

from is_a GO:0007166 | cell surface receptor signaling pathway
to
is_a GO:0007165 | signal transduction (although that seems a bit weak - any chance of introducing a 'receptor signaling pathway'... makes the edit more complex, as other children of 'signal transduction' would have to be folded under it, but for me, defining this pathway as two branches: one IC and one TM-receptor mediated is unnecessary as all the other downstream components are inplace for both).

**Comment by krchristie** [comment]
Hi @hattrill - I think I'd rather not introduce the term 'receptor signaling pathway'. As you point out, it makes the edit more complex. Looking at the terms currently under 'signal transduction', we already have terms like 'G protein-coupled receptor signaling pathway' where the definition states "The pathway can start from the plasma membrane, Golgi or nuclear membrane". I don't want to have to go through the children of 'signal transduction' in order to figure out which ones should be moved to be under a new term for 'receptor signaling pathway'.

**Comment by hattrill** [comment]
Thanks, Karen.....sounds very reasonable. I thought that 'receptor signaling pathway' was pushing my luck :-)
