### ISSUE TITLE
Proposal to obsolete GO:0035656 kinesin-associated melanosomal adaptor activity AND GO:0019895 kinesin-associated mitochondrial adaptor activity

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#17668]
Dear all,

The proposal has been made to obsolete the following terms:
	•	GO:0035656 kinesin-associated melanosomal adaptor activity = 0 annotations
	•	GO:0019895 kinesin-associated mitochondrial adaptor activity = 0 annotations

The reason for obsoletion is that the functions represented by these terms can be assigned by annotating to the parent term, ‘protein binding, bridging’ (GO:0030674) and capturing the proteins bridged with annotation extensions that use the ‘has input’ relation and identifiers for the bridged proteins.

There are no mappings to these terms. 

The terms are not present in any subset (slim).

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete these terms on August 5th, 2019. Unless objections are received by August 5th, 2019. we will assume that you agree to this change.

Thanks, 
--Kimberly

**Comment by ValWood** [comment]
Hi @vanaukenk ,

I would recommend cytoskeletal adaptor activity
https://www.ebi.ac.uk/QuickGO/term/GO:0008093
here since the bridging is from cytoskeleton to  organelle protein.

I hope we are keeping these  broad classes of specific adaptors? I find them useful because there are 100s of them (and increasing numbers I think we will end up with about 20% pombe proteins annotated to protein binding  bridging term eventually, there are just so many molecular connectors!). This is more informative about the physiological context than protein binding, bridging.

**Comment by vanaukenk** [comment]
@ValWood 

'cytoskeletal adaptor activity' might also work, but I think we then need to clarify the definition of that term to state exactly what gene products are considered 'a cytoskeletal protein':

"The binding activity of a molecule that brings together a cytoskeletal protein and one or more other molecules, permitting them to function in a coordinated way. "

For example, are MT motors cytoskeletal proteins or do they also function as adaptors?

**Comment by ValWood** [comment]
Good point.

I puzzled  over what exactly an adaptor was, and  I think the adaptor can work through a actin or Microtubule-associated protein.  In fact, I believe the cytoskeleton community would refer to actin or microtubule-associated proteins as "cytoskeleton proteins" (and I think this fits with how we use the terms actin or microutubule cytoskeleton in GO?). 

In all cases I have come across the adaptor connects to a microtubule or actin-associated protein and not to the actin filament or microtubule directly.  In some cases, multiple proteins are involved- as in the anchoring of cytoplasmic dynein during horsetail movement https://www.pombase.org/reference/PMID:25736293

For cytokinetic ring anchoring the situation is REALLY complicated, and many of the proximal and intermediate layer proteins function as cytoskeletal adaptors.
![cytokinesis](https://user-images.githubusercontent.com/7359272/62136839-d3f35680-b2dc-11e9-9812-cabaddbf28be.jpg)

**Comment by ValWood** [comment]
GO:0015630    microtubule cytoskeleton
Definition 
The part of the cytoskeleton (the internal framework of a cell) composed of microtubules and associated proteins.

GO:0015629   actin cytoskeleton
Definition (GO:0015629 GONUTS page)
The part of the cytoskeleton (the internal framework of a cell) composed of actin and associated proteins. Includes actin

**Comment by vanaukenk** [comment]
@ValWood 

Yes, I think if we can articulate what an 'associated protein' is that would help clarify what gene products then function as cytoskeletal adaptors.

Using 'microtubule cytoskeleton' as an example, and comparing some of the PANTHER families annotated directly to it with the figure above, these are categories of activities I think could be cited as examples of 'associated proteins':

1. Motors
2. Microtubule-associated proteins
3. Cross-linkers
4. Other ATPases (e.g. severing activities)

Activities TBD:

1. Signal transduction or post-translational modification activities, e.g. kinases, phosphatases, acetylases

Activities NOT to include:
1. Cargo molecules that are transported along the cytoskeleton  - not active there, just on their way to where they ARE active

For the MF 'cytoskeletal adaptor activity' definition, perhaps we could refine as follows:

"The binding activity of a molecule that brings together a cytoskeletal protein (either a microtubule or actin filament, or protein directly bound to them) and one or more other molecules, permitting them to function in a coordinated way. "

That leaves open the possibility of an adaptor directly interacting with tubulin or actin, if that was ever found to be the case.

**Comment by ValWood** [comment]
I think the proposed def sounds good.

For cytoskeleton associated proteins  good to mention that cargo are excluded.


However, it seems that although dynein and the motos *used* to be defined as MAPs, they aren't any longer. Which puts us back where we started :(

https://en.wikipedia.org/wiki/Microtubule-associated_protein

"There are many other proteins which affect microtubule behavior, such as catastrophin, which destabilizes microtubules, katanin, which severs them, and a number of motor proteins that transport vesicles along them. Certain motor proteins were originally designated as MAPs before it was found that they utilized ATP hydrolysis to transport cargo. In general, all these proteins are not considered "MAPs" because they do not bind directly to tubulin monomers, a defining characteristic of MAPs.[13] MAPs bind directly to microtubules to stabilize or destabilize them and link them to various cellular components including other microtubules."

(I thought they did bind directly to microtubules!?!)

**Comment by pgaudet** [comment]
Edited definitions, and added hyphens in the term labels to make them more clear: 

 id: GO:0140362
-name: cytoskeletal protein membrane adaptor activity
+name: cytoskeletal protein-membrane adaptor activity
 namespace: molecular_function
-def: "Interacting selectively and non-covalently with both a cytoskeletal protein or protein complex and a membrane, in order to maintain the localization of the protein at a specific membrane location." [PMID:30840879]
+def: "The binding activity of a protein that brings together a cytoskeletal protein (either a microtubule or actin filament, or protein directly bound to them) and a membrane, permitting them to function in a coordinated way." [PMID:30840879]

----

 id: GO:0008093
 name: cytoskeletal adaptor activity
 namespace: molecular_function
-def: "The binding activity of a molecule that brings together a cytoskeletal protein and one or more other molecules, permitting them to function in a coordinated way." [GOC:mtg_MIT_16mar07]
+def: "The binding activity of a protein that brings together a cytoskeletal protein (either a microtubule or actin filament, or protein directly bound to them) and one or more other molecules, permitting them to function in a coordinated way." [GOC:mtg_MIT_16mar07]

Thanks, Pascale
