### ISSUE TITLE
transmembrane transport part

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17663]
2017-05-01 | Added | RELATION | has part GO:0006914 (autophagy)

seems to be the wrong way around. Transmembrane transport doesn't have autophagy as a part?

**Comment by pgaudet** [comment]
Seems like this was done during the autophagy work --- @ukemi ?

**Comment by pgaudet** [comment]
@ukemi 
Autophagy has as a subclass: 
'ends with' some 'transmembrane transport' - which makes transmembrane transport part_of autophagy. I am removing this link, I hope it's OK. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@marcfeuermann tells me that transports (more specifically, export of protein fragments from the lysosome to the cytoplasm) is part of autophagy - the last step. 

So: 
1. It would be nice to have the more precise term, rather than just TM transport (term doesn't exist yet)
2. I dont understand why having 'A ends with B' generates another inference 'B has part A'? I suppose there is some logic, but in this case B needs to be a step specific for A, not as general as TM transport. 

@ukemi should we discuss at an ontology call ? 

Thanks, Pascale

**Comment by cmungall** [comment]
Summary of call: the ontology is fine, inverseOf in OWL only means instance level of inverseOf. The axioms in the asserted ontology are correct. 

We believe QuickGO may be doing something wrong here but we are double checking it is not something we introduce in the release process

**Comment by pgaudet** [comment]
Hi @alexsign 

This seems to be an issue with the QuickGO display: 
In the change log for GO:0055085, it looks like a relation  'has part GO:0006914 (autophagy)' was added on 2017-05-01 


![image](https://user-images.githubusercontent.com/4782928/64981334-da885e00-d889-11e9-949e-ea03347ab75f.png)

however what is in the ontology is autophagy ends with transmembrane transport. 

The go-plus.owl is OK, so presumably the json is also fine. 

Can you please check how this entry of the change log was generated ? 

Thanks, Pascale

**Comment by alexsign** [comment]
@pgaudet The QiuckGO data is based on Gene Ontology data. This part is from go-plus.json file, which firs time added in 2017-05-01. Still there:
{
      "sub" : "http://purl.obolibrary.org/obo/GO_0006914",
      "pred" : "http://purl.obolibrary.org/obo/RO_0002230",
      "obj" : "http://purl.obolibrary.org/obo/GO_0055085"
    }

**Comment by pgaudet** [comment]
Well, this is fine, 'autophagy' ends with transmembrane transport. 

However 'transmembrane transport' does not 'have part' autophagy. 

Thanks, Pascale

**Comment by alexsign** [comment]
@pgaudet  I'm going to review this with @ggeorghiou tomorrow to make sure there is no reverse logging or conversion happening on our side.

**Comment by cmungall** [comment]
What was the outcome of this?

**Comment by pgaudet** [comment]
@alexsign Can you please let us know if this is coming from GO ?

**Comment by cmungall** [comment]
@alexsign you said:

> The QiuckGO data is based on Gene Ontology data. This part is from go-plus.json file, which first time added in 2017-05-01. Still there:
> {
> "sub" : "http://purl.obolibrary.org/obo/GO_0006914", # autophagy
> "pred" : "http://purl.obolibrary.org/obo/RO_0002230",   # ends with 
> "obj" : "http://purl.obolibrary.org/obo/GO_0055085" # transmembrane transport
> }

This was and remains correct. There is nothing wrong with this.

This ticket is about the has-part in the change log here:
https://www.ebi.ac.uk/QuickGO/term/GO:0055085

in the change log it says:

![image](https://user-images.githubusercontent.com/50745/65898702-036b2180-e367-11e9-94d6-30b2e1d11909.png)

(see Val's original comment)

this is incorrect, this has-part relationship is not stated by the GO. One hypothesis is that QuickGO is making an incorrect inference:

`X ends-with some Y ==> Y has-part some X`

I am not sure if this is the case, if so it is wrong. Either way this is a QuickGO bug because the has-part relationship is not stated in GO.

Is there a QuickGO tracker we can transfer this ticket to? If so we can transfer. Otherwise we can keep here to preserve discussion. I assigned you as co-owner of the ticket.

**Comment by alexsign** [comment]
@cmungall yes, you are correct. It is a wrong assumption in QuickGO because we are trying to use parent relationship for it. This however tricky to fix, and we have to discuss possible removal of this or representing it the same way as in AmiGO.

**Comment by pgaudet** [comment]
This is a QuickGO issue - @alexsign Is there a QuickGO tracker where that can be moved?

**Comment by alexsign** [comment]
not really this  is your best bet https://www.ebi.ac.uk/QuickGO/feedback

**Comment by pgaudet** [comment]
Done. I'll close this ticket here as this is not something GO can fix.
