### ISSUE TITLE
flippase parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17672]
At present we do not have flippases represented as transmembrane transporters:

![flippase](https://user-images.githubusercontent.com/7359272/62218362-35cac380-b3a4-11e9-819c-6d75dca84b57.jpg)

and
https://www.ebi.ac.uk/QuickGO/term/GO:0090554

but, it seems that flippase and floppase  is a type of "transmembrane transport":

https://en.wikipedia.org/wiki/Flippase

Flippases (rarely spelled flipases) are transmembrane lipid transporter proteins located in the membrane which belong to ABC transporter family.

the definition of transmembrane transport does not actually exclude this, but the activity/process  it isn't represented as "transmembrane transporter/transport" in the ontology....

So 
transmembrane transport would include
crossing the bilayer AND moving from one side of the bilayer to the other.

**Comment by pgaudet** [comment]
Sorry about the long delay in my response - 

I think wikipedia states that the flippases are transmembrane proteins, not that they do transmembrane transport ? "Flippases (rarely spelled flipases) are transmembrane lipid transporter proteins" 

If we make these children of transmembrane transport, we'll need to change the definition of transmembrane transport, which mentions "the transport of a solute **across** a lipid bilayer". 

Also tagging @marcfeuermann since we're discussed this together at great length.

Thanks, 

Pascale

**Comment by ValWood** [comment]
I see what you mean, it's a bit ambiguous. But yes it could mean  "transmembrane"  (lipid transporters).

However, then the sentence would be redundently constructed because it would repeat the membrane location.

We need an expert!

**Comment by pgaudet** [comment]
> We need an expert! 


Yes

**Comment by pgaudet** [comment]
@ValWood is this OK for now ? Can we close ? Or do you know of a transport expert who can help ? I do feel like this will end up being somewhat subjective. As long as GO is clear on what we mean by 'transmembrane', we should be ok, right ? 

Thanks, Pascale

**Comment by ValWood** [comment]
https://www.ebi.ac.uk/QuickGO/term/GO:0140327
all fixed by another ticket
