### ISSUE TITLE
add DDANAT links to sorocarp spore / stalk cell differentiation terms

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#17670]
GO:0031149  sorocarp stalk cell differentiation 
and it's children
link to:  DDANAT:0000413 stalk cell

GO:0044671  sorocarp spore cell differentiation
And children
link to: DDANAT:0000414 spore

Thanks!

**Comment by vanaukenk** [comment]
@pfey03 

I think the correct way to make these links would be through the equivalence axioms.

Would the dicty anatomy term used in these equivalence axioms (following the standard pattern for differentiation) be correct for the terms above?

GO:0031149 sorocarp stalk cell differentiation
'cell differentiation' and 'results in acquisition of features of' some 'stalk cell'

GO:0044671 sorocarp spore cell differentiation
'cell differentiation' and 'results in acquisition of features of' some 'spore'

If not, is there another dicty anatomy term that we should use?

Thx.

**Comment by vanaukenk** [comment]
A related issue has come up wrt importing the dicty anatomy ontology.  
There are dicty anatomy files in the imports directory, but it looks like they aren't being imported.
This seems to result in equivalence axioms that cite the ID and not the label for DDANAT terms.
Tagging @cmungall to see if there's a reason we aren't importing the dicty anatomy ontology.
Also adding editors discussion tag to follow up on 2019-08-12 editors call.

**Comment by pfey03** [comment]
@vanaukenk Yes, I think that would be the correct way to use. I know the 'some' is part of the axiom and it's fine.

Since DDANAT is strictly for D. discoideum the terms are simple but further defined by their ontology. We won't need 'sorocarp spore cell' as there is no other spore in any Dictyostelid than the spores in the sorocarp, for example.

Greetings from the Dicty meeting!

Thanks,
Petra

**Comment by vanaukenk** [comment]
Thank you @pfey03 !

We'll sort out the issues with the dicty anatomy import and then I can create the equivalence axioms.

**Comment by pfey03** [comment]
Many thanks @vanaukenk

**Comment by vanaukenk** [comment]
@balhoff 
I'm not sure what steps to take here to update the dicty anatomy file and make sure that it is included in the external ontologies for use in editing.

I need to update the ddanat_terms.txt file with the PURLs of the terms we need for this ticket (as well as converting the existing term to a PURL), but then what needs to happen to include the ddanat OWL file so that we can use it in Protege?

There is an old pull request here from @cmungall that looks to address this, at least in part, but it never got merged:
https://github.com/geneontology/go-ontology/pull/13094 

The pull request was in response to this ticket:
https://github.com/geneontology/go-ontology/issues/13073

Thx.

**Comment by balhoff** [comment]
@vanaukenk I will set up the import.

**Comment by balhoff** [comment]
@vanaukenk you can add to ddanat_terms.txt now.
