### ISSUE TITLE
obsolete or merge GO:0061487

### ISSUE THREAD

**Issue by mah11** [geneontology/go-ontology#17680]
This should have been done as part of #12533, but seems to have been overlooked:

DNA replication initiation from late origin ! GO:0061487 should either be made obsolete or merged into its superclass, GO:0006270. I have no preference which is done, but there are no biological grounds for GO:0061487 to be retained as a separate term. 

Rationale, from the older ticket: 

> ... initiation is initiation is initiation. The mechanism and involved gene products are the same at early origins and at late origins, so there is no differentium to distinguish "initiation at late origin" from "initiation".

**Comment by krchristie** [comment]
**Relevant terms:**
GO:0061487 - DNA replication initiation from late origin
GO:0006270 - DNA replication initiation

Reading all the way through the ticket you cite, #12533, it appears to me that although obsoleting **GO:0061487 - DNA replication initiation from late origin** was proposed, that it was decided that it needed to be kept in order to provide a basis for the logical definition for the regulation term that was definitely wanted. The solution agreed upon for the GO:0061487 term was this:

> TODO: redefine GO:0061487, DNA replication initiation from late origin, logically adding a restriction 'has participant some late origin'.

and it has been done.

Since the other ticket makes it clear that not merging/obsoleting GO:0061487 into GO:0006270 was a choice rather than an oversight, I'm going to close this ticket.

**Comment by mah11** [comment]
If it wasn't an oversight, then it was an error of commission.

There simply is no DNA replication initiation process that differs between early and late origins; 
_only_ the regulation differs.

**Comment by krchristie** [comment]
I read through the previous ticket carefully and it seemed to me that the solution that was implemented worked in that it is saying that the ONLY difference between DNA replication and DNA replication at a late origin is the fact that it occurs on a late origin, but NOT that what occurs there is different. 

In another ticket that I am working on, I have already been discussing the fact that SOP discourages regulation terms that do not have a regular term to base a logical definition on. I will bring this up at the editors meeting next week.

**Comment by mah11** [comment]
> ...  it is saying that the ONLY difference between DNA replication and DNA replication at a late origin is the fact that it occurs on a late origin, but NOT that what occurs there is different

This seems inconsistent with recent decisions (or at least recently expressed opinions) pertaining to other branches in BP. For example, in #16695 a request for "protein localization to prospore septin ring" was queried (and subsequently withdrawn) on the grounds that only the destination differentiated it from any other protein localization process - despite precedent in the form of "protein localization to X" terms for many other values of X.

I'm actually less bothered by the existence of a surplus-to-requirements initiation term than by the broader inconsistency - keep both or purge both, but don't make different calls in different parts of the ontology.

**Comment by pgaudet** [comment]
In this case though the term is needed to make a logical definition for the regulation term, which is a little different from what you describe @mah11 . 

However - 'regulation of mitotic DNA replication initiation from late origin' is not even using 'DNA replication initiation from late origin ' in its logical def - (doesn't have a LD!) 

Suggestion for a LD: 
'regulation of mitotic DNA replication initiation from late origin'
= 
'biological regulation' 
and regulates some 'DNA replication initiation'
 and 'has participant' some late_origin_of_replication

This is similar to the current LD of 'DNA replication initiation from late origin', just adding 'biological regulation', and would allow the merge. 

@krchristie Do you think that would work ? 

Thanks, Pascale

**Comment by mah11** [comment]
But there is no difference in how GO terms correspond to biology. The logical definition angle is  artificial, imposed not by something observed about a living system, but by limitations in how we model it.

That said, I think your suggestion will probably work. The regulation term in question should never have been parsed as "regulation of (mitotic DNA replication initiation at late origin)"; it's actually "(regulation of mitotic DNA replication initiation) at late origin".

**Comment by krchristie** [comment]
I'm fine with the suggestion @pgaudet made, so let's go with that.

**Comment by krchristie** [comment]
Since the whole point of this ticket is that this term should not exist, I am going to propose to obsolete it, rather than to merge it and then end up with this term name string as some sort of synonym.

**Comment by mah11** [comment]
That all sounds fine. Thanks!

**Comment by krchristie** [comment]
In doing this, I noticed a couple things that weren't discussed previously. They seemed straightforward so I've just done them and put comments here listing the additional things I've done.

1. The regulation terms, both the vanilla and negative regulation terms, included the word 'mitotic', so I have used the term '**mitotic** DNA replication initiation', rather than just 'DNA replication initiation' in the logical defs, e.g.

regulation of mitotic DNA replication initiation from late origin

> 'biological regulation'
and regulates some '**mitotic** DNA replication initiation'
and 'has participant' some late_origin_of_replication'


2. synonyms

The term  `"DNA replication initiation from late origin" (GO:0061487)` had this synonym:
`synonym: "late replication origin firing" EXACT [GOC:dph, PMID:19221029]`

I've used this string in synonyms for both the vanilla and negative regulation terms, with the corresponding regulation type added to the synonym.
