### ISSUE TITLE
Add "epsilon DNA polymerase complex" as part of "nuclear replisome"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#17723]
I realise this has been discussed before:
https://github.com/geneontology/go-ontology/issues/14691
and the decision was to remove this 'part of' relationship:
id: GO:0008622
name: epsilon DNA polymerase complex
relationship: part_of GO:0043601 ! nuclear replisome

But every recent review/paper I've read asserts that DNApol epsilon _is_ part of the replisome, for example:
Jain et al 2018 (PMID: 30005324)
Yeeles et al 2017 (PMID: 27989442)
Burgers & Kunkel  2017 (PMID: 28301743)
Bai et al 2017 (PMID: 29357060)
Yurieva and O'Donnell 2016 (PMID: 27416113)

It was noted in #14691 that the Burgers & Kunkel review says "Collectively, these results strongly suggest that in undamaged yeast cells, the leading strand is **primarily** replicated by Pol ε".  I think just reflects that there's evidence that both POL delta and epsilon can act as the leading strand polymerase, and that the cell may switch between the two depending on circumstances.  I don't believe there's any debate that POL epsilon is part of the so-called "replisome" - but we could always write to couple of experts if we need to check.

@mah11 
@krchristie 
@hattrill

**Comment by mah11** [comment]
The linked ticket acknowledges that eukaryotic replisomes usually contain Pol ε, but also notes that Pol ε can be found elsewhere. That was, and remains, the reason why we can't add back GO:0008622 part_of GO:0043601.

The comment thread also revealed what appeared at the time to be the possibility that eukaryotic replisomes lacking Pol ε could exist. If that possibility can be reliably excluded, then the link replisome GO:0043601 _has_part_ Pol ε GO:0008622 could be added. I'm happy to take expert input on this point.

**Comment by krchristie** [comment]
@sjm41 - @mah11 has said pretty much what I would have said. Do you have any info that there are replisomes that lack Pol ε? If it is true that ALL replisomes contain Pol ε, then as @mah11 said, we could add a has_part relationship to say that 

nuclear replisome (GO:0043601 ! )
has_part: epsilon DNA polymerase complex (GO:0008622)

If you have found evidence to support this statement, please provide the PMID of the reference. Otherwise, I really don't think there is anything we can do because we can only add either a has_part or a part_of relationship to the ontology if either statement is **ALWAYS** true.

**Comment by sjm41** [comment]
Thanks both.

I provided 5 recent PMIDs in my original post that assert that Pol ε is a canonical member of the 'replisome'.  (A researcher using 'nuclear replisome' as as search term would certainly expect to find annotations to Pol ε, IMO.)  So I still think adding the has_part of relationship is the right thing to do.

It would be very hard to find evidence that Pol ε is **ALWAYS** part of the replisome, no exceptions.  But if there was clear evidence that functional replisomes lacking Pol ε exist, then I guess that would settle the issue.  Do we know of any PMIDs clearing stating that point?

**Comment by ValWood** [comment]
Stephen has a good point that researchers would expect to find pol E under "replisome"
but has_part won't help either, because annotations are not transitive over has_part.

This is a general issue.

So at pombase we have 95 gene products annotated to nuclear replication and I think *most*  of these would be considered "replisome" - but only 18 annotated to "replisome"

Are there any plans to address inconsistencies of this type through inference?

@pgaudet 
@cmungall

**Comment by ValWood** [comment]
Nuclear replisome currently has the children

Child Term | Relationship to GO:0043601
-- | --
GO:0005662    DNA replication factor A complex | part_of
GO:0043599    nuclear DNA replication factor C complex | part_of
GO:0005658    alpha DNA polymerase:primase complex | part_of
GO:0043625    delta DNA polymerase complex | part_of

Is the same not true of these?

**Comment by ValWood** [comment]
The same problem will exist for all multi-component terms?

Also since polE is essential  for replication mustn't it always be a component of the replisome?

**Comment by mah11** [comment]
> Nuclear replisome currently has the children
> 
> > GO:0005662    DNA replication factor A complex 	part_of
> > GO:0043599    nuclear DNA replication factor C complex 	part_of
> > GO:0005658    alpha DNA polymerase:primase complex 	part_of
> > GO:0043625    delta DNA polymerase complex 	part_of
> 
> Is the same not true of these?

None of those complexes have been observed in a DNA repair complex instead of a replisome, whereas Pol ε has. At least, that's what the current ontology structure implies. If any of the other complexes do turn up in a repair complex or any other non-replisome context, then its 'part_of replisome' link would have to be removed.

> Also since polE is essential for replication mustn't it always be a component of the replisome?

This question is ambiguous regarding which direction "always" applies.

The question under consideration in earlier comments (https://github.com/geneontology/go-ontology/issues/17723#issuecomment-522782703, https://github.com/geneontology/go-ontology/issues/17723#issuecomment-522888422) is whether any normal replisomes exist without Pol ε. If not, then the replisome always contains Pol ε, and the has_part link can be added.

As for Pol ε existing outside a replisome, see above re DNA repair.

**Comment by ValWood** [comment]
> None of those complexes have been observed in a DNA repair complex instead of a replisome, whereas Pol ε has.

OK I missed this part!

Anyway if this is essential for replication the has_part can be added. However ,this won't help us to get this complex included in the replisome annotation set.

**Comment by krchristie** [comment]
> Anyway if this is essential for replication the has_part can be added. However ,this won't help us to get this complex included in the replisome annotation set.

The criterion for adding has_part is whether or not a replisome ALWAYS contains Pol ε, not whether Pol ε is essential for replication.

**Comment by pgaudet** [comment]
Sounds like Pol ε always is always part of the replisome - ie being a canonical part should be sufficient? 

I usually ask @bmeldal about this kind of issue. 

Pascale

**Comment by bmeldal** [comment]
Thank for the vote of confidence, @pgaudet ! Unfortunately, I am not the "almighty See" and don't know every complex's function ;-)

I can't add much more here. If you look at the human entry in [UniProt](https://www.uniprot.org/uniprot/Q07864) you see a long list of [Reactome](http://www.reactome.org/content/detail/R-HSA-68483) reactions including the DNA repair pathway, which lets me to conclude that it certainly exists away from the replisome. Whether it's a obligate constituent of of the replisome I can't tell and don't have the time to read into it. Whoever annotated those complexes in CP didn't add much detail ([yeast entry](https://www.ebi.ac.uk/complexportal/complex/CPX-1556)).

has_part - probably
part of - definitely not

Sorry.

**Comment by sjm41** [comment]
This may come down to viruses....at least, DNA viruses that replicate in a host cell nucleus (like SV40).

As mentioned, everything I've read says that Pol epsilon is present and required at nuclear (eukaryotic) replication forks.
Here are two more recent reviews (to add to my previous list):
The Eukaryotic Replisome Goes Under the Microscope 2016 (PMID: 27003891)
DNA polymerase epsilon - more than a polymerase. 2003 (PMID: 12806123)

However, that second reference has a section called "POL ε IS INVOLVED IN REPLICATION OF CELLULAR DNA" that says "The SV40 replisome can be considered the prototypic core replication apparatus in the eukaryotic cell" and the SV40 system only needs Pols alpha and delta (no epsilon). It then goes on to say "The validity of the SV40 DNA replication system as a model of cellular DNA replication is challenged by research done with cellular systems. The catalytic subunit of Pol ε is essential for viability in budding and fission yeast, and temperature-sensitive mutants fail to replicate chromosomal DNA at the restrictive temperature".

A review I found specifically on SV40 replication (PMID: 19101707) says two things of interest:
i) DNA polymerase epsilon is important for chromosomal replication (Seki et al., 2006; Shikata et al., 2006), but SV40 replication does not utilize it in vivo or in vitro (Pospiech et al., 1999; Zlotkin et al., 1996).
ii) though Fig 7 shows "a minimal set of replication proteins at a eukaryotic fork", which includes Pol epsilon.

So...if "nuclear replisome" (GO:0043601) is meant to include SV40-like replisomes, then Pol epsilon should not be part of it.
But if "nuclear replisome" is meant to refer to regular, eukaryotic/nuclear/cellular-based replisomes, then it should, AFAIK.

**Comment by krchristie** [comment]
Hmmm...

If we DO need to represent any possible "_nuclear replisome_", including the ones that include SV40 virus, then as you say we couldn't add Pol epsilon as a part_of "_nuclear replisome_". 

While we could have an upper level term for any "_nuclear replisome_" and then have more specific terms for an "_SV40 type nuclear replisome_" and a "_eukaryotic nuclear replisome_", e.g.
-- nuclear replisome
--- eukaryotic nuclear replisome
--- SV40 type nuclear replisome


However, this is often problematic with respect to annotations since annotators who want to annotate a regular, i.e. non-viral eukaryotic nuclear replisome, are unlikely to even notice the child term for "_eukaryotic nuclear replisome_". If we did this, I think we might want to mark the term "_nuclear replisome_" as a "Do NOT annotate" term so that people couldn't use it. Otherwise, we'd end up with all/most of the "regular" eukaryotic annotations made to the top level term.

So, as @sjm41 pointed out, resolution hinges on whether we need to make the term "_nuclear replisome_" broad enough to include SV40 type nuclear replisomes.

thoughts?? @pgaudet @ukemi  anyone else?

**Comment by krchristie** [comment]
**Disscussed in Ontology Editors' call on 9/9/19**

It was brought up that we have a division between a "regular" `cell` and a `host cell`. Looking at the ontology, we have terms for `nucleus` and `host cell nucleus`; there is no relationship between `nucleus` and `host cell nucleus` because it causes problems, if I recall correctly. Thus a term that would need to accodomate the composition of an SV40 viral replisome, would be related to the `host cell nucleus` term, while the term under discussion `nuclear replisome` is defined with respect to the term `nucleus`. With this in mind, and having just looked at the ontology, I think that we can add this relationship:

`nuclear replisome`
 `has_part` `epsilon DNA polymerase complex`

@pgaudet - Do you still want to tag Patrick for additional input?

**Comment by pgaudet** [comment]
Hi @krchristie 
I think the viral replisome should be annotated to 'replisome' and 'host cell nucleus' separately  - @pmasson55 is that OK ? I find no viral annotations to 'replisome' or children. 

BTW this is a nice recent review for the composition of the different replisomes: 
PMID:31273608, figure 1. We should add it as a cross-reference. 

Pascale

**Comment by pmasson55** [comment]
Hi, 
We actually never used the term viral replisome, instead we used bidirectional double-stranded viral DNA replication for example for herpes viruses or SV40 viral proteins involved in replication.  I'm fine with removing the term viral replisome. Concerning the host proteins that could be of importance for viral replication, they should be tagged with their physiological function I guess and not with viral terms (there are taxonomic constraints anyway, right?)... Maybe host-virus interaction if there is a relevant interaction...Hope this helps.

Patrick.

**Comment by krchristie** [comment]
Thanks for the input @pgaudet and @pmasson55 

There is no go term for `viral replisome`, just for `replisome`, `cytoplasmic replisome`, and `nuclear replisome`. It sounds like there is an effective strategy for annotating viral proteins involved in replication, and also that the term `nuclear replisome` is intended specifically for the normal complex that occurs in cells with nuclei, without needing to deal with viral replication complexes.

Thus, I can go ahead and add this relationship:
`nuclear replisome`
`has_part` `epsilon DNA polymerase complex`

**Comment by sjm41** [comment]
Thanks Karen!
