### ISSUE TITLE
Question: quorum sensing GO:0009372

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17730]
Quoring sensing is defined:

The process in which single-celled organisms monitor their population density by detecting the concentration of small, diffusible signal molecules produced by the cells themselves. PMID:15716452 PMID:8288518

So is quorum sension only the detection and signalling? Or is it also the production of the molecules that are sensed by the "quorum sensing"

These would be quite different in scope. We are not sure whether production of the signalling molecules is caussally upstream, regulatory, or part of the process

**Comment by krchristie** [comment]
The definition of this term cites this Wikipedia page: https://en.wikipedia.org/wiki/Quorum_sensing

which cites this paper:
Bassler, Bonnie L (1999). "How bacteria talk to each other: regulation of gene expression by quorum sensing". Current Opinion in Microbiology. 2 (6): 582–587. doi:10.1016/s1369-5274(99)00025-9. PMID:10607620 

which says this:
> Quorum sensing, or the control of gene expression in response to cell density, is used by both Gram-negative and Gram-positive bacteria to regulate a variety of physiological functions. In all cases, quorum sensing involves the production and detection of extracellular signalling molecules called autoinducers. 

So, since the published literature includes both production of the signal as well as detection, I propose to modify the definition to be clearer.

**Proposed new definition:** - The process in which single-celled organisms monitor their population density by producing small, diffusible, signal molecules and then detecting the concentration of these molecules. PMID:15716452 PMID:8288518 
Add: PMID:10607620

Does this work for you @ValWood ?

**Comment by ValWood** [comment]
That's really helpful. We were looking at production molecules.
We might request children to represent these later.

**Comment by krchristie** [comment]
I supposed I noticed the terms under 'quorum sensing' yesterday, but it didn't sink in. 

<pre>
- quorum sensing (GO:0009372)
-- interspecies quorum sensing (GO:0052097)
--- quorum sensing involved in interaction with host (GO:0052106)
-- intraspecies quorum sensing (GO:0052100)</pre>

The revised definition I proposed earlier was specific to quorum sensing within a single species of microbe and did not really allow for quorum sensing that occurs between species. I took a look at annotations and here are the counts and terms annotated: 

- quorum sensing (80)
- quorum sensing involved in interaction with host (47)
- cell-cell signaling involved in quorum sensing (2)

Of the 47 annotations to '**quorum sensing involved in interaction with host**', 33 are experimental 
- 31 IMP from Mony et al. 2014 
- 1 IMP + 1 IDA from Fujiya et al. 2007

Looking quickly at these 2 papers plus a couple 2006 reviews they led me to, I think that it is specious to try to separate out `interspecies quorum sensing (GO:0052097)` & `intraspecies quorum sensing (GO:0052100)`. Other than in a laboratory monoculture, an organism that is putting out these signals and detecting them, is probably doing it in the context of multiple organisms and it's really the same basic system whether it's detecting its own signal or that of another organism. 

- [ ] **Action item: propose obsoletion of 2 terms:**

Thus, I am going to propose to obsolete these two terms, which have no annotations anyway, since I do not think there is a different process going on between these two things, rather just some differences in specific interactions:
- interspecies quorum sensing (GO:0052097)
- intraspecies quorum sensing (GO:0052100)

----------

There may be some specific things worth capturing, but based on the existing annotations, I am not sure if the term `quorum sensing involved in interaction with host` is one of them.
- 2 annotations from Fujiya et al. 2007 (1 IMP to human SLC22A5 & 1 IDA to Bacillus subtillus phrC) - This paper characterizes the host response to a secreted factor from B. subtillus that happens to be a quorum sensing molecule; it does not talk about the role of phrC in quorum sensing. I think the mammalian protein could be annotated to the existing term 'response to bacterium' or perhaps 'response to symbiotic bacterium'. Or, if people think it's useful, I think we could consider making a term for something like 'response to quorum sensing molecule'. 

- [ ] **Action item:** Challenge these annotations in Protein2GO 

-  31 annotations from Mony et al. 2014 - This paper is about identifying genes of trypanosomes involved sensing their own population while in a host (which is necessary since you can't grow those life stages outside of a host); it does not describe any interaction of the trypanosomes with the host.
- [ ]  **Action item:** Suggest moving these annotations to `quorum sensing` directly since this paper did not show any interaction between quorum sensing genes and host
- [ ] **Action item:** Consider whether this term represents something that is really part of quorum sensing, or whether host sensing is something different


----------

Then, here is a new proposal for a revised definition for `quorum sensing`:

**Proposed new definition**: - The process in which single-celled organisms monitor their own population density, and often that of other microbes, by producing small, diffusible, signal molecules, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst mixed microbial communities such as occur in soil or within host organisms or soil. Pathogenic microbes may also employ quorum sensing pathways to monitor their own population within a host. PMID:15716452 PMID:8288518
**Add**: PMID:10607620, PMID:16630813, PMID:16497924

----------

**References:**
Mony et al. 2014. Genome-wide dissection of the quorum sensing signalling pathway in Trypanosoma brucei. Nature. 2505(7485):681-685. PMID:24336212 (31 IMP annotations)

Fujiya et al. 2007. The Bacillus subtilis quorum-sensing molecule CSF contributes to intestinal homeostasis via OCTN2, a host cell membrane transporter. Cell Host Microbe. 1(4):299-308.  PMID:18005709 (1 IMP annotation, 1 IDA annotation)

Bassler BL, Losick R. 2006. Bacterially speaking. Cell. 125(2):237-46. Review. PMID:16630813.

Camilli A, Bassler BL. 2006. Bacterial small-molecule signaling pathways. Science. 311(5764):1113-6. Review. PMID:16497924

**Comment by ValWood** [comment]
Hi Karen.

re: quorum sensing involved in interaction with host

From the intro of the paper we were reading

Quorum sensing (QS) is a process of bacterial cell-to-cell communication that relies on the production, detection, and response to extracellular signaling molecules called autoinducers [1]. QS allows groups of bacteria to synchronously alter behavior in response to changes in the population density and species composition of the surrounding bacterial community [2,3]. In Gram-negative bacteria, acylated homoserine lactones (AHLs) are common QS autoinducers (reviewed in [4]). Typically, an AHL synthase, usually a LuxI homolog, produces an autoindu- cer that is bound by a partner transcriptional activator, usually a LuxR homolog. LuxR-AHL complexes regulate expression of genes that underpin group behaviors [5]. LuxR-type proteins contain two domains: an amino-terminal AHL-binding domain and a carboxy-terminal helix- turn-helix (HTH) DNA-binding domain [6,7]. Most LuxR-type receptors require their cog- nate AHLs to be bound to function, and in some cases, AHL binding is necessary for LuxR- type proteins to fold and thus resist proteolysis [8–10].
Bacterial pathogens often require QS to establish or to promote infection (reviewed in [11]). One such QS bacterium, Pseudomonas aeruginosa, is a human pathogen that is fre- quently responsible for hospital-acquired infections and is the main cause of morbidity and mortality in cystic fibrosis patients [12,13]. The P. aeruginosa QS circuit consists of two canon- ical LuxI/R pairs: LasI/R and RhlI/R (Fig 1) [14–17]. LasI produces and LasR responds to the autoinducer N-(3-oxododecanoyl)-L-homoserine lactone (3OC12-HSL). The LasR:3OC12– HSL complex activates transcription of many genes including rhlR [18]. RhlR binds to the autoinducer N-butanoyl-L-homoserine lactone (C4-HSL), the product of the RhlI synthase [19]. RhlR:C4-HSL directs a large regulon of genes including those encoding virulence factors such as pyocyanin, elastases, and rhamnolipids, some of which are also members of the Las- R:3OC12-HSL regulon (Fig 1) [20,21]. P. aeruginosa strains harboring mutations in QS regula- tory components have been reported to be attenuated for virulence, and thus, interfering with QS holds promise for the development of novel anti-microbial therapies [22–26].
Beyond controlling virulence, QS controls biofilm formation in P. aeruginosa [26,27]. Bio- film formation is crucial for P. aeruginosa acute and chronic infections [29]. QS-activated genes encoding exoproducts such as the Pel and Psl exopolysaccharides, rhamnolipids, and phenazines are key for biofilms because these products drive the architecture of the developing communities [30–33]. In keeping with this overarching role for QS in biofilm formation, in the laboratory, P. aeruginosa lasR and lasI mutants form defective biofilms that are thin, undif- ferentiated, and easily eradicated by SDS and antimicrobial treatments [27].

so probably the "interaction with host term" is not warranted for "controlling virulence" . This is just one of the  possible  purposes of quorum sensing, but I don't think  this is  "interspecies quorum sensing"

**Comment by ValWood** [comment]
PLoS Pathog. 2017 Jul 17;13(7):e1006504. doi: 10.1371/journal.ppat.1006504. eCollection 2017 Jul.
The RhlR quorum-sensing receptor controls Pseudomonas aeruginosa pathogenesis and biofilm development independently of its canonical homoserine lactone autoinducer.
Sampriti Mukherjee1, Dina Moustafa2, Chari D. Smith1, Joanna B. Goldberg2, Bonnie L. Bassler1,3*

PMID: 28715477

**Comment by mgiglio99** [comment]
Hi,
Commenting on the original question, not the stuff about the host term - I'll put that in issue 17757

I agree on expanding the definition to include production of the molecules.
Here is a revised version of the def proposed by Karen:

Revised new definition: - The process in which single-celled organisms carry out coordinated responses by monitoring their own population density or that of other microbes, producing small, diffusible, signal molecules, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst mixed microbial communities and within host organisms.

**Comment by krchristie** [comment]
@mgiglio99 - I like your proposed definition a lot. I've suggested one additional small modification, in bold. What do you think?

Revised new definition: - The process in which single-celled organisms carry out coordinated responses by monitoring their own population density, **and often also** that of other microbes, by producing small, diffusible, signal molecules, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst microbial communities in the environment or within host organisms.

**Comment by mgiglio99** [comment]
@krchristie 
Sounds good.  : )

**Comment by krchristie** [comment]
In  **merge: cell-cell signaling involved in quorum sensing (GO:0010699) into its parent term quorum sensing (GO:0009372) #18018**, we agreed on a slight modification to the definition (below) and also to make `quorum sensing` a direct child of `cell-cell signaling`. 

> **=> Revised new definition: - `quorum sensing`**
> 
> The cell-cell signaling process in which single-celled organisms carry out coordinated responses by monitoring their own population density, and often also that of other microbes, by producing small, diffusible, signal molecules, detecting the concentration of these molecules, and triggering a signal transduction pathway when a certain threshold is reached. Quorum sensing can occur amongst microbial communities in the environment or within host organisms.
>

**Comment by pgaudet** [comment]
On a related note: " GO:0060245 detection of cell density" should probably be a parent of quorum sensing.

**Comment by ValWood** [comment]
Or merge? Is this different?

**Comment by ValWood** [comment]
OK got it
GO:0060245 detection of cell density 
can be used to detect cell density within a population
(at least that is what it is used for)

Although this is a bit confusing. It seems to be about detating via contact. Is this really detecting cell density?

**Comment by ValWood** [comment]
This one for instance 

UniProtKB:Q99835 | SMO | involved_in | GO:0060248    detection of cell density by contact stimulus involved in contact inhibition | ECO:0000315   IMP | PMID:9422511
-- | -- | -- | -- | -- | --


is about contact inhibition.
I would be inclined to  take the references to "cell density" out of these terms. It's just the assay isn't it?





To investigate the oncogenic potential of the two SMO missense
mutations in BCCs, we transfected rat embryonic fibroblast REF52
cells with E1A together with wild-type or mutant SMO (M1 or M2),
and assessed for focal cells overgrowth. Cells transfected with wildtype SMO and E1A formed a uniform monolayer in culture. In
contrast, E1A plus either mutant SMO induced a transformed
phenotype with focus formation over the confluent monolayer
(Table 1). Cells within the foci lose normal density-dependent
growth inhibition, resulting in increased cellular packing and loss
of fibroblast morphology

**Comment by ValWood** [comment]
GO:0060242    contact inhibition
Definition 
The cellular process in which cells stop growing or dividing in response to increased cell density. PMID:17376520

so why 

GO:0060248    detection of cell density by contact stimulus involved in contact inhibition?

Isn't this just "contact inhibition"?
