### ISSUE TITLE
Some protein-containing complexes are also still cellular anatomical entities.

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#17777]
There are still a small number of terms in the ontology that are both cellular anatomical entities
and protein-containing complexes. We need to choose a classification. Keep in mind that in the GO-CAM specs, protein-containing complexes can enable molecular functions.
'GW body'
'P granule'
'PAM complex, Tim23 associated import motor'
'RNP body'
'TIS granule'
'TORC1 complex'
'TORC2 complex'
'banded collagen fibril'
'chloroplast ribosome'
'chromatoid body'
'collagen anchoring fibril'
'collagen network'
'collagen sheet'
'collagen type VII anchoring fibril'
'complex of collagen trimers'
'condensed chromosome kinetochore'
'condensed nuclear chromosome kinetochore'
'cytoplasmic ribonucleoprotein granule'
'cytoplasmic stress granule'
'cytosolic ribosome'
'high-affinity iron exporter complex'
'high-affinity iron permease complex'
'mitochondrial respiratory chain complex IV pre-assembly complex'
'mitochondrial ribosome'
'mutator focus'
'neuronal ribonucleoprotein granule'
'nuclear stress granule'
'organellar ribosome'
'plastid ribosome'
'polysomal ribosome'
'ribonucleoprotein granule'
'striated muscle myosin thick filament'
'viral integration complex'
P-body
kinetochore
pi-body
piP-body
podosome
ribosome

**Comment by pgaudet** [comment]
I would say: 

is_a protein-containing complex: 
- 'TORC1 complex'
- 'TORC2 complex'
- 'high-affinity iron exporter complex'
-'high-affinity iron permease complex'
-'mitochondrial respiratory chain complex IV pre-assembly complex'

All others 'cellular anatomical entities'. 

Maybe @bmeldal can help ? 

Thanks, Pascale

**Comment by ValWood** [comment]
@pgaudet   your classification looks good to me, and I like @ukemi 's proposed criteria that  complexes must equate to  "functional entities"

**Comment by bmeldal** [comment]
> I would say they don't enable a function and we would never annotate the ribosome as enabling a function. We would annotate its parts as enabling functions.

I think that's what we ended up doing, too. Because the ribosomal subcomplexes carry out different functions during the whole process of translation we created all those complexes but didn't make 'the ribosome' a complex entry.

Do you need me to go through the list above? There are a few that at first glance definitely look like bona fide complexes (have 'protein-containing complex' parent unless otherwise indicated):

'PAM complex, Tim23 associated import motor'
'TORC1 complex'
'TORC2 complex'
'banded collagen fibril' - supramolecular complex & protein-containing complex
'collagen anchoring fibril' - supramolecular complex & protein-containing complex
'collagen network' - supramolecular complex & protein-containing complex
'collagen sheet' - supramolecular complex & protein-containing complex
'collagen type VII anchoring fibril' - supramolecular complex & protein-containing complex
'complex of collagen trimers' - supramolecular complex & protein-containing complex
'condensed chromosome kinetochore'
'condensed nuclear chromosome kinetochore'
'high-affinity iron exporter complex'
'high-affinity iron permease complex'
'mitochondrial respiratory chain complex IV pre-assembly complex'
'striated muscle myosin thick filament'
'viral integration complex'
'kinetochore'

The reason why some have `supramolecular complex` & `protein-containing complex` as parents is that their smallest-definable unit is a complex but they usually function in a larger structure made up of multiples of the complex and therefore have an is_a relationship in the ontology. Other complexes like these have a part_of relationship in the ontology (such as the ribosomal subunits). Maybe something to look at in detail. @dosumis worked on this with me a while ago.

**Comment by ukemi** [comment]
Thanks @bmeldal. The fundamental issue is that we don't want to have something be both a 'cellular anatomical entity' and a 'protein-containing complex'.  All of the components I listed currently have both. Doesn't it make sense that if a component is a 'protein-containing complex' and we want a relationship to 'supramolecular complex' it should be 'protein-containing complex' part_of 'supramolecular complex'? Currently 'supramolecular complex' is_a 'cellular anatomical entity', which I think is ok.

**Comment by bmeldal** [comment]
Yes, got you, slightly missed part of the point this morning.

The bona fide complex terms should have `part_of,` not `is_a`, `some child of "cellular anatomical entity"` relationships. 

E.g., some collagen trimer `NOT is_a` some collagen sheet, but some collagen trimer `part_of` some collagen sheet. A collagen sheet is made up of several collagen trimers etc...

Of the above terms I listed, they are all bona fide complexes except the 6 collagen terms. I found the issue: 

`GO:0098644 complex of collagen trimers is_a GO:0032991 protein-containing complex` is incorrect and needs to be removed. Then the 5 children are fixed, too. And all the bona fide collagen complexes (the trimers) will become part_of `cellular anatomical entity` acc to your rule.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/10517124/63953637-a20b1680-ca79-11e9-9740-7c6fd082e0ee.png">

I don't know for the other terms I didn't list again, I guess they need to have their is_a protein-containing complex relationships removed, too.

**Comment by ukemi** [comment]
Thanks @bmeldal !!! I can make this happen.

**Comment by bmeldal** [comment]
Excellent!

**Comment by ukemi** [comment]
Fixed in #17839
