### ISSUE TITLE
Difference between passive evasion of immune system terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17894]
GO:0051809    passive evasion of immune response of other organism involved in symbiotic interaction
Definition 
Any process in which an organism avoids the immune response of a second organism without directly interfering with the second organism's immune system, where the two organisms are in a symbiotic interaction. PMID:12439615

GO:0042782    passive evasion of host immune response
Definition (
Any mechanism of immune avoidance that does not directly interfere with the host immune system; for example, some viruses enter a state of latency where their protein production is drastically downregulated, meaning that they are not detected by the host immune system. The host is defined as the larger of the organisms involved in a symbiotic interaction. PMID:12439615

I stared at these 2 terms for a while and I don't see a diffrerence? Can they merge?

- [x] this part is done

**Comment by addiehl** [comment]
I believe that GO:0020033 antigenic variation is an active process in trypanosomes and therefore appropriately a sibling of GO:0042782 passive evasion of host immune response.

https://www.ncbi.nlm.nih.gov/pubmed/24859277

Alex

**Comment by ValWood** [comment]
Currently antigenic variation is a child of
GO:0051809    
passive evasion of immune response of other organism involved in symbiotic interaction

and a sibling of
GO:0042782    passive evasion of host immune response

I think from @pgaudet  changes, if the parentage was assumed to be correct it will end up under
GO:0042782    passive evasion of host immune response
after the merg


based on what  you are saying, the current parentage is incorrect and this should be correctly positioned under

GO:0042783   active evasion of host immune response

So do we have any examples of passive processes?
I don't think there will be many "passive process annotations" after this move. I looked yesterday and most  appeared to be related to antigenic variation.

**Comment by pgaudet** [comment]
Right - passive is weird, as if no gene product was mediating it - hence not a 'GO-annotatable' term?

**Comment by ValWood** [comment]
I don't know what it means in this context. 
@addiehl  or @mgiglio99  may know.
I  thought it might not be a necessary grouping term is we has 'types'. But I could not find any...

**Comment by pgaudet** [comment]
Maybe we could drop the distinction between active and passive evasion of immune response ? There are only 5 terms: 

*GO:0042786 active evasion of host immune response via regulation of host antigen processing and presentation' 
* GO:0042784 'active evasion of host immune response via regulation of host complement system'
* GO:0042785 'active evasion of host immune response via regulation of host cytokine network'
* GO:0042783 'active evasion of host immune response'
* GO_0042782 'passive evasion of host immune response'

I could merge GO_0042782 and GO:0042783 and drop 'active' and 'passive' from all term labels. Would that work ? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think so.

GO:0042782 passive evasion of host immune response
has zero annotation, 

GO:0051809   passive evasion of immune response of other organism involved in symbiotic interaction
has no direct annotations. All are to *current * child “antigenic variation” which Alex says is also direct


Better instantiating the types-of process without this axis of classification (which will really just hinder people drilling down the ontology from finding the correct terms)

**Comment by addiehl** [comment]
I agree with dropping the distinction between active and passive evasion of the immune response, as passive evasion does not seem like an actual process

**Comment by pgaudet** [comment]
Good. This is what the ontology looks like now: 

<img width="546" alt="image" src="https://user-images.githubusercontent.com/4782928/65644849-67869200-dfc3-11e9-9f5d-b431d82fe944.png">


Do we need the distinction between 
GO:0020012 evasion or tolerance of host immune response
and  (GO:0042783) evasion of host immune response ? 
There are 'evasion' children but no 'tolerance' children. 

Thanks, Pascale

**Comment by ValWood** [comment]
> Do we need the distinction between
GO:0020012 evasion or tolerance of host immune response

I do not understand the tolerance part. I was thinking about this  in the night. See my comments  in the other ticket...

**Comment by addiehl** [comment]
I believe that evasion and tolerance are actually two distinct things.  Evasion, of which a subtype is antigenic variation, is a strategic employed to avoid engaging a host immune reaction, such as avoiding an ongoing immune response by changing the proteins on the symbionts surface, as trypanosomes do so that no reactivity between host components (antibodies) and symbiont components occur.

Tolerance occurs through the production of symbiont proteins that "defuse" an ongoing host response actively, such as the production of flavohemoglobin by certain virulent forms of E.coli, which specifically deactivates nitric oxide by converting it to NO3-, and thus eliminating its free radical activity against the bacterial DNA and proteins.  In this case, the symbiont product actively engages a host product to inactivate it and thus allow the bacteria to tolerate this form of the host's immune response. (https://www.ncbi.nlm.nih.gov/pubmed/16407044)

Sorry to be so annoying.

**Comment by ukemi** [comment]
Thanks @addiehl. We value your input.

**Comment by pgaudet** [comment]
Thanks @addiehl , this is very useful. 

These are all evasion, right? 
(ie the parent could be renamed?): 

  - 'evasion or tolerance of host immune response' 
  --  'antigenic variation' (OK, if corresponds to evasion) 
  --  'evasion of host immune response' (OK, grouping term)
  --- ' evasion of host immune response via regulation of host antigen processing and presentation' 
  --- 'evasion of host immune response via regulation of host complement system' (should be tolerance?) 
  --- 'evasion of host immune response via regulation of host cytokine network' (should be tolerance?)

**Comment by pgaudet** [comment]
Also: do those terms correspond to 'tolerance'?  

'evasion or tolerance by symbiont of host-produced nitric oxide'
'evasion or tolerance by symbiont of host-produced phytoalexins'
'evasion or tolerance by symbiont of host-produced reactive oxygen species'

Thanks, Pascale

**Comment by addiehl** [comment]
'evasion or tolerance of host immune response'
-- 'antigenic variation' (OK, if corresponds to evasion)
I agree this is evasion and should be moved under 'evasion of host immune response'

-- 'evasion of host immune response' (OK, grouping term)
--- ' evasion of host immune response via regulation of host antigen processing and presentation'
I would call this evasion, because by regulating host antigen processing and presentation, the symbiont avoids provoking an immune response, since successful antigen processing and presentation must occur prior to an adaptive immune response in order to start it off.

--- 'evasion of host immune response via regulation of host complement system' (should be tolerance?)
Arguably this is could be considered evasion or tolerance depending on the steps of the complement cascade that are inhibited.  Evasion, however, appears to be the term primarily used in the literature. Regulation of the early steps of the complement system qualifies as evasion since the symbiont is rendering the complement system blind to the presence of triggering symbiont components.  Regulation of activation of complement proteins C5-C9 could however be considered tolerance, since the complement system has clearly been activated and formation of the membrane attack complex would normally be the end result.  In this sense the symbiont is tolerating activation of the complement system by suppressing the effector activities of the C5-C9 components.  Rather that making two terms, we can simply name the term 'evasion or tolerance of host immune response via regulation of host complement system' to cover both possibilities and move it up a level.  See https://www.ncbi.nlm.nih.gov/pubmed/20062962 for examples of how different gram-positive bacteria inhibit different steps of the complement cascade.

--- 'evasion of host immune response via regulation of host cytokine network' (should be tolerance?)
Similarly, this could be considered evasion or tolerance, depending on which cytokines are being inhibited (https://www.ncbi.nlm.nih.gov/pubmed/23255141).  For instance, disruption of IL-1beta, stops an early step in initiating a full immune response and represents evasion.  On the other hand bacterial components that promote a Th2 immune response via induction of IL-4 and suppression of IL-12, allow for tolerance of an ongoing immune response by directing it away from a Th1 type of immune response that includes effector mechanisms capable of directly killing bacteria.  Again, I think we should name this term 'evasion or tolerance of host immune response via regulation of host cytokine network' to cover both possibilities and move it up a level.

Also: do those terms correspond to 'tolerance'?
'evasion or tolerance by symbiont of host-produced nitric oxide'
'evasion or tolerance by symbiont of host-produced phytoalexins'
'evasion or tolerance by symbiont of host-produced reactive oxygen species'

Yes, I think that these terms should simply be considered tolerance and renamed appropriately and place appropriately in the hierarchy.

Alex

**Comment by mgiglio99** [comment]
This plan/structure makes sense to me.
In my simplistic view of evasion vs. tolerance, evasion is when the symbiont does something to the host to make the immune response stop, while tolerance is when the symbiont does something within itself in order to withstand the onslaught.

I think we do need to think about the modulation terms in the context of the above terms since many of the things described in the terms above are modulation of the immune response.
(Maybe this is already talked about in another issue, I've not made my way through everything yet.)

It would be useful to come up with a word that could encompass modulation, evasion, and tolerance then the distinctions wouldn't necessarily need to be made.

**Comment by ValWood** [comment]
>It would be useful to come up with a word that could encompass modulation, evasion, and tolerance then the distinctions wouldn't necessarily need to be made.

I agree. It would be useful if the high level term was agnostic to evasion or tolerence, and  these were only used in specific terms where it is known .


The definitions of evasion  seem to vary, some say the evasion is by tolerance or modification.

Quite a few of the  review I look at say things like

Mechanism of Action—Part II (Cancer)
Tom Brody Ph.D., in Clinical Trials (Second Edition), 2016
https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/immune-evasion
II Immune Evasion
Immune evasion by cancer cells involves a number of mechanisms, including T-cell exhaustion, immunosuppressive cytokines that “cool down” the immune system, such as the cytokine interleukin-10 (IL-10). 

So could everything be grouped under evasion if it is defined broadly?
Or is this broader usage restricted to cancer cells and not  when describing pathogenicity?

https://www.immunology.org/public-information/bitesized-immunology/pathogens-and-disease/host-%E2%88%92-pathogen-interactions-and
This article presents a selection of both virulence and immune evasion strategies, the latter of which may involve: (1) hiding from the immune system (e.g. within cells); (2) interfering with the function of the immune system (e.g. blocking signals); (3) destroying elements of the immune system (e.g. the structures which present microbial antigens to immune effectors to initiate a response in the host)

It seems that it will be difficult or even impossible to pick apart evasion and tolerance. Could people live with  just calling everything evasion in the parent term?

**Comment by mgiglio99** [comment]
How about "mitigation".
could the term "mitigation of host immune response" cover evasion, tolerance, and modification?

**Comment by pgaudet** [comment]
As an additional parent term ?

**Comment by ValWood** [comment]
I would say instead of. I think we should move away from evasion or tolerance as a grouping term  (they seme to mean different things to different groups of people). If the complement activation can be part evasion or part toleance it will be impossible for curators to figure out.
It would  be better to  refer to actual "processes" (immune system regulation, or PAMP triggered-immunity, antigenic variation etc etc,  rather than "outcomes" tolerence, avoidance which seem to be slightly orthogonal and  less precise in their scope.....

**Comment by mgiglio99** [comment]
I agree - Not additional, instead of.
We could merge the existing evasion, tolerance, and modulation parent grouping terms under a term with "mitigation" instead. 
So we could merge "evasion or tolerance of host immune response" and "modulation by symbiont of host immune response" under "mitigation by symbiont of host immune response".
Same could be done with the "defense response" terms. Then, if needed, a child term might have "tolerance" or another word in it's name if needed, but there wouldn't be a need to a priori sort terms according to which of the three categories they belong in.

**Comment by ValWood** [comment]
@addiehl  would this work for you?

**Comment by addiehl** [comment]
This works if we include appropriate related (or narrow) synonyms to the main term so that curators are not surprised or confused by the word mitigation in the term name.

**Comment by pgaudet** [comment]
- [ ] 'evasion or tolerance by virus of host immune response' <http://purl.obolibrary.org/obo/GO_0030683> 
-> 'mitigation of host immune response by virus' 
- [ ] 'evasion or tolerance of host defenses by virus' <http://purl.obolibrary.org/obo/GO_0019049>
->'mitigation of host defenses by virus' 
- [ ] 'evasion or tolerance of host defenses' <http://purl.obolibrary.org/obo/GO_0030682>
-> 'mitigation of host defenses' 
- [ ] 'evasion or tolerance of host immune response' <http://purl.obolibrary.org/obo/GO_0020012>
-'mitigation of host immune response'

**Comment by pgaudet** [comment]
+ merge : 

'negative regulation by symbiont of host defense response'
into 'suppression of host defenses by symbiont'
