### ISSUE TITLE
exact xref mapping relation type semantics

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#17892]
The GO provides mapping relations (in the sense of https://www.w3.org/TR/skos-reference/#mapping) only for synonyms of entry names, by providing the annotation properties
```
has_broad_synonym
has_exact_synonym
has_narrow_synonym
has_related_synonym
```
No mapping relation specifications are possible in GO for xref assertions, despite these being mostly between hierarchical structures (and so they would be needed in principle). Without such information it is impossible to map cross references exactly and, thus, model GO's information automatically in knowledge bases like Wikidata.

At the least an assertion type for exact database cross referencing would help tremendously.

**Comment by rwst** [comment]
Let me add that at the moment cross references in GO are NOT all exact because they are not all one-to-one (i.e. injective).

**Comment by hdrabkin** [comment]
I could have sworn I replied to this. 
No, ECs are not necessarily 1:1; RHEAs will/are.  RHEA will use a single EC for multiple RHEA ids.
So basically we do have two flavors of XREF. One that means equivalence (RHEA) and some not so equivalent.

**Comment by deustp01** [comment]
The broader issue here, I think, is one of granularity. EC, Rhea, and GO are separate annotation groups with different standards and user interests and there's no reason why they should all treat catalysis with the same degree of granularity in every case. As long as the issue is clean one-to-many mappings, I think it's important to find ways to accommodate that. (Not really a new idea in this group of threads; just felt like articulating it.) @ukemi ?

**Comment by hdrabkin** [comment]
Yes; I guess we need/want different flavors of what an XREF is (like synonyms).

**Comment by deustp01** [comment]
Which is something like what Ralf is getting at, at the start of this ticket? Agreed - the issue is tuning the logic for representation here to accommodate the lumpy biology.

**Comment by hdrabkin** [comment]
Yes exactly.; not something I can implement here...

**Comment by deustp01** [comment]
something for an ontology call?

**Comment by pgaudet** [comment]
Hi @rwst 

This was recently addressed here: https://github.com/geneontology/go-ontology/issues/20620
I added some documentation here: http://wiki.geneontology.org/index.php/Guidelines_for_%27database_cross_references%27_and_%27definition_database_cross_references%27#General_cross-reference_types

Does that resolve this ticket ? 

Thanks, Pascale

**Comment by rwst** [comment]
Yes, many thanks for your work.

**Comment by hdrabkin** [comment]
@pgaudet
Looking at the  doc
"EC and MetaCyc cross-references are  are skos:narrowMatch by default but can be upgraded if 1:1 correspondence
BUT
skos:narrowMatch: GO term meaning is more general than that of the cross-referenced term. More than one NARROW xref is allowed per term, but a given NARROW xref can only be mapped to a single term
This seems confusing to me.
Since EC is describing mechanism, I see  EC as broad by default? (eg EC:2.7.1.216).

**Comment by rwst** [comment]
> EC as broad by default? 

No, it also has very specific entries that would never make a function entity, e.g. EC 3.4.21.111. The problem with EC is that it has both broad and narrow entries.

**Comment by hdrabkin** [comment]
So labeling the default as narrow does not make sense. In some cases it can be upgraded to exact match?.

**Comment by rwst** [comment]
In many, yes.

**Comment by balhoff** [comment]
> No mapping relation specifications are possible in GO for xref assertions, despite these being mostly between hierarchical structures (and so they would be needed in principle).

@rwst we've started to work on this: 

https://github.com/geneontology/go-ontology/issues/20147
https://github.com/geneontology/go-ontology/issues/20620
