### ISSUE TITLE
NTR 'virulence effector-mediated evasion or tolerance of host immune response' and fix definitions related terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#17905]
Decisions from #17437

GO:0030682 evasion or tolerance of host defense response
Definition
Any process, either active or passive, by which an organism avoids or tolerates the effects of its host organism's defense response. The host defense response is mounted by the host in response to the presence of the organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

and
GONEW ~virulence~ effector-mediated evasion or tolerance of host immune response
GONEW proposed def
~The action by which a plant or animal symbiont of establishing establishes itself in a host by manipulation of host immune responses. GLOSS These processes are mediated by effectors secreted by the ~pathogen~ symbiont into the host.
related synonym “pathogen effector-mediated immune evasion”

Note that we used "by manipulation of host immune responses" in the def rather than
"avoids or tolerates" . "Avoids" would be always suppressing the host immune system, but sometimes in the case of necrotroph the effector" activates" the immune system

So we need to either
i) broaden the def of the parents, to include any immune system manipulation (not just tolerance or avoidance)
ii) Move the new term up to be a child of a manipulation term
or
iii) Create a new term to cover necrotrophs (it is rather hijacking the immune system, by killing cells )

We prefer i) or ii) so we can easily find the "effector" term in GO. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood 

The effector does not only affect the immune system, does it ? 

Doesn't we want 'GONEW virulence effector-mediated evasion or tolerance of host defense response'?  (in addition or instead). 

Thanks, Pascale

**Comment by mgiglio99** [comment]
@ValWood 
There is an existing term 'modulation by symbiont of host immune response' GO:0052553, which itself is a child of 'modulation by symbiont of host defense response' GO:0052031.
Perhaps this could be the parent for the new term?
In fact many of the current children of that term represent effector processes needed by the PAMGO folks.
And if we do the more general one @pgaudet suggests, it could be a child of GO:0052031.

And I don't mean to be a pest, but I think we agreed that we'd take the word 'virulence' out of the term name and use it instead in a synonym name. As well as taking 'pathogen' out of the def.

And on a bit of an aside, I'm wondering if we should merge together the 'evasion or tolerance' and 'modulation' terms to be all-encompassing. I know we felt a need to separate these when PAMGO was happening, but now I wonder if it just makes things more complex than it needs to be - but I haven't really thought this through yet - so just thinking out loud.

**Comment by ValWood** [comment]
@CuzickA

**Comment by ValWood** [comment]
I suggested a merge of that term here:
https://github.com/geneontology/go-ontology/issues/17441
it is also incorrectly placed, so we have 2 branches with the same meaning.

I re added the cross outs

**Comment by pgaudet** [comment]
@mgiglio99 
how about using 'effector-mediated evasion or tolerance of host immune response' as the main term label ?

**Comment by ValWood** [comment]
SHould be 
 'effector-mediated evasion or tolerance of host immune response'
I forgot to edit

**Comment by ValWood** [comment]
> And on a bit of an aside, I'm wondering if we should merge together the 'evasion or tolerance' and 'modulation' terms to be all-encompassing. I know we felt a need to separate these when PAMGO was happening, but now I wonder if it just makes things more complex than it needs to be - but I haven't really thought this through yet - so just thinking out loud.

I see what you  mean here (see the other tickets).

I  hadn't really clicked on the difference... you  usually need to modify the immune system to evade or tolerate it so I had been using this branch usually.

I found the other branch later.


I think  some of the modification terms can descendants of the related "evasion or tolerence terms" (unless a symbiont modifies the host immune system for any other reason than to evade or tolerate it?)

You don't always need to modify the immune system to evade or tolerate it (for example in the antigenic variation), so they are not exactly the same.

**Comment by ValWood** [comment]
> Doesn't we want 'GONEW virulence effector-mediated evasion or tolerance of host defense response'? (in addition or instead).

I would prefer to have just the immune system term unless/until we have examples of non-immune, then we can assess if this is "effector activity" or just an alternative role of the "effector". It's hard to know until we see one.  I prefer the don't make the term until we have the example method...

**Comment by mgiglio99** [comment]
Some effectors, namely HopX1 from P. syringae, are able to cause plants to open their stomata to allow the microbe's entry. (When a pathogen is detected, the plant defense is to shut the stomata so microbes can't enter that way, but HopX1 degrades the repressors of genes that open the stomata and thus can reverse the stomatal closure. ) 
See PMID:27359369
In a quick search, I've found other things that I think would count as non-immune system effector activities, but since my knowledge of what counts as part of the plant immune system is minimal, I'm not sure. I'd have to research more.

**Comment by ValWood** [comment]
OK good example... so we will require the parent.

**Comment by ValWood** [comment]
@pgaudet if thse 2 terms are OK could they be added. I'm doing the pathogen host work this week and all seem to need this term.
As I work through these papers I can see if any existing terms should be children of the "effector-mediated" term.

Although I guess now it would be "effector-mediated manipulation of host immune system"
"

**Comment by mgiglio99** [comment]
So the two terms would be: 
'effector-mediated manipulation of host immune system'
'effector-mediated manipulation of host defense response'
Where would the "mitigation" terms we talked about fit in? (The proposed new merge of  evasion, tolerance, and modulation.) As pointed out above, you are using manipulation because sometimes the immune response is activated by the symbiont on purpose.
Should we separate out purposeful activation of the immune system into its own branch and have the rest under "mitigation"?

**Comment by ValWood** [comment]
You are right, this would not be specific enough.
We should use "mitigation "  here instead of manipulation.

In these terms,  we are specifically referring to tolerance/avoidance and not to  "activation by necrotrophic pathogens", which is also a form of manipulation, but not in the normal tolerence or evasion type. I think it makes sense to keep these separate, if possible.

Your "mitigation" seems to capture this distinction?
the action of reducing the severity, seriousness, or painfulness of something.

We can always look into grouping these later if there is an obvious use case to do so...
 (maybe there is to find all "effectors" ?). But the annotations to the existing terms  should all have the "evasion or tolerance" interpretation? and would be better as "mitigation".

It's a great word, I just need to remember that we are using it ;)

**Comment by ValWood** [comment]
I forgot about this ticket and  but I closed some old ones and opened some new ones which also seem to cover everything in this ticket

closed
https://github.com/geneontology/go-ontology/issues/18001
https://github.com/geneontology/go-ontology/issues/18041

opened
https://github.com/geneontology/go-ontology/issues/18310
https://github.com/geneontology/go-ontology/issues/18311


so closing this. Could you look over the 2 new tickets?

**Comment by ValWood** [comment]
discussion here all covered in the new tickets


#18315 opened 9 minutes ago by ValWood
#18314 opened 11 minutes ago by ValWood
#18313 opened 14 minutes ago by ValWood
#18312 opened 26 minutes ago by ValWood
#18311 opened 1 hour ago by ValWood
#18310 opened 1 hour ago by ValWood 0
