### ISSUE TITLE
logical def of protein transporter activity is incorrect

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17969]
transports or maintains the localization of.

should be

transports (maintains is not transport, transport is directed movement).

(parents might be incorrect too)

**Comment by ValWood** [comment]
(this refers to logical definition)

**Comment by pgaudet** [comment]
I am not sure of the history of this relation, but I know it's also meant to be used for 'localization', which is not necessarily 'transport', but could be sequestering, degradations. 

So if we change the relation used here to 'transports' we'd need another relation for 'localizes' (just saying, maybe this is what we want to do...? ). 

Pascale

**Comment by ValWood** [comment]
But doesn't the logical definition need to be precise ? @cmungall  ?
This is the logical definition for "localization", not for "transport"

**Comment by ValWood** [comment]
pinging @cmungall

**Comment by pgaudet** [comment]
Hi @cmungall Could we change the relation 'transports or maintains localization' for transporter activities and BPs to 'RO_0002020' transports ?

**Comment by ValWood** [comment]
@cmungall

**Comment by ValWood** [comment]
This might even be fixed. I  can't see the logical defs so I don't know how I came across this issue

**Comment by cmungall** [comment]
Sorry, I love the github '@'-name notification feature but an email is often best way to ping me

(we need to make the logical defs more globally visible)

@ValWood is correct, the logical definition needs to follow the documented pattern, otherwise we will get incomplete or possibly even incorrect inferences.

I can't find transporter in our documented patterns https://github.com/geneontology/go-ontology/tree/master/src/design_patterns -- it's really important we have all patterns documented in a computable way. All other OBOs are using this system this seems to have lagged in GO

**Comment by ValWood** [comment]
So  trabsport needs a pattern, might now be done via another ticket. If not who should be assigned?

**Comment by ValWood** [comment]
out of date, this now has corect logical def.
