### ISSUE TITLE
NTR:  initial spindle pole body separation involved in meiosis I |(commmunity curation)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#17971]
definition 
The release of duplicated meiotic spindle pole bodies (SPBs)

(I didn't add the detail that we have for mitosis because  it differs in some respects but I'm not sure precisely how it differs yet

PMID:31532702

**Comment by ValWood** [comment]
Note I worded it this way becasue 

initial meiosis I spindle pole body separation 

sounded strange?
but would be more consistent so maybe we should use this?

**Comment by mah11** [comment]
Any word on this? (Asking because we need the new term to resolve an annotation warning.)

**Comment by pgaudet** [comment]
I dont love 'involved in' terms but here you go

+[Term]
+id: GO:0140456
+name: initial spindle pole body separation involved in meiosis I
+namespace: biological_process
+def: "The release of duplicated meiotic spindle pole bodies (SPBs)." [PMID:31532702]
+is_a: GO:0000073 ! initial mitotic spindle pole body separation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/17971 xsd:anyURI
+created_by: pg
+creation_date: 2020-04-22T19:07:22Z
+

**Comment by pgaudet** [comment]
You also seemed to want a better definition, let me know if you want to edit the one you proposed - I dont have any suggestions for this. 

Thanks, Pascale

**Comment by ValWood** [comment]
I also don't like the 'involved in'
We aren't really trying to articulate that it is involved in meiosis I (Although it is), but that it is the "meiosis I spindle pole body" (which is compositionally different from the mitotic spindle pole body).

We could say
meiotic  spindle pole body duplication instead. 

(this fits the  current ) definition. It would lump the separation at  meiosis I and meiosis II but it is essentially the same SPB structure  as far as we are aware....

**Comment by mah11** [comment]
This appears to have gone a bit wrong, probably due to a copy/paste error in the last comment. The ontology now has

 GO:0140456 ! meiotic spindle pole body duplication is_a GO:0000073 ! initial mitotic spindle pole body separation

which makes no sense -- SPB duplication is not a type of SPB separation at any time, and no meiotic SPB process is a type of mitotic SPB process. I think it should be

id: GO:0140456
name: initial meiotic spindle pole body separation
is_a: GO:0110100 ! spindle pole body separation
 and is_a: GO:1903046 ! meiotic cell cycle process, unless Val knows of a more specific meiotic cell cycle parent

**Comment by ValWood** [comment]
Sounds correct. May need additional  rejigging but I haven't been annotating in this area recently. This fix would make things not wrong.

**Comment by pgaudet** [comment]
Thanks @mah11 and @ValWood
