### ISSUE TITLE
cytochrome P450 hydroxylase and epoxidase activity

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#18004]
Dear GO curators,

Would it be possible to create these new terms:
1. all-trans retinoic acid 18-hydroxylase activity [Rhea:55856]; PIMD:22020119
2. testosterone 16-beta-hydroxylase activity [Rhea:46304]; PIMD:21289075
3.  secalciferol 1-monooxygenase activity [Rhea:49064]; PMID:10518789
as children of GO:0004497
4.  arachidonoylethanolamide (anandamide) epoxidase activity [Rhea:53148]; [Rhea:53144]; [Rhea:53140]; PIMD:21289075 as child of GO:0016709?
Also I would like to use GO:0008401 - retinoic acid 4-hydroxylase activity - to annotate [Rhea:51492] and suggest we change it to all-trans retinoic acid 4-hydroxylase activity to distinguish from other isomers. The reference for this GO term PMID:19519282 is about all-trans retinoic acid.

Looking forward to your feedback.

Many thanks for your help.
Nevila Hyka-Nouspikel

**Comment by ukemi** [comment]
For item 4, we need to have a 1:1 mapping between a GO term and a Rhea reaction. Do you know if there is a Rhea reaction for the grouping term? I suspect not since seems like it is a mechanistic classification. If not, would you like all of the reactions represented and would you still like the grouping term?

The all-trans RA request seems reasonable since it is the major species in vivo. But to be sure I will sample some of the papers for the genes already annotated to this term to be sure they don't use 9- or 13-cis. If I recall correctly the isomerization between the isomers is spontaneous.

**Comment by ukemi** [comment]
Perhaps this would work for the grouping reaction:
anandamide epoxidase activity: Catalysis of the reaction: N-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-ethanolamine (ChEBI:2700) + O2 + reduced [NADPH--hemoprotein reductase] = H(+) + H2O + EET (ChEBI:64007) + oxidized [NADPH--hemoprotein reductase]

@amorgat or @alanbridge any ideas?

**Comment by ukemi** [comment]
PMID:9250660 was used in a mouse annotation and shows that the _Cyp26a1_ gene product can metabolize ATRA, 9CRA and 13CRA.

PMID:14532297 was used in a human annotation and shows that CYP26C1 can metabolize ATRA and 9CRA.

PMID:10823918 was used in a human annotation and shows CYP26A1 and CYP26B1 can metabolize ATRA, 9CRA and 13CRA, but greatly prefers ATRA.

PMID:9716180 was used in a human annotation and shows that CYP26A1 is specific for ATRA.

Given that all can convert ATRA but some can also utilize the cis isomers, I am tempted to leave the generic term because the different isomers interact with different receptors and therefore have different biological consequences. 

Tagged for editors' discussion.

**Comment by nnouspikel** [comment]
Hi David,

Here is 1:1 mapping for item 4:
anandamide 8,9 epoxidase activity Rhea:53140
anandamide 11,12 epoxidase activity Rhea:53144
anandamide 14,15 epoxidase activity Rhea:53148

There is no generic RHEA for achidonoylethanolamide (anandamide) epoxidation. 

We might create a GO generic term:
anandamide epoxidase activity 
definition: epoxidation of double bonds of arachidonoylethanolamide
and list the specific terms as children. It's up to you. 

Many thanks!
Nevila

**Comment by nnouspikel** [comment]
Hi David,

Regarding CYP26A1 monooxygenase activity toward retinoic acid, it will be good to have a specific term ‘all-trans RA 4-hydroxylase activity’ mapped to Rhea:51492. 

Thanks!
Nevila
