### ISSUE TITLE
"resistance gene receptor" new term, sibling of "pattern recognition receptor"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18031]
"resistance gene receptor"

child of  "innate immune receptor activity"
synonym related resistance gene

Definition
Combining with an effector entity produced by a pathogen or symbiont in order to activate "effector-triggered immunity ETI".

PMID: 21490299 
It would be OK to make the activity definition more general if necessary (we can link the activity to the process to capture this detail).

Notes/Comments:
We tried to make this generic for effector-triggered immunity
Generally these types of receptors are just called "resistance genes" which is not informative about the function.

I will address ETI/effector triggered immunity in a follow -up ticket

**Comment by ValWood** [comment]
synonyms
intracellular innate receptor activity (@CuzickA  are these always intracellular? I think they must be?)

**Comment by CuzickA** [comment]
> synonyms
intracellular innate receptor activity (@CuzickA are these always intracellular? I think they must be?)

They are not always intracellular 
R genes are often grouped  by functional domains (see below)
![image](https://user-images.githubusercontent.com/11753634/67395202-713cee80-f59d-11e9-9298-4cf5d745846a.png)

The Arabidopsis R gene RPP1 (from PMID:20601497) would fall under the NBS-LRR-TIR class which is intracellular
but eg Tomato Cf2 and Cf9 R genes consist of a transmembrane domain and extracellular LRRs

**Comment by ValWood** [comment]
OK thanks.

**Comment by CuzickA** [comment]
> "resistance gene receptor"

> child of "innate immune receptor activity"
synonym related resistance gene

> Definition
Combining with an effector entity produced by a pathogen or symbiont in order to activate "effector-triggered immunity ETI".

In some cases there is a direct interaction between the resistance gene receptor and the pathogen effector entity, and in other cases the interaction is indirect following the guard hypothesis (below). The pathogen effector entity modifies a host virulence target, this change to the host virulence target is recognised by the resistance gene and ETI triggered.

The above definition sounds like it is just covering the direct interaction. Should it be changed?

![image](https://user-images.githubusercontent.com/11753634/70039774-602ac880-15b2-11ea-8396-6f92414bc215.png)


https://en.wikipedia.org/wiki/Gene-for-gene_relationship
![image](https://user-images.githubusercontent.com/11753634/70039829-73d62f00-15b2-11ea-8006-3dddf16b69e8.png)

**Comment by ValWood** [comment]
I'm going to close this one

Now I found this term
GO:0009870    defense response signaling pathway, resistance gene-dependent

I think we should proably use
child of "innate immune receptor activity"
part of
GO:0009870    defense response signaling pathway, resistance gene-dependent

to annotate  R-genes.

I will check how other R-genes are annotated and request a narrow synonym for 

"innate immune receptor activity"

If this does not work for all our cases we can request  more specific later.

This will work for the cases where Avr interacts directly with the  receptor and I have not annotated any other cases yet.
