### ISSUE TITLE
GPI-anchor biosynthesis activities

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18108]
We don't seem to have many of these, but I assume most of the activities would be known?

I thought the MFs would be linked to GPI-anchor biosynthesis, but here I find

GO:0018265    GPI anchor biosynthetic process via N-asparaginyl-glycosylphosphatidylinositolethanolamine	is_a
GO:0018266    GPI anchor biosynthetic process via N-aspartyl-glycosylphosphatidylinositolethanolamine	is_a
GO:0018269    GPI anchor biosynthetic process via N-seryl-glycosylphosphatidylinositolethanolamine	is_a
GO:0018267    GPI anchor biosynthetic process via N-cysteinyl-glycosylphosphatidylinositolethanolamine	is_a
GO:0016254    preassembly of GPI anchor in ER membrane	part_of
GO:0018268    GPI anchor biosynthetic process via N-glycyl-glycosylphosphatidylinositolethanolamine	is_a
GO:0016255    attachment of GPI anchor to protein	part_of
GO:0050493    GPI anchor biosynthetic process via N-threonyl-glycosylphosphatidylinositolethanolamine	is_a
GO:0018270    GPI anchor biosynthetic process via N-alanyl-glycosylphosphatidylinositolethanolamine	is_a

are these really separate processes? Or do they represent activities?

**Comment by ValWood** [comment]
the only specific activity I found so far is
Pig-L/GPI12 GO:0000225	N-acetylglucosaminylphosphatidylinositol deacetylase activity

**Comment by pgaudet** [comment]
Another point: shouldn't those be children of post-translational modification, not biosynthesis?

**Comment by ValWood** [comment]
The anchor needs to be made before it is used in N-glycosylation though....That's a multi-step process. I think it's OK.

**Comment by pgaudet** [comment]
OK right.

**Comment by deustp01** [comment]
We're colliding again with process boundaries.

Mostly, when a protein undergoes covalent modification, that happens in a single step (phosphorylation, methylation). In a case like ubiqitination, additional steps are needed to get the ubiquitin "activated" so it can be transferred to the target protein, but it's not much of a stretch to say all of those steps are parts of the ubiquitination process: there aren't many, the intermediate products have other no known fate / function. (Though we don't count the steps by which S-adenosylmethionine is generated and regenerated as parts_of protein methylation.)

Here, a long, elaborate biosynthetic pathway is needed to assemble a complicated molecule that is transferred onto a target protein and then often chemically modified further in situ to generate the matured glycoprotein product. As far as I know (but this is essentially textbook knowledge and even there confined to mammalian systems), the many, many intermediates have no function except to be processed further. (I'm pretty sure, for example, that in yeasts where one of the enzymes responsible for an intermediate reaction is inactive, the immediate precursor to that reaction just accumulates). So in that sense, this is just an elaborate version of ubiquitination.

But maybe here, just because the process is so extended, even if its product has only one use - protein modification, it in entitled to a separate biosynthesis label?

**Comment by ukemi** [comment]
Most of the activities are known, but they are not linked in the ontology. For many members of the large complexes we don't know the actual molecular function of the molecules. In general, if we have enumerated subtypes using the the 'x via y' format in the ontology, it means that pathways exist that go through different intermediates. For a start, see this review: PMID:10444375. Looking at the terms mentioned above and the definitions of those terms, it looks like they are all going through a different linkage intermediate. I'm not really sure what you are asking in this ticket. I think these could be well annotated in GO-CAM models, see the straw-man models that @deustp01 and I did a few years ago. 
596a6e0600000186
596a6e0600000152
5970219a00000013
Note well that my model has a lot of genes from different species on it. It is not a true GO-CAM model. It is a development model where I took existing annotations and tried to place all of the genes onto a single framework using the ontology classes. 

I'm not exactly sure what the action is for this ticket.

**Comment by ValWood** [comment]
I was just wondering why we don't have any of the specific activities for the pathway (At least I can only locate one). If a GO cam was built they would mainly be

mannose-ethanolamine phosphotransferase activity part_of GPI anchor biosynthesis because  none of the specific  molecular functions seem to be in GO?

You can close this though. I guess they will get added eventually. I'll request them as I come across them. I was assuming they would be in Rhea and they just needed to be instantiated in GO.

**Comment by ValWood** [comment]
I checked the Noctuia models, I don't think they have this information.
Anyway for now I have the 3 above (PIL/SW and F), will add the others later.

**Comment by ukemi** [comment]
Request specific molecular functions as you come across them if they aren't already in the ontology.

**Comment by ukemi** [comment]
Can you make new tickets with the appropriate info? Term request, reference, Rhea xref...
