### ISSUE TITLE
NTR: GO term for GTP and TTP based nucleoside diphosphate kinase activity

### ISSUE THREAD

**Issue by Fahida-hub** [geneontology/go-ontology#18123]
This is for CACAO at TAMU @jimhu-tamu, @jrr-cpt, @cross12tamu

PMID: 20497505 describes a novel nucleotide kinase encoded by gene 1.7 of bacteriophage T7. Unlike the nucleotide kinase activity described by 

     GO:0047507 (deoxy)nucleoside-phosphate kinase activity

gp1.7 cannot use ATP as the phosphate donor but uses GTP, dGTP or dTTP instead.

We propose three NTRs in the molecular function aspect to allow accurate annotation of T7 gp1.7

NTR1:  create a sibling of  GO:0047507 to encompass ATP-independent (deoxy) nucleoside-phosphate kinase activity defined as catalyzing the reaction NTP + (deoxy)nucleoside phosphate = NDP +( deoxy)nucleoside diphosphate, where the NTP is not ATP or dATP. Alternatively, the IUPAC B code could be used with BTP and BDP to represent not A. 

Like GO:0047507, the new term would be an is_a child of GO:0016776 phosphotransferase activity, phosphate group as acceptor, and have a part_of relationship with GO:0006165 nucleoside diphosphate phosphorylation.

NTR2: create a child of the new term specifying one substrate. ATP-independent dGMP kinase activity.

NTR3 create a child of the new term specifying the other substrate. ATP-independent dTMP kinase activity.

**Comment by jimhu-tamu** [comment]
Anything new on this? If it could be resolved by next week that would help us for grading CACAO

**Comment by hdrabkin** [comment]
checking out RHEA use

**Comment by hdrabkin** [comment]
Since GO:0047507 is associated with EC:2.7.4.13 and RHEA:11216, which are ATP specific (RHEA def :a 2'-deoxyribonucleoside 5'-phosphate + ATP = a 2'-deoxyribonucleoside 5'-diphosphate + ADP), i'm inclined to make a sib of this rection with a proposed def of 
"a 2'-deoxyribonucleoside 5'-phosphate +GTP = a 2'-deoxyribonucleoside 5'-diphosphate + GDP" calling it GTP specific deoxy)nucleoside-phosphate kinase activity, and change the name of the  GO:0047507  to  ATP specific deoxynucleoside-phosphate kinase activity, 
RHEA will want ot create a separate reaction for GTP, dGTP, and dTTP I think

**Comment by hdrabkin** [comment]
RHEA has created separate reactions for the three; they did not want to specify anything using "BTP, etc. "

**Comment by hdrabkin** [comment]
RHEA has created 3 reactions, one for each of the best 3 NTPs used.
RHEA:62124
a 2'-deoxyribonucleoside 5'-phosphate + GTP = a 2'-deoxyribonucleoside
5'-diphosphate + GDP
RHEA:62128
a 2'-deoxyribonucleoside 5'-phosphate + dGTP = a 2'-deoxyribonucleoside
5'-diphosphate + dGDP
RHEA:62132
a 2'-deoxyribonucleoside 5'-phosphate + dTTP = a 2'-deoxyribonucleoside
5'-diphosphate + dTDP
They will be publicly available in the January 2020 Rhea release.

**Comment by hdrabkin** [comment]
@Fahida-hub 
These RHEAs are still not available publically so I cannot create the GO terms yet.

**Comment by hdrabkin** [comment]
@amorgat , do you know why these are public yet? I thought they were in the Jan release?

**Comment by amorgat** [comment]
@hdrabkin Rhea releases are synchronized with UniProt releases.
Since January 2020, UniProt is released every 2 months.
RHEA:62124, RHEA:62128 and RHEA:62132 will be publicly available the April 22th (same as UniProt 2020_02 release).
Sorry for this long delay...
Hope you're doing well. Take good care.

**Comment by hdrabkin** [comment]
+id: GO:0106367
+name: dGTP dependent (deoxy)nucleoside -phosphate kinase activity
RHEA:62128

+[Term]
+id: GO:0106368
+name: dTTP dependent (deoxy)nucleoside - phosphate kinase activity
RHEA:62132

+[Term]
+id: GO:0106369
+name: GTP dependent (deoxy)nucleoside -phosphate kinase activity
RHEA:62124

**Comment by pgaudet** [comment]
Would it not be more clear if the label was "(deoxy)nucleoside -phosphate kinase activity, dGTP as phosphate donor", etc ? 
In other places the 'x-dependent' phrase can be quite ambiguous.

**Comment by hdrabkin** [comment]
Sure; I was patterning them after another term I saw (can't remember) but I can change names easy.
