### ISSUE TITLE
difficult to describe MF: microtubule sliding brake

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18152]
I want to describe the activity of acting as a brake to microtubule sliding.
The mechanism is like this:

![sliding](https://user-images.githubusercontent.com/7359272/68675855-aad79880-0550-11ea-9990-1d0cf2b9c556.jpg)

As overlapping microtubules
start to slide apart, Ase1 molecules become compacted in the
shrinking overlap and the sliding velocity gradually decreases in
a dose-dependent manner. Compaction is driven by moving
microtubule ends that act as barriers to Ase1 diffusion.

any suggestions?

I can't see anything suitable under
https://www.ebi.ac.uk/QuickGO/term/GO:0003674

**Comment by ukemi** [comment]
microtubule lateral binding
negatively_regulates 'plus end directed microtubule sliding'? I think the direction is correct.
'regulation of microtubule-based movement'

**Comment by ValWood** [comment]
OK I wondered if to do that, but I thought that we wanted to have "non-binding" only molecular functions if we knew more about the mechanism than "microtubule binding"?
@pgaudet was that correct?

Anyway I can do it like this for now.

So in this case are we no longer using  "positive" and "negative" regulation of process terms?
I would like to be consistent with what we have done previously and request

'negative regulation of plus end directed microtubule sliding'

If we are using "negatively_regulates" to link functions to processes rather than have "regulation" process terms  we should  do it across all the annotation consistently?

**Comment by ukemi** [comment]
I think adding the negative regulation term would be ok if it is still within scope. I didn't list it because we didn't have it. That's why I made the GO-CAMesque expression in the second line. With respect to the binding function, I thought about the desire not to use them and the only other thing I could think of was the 'protein binding, bridging term' and then having an input of a tubulin or microtubule. It's not inhibiting the kinesin and it's not really cross-linking. It's just kind of getting in the way. That's why I went with lateral binding.

**Comment by ukemi** [comment]
Do you want me to add ''negative regulation of plus end directed microtubule sliding'?

**Comment by ValWood** [comment]
Yes I don't think there is any obvious way to describe this activity. I will do as you suggest, yes please can I have

negative regulation of plus-end directed microtubule sliding

**Comment by ukemi** [comment]
It is plus-end right, because the kinesin moves to the minus end?

**Comment by ukemi** [comment]
Do you have a PMID?

**Comment by ValWood** [comment]
PMID:21892183

yes the sliding is plus-end directed.
