### ISSUE TITLE
NTR: brexanolone biosynthetic process

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/go-ontology#18193]
Hello again :-)

Could I please have
GO:NEW brexanolone biosynthetic process
is_a 
with standard definition and synonyms
where synonyms include the exact one "allopregnanolone biosynthetic process"
brexanolone is CHEBI:50169 (the Wikipedia quotation in the CHEBI entry states that allopregnanolone is a synonym)
PMID:24390875
The CHEBI entry summary says that the chemical is a metabolite of the sex hormone progesterone, so the metabolism and catabolism terms would be in scope, too.

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Sorry, I left that blank earlier:
is_a GO:0006694 steroid biosynthetic process

**Comment by ukemi** [comment]
HI @paolaroncaglia. There is no need to specify the is_a parent because as long as you provide a ChEBI identifier for the primary input or output the term will be classified according to the ChEBI classification. That said, we have found classification by role to be problematic and so the only classification I can guarantee will be stable is the chemical one. If you want a role classification to be asserted, we can do that.

Pinging @krchristie because she is the one working with the roles issue.

**Comment by paolaroncaglia** [comment]
Hi @ukemi (and @krchristie),
Thanks for your feedback and for adding the terms. No need for a role classification, all is well as is.
Paola
