### ISSUE TITLE
GO:0000753    cell morphogenesis involved in conjugation with cellular fusion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18277]
GO:0000753    cell morphogenesis involved in conjugation with cellular fusion

is shmooing? (currently narrow synonym)

I can't think of any other "morphogenesis" process involved in conjugation with cellular fusion?

There is a single child term
GO:0031382    mating projection assembly
but the mating projection does not asselmlb , it forms as  a projection.

therefore "mating proijection formation" would be qa better term.

Perhaps all 3 can merge @Antonialock ? do you agree.

Primary term name
"mating projection formation"?

**Comment by ukemi** [comment]
What about in paramecium?

**Comment by ValWood** [comment]
Well....

GO:0031382 mating projection assembly
is a child of
GO:0000753 cell morphogenesis involved in conjugation with cellular fusion

does "conjugation with cellular fusion"
apply to paramecium

(I was assuming this was a fungal term but perhaps not?)

**Comment by ukemi** [comment]
I think there is a cellular fusion, at least partial, when ciliates conjugate.

**Comment by ValWood** [comment]
Ah right has

Only in Taxon | 4751, 5782 | Fungi or Dictyostelium

so  the parent is probably appropriate.

Instead
1. rename  GO:0031382 mating projection assembly to "mating projection formation"
2. Move  " shmooing" to  be narrow  for GO:0031382

**Comment by ukemi** [comment]
Do you really want to do this and still keep the logical definition as it is or do you want to completely redefine and reclassify it? Right now it is defined as a 'cellular component assembly' that results_in_assembly of some 'mating projection'.
You will lose it's classification to terms that seem appropriate: 'cellular component assembly involved in morphogenesis', 'plasma membrane bounded cell projection assembly'. 

ping @mah11 since she authored this term.

**Comment by ukemi** [comment]
[Term]
id: GO:0031382
name: mating projection assembly
namespace: biological_process
def: "The aggregation, arrangement and bonding together of a set of components to form a cell projection in response to mating pheromone. This process is observed in unicellular fungi." [GOC:mah, PMID:14734532]
synonym: "mating projection biogenesis" RELATED [GOC:mah]
intersection_of: GO:0022607 ! cellular component assembly
intersection_of: results_in_assembly_of GO:0005937 ! mating projection
relationship: part_of GO:0000753 ! cell morphogenesis involved in conjugation with cellular fusion

**Comment by ValWood** [comment]
GO:0120031    JSON
plasma membrane bounded cell projection assembly
Biological Process
Definition (GO:0120031 GONUTS page)
Formation of a prolongation or process extending and that is bounded by plasma membrane, e.g. a cilium,

Seems to be used mainly for cilia. Maybe cilia "assemble" but the definition here seems odd too, because the definition says "formation" not "aggregation, arrangement and bonding"?

@krchristie  do cilia "assemble" or "form"

**Comment by krchristie** [comment]
> GO:0120031 JSON
> plasma membrane bounded cell projection assembly
> Biological Process
> Definition (GO:0120031 GONUTS page)
> Formation of a prolongation or process extending and that is bounded by plasma membrane, e.g. a cilium,

Full def is actually: Formation of a prolongation or process extending and that is bounded by plasma membrane, e.g. a cilium, lamellipodium, or axon.
 
> Seems to be used mainly for cilia. Maybe cilia "assemble" but the definition here seems odd too, because the definition says "formation" not "aggregation, arrangement and bonding"?

This term is a grouping term for quite a number of things, NOT just cilia. A variety of cell projections in mammalian cells, including axons, dendrites, lamellipodia, microvilli, membrane ruffles, and more are grouped here. It was created in order to be able to make some logical distinctions between membrane-bounded cellular projections (like the ones listed above) and non-membrane bounded cellular projections, e.g. bacterial flagella, bacterial conjugation pilli.

> @krchristie do cilia "assemble" or "form"

People talk about "cilium assembly" all the time. "Ciliogenesis" is also popular. "Cilium formation" is listed as an exact synonym of the term `cilium assembly`, though in my recollection, this is not as commonly used as either "cilium assembly" or "ciliogenesis".

I'm not sure that there's really a good way to distinguish "assembly" from "formation" of these large structures. It seems that both words are used relatively interchangeably. Personally, I'm definitely in favor of adding `mating projection assembly` as a synonym, not convinced it's really necessary to make it the primary term name.

Regarding ciliate conjugation, here's a relevant quote from Wikipedia (https://en.wikipedia.org/wiki/Ciliate#Reproduction):

> In some ciliates (peritrichs, chonotrichs and some suctorians), conjugating cells become permanently fused, and one conjugant is absorbed by the other.[12][17] In most ciliate groups, however, the cells separate after conjugation, and both form new macronuclei from their micronuclei.[8]

I'm a little hesitant about the idea of merging these two terms. 
- GO:0000753 cell morphogenesis involved in conjugation with cellular fusion
- GO:0031382 mating projection assembly
Partly, I think we should be really sure that the term `mating projection assembly/formation` will be appropriate for all the ciliates for which this is appropriate. In addition, the first term `cell morphogenesis involved in conjugation with cellular fusion` seems like it could be broader than just the `mating projection assembly` part.


I do agree that the narrow synonym `shmooing`, seems like it would be more appropriate attached to the `mating projection assembly` term.

**Comment by mah11** [comment]
> ping @mah11 since she authored this term.

ha ha, I haven't thought about this area for ages ... but I find myself in full agreement with @krchristie, especially this bit:

>  I'm not sure that there's really a good way to distinguish "assembly" from "formation" of these large structures. It seems that both words are used relatively interchangeably.

**Comment by ValWood** [comment]
Ah right. I always thought formation and assembly had different logical definitions...

It seems we can just add the formation synonym  (but to me "formation' seems a bit broader than "assembly" and a better fit for processes which are partly remodelling of existing structures like cell wall).

**Comment by ukemi** [comment]
They do, but we try to reserve formation for gross anatomical structures. I will add the synonym. Doesn't shmooing require cytoskeletal changes too?

**Comment by ValWood** [comment]
It does, but that also uses microtubules which are already present in pombe. Probably it's all fine. It just seems that formation fits better, but Karen says for cilia assembly is more commonly used.

**Comment by ukemi** [comment]
I will change the name, add the current name as a synonym and add shmooing as a synonym. @mah11 it may have been a while since you thought about this, but I am certain that when you did it was well thought out!
