### ISSUE TITLE
cytoskeleton/nuclear membrane localization -MF (anchoring)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18283]
GO:0090286   
cytoskeletal anchoring at nuclear membrane
Definition The process in which cytoskeletal filaments are directly or indirectly linked to the nuclear membrane.

has 5 experimental annotations from the same paper:

PMID:18396275
SUN1&2 and SYN1-3

These are KASH and SUN domain containing proteins and  are the same proteins that anchor the SPB (a cytoskeleton component, and other microtubule organizing  centres microtubule organising )  in the nuclear membrane

So this is the same "activity" used in very similar processes described in totally different ways:

<img width="690" alt="Screenshot 2019-11-27 at 13 57 24" src="https://user-images.githubusercontent.com/7359272/69729784-d5b01800-111e-11ea-8d94-866de6840c3f.png">

~Part of the problem is describing 
"cytoskeleton anchoring at the nuclear membrane" as "protein  and macromolecule localization. This should really be "organelle localization" with maybe "cytoskeleton localization" as a descendent.
(and removing the cytoskeleton organization" parent.?)~
I think we just dealt with this? If not we have a solution in the other membrane  anchor term (make it clearer that the anchored object can be an organelle)

**Comment by ValWood** [comment]
<img width="600" alt="Screenshot 2019-11-27 at 14 10 40" src="https://user-images.githubusercontent.com/7359272/69730321-bbc30500-111f-11ea-8135-9106533af287.png">

**Comment by ValWood** [comment]
solution
obsolete  GO:0071789   spindle pole body localization to nuclear envelope
This is a molecular function
term and  create new MF term

a descendant of GO:0106006   cytoskeletal protein-membrane adaptor activity

NEW1  cytoskeleton-nuclear membrane adaptor activity

NEW2  MTOC - nuclear membrane adaptor activity (anchor would be better here, more common language?)
NEW3 narrow SPB- nuclear membrane anchor activity (add parent to BP spindle pole body localization)
NEW4   centrosome-nuclear membrane anchor activity

**Comment by pgaudet** [comment]
- [] Create new MF term to replace BP: cytoskeleton-nuclear membrane anchor activity
+ add synonym cytoskeletal protein-nuclear membrane anchor activity
cytoskeletal protein-nuclear membrane adaptor activity

**Comment by pgaudet** [comment]
Reference PMID: 16237665

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140444
+name: cytoskeleton-nuclear membrane anchor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together a cytoskeletal protein or protein complex and a nuclear membrane lipid or membrane-associated protein, in order to maintain the localization of the cytoskeleton at a specific location of the plasma membrane." [PMID:16237665]
+synonym: "cytoskeletal protein-nuclear membrane adaptor activity" EXACT []
+synonym: "cytoskeletal protein-nuclear membrane anchor activity" EXACT []
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/18283 xsd:anyURI
+created_by: pg
+creation_date: 2020-03-24T14:57:59Z
