### ISSUE TITLE
Fix logical definition aflatoxin biosynthetic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18292]
Working on improving the secondary metabolites biosynthesis pathways, @marcfeuermann proposes to add these reactions to the logical definition of 'aflatoxin biosynthetic process':
is_a: GO:0043386 ! mycotoxin biosynthetic process
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: ends_with GO:0140399 ! aflatoxin B synthase activity
intersection_of: has_part GO:0016491 ! oxidoreductase activity
intersection_of: has_part GO:0042469 ! versicolorin reductase activity
intersection_of: has_part GO:0046572 ! versicolorin B synthase activity
intersection_of: has_part GO:0047145 ! demethylsterigmatocystin 6-O-methyltransferase activity
intersection_of: has_part GO:0047146 ! sterigmatocystin 7-O-methyltransferase activity
intersection_of: has_part GO:0102973 ! norsolorinate anthrone synthase activity
intersection_of: has_part GO:0140393 ! norsolorinic acid ketoreductase activity
intersection_of: has_part GO:0140395 ! averantin hydroxylase activity
intersection_of: has_part GO:0140396 ! 5'-hydroxyaverantin dehydrogenase activity
intersection_of: has_part GO:0140397 ! versiconal hemiacetal acetate esterase activity
intersection_of: has_part GO:0140398 ! versicolorin B desaturase activity
intersection_of: has_primary_input CHEBI:30089 ! acetate
intersection_of: has_primary_output CHEBI:22271 ! aflatoxin
intersection_of: has_primary_output CHEBI:22271 ! aflatoxin
intersection_of: starts_with GO:0004321 ! fatty-acyl-CoA synthase activity

+ create new terms to represent individual reactions (recently added in Rhea): 

+[Term]
+id: GO:0140393
+name: norsolorinic acid ketoreductase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: (1'S)-averantin + NADP(+) <=> norsolorinic acid + NADPH." [PMID:10584035, PMID:8368836, RHEA:35447]
+xref: EC:1.1.1.349
+xref: KEGG_REACTION:R10309
+xref: MetaCyc:RXN-9480
+xref: RHEA:35447
+is_a: GO:0045703 ! ketoreductase activity
+created_by: pg
+creation_date: 2019-11-28T14:38:12Z

[Term]
id: GO:0140395
name: averantin hydroxylase activity
namespace: molecular_function
def: "Catalyzes the reaction: (1'S)-averantin + [reduced NADPH--hemoprotein reductase] + O(2) <=> (1'S,5'S)-5'-hydroxyaverantin + [oxidized NADPH--hemoprotein reductase] + H(2)O. Involved in aflatoxin biosynthesis." [EC:1.14.14.116, PMID:8368836]
xref: EC:1.14.14.116
xref: MetaCyc:RXN-9482
xref: RHEA:35575
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
relationship: part_of GO:0045122 ! aflatoxin biosynthetic process
created_by: pg
creation_date: 2019-11-29T08:48:23Z

[Term]
id: GO:0140396
name: 5'-hydroxyaverantin dehydrogenase activity
namespace: molecular_function
def: "Catalyzes the reaction: (1'S,5'S)-hydroxyaverantin + NAD(+) <=> 5'-oxoaverantin + NADH." [EC:1.1.1.352, PMID:14602595]
xref: EC:1.1.1.352
xref: RHEA:35475
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
created_by: pg
creation_date: 2019-11-29T08:56:49Z

[Term]
id: GO:0140397
name: versiconal hemiacetal acetate esterase activity
namespace: molecular_function
def: "Catalyzes the reactions: versiconal hemiacetal acetate + H(2)O <=> versiconal + acetate, as well as versiconol acetate + H(2)O <=> versiconol + acetate." [EC:3.1.1.94, PMID:15006741, PMID:15932995, PMID:8368837]
xref: EC:3.1.1.94
xref: MetaCyc:RXN-9488
xref: MetaCyc:RXN-9493
xref: RHEA:35715
is_a: GO:0016788 ! hydrolase activity, acting on ester bonds
created_by: pg
creation_date: 2019-11-29T10:14:17Z

[Term]
id: GO:0140398
name: versicolorin B desaturase activity
namespace: molecular_function
def: "Catalyzes the reaction: versicolorin B + NADPH + O(2) <=> versicolorin A + NADP(+) + 2 H(2)O. Uses heme-thiolate as a co-factor. Involved in the synthesis of aflatoxins in the fungus Aspergillus parasiticus." [PMID:15006741, PMID:8368837]
xref: KEGG_REACTION:R10479
xref: MetaCyc:RXN-9495
xref: RHEA:35743
is_a: GO:0016717 ! oxidoreductase activity, acting on paired donors, with oxidation of a pair of donors resulting in the reduction of molecular oxygen to two molecules of water
created_by: pg
creation_date: 2019-11-29T10:30:25Z

[Term]
id: GO:0140399
name: aflatoxin B synthase activity
namespace: molecular_function
def: "Catalyzes the reaction: 8-O-methylsterigmatocystin + 2 [reduced NADPH--hemoprotein reductase] + 2 O(2) <=> aflatoxin B + 2 [oxidized NADPH--hemoprotein reductase] + H(2)O + methanol + CO(2). Produces both aflatoxin B(1) and aflatoxin B(2)." [EC:1.14.14.117]
xref: EC:1.14.14.117
xref: MetaCyc:RXN-9497
xref: MetaCyc:RXN-9502
xref: RHEA:35759
is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
relationship: part_of GO:0045122 ! aflatoxin biosynthetic process
created_by: pg
creation_date: 2019-11-29T11:06:07Z

**Comment by cmungall** [comment]
I think we should stick to DPs add other relationships as N conditions not
N+S

**Comment by pgaudet** [comment]
@cmungall I dont know what you mean. 

Do I need to change anything ?

**Comment by cmungall** [comment]
the logical definition is overstated. You will never get inferences under this!

**Comment by pgaudet** [comment]
So I should only add what is 'necessary and sufficient' and add the rest as subclasses ?

**Comment by cmungall** [comment]
Yep! Sorry, I have a bit more time to explain now.

First I was expecting to see a biosynthesis.yaml among out DPs, I see a biosynthesis-from but not a plain biosynthesis. We should really be using these DPs more to have more consistency of logical defs!

The general pattern for "X biosynthesis" is: EquivalentTo biosynthesis and has-output some X. 

This holds for *any* biosynthetic process that outputs X.

Now if we are sure that all cases of X biosynthesis have some particular property, e.g. step A1, we can add an additional axiom "subClassOf has_part some A1"

This is called a "hidden GCI" (I think our tutorial covers this I need to check)

These are very powerful, they act as rules: IF a process outputs X THEN it must have step A1

In my opinion, these are quite dangerous to add for generic "X biosynthesis" terms, as there could be many separate pathways for making X. I would tend to only add these for "pathway-level" processes rather than "grouping-level" processes. I think we often conflate these in GO!

If the pathway is highly variable then there is a potential argument for only including a grouping classes, and doing specific pathways as GO-CAMs. However, I think there is a good argument for doing species-generic specific pathways in the ontology, with conserved steps that can be reused in the GO-CAM.

For this particular process (aflatoxin biosynthesis) I would be wary of hidden GCIs, as there are different subtypes of aflatoxin and these may have different mechanisms to make them.

Here are some different types in metacyc:

https://biocyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-5959
https://biocyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-5960

It may be the case that @marcfeuermann's proposed axioms are for the metacyc superpathway:

https://biocyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-5961

But I'm not sure that GO should represent these combined super-pathways; if we treat this literally it's one process outputting all the different types of afflatoxin!

Btw, This metacyc page has a nice description of species variability. Incidentally, I think we should be xreffing metacyc especially for non-human metabolic pathways

I think there is a lot to discuss here about our future strategy for metabolic processes, I think we will eventually want a project analogous to the Rhea and Reactome ones for non-human metabolic processes.

For now:

 - follow DPs, and make the sufficient conditions as lax as possible but no laxer
 - add additional necessary conditions as `subClassOf R some T` (hidden GCIs), but do this carefully and test with reasoner
 - in general for metabolic processes, the grouping class should have no hidden GCIs (unless evolution really only has hit on a single way of metabolizing the chemical in question), and the more specific criteria should be pushed down to a named pathway subclass
 - make use of databases like metacyc when defining metabolic pathways

**Comment by pgaudet** [comment]
Thanks @cmungall 
1. Can you link to the appropriate DP ? So I follow it. 
2.  @marcfeuermann and I discussed the different products made in this - if you look at the enzymes catalyzing the reactions, they are the same. So the same pathway generates slightly different molecules. They include the exact same reactions. 
3. I am surprised that we want to have 'generic "X biosynthesis" terms, as there could be many separate pathways for making X. '. This is not what we were trying to do - we were trying to  describe a specific pathway; is this not what we want to do in GO?  I hought one of one long-standing aims was to add 'start and ends' of BPs and pathways - to me the best way to be sure that you are annotating the correct pathway is to have all the reactions and check if the pathway you are looking at is the same. I can add the reaction as subclasses, but it would be too bad if this information did not belong in GO. 

Should we discuss at the next Ontology call ?

**Comment by cmungall** [comment]
1. I can't because it's not there, we forgot to make a yaml for it. But it should be obvious what it is, X biosynthesis = biosynthesis and has_primary_output X
2. if you are confident that all variants of all aflatoxin generating processes utilize these reactions then include as hidden GCIs, but I am skeptical. "if you look at the enzymes catalyzing the reactions, they are the same." -- not following, same as what?
3. As I said, we often conflate a generic grouping class with a pathway in GO, we should not do that. I would say that it is fairly common to have more than one way to make X. In these cases we make a generic grouping class for making X (whose definition is simply making X), and then subclasses for pathway-level processes that are defined in terms of their steps. It's not clear the exact level of generality of these pathway-level ones

**Comment by ukemi** [comment]
Has-primary_output

**Comment by pgaudet** [comment]
Decision on today's call: 
1. The equivalence axiom should be the 'minimal' necessary and sufficient' statement: 
'biosynthetic process' 
and has_primary_output some aflatoxin
2. All other statements should go under subclasses using the relation 'has_part' 
3. Update Ontology documentation to describe this.

**Comment by pgaudet** [comment]
Hi @cmungall @ukemi 
I have now changed the LD to this: 

'biosynthetic process'
 and ('has primary output' some aflatoxin)
 and ('has primary input' some acetate)
and ('starts with' some 'fatty-acyl-CoA synthase activity')

and added all other reactions as subclasses. Is this OK ? 
(I notice we have some 'start with' and 'end with' in LDs for other terms). 

Thanks, Pascale

**Comment by pgaudet** [comment]
I also removed 'aflatoxin B synthase activity' as this one is specifically required for aflatoxin B1 and B2, but not G1 and G2. 

@marcfeuermann

**Comment by cmungall** [comment]
To conform to the DP just

'biosynthetic process'
and ('has primary output' some aflatoxin)

the rest are N conditions

**Comment by pgaudet** [comment]
h

**Comment by pgaudet** [comment]
Then to be consistent I should remove these statements from other LDs? 


For eg: 
GO:1990181 acetyl-CoA biosynthetic process from pantothenate
'biosynthetic process' 
and ('has primary output' some acetyl-CoA) 
and ('has primary input' some pantothenate) -> move to subclass? 

---

GO:0061732 mitochondrial acetyl-CoA biosynthetic process from pyruvate
('starts with' some 'mitochondrial pyruvate transmembrane transport') 
and ('ends with' some 'pyruvate dehydrogenase [NAD(P)+] activity')
-> This one seems to be missing the genera ? 


I am interpreting correctly that for 'biosynthetic process' 'starts with' and 'ends with' should never be in the LD ? 


Thanks, Pascale

**Comment by cmungall** [comment]
No - try it in Protege and see what happens

we use a more specific pattern for these.

 1. X biosynthesis: biosynthesis and has-primary-output X
 2. X biosynthesis from Y: biosynthesis and has-primary-output X and
has-primary-input Y

Note that if you dropped the Y clause from definition 2 then 1 and 2 would
be inferred to be equivalent!

**Comment by pgaudet** [comment]
OK thanks. What about 
GO:0061732 mitochondrial acetyl-CoA biosynthetic process from pyruvate
('starts with' some 'mitochondrial pyruvate transmembrane transport')
and ('ends with' some 'pyruvate dehydrogenase [NAD(P)+] activity')
?

**Comment by cmungall** [comment]
good catch, oh this one is totally messed up, it's missing a genus!!! I
thought we had a missing genus check but we don't!!!

Anyway this one should follow

 = biosynthesis and h-p-o some OUT and h-p-i some IN
 subClassOf starts-with S-activity
 subClassOf ends-with E-activity

Bearing in mind hidden GCIs are strong. We are saying there is no other way
to make OUT from IN *without* S and E activities.

**Comment by pgaudet** [comment]
OK - so can we have 'starts with' (and ends with) some BP ? or should it be a MF ?

**Comment by deustp01** [comment]
Jumping in from another (GO-CAM) discussion, I think we concluded that preceding and following relationships, when the time comes to make them, should be at the function rather than the process level so (if I'm remembering right), that might be a reason to want start and end points likewise to  be defined at the function rather than the process level.

**Comment by cmungall** [comment]
Nothing inherently wrong about using a BP (and if the BP used is already stated to start-with an MF the inference propagates). But easier to insist on an MF if it is known, which is should be for a pathway?

**Comment by ukemi** [comment]
Sometimes it is not known or could be more complex, for example in the case of a branched pathway where two initial branches converge onto the main pathway. In this case, we might want to start with a process. ?????

**Comment by pgaudet** [comment]
Right. I find this one odd that it starts with 'transport: 
GO:0061732 mitochondrial acetyl-CoA biosynthetic process from pyruvate
('starts with' some 'mitochondrial pyruvate transmembrane transport')
and ('ends with' some 'pyruvate dehydrogenase [NAD(P)+] activity')

If that's the case then guidelines for any 'organellar' biosynthetic process should start with import of the first metabolite, when it needs to be imported? I would personally have started the biosynthetic process from the first enzymatic reaction of the pathway. 

Either way works - I would just like to document the decision. 

Thanks, Pascale

**Comment by deustp01** [comment]
Or with two functions connected by an OR (if that's legal) to indicate explicitly that both branches of the upstream process can feed the downstream one and distinguish that case from the one (can't think of an example immediately) where only one branch feeds.

**Comment by pgaudet** [comment]
Also, from the January go-ontology jamboree, we decided to remove ' ('starts with' some 'fatty-acyl-CoA synthase activity')

So that the pattern for 'biosynthetic process' is 
'biosynthetic process'
 and ('has primary output' some x)

Thanks, Pascale
