### ISSUE TITLE
More changes to response to host immune response

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18357]
-  [x] * Move 'GO:0020033 antigenic variation' under ~'response to host immune response'~

-  [x]  GO:0019049 evasion or tolerance of host defenses by virus -> rename 'evasion of host defenses by virus '
- [x]  untangle suppression and evasion (and see what's left)
* try to remove the 'mitigation' terms and classify as with 'evasion' or 'suppression' 
(will open a new ticket for this one)

**Comment by pgaudet** [comment]
need to do this with @ValWood 

See also annotation review: https://docs.google.com/spreadsheets/d/11R0XDvmmJZAW8jmM64mz1Xnx3abzwOr6inkgtb3o_Co/edit#gid=0

**Comment by pgaudet** [comment]
*  Move 'GO:0020033 antigenic variation' under 'response to host immune response' -> done in #17894

**Comment by pgaudet** [comment]
- [x] change label mitigation of host defenses by symbiont -> evasion 
- [x]  add antigenic variation under evasion of host defenses by symbiont

**Comment by pgaudet** [comment]
GO:0030683 mitigation of host immune response by virus -> change label to 'evasion of host immune response by virus (consistent with 4 manual annotations and SP-KW mappings)

**Comment by pgaudet** [comment]
We now want to remove 'mitigation', try to change to 'suppresssion' or 'evasion'

**Comment by pgaudet** [comment]
There are 3 SP-KW mappings to GO:0030683 GO:mitigation of host immune response by virus

* UniProtKB-KW:KW-0922 Interferon antiviral system evasion 
* UniProtKB-KW:KW-1125 Evasion of host immunity by viral interleukin-like protein
* UniProtKB-KW:KW-0899 Viral immunoevasion

@pmasson55 Can these be mapped to either 'evasion' or 'suppression'? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Working with @ValWood on this one: 
The issue is that there are both 'evasion' and 'suppression' terms under 'mitigation'. Many annotations seem problematic. We need to review annotations before deciding what terms label to chose (evasion/suppression) and whether we need new grouping terms. 

Pascale

**Comment by pgaudet** [comment]
GO:0020012 mitigation of host immune response propose to obsolete, see #18570

**Comment by pmasson55** [comment]
Concerning viral immunoevasion i guess it should go to evasion.
For the Interferon antiviral system evasion, I would put it in suppression because viral proteins counteracts and suppress the antiviral response.
For the third one,  "Evasion of host immunity by viral interleukin-like protein", it s tricky because there are both evasion and suppression. Evasion is for example down-modulation of  MHC class I expression (degradation or mislocalization) or interference with the antigen binding/presentation process. However the system is not shut-off, so I guess it could go to evasion...
Hope this helps
