### ISSUE TITLE
GO:0005091    guanyl-nucleotide exchange factor adaptor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18409]
GO:0005091    guanyl-nucleotide exchange factor **adaptor** activity

was created in 2008 but has zero annotations.  Is there another term with the same meaning?
Do we have an example of this activity? or a reference?

If it exists, is it correctly positioned under GTPase regulator? That seems incorrect.

**Comment by ValWood** [comment]
2001 even, apparently

**Comment by ukemi** [comment]
PMID:7512734
PMID:31358736

**Comment by ValWood** [comment]
PMID:31358736
SPIN90, an adaptor protein, alters the proximity between Rab5 and Gapex5 and facilitates Rab5 activation during EGF endocytosis
Kim H. Exp Mol Med. 2019
now called
NCK-interacting protein with SH3 domain
NCKIPSD

dip1 is pombe ortholog in endocytosis

**Comment by ValWood** [comment]
not sure about  PMID:7512734, that one seems to be an GTPase exchange factor   (although it is probably also an adaptor for something through its SH3 domain), its is a TRAPP subunit and TRAPP is a vesicle tethering complex.

**Comment by ukemi** [comment]
I was just having a quick look for some validation of the term. The second reference seems to do it. That's why now we have the requirement for a PMID. At least you can trace the provenance of a term to a paper.

**Comment by pgaudet** [comment]
Clearly GEFs do have adaptors: https://en.wikipedia.org/wiki/Guanine_nucleotide_exchange_factor

An example is https://en.wikipedia.org/wiki/GRB2  (P62993) which is annotated to 'SH3/SH2 adaptor activity', which has 30 EXP in QuickGO. 

Should I merge ? Although it seems more informative to talk about which proteins an adaptor connects, rather than through which domain. That would be more consistent with other siblings: 

'JAK pathway signal transduction adaptor activity'
'MAP-kinase scaffold activity'
'receptor signaling complex adaptor activity'
'GKAP/Homer scaffold activity'
'transmembrane receptor protein tyrosine kinase adaptor activity'


Pascale

**Comment by ValWood** [comment]
I did not know  'SH3/SH2 adaptor activity', existed.

I agree adaptors should not be described based on family. Usually the aren't but they are synonyms of some adaptors. For example BAR domain adaptor is a synonym of 
cytoskeletal protein membrane adaptor (GO:0140362)

SH2/SH3 domains are also usually  "cytoskeletal adaptors"
I

**Comment by ValWood** [comment]
I would keep the existing term, (not sure it should be classed as a regulator, but is probably OK).

**Comment by pgaudet** [comment]
Which term would you keep ? 

I would like to obsolete 'SH2/SH3 domain adaptor' and annotate to something more meaningful biologically.

**Comment by ValWood** [comment]
Keep
GO:0005091 guanyl-nucleotide exchange factor adaptor activity


I agree   'SH2/SH3 domain adaptor'  should be obsoleted...

**Comment by ValWood** [comment]
I think this one can close?

**Comment by ValWood** [comment]
Will open a new ticket for 
SH2/SH3 domain adaptor if you want one?

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0005070 SH3/SH2 adaptor activity. The reason for obsoletion is that molecular adaptors should be represented by the type of molecules they serve to adapt, and not their domains. Right now they represent gene products rather than activities. 

There are 29 manual annotations to this term and 12 InterPro mappings. Please review your annotations in this ticket: 
https://github.com/geneontology/go-annotation/issues/2871


Group | Number of annotations
-- | --
BHF-UCL | 7
HGNC-UCL | 1
FlyBase | 5
MGI | 5
UniProt | 9
CAFA | 2
InterPro | 12

This term in not in any subset. 

You can add any comments to the ticket: 
https://github.com/geneontology/go-ontology/issues/18409

We are opening a comment period for this proposed obsoletion. Since there are some annotations we’d like to propose to obsolete this term on March 31st, 2020. Unless objections are received by March 31st, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@RLovering @hdrabkin Would you object to obsoleting GO:0030160 GKAP/Homer scaffold activity ? It seems like it's describing a gene product/complex. 

Thanks, Pascale

**Comment by pgaudet** [comment]
> GO:0030160 GKAP/Homer scaffold activity 

Could probably be annotated as 'cytoskeletal protein-membrane adaptor activity' The binding activity of a molecule that brings together a cytoskeletal protein or protein complex and a plasma membrane lipid or membrane-associated protein, in order to maintain the localization of the cytoskeleton at a specific cortical membrane location.

What do you think ? 


![image](https://user-images.githubusercontent.com/4782928/77428721-d90b9580-6dd8-11ea-83bf-28edb2e36a2b.png)

**Comment by pgaudet** [comment]
Next changes proposed: 

- [] GKAP/Homer scaffold activity -> either merge into 'receptor signaling complex adaptor activity' , or change label to 'synaptic receptor adaptor activity' 
- [] Change label: 'receptor signaling complex adaptor activity' -> signaling receptor complex adaptor activity
