### ISSUE TITLE
difference contractile ring positioning and site selection

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18453]
cytokinesis, site selection (GO:0007105)
Definition
The process of marking the place where cytokinesis will occur.

seems that is should  be a descendant of

Definition | Parents
The process in which a contractile ring is assembled and/or maintained in a specific location.

**Comment by pgaudet** [comment]
@ValWood 
I think you meant the parent should be 'GO:0032187 actomyosin contractile ring localization' (you only had the definition in your original comment). I'll add that.

**Comment by pgaudet** [comment]
Added these relations: 
cytokinesis, site selection (GO:0007105)
part_of GO:0032188 ! establishment of actomyosin contractile ring localization

----
mitotic cytokinesis, site selection (GO:1902408)
part_of GO:1903486 ! establishment of mitotic actomyosin contractile ring localization

OK ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood Should 'contractile ring localization' be a child of 'protein-containing complex localization' ?

**Comment by ValWood** [comment]
I don't think so. The contractile ring isn't a 'protein containing complex" . It's defined as an anatomical entity . i think it should actually be classified as an organelle?

**Comment by ValWood** [comment]
I  think 

mitotic cytokinesis, site selection (GO:1902408)
and
GO:1903486 ! establishment of mitotic actomyosin contractile ring localization

are possibly equivalent?

**Comment by pgaudet** [comment]
Well right I have made them parent of each other, creating a cycle (!)

**Comment by pgaudet** [comment]
OK fixed as you initially suggested.

**Comment by pgaudet** [comment]
WRT contractile ring: right now it is a child of  GO:0110165  cellular anatomical entity; please open a new ticket if you'd like to have it under something like ' GO:0043232 
intracellular non-membrane-bounded organelle' 

Thanks, Pascale

**Comment by mah11** [comment]
WAIT. I don't think this new link works for plants. As far as I can tell, in cytokinesis by cell plate formation (GO:0000912), no contractile ring forms. Site selection is relevant to both cytokinesis by cell plate formation and cytokinesis that uses a contractile ring, so making the site selection term part_of the ring localization term is a serious TPV.

(I also think part_of may not be the ideal relation even for the contractile ring case -- it's more accurate to say that site selection precedes ring localization -- but that's getting into hair-splitting territory.)

> mitotic cytokinesis, site selection (GO:1902408)
> and
> GO:1903486 ! establishment of mitotic actomyosin contractile ring localization
> 
> are possibly equivalent?

They're not, again because plants. The phragmoplast is formed in a "selected" location.

**Comment by ValWood** [comment]
Good point.
OK can you revert. I will double check how to partition between site selection and localization.Actually Pombase annotations are to 2 different pathways, so probably OK.
