### ISSUE TITLE
obsolete: anchoring of the mitotic actomyosin contractile ring to the plasma membrane (GO:1903474)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18454]
6 EXP, all pombe
anchoring of the mitotic actomyosin contractile ring to the plasma membrane (GO:1903474)

I will do these as
MF cytoskeletal protein membrane adaptor
part_of
BP mitotic actomyosin contractile ring assembly
(most likely)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:1903474 anchoring of the mitotic actomyosin contractile ring to the plasma membrane'. The reason for obsoletion is that this term is not necessary, and should be captured as 'MF cytoskeletal protein membrane adaptor
part_of BP mitotic actomyosin contractile ring assembly'. 

Experimental annotations to this term are being removed (affects the PomBase group only). 
This term is not present in any slims. 
There is one InterPro domain: IPR037791 
@happy-lorna Could it be annotated as proposed above ? 

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/18454

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on January 13th, 2020. Unless objections are received by January 13th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood 
This term has 3 regulation children; should they also be obsoleted ?

 GO:1903483 regulation of maintenance of mitotic actomyosin contractile ring localization 
 GO:1903484 negative regulation of maintenance of mitotic actomyosin contractile ring localization
GO:1903485 positive regulation of maintenance of mitotic actomyosin contractile ring localization


I'm asking because they don't have the 'to the plasma membrane' bit in the term, but since they are children of 'anchoring of the mitotic actomyosin contractile ring to the plasma membrane' I think that was implied.   

None of those 3 terms have any annotations. 

Thanks, Pascale

**Comment by happy-lorna** [comment]
We have removed this mapping in InterPro.
Thanks,
Lorna.

**Comment by ValWood** [comment]
We would also need to consider the parent

maintenance of mitotic actomyosin contractile ring 

there is one annotation to this:
"UniProtKB:Q9V4P1	scra	involved_in	GO:0032189    maintenance of actomyosin contractile ring localization	ECO:0000315 IMP	PMID:20237160	
7227 Drosophila melanogaster	FlyBase	"


I don't think we need to split "establishment" and "maintenance" of localization.

For now all of these could merge into the parents

actomyosin contractile ring localization
and
mitotic actomyosin contractile ring localization

Probably we can do more of a tidy up here ....

**Comment by pgaudet** [comment]
I assume that means the regulation children are OK to obsolete ? 
(let's do the tidying up of the rest of the branch in another ticket, ok ? )

**Comment by ValWood** [comment]
yep
