### ISSUE TITLE
Question about 3-demethylubiquinone-6 -8 and -10 ?

### ISSUE THREAD

**Issue by Nizal-Shammry** [geneontology/go-ontology#18476]
Dear GO curators,

I have a question about the terms GO:0061543, GO:0044596 and GO:0099119, specifically the molecules 3-demethylubiquinone-6, 3-demethylubiquinone-8 and  3-demethylubiquinone-10 . I did not find any reference to these molecules in any external databases, there is only 3-demethylubiquinone-9 (in chebi (CHEBI:18238)) and Pubchem https://pubchem.ncbi.nlm.nih.gov/compound/3-Demethylubiquinone-9

Regards

**Comment by hdrabkin** [comment]
GO:0099119 (3-demethylubiquinone-8 3-O-methyltransferase activity)  is used in an annotation with a PMID of PMID:10419476
GO:0061543 is used in an annotation using  PMID:10419476 also 

GO:0044596 ; has metacyc xref using 3-demethylubiquinol-10
metacyc uses an Inchi, which I can find in Pubchem, but not CHEBI; however, I have had problems in the past cut/pasting an Inchi from Metacyc into CHEBI search; I will need to ask CHEBI

-- | --

**Comment by dsiegele** [comment]
3-demethylubiquinone-6 is the oxidized form of 3-demethylubiquinol-6 (CHEBI:64253)
3-demethylubiquinone-8 is the oxidized form of 3-demethylubiquinol-8 (CHEBI:61705)
3-demethylubiquinone-10 is the oxidized form of 3-demethylubiquinol-10 (CHEBI:64182)

**Comment by hdrabkin** [comment]
Thanks Debbie. Yes, what you say is true, but I guess I want to know exactly what the substrates for the methyltransferase activities are. If it's the -quinone and not the quinol, metacyc xref for GO:0044596 has the wrong substrate. I can't find anything to suggest that the quinone to quinol conversion is non-enzymatic.

**Comment by hdrabkin** [comment]
If the quinone-n are in fact the true substrates, I'll request CHEBI ids (as well as RHEA) and remove the metacyc xref.

**Comment by hdrabkin** [comment]
Have put in CHEBI requests for the three -quinones

**Comment by dsiegele** [comment]
Hi Harold, I looked at this issue because of a grad student committee I'm on and I've have been trying to learn about ubiquinone biosynthesis. 

I found PMID:10419476 confusing because Fig 2 shows 3-demethylubiquinone-n as the end product of the chemical synthesis of demethyl-Q3, but in Fig 1 and the legend for Fig 5 demethyl-Q3 is shown as the quinol form.

Happy new year!

**Comment by hdrabkin** [comment]
Yes, I looked at that figure also and am  confused too. This is especially important because it's hard for me to request a RHEA for these reactions if I can't pin the actual substrate.  I don't think the quinone <-> quinol by itself (like a keto/enol tautamer).

**Comment by dsiegele** [comment]
Page 21667-last line of first column and continuing to second column: Compound 5 was reduced to the hydroquinone before the methyltransferase activity was performed.

**Comment by hdrabkin** [comment]
This reduction performed by a separate enzyme?  The quinol (OH) would be oxidized to the quinone (=O) correct?

**Comment by dsiegele** [comment]
For assays with the yeast and rat Coq3 enzymes, which were performed with yeast crude mitochondrial extracts, the quinone (=O) form of compound 5 was added to the extract along with NADH to allow enzymatic reduction to the quinol (-OH form).  O-methylation of compound 5 only occurs in the presence of NADH showing that it is the quinol that is the substrate.

Assays of the E. coli UbiG enzyme were performed with purified His6-UbiG. For these assays, the quinone (=O) form of compound 5 was chemically reduced to the quinol (-OH) with sodium dithionite, which was removed prior to adding it to the O-methyltransferase reaction. 

I think that the substrates for the reaction are the quinol forms of the compounds as shown in Fig 1 of PMID:10419476, which I've copied below.

![image](https://user-images.githubusercontent.com/12094502/71877196-33585c80-30ee-11ea-8286-9c4ba629c677.png)

**Comment by hdrabkin** [comment]
So the names of the terms need to be changed as well as their defs, since they refer to the quinone forms. I will do that today; based on the number of manual annotations (1 IMP, 1 TAS, and 1 IDA to GO:0061543, GO:0044596 and GO:0099119 respectively). Certainly GO:0099119 (Ecocyc) this needs to be changed. Most likely the IMP for 44596 (yeast) based on the use of the yeast extracts in the paper you cite.

**Comment by hdrabkin** [comment]
@deustp01 the TAS for GO:0044596 from Reactome; do you agree with my just fixing the term directly to reflect the quinol substrate rather than the quinone? I imagine that when these were created, there was a systematic typo, since EC and Metacyc xrefs specifiy the quinols as the substrates.
@dsiegele  the IDA for GO:0099119 from EcoCyc;  do you agree with my just fixing the term directly to reflect the quinol substrate rather than the quinone? Since the SGD IMP and EcoCyc The only difference in the 3 terms are the length of the side change which (6, 8, and 10), which is not the issue here.

**Comment by deustp01** [comment]
The [relevant Reactome reaction](https://reactome.org/PathwayBrowser/#/R-HSA-8978934&SEL=R-HSA-2162186&PATH=R-HSA-1430728,R-HSA-196854) shows methylation of the quinol substrate so, yes, that change top the GO term name works for us.

**Comment by hdrabkin** [comment]
@srengel the SGD annotation used the same paper as the Ecocyc annotation; so would you object to my just changing the name and def to reflect that the terms should have been using the quinol forms as substrates not the quiinones?

**Comment by srengel** [comment]
Hi @hdrabkin that's ok with us.  thanks for checking.

**Comment by hdrabkin** [comment]
ok; have implemented and also corrected the parent grouping term typos

**Comment by hdrabkin** [comment]
reopened because?

**Comment by dsiegele** [comment]
I will inform Ingrid Keseler at Ecocyc about the change in name and def. I think they will be OK with it.

**Comment by hdrabkin** [comment]
ok; I thought you had made the annotation for some reason;sorry

**Comment by keseler** [comment]
Thanks, Debby, and yes, the change works for me.
