### ISSUE TITLE
synonym inconsistency in GO:0005351

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#18487]
There should be no difference between "proton:sugar symporter activity" and "sugar:proton symporter activity" synonyms but one is declared EXACT, the other BROAD:
```
id: GO:0005351
name: carbohydrate:proton symporter activity
namespace: molecular_function
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: sugar(out) + H+(out) = sugar(in) + H+(in)." [TC:2.A.1.1.-]
synonym: "proton:sugar symporter activity" EXACT []
synonym: "sugar:proton symporter activity" NARROW []
```

**Comment by pgaudet** [comment]
- Changed all synonyms to 'NARROW', since not all carbohydrates are sugar. 
- Changed definition to be consistent with term label: 
OLD: Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: sugar(out) + H+(out) = sugar(in) + H+(in)." 
NEW: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: carbohydrate(out) + H+(out) = carbohydrate(in) + H+(in)." 

**We do have inconsistencies in how we represent sugar transport: We have a term 'GO:0051119** sugar transmembrane transporter activity' but no sugar symporter (or other subtypes of transporters). CHEBI doesn't have the concept of 'sugar', as far as I can tell. 


**- Link to TCBD** is to a family named 'The Sugar Porter (SP) Family', but that also contains carbohydrate transporters (ie non-sugars): 
- Quinate:H+ symporter (TCDB:2.A.1.1.7; described as an amine in wikipedia: https://en.wikipedia.org/wiki/Quinine) 
- Galacturonic acid (TCDB:2.A.1.1.119), described as a sugar acid (a sugar derivative)
- Glycerol (TCDB:2.A.1.1.125)

So it does correspond to 'carbohydrate' in GO, as far as I can tell. 

Thanks, Pascale

**Comment by rwst** [comment]
Thanks. BTW quinate is the anion not of quinine but https://en.wikipedia.org/wiki/Quinic_acid. No nitrogen involved.
