### ISSUE TITLE
NTR: Negative regulation of interleukin-11 secretion 

### ISSUE THREAD

**Issue by ShirinSaverimuttu** [geneontology/go-ontology#18548]
Request for 'negative regulation of interleukin-11 secretion' term to be added.

Evidence: PMID: 29286137. Figure 3:

> ELISA revealed that the secretion of IL-11 was decreased after transfection with miR-124a mimics compared with the blank and NC group.

Currently only GO:0072609 'interleukin-11 secretion' exists.

cc
@BarbaraCzub 
@RLovering

**Comment by ukemi** [comment]
@BarbaraCzub since we are going to remove the regulate_o_part-of chain, these terms will need to have asserted relationships to the production terms. So you will need to assert that 'negative regulation of interleukin-11 secretion' is a subtype of 'negative regulation of interleukin-11 production' term if it exists. You don't need to go back and do it for all the previous terms. Those will be rolled into the work @balhoff is doing.

**Comment by BarbaraCzub** [comment]
Hi @ukemi thank you for pointing this out. I admit that for the previous secretion terms (or biosynthetic process terms) I was using the equivalence axioms to link them to the production terms, so for those ones the relationships will certainly have been inferred, and not asserted. I will assert them here and from now on. Thanks!
