### ISSUE TITLE
GO:0002227    innate immune response in mucosa

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18580]
GO:0002227    innate immune response in mucosa
21 EXP annotations
Is this term required?

mucosa seems to be epithelial cells and most of these have cell type in extensions.

**Comment by addiehl** [comment]
This term is needed.  The mucosa is more than just epithelial cells, it is a distinct bodily location lining areas exposed to stuff that comes in from outside the body, like the nasal passages, the stomach, the gut.  It has a very distinct set of immune processes that occur no where else in the body.

Just because a term has few annotations does not mean it is not an important biological process.  As has been discussed before, large amounts of the immunological literature has never been annotated for a variety of reasons.

I will come to the GO meeting in Paris to discuss immunological processes.

**Comment by ValWood** [comment]
wouldn't it be better to describe the processes than the location?

This term is defined
"Any process of the innate immune response that takes place in the mucosal tissues."

The terms for describing the specific processes (MHC and interlukin etc)  which are part of the mucosal system  also exist, so there is a good chance that annotation will be very inconsistent. You could infer "mucosal" from location, but  encourage people to annotate using the appropriate pathway terms which are in other branches.

Anyway I can close this one.

**Comment by addiehl** [comment]
Just as a point of information, the mucosal immune response includes processes that occur in submucosal areas.  It's not just a regular immune response in the mucosa, but involves distinct cell types, biological processes, and gene products.  There are multiple scholarly journals devoted to mucosal immunology, and certainly there are many processes not represented in GO.

**Comment by pgaudet** [comment]
@addiehl Great that you can make it to Paris ! 

What's the difference between this term and 'mucosal immune response'? 
'An immune response taking place in mucosal tissues, including those of the intestinal tract, nasal and upper respiratory tract, and genital tract.' ?

**Comment by pgaudet** [comment]
Those are the relevant terms: 


Term ID | Term label | Number of EXP annotations
-- | -- | --
GO:0002385 | mucosal immune response | 22
*GO:0002386 | immune response in mucosal-associated lymphoid tissue | 0
*GO:0002422 | immune response in urogenital tract | 0
*GO:0002227 | innate immune response in mucosa | 18


I propose to merge  the 3 terms with * into 'mucosal immune response'. 

@addiehl Would that be OK ? 

Thanks, Pascale

**Comment by addiehl** [comment]
I would be content to merge GO:0002386 and GO:0002422 into GO:0002385.

I would like to keep GO:0002227 as a child of GO:0002385.  An analogous term 'adaptive immune response in mucosa' should be created.  The term 'immunoglobulin production in mucosal tissue (GO:0002426)' would then have its part_of relation to the new term rather than the more general term (GO:0002385), and the term 'mucosal tolerance induction' (GO:0002427) would then become a subclass of the new term and not of GO:0002385.

Both innate and adaptive immune responses in the mucosa have unique characteristics that distinguish them from innate and adaptive immune responses in other compartments.

Alex

**Comment by pgaudet** [comment]
I'll merge 
* GO:0002386  immune response in mucosal-associated lymphoid tissue 
* GO:0002422  immune response in urogenital tract
(neither have annotations) 

into GO:0002385 mucosal immune response
