### ISSUE TITLE
MP GO:0001909 leukocyte mediated cytotoxicity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18716]
Hello, 

GO:0001909 leukocyte mediated cytotoxicity is directly under 'cell killing' - it seems it should have a 'immune process' parent. 

@addiehl , would 'GO:0002443 leukocyte mediated immunity' be appropriate ? 

Thanks, Pascale

**Comment by addiehl** [comment]
Per the GO immunology revision of 2006, 'leukocyte mediated cytotoxicity' was a child of both 'cell killing' and 'immune effector process'.  Per the term history at QuickGO, on 2013-05-09 the relation to 'immune effector process' was switched to 'leukocyte mediated immunity', which seems appropriate since 'leukocyte mediated immunity' is a subclass of 'immune effector process'.

However, on 2016-06-22, for reasons unknown to me, the relation to 'leukocyte mediated immunity' was deleted outright.

I would favor restoring the relation to 'leukocyte mediated immunity', in addition to the relation to 'cell killing'.  Clever use of logical definitions should enable this to be inferred, not asserted.

Alex

**Comment by pgaudet** [comment]
Thanks @addiehl 
'immune effector process' doesn't have a logical definition, so no inference can be done now. I must say based on children I wouldn't know how to write it:

'immune effector process'
'cell activation involved in immune response'
'complement activation'
'defense response to virus'
'encapsulation of foreign target'
'granuloma formation'
'immune complex clearance'
'immune response-regulating cell surface receptor signaling pathway involved in phagocytosis'
'induced systemic resistance, ethylene mediated signaling pathway'
'induced systemic resistance, jasmonic acid mediated signaling pathway'
'leukocyte degranulation'
'leukocyte mediated cytotoxicity'
'leukocyte mediated immunity'
'leukocyte migration involved in immune response'
opsonization
'respiratory burst involved in defense response'

---


It doesn't look like we can just say 'immune system process' has participant some 'immune cell (which is what we would need to get the correct parent for 'leukocyte mediated cytotoxicity' . 

Thanks, Pascale
