### ISSUE TITLE
obsolete: GO:0052161    modulation by symbiont of defense-related host cell wall thickening

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18726]
GO:0052161    modulation by symbiont of defense-related host cell wall thickening
Definition (GO:0052161 GONUTS page)
Any process in which an organism modulates the frequency, rate or extent of host processes resulting in the thickening of its cell walls, occurring as part of the defense response of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction.

This term, and its descendants
GO:0052105    induction by symbiont of defense-related host cell wall thickening	is_a
GO:0052189    modulation by symbiont of defense-related host cell wall callose deposition
should be obsoleted.

They don't make sense because this is a plant PTI (pathogen triggered immunity) response. The plant  increases callose deposition as a defense response  an infected cell. I think this is to contain the pathogens to prevent them spreading to surrounding cells.

There are appropriate plant terms for this process.
GO:0052542    defense response by callose deposition

But, this (GO:0052161)  is not an evolved process for the pathogen. It happens in the plant as a result of the plant detecting the pathogen. 

Can we search for any other terms under "**response to host defenses**" which have
Any process in blah ......**occurring as part of the defense response of the host organism** ?as it is unlikely that any of these are valid, the 2 statements are logically inconsistent.

again, no annotations, no reference....

**Comment by ValWood** [comment]
Double checking @mgiglio99 ?

I think I have seen papers where the cell wall is made thinner by the pathogen, but not thicker?

**Comment by mgiglio99** [comment]
Hi Val,
I agree with obsoleting these.
Michelle

**Comment by pgaudet** [comment]
Dear all, 


The proposal has been made to obsolete 
-  GO:0052161 modulation by symbiont of defense-related host cell wall thickening
 and its children: 
- GO:0052105 induction by symbiont of defense-related host cell wall thickening
- GO:0052189 modulation by symbiont of defense-related host cell wall callose deposition 
-  GO:0052109 induction by symbiont of defense-related host cell wall callose deposition
- GO:0052202 negative regulation by symbiont of defense-related host cell wall callose deposition 

The reason for obsoletion is that this is a host, not a symbiont process, but is formaluted as a symbiont process. 

There are no annotations, no mappings to those terms. Those terms are no present in any subsets. 

https://github.com/geneontology/go-ontology/issues/18726.

We are opening a comment period for this proposed obsoletion. Since there are a few annotations we’d like to proceed and obsolete this term on February 7th, 2020. Unless objections are received by February 7th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
Another term to obsolete in this branch: 
GO:0075048 cell wall strengthening in symbiont involved in entry into host
No annotations, no mapping, not in any subsets.

**Comment by genegodbold** [comment]
Val wrote: "But, this (GO:0052161) is not an evolved process for the pathogen. It happens in the plant as a result of the plant detecting the pathogen."

Yep, along with a suite of other responses that arise from the transcriptional activation that results (or is a hallmark of) PTI (the mild reaction to pathogen detection) and ETI (effector-triggered immunity) the stronger reaction to pathogen detection.
