### ISSUE TITLE
possible obsoletion GO:0052047   symbiotic process mediated by secreted substance

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18764]
I found this term today

GO:0052047   symbiotic process mediated by secreted substance
An interaction with a second organism mediated by a substance secreted by the first organism, where the two organisms are in a symbiotic interaction.

I thought I had seen the entire branch by now, but I still find new things.

It is possible that this term was created for secreted pathogen effectors? It's difficult  to know. I would suggest obsoletion on the grounds that "first" and "second" organism are not specified. I'll check  the existing annotations first to see If I can figure out what process  it is intended for....

**Comment by ValWood** [comment]
It definitely isn't what I thought it was for....

2 EXP annotations:

UniProtKB:P02751 | FN1 | involved_in | GO:0052047    symbiotic process mediated by secreted substance | ECO:0000314   IDA | PMID:17849409 |   | 9606 Homo sapiens | CAFA |  

UniProtKB:Q8K0C5 | Zg16 | acts_upstream_of_or_within | GO:0052047    symbiotic process mediated by secreted substance | ECO:0000315   IMP | PMID:27849619 | MGI:MGI:3529206 | 10090 Mus musculus | MGI

**Comment by ValWood** [comment]
PMID:27849619 
Gram-positive bacteria are held at a distance in the colon mucus by the lectin-like protein ZG16.
The mouse annotation looks OK, but. could the term be refined  to
" symbiotic process mediated by secreted  host substance"

The human annotation is a bit confusing but from the abstract:
Together these results show that M. tuberculosis posses several Plg receptors suggesting that bound Plg to bacteria surface, can be activated to Plm, endowing bacteria with the ability to break down ECM and basal membranes proteins contributing to tissue injury in tuberculosis.

plasminogen receptors involved in GO:0044542    plasminogen activation in other organism
(this should be under
GO:0044068   modulation by symbiont of host cellular process)


but. this would be an annotation for the Tuberculosis protein.
This isn't an evolved function of fibronectin (plasminogen inhibitor)  (i.e it's not mutualism)

**Comment by pgaudet** [comment]
* MGI:1916286  (Q8K0C5) Zg16 | zymogen granule protein 16
PMID: 27849619 Gram-positive bacteria are held at a distance in the colon mucus by the lectin-like protein ZG16.
is annotated to  'negative regulation by organism of entry into other organism involved in symbiotic interaction', which should be relabeled as 'suppression of symbiont entry into host by host'  
This annotation is sufficient and we don't need 'GO:0052047 symbiotic process mediated by secreted substance' 

* Fibronectin UniProtKB:P02751 
Identification of novel bacterial plasminogen-binding proteins in the human pathogen Mycobacterium tuberculosis.
-> We are not clear what is being annotated here
@pgarmiri any thoughts ? 


In any case, the term 'GO:0052047 symbiotic process mediated by secreted substance' should be obsoleted because it's too vague. 


Thanks, Pascale

**Comment by pgarmiri** [comment]
Indeed, this annotation does look very strange.  I have just deleted it.
Thanks,
Penelope

**Comment by pgaudet** [comment]
No mappings, not in any subsets

**Comment by pgaudet** [comment]
Consider:  GO:0140418 effector-mediated modulation of host process by symbiont

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete: GO:0052047 symbiotic process mediated by secreted substance.

The reason for obsoletion is that this term has been misused to annotate host proteins. 

There is one EXP annotation to this term (MGI) (the other by CAFA has been deleted). There are no mappings to this term. This term is not present in any subsets. 

Any comment may be added to the ticket: https://github.com/geneontology/go-ontology/issues/18764

We are opening a comment period for this proposed obsoletion. Since there are a few annotations we’d like to proceed and obsolete this term on February 17th, 2020. Unless objections are received by February 17th, 2020, we will assume that you agree to this change.



Thanks, Pascale

**Comment by pgaudet** [comment]
@hdrabkin Do you want to delete the mouse annotation: 

> MGI:1916286 (Q8K0C5) Zg16 | zymogen granule protein 16
PMID: 27849619 Gram-positive bacteria are held at a distance in the colon mucus by the lectin-like protein ZG16.
is annotated to 'negative regulation by organism of entry into other organism involved in symbiotic interaction', which should be relabeled as 'suppression of symbiont entry into host by host'
This annotation is sufficient and we don't need 'GO:0052047 symbiotic process mediated by secreted substance'

**Comment by ValWood** [comment]
I don't think we should recommend 
GO:0140418 effector-mediated modulation of host process by symbiont
here. It does not fit any of the existing manual annotations which are all to hosts

**Comment by pgaudet** [comment]
Right it does not fit the current annotations (that's why I don't want to do a merge), but this is the closest term. 'Consider' are different from 'replace by'. But I dont need to put that.

**Comment by ValWood** [comment]
Do you need to add a consider term? I guess  this is  for if people look at the obsolete term in future? I think the meaning is so vague  I wouldn't add any "consider" unless absolutely necessary? 

and the existing annotations don't need this particular "consider"

**Comment by pgaudet** [comment]
No, 'consider' is not necessary. I don't usually add any.

**Comment by hdrabkin** [comment]
done
