### ISSUE TITLE
Obsoletion proposal: GO:0052157 modulation by symbiont of microbe-associated molecular pattern-induced host innate immune response

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#18808]
Annotations to 'GO:0052157 modulation by symbiont of microbe-associated molecular pattern-induced host innate immune response' are to gene products that get recognized by the host. This is not an active process by the symbiont. 

Consider: GO:0046789 host cell surface receptor binding

3 EXP: 
2 UniProt (disputed in P2GO)
1 MTBBASE @Achchuthan 

No mappings, not present in any subsets. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0052157 modulation by symbiont of microbe-associated molecular pattern-induced host innate immune response’. 

The reason for obsoletion is that this term has been misused to annotate proteins that are recognized by host innate immune receptors. 

There are 3 EXP annotations (disputed). 

There are no mappings to this term. This term is not present in any subsets. 

Any comment may be added to the ticket: https://github.com/geneontology/go-ontology/issues/18808.

We are opening a comment period for this proposed obsoletion. Since there are a few annotations we’d like to proceed and obsolete this term on February 17th, 2020. Unless objections are received by February 17th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by ValWood** [comment]
These shouldn't be annotated to 
GO:0046789 host cell surface receptor binding
because that isn't the evolved function from the pathogen perspective.

The host Toll  *receptor * can be annotated to  has_input pathogen protein (with
the dual taxon preferably)

The term  "GO:0046789 host cell surface receptor binding" 
is for  the pathogen utilising host receptors during invasion (for example http://europepmc.org/article/MED/20855594)
Not for recognition of the pathogen by the host.
I don't think it will be useful to mix in all the molecules that the host uses for recognition.

Maybe we should add a comment  to the term (there are only 39 experimental annotations,  to GO:0046789 host cell surface receptor binding and they are probably largely OK ). For example malaria and coronovirus  binding host receptors for invasion.

**Comment by AndreaAuchincloss** [comment]
I used this term 2 1/2 years ago, so my memory is a bit patchy, but I chose this term because this is what I read in the paper (PMID 10426995): "Here it is shown that microbial lipoproteins are potent stimulators of IL-12 production by human macrophages, and that induction is mediated by Toll-like receptors (TLRs). Several lipoproteins stimulated TLR-dependent transcription of inducible nitric oxide synthase and the production of nitric oxide, a powerful microbicidal pathway. Activation of TLRs by microbial
lipoproteins may initiate innate defense mechanisms against infectious pathogens."

I don't think these bacterial outer membrane proteins just recognize a receptor, that wasn't honestly the interesting part of the bacterial protein function, it is the fact they alter the host immune response.

**Comment by ValWood** [comment]
Hi @AndreaAuchincloss  - but, the bacteria didn't evolve the lipoproteins in order to activate the host immune system. i.e. the  bacterial outer membrane proteins don't 'recognise' the receptor. The host receptors 'recognise ' the pathogen cell surface proteins and activate  their innate immune response. 

This is host "initiate innate defense mechanisms against infectious pathogens."
he bacteria evolve processes to avoid the host immune system. Does that make sense?

**Comment by ValWood** [comment]
i.e.  the BP def:
"A biological process represents a specific objective that the organism is genetically programmed to achieve."

**Comment by pgaudet** [comment]
I think the confusion comes from the statement "microbial lipoproteins are potent stimulators of IL-12 production " 
which makes it sound like the bacterial proteins are actively stimulating the immune system - which they are probably are not - they would likely prefer to avoid the immune response, wouldn't they ?

**Comment by ValWood** [comment]
Yes, the statement 
"microbial lipoproteins are potent stimulators of IL-12 production "
is true, but not  the objective ;)

**Comment by AndreaAuchincloss** [comment]
True enough, the bacteria in question would prefer not to come to the attention of the host immune system.
As @ValWood says, these shouldn't be annotated with GO:0046789 (host cell surface receptor binding), what do I replace the about-to-be-obsoleted term with (I made both UniProtKB annotations)? I'm thinking there is not a correct replacement term and I'm thinking of just removing the term without replacing it.

**Comment by pgaudet** [comment]
Right - this is not a 'normal' function for the bacterial protein, I dont see a replacement either.

**Comment by ValWood** [comment]
Yes, that is correct, it isn't GO annotatable (for the pathogen) 

If you also annotated the host receptor protein from the same publication you can add the bacterial protein as an input.

PHI-base also use a pathogen-host interaction phenotype ontology (PHIPO)  to capture changes in the immune activation by alterations to the pathogen proteins.  This. wouldn't be appropriate here because I don't think they were doing any mutational analysis.

There are some examples where you can capture with GO if the pathogen has evolved to activate the host immune system (necrotrophic fungi for example). 

The rule of thumb, is that conserved pathogen proteins  with a  biological role on the pathogen cell surface (or elsewhere), with some role in normal pathogen growth  are usually not annotatable to host defense activation.

The gene products which are activating host defense systems are *usually*  secreted by the pathogen, and evolved solely to interfere with host defenses. I haven't curated enough of these to know if non-effectors can do this too....I am still learning this area.

**Comment by genegodbold** [comment]
So I'm addressing this statement of Dr. Gaudet "which makes it sound like the bacterial proteins are actively stimulating the immune system - which they are probably are not - they would likely prefer to avoid the immune response, wouldn't they" 

1. Figuring out the teleology of bacteria is fraught with problems, even murkier than determining the purposes of God (and I speak as a long-ago seminary graduate :-))
2. There are a lot of bacterial toxins that induce inflammation: anthrax lethal toxin, TcdA and TcdB from Clostridioides difficile, iota toxin from Clostridium perringens, cytolethal distending toxin from Campylobacter and Aggregatibacter actinomycetemcomitans, enterohemolysin from E. coli, exotoxin U from Pseudomonas.
3. Sometimes bacteria *do* stimulate inflammation via non-toxins and sometimes this *seems* to aid their "purposes", most notably Helicobacter pylori and Salmonella

- CagA from Helicobacter pylori can induce IL-8 production in a time-dependent and strain-dependent manner [PMID20938460]. CagA associates with the host TGFbeta-activated kinase 1 (TAK1) at the plasma membrane, enhancing its activity. Polyubiquitination of TAK1 is important for the activation of TAK1 (and IKK). This requires TRAF6 [PMID21326919]. CagA is required for H. pylori-mediated activation of nuclear factor kappa B [PMID19820695].

- CtkA from Helicobacter pylori induces production of pro-inflammatory cytokines (TNF, IL-6, IL-1 beta) in gastric epithelial cells via activation of the host inflammasome [PMID25172221]. CtkA produced by Helicobacter pylori and secreted by a specialized T4SS mediates pro-inflammatory signaling through NFkappaB in host gastric epithelial cells [PMID28759055]. Recombinant CtkA that is catalytically active produces enhanced phosphorylation of the NFkappaB p65 subunit at Ser276 in human epithelial cancer cells [PMID21098302].

- Full length DupA from Helicobacter pylori induced significant production of IL-12p40, IL-12p70, and IL-23 (associated with the Th1 immune response) in human PBMCs.  Monocytes were identified as the PBMC subpopulation that were responsible for the secretion of these cytokines [PMID20533870]. DupA appears to induce IL-8 production in human peripheral blood mononuclear cells [PMID20938460].

- SifA, SpvB, SseF, SseJ and SteA contribute to late inflammation of S. eneterica serovar Typhimurium in a mouse model of colitis in a T3SS-1 deficient strain [PMID31235639].

- Expression of the sopE gene contributes to colitis in a murine model of Salmonella enterica infection. It can induce intestinal inflammation independent of SipA and SopE2 and in the absence of SopB [PMID14742523]. Intestinal inflammation appears to be due to Rho GTPase activation and downstream effects resulting in caspase-1 induction. This results in the maturation and release of the proinflammatory cytokines IL-1 and IL-18 [PMID19683679].

- SipA contributes to most of the colitis observed in a murine model of Salmonella enterica infection. It can induce intestinal inflammation independent of SopE and SopE2 and in the absence of SopB. This occurs through NOD1/2 signaling activating NFkappaB and requires the N terminus of SipA [PMID14742523]. This induction of inflammation is independent of its actin-stabilizing ability [PMID23439302]. 

Sometimes bacteria induce inflammation with one secreted effector for a time only to turn the inflammatory process off with a different (and differently expressed) effector. I'm pretty sure Shigella and M. tuberculosis do though I can't find a convenient reference at the moment. One "reason" that bacteria want to induce inflammation is usually to attract phagocytes to the site. (I think Yersinia pestis as well as Salmonella does this, but I'm going from memory) Why? Because they subvert phagocytosis and hitch a ride in the phagocyte to the regional lymph node where they proceed to infect the other lymphocytes. You're right that it is often the strategy of bugs to lay low and hide (like Francisella and Brucella). And during the infection cycle of a lot of bugs, many species *do* lay low and hide. And sometimes they hide for awhile while they multiply and then, once a "critical mass" is reached, they stop hiding and start causing serious problems (like sepsis).

Anyway, bacteria have a more diverse set of infection strategies so it's harder to generalize about them than, say, viruses. Fungi are pretty weird, too and protozoan parasites are perhaps the strangest of all--and we know the least about them.

(I apologize for the literature dump, but I had my spreadsheet open so I figured I'd might as well use it.)

**Comment by pgaudet** [comment]
Thanks ! How would you describe the function of these bacteria proteins though ? 'inducers of inflammation'?

**Comment by ValWood** [comment]
Hi @genegodbold ,

we have terms to deal with this:
GO:0140404   effector-mediated modulation of host innate immune response by symbiont
(for example)

However, the surface molecular patters on the pathogen/symbiont recognised by the PRR signalling 
didn't evolve to activate the host immune system.

I looked at the above and they all seem to be secreted effector molecules?

**Comment by ValWood** [comment]
Well I only looked at 2 ;)

As far as we know, the PAMP doesn't  evolve to induce the host PAMP-mediated signalling pathway (at least we have no annotatable  example of this so far).  The PAMP is usually a broadly conserved pathogen molecule (lagellin, EF-Tu, and chitin etc). The plant presumably targes these becasue they are conserved. Therefore these are unlikely to be able to evolve to have a role in defence.  Such a process might exist, but we shouldn't add until it is required for annotation....

**Comment by genegodbold** [comment]
To pgaudet: Our "category" for them is "Induce Inflammation", yes. I've got 59 proteins annotated that way.

To ValWood: So I follow Jorge Galan's distinction of a lethal bacterial effector vs a toxin--the difference is that the effector cannot mediate its own passage into the host cell while a toxin can. (I've started looking at fungal and oomycete "effectors" of plants and I don't think they maintain these distinctions, but that's a different issue.)

MAMP/PAMP (I prefer the former, because the immune system has a short way with non-pathogens). Yep, I agree. 

I think it's interesting that it is a "thing" (I call 'passive immune evasion') where the parasite alters its MAMP to make it less immunogenic. Deleting the gene makes the bug more inflammatory and damaging in the short run but it is less successful at establishing an infection. AlmG from Vibrio cholerae, Cbu0678 from Coxiella, PagL and PagP from Salmonella, Lic2B from Haemophilus influenzae, Lipid A phosphatase from P. gingivalis, LpxD1 from Francisella and others do this.

**Comment by genegodbold** [comment]
Dear @ValWood, That GO term (GO:0140404) is pretty high level and vague. I have many hundreds of sequences that would roll up under that one.

**Comment by ValWood** [comment]
yes you are right  (GO:0140404) is high level . Once we get specific examples this area will be fleshed out.
I  have  recently begun to annotate oomycete plant pathogens in this area which is why the terms were added. 

Quite often though it   seems these will be annotated as MF involved in GO:0140404
so the specificity might come from the molecular function (i.e protease inhibitor, or whatever).

The "passive immune evasion:"  seems that it would be described as a type of "antigenic variation"
https://www.ebi.ac.uk/QuickGO/term/GO:0020033
Definition (GO:0020033 GONUTS page)
Any process involved in the biological strategy of changing antigenic determinants on the surface that are exposed to another organism's immune system.

**Comment by genegodbold** [comment]
Hey @ValWood,
So I've always thought of antigenic variation as something like "Var" genes where the parasite is switching out motifs or domains or whole genes through some transcription/translation modification. This happens with exons in eukaryotic parasites. I think some bacteria regularly change out their surface proteins to get the same effect. The "passive immune evasion" I'm talking about typically happens to a lipid structure and it happens after it has gotten made by the "original" enzymatic machinery. Then these extra enzymes come in and snip away a phosphate of lipid A or two carbons at the end of the acyl chains or somesuch so that TLR4 or TLR2-TLR4 isn't provoked by it.

**Comment by ValWood** [comment]
This process possibly need another descendant of the parent 
GO:0042783    
A process by which an organism avoids the effects of the host organism's immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction. 

but what you describe appears to fit the antigenic variation definition too as currently defined (although I have also only seen this used for var genes). Maybe that definition needs tightening?

**Comment by addiehl** [comment]
Getting back to the original term name, "modulation by symbiont of microbe-associated molecular pattern-induced host innate immune response", it sounds like it is about a three organism interaction, so is perhaps confusing from that perspective.

But I absolutely agree with Gene that pathogenic organisms often manipulate the inflammatory and immune responses of their host to serve their own purposes, particularly when such responses aid the spread of the organism from the host.

**Comment by ValWood** [comment]
We have many examples of this but they  have  more clearly defined terms ...
This term was not clear and was incorrectly used.

**Comment by ValWood** [comment]
We have this term
GO:0140423    effector-mediated suppression of pattern-triggered immunity signaling

which is clearer, because we haven't yet come across any examples which are not "effector-mediated"

Making this  explicit should prevent the PAMPs themselves  being annotated to 
"suppression of pattern-triggered immunity signaling"


The reason for obsoletion isn't quite right. This is an active process, it's just this this term  was incorrectly used and in a parallel branch.

**Comment by genegodbold** [comment]
@ValWood I completely agree. In practice it can be a little hard to distinguish. This is sometimes the case for (bad) researchers as well. They'll report phenomenology and I'm thinking: "Are you sure that this isn't *just* the immune system reaction to a microbial component?" 
Because they certainly are not showing a parasite protein-caused mechanism.

Of course, if there is a suppression (as opposed to an instigation) of pattern-triggered immunity signaling, then it is probably going to be caused by the parasite--what else would be causing this? Not, in any circumstance that I can think of, the host? (This is supposing a natural reaction to a pathogen and not an auto-immune condition where there might be endogenous suppressors of extraneous immune reactions.)
