### ISSUE TITLE
Obsolete GO:0052115 energy taxis in host environment and children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18825]
GO:0052115    energy taxis in host environment | is_a

merge in:
GO:0052225    energy taxis on or near other organism involved in symbiotic interaction | is_a
GO:0052224    energy taxis in other organism involved in symbiotic interaction | is_a
GO:0052218    positive energy taxis in environment of other organism involved in symbiotic interaction | i
GO:0052219    negative energy taxis in environment of other organism involved in symbiotic interaction

seem to all mean the same
All unused?

**Comment by pgaudet** [comment]
In fact including indirect children those are the terms: 
'energy taxis in host environment'
'energy taxis on or near host'
'energy taxis within host'
'negative energy taxis in host environment'
'negative energy taxis in host'
'negative energy taxis on or near host'
'positive energy taxis in host environment'
'positive energy taxis in host'
'positive energy taxis on or near host'

No annotations, no mappings, not in any subsets. Will obsolete.

**Comment by pgaudet** [comment]
In this case I think we can have Replace by 'GO:0009453 energy taxis'

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0052115 energy taxis in host environment' and its children:

GO:0052225    energy taxis on or near other organism involved in symbiotic interaction 
GO:0052224    energy taxis in other organism involved in symbiotic interaction 
GO:0052218    positive energy taxis in environment of other organism involved in symbiotic interaction 
GO:0052219    negative energy taxis in environment of other organism involved in symbiotic interaction
GO:0052145 negative energy taxis on or near host
GO:0052146 positive energy taxis on or near host 

The reason for obsoletion is that this represents a process and a location, and the location should be captured as an extension. 

There are no annotations and no mappings to this term. This term is not present in any subsets. 

Any comment may be added to the ticket:https://github.com/geneontology/go-ontology/issues/18825

We are opening a comment period for this proposed obsoletion. Since there are a few annotations we’d like to proceed and obsolete this term on February 17th, 2020. Unless objections are received by February 17th, 2020, we will assume that you agree to this change.

Thanks, Pascale
