### ISSUE TITLE
What does this mean? DNA synthesis involved in UV-damage excision repair 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18912]
This is a strange term (again...)

GO:1904161    DNA synthesis involved in UV-damage excision repair
Any DNA synthesis that is involved in UV-damage excision repair. PMID:10704216

I most likely requested it. but there isn't a specific separate process for  DNA synthesis that is involved in UV-damage excision repair.

It is used to annotate :
DNA polymerase delta by PomBase (4 subunits)
trex1 (MGI)   (I don't find anything to do with replication in this paper?, needs disputing)
and
POLA1  (Uniprot) with a NOT annotation, which would still be correct

DNA polymerase delta is the polymerase involved in replication restart after damage/repair etc:

HR-mediated fork restart at the RTS1-RFB results in a restarted replisome, which is mechanistically distinct from a canonical replisome, with DNA polymerase δ synthetizing both strands (Miyabe et al, 2015). 

I would like to  either
1.  rename this germ to 
DNA replication during replication restart 
and make it a child of
GO:0031297   replication fork processing

OR 
2. obsolete and make a  new term  for 
DNA replication during replication restart 

(DNA replication during replication restart also required for PMID:31575705)

**Comment by ukemi** [comment]
Excision repair removed a small stretch of the damaged strand and then synthesizes new DNA on the good template. I assume this term refers to that new synthesis. For example: PMID:15749700

**Comment by hattrill** [comment]
@sjm41  - we don't have any annotations to this term, but thought this thread this might be of interest to you.

**Comment by ValWood** [comment]
yes, it does refer to the new synthesis, but it isn't a process specific for UV-damage excision repair is it? Other types of DNA repair require this new DNA synthesis too. Doesn't it all use the same polymerase?

Or maybe there is a different polymerase when the dame occurs during S-phase and replication forks need to be restarted.

It just seemed odd that my 4 annotations to this term  were to the 
"DNA polymerase delta" 

which is the polymerase which re-synthesises damaged DNA during replication restart.

GO:1904161 DNA synthesis involved in UV-damage excision repair

doesn't describe DNA polymerase delta in the way I would want to describe it
(I could just use DNA polymerase involved_ in  BER for starters if this is all it is)

I will be removing these 4 annotations which leaves 2 annotations, one  NOT and one dodgy?

Which makes me wonder if the term is really required?

Note that we also have this term
GO:0019985    translesion synthesis
Definition (GO:0019985 GONUTS page)
The replication of damaged DNA by synthesis across a lesion in the template strand; a specialized DNA polymerase or replication complex inserts a defined nucleotide across from the lesion which allows DNA synthesis to continue beyond the lesion. This process can be mutagenic depending on the damaged nucleotide and the inserted nucleotide. PMID:10535901


so I think it is redundant anyway?

**Comment by ValWood** [comment]
I'm happy for you to ignore this one. I will just reannotate polD to a more suitable term.

v

**Comment by ValWood** [comment]
Actually I'm just going to leave it as it is. Can of worms...

**Comment by pgaudet** [comment]
Should we not annotate 'DNA polymerase activity' part of some 'xx-pathway DNA repair ?

**Comment by ValWood** [comment]
Yes, that is what I was thinking. But then I looked deeper and the terms translesion synthesis and children encompass much mpre that the DNA synthesis part. They seem to describe broader repair processes. As that point I decided to leave alone here becasue it is *way* outside my area of expertise. @mah11  does DNA metabolism. She might have some insight.

(although very bizarrely I see my initials in some of these term defs with Eurie Hong, anyway I think this area is a bit scrappy)

**Comment by mah11** [comment]
> @mah11 does DNA metabolism

No, I do DNA *replication*. I have neither extensive nor in-depth knowledge of DNA repair or recombination processes. Based more on what I know about replication than other types of DNA metabolism, a few scattered thoughts ...

- In general, DNA synthesis requires the activities of DNA polymerase and DNA ligase. DNA replication needs DNA synthesis and RNA primer synthesis.

- It makes sense to me that DNA repair may include DNA synthesis. IIRC DNA synthesis in other types of DNA repair, especially those not coupled to replication, usually uses other polymerases than delta or epsilon -- there are a whole bunch of DNA polymerases in eukaryotes, many of which only do some kind of repair synthesis. (That's about all the detail I have to hand right now.)

- I would NOT use this as a term name:

> DNA replication during replication restart

Replication restart is the outcome of processing stalled replication forks, and is therefore a part of the larger DNA replication process, not the other way round.

As for pol delta, the interesting thing about restarted replication is that it appears to use pol delta to replicate both strands, instead of pol epsilon doing the leading strand. IIRC DNA synthesis in other types of DNA repair, especially those not coupled to replication, usually uses other polymerases -- there are a whole bunch of DNA polymerases in eukaryotes, many of which only do some kind of repair synthesis. (That's about all the detail I have to hand right now.)

I have no idea how, or even whether, translesion synthesis fits in here.
