### ISSUE TITLE
NTR:	DNA-binding transcription activator activity, RNA polymerase I-specific

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#18955]
A protein, or a member of a complex, or a non-coding RNA that interacts selectively and non-covalently with a specific DNA sequence (sometimes referred to as a motif) within the regulatory region of a RNA polymerase I-transcribed gene to activate or increase transcription.

**Comment by mah11** [comment]
That def reads like the description of a gene product rather than an activity.

I think the same of the existing def for GO:0001228, although the parent (GO:0001216) def is OK.

**Comment by ValWood** [comment]
I copied it from the 
DNA-binding transcription activator activity, RNA polymerase II-specific

so they probably need revising to the parent

**Comment by colinlog** [comment]
for GO:00003700, DNA-binding transcription factor activity

Would the definition written as below be more acceptable with respect to this being an activity rather than a bio-entity? It is mr ein line with the definition of GO:0001216, which concerns only activators, whilst GO:0003700 covers also repressors GO:0001217

@mah11 
@pgaudet 
@ValWood 
..
Interacting selectively and non-covalently with a DNA sequence (sometimes referred to as a motif) within a _cis_-regulatory region of a gene in order to modulate the frequency, rate or extent of transcription by a RNA polymerase. The activity can be performed by a protein, an RNA or a multimolecular complex. _Cis_-regulatory DNA regions include promoters (proximal and distal), enhancers, silencers, insulators and boundaries. Genes are transcription units and include bacterial operons. 
..

**Comment by mah11** [comment]
@colinlog yes, exactly

**Comment by pgaudet** [comment]
@ValWood What would be the reference for this ? I see you have closed the pombase ticket (https://github.com/pombase/curation/issues/2619) and annotated this as a GTF. Close ?

**Comment by ValWood** [comment]
Yes, there was a later discussion
 dhttps://github.com/pombase/curation/issues/2619#issuecomment-700855980
