### ISSUE TITLE
Merge GO:0061745 GTPase activity, coupled and GO:0042623 ATPase activity, coupled into respective parents

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19078]
* Merge GO:0061745 GTPase activity, coupled: merge into GO:0003924 GTPase activity
1 annotation to a GTPase 

* Merge GO:0042623 ATPase activity, coupled  merge into GO:0016887 ATPase activity
37 EXP 

Group | Number of annotations
-- | --
UniProt | 10
EcoCyc | 8
SGD | 6
MGI | 3
CGD | 2
EcoliWiki | 2
AgBase | 1
BHF-UCL | 1
CACAO | 1
FlyBase | 1
RGD | 1
dictyBase | 1

* Obsolete GO:0061746  single-stranded DNA-dependent GTPase activity: 1 annotation, redundant with another annotation
Q3V5F2 CACAO (single-stranded DNA helicase activity)

**Comment by pgaudet** [comment]
+ merge 
 GO:0061747 CTPase activity, coupled
and  GO:0061748 single-stranded DNA-dependent CTPase activity 
into GO:0043273 CTPase activity 

While the enzyme studied in PMID:26277776, can use other nucleotides as energy source for the reaction, ATP is most efficient, and therefore the most likely nucleotide used in vivo. 

There is no other evidence that this function exists.

**Comment by pgaudet** [comment]
* Also merge 
GO:0103024 XTPase activity' 0 annotations
into 
'GO:0036222 XTP diphosphatase activity' 7 EXP

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0061746 single-stranded DNA-dependent GTPase activity. The reason for obsoletion is that there is no evidence that this reaction occurs under physiological conditions. 

There is a single annotation to Q3V5F2 by CACAO @sandyl27 
which should be deleted as it is redundant with another annotation (single-stranded DNA helicase activity). 

There are no mappings to thus term; this term is not present in any subsets. 

Comments can be added to the ticket: geneontology/go-ontology#19078

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on March 18th, 2020. Unless objections are received by March 18th, 2020, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
@deustp01 
The merges I did in this ticket impact A LOT of reactome mappings. Should I change that in the reactome_xrefs_import file ? (this is what we have in the documentation, but does Reactome integrates that file back ?) 

Thanks, Pascale

**Comment by deustp01** [comment]
@pgaudet Check with @ukemi , but I think the answer is "no" because this file gets dumped and reloaded as part of each Reactome quarterly release. I think that manual patches on the fly are strongly discouraged - that, anyway, is our developers' view.

Basically, if the result of the merge is that GO:xxx becomes obsolete and all annotations that used it should instead now use GO:yyy, we will pick up that change and apply it automatically to all affected annotations as part of our quarterly updating of our local copy of GO. That update propagates into the release that happens a few weeks later, and from there into the new reactome_xrefs_import file. 

Could you confirm that what you are doing here is obsoleting GO:0061745 "GTPase activity, coupled" and suggesting that it be replaced with  GO:0003924 "GTPase activity" and also obsoleting GO:0042623 "ATPase activity, coupled" and suggesting that it be replaced with   GO:0016887 "ATPase activity"? If so, patching Reactome is easy. I'll do it as soon as the obsoletion becomes official, and the changes will propagate into the xref file with our June 2020 release.

Question out of ignorance (but important to avoid future surprises): why didn't those affected Reactome instances turn up on the list of affected annotations at the top of this obsoletion notice? As far as I can tell, we have not used the GTPase-coupled term at all and have used the ATPase-coupled term four times.

**Comment by ukemi** [comment]
Correct. The Reactome file is an automatic product of the Reactome pipeline. Any issues should be dealt with at the source.

**Comment by pgaudet** [comment]
Hi @deustp01 
Sorry if I was unclear. This is a merge, not an obsoletion, I assumed that mappings were automatic. Is this the case ? (ie do you replace alt_ids with primary ids? ) 

There is no Reactome annotation to the term I proposed to obsolete (GO:0061746). 

Thanks, Pascale

**Comment by deustp01** [comment]
I see the merged / obsoleted distinction now - sorry I missed it before and confused things. But as far as what we need to do, it's all the same, isn't it? We need to find all usages of the "coupled" terms and replace them with the plain terms, regardless of the reason why the "coupled" terms are to be dropped?

**Comment by pgaudet** [comment]
I suppose ! Each group has their own workflow. I understand some groups look to alt_ids and obsolete terms having 'replace by' tags and do the replacement automatically.

**Comment by pgaudet** [comment]
(Note that the changes are not yet merged into master)

**Comment by pgaudet** [comment]
@deustp01 
@balhoff  has put in place an automated replacement for this situation. So, if it's OK with you, I can go ahead with the merge, and the ontology and the Reatome annotations will be correct according to the merge operation. 

However you still need to update your file so that there are no conflicts when we import your new file. 

Is that OK with you ? 

More generally that is the proposed procedure for any merge that impacts Reactome data. Ontology editors will notify Reactome but we can (technically) go ahead with merges, if you agree of course. 

Thanks, Pascale

**Comment by deustp01** [comment]
Those plans are fine for us.

**Comment by deustp01** [comment]
I've corrected the four Reactome annotations that used GO:0042623 "ATPase activity, coupled" to use GO:0016887 "ATPase activity"; the revised annotations will propagate to our public website and to the xref file with our release in June.

Going forward, our existing QA will pick up all GO terms in Reactome that have been removed from GO proper by merger or obsoletion, and that weren’t already fixed manually in response to obsoletion notices so we shouldn't need anything additional from ontology editors.
