### ISSUE TITLE
Overall plan for cytokine production, secretion, biosynthesis terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19115]
Outcome of a discussion with @addiehl and @RLovering: 

Overall plan for cytokine production, secretion, biosynthesis terms: 

1. We plan to move 'regulation of x production' terms under 'regulation of gene expression'  #19116
2. Merge 'x secretion' and 'regulation of x secretion' into 'regulation of x production' (annotations first need to be reviewed) #19117
3. Merge 'x production' into 'regulation of x production' (annotations first need to be reviewed)
4. Merge 'x biosynthesis' into 'regulation of x production' (~annotations first need to be reviewed~  We will not review annotations as biosynthesis encompasses production) #19256 
5. Add 'x processing' terms as needed (for proteases), under 'GO:0016485 protein processing' . (We may find we need to create other BPs when we do the annotation reviews)

I'll create tickets for each of those tasks 

Thanks, Pascale

**Comment by addiehl** [comment]
I realized a key problem with merging 'x production' into 'regulation of x production' today as I worked on the Cell Ontology.  The CL needs GO terms terms such as 'interferon-gamma production' so we can make logical definitions like 'T-helper 1 cell' capable_of some 'interferon-gamma production'.

There are currently 145 cell ontology classes that match the DL query
cell and 'capable of' some 'cytokine production'

So it will be better to mark 'x production' terms as do not annotate, rather than merging them.

Alex

**Comment by pgaudet** [comment]
- [ ] added 'gene expression' as a parent of  'GO:0002440 production of molecular mediator of immune response' 
- [x] added 'do not annotate' flag on all children of  'GO:0002440 production of molecular mediator of immune response' 
- [ ] added a note : Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select one of the 'regulation' children terms.

**Comment by pgaudet** [comment]
@RLovering @addiehl 

It would be nice to review the comments (see 4th point in the comment just above), and standardize the definitions of the production terms: We have either:  "The synthesis or release of platelet activating factor following a stimulus, resulting in an increase in its intracellular or extracellular levels. " (GO:0002390; platelet activating factor production), or "The appearance of a cytokine due to biosynthesis or secretion following a cellular stimulus, resulting in an increase in its intracellular or extracellular levels."  (GO:0001816  cytokine production). 

It seems the first definition is more concise; maybe we should opt for that for all the terms ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also - removed parent 'protein metabolic process' from 'cytokine production'

**Comment by RLovering** [comment]
sorry to open this again, but if you remember there were a few cytokines that are activated by processing. So I have an alert on CASP1 which is involved in https://pubmed.ncbi.nlm.nih.gov/15882992/ states caspase-1 mediates the maturation of inflammatory cytokines IL-1β and IL-18.

So I would like to annotate caspase-1 CASP1 as involved in interleukin-1 beta production rather than annotating it as positively regulating interleukin-1 beta production.

CASP1 P29466 is already associated with signaling receptor ligand precursor processing and cysteine-type endopeptidase activity with IL1beta in the AE field, but obviously this does not indicate that it is involved in IL1beta production.

I believe with Alex we came up with a list of cytokines that require processing and I thought that the BP GO terms for these cytokines would be available for inclusion in annotations. But perhaps I misremembered this - sorry if this is the case.

Thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering Can you use this as an extension ? 
CASP1 involved in protein processing/maturation part of protein production ? 

This would be allowed for 'do not annotate' terms.

Thanks, Pascale

**Comment by pgaudet** [comment]
Generally though, if we go this way, we should create a new term, 'protein production', and put 'protein maturation' under this term. 

Thoughts ?

**Comment by deustp01** [comment]
How will those terms differ from the current terms  GO:0019538 protein metabolic process "The chemical reactions and pathways involving a protein. Includes protein modification." and its child  GO:0036211 protein modification process "The covalent alteration of one or more amino acids occurring in proteins, peptides and nascent polypeptides (co-translational, post-translational modifications). Includes the modification of charged tRNAs that are destined to occur in a protein (pre-translation modification)."? Note that  GO:0006412 translation is a grandchild of GO:0019538 protein metabolic process.

**Comment by pgaudet** [comment]
> How will those terms

Which term**s** ? maturation and processing already exist. 

- GO:0019538 protein metabolic process includes proteolysis, so it's not equivalent to production. 
- protein biosynthesis is named translation, and the process Ruth describes is not part of translation.

**Comment by pgaudet** [comment]
Talking with @RLovering 
The term she was looking for is GO:0140447 cytokine precursor processing

**Comment by pgaudet** [comment]
add synonym: 
- interleukin processing NARROW
- interleukin maturation NARROW
