### ISSUE TITLE
EC mentions on GO:0052810 & GO:0052811

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19141]
**id: GO:0052810
name: 1-phosphatidylinositol-5-kinase activity**
=> remove mention of EC:2.7.1.137 from definition and synonyms
(That EC is for 1-phosphatidylinositol 3-kinase)

**id: GO:0052811
name: 1-phosphatidylinositol-3-phosphate 4-kinase activity**
=> remove mention of EC xref "EC:2.7.1.150" from definition and synonyms
(That EC is for 1-phosphatidylinositol-3-phosphate 5-kinase.)

**Comment by hdrabkin** [comment]
Hard time with references; removing these ECs leave the terms without def refs. Used a rectome reference for 0052810, and moved the reactome xref to the def. 
I cannot ask for  rhea if I can't supply a real reference. 
0052811 has only 1 IMP annotation, rest are IEA
0052810 has the reactome annotations.
ECs removed but these terms need to be revisited to give proper references

**Comment by deustp01** [comment]
@hdrabkin it looks like Reactome has literature references to go with both GO mf terms. Would it be useful to dig them out?

**Comment by hdrabkin** [comment]
@deustp01 yes, please. I did find one the -10 term, but had trouble finding one for the -11 term at Reactome, but that might be my misreading something.

**Comment by deustp01** [comment]
It turns out that if you go to the Reactome home page and put a GO identifier, e.g., GO:0052810, into the search box, you'll retrieve a list of all reactions and maybe also all the physical entities 
annotated using that term.

GO:0052810
At the plasma membrane, phosphatidylinositol-4-phosphate 5-kinase type-1 alpha (PIP5K1A) and beta (PIP5K1B) phosphorylate phosphatidylinositol (PI) to produce phosphatidylinositol 5-phosphate (PI5P) (Tolias et al. 1998).
PMID: 9660759

GO:0052811
At the plasma membrane, phosphatidylinositol-5-phosphate 4-kinase type-2 alpha (PIP4K2A) and beta (PIP4K2B) homodimers and heterodimers (Clarke et al. 2010), along with phosphatidylinositol-4-phosphate 5-kinase type-1 alpha (PIP5K1A), beta (PIP5K1B), and gamma (PIP5K1C) phosphorylate phosphatidylinositol 3-phosphate (PI3P) to phosphatidylinositol 3,4-bisphosphate (PI(3,4)P2). The following lists the above proteins with their corresponding literature references: PIP4K2A (Zhang et al. 1997, Rameh et al. 1997, Clarke et al. 2008), PIP4K2B (Zhang et al. 1997, Rameh et al. 1997), PIP5K1A (Zhang et al. 1997, Tolias et al. 1998), PIP5K1B (Zhang et al. 1997, Tolias et al. 1998), and PIP5K1C (Wenk et al. 2001, Di Paolo et al. 2002).
PMIDs: 9211928, 9367159, 9660759, 19896968, 12422219, 18753295, 11604140

**Comment by hdrabkin** [comment]
Ah, that's quicker than how I was trying to do it (go to amigo; find annotations; if Reactome click on id; try to figure out where references are. 
Thanks; I will add a few of these so I can close the ticket.

**Comment by hdrabkin** [comment]
RHEA requested  [help 184070]

**Comment by hdrabkin** [comment]
1-phosphatidyl-1D-myo-inositol + ATP = a 1-phosphatidyl-1D-myo-inositol 5-phosphate + ADP + 2 H(+). (GO:0052810)
is RHEA:44680 (publicly available)  ADDED
a 1,2-diacyl-sn-glycero-3-phospho-(1D-myo-inositol) + ATP = a 1,2-diacyl-sn-glycero-3-phospho-(1D-myo-inositol-5-phosphate) + ADP + H+

Alan created the second reaction for GO:0052811  WAITING 
RHEA:63688a 1,2-diacyl-sn-glycero-3-phospho-(1D-myo-inositol-3-phosphate) + ATP = a 1,2-diacyl-sn-glycero-3-phospho-(1D-myo-inositol-3,4-bisphosphate) + ADP + H

**Comment by hdrabkin** [comment]
not yet as of 5/8/2020

**Comment by hdrabkin** [comment]
RHEA:63180 NADPH + 2 O2 = H+ + NADP+ + 2 superoxide
RHEA:63184 NADH + 2 O2 = H+ + NAD+ + 2 superoxide
However, neither is available publicly yet.

**Comment by pgaudet** [comment]
Hi @hdrabkin 

You wrote this: 

> moved the Reactome xref to the def for 0052811 .

1. Did you really remove the Reactome xref ? We should not do this, since this is being used to create the dbxrefs files. 

2. I. thought we had said we only used Rhea or PMIDs in the dbxref ? 

Thanks, Pascale

**Comment by deustp01** [comment]
@pgaudet @hdrabkin This thread started with the question of which of two possible GO terms a Reactome reaction should map to. I dug out the literature we used to make whatever mapping we made, and Harold went on from there to check the mappings and correct them as needed. I lost track of that part. I don't think we ever got to the policy level of deciding whether mappings should exist at all.

**Comment by pgaudet** [comment]
@hdrabkin and I discussed this - only Rhea should be used as Def xrefs, all others should be dbxrefs.

http://wiki.geneontology.org/index.php/Curator_Guide:_Enzymes_and_Reactions

There is still a lot of work to do to make all the xrefs and def xrefs consistent with those guidelines, but it seems a good idea to not add incorrect ones. 

Thanks for checking, 

Pascale

**Comment by hdrabkin** [comment]
I had to do it because after removing the id that was there, there was NO reference. I put in an interlibrary request for a PMID but have not gotten it yet, and I'm sure the RHEAs will be available on their June release.. So at least it would have a reference for the time being .

**Comment by pgaudet** [comment]
I see. I usually look for annotated papers - in this case I would have taken http://amigo.geneontology.org/amigo/reference/PMID:15249580

Thanks, Pascale

**Comment by hdrabkin** [comment]
Peter supplied refs for me based on the Reactome-ids; My experience with using annotated papers has not been great (rejected by RHEA because sometimes the paper may not have everything needed to precisely define the reaction; doesn't mean the annotation is incorrect, but that the detail needed for each reactant isn't there; I use them as a last resort, and since I was expecting to get a paper from my interlibrary loan, thought it would be ok for a day.

**Comment by hdrabkin** [comment]
RHEA now public RHEA:63688; add to GO:0052811; closing

**Comment by sjm41** [comment]
Thanks!
