### ISSUE TITLE
Integrated Stress Response

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#19153]
Hello Pascale (@pgaudet )

following our discussion please find a draft definitions for 2 new terms

Thanks

Sylvain

1) Create:
Category: Process
Name: Integrated stress response signaling
Definition: The series of molecular signals generated in response to diverse stress stimuli required to restore cellular homeostasis. The core event in this pathway is the phosphorylation of eIF2 alpha by one of four members of the eIF2a kinase family (EIF2AK1/HRI, EIF2AK2/PKR, EIF2AK3/PERK and EIF2AK4/GCN2), which leads to a decrease in global protein synthesis and the induction of selected genes, including the transcription factor ATF4, that together promote cellular recovery.
Synonym: ISR
Cross-ref:
PMID:27629041
https://en.wikipedia.org/wiki/Integrated_stress_response

Child of GO:0033554 cellular response to stress

parent of?
GO:0036499 PERK-mediated unfolded protein response
GO:0039585 PKR signal transduction

and we should maybe create terms for the 2 other downstream kinases EIF2AK1/HRI and EIF2AK4/GCN2 (there are Reactome terms for them)

Should be link the following terms to HRI? Not sure as there might be other stress responses not linked to Integrated stress response

GO:0035967 cellular response to topologically incorrect protein
GO:0034198 cellular response to amino acid starvation
GO:0042149 cellular response to glucose starvation
GO:1903916 regulation of endoplasmic reticulum stress-induced eIF2 alpha dephosphorylation
GO:1903917 positive regulation of endoplasmic reticulum stress-induced eIF2 alpha dephosphorylation
GO:1903912 negative regulation of endoplasmic reticulum stress-induced eIF2 alpha phosphorylation
GO:1903898 negative regulation of PERK-mediated unfolded protein response
GO:1903899 positive regulation of PERK-mediated unfolded protein response

Delete these terms? We already have Function terms for eiF2alpha phosphorylation/dephosphorylation
GO:0036497 eIF2alpha dephosphorylation in response to endoplasmic reticulum stress
GO:0036492 eiF2alpha phosphorylation in response to endoplasmic reticulum stress
GO:0060733 regulation of eIF2 alpha phosphorylation by amino acid starvation

2) Create:
Category: Process
Name: Response to mitochondrial stress
Definition:  Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of mitochondrial stress.
Cross-ref:
PMID:32132706, PMID:32132707

Child of GO:0033554 cellular response to stress
parent of GO:0034514 mitochondrial unfolded protein response

**Comment by ValWood** [comment]
This will be complicated.

As far as I know (I am not certain about this) there are  (at least) 2 things mixed here.

I suspect the "integrated stress response" is what fission yeast researchers call "core environmental stress response" (signals through MAP kinase pathway).
There are separate pathways for  (nitrogen) starvation and oxidative stress signalling through  different MAPK modules. The starvation one is the one which has the eiF2 alpha effector.

There  are also different responses for oxygen starvation (hypoxia), signalling in conjunction with ergosterol levels and through SPEBP signalling. This does not go through MAPK and is a different response.

Although some responses are common to many stresses, they are, as far as I know, often differently activated.

So I am not sure how well this suggestion would work across species. I think we might need to keep this more modular.

That said, I do agree that we should remove the "eiF1alpha de/phosphorylation terms", these just make thing more complicated than it already is (MF in BP ontology). Maybe that would be a good first task here?

**Comment by ValWood** [comment]
OK, "Integrated stress response" is also used by yeast (I have never seen it used by pombe, but  it is clearly adopted by yeast)

A useful recent review
https://www.ncbi.nlm.nih.gov/pubmed/29167799
This conserved stress response in yeast was termed the General Amino Acid Control (GAAC) because it was initially identified as a response to amino acid depletion that upregulates the genes required for amino acid synthesis 7. However, we now know that this same yeast stress response pathway is also activated by starvation for purines 8, glucose limitation/depletion 9, ER stress 10, growth on non-fermentable carbon sources like ethanol 9, high salt 11, treatment with alkylating agents 12, and TOR inhibition 13,14. As such, here we refer to this yeast stress response pathway by the name used in multicelluar eukaryotes, the Integrated Stress Response (ISR) 15. 


So it this   essentially a term to encompass ALL stress signalling?
That would be useful....
We proba bly need to keep the signalling pathways and the  *actual* responses separate.

**Comment by ValWood** [comment]
Also see:
https://github.com/geneontology/go-ontology/issues/13717
I tried to rationalize some of the  terms in this area because it seems very confusing.
Perhaps the first step would be to identify all of the terms in this area and then  see which ones mean the same, or related things?

I  was/am very keen to have a grouping term for PQC (protein quality control system)  as many papers seem to  use this as the broader grouping.   This  is becoming increasingly important. The paper I am reading right now:

"Because the hallmarks of many neurodegenerative disorders are aggregates of misfolded proteins (such as huntingtin in Huntington disease or beta-amyloid in Alzheimer disease), the presence of protein aggregates in cells has often been linked to toxicity, so that preventing aggregate formation and accumulation is still proposed to be a priority goal of the PQC system. However, recent evidence demonstrating active and regulated deposition of misfolded polypeptides into specialized cellular locations challenges the view that links aggregation and toxicity."
Chaperone-Facilitated Aggregation of Thermo-Sensitive Proteins Shields Them from Degradation during Heat Stress.
Cabrera M, Boronat S, Marte L, Vega M, Pérez P, Ayté J, Hidalgo E.
Cell Rep. 2020 Feb 18;30(7):2430-2443.e4. doi: 10.1016/j.celrep.2020.01.077.
PMID: 32075773

Perhaps a good approach would be to try to revise and group the PQC first, and then address the changes in response to starvation. I know that they overlap but they are also distinct.

**Comment by pgaudet** [comment]
- [x] Created new term 
+[Term]
+id: GO:0140467
+name: integrated stress response signaling
+namespace: biological_process
+def: "The series of molecular signals generated in response to diverse stress stimuli required to restore cellular homeostasis. The core event in this pathway is the phosphorylation of eIF2 alpha by one of four members of the eIF2a kinase family (EIF2AK1/HRI, EIF2AK2/PKR, EIF2AK3/PERK and EIF2AK4/GCN2), which leads to a decrease in global protein synthesis and the induction of selected genes, including the transcription factor ATF4, that together promote cellular recovery." [PMID:27629041]
+synonym: "ISR" RELATED []
+xref: Wikipedia:Integrated_stress_response
+is_a: GO:0033554 ! cellular response to stress
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19153 xsd:anyURI
+created_by: pg
+creation_date: 2020-05-26T08:04:10Z

 - [x]  Added children under new terms: 

-- GO:0036499 PERK-mediated unfolded protein response
-- GO:0039585 PKR signal transduction

- **Added new signaling terms under ISR**

- [x] HRI-mediated signaling
Exact synonym: EIF2AK1-mediated signaling

- [x] GCN2-mediated signaling
Exact synonym: EIF2AK4-mediated signaling

**Comment by pgaudet** [comment]
+
+[Term]
+id: GO:0140468
+name: HRI-mediated signaling
+namespace: biological_process
+def: "A series of reactions in which a signal is passed on to downstream proteins within the cell via HRI (also known as EIF2AK1), an intracellular protein kinase that is activated by stress signals." [PMID:27629041]
+synonym: "EIF2AK1-mediated signaling" EXACT []
+is_a: GO:0140467 ! integrated stress response signaling
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19153 xsd:anyURI
+created_by: pg
+creation_date: 2020-05-26T08:46:15Z
+
+[Term]
+id: GO:0140469
+name: GCN2-mediated signaling
+namespace: biological_process
+def: "A series of reactions in which a signal is passed on to downstream proteins within the cell via GCN2 (also known as EIF2AK4), an intracellular protein kinase that is activated by stress signals." [PMID:27629041]
+synonym: "EIF2AK4-mediated signaling" EXACT []
+is_a: GO:0140467 ! integrated stress response signaling
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19153 xsd:anyURI
+created_by: pg
+creation_date: 2020-05-26T08:47:25Z

**Comment by pgaudet** [comment]
@sylvainpoux Please give me any feedback on those terms.

**Comment by sylvainpoux** [comment]
Hi Pascale,

I slightly changed definitions for these 2 terms (I only added something about the type of stress that trigger these kinases, as each kinase is activated by a different stress)

Apart from that, your definitions are fine for me.

Many thanks

Sylvain

GO:0140468
HRI-mediated signaling
biological_process
A series of reactions in which a signal is passed on to downstream proteins within the cell via HRI (also known as EIF2AK1), an intracellular protein kinase that is activated by stress signals, such as heme deficiency, oxidative stress, osmotic shock, mitochondrial dysfunction and heat shock." [PMID:27629041]

GO:0140469
GCN2-mediated signaling
biological_process
"A series of reactions in which a signal is passed on to downstream proteins within the cell via GCN2 (also known as EIF2AK4), an intracellular protein kinase that is activated by stress signals, such as amino acid starvation." [PMID:27629041]

**Comment by pgaudet** [comment]
Also: 
- [x] GCN2-mediated signaling -> add subclass 'cellular response to amino acid starvation'

**Comment by pgaudet** [comment]
This is all we'll do for now.
