### ISSUE TITLE
Check terms related to 'GO:0031933 telomeric heterochromatin' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19188]
- [x] GO:0031933 telomeric heterochromatin will be obsoleted, see discussion in #19086

Those terms need to be reviewed and obsoleted, merged, or their labels & defs changed: 

 - [x]  GO:0031509 | 'telomeric heterochromatin assembly' | 2 EXP
Change label 'subtelomeric'
 - [x]  GO:1905547 | 'regulation of telomeric heterochromatin assembly' | 0 annotations 
Change label 'subtelomeric'
 - [x]  GO:1905548 | 'negative regulation of telomeric heterochromatin assembly' - 0 annotations 
Change label 'subtelomeric'
 - [x]  GO:1905549 | 'positive regulation of telomeric heterochromatin assembly' - 1 EXP
Change label 'subtelomeric' 

 - [x]  GO:1990152 | 'protein localization to telomeric heterochromatin' | 0 EXP merge into GO:1903213 | 'protein localization to subtelomeric heterochromatin' 

 - [x]  GO:1902682 |  protein localization to nuclear pericentric heterochromatin  | 3 EXP pombase  -> change label to protein localization to ~nuclear~ pericentric heterochromatin 

Val to advise on: 
 - [ ]  GO:0032121 | 'meiotic attachment of telomeric heterochromatin to spindle pole body' | 8 EXP pombase

**Comment by ValWood** [comment]
can you change label
GO:0032121 | 'meiotic attachment of telomeric heterochromatin to spindle pole body' | 8 EXP pombase
to meiotic attachment of telomeric repeat region spindle pole body?

All the annotations are to the repeat region components, and the paper used in the term does not mention chromatin

cheers
val

**Comment by ValWood** [comment]
This one is OK no
GO:0097355 protein localization to heterochromatin ??

**Comment by ValWood** [comment]
GO:0031509 | 'telomeric heterochromatin assembly' | 2 EXP
  GO:1905547 | 'regulation of telomeric heterochromatin assembly' | 0 annotations

merge into subtelomeric heterochromatin terms

**Comment by RLovering** [comment]
GO:1905547 | 'regulation of telomeric heterochromatin assembly' | 0 annotations has 1 experimental annotation, I agree that this needs to be revised but it is a bit worrying that you have listed it as having no annotations 
Q8N6T7 SIRT6 PMID:21847107
I had assumed that the regulation terms will be available still? 

Would it be possible just to rename the terms eg: 

  | GO:1905549                positive regulation of telomeric heterochromatin assembly

change to  positive regulation of subtelomeric heterochromatin assembly

Thanks

Ruth

**Comment by ValWood** [comment]
Hi Ruth, for these IIRC the reason a merge was not suggested was that not all of the genes annotated were "heterochromatin associated". Some were  telomere repeat associated.
If all the annotations would be OK, it could be merged/renamed instead (that would be better).

**Comment by RLovering** [comment]
well as there is only one annotation associated with regulation of telomeric heterochromatin assembly' I think this would be ok, although it would be good to define the start and end of the process itself as I wonder if SIRT6 is involved in the process rather than regulating it ;(

**Comment by ValWood** [comment]
I think I agree Ruth. Although I  have Sir2  directly to "chromatin assembly"  I have it annotated to  "regulation of H3-K9 methylation" but is this real regulation? @colinlog ?
Of course the  deacetylation is required for the H3-K9 methylation but is it regulatory, or just "causally upstream"?

Can we discuss on the next call?

**Comment by ValWood** [comment]
Hi @pgaudet 
GO:0032121 | 'meiotic attachment of telomeric heterochromatin to spindle pole body' 
I looked at this yesterday ignore for this ticket and deal with here (with some other related):
https://github.com/geneontology/go-ontology/issues/19229

**Comment by colinlog** [comment]
In 'regulatory', there is the concept of 'rate limiting' which is obviously
also an instance of 'causally upstream'.

A traffic light regulates car traffic by changing color. The receptors are
the drivers' eyes who detect the traffic light's color. The drivers
regulate their cars by pushing pedals and steering the wheel. etc...

A very strict definition for regulator could exploit the idea that :  "a
regulator is not part of the process itself" . However, this is a human
mind construction because some level of physical binding is a pre- for any
biochemical action and 'not being part of a process is therefore always a
bit of a fabrication/abstraction.

Some people in the cell cycle checkpoint field argued that the 'true'
checkpoint proteins, which I would equivocate to the 'regulators' we wish
to speak about, were dispensable for the cell division process itself but
were able to block the process when the checkpoint was activated. We do not
need the traffic lights to go from A to B. Hence, in a negative/inhibitory
regulation scenario, the 'true regulator/checkpoint protein is indeed not a
necessary part of the process, it will exert its effect by impinging on a
necessary (and therefore potentially rate limiting) component of the
process and stopping it from working. Activation then involves blocking the
blocker. In such chains made up of only negative interactions, the odd
numbered components are repressors and the even numbered components are
activators. For enzymes, regulatory subunits are proteins that stop the
intrinsic activity of the proteins they regulate. Then these regulatory
subunits must be subject to regulation themselves. How then to identify
what protein is the most upstream / master regulator who hears the
initiating signal for the process then? Does it exist, strictly speaking,
or is it all cycles of causally linked events?

Furthermore, what about the 'activator scenarios', where the regulator (the
car driver, the accelerator pedal, the injector for the carburator),
'hears' a message by binding something or changing in conformation and it
is then no longer the missing/too slow rate limiting protein factor for the
execution of the process? Can it then still be argued that 'true
regulators' / 'checkpoint factors' are not part of the process?

Deep down, biochemical regulation is always the fact that one thing changes
conformation (tertiary or quaternary), therefore that the regulator has at
least two states, ON or OFF.  Then, regulation implies the capacity of
intrinsic metastability. As many proteins are phosphoproteins, molecular
biology has many 'regulators. That is reality. In the real world,
regulation is itself a process that is best modelled as a transduction of
molecular signals that are causally upstream of each other. Two regulators
then do stand out: the 'receptor', at the beginning of the regulative
signal transduction chain and the 'effector'  located at the end of the
signal transduction chain which impinges on a necessary protein of the
regulated process. This argument is eerily similar to the request from Val
and others in the consortium to identify the beginning and the end of
biological processes, and of course, we do not mean fertilisation of the
oocyte and death of the multicellular organism, as there is so much more to
molecular cell biology and genetics.

For the specific example,
1. The Sir2 histone deacetylase i is recruited by its substrate, the
acetylated histone lysine.  Very annoying for the simplists. The antagonist
of the deacetylase, namely the acetylase, is in fact an activator of the
deaetylase activity, it is a pre-requisite for Sir2 to be able to exert its
biological role. And this is mutual, the acetylase can only work again if
the deacetylase provides it with an unacetylated histone, although arguably
the ribosome also feeds this system with unmodified histones, once per
histone. We may therefore have to consider the existence of cycles of
interactions and the fact that within these cycles one or the other
component is only rate limiting as a function of the level of activity of
the other components of the cycle. The sir2 deacetylase is only rate
limiting, it is only a 'regulator' at the telomere, if there is acetylase
activity to antagonise. (The motor's pistons in the cylinder need to go up
and down, there is a fuel injection phase and a fuel explosion phase)

2. The Sir2 histone deacetylase is recruited to the telomere by the
regulator Rap1 protein (wiki: Rap1 contains a Sir3-binding domain that
recruits Sir3 to the silencers.[14]
<https://en.wikipedia.org/wiki/SIR_proteins#cite_note-Morette_SIR_RAP1-14>
Once at the silencers, Sir3 recruits Sir4-Sir2 dimers to the chromatin
nucleation site. Sir2 then deacetylates histone H3 and H4 tails, and free
Sir3 binds the now-deacetylated lysine residues H4K16,79, and recruits
additional Sir4-Sir2 dimers to promote the further spreading of the
heterochromatin domain.) So Rap1 is the uptream regulator who 'hears' a
message. It regulates because it controls ab initio activity, it controls
initiation of the heterochromatin formation process at the telomere. (Rap1
is a bit like the key to the starter that the driver turns when it wants to
start the car)

I would argue that Rap1 is the true regulator because it binds not one
thing but two, it binds DNA and proteins. It integrates the DNA sequence
with cellular protein biochemistry so as to enrich subtelomeric regions
with the Sir2 deacetylase that then helps to promote and later maintain the
'silent/transcritpionally inactive state called heterochromatin. Sir2, Sir3
and Sir4 maintain/assemble the state. Rap1 conveys the prime signal.

So, my take home message is: sequence specific DNA binding transcription
factors *that depend on protein co-regulators* are a very particular class
of regulators of biological processes, they belong to a positive /
activator class of scenarios because they recruit an activity displayed by
their co-regulators (even if those are repressors of the process). *SIR2 is
an enzyme that is a TFs co-regulator, SIR2 is not as much of a regulator
itself.* However, there is a more upstream causality, the DNA. Rap1, as a
dbTF is in fact the DNA's co-regulator (the key is manipunlated by the
driver, the true regulator who decides everything, except the color of the
trafic light). Rap1, reads a continuous signal emanating from a non-protein
entity, in this case the DNA sequence, and 'tells' the other proteins about
it, it regulates them there when it is bound to its DNA target site.

Generally speaking: Regulated proteins interact with proteins or other
compounds that switch them between OFF and ON states. Regulator is a
construction of the mind whereby the beginning or the end of a signal
transduction cascade is considered as separate from (not strictly a
necessary part of) a metabolic process that is performed by other proteins
than those that transduce the signal, even though without the activators or
the repressors of the repressors the process does not take place.

Genetics may help too? For instance, epistasis distinguishes signal
transduction from biosynthesis in that the epistatic gene (whose mutant
phenotype occludes the other mutant's phenotype) is 'upstream' / 'acting
before' in a molecular biosynthesis pathway but 'downstream' / 'acting
after' in a signal transduction pathway. The points of switching from
downstream to upstream in epistasis direction may then be the proteins that
we could wish to call 'The Regulators' because will be 'at the ends' of the
perceived signal transduction cascade and affect the 'beginning' of the
metabolic process.

Receptors are regulators of what they regulate, but they are also their
ligand's co-regulators. Epistemologically we chose to call them the
regulators, often because the ligands for the regulators we consider are
cell extrinsic (electromagnetic radiation, proteins/metabolites) that
indicate a state outside the cell we are annotating the molecular process
to, or they are intracellular transport beginning or end-points for a
cargo, or for macromolecular biosynthesis processes like replication,
transcription and translation they are DNA or RNA sequences, that indicate
a spatial location inside the cell where something should (not) begin
happen. (After all, the traffic light changed color because it was
programmed to do that by a human, who arguably is the master regulator of
traffic, who delegated this regulatory task to an automaton programmed to
specifications determined by a committee of law-abiding and law sustaining
citizens!)

Curious to hear what you think 13h30 Thursday?

**Comment by ValWood** [comment]
Sorry I did not respond to this. Very interesting.
I have been thinking a lot about regulation and  we really do need to pin down what we mena by regulation in GO (maybe multiple things).

I have lots of questions for you!


At pombase we reviewd all annotation to 'biological regulation'  back in 2017 ( gosh it seemed like last year)
After review everything seemed to fit into one of these "types"


1. Regulation is either upstream of a process (or downstream?)
2. OR it is regulation of a biological quality
3. Upstream regulation can be signal transduction/ regulation of gene expression/catabolism
or substrate availability ( some cases of substrate availability  will be independent of signal transduction)
4. Within process regulation can be
i). Direct regulation of a molecular function (activity or binding)
ii) Regulation of pathway "decision" for a branched pathway within a process (e.g. within DNA repair process-specific pathway choices can be regulated, or "mating-type switching/imprinting)
iii) Regulation of localization 
iv) Rate limiting  (slowest) step usually within a metabolic pathway
v) Operating within a process to negatively regulate the process whilst some step is completed or correction is made (I guess this is always going to be a class of  i) eventually, but sometimes we don't know the specific MF that is regulated, but  know that it is "within pathway" regulation)

This seems to be along the lines you are saying so maybe we can integrate

I tend to think of the within process regulation of an activity as "part_of" the broader process, but it might be regulation of a sub-process.

Cytokinesis provides a good illustration of this.
https://github.com/pombase/curation/issues/2245
