### ISSUE TITLE
GO:0006836 only_in_taxon Metazoa is too strict, "neurotransmitters" are also used by other taxons

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#19198]
SGD is receiving failed taxon constraint notices for the following GO IDs under "GO:0006836 only_in_taxon Metazoa  :
GO:0015812 gamma-aminobutyric acid transport       
GO:0001761 beta-alanine transmembrane transporter activity
GO:0015220 choline transmembrane transporter activity   
GO:0015871 choline transport                         
GO:0015187 glycine transmembrane transporter activity
GO:1904983 glycine import into mitochondrion       
GO:0015495 gamma-aminobutyric acid:proton symporter activity
GO:0005313 L-glutamate transmembrane transporter activity
GO:0015187 glycine transmembrane transporter activity
GO:1904983 glycine import into mitochondrion       
GO:0005313 L-glutamate transmembrane transporter activity

These restrictions seem to be too strict, for GABA in plants see PMID:12223787 "GABA is a four-C, nonprotein amino acid found in virtually all prokaryotic and eukaryotic organisms as a significant component of the free amino acid pool",  see also yeast pathways: https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?object=YEAST-4AMINOBUTMETAB-PWY

**Comment by pgaudet** [comment]
@krchristie is working on those. 

@suzialeksander those should only trigger warnings, but the annotations should still be exported. 

Thanks, Pascale

**Comment by krchristie** [comment]
Looking at "glycine transmembrane transporter activity", it is being placed under "neurotransmitter transmembrane transporter activity" due to an inference rather than being directly asserted, so I think this will go away as soon as we stop reasoning over ChEBI roles. We've come up with a plan, so we should be fixing this soon now.

**Comment by RLovering** [comment]
Hi Karen

Please could you confirm what will happen for annotations associated with the specific chemical  child terms for GO:0006836 neurotransmitter transport. ie will the new ontology require curators to curate to both the specific chemical transported term and to the GO:0006836 neurotransmitter transport term? And if so will the new required annotations be created automatically or will there be a spreadsheet advising additional curation.

Thanks

Ruth

@ShirinSaverimuttu

**Comment by RLovering** [comment]
Hi Karen

also I should have said that Shirin had asked me the following:

1. whether dopamine transport should be a child of GO:0006836 neurotransmitter transport 
2. that histamine transport should not be a child of GO:0006836 neurotransmitter transport
3. that Serotonin transport should remain a child of GO:0006836 neurotransmitter transport

Obviously without knowing how you plan to address this problem it is difficult for me to advise her

Best

Ruth

**Comment by krchristie** [comment]
> Hi Karen
> 
> Please could you confirm what will happen for annotations associated with the specific chemical child terms for GO:0006836 neurotransmitter transport. ie will the new ontology require curators to curate to both the specific chemical transported term and to the GO:0006836 neurotransmitter transport term? And if so will the new required annotations be created automatically or will there be a spreadsheet advising additional curation.
> 
> Thanks
> 
> Ruth
> 
> @ShirinSaverimuttu

Hi @RLovering & @ShirinSaverimuttu 

There are already numerous neurotransmission specific terms for various neurotransmitters, e.g.

![neurotransmissionSecretionChildren](https://user-images.githubusercontent.com/10533218/79801501-18af9980-8313-11ea-9639-9e80fe80c40e.png)

So, if people want to annotate to secretion of a specific compound as a neurotransmitter, they should use the specific term for neurotransmission via that compound.

> Hi Karen
> 
> also I should have said that Shirin had asked me the following:
> 
>     1. whether dopamine transport should be a child of GO:0006836 neurotransmitter transport
>     2. that histamine transport should not be a child of GO:0006836 neurotransmitter transport
>     3. that Serotonin transport should remain a child of GO:0006836 neurotransmitter transport
> 
> Obviously without knowing how you plan to address this problem it is difficult for me to advise her
> 
> Best
> 
> Ruth

For these more general terms, I think it is a problem to have a generally named term that has an implicit more specific meaning, e.g. ALL `serotonin transport` is a type of `neurotransmitter transport`. This gets us into trouble when we have compounds like acetylcholine that is often a neurotransmitter but can also be a hormone. Looking right now at serotonin terms, it seems that this may be a problem with serotonin also since `serotonin secretion by platelet` seems unlikely to be a type of `neurotransmitter transport`

![serotoninSecByPlatelet](https://user-images.githubusercontent.com/10533218/79803480-ec961780-8316-11ea-87f8-203103ce594b.png)

Thus, my thoughts at the moment are that if you are using a specific term like `serotonin secretion, neurotransmission`, you  will be fine because this is already specific with respect to compound and to neurotransmission. However, I think that annotation review may be required if you are using more general terms like `serotonin transport` if you also want that to say that this instance of `serotonin transport` is a type of `neurotransmission`. 

I don't know that I can say anything further at the moment and I haven't compiled the annotations for the `neurotransmitter` role yet.

**Comment by pgaudet** [comment]
I think this is fixed with the removal of chebi roles. SGD has no taxon constraints violations in the latest GO release, http://release.geneontology.org/2020-10-09/reports/gorule-report.html
