### ISSUE TITLE
Definitions sometimes have newlines and other escaping oddities (in some exports)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#19199]
We have recently run into an issue on the GO helpdesk where a user trying to get bulk definitions from Solr was having trouble parsing the TSV file due to newlines appearing in the definitions. For example, in `GO:0015897 organomercurial transport`. I would assume given how few definitions have this that this is not the intention.

As well, the quotation pattern in `GO:0099568 cytoplasmic region` seems to generate triple quotes (`"""`) at the end of the definition. Two questions here. 1) why is the use of quotes not standard in GO (i.e. the definition should not be a quote) and 2) Have checks or guidelines on how quotes are used.

It could be that some of these issues are due to issues in owltools, but the newline thing seems like it might be good as a general rule.

Tagging @cmungall

**Comment by cmungall** [comment]
generally it's very easy to accidentally insert these when using Protege.

Technically it's perfectly valid to have newlines inside, and these should always be escaped on emission to other formats. However, there is no reason to have these, we should replace them with spaces. For this we can have a general robot check: https://github.com/ontodev/robot/issues/664

The quotes is harder. What is happening here is that there is an accidental quote in the def of GO:0099568. This is escaped leading to `\""`. Depending on the output format different escaping rules may apply.

This is harder to check for accidents vs intentional use of quotes inside defs. We could at least check for quote balancing, but that would yield false positives where this is intentional (e.g. double or single quotes as shorthand for feet/inches - not something we'd generally need to do in GO, but some ontologies may need this, so a robot check may be inappropriate).

We could simply ban all quote characters in defs as a GO specific rule, I'm perfectly happy with this as a stylistic choice, I dislike scare quotes as they detract from having simple concise textual definitions, e.g there is no reason to have them here:

```
def: "The process where the \"Cap structure\" (composed of a 7- methylguanosine (m7G) group and associated cap-binding proteins) located at the 5' end of an mRNA molecule, which serves as a \"molecular tag\" that marks the spot where the 40S ribosomal subunit is recruited and will then scan in a 5' to 3' direction until an AUG codon is encountered in an appropriate sequence context to initiate mRNA translation." [PMID:17284590, PMID:19604130]
```

**Comment by pgaudet** [comment]
Affects GO:0015897, GO:1905011, GO:0090481, GO:0090480, GO:0140261, and GO:0120078

**Comment by pgaudet** [comment]
I removed the offending characters from the definitions. @balhoff Can you add a check for this ? 
Thanks, Pascale

**Comment by ukemi** [comment]
25 terms have " in the definition.

**Comment by pgaudet** [comment]
@cmungall What's the rule WRT quotes ? Single but no double quotes are allowed ?

**Comment by pgaudet** [comment]
Checks to add: 
- New line character
- Double quote (to be confirmed, but I think now they all all removed from the definitions. I used commas, parenthesis or in a few cases single quotes)
- Definition must end with a period
- 'comment=' should not be allowed (this is a comment mistake because in Protégé it is the default type of new annotation. 

@balhoff can you implement those?

**Comment by pgaudet** [comment]
I added this to the next ontology call so everyone is aware of the guidelines. 
I'll update the documentation.

**Comment by balhoff** [comment]
> 'comment=' should not be allowed (this is a comment mistake because in Protégé it is the default type of new annotation.

@pgaudet do you mean the text "comment=" inside a definition? Or using the comment property instead of the definition property? It it's the latter we can't really prevent it since comment is part of OBO, but at least providing more than one should already be caught).

**Comment by pgaudet** [comment]
No - the text `comment=` (comment followed by =) should not be found anywhere. 
Real comment tags start with `colon:`

Thanks, Pascale

**Comment by balhoff** [comment]
@pgaudet there are 703 terms with definitions that don't end with a period. They all seem to be catalysis:

```
term,definition,reason
http://purl.obolibrary.org/obo/GO_0102614,"Catalysis of the reaction: germacra-1(10),4,11(13)-trien-12-oate + NADPH + O2 + H+ <=> 8beta-hydroxy-germacra-1(10),4,11(13)-trien-12-oate + NADP + H2O",Definition does not end with a period.
http://purl.obolibrary.org/obo/GO_0103073,Catalysis of the reaction: anandamide + H2O <=> arachidonate + ethanolaminium(1+),Definition does not end with a period.
http://purl.obolibrary.org/obo/GO_0102887,"Catalysis of the reaction: 2-trans,6-trans-farnesyl diphosphate <=> beta-sesquiphellandrene + diphosphoric acid",Definition does not end with a period.
http://purl.obolibrary.org/obo/GO_0102615,"Catalysis of the reaction: ent-cassa-12,15-diene + NADPH + O2 + H+ <=> 2alpha-hydroxy-ent-cassadiene + NADP + H2O",Definition does not end with a period.
```

Should we append periods to all these?

**Comment by pgaudet** [comment]
> Should we append periods to all these?

Yes please !
