### ISSUE TITLE
cytolysis

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#19207]
Hi
This term GO:0001897 cytolysis by symbiont of host cells can have a taxon ID added
But with this term adding the taxon ID leads to an error GO:0001900 positive regulation of cytolysis by symbiont of host cells

Is this intentional or is there something missing?

Thanks

Ruth

**Comment by RLovering** [comment]
After discussion with Pascale we realised that the GO:0001900 positive regulation of cytolysis by symbiont of host cells term should have Taxon ID option available in Protein2GO.

Alex please can you look at the 'transitive' transfer of rules to the regulation terms

Thanks

Ruth
@alexsign

**Comment by alexsign** [comment]
@RLovering @pgaudet 
I think it works as designed because there is no "Is a" or "Part of" relationships between GO:0044419
and GO:0001900
https://www.ebi.ac.uk/QuickGO/term/GO:0001900

"Extra Tax Id can only be used with terms that are descendants of GO:0044419 (interspecies interaction between organisms) or GO:0018995 (host cellular component)" it's implemented in the Protein2GO just error message is wrong. I need to update the error message at some point.

**Comment by pgaudet** [comment]
ok thanks Alex. Why not also include 'regulates' ? 
Otherwise I'll create a 'regulation of interspecies interaction' grouping term.

**Comment by pgaudet** [comment]
Hi @RLovering 
Thanks for pointing this out. I have modified gorule-0000015 
@alexsign has been notified, this will trickle into P2GO soon. 

Thanks, Pascale
