### ISSUE TITLE
mitigation, final fixes

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19237]
from
https://github.com/geneontology/go-ontology/issues/18357

we have 3 "mitigation terms"
Would like to if possible reclassify as "evasion" or "supression"

All related to viral  host interactions
<img width="448" alt="Screen Shot 2020-04-07 at 14 53 41" src="https://user-images.githubusercontent.com/7359272/78677367-90c39b80-78df-11ea-9bd6-a6299321de0a.png">

but there seems to be some redundancy/strangeness  in the parentages?

1. The term
GO:0030683   mitigation of host immune response by virus
has the parent

GO:0050690    regulation of defense response to virus by virus
!!!!

**Comment by ValWood** [comment]
in the old ticket patrick @pmasson55  said

Concerning viral immunoevasion i guess it should go to evasion.
For the Interferon antiviral system evasion, I would put it in suppression because viral proteins counteracts and suppress the antiviral response.
For the third one, "Evasion of host immunity by viral interleukin-like protein", it s tricky because there are both evasion and suppression. Evasion is for example down-modulation of MHC class I expression (degradation or mislocalization) or interference with the antigen binding/presentation process. However the system is not shut-off, so I guess it could go to evasion...
Hope this helps

**Comment by pgaudet** [comment]
> GO:0050690 regulation of defense response to virus by virus

Has no annotations. 

Merge into child GO:0030683 mitigation of host immune response by virus

**Comment by pgaudet** [comment]
> we have 3 "mitigation terms"
Would like to if possible reclassify as "evasion" or "supression"

I can create parents 'evasion' and 'suppression' and get rid of the grouping terms ?

**Comment by pgaudet** [comment]
ACTION from 2020-04-23 Multi-organism call: 
 look at terms under mitigation and see if some terms can be merged.

**Comment by dsiegele** [comment]
2020-04-23 Summary of multiorganism call
Bkgd: Previously, GO:0030682 'evasion or suppression of host defenses by symbiont' was renamed 'mitigation of host defenses by symbiont'. The idea was to use 'mitigation' as a grouping term with child terms of 'suppression of...' and 'evasion of.......'  
[issue #17905](https://github.com/geneontology/go-ontology/issues/17905)   

- Merge modulation into mitigation whenever possible, but need to review child terms.  See ACTION item above
     i) Many of the "induction of ...." terms refer to normal host defenses and can be gotten rid of.
    ii) May be able to merge some of the child terms. Some of the existing child terms look like read-outs rather than processes. Look at these in the context of effector-mediated terms. 
     - May need to make additional effector-mediated terms. 

- need new terms to capture when symbiont pathogen isn't trying to protect itself from the immune system, but is hijacking immune response for it's own benefit, e.g. nectrophic pathogens 

- Still need to resolve question of what child terms to have for GO:0030682 'mitigation of host defenses by symbiont'
     - suppression, evasion, tolerance
     - is antigenic variation a type of evasion of host defenses

- Recommendation to annotators: Use more general terms for biological process, and, if have more information about a molecular target, capture that information as a molecular function: inhibits xx activity

**Comment by ValWood** [comment]
I said I would provide  examples of how we hook up MF to BP

example session 1

https://canto.phi-base.org/curs/bd02fdb6831712ca/ro/

(Note, I'm not happy with the term name here  now)

GO:0140295 	pathogen-derived receptor ligand activity


This is an pathogen effector that interacts with a  host receptor to  
increase or reduce signalling (depending whther a necrotroph or biotroph)

But the term is a bit passive. It should be reworked as some sort of 
'receptor decoy'

but you can see that we can couple the  pathogen protein, use the host 
receptor as input, and link to the process, in this case

effector-mediated induction of plant hypersensitive response

Below the GO annotation you can see the assays that were done in this paper (i.e all the phenotypes). We collect all these as the core of the PHI base work is to  link
specific host/pathogen genotypes (multispecies genotypes), to virulance and avirulence phenotypes

In this example

*https://canto.phi-base.org/curs/cc6cf06675cc6e13/ro/ *

P. striiformis 	PSTG_12806

inhibits T. aestivum


petC 	GO:0009496 	plastoquinol--plastocyanin reductase activity

The purpose of this interction is not to inhibit respiration per se, but 
to inhibit oxidative species production  which is a PTI immune response. 
This interaction results in cell death, but the fungi (which in this 
case feeds on live plant material), obtains nutrients from neighbouring 
cells.

I would not say we have got all of this quite right yet. But we are 
constantly tweaking as we build PHIPO, and understand the terms in GO 
and the biology.

**Comment by mgiglio99** [comment]
Hi all,

(I know we went over some of this last time - but I'm still a bit confused - sorry.) My recollection of the original plan from the fall was that all 'evasion' and 'suppression' and 'tolerance' terms were to be joined together under the new name 'mitigation'. One of the reasons for this was so that we wouldn't have to decide when something was an evasion or tolerance or whatever - as long as it was somehow "dealing with" the host defenses it could go under mitigation. I gather some of that happened but not all and that the plan changed once the process got started.  This particular ticket was made with the goal of getting rid of the mitigation terms that were made last fall and returning to having separate branches for evasion, suppression, etc. - is that correct? 
I've tried to take a step back so I can wrap my head around the modulation, evasion, tolerance, and suppression terms with the hope of understanding the overall structure. It is confusing, as we all know, and that's, of course, what we're trying to fix.
Some overall questions I have:
--Based on the notes from last meeting, I'm not sure if we are still trying to get rid of the mitigation node or not. Pascale's posted action item talks about merging the mitigation terms (presumably into other terms), while Debby's notes talk about merging modulation terms into mitigation terms. 
--If we are keeping mitigation, are we thinking of making evasion, suppression, etc all be children of it?

With regard to specific notes from last time:
> need new terms to capture when symbiont pathogen isn't trying to protect itself from the immune system, but is hijacking immune response for it's own benefit, e.g. nectrophic pathogens PMID: 22303261

We have this term: 'effector-mediated induction of plant hypersenstive response by symbiont' (a grandchild of 'mitigation of host defenses by symbiont).  I think this is the term we need - but it has parentage all over the tree in places that seem incorrect to me. I think it should only be under 'interspecies interaction between organisms' - but it also has parentage in the "regular" single organism 'regulation of cell death'. To remind us, this process is when a pathogen effector protein interacts with a plant resistance protein and the hypersensitive response results. The def clearly states this is a symbiont process. This term should be for symbiont proteins, not for plant proteins. And it seems to me that it shouldn't have parentage in the "regular" single organism tree. Also, I wonder if avoiding the word "induction" would be helpful - should we try instead to capture this a different way - perhaps something like 'effector-mediated triggering of hypersensitive response by symbiont'?

A question from last time:

> is antigenic variation a type of evasion of host defenses

I would say yes it is.

As an aside, as I was looking at this area of the tree I was wondering:
Do we need special virus terms? Can't the virus terms just be generic? So could we merge 'mitigation of host defenses by virus' into its parent ('mitigation of host defenses by symbiont')?
And could we remove the virus references from the children of 'mitigation of host defenses by virus' - for example change 'DNA end degradation evasion by virus' to 'evasion of DNA end degradation by symbiont'
And same for other children.

I better stop here. There's a bunch of other confusing stuff for me - but this post might never end if I keep going.

**Comment by ValWood** [comment]
Re:
> I think it should only be under 'interspecies interaction between organisms' - but it also has parentage in the "regular" single organism 'regulation of cell death'. 


Yes, I think you are right. Historically we used to link things up to the single organism process they were regulating. But this isn't really correct.I agree these relationships should be removed.

I agree about the taxa-specific terms too. My preference would be to remove them entirely because   keeping them will require nearly every term to have multiple instantiations. This is only one example of 100's but it is probably not a controversial one.

**Comment by pgaudet** [comment]
@ValWood 
What needs to be done here? We should perhaps close this and create a new ticket with a more up to date task?

**Comment by ValWood** [comment]
I'm happy for this ticket to close. I can't remember precisely why we wanted to get rid of it. I quite like 'mitigation' for some contexts. I guess it means the same as 'defense response' though?

**Comment by pgaudet** [comment]
Oh - I thought it was for 'suppression', in cases where that term doesn't make sense.

**Comment by ValWood** [comment]
It might be. My memory is hazy....

**Comment by pgaudet** [comment]
OK if we cannot remember, I'm closing.

**Comment by mgiglio99** [comment]
This whole issue I found very confusing - way way back we decided to use "mitigation" to group things that were evasion,suppression or tolerance. (see comments above from Debby on April 23 2020 and me on May 6  2020). Then at some point I think there was a decision to get rid of the ''mitigation" terms, but I wasn't part of that decision and so I'm not  clear on why. What I fear is that we are now somewhere between implementation of the original plan from fall of 2019 and whatever the new plan was from spring of 2020.
