### ISSUE TITLE
nuclear chromosome, telomeric region

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19232]
nuclear chromosome, telomeric region
should merge into 
chromosome, telomeric region
(at present it has only one child, nuclear subtelomeric heterochromatin, but is also used for non-heterochromatin proteins)

**Comment by pgaudet** [comment]
In this case I would also merge 
'nuclear subtelomeric heterochromatin' 
into 'chromosome, subtelomeric region' 

@RLovering @colinlog please confirm this is ok.

**Comment by RLovering** [comment]
'nuclear subtelomeric heterochromatin' has 3 parents.
 GO:0000784 nuclear chromosome, telomeric region
 GO:0005720 nuclear heterochromatin
 GO:0099115 chromosome, subtelomeric region

and 'nuclear chromosome, telomeric region' has 3 parents:
 GO:0005634 nucleus
 GO:0000228 nuclear chromosome
 GO:0000781 chromosome, telomeric region

Then the proposal is that:
VAL: chromosome, telomeric region
> nuclear chromosome, telomeric region (merged into parent)

PASCALE: chromosome, subtelomeric region
> nuclear subtelomeric heterochromatin  (merged into parent)

1. I don't think Val's suggestion would be a good idea unless  GO:0000781 chromosome, telomeric region was given the parent GO:0000228 nuclear chromosome
But I do think that the parent relation to nucleus is not required for 'nuclear chromosome, telomeric region'  as long as there is the parent term GO:0000228 nuclear chromosome. Otherwise people will have to co-annotate to GO:0000228 nuclear chromosome and GO:0000781 chromosome, telomeric region.

2. WRT Pascales suggestion: I'm sorry but I haven't been following the heterochromatin discussion. If heterochromatin or equivalent term is being kept then this would only make sense if the chromosome, subtelomeric region term has a relation to heterochromatin. And I can't remember if all of the subtelomeric region is heterochromatic or whether it has some genes within this region.

Ruth

**Comment by ValWood** [comment]
I have moved all of our subtelomeric heterochromatin annotation to this term!
If anything is changed it should only  be to rename to  "subtelomeric heterochromatin" but please don't merge into a non-heterochromatin term. It took me ages to reannotate these.

I am happy to keep the nuclear terms. The only reason I suggested that we remove 'nuclear' from the chromosome terms and merge into a non-nuclear parent  is that these terms cause problems for higher eukaryotes and other species that undergo a  open mitosis (and a nuclear chromosome is not a different entitiy than a non-nuclear chromosome). For fission yeast, which does closed mitosis the chromosomes are always nuclear so the current arrangement is fine.

**Comment by colinlog** [comment]
Ruth said "And I can't remember if all of the subtelomeric region is heterochromatic or whether it has some genes within this region."
The answer is: there are many organisms with subtelomeric genes, and these are heterochromatin. However, it is not at all clear that this is **always** true (subtelomeric genes, and heterochromatin' for organisms nor chromosomes within one species. For instance, the rRNA genes at the acrocentric p arms (13, 14, 15, 21, 22) ar econsidred heterochromatin, except when they are transcribed, then they are nucleolar.

Altogether, I would argue that 'GO:0000792 (CC) heterochromatin' is here to stay and it can have children that indicate in what part of the chromosome it is located (subtelomeric, pericentric or neither of these). These are CC aspect terms. However, it is not handy to merge 'chromosome, subtelomeric region GO:0099115 (CC)' and 'heterochromatin GO:00000792 (CC)' because some CC, MF and BP terms can be children of both, but these two terms can be separate from each other. Both are descendants of 'GO:00005694 (CC) chromosome', via GO: chromatin GO:0000785 (CC) or via  'chromosomal region GO:0098687 (CC)' This branch is fine. 
What is somewhat inconsistent/confusing is that nuclear is usd as  qualifier for subtelomeric heterochromatin but not for pericentric heterochromatin and not heterochromatin (GO:1990707 (CC) nuclear subtelomeric heterochromatin, GO:0005721 (CC) pericentric heterochromatin and GO:0000792 (CC) heterochromatin. The terms 'GO:0005720 (CC) nuclear heterochromatin ' and ' GO:0000790 nuclear chromatin  (CC)' all have nuclear as qualifier. So, let's discuss how to make this consistent. Everything is possible and therefore we 
(i) remove nuclear from everywhere and just make them kids of 'nucleus'.  This is the most economical in terms of reducing term proliferation. However, it negates nuclear membrane breakdown, as Val points out. 
(ii) Duplicate all the terms so as to have a 'nuclear' and '_not nuclear_' version of the terms. thi sis alread the case for heterochromatin (790) that also exists as nucear heterochromatin (5720)
(iii)  we identify the branches that will need a non-nuclear aspect? For example kinteochore is the non-nulcear aspect of the centromere in open mitosis organisms?

In any case, I would argue that it is worthwhile considering aligning pericentric heterochormatin and subtelomeric heterochormatin terms ancestry in the CC branch. It is weird that subtelomeric heterochromatin is nuclear but pericentric heterochormatin is '_not nuclear_'.

**Comment by ValWood** [comment]
Re:
 Everything is possible and therefore we
(i) remove nuclear from everywhere and just make them kids of 'nucleus'. This is the most economical in terms of reducing term proliferation. However, it negates nuclear membrane breakdown, as Val points out.
(ii) Duplicate all the terms so as to have a 'nuclear' and 'not nuclear' version of the terms. this is already the case for heterochromatin (790) that also exists as nucear heterochromatin (5720)
(iii) we identify the branches that will need a non-nuclear aspect? For example, kinteochore is the non-nuclear aspect of the centromere in open mitosis organisms?

i) would not be correct because for many species this would not always be true (although it would always usually be true). It might  result in  logic problems if  'hardcoded' in the ontology

ii) and iii) are essentially the same solution and would cause a proliferation of nuclear and non-nuclear terms.   These  are a bit confusing for curators because they are often not sure why both terms exist (especially for species with closed mitosis where centromeres and telomeres are always nuclear. We can see this because, many annotations use the non-nuclear terms.

 An alternative solution is to remove the nuclear parentage, and merge the existing terms into a non-nuclear term. This solution would require concurrent annotation to nucleus (but the nuclear observation is usually from different experiments or is an additional observation from a single experiment, so I would not have a problem with this).  It would also be possible to fill annotation gaps by inference.  So, annotations to terms under chromosome which also were  "always sometimes nuclear" (i.e anything centromere, telomere or descendants)  could have a "nucleus" annotation inferred. This might seem a complicated  solution but it might give more consistent annotation across the board. 

@cmungall is there any precedent for doing something like this (I'm sure we have not done it in GO, but elsewhere?). I have previously wondered if we could use such inferences for the has_part type annotations which are sometimes but not always true.

**Comment by ValWood** [comment]
closing, as is essentially duplicate of:
https://github.com/geneontology/go-ontology/issues/20000
