### ISSUE TITLE
NTR: prenylated FMNH2 binding, prenylated FMNH2 biosynthetic process

### ISSUE THREAD

**Issue by keseler** [geneontology/go-ontology#19244]
Ran across this when trying to clean up the cofactor/coenzyme annotations in EcoCyc.  Prenylated FMNH2 acts as a coenzyme for UbiD.  So I'd need the specific binding term under the coenzyme binding class and the biosynthetic process term under the coenzyme biosynthetic process class.  PMIDs 25647642, 26083754, 26083743.
Thanks!
-Ingrid

**Comment by krchristie** [comment]
Hi @keseler 

I have made the terms you requested, except that since the coenzyme grouping terms are gone, they aren't subclasses of those terms, but are automatically classified under the appropriate chemical classes based on having used the ChEBI term for `prenyl-FMNH2` in the equivalence axioms.

Also, since ChEBI uses the name `prenyl-FMNH2`, I have used that nomenclature in the main term names, and have used `prenylated FMNH2` in synonyms.

Here are the terms I've created. Please let me know if you see anything amiss.

Thanks,

-Karen

+[Term]
+id: GO:0120232
+name: prenyl-FMNH2 biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in prenyl-FMNH2, an essential cofactor for the decarboxylase enzymes UbiD and Fdc1." [GOC:krc, PMID:25647642, PMID:26083743, PMID:26083754]
+synonym: "prenyl-FMNH2 anabolism" EXACT []
+synonym: "prenyl-FMNH2 biosynthesis" EXACT []
+synonym: "prenyl-FMNH2 formation" EXACT []
+synonym: "prenyl-FMNH2 synthesis" EXACT []
+synonym: "prenylated FMNH2 anabolism" EXACT []
+synonym: "prenylated FMNH2 biosynthesis" EXACT []
+synonym: "prenylated FMNH2 biosynthetic process" EXACT []
+synonym: "prenylated FMNH2 formation" EXACT []
+synonym: "prenylated FMNH2 synthesis" EXACT []
+is_a: GO:0044271 ! cellular nitrogen compound biosynthetic process
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:87531 ! prenyl-FMNH2
+created_by: krc
+creation_date: 2020-06-30T19:09:11Z

+[Term]
+id: GO:0120233
+name: prenyl-FMNH2 binding
+namespace: molecular_function
+def: "Interacting selectively and non-covalently with prenyl-FMNH2, a flavin mononucleotide obtained by prenylation of the N-10 position of FMNH2 followed by cyclisation. An essential cofactor for the decarboxylase enzymes UbiD and Fdc1." [GOC:krc, PMID:25647642, PMID:26083743, PMID:26083754]
+synonym: "prenylated FMNH2 binding" EXACT []
+intersection_of: GO:0005488 ! binding
+intersection_of: has_input CHEBI:87531 ! prenyl-FMNH2
+created_by: krc
+creation_date: 2020-06-30T19:32:01Z

**Comment by alanbridge** [comment]
Hi, 

would you consider using CHEBI:87467, the major microspecies of prenyl-FMNH2 at pH7.3 and the form used in Rhea and UniProt?

https://www.rhea-db.org/searchresults?q=CHEBI%3A87467
https://www.uniprot.org/uniprot/?query=CHEBI%3A87467&sort=score

pinging @amorgat 

All the best, Alan

**Comment by krchristie** [comment]
> Hi,
> 
> would you consider using CHEBI:87467, the major microspecies of prenyl-FMNH2 at pH7.3 and the form used in Rhea and UniProt?
> 
> https://www.rhea-db.org/searchresults?q=CHEBI%3A87467
> https://www.uniprot.org/uniprot/?query=CHEBI%3A87467&sort=score
> 
> pinging @amorgat
> 
> All the best, Alan

Thanks for the suggestion. I'll try to be more alert to looking for the biologically relevant species in the future, but always happy to get feedback if I miss something.

-Karen
