### ISSUE TITLE
New term for Dicty response to nutrient / food

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#19278]
Dicty feeds on bacteria in the soil, or in the lab on bacteria plated on agar. When they feed they proliferate, we call it growth.
I have a paper that identified genes and suggests genetic pathways that control breakdown/digestion of gram-positive and gram-negative bacteria (PMID: 23664307). 

Can these dicty food categories be added under:
 
GO:0031670: cellular response to nutrient
New: cellular response to gram-positive bacterium
New: cellular response to gram-negative bacterium

I'm also open to any other suggestions how to capture Dicty ability to break down these gram+ or gram- bacteria.

Thanks!

**Comment by pgaudet** [comment]
Hi @pfey03 

This is not really working as response to nutrient because the terms you propose can also be defense responses. 

Either you can co-annotate or we could create more precise terms, 
- cellular response to gram-positive bacteria as food source
- cellular response to gram-negative bacteria as food source

@ValWood @mgiglio99 any thoughts on this ?

**Comment by pgaudet** [comment]
@krchristie 
On a slightly different topic, 'nutrient' is also a role. This is also causing bad inferences: Children of  GO:0007584 response to nutrient are : 

* GO:0051780 behavioral response to nutrient
* GO:0031670 cellular response to nutrient
* GO:0009594 detection of nutrient
* GO:0033198 response to ATP
* GO:1905429 response to glycine
* GO:1903576 response to L-arginine
* GO:1902065 response to L-glutamate
* GO:1904844 response to L-glutamine
* GO:0000304 response to singlet oxygen
* GO:0033273 response to vitamin 


Maybe the best solution is to merge into  GO:0032094 response to food / GO:0071240 cellular response to food, since nothing seems to get further inferred from 'food role'.

**Comment by ValWood** [comment]
I'm not sure. I had a look at the paper and the model isn't very 'fleshed-out' so I wondered if there is anything more recent.

This 2020 paper  conclusion says

 Second, in all these studies (Farbrother et al., 2006; Carilla-Latorre et al., 2008; Sillo et al., 2008; Nasser et al., 2013), including the present study, **it is not possible to disentangle completely metabolic adaptation from bacterial sensing**: bacteria are both a source of nutrients, and a source of extracellular signals. In the current study M. luteus did not induce any major change in gene expression and this observation suggests that the physiology and transcriptome of D. discoideum cells is not perturbed in this setup simply by the fact that bacteria represent an alternative food source to HL5c. Third, it is not easy to relate the observed changes to the situation(s) encountered by D. discoideum in their natural habitat. For example, when meeting a K. pneumoniae bacterium, does D. discoideum adapt its gene expression pattern to eat and kill efficiently K. pneumoniae, or all Gram-negative bacteria? Does D. discoideum on the contrary avoid phagocytosis and upregulate genes allowing escape, because some Gram-negative bacteria are pathogenic?


So I think I would be careful of inferring too much from these (but I don't understand the biology so well)

Personally I would  maybe see if there is any way to really connect the individual gene products then I would try to link by
MF (e.g lysozyme) 
Should this have an F-P link to part_of BP GO:0009253   peptidoglycan catabolic process
(which implies gram-negative bacteria anyway) 
part_of  some nutrient assimilation term
part_of "response to bacteria/gram negative bacteria"

if there is enough information.

I would always try to couple the "response to" terms to a non-response process, and  if this is not possible I wonder if there is really enough information.


More questions from a scout around....
How does "response to nutrient" differ from response to food?
Why is 'response to nutrient levels' a parent of 'response to nutrient' and not the other way around?
Why is 'catabolism by organism of cell wall peptidoglycan in other organism' a multi organism process?

sigh.....sorry...

**Comment by ValWood** [comment]
anyway, I think I would post-compose with part_of "some response" term rather than creating more granular response to terms incorporating processes.

**Comment by pgaudet** [comment]
> How does "response to nutrient" differ from response to food?

That's why I was suggesting a merge.

**Comment by krchristie** [comment]
I haven't looked specifically at the food or nutrient roles specifically yet, and based on the relatively small number of complaints related to these roles, compared to cofactor, drug, and neurotransmitter, they aren't the next roles on my list to deal with.

**Comment by ValWood** [comment]
> That's why I was suggesting a merge.

Ah IOK, I didn't see that

**Comment by pfey03** [comment]
@ValWood First, thanks for looking so much into Dicty papers. I don't quite understand your comment about M. lutes, do you mean the low GFP expression in Fig. S1? It's low for most other gram-pos promoter:GFP fusions.

In this paper they used a wide range of bacteria to test. In the wild, Dicty needs to distinguish what it eats and rather doesn't, aside from the fact they also pack some other bacteria for later when fruiting (farmer). I agree, that the paper only hints at what regulations could play a role.

Fig. 3 of the Nasser paper shows transcriptional profiles and that different genes are expressed in WT cells feeding either on gram-neg or gram-pos bacteria. The mutant analyses and transcriptome data match.
 
The rest is interpretation and speculation such as lysozymes/hydrolases expressed to digest gram+ bacterial cell wall.

@pgaudet 
I could probably just annotate to GO:0071240 'cellular response to food'. IMP and / or IEP. More I cannot do from this paper as there is no MF data. 

But for phenotypes I would be specific to gram-pos and gram-neg bacteria. And for UPHENO patterns I need the gram-/+ as entities but I'm not aware of any. That's why I suggested the more specific 'response to' GO terms to be covered.

Thanks|

**Comment by mgiglio99** [comment]
would it work to make new terms:
'response to gram-positive bacteria as food source'
'response to gram-negative bacteria as food source'
as children of 'response to food'?

I share Val's question about 'response to nutrient' and 'response to food'.

**Comment by pfey03** [comment]
For me these terms would work, absolutely! 
I also agree to the merging response to food and - nutrition.
Thanks

**Comment by ValWood** [comment]
One other thought. If you are using a "response to bacteria" term, or any term under
GO:0044419    interspecies interaction between organisms

you can use dual  taxon in the taxon field to specify the 'interacting species' so you could put the taxon for the gram-positive and gram-negative bacteria in here.

It is quite hidden for users (and curators!), but GO should make this more prominent.  Even make it mandatory for this branch....
This approach would be much more sustainable than the response to fungi, response to bacteria etc,
and would allow the exact species, or a species group to be captured (depending no  the available information). 
If we used this   option routinely it would make ontology development much simpler, and annotation more consistent.

**Comment by gthayman** [comment]
I would think a nutrient would be a subcategory of food, such as protein or carbohydrate. I'm a little surprised 'response to nutrient' and 'response to food' are siblings, rather than the former being a child of the latter. I would be opposed to merging these. I wholeheartedly agree with Val's question: Why is 'response to nutrient levels' (more information, more granular) the parent, not the child, of 'response to nutrient' (less information, less granular)?

**Comment by pfey03** [comment]
I agree a modular system using taxon IDs is good for many cases. However, if you want to annotate to a (well known) group, a GO term might be helpful to have. 
We could add specific taxons in addition.

**Comment by pfey03** [comment]
I looked at bacterial taxons but that's not satisfactory. And gram-positive and negative are cell wall characteristics but a **well-known grouping**.
@pgaudet your original suggestion and reiterated by @mgiglio99 could you add children to 
GO:0071240 cellular response to food
- cellular response to gram-positive bacteria as food source
- cellular response to gram-negative bacteria as food source
Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a gram-positive bacterial food stimulus. 

Let me know if this sounds reasonable.

**Comment by tberardini** [comment]
On the 'food' vs. 'nutrient' part of the discussion:
---
From the response to food definition:

> food is anything which, when taken into the body, serves to nourish or build up the tissues or to supply body heat. 

I can't find a definition of 'nutrient' in any of the GO terms containing that string that I examined. 

From the above, _food_ sounds 'animal'-centric, while _nutrient_ could be interpreted as more broadly applicable. I would not annotate any plant gene products to 'response to food' (or children),  but I could see using 'response to nutrient' as a grouping term to retrieve plant annotations to child terms.  

I'm not quite sure whether one of the possible suggested edits is to merge 'response to nutrient' into 'response to food', that's one way I read the comments above.  I would NOT be in favor of such a move.

Apologies to those gardeners who use the term 'plant food' on a regular basis.

**Comment by krchristie** [comment]
> @krchristie
> On a slightly different topic, 'nutrient' is also a role. This is also causing bad inferences: Children of GO:0007584 response to nutrient are :
> 
>     * GO:0051780 behavioral response to nutrient
>     * GO:0031670 cellular response to nutrient
>     * GO:0009594 detection of nutrient
>     * GO:0033198 response to ATP
>     * GO:1905429 response to glycine
>     * GO:1903576 response to L-arginine
>     * GO:1902065 response to L-glutamate
>     * GO:1904844 response to L-glutamine
>     * GO:0000304 response to singlet oxygen
>     * GO:0033273 response to vitamin
> 
> Maybe the best solution is to merge into GO:0032094 response to food / GO:0071240 cellular response to food, since nothing seems to get further inferred from 'food role'.

@pgaudet - Yes, I am aware that both `food` and `nutrient` are ChEBI roles. The action I proposed today (4/20/20) in the ontology editors call to stop reasoning over roles with respect to which chemicals have a specific role will solve the problem you are talking about without needing to merge (and it's not clear to me that merging while still reasoning over roles would solve it since I think that reasoning may move up the tree).

**Comment by krchristie** [comment]
> I would think a nutrient would be a subcategory of food, such as protein or carbohydrate. I'm a little surprised 'response to nutrient' and 'response to food' are siblings, rather than the former being a child of the latter. I would be opposed to merging these. I wholeheartedly agree with Val's question: Why is 'response to nutrient levels' (more information, more granular) the parent, not the child, of 'response to nutrient' (less information, less granular)?

Within ChEBI, nutrient is a subtype of food:

![foodNutrient-tree](https://user-images.githubusercontent.com/10533218/79797562-552bc700-830c-11ea-9f89-bfa811bdb4e7.png)

**Comment by krchristie** [comment]
> I looked at bacterial taxons but that's not satisfactory. And gram-positive and negative are cell wall characteristics but a **well-known grouping**.
> @pgaudet your original suggestion and reiterated by @mgiglio99 could you add children to
> GO:0071240 cellular response to food
> 
>     * cellular response to gram-positive bacteria as food source
>     * cellular response to gram-negative bacteria as food source
>       Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a gram-positive bacterial food stimulus.
> 
> 
> Let me know if this sounds reasonable.

From a quick look at the existing terms referring to the ChEBI roles `food` and `nutrient`, it's possible it may be problematic to have any child terms under them because what is a food to a given organism is not the same across all taxa. So, you can give them parentage under `response to food`, but how we deal with the food and nutrient terms may change when I get to those roles.

I think these proposed new terms would be also be fine as child terms of the existing term `response to bacterium (GO:0009617)` so please make sure they get this parentage also.
-- response to bacterium (GO:0009617)
--- cellular response to gram-positive bacteria as food source (GO:NEW)
--- cellular response to gram-negative bacteria as food source (GO:NEW)

**Comment by pfey03** [comment]
@krchristie, @pgaudet 
Yes parentage of response to bacterium (GO:0009617) seems important, it has also defense to bacterium and children and it's good to have that branch.
Would be great if these will be added soon so I can move on and wait for the terms to appear for annotations.
Thanks!

**Comment by pfey03** [comment]
@pgaudet, I read more into the full paper (PMID: 23664307) including discussion and others, and now think that eating and killing bacteria for Dicty is probably regulated by the same and overlapping pathways and different genes/pathways for gram+ and neg. The killing might serve different purposes.

so maybe in GO, I would rather annotate to these new terms, at least for this paper:
-- response to bacterium (GO:0009617) 
--- cellular response to Gram-positive bacterium (GO:NEW)
--- cellular response to Gram-negative bacterium (GO:NEW)

The above new terms should be parent of the existing:
- defense response to Gram-positive bacterium (GO:0050830)
- defense response to Gram-negative bacterium (GO:0050829) 

For phenotypes it's different but I could use the looser new term and make 'as food source' a narrow synonym. 

In case  other groups like the
> cellular response to Gram-positive/negative bacteria as food source
 
then I would like to have both, the above without the food source, and these.

Thanks,
Petra

**Comment by pfey03** [comment]
@pgaudet I have now added phenotypes to the ontology to annotate to those genes and would appreciate if you could add the the non-contentious new terms I described above, you can even skip, the 'cellular' for my purposes.
-- response to bacterium (GO:0009617)
--- response to Gram-positive bacterium (GO:NEW)
--- response to Gram-negative bacterium (GO:NEW)
---- defense response to Gram-positive bacterium (GO:0050830)
---- defense response to Gram-negative bacterium (GO:0050829)

Many thanks!!

**Comment by pgaudet** [comment]
Here you go: 

 
+[Term]
+id: GO:0140459
+name: response to Gram-positive bacterium
+namespace: biological_process
+def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a stimulus from a Gram-positive bacterium." [PMID:23664307]
+is_a: GO:0009617 ! response to bacterium
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19278 xsd:anyURI
+created_by: pg
+creation_date: 2020-04-30T07:33:34Z
+
+[Term]
+id: GO:0140460
+name: response to Gram-negative bacterium
+namespace: biological_process
+def: "Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a stimulus from a Gram-positive bacterium." [PMID:23664307]
+is_a: GO:0009617 ! response to bacterium
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19278 xsd:anyURI
+created_by: pg
+creation_date: 2020-04-30T07:34:38Z

Thanks, Pascale

**Comment by pgaudet** [comment]
@krchristie I create the new terms. I suggest you mage a new ticket for the nutrient/food roles, if needed. 
Thanks, Pascale
