### ISSUE TITLE
parentage and relationship between terms for cytoplasmic viral assembly compartment

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#19286]
GO:0039714 cytoplasmic viral factory "A viral factory located in the cytoplasm of a host cell." no PMID, 69 annotations according to quickGO
and
GO:0072516 viral assembly compartment "A membrane-bounded compartment that forms in the cytoplasm of virus-infected cells, in which virus assembly takes place.' PMID:20374631, no annotations

What is the intended difference between these two terms? Specifically, what distinguishes GO:0072516 from GO:0039714 or one of the children of GO:0039714 such as  GO:0072517
host cell viral assembly compartment?

And while I'm being confused, all of these structures are cytoplasmic vesicles / intracellular membraneous structures. Should they have parents to indicate that? (Or does that collide with the host cell feature?)

Ruth is tagged because of the BHF tag on GO:0072516.

**Comment by RLovering** [comment]
Oh dear, this ticket lists the original request I made. assembly compartment #8199
Not sure why I didn't create the annotations though. The viral/host ontology has been revised a few times since I requested the terms, so I would rather someone else to this on

**Comment by ukemi** [comment]
Strictly from the definitions and link to ViralZone:
GO:0072516  (viral assembly compartment) need not be double membrane enclosed, but needs to be membrane enclosed and needs to be in the cytoplasm.
GO:0039714 (cytoplasmic viral factory) needs to be in the cytoplasm, but doesn't need to be membrane enclosed.
The picture in the ViralZone link from the second term VZ:1951 shows the complexity of these factories.

**Comment by ukemi** [comment]
Looking again, we have both viral assembly compartment and host cell viral assembly compartment. Perhaps the former is not host cell-derived but is membrane bounded and in the cytoplasm?????? Seems like GO:0072516 (viral assembly compartment) is the odd term out. All of the things under the host term align with viralzone. I'm not confident enough in my knowledge breadth of viruses to make changes though.

**Comment by pgaudet** [comment]
@pmasson55 Thoughts ?

**Comment by pmasson55** [comment]
First the difference between assembly and factory. Viral factory is the place where the virus replication occurs, in an environment protected from the host immune system. You can have cytoplasmic or nuclear viral factories (so it's related to replication). Concerning assembly, it's the place where the assembly of the virus occurs, meaning the capsids form and grabs the genetic material.  For the second part, I guess viral assembly compartment and host cell viral assembly compartment mean the same cellular component. I guess they can be fused.  The thing is to keep the best term for a clean hierarchy. Since there is a whole branch of components with host term, we may keep the "host cell viral assembly compartment".

**Comment by ukemi** [comment]
Thanks @pmasson55! I will merge 'viral assembly compartment' into 'host cell viral assembly compartment', assuming they never assemble outside of a host cell. I'll also have a look at the definitions based on what you noted above to see if I can make them clearer.
