### ISSUE TITLE
Review branch GO:0070920 regulation of production of small RNA involved in gene silencing by RNA

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19303]
@RLovering @ValWood

**Comment by ValWood** [comment]
I haven't used this term.


but I'm wondering why it isn't 
MF part_of regulation of gene silencing by (mi)RNA
-the production of the si/mi RNA  are the individual well-characterised steps in the pathway (performed by argonaut dicer etc).


(@pgaudet  note that this term is not part of 'chromatin silencing, the ones we were looking at)

**Comment by pgaudet** [comment]
regulation of pre-miRNA processing
remove parent 'regulates some 'production of miRNAs involved in gene silencing by miRNA', since this is more specific than the term 

(ie, current hierarchy: 
is_a regulation of pre-miRNA processing is_a regulation of production of miRNAs involved in gene silencing by miRNA

**Comment by pgaudet** [comment]
Annotations are here: 
https://docs.google.com/spreadsheets/d/1Pm_-HYbAC1Sp4Xewm0GvcHTUPGWgVbIxvOXNxq1Kbbg/edit#gid=0

**Comment by pgaudet** [comment]
The proposal is to obsolete: 

'regulation of production of small RNA involved in gene silencing by RNA'
'regulation of production of miRNAs involved in gene silencing by miRNA'
'negative regulation of production of miRNAs involved in gene silencing by miRNA'
'positive regulation of production of miRNAs involved in gene silencing by miRNA'
'regulation of production of siRNA involved in gene silencing by small RNA'
'regulation of production of siRNA involved in RNA interference'
'negative regulation of production of siRNA involved in RNA interference'
'positive regulation of production of siRNA involved in RNA interference'

**Comment by pgaudet** [comment]
Actions - from discussion with @colinlog 


- [ ] NTR: siRNA catabolic process child of ncRNA catabolic process, to annotate URT1 (URT1) PMID:25928405

* GO:0030422 production of siRNA involved in RNA interference & GO:0070919 production of siRNA involved in gene silencing by small RNA' 
- [ ] merge and change label to 'production of siRNA 

* GO:0010267 production of ta-siRNAs involved in RNA interference'
- [ ]  change label to production of ta-siRNA

* 'regulation of production of siRNA involved in gene silencing by small RNA'
*  - [ ]  change label to regulation of production of siRNA 
* 'regulation of production of siRNA involved in RNA interference'
*'negative regulation of production of siRNA involved in RNA interference'

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140745
+name: siRNA transcription
+namespace: biological_process
+def: "The transcription of a small interfering RNA from an RNA template." [PMID:23001036]
+is_a: GO:0001172 ! transcription, RNA-templated
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19303 xsd:anyURI
+created_by: pg
+creation_date: 2021-12-13T13:08:09Z
+
+[Term]
+id: GO:0140746
+name: siRNA catabolic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the breakdown of small interfering RNA transcripts (siRNAs)." [PMID:25928405]
+intersection_of: GO:0009056 ! catabolic process
+intersection_of: has_primary_input SO:0000646 ! siRNA
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19303 xsd:anyURI
+created_by: pg
+creation_date: 2021-12-13T13:11:22Z

**Comment by pgaudet** [comment]
- [ ] Merge     GO:0031050   dsRNA processing (since EXP annotation to worm Dicer) into GO:0034470 ncRNA processing

**Comment by pgaudet** [comment]
- [ ] Change labels: 

'production of small RNA involved in gene silencing by RNA' -> small RNA processing 
'production of lsiRNA involved in RNA interference' -> lsi RNA processing 
'production of miRNAs involved in gene silencing by miRNA' -> mi RNA processing 
'production of siRNA involved in gene silencing by small RNA' -> si RNA processing 
'production of siRNA involved in RNA interference' merge into 'si RNA processing ' above
'production of ta-siRNAs involved in RNA interference' -> ta-siRNA processing 


- [ ] Likewise for corresponding regulation terms
- [ ] change the definition to match other RNA processing definitions: Any process that results in the conversion of a primary non-coding RNA (ncRNA) transcript into its mature form. (replacing the product as appropriate).

**Comment by ValWood** [comment]
I don't think the merge of 'production' into 'processing' is a generally safe assumption.

In none Metazoans, annotations to this term also include 
RNA-directed RNA polymerase. 
e.g. https://www.pombase.org/gene/SPAC6F12.09
This isn't processing, but it is production (I don't mind removing production terms,  but the merge is not safe).

**Comment by ValWood** [comment]
+id: GO:0140745 +name: siRNA transcription

This term seems to combine different processes. In pombe siRNA is produced by "RNA-directed RNA polymerase" in which case the process is equivalent to a molecular function. This might not be the case for other species though. What do you expect to see annotated to this term?

**Comment by pgaudet** [comment]
> GO:0140745 +name: siRNA transcription

Indeed it was for the polymerase, similar to any transcription - isn't it?

**Comment by ValWood** [comment]
Is it useful for modelling to describe this as  'transcription' though?  (it is really part of negative regulation of gene expression). Transcription is really about "information content" and could refer strictly to transcribing  'genes'.

siRNAs are expressed as part of "siRNA dependent gene silencing" but this is just a single step. I don't see the advantage of a term to describe the expression of the siRNA as a process.

It seems that 
"RNA-directed RNA polymerase" part_of "siRNA-dependent facultative heterochromatin assembly"
or similar would be sufficient.
It is a single step in the  nucleation of heterochromatin formation, and connecting in this pathway to the other components of siRNA generation (dicer, argonaut etc) we really don't need to say anything about 'transcription' explicitly.


This would make the ontology much cleaner, since then "positive regulation of transcription"  would not be simultaneously  be a positive and negative regulation of gene expression in different contexts.

Although as you know, I think transcription should be represented by pathways (Pol I,II and III) rather than by molecule type, which can be described by inputs using SO terms or  database identifiers to describe the transcribed entities. The pathways align more closely with other processes (for example transcription by polymerase I is always causally upstream of ribosome biogenesis ,  transcription from pol II is always causally upstream of tRNA metabolism (although it is also upstream of other processes).

So I don't see the advantage of annotating "RNA-directed RNA polymerase" to a "transcription" bin, because it is not connected in any way to canonical transcription. In fact, adding this to the transcription 'bin' will make enrichment worse for "transcription of hereditary information".

**Comment by ValWood** [comment]
This parentage seems problematic for centromeric heterochromatin assembly where the siRNAs aren't always part of  "gene expression".
This is a more general issue though, probably only the "transcription associated" heterochromatin terms  should be under transcription (i.e. 
GO:0045815 | epigenetic maintenance of chromatin in transcription-competent conformation AND co-transcriptional chromatin reassembly (GO:0140673)


GO:0010467    gene expression
* GO:0006351    transcription, DNA-templated
* * name: siRNA transcription

**Comment by pgaudet** [comment]
Annotations are here: https://docs.google.com/spreadsheets/d/1Pm_-HYbAC1Sp4Xewm0GvcHTUPGWgVbIxvOXNxq1Kbbg/edit#gid=0

**Comment by pgaudet** [comment]
I opened an annotation ticket for the review of annotations, see 
https://github.com/geneontology/go-annotation/issues/4168

I will close this - @ValWood I think the centromeric heterochromatin is unrelated, please open a new ticket if you want changes to that term. 

Thanks, Pascale
