### ISSUE TITLE
Problem with automatic (logical) association leads to GO Violation

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#19461]
When reviewing GO Violations from the snapshot this one
ERROR - Violates GO Rule: GORULE:0000006: IEP and HEP usage is restricted to terms from the Biological Process ontology -- TAIR locus:2092221 STP10 GO:0005623 TAIR:Publication:501768255|PMID:26893494 IEP C AT3G19940 AT3G19940|STP10|SUGAR TRANSPORT PROTEIN 10|MPN9.18 protein taxon:3702 20160301 GOC TAIR:locus:2092221

Is an error we cannot fix because the annotation to cell was made based on the curation of this gene product to cellular response to glucose stimulus (GO:0071333).

I guess I can fix this by removing the causal annotation but shouldn't there be a rule agains propagation of annotations to component when the evidence code is IEP?

**Comment by pgaudet** [comment]
@cmungall @balhoff @vanaukenk 
It makes sense to either remove inferences or to add a different evidence code for inferences (I thought we wanted to do that anyway?) It doesn't always make sense to use the same evidence code across different GO aspects.

**Comment by vanaukenk** [comment]
It seems reasonable to me to consider a different evidence code.

As things currently stand, the distinguishing feature of these inferential annotations is that they are 'Assigned_by' GOC, but otherwise look like a manual annotation from the originating group, e.g. they include MOD publication id, list all the synonyms, etc.

ECO has an evidence code, "evidence based on logical inference from manual annotation used in automatic assertion" that perhaps would fit what we do with the inferences from the ontology:

https://www.ebi.ac.uk/ols/ontologies/eco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FECO_0000364

although in GAF, I think this would map up to IEA.  But maybe that's okay?

Perhaps we could even include the GO id for the originating term annotation in the With/From field so we could further track the provenance of the inferred annotation?

**Comment by lreiser** [comment]
That seems reasonable to me.

**Comment by tberardini** [comment]
Found the older ticket with relevant discussion: https://github.com/geneontology/go-annotation/issues/1395

**Comment by tberardini** [comment]
And: https://github.com/geneontology/go-annotation/issues/2556

**Comment by ValWood** [comment]
I still support my comments in the older ticket. 

I t doesn't really makes sense to use the same evidence code for location if no localization  experiment was not performed.  This would not make sense to biologist end users.

Ideally we would not use IEP for *anything* . Maybe as a special case, there should be no propagation *of any type* for this evidence code (IEA/ISS or inter ontology link). It needs strict containment. It definitely would be dangerous to transfer by ISS in most cases.

**Comment by pgaudet** [comment]
The decision from the ontology call is to keep using the same evidence code for the inter-ontology inferences (mostly because we don't know for sure what users expect). I will request to change gorule-0000015 so that this does not get reported as a violation anymore. 

Thanks, Pascale
