### ISSUE TITLE
protein serine kinase activity (using GTP as donor)

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#19523]
Hi GO,

I would need a GO term for a very interesting article that describes an atypical serine protein kinase activity using GTP as donor (PMID:32322062) for PCK1 (UniProt accession P35558)
Thanks
Sylvain

Name: protein serine kinase activity (using GTP as donor)
Definition: 
Catalysis of the reactions: GTP + L-seryl-[protein] = GDP + H(+) + O-phospho-L-seryl-[protein]
Child of:  GO:0004672 protein kinase activity
Xrefs
Rhea:64020
PMID:32322062

Note that it might be good to modify the Name of  GO:0004674
FROM:
GO:0004674 protein serine/threonine kinase activity
TO:
GO:0004674 protein serine/threonine kinase activity (using ATP as donor)

**Comment by pgaudet** [comment]
I dont think we need to modify the label of  GO:0004674.

**Comment by pgaudet** [comment]
how about 'atypical GTP serine protein kinase, using GTP as donor' for the label?

**Comment by sylvainpoux** [comment]
It would be perfect:

Name: Atypical protein serine kinase activity (using GTP as donor)
Definition:
Catalysis of the reactions: GTP + L-seryl-[protein] = GDP + H(+) + O-phospho-L-seryl-[protein]
Child of: GO:0004672 protein kinase activity
Xrefs
Rhea:64020
PMID:32322062

**Comment by hdrabkin** [comment]
I don't like the 'atypical' ;
There are obviously TWO types of protein serine kinase activity, one ATP dependent, the other GTP dependent. (instead of saying using XTP as a donor). We do these for other reactions where there is an ATP and a GTP dependent reactions.
Since all of the children of GO:0004674 are ATP dependent, as their definitions and associated RHEAs indicate, I think it is good thing to add ,ATP dependent" to that term.
HOWEVER
The suggested parent term for the new term, is defined as using ATP. 
I suggest altering the def to reflect that children can be using EITHER ATP or GTP.

**Comment by pgaudet** [comment]
Are we not complicating things for users, based on a rare exception ? 
Could the new term be a sibling of 'GO:0004674 protein serine/threonine kinase activity' ? 

If we create a new parent term it may lead to incorrect annotation. Unless we use a 'do not annotate' flag but people have been ignoring those.

**Comment by ValWood** [comment]
>If we create a new parent term it may lead to incorrect annotation. Unless we use a 'do not annotate' flag but people have been ignoring those.

If this is the case  the checks  should be  mandated by converting  to hard checks. Otherwise we are back to square 1 (presumably these are already reported in logs as warnings, so groups should fix (or be prompted to if they aren't).  Going forward, curation tools can  easily be configured to prevent annotation to blocked terms  by forcing  more specific choices. We do this in Canto. Can should discuss when/if we revive the QC group.

**Comment by hdrabkin** [comment]
I do want to make new_GO a sib of GO:0004674, but its parent has ATP in it's def. I was just trying pointing out why we couldn't make it a CHILD of 4674
However, the parent term may be ok: protein kinase activity, because  it has the def
Catalysis of the phosphorylation of an amino acid residue in a protein, usually according to the reaction: a protein + ATP = a phosphoprotein + ADP.
The key part is the "usually "  for what follows.
OR, could tweak def of protein kinase activity to use NTP 
We do this for other terms
polynucleotide 5'-hydroxyl-kinase activity, with ATP and GTP dependent children.
;
However,I m leaning NOT to change def but leave it because it does say 'usually', and make the new term a child of it.

**Comment by pgaudet** [comment]
Got it, sounds good ! Thanks, Pascale

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106264
+name: protein serine kinase activity (using GTP as donor)
