### ISSUE TITLE
update definitions of "spliceosomal snRNP complex" and child terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19659]
Hi @krchristie ,

I have a (quick, hopefully ) question for you.

I was revising some old spliceosomal complex annotations.

I have a bunch of things annotated to: 
GO:0005686 U2 snRNP 
Def: A ribonucleoprotein complex that contains small nuclear RNA U2.

so should this term be a superclass of 
GO:0071004 U2-type prespliceosome 
?

it isn't ,but logically it seems that is should be if
GO:0071004 U2-type prespliceosome  contains the small nuclear RNA U2

(maybe it doesn't, I'm basing this one an assumption, I tried to find out but all my searches  for " U2-type prespliceosome " only give GO terms so it all gets a bit circular).

many thanks if you can help,

Val

**Comment by krchristie** [comment]
Hi @ValWood 

This term is for the U2 snRNP, which is an independent complex contain the U2 snRNA and several proteins when it is not part of a spliceosomal complex and it's known that cells have pools of free U2 snRNP. It's possible that some of the U2 snRNP proteins are only present in the U2 snRNP and not in any spliceosomal complexes (I forget which of the free snRNPs contain proteins that dissociate when that snRNP joins "the" spliceosome. I wish the comments displayed in more interfaces since this is stated in the comment (let me know if you think the comment could be clearer).

> [Term]
id: GO:0005686
name: U2 snRNP
namespace: cellular_component
def: "A ribonucleoprotein complex that contains small nuclear RNA U2." [GOC:krc, GOC:mah]
comment: U2 snRNP refers to the U2 small nuclear RNA and the proteins that associate with it. U2 snRNP is not considered to be a type of spliceosomal complex by itself.
synonym: "17S U2 snRNP" NARROW []
synonym: "snRNP U2" EXACT [GOC:mah]
is_a: GO:0097525 ! spliceosomal snRNP complex

----

This term, and its child terms, represent various specific assembled spliceosomal complexes that at some point in the cycle contain the U2 snRNP (the major form of spliceosomal complexes), as opposed to the U12 snRNP (the minor form, which is absent from cerevisiae; I don't know about whether pombe has the minor spliceosome. The minor spliceosome has been lost at least 7 independent times). I no longer remember why we decided to use the names U2-type and U12-type instead of major and minor, which are the older names and still synonyms of these terms. Perhaps the research community was changing it's usage.

> [Term]
id: GO:0005684
name: U2-type spliceosomal complex
namespace: cellular_component
def: "Any spliceosomal complex that forms during the splicing of a messenger RNA primary transcript to excise an intron that has canonical consensus sequences near the 5' and 3' ends." [GOC:krc, GOC:mah, PMID:11343900]
comment: A U2-type complex refers to any of the snRNP-based complexes that form during splicing that uses U2 (as opposed to U12). There are complexes that form during U2-splicing that don't necessarily contain the U2 snRNP.
synonym: "GT-AG spliceosome" NARROW [GOC:krc, GOC:mah]
synonym: "major (U2-type) spliceosomal complex" EXACT [GOC:krc, GOC:mah]
synonym: "major spliceosomal complex" EXACT [GOC:krc, GOC:mah]
is_a: GO:0005681 ! spliceosomal complex

----

I have an aversion to the term "the spliceosome" since it isn't really "a complex", but rather a series of complexes, starting with the binding of the U1 snRNP to the 5' splice site, then the binding of the U2 snRNP to the branchpoint sequence to form the prespliceosome. I've put the order of the defined complexes below. U2 snRNA is present in everything except the commitment complex, which only contains the U1 snRNA.

1. commitment complex
2. prespliceosome
3. precatalytic spliceosomal complex
4. catalytic step 1 spliceosome
5. catalytic step 2 spliceosome
6. post-spliceosomal complex
7. post-mRNA release spliceosomal complex

Here's a view from Protege showing the `spliceosomal snRNP complex` term and its children, and also the child terms of `U2-type spliceosomal complex` as well as of `U12-type spliceosomal complex`, which differs in assembly from the U2-type in that U11 & U12 form a complex before binding to the mRNA, unlike what I described above where U1 and U2 bind sequentially.

![U2-snRNP-vs-spliceosome](https://user-images.githubusercontent.com/10533218/85485240-2ab0f100-b57d-11ea-8da6-3d3d4e5cff6f.png)

----

So, with all that background, the short answer to your question is no, the `U2 snRNP` term should not be a parent of the `U2-type spliceosomal complex` term. I hope it makes sense why that is true now. I'm going to go ahead and close this ticket, but let me know if you have further questions.

Regarding annotation, the majority of gene products present in the U2 snRNP are present in at least some of the spliceosomal complexes, but like I said earlier, I know that some of the spliceosomal snRNPs contain a protein or two that  dissociate when that snRNP joins the spliceosome cycle of complexes. When I was annotating these at SGD, I only annotated a given gene product to a specific spliceosomal complex term when I had experiments that showed the composition of specific complexes in the cycle.

@pgaudet - Since @ValWood tagged me with this question and I think no further action needs to be taken, I've claimed the ticket and tagged you so you can include it in the rota.

**Comment by ValWood** [comment]
This is really useful!

My only outstanding question is: 
Should
GO:0005686 U2 snRNP
Def: A ribonucleoprotein complex that contains small nuclear RNA U2.

have something else in the definition? It does not seem to be necessary and sufficient  to define what is meant by GO:0005686 U2 snRNP
(it sounds like any  complex containing small nuclear RNA U2 would fit this description)

i.e. GO:0071004 U2-type prespliceosome
is_a 
A ribonucleoprotein complex that contains small nuclear RNA U2.

**Comment by krchristie** [comment]
@ValWood - That's a good point. I'll think about this and see what I can do to be clearer.

**Comment by krchristie** [comment]
Hi Val,

I took a look at a couple chapters in my copy of The RNA World (2nd edition). Based on that, here are some ideas. I think that this issue extends beyond the term for U2. So if I change the definition for U2, I should also change the definition of the term **small nuclear ribonucleoprotein complex** and all of the child terms under it. 

What do you think of these possible new defs?

**U2 snRNP**
- **Current Def:** A ribonucleoprotein complex that contains small nuclear RNA U2.
- **Idea for new Def:** A small tight complex containing the U2 snRNA, a heptameric ring of Sm proteins, as well as several proteins that are unique to the U2 snRNP, most of which remain associated with the U2 snRNA both while the U2 snRNP is free or assembled into a series of spliceosomal complexes.


**small nuclear ribonucleoprotein complex**
- **Current Def:** A complex composed of RNA of the small nuclear RNA (snRNA) class and protein, found in the nucleus of a eukaryotic cell. These are typically named after the snRNA(s) they contain, e.g. U1 snRNP or U4/U6 snRNP. Many, but not all, of these complexes are involved in splicing of nuclear mRNAs.
- **Idea for new Def:** A small tight complex of one or more proteins with a small nuclear RNA (usually between 60-300 nucleotides in length), found in the nucleus of a eukaryotic cell. These are typically named after the snRNA(s) they contain, e.g. U1 snRNP, U4/U6 snRNP, or 7SK snRNP. Many, of these complexes become part of the spliceosome involved in splicing of nuclear mRNAs. Others are involved in regulation of transcription elongation or 3'-end processing of replication-dependent histone pre-mRNAs.

-Karen

ISBN:087969-589-7 (as printed in book)

ISBN-13: 978-0879695897
ISBN-10: 0879695897

**Comment by ValWood** [comment]
Hi @krchristie this sounds great to me. But you are the expert  here anyway.

Minor comment: does "tight" add anything?  (I ask becasxue I'm not really sure what a 'tight complex' is.

Also shouldn't the def of "U2 snRNP" be derived from the direct ancestor? So that  would still begin with "A ribonucleoprotein complex", followed by the differentia that you suggest?

**Comment by pgaudet** [comment]
Ready ?

**Comment by krchristie** [comment]
> Ready ?

probably, but it will be somewhat time consuming to actually do as parallel changes will need to be made for numerous snRNA complex terms. I'm focusing on annotation this week, but I'll try to get to this next week.

**Comment by pgaudet** [comment]
Great, thanks !
