### ISSUE TITLE
NTR: defense response to parasitoid wasp infection

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19693]
Could I have:

defense response to parasitoid wasp infection

is_a defense response to insect GO:0002213

Reactions triggered in response to the presence of parasitoid wasp eggs or larvae that act to protect the cell or organism. (PMID: 22588641, PMID:32396065).

GOC:ha

Thanks

**Comment by ValWood** [comment]
HI @hattrill 
The multi-species group is hooing to phase out these  response to roganism/clade terms because they cause inconsistent annotation (people are using them often in place of the correct , more specific term describing the actual process) and the processes aren't really "species' or 'clade' specific. They are largely 'molecule specific'.

Is there a way you could capture the 'pathogen interaction' by connecting the fly gene to the pathogen gene (i.e as a reception substrate for example)?

**Comment by hattrill** [comment]
For so called antimicrobial peptides (AMP), the mechanism of action is often unknown. So, we don't know what they interact with and how they clear the organism.

In many instances, all we know is that they are small, induced upon infection (usually by an immune-activated pathway, for which we might know the biological agent and their expression has a negative effect on the invading organism. They probably act by punching holes in membranes or coating targets....we just don't know. All we really know that they are often specific to the organism.

**Comment by hattrill** [comment]
I can see that they can be used inconsistently, as they are very broad.

Is the innate immune response branch going to have the organism specific terms removed as well?

**Comment by ValWood** [comment]
There are two main issues with the current situation (also independently noted in numerous conversations by the multispecies working group @dsiegele and @mgiglio99 and by  PHI-base collaborators). 

1. When  these terms are used, the
"GO:0051817   modulation of process of other organism involved in symbiotic interaction" terms are often ignored.
( not helped by the fact that this term and the descendants are *really* difficult to locate, and the "response to species" terms are very prominent  at a high level, so more improvements are required).

Ideally, the annotation would say something more specific about how the host is interacting with the pathogen.

and 

2. If the annotations to the correct term are made, we have independent annotations are describing orthogonal aspects of the same observation that should be combined.

My previous preferred solution was to make this branch only available in extensions (this has worked well for the phase terms), but the sustainability of requests for every type of pathogen remains.
I previously thought we should not need to refer to the species because if annotations are made correctly the interacting organism will be in the taxon field, but this is quite hidden and I'm not even sure that all tools observe this requirement for pathogen-host interaction annotations.

Perhaps the most sustainable way to deal with this, and to capture any species at any level of granularity, would be to enable an extension   "interacting_species"  (or similar) on any term/annotation under 
GO:0044419   interspecies interaction between organisms

This would resolve all of the current issues:

1. We would be able to cull all "response to species", and would not need to add terms for every species
...the current situation is even worse than "response to favourite species":

This is one example:

GO:0009615    response to virus | 113,781 annotations
-- | --
GO:0051607    defense response to virus | 103,512 annotations
GO:0098586    cellular response to virus | 4,974 annotations
GO:0050688    regulation of defense response to virus | 6,015 annotations
GO:0050687    negative regulation of defense response to virus | 1,996 annotations
GO:0050690    regulation of defense response to virus by virus | 870,719 annotations
GO:0050691    regulation of defense response to virus by host | 2,111 annotations
GO:0002230    positive regulation of defense response to virus by host | 1,750 annotations
GO:0050689    negative regulation of defense response to virus by host
etc.....

This is not remotely sustainable.

2. Annotation would be more consistent, and we would always get the biologically relevant term in addition to the pathogen. 

3. It would/should be easy to configure in tools, they would need to make a taxon ID available in this slot.

4 We could get rid of the dual taxon  notation that is very hidden and not mandated


@thomaspd 
@cmungall

**Comment by hattrill** [comment]
For the experiments we encounter, the broad-brush categories really capture the experiment at the level they are intended e.g gram-negative bacterial, virus.

If groups want to capture interactions right-down to the species level, then I am ok with taxon ids in extensions.

I would prefer have something in broad classes - classification based on some attributes, such as gram negative, may not be necessarily aligned with taxonic lineage. I am not so sure that there is an explosion, if these are restricted to the broader classes. Could do with a good tidy tho' to harmonize on meaning - i.e. do we need separate defense response and innate response?

**Comment by ValWood** [comment]
broad classes would probably be sufficient (better actually because  options could be provided rather than everyone needing to look up taxon IDs which is tedious).

> do we need defense response and innate

unfortunately yes. there are defenses that are not immune response related

**Comment by addiehl** [comment]
+1  there are defenses that are not immune response related

**Comment by pgaudet** [comment]
We discussed this on the multiorganism call - and @hattrill if you are OK with taxon ids in extensions, then can you use GO:0009625 response to insect and add the parasitoid wasp taxid ? 

In this case we would not create the term. 


Thanks, Pascale

**Comment by hattrill** [comment]
What relation would you suggest?
Unfortunately, there are no tools which allow a search on taxid in extensions so it will get lost.

**Comment by pgaudet** [comment]
You think searching the taxon is needed ? I was hoping 'insect' would be granular enough as a search term, and users could view the exact taxon.

**Comment by hattrill** [comment]
They are more likely to look for parasite or parasitic insect, but we don't have a specific parasite branch.

(but I think that an insects for insects is not intuitive - certainly, when I spoke to Nick Brown he thought that parasitic insect was essential for users to find the annotations)

**Comment by pgaudet** [comment]
I see. Are parasitic insects always parasitic ? We have the same issue with pathogen.

**Comment by pgaudet** [comment]
Talking with @vanaukenk - Kimberly proposes to use 'has input'; would that work ? 

Also, if @mgiglio99 @dsiegele @ValWood agree I could create 'defense response to parasitic insect', as a child of 'defense response to insect'. 

Finally - if this is a response to **infection**, shouldn't there be some link to an immune response ?

**Comment by hattrill** [comment]
I am not an expert on parasitic wasps, but the laying of eggs in host/presence of larvae is always parasitic act.

I have been quite conservative for this particular example and some of the processes involved in the immune response e.g. melanization and pathways can be described with co-annotation or used in an extension in some way.

I think if there was a link to immune response, it would not be incorrect as it is a response to an infection.

**Comment by hattrill** [comment]
has_input could work.

**Comment by mgiglio99** [comment]
I don't know much about parasitic insects, but I do fear that we will have the same issues with 'parasitic' as we had with 'pathogenic'. To me, the fact that the term is 'defense response to...' and not just 'response to...' already implies that the insect is doing harm and is therefore parasitic or pathogenic. 
Would it be an option to make 'defense response to parasitic insect' a narrow synonym to 'defense response to insect'? That would solve the searching issue.

**Comment by hattrill** [comment]
Following this discussion: using taxon ids in extensions with has_input to specify species:
@alexsign would it be possible to add NCBI:txid to the has_input field in Protein2GO?

**Comment by vanaukenk** [comment]
Note a parallel discussion here:  https://github.com/geneontology/go-shapes/issues/237
I've put these two tickets on the agenda for the 2020-10-19 ontology editors call.

**Comment by pgaudet** [comment]
On the ontology editor call we agreed that 'has input' is the correct relationship for this.

**Comment by ValWood** [comment]
I think I misunderstood what this ticket was about. So let me get this straight.
In GO traditional annotation the interacting taxon goes (for any pathogen-host interaction term)  in the taxon field with a separator
In GO-Cam the interacting  the taxon goes in an extension field using has_input (or is this just in the case o the "response to species" terms), which would be very confusing.

Questions
So do you plan that people no longer use the taxon field for this information longer term?
Or is the plan that we redundantly populate both fields in a GAF file ?
And where does this fit in GPAD (I presume GPAD has a taxon field too?)

**Comment by pgaudet** [comment]
> So do you plan that people no longer use the taxon field for this information longer term?

It's a difference of format between GAF and GPAD. 

> Or is the plan that we redundantly populate both fields in a GAF file ?

I dont think so - I think the interacting taxon stays in the taxon field. There is no plan to further change the GAF specs. 


And where does this fit in GPAD (I presume GPAD has a taxon field too?)
> Yes, according to the latest specs: https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-1_2.md

@vanaukenk can confirm. 

Can this be closed ? 

@hattrill This is now a P2GO issue ?

**Comment by ValWood** [comment]
My questions are answered.

**Comment by pgaudet** [comment]
I created a separate annotation ticket for the use of 'has input' + the species in an extension, 
https://github.com/geneontology/go-annotation/issues/3514

As far as the ontology goes, this is resolved.

Thanks, Pascale

**Comment by mgiglio99** [comment]
Hi - I looked at the other issue as well as this one. I just want to make sure I understand the resolution here - the new term requested above was not made. 
And the wasp situation will be handled with use of taxon id extensions.
Correct?

**Comment by pgaudet** [comment]
Yes @mgiglio99 this is right. 

We suggested to @hattrill to use GO:0002213 defense response to insect. 

Thanks, Pascale
