### ISSUE TITLE
Impossible to use GO:0033643 (host cell part) and its descendants with taxo Opisthokonta, Why ?

### ISSUE THREAD

**Issue by FJungo** [geneontology/go-ontology#19742]
Hi
I received the following warning for a previous annotation:

GO:0033643 never_in_taxon Opisthokonta            protein K7N5L0 

GO:0033643 (host cell part) and its descendants should NEVER be used with gene products from the taxonomic group Opisthokonta.

I don't understand why a fungal protein cannot target another organism. In any case, that's what I meant, since this protein targets bacterial membrane.

Please, could you clarify this new constrain (only recently added) ?

**Comment by pgaudet** [comment]
@FJungo What protein are you trying to annotate ? (which species interacts with which species?)

**Comment by ValWood** [comment]
https://www.uniprot.org/uniprot/K7N5L0
would seem ok? 

Probably this 
https://github.com/geneontology/go-ontology/issues/19715
can only be never in vertebrates.

We will need to deal with fungal problems on a case-by-case basis and be mindful of annotation transfer and automated mappings.
v

**Comment by pgaudet** [comment]
Changed taxon constraint to 'never in Vertebrata <Metazoa>' 

Thanks, Pascale

**Comment by pgaudet** [comment]
PR: https://github.com/geneontology/go-ontology/pull/19748

**Comment by RLovering** [comment]
Hi 

I also do not understand the logic of this. eg GO:0020003 symbiont-containing vacuole and other terms under  GO:0018995 host cellular component are likely to include gene products contributed by the host cell. Why is the host taxon not allowed to be included?

in reference to the comments above, it is also not clear to me why the fungal peptide https://www.uniprot.org/uniprot/K7N5L0 is thought to be a unique anti-pathogen approach, I would have thought that humans also have gene products that inhibit pathogens through direct targeting of the pathogen membrane

Thanks

Ruth

**Comment by pgaudet** [comment]
@RLovering Would you remove all taxon constraints on GO:0018995 host cellular component  ?

**Comment by pgaudet** [comment]
Actually @RLovering 

The children of 'GO:0033643 host cell part' are *meant* to annotate symbiont gene products. 
For example we say 'viral protein X located_in host nucleus'. 
The host proteins are annotated to 'nucleus'. 

So, in the example you give, there should be an equivalent host term for the symbiont-containing vacuole. This is the whole point of that structure (otherwise we can get rid of 'host nucleus' and annotate symbiotic gene products to 'nucleus'. 

That being said, perhaps all terms should have 'host' in the label to avoid confusion. Would that help ? 

Thanks, Pascale

**Comment by ValWood** [comment]
> GO:0020003 symbiont-containing vacuole and other terms under GO:0018995 host cellular component are likely to include gene products contributed by the host cell. Why is the host taxon not allowed to be included?

These terms are to represent protein symbiont localization in the host. 
This isn't a 'real' vacuole. See comment
Comments
Note that this term does not have a relationship to 'vacuole ; GO:0005773' because it does not fit the definition of a vacuole; the parasitophorous vacuole was so named because it resembles a vacuole in the microscope.


Some host-genes do target pathogen cell surface proteins, all of the examples I've annotated are after the pathogen has invaded, and occur in the host cytoplasm. 
In cases cell-surface host -cell surface pathogen contact (pathogen recognition- first lines of defense ),  I  wouldn't annotate the host protein to the pathogen membrane or cell surface. I would annotate to the  "cell surface" (i.e self cell surface for the host) and capture the interaction with a pathogen cell-surface protein. The host protein is still part of the host-cell surface.

I'm not aware of host proteins which target the pathogen membrane per se (i.e secreted proteins) -most defences appear to be immune defenses and mitigation and occur within the host @dsiegele @mgiglio99  can you think of any secreted host defense proteins ?  If they exist, I think I would still annotate as extracellular, rather than to a specific pathogen component.

From what I remember of the history, these terms were treated specifically to allow the  differentiation of symbiont protein annotated to host structures. If this is not the case, than a separate branch would not be necessary.
If we were to annotate host proteins in symbiont structures  we would need a dedicated branch  to represent "host protein localization symbiont cell" , but as I say, I don't have any examples of this.

note that the definition of Definition 
GO:0018995    host cellular component
is
Any organism in which another organism, especially a parasite or symbiont, spends part or all of its life cycle and from which it obtains nourishment and/or protection.

This term and its descendants should absolutely be restricted to symbiont gene products.
Although the definition is a bit whacky.  It should be "any cellular component " not "any organism".  We are annotating gene products not 'organisms'
Maybe also the key point "a parasite or symbiont, spends part or all of its life cycle " should be iterated in the descendants?

**Comment by ValWood** [comment]
was this to close?

**Comment by pgaudet** [comment]
I think this can be closed, yes
