### ISSUE TITLE
NTR: negative regulation of posttranslational protein targeting to membrane, translocation (and parent) 

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#19791]
Hi,

I would like to request the following term 'negative regulation of posttranslational protein targeting to membrane, translocation' be added to the process ontology. This will require an additional term be created first in the process ontology 'regulation of posttranslational protein targeting to membrane, translocation' using the regulates relationship. Authors present evidence that yeast STE24, a metalloprotease involved in N-terminal proteolytic processing and a component of the ER quality control mechanism that removes faulty proteins clogging ER translocation channels, also functions as a negative regulator of N-terminal signal peptide–independent translocation into the endoplasmic reticulum

Here is what I am thinking:

GO:0031204 posttranslational protein targeting to membrane, translocation 
----->GO:XXXXXXX regulation of posttranslational protein targeting to membrane, translocation	(regulates)
----------->GO:YYYYYYY negative regulation of post-translational protein targeting to endoplasmic reticulum membrane, translocation (is_a)

GO:XXXXXXX	regulation of posttranslational protein targeting to membrane, translocation
Definition: 	Any process that modulates the frequency, rate or extent of posttranslational protein translocation through the ER membrane.

Synonyms:     	regulation of SRP-independent endoplasmic reticulum protein-membrane targeting, translocation
		regulation of N-terminal signal peptide–independent translocation into the ER 
 		regulation of posttranslational endoplasmic reticulum membrane protein translocation

GO:YYYYYYY	negative regulation of posttranslational protein targeting to membrane, translocation
Definition: 	Any process that stops, prevents or reduces the frequency, rate or extent of posttranslational protein translocation through the ER membrane.

Synonyms:     	negative regulation of SRP-independent endoplasmic reticulum protein-membrane targeting, translocation
		negative regulation of N-terminal signal peptide–independent translocation into the ER 
 		negative regulation of posttranslational endoplasmic reticulum membrane protein translocation

Reference:
Hosomi A, et al. (2020) The ER-associated protease Ste24 prevents N-terminal signal peptide-independent translocation into the ER in Saccharomyces cerevisiae. J Biol Chem.
https://www.yeastgenome.org/reference/S000275006
PMID: 32513868

Cheers,
Rob

**Comment by krchristie** [comment]
Hi @robnash 

Thanks for providing so much info about what terms you need, it makes it very easy!

You didn't mention whether the synonyms should be EXACT, NARROW, etc. and it seemed to me that the ones like this should be narrow, since they are limited to signal-peptide independent mechanisms while the terms you requested aren't obviously limited in that way:
- regulation of SRP-independent endoplasmic reticulum protein-membrane targeting, translocation
- regulation of N-terminal signal peptide–independent translocation into the ER

while the ones like this could be exact:
- regulation of posttranslational endoplasmic reticulum membrane protein translocation

but if you disagree with what I put in, let me know what they should be instead.

Thanks,

-Karen
