### ISSUE TITLE
New term request: 2-iminobutanoate/2-iminopropanoate deaminase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19832]
2-iminobutanoate/2-iminopropanoate deaminase

https://enzyme.expasy.org/EC/3.5.99.10
https://www.rhea-db.org/reaction?id=39975
https://www.rhea-db.org/reaction?id=40671

Needed to annotate human RIDA (P52758) (see PMID: 22094463) and orthologs.

Think parents should be:
- hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds (GO:0016810)
- deaminase activity (GO:0019239)

**Comment by krchristie** [comment]
@sjm41 - I see that you link to two Rhea reactions that are represented by a single EC number. 

@hdrabkin - How do we deal with this? Do we have to make two entries, one for each Rhea?, or is it OK to link both Rhea IDs to one term? Based on the paper, it seems like it would make more sense to have a single GO term since this activity is highly conserved and acts on a variety of imine substrates.

____

**RHEA:39975**          (APPROVED)
2-iminobutanoate + H2O = 2-oxobutanoate + NH4(+) 

**RHEA:40671**          (APPROVED)
2-iminopropanoate + H2O = NH4(+) + pyruvate 

___

**ENZYME entry: EC 3.5.99.10**

**Accepted Name:** 
- 2-iminobutanoate/2-iminopropanoate deaminase

**Alternative name(s):** 
- Enamine/imine deaminase

**Reaction catalysed:** 
- 2-iminobutanoate + H(2)O <=> 2-oxobutanoate + NH(3)
- 2-iminopropanoate + H(2)O <=> pyruvate + NH(3)

**Comment(s)**
- This enzyme, which has been found in all species and tissues examined, catalyzes the hydrolytic deamination of imine intermediates formed by several types of pyridoxal-5'-phosphate-dependent dehydratases, such as EC 4.3.1.19 and EC 4.3.1.17.
- The reactions, which can occur spontaneously, are accelerated to minimize the cellular damage that could be caused by these reactive intermediates.

**Comment by hdrabkin** [comment]
Need new reaction. Cannot have 2 rhea for one go term.

**Comment by hdrabkin** [comment]
However, 
'The reactions, which can occur spontaneously, are accelerated to minimize the cellular damage that could be caused by these reactive intermediates.;
Does this mean non-enzymatically?

**Comment by krchristie** [comment]
> Need new reaction. Cannot have 2 rhea for one go term.

That's what I thought. Is there an easy way to figure out if there is a grouping term?

**Comment by krchristie** [comment]
> However,
> 'The reactions, which can occur spontaneously, are accelerated to minimize the cellular damage that could be caused by these reactive intermediates.;
> Does this mean non-enzymatically?

Yes, it sounds to me that the reactions can happen non-enzymatically because the imino-x compounds are reactive and can damage various things in the cell by reacting with them. I don't see how that impacts the fact that the activities catalyzed by this enzyme is valid since apparently it's role is to deactivate imino-x compounds so that they don't damage something else by reacting with them.

**Comment by hdrabkin** [comment]
Usually, if it's 2 reactions for a single EC, the I use th EC as the grouping term and create the two subreactions 
so in this case I guess EC 3.5.99.10 is the grouping term (this term gets no RHEAs), and then the children would be each of the RHEAs (which also get the same EC for xref).

**Comment by krchristie** [comment]
So basically, I need to create 3 terms, one for the grouping term, associated with EC:3.5.99.10, and two child terms, each with a specific Rhea ID. Did I understand that correctly?

**Comment by sjm41** [comment]
I think that's right Karen - three terms needed - but I'll let Harold confirm.
Thanks for figuring this out, and sorry for the extra terms!!

**Comment by hdrabkin** [comment]
Just check that those RHEAs aren't used somewhere else in the ontology. If they are then there are more problems 8=(

**Comment by krchristie** [comment]
> Usually, if it's 2 reactions for a single EC, the I use th EC as the grouping term and create the two subreactions
> so in this case I guess EC 3.5.99.10 is the grouping term (this term gets no RHEAs), and then the children would be each of the RHEAs (which also get the same EC for xref). The RHEA ids would suffice for the def ref.

@hdrabkin - So, I put the EC xref on all 3 terms?

**Comment by krchristie** [comment]
> I think that's right Karen - three terms needed - but I'll let Harold confirm.
> Thanks for figuring this out, and sorry for the extra terms!!

@sjm41  -No worries, it's not a big deal to make three terms. I don't do as much with Rhea as @hdrabkin so I just wanted to make sure I'm doing it right.

**Comment by hdrabkin** [comment]
Sorry just saw your question. Yes, it's ok to put the EC on them all.

**Comment by krchristie** [comment]
> Sorry just saw your question. Yes, it's ok to put the EC on them all.

I made broad synonyms with the EC number as a reference for each of the specific reaction terms, so searching for the EC # should pull up all 3 terms. 

I did not make the EC # a direct dbxref on those two terms.

Is that OK?

**Comment by krchristie** [comment]
@hdrabkin - just added rhea label to this ticket too, in case you need to add these two new terms with Rhea IDs in your count
