### ISSUE TITLE
Resolution of protein-DNA covalent cross-linking

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#19856]
Hi GO,
I would need a new term to describe resolution of protein-DNA covalent cross-linking. Different proteases mediate this specific activity WSS1 in yeast, SPRTN or FAM11A in human.

Thanks

Sylvain

Name: Resolution of protein-DNA covalent cross-linking
Category: Process
Definition: the cleavage of covalent cross-link between DNA and a protein.

child of GO:0006281 DNA repair

PMID:32165630
PMID:27852435
PMID:27871366
PMID:30595436

**Comment by hdrabkin** [comment]
Hi @sylvainpoux 
' the cleavage of covalent cross-link between DNA and a protein.'
Is this the only step? Should it be an MF if so?

**Comment by ValWood** [comment]
I agree a function term would be good here. @Antonialock  asked me about requesting such a function term for

https://curation.pombase.org/pombe/curs/d43ed7beb6c57947/ro/
https://www.pombase.org/reference/PMID:27871365

29/05/2019
"Not sure if new GO terms should be requested....it is apparently involved in DPC (resolves covalent DNA protein crosslinks). The proteasome also does this but they act in different repair pathways. Later paper suggests it allows translesion synthesis to proceed over the lesion (since the interfering protein is degraded)"
and
"no GO term to describe the SS DNA dependent peptidase DPC bit, but not sure how to fit those terms"

 I suggested
"I would leave at  DNA repair for now, the next paper will probably spell the whole story... DPC seems like an acivity rather than a process so likely a better MF term is required..."

but I agree an MF term sounds appropriate here.

**Comment by hdrabkin** [comment]
Rethinking:

I think this IS a legit process in that there are more than one way to repair these (and more than one step needed to repair the DNA afterward. 
https://link.springer.com/article/10.1186/s13578-019-0366-z
Very informative

1. Nuclease-dependent repair mechanisms targeting DNA molecules: NER, HR, and others
2 Hydrolysis of the chemical bond between proteins and DNA by TDP1 and TDP2/ZNF451
  "Note: After hydrolysis by TDP1, the DNA has a 3′-phosphate end, which must be further processed by polynucleotide kinase phosphatase to generate a 3′-hydroxyl end that can be extended by polymerases ";
    THUS, there IS more than one step
3. Proteolysis-dependent repair mechanisms targeting cross-linked proteins: proteasomes, SPRTN/Wss1, and acidic repeat-containing protein/germ cell nuclear antigen-1

**Comment by ValWood** [comment]
But isn't this a specific molecular function that is part of this pathway?
How  should we capture the substrate of the protease?

**Comment by hdrabkin** [comment]
has_input during annotation?
 Resolution of protein-DNA covalent cross-linking
Definition: the cleavage of covalent cross-link between DNA and a protein.
  apparently can be done by hydrolysis or proteolysis. ; 
I think process just says cleavage; doesn't say by what

**Comment by ValWood** [comment]
I still don't understand why it isn't a molecular function term....

**Comment by hdrabkin** [comment]
The confusion is the name (resolution; which is more than one step), with the definition of 'the cleavage'.  If it's just the cleavage step here, then there are 3 unrelated ways to cleave the x-link product: one via excision (#1), one via hydrolysis (#2), and one via destruction of the protein (#3).

**Comment by ValWood** [comment]
OK that makes sense.
So i t sounds like a BP term might b needed to describe  the process, and a  specific MF protease  term to describe the  cleavage event performed by this family if there is enough information to describe this?

**Comment by hdrabkin** [comment]
Something like that; the proposed def is not good for the proposed process. Easiest thing would be to just annotate to DNA repair and if the gene product is a protease, then a proteolytic activity

**Comment by hdrabkin** [comment]
OR: maybe make the term, substituting 'removal' for cleavage, and use the review article cited above instead of the suggested PMID

**Comment by sylvainpoux** [comment]
Hi Val and Harold,
regarding the molecular function, I would say that as long we don't understand the molecular mechanism, it is better to have a process term since different proteins from different families cleave protein-DNA covalent cross-linking, suggesting that different molecular function terms might apply. We know the proteins here are proteases, but it is unclear where the cleavage takes place.

**Comment by hdrabkin** [comment]
Hi @sylvainpoux 
So perhaps if known they are proteases that can be handled via other annotations. The process name you suggest would cover all three ways of 'resolving' the x-linked lesion.  I'm in favor or making the term with the slight change to the definition so that it is not implied that it only refers to proteolysis.

**Comment by sylvainpoux** [comment]
Hi,
I would be wondering if the new term has been created?
Thanks
Sylvain

**Comment by hdrabkin** [comment]
@sylvainpoux are you ok with my suggested definition change  to 'the removal of covalent cross-link between DNA and a protein' and using the reference I suggeted ?

**Comment by hdrabkin** [comment]
@synvainpoux, I'm also wondering if the name should be 'protein-DNA covalent cross-linking repair' to be in line with the other children. Your suggested name would be a synonym

**Comment by sylvainpoux** [comment]
yes, that's fine. Sorry I didn't realized that you were waiting for my feedback
Thanks
Sylvain

**Comment by sylvainpoux** [comment]
fine for me too

**Comment by hdrabkin** [comment]
+id: GO:0106300
+name: protein-DNA covalent cross-linking repair
