### ISSUE TITLE
NTR: CCA tRNA nucleotidyltransferase

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#19854]
Hello:

Two enzymes from Dictyostelium described in PMID: 32717856 are characterized as "CCA-adding enzyme". Currently in the GO, this activity is associated with GO:0004810 tRNA adenylyltransferase activity (EC 2.7.7.25). However, a comment in this entry says "This term represents a deleted EC activity and is scheduled for obsoletion". 

A new enzymatic activity (EC 2.7.7.72), combining former EC 2.7.7.21 and EC 2.7.7.25 has been described by ExPASy described at: 

https://enzyme.expasy.org/EC/2.7.7.72

Could you please create a new GO term according to the guidelines suggested by ExPASy? 

Name: CCA tRNA nucleotidyltransferase
Ontology: function
Synonyms:
Definition: A tRNA precursor + 2 CTP + ATP <=> a tRNA with a 3' CCA end + 3 diphosphate

Reference: PMID: 32717856 Unusual Occurrence of Two Bona-Fide CCA-Adding Enzymes in Dictyostelium discoideum

**Comment by rjdodson** [comment]
Update on my request. I think this activity is already in the GO as:

GO:0052929 ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity. 

However, to avoid confusion, that GO entry should have the synonyms:
CCA tRNA nucleotidyltransferase
CCA-adding enzyme activity

**Comment by ValWood** [comment]
see also
https://github.com/geneontology/go-ontology/issues/11721

**Comment by ValWood** [comment]
see also
https://github.com/geneontology/go-ontology/issues/11721

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/17855

**Comment by hdrabkin** [comment]
I think I would modify the existing term with the corrected EC. And add RHEA while I'm at it.

**Comment by hdrabkin** [comment]
I think I need to merge all of these terms into one;
There is so far only one organism that uses two separate enzymes (one to add the CC, and another to add the A); otherwise, all others mentioned in #17855 refer to the same 'reaction" which is RHEA:14433.

**Comment by hdrabkin** [comment]
GO:0052929 ATP:3'-cytidine-cytidine-tRNA adenylyltransferase activity. is actually the reaction that adds an A to the CCA. As it turns out, organisms with TWO separate enzymes to perform the addition of CC, and then the addition of just A to the 3' end of a tRNA are quite numerous, and not just restricted to certain bacteria; Pombe needs two enzymes.
The majority of eukaryotic organisms carry only a single gene for a CCA-adding enzyme that acts on both the cytosolic and mitochondrial tRNA pool. Most bacteria only have one enzme.

At the moment, I don't see an activity in GO do describe adequate the entire CCA (in steps of course.).
Personal experience (I've purified the bacterial enzyme). The "CCA" enzyme can be used to 'swap' out the terminal A with radiolabeled ATP; so in that instance one is looking at just A addition, but that enzyme actually can do all three).

**Comment by pgaudet** [comment]
Annotations to GO:0004810 have been checked- 
* Human [PMID:11504732](http://amigo.geneontology.org/amigo/reference/PMID:11504732) was changed
* Dicty  [PMID:32717856](http://amigo.geneontology.org/amigo/reference/PMID:32717856) was disputed in  P2GO.

**Comment by sjm41** [comment]
@hdrabkin There are also some related parentage inconsistencies to clean up here - see #17855
