### ISSUE TITLE
NTRs for U2 snRNA methyltransferases

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#19868]
PMID:31913360 and PMID:32637152 describe a U2 snRNA m6A methyltransferase activity for the human and fly METTLL4 proteins, respectively.

Human METTL4 catalyzes Am to m6Am of U2 snRNA, whereas the fly protein is slightly different, catalyzing A to m6A of U2 snRNA. (the only difference between m6Am and m6A is the 2′-O-methyl group on the sugar)

I think we need some new terms/tweaks to MF and BP to accurately annotate these:
1. Currently, under RNA methyltransferase activity (GO:0008173), the only snRNA child term appears to be "U6 snRNA (adenine-(43)-N(6))-methyltransferase activity" (GO:0120048).
Looks like we need a new grouping term here of 'snRNA methyltransferease activity', and then put GO:0120048 along with 2 new MF terms for the activities described above as children.

2. Similar siutation for BP. Currently, under "RNA methylation" (GO:0001510), the only snRNA child term appears to be "snRNA 2'-O-methylation" (GO:1990437) -> "U6 2'-O-snRNA methylation" (GO:1990438). Looks like we need a new grouping term here of 'snRNA methylation', and then put GO:1990437 under that. I guess then we need two additional child terms for the U2-specific methylation, with and without the 2'-O-methylation?

For the human activity, I can see the appropriate Rhea xref (RHEA:62672) on the UniProt page:
https://www.uniprot.org/uniprot/Q8N3J2

Not sure that a Rhea xref currently exists for the fly activity.

**Comment by hattrill** [comment]
Hi @hdrabkin have you had a chance to look at this for @sjm41 yet?

**Comment by hdrabkin** [comment]
U2 snRNA methyltransferases  I need defs for new rxns 
  "Human METTL4 catalyzes Am to m6Am of U2 snRNA, whereas the fly protein is slightly different, catalyzing A to m6A of U2 snRNA. (the only difference between m6Am and m6A is the 2′-O-methyl group on the sugar)"
    Is there a specific position target in the RNA and is it the same for all?
Also, do we want additional process terms for each position?

**Comment by sjm41** [comment]
Can you base the definition for the human reaction on the RHEA reaction?
https://www.rhea-db.org/rhea/62672

And then mirror that for the fly reaction?

Just let me know if I should have a go at drafting the definitions myself, though I'm not sure of the preferred format/content etc....

**Comment by hdrabkin** [comment]
How do these sound
GO new1
snRNA methyltransferease activity
 Def: Catalysis of the transfer of a methyl group from a donor to a nucleoside residue in an snRNA molecule.
PMID:27573892
is_a  RNA methyltransferase activity (GO:0008173)

GO new2
U2 snRNA 2'-O-methyladenosine m6 methylase activity.
Catalysis of the reaction:   a 2'-O-methyladenosine in U2 snRNA +  S-adenosyl-L-methionine =  an N6-methyl-2'-O-methyladenosine in U2 snRNA +  S-adenosyl-L-homocysteine + H+
RHEA:62672; PMID:31913360
Is_a GO new1

GO new3
U2 snRNA  adenosine m6 methyase activity. 
Catalysis of the reaction:   a adenosine in U2 snRNA +  S-adenosyl-L-methionine =  an N6-methyl-adenosine in U2 snRNA +  S-adenosyl-L-homocysteine + H+.  PMID:32637152
is_a GO new1

And then make 
GO:0120048 an is_a to GO new1

**Comment by sjm41** [comment]
Thanks Harold - they look good to me.
(Note there's a little typo 'methyase' in the 'GO new3' name)

Do you think we need BP terms to match, given we already have GO:1990437 and GO:1990438?
Maybe:
```
- snRNA methylation (new) <- use this for fly METTLL4 
    - snRNA 2'-O-methylation (GO:1990437)
        - U6 2'-O-snRNA methylation (GO:1990438) 
        - U2 2'-O-snRNA methylation (new) <- use this for human METTL4
```

**Comment by hdrabkin** [comment]
activities added. still thinking on processes.

**Comment by pgaudet** [comment]
Right - I thought we wanted to git rid of the one-step BPs that mirror MFs. Are there abjections to that ? The first step would be to stop creating terms.

**Comment by hdrabkin** [comment]
Ok, since we want to delay until next call (Jan) I will stop here for now.

**Comment by sjm41** [comment]
I'd be happy with @hdrabkin's suggested BPs (and get rid of GO:1990438)

**Comment by hdrabkin** [comment]
Done but I left GO:1990438 in place for now as there are 14 annotations. I suppose I could merge it up into GO:1990437 (@pgaudet ?)

**Comment by pgaudet** [comment]
I'm not sure what's the appropriate level of granularity for those BPs. 

I would think that 'methylation' is not a process; what's interesting is to have an overview of all MFs needed to produce one product (U1, U2, U3, etc). See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4154345/

What do you think ?

**Comment by hdrabkin** [comment]
Well, generally speaking I would think a process is more than one step. All of the methylations, etc.  could be considered types of RNA modification (which we have as a GO term).

**Comment by sjm41** [comment]
Hi @hdrabkin 
Can you add 'snRNA modification' as an additional parent of 'snRNA methylation'. Then can remove redundant 'snRNA modification' parent on 'snRNA 2'O-methylation'.
![Screenshot 2021-02-01 at 08 11 41](https://user-images.githubusercontent.com/16306861/106431644-79a0fc00-6465-11eb-99d4-20633d2d3376.png)

**Comment by sjm41** [comment]
Hi @pgaudet . Thanks for finishing this off! Can I just check that, after your fixes, "snRNA methylation" still has "GO:0001510 RNA methylation" as a parent (in addition to the new 'GO:0040031 snRNA modification' parent)?  I think it should be.

**Comment by sylvainpoux** [comment]
Hi @pgaudet, thanks for sharing this discussion. 

This is a complex question and my opinion is that it is not the moment to delete most of these terms, at least now.

RNA modifications are not only catalyzed by the catalytic subunit, but in many cases, specificity is frequently provided by the non-catalytic subunit.

I will just give 2 examples: 

1) METTL14 (https://www.uniprot.org/uniprot/Q9HCE5). Most of m6 RNA modifications are catalyzed by METTL3, but the RNA-binding subunit is METTL14. It is therefore important to keep the process term for METTL14 to indicate that this RNA-binding protein is directly involved in m6A methylation. An option would be to create a "fake" FUNCTION term that specifically corresponds to METTL14. But which term? m6a methyltransferase activator activity? It is not really an activator since it binds RNA. The same for other components of the multiprotein complex such as WTAP or VIRMA? We could imagine to annotate the process via the complex (ComplexPortal), but I think we are not ready yet. At least, the Process term allows to indicate that this proteins is directly involved in RNA methylation.

2) TRMT112 (https://www.uniprot.org/uniprot/Q9UI30) is a non-catalytic subunit of many RNA/protein methyltransferases. We could again create FUNCTION terms like “tRNA methylation activator activity” or “rRNA (guanine-N7)-methyltransferase activity”. But we would then create 4-5 inaccurate terms  for this protein. Because we don’t know precisely what the exact function of this protein. We only know that TRMT112 binds catalytic methyltransferases and that it is essential for methylation. We however don’t know its precise FUNCTION.

So, my question is: is it really a priority to delete these terms? I agree that it is a good idea to deprecate combinatorial process terms (protein phosphorylation involved in …), but I’m not sure it is time to delete Process terms for molecular machines until we have good systems to replace them (via ComplexPortal, GO-CAM). 

Deleting these terms and replace them with FUNCTION terms would also imply a lot of retrofit annotation. It would take a lot of time to revisit publications for a limited added value.

Thanks

Sylvain

**Comment by pgaudet** [comment]
Thanks for spotting this @sjm41 
Added the relation back.
