### ISSUE TITLE
Membrane remodeling and Double membrane vesicle viral factory assembly

### ISSUE THREAD

**Issue by pmasson55** [geneontology/go-ontology#19943]
Dear GO curators,

Would it be possible to create
1. new_GO:
Name: membrane remodeling activity
Ontology: molecular_function
Synonyms: Membrane rearrangement activity

Ex: PMID: 32555292 (title: GTP hydrolysis by Synechocystis IM30 does not decisively affect its membrane remodeling activity)

Definition: Any protein that can remodel or rearrange membranes.

----

And also GO has  a cellular component termed :

"double membrane vesicle viral factory", would it be possible to create:

2. new_GO:
Name: double membrane vesicle viral factory assembly
Ontology Biological_process
Definition: Any protein involved in the assembly of a cytoplasmic viral factory that consists of a double-membrane bound vesicle.

Thanks for your help, you can ask if you need more information,
Patrick

**Comment by ValWood** [comment]
I agree it sounds like a process rather than an ctivity.

I think we have actively avoided "remodelling" in terms in favour of plain "organization" (we would use cell wall organization for  cell wall reorganization, for example). Usually I would qualify this with an extension to say when it is occuring.

For example
plasma membrane organization  happens_during conjugation with cellular fusion 
would be the way I would annotate the plasma membrane 'reorganization' that occurs during conjugation.

Otherwise it is hard to decide which parts of processes constitute "reorganization" (most things).


This might be slightly different though, I don't know, probably more info required @pmasson55 

Why not something like "cytoplasmic viral factory formation"

@ukemi  may have some insight into the historical avoidence or "reorganization"

We do have 7 terms with "reorganization " in them, but  I think we should probably purge these.

**Comment by ValWood** [comment]
I opened a ticket about reorganization
https://github.com/geneontology/go-ontology/issues/14087
then closed it with the comment "for another day"

**Comment by pgaudet** [comment]
Will not create 'membrane remodeling activity' as this is not understood sufficiently at the molecular level.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140526
+name: double membrane vesicle viral factory assembly
+namespace: biological_process
+def: "A process that results in the assembly of a cytoplasmic viral factory consisting of a double-membrane bound vesicle." [PMID:32555292]
+is_a: GO:0022607 ! cellular component assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19943 xsd:anyURI
+created_by: pg
+creation_date: 2020-09-29T08:26:51Z
