### ISSUE TITLE
NTRs for nucleus: mitotic nuclear bridge

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#19946]
NTR mitotic nuclear bridge
Definition: The narrow constricted region that forms around the anaphase spindle and links a segregating nucleus during closed mitosis.
Parent : nucleus
synonym: nuclear bridge (broad)

NTR mitotic nuclear bridge stalk 
Definition: The region of a mitotic nuclear bridge proximal to the neck of each daughter nucleus
Parent: NTR mitotic nuclear bridge

NTR  mitotic nuclear bridge midzone
Definition: The central region of a mitotic nuclear bridge where basketless nuclear pores are corralled into a characteristic bulghe containing excess membrane.
Parent: NTR mitotic nuclear bridge

Citing

Closed mitosis requires local disassembly of the nuclear envelope.
Dey G, Culley S, Curran S, Schmidt U, Henriques R, Kukulski W, Baum B.
Nature. 2020 Sep;585(7823):119-123. doi: 10.1038/s41586-020-2648-3. Epub 2020 Aug 26.
PMID: 32848252

<img width="685" alt="Screenshot 2020-09-06 at 09 36 32" src="https://user-images.githubusercontent.com/7359272/92322715-e46f1800-f02a-11ea-8973-92f96e94b9d1.png">

**Comment by mah11** [comment]
I would rejig the text definitions, especially for the first one, because "links a segregating nucleus" doesn't make sense (links it to what?).

id: GO:new1
name: mitotic nuclear bridge
def: A narrow constricted region of the nucleus that forms around the anaphase spindle during closed mitosis, and connects the main portions of the newly forming daughter nuclei.
synonym: "nuclear bridge" BROAD []
**is_a: ?**
relationship: part_of GO:0005634 ! nucleus

id: GO:new2
name: mitotic nuclear bridge stalk
def: Either of the regions of a mitotic nuclear bridge proximal to the main portion of each daughter nucleus. The nuclear envelope in the stalk regions is depleted of nuclear pore complexes.
**is_a: ?**
relationship: part_of GO:new1 ! mitotic nuclear bridge

id: GO:new3
name: mitotic nuclear bridge midzone
def: The central region of a mitotic nuclear bridge, distal to the main portions of the daughter nuclei. The midzone forms a bulge that is enriched in nuclear pores that lack baskets.
**is_a: ?**
relationship: part_of GO:new1 ! mitotic nuclear bridge

**Comment by pgaudet** [comment]
How about is_a 'cellular anatomical entity' - same as 'half bridge of spindle pole body' ?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140510
+name: mitotic nuclear bridge
+namespace: cellular_component
+def: "A narrow constricted region of the nucleus that forms around the anaphase spindle during closed mitosis, and connects the main portions of the newly forming daughter nuclei." [PMID:32848252]
+synonym: "nuclear bridge" BROAD []
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0005634 ! nucleus
+created_by: pg
+creation_date: 2020-09-07T09:59:46Z
+
+[Term]
+id: GO:0140511
+name: mitotic nuclear bridge stalk
+namespace: cellular_component
+def: "Either of the regions of a mitotic nuclear bridge proximal to the main portion of each daughter nucleus. The nuclear envelope in the stalk regions is depleted of nuclear pore complexes." [PMID:32848252]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0140510 ! mitotic nuclear bridge
+created_by: pg
+creation_date: 2020-09-07T10:06:23Z
+
+[Term]
+id: GO:0140512
+name: mitotic nuclear bridge midzone
+namespace: cellular_component
+def: "The central region of a mitotic nuclear bridge, distal to the main portions of the daughter nuclei. The midzone forms a bulge that is enriched in nuclear pores that lack baskets." [PMID:32848252]
+is_a: GO:0110165 ! cellular anatomical entity
+created_by: pg
+creation_date: 2020-09-07T10:08:02Z

**Comment by ValWood** [comment]
ha ha good point. I originally put "links segregating nuclei" then made it non-plural without changing the context.
