### ISSUE TITLE
Fusogenic activity

### ISSUE THREAD

**Issue by pmasson55** [geneontology/go-ontology#19942]
Dear GO curators,

Would it be possible to create
new_GO:
Name
    Fusogenic activity 
Ontology
    molecular_function
Synonyms
    membrane fusion activity

Ex: PMID: 11493675, PMID: 32100701 

Definition:
Any protein with fusogenic activity that mediates membrane fusion.

Thanks for your help,
Patrick

**Comment by cmungall** [comment]
The def is a bit circular :-)

So is this just a shortcut for positively regulates some membrane fusion?

**Comment by ValWood** [comment]
This review on membrane fusion looks useful
https://www.cell.com/fulltext/S0092-8674(03)00112-0

We have membrane fusion as a process, but certainly, for viral proteins (and possibly in eukaryotes)  there should also  be an MF.

The (current) process is defined:
The membrane organization process that joins two lipid bilayers to form a single membrane.

so maybe the MF should be
The activity that joins two lipid bilayers to form a single membrane?

Also, in eukaryotes most of these  'fusion proteins' seem to be GTPases,  so maybe we would also require
"membrane fusion GTPase  activity" as a descendant (to avoid annotation of the same activity in different branches).

In eukaryotes, the anchoring/tethering/docking events which precede the membrane fusion seem to be included in the process/pathway. For example: 
SNAP receptor activity (GO:0005484
Acting as a marker to identify a membrane and interacting selectively with one or more SNAREs on another membrane to mediate membrane fusion.

is part of membrane fusion process but does not itself have fusion activity (or maybe it does?).

**Comment by pmasson55** [comment]
Hi Val,
Thx for your input, your definition looks good for the MF.
"The activity that joins two lipid bilayers to form a single membrane ".
A lot of viruses possess fusion proteins. They get usually cleaved to release the chain that possess this activity in order to prevent undesired fusion too early... This is the case for SARS-COV2 spike protein S2 (https://www.uniprot.org/uniprot/P0DTC2) or Human respiratory syncytial virus (https://www.uniprot.org/uniprot/P03420). 
Concerning eukaryotes, I'm not sure if SNARE proteins actually possess this exact same activity although they definitively mediate fusion. Should we restrict the term to viruses?

**Comment by pgaudet** [comment]
Here are the 2 new terms: 

+[Term]
+id: GO:0140522
+name: fusogenic activity
+namespace: molecular_function
+def: "The activity of joining two lipid bilayers to form a single membrane." [PMID:11493675, PMID:12600315, PMID:32100701]
+is_a: GO:0003674 ! molecular_function
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19942 xsd:anyURI
+created_by: pg
+creation_date: 2020-09-24T09:45:21Z
+
+[Term]
+id: GO:0140523
+name: membrane fusion GTPase activity
+namespace: molecular_function
+def: "A GTPase activity that mediates the joining two lipid bilayers to form a single membrane." [PMID:29663589]
+is_a: GO:0140522 ! fusogenic activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19942 xsd:anyURI
+created_by: pg
+creation_date: 2020-09-24T09:49:40Z

Thanks, Pascale

**Comment by cmungall** [comment]
This feels odd. First we have a single child, often a bad smell.

It seems we're not super-clear about when to apply these? Two of the refs
are about viral proteins (albeit one coopted in mammals). Is it obvious to
curators which genes this would apply to? Do we have a strategy for making
annotations reasonably comprehensive? Of course, annotations are never
complete, open world assumption, etc. But IMO we confuse users when we have
some term representing some pretty core biology and there is either nothing
or deceptively few genes under it.

There is no link to the process of membrane fusion. Surely all fusogenic
activity is part of a membrane fusion process?

What about the reciprocal. Is it possible to have a membrane fusion process
without fusogenic activity?

**Comment by ValWood** [comment]
So at present we have proteins with "fusogenic activity", but we never had such a term before.

I have annotated these (which are all GTPases so far), to 
GTPase involved_in membrane fusion

I  would therefore  like a term which combined the GTPase and  'fusogenic activity' (because I don't want to make separate annotations for a single activity, and  if fusogenic activity exists I want to use it, otherwise fusogerns would be annotated in different ways.

I assume that, if the viral protein is not a GTPase it uses another mechanism that we don't yet know to perform the same activity. So although it seems odd to have a single descendant I think it is probably justified here.

However, these terms might be difficult to find. I don't really like "fusogenic activity" possible because I never heard it before, and it is an adjective.
Possibly this would be better as a synonym? and standardising the  the names to "membrane fusion activity"?

and it should definitely be related to the membrane fusion process (it is also a process, I think, because in some pathways there are preceding steps like 'docking'
which are sometimes  performed by the same protein:

[Uploading Screenshot 2020-09-25 at 08.04.45.png…]()
https://www.pnas.org/content/108/27/11133

But sometimes multiple proteins

<img width="264" alt="Screenshot 2020-09-25 at 08 21 02" src="https://user-images.githubusercontent.com/7359272/94238292-0f50db80-ff08-11ea-849f-5cdd7db18bf6.png">

https://www.researchgate.net/publication/277191230_Function_of_human_surf4_in_the_early_secretory_pathway/figures?lo=1

because here I would annotate the tethering proteins to the membrane fusion pathway.

@pmasson55 is the mechanism  of the viral  fusion protein known? Can it fuse membranes in isolation or does it need to co-opt some of the host machinery?  (I could not access the paper, even with my VPN)...because membrane fusion in eukaryotes generally seems to be an energy requiring process. 
For instance, one possibility is that it could act as a 'decoy tether'. If that were the case  then it  might be better to make only a "membrane fusion" process annotation rather than a molecular function, perhaps?

**Comment by pmasson55** [comment]
Hi Val, Chris, Pascale

@cmungall ,  the strategy here would be to annotate all viral fusion proteins, which concerns  basically most of enveloped viruses. From a curator point of view (at least for viral proteins..) it's  pretty clear what to annotate with this term (and there are a lot of these proteins...).
@ValWood , yes viral fusion proteins actually can fuse membranes in isolation, they usually require a step to activate them (cleavage or so)  in order to prevent undesired fusion... : (PMID:32641474) "These gB chimeras were intrinsically fusion active and led to the formation of multinucleated cell syncytia when expressed in the absence of other viral proteins." 
@ValWood, I think  membrane fusion activity is very good 
Here is another paper describing viral fusion in detail (PMID:10332732)
And FYI  (PMID: 29254991) where " In this Review, we focus on fusogens – specialized proteins that function to directly fuse membranes"
Hope this helps...

**Comment by ValWood** [comment]
OK in this case I think the current arrangement is OK.

The F-P link needs adding.
and the labels could probably be more consistent.

**Comment by pgaudet** [comment]
Hi, 

I've added 'part of' membrane fusion' to 'fusogenic activity', and changed the label of 'membrane fusion GTPase activity' to 
'GTPase-dependent fusogenic activity'. Let me know if there are other issues with these terms. 

Thanks, Pascale

**Comment by cmungall** [comment]
It's still not clear to me what our strategy is to populate this for non-viruses.

@ValWood sounds like you are planning to manually migrate all annotations to GTPase activity that have extension involved-in membrane fusion to the "membrane fusion GTPase activity" term in 21e9d7d25b4e5002c8e593f03b5ddd51c47b4515 ? What's our strategy for ensuring population from other databases?

I'm worried we will end up with a term that will look very confusing (outside of viruses), with ad-hoc population of annotation. I know we of course have this in many cases already but perhaps we shouldn't make it worse.

**Comment by ValWood** [comment]
> Re It's still not clear to me what our strategy is to populate *this for non-viruses*  

I think that horse has bolted.
* insert "any species" whenever we add a new term.

My understanding is that for GO and most participating resources, annotation breadth and specificity isn't a priority.  So, I'm only really trying to ensure that the next time a curator comes with a "membrane fusion activity" they will locate the correct term.  I think the new arrangement will permit this going forwards, because any combination ion "membrane fusion" "fusogenic" should locate the correct term, and will group the gene products which have the same molecular activity, albeit by a different mechanism.

The 'population' of the new term, I had not considered because most of the GO annotation that exists is _ad-hoc_ and non-specific. As far as I am aware, there are not many resources strive to get every annotation as specific as possible (in fact at the last GO meeting, I remember people saying that old annotation would not be revisited if it was correct but not specific enough).   So this is not a problem with this particular term, it's an endemic issue for GO  annotation generally. And I have stopped being a good citizen and advising where more specific annotation  would be appropriate many years ago. Now I only report obvious errors.

The way I handle this issue for PomBase is to scan the new ontology tickets and migrate annotation if a new, more specific but more appropriate term is added. This is why the daily digest was useful, I could immediately follow tickets where new detail was added to the ontology and migrate annotations as necessary.

The only tool/strategy we have consortium-wide is to make terms which we know are not specific enough (where a descendant should always be possible), unavailable for direct annotation. We have begun to do this but I suspect the warnings are largely ignored (I guess Jenkins would answer this), and it would not work in this case because we cannot always be more specific about a GTPase.

GO could also, (as with obsoletions), announce when a new term is added that might be more appropriate for existing annotations and hope that people migrate? But we know that warnings and soft checks are ignored, because they are not high priority. 
There are ~400 experimental annotations to membrane fusion,  but only a small number of these  are  GTPases catalysing the fusion event (perhaps a combination of term and PANTHER family could provide the list?)

The other option is that we don't represent these different   "membrane fission" activities in the same branch-  but that seems wrong too based on the definition.  Unless these 'activities' are different enough to be distinct (perhaps we could differentiate them further? - but they both appear to catalyse the fusion of lipid bilayers?)

Note also, that we already have a term for
membrane scission GTPase motor activity (GO:1990606)
To describe the dynamin family proteins which are involved in membrane fission
https://en.wikipedia.org/wiki/Dynamin

(Aside: Although historically people seem to prefer
GO:0003373    dynamin family protein polymerization involved in membrane fission
GO:0003374    dynamin family protein polymerization involved in mitochondrial fission
which combine information about protein family/gene product/ function and process.....)

The reason I prefer this precision in the GTPase terms is that membrane fusion/fisson  are larger processes/pathways which involve other  GTPases,  so  
"GTPase part_of membrane fusion"  
could potentially mean lots of  different things. This way, I can locate the actual GTPase which is acting directly to catalyse the fusion or scissoring of the membrane.
