### ISSUE TITLE
basal body, basal granule, kinetosome

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#19944]
Dear Midori,
Im missing the term "basal body" in the cellular component terms of the GeneOntology. Could you please add it? Its for the localization of ec 2.3.1.108, PMID:29869029 at the BRENDA Database.

Definition of basal body (Merriam Webster Dictionary)
    a minute distinctively staining cell organelle found at the base of a flagellum or cilium and identical to a centriole in structure — called also basal granule, kinetosome

Good wishes, thank you,
Marion

**Comment by krchristie** [comment]
Hi,

We already have a term for `ciliary basal body`, with this definition and other info: 

**id:** GO:0036064
**name**: ciliary basal body
**namespace**: cellular_component
**def**: "A membrane-tethered, short cylindrical array of microtubules and associated proteins found at the base of a eukaryotic cilium (also called flagellum) that is similar in structure to a centriole and derives from it. The cilium basal body is the site of assembly and remodelling of the cilium and serves as a nucleation site for axoneme growth. As well as anchoring the cilium, it is thought to provide a selective gateway regulating the entry of ciliary proteins and vesicles by intraflagellar transport." [GOC:cilia, GOC:clt, PMID:21750193]
**comment**: In most eukaryotic cells, 'ciliary basal body' (GO:0036064) and 'centriole' (GO:0005814) represent a common entity that cycles through its function in cell division, then ciliogenesis, then cell division again. However, these structures are modified extensively as they transition into each other, and may contain different proteins, specific to each component.
**synonym**: "basal body" BROAD []
**synonym**: "cilial basal body" EXACT []
**synonym:** "cilium basal body" EXACT [GOC:bf]
**synonym**: "microtubule basal body" EXACT []
**xref**: NIF_Subcellular:sao11978067
**intersection_of**: GO:0005815 ! microtubule organizing center
**intersection_of**: part_of GO:0005929 ! cilium
**relationship**: part_of GO:0005929 ! cilium
**relationship**: part_of GO:0042995 ! cell projection
**created_by:** bf
**creation_date**: 2011-12-15T10:40:20Z

Note that we also have a separate term for `centriole`, as discussed in the comment that is attached to the term for `ciliary basal body`.

I'm pretty familiar with eukaryotic cilia, and I'm not familiar with either "basal granule" or "kinetosome" as synonyms for the cilary basal body. 

When I searched for "basal granule" in PubMed, I only got 9 papers, most of which were about basal granule cells, and then 1 about bacterial flagella, and then 1 about tetrahymena cilia where it says in the abstract that `The two external axonemal tubules terminate in a basal granule immediately above the basal plate in the distal end of the basal body.` which sounds to me like the basal granule is near the basal body, but not part of it. At the moment, I'm not keen on adding this as a synonym as it doesn't seem to be in current usage and the little bit of old usage I see isn't clear cut that it is a synonym. If you have a good source for using this phrase as a synonym, let me know and I'll reconsider.

When I search for "kinetosome" in PubMed, I get several thousand papers, though most of what is highlighted is actually "basal body". Highlighting for "kinetosome" in abstracts suggests that this term is common in ciliated protists, which I'm not particularly well read on except for chlamydomonas. These two papers (PMID:32523809, PMID:32544843) might be a good references for this synonym, or let me know if you have a better suggestion. Since I don't remember ever coming across usage of kinetosome for the ciliary basal body in vertebrates, nemotodes, or Drosophila, I think I'll put it in as a NARROW synonym, but let me know if you think it should be something else.

Thanks,

-Karen

**Comment by brendamg** [comment]
Hmm, I`m not familiar with eukaryotic cilia. But it seems to be reasonable. "In interphase, immunolabeled ATAT1 was observed in centrioles, nuclei, and basal bodies if the cells projected primary cilia." I`ll use this term. Thanks, Marion

**Comment by krchristie** [comment]
> Hmm, I'm not familiar with eukaryotic cilia. But it seems to be reasonable. "In interphase, immunolabeled ATAT1 was observed in centrioles, nuclei, and basal bodies if the cells projected primary cilia." I'll use this term. Thanks, Marion

I only have access to the abstract, not the full text, but from the phrase "and basal bodies if the cells projected primary cilia." in the sentence you quote, the term `ciliary basal body` is definitely appropriate for that localization.

**Comment by krchristie** [comment]
A review that could be used as a reference for the kinetosome synonym:

> Chapman MJ, Dolan MF, Margulis L. Centrioles and kinetosomes: form, function, and evolution. Q Rev Biol. 2000;75(4):409-429. doi:10.1086/393621 
PMID:11125699
