### ISSUE TITLE
NTR: regulation terms for viral gene silencing in virus induced gene silencing

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#19958]
The process that I want capture from https://pubmed.ncbi.nlm.nih.gov/30308158/  is 

RNA virus protein CrPV-1A inhibits AGO-2 in the production of siRNAs involved in RNA virus gene silencing.

AGO-2 is involved in RNA virus gene silencing by siRNAs (produced from diced viral dsRNAs)  via silencing complex loading.

I think that having regulation terms for 'viral gene silencing in virus induced gene silencing' GO:0060145  
Def "The posttranscriptional gene silencing of viral genes after viral infection. "
might do the job, but I am not quite sure about this. 

@pgaudet - have you any insight from the pathogens working group?

![Screenshot 2020-09-08 at 10 59 58](https://user-images.githubusercontent.com/11865746/92462721-bd4b4e80-f1c2-11ea-82af-f1d6c452efbf.png)

**Comment by hattrill** [comment]
Any chance of having a new term before Nov release?

**Comment by pgaudet** [comment]
Thanks for the ping @hattrill 

Looks like we need the normal host process 'RNAi-mediated antiviral immunity', and this term would be 'suppression of host RNAi-mediated antiviral immunity' - does that seem right to you ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Looking at the paper, that does seem like a better solution/description. I would be happt with that.

**Comment by pgaudet** [comment]
The term 'virus induced gene silencing' is described as a technique, see PMID:12828943, http://www.plantphysiol.org/content/142/1/21 and many other references. Otherwise it does seem like its the same as ' RNAi-mediated antiviral immune response'. 

In https://www.longdom.org/open-access/applications-of-virus-induced-gene-silencing-vigs-in-plant-functional-genomics-studies-2329-9029-1000229.pdf
they describe VIGS as follows: 

>  Post  transcriptional  gene  silencing  (PTGS)  is  an  epigenetic phenomenon  that  results  in  the  sequence specific  degradation  of endogenous mRNAs [8]
> There are several evidences pointing to the evolution of PTGS as an antiviral  mechanism  in  plants  [1,8,13].  Viruses  by  themselves  can trigger PTGS in certain plant species [8,14].
> Viruses are not passive in the face of plant defense, and they have evolved proteins that can act as suppressors of PTGS [8,15]. The main triggering molecule of PTGS is double stranded RNA, dsRNA.

@tberardini do you think I can rename that term RNAi-mediated antiviral immune response ? 

GO:0009616    virus induced gene silencing |  179 annotations in QuickGO

We also need to look at children (can be done later) 

GO:0051215 DNA virus induced gene silencing | 0 annotations (as mentioned above, the main trigger is RNA)
GO:0051214 RNA virus induced gene silencing | 97 annotations in QuickGO
-> is probably the same process / merge OR obsolete and suggest REPLACED BY GO:0009616 RNAi-mediated antiviral immune response

GO:0060144 host cellular process involved in virus induced gene silencing | 0 annotations
GO:0060146 host gene silencing in virus induced gene silencing | 0 annotations
-> probably do not exist -> obsolete

GO:0060145 viral gene silencing in virus induced gene silencing | 10 annotations in QuickGO
GO:0060150 viral triggering of virus induced gene silencing  | 0 annotations
-> probably means the same as 'RNAi-mediated antiviral immune response'  = merge OR obsolete and suggest REPLACED BY GO:0009616 RNAi-mediated antiviral immune response

@tberardini 
@hattrill 
does this seem OK to you ? 

Thanks, Pascale

**Comment by tberardini** [comment]
> @tberardini do you think I can rename that term RNAi-mediated antiviral immune response ?

@pgaudet  Yes. Please retain 'VIGS' and 'viral-induced gene silencing' as synonyms.  Thanks.

**Comment by pgaudet** [comment]
New term created: 

+[Term]
+id: GO:0140533
+name: suppression of host RNAi-mediated antiviral immune response
+namespace: Any process in which a symbiont stops, prevents, or reduces the rate or extent of the host's RNAi-mediated antiviral immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction.
+namespace: biological_process
+synonym: "suppression of host RNAi-mediated antiviral immunity" EXACT []
+synonym: "suppression of host RNAi-mediated gene silencing" EXACT []
+is_a: GO:0052170 ! suppression by symbiont of host innate immune response
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19958 xsd:anyURI
+created_by: pg
+creation_date: 2020-10-28T07:55:27Z
+

Other changes: 

 **id: GO:0009616**
-name: virus induced gene silencing -> change label to 'RNAi-mediated antiviral immunity'
- changed def to  "RNA-mediated post-transcriptional gene silencing mechanism that protects against foreign organism invasion by restricting viral replication and dissemination." [GOC:jl, PMID:17693253, PMID:21724934, PMID:23686236, PMID:24732439, PMID:31100912]
- changed comment to: Virus induced gene silencing (VIGS) is used as a technique to control plant gene expression; when used in that context, this does not represent a normal biological process and is outside the scope of GO.

Also, it looks like the response to DNA viruses and RNA viruses use slightly different pathways (see PMID:17693253), at least in plants, so I kept both terms: 
 id: GO:0051214
-name: RNA virus induced gene silencing -> change label to  "RNAi-mediated antiviral immunity against RNA virus"
- changed def to   "Gene silencing induced by RNA viruses leading to a sequence-specific degradation of target mRNAs or post-transcriptional gene silencing. In plants, DCL4 is the primary Dicer to detect RNA viruses." [PMID:15165191]
 synonym: "RNA VIGS" EXACT []
+synonym: "RNA virus induced gene silencing" EXACT []
 synonym: "RNA virus-induced gene silencing" EXACT []
-is_a: GO:0009616 ! virus induced gene silencing
+xref: PMID:17693253
+is_a: GO:0009616 ! RNAi-mediated antiviral immunity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/19958 xsd:anyURI
 
 [Term]
 id: GO:0051215
-name: DNA virus induced gene silencing -> change label to "RNAi-mediated antiviral immunity against DNA virus"
- changed def to  "Gene silencing induced by DNA viruses leading to a sequence-specific degradation of target mRNAs or post-transcriptional gene silencing.  In plants, DCL3 is the primary Dicer to detect DNA viruses." [PMID:15165191, PMID:17693253, PMID:23151511]

I hope this addresses what you wanted @hattrill 
Thanks, Pascale

**Comment by pgaudet** [comment]
Open question: 
- Is this adaptive immunity or innate immunity ? Right now I have it under innate immunity, but in some papers they describe this (or a different process? ) as adaptive immunity, see for eg PMC1262564. If someone wants to change this or create new terms please let me know.

**Comment by pgaudet** [comment]
Also merged: 
GO:0060145 viral gene silencing in virus induced gene silencing | 10 annotations in QuickGO
GO:0060150 viral triggering of virus induced gene silencing | 0 annotations

into GO:0009616 'RNAi-mediated antiviral immune response'

**Comment by hattrill** [comment]
Thanks @pgaudet that seems fine to me. 

 Certainly, 'innate immunity' is where we're coming from.

**Comment by hattrill** [comment]
Hi @pgaudet can I ask a question about using "suppression of host RNAi-mediated antiviral immune response" - when host proteins are "hijacked" to aid this, can we use this term? It is resticted to the symbioant in the definitiion and never_in metazoans. 
Or perhaps would be better to have regulation terms for 'RNAi-mediated antiviral immune response' and its children and use those for hijacked proteins?

**Comment by pgaudet** [comment]
Hi @hattrill 
Generally we would like to hijacked proteins to be annotated as such, to show that this is not their normal function. For example we have 'virus receptor activity'. 

In this case I dont understand how the host would mediate its own immune response ?

**Comment by hattrill** [comment]
So, the viral protein forms a new E3 ligase complex with host components and then targets the host AGO-2 protein which mediates the viral silencing for degradation.

**Comment by pgaudet** [comment]
Interesting !! 

@ValWood @dsiegele @mgiglio99 @thomaspd @cmungall what do you think ?

**Comment by ValWood** [comment]
The same as @pgaudet  - these are not normal/evolved processes for the host, and GO represents normal processes. The host pathways are being manipulated by the pathogen. It's interesting, but outside the scope of GO. 

You can annotate the viral proteins to whichever  inhibition of the relevant host enzymes/pathways.

For more detail  of the specific phenotypes caused by the virus you would need to use a pathogen-host interaction phenotype ontology that models this in more detail.

**Comment by hattrill** [comment]
Ok. yes - used for viral protein.
