### ISSUE TITLE
Cleaning up the 'GO:0007534 gene conversion at mating-type locus'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#19999]
From #18777 - other changes needed in the area of homologous recombination, specifically under 'GO:0007534 gene conversion at mating-type locus'

 - [x]  'GO:0034624 DNA recombinase assembly involved in gene conversion at mating-type locus' -> 0 annotations -> obsolete, GO-CAM model
 - [x] 'GO:0000728 gene conversion at mating-type locus, DNA double-strand break formation' -> 2 EXP -> substep, merge into 'GO:0007534 gene conversion at mating-type locus'
 - [x]  'GO:0031292 gene conversion at mating-type locus, DNA double-strand break processing'  -> 6 EXP -> substep, merge into 'GO:0007534 gene conversion at mating-type locus'
 - [x] 'GO:0000734 gene conversion at mating-type locus, DNA repair synthesis'  -> 2 EXP -> substep, merge into 'GO:0007534 gene conversion at mating-type locus'
 - [x]  'GO:0061500 gene conversion at mating-type locus, termination of copy-synthesis'  -> 1 EXP -> substep, merge into 'GO:0007534 gene conversion at mating-type locus'
 - [x] 'GO:0010708 heteroduplex formation involved in gene conversion at mating-type locus'  -> 0 annotations -> substep, merge into 'GO:0007534 gene conversion at mating-type locus'
 - [x] 'GO:0034636 strand invasion involved in gene conversion at mating-type locus '  -> 1 EXP -> substep, merge into 'GO:0007534 gene conversion at mating-type locus'

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0034624 DNA recombinase assembly involved in gene conversion at mating-type locus'. The reason for obsoletion is that this is a MF that is part of a BP and should be represented by a GO-CAM model. 

There are no annotations and no mappings to this term. This term is not present in any subsets. 

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on September 24th, 2020. Unless objections are received by September 24th, 2020. we will assume that you agree to this change.

Comments may be added to the ticket : https://github.com/geneontology/go-ontology/issues/19999



Thanks, Pascale

**Comment by mah11** [comment]
Will a more general "DNA double-strand break formation" term be added? If not, how should the substep that GO:0000728 represents be modeled? Its current superclass, GO:0090305 ! nucleic acid phosphodiester bond hydrolysis, looks insufficiently specific. (The answer will be useful for FYPO logical defs as well as annotations.)

**Comment by ValWood** [comment]
also, just noticed:


Definition | Parents
The cell cycle process in which double-strand breaks are generated at defined hotspots throughout the genome during meiosis I. This results in the initiation of meiotic recombination.

but isn't this a step in the recombination process?

If not it seems odd to have descendant terms like

meiotic DNA double-strand break formation involved in reciprocal meiotic recombination

it is either part of recombination, or it isn't?

**Comment by pgaudet** [comment]
> how should the substep that GO:0000728 represents be modeled

Isn't that the MF endonuclease activity ? Do we need a process ?

**Comment by ValWood** [comment]
@mah11  is on vacation.

I'm not sure that 
"DNA double-strand break formation" isn't a process because there are gene products annotated that are not andonucleases.

The term is defined
"The cell cycle process in which double-strand breaks are generated at defined hotspots throughout the genome during meiosis I. This results in the initiation of meiotic recombination. PMID:11529427"

Does this mean that  it is part of recombination or not (I would say that it is)
Perhaps these annotations should be just to  the relevant 'recombination' term. I think some of these are "required for ds-break formation" because they are required upstream to localize the nuclease to the double-strand break

but it might make more sense to  annotate the nuclease to

'endonuclease' involved in "meiotic DNA recombination"  (or whatever)  and to try to annotate functions on the other participating  gene products (or not), depending if we have the  information.

We should wait to see what @mah11 thinks., and also ask SGD.

There are only 48 annotation (far fewer genes)

These are the annotated fission yeast genes (6 genes/12 annotations)
https://www.pombase.org/results/from/id/b4befca6-b84d-4cd2-abba-d92f0e69bf3b

These are the 
17 SGD annotations
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0042138&taxonId=559292&taxonUsage=descendants&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

**Comment by mah11** [comment]
>>  how should the substep that GO:0000728 represents be modeled?
> 
> Isn't that the MF endonuclease activity ? Do we need a process ?

I don't know enough about recombination to answer this question directly.

It seems that at present, GO isn't internally consistent, because it has "DSB formation" terms for types of recombination (in addition to GO:0000728, there's GO:0042138 ! meiotic DNA double-strand break formation and its subclasses), but not a generic term. The existing terms give an impression that GO has regarded DSB formation as a process until now, although of course that can change if need be.

I'm not making a statement about whether the DSB formation step(s) fit MF or BP better; rather, I'm asking what GO will have in place when this work is done. (I doubt that I can easily build a logical definition for the phenotype term I have in mind using an endonuclease MF term, but it's not a big problem; I just want to know if that will be the case.)

> @mah11 is on vacation.

No I'm not.

**Comment by deustp01** [comment]
My colleague Hannah Klein has spent her career studying the relationships among replication, recombination, repair, and transcription. In that time, I doubt she has spent as much as 5 minutes thinking about GO, process-function distinctions, and process boundaries, but she's certainly an expert in the issues coming up in this ticket - https://med.nyu.edu/faculty/hannah-l-klein (the web page has contact information).

**Comment by pgaudet** [comment]
I've added those relations: 

+relationship: has_part GO:0000729 ! DNA double-strand break processing
+relationship: has_part GO:0000731 ! DNA synthesis involved in DNA repair
+relationship: has_part GO:0030491 ! heteroduplex formation
+relationship: has_part GO:0042148 ! strand invasion
+relationship: has_part GO:0071170 ! site-specific DNA replication termination

If those subprocesses were right, then this should be OK ? 

Thanks, Pascale
