### ISSUE TITLE
Merge nuclear x complex terms for nuclear complexes that are not always part of the nucleus (merge location specific versions of complexes)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20000]
Hello, 

Many 'x nuclear complex' terms correspond to complexes that are not always part of the nucleus. 

This includes: 
- GO:0000788 nuclear nucleosome (21 EXP) ->  merge into GO:0000786 nucleosome (39 EXP)
- GO:0000787 cytoplasmic nucleosome (1 EXP) ->  merge into GO:0000786 nucleosome (39 EXP)

- GO:0000790 nuclear chromatin (876 EXP) -> GO:0000785 chromatin (301 EXP)

- GO:0005719 nuclear euchromatin  (67 EXP) ->  GO:0000791 euchromatin (30 EXP)
- GO:0005720 nuclear heterochromatin (83 EXP) ->  GO:0000792 heterochromatin (108 EXP)

Other related terms that were not in the original list: 
- GO:1902377 nuclear rDNA heterochromatin (13 EXP) ->  GO:0033553 rDNA heterochromatin (23 EXP)
- GO:0031618 nuclear pericentric heterochromatin (68 EXP) -> GO:0005721 pericentric heterochromatin (36 EXP)
- GO:1904834 nuclear CENP-A containing chromatin (4 EXP) -> GO:0061638 CENP-A containing chromatin (5 EXP)
- GO:0000784 nuclear chromosome, telomeric region (213 EXP) -> GO:0000781 chromosome, telomeric region (103 EXP)
-  GO:1990707 nuclear subtelomeric heterochromatin (34 EXP) -> GO:0099115 chromosome, subtelomeric region (1 EXP)
- GO:0000780 condensed nuclear chromosome, centromeric region (70 EXP) -> GO:0000779 condensed chromosome, centromeric region (36 EXP)
- GO:0000942 condensed nuclear chromosome outer kinetochore  (13 EXP) -> GO:0000940 condensed chromosome outer kinetochore (21 EXP)
- GO:0000941 condensed nuclear chromosome inner kinetochore (11 EXP) -> GO:0000939 condensed chromosome inner kinetochore (e EXP) 
- GO:0000778 condensed nuclear chromosome kinetochore (136 EXP) ->   GO:0000777 condensed chromosome kinetochore (36 EXP)

                

@RLovering @colinlog Is this OK with you ? 
 @cmungall @ukemi Do you remember if this was discussed/proposed before ? @ValWood and I thought there was, but we cannot find the ticket/minutes. 

Thanks, Pascale

**Comment by krchristie** [comment]
> Hello,
> 
> Many 'x nuclear complex' terms correspond to complexes that are not always part of the nucleus.
> 
> This includes:
> 
>     * GO:0000788 nuclear nucleosome (21 EXP) ->  merge into GO:0000786 nucleosome
> 
>     * GO:0000787 cytoplasmic nucleosome (1 EXP) ->  merge into GO:0000786 nucleosome
> 
>     * GO:0000790 nuclear chromatin (876 EXP) -> GO:0000785 chromatin
> 
>     * GO:0005719 nuclear euchromatin  (67 EXP) ->  GO:0000791 euchromatin
> 
>     * GO:0005720 nuclear heterochromatin (83 EXP) >  GO:0000792 heterochromatin
> 
> 
> +others - Most complete list to follow.
> 
> @RLovering @colinlog Is this OK with you ?
> @cmungall @ukemi Do you remember if this was discussed/proposed before ? @ValWood and I thought there was, but we cannot find the ticket/minutes.
> 
> Thanks, Pascale

It might be helpful to also give the counts of annotations made to the non-nuclear terms.

**Comment by pgaudet** [comment]
Hi @krchristie 

I've updated the previous comment to add the counts of annotations made to the non-nuclear terms.

**Comment by pgaudet** [comment]
Hi, 

I am discussing this with @colinlog and @RLovering 

They agree on the merges. Moreover, for the issue of proteins retained on chromatin/nucleosome during the mitosis/meiosis, we should create a new term 'mitotic/meiotic chromosome'   - or resurrect GO:0005708 mitotic chromosome, modifying the definition to indicate that this is a chromosome present during the mitotic/meiotic phase. If this concept is needed, of course.

Thanks, Pascale

**Comment by pgaudet** [comment]
Will also merge 


 - [ ] GO:1902377 nuclear rDNA heterochromatin (13 EXP) -> GO:0033553 rDNA heterochromatin (23 EXP)
 - [ ]  GO:0031618 nuclear pericentric heterochromatin (68 EXP) -> GO:0005721 pericentric heterochromatin (36 EXP)
 - [ ]   GO:1904834 nuclear CENP-A containing chromatin (4 EXP) -> GO:0061638 CENP-A containing chromatin (5 EXP)
 - [ ]  GO:0000784 nuclear chromosome, telomeric region (213 EXP) -> GO:0000781 chromosome, telomeric region (103 EXP)
 - [ ]   GO:1990707 nuclear subtelomeric heterochromatin (34 EXP) -> GO:0099115 chromosome, subtelomeric region (1 EXP)
 - [ ]  GO:0000780 condensed nuclear chromosome, centromeric region (70 EXP) -> GO:0000779 condensed chromosome, centromeric region (36 EXP)
 - [ ]  GO:0000942 condensed nuclear chromosome outer kinetochore (13 EXP) -> GO:0000940 condensed chromosome outer kinetochore (21 EXP)
 - [ ]  GO:0000941 condensed nuclear chromosome inner kinetochore (11 EXP) -> GO:0000939 condensed chromosome inner kinetochore (e EXP)
 - [ ] GO:0000778 condensed nuclear chromosome kinetochore (136 EXP) -> GO:0000777 condensed chromosome kinetochore (36 EXP)


@ValWood  @RLovering @colinlog  Please let me know of that's not appropriate.

Thanks, Pascale

**Comment by ValWood** [comment]
It's a big change-  but we have been saying we would do it for a long time. It doesn't currently make sense  ontologically  (because   chromosomes in an organism undergoing open mitosis are not always nuclear). So we are encoding a single entity as two different entities  depending on the location. So the current situation is weird...

**Comment by colinlog** [comment]
Hi Val, can you, in GO, say that a chromosome made of 2 DNA stands that can measure several centimeters and harbour millions of histone octamers as well as more than thousand diferent proteins is a 'single entity'? I mean, GO is about molecules and this is not one molecule but a huge molecular *assembly*. I would rather to argue that the mitotic (and meiotic) chromosome is a **different** assembly than the interphase chromomosome, mainly due to its topology that results in an extreme degree of compaction, but also in terms of protein content, and in terms of the centromere that is officially a kinetochore at that point of the cell cycle.  Therefore, I would argue that yes, the mitotic (and even more so the meiotic) chromosome is a different 'entity' than the interphase - decompacted nuclear eukaryotic chromosome. It is not solely a matter of cellular location and (cell cycle) phase, it is molecular distinction.

**Comment by ValWood** [comment]
Hi Colin,
For sure, it has a different composition. But  generally  these terms would not be used for direct annotation anyway.
We use "chromosome" rarely, and if we do we can qualify with a "phase" extension.

For example
chromosome
  | hhp1 during meiosis I cell cycle phase
  | hhp2 during meiosis I cell cycle phase
  | mei2 during meiosis I cell cycle phase
  | pds5 during mitotic prometaphase, mitotic interphase

This is better for 2 reasons.
1. The  'meiotic' and 'mitotic' chromosomes you refer to do not have the same composition fro the entire cycle, so we can specify precisely when a particular gene product becomes a part_of a chromosome.

2. It would be  a large ontology burden to need to add a mitotic and meiotic version of each chromosome (and it would still not provide the specificity we get from using the  extensions which allow us to be very precise about the stage (otherwise  there would be an additional increase "interphase mitotic chromosome" etc).

**Comment by ValWood** [comment]
...so essentially this is a different axis of classification and  would need to be instantiated for everything

e.g. 
 interphase mitotic chromosome, telomeric region
interphase euchromatin
etc, etc

**Comment by pgaudet** [comment]
Ontology editors agree with the merge.

**Comment by colinlog** [comment]
Chromosomes they are, indeed.   I understand what you say and see sense in such 'sentences' / 'GO-CAM expressions' that explicitly qualify temporal phase and [cellular / tissue / anatomical / geographical] location qualifiers. This type of grammatical articulations bring 'GO-virtual-representations' much closer to 'Bio-reality'.  The merges are very welcome!  

And now, should GO then decide what qualifiers are implicit - unless otherwise stated - when chromosome or a descendant GO-term is used? 'Interphase' and 'nuclear', I would guess ;-)  Basically, officialising the concept of a ground-state / default set of qualifiers...

**Comment by ValWood** [comment]
re
>And now, should GO then decide what qualifiers are implicit - unless otherwise stated - when chromosome or a descendant GO-term is used? 'Interphase' and 'nuclear', I would guess ;-) Basically, officialising the concept of a ground-state / default set of qualifiers...

The phase terms  are routinely  used as annotation extensions for "phases" and "cell cycle stages"
as documented here.
http://wiki.geneontology.org/index.php/Annotation_Extension_Relation:happens_during
http://wiki.geneontology.org/index.php/Annotation_Extension_Relation:exists_during

But I always find these very difficult to locate on the GO wiki...
