### ISSUE TITLE
NTR: Pellicular membrane

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#20034]
Hi,
Can I request a new term for the pellicular membrane please? This term is required to annotate genes with cellular localisation data from the TrypTag project (http://tryptag.org/).

**Accession: GO:xxxxxx
Name: pellicular membrane
Ontology: cellular_component
Synonyms: pelliular plasma membrane, pellicle membrane
Definition: The portion of the plasma membrane surrounding the pellicle, a structure enclosing certain parasite cells such as certain apicomplexa and Euglenozoa.These membranes are associated with infrastructure of microtubules, microfilaments and other organelles.
Comment: This sub-domain of the plasma membrane excludes the ciliary and ciliary pocket membranes.
is_a: GO:0020039 ! pellicle
is_a: GO:0005886 ! plasma membrane
bounding_layer_of: GO:0020039 ! pellicle
never_in_taxon: NCBITaxon:33154 (Opisthokonta)
never_in_taxon: NCBITaxon:2 (Bacteria)
Source: PMID:6993644, PMID:7175771, PMID:18095354, PMID:30550896**

Thanks & best wishes,
Achchuthan

**Comment by pgaudet** [comment]
@Achchuthan Are there taxon restrictions we should add ?

**Comment by Achchuthan** [comment]
Hi @pgaudet & @krchristie,

The taxon constraint for this term is the same as GO:0020039 (pellicle). So, I added the following "never_in_taxon" constrains above - never_in_taxon: NCBITaxon:33154 (Opisthokonta)
never_in_taxon: NCBITaxon:2 (Bacteria)

Thanks,
Achchuthan

**Comment by krchristie** [comment]
Hi @Achchuthan 

Thanks again for such a detailed stanza. It makes this ticket very easy to do.

I've made a few tweaks of parentage
- Based on the comment `This sub-domain of the plasma membrane excludes the ciliary and ciliary pocket membranes.`, this new term can not be **is_a GO:0005886 ! plasma membrane** because it is a part_of a plasma membrane rather than a type of plasma membrane, so I've used `plasma membrane region` instead. This is consistent with a previous decision in GO that the ciliary membrane is part_of the plasma membrane, so here the ciliary membrane and the pellicular membrane together comprise the plasma membrane.
- Likewise, the new term can not be **is_a: GO:0020039 ! pellicle** because it is a portion of the pellicle. As you have also indicated that it is the **bounding_layer_of: GO:0020039 ! pellicle**, I have used this `bounding layer of` relationship in a logical definition which defines it as part of the `pellicle`.

Here's the term I'm putting in. Let me know if you see anything I missed.

[Term]
id: GO:0120267
name: pellicular membrane
namespace: cellular_component
def: "The portion of the plasma membrane surrounding the pellicle, a structure enclosing some parasite cells such as certain apicomplexa and Euglenozoa. These membranes are associated with an infrastructure of microtubules, microfilaments, and other organelles." [GOC:ach, GOC:krc, PMID:18095354, PMID:30550896, PMID:6993644, PMID:7175771]
comment: This sub-domain of the plasma membrane excludes the ciliary and ciliary pocket membranes.
synonym: "pellicle membrane" EXACT []
synonym: "pelliular plasma membrane" EXACT []
is_a: GO:0098590 ! plasma membrane region
intersection_of: GO:0016020 ! membrane
intersection_of: bounding_layer_of GO:0020039 ! pellicle
created_by: krc
creation_date: 2020-09-29T21:08:28Z

Thanks, 

Karen

**Comment by Achchuthan** [comment]
Hi @krchristie,
Thank you very much for providing this term and also for making the required changes to the relationships.

I have actually made a typo in the synonym:
It now reads as "synonym: "pelliular plasma membrane" EXACT []". It should have been "synonym: "pelli**c**ular plasma membrane" EXACT []"

Could you please be able to update this please?

Sorry for the error.

Thanks & best wishes,
Achchuthan

**Comment by krchristie** [comment]
Thanks for catching that. I had noticed that typo, but forgotten it by the time I copy/pasted it into the new term.
