### ISSUE TITLE
please remove "signal transduction by protein phosphorylation" as a descendant of protein phosphorylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20071]
This term is a descendant of protein phosphorylation, which is incorrect, the signal transduction is a broader process than "phosphorylation".

This term 
"signal transduction by protein phosphorylation"
has as a descendant
GO:0000165    MAPK cascade

which results in many inferences to "protein phosphorylation" 

Ideally the term would just be removed (merged into signal transduction) ?

**Comment by RLovering** [comment]
I assume you mean to remove  GO:0023014 signal transduction by protein phosphorylation.

There are currently 1,210,104 annotations associated directly with this term. Although 1,209,272 are based on GOC interontology links to the MF child term GO:0000155 phosphorelay sensor kinase activity. If you remove the Ensembl and PAINT annotations then there are less than 100 annotations only:

AgBase | 0.00 | 55
-- | -- | --
EcoCyc | 0.00 | 32
EnsemblProtists | 0.00 | 7
RGD | 0.00 | 5
MGI | 0.00 | 4
UniProt | 0.00 | 4
CACAO | 0.00 | 3

The term GO:0023014 signal transduction by protein phosphorylation has 2 parents:
 GO:0006468 protein phosphorylation
 GO:0007165 signal transduction

If the term was merged into a parent I think merging into GO:0007165 signal transduction would be best, as there maybe proteins annotated to protein phosphorylation that should actually be annotated to regulation of protein phosphorylation. Where as the signal transduction aspect is less likely to be a wrong annotation.

However, what would you do with the child terms?
 GO:0023016 signal transduction by trans-phosphorylation (>100 annotations)
 GO:0023015 signal transduction by cis-phosphorylation (0 annotations)
 GO:0000155 phosphorelay sensor kinase activity (>1,000,000 annotations) this will be fine with the GO:0007165 term removed due to alternative relations to phosphorylation.
 GO:0000165 MAPK cascade  (>1,000,000 annotations)

Ruth

**Comment by ValWood** [comment]
GO:0023016 signal transduction by trans-phosphorylation (>100 annotations) -> merge into signal transduction

GO:0000165 MAPK cascade (>1,000,000 annotations) keep (it will still have a signalling parent, it represents a signalling module).

**Comment by pgaudet** [comment]
- [x] GO:0000165 MAPK cascade -> remove 'signal transduction by protein phosphorylation', keep 'intracellular signal transduction'
- [ ] GO:0023016 signal transduction by trans-phosphorylation (>100 annotations) -> merge into GO:0007165 signal transduction
- [ ] GO:0023015 signal transduction by cis-phosphorylation (0 annotations) -> merge into GO:0007165 signal transduction
- [x] GO:0000155 phosphorelay sensor kinase activity, remove 'part of' some 'signal transduction by protein phosphorylation', keep 'part of' some 'phosphorelay signal transduction system'

**Comment by pgaudet** [comment]
I will also merge     GO:0023045     signal transduction by conformational transition > 0 annotations
