### ISSUE TITLE
cellular response to L-serine

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#20098]
new term request: cellular response to L-serine
parent term: cellular response to L-serine
PMID: 11090983
definition: Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a L-serine stimulus.

**Comment by pgaudet** [comment]
@slaulederkind 
The 'response to' terms are problematic, and it would be nice to find alternatives to express what happens to cells exposed to various stimuli. 

Here it looks like bcl-w is measured as an apoptotic/cell death marker. I wonder if you could use ' GO:0097191 extrinsic apoptotic signaling pathway' with 'has input' L-serine ? 

@vanaukenk would that be valid ? 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet @slaulederkind 

'has input' is certainly valid wrt allowed relations, but I'm not sure it's really how we'd want to annotate the paper for GO.

Stan, do you think the experiments described here refer to a normal, physiological process or something that happens under pathological conditions?

I'm looking at the final paragraph of the paper:

"The concentrations of l-Ser and Gly in the extracellular milieu of the normal mature brain may be ∼5 μM [1], [4] that are too low to induce the upregulation of bcl-w expression. Yet, both amino acids appear to increase in the extracellular space of the pathological brain [9], presumably because large amounts of l-Ser and Gly are supplied from blood plasma through the damaged blood brain barrier or from astrocytes that are stimulated by glutamate [5]. Indeed, recent reports demonstrated that Bcl-w is upregulated in the ischemic brain [6], [16]. This finding is likely to be related to the increased concentrations of l-Ser and Gly under the pathological condition."

If you did make an annotation to bcl-w from this paper, it seems like 'negative regulation of apoptotic signaling pathway' (GO:2001234) might be more appropriate (maybe you could drill deeper to an extrinsic or intrinsic pathway child term, but I couldn't tell for sure from the experiments).  

I honestly think a GO-CAM would describe this biology better.

**Comment by pgaudet** [comment]
Thanks @vanaukenk 
@slaulederkind Is it OK for you to annotate 'negative regulation of apoptotic signaling pathway' or 'negative regulation of extrinsic apoptotic signaling pathway' to indicate that the inducer is extracellular? 

If that works, we'll close this ticket. 

Thanks, Pascale

**Comment by slaulederkind** [comment]
Close it.  Thanks.

**Comment by pgaudet** [comment]
Thanks @slaulederkind
