### ISSUE TITLE
glyoxylate reductase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20216]
should there be a relationship between:

GO:0030267 | glyoxylate reductase (NADP) activity 
Catalysis of the reaction: glycolate + NADP+ = glyoxylate + NADPH + H+.
RHEA | 10992

be a descendant of 
GO:0047964 | glyoxylate reductase activity?
Catalysis of the reaction: glycolate + NAD+ = glyoxylate + NADH.
RHEA | 18229
common parent?

it's all a bit odd.
glyoxylate reductase activity has exact synonym glyoxylate reductase activity

**Comment by ValWood** [comment]
confusing
https://en.wikipedia.org/wiki/Glyoxylate_reductase

**Comment by ValWood** [comment]
I opened this ticket becasue pombe and cerevisiae used

GO:0047964 | glyoxylate reductase activity
but PAINT inferences are to
GO:0030267 | glyoxylate reductase (NADP) activity

**Comment by hdrabkin** [comment]
Note the different RHEAs because one activity uses NADP and the other uses NAD. They are different reactions.  I should change the name of GO:0047964 | glyoxylate reductase activity to glyoxylate reductase (NAD+ ) activity.
The two reactions also have a different ECs, which map to their respective RHEA. 
EC:1.1.1.79 vs EC:1.1.1.26
Both children of EC:1.1.1 , oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

The name comes from the EC:1.1.1.26, which since it only uses NAD should be named to distinguish it from the EC:1.1.1.79

**Comment by hdrabkin** [comment]
done.

**Comment by ValWood** [comment]
Could you create a common parent? I think that would help curators as they would see immediately there are 2 terms and make an effort to ensure they are using the correct one. Currently  the annotations are to either term arbitrarily. I still need to check the annotations.

**Comment by pgaudet** [comment]
I think 
GO:0047964 | glyoxylate reductase activity should be renamed glyoxylate reductase activity (NAD(+)). 

and a comment parent would make sense.

**Comment by hdrabkin** [comment]
Used "NAD+" because that's the CHEBI name (CHEBI:15846) and NADP+ (CHEBI:18009); the CHEBI asci names have 
NAD(+) AND NADP(+).

**Comment by hdrabkin** [comment]
+id: GO:0106345
+name: glyoxylate reductase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: glycolate + NAD(P)+ = glyoxylate + NAD(P)H." [GOC:curators, PMID:3548703]
+is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
+created_by: hjd
+creation_date: 2020-12-08T14:14:31Z

GO:0047964 and GO:0030267  are now children of the new term
