### ISSUE TITLE
flavin-linked sulfhydryl oxidase activity vs.  protein disulfide oxidoreductase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20219]
Are these the same?

GO:0016971
flavin-linked sulfhydryl oxidase activity
Catalysis of the formation of disulfide bridges.

GO:0015035 | protein disulfide oxidoreductase activity
Catalysis of the reaction: a protein with reduced sulfide groups = a protein with oxidized disulfide bonds.

They sound the same but they are in different parts of the graph?

**Comment by ValWood** [comment]
Any thought on this @hdrabkin ?

**Comment by hdrabkin** [comment]
@deustp01 , what do you think?

**Comment by hdrabkin** [comment]
GO:0016971 has no xrefs; but UniProt uses the PMID and has EC 1.8.3.2  and RHEA:17357
So if I put these for this entry, the def will change 
Catalysis of the formation of disulfide bridges. to O2 + 2 R'C(R)SH = H2O2 + R'C(R)S-S(R)CR'.

**Comment by hdrabkin** [comment]
Will email RHEA (@amorgat )

**Comment by amorgat** [comment]
I hand over to Kristian(@kaxelsen)  because I'm a little overwhelmed by work

**Comment by deustp01** [comment]
> Are these the same?
> 
> GO:0016971
> flavin-linked sulfhydryl oxidase activity
> Catalysis of the formation of disulfide bridges.
> 
> GO:0015035 | protein disulfide oxidoreductase activity
> Catalysis of the reaction: a protein with reduced sulfide groups = a protein with oxidized disulfide bonds.

GO:0015035 protein disulfide oxidoreductase activity has a child,  GO:0097573 glutathione oxidoreductase activity whose description includes the comment
`Note that this activity is different from GO:0015038 'glutathione disulfide oxidoreductase activity'. See PMID:18992757: "Grxs [glutaredoxins] can also reduce mixed disulfides between proteins or low molecular weight thiols and GSH in reactions that require only their N-terminal active- site cysteine. It is important to note that the reduction of glutathionylated substrates through the monothiol mechanism seems to be the major activity of Grxs; all dithiol Grxs described so far catalyze these reactions, but not all dithiol Grxs catalyze the reduction of protein disulfides by the dithiol mechanism".`

I don't know the relevant chemistry, so I'm only the messenger here passing on the comment.

**Comment by ValWood** [comment]
The plot thickens !
I can't remember what alerted me to this but I presume it was coannotation. So now we have another term in the mix.

<img width="420" alt="Screenshot 2020-11-05 at 21 12 20" src="https://user-images.githubusercontent.com/7359272/98296974-a3a06a80-1fab-11eb-8488-bd9fee56ab12.png">

**Comment by kaxelsen** [comment]
From the names of the GO terms I could not see whether the two terms are identical, so I looked at the definitions. 
GO:0016971 cites PMID:10899311. This article is about Erv1p from Saccharomyces cerevisiae which is annotated as EC 1.8.3.2 (RHEA:17357; MetaCyc: THIOL-OXIDASE-RXN).  So this term describes a specific enzyme. 

GO:0015035 cites  MetaCyc:DISULFOXRED-RXN. This MetaCyc reaction is linked to E. coli DnaJ but seems to have a much broader scope than GO:0016971. 

This is also reflected in the usage in UniProtKB/Swiss-Prot where the term only is used for entries annotated as EC 1.8.3.2 (26 entries) whereas GO:0015035 is used in 679 entries, including the 26 entries annotated as EC 1.8.3.2. Maybe GO:0015035 is badly defined, because the synonym "heme lyase disulfide oxidoreductase activity" can be found in only 29 entries, and these entries do not include DnaJ. There is not much overlap between the synonym and the GO term in UniProtKB/Swiss-Prot as a search for both only finds 6 entries. 

So my conclusion is that according to usage GO:0016971 is a child of GO:0015035, they are definitely not identical. A question is whether the definition of GO:0015035 is precise enough for its intended usage.

**Comment by ValWood** [comment]
@kaxelsen  thanks!

**Comment by hdrabkin** [comment]
So I can assert the relationship between GO:0016971 and GO:0015035 and close?

**Comment by ValWood** [comment]
@kaxelsen  does @hdrabkin  solution work?

**Comment by kaxelsen** [comment]
I'm afraid my knowledge of English is too limited to understand what "assert" means in this context. And what is the relationship between GO:0016971 and GO:0015035?

**Comment by pgaudet** [comment]
@kaxelsen This is not English, is GO-jargon... 

Harold mean, adding manually the statement (assertion) that GO:0016971 is_a GO:0015035 (this is what you suggest above: https://github.com/geneontology/go-ontology/issues/20219#issuecomment-722666080)

(It also seems like definitions could be improved)

**Comment by kaxelsen** [comment]
What I did in my comment was to try to answer the question of whether the two terms were identical and to analyse the current usage of them. What Harold suggests is **a** solution to my conclusions, but I don't know if that solution is what you prefer. There might be other solutions that I have not thought of.

**Comment by pgaudet** [comment]
Sure :) thanks for your help.

**Comment by pgaudet** [comment]
Just wondering - we already have a GO term for EC 1.8.3.2 ; RHEA:17357, GO:0016972 thiol oxidase activity
Should we not merge the specific gene product into that term 'GO:0016971 flavin-linked sulfhydryl oxidase activity'? since that one has no EC/Rhea?

**Comment by pgaudet** [comment]
Is GO:0015037 peptide disulfide oxidoreductase activity different  from GO:0015035 | protein disulfide oxidoreductase activity? 
Annotated proteins belong to these families: 

glutathione reductase 
protein disulfide isomerase 
glutaredoxin-1


etc 

Thanks, Pascale

**Comment by pgaudet** [comment]
especially that other places in the ontology we use 'peptidyl' to refer to a protein, such as GO:0018212 peptidyl-tyrosine modification

**Comment by deustp01** [comment]
My textbook recollection is that enzymes whose physiological substrate is a protein can also typically act on much smaller peptides and even on other small molecules, e.g., proteases that hydrolyze ester bonds. If there are enzymes that act only on peptides and not larger proteins or vice versa, that could be a reason to preserve the distinction. Otherwise, @hdrabkin 's objection to adding differentia (like overall substrate size) onto the good ones from enzyme mechanism looks exactly right.

**Comment by deustp01** [comment]
> we use 'peptidyl' to refer to a protein,

Exactly - the enzyme's behavior is determined by the immediate neighborhood of the feature it is acting on.

**Comment by pgaudet** [comment]
Thanks, I will merge

**Comment by pgaudet** [comment]
Actually 1.8.1.8      Protein-disulfide reductase corresponds to the version that uses NAD(P) as acceptor. 
We should probably keep one term also a term with no specified acceptor.

**Comment by hdrabkin** [comment]
That has 2 RHEAS : make 2 children to the 1.8.18 term

  | RHEA:18749 | [protein]-dithiol +   NAD+ =   [protein]-disulfide +   H+ +   NADH | EC:1.8.1.8 Protein-disulfide reductase | 9,594 protein(s) (UniProtKB)
-- | -- | -- | -- | --
  | RHEA:18753 | [protein]-dithiol +   NADP+ =   [protein]-disulfide +   H+ +   NADPH | EC:1.8.1.8 Protein-disulfide reductase | 9,594 protein(s) (UniProtKB)

**Comment by pgaudet** [comment]
Well that's another case where it's not sorted; same number of annotations. Let's revisit this at some later point. 

@kaxelsen @amorgat

**Comment by pgaudet** [comment]
I made some improvements, but this branch still probably needs some work..
