### ISSUE TITLE
Review of term definition  GO=GO:0072546; ER membrane protein complex

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#20234]
Hi,
there are growing evidences that the EMC /ER membrane protein complex is involved in the insertion of proteins in the membrane of the ER: PubMed=29242231, PubMed=32459176 . Could you please review the definition which does not fit these new data. Could it be that it describes another complex with the same name but looking at the description of SGD (https://www.yeastgenome.org/locus/S000000550#go), it does not seem to be the case.

From Guna et al. "The substrates that fail insertion without EMC probably contribute to many of EMC’s reported phenotypes, such as ER stress (17), aberrant membrane protein trafficking or degradation (18–21), altered lipid homeostasis (22), or altered
viral replication (27)."

Thanks for your help.
Best, Lionel

**Comment by ValWood** [comment]
@pgaudet, this is the complex we were talking about earlier!

@lbreuza do you think it would be helpful to call this  "EMC complex" too?   Otherwise people may think it is just a generic grouping term.

I think the current def comes from

"Together, our findings support that the EMC tethers ER to mitochondria, which is required for phospholipid synthesis and cell growth."
http://europepmc.org/article/MED/25313861
(probably me)

I think this was me, but seems to be very out of date.

This is a nice Cell paper too
https://pubmed.ncbi.nlm.nih.gov/30415835/

also ERMES complex is THE mitochondrial_ER membrane tethering complex  these days :) The earlier work could be an indirect phenotype as a consequence of failure to insert ERMES correctly.

I have some  annotation corrections to do!

**Comment by lbreuza** [comment]
> 
> 
> @pgaudet, this is the complex we were talking about earlier!
> 
> @lbreuza do you think it would be helpful to call this "EMC complex" too? Otherwise people may think it is just a generic grouping term.
@ValWood yes indeed it sounds as you said but EMC is a synonym so that could be fine. My main problem is with the definition that is too specific and probably 'wrong' wrt to new data.

> 
> I think the current def comes from
> 
> "Together, our findings support that the EMC tethers ER to mitochondria, which is required for phospholipid synthesis and cell growth."
> http://europepmc.org/article/MED/25313861
> (probably me)
> 
> I think this was me, but seems to be very out of date.
> 
> This is a nice Cell paper too
> https://pubmed.ncbi.nlm.nih.gov/30415835/
@ValWood yes this one is also in my update!
> 
> also ERMES complex is THE mitochondrial_ER membrane tethering complex these days :) The earlier work could be an indirect phenotype as a consequence of failure to insert ERMES correctly.
> 
> I have some annotation corrections to do!

**Comment by pgaudet** [comment]
I changed the definition and the term label. 

I made the synonyms "endoplasmic reticulum membrane protein complex" and "ER membrane protein complex" BROAD because they do sound quite general. 

Thanks, Pascale
