### ISSUE TITLE
MF in BP ontology

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20268]
GO:0052054
negative regulation by symbiont of host peptidase activity

Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of host protease activity, the catalysis of the hydrolysis of peptide bonds in a protein. The host is defined as the larger of the organisms involved in a symbiotic interaction.

this should be GO:0004866  endopeptidase inhibitor activity

has one annotation
https://www.uniprot.org/uniprot/Q6PQH2
(this  IDA annotation could just be moved to the appropriate function term, currently provided by a KW mapping)

**Comment by ValWood** [comment]
from comment
Secreted effector that interacts with and inhibits the pathogenesis-related P69B subtilisin-like serine protease of host tomato (PubMed:15096512). Inhibition of host proteases by a pathogen extracellular protease inhibitor forms a specific type of defense-counterdefense mechanism between plants and microbial pathogens (PubMed:15096512).1 Publication

the process should be
GO:0140415    effector-mediated modulation of host defenses by symbiont

**Comment by pgaudet** [comment]
This applies to the whole branch -     GO:0052148  modulation by symbiont of host catalytic activity or even  GO:0052055
   modulation by symbiont of host molecular function

Maybe we can look at this together on a future call ?

**Comment by ValWood** [comment]
Yes.
At PHI-base we have been annotating these as:

x inhibitor activity involved_in effector-mediated blah (usually immune but sometimes other processes)

**Comment by ValWood** [comment]
Ah I see that is what I said above...

**Comment by pgaudet** [comment]
We need to review the entire branch, GO:0052055 modulation by symbiont of host molecular function
this, but that involves reviewing the virus keywords

@pmasson55 - can you help ?

**Comment by pgaudet** [comment]
Discussing with @pmasson55 

The Keywords have a hierarchy, for example like this part: 
* Inhibition of host interferon signaling pathway by virus (KW-1114) 
* * mapped to GO suppression by virus of host type I interferon-mediated signaling pathway [ GO:0039502 ]
* children include: 
* * Inhibition of host STAT1 by virus (KW-1105)  -> mapped to 'suppression by virus of host STAT1 activity [ GO:0039563 ]'
* * Inhibition of host STAT2 by virus (KW-1106) -> mapped to 'suppression by virus of host STAT2 activity [ GO:0039564 ]'
* * Inhibition of host TYK2 by virus
* * Modulation of host PP1 activity by virus
etc

* Note that mappings to parent terms are applied to each entry, so that an entry with KW-1105 will get both GO:0039563 and GO:0039502
* We *could* change the mapping for the 'inhibitors of activity', like KW-1105, to 'transcription factor inhibitor activity', however if we do that we loose which transcription factor is inhibited when we do mappings (we can capture those are extensions and inputs in P2GO and GO-CAMs, but any propagations loose it). 
* We could nevertheless move the terms to MF, for example 'STAT1 transcription factor inhibitor activity' - however our guidelines state that we don't want to capture gene products in the term. 

@cmungall @ValWood @thomaspd 
thoughts ? 

Thanks, Pascale

**Comment by ValWood** [comment]
@pgaudet  I think this has been done by another route?

**Comment by pgaudet** [comment]
Right ! Closed in #21740

Thanks
