### ISSUE TITLE
Change defintion transcription coregulator activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20464]
Per @RLovering 's suggestion - to accommodate Mediator subunits, that (presumably) don't all bind to dbTFs. This is likely the case for other coTFs. 

New proposed def: 

A transcription regulator activity that regulates the activity of a DNA-bound DNA-binding transcription factor, either on its own or as part of a complex. Coregulators often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators.

@colinlog 
Thanks, Pascale

**Comment by colinlog** [comment]
Please keep in mind that eukaryotic genes are intrinsically repressed by
nucleosome formation. Mediator's function lies at the border between GTF
and co-regulator. I would find 'mediates' much better than 'regulates' if
you wish to better accommodate the mediator complex in the dbTF coregulator
definition. Can we please look through the Relations Ontology to find an
alternative to 'regulates' if 'mediates' is not appropriate? Otherwise,
this latest change in the definition brings us back to a very ambiguous
definition that will very probably hamper proper annotations to this term.
I find it confusing to now explicitly demand that the 'dbTF coregulator' be
a 'dbTF regulator', whilst it is primarily a causally linked mechanistic
effector, a co-factor for the dbTF even though often the acetyl
transferases also feedback on the dbTF to amplify its activity and the
deacetylases feedback to repress its activity. The concept is that the dbTF
finds the genomic address and then the coregulator performs a 'downstream'
molecular function that regulates transcription at that spot on the genome
. Binding to the dbTF is not a prerequisite, but performing its
transcription regulating function as a consequence of a *preceding* DNA
binding event by a dbTF is. As discussed during the Berkeley jamboree,
there are also epigenetic signal transduction cascades that take place at
regulatory DNA elements (including self-perpetuating feedback loops) and
these often involve covalent histone modifications that are sometimes
maintained even in the absence of the initially instigating signal provided
by the dbTF DNA binding event. Nevertheless, without the continued presence
of dbTFs at a eukaryotic promoter it will not be the source of full length
RNA transcripts and it will not therefore need to be repressed more than
what nucleosome formation achieves.

Bottom line: I had thought we would refrain just now from calling into life
the coregulator's coregulators and would bag all the activities that are
recruited by dbTFs as dbTF coregulators. This logic is based on the concept
that while the co-regulators may reinforce or enable the activity of a
previously marked genomic address (a cis-regulatory transcrition control
element like an enhancer or a promoter), it is only the dbTFs that can
'discover' a genomic adress and mark it for transcription
activity/inactivity at the hand of enzymtic and other protein complexes
that it reruits there *and* the other molecualr activities that these
coregulators recruit or exclude. At some point a distinction must indeed be
made between generic chromatin structural proteins (nucleosomes) and those
that are coregulators (nucleosome remodelers) as well as the 'epigentic
processes that function autonomously, but this will not be made easier by
stipulating that coregulators regulate the dbTFs activity. What dbTF
coregulators do is to regulate events that lead to RNA polymerase
(in)activity *after* the dbTF has bound the DNA. That explicit
spatio-temporally ordered causality relationship which is one of subject
and ruler, of hierarchy in the decision making process that makes the DNA
binding site the code and the dbTF its reader and the coregulator the
helper of the code-reading dbTF has been wiped from the newly proposed
version of the coregulator definition, I think.

**Comment by pgaudet** [comment]
New proposal with @colinlog 

A transcription regulator activity that modulates the transcription of specific gene sets via binding to a DNA-bound DNA-binding transcription factor, either on its own or as part of a complex. A transcription regulator activity that modulates the transcription of specific gene sets via selective and non-covalent binding to a DNA-bound DNA-binding transcription factor. 
Coregulators often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators.

Will confirm with @RLovering

**Comment by pgaudet** [comment]
New coactivator def: GO:0003713

A transcription coregulator activity that activates or increases the transcription of specific gene sets via binding to a DNA-bound DNA-binding transcription factor, either on its own or as part of a complex. Coactivators often act by altering chromatin structure and modifications. For example, one class of transcription coactivators modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators. A fourth class of coactivator activity is the bridging of a DNA-binding transcription factor to the general (basal) transcription machinery. The Mediator complex, which bridges sequence-specific DNA binding transcription factors and RNA polymerase, is also a transcription coactivator.

New corepressor def: GO:0003714
A transcription coregulator activity that represses or decreases the transcription of specific gene sets via binding to a DNA-bound DNA-binding transcription factor, either on its own or as part of a complex. Corepressors often act by altering chromatin structure and modifications. For example, one class of transcription corepressors modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators.

New 'nuclear receptor corepressor activity' def GO:0140536
A transcription corepressor activity that represses or decreases the transcription of specific gene sets via binding to a DNA-bound nuclear receptor, either on its own or as part of a complex. Nuclear receptor corepressors often act by altering chromatin structure and modifications. For example, one class of transcription nuclear receptor corepressors modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators.

New 'nuclear receptor coactivator activity' def GO:0030374
A transcription coactivator activity that activates or increases the transcription of specific gene sets via binding to a DNA-bound nuclear receptor,  either on its own or as part of a complex. Coactivators often act by altering chromatin structure and modifications. For example, one class of transcription coregulators modifies chromatin structure through covalent modification of histones. A second class remodels the conformation of chromatin in an ATP-dependent fashion. A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators. A fourth class of coactivator activity is the bridging of a DNA-binding transcription factor to the general (basal) transcription machinery. The Mediator complex, which bridges sequence-specific DNA binding transcription factors and RNA polymerase, is also a transcription coactivator.

**Comment by pgaudet** [comment]
Another minor change from @colinlog 

Replace 'A third class modulates interactions of DNA-binding transcription factor with other transcription coregulators.' 
by A third class modulates interactions of **DNA-bound** DNA-binding transcription factor with other transcription coregulators.

Thanks, Pascale
