### ISSUE TITLE
NTR: Sleep homeostasis terms

### ISSUE THREAD

**Issue by cerivs** [geneontology/go-ontology#20499]
**Please describe your question, idea, or concern.**
Curating a zebrafish paper PMID:31537465 where they are talking about sleep homeostasis distinct from circadian cycle.  I can't find any terms in GO that map to that concept.  Am I missing them?

They of course say it is an emerging field of study.   They cite fly papers  https://flybase.org/reports/FBrf0232501 and https://pubmed.ncbi.nlm.nih.gov/29208223/ and mouse https://pubmed.ncbi.nlm.nih.gov/30297727/; https://pubmed.ncbi.nlm.nih.gov/27806374/.    Are there any plans to create terms for sleep homeostasis, or  already a group working on those terms?

**Comment by krchristie** [comment]
Interesting, I don't see anything that matches what you're looking for either. 

Here's a quote from the paper you're curating:

PMID:31537465
> Sleep is regulated by two interacting processes: a circadian, 24 h process that sets sleep relative to the phase of the day and night cycle and a homeostatic process that increases sleep drive as a function of prior wakefulness (Borbély, 1982). While the molecular and neuronal underpinnings of circadian rhythms are fairly well understood, the mechanisms that measure and actuate homeostatic sleep pressure are only starting to be elucidated in flies (Donlea, 2017, Liu et al., 2016) and in vertebrates (Funato et al., 2016).

https://en.wikipedia.org/wiki/Circadian_rhythm
> A circadian rhythm is a natural, internal process that regulates the sleep-wake cycle and repeats on each rotation of the Earth roughly every 24 hours.[1] It can refer to any biological process that displays an endogenous, entrainable oscillation of about 24 hours. These 24-hour rhythms are driven by a circadian clock, and they have been widely observed in plants, animals, fungi, and cyanobacteria.[2]

> Processes with 24-hour oscillations are more generally called diurnal rhythms; strictly speaking, they should not be called circadian rhythms unless their endogenous nature is confirmed.[3] 

https://en.wikipedia.org/wiki/Diurnal_cycle
> A diurnal cycle is any pattern that recurs every 24 hours as a result of one full rotation of the Earth[1] around its own axis. 
> Diurnal cycles of environmental conditions (light or temperature) can result in similar cycles in dependent biological processes, such as photosynthesis in plants,[2] or clinical depression in humans.[3] Plant responses to environmental cycles may even induce indirect cycles in rhizosphere microbial activities, including nitrogen fixation.[4]


It sounds to me like our regular daily sleep cycle is affected by two different regulatory process. I'm thinking about whether this idea might work. 
- Change the name of `circadian sleep/wake cycle` to `diurnal sleep/wake cycle`. 
- Change terms like `regulation of circadian sleep/wake cycle` to `circadian regulation of diurnal sleep/wake cycle`
- Add terms for `homeostatic regulation of diurnal sleep/wake cycle`

It also occurs to me that it might be better to keep the current terms like `regulation of circadian sleep/wake cycle` as general terms that encompass **any** type of regulation of the diurnal sleep/wake cycle, and then create two types of regulation terms underneath for **circadian regulation** and **homeostatic regulation**. Probably worth taking a look at current annotations to see if all the current annotations to regulation terms are for circadian regulation.

**Comment by pgaudet** [comment]
Hi @krchristie 

I find a slightly different definition for diurnal: 
https://www.healthline.com/health/biological-rhythms
* **circadian rhythms:** the 24-hour cycle that includes physiological and behavioral rhythms like sleeping
* **diurnal rhythms:** the circadian rhythm synced with day and night. Diurnal animals sleep during the day, noctural at night (https://en.wikipedia.org/wiki/Sleep_in_non-human_animals). It looks like sleep always has some circadian basis (animals have some sleep cycle each day)

so I wonder if we could simplify your proposal further to: 

- Change the name of `circadian sleep/wake cycle` to `sleep/wake cycle` (or not; that should remain a circadian cycle)
- Terms like `regulation of circadian sleep/wake cycle` -> do not change
- Add terms for `homeostatic regulation ~of diurnal~ sleep/wake cycle` 


What do you think ?

**Comment by mah11** [comment]
tangential, but

> Diurnal animals sleep during the day, noctural at night

this is backwards

**Comment by pgaudet** [comment]
Right - thanks @mah11 !

**Comment by krchristie** [comment]
> Hi @krchristie
> 
> I find a slightly different definition for diurnal:
> https://www.healthline.com/health/biological-rhythms
> 
* **circadian rhythms:** the 24-hour cycle that includes physiological and behavioral rhythms like sleeping
* **diurnal rhythms:** the circadian rhythm synced with day and night. Diurnal animals sleep during the day, noctural at night (https://en.wikipedia.org/wiki/Sleep_in_non-human_animals). It looks like sleep always has some circadian basis (animals have some sleep cycle each day)

Yes, I am aware of that use of diurnal as well, but wanted to come up with a word other than `circadian` to describe the sleep cycle. I think that use of the word `daily` would be better than `diurnal` to describe the sleep/wake cycle since `diurnal` can be confusing between meaning a daily cycle or meaning animals that are wakeful in the daytime.

 
> 
> so I wonder if we could simplify your proposal further to:
* Change the name of `circadian sleep/wake cycle` to `sleep/wake cycle` (or not; that should remain a circadian cycle)
=> I think that the name should change because I think that the circadian part is a regulation cycle for a process that might not always be circadian. If sleep homeostasis drives you to take an afternoon nap that you don't normally take, is that circadian sleep? I'm still thinking through whether I have a preference between `daily sleep/wake cycle` or just `sleep/wake cycle`. I think there are some inconsistencies in the way we are doing circadian terms, but I'll put that in a different ticket since it is broader than this request.
* Terms like `regulation of circadian sleep/wake cycle` -> if we change the name of the term `circadian sleep/wake cycle`, then we need to change the name of the regulation term to match. I'd like to avoid having a term called `circadian regulation of circadian sleep/wake cycle`
* Add terms for `homeostatic regulation ~of diurnal~ sleep/wake cycle`

**Comment by raymond91125** [comment]
How about a new term "sleep homeostasis" IS_A "homeostatic process"
Definition: A homeostatic process that enables organisms to compensate for the loss of sleep or surplus sleep.
Reference: http://www.scholarpedia.org/article/Sleep_homeostasis

**Comment by raymond91125** [comment]
another ref PMID:19250170

**Comment by pgaudet** [comment]
Thanks @raymond91125 

Maybe this can be made even more general? See PMID:30509635

Definition: A homeostatic process in which the drive for sleep increases sleep propensity with prolonged wakefulness?  (it seems 'propensity' better describes the phenomenon than 'compensation' which seems a specific case. ) 

I would not cite http://www.scholarpedia.org/article/Sleep_homeostasis as sometimes these sites disappear, there seem to be enough references in pubmed. 


Thanks, Pascale

**Comment by pgaudet** [comment]
The parent should be 'GO:0048871 multicellular organismal homeostasis'

**Comment by raymond91125** [comment]
Thanks.
