### ISSUE TITLE
missing parent for atrioventricular canal morphogenesis

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#20493]
Hi 
please add the missing parent for GO:1905222 atrioventricular canal morphogenesis
This should be a part_of child of GO:0036302 atrioventricular canal development
Thanks
Ruth
@ckyli

**Comment by pgaudet** [comment]
Fixed LD of the parent 'anatomical structure morphogenesis' 

'anatomical structure morphogenesis'
 and ('results in morphogenesis of' some 'anatomical structure')- but that doesn't help because 
'embryonic structure' is_a  'developing anatomical structure'
but 'developing anatomical structure' is not an 'anatomical structure' - @cmungall I suppose this is intended ? 

Will add the relation @RLovering requested as a direct subclass.

**Comment by cmungall** [comment]
@pgaudet - I think you have identified an issue in uberon - want to make an uberon ticket?

I don't think it's a blocker here

**Comment by pgaudet** [comment]
Done https://github.com/obophenotype/uberon/issues/1691
