### ISSUE TITLE
GO:0045182 translation regulator activity parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20607]
GO:0090079    translation regulator activity, nucleic acid binding
has a direct parent to molecular function, but
GO:0045182 translation regulator activity

doesn't.

I think this is affecting our display (means that these appear as binding terms rather than MF terms)

<img width="487" alt="Screenshot 2020-12-16 at 17 14 51" src="https://user-images.githubusercontent.com/7359272/102382342-42b07d00-3fc2-11eb-894a-cf4c9ce56bb2.png">

**Comment by ValWood** [comment]
Or, should these have has_part to binding? I'm still not sure how this works?

**Comment by mah11** [comment]
> GO:0090079 translation regulator activity, nucleic acid binding
> has a direct parent to molecular function

No it doesn't (assuming "has a direct parent to" means "has a direct is_a link to"). The diagram shows that GO:0090079 is is_a GO:0045182 and is_a GO:0003676 nucleic acid binding (is the latter what you meant?).

I wouldn't expect GO:0045182 to have is_a GO:0003676 because it's meant to encompass regulators that bind nucleic acid and ones that don't. It's possible that GO:0090079 should be connected to GO:0003676 by has_part instead of is_a, but that opens its own can of worms.

**Comment by ValWood** [comment]
I was following the wrong link.
