### ISSUE TITLE
new taxon constraints, never in yeast

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20643]
It is a joy to be able to see all of the nuclear descendants easily  now the complexes are grouped.

Please add the following taxon restrictions:

Never in yeast, nucleus descendants
 - [ ] GO:0046808    assemblon  - obsolete ?  #20746
 - [x] GO:0031039 macronucleus (+ only in protozoa?)
 - [x] GO:0031040 micronucleus (+ only in protozoa?)
 - [x] GO:0045120  pronucleus  (+ only in metazoa?)
 - [ ] GO:0098537 lobed nucleus (seems to be immune cells so only in multicellular organisms with immune system)

also 
 - [x] GO:0060418    yolk plasma (+ only in metazoa?)
 - [x] GO:0045180    basal cortex   -> only in metazoa
 - [x] GO:0090652    basolateral cytoplasm  -> only in metazoa
term says "Used in reference to animal polarized epithelial cells." but has no annotation
 - [x] GO:0016323    basolateral plasma membrane 
 - [x] GO:0009925    basal plasma membrane -> see below https://github.com/geneontology/go-ontology/issues/20643#issuecomment-767454911
 - [x] GO:0044297    cell body
 - [ ] GO:0033012    porosome
 - [x] GO:0046868    mesosome (+ only in bacteria?) -> artifact, see https://en.wikipedia.org/wiki/Mesosome, but a few papers exist, see PMID:33309146, PMID:33327493
 - [x] GO:0031911     cytoproct (+ only in tetrahymena?) -> also found in other unicellulars, such as Euglenozoa, so I will add 'never in metazoa'

**Comment by pgaudet** [comment]
GO:0009925 basal plasma membrane is also found in plants. I dont know what's the taxonomic range
@AndreaAuchincloss is it found in bacteria?

**Comment by AndreaAuchincloss** [comment]
Nope, nor in archaea.

**Comment by pgaudet** [comment]
Not sure where to put porosome. PMC4580239 states "Discovery of the **universal** secretory machinery in cells –the porosome, came as no surprise since porosome-like ‘canaliculi’ structures for secretion from human platelets, the **secretory machinery** in single-cell organisms like the **secretion apparatus** in bacteria and Toxoplasma gondii, and the **contractile vacuole** in paramecium, have been demonstrated."

Maybe 'only in Eumetazoa '? There are no annotations; the papers I find talk about mammalian systems (pancreatic and neuronal cells).
