### ISSUE TITLE
Is NO a ROS?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20718]
GO:0034614   cellular response to reactive oxygen species
Biological Process

Definition (GO:0034614 GONUTS page)
Any process that results in a change in state or activity of a cell (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of reactive oxygen species stimulus. Reactive oxygen species include singlet oxygen, superoxide, and oxygen free radicals.

cellular response to ROS | exact

has the descendant
GO:0071732    cellular response to nitric oxide

but is nitric oxide a reactive oxygen species?

The paper I am reading says

"ROS, as a signaling molecule that causes oxidative stress, is formed
due to incomplete reduction of oxygen on the electron transfer chain
of mitochondria in most cell types (Dröge, 2002; Fridovich, 2004).
NO, also acting as a signaling molecule plays a pivotal role in the negative feedback system to regulate ROS levels in S. pombe..."

Since ROS and NO might be involved in glucose deprivation-
induced activation of Rst2 (Kato et al., 2013), we sought
to investigate whether ROS and NO are involved in mitochondrial
complex III/IV inhibitors-induced transcriptional activation of Rst2.
ROS levels and NO levels of wild-type cells stimulated with mitochondrial
complex III/IV inhibitors were measured by labeling with
a ROS probe DCFH-DA and a NO probe DAF-FM DA, respectively.

so  it seems that NO is not a ROS?

**Comment by ValWood** [comment]
Also, do we really need cellular and non-cellular versions of these terms?

**Comment by mah11** [comment]
> is nitric oxide a reactive oxygen species?

[ChEBI](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A26523) says yes (I was surprised, but it's on the "incoming" list).

**Comment by ValWood** [comment]
it seems odd and it isn't mentioned in the definition.
https://en.wikipedia.org/wiki/Nitric_oxide
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A16480
it is only described as a free radical, not a reactive oxygen species.
I  guess I should ask on the CHEBI tracker...

**Comment by raymond91125** [comment]
It appears that Nitric oxide is a Reactive Nitrogen Species (RNS) rather than an ROS.
"Nitrogen-containing oxidants, such as nitric oxide (NO.) peroxynitrite (ONOO.), nitrogen dioxide (NO2) are called reactive nitrogen species (RNS)."
"Reactive oxygen species (ROS) are small molecules derived from oxygen molecules including free oxygen radicals, such as superoxide (O2⋅_), hydroxyl (⋅OH), peroxyl (RO2⋅), and alkoxyl (RO_) as well as hypochlorous acid (HOCl), ozone (O3), singlet oxygen (1O2), and hydrogen peroxide (H2O2), which are non-radicals. "
REF: 
https://www.intechopen.com/books/basic-principles-and-clinical-significance-of-oxidative-stress/biochemistry-of-reactive-oxygen-and-nitrogen-species
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6009602/

**Comment by ValWood** [comment]
Thanks, @raymond91125  !   I'll open a CHEBI ticket.

**Comment by pgaudet** [comment]
The link has been removed form CHEBI. 

@balhoff I assume this will be automatically fixed in GO; when do we expect to see this fixed ?

**Comment by balhoff** [comment]
We have an open PR to update CHEBI. I would like some help from @hdrabkin to take a look at our use of CHEBI:77120.

**Comment by hdrabkin** [comment]
Just saw this Nitric Oxide IS a reactive oxygen species.  
http://www.plantphysiol.org/content/167/4/1209

**Comment by ValWood** [comment]
Maybe that is incorrect? The consensus seems to be that it isn't a ROS.

**Comment by hdrabkin** [comment]
I would defer to CHEBI, but just happened to see the above statement in that reference.

**Comment by raymond91125** [comment]
The way I interpret this commentary is that ROS and NO are distinct entities, actually. The title is: "Interplay of Reactive Oxygen Species and Nitric Oxide: Nitric Oxide Coordinates Reactive Oxygen Species Homeostasis", which implies that they are different.
Then the one suspect sentence is: "The most important redox molecules are reactive oxygen species (ROS), such as singlet oxygen, hydroxyl radical, superoxide anion, hydrogen peroxide, and nitric oxide (·NO)." I would read this as ROS and NO are both important redox molecules.
English is a second language to me. Full disclosure. :-)

**Comment by ukemi** [comment]
PMID:29707643, section 2.3

**Comment by pgaudet** [comment]
(just to make it easier): 

> PMID:29707643, section 2.3

states: 
Similar to ROS, the term reactive nitrogen species (RNS) has been coined to include nitric oxide (NO▪), peroxynitrite, nitrogen dioxide radical (NO2▪), and other oxides of nitrogen or nitrogen-containing reactive species. Because RNS are almost exclusively oxygen-containing species, by definition, they may also be classified as ROS. For example, peroxynitrite is classified as either an ROS or an RNS.

**Comment by pgaudet** [comment]
I think we can close this - this will be classified as ChEBI classifies it.
