### ISSUE TITLE
Cardiac conduction term revisions

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#20731]
Hi David

sorry about this but I have also discussed this with Andrew Cook who works on heart development and he has confirmed that the bundle of His leads to the bundle branches and that it is there that contact the Purkinje myocyte directly. I am very reluctant to create new terms for each part of the conduction system. I wonder if we could use the concept that the bundle of his includes the bundle branches, which is what was implied by the term that was created, also in discussions with heart physiology experts.

Current term GO:0086069 bundle of His cell to Purkinje myocyte communication
add exact synonym:
bundle branch cardiac muscle cell to Purkinje myocyte communication

But there are a lot of bundle of his terms and maybe this is just not necessary, what do you think?

Thanks

Ruth

**Comment by ukemi** [comment]
Hi Ruth,

I think this is a viable option, but whatever we decide with respect to the branches versus the bundle itself needs to come from Uberon. If you look at Uberon, there is a term  'atrioventricular bundle' that has the synonym 'bundle of His'. That term has two parts, the left branch and the right branch. If I'm understanding you correctly, this is consistent with your proposal. So it seems that 'I wonder if we could use the concept that the bundle of his includes the bundle branches' is true and consistent with Uberon. You might want to ask the ontology editors to switch the synonym and primary term name if you think it more closely represents the original intent of the term. Or maybe ask to change the primary term name 'bundle of His branch cell to Purkinje myocyte communication' to make it more explicit. This seems like it would be ok, since we definitely wanted to represent the communication at the cellular level and this seems all consistent with how Uberon represents the structures. Do you think this parthood is consistent with the way the anatomy would be viewed by the experts? Ie, is it ok to have the branches be part of the bundle? Perhaps additional synonyms could be added to reflect the nomenclature in Uberon. From your description above, it also seems that there is a part missing from Uberon that represents the bundle itself. The only parts in Uberon now are the left and right branch. But above you say that the bundle leads to the branches. Maybe there is a structure that would be the 'bundle proper'?  Hope this makes sense!

**Comment by RLovering** [comment]
Thanks David
I agree there are a lot of different names for the components of the conduction system.
In this article: https://dev.biologists.org/content/143/2/197 Fig 1 (and text)

- sinoatrial node (SAN) - located in atria
- atrioventricular node (AVN) - located in atria
- atrioventricular bundle (AVB, bundle of His, His bundle) - located in ventricles
- atrioventricular junction - located in ventricles
- right bundle branch - located in ventricles
- left bundle branch - located in ventricles
- peripheral ventricular conduction system (Purkinje fibre network) - located in ventricles
The atrial and ventricular myocardial tissues are electrically isolated from one another by a plane of connective tissue formed by the annulus fibrosus and central fibrous body. 
- ventricular conduction system (VCS) is all the conduction system located on the ventricular side of this connective tissue (ie it includes

**Comment by RLovering** [comment]
https://github.com/obophenotype/uberon/issues/1785
