### ISSUE TITLE
NTR: 2-hydroxyacyl-CoA lyase

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#20787]
I'm looking for the MF term for the pombe ortholog of HACL1 
https://www.uniprot.org/uniprot/Q9UJ83

Peroxisomal 2-OH acyl-CoA lyase involved in the cleavage (C1 removal) reaction in the fatty acid alpha-oxydation in a thiamine pyrophosphate (TPP)-dependent manner (PubMed:28289220, PubMed:21708296, PubMed:10468558). 

It is Rhea
2-hydroxy-3-methylhexadecanoyl-CoA = 2-methylpentadecanal + formyl-CoA

the GO annotation is only to
carbon-carbon lyase activity

but I can't find a suitable term.

**Comment by hdrabkin** [comment]
Hi Val
the reactions shown does not seem to reflect the name of the term you request; The reaction you list would be a child of the requested term. 
Wiki has this, which outlines  the 2-hydroxyacyl-CoA and the the R group, which could bye the 3-methylhexadecanoy-
https://en.wikipedia.org/wiki/2-hydroxyphytanoyl-CoA_lyase as reaction. 
2-hydroxy-3-methylhexadecanoyl-CoA IS a 2-hydroxyacly-CO; 
Note the R group 
The reaction you list for the rhea just has a different R group. 
So I can make the term but cannot use the RHEA for the def because it's a different substrate. 
So for the term to 
Catalysis of the reaction: A 2-hydroxyl-CoA = formyl-CoA + a propanol (with the PMIDs you supply)
The RHEA used would be a child term of this new one.
Does this make sense; the parent would be the carbon-carbon lyase activity

**Comment by ValWood** [comment]
OK I'm not sure. I was just basing my request on the annotation at UniProt. I wanted to ISS and 
carbon-carbon lyase activity did not seem specific enough for the described activity.
Does the Uniprot entry need updating to reflect this (i.e to align the description with the Rhea, and the Rhea with GO?)
 @pgaudet who would be a good person to look at the UniProt entry?

**Comment by hdrabkin** [comment]
Well, again, the RHEA they use is a reaction that uses a 3-substituted 2-hydroxyacyl-CoA as a substrate, based on the 2 papers paper cited in the RHEA entry for Q9UJ83. The protein name is more general than that; don't know if the UniProt protein can act on any or more than one  3-substituted 2-hydroxyacyl-CoA . 
I can make the two terms.

**Comment by hdrabkin** [comment]
Just to clarify
2-Hydroxyphytanoyl-CoA  (from Wiki) and 2-hydroxy-3-methylhexadecanoyl-CoA are two different substrates (the latter having methyl groups on the fatty acid chain.
RHEA would treat each reaction as a separate id.
and the UniProt entry already ists two reactions:s 
2-hydroxyoctadecanoyl-CoA = formyl-CoA + heptadecanal1 Publication
and 
2-hydroxyphytanoyl-CoA = 2,6,10,14-tetramethylpentadecanal + formyl-CoA1 Publication
EC:4.1.2.n21 Publication

So the GO term for the RHEA used should have the name '2-hydroxy-3-methylhexadecanoyl-CoA lyase activity'
2-hydroxy-CoA ligase activity would be its parent.

**Comment by hdrabkin** [comment]
+id: GO:0106359
+name: 2-hydroxyacyl-CoA lyase activity
+[Term]
+id: GO:0106360
+name: 2-hydroxy-3-methylhexadecanoyl-CoA lyase activity

**Comment by ValWood** [comment]
tks H.

**Comment by pgaudet** [comment]
Hi @ValWood 
Did you need both terms here? 

- '2-hydroxyacyl-CoA lyase activity'
- - '2-hydroxy-3-methylhexadecanoyl-CoA lyase activity'

We are being inconsistent; there are several more substrates described in RHEA. 

I propose we 'merge'(osbsolete+ replace by) '2-hydroxy-3-methylhexadecanoyl-CoA lyase activity' into '2-hydroxyacyl-CoA lyase activity'

**Comment by ValWood** [comment]
That works for me.

I am getting 
[GO:0016831](https://www.pombase.org/term/GO:0016831)	
[carboxy-lyase activity](https://www.pombase.org/term/GO:0016831)
[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with [KW-0210](https://www.uniprot.org/keywords/KW-0210)
GO:0016831 | carboxy-lyase activity

for this enzyme, is that mapping incorrect do you think?

Val


[GO:0016831](https://www.pombase.org/term/GO:0016831)	
[carboxy-lyase activity](https://www.pombase.org/term/GO:0016831)


GO:0016831 | carboxy-lyase activity
-- | --


[GO:0016831](https://www.pombase.org/term/GO:0016831)	
[carboxy-lyase activity](https://www.pombase.org/term/GO:0016831)

**Comment by pgaudet** [comment]
I think this is right - Decarboxylase is a synonym of [carboxy-lyase activity](https://www.pombase.org/term/GO:0016831). 

OK ?

**Comment by ValWood** [comment]
but  [GO:0016831](https://www.pombase.org/term/GO:0016831)
[carboxy-lyase activity](https://www.pombase.org/term/GO:0016831)

isn't a parent of
GO:0106359
+name: 2-hydroxyacyl-CoA lyase activity

it's a GO:0016832   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0016832/complete)
aldehyde-lyase activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 2-hydroxy-3-methylhexadecanoyl-CoA lyase activity', because this represents a specific substrate of its parent, GO:0106359 2-hydroxyacyl-CoA lyase activity. The term will be 'replaced by' GO:0106359. 

There is a  single manual annotation by pombase @ValWood 
One UniProt annotation has been fixed. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/20787

Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood 
KW-0210 is correctly mapped to GO:0016831 (ie [EC:4.1.1.-](https://enzyme.expasy.org/EC/4.1.1.-)

If there is a pombase entry incorrectly mapped to KW-0210  please open an annotation ticket. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Obsoleted term in https://github.com/geneontology/go-ontology/pull/25233
