### ISSUE TITLE
synonym for GO:0070824 SHREC complex

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#20938]
SHREC is an acronym for "Snf2/HDAC containing repressor complex" PMIDs are 17289569 and 27105116.

**Comment by rwst** [comment]
I also find "Snf2/Hdac Repressive Complex" in the latter PMID.

**Comment by pgaudet** [comment]
Fixed the synonyms. Is this always a transcription regulator complex ? Not according to the definition, "A histone deacetylase complex that contains a core of four proteins -- Clr1, Clr2, Clr3, and Mit1 in fission yeast -- and localizes to all heterochromatic regions in the genome as well as some euchromatic sites. The complex is involved in regulating nucleosome positioning to assemble higher-order chromatin structures."

It had as a parent "transcription repressor complex". I am removing that (because that implied dbTF); but I wonder if I should add back the more general "transcription regulator complex"

@mah11 

Thanks, Pascale

**Comment by mah11** [comment]
This is not an area I know well. The only thing I can contribute is a link to the ticket for which GO:0070824 was added - #6291

**Comment by pgaudet** [comment]
ok thanks !

**Comment by pgaudet** [comment]
I'll leave it at that until we know more.

**Comment by ValWood** [comment]
SHREC is an important component of the RNAi machinery. If we take @colinlog view that the default state for chromatin is to be repressed then SHREC and its ilk are not transcriptional repressors in the true sense.

More accurate would be the obsoleted "chromatin assembly complex", but in its absence whey not just "histone deacetylase complex"

@colinlog ?
