### ISSUE TITLE
Obsolete 'detection of stimulus involved in cell cycle checkpoint' branch

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#20976]
Dear all, 

The proposal has been made to obsolete the 'detection of stimulus involved in cell cycle checkpoint' branch. The reason for obsoletion is that these terms correspond to molecular functions. The terms impacted are: 

GO:0090429 detection of endogenous biotic stimulus
GO:0072394 detection of stimulus involved in cell cycle checkpoint 
GO:0072409 detection of stimulus involved in meiotic cell cycle checkpoint
GO:0072412 detection of stimulus involved in mitotic cell cycle checkpoint
GO:0072415 detection of stimulus involved in spindle checkpoint 
GO:0072460 detection of stimulus involved in meiotic recombination checkpoint
GO:0072463 detection of stimulus involved in meiotic spindle assembly checkpoint 
GO:0072475 detection of stimulus involved in mitotic spindle checkpoint
GO:0072484 detection of stimulus involved in spindle assembly checkpoint
GO:0072481 detection of stimulus involved in mitotic spindle orientation checkpoint
GO:0072469 detection of stimulus involved in cell size control checkpoint
GO:0072448 detection of stimulus involved in G1 cell size control checkpoint
GO:0072451 detection of stimulus involved in G2 cell size control checkpoint
GO:0072397 detection of stimulus involved in cytokinesis checkpoint
GO:1903819 detection of stimulus involved in mitotic cytokinesis checkpoint
GO:0072400 detection of stimulus involved in mitotic DNA integrity checkpoint
GO:1902401 detection of stimulus involved in mitotic DNA damage checkpoint
GO:0072442 detection of stimulus involved in mitotic DNA replication checkpoint 
GO:0072427 detection of DNA damage stimulus involved in intra-S DNA damage checkpoint
GO:0072430 detection of DNA damage stimulus involved in mitotic G1 DNA damage checkpoint
GO:0072433 detection of DNA damage stimulus involved in mitotic G2 DNA damage checkpoint 
GO:1903821 detection of stimulus involved in morphogenesis checkpoint

There is a single annotation to those terms, by MGI (MGI:1328317). There are no mappings, those terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/20976
 
Thanks, Pascale

**Comment by hdrabkin** [comment]
What ticket had the discussion on this? The link just comes back to this ticket. Looking for suggested functions to replace?

**Comment by ValWood** [comment]
It seems that it shouldn't be annotated to a "checkpoint" term.

in the abstract
"Notably, Trex1-deficient cells show defective G1/S transition and chronic ATM-dependent checkpoint activation, even in the absence of exogenous stress, correlating with persistent single-stranded DNA molecules produced in S phase, which accumulate in the ER."

So Trex1 isn't part of  checkpoint activation. However, in it's absence  abherrant DNA structures which are recognised by the  DNA integrity checkpoints accumulate.

When Trex1 is removed, a pathological situation arises and the checkpoint is activated. The gene product Trex1 itself isn't regulating the checkpoint is it?

"The data indicate chronic ATM-mediated checkpoint activation in Trex1−/− cells in the absence of exogenous DNA damage."

New MF terms will be created for "sensors" as required, but this doesn't appear to be a sensor. I would not make an annotation (other than of the are experiments to show the normal process of degrading DNA GO:0006308    DNA catabolic process ...in fact this seems to be removing toxic DNA-intermediates?)

**Comment by pgaudet** [comment]
Actually there are 2 annotations from 2 papers: 
- PMID:18045533 (the paper Val looked at)
- In the results, the authors write "these data show that unstressed Trex1−/− MEFs are defective in G1/S transition.", and in the discussion the authors write "Trex1 acts on an ssDNA polynucleotide species arising from the processing of aberrant DNA replication intermediates, leading to chronic ATM-dependent checkpoint " - so really 'signaling' would be OK as a process 
- This supports an annotation to GO:0031571 mitotic G1 DNA damage checkpoint (we have changed the label to 'mitotic G1 DNA damage checkpoint signaling' in #20935) 

- PMID:23993650 -> I dont see 'checkpoint' being mentioned; DNA damage sensor would seem appropriate. Let me know if you want the term to be created. 


Thanks, Pascale

**Comment by ValWood** [comment]
> "Trex1 acts on an ssDNA polynucleotide species arising from the processing of aberrant DNA replication intermediates, leading to chronic ATM-dependent checkpoint " - so really 'signaling' would be OK as a process

This isn't signalling though? A gene that is deleted thereby causing an increase in toxic by-products that are detected by a checkpoint isn't signalling. In a normal situation, this wouldn't occur, its a 'pathological' phenotype.  At least, from his data, my interpretation was that the cell is detecting, and trying to fix a problem, but because the problem is not correctable, the checkpoint is overwhelmed.
I see these phenotypes a lot in different mutants. For example, in fission yeast a 'cut' phenotype   occurs if the spindle checkpoint is 'overwhelmed' (162 genes so far). The checkpoint is usually activated because of some problem assembling the spindle or connecting the chromosomes. However, if a key component is absent, the problem is impossible to repair and the checkpoint eventually becomes overwhelmed/expires and cytokinesis proceeds even without correct chromosome segregation.
Similar problems occurs with DNA integrity checkpoints Most elongated inviable phenotypes (>460 genes)   result from a block at G2 checkpoints to fix interphase problems, these can be caused by defects in replication or even way upstream  (transcription, translation, splicing). The gene products which are absent, or mutated, have no role in signalling in a 'normal situation'.  
If we do this, thousands of gene products could become annotated to signalling, because their mutation or absence results in checkpoint activation. Unfortunately, researchers sometimes refer to these obsevations as checkpoint activation or regulation, but the content is slightly different to 'real regulation'.

There are some instructions about this somewhere but I have no idea where they went (maybe on the wiki?). I'll try to track hem down as they should be added as comments to all of the checkpoint terms.

(disclaimer: I may have misinterpreted this paper due to lack of knowledge about this area in higher eukaryotes, but I don't see how a deficiency can be attributed to signalling in these cases)

**Comment by hdrabkin** [comment]
done

**Comment by pgaudet** [comment]
+ GO:0009726 detection of endogenous stimulus (No annotations)
