### ISSUE TITLE
"mitochondrial DNA replication" parentage, missing "DNA biosynthetic process"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21036]
HI,

I noticed that we are picking up a mapping for 
"DNA biosynthetic process" when  we have already an experimental annotation to "mitochondrial DNA replication"

Since we only display non-redundant IBA this implies an ontology issue. Is there any reason why
"mitochondrial DNA replication" cannot be is_a "DNA biosynthesis process"?

**Comment by ValWood** [comment]
Note that 'DNA replication' isn't under 'DNA biosynthetic process' due to  the synthesis of RNA primers, but here:

https://github.com/geneontology/go-ontology/issues/17716
it was decided that  "mitochondrial DNA replication"
could go under  "DNA biosynthetic process"  and the parentage was added. 

Was this parent subsequently removed?

**Comment by ValWood** [comment]
Maybe
DNA strand elongation (GO:0022616)
can also be  prt_of
"DNA biosynthetic process" ?

**Comment by mah11** [comment]
> Maybe DNA strand elongation (GO:0022616) can also be part_of "DNA biosynthetic process" ?

No, because lagging strand elongation involves the synthesis of quite a few RNA primers.

Maybe leading strand elongation could have the link, but not if the current structure is correct -- right now both leading strand elongation (GO:0006272) and lagging strand elongation (GO:0006273) have the same has_part links: `relationship: has_part GO:0006269 ! DNA replication, synthesis of RNA primer` and `relationship: has_part GO:0043137 ! DNA replication, removal of RNA primer`.

For the leading strand I guess it comes down to whether "elongation" starts before or after the RNA primer is removed (and I don't remember myself; I know initiation better than the rest of the replication process).

**Comment by mah11** [comment]
> #17716 it was decided that "mitochondrial DNA replication" could go under "DNA biosynthetic process" and the parentage was added

That's not how I read that ticket -- instead, "DNA synthesis involved in mitochondrial DNA replication" (GO:0110166) was added, and that's what has the link to DNA biosynthetic process.

I also looked again at the reviews I linked to the older ticket, and they cite evidence that RNA-DNA hybrids may be formed as part of mtDNA replication in some mammalian mitochondria, which would argue in favor of the existing arrangement in GO.

**Comment by ValWood** [comment]
OK there does seem to be evidence of mitochondrial priming.
