### ISSUE TITLE
positive regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21104]
regulation of activity in process:

should we remove
positive regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity

we had  used for a kinase  it where

positive regulation of isopentenyl diphosphate biosynthetic process, mevalonate pathway

was sufficient.

Only 2 EXP -one PomBAse, one TAIR. I'm removing ours.

**Comment by pgaudet** [comment]
Actually there are 3 terms, with annotations by BHF also: 

* GO:2001215 regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity
* GO:2001216 negative regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity
* GO:1900490 positive regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity 

Looks like the annotations could be changed to 
'acts upstream of, (negative/positive) effect', with 'has input' (gene name)
This should work for miRNAs, and for he TAIR paper, I dont see the mechanism, so that would be the appropriate relation.

@RLovering @tberardini does that work for you ? 

Thanks, Pascale

**Comment by tberardini** [comment]
I thought I commented but looks like I didn't. Works for me.  TAIR annotation updated.

**Comment by pgaudet** [comment]
HI @RLovering 
You have 2 annotations, to microRNAs RNAcentral:URS00002367FA_9606 and RNAcentral:URS00004176D4_9606. 
From the abstract I dont know that we can put an MF, but perhaps the BP should be 'GO:0150165 miRNA-mediated inhibition of transcription by RNA polymerase II', with 'negatively regulates' hydroxymethylglutaryl-CoA reductase (NADPH) activity. 

Would that work?

**Comment by pgaudet** [comment]
Discussion with @RLovering @gantonazzo @hattrill 

http://noctua.berkeleybop.org/editor/graph/gomodel:5b528b1100000061

<img width="709" alt="image" src="https://user-images.githubusercontent.com/4782928/142873158-233b2a6d-8920-4972-a04e-256cc1ac723a.png">


Annotation Preview: 

FOXO3 Hsap | enables | DNA-binding transcription activator activity | PMID:18393360 | direct assay evidence used in manual assertion |   |   | 20180725 | GO_Central | part_of(positive  regulation of transcription by RNA polymerase  II),positively_regulates(protein kinase inhibitor  activity),has_input(CDKN1B Hsap)

We would like to also see the annotation 'FOXO3 acts upstream of, positive effect' of 'mitotic cell point signaling'.  
and moreover, while existing tools what they are doing now, it would be better (if not ideal) it would be better to even have acts upstream of, positive effect' _positive regulation of mitotic cell point signaling_.

@thomaspd @vanaukenk is this what is planned?

**Comment by vanaukenk** [comment]
@thomaspd - would you be able to attend a GO-CAM Office Hours call tomorrow (Tuesday, November 23rd - 8am PST)?

**Comment by pgaudet** [comment]
Discussing with @thomaspd 
He proposes to make an annotation for FOXO3 to 'positive regulation of cell cycle checkpoint' (positive regulation of cell cycle checkpoint **signaling** is NOT a GO term). 

<img width="738" alt="image" src="https://user-images.githubusercontent.com/4782928/145194167-a96e8803-cf79-4b69-80c0-3075a5ff0039.png">

This exports 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/4782928/145194344-5b78d3b9-581b-4c58-8e26-01fd0ab5427b.png">


@vanaukenk @RLovering Does that seem like a good solution? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Discussing with @vanaukenk @thomaspd @ukemi 

The annotations for URS00004176D4_9606 from PMID:24296663 would be
- URS00004176D4_9606 enables mRNA binding (or whatever the miRNA function we agree on) has input P04035 (3-hydroxy-3-methylglutaryl-coenzyme A reductase), negatively regulates 'GO:0004420 hydroxymethylglutaryl-CoA reductase (NADPH) activity' _(instead of 'GO:2001216 acts upstream of or within negative regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity)_
- URS00004176D4_9606 involved in GO:0106108 negative regulation of (R)-mevalonic acid biosynthetic process (already annotated)


OK with you @RLovering ? 

Thanks, Pascale

**Comment by ValWood** [comment]
To me, it doesn't seem right to say that something which regulates the expression of a gene regulates its activity. I would only say it negatively regulated the process (i.e cholesterol biosynthesis or whatever). To regulate an enzymatic activity, doesn't the activity already need to exist? if a microRNA or mRNA is somehow repressing the expression, in many cases that is the 'default'. The expression needs to be actively turned on in some way, and only once a gene product is expressed can you alter its activity.

I'm also leary of transcription regulation of cell cycle checkpoint signalling. Most checkpoint signalling is controlled translationally (based on  appropriate size and other environmental conditions ) so I would not expect to see a transcription factor annotated to 
"positive regulation of mitotic cell point signaling". Of course the genes need to be expressed, but they are generally  not regulatory.

but acts upstream of, positive effect'  mitotic cell-cycle checkpoint point 
seems OK.
(i.e. it affects checkpoint signalling but isn't directly regulating it).

Of course, if you fail to transcribe an inhibitor that is usually present,  and would be inactivated to allow cell cycle progression when the right conditions are met, you will get uncontrolled proliferation.  But it seems a stretch to connect the transcription factor itself to this regulation.  There are no mention of any "checkpoint" in the cited paper. All this paper shows is that FOXO transcribes CDKN1B. But this It does not demonstrate that any downstream process is transcriptionally regulated.

**Comment by RLovering** [comment]
Thank you so much for thinking about this. Sorry to have taken so long that my response probably contradicts that of Val's response above.

I have also got very confused because I am not sure if we are discussing a miR which binds to a mRNA to prevent translation or a miR that binds to the DNA and prevents transcription.

If we are discussing a mir that binds to mRNA and inhibits translation/increases mRNA degradation

Ideally I would like to see 2 MF terms for miRs so I agree with 

- URS00004176D4_9606 enables mRNA binding (or whatever the miRNA function we agree on) has input P04035 (3-hydroxy-3-methylglutaryl-coenzyme A reductase), negatively regulates 'GO:0004420 hydroxymethylglutaryl-CoA reductase (NADPH) activity' (instead of 'GO:2001216 acts upstream of or within negative regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity)

Consequently I would also create another annotation based on this article such as 

- URS00004176D4_9606 enables translation inhibitor activity (or an appropriate 'activity' MF term) has input P04035 (3-hydroxy-3-methylglutaryl-coenzyme A reductase), negatively regulates 'GO:0004420 hydroxymethylglutaryl-CoA reductase (NADPH) activity' (instead of 'GO:2001216 acts upstream of or within negative regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity)

I have 2 questions about the 'negatively regulates' annotation extension:
1. If a reduction in the amount of P04035 (3-hydroxy-3-methylglutaryl-coenzyme A reductase) is shown in the article can we add this information even if there is no assay confirming a reduction in the activity of the protein (I realise that for enzymes the activity is what is usually measured, but for other proteins , such as receptors or transcription factors the change in the level of 'activity' of protein may not be shown. We have been annotating conservatively on this and only creating annotations that imply a change in the activity of the target if this is actually shown, ie we have not annotated a change in the target 'activity' if only a change in the amount of target is shown.
2. I would probably create the direct annotation: URS00004176D4_9606 involved in  GO:2001216 negative regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity and therefore would add the annotation extension: part_of GO:2001216 negative regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity rather than negatively regulates GO:0004420 hydroxymethylglutaryl-CoA reductase (NADPH) activity. Are these options equivalent?

WRT the other annotation this looks good to me
- URS00004176D4_9606 involved in GO:0106108 negative regulation of (R)-mevalonic acid biosynthetic process (already annotated) 

I guess my other request would be to recognise that according to UniProt P04035 (3-hydroxy-3-methylglutaryl-coenzyme A reductase) 'Catalyzes the conversion of (3S)-hydroxy-3-methylglutaryl-CoA (HMG-CoA) to mevalonic acid, the rate-limiting step in the synthesis of cholesterol and other isoprenoids, thus plays a critical role in cellular cholesterol homeostasis'. The article annotated (entitled Identification of miR-185 as a regulator of de novo cholesterol biosynthesis and low density lipoprotein uptake) also includes data that suggests that the miR is involved in the response to cholesterol and also acts_upstream of GO:0045541 negative regulation of cholesterol biosynthetic process. Is this going to be acceptable or is this all too upstream?

If it is acceptable then I would add an annotation extension:
URS00004176D4_9606 involved in GO:0106108 negative regulation of (R)-mevalonic acid biosynthetic process annotation extension: causally upstream of GO:0045541 negative regulation of cholesterol biosynthetic process, part_of cellular response to cholesterol (as a single statement).

If we are talking about transcription, then I think I still agree that if the transcription regulator changes the amount of transcript and the amount of protein or activity of the protein is also measured and found to change then I would also apply the terms above. Although I have to admit that I think on Monday I was saying that there needs to be better guidelines about the use of negatively/positively regulating an activity v being an activity inhibitor/activator. There are guidelines that state that to be an activator or inhibitor the entity has to directly bind to the target. Which I have followed, but I was not aware of any guidelines that stated that a process term implying negatively/positively regulating an activity had to imply direct binding. After all if this was implied then there would be complete redundancy between the BP negatively/positively regulating an activity and the MF activity inhibitor/activator.

Sorry about the number of issues raised here.

Ruth

**Comment by hattrill** [comment]
Are we going to talk about this on Friday or Monday? There are so many points here that we need to have a discussion.

**Comment by ValWood** [comment]
I'm a bit confused how the transcription-> regulation of checkpoint became part ofthe positive regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity
ticket. These aren't connected are they?

**Comment by RLovering** [comment]
I think two completely different conversations  have been merged here.

**Comment by pgaudet** [comment]
> I'm a bit confused how the transcription-> regulation of checkpoint became part of the positive regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity
ticket. These aren't connected are they?


See http://amigo.geneontology.org/amigo/gene_product/RNAcentral:URS00004176D4_9606

there is a microRNA annotated to 'negative regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity', since it prevents/inhibits the translation of the protein, so the activity in the cell is decreased. To reannotate this, I looked at how we proposed to link transcription factors (ie, other regulators or gene expression), and this gave the proposal I put here yesterday: https://github.com/geneontology/go-ontology/issues/21104#issuecomment-988879725

So @RLovering if you are OK with a solution like this, please reannotate and I will go ahead and obsolete 'regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity' and the + and - children. 

Thanks, Pascale

**Comment by RLovering** [comment]
done thanks
Ruth

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 

*  GO:2001215 regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity
*  GO:2001216 negative regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity
* GO:1900490 positive regulation of hydroxymethylglutaryl-CoA reductase (NADPH) activity
The reason for obsoletion is that are molecular functions represented as biological processes. 

Annotations have been removed; there are no mappings; these terms are no present in an subsets. 

You may comment on the ticket: https://github.com/geneontology/go-ontology/issues/21104


Thanks, Pascale
