### ISSUE TITLE
nuclear mRNA surveillance of spliceosomal pre-mRNA splicing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21116]
How does
GO:0071033    nuclear retention of pre-mRNA at the site of transcription
differ from it's parent
GO:0071030   nuclear mRNA surveillance of spliceosomal pre-mRNA splicing

Isn't  'nuclear retention' just describing that the process occurs in the nucleus?

**Comment by pgaudet** [comment]
@krchristie 
I think you created those terms, can you comment on this ?

**Comment by ValWood** [comment]
More info.

Note there are no siblings (which seems odd)
However, there is also a child:
nuclear retention of pre-mRNA with aberrant 3'-ends at the site of transcription
but this term does not seem to be explicitly  spliceosomal?

Most annotations are to exosome. I guess the exosome is retaining the mRNAs to degrade them, but 'retention' sounds more of a phenotype than a step in the process?

**Comment by pgaudet** [comment]
'retention' may be sequestering?

**Comment by krchristie** [comment]
Looking at the ontology, these two terms were created as part of a set of terms to deal with RNA catabolism when Dianna Fisk several other SGD curators were focusing on that topic in a comprehensive way. I'm sure I contributed to how the terms are organized based on practice at the time, but I don't have particularly much recollection of how nuclear RNA surveillance works.

- GO:0071025 - RNA surveillance (P)
- GO:0071026 - cytoplasmic RNA surveillance (P)
- GO:0071027 - nuclear RNA surveillance (P)
- GO:0071028 - nuclear mRNA surveillance (P)
- GO:0071029 - nuclear ncRNA surveillance (P)
- **GO:0071030 - nuclear mRNA surveillance of spliceosomal pre-mRNA splicing (P)**
- GO:0071031 - nuclear mRNA surveillance of mRNA 3'-end processing (P)
- GO:0071032 - nuclear mRNA surveillance of mRNP export (P)
- **GO:0071033 - nuclear retention of pre-mRNA at the site of transcription (P)**
- GO:0071034 - CUT catabolic process (P)
- GO:0071035 - nuclear polyadenylation-dependent rRNA catabolic process (P)
- GO:0071036 - nuclear polyadenylation-dependent snoRNA catabolic process (P)
- GO:0071037 - nuclear polyadenylation-dependent snRNA catabolic process (P)
- GO:0071038 - nuclear polyadenylation-dependent tRNA catabolic process (P)
- GO:0071039 - nuclear polyadenylation-dependent CUT catabolic process (P)
- GO:0071040 - nuclear polyadenylation-dependent antisense transcript catabolic process (P)
- GO:0071041 - antisense RNA transcript catabolic process (P)
- GO:0071042 - nuclear polyadenylation-dependent mRNA catabolic process (P)
- GO:0071043 - CUT metabolic process (P)
- GO:0071044 - histone mRNA catabolic process (P)
- GO:0071045 - nuclear histone mRNA catabolic process (P)
- GO:0071046 - nuclear polyadenylation-dependent ncRNA catabolic process (P)
- GO:0071047 - polyadenylation-dependent mRNA catabolic process (P)
- GO:0071048 - nuclear retention of unspliced pre-mRNA at the site of transcription (P)
- GO:0071049 - nuclear retention of pre-mRNA with aberrant 3'-ends at the site of transcription (P)
- GO:0071050 - sno(s)RNA polyadenylation (P)
- GO:0071051 - polyadenylation-dependent snoRNA 3'-end processing (P)

The two terms you asked about are part of a structure that is shared with another pair of terms where one is specifically a localization term that is 'part_of' a nuclear mRNA surveillance term

![20210316-GO_0071030-tree](https://user-images.githubusercontent.com/10533218/111386515-971ed380-8669-11eb-822b-fe02769b39e0.png)

![20210316-GO_0071033-tree](https://user-images.githubusercontent.com/10533218/111386520-97b76a00-8669-11eb-97db-e4a75ba202a9.png)


Regarding specific questions from @ValWood @pgaudet 

> How does
> GO:0071033 nuclear retention of pre-mRNA at the site of transcription
> differ from it's parent
> GO:0071030 nuclear mRNA surveillance of spliceosomal pre-mRNA splicing
> 
> Isn't 'nuclear retention' just describing that the process occurs in the nucleus?

I would read the key part of this localization as **'retention [snip] at the site of transcription'**, which is a more specific localization somewhere in the nucleus. To me this is specifically retaining the improperly process pre-mRNA at the site of transcription, rather than releasing it. Thus, regarding suggestion of @pgaudet that perhaps this is just sequestering, I'm not sure that's appropriate as 'sequestering' doesn't have the same meaning as 'retention' about keeping the thing in the place where it was already located, not just group things together.

> Most annotations are to exosome. I guess the exosome is retaining the mRNAs to degrade them, but 'retention' sounds more of a phenotype than a step in the process?

I'm not sure I agree with this comment, but I don't remember this area well enough to comment specifically. Perhaps SGD ( @srengel ) should comment as this was a comprehensive annotation effort 


> Note there are no siblings (which seems odd)
By this, do you mean that **GO:0071033 - nuclear retention of pre-mRNA at the site of transcription (P)** is the only part_of child of the term **GO:0071030 - nuclear mRNA surveillance of spliceosomal pre-mRNA splicing (P)**?


> However, there is also a child:
> nuclear retention of pre-mRNA with aberrant 3'-ends at the site of transcription
> but this term does not seem to be explicitly spliceosomal?

Why should  **'nuclear retention of pre-mRNA with aberrant 3'-ends at the site of transcription'** be explicitly spliceosomal? Generation of mRNA 3' ends is done by the polyadenylation/cleavage machinery, not the spliceosome.

**Comment by ValWood** [comment]
Apologies. I meant to question the relationship between

GO:0071048      nuclear retention of unspliced pre-mRNA at the site of transcription 
being a descendant of
GO:0071030 nuclear mRNA surveillance of spliceosomal pre-mRNA splicing

it seems that  this is not always true?

Otherwise I am happy for this ticket to close. Although  there seem to  too many substrate specific terms to describe the same pathway, it isn't completely clear to me which RNA types have separate pathways and which are the same....The current structure is  more historical than incorrect.

**Comment by krchristie** [comment]
> Apologies. I meant to question the relationship between
> 
> GO:0071048      nuclear retention of unspliced pre-mRNA at the site of transcription
> being a descendant of
> GO:0071030 nuclear mRNA surveillance of spliceosomal pre-mRNA splicing
> 
> it seems that this is not always true?

Do you have an example when this is not true? 

In cerevisiae, I'm only aware of one nuclear transcribed protein coding gene that is spliced by anything other than the spliceosome, which is that of Hac1, but that occurs in the cytoplasm by a pathway that shares a mechanism with the tRNA splicing that occurs in the cytoplasm.

> On overload of the folding capacity in the ER, Ire1p forms an oligomer to allow trans-autophosphorylation by the kinase domain. Concomitant activation of the endonuclease domain initiates unconventional unconventional cytoplasmic splicing of HAC1 pre-mRNA, HAC1u mRNA. HAC1 encodes a bZIP-type transcription factor responsible for activating expression of UPR target genes. The resulting exons from HAC1u mRNA are ligated to HAC1i mRNA by tRNA ligase, Rlg1p/Trl1p. The
primary role of Rlg1p is to ligate tRNA exons, which are also produced in the cytoplasm by tRNA splicing endonuclease on the mitochondria. To catalyze the tRNA and HAC1 ligation, Rlg1p has three enzymatic activities: 2′-3′ cyclic phosphodiesterase, polynucleotide kinase, and adenylate synthetase/RNA ligase. The HAC1 splicing is finished by 2′-phosphotransferase, Tpt1p, which removes a 2′-phosphate left at the splicing junction of tRNA.

Mori et al. 2010. Dual functions of yeast tRNA ligase in the unfolded protein response: unconventional cytoplasmic splicing of HAC1 pre-mRNA is not sufficient to release translational attenuation. Mol Biol Cell. 2010 Nov 1;21(21):3722-34. PMID:20844078

**Comment by ValWood** [comment]
I see now from the definition

Definition (GO:007103 ) The process involved in retention of aberrant or improperly formed mRNAs, e.g. those that are incorrectly or incompletely spliced or that have incorrectly formed 3'-ends, within the nucleus at the site of transcription. 

That this is a grouping term for retention from different pathways - I think it is just an odd classification. 

Happy to close for now.
