### ISSUE TITLE
NTR: opioid growth factor receptor activity

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#21110]
The definition of GO:0004985 opioid receptor activity states "Combining with an opioid (any narcotic derived from or resembling opium), and transmitting the signal across the membrane by activating an associated G-protein." which is fine but excludes the zeta receptor a.k.a. opioid growth factor receptor which is not a GPCR. Unfortunately curators annotated it to GO:0004985, perhaps for lack of alternative, so I'm requesting the following:

```
name: opioid growth factor receptor activity
namespace: molecular_function
def: "Combining with the opioid growth factor (OGF, met-enkephalin) and transmitting the signal across the membrane by other means than activating an associated G-protein. Met-enkephalin is an endogenous opioid peptide that binds to opioid and opioid growth factor receptors, regulating tissue growth in a variety of processes." PMID 10677613, 11890982.
is_a: transmembrane signaling receptor activity ; GO:0004888
```

While this request is outside of a GOA project, I have curated for UniProt-GOA in the past so you might still have my handle/credentials, otherwise I'm currently curating for Reactome---perhaps this suffices?

**Comment by pgaudet** [comment]
Is there a way to define this positively? as opposed to "by other means than activating an associated G-protein" 

I've been looking at the papers, it looks like a strange kind of nuclear receptor?

**Comment by rwst** [comment]
We could just leave out the "not GPCR" bit. It would make e.g. the delta receptors have opioid growth factor receptor acrivity as well. Which is semantically correct because they bind the molecule too. It is also correct in not defining for a specific gene product---which  apparently is a frequent temptation.

**Comment by pgaudet** [comment]
Is the mechanism of action of this receptor known? Oherwise perhaps we can call it 'intracellular opoid receptor activity'?

**Comment by rwst** [comment]
Not "opioid recptor" --- it specifically binds to opioid growth factor a.k.a met-enkephalin, and this property should suffice.

**Comment by pgaudet** [comment]
Here's the new term: 

+[Term]
+id: GO:0140625
+name: opioid growth factor receptor activity
+namespace: molecular_function
+def: "Combining with the opioid growth factor (OGF, met-enkephalin) and transmitting the signal across the nuclear membrane. Met-enkephalin is an endogenous opioid peptide that binds to opioid and opioid growth factor receptors, regulating tissue growth in a variety of cellular processes." [PMID:11890982]
+synonym: "met(5)]-enkephalin receptor activity" RELATED []
+synonym: "met-enkephalin receptor activity" RELATED []
+is_a: GO:0001653 ! peptide receptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21110 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-17T13:15:33Z

 - [x]  I changed the label for GO:0004985 opioid receptor activity to G protein-coupled opioid receptor activity, as well as 
 - [ ]  Do you want a 'signaling pathway' BP term?  
GO:0038046 enkephalin receptor activity to G protein-coupled enkephalin receptor activity
 - [ ]  The annotations are coming from InterPro IPR039574 - @sarach06 @EBI-Hsinyu can you please change the mapping to GO:0140625 (when the term is available, of course)
 - [x]  I remove the UniProt NAS annotation from PMID:10677613 since this does not have direct evidence for the opioid growth factor receptor activity. 


Thanks, Pascale

**Comment by rwst** [comment]
Thanks, agree with all changes.

**Comment by rwst** [comment]
Note the typo in your comment: `met(5)]-enkephalin`

**Comment by pgaudet** [comment]
Also created the BP 

 
+[Term]
+id: GO:0140626
+name: opioid growth factor receptor signaling pathway
+namespace: biological_process
+def: "The series of molecular signals generated as a consequence of an opioid growth factor receptor binding to its physiological ligand, opioid growth factor (OGF, met-enkephalin). The OGF-OGFr complex leads to the increase in the synthesis of the selective cyclin-dependent kinase (CDK) inhibitor proteins, p12 (POLD4) and p16 (CDKN2A)." [PMID:19675283, PMID:19923357]
+comment: Note that this term represents the activation of the zeta-opioid receptor. Do not confuse with GO:0038003 ; G protein-coupled opioid receptor signaling pathway, activated by the delta, kappa, mu, and nociceptin receptors.
+xref: Wikipedia:OGFr
+xref: Wikipedia:Opioid_receptor
+intersection_of: GO:0007165 ! signal transduction
+intersection_of: starts_with GO:0140625 ! opioid growth factor receptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21110 xsd:anyURI
+created_by: pg
+creation_date: 2021-03-18T08:30:43Z
