### ISSUE TITLE
NTRs: ciliary pro-basal body maturation & ciliary basal body segregation

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#21153]
Hi,
Can I request the following two new terms please?

Accession: GO:xxxxxx
Name: ciliary pro-basal body maturation
Ontology: biological_process
Synonyms: flagellar pro-basal body maturation, flagellar probasal body maturation, pro-basal body maturation
Definition: A process that is carried out at the cellular level which results in the conversion of an immature and partially assembled ciliary pro-basal body into a mature basal body that is capable of nucleating a cilium.
is_a: GO:0032053 ! ciliary basal body organization
[RO:0002588 relation] RO:0002588: GO:0036064 ! ciliary basal body
Source: PMID:26862392, GOC:ach

Accession: GO:xxxxxx
Name: ciliary basal body segregation
Ontology: biological_process
Synonyms: microtubule basal body segregation, ciliary basal body separation, microtubule basal body separation
Definition: The process in which the duplicated basal bodies migrate in pairs to the mitotic poles of the nucleus and results in equal distribution in the daughter cells. Ciliary basal body segregation ensures inheritance of the duplicated mitochondrial DNA to the two daughter cells in the Trypanosoma parasites.
is_a: GO:0032053 ! ciliary basal body organization
Source: PMID:1876188, PMID:4055898, PMID:26272611, PMID:26862392, PMID:27252853, GOC:ach

Thanks & best wishes,
Achchuthan

**Comment by krchristie** [comment]
> Name: ciliary pro-basal body maturation
> Ontology: biological_process
> Synonyms: flagellar pro-basal body maturation, flagellar probasal body maturation, pro-basal body maturation
> Definition: A process that is carried out at the cellular level which results in the conversion of an immature and partially assembled ciliary pro-basal body into a mature basal body that is capable of nucleating a cilium.
> is_a: GO:0032053 ! ciliary basal body organization
> [RO:0002588 relation] RO:0002588: GO:0036064 ! ciliary basal body
> Source: PMID:26862392, GOC:ach

I thought that it also seemed that we could say that this starts with a ciliary pro-basal body, and then it seemed that I could combine the statements you provided with the one I added and make it the logical definition, like this:

+intersection_of: GO:0016043 ! cellular component organization
+intersection_of: results_in_assembly_of GO:0036064 ! ciliary basal body
+intersection_of: starts_with GO:0120280 ! ciliary pro-basal body

Let me know if you agree with this or think any changes are needed.

**Comment by krchristie** [comment]
> Accession: GO:xxxxxx
> Name: ciliary basal body segregation
> Ontology: biological_process
> Synonyms: microtubule basal body segregation, ciliary basal body separation, microtubule basal body separation
> Definition: The process in which the duplicated basal bodies migrate in pairs to the mitotic poles of the nucleus and results in equal distribution in the daughter cells. Ciliary basal body segregation ensures inheritance of the duplicated mitochondrial DNA to the two daughter cells in the Trypanosoma parasites.
> is_a: GO:0032053 ! ciliary basal body organization
> Source: PMID:1876188, PMID:4055898, PMID:26272611, PMID:26862392, PMID:27252853, GOC:ach

I don't want to hold up your term for any of the other changes I'd like to make to start bringing together the basal body and centrosome sides of this structure in a coherent way in GO. So for now, I'll go ahead and put it in as you requested except with parentage of is_a `cellular process` instead of what you suggested or what I currently think that I would like to change it to.

I would also welcome your input on my thoughts on bringing together the basal body and centrosome sides together in a more coherent way in GO. Do you think this works for organisms that don't use the basal body as a centrosome?


It doesn't seem quite right to me that this term would be a type of `ciliary basal body organization` since in GO we normally use `organization` to describe the assembly and/or arrangement of a structure, but not it's positioning or movement.

I looked at how we place some potentially relevant existing terms:

* centrosome cycle (GO:0007098) [is_a 'cell cycle process']
* - centrosome separation (GO:0051299) [is_a 'cell cycle process'] [part of 'centrosome cycle']

* microtubule organizing center localization (GO:0061842)
* - centrosome localization (GO:0051642) [is_a 'microtubule organizing center localization']

* chromosome segregation (GO:0007059) [is_a 'cellular process']
* - chromosome separation (GO:0051304) [is_a 'cell cycle process'] [part of 'chromosome segregation']

The term that seems most comparable to the new term you are requesting is `centrosome separation`, which I like since these terms should match since the `centriole` and `basal body` are basically the same base structure with different modifications depending on which role they are playing, noting that basal bodies/centrosomes of some organisms or cell types have both roles, while others have only one or the other.

> [Term]
> id: GO:0051299
> name: centrosome separation
> namespace: biological_process
> def: "The process in which duplicated centrosome components move away from each other. The centriole pair within each centrosome becomes part of a separate microtubule organizing center that nucleates a radial array of microtubules called an aster. The two asters move to opposite sides of the nucleus to form the two poles of the mitotic spindle." [GOC:ai] 
> is_a: GO:0022402 ! cell cycle process
> relationship: part_of GO:0007098 ! centrosome cycle

However, the existing definitions of `cell cycle` and `cell cycle process` in GO seem problematic in that they specify only replication and segregation of genetic material.

> [Term]
> id: GO:0007049
> name: cell cycle
> namespace: biological_process
> def: "The progression of biochemical and morphological phases and events that occur in a cell during successive cell replication or nuclear replication events. Canonically, the cell cycle comprises the replication and segregation of genetic material followed by the division of the cell, but in endocycles or syncytial cells nuclear replication or nuclear division may not be followed by cell division." [GOC:go_curators, GOC:mtg_cell_cycle]
> synonym: "cell-division cycle" EXACT []
> xref: Wikipedia:Cell_cycle
> is_a: GO:0009987 ! cellular process
> 
> [Term]
> id: GO:0022402
> name: cell cycle process
> namespace: biological_process
> def: "The cellular process that ensures successive accurate and complete genome replication and chromosome segregation." [GOC:isa_complete, GOC:mtg_cell_cycle]
> subset: gocheck_do_not_annotate
> intersection_of: GO:0009987 ! cellular process
> intersection_of: part_of GO:0007049 ! cell cycle

Looking at all 5 of the references you cited for your requested new term, I think they support saying that `basal body segregation` is a cell cycle process. Looking at the WikiPedia page for the cell cycle (https://en.wikipedia.org/wiki/Cell_cycle), I think that the problem is that the existing GO definitions were written quite a while ago without the benefit of some of the current knowledge about the relationship between the basal body and centrosome and the fact that there the basal body is not involved in chromosome segregation in all organisms.

=> **Thus, I think that the cell cycle terms should be broadened to include segregation of organelles, such as the basal body.**

The next follow-on change would be to broaden the term name (& also definition) of `centrosome cycle` so that it is the `centrosome/basal body cycle`. This is the type of change I've been thinking about for a while about how to bring the centrosome and basal body terms together in a coherent way. This doesn't cover everything, but I think this is a nice step forwards in that direction.

Summary:
- I like your proposed term almost as is, except is_a parentage
- change parentage of new term to [is_a 'cell cycle process']
- also add [part of 'centrosome cycle']
- change `centrosome cycle` to `centrosome/basal body cycle` => ?? new issue
- changes to definitions of `cell cycle` & `cell cycle process` => new issue

Additional oddity noticed
- it seems that `chromosome segregation` should be is_a `cell-cycle process` => new issue

**Comment by Achchuthan** [comment]
> > Name: ciliary pro-basal body maturation
> > Ontology: biological_process
> > Synonyms: flagellar pro-basal body maturation, flagellar probasal body maturation, pro-basal body maturation
> > Definition: A process that is carried out at the cellular level which results in the conversion of an immature and partially assembled ciliary pro-basal body into a mature basal body that is capable of nucleating a cilium.
> > is_a: GO:0032053 ! ciliary basal body organization
> > [RO:0002588 relation] RO:0002588: GO:0036064 ! ciliary basal body
> > Source: PMID:26862392, GOC:ach
> 
> I thought that it also seemed that we could say that this starts with a ciliary pro-basal body, and then it seemed that I could combine the statements you provided with the one I added and make it the logical definition, like this:
> 
> +intersection_of: GO:0016043 ! cellular component organization
> +intersection_of: results_in_assembly_of GO:0036064 ! ciliary basal body
> +intersection_of: starts_with GO:0120280 ! ciliary pro-basal body
> 
> Let me know if you agree with this or think any changes are needed.

Thanks a lot for these suggestions. They are fantastic and I agree with them.

**Comment by Achchuthan** [comment]
> > Accession: GO:xxxxxx
> > Name: ciliary basal body segregation
> > Ontology: biological_process
> > Synonyms: microtubule basal body segregation, ciliary basal body separation, microtubule basal body separation
> > Definition: The process in which the duplicated basal bodies migrate in pairs to the mitotic poles of the nucleus and results in equal distribution in the daughter cells. Ciliary basal body segregation ensures inheritance of the duplicated mitochondrial DNA to the two daughter cells in the Trypanosoma parasites.
> > is_a: GO:0032053 ! ciliary basal body organization
> > Source: PMID:1876188, PMID:4055898, PMID:26272611, PMID:26862392, PMID:27252853, GOC:ach
> 
> I don't want to hold up your term for any of the other changes I'd like to make to start bringing together the basal body and centrosome sides of this structure in a coherent way in GO. So for now, I'll go ahead and put it in as you requested except with parentage of is_a `cellular process` instead of what you suggested or what I currently think that I would like to change it to.
> 
Thanks a lot for providing this term without any delay.

> I would also welcome your input on my thoughts on bringing together the basal body and centrosome sides together in a more coherent way in GO. Do you think this works for organisms that don't use the basal body as a centrosome?
> 
I agree that terms that represent centrosome and basal body should be brought together in a more coherent way in GO, possibly under a common parentatge as basal body and centriole are same. I think it works for organisms that don't use the basal body as a centrosome as well. I actually wanted to request a term for ciliary basal body duplication as well. But, I found that the term for centriole replication covers ciliary basal body duplication as a synonym.
"Accession: GO:0007099
 Name: centriole replication
 Ontology: biological_process
 Synonyms: centriole duplication, ciliary basal body duplication, microtubule basal body duplication
 Alternate IDs: GO:0032054
 Definition: The cell cycle process in which a daughter centriole is formed perpendicular to an existing centriole. An immature centriole contains a ninefold radially symmetric array of single microtubules; mature centrioles consist of a radial array of nine microtubule triplets, doublets, or singlets depending upon the species and cell type. Duplicated centrioles also become the ciliary basal body in cells that form cilia during G0. Source: GOC:cilia, PMID:9889124, GOC:kmv, ISBN:0815316194"

> It doesn't seem quite right to me that this term would be a type of `ciliary basal body organization` since in GO we normally use `organization` to describe the assembly and/or arrangement of a structure, but not it's positioning or movement.
> 
I agree. Sorry, I should have put more thought into it.

> I looked at how we place some potentially relevant existing terms:
> 
>     * centrosome cycle (GO:0007098) [is_a 'cell cycle process']
> 
>     * * centrosome separation (GO:0051299) [is_a 'cell cycle process'] [part of 'centrosome cycle']
> 
>     * microtubule organizing center localization (GO:0061842)
> 
>     * * centrosome localization (GO:0051642) [is_a 'microtubule organizing center localization']
> 
>     * chromosome segregation (GO:0007059) [is_a 'cellular process']
> 
>     * * chromosome separation (GO:0051304) [is_a 'cell cycle process'] [part of 'chromosome segregation']
> 
> 
> The term that seems most comparable to the new term you are requesting is `centrosome separation`, which I like since these terms should match since the `centriole` and `basal body` are basically the same base structure with different modifications depending on which role they are playing, noting that basal bodies/centrosomes of some organisms or cell types have both roles, while others have only one or the other.
> 
> > [Term]
> > id: GO:0051299
> > name: centrosome separation
> > namespace: biological_process
> > def: "The process in which duplicated centrosome components move away from each other. The centriole pair within each centrosome becomes part of a separate microtubule organizing center that nucleates a radial array of microtubules called an aster. The two asters move to opposite sides of the nucleus to form the two poles of the mitotic spindle." [GOC:ai]
> > is_a: GO:0022402 ! cell cycle process
> > relationship: part_of GO:0007098 ! centrosome cycle
> 
> However, the existing definitions of `cell cycle` and `cell cycle process` in GO seem problematic in that they specify only replication and segregation of genetic material.
> 
> > [Term]
> > id: GO:0007049
> > name: cell cycle
> > namespace: biological_process
> > def: "The progression of biochemical and morphological phases and events that occur in a cell during successive cell replication or nuclear replication events. Canonically, the cell cycle comprises the replication and segregation of genetic material followed by the division of the cell, but in endocycles or syncytial cells nuclear replication or nuclear division may not be followed by cell division." [GOC:go_curators, GOC:mtg_cell_cycle]
> > synonym: "cell-division cycle" EXACT []
> > xref: Wikipedia:Cell_cycle
> > is_a: GO:0009987 ! cellular process
> > [Term]
> > id: GO:0022402
> > name: cell cycle process
> > namespace: biological_process
> > def: "The cellular process that ensures successive accurate and complete genome replication and chromosome segregation." [GOC:isa_complete, GOC:mtg_cell_cycle]
> > subset: gocheck_do_not_annotate
> > intersection_of: GO:0009987 ! cellular process
> > intersection_of: part_of GO:0007049 ! cell cycle
> 
> Looking at all 5 of the references you cited for your requested new term, I think they support saying that `basal body segregation` is a cell cycle process. Looking at the WikiPedia page for the cell cycle (https://en.wikipedia.org/wiki/Cell_cycle), I think that the problem is that the existing GO definitions were written quite a while ago without the benefit of some of the current knowledge about the relationship between the basal body and centrosome and the fact that there the basal body is not involved in chromosome segregation in all organisms.
> 
> => **Thus, I think that the cell cycle terms should be broadened to include segregation of organelles, such as the basal body.**
> 
I agree we should be broadening the definitions of cell cycle terms to reflect segregation of organelle and organellar genomes.
> The next follow-on change would be to broaden the term name (& also definition) of `centrosome cycle` so that it is the `centrosome/basal body cycle`. This is the type of change I've been thinking about for a while about how to bring the centrosome and basal body terms together in a coherent way. This doesn't cover everything, but I think this is a nice step forwards in that direction.
> 
> Summary:
> 
>     * I like your proposed term almost as is, except is_a parentage
> 
>     * change parentage of new term to [is_a 'cell cycle process']
> 
>     * also add [part of 'centrosome cycle']
> 
>     * change `centrosome cycle` to `centrosome/basal body cycle` => ?? new issue
> 
>     * changes to definitions of `cell cycle` & `cell cycle process` => new issue
> 
> 
> Additional oddity noticed
> 
>     * it seems that `chromosome segregation` should be is_a `cell-cycle process` => new issue

The suggested changes are really fantastic. Looking forward to these changes.

**Comment by krchristie** [comment]
@Achchuthan - Thanks for making it all the way through my previous comment and requests for feedback. I'm really glad to hear you agree with what I'm proposing. The papers you provided as references for the basal body segregation were really helpful!

**Comment by pgaudet** [comment]
This seems done
