### ISSUE TITLE
Odd parent - child relationships for binding MF terms

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#21211]
The immediate is_a children of GO MF term GO:0005488 “binding” include binding terms for alkenes, heterocyclic compounds, quaternary ammonium groups, and ice, making them siblings of GO:0036904 “small molecule binding” rather than is_a children of it.
Similarly, why are cargo receptor ligand activity, exogenous protein binding (GO:0140272), protein containing complex binding (GO:0044877)  siblings of GO:0005515 “protein binding” rather than is_a children of it?
@ukemi

**Comment by edwong57** [comment]
I'm not exactly sure what the questions/answers are. Are you asking/suggesting that some binding terms be made children of 'small molecule binding'? And that GO:0140272 and GO:0044877 be made children of GO:0005515? Should this be a larger discussion at a GO editor meeting?

**Comment by edwong57** [comment]
Okay, that makes more sense now. Thanks!

**Comment by edwong57** [comment]
protein-containing complex binding was updated during GO editor call to have 'binding' as a parent

**Comment by pgaudet** [comment]
Thanks @edwong57 
For reference, the PR is here: https://github.com/geneontology/go-ontology/pull/26153/commits/fd73dfde3323fde085b2bdcad9ea1e5931c40068

**Comment by edwong57** [comment]
2-aminoethylphosphonate binding was moved to be under 'small molecule binding'
GO:0000035 - acyl binding seems redundant with GO:0120227 - obsolete one?
amide binding and amine binding - keep under 'binding' because children underneath may or may not be 'small molecule' -- 'any low molecular weight, monomeric, non-encoded molecule'

**Comment by pgaudet** [comment]
Are you sure GO:0000035 - acyl binding is redundant with GO:0120227 acyl-CoA binding? 

I think some acyls exist without coA ?

**Comment by deustp01** [comment]
Definitely - "In chemistry, an acyl group is a moiety derived by the removal of one or more hydroxyl groups from an oxoacid, including inorganic acids. It contains a double-bonded oxygen atom and an organyl group ( R−C=O) or hydrogen in the case of formyl group ( H−C=O)." (Wikipedia) Some acyl groups can be esterified with coenzyme A.

**Comment by edwong57** [comment]
Cool. Thanks for pointing that out.

**Comment by edwong57** [comment]
Spreadsheet of changes - https://docs.google.com/spreadsheets/d/1hk-wrf0VWiZ_ngjqhUCBKCLVJWBYPkEwyzMcfnvGjao/edit?usp=sharing

**Comment by pgaudet** [comment]
Hi @edwong57 

kinetochore is classified as a 'cellular anatomical entity, you should remove is_a  'protein-containing complex binding'. 

In fact, since the logical definition of 'protein-containing complex binding' is 

  'protein-containing complex binding'
  and has primary input some 'protein-containing complex', 

we should not assert 'protein-containing complex binding' on any of the terms, this should be automatically inferred by the ontology. 

If the classification between cellular anatomical entity and protein-containing complex is incorrect, we should fix that in the CC, not in the 'binding' branch. 

Thanks, Pascale
