### ISSUE TITLE
nucleoside-triphosphatase activity (GO:0017111) = EC:3.6.1.15?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21232]
Currently there is:

id: GO:0017111
name: nucleoside-triphosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: a nucleoside triphosphate + H2O = nucleoside diphosphate + phosphate." [EC:3.6.1.15]
xref: EC:3.6.1.15
xref: RHEA:23680
is_a: GO:0016462 ! pyrophosphatase activity

Problem is that EC:3.6.1.15 seems to be for a specific enzyme (https://enzyme.expasy.org/EC/3.6.1.15), while the GO term is used as a grouping term for 6 is_a children with different EC/RHEA xrefs:
GO:0050333 thiamin-triphosphatase activity (EC 3.6.1.28 / RHEA 11744)
GO:0003774 motor activity
GO:0140603 ATP hydrolysis activity (RHEA 13065)
GO:0043273 CTPase activity
GO:0003924 GTPase activity (RHEA 19669, which maps back to EC:3.6.5.-)
GO:0050339 thymidine-triphosphatase activity (EC 3.6.1.39 / RHEA 19013)

So, is "GO:0017111 nucleoside-triphosphatase activity" meant to be broader than EC:3.6.1.15?  If so, then we should remove its EC:3.6.1.15 xref and create a new, separate term for EC:3.6.1.15 under GO:0017111.

Related point -  if GO:0003924 GTPase activity accurately maps back to EC:3.6.5.-, then maybe GO:0003924 needs moving to be a direct child of child of "hydrolase activity, acting on acid anhydrides (GO:0016817)" (= EC:3.6)??

**Comment by sjm41** [comment]
@hdrabkin Appreciate your thoughts on this one too.

**Comment by hdrabkin** [comment]
So the EC appears to just be mechanistic; the other GO terms are substrate specific. 
The EC parent of 3.6.1 
GO:0003924 GTPase activity (RHEA 19669, which maps back to)  ARGH!
19669 is the GTP specific substrate rexn; 
The EC 3.6.1 is only found in an obsoleted GO term which was a grouping term specific to GTP.

**Comment by sjm41** [comment]
@kaxelsen Can you provide any extra insights on the above?  Is https://enzyme.expasy.org/EC/3.6.1.15 meant to be for a specific enzyme/reaction (which is how the EC comments read), or more generic/mechanistic (which is how the EC name and  reaction read, and is how the xreffed GO term is used). Thanks.

**Comment by kaxelsen** [comment]
All EC numbers describe specific proteins. That means that if an EC number is associated with a generic reaction, it is because the enzyme it describes has a broad substrate specificity. Likewise, an EC number associated with a very specific reaction describes an enzyme with very narrow substrate specificity (or that will only see that one substrate in vivo). An EC number will never be a parent for another EC number, e.g. EC 1.1.1.1 associated with the reaction "an alcohol + NAD+ = an aldehyde + NADH + H+" is not the parent for all the EC numbers describing the oxidation of specific alcohols with NAD+, it is just an alcohol dehydrogenase that oxidises all alcohols.

So I think you should remove the EC number from GO:0017111, but you can keep the reaction

**Comment by sjm41** [comment]
Thanks @kaxelsen - makes sense!  It did look odd to see this GO term with a 4-digit EC xref having several children with other 4-digit EC xrefs.  As you both say, removing EC:3.6.1.15 from GO:0017111 will resolve and clarify things.

**Comment by sjm41** [comment]
@kaxelsen - one other thing, looking the EC parent here (and how it relates to GO structure):

EC:3.6.1.- is "Hydrolases -> Acting on acid anhydrides -> In phosphorus-containing anhydrides"
but there are also these 'sister' groupings:
EC:3.6.4.- Hydrolases -> Acting on acid anhydrides -> Acting on ATP; involved in cellular and subcellular movement
EC:3.6.5.-Hydrolases -> Acting on acid anhydrides -> Acting on GTP; involved in cellular and subcellular movement

Aren't ATP and GTP specific examples of "phosphorus-containing anhydrides"? Naively, that makes me think those ECs would be subclasses of 3.6.1.-?  But maybe it's the "involved in cellular and subcellular movement" aspect that distinguishes these classes and makes them a separate 3-digit grouping?  Do you mind clarifying that for me, thanks!

**Comment by hdrabkin** [comment]
GO:0017111 fixed; will close ticket; Other issue maybe goes in separate ticket?

**Comment by sjm41** [comment]
Thanks Harold.  Yes, I'll pursue my wider query about EC:3.6.-.- with Kristian elsewhere (if he doesn't answer here!) and make a new ticket if required.

**Comment by kaxelsen** [comment]
@sjm41 It is exactly as you say. The enzymes in EC 3.6.4- and EC 3.6.5.- are all involved in movement. Note that most of the EC numbers earlier classified here have been transferred to the new EC 5.6.-.- (Isomerases altering macromolecular conformation) since the movement involves conformational changes.
