### ISSUE TITLE
NTR: cardiolipin hydrolysis activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#21230]
Dear editors,
PubMed=28442572 describes the cardiolipin hydrolase activity of PNPLA8 UniProtKB/Q9NP80, a reaction that hydrolysis the fatty acid chains of cardiolipin  to release lysocardiolpin. The GO term GO:0035755 cardiolipin hydrolase activity has the following definition : "Catalysis of the hydrolysis of cardiolipin (1,3-bis(3-phosphatidyl)glycerol) to form phosphatidic acid (PA)" that does not fit to [Rhea:52812].
Should we modify the definition of  GO:0035755 or create a new term.

Thanks for your help.

**Comment by pgaudet** [comment]
Hi @lbreuza 

There are 3 annotations to GO:0035755 cardiolipin hydrolase activity
from PMID:17028579 and PMID:21397848 by @sylvainpoux 

* Those papers describe production of PA
* The entries do not have a RHEA (Q9VKD7 and Q8N2A8)
* The RHEA you mention, RHEA:52812, cross references proteins annotated to EC:3.1.1.4
* GO has multiple terms with cross references to EC:3.1.1.4, the most general being GO:0004623 phospholipase A2 activity, which links to RHEA:15801

This seems inconsistent - or do you suggest multiple activities for those proteins?

Thanks, Pascale

**Comment by pgaudet** [comment]
After discussing with @lbreuza - 
1. The entries have MANY activities, and hence many ECs. EC:3.1.1.4 does not correspond to RHEA:52812.
2. Changes: 
-def: "Catalysis of the hydrolysis of cardiolipin (1,3-bis(3-phosphatidyl)glycerol) to form phosphatidic acid (PA)." [GOC:sp, PMID:17028579, PMID:21397848]
+def: "Catalysis of the hydrolysis of cardiolipin (1,3-bis(3-phosphatidyl)glycerol), releasing phosphatidic acid (PA)." [GOC:sp, PMID:17028579, PMID:21397848, RHEA:52812]
+xref: RHEA:52812

Thanks, Pascale

**Comment by alanbridge** [comment]
I'm a bit confused, "Catalysis of the hydrolysis of cardiolipin (1,3-bis(3-phosphatidyl)glycerol) to form phosphatidic acid (PA)" does not correspond to RHEA:52812 - the latter hydrolyses cardiolipin releasing a fatty acid, not PA.

**Comment by lbreuza** [comment]
You're right...I missed that.

**Comment by alanbridge** [comment]
I don't think we have such a reaction in Rhea: https://www.rhea-db.org/rhea?query=CHEBI%3A62237+AND+CHEBI%3A15377

Could you ask Lucila Aimo to check the paper 17028579 and others that show this activity? The UniProt entry https://www.uniprot.org/uniprot/Q8N2A8 may need an update. 

All the best, Alan

**Comment by pgaudet** [comment]
(for information this is the original ticket where the term was requested: https://github.com/geneontology/go-ontology/issues/8492

**Comment by alanbridge** [comment]
NB: we do actually have a reaction for this in Rhea that was curated as part of the SwissLipids project but not yet made public:

RHEA:44884 a cardiolipin + H2O = 1,2-diacyl-sn-glycero-3-phospho-(1'-sn-glycerol) + a 1,2-diacyl-sn-glycero-3-phosphate + H+ 

i.e. 

CL + H2O => PG + PA

it's status is "pending" so needs looking at; the reason given in the Rhea curator tool is that there is actually no proof PG is produced - in fact, PG levels seem to drop. Hence the status as we were a little unsure of what the final products were.

**Comment by aimol** [comment]
Hi,
Thanks for including me in this discussion. I forgot that RHEA:44884 was pending, so good to come back to it. I understand your concern Alan, I think the fact that in PMID:17028579 PG levels seem to drop could be due to methodological causes, the labeling of the cardiolipin is not clearly explained in the paper.  I've checked the other references in RHEA:44884 and both PMID:4632675 and PMID:274715 seem to support this reaction, as well as PMID:4316362. In PMID:274715 they synthesized a spin-labeled cardiolipin stereospecifically labeled in the 3-(3-sn-phosphatidyl) end of the molecule and find that: Hydrolysis of spin-labeled cardiolipin provided spin-labeled phosphatidic acid only... The isolated phosphatidylglycerol was not appreciably spin labeled. And in PMID:4632675 they treat the cardiolipin with PLD and its products with other types of phospholipases in order to find out exactly where PLD would cut the cardiolipin molecule. They conclude that cardiolipin-specific phospholipase D has an absolute specificity for the bond between phosphate and the C-3’ of cardiolipin’s central glycerol. So, "Catalysis of the hydrolysis of cardiolipin (1,3-bis(3-phosphatidyl)glycerol) to form phosphatidic acid (PA)." would be correctly associated to PMID:17028579 imop. PMID:21397848 is from the same group as PMID:17028579, they do not focus on PLD enzymatic activity, they refer to PMID:17028579 to support the fact that PLD acts on cardiolipin producing PA, and their study focuses on the effects of PA signaling.
Regarding PMID:28442572, the enzymatic activity is different, RHEA:52812 is correct, but the enzyme is not a phospholipase D so the definition of GO:003575 would not apply in this case, a phospholipase A2 definition would be more appropriate.
I hope this helps.
Lucila

**Comment by alanbridge** [comment]
Hi, 

thanks Lucila great detective work - I always love it when we have to go back and look at biochemistry papers from the 70s! 

Pascale, maybe we could make the name more specific?

e.g. GO:0035755 cardiolipin hydrolase activity producing phosphatidate 

and maybe add a synonym?

GO:0035755 cardiolipin phospholipase D activity (?)

def: "Catalysis of the hydrolysis of cardiolipin (1,3-bis(3-phosphatidyl)glycerol), releasing phosphatidic acid (PA)."

or maybe base it on Rhea? 

def: "Catalysis of the reaction a cardiolipin + H2O = 1,2-diacyl-sn-glycero-3-phospho-(1'-sn-glycerol) + a 1,2-diacyl-sn-glycero-3-phosphate + H+"

xrefs:

PMID:274715, PMID:4632675, PMID:17028579 (these three are used in Rhea and characterize the activity pretty well)
+xref: RHEA:44884

@lbreuza @aimol could you update the PLD6 entry and related entries please?

Have a good day, Alan

**Comment by pgaudet** [comment]
After discussion with @aimol - @lbreuza and I propose to

1. change the definition of children of GO:0004620 phospholipase activity, for example for 

GO:0004623 phospholipase A2 activity
**Current def:** 
Catalysis of the reaction: phosphatidylcholine + H2O = 1-acylglycerophosphocholine + a carboxylate.

Change to something like: 
Hydrolysis of a glycerophospholipid, removing the fatty acid attached to the sn2-position. Substrates include phosphatidylcholine, phosphatidylethanolamine, choline plasmalogen and phosphatides, for example catalyzing the reaction: phosphatidylcholine + H2O = 1-acylglycerophosphocholine + a carboxylate.


2. Obsolete (or merge) GO:0035755 cardiolipin hydrolase activity since this represents a specific substrate of PLD.


@alanbridge @aimol please let us know what you think.

**Comment by pgaudet** [comment]
Moved to #21259 

No new term will be created here.

**Comment by alanbridge** [comment]
I think you need a 1:1 GO:Rhea mapping? I would not obsolete (or merge) GO:0035755 cardiolipin hydrolase, keep a Rhea for that GO.

**Comment by pgaudet** [comment]
> I think you need a 1:1 GO:Rhea mapping? I would not obsolete (or merge) GO:0035755 cardiolipin hydrolase, keep a Rhea for that GO.

I would like to have a sense for how many descendants of phospholipases we need to create in this case - any idea? 

I think we already recognize that we cannot have a 1:1 mapping between GO and RHEA, for example for ATPases, in RHEA it's a single reaction (AFAIK), while in GO we have more more granularity. 

Likewise for transporters, in GO we have decided to split ABC types and P-type, but in RHEA they are not systematically split. 

So I am not clear to what extent we can really align at 100%, although this is certainly desirable. - to be rediscussed...!

**Comment by alanbridge** [comment]
A few dozen reactions for these, maybe in the 100-200 bracket, considering all common phospholipid classes. We should be able to map these 1:1 to GO without any issues. All of these reactions should exist in Rhea already; I'm sure @hdrabkin can help too.

Each contains 2 fatty acyl chains, 1 phosphate-based head, and there are 4 ways to cut it - remove fatty acid at sn1, and/or sn2, or cut between glycerol and phosphate, or cut between the head and the phosphate. PLA, PLB, PLC, PLD. 

For the GO term GO:0035755 cardiolipin hydrolase there really is no need to merge nor obsolete it. It maps 1:1 to a Rhea with no issues at all. 

The ATPase question is a little different - here we are talking about small molecule metabolism which is mappable 1:1.
