### ISSUE TITLE
NTR: integral to cytoplasmic side of mitochondrial outer membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21253]
integral to cytoplasmic side of mitochondrial outer membrane

Def
A component of the mitochondrial outer membrane consisting of the gene products having at least some part of their peptide sequence embedded in the hydrophobic region of the membrane, and  at least some part of their peptide sequence in the cytoplasm.

child of
GO:0032473 | cytoplasmic side of mitochondrial outer membrane 
AND
GO:0031307 | integral component of mitochondrial outer membrane

ref
PMID:33483504

(not to self ~mdm10~ & emr1)

**Comment by raymond91125** [comment]
![image](https://user-images.githubusercontent.com/619520/140434413-37dfb0c7-d718-408f-b555-2bbd2446f973.png)

Emr1 is a single pass membrane-spanning protein that inserts in mitochondrial external membrane. Thus GO:0031307 | integral component of mitochondrial outer membrane makes sense.

But the use of GO:0032473 does not seem right.  GO:0032473 | cytoplasmic side of mitochondrial outer membrane. DEF The external (cytoplasmic) face of the mitochondrial outer membrane, with Comment: In GO, 'external side' still refers to part of the membrane and does not refer to components beyond (outside of) the membrane.

I don't know of way to specify the peri-mitochrondrial-outer-membrane space since it is is unbounded.

**Comment by ValWood** [comment]
I don't completely understand what this comment means:
In GO, 'external side' still refers to part of the membrane and does not refer to components beyond (outside of) the membrane.

I presume anything that is membrane attached *is* included?

**Comment by raymond91125** [comment]
"and at least some part of their peptide sequence in the cytoplasm." -- This part of your proposal I think does not fit the definition of GO:0032473. GO:0031307 already covers the part about being in the mito outer membrane.
I just don't know of a proper way to specify the cytoplasmic protrusion. @pgaudet Do you have a suggestion? Thanks.

**Comment by ValWood** [comment]
for emr1 ""and at least some part of their peptide sequence in the cytoplasm." is true. It has a cytoplasmic domain?

**Comment by raymond91125** [comment]
@ValWood It seems that your proposed definition is for a peptide (sequence) rather than a CC per se.

**Comment by ValWood** [comment]
Agreed. We need a better way to represent this (the same problem applies to all of these types of term), but I can use the 2 separate terms, as both are true based on the defs.

**Comment by raymond91125** [comment]
@ValWood Thanks. I think CC is about compartments. We may need something else to model topology (if there isn't one).
