### ISSUE TITLE
primary active transmembrane transporter activity (GO:0015399) & EC:7.-.-.-

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21274]
EC:7.-.-.- (translocases - https://enzyme.expasy.org/EC/7.-.-.-) is currently an xref on:

id: GO:0005215
name: transporter activity
def: "Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells." [GOC:ai, GOC:dgf]
xref: EC:7.-.-.-
is_a: GO:0003674 ! molecular_function

But that GO term covers much more (such as passive transporters, channels) than the enzymatic translocase (EC:7) class, so should be removed.

But it looks like it might be appropriate to add EC:7.-.-.- to this term:
id: GO:0015399
name: primary active transmembrane transporter activity
def: "Enables the transfer of a solute from one side of a membrane to the other, up the solute's concentration gradient, by binding the solute and undergoing a series of conformational changes. Transport works equally well in either direction and is powered by a primary energy source, directly using ATP. Primary energy sources known to be coupled to transport are chemical, electrical and solar sources." [GOC:mtg_transport, ISBN:0815340729, TC:3.-.-.-.-]
synonym: "primary active transporter" RELATED []
xref: TC:3
is_a: GO:0022804 ! active transmembrane transporter activity

Further:
- "directly using ATP" should be removed from the GO:0015399 definition, as the next sentence lists alternative energy sources (and the child terms include non-ATP sources)
- could/should GO:0015399 have the additional parent of 'catalytic activity' (GO:0003824)?

What do you think @kaxelsen ?

**Comment by sjm41** [comment]
@pgaudet I'd forgotten about this ticket....  I think all my points still stand?

**Comment by sjm41** [comment]
Hi @pgaudet Thanks for sorting out the EC:7 xref here.

There were two more suggestions at the end of my original post - what do you think of those:

- "directly using ATP" should be removed from the GO:0015399 definition, as the next sentence lists alternative energy sources (and the child terms include non-ATP sources)

- could/should GO:0015399 have the additional parent of 'catalytic activity' (GO:0003824)?

**Comment by pgaudet** [comment]
> "directly using ATP" should be removed from the GO:0015399 definition, as the next sentence lists alternative energy sources (and the child terms include non-ATP sources)

Thanks, I changed the definition to "Enables the transfer of a solute from one side of a membrane to the other, up the solute's concentration gradient, by binding the solute and undergoing a series of conformational changes. Transport works equally well in either direction and is powered by a primary energy source. Primary energy sources known to be coupled to transport are chemical such as ATP hydrolysis, redox energy and photon energy."

> could/should GO:0015399 have the additional parent of 'catalytic activity' (GO:0003824)?

No, because of the child GO:0015454 light-driven active transmembrane transporter activity. I added the following logical definitions to children terms: 

**GO:0015452 'methyl transfer-driven active transmembrane transporter activity'**
'primary active transmembrane transporter activity'
and 'has part' some 'methyltransferase activity'

**GO:0015451 'decarboxylation-driven active transmembrane transporter activity'**
'primary active transmembrane transporter activity'
and 'has part' some 'carboxy-lyase activity'

**GO:0015453 'oxidoreduction-driven active transmembrane transporter activity'**
'primary active transmembrane transporter activity'
and 'has part' some 'oxidoreductase activity'

GO:0042626
already had this logical definition: 
'primary active transmembrane transporter activity'
 and ('has part' some 'ATP hydrolysis activity')

**Comment by sjm41** [comment]
Thanks again!

Though I see that the definition of "GO:0015454 light-driven active transmembrane transporter activity" begins with "Primary active transport of a solute across a membrane, driven by light. Primary active transport is catalysis of the transport of a solute across a membrane...", which suggests that this term could legitimately have the 'catalytic activity parent' (catalysis driven by photon energy)?? 

(There doesn't appear to be any annotations to this term, but maybe there should be https://tcdb.org/search/result.php?tc=3.E)

**Comment by pgaudet** [comment]
Added 'has part' catalytic activity' to 'primary active transporter activity'

**Comment by sjm41** [comment]
(see #23876 for resolution of GO:0015454 issue)
