### ISSUE TITLE
inconsistency virion / virion component vs cytosol / cytosolic part

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#21370]
I don't get it. You have obsoleted GO:0019012 virion in favor of GO:0044423 virion component but ask it should not be used. OTOH you keep cytosol. Can you please explain?

**Comment by rwst** [comment]
I cannot find a ticket where obsoletion of GO:0019012 virion is discussed. What is the reason for this obsoletion?

**Comment by pgaudet** [comment]
> I cannot find a ticket where obsoletion of GO:0019012 virion is discussed. What is the reason for this obsoletion?

Virion not obsoleted, it was merged into 'virion component', see 'https://github.com/geneontology/go-ontology/issues/21191.  In the ontology merged terms look like obsoletes: 

<img width="548" alt="image" src="https://user-images.githubusercontent.com/4782928/116703411-8bddf800-a9ca-11eb-8a32-7c1602dada7e.png">


but you can tell it's a merge because its ID is a secondary ID of the term in which it has been merged, here  GO:0044423 
virion component. 

Does that answer your concerns?

**Comment by rwst** [comment]
Yes, to a certain extent, thanks.
