### ISSUE TITLE
NTR: appressorium-mediated entry into host

### ISSUE THREAD

**Issue by Achchuthan** [geneontology/go-ontology#21505]
Hi,

Can I request the following new term please?

Accession: GO:xxxxxx
Name: appressorium-mediated entry into host
Ontology: biological_process
Synonyms: appressorium-mediated host invasion, appressorium-mediated host penetration, appressorium-mediated invasion into host, appressorium-mediated penetration into host
Definition: Penetration by a symbiont into a host organism via appressorium. The host is defined as the larger of the organisms involved in a symbiotic interaction.
is_a: GO:0044409 ! entry into host
Source: PMID:14731267, PMID:22589729, GOC:ach

Thanks & best wishes,
Achchuthan

**Comment by ValWood** [comment]
Hi AGO:0075016    JSON
appressorium formation
Biological Process

Definition (GO:0075016 GONUTS page)
The process in which a swollen, flattened portion of a symbiont filament is formed on or near its host organism, to adhere to and for the purpose of penetrating the host surface.GO:0075016    JSON
appressorium formation
Biological Process

Definition (GO:0075016 GONUTS page)
The process in which a swollen, flattened portion of a symbiont filament is formed on or near its host organism, to adhere to and for the purpose of penetrating the host surface.ch,

this term already exists: (it is under  GO:0075015   formation of infection structure, a child of entry into host)

GO:0075016    appressorium formation
The process in which a swollen, flattened portion of a symbiont filament is formed on or near its host organism, to adhere to and for the purpose of penetrating the host surface.

**Comment by pgaudet** [comment]
We also have "GO:0075001 adhesion of symbiont appressorium to host". 

Based on https://en.wikipedia.org/wiki/Appressorium, it looks like appressorium formation, adhesion to host and penetration are coupled processes, or even substeps of the same process. Should we  consider having a single term that describes the entire process? 

Thanks, Pascale

**Comment by ValWood** [comment]
I think a single process would do . I 'm not sure that we know the individual molecular steps.

**Comment by ValWood** [comment]
The appressorium forms a penetration peg, and we also have this unused term under
GO:0075015    formation of infection structure
GO:0075053    penetration peg formation
This term is not used....
Which species form penetration pegs? 
Is this fungal specific? @mgiglio99

**Comment by krchristie** [comment]
We have quite a number of appresorium terms:
* GO:0075003 - adhesion of symbiont appressorium to host
* GO:0075016 - appressorium formation
* GO:0075017 - regulation of appressorium formation
* GO:0075018 - positive regulation of appressorium formation
* GO:0075019 - negative regulation of appressorium formation
* GO:0075025 - initiation of appressorium formation
* GO:0075026 - regulation of appressorium initiation
* GO:0075027 - positive regulation of appressorium initiation
* GO:0075028 - negative regulation of appressorium initiation
* GO:0075029 - formation of appressorium germ tube hook structure
* GO:0075030 - modulation of formation of symbiont germ tube hook structure for appressorium development
* GO:0075031 - positive regulation of formation of symbiont germ tube hook structure for appressorium development
* GO:0075032 - negative regulation of formation of symbiont germ tube hook structure for appressorium development
* GO:0075033 - appressorium septum formation
* GO:0075034 - nuclear division involved in appressorium formation
* GO:0075035 - appressorium maturation
* GO:0075036 - regulation of appressorium maturation
* GO:0075037 - positive regulation of appressorium maturation
* GO:0075038 - negative regulation of appressorium maturation
* GO:0075039 - establishment of turgor in appressorium
* GO:0075040 - regulation of establishment of turgor in appressorium
* GO:0075041 - positive regulation of establishment of turgor in appressorium
* GO:0075042 - negative regulation of establishment of turgor in appressorium
* GO:0075043 - melanization of appressorium wall

and also three other terms that mention "appressorium" in their definition:
* GO:0075226 - encysted zoospore germination [*uses mispelled version 'appresorium']
* GO:0075201 - penetration hypha formation
* GO:0120164 - conidium germination

**Comment by Achchuthan** [comment]
I think we need a separate term for appressorium formation (GO:0075016). As described in PMID:22589729, some of the mutants do not affect appressorium formation, but results in defective appressorium mediated penetration. But, I think GO:0075001 (adhesion of symbiont appressorium to host) could be combined with this requested term (appressorium-mediated entry into host). Otherwise, I am wondering whether it would be possible to keep all these as separate terms and create an overall parent term to cover all these terms, if this makes sense?

Thanks,
Achchuthan

**Comment by krchristie** [comment]
Hi @Achchuthan 

Unfortunately, it is quite hard to see the part_of relationships, but looking through the relationships,  the term "appressorium formation" is already meant to be the general term. It has these EXACT synonyms:
* "appressorium formation for entry into host, on or near host" EXACT []
* "appressorium formation on or near host" RELATED []
* "formation of an appressorium by symbiont on or near host" EXACT []

and **is_a: GO:0075015 ! formation of infection structure**


Here are the relationships I see between the non-regulation terms, where I am using dashes to indicate nesting of terms:


-- **GO:0075016 - appressorium formation**

--- **GO:0075035 - appressorium maturation** [part_of 'appressorium formation']
---- **GO:0075039 - establishment of turgor in appressorium** [part_of 'appresorium maturation']
---- **GO:0075043 - melanization of appressorium wall** [SubClassOf 'appresorium maturation'] ?? _should this be part_of instead of is_a_ ??

--- **GO:0075033 - appressorium septum formation** [part_of 'appressorium formation']

--- **GO:0075025 - initiation of appressorium formation** [part_of 'appressorium formation']
---- **GO:0075029 - formation of appressorium germ tube hook structure** [part_of 'initiation of appressorium formation]

--- **GO:0075034 - nuclear division involved in appressorium formation** [part_of 'appressorium formation']



Then this term does not seem to be placed in the part_of relationship structure with any of the other appressorium terms. Where should this term be placed in relationship to the rest of the terms?
- **GO:0075003 - adhesion of symbiont appressorium to host** == request

**Comment by ValWood** [comment]
There are way too many terms here, that were added with no use case or reference.

we should definitely obsolete 
GO:0075033 - appressorium septum formation
GO:0075034 - nuclear division involved in appressorium formation
(unused) 

These are just describing the division resulting in the specialized cell type. They are too specific.

**Comment by ValWood** [comment]
>But, I think GO:0075001 (adhesion of symbiont appressorium to host) could be combined with this requested term (appressorium-mediated entry into host).

Note that this is a term pending obsoletion because it represents a MF in the BP ontology.

**Comment by ValWood** [comment]
Note that the multi-organism group are aware of problems in the  penetration of host branch,as part of the multi-species branch revisions:
https://github.com/geneontology/go-ontology/issues/18465#issuecomment-567712520
but we haven't got to it yet.

**Comment by Achchuthan** [comment]
> There are way too many terms here, that were added with no use case or reference.
> 
> we should definitely obsolete
> GO:0075033 - appressorium septum formation
> GO:0075034 - nuclear division involved in appressorium formation
> (unused)
> 
> These are just describing the division resulting in the specialized cell type. They are too specific.

I agree. I will never be using these terms in my annotations.

**Comment by krchristie** [comment]
> * As of now, I think "GO:0075003 - adhesion of symbiont appressorium to host" can only be placed in this relationship: is_a "adhesion of symbiont infection structure to host". This is already added to the GO term.
 
Actually, I think **"GO:0075003 - adhesion of symbiont appressorium to host"** could stay as is_a "adhesion of symbiont infection structure to host" and also be part_of "appressorium formation", which seems like it should be since it is defined as what keeps the appressorium attached to the host, so it seems like it should have some relationship to "appressorium formation". 

Here is our current definition of this term:

**"GO:0075003 - adhesion of symbiont appressorium to host"**
**Def:** The attachment of an appressorium of the symbiont to its host via adhesion molecules. The host is defined as the larger of the organisms involved in a symbiotic interaction.

> * I am wondering whether we should leave "GO:0075003 - adhesion of symbiont appressorium to host"  as it is or whether we should broaden the GO term/ definition/ synonyms for "Appressorium formation" (GO:0075016) to include adhesion and penetration. If we do so, "appressorium formation" will no longer be a is_a "formation of infection structure".

My knowledge of fungal infection structures is quite old from a really interesting fungal genetics meeting at least a decade ago. I took a quick look at Wikipedia: https://en.wikipedia.org/wiki/Appressorium and here are some select quotes from the **Appressorium** page:

> Following spore attachment and germination on the host surface, the emerging germ tube perceives physical cues such as surface hardness and hydrophobicity, as well as chemical signals including wax monomers that trigger appressorium formation. 

> Appressorium formation begins when the tip of the germ tube ceases polar growth, hooks, and begins to swell.

> **Formation**
> The attachment of a fungal spore on the surface of the host plant is the first critical step of infection. Once the spore is hydrated, an adhesive mucilage is released from its tip.[3] During germination, mucilaginous substances continue to be extruded at the tips of the germ tube, which are essential for germ tube attachment and appressorium formation.[4]


I am wondering what is supposed to be part of "appressorium formation", abd whether are steps that are part of infection that occur before or after "appressorium formation".

>     * I agree that GO:0075043 - melanization of appressorium wall should be 'part_of' instead of 'is_a'.

great.

**Comment by Achchuthan** [comment]
> > * As of now, I think "GO:0075003 - adhesion of symbiont appressorium to host" can only be placed in this relationship: is_a "adhesion of symbiont infection structure to host". This is already added to the GO term.
> 
> Actually, I think **"GO:0075003 - adhesion of symbiont appressorium to host"** could stay as is_a "adhesion of symbiont infection structure to host" and also be part_of "appressorium formation", which seems like it should be since it is defined as what keeps the appressorium attached to the host, so it seems like it should have some relationship to "appressorium formation".
> 
Sounds good to me!

> Here is our current definition of this term:
> 
> **"GO:0075003 - adhesion of symbiont appressorium to host"**
> **Def:** The attachment of an appressorium of the symbiont to its host via adhesion molecules. The host is defined as the larger of the organisms involved in a symbiotic interaction.
> 
> > * I am wondering whether we should leave "GO:0075003 - adhesion of symbiont appressorium to host"  as it is or whether we should broaden the GO term/ definition/ synonyms for "Appressorium formation" (GO:0075016) to include adhesion and penetration. If we do so, "appressorium formation" will no longer be a is_a "formation of infection structure".
> 
> My knowledge of fungal infection structures is quite old from a really interesting fungal genetics meeting at least a decade ago. I took a quick look at Wikipedia: https://en.wikipedia.org/wiki/Appressorium and here are some select quotes from the **Appressorium** page:
> 
> > Following spore attachment and germination on the host surface, the emerging germ tube perceives physical cues such as surface hardness and hydrophobicity, as well as chemical signals including wax monomers that trigger appressorium formation.
> 
> > Appressorium formation begins when the tip of the germ tube ceases polar growth, hooks, and begins to swell.
> 
> > **Formation**
> > The attachment of a fungal spore on the surface of the host plant is the first critical step of infection. Once the spore is hydrated, an adhesive mucilage is released from its tip.[3] During germination, mucilaginous substances continue to be extruded at the tips of the germ tube, which are essential for germ tube attachment and appressorium formation.[4]
> 
> I am wondering what is supposed to be part of "appressorium formation", abd whether are steps that are part of infection that occur before or after "appressorium formation".
> 
It looks to me that "appressorium formation" is part of the infection process and infection process definitely starts before the formation of appressorium and continues during and after appressorium formation. I think that the infection process starts when the spores are attached to the host surface. The attachment of spore and germination precedes appressorium formation. As the appressorium matures, it becomes firmly attached to the host. So, you are right that "adhesion of symbiont appressorium to host" (GO:0075003) is part_of "appressorium formation". The infection process continues after appressorium formation with penetration of appressorium into the host. I'm not sure whether I have answered your question.

**Comment by Achchuthan** [comment]
Hi @krchristie, @ValWood, @pgaudet 

A gentle reminder about this issue? Do we have any further developments regarding merging of appressorium-related terms and incorporating penetration into the new merged term?

Thanks,
Achchuthan

**Comment by krchristie** [comment]
> Hi @krchristie, @ValWood, @pgaudet
> 
> A gentle reminder about this issue? Do we have any further developments regarding merging of appressorium-related terms and incorporating penetration into the new merged term?
> 
> Thanks,
> Achchuthan

Hi @Achchuthan - Thanks for the reminder. I'm doing ontology work this week, so I'll put this on my priority list to work on again. Today, I'll go through the ticket and figure out what has been decided and what questions remain.

Thanks,

-Karen

**Comment by Achchuthan** [comment]
Hi @krchristie, 
Sounds good! Thanks!!
Best wishes,
Achchuthan

**Comment by krchristie** [comment]
This is what I see that we've agreed to do:

- [ ] add new term for "**appressorium-mediated entry into host**" per stanza in your initial request
- [ ] change "**melanization of appressorium wall**" from IS_A "**appressorium maturation**" to PART_OF
-- Since this left "**melanization of appressorium wall**" without an IS_A parent, I chose "**pigment accumulation**" as an is_a parent
- [ ] added PART_OF "**appresorium formation**" parentage to "**adhesion of symbiont appressorium to host during symbiotic interaction**"
- [ ] fix spelling error of "appresorium" in definition of "**encysted zoospore germination**"
- [ ] Obsolete these two terms:
-- GO:0075033 - appressorium septum formation
-- GO:0075034 - nuclear division involved in appressorium formation

I've done the first 4 items, and will send out obsoletion emails tomorrow.

Let me know if you see anything I missed.

**Comment by Achchuthan** [comment]
Hi @krchristie.
All of these sounds great! I don't think you have missed anything from the above discussion. Thanks a lot for taking your time to work on these changes.
BW,
Achchuthan

**Comment by krchristie** [comment]
> Hi @krchristie.
> All of these sounds great! I don't think you have missed anything from the above discussion. Thanks a lot for taking your time to work on these changes.
> BW,
> Achchuthan

Hi @Achchuthan - sorry it took so long to get back to this. The discussion got complicated enough that it ceased to be a quick ticket to go through and figure out all the parts to be done.

I've opened a new ticket for the obsoletions: **Proposal to obsolete two overly specific appressorium formation terms** #21923

Since everything else we agreed on in this ticket, I'm going to close this ticket. 

Thanks,

-Karen

**Comment by Achchuthan** [comment]
Hi @krchristie,
I completely understand! This was not a straightforward issue and had several action items. Even, this issue slipped out of mind for some time.
Thanks & best wishes,
Achchuthan
