### ISSUE TITLE
Obsolete regulation of nucleosome density (GO:0060303)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21503]
**Term to be merged: Provide GO ID and term label**

regulation of nucleosome density (GO:0060303)

**Which term do you propose this term merge into? Provide GO ID and term label**

nucleosome organization,
although some  annotation might be better as "nucleosome positioning" or nucleosome assembly/disassembly so perhaps obsoletion is better?

**Reason for merge**
but regulation of  nucleosome density is more of an observation (change in nucleosome positions) than a process

**Any other information**
I requested this term, back in the day, it seems very phenotype-y (these are 'affecting nucleosome density')
https://github.com/geneontology/go-ontology/issues/5189
but no longer use it for the publication it was requested for
https://www.pombase.org/reference/PMID:17446861

Most of the  EXP annotations are PomBase 20/30
others 
SGD 8
FlyBAse 1
Agbase 1

@colinlog  does this sound OK to you?

**Comment by colinlog** [comment]
Dear Val, Pascale and the other readers,
From a process-centric view, there is the nucleosome level and the polynucleosome array level (the 'real' stuff eukaryotic nuclear chromatin is made of). Both are part of the process chromatin organization. These processes are driven by activities that are often enzymes (ATPases, histone modifiers) but can be 'binders/readers' of the (poly-)nucleosome.
* Nucleosome level:
- Post- or co-replication nucleosome (dis)assembly (product is histone octamer with 147 bp of DNA)
- Post or co-transcriptional (dis)assembly, which is itself part of transcription initiation, promoter escape or transcription elongation 
- Mono-nucleosome remodelling which is itself to be subdivided into
> moving the nucleosome along the DNA (ATP-dependent activity). At gene enhancers, silencers and promoters but also inside transcribed regions to modulate splicing or transcription termination and probably also for DNA replication, repair and recombination as well as (sister-)chromatid cohesion, extrusion.
> changing the nucleosome by replacing a canonical H2A, H2B or H3 histone (there no H4 variants known??) with a variant isoform (H2A.Z and other H2A variants, H3.3, CENP-A). Here there isalso a distinction between single histone insertion (SWR1 ATPase) or H2A-H2B dimer exchange. 
> post-translational modification of histones, sometime in the nucleosome, sometimes when the histone is in the cytoplasm or nucleosoplasm. There are more than 250 of these histone modifications. This may also include histone tail clipping.
* Polynucleosome level:
- Chromatin folding processes (eg H416ac is known to strongly modulate chromatin compaction at the 'inter-nucleosoma' contact level)
> polynucleosome 30 nm fibre topology modulation one-start and two-start fibres (two-start is apparently the most common !!! and affected by many chromatin-binding proteins)
> Nucleosome spacing (the activities are known and are ISWI or CHD ATPase enzyme activities) that makes nucleosomal arrays with rather precise linker lengths between adjacent nucleosomes that then have specific folding options.
- polynucleosome binding via protein and/or(methylated) DNA binding leading to specific polynucleosome topologies that are stabilized into euchromatin or heterochromatin conformations.

Despite the appearances, the above may not be comprehensive. Rather, it is a minimum. My thoughts are that we should refactor this part of the ontology holistically and straight away organise the BPs hierarchically, with MFs that underlie them. The logic being that MFs are protein activity-centric while the processes should be process product-centered. 

All this to say that it may be most effective to consider the whole matter of chromatin organization of rather than tinkering/obsoleting with individual terms and merging them with an upper term, which would overly simplify the GO and render future annotation options ambiguous.

**Comment by ValWood** [comment]
I removed the PomBase annotations to prevent propagation. These were just a phenotype, and they all had more informative annotations. Introducing a "regulation of quality" term (i.e. density), doesn't seem to be helpful.

So I'll add 'transcription' and 'low priority' labels

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0060303 regulation of nucleosome density. The reason for obsoletion is that this represents a readout and in some cases a phenotype, and the term can be misconstrued for chromatin compaction. 

There are 11 EXP annotations: https://docs.google.com/spreadsheets/d/1HV2nb-8U7b8b9b85pmcCF9m3Uw3z1zMPSTOknPwVLc4/edit#gid=0

1 FlyBase
9 SGD

Suggestions for reannotations have been made, including to a new term 'GO:0140750 nucleosome array spacer activity'. 

There are no mappings; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/21503

Thanks, Pascale
