### ISSUE TITLE
NTR: mitochondrion proliferation

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#21537]
Hi 
It seems like the role of mitochondria in the cell is not well described in GO.

Their role in apoptosis is captured and yet the idea of increasing the activity of a mitochondria or increasing the number of mitochondria is not.

I would like to see 2 new parent terms created (and their regulation child terms) (I have created another ticket for the other term. https://github.com/geneontology/go-ontology/issues/21538)

* **Suggested term label:mitochondrial proliferation**
* **Definition (free text)**
The multiplication of mitochondria, resulting in the expansion of the number of mitochondria within a cell. 

*with the note that **This term should not be used directly**

* **Reference, in format PMID:28301064**

* **Parent term(s)**
possibly  GO:0007005 mitochondrion organization

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Suggested term label: regulation of mitochondrial proliferation**
* **Definition (free text)**
Any process that modulates the rate, frequency or extent of mitochondrial proliferation within a cell.

*with the note that **The use of this term should be limited to the occassions where the number of mitochondria changes within a cell rather than changes associated with cell proliferation or apoptosis**

* **Suggested term label: positive regulation of mitochondrial proliferation**
* **Definition (free text)**
Any process that increases the rate, frequency or extent of mitochondrial proliferation which that leads to an increase in the number of mitochondria in a cell.

*with the note that **The use of this term should be limited to the occassions where the number of mitochondria increased within a cell rather than an increase due to a cell proliferation**

* **Suggested term label: negative regulation of mitochondrial proliferation**
* **Definition (free text)**
Any process that decrease the rate, frequency or extent of mitochondrial proliferation.

*with the note that **The use of this term should not be used when the regulation is associated with apoptotic processes where child terms of  GO:0008637 apoptotic mitochondrial changes may be more relevant**

* **Justification**
https://pubmed.ncbi.nlm.nih.gov/28301064/ describes: The activation of this PGC-1α - NRF -Tfam pathway leads to synthesis of mitochondrial DNA and proteins and generation of new mitochondria. While the proteins associated with this pathway could be annotated as GO:0090297 positive regulation of mitochondrial DNA replication this term is not linked to the key aspect of why there an increase in mitochondrial DNA replication is occuring, ie because the cell is increasing the number of mitochondria.

Another option might be to use  GO:0090141 positive regulation of mitochondrial fission, note that GO:0000266 mitochondrial fission has the related synonym: mitochondrial proliferation. But again while the mitochondrion will divide, presumably by fission the key aspect of regulating the number of mitochondria is missed. The annotation of proteins involved in the regulation of fission should surely be limited to those that are closely related to the process, not to proteins in the PGC-1α - NRF -Tfam pathway.

Thanks Ruth

**Comment by ValWood** [comment]
Hi Ruth

mitochondrial proliferation sounds like a phenotype, and it is used in multiple ways:

It is the outcome of the process of "increased mitochondrial fission" (creation of more smaller mitochondria) or increased 'mitochondrion biogenesis" increase in the number of new mitochondria (we do not have this term, this would be valid as it would keep the distinction).


Proliferation could be a related synonym for these  terms.

**Comment by RLovering** [comment]
I disagree with this being a 'phenotype'. 

I think mitochondrial fission is equivalent to the cell term 'cytokinesis'. It doesn't really capture how some cells need more mitochondria than other cells and that therefore the number of mitochondria / cell needs to be regulated. 

I would be happy with the term 'mitochondrion biogenesis'. However as mitochondria have their own DNA and as such are like mini-cells I am not sure that the definition: A cellular process that results in the biosynthesis of constituent macromolecules, assembly, and arrangement of constituent parts of mitochondrion. Really describes the process. But mitochondrial biogenesis does seems to be an accepted term, the phrase identifies >90,000 articles in PMC eg:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3883043/  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7205802/. So this seems to be the easiest option.

BTW I was looking at the regulation of cell division and regulation of cytokinesis and I think these definitions need to be edited to be in line with the parent terms: 
regulation definitions: 
* reg cell division: Any process that modulates the frequency, rate or extent of the physical partitioning and separation of a cell into daughter cells. 
* reg cytokinesis: Any process that modulates the frequency, rate or extent of the division of the cytoplasm of a cell and its **separation** into two daughter cells. 

Term definitions:
* cell division: The process resulting in division and partitioning of components of a cell to form more cells; **may or may not be accompanied by the physical separation of a cell into distinct, individually membrane-bounded daughter cells**.
* cytokinesis: The division of the cytoplasm and the plasma membrane of a cell and its **partitioning** into two daughter cells. 

Thanks for looking at this request so quickly

Ruth

**Comment by ValWood** [comment]
A bit more infomation/clarification.

In single-celled organisms (and presumably most cells), during interphase the mitochondria fuse together into a very small number of large mitochondria. There is no mechanism for partitioning, so at mitosis the mitochondria undergo lots of fission to create a large number of smaller mitochondria. This ensures that at cell division each cell is likely to receive some mitochondria at division (and probably also so that the mitochondria are not ruptured by the cleavage machinery. So the 'process which occurs at  the end of interphase could be called 'proliferation' because it results in more mitochondria. 

 After division, during the next interphase, the number of mitochondria will need to increase as the cell doubles its contents. This process is relatively unstudied at the molecular level which is why we currently have no term for this.  Will involve making/ moving  membrane material via ERMES?, DNA replication and translating/importing proteins (Both nuclear and mitochondrial encoded).

So, 'proliferation'  could refer to 2 distinct processes, one of growth, and one of division (it's just the observation that there are a larger *number* of mitochondria). I guess 'proliferation' could be a parent of biogenesis and fission if it is useful. 


mitochondrial DNA replication (GO:0006264) 
mitochondrial translation (GO:0032543)
protein import into mitochondrial matrix (GO:0030150)
other import terms
would need to be placed under the biogenesis term.

**Comment by ValWood** [comment]
I'm only commenting on this because I fairly recently reviewed all of our mitochondrial annotation, and I just wanted to make sure that any changes to the structure are consistent with
the existing annotation.

**Comment by RLovering** [comment]
Hi Val

as always your insight is so helpful. There is also the aspect of some cells requiring more mitochondria as they differentiate or are activated maybe to enable them to perform their new role.

What would be nice about what you have suggested above is that there would be a grouping term which might be useful when proteins required for these specific processes are all coregulated and therefore the overall goal of mitochondrial DNA replication is seen.

**Comment by ValWood** [comment]
I was just going to comment on this ticket again. I think the proliferation term you suggested will be fine in this context. I think I have an aversion to 'proliferation because of all the problems the "cell proliferation" terms caused for single-celled organisms, but here it is a cell level process, so it's fine!

**Comment by pgaudet** [comment]
Thanks to both for the useful discussion.

@RLovering Do you need the regulation terms? Seems like mitochondrial proliferation would be sufficient to capture the paper you mention?

**Comment by RLovering** [comment]
yes this is fine - thanks
