### ISSUE TITLE
missing relation for translation slimming effectively

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21560]
because 
id: GO:1904689
is no longer 
is_a: GO:2000766 ! negative regulation of cytoplasmic translation

2021-05-30 | Deleted | RELATION | is a GO:2000766 (negative regulation of cytoplasmic translation)

https://www.pombase.org/gene/SPBC800.09

translation initiation inhibitor 

no longer slims to cytoplasmic translation.

Or, should the annotation be different? not sure?

**Comment by mah11** [comment]
probably same reason as noted [here](https://github.com/geneontology/go-ontology/issues/21557#issuecomment-854485669)

**Comment by pgaudet** [comment]
That's weird because there was already a is_a relation: 

<img width="517" alt="image" src="https://user-images.githubusercontent.com/4782928/120976594-c75ea580-c772-11eb-9534-d61e0b4b7cdb.png">


Maybe the ontology is inconsistent WRT is_a and part_of relations in this area? 

I tried to make regulation of transcription initiation part_of regulation of transcription. Let me know if you still find inconsistencies. 

Thanks, Pascale

**Comment by mah11** [comment]
Val is saying that gps annotated to GO:1904689 ! negative regulation of cytoplasmic translation initiation are no longer annotated by transitivity to GO:0002181 ! cytoplasmic translation. I suspect it's mainly because GO no longer treats the `regulates` relations as transitive over `part_of` (specifically GO:0002183 ! cytoplasmic translational initiation `part_of` GO:0002181 ! cytoplasmic translation).

The image shows superclasses for GO:2000766, but the `is_a` relation that was deleted was a subclass of GO:2000766 (GO:1904689 used to be `is_a` GO:2000766 but isn't any more). I don't know whether that link was asserted or inferred, but if it was inferred before, that inference would no longer be made.

**Comment by pgaudet** [comment]
OK yes @mah11 this is right. Is there any relation that needs to be asserted? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Added to the parent class: 

GO:1904688 regulation of cytoplasmic translational initiation
regulates GO:0002181 ! cytoplasmic translation

Hopefully that will fix the issue. 

Thanks, Pascale

**Comment by pgaudet** [comment]
An additional comment: as @mah11 points out, we have removed the automatic inferences for regulates over part of, because that was creating incorrect assertions , see #13926

The google spreadsheet of the inferences we kept and removed is here: https://docs.google.com/spreadsheets/d/16Foto8g-0iy71OXqTnc0DV1ZvTIc0IjX10WmksPghfA/edit#gid=0

It may well be that there were omissions, please let us know if you find other issues. 

Thanks, Pascale
