### ISSUE TITLE
GO:0097617 annealing activity - merge into GO:0036310 annealing helicase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21614]
Please provide as much information as you can:

* **GO term ID and Label**
 GO:0097617 annealing activity

* **Reason for merge**
This does not represent a normal function - and no different from descendant under physiological conditions.

* **Are there annotations to this term?**
- How many EXP:
0 

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
Reactome:R-HSA-5686642 

* **Is this term in a subset? (check the AmiGO page for that term)**
No 

* **Any other information**

**Comment by pgaudet** [comment]
Questions: 
 - [ ] parentage: should annealing activity be a 'motor activity'? 
 -  current subclasses are: 'nucleic acid binding' and 'has part' some 'ATP hydrolysis activity'; I propose
 is_a motor activity
and  'has part' some 'nucleic acid binding' 
and 'has part' some 'ATP hydrolysis activity'
- it *is* referred to as a motor in the original term request ticket, see #9815
- [ ] Made this term a superclass of '
- DNA/DNA annealing activity'
-'DNA/RNA hybrid annealing activity'
- 'RNA strand annealing activity' 
- - but this is not consistent with the definition, that refers to DNA-DNA annealing: 
current definition "Catalysis of the ATP-dependent rewinding of single-stranded DNA (ssDNA) to reform base pairs between strands. Often acts on ssDNA bubbles bound by replication protein A (RPA)." 
 - Is is really a catalysis ? How about, "A motor activity that rewinds nucleic acids to reform base pairs between strands, driven by ATP hydrolysis."? 
 - Definition of current subclasses: 
 - - DNA/DNA annealing activity': A nucleic acid binding activity that brings together complementary sequences of ssDNA so that they pair by hydrogen bonds to form a double-stranded DNA.
 - -'DNA/RNA hybrid annealing activity': Facilitates the base-pairing of single-stranded RNA to double-stranded DNA resulting in the formation of R-loops.
 - - 'RNA strand annealing activity' : Facilitates the base-pairing of complementary single-stranded RNA.
It would be nice to harmonize these.

**Comment by pgaudet** [comment]
@ValWood @sjm41 @hattrill @bmeldal @colinlog 
any thoughts on the above questions?

**Comment by ValWood** [comment]
I checked the PomBAse annotations.

We have 


https://www.pombase.org/gene/SPAC57A10.10c
GO:0033592 | RNA strand annealing activity | 3
part of&nbsp;tRNA folding | IDA | Naeeni AR et al. (2012)
PMID:22203678
Using in vitro FRET-based assays, we show that human and Schizosaccharomyces pombe La proteins harbor RNA chaperone activity by enhancing RNA strand annealing and strand dissociation.

So maybe a chaperone term is more appropriate here?


https://www.pombase.org/reference/PMID:17673174
Translation initiation factor eIF1A possesses RNA annealing activity in its oligonucleotide-binding fold.....Our results indicate that eIF1A may function as an RNA chaperone, inducing conformational changes in rRNA in the 43S preinitiation complex.

again chaperone...

this paper
https://royalsocietypublishing.org/doi/10.1098/rsob.140193

appears to be  an a annealing activity of condensin but it is not ATP dependent and is definitely not a helicase. I don't know if this should really be annotated as an activity? Is it removing SSB? I don't really know how I should annotate this. @colinlog ?


Anyway, if  the activity is not required it should be obsoleted and not merged based on existing annotations.

**Comment by ValWood** [comment]
I'm not sure I should have made this annotation for cohesin. I don't know if it a relevant in vivo activity. @colinlog what do you think?

**Comment by pgaudet** [comment]
Are you strictly talking about 'annealing activity', or are you thinking children should be obsoleted as well?

**Comment by ValWood** [comment]
I forgot there were children. I was only really making the point that not all 'annealers' are helicases or even ATPases.

**Comment by sjm41** [comment]
Looking at the fly annotations, we have:

1. "annealing helicase activity" on Marcal1 (ortholog of human SMARCAL1) IDA from PMID:24866343, IMP from PMID:28258182.  This mediates DNA "annealing during synthesis-dependent strand annealing (SDSA). Elimination of the ATP-binding activity of Marcal1 also reduced annealing-dependent repair, suggesting that the annealing activity requires translocation along DNA."

2. "DNA/DNA annealing activity" on Blm (ortholog of human BLM) IDA from PMID:17272294.  That paper says ""Besides helicase activity, several recent studies showed enhanced complementary DNA strand annealing by BLM and other RecQ helicases. Such activity has been demonstrated for BLM (9), WRN (10,11), RecQ5β (12), and RecQ1 (13). Strand annealing occurs most efficiently **in the absence of ATP**."  This also is part of the SDSA pathway.

3. "RNA strand annealing activity" on five EIF4B and EIF4H initiation factors from InterPro:IPR033107 or PTN000579859 (source = cerevisiae TIF3). PMID: 7543843 defines 'RNA annealing' simply as "catalysing RNA duplex formation between RNAs with complementary sequences", and the Tif3p (EIF4B) activity is described as 'ATP-independent'.

So....at face value, only the current 'annealing helicase activity' annotation on SMARCL1 is ATP-dependent, which would mean the merge shouldn't happen...and the current structure makes some sense?

**Comment by pgaudet** [comment]
Thanks for looking at the annotations. This was the structure of the tree before I made edits: 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/4782928/122379979-ae6ea500-cf67-11eb-9b69-dfbc39551d93.png">
 
 -[ ] Looks like the 'helicase' name come from a helicase-like domain in SMARCAL1 and related proteins, but there is no helicase activity, as fas as I can tell. See PMID: 21078962
> AH2 catalyzes the ATP-dependent rewinding of replication protein A (RPA)-bound complementary single-stranded DNA, but does not exhibit any detectable helicase activity.

-> So, to avoid confusion, l I would remove 'helicase' from the term label. 
We could keep 'annealing activity' I could change the label of annealing helicase activity (which is the name of the gene product) to  'ATP-dependent annealing activity. 

Would that work? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, I wonder about the binding parents for these terms. Typically we dont capture substrate binding in the ontology. 

Or if these are useful we should also have them for DNA/DNA annealing activity.

**Comment by sjm41** [comment]
Thanks. Keeping the old structure and renaming 'annealing helicase activity' works for the fly research/annotations.  The def says it's specific to DNA, so should we use "ATP-dependent DNA/DNA annealing activity" as the renamed term?  Then, should it be a child of 'DNA/DNA annealing activity'?? 

Also see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3409536/, which includes "Traditionally, helicases are known to unwind double-stranded DNA or RNA in an ATP-dependent manner. However, increasing evidence suggests that some helicases can rewind, or anneal, complementary strands of polynucleic acids in the presence or absence of nucleoside triphosphate (Figure 1). Moreover, two so-called human helicases that were identified recently appear to only have ATP-dependent rewinding activity [11–15]. "

**Comment by pgaudet** [comment]
Should we not have the helicase discussion elsewhere?

**Comment by sjm41** [comment]
I wasn't intending to introduce a 'helicase discussion' here! The quote I gave from the paper was just intended the support that some real helicases also do annealing either with or without ATP, while the so-called annealing helicases only do ATP-dependent annealing.  That is, we do need both ATP-independent and ATP-dependent GO terms.

**Comment by pgaudet** [comment]
Ahhhh ! thank you for explaining (I will still create a separate helicase ticket).

**Comment by colinlog** [comment]
My take is that
(i) not all annealing activities (for DNA and for RNA) are ATP-dependent. Any protein that can bind two nuleic acid molecules simultaneously will speed-up annealing reactions. The physiological / GO relevance depends on the types of experiments reported in a publication. Rad52 is most definitely a physiological DNA annealing factor involved in homologous DNA recombination, ***but*** it is not an ATPase (see P43351 RAD52)

and secondly, that not all ATPases are motors !

(ii) Perhaps, only when a field considers it's ATPase to be a motor, should GO annotate to 'motor activity'. In other words: there are ATPases that are not motors (that catalyse a movement that is typically anisotropic/polar; eg 5' to 3' translocation, or minus end microtubule motors such as eg: HELB - Q8NG08 or Q9BVG8 KIFC3). Rather, some of these ATPases (eg the AAA+ ATPases Pontin/Reptin aka RUVBL1 and RUVBL2) are remodelling protein complexes or nucleic acid - protein complexes and have been called disaggregases [eg; PMID: 26303906] or quaternary chaperones, ie; chaperones for complex formation [eg; PMID: 29844425]. They also associate with HSP90/70 ATPses but not always! I informally called the RUVBs 'protein shakers' last week during the Jamboree. But, PMID: 29643509 call the RUVBL1-RUVBL2 heterohexameric ring subcomplex of the INO80 complex a 'stator' that allows the 'INO80 motor' to "prevent rotation of the motor with respect to the nucleosome, leading to rotation and translation of entry DNA" which is a reaction that 'pumps DNA into the nucleosome', similar to othe SNF2-type enzymes.

(iii) The cohesin (SMC1 + SMC3) and condensin (SMC2+SMC4) ATPases are 'DNA extrusion enzymes' whose reaction products were visualized as single tethered DNA molecules [PMID: 29472443, 31780627, 31753851], this is probably falling under 'motor activity'. Note that they need to be heterodimers and need the other cohesin/condensin subunits to exert this activity. We are looking protein complexes, not single enzyme proteins!

(iv) For the SNF2 type nucleosome remodellers, most are translocases that manage to move histone octamers along a DNA strand using a 'nucleosome-tethered DNA translocation/pumping activity, and so they would probably qualify for 'motor activity' (see also my paper PMID: 19626125) . But, not all SNF2-type ATPases are truly translocases. SWR1 does not slide nucleosomes, it 'only' removes a H2A-H2B dimer to replace it with a H2A.Z-H2B dimer and very recent -unpublished- news is that human SMARCA1 / yeast FUN30 is actually removing the entire octamer from DNA and helps to put it back elsewhere on the same DNA or on another DNA. Also SMARCA2 and SMARCA4 complexes can do that in vitro, although they tend to slide octamers over DNA rather than chaperone them away from their DNA -- full octamer dissociation from DNA / histone octamer chaperoning is not their main activity.

**Comment by pgaudet** [comment]
From 
https://github.com/geneontology/go-ontology/issues/21614#issuecomment-863157024

> The def says it's specific to DNA, so should we use "ATP-dependent DNA/DNA annealing activity" as the renamed term? Then, should it be a child of 'DNA/DNA annealing activity'??

yes and yes

**Comment by ValWood** [comment]
>I informally called the RUVBs 'protein shakers' last week during the Jamboree. But, PMID: 29643509 call the RUVBL1-RUVBL2 heterohexameric ring subcomplex of the INO80 complex a 'stator' that allows the 'INO80 motor' to "prevent rotation of the motor with respect to the nucleosome, leading to rotation and translation of entry DNA" which is a reaction that 'pumps DNA into the nucleosome', similar to othe SNF2-type enzymes.

Can we use this information to define the 

--nucleosome loading ATPase stator activity
--nucleosome loading ATPase motor activity

**Comment by ValWood** [comment]
removed previous comment, I didn't mean to post this.
I'm still unclear of the axis of classification for the  different types  of DNA/nucleosome dependent ATPases.
At present many can be described using multiple unrelated terms for the same activity.

**Comment by ValWood** [comment]
i.e translocases, loaders, chromatin remodelers.... 
Do we need to open tickets for these  issues or are they in progress?

**Comment by ValWood** [comment]
@colinlog 
https://www.uniprot.org/uniprot/Q9BVG8 KIFC3
is described as a  minus-end motor  activity is this incorrect?
