### ISSUE TITLE
resolve Rhea mapping for 'L-aminoadipate-semialdehyde dehydrogenase activity' GO:0004043 (NAD / NADP issue)

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21639]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/42d6ca8bde35c51d604a6a5385d5ffde18f09f3d98fe0821f7d118bb51987955.png)

- [(S)-2-amino-6-oxohexanoate + H2O + NAD(+) <=> 2 H(+) + L-2-aminoadipate + NADH](http://rdf.rhea-db.org/12311) EquivalentTo [METACYC:ALLYSINE-DEHYDROG-RXN](http://metacyc.org/ALLYSINE-DEHYDROG-RXN)	(most probable)	0.75
- [(S)-2-amino-6-oxohexanoate + H2O + NAD(+) => 2 H(+) + L-2-aminoadipate + NADH](http://rdf.rhea-db.org/12309) ProperSuperClassOf [REACTOME:R-HSA-70941.4](http://reactome.org/R-HSA-70941.4)	(most probable)	0.7
- [L-aminoadipate-semialdehyde dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0004043) ProperSuperClassOf [(S)-2-amino-6-oxohexanoate + H2O + NAD(+) = 2 H(+) + L-2-aminoadipate + NADH](http://rdf.rhea-db.org/12308)		0.15
- [(S)-2-amino-6-oxohexanoate + H2O + NAD(+) = 2 H(+) + L-2-aminoadipate + NADH](http://rdf.rhea-db.org/12308) ProperSubClassOf [EC:1.2.1.31](http://purl.uniprot.org/enzyme/1.2.1.31)		0.1
- [(S)-2-amino-6-oxohexanoate + H2O + NADP(+) = 2 H(+) + L-2-aminoadipate + NADPH](http://rdf.rhea-db.org/12304) EquivalentTo [EC:1.2.1.31](http://purl.uniprot.org/enzyme/1.2.1.31)	(most probable)	0.75
- [(S)-2-amino-6-oxohexanoate + H2O + NAD(+) => 2 H(+) + L-2-aminoadipate + NADH](http://rdf.rhea-db.org/12309) ProperSubClassOf [METACYC:1.2.1.31-RXN](http://metacyc.org/1.2.1.31-RXN)		0.1
- [L-aminoadipate-semialdehyde dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0004043) EquivalentTo [EC:1.2.1.31](http://purl.uniprot.org/enzyme/1.2.1.31)	(most probable)	0.8
- [L-aminoadipate-semialdehyde dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0004043) EquivalentTo [METACYC:1.2.1.31-RXN](http://metacyc.org/1.2.1.31-RXN)	(most probable)	0.8
- [(S)-2-amino-6-oxohexanoate + H2O + NADP(+) => 2 H(+) + L-2-aminoadipate + NADPH](http://rdf.rhea-db.org/12305) EquivalentTo [METACYC:1.2.1.31-RXN](http://metacyc.org/1.2.1.31-RXN)	(most probable)	0.75

**Comment by pgaudet** [comment]
I am not convinced that NADP is ever used as a cofactor as described in RHEA:12304

RHEA:12304 cites 3 Publications: 

 1.   Cloning and characterization of pcd encoding delta'-piperideine-6-carboxylate dehydrogenase from Flavobacterium lutescens IFO3084. PMID:11098140
**-> Mentions NAD, not NADP**


2.  Metabolism of pipecolic acid in a Pseudomonas species. 3. L-alpha-aminoadipate delta-semialdehyde:nicotinamide adenine dinucleotide oxidoreductase. PMID:4285660
**-> Describes reaction as NAD but adds NAD(P) because "Sensitivity to sulfhydryl reagents (Table III) is consistent with this hypothesis, for oxidations of aldehydes to acids are thought to proceed via enzyme-bound hemimercaptal intermediates (14). We have therefore named the enzyme L-a-aminoadipate Lsemialdehyde : NAD(P) oxido- reductase and suggest its inclusion in EC class 1.2.1"  -> is this sufficient evidence?** 
 

 3. Delta-1-piperideine-6-carboxylate dehydrogenase, a new enzyme that forms alpha-aminoadipate in Streptomyces clavuligerus and other cephamycin C-producing actinomycetes.

 **"The native protein is a monomer of 56.2 kDa that efficiently uses P6C (apparent Km 14 microM) and NAD+ (apparent Km 115 microM), but not NADP+ or other electron acceptors, as substrates. "**

@amorgat @kaxelsen Does the reaction described by RHEA:12304 exist? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@balhoff can we decide that mo action is needed and the mappings are OK ?

**Comment by kaxelsen** [comment]
{code}
1. Cloning and characterization of pcd encoding delta'-piperideine-6-carboxylate dehydrogenase from Flavobacterium lutescens IFO3084. PMID:11098140
-> Mentions NAD, not NADP
{code}

Wrong, in Table VI they show activity with NADP (it is almost as good as NAD)

So RHEA:12304 does exist. It also shown in PubMed=10320345 from LYS2_YEAST (P07702)

**Comment by kaxelsen** [comment]
Some additional information:
When looking at the usage of EC 1.2.1.31 in UniProtKB, I noted that:
We do not have any links to bacterial enzymes (Ref. 1 defining the usae of NAD(P) was from Pseudomonas)
The mammalian entries annotated as being EC 1.2.1.31 only accept NAD
The yeast (and other fungal) enzyme(s) annotated as being EC 1.2.1.31 only accept NADP.
So I might suggest two new EC numbers one for NAD usage and the other for NADP usage.

**Comment by pgaudet** [comment]
> The mammalian entries annotated as being EC 1.2.1.31 only accept NAD

How come then, P49419 is annotated to both 
(S)-2-amino-6-oxohexanoate + H2O + NADP+ = 2 H+ + L-2-aminoadipate + NADPH (RHEA:12304) 
and (S)-2-amino-6-oxohexanoate + H2O + NAD+ = 2 H+ + L-2-aminoadipate + NADH (RHEA:12308)

Isn't this NAD(P)?

**Comment by kaxelsen** [comment]
Yes indeed, but as all the entries have been annotated as EC 1.2.1.31, they have both reactions linked to this EC number.
That is the reason I write:

> So I might suggest two new EC numbers one for NAD usage and the other for NADP usage. ;-)

**Comment by pgaudet** [comment]
I see. I thought UniProt was assigning RHEAs independent of ECs- looks like that's not the case

**Comment by kaxelsen** [comment]
We do, but we have not retrofitted all the existing annotations. So when we first changed from text reactions to Rhea reactions, we "just" switched all reactions. Anyway, the assignment of EC 1.2.1.31 to all these entries are wrong as EC 1.2.1.31 describes enzymes that can accept both NADH _and_ NADPH, and this is not the case for the current entries, they accept NADH _or_ NADPH.

**Comment by pgaudet** [comment]
I see, thanks!
