### ISSUE TITLE
Taxon constraint: GO:0016055 Wnt signaling pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21642]
Please provide as much information as you can: 

GO:0016055 Wnt signaling pathway

* **Request to add a taxon constraint:**

* * **never in taxon: **
fungi?

**Comment by pgaudet** [comment]
There is already 'Only in Taxon | 33208 | Metazoa' 

are you getting annotations? This sound already exclude fungi.

**Comment by ValWood** [comment]
Yep, see: 
https://www.pombase.org/results/from/id/ed3c0b9b-6040-4dca-afaf-df4a763dc378

**Comment by pgaudet** [comment]
@dustine32 @kltm 

I thought annotations that violate taxon constraints were filtered - this one is reported in the pombase error report: 
`ERROR - Violates GO Rule: GORULE:0000013: Taxon-appropriate annotation check -- PomBase SPBC1347.06c cki1 involved_in GO:0016055 PMID:21873635 IBA PANTHER:PTN000226268|UniProtKB:P49674 P Casein kinase I homolog 1 UniProtKB:P40233|PTN000226265 protein taxon:284812 20170228 GO_Central`

but still shows up in AmiGO, and is exported in our files: 

http://amigo.geneontology.org/amigo/gene_product/PomBase:SPBC1347.06c

Can you please check what is not working? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet Just to get a feel, does it look like taxon constraints are generally not working, or are you running into a handful of cases that are getting through? Also, we can check to see if this is a new thing or if it has been slipping by us.

**Comment by kltm** [comment]
Noting that this seems to be coming from paint_pombase.

**Comment by kltm** [comment]
@dustine32 Just checking, are the paint files processed the same way as the others in the taxon filtering stage, or are those handled "upstream"?

**Comment by dustine32** [comment]
@kltm PAINT is handled a little differently as a "mixin" but the idea is that GO rule 13 is supposed to filter out these TC violations. So, if it does end up being more than a handful, something is wrong. I'm still debugging this.

**Comment by dustine32** [comment]
OK, after a lot of time spent staring at my debugger, I figured out that the "temporary post-filter" step commands just needed to add an option (`-l all`) to turn on ALL of the GO rules again. This option became required recently due to changes made for https://github.com/biolink/ontobio/issues/544.

Confusingly, the invalid `PomBase SPBC1347.06c cki1 involved_in GO:0016055` line was reported invalid as @pgaudet pointed out, making it look like the TC check rule (GO rule 13) was running. However, this rule ran only on the source `pombase.gaf` in the mega-step (filtering the IBA out), but not the `paint_pombase.gaf` in the later post-filter (adding the IBA back).

The little test in PR https://github.com/geneontology/go-site/pull/1709#issue-675833213 shows that adding this option will correctly filter out that taxon-invalid IBA line for PomBase.

**Comment by kltm** [comment]
@pgaudet This was merged into master and should be available for testing.

**Comment by pgaudet** [comment]
I still find the offending ID GO:0016055 in 
http://snapshot.geneontology.org/annotations/pombase.gaf.gz
(release date: date | "2021-06-22") 

Maybe this is a lag because snapshot has not ran since the merge was done?

**Comment by pgaudet** [comment]
This annotation is now gone :)
