### ISSUE TITLE
Term merge? ERAD

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#21689]
ERAD pathway (GO:0036503)
Definition
The protein catabolic pathway which targets endoplasmic reticulum (ER)-resident proteins for degradation by the cytoplasmic proteasome. It begins with recognition of the ER-resident protein, includes retrotranslocation (dislocation) of the protein from the ER to the cytosol, protein modifications necessary for correct substrate transfer (e.g. ubiquitination), transport of the protein to the proteasome, and ends with degradation of the protein by the cytoplasmic proteasome.

Has the descendents

	ER-associated misfolded protein catabolic process
	mannose trimming involved in glycoprotein ERAD pathway
	ubiquitin-dependent ERAD pathway
	ubiquitin-dependent glycoprotein ERAD pathway

1. I don't think this pathway is for resident proteins, it certainly isn't _only_ for resident proteins? The glycoproteins which are exported through the secretory system also undergo QC via this pathway.

Does anybody know where this statement came from?

2. I don't see any immediate difference between
GO:0036503 and
GO:0030433 ubiquitin-dependent ERAD pathway 
GO:0071712 ER-associated misfolded protein catabolic process

If the parentage is taken into consideration.

3. Descendant 
	mannose trimming involved in glycoprotein ERAD pathway
Looks like a molecular function

**Comment by RLovering** [comment]
Hi Val

surely it would be good to use the AE to link the mannose BP/MF to the BP ERAD pathway before this is merged so that this information is protected rather than lost?

Also how many of these terms are you planning to merge as it is not clear from this email. Rebecca worked on curating this area for a long time so I am not sure of the biology she was trying to capture with the terms that look similar but she felt needed separate terms for, at least I assume she felt these were both required

it looks like UCL has only identified 4 human proteins involved in the mannose/ERAD pathway:
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:1904382&assignedBy=ARUK-UCL,BHF-UCL,ParkinsonsUK-UCL

But there are 19 expt supported annotations
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:1904382&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants 

I can't work on this for a week due to leave and other committments, could you delay this merge until I have had a chance to edit these - assuming the other groups are happy with this proposal

Ruth

**Comment by ValWood** [comment]
I don't think a merge is ever processed without reviewing the annotations, but by definition these seem to be identical

GO:0036503 ERAD pathway
GO:0030433 ubiquitin-dependent ERAD pathway
GO:0071712 ER-associated misfolded protein catabolic process

are the same.
GO:0030433 ubiquitin-dependent ERAD pathway
and
GO:0071712 ER-associated misfolded protein catabolic process
are currently descendents

The GO definition of ERAD is at odds  with other definitions.

for example  wikipedia:
Endoplasmic-reticulum-associated protein degradation (ERAD) designates a cellular pathway which targets misfolded proteins of the endoplasmic reticulum for ubiquitination and subsequent degradation by a protein-degrading complex, called the proteasome.

https://www.nature.com/articles/ncb0805-766
"Endoplasmic reticulum (ER)-associated protein degradation (ERAD) eliminates misfolded or unassembled proteins from the ER"

To me the current terms don't really make sense, so either merge or clarification is required.

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/23092
duplicate
