### ISSUE TITLE
response to paclitaxel

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#21750]
Hi Karen

I think I have missed some of the discussions on the drug response and drug metabolism terms. 

There are currently 4 terms with 

GO:0042616                paclitaxel metabolic process | 754 annotations
--|--
GO:0042617                paclitaxel biosynthetic process | 752 annotations
GO:1901555                response to paclitaxel | 19 annotations
GO:1905705                cellular response to paclitaxel  | 3 annotations

The metabolism/biosynthesis definitions refer to paclitaxel as an anti-cancer agent, although it is a naturally occuring chemical found in the yew tree bark:
The chemical reactions and pathways resulting in the formation of paclitaxel, an alkaloid compound used as an anticancer treatment. 

Should the response to paclitaxel terms exist? if so should their use in annotations be limited to those plant that synthesis paclitaxel with the taxon constraint of not in mammals be associated with this term. With the existing non-plant annotation moved to response to drug terms with https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:45863 in the annotation extension with 'has_input' relation?

I guess these non-plant annotations could also be associated with the response to paclitaxel parent term response to lipid?

Thanks

Ruth

**Comment by krchristie** [comment]
> Hi Karen
> 
> I think I have missed some of the discussions on the drug response and drug metabolism terms.
> 
> There are currently 4 terms with
> GO:0042616 paclitaxel metabolic process 	754 annotations
> GO:0042617 paclitaxel biosynthetic process 	752 annotations

The vast majority of these are IEA annotations. The taxa I took a quick look at are all other conifers.
Evidence   Code | paclitaxel biosynthetic process | paclitaxel metabolic process | Grand Total
-- | -- | -- | --
IDA |   | 2 | 2
TAS | 2 |   | 2
IEA | 750 |   | 750


Here are the 4 non-IEA annotations.
Symbol | Gene name | GO term | Source | Taxon | Ev | Reference | Date
-- | -- | -- | -- | -- | -- | -- | --
pam | Phenylalanine aminomutase (L-beta-phenylalanine forming) | paclitaxel biosynthetic process | UniProt | Taxus chinensis | TAS | PMID:24786474 | 20140604
pam | Phenylalanine aminomutase (L-beta-phenylalanine forming) | paclitaxel biosynthetic process | UniProt | Taxus canadensis | TAS | PMID:21361343 | 20140604
Q84KI1 | Taxoid 14-beta-hydroxylase | paclitaxel metabolic process | UniProt | Taxus cuspidata | IDA | PMID:12729625 | 20120629
Q6JTJ0 | Taxoid 7-beta-hydroxylase | paclitaxel metabolic process | UniProt | Taxus cuspidata | IDA | PMID:15157877 | 20120629

I'd say these annotations all look appropriate.

> The metabolism/biosynthesis definitions refer to paclitaxel as an anti-cancer agent, although it is a naturally occuring chemical found in the yew tree bark:
> Def: The chemical reactions and pathways resulting in the formation of paclitaxel, an alkaloid compound used as an anticancer treatment.

I agree that the definition should be revised. How about using the description from ChEBI instead of mentioning its use as a cancer drug. Here's an idea:

Proposed new def: The chemical reactions and pathways resulting in the formation of paclitaxel, a tetracyclic diterpenoid isolated originally from the bark of the Pacific yew tree, Taxus brevifolia. 

> GO:1901555 response to paclitaxel 	19 annotations
> GO:1905705 cellular response to paclitaxel 	3 annotations


 




> Should the response to paclitaxel terms exist? if so should their use in annotations be limited to those plant that synthesis paclitaxel with the taxon constraint of not in mammals be associated with this term. With the existing non-plant annotation moved to response to drug terms with https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:45863 in the annotation extension with 'has_input' relation?
> 
> I guess these non-plant annotations could also be associated with the response to paclitaxel parent term response to lipid?
> 
> Thanks
> 
> Ruth

**Comment by RLovering** [comment]
Hi Karen

thanks for your comments I agree with your interpretation. 

Your proposed new def: The chemical reactions and pathways resulting in the formation of paclitaxel, a tetracyclic diterpenoid isolated originally from the bark of the Pacific yew tree, Taxus brevifolia. 
looks good to me, please implement

I will contact RGD and Flybase and see what they want to do with these

Best

Ruth

**Comment by krchristie** [comment]
> Hi Karen
> 
> thanks for your comments I agree with your interpretation.
> 
> Your proposed new def: The chemical reactions and pathways resulting in the formation of paclitaxel, a tetracyclic diterpenoid isolated originally from the bark of the Pacific yew tree, Taxus brevifolia.
> looks good to me, please implement

Great. Thanks for checking the proposal. I'll change this next week.

> I will contact RGD and UniProt and see what they want to do with these

Thanks!

I think that transferring these annotations to the existing terms "response to xenobiotic stimulus" and/or "response to organic cyclic compound" would be good options.

It might be that we should consider obsoleting response terms like this, to some specific compound that is generally a xenobiotic for most organisms. I think that there are a lot of them, and I don't want to get involved in going through them systematically. However, since we've just done the analysis for this one, I wouldn't mind proposing to obsolete it now since I think there are reasonable existing options to transfer the annotations to. What do you think @RLovering ?

**Comment by alanbridge** [comment]
Hi 

in UniProt we asked curators to apply this rule of thumb when annotating enzymes and transporters: limit the annotation to those compounds that the enzyme / transporter would have evolved to deal with. We asked them not to think of whether the compound is an "endogenous metabolite" or xenobiotic, as that isn't always helpful; a transporter that evolved to exclude heavy metals from cells is dealing with compounds the cells don't want, and are not metabolites or endogenous compounds of the cell, but that is the biological function.

So we do have curators annotating natural product metabolic pathways in UniProt (drugs). That is in scope. This is mainly in fungi and plants and a few microbes. But we don't want to get into annotating the effects of these compounds on say human proteins. That is out of scope (rather in scope for a resource like DrugBank or ChEMBL).

Could you apply the same rule of thumb to response to terms for drugs like taxol? i.e. allow the response to term for organisms that evolved mechanisms to respond to those compounds (in the doses in which they are found in the environment naturally), which like Karen said, may include insects, or maybe microorganisms. That would allow you to keep the term and not obsolete it. Most cells will respond to most insults if the dose is high enough. 

Terpenes are isoprenoids which are lipids. Annotating to response to lipid is not really informative though - human cells may contain up to 100,000 lipids, and given their ubiquity and central roles in structuring cells, most processes could probably be affected by changes in one or more lipids/membranes given a high enough dose/change.

All the best, Alan

**Comment by krchristie** [comment]
Hi Alan,

Thanks very much for your thoughtful comments on this issue. @vanaukenk put this on the agenda for the GO annotation call on 7/20/21 for discussion. We are not currently considering a large scale obsoletion of terms of this type, but we do feel that many of them were created to deal with specific experiments applying exogenous chemicals to organisms were not evolved to deal with. Below, I give some of the current thinking of the ontology editors group.

> in UniProt we asked curators to apply this rule of thumb when annotating enzymes and transporters: limit the annotation to those compounds that the enzyme / transporter would have evolved to deal with. We asked them not to think of whether the compound is an "endogenous metabolite" or xenobiotic, as that isn't always helpful; a transporter that evolved to exclude heavy metals from cells is dealing with compounds the cells don't want, and are not metabolites or endogenous compounds of the cell, but that is the biological function.

I initially proposed obsoleting all of the xenobiotic terms as the role of "xenobiotic" varies depending on the compound-species combination. When we discussed the role of "xenobiotic" at an ontology editors meeting, it was agreed to obsolete  "xenobiotic" terms from the Molecular Function aspect of the ontology because it is not possible to define a function that is always true with respect to a role which may or may not be relevant in a given context. However, @thomaspd wanted to keep xenobiotic terms in the Biological Process aspect, as it is a normal process for organisms to need to respond to foreign, i.e.xenobiotic, compounds. Though we will keep xenobiotic terms in the Process aspect, we will not longer assert that any specific compound is a xenobiotic within the GO structure since it is often not true for all organisms. Thus, annotating to a term like "response to xenobiotic stimulus" is not going to give you any sense of what type of what type of chemical is involved. To annotate the chemical info would require annotating to a chemically relevant term. A chemically relevant term could be a very specific term like the existing "response to paclitaxel", or it could be a more general term like the "response to organic cyclic compound" term I suggested. 

> We do have curators annotating natural product metabolic pathways in UniProt (drugs) (see https://pubmed.ncbi.nlm.nih.gov/33445429/). That is in scope. This is mainly in fungi and plants and a few microbes. But we don't want to get into annotating the effects of these compounds on, say, human proteins. That is out of scope for UniProt now - more the goal of a resource like DrugBank or ChEMBL.
 
> Could you apply the same rule of thumb to response to terms for drugs like taxol? i.e. allow the response to term for organisms that evolved mechanisms to respond to those compounds (in the doses in which they are found in the environment naturally), which like Karen said, may include insects, or maybe microorganisms. That would allow you to keep the term and not obsolete it. Most cells will respond to most insults if the dose is high enough.

Regarding annotations to the term "response to paclitaxel", I think that all of the current experimental annotations to these terms (made for rat & drosophila) need to be reevaluated as I doubt they meet the curation criterion you stated above: "limit the annotation to those compounds that the enzyme / transporter would have evolved to deal with", which is also the strategy that GO is currently trying to apply, though it has not always been applied in the past. Rather, I think that this term was requested in order to annotate experiments that used exogenously-applied paclitaxel. If there was a current annotation need for the term "response to paclitaxel", I would have no objection to keeping it. However, the plants that produce it have only been annotated to the "paclitaxel biosynthetic/metabolic process" terms, and have NOT been annotated to the "response to paclitaxel" term, which I think is appropriate since I don't think we generally create "response to x" terms for endogenous stimuli. Thus, at the moment, I am slightly in favor of obsoleting this term as I don't think there is any current annotation need for it.

> Terpenes are isoprenoids which are lipids. Annotating to response to lipid is not really informative though - human cells may contain up to 100,000 lipids, and given their ubiquity and central roles in structuring cells, most processes could probably be affected by changes in one or more lipids/membranes given a high enough dose/change.

I completely agree that "response to lipid" would not be an informative annotation. As I said above, I think "response to organic cyclic compound" might be appropriate.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
* GO:1901555 response to paclitaxel
and 
*  GO:1905705 cellular response to paclitaxel

The reason for obsoletion is that this represents a response to xenobiotic stimulus, and we have decided that we would not create responses to all specific xenobiotics. 

There are 2 EXP annotations to this term by RGD. 

You can comment on the ticket:  https://github.com/geneontology/go-ontology/issues/21750

Thanks, Pascale

**Comment by pgaudet** [comment]
+ merge GO:0042617 paclitaxel biosynthetic process into parent 
GO:0042616 paclitaxel metabolic process

**Comment by slaulederkind** [comment]
The RGD annotations have been changed.
