### ISSUE TITLE
resolve Rhea mapping for 'beta-ketoacyl-acyl-carrier-protein synthase II activity' GO:0033817

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#21801]
![](https://github.com/geneontology/go-rhea-boom/raw/7c0115de3cf28346faefe7b6da4b56a8bbc32024/rhea-boom/def0e414c39c925b23ffc763de6531d82262d968aab2f1c5c2a6123dbe4c5302.png)

- [(9Z)-hexadecenoyl-[ACP] + H(+) + malonyl-[ACP] = 3-oxo-(11Z)-octadecenoyl-[ACP] + CO2 + holo-[ACP]](http://rdf.rhea-db.org/55040) EquivalentTo [EC:2.3.1.179](http://purl.uniprot.org/enzyme/2.3.1.179)	(most probable)	0.75
- [(9Z)-hexadecenoyl-[ACP] + H(+) + malonyl-[ACP] => 3-oxo-(11Z)-octadecenoyl-[ACP] + CO2 + holo-[ACP]](http://rdf.rhea-db.org/55041) EquivalentTo [METACYC:2.3.1.179-RXN](http://metacyc.org/2.3.1.179-RXN)	(most probable)	0.75
- [beta-ketoacyl-acyl-carrier-protein synthase II activity](http://purl.obolibrary.org/obo/GO_0033817) EquivalentTo [EC:2.3.1.179](http://purl.uniprot.org/enzyme/2.3.1.179)	(most probable)	0.8
- [beta-ketoacyl-acyl-carrier-protein synthase II activity](http://purl.obolibrary.org/obo/GO_0033817) ProperSubClassOf [(11Z)-hexadecenoyl-[ACP] + H(+) + malonyl-[ACP] = 3-oxo-(13Z)-octadecenoyl-[ACP] + CO2 + holo-[ACP]](http://rdf.rhea-db.org/14565)		0.15
- [beta-ketoacyl-acyl-carrier-protein synthase II activity](http://purl.obolibrary.org/obo/GO_0033817) EquivalentTo [METACYC:2.3.1.179-RXN](http://metacyc.org/2.3.1.179-RXN)	(most probable)	0.8

**Comment by pgaudet** [comment]
Looks like the reaction represented by GO:0033817 is currently mapped RHEA:14565, mapped to 'GO:0033817 beta-ketoacyl-acyl-carrier-protein synthase II activity', is a specific form RHEA:22836 (a fatty acyl-[ACP] + H+ + malonyl-[ACP] = a 3-oxoacyl-[ACP] + CO2 + holo-[ACP]) 

which corresponds to
* EC 2.3.1.41 	Beta-ketoacyl-[acyl-carrier-protein] synthase I
* GO:0004315  3-oxoacyl-[acyl-carrier-protein] synthase activity

Since there is a single gene annotated, UniProtKB:P0AAI5, which is also mapped to the parent RHEA, I will merge GO:0033817 into GO:0004315  3-oxoacyl-[acyl-carrier-protein] synthase activity. 

Pascale

**Comment by pgaudet** [comment]
Actually- the mapping to EC:2.3.1.79 to GO:0033817 was wrong; already mapped to GO:0008925. So I will remove all references to EC:2.3.1.79 from GO:0033817.
