### ISSUE TITLE
missing parent for cellular modified amino acid biosynthetic process

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#21847]
GO:0042398 cellular modified amino acid biosynthetic process
should have is_a relation to 
 GO:0006575 cellular modified amino acid metabolic process

thanks
Ruth

**Comment by raymond91125** [comment]
I think the reason why they are not connected is because
GO:0042398 cellular modified amino acid biosynthetic process is logically defined as 'biosynthetic process' and ('has primary output' some 'amino acid derivative')
whereas
GO:0006575 cellular modified amino acid metabolic process is logically defined as '*cellular* metabolic process' and ('has primary input or output' some 'amino acid derivative')

**Comment by ValWood** [comment]
The logical defs seem inconsistent in this case?
As far as I'm aware "x biosynthetic process" should always be is_a "x metabolic process"

**Comment by raymond91125** [comment]
@ValWood I implemented the change that solves the problem. The revised logical definition is able to achieve "x biosynthetic process" should always be is_a "x metabolic process".

Do we still need the ticket open?
Thanks.

**Comment by ValWood** [comment]
Right, sorry about that @raymond91125  I though that you were just stating that they should not be connected ;0
