### ISSUE TITLE
Help resolving BPs with overlapping synonyms

### ISSUE THREAD

**Issue by cthoyt** [geneontology/go-ontology#21868]
I'm curating equivalences between GO biological processes and KEGG pathways (the non-species specific ones that have identifiers like `^map\d+$`).

I'm unsure how to curate the relationships between the following GO terms with Adipocytokine signaling pathway ([kegg.pathway:map04920](https://bioregistry.io/kegg.pathway:map04920)), which all share "adipocytokine signaling pathway" as a synonym:

- tumor necrosis factor-mediated signaling pathway ([GO:0033209](https://bioregistry.io/GO:0033209))
- leptin-mediated signaling pathway ([GO:0033210](https://bioregistry.io/GO:0033210))
- adiponectin-activated signaling pathway ([GO:0033211](https://bioregistry.io/GO:0033211))

One solution might be to have a parent class for all three of these that exact matches KEGG's notion of adipocytokine signaling pathway, but the place where these three GO processes appear are in pretty different places in the class hierarchy such that this doesn't make any sense. Any feedback appreciated!

**Comment by ValWood** [comment]
In general, IMHO it will be almost impossible to map  KEGG signalling pathways to GO usefully. Many pathways have multiple ways of describing them in GO (by receptor, by ligand, by type, response, pathway member,  by module i.e. MAPK cascade - with no clear beginnings and ends).   There isn't really any easy way to define the signalling pathway labels .

(making this comment mainly so that I can follow this ticket)

**Comment by pgaudet** [comment]
Hi @cthoyt 
As @ValWood points out, it may be difficult to have a 1:1 correspondence across resources. 

https://www.rndsystems.com/research-area/adipocytokines defines adipocytokines as cytokines produced by adipocytes; this is a not an axis of classification in GO. All 3 terms are under  GO:0019221 cytokine-mediated signaling pathway; is this too broad? At least it is correct. 

Thanks, Pascale
