### ISSUE TITLE
NTR: biological condensate

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21881]
Please provide as much information as you can: 

* **Suggested term label:**
biological condensate

* **Definition (free text)**
Intracellular non-membrane-bounded organelle concentrating a certain set of multivalent biopolymers. 

* **Reference, in format PMID:#######**
PMID:33938068
PMID:29602697

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
* GO:0043232 intracellular non-membrane-bounded organelle

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Requested to align with the IDPO ontology.

**Comment by pgaudet** [comment]
@colinlog FYI- I  am creating this term; please improve any aspect as needed.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140686
+name: biological condensate
+namespace: cellular_component
+def: "Intracellular non-membrane-bounded organelle concentrating a certain set of multivalent biopolymers." [PMID:29602697, PMID:33938068]
+is_a: GO:0043232 ! intracellular non-membrane-bounded organelle
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21881 xsd:anyURI
+created_by: pg
+creation_date: 2021-07-29T09:56:55Z

**Comment by pgaudet** [comment]
@federicaquaglia

**Comment by pgaudet** [comment]
@federicaquaglia Looking more closely at PMID:29602697, maybe 'biological condensate' could be a synonym to the existing GO:0043232 intracellular non-membrane-bounded organelle, instead of creating a new term?

**Comment by ValWood** [comment]
Hi,

What is the rationale for adding the term 'biological condensate'? This is really a physiochemical properties, rather than a biological component it seems out of scope. At best, a slightly arbitrary grouping term; At worst because of the complexity of the biology encompasses it would be a true path violation nightmare.

I highlighted some 'consensate' terms in this graph. I agree that it could be a related synonym of  the existing GO:0043232 .

<img width="603" alt="Screenshot 2021-07-30 at 08 24 59" src="https://user-images.githubusercontent.com/7359272/127617332-8af288bf-5489-4b0e-be44-c5a708fcfad4.png">

**Comment by hattrill** [comment]
There is a lot of interest in phase separation and the regulation of this as a process at the moment - I am asking Nick Brown to have a look at this as he flagged it as a topic that is gaining momentum in research.

**Comment by ValWood** [comment]
Agreed, there A LOT OF interest as a topic, but it's still a biophysical property rather than a process.

stress granule formation 
https://pubmed.ncbi.nlm.nih.gov/34100129/

mRNA decapping
https://pubmed.ncbi.nlm.nih.gov/33767388/

chromosome segregation
https://pubmed.ncbi.nlm.nih.gov/32285141/

parts of cytokinesis
https://pubmed.ncbi.nlm.nih.gov/32285141/

etc, etc,

these are the biophysical mechanisms, not the processes themselves (it's just HOW they occur)

do we really want to represent these processes as "phase separation"...maybe if so just tag the respective definitions  with "this process is proposed to occur by a phase separation mechanism"

Everything is phase separation really......



MAybe the definitions could

**Comment by ValWood** [comment]
I think my issue is that this is an intrinsic property of the biomolecules rather than something that individual genes perform. How would  such process terms be used in annotation?
In fact, it is a good argument to remove some assembly terms....(which has been a topic for a while...)

**Comment by mah11** [comment]
Um, is this straying off topic a bit? Not that concerns over whether gene products act in phase separation aren't inherently valid, but this ticket is about a cellular component term (which I would accept as legit if there's a way to distinguish it from other non-membrane-bounded organelles AND gene products do things there).

**Comment by hattrill** [comment]
Yes - agreed! It's a CC thing here!

**Comment by hattrill** [comment]
Rather sensibly, David Hill is trying to get it back onto the subject of whether these can be distinguished as a cellular component distinct from or related to non-membrane bound organelle!

**Comment by pgaudet** [comment]
Right - this is exactly what we have been discussing with the DisProt foks. If there is no clear distinction, I will add it as a synonym.

**Comment by esalladini** [comment]
Hi,
In my opinion the GO: 0043228 definition might fit quite well our purpose. In fact, that term includes the nucleolus formation that is a good example of what we are annotating for IDRs in DisProt.

**Comment by ValWood** [comment]
It might be useful to have the grouping term as a descendant of 

if any of these are not condensates? I would imagine the cytoskeleton components  and ribosome are not for example?

GO:0042646    plastid nucleoid | is_a
GO:0097597    ventral disc | is_a
GO:0120293    dynein axonemal particle | is_a
GO:0042645    mitochondrial nucleoid | is_a
GO:0030075    bacterial thylakoid | is_a
GO:0098681    synaptic ribbon | is_a
GO:0043590    bacterial nucleoid | is_a
GO:0098682    arciform density | is_a
GO:0005840    ribosome | is_a
GO:0010369    chromocenter | is_a
GO:0099091    postsynaptic specialization, intracellular component | is_a
GO:0046858    chlorosome | is_a
GO:0098536    deuterosome | is_a
GO:0031411    gas vesicle | is_a
GO:1990732    pyrenoid | is_a
GO:0034515    proteasome storage granule | is_a
GO:0098593    goblet cell theca | is_a
GO:0005730    nucleolus | is_a
GO:0045170    spectrosome | is_a
GO:0005818    aster | is_a
GO:0140453    protein aggregate center | is_a
GO:0032019    mitochondrial cloud | is_a
GO:0042151    nematocyst | is_a
GO:0005819    spindle | is_a
GO:0005856    cytoskeleton | is_a
GO:0002102    podosome | is_a
GO:0005814    centriole | is_a
GO:0044312    crystalloid | is_a
GO:0035770    ribonucleoprotein granule | is_a
GO:0005694    chromosome | is_a
GO:0005811    lipid droplet | is_a
GO:0000776    kinetochore | is_a
GO:0097727    blepharoplast | is_a
GO:0043292    contractile fiber | is_a
GO:1990934    nucleolus-like body | is_a
GO:0062159    contractile vacuole complex | is_a
GO:1990973    transmembrane actin-associated (TAN) line | is_a
GO:0031469    polyhedral organelle | is_a

**Comment by pgaudet** [comment]
@ValWood I assume that this is still not well defined. I will do NARROW SYNONYM for now, until the biological condensates are better defined.

OK ?

**Comment by ValWood** [comment]
Fine for me- I would not fancy trying to define it right now ;)

**Comment by hattrill** [comment]
That sounds like the best solution for now. I think that this is something that we would like to look at in the future - even if to say that it's not within the scope of the GO, as there is interest from our community - but more a future thing and not now thing for us. I too "I would not fancy trying to define it right now ;)"

**Comment by colinlog** [comment]
These are definitely a relevant type of CC and for eukaryotic transcription they appears to be functional, in the sense that specific protein domains drive this physical phenomenon inside a living cells' nucleus. Therefore, an MF  liquid-liquid phase separation (LLPS) would be fitting as companion for this CC, and that is also what the disordered protein community is wishing for, isn't it? 

There is indeed a (to be verified/curated - and I also do not fancy taking that task on by myself -) set of existing GO CC terms that emerge as LLPS-driven cellular compartments. Thus, 'non-membrane bound cellular compartment' would be a good synonym/ancestor term. However, the ribosome itself has been labeled as a 'non-membrane-bound cell compartment' even though it is not a LLPS droplet. Perhaps the ribosome could officially go back to being a 'RNA-protein COMPLEX' rather than an organelle, to avoid a violation? After all, the only reason that the ribosome has 'organellar status' is that it is so lrge as to be visible in historical electron micropgraphs and therefore was labelled a cellular ultrastructural feature / organelle. However, from classic crystallography and new EM work, it is clear that the ribosome is not a liquid-liquid phase separated compartment, rather it is a consistently structured complex that uses hydrophobic water-excluding protein-interfaces together with electrophylic interactions to attain its structure, which is NOT disordered, as such. 

I concur with Val that LLPS cannot be considered a process, it is a CC that emerges when proteins with the MF LLPS are 'active' and this helps drive a multitude of (but not all/any) BPs, including transcription regulation.

**Comment by pgaudet** [comment]
@colinlog Are you saying that all other children of 'non-membrane-bounded organelle' shown in the comment above https://github.com/geneontology/go-ontology/issues/21881#issuecomment-889820337 , except for ribosome, are biological condensates?

**Comment by pgaudet** [comment]
Added 'biological condensate' as a NARROW synonym of non-membrane-bounded organelle.

**Comment by ValWood** [comment]
biological condensate | narrow
should probably be 'related'.

Condensates are not restricted to non-membrane bound organelles
(cdc15  & co in the cytokinetic ring- the cytokinetic ring is membrane bound).

I still think we should be wary of trying to align componets with condensates, they are orthogonal (a condensate is an emergent property of some  interactomes)

**Comment by pgaudet** [comment]
Changed the synonym scope. I dont think more work is needed right now for this, people can find 'condensate' in GO if they look for it, and will see that we dont consider it a specific CC. 

Thanks, Pascale

**Comment by cmungall** [comment]
What about adding a PATO axiom to specific INMBOs and other components?

**Comment by hattrill** [comment]
tagging @gantonazzo
