### ISSUE TITLE
Term merge: GO:0019951 Smt3-protein conjugation & GO:0016925 protein sumoylation

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#21890]
**Term to be merged: Provide GO ID and term label**
GO:0019951 Smt3-protein conjugation (def:  The covalent addition to a protein of Smt3, a ubiquitin-like protein.)

**Which term do you propose this term merge into? Provide GO ID and term label**
GO:0016925 protein sumoylation (def: The process in which a SUMO protein (small ubiquitin-related modifier) is conjugated to a target protein via an isopeptide bond between the carboxy-terminus of SUMO with an epsilon-amino group of a lysine residue of the target protein.)

**Reason for merge**
- Smt3 is the S. cerevisiae SUMO protein
- GO:0019951 doesn't have any annotations

**Any other information**
Also review GO:0019951 parent: GO:0019950 SMT3-dependent protein catabolic process (no annotations)

**Comment by pgaudet** [comment]
How about merging into  GO:0140082  SUMO-ubiquitin ligase activity? 

We should also deal with GO:0019950 SMT3-dependent protein catabolic process 
It cannot be merged into     GO:0019940  obsolete SUMO-dependent protein catabolic process  - was obsoleted because "This term was made obsolete because it does not reflect an accurate biological process, as sumoylation of a protein does not lead to catabolism of that protein." - Is this true? Uniprot https://www.uniprot.org/uniprot/P61956 states "Polymeric SUMO2 chains are also susceptible to polyubiquitination which functions as a signal for proteasomal degradation of modified proteins (PubMed:18408734, PubMed:18538659, PubMed:21965678, PubMed:9556629)." - maybe GO:0019940  should be restored - or SMT3-dependent protein catabolic process  be obsoleted.

Thanks, Pascale

**Comment by sjm41** [comment]
_How about merging into GO:0140082 SUMO-ubiquitin ligase activity?_
Do we really want to merge a BP term (GO:0019951) with a MF term (GO:0140082)?
If we do, then we should probably look at the more general MF term "GO:0019789 SUMO transferase activity"?
But why not merge with "GO:0016925 protein sumoylation"??

_We should also deal with GO:0019950 SMT3-dependent protein catabolic process_
I'm no expert here, but I think it's true the sumoylation is not a (primary) degradation signal - I think that UP sentence is just saying the sumoylation may lead to polyubiquitination, and that polyubiquitination leads to degradation.  Given this, and the fact there are no annotations to GO:0019950, I'd vote for obsoleting it.

**Comment by raymond91125** [comment]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0019950 SMT3-dependent protein catabolic process
* **Reason for deprecation**
SMT3-dependent protein modification does not lead to protein degradation directly.
* **"Replace by" term (ID and label)** *
none 
* **"Consider" term(s) (ID and label)**
none

* **Are there annotations to this term?**
none

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
none
* **Is this term in a subset? (check the AmiGO page for that term)**
no
* **Any other information**
We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on August 16th. Unless objections are received by August 15th, we will assume that you agree to this change.
