### ISSUE TITLE
Amend Taxon constraint:  NADH dehydrogenase complex 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#21901]
GO:0030964 | NADH dehydrogenase complex | Never in Taxon | 4751 | Fungi |  
-- | -- | -- | -- | -- | --

Some fungi have complex I e.g. Y lipolytica
https://elifesciences.org/articles/39213

"We report the cryo-EM structure of complete mitochondrial complex I from the aerobic yeast Yarrowia lipolytica both in the deactive form and after capturing the enzyme during steady-state activity." 

Pombe and cerevisiae do not have it, but other yeasts are known to have it - N. crassa?

**Comment by ValWood** [comment]
Actually, the "NADH dehydrogenase complex term" might be OK even for pombe and cerevisiae.  They  do not have GO:0005747    mitochondrial respiratory chain complex I
but the do have NADH dehydrogenase.

Some other yeast do have complex I, which is why the original taxon constraints were added only for fission and budding yeast. The taxonomic distribution of the complex is quite strange.

GO:0005747    mitochondrial respiratory chain complex I is a large (>40 subunit complex, although the def says 25, I remember an early bovine paper where the number was over 40). Complex I probably has additional  roles, and is absent from fission and budding yeast *except* for a couple of subunits (MF unknown) that are not related to the NADH dehydrogenase activity. They are possibly something to do with iron cluster assembly.

Part of the weirdness might derive from 'generalising ' complex I
so that it can be used by bacteria for the "NADH dehydrogenase." activity.

All I know is, that based on protein complex subunit presence, these 2 taxon constraints are correct:

GO:0005747 | mitochondrial respiratory chain complex I | Never in Taxon | 4895 | Schizosaccharomyces |  
GO:0005747 | mitochondrial respiratory chain complex I | Never in Taxon | 4930 | Saccharomyces

I don't know about any of the other taxon constraints.

**Comment by pgaudet** [comment]
so, do we remove taxon constraints from NADH dehydrogenase complex?

**Comment by pgaudet** [comment]
Removed  GO:0030964 | NADH dehydrogenase complex | Never in Taxon | 4751 | Fungi

**Comment by ValWood** [comment]
That should work...
