### ISSUE TITLE
NTR: molecular condensate scaffold activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#21937]
Please provide as much information as you can: 

* **Suggested term label:**
* molecular condensate scaffold activity

* **Definition (free text)**
Binding and bringing together two or more macromolecules in contact, permitting those molecules to organize as a molecular condensate.

* **Reference, in format PMID:#######**
PMID:28225081

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0030674 protein-macromolecule adaptor activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
liquid condensate scaffold activity EXACT 

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
For IDPO alignment - requested by DisProt group @federicaquaglia @esalladini

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140693
+name: molecular condensate scaffold activity
+namespace: molecular_function
+def: "Binding and bringing together two or more macromolecules in contact, permitting those molecules to organize as a molecular condensate." [PMID:28225081]
+is_a: GO:0030674 ! protein-macromolecule adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/21937 xsd:anyURI
+created_by: pg
+creation_date: 2021-08-09T15:13:52Z

**Comment by ValWood** [comment]
I want to tag this publication in this ticket for future reference, because it describes "phase separation" as an activity, rather than a process, and this term might eventually morph into such an activity?

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7341897/
Phase-separation, is an emergent property of multivalent scaffold proteins that are present at high local concentration and display liquid-like behavior.

and from the abstract:
We suggest the CPC combines phase-separation, kinase, and histone code reading activities to enable the formation of a chromatin body with unique biochemical activities at the inner-centromere.
