### ISSUE TITLE
NTR: [chromatin-nuclear membrane anchor activity]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22081]
Please provide as much information as you can: 

* **Suggested term label:**
we have
GO:0062239    heterochromatin-nuclear membrane anchor activity
and
GO:0062240   euchromatin-nuclear membrane anchor activity
but for 
https://www.japonicusdb.org/reference/PMID:24184107
we need a parent
GO:XXXXX    chromatin-nuclear membrane anchor activity

because  these experiments are looking at condensed chromosomes in. mitosis and I don't know which it is.

* **Definition (free text)**
based on children:
Binding to chromatin and the nuclear inner membrane, in order to establish and maintain the heterochromatin location and organization, or  to enable equal segregation of the nuclear membrane during mitosis.

* **Reference, in format PMID:#######**
PMID:24184107

* **Gene product name and ID to be annotated to this term**
S. japonicus man1

* **Parent term(s)**
GO:0043495    protein-membrane adaptor activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
See above

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140707
+name: chromatin-nuclear membrane anchor activity
+namespace: molecular_function
+def: "Binding to chromatin and the nuclear inner membrane, in order to establish and maintain the heterochromatin location and organization, or to enable equal segregation of the nuclear membrane during mitosis." [PMID:24184107]
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22081 xsd:anyURI
+created_by: pg
+creation_date: 2021-09-02T06:18:21Z


+ moved GO:0062239 heterochromatin-nuclear membrane anchor activity
and
GO:0062240 euchromatin-nuclear membrane anchor activity under the new term
