### ISSUE TITLE
missing parent/superclass GO:0009098	leucine biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22096]
GO:0009098 | leucine biosynthetic process
should be is_a
GO:0009081 | branched-chain amino acid metabolic process

**Comment by pgaudet** [comment]
There was an issue with the use of the amino acid versus its conjugate in the logical definition (valine had the same issue): 
In the branch describing branched amino acids, we had valine, leucine and isoleucine. However some terms (like the metabolism terms and some transport terms) were using valinate and leucinate in the LD. I changed to the most common forms - but maybe I should have edited the children of 'branched amino acids'? not sure how to do this, since that 's not part of GO.

**Comment by ValWood** [comment]
Is it inferred from ChEBI?

**Comment by pgaudet** [comment]
> Is it inferred from ChEBI?

I think so, but I am not sure. I'd like to check with @cmungall
