### ISSUE TITLE
Distinguish hemopoiesis in vertebrates and in insects 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22178]
Hemopoiesis is creating taxon constraints issues, see #16298

We need your input @hattrill

**Comment by pgaudet** [comment]
Likewise for the renal system, Malpighian tubule development

**Comment by hattrill** [comment]
will look at this.

**Comment by hattrill** [comment]
We've had issues with renal terms before: https://github.com/geneontology/go-ontology/issues/18307

I think that the issue here stems from 'urogenital system development' rather than 'renal system development' - but I could be wrong.
In Uberon 'renal system' is kept "separate" from 'genitourinary system' (UBERON:0004122)
<img width="338" alt="Screenshot 2021-09-22 at 13 46 49" src="https://user-images.githubusercontent.com/11865746/134350626-be613546-bb78-492c-ae34-64aff8c23865.png">

<img width="256" alt="Screenshot 2021-09-22 at 13 46 07" src="https://user-images.githubusercontent.com/11865746/134350661-7305ea49-9b3a-40eb-951c-1b2c23094474.png">

Thus, malpighian tubules are part of the renal system.

In GO, renal system development is part of urogenital system development 


<img width="457" alt="Screenshot 2021-09-22 at 14 15 40" src="https://user-images.githubusercontent.com/11865746/134352221-e844ce3c-775f-4d6b-801a-6ab9a12a4706.png">

Not sure if this is massively useful grouping term - only renal, prostate and cloaca development under it. I think system is more of a functional grouping rather than anything (renal system = The renal system in an anatomical system that maintains fluid balance and contributes to electrolyte balance, acid/base balance, and disposal of nitrogenous waste products). 

Only 18 exp terms to urogenital system development (125 in total) and I expect these could be more precise.

What would happen if we 'uncoupled' urogenital system development and renal system development or obsoleted urogenital system development?

**Comment by hattrill** [comment]
WRT hemopoiesis, I think that the fundamental issue is that the current definition is under an organ system development whereas insect hemopoiesis occurs in circulating cells. 
So, I think that we could look at moving the annotations/terms under hemocyte development/differentiation - which is insect specific. We have specific terms for the 3 types of D.mel cell differentiation terms - I will have to look at the papers to see what we wanted to capture.

**Comment by raymond91125** [comment]
I think perhaps the Vertebrata taxon restriction should not be placed on hemopoiesis as it is relevant to diverse animals, see PMID:30733377.

Figure 1. Phylogenetic tree depicting key events during the evolution of metazoan blood cells. HSCs, hematopoietic stem cells.
![image](https://user-images.githubusercontent.com/619520/177621784-62ed27cd-71d4-44e9-962c-8e3fc5079874.png)

**Comment by raymond91125** [comment]
Regarding renal system development, perhaps change
renal system development part_of urogenital system development
to
urogenital system development has_part renal system development

**Comment by raymond91125** [comment]
@pgaudet Do you think the two proposed changes are sufficient?
1. hemopoiesis should not be restricted to vertebrates
2. urogenital system development has_part renal system development

Thanks.

**Comment by pgaudet** [comment]
@hattrill would know better than me

**Comment by hattrill** [comment]
> Thanks. That seems to me as if it would fix the issues.

**Comment by raymond91125** [comment]
I think GO:0030097 hemopoiesis should be a cell type development rather than the current IS_A GO:0048534 hematopoietic or lymphoid organ development.
https://en.wikipedia.org/wiki/Haematopoiesis
I propose a LD:  'developmental process' and ('results in development of' some CL:0000988 hematopoietic cell).
Makes sense? @ukemi @hattrill  Thanks.

**Comment by hattrill** [comment]
@raymond91125 that seems a better LD t to me

**Comment by raymond91125** [comment]
I hope all the issues have been resolved. If not, please reopen. Thanks, everyone.
