### ISSUE TITLE
Missing parent: transmembrane protein dislocase activity (GO:0140567)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22209]
* **GO term ID and label for which you request a new superclass**
transmembrane protein dislocase activity (GO:0140567)

* **New superclass (parent) suggested**
Maybe change current parent of "GO:0140318 protein transporter activity" to "ATPase-coupled transmembrane transporter activity"
OR
add "ATP-dependent activity (GO:0140657)"

* **Reference(s), if appropriate**
See definition of current Rhea xref: https://www.rhea-db.org/rhea/66168

**Comment by pgaudet** [comment]
Thanks for pointing this out. Note that this is not a transmembrane transporters, it extracts proteins from membranes. I added the parent "ATP-dependent activity (GO:0140657)", and added to the definition 

"The activity of removing a protein from a membrane, by binding to a transmembrane helical fragment of a tail-anchored protein and releasing it from the the hydrophobic region of one or both lipid bilayers. **The reaction is driven by ATP hydrolysis."**


@sylvainpoux tagging you since you originally requested the term. 

Thanks, Pascale
