### ISSUE TITLE
NTR: endothelial cell tube formation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#22302]
Please provide as much information as you can: 

* **Suggested term label:**

endothelial cell tube formation

* **Definition (free text)**

The developmental process pertaining to the initial formation of an endothelial tube.

* **Reference, in format PMID:#######**

PMID:8442917

* **Gene product name and ID to be annotated to this term**

Dicer1, RGD:1309381

* **Parent term(s)**

endothelial tube morphogenesis” (GO:0061154)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by krchristie** [comment]
>* **Parent term(s)**  
> endothelial tube morphogenesis” (GO:0061154)

This term is not an appropriate is_a parent for 'endothelial tube formation' as the new term for **formation** is **part of** 
**morphogehesis**. I have represented this part_of relationship with a direct subClass assertion:

`'part of' some 'endothelial tube morphogenesis'`

I have chosen "endothelial tube formation (GO:0072175)" as the is_a parent for your new term "endothelial tube formation" 

______

FYI for GO editors: 

I have removed this directly asserted SubClass:
`is_a: GO:0035148 ! tube formation`

since it was redundant with the Equivalence Axiom:
```
intersection_of: GO:0035148 ! tube formation
intersection_of: results_in_formation_of UBERON:0003914 ! epithelial tube
```
