### ISSUE TITLE
GO:0005337

### ISSUE THREAD

**Issue by amorgat** [geneontology/go-ontology#22376]
Hi @hdrabkin, @pgaudet 
In the current release (Rel 119) GO:0005337 is linked to 2 Rhea reactions
| RHEA:27318 | uracil(in) =   uracil(out) |   
| RHEA:33163 | β-nicotinamide D-riboside(in) =   β-nicotinamide D-riboside(out)|  

GO:0005337 is a parent term describing nucleoside transmembrane transporter activity
Please, would your remove the links to Rhea
BTW, I have trouble with RHEA:27318 quartet - it will be replaced by RHEA:69404 uracil(in) = uracil(out) in Rhea Rel 121

**Comment by hdrabkin** [comment]
I only see GO:0005337 linked to one RHEA in our editor's file, RHEA:27318 (we cannot have more than one exactMatch RHEA per term).  Uracil is a base, not a nucleoside (base+ sugar), so the term is incorrectly mis-mapped anyways.
I will remove it now. 
It COULD be used as for GO:0015210,  uracil transmembrane transporter activity. 
I've noticed that there is no parent/child between nucleobase transmembrane transporter activity, and
uracil transmembrane transporter activity.
adenine transmembrane transporter activity
cytosine transmembrane transporter activity
guanine transmembrane transporter activty

@pgaudet , was this intentional?  If not I can add the nucleobase transmembrane transporter activity, parentage to the 4 nucleobase transporter activities 

RHEA:33163 is only currently linked to GO:0034257

**Comment by pgaudet** [comment]
@amorgat 
I have no idea why RHEA has the mapping RHEA:33163 <->GO:0005337

It's not on snapshot (Nov 8th), it's not in the current release
http://release.geneontology.org/2021-10-26/ontology/external2go/rhea2go
neither in the September one
http://release.geneontology.org/2021-09-01/ontology/external2go/rhea2go
nor August
http://release.geneontology.org/2021-08-18/ontology/external2go/index.html
or July
http://release.geneontology.org/2021-07-02/ontology/external2go/index.html
June 
http://release.geneontology.org/2021-06-16/ontology/external2go/index.html
May
http://release.geneontology.org/2021-05-01/ontology/external2go/index.html


Do you? This is very strange.

**Comment by pgaudet** [comment]
@hdrabkin 

The relations between nucleobase transmembrane transporter activity, and
uracil transmembrane transporter activity.
adenine transmembrane transporter activity
cytosine transmembrane transporter activity
guanine transmembrane transporter activty
are there, just indirect 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/4782928/141278308-4e19ce59-8780-4292-9385-678dada13b85.png">

**Comment by hdrabkin** [comment]
@pgaudet 
AHA! I didn't look at indirect, only direct. Ok, I removed the  uracil nucleobase term from the nucleoside transporter term, so I can close this.
