### ISSUE TITLE
Term merge: GO:0002142 stereocilia ankle link complex & GO:1990696 USH2 complex

### ISSUE THREAD

**Issue by sandraorchard** [geneontology/go-ontology#22379]
GO:0002142 stereocilia ankle link complex

* **Which term do you propose this term merge into? Provide GO ID and term label**  GO:1990696 USH2 complex

* **Reason for merge** They are synonyms for the same entity. Component list in GO:1990696 is correct. In GO:0002142 Vlgr1=ADGRV1 and is a component of USH2, Vezatin has only been shown to colocalise with the complex.

* **Reference(s)** PMID: 25406310 (USH2), PMID: 33193648 "The USH2 proteins usherin, ADGRV1, and whirlin interact with one another to form a multiprotein complex called the ankle link (or USH2) complex within the cytoplasmic region of ankle links.....The formation of the USH2 quaternary protein complex relies on the heterodimerization between PDZD7 and whirlin...."

USH2 complex seems to winning out as the preferred name.

**Comment by krchristie** [comment]
Thanks for reporting this @sandraorchard 

I'm on vacation for various reasons from November 11-26, so I'll work on this once I'm back.

-Karen

**Comment by krchristie** [comment]
Hi @sandraorchard 

One of the papers you cite:

Chen Q, et al. **Whirlin and PDZ domain-containing 7 (PDZD7) proteins are both required to form the quaternary protein complex associated with Usher syndrome type 2**. J Biol Chem. 2014. 289(52):36070-88. PMID: 25406310

> talks about how the "USH2A, GPR98, WHRN, and PDZD7 genes have been found to express in inner ear hair cells and retinal photoreceptors"

and goes on to talk about the USH2 complex in photoreceptors and how it may have a different composition than the USH2 complex in hair cells:

> PDZD7 localization could not be determined in mouse photoreceptors in our previous study (16). Additionally, unlike in inner ear hair cells, where PDZD7 is essential for the normal localizations of USH2A, GPR98, and WHRN (16), knockout of Pdzd7 expression in mouse photoreceptors does not affect the localizations of the three USH2 proteins at the periciliary membrane complex (16). These findings suggest that PDZD7 is dispensable for the **USH2 complex formation in photoreceptors**.

Thus, I think that merging theses two terms is not appropriate:

```
id: GO:1990696
name: USH2 complex
namespace: cellular_component
def: "A protein complex composed of four proteins, loss of which results in Usher Syndrome type 2 (USH2 syndrome), a leading genetic cause of combined hearing and vision loss. This complex is conserved in many species; in mice, it is composed of USH2A, GPR98 (aka ADGRV1), WHRN, and PDZD7." [GOC:krc, PMID:25406310]
synonym: "USH2 quaternary protein complex" EXACT []
is_a: GO:0032991 ! protein-containing complex
created_by: krc
creation_date: 2015-03-12T17:29:18Z

id: GO:0002142
name: stereocilia ankle link complex [0 annotations]
namespace: cellular_component
def: "A complex of proteins that connect growing stereocilia in developing cochlear hair cells, composed of Vlgr1, usherin, vezatin, and whirlin." [PMID:16775142]
is_a: GO:0032991 ! protein-containing complex
relationship: part_of CL:0000000 ! cell
relationship: part_of GO:0002141 ! stereocilia ankle link
created_by: hjd
creation_date: 2009-05-06T10:33:57Z
```

However, there is also this term:
```[Term]
id: GO:0002141
name: stereocilia ankle link [0 annotations]
namespace: cellular_component
def: "A stereocilia coupling link that is composed of a fine filament present in developing stereocilia that couples the bases of individual stereocilia to one another. They are not present in mature stereocilia." [PMID:17567809]
is_a: GO:0002139 ! stereocilia coupling link
created_by: hjd
creation_date: 2009-05-06T10:31:56Z
```

and I'm not really sure what the difference between the two terms **stereocilia ankle link complex** and**stereocilia ankle link** are or whether we actually need two terms here.

I'm also thinking that they existing term for **USH2 complex** may need some further thought since the same name is used for complexes containing USH2 in two different locations, but which may have slightly different compositions in the two different locations.

I'm not to the point of having a clear idea how to proceed, but wanted to let you know I'm working on this now.

**Comment by raymond91125** [comment]
@sandraorchard Do you still think the merge should take place? I guess the key issues are that whether PDZD7 is a core component of the USH2 complex and whether Vezatin is a core component of stereocilia ankle link complex. If not for both, we can revise the definition of USH2 complex and then merge with stereocilia ankle link complex. Otherwise, perhaps we should leave them alone.

**Comment by raymond91125** [comment]
I'm closing this issue for now. If there are new inputs, we can reopen.
