### ISSUE TITLE
NTR: [Self-resistance to endogenously produced compounds ]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#22413]
In the frame of the annotation of natural products biosynthesis, I would propose a new BP term associated with self-resistance. Many secondary metabolites produced by many prokaryote and eukaryote species have potent biological activities, to which the producer organism must be resistant. An example of pharmaceutical interest is mycophenolic acid (MPA), an immunosuppressant molecule produced by several Penicillium species. If the producing organism contains the targeted pathway or cellular components, then it is required that it evolves a way to prevent self-toxicity.

BP:
"Self-resistance to endogenously produced compounds"
or
"Self-resistance"

Definition: Mechanism of resistance that prevents self-toxicity towards an endogenously produced compound. 

PMID:29763292,  21923907

Gene products:
W6QIT2, F1DBB2

Parent term:
GO:0006952 defense response

I would not create any child terms specific to the various compounds.

Thanks a lot.
Best regards,
Marc.

**Comment by pgaudet** [comment]
Hi @marcfeuermann 
Could this go under 'detoxification'? def is "Any process that reduces or removes the toxicity of a toxic substance. These may include transport of the toxic substance away from sensitive areas and to compartments or complexes whose purpose is sequestration of the toxic substance."

This seems better aligned than 'defense response', which is 'Reactions, triggered in response to the presence of a foreign body or the occurrence of an injury, which result in restriction of damage to the organism attacked or prevention/recovery from the infection caused by the attack.'

What do you think? 

Thanks, Pascale

**Comment by marcfeuermann** [comment]
Hello @pgaudet,
Yes indeed your proposal sounds by far better. I was searching for a good parent and missed the detoxification term.
Thanks a lot.
Marc.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140729
+name: self-resistance to endogenously produced metabolite
+namespace: biological_process
+def: "A process that reduces or removes the toxicity of an endogenously produced substance. Mechanisms of resistance to endogenously produced compounds include modification the compound, export, sequestration, or mutations in the target enzyme." [PMID:21923907, PMID:29763292]
+synonym: "prevention of self-toxicity" EXACT []
+synonym: "self-resistance to bioactive secondary metabolite" EXACT []
+synonym: "self-resistance to endogenously produced compound" EXACT []
+synonym: "self-resistance to endogenously produced toxin" EXACT []
+is_a: GO:0098754 ! detoxification
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22413 xsd:anyURI
+created_by: pg
+creation_date: 2021-11-24T06:32:14Z
+
