### ISSUE TITLE
New Generic GO slim - MF subset

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22482]
Hello, 

With @hattrill @ValWood and @RLovering we have produced a new generic subset for MF

It has much fewer binding terms (6, while the current has 16)

Terms in the new generic subset: 

GOID	Term label
GO:0003774	cytoskeletal motor activity
GO:0005198	structural molecule activity
GO:0005215	transporter activity
GO:0009975	cyclase activity
GO:0016209	antioxidant activity
GO:0016491	oxidoreductase activity
GO:0016740	transferase activity
GO:0016787	hydrolase activity
GO:0016829	lyase activity
GO:0016853	isomerase activity
GO:0016874	ligase activity
GO:0031386	protein tag
GO:0032451	demethylase activity
GO:0038024	cargo receptor activity
GO:0044183	protein folding chaperone
GO:0045182	translation regulator activity
GO:0045735	nutrient reservoir activity
GO:0060089	molecular transducer activity
GO:0060090	molecular adaptor activity
GO:0090729	toxin activity
GO:0098772	molecular function regulator
GO:0140096	catalytic activity, acting on a protein
GO:0140097	catalytic activity, acting on DNA
GO:0140098	catalytic activity, acting on RNA
GO:0140104	molecular carrier activity
GO:0140110	transcription regulator activity
GO:0140223	general transcription initiation factor activity
GO:0140299	small molecule sensor activity
GO:0140313	molecular sequestering activity
GO:0140657	ATP-dependent activity
GO:0140691	RNA folding chaperone
GO:0003723	RNA binding
GO:0008092	cytoskeletal protein binding
GO:0003677	DNA binding
GO:0008289	lipid binding
~GO:0019899	enzyme binding~
GO:0042393	histone binding

For human, the new goslim-generic-mf has better coverage: using the Princeton GOTerm mapper tool, 3987 annotated genes were not in the slim, compared to 4823 with the current goslim-generic (my notes are here: https://docs.google.com/document/d/18BEPHcayvuq4m0QWCCRzDVaOdojMQiYgH2H6ZGBmw6A/edit#) 

If there are no objections, I'll implement that. 

Thanks, Pascale

**Comment by ValWood** [comment]
consider
cell adhesion mediator activity (GO:0098631)? (currently a binding term, but should probably be a molecular function has_part binding?)


note 
GO:0140691 RNA folding chaperone has only a single annotation in the entire GO. Maybe RNA binding would suffice for now?

**Comment by hattrill** [comment]
> GO:0140691 RNA folding chaperone has only a single annotation in the entire GO. Maybe RNA binding would suffice for now?

Agreed

**Comment by RLovering** [comment]
Hi 
I don't know enough about RNA chaperones or RNA folding to know how many proteins are involved in the process. However, I am concerned that unless there has been an annotation project focused on this area it is difficult to be sure whether this term is required.
In addition, following from our recent MF SLIM discussions where the 'binding' domain of GO was considered to be excluded, and then included I have realised that more MF terms are required for RNA functions.
This article https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC6086601/ suggests that the MF term should stay but that an annotation project should focus on populating this term with relevant gene products.

**Comment by ValWood** [comment]
Wouldn't it be better to review the slims annually to check coverage and bring in newly populated terms (and remove binding terms) . Otherwise it looks odd  to have terms in the slim with no annotations.

**Comment by deustp01** [comment]
Time to phjlosophize. What is the purpose of a slim? To provide a balanced summary of all of biology, or a summary skewed towqard intensively studied areas of it? And if an important use of slims is comparative data analysis, isn't stability of a slim over time important to allow reliable comparison between analyses? (An archive of old slims could address this issue, but that probably comes with some management problems.)

**Comment by RLovering** [comment]
Maybe we should contact this group https://www.phd-rna-biology.at/network/
and although this is a 2007 article perhaps ask them for a list of RNA chaperones based on this
https://www.tandfonline.com/doi/pdf/10.4161/rna.4.3.5445?needAccess=true (the website list in this article doesn't work www.projects.mfpl.ac.at/rnachaperones).
However, this brings in the idea that RNA chaperones have a variety of activities some of which I know you would want to classify as processes ;(
See Fig 1 (this is about the assays but I think these descriptions are useful):
A) RNA chaperone activity (RCA) on double-stranded RNA can result in:
-  helix destabilization (duplex unwinding)
- full strand dissociation (RNA melting) 
- strand displacement (strand exchange)
(B and E) Cis-splicing: Proteins with RCA significantly increase the population of pre-RNA molecules with splicing competent conformation. 
(C) Trans-splicing: if the pre-RNA is transcribed in two pieces, which have to anneal for the formation of an active ribozyme. Proteins with RCA facilitate trans-splicing by bringing 2 RNAs together appropriately. 
(D) RCA may resolve misfolded hammerhead ribozyme complexes (requires two activities—annealing and strand displacement). 
(F) RCA may resolve misfolded to prevent early transcription termination.

The article then defines specific protein families:
1. Heterogeneous  nuclear  ribonucleoproteins  (hnRNPs).
- hnRNP  I  and  hnRNP  K  are  active  in  splicing  assays
- hnRNP  A1  was  demonstrated  to  enhance hammerhead ribozyme cleavage.
- hnRNP  A1,  hnRNP  C1/C2,  hnRNP  U,  hnRNP K and hnRNP I promote RNA annealing.
2. Cold  shock  domain  proteins  (CSPs) (9 CSPs in E. coli)
- CspA and CspE function as  transcription  antiterminators  or  translational  enhancers  at  low temperature,  where  RNA  secondary  structures  become  inhibitory. 
- ribosomal  protein  S1  has  RNA  chaperone activity in the context of ribosomal proteins.
- translation initiation factor 1 (IF1), has RNA chaperone activity: splicing of  a  misfolded  intron  and resolves terminator stem.
- in eukaryotes: YB-1,  which  is  a  general  regulator  of  translation  by  modulating mRNA  structural  rearrangements  and  packaging. promotes  non-specific  strand  displacement  and  annealing  of  both RNA and DNA.
3. Ribosomal  proteins. 
- RCA activity suggested for S1, S12, L1, L3,  L13,  L15,  L16,  L18,  L19,  L22  and  L24
4. Histone-like proteins from bacteria.
5. Viral  nucleocapsid  proteins  (NCps)

Then classifies these according to 'function':
RNA Annealers 
DEXD/H-BOX (RNA heliicases)
plus RCAs intrinsically  unstructured proteins

Interesting statements from another article:
https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC7404189/

- cotranscriptional RNA folding constitutes a dynamic and intricate process so Colin maybe able to shed light on the RNA chaperones at the transcriptional level.
- RNA Modifications, Editing and Sequence Composition as affecting the RNA structure.
- Helicases comprise the largest group of transient remodelers of DNA and RNA structural arrangement: Some of them translocate along an RNA strand, unwind RNA duplexes, and displace proteins, while others are capable of solely unwinding dsRNA regions and/or mediating RNA-annealing
- RBPs exert local RNA structural alterations as well as changes of structural context of adjacent regions due to torsional stress and thermodynamic compensation of local alterations.
- I think Table 1 https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC7404189/table/ijms-21-05161-t001/ might provide a list of RBPs that modulate RNA structure.

Note that MF term  GO:0008248 obsolete pre-mRNA splicing factor activity removed because this is a process. Of the 353 human proteins associated with the GO term  GO:0008380 RNA splicing only 107 have MF annotations that are not a binding term. I have got the spreadsheet I used for this. But looking at just the first one I noticed without an MF (that was not a binding term) is https://www.uniprot.org/uniprot/P22626 prthe UniProt summary states: The hnRNP particle arrangement on nascent hnRNA is non-random and sequence-dependent and serves to condense and stabilize the transcripts and minimize tangling and knotting. Not sure which of the proteins in the hnRNP are responsible for the RNA chaperone activity but presumably some are.

**Comment by RLovering** [comment]
[RNA_chaperone.xlsx](https://github.com/geneontology/go-ontology/files/7627321/RNA_chaperone.xlsx)

**Comment by pgaudet** [comment]
Can we keep the RNA discussion on the RNA ticket? this work will not be done here ;)

**Comment by RLovering** [comment]
Good idea, but I have opened a separate ticket as I don't think this is relevant to RNA function terms
https://github.com/geneontology/go-ontology/issues/22499

**Comment by hattrill** [comment]
Yes to that. I think that it is not possible to capture all the GTPases in the way that all ATPases can be described as coupled.

**Comment by ValWood** [comment]
Agreed!

**Comment by pgaudet** [comment]
For GO:0003677 DNA binding, not including it excludes 313 proteins (whereas there are 1900 transcription regulators and 45 GTF. 

Most of the excluded proteins are histones - do we have a MF for histone? should we have something like 'structural constituent of nucleosome'?

**Comment by ValWood** [comment]
I don't like  'structural constituent of nucleosome'
it doesn't say anything about the role of histone. 

Recently we were discussing with @colinlog  the role of histones as 'signal integrators' through their role as adaptors.
Recently I have been using "chromatin-protein adaptor"
and recording the 'active' modified form.
https://www.pombase.org/term/GO:0140463

I don't know if this is perfect, but it is better than  'structural constituent of nucleosome', which makes it sound a bit inert.

It's funny histones have always been so poorly  considering their importance!

**Comment by pgaudet** [comment]
Should we keep DNA binding in the slim? 
Other than histones, I dont see what this group brings: shorturl.at/cnpLY

**Comment by ValWood** [comment]
I don't see any compelling reason to keep it. Can also explain to  curators why it is excluded and encourage people to annotate the histones.

Soon there will be annotations for most histones that can be "PAINTED" ( provided we are agreed about the term I used!), which can be discussed on the next call?

**Comment by RLovering** [comment]
sorry to be annoying but I prefer the name 'structural constituent of nucleosome' because most people know this will include histones. We have cell adhesion molecule, which doesn't convey that the majority of these are involved in signaling pathways. 'Chromatin-protein adaptor' is challenging for me because the histone is part of the chromatin. So it is weird to say it links chromatin to proteins. Plus I am not convinced that the function of the histone is always as an adaptor, the structural aspect is also key. 

In addition, https://www.abcam.com/epigenetics/histone-modifications points out that H1 is not in the nucleosome but stabilizes the 'internucleosomal DNA' and that "Some modifications disrupt histone-DNA interactions, causing nucleosomes to unwind. In this open chromatin conformation, called euchromatin, DNA is accessible to binding of transcriptional machinery and subsequent gene activation. In contrast, modifications that strengthen histone-DNA interactions create a tightly packed chromatin structure called heterochromatin. In this compact form, transcriptional machinery cannot access DNA, resulting in gene silencing." So - in heterochromatin are histones acting as adaptors? Maybe I am missing what is bound by the histones to enable the adaptor function term to be applied?

I think that the reason for a lack of histone annotations in humans is because of all the paralogs which make it difficult to know which protein has actually been investigated. So potentially most experiments would be considered as NAS evidence. 

Shouldn't we keep DNA binding in the SLIM until we have these 300 proteins assigned to an additional function?

**Comment by ValWood** [comment]
> the structural aspect is also key.

I guess "structural element of nucleosome" is one major activity, but also, and *really importantly* for epigenetics, transcription, chromosome segregation, is 
the activity of the modified forms (and we need to curate these connections to make the causal models). All of the modified forms have slightly *different* activities because they provide a 'platform' for different assemblies of signalling pathways or chromatin-modifying machineries, dependent on the individual modification(s). 
I have never felt that 'adaptor' was really the correct term. A lot of things called 'adaptors' are really ' recruiters'. I  just don't think we have a satisfactory label.
We need something like "modification-dependent recruitment activity", defined in a way that it does not need to be an "adaptor"  subclass (although some recruiters are also really adaptors so it gets complicated).

**Comment by ValWood** [comment]
A term like
 "modification-dependent recruitment activity"
would also work for the many other cases where a modification recruits another protein (sometimes the protein that performed the modification).

**Comment by ValWood** [comment]
>Slimming results for the human genome using the new generic GO slim:
What is the 'dropout' now?

**Comment by RLovering** [comment]
As GO doesn't really capture modifications or ion dependancies much why not just have 'recruitment activity' or 'chromatin-modifying recruitment activity' or 'nucleosome recruitment activity' I think there may be other proteins that 'recruit' only when they are modified. I am concerned that the term "modification-dependent recruitment activity" doesn't provide any information to the user about the function of the protein is. But I have a feeling that you won't want the location aspect included. Although there are a lot of MF terms with location included in the name.
I still think the structural role should also be captured as other structural proteins are annotated with this function. Plus as you say hopefully PAINT can apply these both terms across many histones ;)

**Comment by pgaudet** [comment]
I put this for discussion on a transcription call. Since Val cannot be there on Friday, lets discuss this next Monday.

**Comment by ValWood** [comment]
"As GO doesn't really capture modifications or ion dependancies much "

But the modifications are required to capture the biology. PomBase uses PRO to capture the modifications. It's really critical for the histones, but also for most  dynamic processes. See here for  examples: https://www.pombase.org/term/GO:0140463
The only issue is that the terms are not really generic enough currently.

I have also  with adaptor molecules for cytokinesis.

Probably the reason these are not curated is because a) there are not so many mechanistic paper, and b)  where there are they are quite complicated so curators avoid them and c) it only really becomes critical to capture the modification dependencies once you are curating pathways. Without this information the pathways don't make sense, because the outputs (pathway  active or inactive) depend on the modifications.

**Comment by pgaudet** [comment]
I put the histone MF as a discussion topic on a future transcription call, I am not sure when we'll all be around again, but this will be discussed before I make any changes. I'll keep DNA binding in the slim for now.

**Comment by pgaudet** [comment]
On the transcription call we decided to replace 'DNA binding' by 'structural constituent of chromatin'. 

@hattrill do you want to do the same for the drosophila slim?

**Comment by RLovering** [comment]
Are we ready to replace 'DNA binding' by 'structural constituent of chromatin'? how many gps drop out with this change?

**Comment by hattrill** [comment]
For now, I'd be happy just to add this term to the fly slim and keep  'DNA binding' as they are not an exact overlap and as I might want to do some reannotation here and see what falls out - I've used terms such as 'histone binding', and 'DNA binding' where they might be better as 'structural constituent of chromatin' - but at the moment, I only have 2 genes with this term used in annotation.

**Comment by pgaudet** [comment]
Discussion with @ValWood and @hattrill 

add 

* catalytic activity [GO:0003824] (to catch all catalytic activities that are NOT descendant of EC classes)
* transcription regulator activity [GO:0140110]
* virus coreceptor activity [GO:0120274]
* virus receptor activity [GO:0001618]

**Comment by pgaudet** [comment]
I added the last 4 terms above. I am closing this ticket, let's open new tickets if we want more changes.
