### ISSUE TITLE
Remove obsolete EC:1.11.1.15 from peroxiredoxin activity (GO:0051920 name) def

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#22598]
Please remove the obsolete EC:1.11.1.15 (or replace it with EC:1.11.1.24) in the attribution of the def on this term:

id: GO:0051920
name: peroxiredoxin activity
def: "Catalysis of the reaction: 2 R'-SH + ROOH = R'-S-S-R' + H2O + ROH." [EC:1.11.1.15, RHEA:10008]
comment: Includes redox chemistry as part of the catalytic reaction (2 R'-SH = R'-S-S-R'), where R' refers to peroxiredoxin itself). Not to be confused with GO:0004601 (peroxidase activity, EC:1.11.1.7), which has a different reaction mechanism.
xref: EC:1.11.1.24
xref: RHEA:10008

See https://enzyme.expasy.org/EC/1.11.1.15

**Comment by pgaudet** [comment]
It seems the entire branch represents the same activity? 

'peroxiredoxin activity' -> 
and children: 
'peroxynitrite reductase activity' -> 2 ISO, original evidence missing 
'thioredoxin peroxidase activity' -> 44EXP 
'tryparedoxin peroxidase activity' -> 1 EXP to a paper characterizing a 'peroxiredoxin' 


I think they all catalyze the same reaction? 

see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4509974/

**Comment by sjm41** [comment]
Are you considering merging those 3 children into the parent?

'thioredoxin peroxidase activity' at least has a specific RHEA xref (RHEA:63528), which is different to the RHEA xref on the parent term 'peroxiredoxin activity' (RHEA:10008), so there must be some difference there.

There are some other issues associated with this term, documented in https://github.com/geneontology/go-ontology/issues/23121

Main point here though was just to get rid of the obsolete EC number in the GO:0051920 definition.... :-)

**Comment by pgaudet** [comment]
yeah sorry I cant' help but to look at the branch...

**Comment by sjm41** [comment]
Thanks Pascale.

But I don't think EC:1.11.1.24 should be an xref to thioredoxin peroxidase activity (GO:0008379) - that GO term has xref of RHEA:63528 (which has no EC association), whereas RHEA:62620 has the EC:1.11.1.24 xref.

RHEA:63528:
[thioredoxin]-dithiol + a H2O2 = [thioredoxin]-disulfide + 2 H20

RHEA:62620 (EC:1.11.1.24):
[thioredoxin]-dithiol + a hydro peroxide = [thioredoxin]-disulfide + an alcohol + H20

This also means EC:1.11.1.24 should also be removed from the general term peroxiredoxin activity (GO:0051920).

I think we need to add a new GO term for RHEA:62620/EC:1.11.1.24 (if we want it)

**Comment by pgaudet** [comment]
> But I don't think EC:1.11.1.24 should be an xref to thioredoxin peroxidase activity (GO:0008379) -

I wondered about that, but EC describes both thioredoxin peroxidase activity (GO:0008379) AND thioredoxin peroxidase activity (GO:0008379): while the label is 'Thioredoxin-dependent peroxiredoxin', the description is clearly general for peroxidins. 

@kaxelsen how should we interpret the EC definition? just the reaction? I do usually take the comments into account. 

Thanks, Pascale

**Comment by kaxelsen** [comment]
The transfer note at expasy is unfortunately not completely covering the IUBMB information. This is because the curator tool I have been until now could only handle one-to-one transfers of EC numbers. At IUBMB the transfer note reads:

https://www.enzyme-database.org/query.php?ec=1.11.1.15
peroxiredoxin. Now described by EC 1.11.1.24, thioredoxin-dependent peroxiredoxin; EC 1.11.1.25, glutaredoxin-dependent peroxiredoxin; EC 1.11.1.26, NADH-dependent peroxiredoxin; EC 1.11.1.27, glutathione-dependent peroxiredoxin; EC 1.11.1.28, lipoyl-dependent peroxiredoxin; and EC 1.11.1.29, mycoredoxin-dependent peroxiredoxin.

So, there are actually 6 different types of peroxiredoxins, each with their own EC number and each using a different oxidant.

EC 1.11.1.24; RHEA:62620 [thioredoxin]-dithiol + a hydroperoxide = [thioredoxin]-disulfide + an alcohol + H2O
EC 1.11.1.25; RHEA:62624 [glutaredoxin]-dithiol + a hydroperoxide = [glutaredoxin]-disulfide + an alcohol + H2O 
EC 1.11.1.26; RHEA:62628 a hydroperoxide + H+ + NADH = an alcohol + H2O + NAD+
EC 1.11.1.27; RHEA:62632 a hydroperoxide + 2 glutathione = an alcohol + glutathione disulfide + H2O 
EC 1.11.1.28; RHEA:62636 (R)-N6-dihydrolipoyl-L-lysyl-[lipoyl-carrier protein] + a hydroperoxide = (R)-N6-lipoyl-L-lysyl-[lipoyl-carrier protein] + an alcohol + H2O
EC 1.11.1.29; RHEA:62640 [mycoredoxin]-L-dithiol + a hydroperoxide = [mycoredoxin]-L-disulfide + an alcohol + H2O

**Comment by pgaudet** [comment]
Thanks for your input @kaxelsen this is very useful! 


@sjm41 I removed EC:1.11.1.24 from GO:0008379 thioredoxin peroxidase activity 

I'm not sure what to do about the other reactions - should we wait to create them until there is a request? 

Also, GO has 2 other siblings, 
 *tryparedoxin peroxidase activity: [protein]-dithiol + ONOO- = [protein]-disulfide + NO2- + H2O: 1 IDA from [PMID:32388269](http://amigo.geneontology.org/amigo/reference/PMID:32388269 - also annotated to '[trypanothione-disulfide reductase activity](http://amigo.geneontology.org/amigo/term/GO:0015042)' 
* [is_a relation] [GO:0072541](http://amigo.geneontology.org/amigo/term/GO:0072541#display-lineage-tab) peroxynitrite reductase activity: tryparedoxin + hydrogen peroxide = tryparedoxin disulfide + H2O: 2 ISO annotations, no EXP 
* * ISO are with P30044, itself annotated to EC 1.11.1.24
* 
I dont how how/whether these relate to the list from @kaxelsen above. Looks like they dont and probably could be obsoleted?

**Comment by sjm41** [comment]
@pgaudet I commented on those sibling cases in #23121 - both should be moved to being children of "peroxidase activity" rather than "peroxiredoxin activity" IMO.

Yes, I wouldn't bother adding the other reactions Kristian mentions until there's a request for them.

Shall we close this ticket, and try to finish off the remaining edits in #23121?

**Comment by pgaudet** [comment]
yes! thanks
