### ISSUE TITLE
Obsoletion notice: 'C4-methyltransferase activity' and 'C4-demethylase activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22652]
Hello, 

The proposal has been made to obsolete 
GO:0102675 'C4-methyltransferase activity' and 
GO:0102674 'C4-demethylase activity'

The reason for obsoletion is that there is no evidence that these reactions exist. They link to non-existing MetaCyc entries: MetaCyc:RXN-4181 and MetaCyc:RXN-4208. 

There are no annotation, no mappings to these terms. These terms are not present in any subsets. 

Thanks, Pascale

**Comment by colinlog** [comment]
what about rRNA 4-c methylation? See for example PMID: 32371392 that points human METTL15 as such a 4-C cytosine mehylase.

**Comment by pgaudet** [comment]
This is not what this term was about- def: Catalysis of the reaction: 24-ethylidenelophenol + a demethylated methyl acceptor <=> avenasterol + a methylated methyl acceptor.

**Comment by pgaudet** [comment]
@colinlog I think the activity you refer to is GO:0071424 rRNA (cytosine-N4-)-methyltransferase activity

**Comment by alanbridge** [comment]
Hi Pascale, 

This term 

GO:0071424 rRNA (cytosine-N4-)-methyltransferase activity
Catalysis of the reaction: S-adenosyl-L-methionine + rRNA = S-adenosyl-L-homocysteine + rRNA containing N4-methylcytosine.

should that map to 

https://www.rhea-db.org/rhea/62520
a cytidine in rRNA + S-adenosyl-L-methionine = an N(4)-methylcytidine in rRNA + H(+) + S-adenosyl-L-homocysteine

All the best for 2022, Alan

**Comment by keseler** [comment]
Hi Pascale,

I asked our MetaCyc curator about these reactions, and here is his reply:

"Looks like these reactions were deleted because they were erroneous.

For example, look at RXN-4181. There is a still a copy of it online at
https://solcyc.solgenomics.net/LYCO/NEW-IMAGE?type=REACTION&object=RXN-4181

[...]

The actual process is described in current MetaCyc by the reactions RXN-19724, RXN-11933, and RXN-11934, which show how the methyl group is first oxidized (in three subreactions) to a carboxylate group by SMO1/SMO2 (EC 1.14.18.11), followed by decarboxylating dehydrogenase (EC  1.1.1.418), forming a sterone that is finally reduced by an unknown 3beta dehydrogenase to epistrol. If you count the subreactions, this process requires 5 reactions b y 3 different enzymes."

Just wanted to let you know about the history of these deletions.  You can see some updated reactions/enzymes here:
https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-2541&detail-level=2
compared to the original ones here:
https://solcyc.solgenomics.net/LYCO/NEW-IMAGE?type=PATHWAY&object=PWY-2541&detail-level=2

Cheers,
Ingrid

**Comment by pgaudet** [comment]
Thanks @keseler this is very helpful, I will check that we have the other reactions.
