### ISSUE TITLE
Changes to  GO:0070922  small RNA loading onto RISC

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22653]
- [ ]  GO:0070922  small RNA loading onto RISC -> do not annotate: should be able to annotae to a specific child (miRNA or siRNA)
- [ ] miRNA loading onto RISC involved in gene silencing by miRNA -> fix label to 'miRNA loading onto RISC'

**Comment by RLovering** [comment]
Hello,
 
Following up on our work from Monday – I was looking at the branch
* GO:0070922 small RNA loading onto RISC
* * GO:0035280 miRNA loading onto RISC involved in gene silencing by miRNA (removed cross-out part of the label as we agreed on Monday)
* * GO:0070923 siRNA loading onto RISC involved in gene silencing by small RNA
* * GO:0035087 siRNA loading onto RISC involved in RNA interference
 
The term ‘GO:0070923 siRNA loading onto RISC involved in gene silencing by small RNA’ seems to be talking about heterochromatin assembly by small RNA: the definition is ‘The process in which a single-stranded small RNA associates with the RNA-initiated silencing complex (RISC); occurs as part of a process of chromatin gene by small RNA.’
 
‘a process of chromatin gene » doesn’t mean anything, but I assume ‘silencing’ was omitted, so it would be ‘a process of chromatin gene silencing’
If this really does talk about heterochromatin assembly, is RISC involved? I thought RISC was only involved in post-transcriptional regulation. To this point, the definition of ‘GO:0016442 RISC complex’ is: ‘A ribonucleoprotein complex that contains members of the Argonaute family of proteins, small interfering RNAs (siRNAs) or microRNAs (miRNAs), and miRNA or siRNA-complementary mRNAs, in addition to a number of accessory factors. The RISC complex is involved in posttranscriptional repression of gene expression through downregulation of translation or induction of mRNA degradation.
There are only 2 Fly annotations to ‘GO:0070923 siRNA loading onto RISC involved in gene silencing by small RNA’ from a single paper, PMID:19684574. As fasr as I can tell, the paper did not do any experiments that would enable to distinguish whether the gene silencing occurs pre pr post-transcriptionally.
 
My conclusion is that ‘GO:0070923 siRNA loading onto RISC involved in gene silencing by small RNA’ in quite dubious, and that the RISC complex is only involved in post-transcriptional gene silencing by RNA.

**Comment by hattrill** [comment]
Ref for RISC Figure 3. Mechanisms of siRNA Silencing http://europepmc.org/article/MED/19239886

**Comment by ValWood** [comment]
From my understanding  RITS is a type of RISC complex:

https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC2709356/

The RNA-induced Silencing Complex: A Versatile Gene-silencing Machine*

"Transcriptional Silencing and Formation of Heterochromatin Beyond targeting mRNAs, some RISCs act directly on the genome. The best studied of these assemblies is the fission yeast RITS complex, which contains AGO1 with an associated siRNA, a protein called TAS3, and the chromodomain protein CHP1 (11). The RITS complex interrogates nascent transcripts as they are generated by RNA polymerase II in the nucleus. Upon target recognition, the complex recruits histone methyltransferases, which modify histones associated with the DNA locus, forming heterochromatin (40). The CHP1 subunit of the RITS complex specifically recognizes histone 3 proteins methylated at Lys9, further reinforcing the association of the RITS complex with heterochromatin (41). The RITS complex also physically interacts with an RNA-directed RNA polymerase complex, which converts the targeted transcripts into dsRNA. Dicer then cleaves the dsRNA into new siRNAs, which can be loaded into new RITS complexes, thereby establishing a self-perpetuating silencing loop. Although the level of molecular detail is less well understood in other systems, plants and animals contain analogous systems for small RNA-guided formation of heterochromatin (42). In particular, the Piwi clade appears to function in transcriptional silencing and formation of heterochromatin (18)."

So it  operates in heterochromatin assembly in fission yeast.

But  isn't "loading" a single step process that needs to be converted to an MF tem (so that we can us it in different contexts? This doesn't seem to belong in biological  process?

**Comment by pgaudet** [comment]
Annotations to small RNA loading onto RISC: https://docs.google.com/spreadsheets/d/1At5bS5hmNS8sZ7cgE8ncpl9_Hcs4oyn4h_bMnbbODLg/edit?usp=drive_web&ouid=116162935390241629304

**Comment by pgaudet** [comment]
id: GO:0070922
-name: small RNA loading onto RISC
change label to  RISC complex assembly


update def from "The process in which a single-stranded small RNA associates with the RNA-initiated silencing complex (RISC); occurs as part of a process of gene silencing by small RNA." [GOC:mah, PMID:19239886]
to "The process in which a single-stranded small RNA is incorporated within the RNA-initiated silencing complex (RISC). The assembly includes the maturation of the small RNA, the stabilization of the complex by accessory proteins of the RISC complex, duplex separation and the release of the second strand, forming a base-pairing completent complex that mediates gene silencing by small RNA." [PMID:19239886, PMID:22233755, PMID:27184117]


Thanks, Pascale

**Comment by ValWood** [comment]
OK by me
