### ISSUE TITLE
NTR protein recruiting activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22925]
This is to describe the opposite of 'sequestering'. 

Child of protein adaptor activity
Definition: 

synonym: 

@pmasson55 @sylvainpoux @thomaspd

**Comment by pgaudet** [comment]
Add children: 
- GO:0001139 RNA polymerase II complex recruiting activity
- 'GO:0001010 RNA polymerase II sequence-specific DNA-binding transcription factor recruiting activity'

**Comment by ValWood** [comment]
Protein adaptors are "recruiting", so how would you define this term?
We even use "recruits" as the 'display label ' for many adaptors:
https://www.pombase.org/term/GO:0030674

For example [cytoskeletal protein-membrane anchor activity](https://www.pombase.org/term/GO:0106006)
is recruiting proteins to the membrane.

I only ask because I wanted a term for " recruiting " for many years, and was told to use "adaptor", now I will need to request that all the adaptor children I used are changed to "recruiting" (which might be better).

Here is a little bit of the history:
https://github.com/geneontology/go-ontology/issues/17155

**Comment by ValWood** [comment]
You would need to  rename most of the terms the adaptor branch

**Comment by pgaudet** [comment]
Maybe the solution is to add 'recruiting' as a NARROW synonym to many terms in that branch (where it seems appropriate)

**Comment by ValWood** [comment]
I think it should probably usually be exact.
kinetochore adaptor activity "recruits"
chromatin-protein adaptor activity "recruits"
cargo adaptors "recruit"

but recruits would be odd for some of the adaptors that are connecting larger cellular components:
centromere-nuclear envelope anchor activity
heterochromatin-nuclear membrane anchor activity


The other anomaly is "histone reader" but that is weird anyway.
The histone is recruiting the 'reader' so it is the opposite way round to how we would usually annotate in a causal model. I think this  term will cause lots of confusion.

**Comment by pgaudet** [comment]
OK to add synonyms 
@thomaspd @pmasson55 @sylvainpoux

**Comment by pgaudet** [comment]
Added synonyms: 

- [ ] protein-macromolecule adaptor activity  -> protein recruiting activity RELATED []
- [ ] signaling adaptor activity -> signaling protein recruiting activity EXACT []
- [ ] cytoskeletal protein-membrane anchor activity -> cytoskeletal protein to membrane recruiting activity EXACT []


I did not add synonyms to other siblings because these terms dont always states what is recruited where. 

Thanks, Pascale
