### ISSUE TITLE
NTR enzyme-substrate adaptor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22972]
This has come up a lot, we want to create a new term to represent 'substrate adaptor activity' 
child of 'GO:0030674 protein-macromolecule adaptor activity'

parent of 
- 'protein ADP-ribosyltransferase-substrate adaptor activity' NTR in #22874 
- GO:1990756 ubiquitin ligase-substrate adaptor activity

**Comment by pgaudet** [comment]
Examples in PMID:34358446 (methylase adaptor), PMID:16250895 (ubi ligase)

**Comment by pgaudet** [comment]
Proposed def: An adaptor that brings together a protein and its substrate. Adaptors recruit the substrate to its enzyme, thus contributing to substrate selection and specificity.

@sylvainpoux feel free to improve

@ValWood you may have suggestions as well?

**Comment by ValWood** [comment]
Substrate adaptor will be useful, but how do you define a substrate in this instance.

Many of the chromatin protein adaptors could be defined as 'substrate adaptors' because they recruit a substrate for another activity (i.e a kinase that is a substrate of another kinase). Signalling adaptors are often substrate adaptors.  A clathrin adaptor is a substrate adaptor.  Everything is a substrate of something, so do you mean something more specific here? If not, I'm not sure if the grouping term will help.

**Comment by lbreuza** [comment]
To avoid annotation to kinetochore and signaling adpators should'nt you modify the definition to have "...together an enzyme and its substrate..."?

**Comment by pgaudet** [comment]
Hi, 

In fact this is the definition I ended up giving this term: An adaptor that brings together an enzyme and its substrate. Adaptors recruit the substrate to its enzyme, thus contributing to substrate selection and specificity.

I updated the comment to reflect that. Thanks for the feedback! 

Pascale

**Comment by deustp01** [comment]
@ukemi  Are we edging towards recognizing an additional function that can be enabled by protein components of complexes, that is within the scope of GO annotation?

**Comment by ukemi** [comment]
@deustp01 I think yes. This might be useful as we move forward trying to replace some of our molecular events and as we think about the individual roles of GPs in Reactome complexes.
