### ISSUE TITLE
Taxon constraints inherited from uberon are too metazoan-specific

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#23012]
See this ticket, starting from this comment yesterday: https://github.com/geneontology/go-ontology/issues/21217#issuecomment-1066102512

@balhoff summarizes:

> The owltools taxon subset command is more aggressive than normal taxon constraint reasoning. In this case there is a pretty large reasoner explanation, but it includes the relation that anatomical structures start existing during or after zygote stage, zygote stage is part of embryo stage, and then embryo stage relates to all sorts of stuff that is not in yeast.

> We could either do a lot of work in Uberon to make all these relationships more taxon-specific, or provide you with a different script that only removes terms over the standard taxon constraint propagation rules.

This summary is correct: Here is the source of the confusion: all classes in Uberon were originally intended for metazoa. CARO was originally intended as the true species-neutral form. However, CARO is not well maintained and it's confusing having latticey terms that are trivially differentiated only be species, so GO has been using Uberon terms as if they were species neutral

Action, from immediate to longer term:

 1. [ ] @balhoff - what about as an immediate fix using robot to filter for a conservative set of ObjectProperties prior to the taxon operation?
 2. [x] I made an issue to make the relationship metazoan specific in uberon, which will fix this: https://github.com/obophenotype/uberon/issues/2348 
 3. [ ] we need better checksums as part of the QC process more generally

Note the uberon fix may take some discussion, and then will need to be percolated to GO

The final item will take some time but broadly speaking we should be annotating terms we know for sure to be in a taxon with present-in taxon. It would also be good to see a diff with each release of which terms dropped out for main taxa. Some of this should be apparent from the snapshot releases - I assume yesterday we would have been an increase in taxon violations for pombe - but I don't think we have an alert mechanism for deltas here.

**Comment by ValWood** [comment]
thanks!

**Comment by kimrutherford** [comment]
Thanks Jim and Chris.  We'll be happy with whatever solution you can come up with.  We have no problem with moving away from OWLTools if that's the best plan.

**Comment by ValWood** [comment]
@balhoff  you are correct- this brings back many many terms that I previously spent a lot of time adding  taxon restrictions to, so that our users would not see them in the curation tool drop down. It seems trivial but it just seems odd to implement  a system that makes the taxon restrictions worse than they used to be (this seems to be a recent problem).

But I don't fully understand the situation..... I guess my question is, why use uberon for taxon restrictions if it messes things up.

Why not remove the offending relation that "anatomical structures start existing during or after zygote stage"
this is just not true for many cell level anatomical structures. Or, restrict it to tissue and organ level anatomical structures  in some way. Or don't rely on uberon for GO taxonomic restrictions?

**Comment by balhoff** [comment]
We're fixing the Uberon issues in parallel; I just wanted to try to give you a quicker option. Uberon provides many useful taxon constraints; I would say the problem ones here are just errors.

My new script is a bit more transparent than the owltools command, so I find it easier to understand what is happening. But I'll focus on getting the changes into Uberon and see if we can quickly get a release out.

**Comment by ValWood** [comment]
Don't worry about a quick fix especially for us if the changes are pending. I'm happy to keep sessions that I can't approve  back for a while to save you doing extra work.  Weeks is OK, but let me know if it is many months as we may then need an interim fix.

**Comment by ValWood** [comment]
Hi,
revisiting this ticket, do you have an ETA for the fix rather than the proposed workaround? 

I ask because I thought this was only preventing me re-approving curation sessions that I needed to edit. However, it just struck me that this will prevent any of our community curators from using terms in the anatomical structure branch (so anything to do with conjugation, cell polarity, sporulation etc).

I didn't really want to implement the "replacement script" because a) it isn't really clear to me what this is doing and b) would it be practical since we erimport the ontology into PomBAse every day. Would we need to do this every time we update?

So I really wanted to check when a proper fix is expected so we can get back to working as normal.
It seems really (since this issue presumably affects other databases, they just haven't noticed). Would it not be more prudent NOT to use the uberon taxon constraints until this issue is resolved?

I guess really we are waiting on 
https://github.com/obophenotype/uberon/issues/2348
which is assigned  to @cmungall 

Thanks for any update you can provide so that we can decide  what we need to do from a users perspective.

**Comment by balhoff** [comment]
@cmungall could you take a look at this PR? https://github.com/obophenotype/uberon/pull/2390

**Comment by ValWood** [comment]
Thanks Jim!

**Comment by ValWood** [comment]
this change should fix this issue:
https://github.com/geneontology/go-ontology/issues/23445

**Comment by pgaudet** [comment]
@balhoff are these changes now in GO ?

**Comment by balhoff** [comment]
Yes, but yesterday I found there is one additional problem axiom involving 'zygote stage'. I sent @ValWood a workaround to get things working at PomBase, and I will open an issue at Uberon to fix the rest.

**Comment by ValWood** [comment]
Yay , the work-around worked, and I could approve all of the unapproved sessions.  I should have listened and got Kim to do that before. It sounded complicated to me but not to @kimrutherford  !
Thanks @balhoff

**Comment by pgaudet** [comment]
Excellent!
