### ISSUE TITLE
NTR: [beta-alanine:sodium symporter activity]

### ISSUE THREAD

**Issue by SHS111** [geneontology/go-ontology#23062]
Please provide as much information as you can: 

* **Suggested term label: beta-alanine:sodium symporter activity

* **Definition: Enables the transfer of a solute or solutes from one side of a membrane to
the other according to the reaction: beta-alanine(out) + Na+(out) = beta-alanine(in) Na+(in). 

* **Reference :PubMed=8420981 
    Please see fig 2 and materials and methods

* **Gene:Slc6a13and ID:  S6A13_MOUSE

* **Parent term: GO:0001761
 
* **Synonyms: sodium/chloride-dependent beta-alanine transporter | broad

**Comment by pgaudet** [comment]
Hi @SHS111 

Looking at the paper and the entry, the function of Slc6a13 is probably best described by '[GO:0005283 amino acid:sodium symporter activity](http://amigo.geneontology.org/amigo/term/GO:0005283#display-lineage-tab)' with the extension 'has_input' beta-alanine, since it 's not specific for beta-alanine but also transports other amino acids. Does that work for you? 

Thanks, Pascale

**Comment by SHS111** [comment]
Hi Pascale,
I agree with you, it also transports taurine and GABA which have their specific GO term  ie why I thought of asking a new term for beta-alanine.
But it suits me also to do as you have suggested with an extension.
Thanks a lot for your message.
Wishing u a nice day.
Cheers
Shyamala

**Comment by pgaudet** [comment]
What is interesting is that GABA is not an alpha amino acid either, and taurine is described as an 'amino acid derivative. 

So that raises 2 questions: 
- are there transporters specific for taurine and GABA? 
- do we need a different term along the lines of 'modified amino acid:sodium symporter activity'? 

What do you think? 

Thanks, Pascale

**Comment by SHS111** [comment]
Hi Pascale,
I will check and get back to you.
Thanks & Cheers
Shyamala

**Comment by SHS111** [comment]
Hi Pascale,
The transporter SLC6A1  is specific for GABA.  I did not find  one which is specific for taurine only.
SLC6A6, SLC6A11 & SLC6A13 can transport taurine, beta-alanine, GABA.
Seems like a good idea to create 'modified amino acid:sodium symporter activity' .
Hope this helps.
Cheers
Shyamala

**Comment by pgaudet** [comment]
No longer needed - @SHS111 used '[GO:0005283 amino acid:sodium symporter activity](http://amigo.geneontology.org/amigo/term/GO:0005283#display-lineage-tab)' with the extension 'has_input' beta-alanine, since it 's not specific for beta-alanine but also transports other amino acids.
