### ISSUE TITLE
NTR: [XCL1 production]

### ISSUE THREAD

**Issue by rvita** [geneontology/go-ontology#23071]
similar to the recent NTR for amphiregulin production https://github.com/geneontology/go-ontology/issues/21878
we are requesting another cytokine production term

Please provide as much information as you can: 

* **Suggested term label:**
XCL1 production

* **Definition (free text)**
The appearance of XCL1 due to biosynthesis or secretion following a cellular stimulus, resulting in an increase in its intracellular or extracellular levels.

* **Reference, in format PMID:#######**
https://en.wikipedia.org/wiki/XCL1
PMID: 7973732

* **Gene product name and ID to be annotated to this term**
XCL1

* **Parent term(s)**
GO:0001816
cytokine production

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
lymphotactin production

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Please assign to Pascale, Thanks!

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140779
+name: XCL1 production
+def: "The appearance of XCL1 due to biosynthesis or secretion following a cellular stimulus, resulting in an increase in its intracellular or extracellular levels." [PMID:7973732]
+comment: Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select one of the 'regulation' children terms.
+subset: gocheck_do_not_annotate
+synonym: "lymphotactin production" EXACT []
+xref: Wikipedia:XCL1
+is_a: GO:0001816 ! cytokine production
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23071 xsd:anyURI
+created_by: pg
+creation_date: 2022-03-24T07:11:34Z
