### ISSUE TITLE
Query : GO:0010599 primary lsiRNA processing

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23093]
Hi @tberardini 

We are reviewing the small regulatory non-coding RNA branch, and we're not sure what to do with GO:0010599 primary lsiRNA processing: there is a single paper used both for the term and 3 annotations, and we cannot find mention of lsiRNA in other papers  - or they may be subtypes/precursors of siRNAs, see PMID:23272103

Based on the little evidence that this is really a different type of small regulatory non-coding RNA, would you agree to merge it into  GO:0030422 siRNA processing? 

Thanks, 

Pascale 

@hattrill @RLovering

**Comment by tberardini** [comment]
I don't think we can merge it because the def of GO:0030422 (called 
**production of siRNA involved in post-transcriptional gene silencing by RNA**
 in my view, not **siRNA processing**) includes a length, "small interfering RNA molecules (siRNAs) of 21-23 nucleotides."

The[ paper that describes the lsiRNAs](https://pubmed.ncbi.nlm.nih.gov/18003861/) refers to these RNAs as "a novel class of small RNAs, long siRNAs (lsiRNAs), which are 30-40 nt ".  Since the lengths are different, I don't support the merge.

**Comment by tberardini** [comment]
I'd recommend reaching out to the authors of that Arabidopsis paper to ask about recent progress/changes. That could produce information to guide a merge/non-merge.

**Comment by RLovering** [comment]
good idea

**Comment by pgaudet** [comment]
We found a nice review that describes that lsiRNA processing occurs via a different pathway, so we'll keep the term
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3752435 (see Fig 1).

**Comment by tberardini** [comment]
Nice find.  Thank you for continuing to investigate to find this good solution.
