### ISSUE TITLE
NTR:  phosphate uniporter activity 

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#23132]
Please provide as much information as you can: 

* **Suggested term label:**
phosphate uniporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: phosphate(in) = phosphate(out). 

* **Reference, in format PMID:#######**
PMID:29642010
* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
uniporter activity GO:0015292

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
RHEA:32823
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by Argoudpuy** [comment]
Hi,
just a rectification of my request:
could you please replace Suggested term label: phosphate uniporter activity by Suggested term label: **phosphate ion uniporter activity** in my new request term
therefore the parent term will be : membrane potential driven uniporter activity GO:0022810 insteed of Parent term(s)
uniporter activity GO:0015292.
Many thanks
Guilaine

**Comment by hdrabkin** [comment]
I could make the term. However, RHEA:32823 cannot be used as it is already assigned to GO:0015114, phosphate ion transmembrane transporter activity.  Enables the transfer of phosphate (PO4 3-) ions from one side of a membrane to the other.

How is your requested term different?

**Comment by Argoudpuy** [comment]
Hi,
I didn't see that RHEA:32823 is already assigned to GO:0015114, because I searched in QuickGo with the term phosphate uniporter activity, and it was not there.  
Moreover in the PMID:29642010, authors describe that the phosphate transport is driven by an electrochemical gradient, here is the difference with GO:0015114.
therefore the phosphate uniporter activity would be more appropriate that GO:0015114 (https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0015114) because the later is not related in the ontology to the term "secondary active transmembrane transporter activity GO:0015291" whom the uniporter activity GO:0015292 term is a child
I hope that make sens to create the new term phosphate uniporter activity.
Many thanks
Guilaine

**Comment by pgaudet** [comment]
Hi @Argoudpuy 

This is odd, the xref really is there, since 2018 

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/4782928/161686344-8a700d32-707e-424d-b7e5-230a258f4ff1.png">

**Comment by pgaudet** [comment]
This is a really unusual mechanism since the protein has two different functions depending on where it's located, but there are other papers that support that (at least one, PMID:32474835) 

However is 'uniporter' right ? 
![image](https://user-images.githubusercontent.com/4782928/161687302-7081104e-f123-4993-9eaa-0830bb1a95a7.png)

It seems to be a symporter, doesn't it (in the paper they mention 'co-transporter')

**Comment by pgaudet** [comment]
A few more observations: 
* The Na:Pi reaction is captured by http://amigo.geneontology.org/amigo/term/GO:0015319, which seems correctly mapped to https://tcdb.org/search/result.php?tc=2.A.1.14.6 and describes SLC17a (Q61983)
* GO:0005436 sodium:phosphate symporter activity seems to represent the same reaction (no mappings) -> merge? 
* We would be missing glutamate:phosphate symporter activity- @Argoudpuy would that describe the reaction? 
* RHEA:32823 is not appropriate here, since it's only phosphate transport and not the other molecules. 

Thanks, Pascale

**Comment by Argoudpuy** [comment]
Hi,
 at the plasma membrane works as a sodium:phosphate symporter activity GO:0005436 (Evidence:PubMed=29642010, see Fig. 5 and 6) and at the vesicular membrane as phosphate uniporter (see Evidence:PubMed=29642010, see  Fig. 3.)
thanks
Guilaine

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140787
+name: phosphate ion uniporter activity
+namespace: molecular_function
+def: "Catalysis of the active transport of a phosphate ion across a membrane by a mechanism involving conformational change, where energy for active transport is derived from membrane potential if the solute is charged." [PMID:29642010]
+is_a: GO:0022810 ! membrane potential driven uniporter activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23132 xsd:anyURI
+created_by: pg
+creation_date: 2022-04-05T07:42:20Z
