### ISSUE TITLE
how to annotate shikimate pathway

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23281]
We have the term,

GO:0019632   shikimate metabolic process
The chemical reactions and pathways involving shikimate, (3R,4S,5R)--3,4,5-trihydroxycyclohex-1-ene-1-carboxylate, the anion of shikimic acid. It is an important **_intermediate_** in the biosynthesis of aromatic amino acids.**

But no biosynthetic term.
I thought we have a plan  not to annotate 'intermediates"  so  do I need a term for 
shikimate biosynthetic  process?
 of would you instead annotate to  biosynthesis of each of the aromatic amino acids?

@deustp01 
@ukemi 
@pgaudet 
@vanaukenk 
I checked in Noctua but I could not  find any amino acid biosynthesis pathways. I guess this is a question about starts and ends of processes?

(I am thing to Noctua this pathway  with a visitor on Monday, but I do not know which process terms to use)

**Comment by ValWood** [comment]
So currently people have either annotate to  shikimate metabolism 29486 (17 EXP), OR aromatic amino acid family biosynthesis 2,395,157 (160 EXP)

<img width="755" alt="Screenshot 2022-05-06 at 17 34 56" src="https://user-images.githubusercontent.com/7359272/167175441-9e0cc046-2cfa-4688-9850-cfb9714a58da.png">

(there is also a shikimate catabolic process for some pathogens)

**Comment by deustp01** [comment]
The issue here is that shikimate is an aromatic acid (but not an amino acid), one of whose metabolic fates is to be converted to tyrosine (an aromatic amino acid). That's the limit of my knowledge. IF the ONLY fate of shikimate is metabolism to tyrosine, then this term could be an is_a child of aromatic amino acid metabolism. If there are other fates for shikimate that do NOT involve amino groups, then the current hierarchy looks OK and existing manual annotations and computational inferences from them may need checking for accuracy.

**Comment by ValWood** [comment]
OK, It is required for the synthesis of folates too.
https://en.wikipedia.org/wiki/Shikimate_pathway

So, in this case, would the "start_of"  tyrosine biosynthesis be the first step **after** shikimate biosynthesis?
Or would I annotate the components of this pathway directly to tyrosine biosynthesis?

**Comment by pgaudet** [comment]
@marcfeuermann Have you annotated this one? Any suggestions?

**Comment by ValWood** [comment]
I was hoping there would be some general rules for metabolic pathways starts and ends when dealing with branch points etc. to emerge from annotating metabolic pathways in Noctua more generally, so this question is not necessarily specific for shikimate, or to Marc. I can bring the question to a Noctua discussion once I have  plugged in the activities.

**Comment by pgaudet** [comment]
OK - see also #22542

**Comment by ukemi** [comment]
In addition, after the section on glycolysis starting with glucose, most college-level textbooks also describe how other sugars can feed into glycolysis. That's why it's important to look closely and try to follow community usage. There are also species-specific issues of pathway boundaries. A good example of that is purine catabolism, which we have talked about several times in the pathway2GO updates at GOC meetings.

**Comment by deustp01** [comment]
All of which makes this a hard ontology development and curation problem, and frustrating because the available fixes need a fair amount of expertise and do not scale.

**Comment by ValWood** [comment]
I think we can close this one. On reflection, I would not annotate this pathway to 
shikimate biosynthesitc process. In fact shikimate pathway is a related synonym of "aromatic amino acid metabolic process" which makes sense. Eventually I will annotate to each of the 3 amino acids that  chrorismate (the pathway end product) is a precursor for (and anything else).  and I won't annotate to chorismate or shikimate biosynthetic process terms.

I hope that makes sense?
