### ISSUE TITLE
GO:0034497	protein localization to phagophore assembly site (merge)?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23303]
GO:0034497	protein localization to phagophore assembly site
Is a child of 	autophagosome assembly
But how  is it distinguished from autophagosome assembly?
I annotated just to  the parent "autophagosome assembly (GO:0000045)"

(I am filtering PAINT annotations to the children because I don't know what they add?)
@marcfeuermann 
@pgaudet

**Comment by ValWood** [comment]
@pgaudet

**Comment by marcfeuermann** [comment]
Hi Val
Autophagosome formation is initiated by assembly and recruitment of the core autophagy machinery to phagophore assembly sites. Then the core autophagy machinery can perform autophagosome assembly. So 'GO:0034497 protein localization to phagophore assembly site' is only the initial step of autophagosome assembly and that's why I would keep it as a child term and not merge the two.
Cheers,
Marc.
