### ISSUE TITLE
Change logical definition of 'GO:0019674 NAD metabolic process

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#23467]
Need to change to 'has primary participant some 'NAD(1-)
Will also need to fix children 

Do we also need to fix NADH met proc and NADP (change to NADP(-1) as primary and NADPH met proc?

**Comment by ukemi** [comment]
@deustp01 this came about from my looking at the output of the new cobalamin metabolism model. Because some of the enzymes use NAD and NADH as redox factors, we are inferring that all of the enzymes in the pathway are involved in NAD or NADH metabolism. I think this is misleading, don't you? Certainly there are some pathways that generate or recycle redox potential for cellular use, but wouldn't we want to restrict those manually by declaring the inputs and outputs as primary?

**Comment by deustp01** [comment]
@ukemi agreed - same as not inferring that a MAP kinase cascade is involved in ATP catabolism.

**Comment by ukemi** [comment]
As long as @hdrabkin didn't change the logical defs of the other terms, they won't be inferred any more. They will still be participants, but they won't be inferred to be NAD(H) metabolic processes. In order for that inference to be made we have to assert the participation of the NAD(H) as a primary input or output.

**Comment by deustp01** [comment]
And meanwhile, here is a brand new paper from JBC that reviews NAD metabolism ([PMID: 35595095](https://pubmed.ncbi.nlm.nih.gov/35595095/)) - maybe a good source of expert advice on boundaries between NAD metabolism and NAD turnover in redox reactions.
