### ISSUE TITLE
Merge 'envenomation resulting in modulation of cell migration in another organism' into parent 'modulation of cell migration in another organism'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23656]
- [x]  GO:0044624 envenomation resulting in modulation of cell migration in another organism  ==> GO:0044621 modulation of cell migration in another organism
- [x]   GO:0044625 envenomation resulting in negative regulation of cell migration in another organism ==> GO:0044622 negative regulation of cell migration in another organism => change label to suppression of cell migration in another organism
- [x]  GO:0044626 envenomation resulting in positive regulation of cell migration in another organism  ==> GO:0044623 positive regulation of cell migration in another organism => change label to induction of cell migration in another organism

**Comment by pgaudet** [comment]
Need to find references - the papers cited dont clearly talk about the toxin modulating cell migration under physiological conditions: 
* PMID:16772304 (annotation to GO:0044621 modulation of cell migration in another organism
* PMID:19932752 cited for GO:0044624 envenomation resulting in modulation of cell migration in another organism 
It seems like some doses of the venom modulate cell migration, but the papers are looking for anti-cancer drugs or wound healing drugs (that stimulate macrophage infiltration).

**Comment by pgaudet** [comment]
Also, @FJungo will help looks for physiological examples of 'GO:0044621 modulation of cell migration in another organism: 
this term is not precise enough to know what process is being disrupted: epithelial cell migration /wound healing? macrophage migration / immune response 


@genegodbold @pmasson55 @mgiglio99 @dsiegele 

Do you have examples of modulation of host cell migration for bacteria/viruses?

**Comment by genegodbold** [comment]
@pgaudet 
What counts as modulation of migration? 
Lots of bacterial virulence factors paralyze phagocytes like macrophages by messing with their cytoskeleton. So then they  cn't migrate.
Others affect the chemokine environment so that they don't move as they would in the absence of those virulence factors. There are secreted Streptococcal proteases that cleave interleukin-8 and complement inflammatory mediators like C5a so that the host neutrophils "lose" coordination of the response with deleterious effects on the host.

Is this modulation of migration? I count the former as anti-phagocytic and use terms like
PATHGO:0000232 (suppresses phagocytosis in another organism) OR PATHGO:0000231 (suppresses opsonization in another organism)

I also use PathGO terms specifying what aspect of the host cell cytoskeleton is disabled 'in another organism'
PATHGO:0000028 (modulates cytoskeleton dynamics in another organism)

- PATHGO:0000216 (mediates filamentous actin depolymerization in another organism)
- PATHGO:0000260 (mediates filamentous actin rearrangement in another organism)
- PATHGO:0000261 (mediates actin polymerization in another organism)
- PATHGO:0000217 (mediates actin crosslinking in another organism)
- PATHGO:0000340 (mediates actin stabilization in another organism)
- PATHGO:0000378 (mediates filamentous actin destabilization in another organism)
- PATHGO:0000221 (mediates microtubule stabilization in another organism)
- PATHGO:0000222 (mediates microtubule destabilization in another organism)
- PATHGO:0000280 (mediates microtubule rearrangement in another organism)

**Comment by pgaudet** [comment]
Nice! These are much more specific. Thanks for pointing this out.
