### ISSUE TITLE
SMAD protein signal transduction new parent 

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#23773]
Add new parent to SMAD protein signal transduction following discussion on https://github.com/geneontology/go-annotation/issues/4239

GO:0035556 intracellular signal transduction
>is_a GO:0060395 SMAD protein signal transduction

With New definition: An intracellular signal transduction process that starts with the activation of a SMAD protein, and ultimately effecting a change in the functioning of the cell, for e. g. transcription. SMAD proteins are activated by protein serine/threonine kinase cell surface receptors.

Thanks

Ruth

**Comment by pgaudet** [comment]
Proposed new definition with @gantonazzo @hattrill @RLovering 

An intracellular signal transduction pathway that starts with the activation of a SMAD protein, leading to the formation of a complex with co-SMADs, which translocates to the nucleus, where it regulates transcription of specific target genes. 

+ add comment: Note that the receptor and its ligand regulate the pathway, since it is an intracellular signaling pathway.
