### ISSUE TITLE
NTR: receptor ligand binding

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#23891]
Hi

I am trying to curate DLL1 and DLL4 (orthologs of fly delta/Dl). I have annotated these as having receptor ligand activity - as they bind to NOTCH. But I would like to curate Notch with a term that is better than
* protein binding WITH DLL4

The protein binding ontology is quite flat when it comes to ligands, so I would like to propose that the term 
receptor ligand binding is created to match the receptor ligand activity branch of the ontology.

**Suggested term label:**

    * receptor ligand binding

**Definition (free text)**

   * Binding to a receptor ligand factor, proteins or polypeptides that bind to a receptor to effect a change in the activity of the receptor. 

**Reference, in format PMID:#######**

    * PMID: 15466159, PMID: 9520411

**Gene product name and ID to be annotated to this term**

    * NOTCH

**Parent term(s)**

    * GO:0005515 protein binding

Child term(s)
* GO:0019838 growth factor binding
* GO:0019955 cytokine binding
* Additional NTR: differentiation factor binding:
Definition: Binding to a differentiation factor, proteins or polypeptides that stimulate a cell or organism to differentiate. (see NTR differentiation factor activity https://github.com/geneontology/go-ontology/issues/23889) 

Thanks

Ruth

**Comment by hattrill** [comment]
Hi @RLovering

I will first say that I find the term label "receptor ligand binding" a bit confusing - bit too similar to 'receptor ligand activity' or could be mistakenly used for any old protein binding a ligand. Perhaps something like "receptor ligand-binding activity" might  be more explicit.

But, I think this bleeds into the issue of GO:0004888 transmembrane signaling receptor activity: Combining with an extracellular or intracellular signal and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity or state as part of signal transduction. 

The way the GOC is leaning is that transmembrane signaling receptor activity  has_input the next downstream component - which doesn't make sense to me as this is very variable and subject to interpretation which can be wrong. I think that is make more sense to have a consistent approach where transmembrane signaling receptor activity encompasses the binding aspect, which is universal to receptors. 

Notch is a good example where the downstream target would be hard or incorrect to capture: notch being a receptor and TF:
<img width="796" alt="Screenshot 2022-08-30 at 08 00 57" src="https://user-images.githubusercontent.com/11865746/187372160-21d64c2f-2fe1-4514-9656-8e3da00e19dc.png">

Not sure if that using "transmembrane signaling receptor activity" in the way I've suggested would satisfy your needs or please the rest of the GOC ;-) but I too would like a consistent and logical way to define receptors' interaction with ligands so that users can easily query GO for this and not have to know the collective GOC mind (hence my obsession with signaling receptor activity).

**Comment by pgaudet** [comment]
@RLovering Do you still need this term?

**Comment by RLovering** [comment]
Can we use IPI with GO:0004888 transmembrane signaling receptor activity and then add the ligand to the With field?

**Comment by ValWood** [comment]
closing as "out of date"
@hattrill @pgaudet  please reopen if this is incorrect
