### ISSUE TITLE
Textual definition update:  query def of 1,3-beta-glucanosyltransferase activity (GO:0042124)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24036]
term: 1,3-beta-glucanosyltransferase activity (GO:0042124)
Definition |
Catalysis of the splitting and linkage of (1->3)-beta-D-glucan molecules, resulting in (1->3)-beta-D-glucan chain elongation. [PMID:10809732]

Is this definition correct? I was surprised about the **" splitting"** part? I thought it was just linkage?
I could not find any reaction info anywhere.
Has this term been aligned with rhea?

**Comment by hdrabkin** [comment]
This has no RHEA assigned to it in the ontology.  The def is not worded clearly. 
I assume it is using  UDP-alpha-D-glucose  to transfer a glucose to a beta-D-glucan molecule. 
this might be 
[RHEA:21476]( [(1→3)-β-D-glucosyl](n) + UDP-α-D-glucose = [(1→3)-β-D-glucosyl](n+1) + H+ + UDP

**Comment by hdrabkin** [comment]
RHEA:21476 already assigned to 1,3-beta-D-glucan synthase activity GO:0003843

**Comment by hdrabkin** [comment]
@amorgat , what do you think about this one.

**Comment by ValWood** [comment]
I could not find a reaction, but most schematics seem to show it is joining 2 existing carbohydrate chains (via a branched linkage?), as part of cell wall remodelling. It seems to be the only enzyme in this branch of GO. it's parent
glucanosyltransferase activity (GO:0042123) has no other descendants.

**Comment by ValWood** [comment]
here is some more information, it seems it is a 2-step reaction
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0014046
The chromatogram shows that the enzyme preferentially released an oligosaccharide of 6-8 glucose units from the reducing end of G13r and transferred it to the acceptor laminari-oligosaccharide ([Figure S3A](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0014046#pone.0014046.s003)). Thus, the major initial products were G6–8r and rG18–20r, in agreement with the two-step reaction scheme previously described by Hartland et al. [[38]](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0014046#pone.0014046-Hartland1). Analysis of r-gas2p and r-gas5p indicated a slight difference with r-gas1p activity...
These results indicated that although the catalytic reaction was the same, the three enzymes had slight differences in substrate recognition. In all cases, the pattern observed after prolonged incubation times indicated that the initial transfer products could be subsequently re-used either as donors or acceptors, resulting in a broad range of transfer products of increasing size (degree of polymerization >30) until they became water-insoluble. The minimum oligosaccharide that could be used in the reaction was an oligosaccharide of 9 glucose units (data not shown)

**Comment by deustp01** [comment]
> We do not have a Rhea reaction for this activity, and we will not get one either

This is a tangent for discussion beyond this ticket. If an expert in glycobiology were to construct a reaction involving generic chemical entities that magically was both general enough to span all the possibilities and also specific enough to be informative to human and computational users, would Rhea then be able to create a reaction. I am definitely not such an expert, so this is a hypothetical question. It is of interest because we'd like to have a Rhea reaction for every GO MF catalysis term, even if use of that reaction involves making narrow / broad synonym relationships between the Rhea generic reaction and the GO term@ukkemi

**Comment by kaxelsen** [comment]
I don't know if we could create a Rhea reaction for this case (but I don't think so), but more generally it is not possible to create Rhea reactions for all possible reactions, so you will have to live with reactions for which there are "only" text reactions. Glycosyltransferase reactions, and peptidase reactions are prime examples of things that are difficult or impossible to fit into Rhea. Firstly, the substrate is a polymer, Secondly, if the enzymes are cutting 'endo' the resulting products may have undefined lenghts, or for peptidases, undefined composition around the cutting site. These things combined makes it impossible to fit into the Rhea scheme.
For the time being it will not be a priority area either to find a way to include such reactions, since there still are countless reactions describing transformations of small molecules that still need to be created.

**Comment by ValWood** [comment]
Thanks @kaxelsen and @deustp01
 I think I used to know  this, but forgot. Is 1,3-beta-glucanosyltransferase the only known enzyme of this type (it seems to be the only child of glucanosyltransferase activity (GO:0042123) .

  for me this one can close once you are finished.

**Comment by deustp01** [comment]
Which puts @kaxelsen far ahead of me!

**Comment by hdrabkin** [comment]
So if GO:0042124 def is correct, I can close this ticket out?

**Comment by ValWood** [comment]
yep
