### ISSUE TITLE
Add synonym GO:0052745 inositol phosphate phosphatase activity

### ISSUE THREAD

**Issue by manulera** [geneontology/go-ontology#24182]
"Inositol pyrophosphatase activity" seems to be used as a synonym in these papers (see titles)

[PMID:32303658](https://pubmed.ncbi.nlm.nih.gov/32303658/) (Fig. 3 depiction of the reaction)

[PMID:35536002](https://pubmed.ncbi.nlm.nih.gov/35536002/)

**Comment by pgaudet** [comment]
Hi, 

I could add a 'broad synonym', because this is not true for one of the children, inositol monophosphate phosphatase activity. 

However it does fit the definition: 
"Catalysis of the reaction: inositol phosphate(n) + H2O = inositol phosphate(n-1) + phosphate. This reaction is the removal of a phosphate group from an inositol phosphate."
ie this definition excludes inisitol mnophosphate phosphatase activity. Maybe this term should be moved elsewhere. 

@sjm41 Could we discuss this tomorrow? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @manulera 

@sjm41 and I are reviewing this branch, and there is quite some confusion in part because there are two phosphatase branches that are split very high in the ontology: 


<img width="362" alt="image" src="https://user-images.githubusercontent.com/4782928/197489945-006ffbbd-59bd-4fe9-b169-be8a9b6ab323.png">


To clarify, we have changed the label of GO:0016791 phosphatase activity to phosphoric monoester hydrolase activity, to match EC and the term definition. It may be useful to create a 'phosphatase' grouping class to group the monoester hydrolase and the pyrophosphatases, but when we looked at that it was a bit more complex than it seemed at first glance. 

I'll open a different ticket to discuss this. 

Thanks, Pascale
