### ISSUE TITLE
GO:0008440    inositol-1,4,5-trisphosphate 3-kinase activity (synonyms)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24266]
GO:0008440    inositol-1,4,5-trisphosphate 3-kinase activity
Has synonym "IP3 3-kinase activity"
 Narrow (is that correct?)

This is a  IP3 3-kinase activity and presumably there are slightly different specificities, of which this is one?
So it seems broad?

**Comment by ValWood** [comment]
In fact, shouldn't it be exact synonym of
GO:0051766   inositol trisphosphate kinase activity?

(it would be really nice if all of the IPX kinases  had the exact synonym to land you on the parent term, because it's really confusing...)

**Comment by ValWood** [comment]
There are lots of broad and narrow synonyms on the children. It would be better if they were just placed as "exact synonyms" of the term they relate to.

**Comment by hdrabkin** [comment]
Yes; clearly we have more than one i3p substrate
we have 1,4,5, and 1,3,4
ip3 would definitely be broad, and would definitely fit GO:0051766
As per all the synonyms
These appear to be derived from the EC entry (2.7.1.127) for inositol-trisphosphate 3-kinase.
1D-myo-inositol-trisphosphate 3-kinase
Inositol 1,4,5-trisphosphate 3-kinase. <<<<<<< would be narrow synonym 
Ins(1,4,5)P3 3-kinase.<<<<<<< narrow
IP3 3-kinase <<<<< exact)
IP3K. <<<< broad: does not specify 1,4,5 or 1,3,4


But EC:2.7.1.159 ( note that EC says the ENZYME carries out either adding to 5, or adding to 6.
We two separte activities (two rheas) :GO:0052726 (for addition to 5; RHEA:13253) and GO:0052725 (for addition to 6, RHEA:20940). 

The synonyms derive from the EC number (mapped to both GO:0052726 and GO:0052725)
inositol trisphosphate 5/6-kinase.<<<<<<< sort of narrow-ish
Ins(1,3,4)P3 5/6-kinase. <<<<<<< sort of narrow-ish
IP56K. <<<<<< broad because the 1,4,5 or 1,3,4 aren't specified). 

GO:0051766 is an broad grouping term made by GO. for the 3 (that is they are all IP3Ks;

**Comment by hdrabkin** [comment]
In fact, I suggest that  I add the IP3K to the grouping term which currently has no synonyms.  And make sure IP3 is a broad synonym for the children (not narrow).  Or maybe 'related' ?
Then, if someone searched on IP3 they would see there were 3 children. 
Again, the synonyms for the children come from the EC entries.

**Comment by hdrabkin** [comment]
Another note:
for the grouping term: this name is a general name.(ie, inositol trisphosphate kinase (not saying what position gets the phosphate)
At EC, the 1,4,5 is called 'inositol trisphosphate 3-kinase, BUT the reaction is specific for the 1,4,5 substrate  and specifies that it is position 3 that gets modified, hence the separate GO term)

**Comment by hdrabkin** [comment]
So if I mark the synonyms as above, could that be ok?

**Comment by ValWood** [comment]
Yes, perfect! I really struggle with this branch and I have a had a few papers recently...

**Comment by pgaudet** [comment]
@kaxelsen I am trying to clean up term synonyms and match the definitions  with those of RHEA: 
In GO many (or all, as far as I can tell) reactions had 2 hydrogens in the products, for example: 
   
> GO:0008440 inositol-1,4,5-trisphosphate 3-kinase activity
Catalysis of the reaction: 1D-myo-inositol 1,4,5-trisphosphate + ATP = 1D-myo-inositol 1,3,4,5-tetrakisphosphate + ADP + 2 H+ (RHEA:11020)


However in RHEA there is usually a single hydrogen, except for 

> GO:0000823   inositol-1,4,5-trisphosphate 6-kinase activity (RHEA:32359)

which has 2 ATP in the substrates and ADP and 2 H+. in the products. 


I dont see why this one would be different, just I just wanted to confirm with you before making more edits.

Thanks, Pascale

**Comment by deustp01** [comment]
Just now I only see one output H+ in [RHEA:11020](https://www.rhea-db.org/rhea/11020), but see two in [RHEA:32359](https://www.rhea-db.org/rhea/32359). All of this seems consistent with the idea that number of output H+ equals the number of input ATPs consumed in the phosphorylation reaction. And I guess the definition for [GO:0008440](https://www.ebi.ac.uk/QuickGO/term/GO:0008440) needs to be changed in line with this?

**Comment by kaxelsen** [comment]
> > GO:0000823   inositol-1,4,5-trisphosphate 6-kinase activity (RHEA:32359)
> 
> which has 2 ATP in the substrates and ADP and 2 H+. in the products.
> 
> I dont see why this one would be different, just I just wanted to confirm with you before making more edits.
> 
> Thanks, Pascale

It is because RHEA:32359 produces 1D-myo-inositol 1,3,4,5,6-pentakisphosphate.
The Rhea reaction corresponding to your current text in the definition: D-myo-inositol 1,4,5-trisphosphate + ATP = D-myo-inositol 1,4,5,6-tetrakisphosphate + ADP + 2 H+. Source: MetaCyc:2.7.1.151-RXN
is RHEA:17717: 1D-myo-inositol 1,4,5-trisphosphate + ATP = 1D-myo-inositol 1,4,5,6-tetrakisphosphate + ADP + H+

Note that the synonym lpmK from GO:0000823 is linked to EC 2.7.1.151, inositol-polyphosphate multikinase (https://www.enzyme-database.org/query.php?ec=2.7.1.151), that has RHEA:32359 as overall reaction with the two step reactions RHEA:17717 and RHEA:11856

**Comment by ValWood** [comment]
@sjm41  and @rozaru  could you check, it seems likely that  your work here
https://github.com/geneontology/go-ontology/issues/28385
makes this ticket out of date?

**Comment by sjm41** [comment]
@ValWood I am not sure what the outstanding task(s) is on this ticket. Looks like Harold and Pascale did some clean-up of synonyms in this ticket, while Rossana and I did not review synonyms in #28385 (just the xrefs, defs and relationships).
If you're happy with the current synonyms on these terms, then I think you could close this.

**Comment by rozaru** [comment]
The 2 steps reaction for EC 2.7.1.151 is sorted normally now.
It is covered by:

id: GO:0000823
name: inositol-1,4,5-trisphosphate 6-kinase activity
xref: EC:2.7.1.151 BROAD
xref: RHEA:17717 {source="skos:exactMatch"} EXACT

and

id: GO:0000824
name: inositol-1,4,5,6-tetrakisphosphate 3-kinase activity
xref: EC:2.7.1.151 {source="skos:broadMatch"}
xref: RHEA:11856 {source="skos:exactMatch"}

------

For the IP3K synonym:

The grouping term is now:
id: GO:0051766
name: inositol trisphosphate kinase activity
def: "Catalysis of the reaction: inositol trisphosphate + ATP = inositol tetrakisphosphate + ADP + H+." [GOC:ai]
synonym: "IP3K" BROAD []


id: GO:0008440
name: inositol-1,4,5-trisphosphate 3-kinase activity
namespace: molecular_function
def: "Catalysis of the reaction: 1D-myo-inositol 1,4,5-trisphosphate + ATP = 1D-myo-inositol 1,3,4,5-tetrakisphosphate + ADP + H+." [RHEA:11020]
synonym: "1D-myo-inositol-trisphosphate 3-kinase activity" BROAD []
synonym: "inositol trisphosphate 3-kinase activity" BROAD []
synonym: "inositol-trisphosphate 3-kinase activity" BROAD []
synonym: "Ins(1,4,5)P3 3-kinase activity" RELATED [EC:2.7.1.127]
synonym: "IP3 3-kinase activity" NARROW [EC:2.7.1.127]
synonym: "IP3K activity" NARROW [EC:2.7.1.127]

It looks OK as IP3K activity in the literature is normally used for inositol-1,4,5-trisphosphate 3-kinase activity.

I think you can close the ticket.

**Comment by ValWood** [comment]
Thanks both, closing.
