### ISSUE TITLE
NTR: BP:Target-directed microRNA degradation & MF term: Target-directed miRNA base-pairing activity (?)

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#24359]
***New BP Term: Target-directed microRNA degradation**

*Definition: The process in which a miRNA targeted for degradation by a non-coding RNA or mRNA. The binding of a miRNA by an RNA within a RISC complex resulting in either ubiquitin-mediated degradation of AGO protein or the displacement of the 3' end of the miRNA exposing it nucleases.  

*References: PMID:33184237, PMID:36207543, PMID:36150386

*Gene product name and ID to be annotated to this term: FBgn0263380, lncRNA:marge; FBgn0085430, Dora

*Parent term(s): is_a miRNA catabolic process GO:0010587
                         is_a negative regulation of miRNA-mediated gene silencing GO:0060965

***New MF Term:  Base-pairing target-directed miRNA-suppressor activity**

*Definition: A suppressor miRNA-mediated gene silencing by base-pairing with a miRNA within a RISC complex resulting in the promotion of the miRNA to nuclease-mediated degradation.

*References: PMID:33184237, PMID:36207543, PMID:36150386

*Gene product name and ID to be annotated to this term: FBgn0263380, lncRNA:marge

*Parent term(s): miRNA binding GO:0035198

*Note: I think that this is a sister term to miRNA inhibitor activity GO:0140869 rather than synonymous.

Tagging @gantonazzo @RLovering @pgaudet as this relates to miRNA project

**Comment by pgaudet** [comment]
PMID:36207543 is not a paper- its a  Nature 'Research highlights' citing PMID:36150386

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140958
+name: target-directed miRNA degradation
+namespace: biological_process
+def: "The process in which a miRNA is targeted for degradation by a non-coding RNA or mRNA. The binding of an RNA to a target miRNA within a RISC complex results in either ubiquitin-mediated degradation of AGO protein or the displacement of the 3' end of the miRNA, exposing it to nucleases." [PMID:33184237, PMID:36150386]
+synonym: "target-directed microRNA degradation" EXACT []
+synonym: "TDMD" EXACT []
+is_a: GO:0010587 ! miRNA catabolic process
+is_a: GO:0060965 ! negative regulation of miRNA-mediated gene silencing
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24359 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-16T06:53:51Z
+
+[Term]
+id: GO:0140959
+name: base-pairing target-directed miRNA suppressor activity
+namespace: molecular_function
+def: "An inhibitor activity that acts by base-pairing with a miRNA, exposing it to  nuclease-mediated degradation." [PMID:33184237, PMID:36150386]
+synonym: "base-pairing target-directed microRNA suppressor activity" EXACT []
+is_a: GO:0140678 ! molecular function inhibitor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24359 xsd:anyURI
+created_by: pg
+creation_date: 2022-11-16T07:00:15Z
+

**Comment by pgaudet** [comment]
Note that I changed the definition of 'base-pairing target-directed miRNA suppressor activity' so it sounds less 'processy'

**Comment by pgaudet** [comment]
I understand you want this a sister term to miRNA inhibitor activity GO:0140869 rather than synonymous, but we should improve the definition of GO:0140869. As things stand, it could be a child - the definition of 'miRNA inhibitor activity' is Stops, prevents or reduces the activity of a miRNA via base-pairing, direct binding and/or post-translational modification. An example of this activity is mediated by long non-coding RNAs (lncRNAs).

If we dont make that definition more specific, the new term could be a subtype of this activity, which acts by targeting the miRNA for degradation. 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi A

**Comment by RLovering** [comment]
Hi All

I think that we created the miRNA inhibitor activity GO:0140869 term for ncRNAs that have base-pairing target-directed miRNA suppressor activity see https://github.com/geneontology/go-ontology/issues/23028


    k, A regulatory network consisting of different types of ncRNAs. Cyrano, harbouring miR-7 binding sites, targets miR-7 for degradation and prevents miR-7 from repressing its target RNAs including the circRNA Cdr1as.

Proposed:

    Use new MF term GO:0140869 miRNA inhibitor activity
    BP: GO:0000512 lncRNA-mediated post-transcriptional gene silencing

Possibly Helen didnt see this term? I am happy for this term to be renamed as base-pairing target-directed miRNA suppressor activity but I don't think a new term is needed.

I think more edits are needed for 
*New BP Term: Target-directed microRNA degradation

*Definition: The process in which a miRNA targeted for degradation by a non-coding RNA or mRNA. The binding of a miRNA by an RNA within a RISC complex resulting in either ubiquitin-mediated degradation of AGO protein or the displacement of the 3' end of the miRNA exposing it nucleases.

The definition does not make sense wrt degrading a miR. Also this assumes that all miRs bound by a lncRNA are degraded due to inclusion in the RISC. This will not always be shown and if other mechanisms are identified ...?

We have the term: GO:0000512 lncRNA-mediated post-transcriptional gene silencing 
Definition:
A post-transcriptional gene silencing pathway in which regulatory long noncoding RNAs (lncRNAs) elicit silencing of specific target genes, often miRNAs or mRNAs. - again possibly Helen didn't see this term. if you decide the more specific term is required please make sure it is added as a child to GO:0000512 lncRNA-mediated post-transcriptional gene silencing 

Helen please look at the ticket [listed](https://github.com/geneontology/go-ontology/issues/23028) as we created terms for many lncRNA roles as listed in a review before requesting more GO terms for ncRNAs  

I think we discussed the possible parent GO:0060965 ! negative regulation of miRNA-mediated gene silencing but I am not sure we are happy with making the statement that neg reg a miR always neg regs  miRNA-mediated gene silencing. For example, I only annotate a miR as regulating a protein function/process if this downstream effect is actually shown. Also we have lots of transport terms that are likely to affect the homoestatis of the chemical transported but the transport terms are not listed as part of the homeostasis term.

Please do not release these terms until the definitions and placements in the ontology have been revised

Thanks

Ruth

**Comment by pgaudet** [comment]
Helen specifically wrote 

> Note: I think that this is a sister term to miRNA inhibitor activity GO:0140869 rather than synonymous

**Comment by RLovering** [comment]
but did you read the definition of the term and look at the ticket that lead to the creation of this term?

**Comment by RLovering** [comment]
*Definition: The process in which a miRNA targeted for degradation by a non-coding RNA or mRNA. The binding of a miRNA by an RNA within a RISC complex resulting in either ubiquitin-mediated degradation of AGO protein or the displacement of the 3' end of the miRNA exposing it nucleases.

seems to imply that there is degradation of AGO but not degradation of the contents of this complex especially as I am not sure that ubiquitin-mediated degradation complexes have RNases. Or are you implying that by degrading AGO you are exposing the doublestranded RNA to RNases that degrade doublestranded RNA?

**Comment by hattrill** [comment]
I am confused about the suggestion of this BP, @RLovering  GO:0000512 lncRNA-mediated post-transcriptional gene silencing:
is defined as
"A posttranscriptional gene silencing pathway in which regulatory RNAs elicit silencing of specific target genes, either by mRNA destabilization or inhibition of translation."

This is a lncRNA acting to inhibit miRNA-dependent gene silencing. It also does not need to be a lncRNA - it could be an mRNA sequence.

**Comment by hattrill** [comment]
My suggestion of a different MF was bacause the RNA acts at the level of the RISC complex, rather than a sponge activity etc. I am ok with using miRNA inhibitor activity, but the definition would need to be changed (Stops, prevents or reduces the activity of a miRNA via base-pairing, direct binding and/or post-translational modification. An example of this activity is mediated by long non-coding RNAs (lncRNAs).)

It reads as if the post-translational modification happens to the miRNA & base-pairing should be in the term label as that is the mechanism.

**Comment by RLovering** [comment]
Hi 
The problem is whether sponge can recruit RISC which is suggested in this article:
https://www.sciencedirect.com/science/article/pii/S0169409X14001045
And also it might not always be shown if a lncRNA is inhibiting miRs via binding alone or via the RISC eg:
https://pubmed.ncbi.nlm.nih.gov/33986850/ and therefore this information probably will not always be distinguished. In which case if we keep this term we need to have a parent for sponge - just sopping up but not degrading miRs and binding and causing degradation - presumably by RISC although I don't know if there are other methods for double stranded RNA being degraded. This article https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4070712/ seems to be saying that you can decide the mechanism based on the alignment of the sequence.

**Comment by hattrill** [comment]
Looking at [examples](https://docs.google.com/spreadsheets/d/1fCwIKATu8qj-wGnYcG7qoVQPLJOrIOEdmsL22YNMlYY/edit?usp=sharing) to see if it is possible to separate the processes for miRNA degradation via base-pairing with complementary RNAs

**Comment by hattrill** [comment]
Hi @RLovering I am just thinking if it makes sense to replicate the structure of mRNA stability wrt general decay mechanism and silencing activities for miRNAs - therefore, could annotate at the appropriate level of detail for the evidence i.e. be as vague as miRNA destabilization or as specific as lncRNA-mediated gene silencing by miRNA destabilization.

![Screenshot 2022-11-25 at 11 49 37](https://user-images.githubusercontent.com/11865746/203980980-30c05514-ff9f-4191-b81f-56312eb6bb61.png)

**Comment by hattrill** [comment]
looking at the examples of miRNA regulation by RNAs, I guess there are two types:

I think that for true "target-directed miRNA degradation":
1. RNA-miRNA mediated.
2. Occur within "RISC" ie the passanger:miRNA should get incorporated into RISC. 
3. The passenger stand should stay the same over time and not decrease, while the guide strand decreases.
4. There should be extensive base-pairing (and therefore sequence-specific)
5. Non-specific nucleases involved as results in exposure of miRNA to cellular nucleases (?)

These 'conditions' are not always met in the experiments.

It is more difficult to find a unifying definition for miRNA sponges:
Seems to be used for instances where the miRNA is degraded and when it is not. The difference is the sponge will be degraded too or it will just sequester the miRNA and levels will not change much.

@RLovering are you available tomorrow (Tues) for a quick Skype about this?

**Comment by hattrill** [comment]
For the MF I suggest that we have a single term.

**Merge:** miRNA inhibitor activity GO:0140869 and target-directed miRNA degradation GO:0140959

-this term could encompass both sponges and TDMD as the difference seems to lie in extensive the base-pairing is, which is something we can't capture in a MF term.

**Rename** this term so that it explicitly captures the base-pairing as part of the MF

e.g.
miRNA inhibitor via base-pairing activity
or
base-pairing miRNA suppressor activity

**Change definition** to be vaguely encompass RNAs that acts sponges and in TDMD and that the outcome will be the gene silencing activity of the miRNA (rather than any other activity). This gives us a firm criteria: must base-pair, must reduce gene-sliencing mediated by the miRNA.

"Stops, prevents or reduces the activity of miRNA-mediated gene silencing activity by base-pairing with the miRNA. An example of this activity is mediated by long non-coding RNAs (lncRNAs)."

add synonym: miRNA sponge

**Comment by hattrill** [comment]
From comparing RNA-mediated miRNA activity inhibition:


  | miRNA Sponge | Target-directed miRNA decay
-- | -- | --
Base-pairing between RNAs | Y | Y
Complementary | similar to miRNA-mRNA | Extended
Degradation of miRNA | No when sequestered/Y when degraded | Yes
Degradation of inhbitor RNA? | No when sequestered/Y when degraded | No (should be stabe)
Mechanism | Sequestering/Competition/cleavage of both in RISC; and suggested displacemnt from RISC | Displacement from RISC/destruction of RISC by Ub-mechabisn - required displacement of miRNA from PAS domain of AGO protein because of extended 3' bp'ing


 there tends to be those that are referred to a sponges/decoys and those that mediated target-directed miRNA degradation. The latter is easier to define and class as a process with steps, but the experiments that would help classify this as TDMD are not always done. The sponges/decoys are harder in that sometimes they sequester or act competitively with miRNA and sometimes this leads to degradation of the miRNA (and other RNA, from what I can glean). So, the BP would have to be described by the fate of the miRNA e.g. miRNA destabilization and/or we could go as specific as naming the GP responsible for the activity lncRNA-mediated gene silencing by miRNA destabilization, which I've mooted above.

https://docs.google.com/spreadsheets/d/1fCwIKATu8qj-wGnYcG7qoVQPLJOrIOEdmsL22YNMlYY/edit?pli=1#gid=794397174
<google-sheets-html-origin><style type="text/css"></style>

**Comment by pgaudet** [comment]
For GO:1903231 mRNA base-pairing translational repressor activity

- [ ] Add synonym: to the miRNA MF term: GO:1903231 mRNA base-pairing translational repressor activity ->>>  translational inhibitor activity via mRNA base-pairing 

- [ ] GO:1903231 : fix comment: This term is indended for microRNAs that act by base-pairing with a target mRNA.
->>> fix typo

**Comment by hattrill** [comment]
Hi @pgaudet I am re-opening this as after talking with Giula and Ruth we thought that the TDMD term should be "equilavent" in the ontology to lnc-mediated post-transcriptional gene silencing - both can act on miRNAs and both are 'silencing" miRNAs. We should annotate the regulation of miRNA gene silencing separately, I think rather than encoding it in the ontology.

So, could you make this an RNA-mediated gene silencing and post-transcriptional gene silencing child?

![Screenshot 2023-04-20 at 17 43 08](https://user-images.githubusercontent.com/11865746/233594543-a009afe5-ca06-44d2-a6da-3774f6bdb033.png)

**Comment by pgaudet** [comment]
Do you want to keep the current parent classes? 

'miRNA catabolic process'
and 
'negative regulation of miRNA-mediated gene silencing'
?

**Comment by hattrill** [comment]
Do you think that would be ok to  keep? Happy to if so.

**Comment by pgaudet** [comment]
The term now has 4 parents: 

RNA-mediated gene silencing
post-transcriptional gene silencing child
miRNA catabolic process
negative regulation of miRNA-mediated gene silencing


I dont think it should have both 'negative regulation of miRNA-mediated gene silencing' and 'RNA-mediated gene silencing' ; should it ? which one is it ?

**Comment by hattrill** [comment]
so, to be consitent with l  ncRNA-mediated post-transcriptional gene silencing then it should be  'RNA-mediated gene silencing' 
 but it seems odd to have 'negative regulation of miRNA-mediated gene silencing' as well to me also,

So, if we lose the connection with 'negative regulation of miRNA-mediated gene silencing' I think that is better (as it's indirect).
