### ISSUE TITLE
NTR: Multi-pass transmembrane protein insertion into ER membrane

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#24358]
Hi GO,

I would need a couple of terms for a complex that mediates insertion of multi-pass membrane proteins into the endoplasmic reticulum (ER) membrane.

Thanks

Sylvain

1)
Multi-pass transmembrane protein insertion into ER membrane
Category: Process
Definition: A process of protein insertion of multi-pass membrane proteins into the endoplasmic reticulum (ER) membrane.
Child of GO:0045048; P:protein insertion into ER membrane
PMID:36261528; 
PMID:36261522;

2)
Multi-pass translocon complex
Category: Component
Definition: The multi-pass translocon (MPT) complex mediates insertion of multi-pass transmembrane proteins into endoplasmic reticulum (ER) membrane. It is composed of subcomplexes, the GEL complex (composed of RAB5IF/OPTI and TMCO1), the BOS complex (composed of NCLN/Nicalin, NOMO and TMEM147) and the PAT complex (composed of WDR83OS/Asterix and CCDC47). The MPT complex associates with the SEC61 complex.

Child of  GO:0032991 protein-containing complex
Child of GO:0045048; P:protein insertion into ER membrane
PMID:36261528; 
PMID:36261522;

**Comment by sylvainpoux** [comment]
Hi Raymond, 

1)
Yes, we might link GO:0031204  to Multi-pass transmembrane protein insertion into ER membrane. The new finding here is that multi-pass membrane proteins are inserted via a new process which differs from insertion of proteins with few (1-3) transmembrane regions.

"The multi-pass translocon complex takes over after the SEC61 complex: following membrane insertion of the first few transmembrane segments of proteins by the SEC61 complex, the MPT complex occludes the lateral gate of the SEC61 complex to promote insertion of subsequent transmembrane regions."

It is why we definitively need a specific term for multi-pass membrane proteins

2) The multi-pass translocon complex differs from GO:0005784 Sec61 translocon complex. Since it inhibits this complex and takes over after the SEC61 complex. In my opinion, these 2 complexes should not be linked. 

Moreover, there composition strongly differs, while both complexes contain SEC61A, SEC61B and SEC61G, the multi-pass translocon complex does not contain OST.

Thanks

Sylvain

**Comment by sylvainpoux** [comment]
After discussing with @pgaudet, we arrived to the conclusion that we should refine the definition

Multi-pass transmembrane protein insertion into ER membrane
Category: Process
Definition: A process of protein insertion of multi-pass membrane proteins into the endoplasmic reticulum (ER) membrane. Insertion of multi-pass membrane proteins is mediated by the multi-pass translocon complex and takes place following membrane insertion of the first few transmembrane segments of proteins by the SEC61 complex to promote insertion of subsequent transmembrane regions
Child of GO:0045048; P:protein insertion into ER membrane
PMID:36261528;
PMID:36261522;

**Comment by ValWood** [comment]
I agree with the new term Multi-pass transmembrane protein insertion into ER membrane absolutely. 

For Multi-pass translocon complex  the term TMCO1 translocon
Was created to represent what is now called Multi-pass translocon complex.

I would repurpose this complex and rename it to Multi-pass translocon complex.

Suggest  slightly revised def:
An ER intramembrane protein complex involved in the insertion of multi-pass transmembrane proteins into the endoplasmic reticulum (ER) membrane.
Substrates enter via the lateral gate of the Sec61 translocon.

Comprises the GEL subcomplex (composed of RAB5IF/OPTI and TMCO1), the BOS subcomplex (composed of NCLN/Nicalin, NOMO and TMEM147) and the PAT subcomplex (composed of WDR83OS/Asterix and CCDC47). 

Exact synonym MPT complex

Then I would add the taxon restriction  “only in metazoa” because despite extensive searches I have only been able to identify the chaperone part (Pat complex) in yeast. 
Maybe for yeast the Sec61 + PAt is sufficient to handle all.
We can change the species scope if the missing  5 components turn up in yeast but this is unlikely because I am finding the related GET/EMC subunits as best hits.

**Comment by ValWood** [comment]
Re
GO:0031204 post-translational protein targeting to membrane, translocation 
Definition The process in which a protein translocates through the ER membrane posttranslationally.

This is a really confusing term.
https://github.com/geneontology/go-ontology/issues/20913

The definition isn’t about targeting at all. 
Targeting usually refers to the chaperoning of a protein to an organelle (i.e via the signal sequence). Targeting and translocation don’t make sense in the same term name, and the term name doesn’t mention ER.

One of it’s parents is
GO:0045047  protein targeting to ER
The process of directing proteins towards the endoplasmic reticulum (ER) using signals contained within the protein. 
GO:0045047 IS describing targeting.

The  term  GO:0031204 post-translational protein targeting to membrane, translocation 
 was possibly created to refer to the general transport across the ER membrane into the lumen, (i.e protein transport into the ER) because I don’t see a term for this. 
This is likely because most of the 23 EXP are to Sec61 subunits.
But it is all unclear.  

All of the terms under ‘targeting that do not refer to targeting need to be obsoleted and re-established in the correct place.

We need a general term for transport into the ER (lumen or membrane), because some pathway components are shared, and the specific terms  (like membrane insertion) could be positioned underneath.

**Comment by ValWood** [comment]
I just realised we never actually added TCO1 translocon !
https://github.com/geneontology/go-ontology/issues/22000
But it is the same thing.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160063
+name: multi-pass transmembrane protein insertion into ER membrane
+namespace: biological_process
+def: "A process of protein insertion of multi-pass membrane proteins into the endoplasmic reticulum (ER) membrane. Insertion of multi-pass membrane proteins is mediated by the multi-pass translocon complex and takes place following membrane insertion of the first few transmembrane segments of proteins by the SEC61 complex to promote insertion of subsequent transmembrane regions." [PMID:36261522, PMID:36261528]
+is_a: GO:0045048 ! protein insertion into ER membrane
+created_by: rynl
+creation_date: 2022-11-17T23:38:14Z

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160064
+name: multi-pass translocon complex
+namespace: cellular_component
+def: "A protein complex that mediates the insertion of multi-pass transmembrane proteins into endoplasmic reticulum (ER) membrane. Substrates enter via the lateral gate of the Sec61 translocon. The complex comprises the GEL subcomplex (composed of RAB5IF/OPTI and TMCO1), the BOS subcomplex (composed of NCLN/Nicalin, NOMO and TMEM147) and the PAT subcomplex (composed of WDR83OS/Asterix and CCDC47)." [] {comment="PMID:36261522", comment="PMID:36261528"}
+synonym: "MPT complex" EXACT []
+synonym: "TMCO1 translocon" RELATED []
+is_a: GO:0032991 ! protein-containing complex
+relationship: capable_of_part_of GO:0160063 ! multi-pass transmembrane protein insertion into ER membrane
+created_by: rynl
+creation_date: 2022-11-18T01:16:20Z

**Comment by raymond91125** [comment]
New terms added. Let me know if there's more to do. Thanks!
