### ISSUE TITLE
plan to revise chromosome segregation branch and define start and end points

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24377]
First these are the stages of chromosome segregation ordered temporally to the best of my knowledge as a starting point.

 We should define "chromosome segregation" as beginning in M-phase.
The order of events (for mitotic chromosome segregation)
**prophase** 
centrosome/SPB duplication (is this true for metazoa or does this occur in G2?)
followed by spindle pole body migration/spindle formation
chromosome condensation (does this happen simultaneously?)

**prometaphase**
kinetochores assembly onto CENP-A chromatin (question-  is any of the inner kinetochore assembled during interphase?)
lateral attachment of chromosomes to spindle microtubules

**metaphase** 
chromosome alignment/ end-on attachment of chromosomes to microtubule spindles

**anaphase**
- mitotic anaphase A
sister chromatid separation /cohesin kleisin cleavage (controlled by the SAC/APC)
- mitotic anaphase B
spindle elongation (phase 3) distance is lengthened between poles of the mitotic spindle during 

I'm a bit unsure about the end point.....

@colinlog @manulera @pgaudet  could you review my suggestions?

**Comment by ValWood** [comment]
These changes are required to align with the above:
https://github.com/geneontology/go-ontology/issues/24376
https://github.com/geneontology/go-ontology/issues/24375
https://github.com/geneontology/go-ontology/issues/24374

**Comment by ValWood** [comment]
Also need to fit this in
https://github.com/geneontology/go-ontology/issues/13542

**Comment by manulera** [comment]
Some comments:
* Another event that coincides with the start of mitosis in wild-type yeast is the disappearance of cytoplasmic microtubules (not sure if this is relevant here).
* SPB duplication starts before mitosis: https://pubmed.ncbi.nlm.nih.gov/15385623/

Not entirely sure about the exact timing of events in prophase and metaphase that you ask about, but we can discuss this and I could read about it.

Regarding the end of anaphase B. I don't think it is entirely established, for fission yeast I would use the spindle disassembly as an indicator of the end of anaphase B, because:
* Slowing down / arresting spindle elongation genetically (klp9D -kinesin 6- PMID:19686686) or with drugs (cerulenin PMID:35293864) delays the end of anaphase.
* Similar phenotypes have been observed in animal cells in which a certain spindle length is required for mitotic exit: https://elifesciences.org/articles/47646

However, I don't know what would be a consensual sign of end of anaphase B, perhaps chromosome decondensation?

For example, deletion of imp1 in fission yeast (PMID:32502403) prevents spindle degradation (eventually spindles are cut by the cytokinetic ring), and deletion of kinesin-8 or other APC-related components in budding yeast delay spindle disassembly and mitosis lasts longer (PMID:21079246). In these cells, the microtubule cytoskeleton structures characteristic of interphase do not appear until the spindle disassembles, and probably chromosomes remain condensed (although this has not been directly imaged, I think).

In the animal cell paper mentioned above, the picture is similar, and they specifically looked at chromosome decondensation and showed that chromosome decondensation and nuclear envelope reformation (what they consider signs of mitotic exit) require the spindle to reach a certain length.

![image](https://user-images.githubusercontent.com/22526102/202511374-f2655138-83ad-4ddd-b456-060e9912bd69.png)

So maybe chromosome decondensation is a good indicator of end of ana B?
