### ISSUE TITLE
Change label GO:0052151 positive regulation by symbiont of host apoptotic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24503]
GO:0052151 positive regulation by symbiont of host apoptotic process

should be 'induction' 

+ have taxon constraints to prevent host proteins being annotated. 

@genegodbold

**Comment by edwong57** [comment]
I changed the term name to: "induction by symbiont of host apoptotic process' and added 'positive regulation by symbiont of host apoptotic process' as an exact_synonym. I'm not sure how/what taxon constraints should be added. Please let me know if I should remove the synonym, but I figured it should be added since that was the previous term name.

**Comment by pgaudet** [comment]
Hi @edwong57 

This looks good. Dont worry about the taxon constraints; we want to add these to a more general parent (at some point). 

Thanks!

**Comment by genegodbold** [comment]
Hey @pgaudet, how are you seeing this term work out? I've got close to 200 symbiont (parasite) sequences that inhibit or promote host apoptotic processes. I thought we had come to a conclusion that "positive regulation" should be reserved for intra-host homeostatic processes, no? *Induction* doesn't seem right because these things aren't the host *reacting* to the symbiont, this is the symbiont executing a host cell or preventing a host cell from being executed. That's a different thing, yes?

**Comment by pgaudet** [comment]
Hi @genegodbold 

I am not sure I am following - 

> I thought we had come to a conclusion that "positive regulation" should be reserved for intra-host homeostatic processes

Exactly, which is why we changed that one to induction, to describe that the symbiont is affecting a host process. Right ?

**Comment by genegodbold** [comment]
Dear @pgaudet, I could be wrong, but I thought we had reserved *induction* for something that the host does in reaction to a symbiont and not dependent on anything other than the (host)-detected presence of the symbiont.

We need some active terms for when a symbiont/parasite does something to a host. Here are some possibilities for verbs that, I think, indicate that something non-normal and non-host-directed is occurring:
- suppress
- subvert
- disrupt
- defeat
- counter
- inhibit
[the above terms seem appropriate for when a host process is *diminished* by the parasite]
- exacerbate
- provoke
- stimulate
[these terms seem appropriate for when a host process is increased/supplemented by the parasite]

What do you think?

**Comment by pgaudet** [comment]
I want to make sure I understand your proposal - are you suggesting we use a specific terms for host disturbing a symbiont process, and a different terms for the symbiont disturbing the host ?

**Comment by genegodbold** [comment]
Hey @pgaudet, I wasn't explicitly doing that, but that makes sense to me. The host innate immune system is *induced* by the symbiont (particularly a pathogen). That is, the **detected presence** of the symbiont/parasite starts a normal process in the host that upregulates host molecules having to do with immunity.

What the parasite is doing in the host is NOT a normal host homeostatic process and therefore it makes sense to distinguish it. Also, one of the things that makes it hard to find GO terms that are specifically related to pathogenesis is that the GO terms that do exist--FOR PARASITE PROCESSES--are frequently contaminated with host proteins (as we have seen and remarked upon). The process terms SHOULD be distinguished for things that the host does to the parasite and the parasite does to the host.
