### ISSUE TITLE
Missing parent: GO:1990542 mitochondrial transmembrane transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24829]
* **GO term ID and label for which you request a new superclass**

GO:0006839   mitochondrial transport
Transport of substances into, out of or within a mitochondrion.

does not have

GO:0140021 mitochondrial ADP transmembrane transport

Or 

GO:1990544 mitochondrial ATP transmembrane transport

As descendants

**Comment by ValWood** [comment]
Actually most things seem to be protein transport under here,

https://www.pombase.org/term/GO:0006839

non of the transmembrane transport so maybe this is intentions, but transmembrane transport used to also be under here and ins't excluded by te definition.

**Comment by ValWood** [comment]
So this is the issue:


GO:1990542 mitochondrial transmembrane transport
2021-11-20 | Deleted | RELATION | is a GO:0006839 (mitochondrial transport)

**Comment by pgaudet** [comment]
Where do you see that ? 

I see the relations here

<img width="625" alt="image" src="https://user-images.githubusercontent.com/4782928/215507390-0c3c5797-2735-48ed-a407-e11a1c41f353.png">

**Comment by pgaudet** [comment]
In fact what is missing is the relation between 'mitochondrial transport' and 'mitochondrial transmembrane transport' 

This is because the logical definitions dont use the same genera: 

mitochondrial transmembrane transport
transport
 and ('results in transport across' some 'mitochondrial membrane')
 and ('results in transport to from or in' some mitochondrion)


**mitochondrial transport**
'intracellular transport'
 and ('results in transport to from or in' some mitochondrion)

**mitochondrial transmembrane transport**
transport
 and ('results in transport across' some 'mitochondrial membrane')
 and ('results in transport to from or in' some mitochondrion)


I changed 'mitochondrial transmembrane transport to intracellular transport, these should now be children of each other

Thanks, Pascale
