### ISSUE TITLE
Change in GO subset goslim_mouse

### ISSUE THREAD

**Issue by mdolanme** [geneontology/go-ontology#24835]
MGI wants to remove 'cell death' GO:0008219 from the goslim_mouse GO subset and add 'programmed cell death' GO:0012501 to the subset.

**Comment by ValWood** [comment]
Hi 
@tberardini @lreiser 
@hattrill @gantonazzo 
I will do the  same for TAIR and FlyBase

@mdolanme are you the contact for Alliance, if not who should I inform?

@pgaudet  I will move the CHEMBL one, but we should let them know because they may be using the term in the broader 'any cell death' context.

**Comment by tberardini** [comment]
I'm still working my way through the annotations but please go ahead, @ValWood.

**Comment by mdolanme** [comment]
Maybe better to have Kimberly be the GO-Alliance contact (if that works for her).
The biological function working group is currently in maintenance mode.

**Comment by pgaudet** [comment]
ChEMBL contact is @BZdrazil
