### ISSUE TITLE
Term merge: polynucleotide adenylyltransferase activity (GO:0004652) & RNA adenylyltransferase activity (GO:1990817)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24859]
* **Terms to be merged: Provide GO ID and term label**
polynucleotide adenylyltransferase activity (GO:0004652)
RNA adenylyltransferase activity (GO:1990817)

- polynucleotide adenylyltransferase activity (GO:0004652) has a single is_a child term, RNA adenylyltransferase activity (GO:1990817) - there is no "DNA adenylyltransferase activity" sister GO term
- The RHEA:11332 xref on polynucleotide adenylyltransferase activity (GO:0004652) specifies RNA, so should be on RNA adenylyltransferase activity (GO:1990817)
- The EC:2.7.7.19 xref on polynucleotide adenylyltransferase activity (GO:0004652) also specifies RNA in the 'reaction' (matching RHEA:11332), though the second comment on the EC entry (in bold below) specifies DNA - I suspect this is a typo for "RNA" @kaxelsen?

=> Seems like GO:0004652 and GO:1990817 could be merged with the final term name being "poly(A) RNA polymerase activity", retaining the definition on GO:1990817

id: GO:0004652
name: polynucleotide adenylyltransferase activity
def: "Catalysis of the template-independent extension of the 3'- end of an RNA or DNA strand by addition of one adenosine molecule at a time. Cannot initiate a chain 'de novo'. The primer, depending on the source of the enzyme, may be an RNA or DNA fragment, or oligo(A) bearing a 3'-OH terminal group." [EC:2.7.7.19]
xref: EC:2.7.7.19
xref: MetaCyc:POLYNUCLEOTIDE-ADENYLYLTRANSFERASE-RXN
xref: Reactome:R-HSA-72185 "mRNA polyadenylation"
xref: RHEA:11332
is_a: GO:0070566 ! adenylyltransferase activity

id: GO:1990817
name: RNA adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the template-independent extension of the 3'- end of an RNA strand by addition of one adenosine molecule at a time. Cannot initiate a chain 'de novo'. The primer, depending on the source of the enzyme, may be an RNA, or oligo(A) bearing a 3'-OH terminal group." [GOC:vw]
is_a: GO:0004652 ! polynucleotide adenylyltransferase activity

https://enzyme.expasy.org/EC/2.7.7.19
Name: polynucleotide adenylyltransferase.
Alternative Name(s): NTP polymerase, poly(A) polymerase, RNA adenylating enzyme.
Reaction: ATP + RNA(n) <=> diphosphate + RNA(n)-3'-adenine ribonucleotide
Comment(s):  Also acts slowly with CTP. **Catalyzes template-independent extension of the 3'-end of a DNA strand by one nucleotide at a time**. Cannot initiate a chain de novo. The primer, depending on the source of the enzyme, may be an RNA or DNA fragment or oligo(A) bearing a 3'-OH terminal group.

https://www.rhea-db.org/rhea/11332
ATP + RNA(n) = diphosphate + RNA(n)-3'-adenine ribonucleotide

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0004652 polynucleotide adenylyltransferase activity' , and replace the term by GO:1990817 RNA adenylyltransferase activity, because these two terms are equivalent. 

There are annotations by the following groups: 

(20) SGD
(16) UniProt
(5)	FlyBase
(5)	PomBase
(5)	WB
(2)	GeneDB
(1)	CGD
(1)	ComplexPortal
(1)	EcoliWiki
(1)	MGI


There are 6 InterPro mappings:
InterPro:IPR007012
InterPro:IPR007010
InterPro:IPR014492
InterPro:IPR040136
InterPro:IPR040137
InterPro:IPR045862
 
1 UniRule
UniRule:UR000999770
 
1 EC: will be moved in the ontology
EC:2.7.7.19

1 RHEA: will be moved in the ontology
RHEA:11332


You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24859

Thanks, Pascale
