### ISSUE TITLE
Q telomere capping (GO:0016233)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24931]
Should telomere capping be an activity, rather than a process?

The process is

GO:0031848 | protection from non-homologous end joining at telomere

**Comment by ValWood** [comment]
I also see
GO:0048239   negative regulation of DNA recombination at telomere

but this is really the same as
GO:0031848 | protection from non-homologous end joining at telomere

The end protection prevents recombination AND non-homologous end joining

**Comment by deustp01** [comment]
> Should telomere capping be an activity, rather than a process?

Here's the definition: "A process in which telomeres are protected from degradation and fusion, thereby ensuring chromosome stability by protecting the ends from both degradation and from being recognized as damaged DNA. May be mediated by specific single- or double-stranded telomeric DNA binding proteins."

That sounds like capping comprises one or more binding events. If these can be captured and individuated then it's a process. To the extent that binding is out of scope for GO (because of the issue of figuring out what gene product enables it), tallying the events and gene products is harder.

**Comment by ValWood** [comment]
I was wondering what the molecular function of "shelterin" would be , other than "telomere binding"

**Comment by ValWood** [comment]
see
https://github.com/geneontology/go-ontology/issues/23997
which is closely related.
