### ISSUE TITLE
NTR: [Negative regulation of membrane depolarization magnitude]

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24954]
Please provide as much information as you can: 

* **Suggested term label:**
Negative regulation of membrane depolarization magnitude

* **Definition (free text)**
Any process that decreases the extent of membrane depolarization. Membrane depolarization is the process in which membrane potential changes in the depolarizing direction from the resting potential, usually from negative to positive.

* **Parent term(s)**
has parent regulation of membrane depolarization [GO:0003254]

**Comment by pgaudet** [comment]
Hi @sharan-gh 

Would you please include references for all the terms you request. Also, an example of a gene that would be annotated to this would be useful. The rationale being that this allows GO editors to ensure that the terms are created in a way that is consistent with the rest of the ontology. 

Thanks, Pascale

**Comment by sharan-gh** [comment]
Hi @pgaudet,

Yes, I will add references and gene annotations wherever possible. I have more terms to add, but will make sure I have references and genes assigned before opening a ticket.

Thank you,
Sharan

**Comment by ValWood** [comment]
This does not seem like a GO process.  I thought we do not add terms anymore unless there is a use case as in a specific gene to annotate because of the issues this has caused in the past with orphan terms. I would say we should keep to this rule and only add terms with clear, published annotation use cases. But the "magnitude" of a signal seems out of scope for GO. We haven't added magnitude of any type of signalling pathway- we would use the "negative regulation" term here.
