### ISSUE TITLE
BP for calcium ion importer

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24965]
I have 3 term choices 

<img width="381" alt="______FRIDAY GO TRACKER" src="https://user-images.githubusercontent.com/7359272/220078326-e6012d45-c9ab-4602-b65e-f7212a79ab39.png">

@pgaudet  what is the preferred solution?
Can I add 
Calcium ion import across plasma membrane into cytosol
(or does import imply import into cell- this isn't necessarily how it is used, I see it used  also for ER->cytosol)

**Comment by pgaudet** [comment]
There are a lot of inconsistencies in that branch. 

To me, just 'import' doesn't mean anything, it could be 'import into cell', 'import into ER', vacuole etc

I thought for a while that 'import across the plasma membrane' was better for bacteria and plants, because many of the transporters are at the plasma membrane, but maybe the best is 'import into cell' 

'calcium import into cytosol' is not clear enough, it can mean from the extracellular medium or from intracellular stores. 

Specifically for calcium, there seems to be way too many terms already.  Should we look at that on one of our calls? 

Pascale

**Comment by ValWood** [comment]
Yes, no hurry I just want to annotate them consistently.

**Comment by ValWood** [comment]
I will add the term I  needed
calcium ion import across plasma membrane

**Comment by ValWood** [comment]
Calcium import across plasma membrane should be a child of 
calcium ion import
and
calcium ion import into cytosol

(these two terms should perhaps be 'transmembrane' terms but that can be looking into later. I just want to add the missing parent here to suppress summarize the annotation  better)


<img width="424" alt="Screenshot 2023-12-01 at 17 09 26" src="https://github.com/geneontology/go-ontology/assets/7359272/24d10a20-143a-4e9d-8aa7-9d21d06f949c">

**Comment by pgaudet** [comment]
I would lean towards obsoleting GO:0070509 calcium ion import  (and all "import" terms that dont mention where a substrate is imported), as well as 'GO:1902656 calcium ion import into cytosol', since that includs both import from extracellular and import from calcium stores. 

 Most likely the term curators were trying to use was calcium import across plasma membrane.

**Comment by ValWood** [comment]
I agree, I only added these to fix a short term problem of function predictions.
But all substrate specific transport needs review/merge. I was worried it might take longer than  the next batch of function predictions ;)
Plus it's easier to do the obsolete and replace if the child terms are in the correct place (unless these had been isolated because the obsoletion was already in progress?)
