### ISSUE TITLE
cell killing vs cell death

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25174]
@pgaudet  Should these be related in GO?

**Comment by pgaudet** [comment]
I dont think so - killing a cell means killing another cell, and is typically a defense reponse (that bit needs to be improved, I think it's missing from the ontology), cell death is often an internal cellular program. I am not sure how we mode when a cell induces apoptosis in another cell ?

**Comment by ValWood** [comment]
OK, I think it has probably been used incorrectly. I can see that immune cell mediated cell killing belongs under here, but a lot of the co-annotations are to
for instance, 
GO:0150064 vertebrate eye-specific patterning
GO:0036257 multivesicular body organization
GO:0008584  male gonad development
GO:0051402 neuron apoptotic process
GO:0008340   determination of adult lifespan
GO:0007431 salivary gland development
GO:0008285 negative regulation of cell population proliferation
Should the definition really be more specific  in the context of defense?

**Comment by pgaudet** [comment]
Looks like these are developmental ?

**Comment by ValWood** [comment]
Yep. It seems that apoptosis in the context of development should. be excluded from cell killing?

**Comment by pgaudet** [comment]
Definitely! 

Although in this case I wonder, looking at the first one GO:0150064 vertebrate eye-specific patterning - there are 3 EXP annotations, including 2 to complement system proteins, which are likely killing as a defense response in some pathway independent of eye patterning.

**Comment by pgaudet** [comment]
The third being integrin, also involved in immune processe

**Comment by pgaudet** [comment]
[complement-mediated synapse pruning](http://amigo.geneontology.org/amigo/term/GO:0150062)

**Comment by pgaudet** [comment]
I suspect you are getting these co-annotations from children of cell killing

'complement-dependent cytotoxicity'
'leukocyte mediated cytotoxicity'
'microglial cell mediated cytotoxicity'
'natural killer cell mediated cytotoxicity'
'neutrophil mediated cytotoxicity'
'T cell mediated cytotoxicity'

which as far as I remember could not be moved under 'killing of cells of another organism' because they also serve to eliminate tumor cells ('GO:0002420 natural killer cell mediated cytotoxicity directed against tumor cell target'
'GO:0002419 T cell mediated cytotoxicity directed against tumor cell target') (and now I see, during development).  The tumor cell process could probably be moved out.  

For the developmental processes ideally we'd have a new branch under developmental process. I am not sure how people annotate tumor cell elimination (and where these annotations shoul.

**Comment by ValWood** [comment]
There are ~400 annotation to both 
GO:0001906 cell killing
GO:0012501 programmed cell death
with regulates closure
