### ISSUE TITLE
Change label 'GO:0000139 Golgi membrane' to Golgi apparatus membrane' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25187]
To be consistent with other 'Golgi' terms, the term label of 'GO:0000139 Golgi membrane' should be changed  to Golgi apparatus membrane'

**Comment by ValWood** [comment]
It's usually referred to as "Golgi membrane" though (97% PubMed).
and we have lots of other terms Golgi which don't specify "apparatus" (cisterna, lumen). Putting apparatus in here sounds a bit weird?

**Comment by pgaudet** [comment]
Right - maybe add as a synonym? This term should be returned when searching for Golgi apparatus.

**Comment by pgaudet** [comment]
Also consider adding 'Golgi apparatus' in the synonyms of these terms (if they are not already there): 

'Golgi cis cisterna membrane' http://purl.obolibrary.org/obo/GO_1990674
'Golgi cis cisterna' http://purl.obolibrary.org/obo/GO_0000137
'Golgi cisterna membrane' http://purl.obolibrary.org/obo/GO_0032580
'Golgi cisterna' http://purl.obolibrary.org/obo/GO_0031985
'Golgi organization' http://purl.obolibrary.org/obo/GO_0007030
'Golgi reassembly' http://purl.obolibrary.org/obo/GO_0090168
'Golgi disassembly' http://purl.obolibrary.org/obo/GO_0090166
'Golgi distribution to daughter cells' http://purl.obolibrary.org/obo/GO_0090167
'Golgi inheritance' http://purl.obolibrary.org/obo/GO_0048313
'Golgi localization' http://purl.obolibrary.org/obo/GO_0051645
'Golgi lumen acidification' http://purl.obolibrary.org/obo/GO_0061795
'Golgi lumen' http://purl.obolibrary.org/obo/GO_0005796
'Golgi medial cisterna membrane' http://purl.obolibrary.org/obo/GO_1990675
'Golgi medial cisterna' http://purl.obolibrary.org/obo/GO_0005797
'Golgi medial cisterna-derived vesicle fusion with Golgi cis cisterna membrane' http://purl.obolibrary.org/obo/GO_1990690
'Golgi membrane coat protein complex assembly' http://purl.obolibrary.org/obo/GO_0048197
'Golgi membrane fusion' http://purl.obolibrary.org/obo/GO_0036504

**Comment by raymond91125** [comment]
I'm not sure if there is any distinction between Golgi, Golgi apparatus, Golgi body, and Golgi complex (see Wikipedia). For GO:0005794, Golgi complex is an exact synonym whereas Golgi is a broad synonym and there is no "Golgi body" synonym (but it is there for the term 'Golgi localization').

That said, I think adding all the synonyms to all the terms that are about 'Golgi' is probably an overkill but doing it just for some terms seems haphazard. There are a lot more terms that contain "Golgi" than what's in the list above. Text searching technology should be sophisticated enough to retrieve the synonyms automatically. For example, when I Google search Golgi localization, some of the top hits contain the string "Golgi apparatus". We can expect this ability to get better.

If we think there is enough value to add all possible synonyms now, we should do that programmatically so that they are done more systematically. And the code could be applied to other similar cases.

What do you think? Thanks.
