### ISSUE TITLE
Review problem taxon constraints

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#25400]
I removed these constraints from `only_in_taxon.tsv` because they slipped through QC checks and were causing unsatisfiable classes:

```
GO:0010098	suspensor development	NCBITaxon:6072	Eumetazoa
GO:0031154	culmination involved in sorocarp development	NCBITaxon:33680	Myxogastria	
GO:0031152	aggregation involved in sorocarp development	NCBITaxon:33680	Myxogastria	
GO:0099138	altruistic chimeric sorocarp development	NCBITaxon:33680	Myxogastria	
```

One reason is that Myxogastria wasn't yet in our taxon import.

**Comment by pgaudet** [comment]
GO:0010098, suspensor development >> suspensor is a plant structure ; do we inherit TC from PO? 
Others (GO:0031154, GO:0031152, GO:0099138) are currently Only in Taxon | 33083 | Dictyostelia, which is a [Eumycetozoa](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=142796&lvl=3&lin=f&keep=1&srchmode=1&unlock), not a Myxogastria

The common parent would be [Evosea](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=2605435&lvl=3&lin=f&keep=1&srchmode=1&unlock) 

@ValWood how did you pick up these as terms needing TCs? (since they already had TCs...) 

Thanks, Pascale

**Comment by ValWood** [comment]
They came through the function prediction pipeline. They did make predictions on obsolete terms too, but I thought that I checked them all. The suspensor development doesn't have one.

It's weird that I would put these 3 anyway since the taxon constraint would go on the parent "sorocarp development" not on each child.  I think I must have mixed up my checked list with the  list of all the terms which had predictions.

**Comment by pgaudet** [comment]
We may get a TC from PO for GO:0010098, suspensor development - I dont dare loading the Protégé plugin

I think @dustine32 generates a full list of all TCs for PAINT - @dustine32 is there some place we can access a current version of this file? 

Thanks, Pascale

**Comment by ValWood** [comment]
I don't see a tax constraint for GO:0010098, suspensor development in QuickGO though. I would see it there from any source wouldn't I?

**Comment by pgaudet** [comment]
No, quickgo does not show TC coming outside of GO.

**Comment by dustine32** [comment]
@pgaudet Here is the current file used by PAINT, generated using [gaferencer](https://github.com/geneontology/gaferencer) and based on the 2023-03-06 GO release ontology:
http://data.pantherdb.org/TaxonConstraints/TaxonConstraintsLookup.txt

A newer file based on the 2023-05-10 GO ontology should be available in a few days.

**Comment by balhoff** [comment]
@pgaudet @ValWood 

![image](https://github.com/geneontology/go-ontology/assets/210210/b29d1a56-cec9-4129-b165-a64d582cf14c)

**Comment by pgaudet** [comment]
Thanks @balhoff  - @ValWood this is what the taxon plugin does (but it makes Protégé very slow)

**Comment by ValWood** [comment]
Can this be closed?

**Comment by balhoff** [comment]
@ValWood if you are satisfied with the taxon constraints on those terms, then yes please close.

**Comment by ValWood** [comment]
The sorocarp terms have constraints.
GO:0010098	suspensor development doesn't

@pgaudet mentions above this may come from PO. I don't know how that works. Happy to close if it will come from elsewhere.
