### ISSUE TITLE
NTR disruption of anatomical structure in another organism, disruption of cell in another organism and disruption of tissue in another organism

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25514]
+[Term]
+id: GO:0141060
+name: disruption of anatomical structure in another organism
+namespace: biological_process
+def: "The disruption of the an anatomical structure of another organism, leading to damage or temporary subversion of that structure." []
+is_a: GO:0044419 ! biological process involved in interspecies interaction between organisms
+created_by: pg
+creation_date: 2023-06-07T14:40:30Z
+
+[Term]
+id: GO:0141061
+name: disruption of cell in another organism
+namespace: biological_process
+def: "The disruption of the a cell of another organism, leading to damage or temporary subversion of that cell." []
+is_a: GO:0141060 ! disruption of anatomical structure in another organism
+created_by: pg
+creation_date: 2023-06-07T14:41:21Z
+
+[Term]
+id: GO:0141062
+name: disruption of tissue in another organism
+namespace: biological_process
+def: "The disruption of the a tissue of another organism, leading to damage or temporary subversion of that tissue." []
+is_a: GO:0141060 ! disruption of anatomical structure in another organism
+created_by: pg
+creation_date: 2023-06-07T14:41:39Z

**Comment by pgaudet** [comment]
@genegodbold please provide some references.

**Comment by pgaudet** [comment]
I also reorganized that branch to include existing terms: 

<img width="474" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/d63670f0-5599-415e-880f-8e23c6eb13eb">


So that we now have two main branches: 

- 'disruption of anatomical structure in another organism'
- and 'modulation of process of another organism'

**Comment by genegodbold** [comment]
**Tissue disruption**: 
1. Aeromonas cytotoxic enterotoxin (Act) from _Aeromonas hydrophila_--Act has hemolytic, cytotoxic, and enterotoxic activity. Act produces extensive damage to the epithelium of the small intestine [PMID:8330262][PMID:9673226]. Act is secreted via a T2SS [PMID:24199174]. Act causes degeneration of crypts and villi of the small intestine in rats. Act activates proinflammatory cytokine and eicosanoid cascades in host macrophages and a rat intestinal epithelial cell line which leads to tissue damage and a fluid secretory response [PMID:11895956].
2. CagA from _Helicobacter pylori_: CagA is recruited to the host cell membrane, there interacting with the tight junction proteins ZO-1 and JAM, forming a multiprotein complex at the bacterial attachment site and altering the composition and function of tight junctions. They become leaky [PMID:12775840]. CagA activates the hepatocyte growth factor receptor pathway, leading to host cell scattering and proliferation. This perturbs the integrity of another type of cell-to-cell junction, the adherent junction, composed of the protein E-cadherin. The E-cadherin proteins are internalized and redistributed [PMID:16102958].
3. Cell-cycle inhibiting factor (Cif) from _Escherichia coli_: Cif has a cytopathic effect on intestinal epithelial cells. This is characterized by a progressive recruitment of focal adhesion plaques leading to the assembly of stress fibers and inhibition of the cell cycle at the G2/M phase transition. Cells in this state do not mitose but continue to replicate DNA. EPEC and EHEC strains that lack Cif expression do not produce a cytopathic effect upon infection of host cells. This effect is restored upon complementation with functional Cif [PMID:14651638].
4. Extracellular serine protease (EspP, protease secreted by STEC, PssA) from _Escherichia coli_: EspP/PssA is a plasmid-encoded serine protease secreted from E. coli that is cytotoxic to Vero cells and causes changes in actin morphologies [PMID:9379905]. It is a class-1 SPATE protein that proved to be only cytopathic and not cytotoxic to other cell lines [PMID:23689588]. EspP can polymerize and form cable-like structures that correlate with the cytopathic effects on cultured epithelial cells [PMID:20688909].
5. Exfoliative toxin A and B (Eta, Etb) from _Staphylcocccus aureus_: Exfoliative toxin A and B are the specific virulence factors responsible for Staphylococcal scalded skin syndrome, a generalized blistering skin disease induced by _S. aureus_. Eta  cleaves desmoglein 1, a desmosomal adhesion molecule. Inactivation of desmoglein 1 results in the formation of blisters [PMID:11982763]. Desmoglein-1 plays a key role in maintaining the structure and barrier function of the epidermis.  Exfoliative toxins cleave a single peptide bond in the extracellular domain of desmoglein 1 and do not cleave the closely related molecules desmoglein 3 or E-cadherin. Loss of desmoglein 1 results in the loss of intercellular adhesion and allows bacteria to form blisters under the epithelial sheet, providing protective niches in which they can survive and proliferate. Exfoliative toxins produced by S. aureus rapidly diffuse into the skin tissue [PMID:16102958]. ETA causes disorganization and disruption of the startus spinosum and the stratum granulosum, two cellular layers of epidermis [PMID:9261066]. The crystal structures of Eta, Etb, and Etd have been solved [PMID26299923].

**Comment by genegodbold** [comment]
**Larger scale disruption?**
1. Intravenous injection of 37.5 microgram of **edema factor** with 37.5 microgram of protective antigen into female BalbC/J mice causes widespread histopathological lesions in the adrenal glands, lymphoid organs, bone, bone marrow, gastrointestinal mucosa, heart, kidneys, reproductive tract mucosa and follicular cells, and submandibular glands. No lesions of the liver or brain are observed. All seven female BalbC/J mice given 37.5 microgram of EF + 37.5 microgram of PA (i.v.) died within 60 h with a median survival time of 40 hours. All ten mice given 50 microgram of each and all four mice given 100 microgram of each died within 40 and 10 hours respectively with median survival times of 27 and 6 h respectively. Of the (6) mice given 25 microgram of each, only two died (within 40 h) while the rest survived. Depending on the administered dose of ET to mice, within 5-20 minutes the animals exhibit decreased mobility and increased difficulty in breathing. At the highest dose (100 microgram), mortality occurred in as little as four to five hours [PMID:16251415]. Edema toxin specifically targets hepatocytes during _Bacillus anthracis_ infection [PMID:23995686].
2. Community-acquired respiratory distress syndrome (CARDS) toxin: **CARDS toxin** has ADP-ribosylating and vacuolating activities. Intranasal administration of the recombinant toxin to rodents (700 picomoles) and primates recapitulates most of the symptoms of _Mycoplasma pneumoniae_ infection with a dose-dependent early vacuolization and cytotoxicity of the bronchiolar epithelium followed by lymphocytic infilitration with corrresponding decrease in airway function and alteration of cytokines [PMID:19859545].
3. Lung injury in a mouse model of _Pseudomonas aeruginosa_ infection is caused by **Elastase B** (LasB) and takes the form of diffuse alveolar damage, hemorrhage, and hyaline membranes. Purified LasB recapitulates lung injury similar to bacterial infection and this appears to be the result of damage to the extracellular matrix of the lung and proteins involved in coagulation [PMID:34393497].
4. Acute lung injury in a mouse model of pneumonia caused by _P. aeruginosa_ requires that catalytically active **Exotoxin U** be delivered to target cells [PMID:15640644].

**Comment by genegodbold** [comment]
Hey @pgaudet, what about when the symbiont *inhibits* clotting or increases vascular permeability?
- Coagulation targeting metallo-endo peptidase of _Acinetobacter baumannii_ (CpaA): **CpaA** is a T2SS effector, zinc-dependent metalloprotease, that can cleave host fibrinogen (the A-alpha chain) and host factor V which are involved in contact-activated clotting. CpaA cuts factor V in a dose-dependent manner to inhibit blood clotting [PMID:24910020]. The human coagulation factor XII (fXII) is also a substrate of CpaA which cuts factor XII in one of its highly glycosylated areas. By inactivating fXII, CpaA may attenuate important antimicrobial defense mechanisms such as intravascular thrombus formation, thus allowing A. baumannii to disseminate [PMID:30563903].
- Lethal toxin (**TcsL**) of _Paeniclostridium sordellii_: TcsL cytotoxicity is driven by glucosylation of host Ras-type small GTPases: Ras, Rac, and Cdc42 [PMID:28025502]. TcsL has two enzymatic domains, an N-terminal glucosyltransferase domain and an autoprocessing domain responsible for release of the GTD within the cell. The GTD uses its N-terminal membrane localization domain for orientation on membranes and modification of GTPases. Point mutations that disrupt the glucosyltransferase, autoprocessing, or membrane localization activities were introduced into a recombinant version of TcsL, and the activities of these mutants were compared to those of wild-type toxin. All mutants were defective or impaired in cytotoxicity but differed in their modification of Rac1 and Ras [PMID:27303685]. Sublethal (0.25 micrograms/kg), intramuscular doses of LT administered to mice cause pronounced localized edema, inflammation, myofibril disassembly, and degeneration of skeletal muscle fibers in the injected area within 24 hours. The small GTPases within the muscle tissue are glucosylated. The injury is eventually regenerated over two months [PMID:15155613]. Lethal toxin seems to be required for rapid death, or toxic shock syndrome, from _P. sordellii_ [PMID:19527792]. _P. sordellii_ infection leads to edema and hypotension, and TcsL induces vascular permeability in the lungs of mice [PMID:17322384].

**Comment by pgaudet** [comment]
Fixed labels: 

- [x] GO:0044067  modification by symbiont of host cell-cell junction >>>  modification of host cell-cell junction 
- [x] GO:0098864 modification by symbiont of host tight cell-cell junction >>> stabilization of host tight cell-cell junction, changing reference to PMID:25838979 and superclass to is_a: GO:0044067 ! modification of host cell-cell junction 
- [x] GO:0098865   disruption by symbiont of host tight cell-cell junction >>>  disruption of host tight cell-cell junction

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141066
+name: disruption of host extracellular matrix
+namespace: biological_process
+def: "The chemical reactions and pathways performed by an symbiont resulting in the breakdown of the extracellular matrix of its host." [PMID:25865874]
+is_a: GO:0141041 ! disruption of extracellular matrix of another organism
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25514" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-14T13:51:30Z
