### ISSUE TITLE
Separate NF-kappaB canonical and non-canonical pathways

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25583]
The non-canonical NF-kappaB pathway is not a type of the canonical pathway, see Fig 1 from https://www.frontiersin.org/articles/10.3389/fimmu.2021.730684/full (PMID: 34659217)

<img width="981" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/788baf27-4f90-41f8-b2a2-d67fe22e9d4d">

- [ ] GO:0061765 perturbation by virus of host NIK/NF-kappaB cascade >> move from is_a GO:0085032 ! pertubation of host I-kappaB kinase/NF-kappaB cascade to is_a: GO:0052027 ! perturbation of host signal transduction pathway
- [ ] ...
- [ ]

**Comment by pgaudet** [comment]
GO:0038061 'NIK/NF-kappaB signaling' and GO:0007249 'I-kappaB kinase/NF-kappaB signaling'
remove MF to BP link: 
'has part' some 'positive regulation of NF-kappaB transcription factor activity'

**Comment by RLovering** [comment]
Hi
I think it would be good to have a new term: NF-kappaB signaling as the parent to these 2 terms
Possible Definition: The intracellular signaling process by which an activated membrane receptor signal is passed on to downstream components within the cell through activation of the DNA binding transcription factor NF-kappaB. The pathway starts either with activation of NF-kappaB or I-kappaB kinases.
Note: only the intracellular components should be associated with this term, ligands and membrane receptors regulate the pathway, I-kappaB negatively regulates this pathway.

**Comment by pgaudet** [comment]
Hi @RLovering 
Are you sure we need? I think people are mostly looking at the canonical pathway. See
https://www.frontiersin.org/articles/10.3389/fimmu.2021.730684/full

> The canonical NF-κB pathway is **rapid and transient,** and mainly stimulated by proinflammatory cytokines such as IL-1β, tumor necrosis factor (TNF)-α, antigen ligands, and toll-like receptors (TLRs).


The non-canonical NF-κB signaling pathway is **slow and persistent**, and generally activated by ligands of the TNF receptor superfamily, including lymphotoxin beta (LTB), CD40, OX40, RANK, TWEAK and B cell-activating factor (BAFF). 

I'm worried we'd loose specificity, trying to be too careful. 

What do you think ?

**Comment by pgaudet** [comment]
Decision is to change the term labels to 'canonical' and 'non-canonical' NF-kappaB cascade'.

**Comment by RLovering** [comment]
I do find it difficult confirming that a pathway is canonical or non-canonical - as this is not my area of expertise. For example I was looking at c-REL which is not listed in the figure above. I found this article https://www.hindawi.com/journals/jir/2012/239368/ and Fig 1 confirms that c-REL is in the canonical pathway, but the image does not include very many of the proteins listed in the figure from (PMID: 34659217) above. The legend from the figure below is also a bit helpful for c-REL
Canonical and alternative NF-κB activation pathways in T cells. ... Activation of the canonical NF-κB-signalling pathway: The inhibitory IκB proteins typically bind to dimers of the NF-κB family such as p65/p50 (not shown in the figure) and c-Rel/p50 (in the figure) to generate inactive complexes that are sequestered in the cytosol. PKCθ is a central molecule for TCR-mediated NF-κB activation. Phosphorylation of CARMA by PKCθ results in formation of stable CARMA/Bcl10/MALT1 complex and activation of IKK. Activated IKKβ kinase mediates phosphorylation of IκB molecules and recruitment of ubiquitin ligase. 
![Screenshot 2023-07-10 at 11 06 12](https://github.com/geneontology/go-ontology/assets/12080010/b9776519-ae4e-4477-8f34-da3d0573a09a)

Activation of alternative NF-κB pathway is triggered by a subset of TNFR family members and is mediated by NIK and IKKα that phosphorylates p100. The ubiquitin-proteasome pathway is involved in activation of NF-κB via specific degradation of IκBs and processing of p100 to produce p52.
In the figure from (PMID: 34659217) above the canonical and non-canonical pathways are distinguished by canonical: TAK1/RELA and ubiquitination/degradation of IKalpha and non-canonical TNFreceptor/NIK/RELB and ubiquitination/degradation of P100(NFKB2). The figure added, adds canonical option for REL: PRKCQ(PKC theta) and the CARMA/Bcl10/MALT1 complex and (similar to above) the ubiquitination/degradation of I-kappa-B isoforms (NFKBIA, NFKBIB, NFKBIE).

Yes I agree that if you have the general term NF-kappaB signal transduction you are likely to get more curators using this term rather than the more specific child terms. I just worry that if you have a miR that regulates the signaling via a specific NF-Kappa-B subunit eg c-REL/REL that they will need to rely on understanding the difference between canonical and non-canonical in order to apply the specific term. There is not sufficient information in the current definitions for these two terms for someone to curate to one or the other term based on regulation of a NF-kappaB subunit and evidence of regulation of the NF-kappaB signal based on change in gene expression. The addition of the parent term would help curators at least curate to NF-kappaB signal transduction rather than just intracellular signal transduction or no signal cassette at all. But I leave it to you to choose. I just added the figure to this record for my information as I find it challenging. I opened the ticket so that you can read this and then closed it because I am not going to push for the parent 
NF-kappaB signal transduction term

Thanks

Ruth

**Comment by RLovering** [comment]
Hi Pascale

sorry I just noticed that in your figure TNF stimulates the canonical pathway but in my figure TNFR stimulates the non-canonical

Sorry about this

Ruth

**Comment by pgaudet** [comment]
Hi @RLovering 
I dont think this is inconsistent, just confusing: The paper I cite (https://www.frontiersin.org/articles/10.3389/fimmu.2021.730684/full) mentions: 

The **canonical NF-κB pathway** is rapid and transient, and mainly stimulated by proinflammatory cytokines such as IL-1β, **tumor necrosis factor (TNF)-α**, antigen ligands, and toll-like receptors (TLRs). Activation of the canonical NF-κB pathway relies on phosphorylation and ubiquitination of IκB kinase α/β (IKKα/β) causing the degradation of κB inhibitory factors (IκBs) protein, thereby countering inhibition of the nuclear transcription factor heterodimer RelA/p50 by IκBs ([4](https://www.frontiersin.org/articles/10.3389/fimmu.2021.730684/full#B4), [5](https://www.frontiersin.org/articles/10.3389/fimmu.2021.730684/full#B5)). 

The **non-canonical NF-κB signaling pathway** is slow and persistent, and generally activated by ligands of the **TNF receptor superfamily,** including lymphotoxin beta (LTB), CD40, OX40, RANK, TWEAK and B cell-activating factor (BAFF).

OK ?

**Comment by RLovering** [comment]
Yes thanks
