### ISSUE TITLE
Unbalanced reaction? oxoglutarate dehydrogenase (succinyl-transferring) activity (GO:0004591)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25639]
@pgaudet 
Looking at the Rhea, this should have "+H" too?

 oxoglutarate dehydrogenase (succinyl-transferring) activity (GO:0004591)
Definition
Parents
Catalysis of the reaction: 2-oxoglutarate + lipoamide = S-succinyldihydrolipoamide + CO2.

**Comment by pgaudet** [comment]
Yes, this seems to be missing. There are many cases where the reactions are not quite right in GO (I think this may date from EC) 

Should I update it?

**Comment by ValWood** [comment]
I guess so! or I can do it tomorrow. 

Should it be possible to automate the identification of reactions where the GO description does not match the aligned Rhea reaction? Might be a nice student project? @cmungall

**Comment by deustp01** [comment]
> There are many cases where the reactions are not quite right in GO

In mapping their chemically correct reactions to the rest of us, Rhea allows wrong numbers of protons and wrong charge states of otherwise correctly identified small molecules. I believe they have a script that does this. @kaxelsen?  For Reactome / pathways2GO purposes, we take Rhea as the single source of truth to resolve these discrepancies. Is that a useful approach here?
