### ISSUE TITLE
Molecular Function for MHC heavy chains : antigen presentation activity?

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#25644]
Hi,
I have a question concerning the term that should be used to describe the Molecular Function of MHC heavy chain that bind and display antigens at the surface of antigen-presenting cells as part of the MHC complex.
So far, there are some annotations to GO:0003823 antigen binding which definition is :
"Binding to an antigen, any substance which is capable of inducing a specific immune response and of reacting with the products of that response, the specific antibody or specifically sensitized T-lymphocytes, or both. Binding may counteract the biological activity of the antigen. "

Synonyms: immunoglobulin | related
antibody | related
opsonin activity | related
B cell receptor activity | related

I am not sure it really fits the actual MF of MHC heavy chain as it is not obvious from the definition and synonyms. Should we update it to also describe the property of antigen display or should we create a new term : antigen presentation/presenting/display activity?

Thanks for your help.
Lionel

**Comment by deustp01** [comment]
@addiehl my recollection is that immunologists see (used to see?) a really deep distinction between recognition of a an antigen by an immunoglobulin and recognition of an antigen by an MHC complex, not only because the sizes / chemical makeups of the antigens tend to be different but because the two kinds of recognition are involved in distinct processes?

**Comment by addiehl** [comment]
Several points:
1) The MHC Class I, and Class II protein complexes clearly bind peptides, and in some cases lipids, and many of the things bound are bone fide antigens, so in fact "antigen binding" is an appropriate molecular function term to annotate to the Class I heavy chain and the two subunits of the Class II dimer, as well as Class Ib heavy chains in certain cases.

2) Most of the MHC gene products in various organisms have annotations to one or more antigen processing and presentation terms. I agree that these annotations do not specify the "display" aspect of MHC molecules, but the general definition of 'antigen processing and presentation', "The process in which an antigen-presenting cell expresses antigen (peptide or lipid) on its cell surface in association with an MHC protein complex," certainly implies that the antigen is present at the cell surface as part of an MHC protein complex.

3) The antigen display property/activity you mention sounds like an actual BFO function, not process, as the display is not an active process but rather the MHC complexes sitting at the surface of the cell with bound peptide being visible to T cells. Since GO MFs are generally considered BFO processes, antigen display activity doesn't seem like a valid GO MF as it is a static situation.  The relevant processes and molecular functions are already described in GO in the various antigen processing and presentation terms, and the 'antigen binding' function.  I do get that you want to capture the teleological function of MHC molecules in presenting (displaying) antigens for recognition by T cell receptors (and certain other receptors as well in a more non-specific way).

Three solutions from my point of view:
1.  Add an 'antigen binding by MHC protein complex' term as a child of 'antigen biding' with a definition like "Binding to an antigen by an MHC class I, MHC class II, or MHC Class Ib protein complex, for the purpose of displaying the antigen to T cells and natural killer cells.

(and yes, NK cell receptors do care about the peptides ([PMID:24744756](https://pubmed.ncbi.nlm.nih.gov/24744756)))

2.  Add an addition gloss sentence (in bold) to the definition of 'antigen binding': "Binding to an antigen, any substance which is capable of inducing a specific immune response and of reacting with the products of that response, the specific antibody or specifically sensitized T-lymphocytes, or both. Binding may counteract the biological activity of the antigen. **Antigen binding by an MHC protein complex allows the antigen to be displayed to a T cell or NK cell.**"

3. Do nothing and rely on the existing GO terms.

I favor the first solution, though this will mean older annotations of MHC gene products to 'antigen binding' will not be as specific as they could be.

I will include colleagues from IEDB in case they have opinions here: @bpeters42, @rvita

Thanks, Alex

**Comment by bpeters42** [comment]
Thanks Alex; I agree with your preference for 1) - Bjoern

**Comment by lbreuza** [comment]
Thanks Alex. My preference goes to 2 as it has no consequence on old annotations. Let's see if we have some other comments in the coming days and then we can make the new term query to editors to get their agreement.
Best, Lionel

**Comment by lbreuza** [comment]
Hi,
I just submitted a new term request as you were suggesting.  NTR: [antigen binding by MHC protein complex] #25748
Thanks, Lionel

**Comment by pgaudet** [comment]
Also, fixed the synonyms & synonym scope: 

-synonym: "antibody" RELATED  >> +synonym: "antibody activity" RELATED 
-synonym: "B cell receptor activity" RELATED  >> NARROW 
-synonym: "immunoglobulin" RELATED >> remove 
-synonym: "opsonin activity" RELATED   >> NARROW 
+add synonym: "major histocompatibility complex activity" NARROW []
+add synonym: "major histocompatibility complex antigen display activity" NARROW []
+add synonym: "MHC activity" NARROW []
