### ISSUE TITLE
2-polyprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25682]
Similar to #25680....

Currently we have:
```
2-polyprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity (GO:0008425) (EC:2.1.1.-, no RHEA)
    |__2-hexaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity (GO:0043334) (no EC/RHEA)
    |__2-heptaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity (GO:0043428) (no EC, RHEA:44756)
    |__2-octaprenyl-6-methoxy-1,4-benzoquinone methylase activity (GO:0043333) (EC:2.1.1.201, no RHEA)
    |__2-nonaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity (GO:0043429) (no EC/RHEA)
    |__2-decaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity (GO:0043430) (RHEA:44764)
```

![Screenshot 2023-07-05 at 14 09 43](https://github.com/geneontology/go-ontology/assets/16306861/ebeb9975-da67-49ed-a95c-fd717dc1c869)

EC:2.1.1.201 says:
Name: 2-methoxy-6-polyprenyl-1,4-benzoquinol methylase 
Reaction: a 2-methoxy-6-all-trans-polyprenyl-1,4-benzoquinol + S-adenosyl-L-methionine <=> a 6-methoxy-3-methyl-2-all-trans-polyprenyl-1,4-benzoquinol + H(+) + S-adenosyl-L-homocysteine

Comments: Ubiquinones from different organisms have a different number of prenyl units (for example, ubiquinone-6 in Saccharomyces, ubiquinone- 9 in rat and ubiquinone-10 in human), and thus the natural substrate for the enzymes from different organisms has a different number of prenyl units. However, the enzyme usually shows a low degree of specificity regarding the number of prenyl units. 

So, I suggest:
- [x] Remove EC:2.1.1.201 from GO:0043333
- [x] Change EC:2.1.1.- to EC:2.1.1.201, and add RHEA:28286 to the parent term GO:0008425
- [ ] Consider obsoleting the 5 child terms given this is essentially the same activity on different species-specific substrates.

**Comment by sjm41** [comment]
@pgaudet I've done the xref corrections. What do you think about the obsoletion suggestion?

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

GO:0043429 2-nonaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
GO:0043428 2-heptaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
GO:0043430 2-decaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
GO:0043334 2-hexaprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity
GO:0043333 2-octaprenyl-6-methoxy-1,4-benzoquinone methylase activity

since these represent species-specific substrates, as stated in the EC comment: "Ubiquinones from different organisms have a different number of prenyl units"  and "However, the enzyme usually shows a low degree of specificity regarding the number of prenyl units.". 
These will be replaced by the parent term " GO:0008425 2-polyprenyl-6-methoxy-1,4-benzoquinone methyltransferase activity" 

The parent of GO:0008425, 'GO:0030580 quinone cofactor methyltransferase activity' will also be obsoleted and replaced by GO:0008425, since these describe the same reaction.
