### ISSUE TITLE
NTR: 	U6 snRNP assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25721]
Please provide as much information as you can: 

* **Suggested term label:**

U6 snRNP assembly

* **Definition (free text)**

standard

* **Reference, in format PMID:#######**

PMID:37403782

* **Gene product name and ID to be annotated to this term**

pombe bmc1, pof8, thc1

* **Parent term(s)**

GO:0000387 | spliceosomal snRNP assembly

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
I wanted to ask about this. The authors describe as  U6 snRNP assembly, but they are part of U6 snRNP complex. They do seem to be actively involved in assembly and stability of the complex though.

I wondered if "maturation" would be better?
https://www.pombase.org/reference/PMID:37403782
U6 is the only spliceosomal RNA transcribed by RNA Polymerase III and undergoes an extensive maturation process. In humans and fission yeast, this includes addition of a 5' γ-monomethyl phosphate cap by members of the Bin3/MePCE family as well as snoRNA guided 2'-O-methylation.

but  this doesn't seem to fit very well with the existing organization.

@krchristie  how would you place it?
at the moment I just used [spliceosomal snRNP assembly](https://www.pombase.org/term/GO:0000387)

**Comment by krchristie** [comment]
> I wanted to ask about this. The authors describe as U6 snRNP assembly, but they are part of U6 snRNP complex. They do seem to be actively involved in assembly and stability of the complex though.

...not exactly sure what you mean here, particularly with respect to "they are part of U6 snRNP", so if what I say below doesn't address your question, please clarify.
 
> I wondered if "maturation" would be better? https://www.pombase.org/reference/PMID:37403782 U6 is the only spliceosomal RNA transcribed by RNA Polymerase III and undergoes an extensive maturation process. In humans and fission yeast, this includes addition of a 5' γ-monomethyl phosphate cap by members of the Bin3/MePCE family as well as snoRNA guided 2'-O-methylation.
> 
> but this doesn't seem to fit very well with the existing organization.
> 
> @krchristie how would you place it? at the moment I just used [spliceosomal snRNP assembly](https://www.pombase.org/term/GO:0000387)

Reading the abstract, this sentence:
> Here, we show that Bmc1 and Pof8 are required for the formation of a **distinct** U6 snRNP that promotes 2'-O-methylation of U6, and identify a **non-canonical snoRNA that guides this methylation**.
sounds to me like they are talking about a different nucleoprotein complex that contains U6 snRNA and modifies U6 snRNA, whether the same U6 snRNA molecule or a different one is not clear from the abstract.

I would use this existing term "**U6 2'-O-snRNA methylation**" (GO:1990438):

![20230714-U6-methylation](https://github.com/geneontology/go-ontology/assets/10533218/d3317daf-b9b5-4f2f-9a5a-0656763791de)

It is quite common that processing of a non-coding RNA occurs simultaneously with the assembly of the RNP that it becomes part of. The fact that a snoRNA is involved suggests that Bin3 and the snoRNA do NOT become part of the U6 snRNP that becomes part of the spliceosome (which is how the "**U6 snRNP**" term is currently defined). 

I think that may you need to make a new complex term for this "**distinct** U6 snRNP that promotes 2'-O-methylation of U6", and that it should probably be a child of "**sno(s)RNA-containing ribonucleoprotein complex**" (GO:0005732) since it contains a snoRNA and functions as a snoRNP complex with the snoRNA acting as the guide for the methylation activity. Then all the gene products in this "**distinct** U6 snRNP that promotes 2'-O-methylation of U6" would be annotated to the new complex term and to the existing term  "**U6 2'-O-snRNA methylation**" (GO:1990438).

![20230714-RNPcomplexes-snoRNP-focus](https://github.com/geneontology/go-ontology/assets/10533218/b0130ec8-2048-43d1-8e2f-02dc6715272e)

**Comment by ValWood** [comment]
Thanks  @krchristie  That was useful!
