### ISSUE TITLE
NTR: [antigen binding by MHC protein complex]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#25748]
Please provide as much information as you can: 

* **Suggested term label:**
antigen binding by MHC protein complex

* **Definition (free text)**
Binding to an antigen by an MHC class I, MHC class II, or MHC Class Ib protein complex, for the purpose of displaying the antigen to T cells and natural killer cells.

* **Reference, in format PMID:#######**
PMID:35948544

* **Gene product name and ID to be annotated to this term**
HLAA, HLAB,...

* **Parent term(s)**
[GO:0003823] antigen binding

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Please check #25644 for further discussion and possibilities.

**Comment by pgaudet** [comment]
Hi @lbreuza @addiehl 

This seems like an annotation to me ('x activity mediated by protein complex y'), so I prefer not to create this, because we don't have that type of pattern in GO. 

I propose you use 'antigen binding' with the modified definition suggested in https://github.com/geneontology/go-ontology/issues/25644 with the BP antigen processing and presentation. 

Hopefully in the future we can create MFs that would distinguish the functions of immunoglobulins and MHCs. 

Thanks, Pascale
