### ISSUE TITLE
NTR: [Protein-pyrophosphorylation activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#25934]
Hi GO, 

I would need a new GO term for "Protein-pyrophosphorylation activity", a long sought enzyme that was identified recently (PMID:36603579).

Thanks

Sylvain

Description: Protein-pyrophosphorylation activity
Category: Molecular function
Definition: Catalysis of the reaction: protein serine phosphate + inositol 5-triphosphate pentakisphosphate = protein serine diphosphate + inositol 5-diphosphate pentakisphosphate 

Xref
PMID:36603579
Rhea:64104
EC=2.7.4.- 

child of  
GO:0016776 phosphotransferase activity, phosphate group as acceptor

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141090
+name: protein serine pyrophosphatase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: protein phospho-serine + inositol 5-triphosphate pentakisphosphate = protein diphospho-serine + inositol 5-diphosphate pentakisphosphate." [PMID:36603579, RHEA:64104]
+xref: RHEA:64104
+is_a: GO:0016462 ! pyrophosphatase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25934" xsd:anyURI
+created_by: pg
+creation_date: 2023-08-21T07:53:21Z
+

**Comment by pgaudet** [comment]
Hi @sylvainpoux 

I did a bit different from what you requested: 
- parent: GO:0016462 ! pyrophosphatase activity
- did not add the partial EC
Please let me know if this is not OK for you. 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi @pgaudet,

Many thanks!

Sylvain

**Comment by sjm41** [comment]
Hi @sylvainpoux @pgaudet 

- the paper describes this enzyme as a "pyrophosphorylase" rather than a "pyrophosphatase", ie. a phosphorylation (kinase, ie transferase) activity rather than a phosphatase (hydrolase) activity.  Looking at RHEA:64104, that seems to be true from the perspective of the protein entity.
- I agree the partial EC shouldn't be added, but the suggestion of EC:2.7.4.- (= Phosphotransferases with a phosphate group as acceptor) is consistent with the previous point
- So:

- [ ] change name to "protein serine pyrophosphorylase activity"
- [ ] change parent to "GO:0016776 phosphotransferase activity, phosphate group as acceptor (EC:2.7.4.-)

??

**Comment by kaxelsen** [comment]
I have just revisited what I wrote to @sylvainpoux and it was maybe not clear.
The enzyme is not a phosphatase and phosphatases removes phosphates from substrates.
It is not a phosphorylase either, as these uses inorganic phosphate as the subtrate.
So I would call this enzyme a phosphotransferase.
