### ISSUE TITLE
clean up of transcriptional regulation terms - cell cycle terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26002]
Finishing off https://github.com/geneontology/go-ontology/issues/12739

There are some terms related to the cell cycle: 

- [x] GO:0010674 | negative regulation of transcription from RNA   polymerase II promoter involved in meiotic cell cycle
- [x] GO:0071930 | negative regulation of transcription involved in G1/S transition of   mitotic cell cycle
- [x] GO:0090419 | negative regulation of transcription involved in G2/M transition of   mitotic cell cycle
- [x] GO:0051038 | negative regulation of transcription involved in meiotic cell cycle
- [x] GO:0010673 | positive regulation of transcription from RNA polymerase II promoter   involved in meiotic cell cycle
- [x] GO:0007072 | positive regulation of transcription involved in exit from mitosis
- [x] GO:0007073 | positive regulation of transcription involved in exit from mitosis, from   RNA polymerase I promoter
- [x] GO:0007074 | positive regulation of transcription involved in exit from mitosis, from   RNA polymerase II promoter
- [x] GO:0007075 | positive regulation of transcription involved in exit from mitosis, from   RNA polymerase III promoter
- [x] GO:0071931 | positive regulation of transcription involved in G1/S transition of   mitotic cell cycle
- [x] GO:0090282 | positive regulation of transcription involved in G2/M transition of   mitotic cell cycle
- [x] GO:0051039 | positive regulation of transcription involved in meiotic cell cycle
- [x] GO:0010672 | regulation of transcription from RNA polymerase II promoter involved in   meiotic cell cycle
- [x] GO:0000083 | regulation of transcription involved in G1/S transition of mitotic cell   cycle
- [x] GO:0000117 | regulation of transcription involved in G2/M transition of mitotic cell   cycle
- [x] GO:0051037 | regulation of transcription involved in meiotic cell cycle
- [ ] 

Annotations: [https://github.com/geneontology/go-annotation/issues/4720
- 145 annotations + 3 extensions](https://docs.google.com/spreadsheets/d/1ctk_ArpXgEJQboPxn_uK74VOWxjepCodmzCfhF_otuQ/edit#gid=0)
- 1 InterPro mapping

assigned_by
--
BHF-UCL | 3
CGD | 6
ComplexPortal | 6
FlyBase | 4
MGI | 4
PomBase | 20
RGD | 1
SGD | 92
UniProt | 11

@ValWood any suggestions about these? They may represent specific pathways, but perhaps they should be reformulated?

**Comment by ValWood** [comment]
Where is the list of annotations?

I don't know. They only represent specific pathways the same as any transcription factor transcribing a collection of genes.

For most cell cycle processes the regulation is not at the level of transcription. Obviously, the proteins need to be expressed, but cell cycle regulation between phases is largely post-transcriptional. The only exception I know is that for S. cerevisiae there is a positive feedback loop for the expression of cyclin in G1/S (In pombe this is different).  Another exception might be the switches between somatic cell growth and meiosis which is regulated partly  by transcription (but this  regulatory network is so complicated I have barely thought about it).
But I thought we planned to post-compose when transcription directly regulates a process, so personally, I don't see a huge need for these particular precomposed terms (as in most cases it is causally upstream, rather than regulatory).

Who uses them (I could not find the annotation spreadsheet via the link)?

**Comment by pgaudet** [comment]
You can see annotations here https://github.com/geneontology/go-annotation/blob/master/reports/4720/GO_0000083-GO_0000117-GO_0007072-GO_0007073-GO_0007074-GO_0007075-GO_0010672-GO_0010673-GO_0010674_etc.tsv

but I haven't made the spreadsheet

**Comment by ValWood** [comment]
Maybe ask SGD about this, since they have a lot of annotation. I think it could be captured with GO -CAM though

**Comment by ValWood** [comment]
better

**Comment by pgaudet** [comment]
Looking at the annotations, it looks like we can go ahead and obsolete this. SGD and UniProt annotations have already been moved.
