### ISSUE TITLE
NTR: [signal peptidase activity]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26007]
Please provide as much information as you can: 

* **Suggested term label:**

signal peptidase activity

* **Definition (free text)**

Catalysis of the hydrolysis of a signal peptide of a polypeptide chain, in a reaction that requires a free N-terminal amino group, C-terminal carboxyl group or both.

* **Comment**

This reaction occurs during or after transport to a specific location in the cell

* **Reference, in format PMID:#######**

use a ref from https://en.wikipedia.org/wiki/Signal_peptidase

* **Gene product name and ID to be annotated to this term**

These
https://www.pombase.org/term/GO:0006465

All are proteases (with one regulatory subunit), so this appears to be single step. Instead I would annotate the process to "protein maturation" or "mitochondrial protein maturation"

* **Parent term(s)**

GO:0008238   exopeptidase activity

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**

not sure about this:

* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

@pgaudet  no hurry for this, but do you think this is OK? Otherwise we aren't really capturing the process often (or the function).

**Comment by sjm41** [comment]
@ValWood We used to have a bunch of signal peptidase terms, but they were all obsoleted because they 'referred to gene products". E.g.:

id: GO:0042499
name: obsolete signal peptide peptidase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the intramembrane proteolysis of a signal peptide, following its removal from a preprotein." [PMID:12077416]
comment: This term was made obsolete because it represents a gene product.
synonym: "signal peptide peptidase activity" EXACT []
synonym: "SPP" EXACT []
xref: EC:3.4.23.-
is_obsolete: true
replaced_by: GO:0042500

id: GO:0009003
name: obsolete signal peptidase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the cleavage of a signal peptide from a protein precursor." [GOC:mah]
comment: This term was made obsolete because 'signal peptide' is difficult to define unambiguously, and because the term refers to gene products.
synonym: "signal peptidase activity" EXACT []
is_obsolete: true
replaced_by: GO:0008233

id: GO:0009004
name: obsolete signal peptidase I activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the cleavage of N-terminal leader sequences from secreted and periplasmic proteins precursor." [GOC:curators]
comment: This term was made obsolete because it represents a gene product.
synonym: "bacterial leader peptidase 1" RELATED []
synonym: "bacterial leader peptidase I activity" NARROW []
synonym: "Escherichia coli leader peptidase" NARROW []
synonym: "eukaryotic signal peptidase" NARROW []
synonym: "eukaryotic signal proteinase" NARROW []
synonym: "HOSP" RELATED []
synonym: "leader peptidase activity" RELATED []
synonym: "leader peptidase I" RELATED []
synonym: "leader peptide hydrolase activity" RELATED []
synonym: "leader proteinase activity" RELATED []
synonym: "phage-procoat-leader peptidase activity" NARROW []
synonym: "pilin leader peptidase" NARROW []
synonym: "prokaryotic leader peptidase" NARROW []
synonym: "prokaryotic signal peptidase" NARROW []
synonym: "prokaryotic signal proteinase" NARROW []
synonym: "propeptidase activity" RELATED []
synonym: "PuIO prepilin peptidase" NARROW []
synonym: "signal peptidase I activity" EXACT []
synonym: "signal peptide hydrolase activity" RELATED []
synonym: "signal proteinase activity" RELATED []
synonym: "signalase activity" RELATED []
synonym: "SPase I activity" RELATED []
synonym: "SPC" RELATED []
is_obsolete: true
replaced_by: GO:0004252


Regarding EC xrefs, EC 3.4.21.89 (signal peptidase I = GO:0009004 above) may match what you require? In UniProt, EC 3.4.21.89 is annotated to "Signal peptidase complex catalytic subunit SEC11A/B/C" (in humans), which are orthologs of pombe sec11.

**EC 3.4.21.89**
Accepted Name: signal peptidase I
Alternative Name(s): bacterial leader peptidase I, phage-procoat-leader peptidase, SPase I
Reaction catalysed: Cleavage of hydrophobic, N-terminal signal or leader sequences from secreted and periplasmic proteins
Comment(s):
- Unaffected by inhibitors of most serine peptidases, but site-directed mutagenesis implicates a Ser/Lys catalytic dyad in activity.
- Cleaves a single bond -Ala-|-Ala- in M13 phage procoat protein, producing free signal peptide and coat protein.
- Eukaryote signal peptidases that may have somewhat different specificity are known from the endoplasmic reticulum membrane and mitochondrial inner membrane.
- Belongs to peptidase family S26. 


Also, the parent term for 'signal peptide peptidase' would be endopeptidase, rather than exopeptidase.

**Comment by ValWood** [comment]
OK. I can't find the closure ticket, but this one isn't really a single gene product.

**Comment by ValWood** [comment]
@pgaudet  do you have any thoughts on this?
We have a process term 
GO:0006465 | signal peptide processing
but shouldn't  this really be an activity?

**Comment by ValWood** [comment]
OK.

**Comment by pgaudet** [comment]
Closing for now. We ca revisit later
