### ISSUE TITLE
NTR: reverse gyrase

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#26019]
Hi,
Reverse gyrase is a type of topoisomerase activity for which there is no GO term. It is currently annotated with "GO:0003918, DNA topoisomerase II activity (double strand cut, ATP-hydrolyzing) activity", which I think is wrong. 

The enzyme introduces positive supercoils into closed DNA in an ATP-dependent fashion. This is the only protein known to introduce positive supercoils, it is only found in thermophiles and is the unique hallmark of thermophiles.

I will attach a small table with comparative data for reverse gyrase, topoisomerase I and topoisomerase II.

[Topoisomerases-table.docx](https://github.com/geneontology/go-ontology/files/12514442/Topoisomerases-table.docx)

Reverse gyrase is almost always a monomer, binds and cleaves single-strand DNA, changes the DNA linking number by +1 (like topoisomerase I), but uses ATP to introduce positive supercoils (like topoisomerase II). Topo II binds and cleaves double-stranded DNA and changes the linking number by +2, another reason its EC and activity are not correct for reverse gyrase; see the table. I am asking for a new EC number for this activity and I think GO should follow suit.

Suggested term label, (it copies the term labels for topo I and topo II)
Reverse gyrase (single strand cut, ATP-hydrolyzing) activity

Definition: 
Catalysis of a DNA topological transformation by transiently cleaving one DNA strand at a time to allow passage of another strand; changes the linking number by +1 per catalytic cycle, is driven by ATP hydrolysis. 

Reference; PMID:25013168
Alas there is not a more recent review.

the GN for these enzymes is rgy

It is a child of GO:0003916, DNA topoisomerase activity.

There no terms I know of that should be its children. There are no synonyms, as I said above I am asking for a new EC number because neither of the EC numbers for topo I (5.6.2.1) or topo II (5.6.2.2) are correct. Rhea won't make a term (for now?), it would be text only.

Cross-references:
Hopefully a new EC will be forthcoming
https://en.wikipedia.org/wiki/Reverse_gyrase

**Comment by raymond91125** [comment]
It appears that the reverse gyrase has also RNA-topoisomerase activity [WIKI]. Should we have then "reverse gyrase activity" to be IS_A "isomerase activity". Alternatively, we can have "DNA reverse gyrase activity" IS_A "DNA topoisomerase activity".

**Comment by pgaudet** [comment]
@raymond91125 I dont see the RNA gyrase in the wiki entry - it seems to mention RNA topoisomerase for ' type IA topoisomerase class', and while the reverse gyrase belongs to this family, I dont see where it is mentioned that is also acts on RNA. 

Thanks, Pascale

**Comment by raymond91125** [comment]
The RNA substrate part may not be entirely clear but there are several related mentions in the literature. If the proposed MF is DNA-specific, we may as well make that explicit, I think.

1. Wiki: More specifically, reverse gyrase is a member of the type IA topoisomerase class; along with the ability to relax negatively or positively supercoiled DNA[5] (which does not require ATP[6][7]), type IA enzymes also tend to have RNA-topoisomerase activities.
2. PMID:25013168 Overall, the helicase domain of reverse gyrase thus undergoes a similar conformational cycle as DEAD-box proteins (65–67) (reviewed in (58)), alternating between open and closed states with different DNA affinities (Figure ​(Figure2B).2B). While closing is coupled to the cooperative binding of ATP and DNA/RNA in reverse gyrase and DEAD-box proteins alike,
3. PMID:11823434 A search with DALI (Holm and Sander, 1993) revealed that H3 is structurally homologous to residues 1–46 of the E.coli rho transcription terminator. This region in rho is involved in RNA binding (Dombroski and Platt, 1988; Dolan et al., 1990) and may play an analogous role in reverse gyrase, 
4. PMID:20851892 In addition, because reverse gyrase is able to bind RNA,3 it might also remove secondary structures in DNA-RNA hybrids.

**Comment by raymond91125** [comment]
@AndreaAuchincloss What do you think? Thanks.

**Comment by AndreaAuchincloss** [comment]
Hi, 
I've probably read most of the papers in the field, and I've not seen any mention of an RNA topoisomerase activity; then again once people decide it doesn't have that activity, they no longer look for it. However I do not think it is appropriate for this particular protein, we could add a phrase along the lines of "only known to be active on DNA" if you want to, although as a child of DNA topoisomerase activity that may be evident(?).

1. Type IA enzymes tend to have RNA-topoisomerase activity is not proof for a domain function in reverse gyrase.
2. The mention in PMID:25013168 refers to DEAD box helicases as I read the sentence.
3. PMID:11823434 postulates the H3 domain to be involved in DNA-binding.
4. PMID:20851892 they say RG can bind RNA with a tiny 3 as unpublished results. If they haven't published the data since 2010 I don't know if I think it is worth mentioning.

I can't find any evidence of an RNA gyrase activity, to add it to the GO term would be misleading in my opinion.

**Comment by ValWood** [comment]
Is "RNA topoisomerase even physiologically possible? I thought it was to relax supercoiling and relax linking number in a topological transformation.

**Comment by raymond91125** [comment]
@AndreaAuchincloss Thanks for the clarification.

+[Term]
+id: GO:0160097
+name: reverse gyrase activity
+namespace: molecular_function
+def: "Catalysis of a DNA topological transformation by transiently cleaving one DNA strand at a time to allow passage of another strand; changes the linking number by +1 per catalytic cycle, is driven by ATP hydrolysis." [PMID:25013168]
+xref: WIKIPEDIA:Reverse_gyrase
+is_a: GO:0003916 ! DNA topoisomerase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26019" xsd:anyURI
+created_by: rynl
+creation_date: 2023-09-08T16:47:25Z
