### ISSUE TITLE
NTR - metabolism: [branched-chain alpha-ketoacid dehydrogenase phosphatase activity]

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#26158]
Dear GO curators,

Could you please consider creating a new term:

[3-methyl-2-oxobutanoate dehydrogenase (acetyl-transferring)] phosphatase activity
child of GO:0004722

Catalysis of the reaction: 
Reaction=H2O + O-phospho-L-seryl-[3-methyl-2-oxobutanoate dehydrogenase] = L-seryl-[3-methyl-2-oxobutanoate dehydrogenase] + phosphate [Rhea:77247]
Evidence: PubMed=17336929; PubMed=22589535; PubMed=19411760
https://enzyme.expasy.org/EC/3.1.3.52

Rhea:77247 is approved but not public yet.

The new term can be used to annotate PPM1K https://www.uniprot.org/uniprotkb/Q8N3J5/entry and orthologues. PPM1K forms a functional kinase and phosphatase pair with BCKDK https://enzyme.expasy.org/EC/2.7.11.4; GO:0047323

Many thanks for your help,
Nevila Hyka-Nouspikel

**Comment by pgaudet** [comment]
Hi @nnouspikel 

We do not create terms for specific substrates for protein kinases and protein phosphatases. For GO this corresponds to 
https://www.rhea-db.org/rhea/20629

I thought this was also the scope of RHEA (ie chemically, it is the same reaction); but it seems this is no longer the case?

Thanks, Pascale

**Comment by kaxelsen** [comment]
Rhea creates reactions for specific proteins as little as possible. One case were we do create such reactinos is when there is an EC number linked to the reaction because IUBMB does create reactions for specific proteins. In the specific case of protein kinases it is the only way to make nonidentical reactions for different kinases.
