### ISSUE TITLE
Obsolete: GO:0070584 mitochondrion morphogenesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26187]
GO:0070584 mitochondrion morphogenesis
The process in which the anatomical structures of a mitochondrion are generated and organized.

How does this term differ from the parent "mitochondrion organization"?
It has no children, and 69 EXP annotations.

I suggest merging up.

@hattrill  most annotations D.m. what do you think? 

In this instance 'morphogenesis' is a phenotype, and probably in most cases there are already annotations to one of the other subclasses of mitochondrion organization? ( i.e. size and shape are a consequence of fission and fusion, not directly programmed like in growth and development)

**Comment by pgaudet** [comment]
Hi @ValWood 
We should always strive to look at these types of terms globally. 

In this case, the hierarchy is like this: 
<img width="442" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/0c06b82a-2819-456b-bc99-f5d0b63d4f5a">



I suggest: 

- [ ] renaming cellular component morphogenesis to 'cellular anatomical entity morphogenesis, to match the top level in that branch 
- [ ] obsolete 'cell part morphogenesis' with replace by cellular component morphogenesis/cellular anatomical entity morphogenesis
- [ ] Not sure we need 'cell projection morphogenesis, since all children are children of that term. 

Thanks, Pascale

**Comment by ValWood** [comment]
Cell part projection morphogenesis is probably OK. Here there is a precisely controlled shape . There is a biological programme to create a specific shape (in each cell).

Mitochondrion seems  quite different , they are derived from the ER, and then are maintained over multiple cell divisions  by fission and fusion. 
So we could just get rid of mitochondrion morphogenesis  which is easy because it is in an isolated branch, and keeps mitochondrion organization annotation neater (this is more critical because it is a revived area of interest in the past year or too, a lot of uncharacterized unknowns are in here).

 I don't know much about  cell projection but I'd be inclined to keep "cell projection morphogenesis" and  obsolete "cell part morphogenesis" as an unnecessary grouping term  if GO:0070584 mitochondrion morphogenesis obsoletion is agreed. If that seems OK, I can do that.

**Comment by hattrill** [comment]
Hi @ValWood happy with the suggestion to merge mito morph with mitochondrion organization.

**Comment by ValWood** [comment]
OK I will proceed with obsoletion/merge  shortly.

**Comment by ValWood** [comment]
@pgaudet  are you OK for me to merge "mitochondrial morphogenesis" into "mitochondrial organization"
and merge "cell part morphogenesis" into cellular component morphogenesis (since "cell projection morphogenesis" will be the only type, single inheritance)

**Comment by pgaudet** [comment]
Sure 

We should create a different ticket for the obsolete/replace of "cell part morphogenesis" with "cellular component morphogenesis" since it's more general. 

Also, "cellular component morphogenesis"  should be renamed "cellular anatomical structure morphogenesis" (and the LD adjusted accordingly) 

Thanks, Pascale

**Comment by ValWood** [comment]
This term has a comment, which I had not previously noticed:

Note that this term is intended for annotation of gene products involved in mitochondrial shape changes associated with development; an example is the morphogenesis of the Nebenkern during spermatogenesis.

and does not appear to reflect how is  used.

(Also in this case why isn't it a descendent of 'sperm mitochondrion' organization?)

There is also a term
GO:0007287   Nebenkern assembly
Fusion of mitochondria during insect spermatid differentiation to form two masses, which wrap around each other to form a densely packed sphere called the Nebenkern.

So I will proceed with the proposed obsoletion.

@hattrill  should GO:0007287   Nebenkern assembly be a descendent of 
'sperm mitochondrion' organization'?
are both terms required?  maybe we could just relocate 
GO:0007287   Nebenkern assembly and get rid of  'sperm mitochondrion' organization' as a "cell type + term"
Let me know what you think.

**Comment by ValWood** [comment]
add synonym
