### ISSUE TITLE
Missing parent:  GO:0045815 transcription initiation-coupled chromatin remodeling

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26319]
GO:0045815 transcription initiation-coupled chromatin remodeling should be a child of 

GO:0006352 DNA-templated transcription initiation

[See go-annotation-4792](https://github.com/geneontology/go-annotation/issues/4792#issuecomment-1782588403)

**Comment by pgaudet** [comment]
The problem is that right now this term has these other superclasses: 

<img width="453" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/bcdd9987-a715-455d-aa65-e022dbcb8f19">


So, if we add 'part of initiation', we need to remove  'regulation of gene expression' (we dont want the process to be part of transcription AND regulating transcription) 

@colinlog @ValWood

**Comment by ValWood** [comment]
It wouldn't be regulating transcription though would it? It would be 
part_of transcription, and regulating "epigenetic expression" (2 separate roles). At least that was my understanding?

Although  I'm not sure if the role is "regulation of epigenetic gene expression" in the GO sense of regulation because it is "within pathway" , shouldn't 
GO:0045815 transcription initiation-coupled chromatin remodeling  be only part_of  chromatin remodeling ?

**Comment by colinlog** [comment]
I agree Val,

There are dbTFs that regulate transcription by recruiting co-TFs to genes. Some of these coTFs remodel chromatin.
However, not all chromatin remodelers regulate transcription as coTFs. Rather, some (all?) chromatin remodellers 'set the stage' within which the coTF chromatin remodellers operate. At some genes their activity is 'untargetted' in the sense of direct recruitment to a chromosomal region by a sequence-specific dbTF. The remodelers are there in the nucleus and react to the availability of their binding partners and enzymatic substrates. The binding substrates may be (de)modified nucleosomal histones (that are themselves the products of previous chromatin remodelling events), or other (modified) proteins or (modified) nucleic acids.

So, perhaps the right way to organise the terms would be to 

1. Put remodelling somewhere in the transcription BP branch (acts on cis-acting regions) instead of txn regulation.
2. Only add the GO:00003712 / 3713 / 3714 when there is evidence for dbTF-dependent recruitment which means it is regulating transcription. 

At that point the chromatin remdelling activity of that protein can be included as coTF activity (for a specific dbTF at a specific gene in a specific cell under a given environmental circumstance / temporal phase)

What is perhaps disturbing (?) is that once a chromatin remodelling protein has been called a coTF for one gene in one cell type, for GO it would be 'regulating transcription' everywhere all the time, even when it is not targetted by a dbTF and is 'just part of the transcription BP', which for some of the chromatin remodellers is most of the cases. For example ISWI complexes that work at gene promoters are constantly resetting many gene's promoters to a latent transcriptional state, but there is also evidence that some activating and repressing dbTFs can recruit them under some conditions at a specific gene.

Does this help?

**Comment by colinlog** [comment]
Note, next to RNA transcription, there is also chromatin remodelling  for 

DNA replication
DNA repair
DNA recombination

So, in eukaryotes, chromatin remodelling is part-of all these processes

**Comment by pgaudet** [comment]
- [ ] Added part_of GO:0006367 ! transcription initiation at RNA polymerase II promoter
- [ ] removed  superclass 'GO:0010628 positive regulation of gene expression'
- [ ] removed  superclass GO:0040029 ! epigenetic regulation of gene expression
