### ISSUE TITLE
where is "threonine deaminase"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26359]
We have some paper referring to threonine deaminase in fission yeast
https://pubmed.ncbi.nlm.nih.gov/?term=%22threonine+deaminase%22+and+%22fission+yeast%22&sort=date

This is threonine deaminase

https://www.ebi.ac.uk/QuickGO/term/GO:0004794
Threonine deaminase is a related synonym of

GO:0004794  L-threonine ammonia-lyase activity
L-threonine = 2-oxobutanoate + NH3

but are they the same thing ? If so can the synonym be exact. If not how do they differ?

Searching PubMed
"Threonine deaminase" 319
"threonine ammonia-lyase" (10)

**Comment by ValWood** [comment]
OK I think they are the same:

Threonine deaminase (l-threonine dehydratase EC 4.2.1.16)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC251809/

with  "threonine deaminase" appearing to be the most common name in the literature?

**Comment by pgaudet** [comment]
WRT name: we have aligned to EC https://enzyme.expasy.org/EC/4.3.1.19
Maybe we shouldn't have, UniProt entries seem to use threonine deaminase: 
https://www.uniprot.org/uniprotkb/P20132/entry

**Comment by pgaudet** [comment]
Actions needed for this term: 

- [ ] fix label (although all other terms in that branch are 'ammonia lyases') 
- [ ] fix synonym types as appropriate
- [ ] fix definition to match RHEA [4.3.1.19](https://www.rhea-db.org/rhea/22108)
- [ ] remove comment 'Note that this function was formerly EC:4.2.1.16.' since that EC is obsolete. 
Thanks, Pascale

**Comment by ValWood** [comment]
> fix definition to match RHEA [4.3.1.19](https://www.rhea-db.org/rhea/22108)

do I change NH3 to NH4?
And if so do I need to fix the subClass of, or is ammonium OK?

**Comment by deustp01** [comment]
> do I change NH3 to NH4?

NH4+ ([CHEBI:28938](https://www.ebi.ac.uk/chebi/reaction.do?chebiId=CHEBI:28938
)) is the predominant form at pH 7.3 and is the one used in RHEA reactions 
BUT we don't add "zwitterion" to default names of amino acids who have that predomiant form at pH 7.3, so that is a separate issue (and maybe one to be ignored?)

**Comment by ValWood** [comment]
thanks @deustp01 !

**Comment by pgaudet** [comment]
I have been aligning chemicals with RHEA (also I usually change the def xref to the RHEA, since this is usually our 'source of truth).

**Comment by ValWood** [comment]
I looked at the Rhe reaction and aligned with that (I think), is it correct what I have done?

**Comment by pgaudet** [comment]
Yes, that was just to help in future definition changes. This one here is right.
