### ISSUE TITLE
NTR: meisosome

### ISSUE THREAD

**Issue by draciti** [geneontology/go-ontology#26434]
Please provide as much information as you can: 

* **Suggested term label:**

meisosome

* **Definition (free text)**
A membrane-folded structure on the apical side of the epidermis. Meisosomes are composed of stacked parallel folds of the epidermal plasma membrane, alternately filled with apical extracellular matrix, the cuticle in C. elegans. They define plasma membrane subdomains, characterised by pleckstrin homology domain binding. Meisosomes stands for multiple eisosomes, as they share structural similarities with eisosomes, which are furrow-like sub-domains of the plasma membrane facing the yeast cell wall. 

* **Reference, in format PMID:#######**
PMID:36913486

* **Gene product name and ID to be annotated to this term**
vha-5 [WBGene00006914]

* **Parent term(s)**
GO:0110165 ! cellular anatomical entity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160132
+name: meisosome
+namespace: cellular_component
+def: "A cell part that is composed of multifold plasma membrane of the epidermis where it is in direct contact with apical extracellular matrix. Meisosome, or multiple eisome is named because of its superficial similarity to yeast eisosome." [PMID:36913486]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of CL:0000362 ! epidermal cell
+created_by: rynl
+creation_date: 2023-12-12T19:03:38Z
