### ISSUE TITLE
Missing parent: GO:0140818 | mRNA 5'-phosphatase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26595]
* **GO term ID and label for which you request a new superclass**

GO:0140818 | mRNA 5'-phosphatase activity
does not have superclass

GO:0004651 | polynucleotide 5'-phosphatase activity

**Comment by pgaudet** [comment]
Something is not right about GO:0004651 | polynucleotide 5'-phosphatase activity - 

GO ID | label | EC | RHEA  | EC& RHEA description 
-- | -- |  -- | --
GO:0140818 | mRNA 5'-phosphatase activity | EC:3.6.1.74 | [RHEA:67004](https://www.rhea-db.org/rhea/67004)
GO:0004651 | polynucleotide 5'-phosphatase activity | EC:3.1.3.3 |  RHEA:11008  | *purine*  ribonucleoside in mRNA

* EC:3.1.3.33 and [RHEA:11008](https://www.rhea-db.org/rhea/11008) has a single entry in UniProt: A0A7H0DN85, annotated to EC:3.1.3.33 by similarity

* RHEA:11008 has a note that the more general form of the reaction id [RHEA:67004](https://www.rhea-db.org/rhea/67004)

**Comment by pgaudet** [comment]
Related to  #24892

**Comment by raymond91125** [comment]
The term relationship should be:
GO:0140818 "mRNA 5'-phosphatase activity" EC 3.6.1.74 covers both purine and pyrimidine substrates
... GO:0004651 "polynucleotide 5'-phosphatase activity" EC 3.1.3.33 covers ONLY PURINE substrates

**Comment by sjm41** [comment]
Another odd thing here is the EC number (EC:3.1.3.3) for GO:0004651 polynucleotide 5'-phosphatase activity: if this activity is removing one phosphate from "a 5'-end triphospho-(purine-ribonucleoside) in mRNA", then I think it should have a EC:3.6 (Hydrolases - Acting on acid anhydrides) prefix rather than 3.1 (Hydrolases - Acting on ester bonds). Then the new relationship suggested by @raymond91125 would make sense.

What do you think about the EC:3.1.3.3 number here @kaxelsen ?

**Comment by kaxelsen** [comment]
I think you are right, especially since the comment says: "Does not act on nucleoside monophosphates", which is where the ester bond is. I will look into it and suggest a transfer of the EC number to the subclass EC 3.6

**Comment by kaxelsen** [comment]
@sjm41 I'm sorry, but my first impression of the problem was wrong. After reading the evidence for the EC 3.1.3.33 entry (PMID: [4289819](https://pubmed.ncbi.nlm.nih.gov/4289819) ), I  have learned that the entry only covers 5'-MONOphosphorylated polynucleotides, so it is the Rhea mapping that is completely wrong. 
So in the table above it is the Rhea mapping and the EC & Rhea description that is wrong. The substrate of EC 3.1.3.33. is a "a 5'-end phospho-(nucleoside) in RNA or DNA" 

We are unfortunately in the middle of a freeze, so I will not be able to go further with this problem for the next couple of days, and I'm not sure I can create a Rhea reaction as the enzyme works on both RNA and DNA.

**Comment by sjm41** [comment]
Thanks @kaxelsen 

It sounds like the GO:0004651 definition (which is attributed to EC:3.1.3.33) is actually correct then!:
"Catalysis of the reaction: 5'-phosphopolynucleotide + H2O = polynucleotide + phosphate." [EC:3.1.3.33]
(and we should ignore the current (incorrect) EC def that says it's specific for purines)

Which means the action item for GO here is just to remove the RHEA:11008 xref from GO:0004651? (on the understanding that the EC:3.1.3.33 reaction definition will get corrected in time)

Though maybe we should also change the GO term name to "polynucleotide 5'-**mono**phosphatase activity" to be clearer?

==

id: GO:0004651
name: polynucleotide 5'-phosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: 5'-phosphopolynucleotide + H2O = polynucleotide + phosphate." [EC:3.1.3.33]
synonym: "5'-polynucleotidase activity" RELATED [EC:3.1.3.33]
synonym: "polynucleotide 5'-phosphohydrolase activity" RELATED [EC:3.1.3.33]
synonym: "polynucleotide 5'-triphosphatase activity" RELATED [EC:3.1.3.33]
xref: EC:3.1.3.33
xref: MetaCyc:RXN-21861
xref: RHEA:11008
is_a: GO:0016791 ! phosphatase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25810" xsd:anyURI

**Comment by kaxelsen** [comment]
For your information: EC 3.1.3.33 is now linked to RHEA:67772 and RHEA:67776, both public

**Comment by raymond91125** [comment]
> For your information: EC 3.1.3.33 is now linked to RHEA:67772 and RHEA:67776, both public

I'm not seeing the reference to EC 3.1.3.33 on pages of RHEA:67772 and RHEA:67776. The RHEAs do refer to MetaCyc RXN-21861 which then refers to EC 3.1.3.33. But information about the EC is different at the three different sites: Brenda, Expasy, and enzyme-database.

For https://amigo.geneontology.org/amigo/term/GO:0004651, the text definition is presently different from the participants.
As @sjm41 mentioned, should we wait for EC to be corrected? That is the only XREF for GO:0004651.
Also, GO:000465 EXP annotations appear to be incompatible with the definition found in PMID:4289819, RHEA:67772, or RHEA:67776.

**Comment by kaxelsen** [comment]
@raymond91125 The changes have been made in the working copy of ENZYME. They will unfortunately only become public in UniProt release 2024_02 (that includes releases of ENZYME and Rhea).

**Comment by ValWood** [comment]
I haven't fully followed the changes  here, but was 
O:0004651
name: polynucleotide 5'-phosphatase activity
correct for the mRNA capping enzyme  (i.e will it be a parent of mRNA 5'-triphosphate monophosphatase activity)
or do I need to get these annotations/PAINT mappings updated?

<img width="1093" alt="Screenshot 2024-02-28 at 17 28 12" src="https://github.com/geneontology/go-ontology/assets/7359272/c9519410-13ce-468d-a9cc-94e27fbf1e10">

If so can do this in advance of the GO/Rhea changes.

**Comment by raymond91125** [comment]
I was hoping to see the new release of UniProt to make sure exactly what we are going to do. Just a couple of days more?

**Comment by ValWood** [comment]
Ok, not in a hurry, I just need to remember not to forget that I need to do something ;)

**Comment by raymond91125** [comment]
> For your information: EC 3.1.3.33 is now linked to RHEA:67772 and RHEA:67776, both public
@kaxelsen I'm not seeing this in Release of 27-Mar-24, https://enzyme.expasy.org/index.html. Am I missing something? Thanks.

**Comment by raymond91125** [comment]
This is all still very confusing. EC and RHEA have not been updated. As it stands, GO:0004651 polynucleotide 5'-phosphatase activity, the only DEF XREF is EC:3.1.3.33 which is purine ribonucleoside specific, thus it should be a child of GO:0140818 mRNA 5'-triphosphate monophosphatase activity rather than a parent.

Parenthetically, PMID:4289819 described 3 different activities, one of those is a RNA/DNA 5' phosphatase. "A third unique phosphatase activity was also encountered in extracts of phage-infected cells. An enzyme, purified extensively from this source, was found capable of removing the 5’-phosphate groups of ribo- and deoxyribopolynucleotides", and "The final preparation shows a high degree of specificity in the cleavage of 5’-phosphoryl groups from polynucleotides and is without effect on 5’-mononucleotides."

**Comment by raymond91125** [comment]
@ValWood I think the answer to your original question is that GO:0004651 | polynucleotide 5'-phosphatase activity is probably not a superclass of GO:0140818 | mRNA 5'-phosphatase activity

**Comment by raymond91125** [comment]
I changed the DEF and XREF to that of RHEA:11008. This is neither perfect nor final but hopefully EC can get their fixes in before we do anything more.
Please let me know if anyone thinks more should be done now. Thanks.

**Comment by kaxelsen** [comment]
> @raymond91125 The changes have been made in the working copy of ENZYME. They will unfortunately only become public in UniProt release 2024_02 (that includes releases of ENZYME and Rhea).

I'm sorry. The entries did not become public in release 2024_02 as I expected. But release 2024_03 is May 29 so it should all be good by then.

**Comment by ValWood** [comment]
OK,
I will report the mapping for


GO:0004651 | polynucleotide 5'-phosphatase activity | IBA with CAL0000199068 , PTN001999388 , S000006149 , S000004792

**Comment by ValWood** [comment]
RIght in that case the existing annotations are correct. But the enzyme is not specific for  purine (as far as I know)
so why do we need this term?

**Comment by raymond91125** [comment]
Let's wait until the end of May to see what needs to be done. Thanks.

**Comment by raymond91125** [comment]
@ValWood Given the revised EC/RHEA, GO:0004651 is not a superclass of GO:0140818.

**Comment by raymond91125** [comment]
Please reopen if more is to be done.
