### ISSUE TITLE
Query:  GO:1990263 spore wall assembly MAPK cascade and  GO:0062031 filamentous growth MAPK cascade

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26611]
Hi @ValWood , @srengel @jlewsmith 

@hattrill @gantonazzo and I are looking at intracellular signaling cassettes and we propose to obsolete these 2 terms: 
GO:1990263 spore wall assembly MAPK cascade and  GO:0062031 filamentous growth MAPK cascade

they have not been used for annotation. but they are in this review cited for term creation: PMID: [17604854](https://pubmed.ncbi.nlm.nih.gov/17604854)

however a newer paper only talks about 3 pathways: PMID: [32552303](https://pubmed.ncbi.nlm.nih.gov/32552303), as if these are the 3 main pathways? We dont want to imply the other 2 don't exist, but it seems we could have many different triggers for MAPK cascades. 

Please let us know if you're OK with obsoletion. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, how does GO:0062031 filamentous growth MAPK cascade relate to 
[signal transduction involved in filamentous growth](http://purl.obolibrary.org/obo/GO_0001402)?

**Comment by ValWood** [comment]
Pombe only has
P38 (Stress)
Cell wall integrity
pheromone response MAPK cascade 

Osmolarity, is the p38 (it responded to multiple different stresses with different upstream inputs i.e. for oxidative stress, salinity, nutrient stress etc etc etc)


But see the comments in 
https://github.com/geneontology/go-ontology/issues/26610#issuecomment-1850723346
this is quite a major change because the "MAPK cascade" terms were only for the MAPK cassette.

**Comment by jlewsmith** [comment]
Hello Pascale,

I am no expert on MAPK cascades, but I can offer some C. albicans perspective.

Regarding your last question about how does GO:0062031 filamentous growth MAPK cascade relate to
signal transduction involved in filamentous growth<http://purl.obolibrary.org/obo/GO_0001402>, the former is more specific than the latter because there appear to be multiple signaling pathways that trigger filamentation in C. albicans, and not all involve MAP kinases.



As to your related question about GO:0010969 regulation of pheromone-dependent signal transduction involved in conjugation with cellular fusion being the same or different from

GO:0071507 pheromone response MAPK cascade, I'd say that for as much as is known at present, they're not really different for C. albicans because the pheromone response does involve MAPK and does lead to conjugation. I'd be fine with keeping one or the other depending on what's useful for SGD and PomBase.



Best regards,
Jodi



________________________________

**Comment by srengel** [comment]
this one is a thing: filamentous growth MAPK cascade

but not sure about the spore wall one, will have to do some reading and looking around...

**Comment by robnash** [comment]
I am not sure if the idea here is to remove terms that refer to specific MAPK cascades, like GO:0062031 filamentous growth MAPK cascade and GO:0071507 pheromone response MAPK cascade and annotate higher up in the tree to terms like GO:0051403 stress-activated MAPK cascade or even higher to GO:0000165 MAPK cascade, since these cassettes are used in multiple pathways? 

For example, for pheromone signaling, in my mind, I consider GO:0071507 pheromone response MAPK cascade to be part of GO:0000750 pheromone-dependent signal transduction involved in conjugation with cellular fusion. Similarly, I think GO:0062031 filamentous growth MAPK cascade is part of a larger process, GO:0001402 signal transduction involved in filamentous growth. In the case of usage, yes, this term (GO:0062031) could be used for yeast annotations (was not either because of oversight or the constant back and forth about these pathways that seems to continue to be revisited over and over and over). So this one is a useful term (and as Stacia mentioned is a thing) but if the idea is to remove specific MAPK terms if components are shared in other cascades like the overlap in filamentous signaling and pheromone signaling and annotate to a more generic term than maybe it makes sense.

The other term GO:1990263 spore wall assembly MAPK cascade, was created to annotate a potential signaling cascade involved in spore wall assembly. The pathway has not been fully defined but is thought to include SMK1 (see for example, figure 1 in PMID: 17604854 (https://pubmed.ncbi.nlm.nih.gov/17604854/) and PMID: 7958885 (https://pubmed.ncbi.nlm.nih.gov/7958885/) and SPS1, a STE20-like kinase that may function upstream of SMK1 (see figure 7 and the section '2.4.5. The Smk1 pathway" in PMID: 25218923 (https://pubmed.ncbi.nlm.nih.gov/25218923/).

**Comment by pgaudet** [comment]
Thanks @robnash @jlewsmith @srengel for your input. 

Concerning the GO:0062031 filamentous growth MAPK cascade term, I have updated the definition to be explicit about members of the cascade: 

-old def: "The MAPK cascade which is activated as a result of partial nutrient deprivation and which results in filamentous growth." [PMID:17604854, PMID:38187743]
**+new def: "A MAPK cascade containing at least the Kss1 MAP kinase. It starts with the activation of Ste20, a MAP4K, which activates Ste11, a MAP3K, which in turn activate Ste7, a MAP2K, which activates Kss1. The kinases in each tier phosphorylate and activate the kinases in the downstream tier. The filamentous growth MAPK cascade is activated as a result of partial nutrient deprivation and  results in filamentous growth." [PMID:17604854, PMID:33335117, PMID:38187743]**


please let me know if you'd like to modify this.

**Comment by pgaudet** [comment]
@srengel @robnash @hattrill 

WTR the spore wall pathway, I found this paper: https://pubmed.ncbi.nlm.nih.gov/28223369/
which states 
> Smk1 is a meiosis-specific mitogen-activated protein kinase (MAPK) in Saccharomyces cerevisiae that couples spore morphogenesis to the completion of chromosome segregation.

OK, cell wall pathway

> However, it is not activated by a dual-specificity MAPK kinase. Instead, T207 in Smk1's activation loop is phosphorylated by the cyclin-dependent kinase (CDK)-activating kinase (Cak1)

So, that makes it *not* a MAPK cascade, right? If this is the case, we should obsolete  GO:1990263 spore wall assembly

Thanks, Pascale

**Comment by srengel** [comment]
we don't have any annotations to GO:1990263.  looking at the history of the term, and the fact that SGD isn't using it at all, i think we're fine with @pgaudet suggestion to obsolete it.
