### ISSUE TITLE
Textual definition update: GO:0000196 cell wall integrity MAPK cascade

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26610]
Hi @srengel @ValWood 

GO:0000196 cell wall integrity MAPK cascade is currently defined as 'A MAPK cascade that contributes to cell wall organization or biogenesis.' We have found newer reviews that describe the pathways in more detail, for example PMID:26945038 describes this as starting with 'transmembrane sensor proteins (Wsc1–3, Mid2 and Mtl1) that sense cell wall damage and transmit the signal through interaction of their cytoplasmic domain with the GDP/GTP exchange factor Rom2, which activates the small GTPase Rho1 by catalyzing nucleotide exchange. Rho-GTP then interacts with protein kinase C, which activates a conserved mitogen-activated protein (MAP) kinase signaling cascade. Target transcription factors are the SBF complex, which regulates cell cycle progression, and Rlm1, which activates genes required for compensatory changes in cell wall metabolism. ' 

Couple of points: 
1. This should not be is_a [MAPK cascade](http://purl.obolibrary.org/obo/GO_0000165), since it is broader than than; it should be an '[intracellular signal transduction](http://purl.obolibrary.org/obo/GO_0035556)' 
2. We could change the label to 'fungal-cell wall integrity signaling'? 
3. We could change the definition to something a bit more specific like 'A signaling pathway that starts with the sensing of cell wall damage, mediated by Rho proteins and MAP kinase cascade, and ends with regulation of transcription of genes involved in cell cycle progression and cell wall metabolism.

What do you think ? 
We can add 'has part' Rho signaling' and 'MAPK signaling cascade'.

**Comment by ValWood** [comment]
I don't have a major objection, but this is a major change to how we were told to annotate MAPK cascade in 2017 as a result of the signalling workshop.

MAPK was only to be used for the signaling cassette, from MAPKKK(K)->MAPKK and MAPK.

See:
Definition ([GO:0000165 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0000165))
An intracellular protein kinase cascade containing at least a MAPK, a MAPKK and a MAP3K. The cascade can also contain an additional tiers: the upstream MAP4K. The kinases in each tier phosphorylate and activate the kinase in the downstream tier to transmit a signal within a cell. PMID:20811974 PMID:9561267

Comments
MAPK cascades lie downstream of many cell surface receptors and cooperate in transmitting various extracellular signals to the nucleus. One way by which the specificity of each cascade is regulated is through the existence of several distinct components in each tier of the different cascades. The cascades are typically named according to the component in the MAPK tier.

MAPK signalling was the example used, and we were told to annotate anything upstream of the MAPKKK  pathway as "regulation of MAPK signalling" This is because there usually are multiple pathways feeding into the MAPK module.

(we were also allowed to include the adaptors, but none of the upstream signalling)

This is what I always followed:

If this changes everyone will need to be informed because we all revised annotations to match this. I remember very clearly because it is one of the few Noctual models I made.

(I prefer to describe by complete pathway so I'm happy to change, it makes more sense in many ways)

**Comment by pgaudet** [comment]
Hi @ValWood 

Thanks for the comments. If I understand correctly, your comments are consistent with the proposal - ie the children of GO:0051403 stress-activated MAPK cascade are broader than the MAPK cascade, so they should not be there anyway: 

<img width="546" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/fa32a31c-7d7e-4564-9c3e-a37a444a02dc">

Right ?

**Comment by ValWood** [comment]
I'm not sure. Historically any term with MAPK cascade only referred to the signalling cassette. These terms were supposed to represent different signalling cassettes, but  in the end they didn't, they sometimes represented the use of the same signalling cassette in different stress situations, so in that respect, they are narrower rather than broad (but unnecessary IMHO). 
Personally I only used on stress-activated MAPK-term (p38MAPK) because Sty1 is a p38 kinase.
When the Sty1 (p38) pathway was activated in response to different stresses, I do this by coupling with 
part_of "response to oxidative stress" or "response to osmotic stress".

So I might not be the best person to ask.

**Comment by ValWood** [comment]
If you are referring to the regulation terms, these are "broader" because they refer to the inputs.

There are probably quite extensive notes somewhere about this because it was the first pathway that the signalling group tackled and it was discussed on quite a few annotation calls.

@vanaukenk might remember more...

**Comment by hattrill** [comment]
Hi @ValWood - so as you said above the MAPK cascade terms should be restricted to the MAPKs and the scaffolds is the same as from the signaling workshop. I guess the question is, does 'cell wall integrity MAPK cascade' mean a specific set of MAPKKK/KK/Ks+adaptors 


So, I think that the question is whether the "cell wall integrity MAPK cascade" is a specific set of MAPKKK/KK/Ks like p38 MAPKs, for example or whether it is falls under a class that we have already.

The def for cell wall integrity MAPK cascade: "A MAPK cascade that contributes to cell wall organization or biogenesis." is just based on the process, rather than defining the components
Looking at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1197416/  they list Bck1, Mkk1/2, and Mpk1  (s.c.) 

<img width="375" alt="Screenshot 2023-12-12 at 16 51 44" src="https://github.com/geneontology/go-ontology/assets/11865746/3a28a943-d0fc-49cc-a743-64cfee2b3a1e">


So, if this cassette is a distinct set, it would be good to give it a more descriptive definition and term name. If not distinct, could be merged with another.

Then, perhaps there would be a term for the pathway: 'fungal-cell wall integrity signaling'?

**Comment by robnash** [comment]
Not sure what is needed her wrt comments. My understanding is that the term: GO:0000196 cell wall integrity MAPK cascade was created to describe ONLY the components of the MAPK cascade, which in yeast includes (MAPK4 (PKC1), MPAK3 (BCK1), MAPK2 (MKK1 and MKK2) and MAPK (SLT2 (aka  MPK1) and possibly KDX1 (aka MLP1The full pathway from sensors, through to transcription factors should be annotated to some kind of common term like the proposed 'fungal-cell wall integrity (CWI) signaling', but only the MAPKs (and maybe the scaffolds) should be annotated to GO:0000196 cell wall integrity MAPK cascade. The review I have been looking at is not the most up to date but a good one (Levin, 2011; PMID:22174182)

Helen questioned whether this is a specific and unique set and I believe in yeast it does fit this criteria. This is not the case for the pheromone and pseudohyphal/invasive growth MAPKs where there is almost complete overlap (STE11, STE7 and FUS3 + KSS1)  This cassette, however, does respond to more than just cell wall stress/damage. See for example, Jiménez-Gutiérrez et al., 2020; PMID: 31342212, where they describe other stimuli that activate this signaling pathway including protein unfolding, low or high pH, or plasma membrane, oxidative and genotoxic stresses. So the definition need to be broad enough to encompass more than just cell wall damage

**Comment by ValWood** [comment]
Sorry I misunderstood the question.

Fission yeast has 3 independent MAPK cassettes:
cell wall integrity MAPK cascade
Mkh1, pek1, pmk1

p38MAPK
Sty1/wis1/wis4

pheromone response MAPK cascade
Byr,byr2,spk1

I notice we also have PAINT annotations to
osmosensory signaling MAPK cascade
From panther, but in fission yeast the P38MAPK and osmosensory are the same MAPk module

**Comment by hattrill** [comment]
Thanks @ValWood and @robnash that's really helpful.

So starting with "cell wall integrity MAPK cascade", just updating the definition to match the ones for p38 and ERK5 examples would be a good start. Suggestion below - please edit/correct as desired.
Def:
An intracellular protein kinase cascade containing at least SLT2 (S.cerevisiae)/Pmk1 (S.pombe) MAPK, a MAPKK and a MAP3K. The cascade can also contain an additional tier: the upstream MAP4K. The kinases in each tier phosphorylate and activate the kinases in the downstream tier to transmit a signal within a cell. In yeast, the cell wall integrity MAPK cascade is part of a signaling pathway that contributes to the maintenance of cell wall integrity.

Should we put a taxon constriant on this @pgaudet ?

**Comment by hattrill** [comment]
For osmosensory signaling MAPK cascade: Should we merge osmosensory signaling MAPK cascade with p38MAPK signaling, as HOG1 and Sty1 are p38 MAPKs?
There ia also a signaling pathway term : osmosensory signaling pathway, so these components could be annotated to the cascade and the pathway, so the osmosensory sense will not be lost.

**Comment by ValWood** [comment]
Your suggestions seem good.

One concern. It seems that now we  plan to have broader pathways 
osmosensory signaling pathway
If so, how will the cascade be related to the broader pathway? will it be part_of or has_part?

**Comment by pgaudet** [comment]
The osmosensory signaling pathway would have 'has part' MAPK cascade'. We cannot do the other way around, ie  MAPK cascade' part of 'osmosensory signaling pathway', since this is not always true.

**Comment by ValWood** [comment]
could it be

cell wall integrity MAPK cascade part_of osmosensory signaling pathway
though?

**Comment by hattrill** [comment]
> could it be
> 
> cell wall integrity MAPK cascade part_of osmosensory signaling pathway though?

I guess if the kinases involved are the SLT2/Pmk1 this would be the correct usage. A cassette should be a unit in itself.

I think from the comments above, it would be p38MAPK cascade part of osmosensory signaling pathway. This is consistent with other MAPK-containing pathways e.g.
ERK1 and ERK2 cascade part_of epidermal growth factor receptor signaling pathway
ERK1 and ERK2 cascade part_of platelet-derived growth factor receptor signaling pathway
ERK1 and ERK2 cascade part_of fibroblast growth factor receptor signaling pathway

**Comment by ValWood** [comment]
cell wall integrity MAPK  isn't p38,  the human ortholog is MAPK7 (ERK5)

**Comment by hattrill** [comment]
No, that's not what I meant - from the comments above, Sty1 is a p38? and is a osmosensory component? Hence the suggestion to merge  osmosensory signaling MAPK cascade and p38MAPK cascade

**Comment by ValWood** [comment]
oh my comment wass mixed up,
I meant to say cell wall integrity MAPK part of some general cell wall integrity signalling. I will delete the previous comment.

I agree to merge 
osmosensory signaling MAPK cascade into p38MAPK cascade

**Comment by hattrill** [comment]
That depends if "cell wall integrity signaling" is a definable pathway or various stress-response pathways that use the cell wall integrity MAPK cascade" and have terms that better describe them - if the latter is the case, then we don't need to make a new term.

**Comment by pgaudet** [comment]
- [x] Updated definition of GO:0000196 cell wall integrity MAPK cascade from "A MAPK cascade that contributes to cell wall organization or biogenesis." to "An intracellular protein kinase cascade containing at least SLT2 (S.cerevisiae)/Pmk1 (S.pombe) MAPK, a MAPKK and a MAP3K. The cascade can also contain an additional tier: the upstream MAP4K. The kinases in each tier phosphorylate and activate the kinases in the downstream tier to transmit a signal within a cell. In yeast, the cell wall integrity MAPK cascade is part of a signaling pathway that contributes to the maintenance of cell wall integrity."
- [ ] What TC should I add? I see that plants also have a cell wall integrity signaling pathway that includes MAPKs, see PMID: [35674976](https://pubmed.ncbi.nlm.nih.gov/35674976)

**Comment by hattrill** [comment]
For TC, I would suggest definitely: "never in" animals
And probably: "Only in" plants, algae and fungi

**Comment by pgaudet** [comment]
To do: obsolete [GO:0000161](https://www.ebi.ac.uk/QuickGO/term/GO:0000161) osmosensory signaling MAPK cascade + regulation children

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0000161 osmosensory signaling MAPK cascade and its regulation children, GO:0140531 regulation of osmosensory signaling MAPK cascade and GO:0140532 negative regulation of osmosensory signaling MAPK cascade. The reason for obsoletion is that this represents the same pathway as GO:0038066 'p38MAPK cascade', as described in PMID: 32794416 (see Fig1). The terms will be replaced as follows: 
- GO:0000161 osmosensory signaling MAPK cascade >  GO:0038066 'p38MAPK cascade'
- GO:0140531 regulation of osmosensory signaling MAPK cascade > GO:1900744 regulation of p38MAPK cascade
- GO:0140532 negative regulation of osmosensory signaling MAPK cascade > GO:1903753 negative regulation of p38MAPK cascade
All annotations are by SGD and will be automatically replaced, see reports in https://github.com/geneontology/go-annotation/issues/4928


There are no mappings to these terms, these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26610

Thanks, Pascale

**Comment by pgaudet** [comment]
Fixed definition of GO:0038066 'p38MAPK cascade' to include yeast: 

A MAPK cascade containing at least the p38MAPK (MAPK14) MAP kinase, or Hog1 in yeast. It starts with the activation of a MAP3K, and the consecutive activation of a MPK2K and of p38MAPK. The cascade can also contain an additional tier: the upstream MAP4K. The kinases in each tier phosphorylate and activate the kinases in the downstream tier. The p38MAPK cascade is activated by stress signals, including hyperosmolarity, as well as by G protein-coupled receptors, growth factors, and cytokines, and results in cellular responses such as cell proliferation, cell differentiation, apoptosis and inflammation.

**Comment by pgaudet** [comment]
@robnash suggestion: 

Add synonyms to p38MAPK cascade and regulation terms: 
GO:0000161 osmosensory signaling MAPK cascade
GO:0140531 regulation of osmosensory signaling MAPK cascade
GO:0140532 negative regulation of osmosensory signaling MAPK cascade
