### ISSUE TITLE
NTR: symbiont-mediated perturbation of host Rab signal transduction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26637]
+[Term]
+id: GO:0141127
+name: symbiont-mediated perturbation of host Rab signal transduction
+namespace: biological_process
+def: "A process in which a symbiont alters a Rab protein family-mediated signal transduction pathway in its host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction." [MITRE:tk]
+synonym: "modulation by symbiont of host Rab protein mediated signal transduction" EXACT []
+synonym: "modulation by symbiont of host Rab protein signal transduction" EXACT []
+synonym: "modulation by symbiont of host Rab protein-mediated signal transduction" EXACT []
+synonym: "modulation of host Rab protein signal transduction by symbiont" EXACT []
+synonym: "modulation of host Rab protein signaling by symbiont" EXACT []
+synonym: "modulation of host Rab protein signalling by symbiont" EXACT []
+synonym: "perturbation of host Rab protein signal transduction" EXACT []
+synonym: "symbiont-mediated perturbation of host Rab protein signal transduction" EXACT []

@genegodbold please provide references

**Comment by genegodbold** [comment]
**Affects Rho-family small GTPases**
- **Immunoglobulin-binding protein A** (IbpA) from _Histophilus somni_: IbpA is a large AMPylating protein with two Fic domains that _targets the host Rho small GTPases RhoA, Rac, and Cdc42_ on a conserved tyrosine in the GTPase switch I region. This blocks activation of downstream effectors leading to actin cytoskeletal collapse, cell rounding and cytotoxicity [PMID:20176790]. IbpA appears to interrupt some functions of phagocytic cells that are probably due to its action on the host cytoskeleton [PMID:30201700]. 
- **AexT** from _Aeromonas_: The secreted effector AexT probably acts as an ADP-ribosyltransferase for host small GTPases of the Rho family [PMID:11889090] and [PMID:17689917].
- **Dermonecrotizing toxin** (DNT) from _Bordetella_ sp: DNT targets the host Rho family small GTPases (Rho, Rac, and Cdc42). It enzymatically removes an amine group at a conserved glutamine (Gln63 in RhoA, Gln61 in Rac1 and Cdc42) changing it to Glu and causing constitutive activation of the small GTPase which then results in the formation of filopodia, ruffles, and stress-fibers [PMID:15694861]. 
- The **BopE** effector from _Burkholderia pseudomallei_ has guanine nucleotide exchange factor (GEF) activity towards host Rac1 and Cdc42, both Rho-family small GTPases [PMID:12897019]. 
- **CT166** from _Chlaymidia trachomatis_ has an N terminus that resembles the clostridial glucosylating toxins. When ectopically expressed in HeLa cells, CT166 induces actin reorganization with a loss of actin stress fibers and subsequent cell rounding. These effects are correlated with glucosylation of the host Rac1 small GTPase [PMID:20360858].

**Affects Rab-family small GTPases**
- **Rab2 interacting conserved protein A** (RicA) from _Brucella_ sp: RicA is an effector of Brucella that associates with the host small GTPase Rab2, in its GDP-bound form, in a macrophage cell line [PMID:21501366]. RicA and Rab2 interact with an affinity in the tens of micromolar; this interaction does not depend on the bound nucleotide state of Rab2 under the assayed in vitro conditions [PMID:24251537].
- **Chlamydia promoter of survival** (CpoS; CT_229) from _Chlamydia trachomatis_: CpoS is a chlamydial T3SS effector that recruits host Rab small GTPases and Rab effectors to the periphery of the inclusion body in infected cells. In doing so it redirects and intercepts host clathrin-coated vesicles from the recycling pathway to the periphery of the inclusion [PMID:30893609].
- **Ehrlichia translocated factor-3** (Etf-3; Ech0767) from _Ehrlichia chaffeensis_ is a T4aSS effector that localizes to ehrlichial inclusions and sequesters the host Rab5 small GTPase in its GTP-bound form. Etf-2 delays Rab5 dissociation from (and Rab7 localization to) phagosomes from endosomes. Binding of Etf-2 to Rab5-GTP delays Rab5 inactivation and avoids routing of ehrlichial inclusions to host phagosomes [PMID:30181274].
