### ISSUE TITLE
Obsoletion request: GO:0036210 protein modification process in another organism & GO:0044000  movement in host

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26646]
Dear all, 

The proposal has been made to obsolete the following terms in the 'biological process involved in interspecies interaction branch: 

- [x] - GO:0036210 protein modification process in another organism: process not specific enough
- [x] - GO:0044000  movement in host: unnecessary grouping class

As well as the following terms that describe a host response, not a symbiont process: 

- [x] - GO:0052019 modulation by symbiont of host hormone or growth regulator levels
- [x] - GO:0075343 modulation by symbiont of abscisic acid levels in host
- [x] - GO:1990218 positive regulation by symbiont of abscisic acid levels in host
- [x] - GO:0052021 modulation by symbiont of ethylene levels in host
- [x] - GO:1990212 positive regulation by symbiont of ethylene levels in host
- [x] - GO:0044032 modulation by symbiont of indole acetic acid levels in host
- [x] - GO:0044846 negative regulation by symbiont of indole acetic acid levels in host
- [x] - GO:1990210 positive regulation by symbiont of indole acetic acid levels in host 
- [x] - GO:0052022 modulation by symbiont of jasmonic acid levels in host
- [x] - GO:1990211 positive regulation by symbiont of jasmonic acid levels in host
- [x] - GO:0052023 modulation by symbiont of salicylic acid levels in host
- [x] - GO:1990213 negative regulation by symbiont of salicylic acid levels in host
- [x] - GO:0052024 positive regulation by symbiont of hormone or growth regulator levels in host 
- [x] - GO:0052075 induction by symbiont of host jasmonic acid-mediated defense response
- [x] - GO:0052104 induction by symbiont of host systemic acquired resistance
- [x] - GO:0044832 induction by virus of host cytokine production
- [x] - GO:0052102 positive regulation by symbiont of defense-related host calcium-dependent protein kinase pathway
- [x] - GO:0052074 positive regulation by symbiont of host salicylic acid-mediated defense response
- [x] - GO:0052064 induction by symbiont of defense-related host reactive oxygen species production 
- [x] - GO:0052062 induction by symbiont of host phytoalexin production
- [x] -  GO:0052344 positive regulation by symbiont of host phytoalexin production 

These terms have no mappings, no annotations, and are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26646

Thanks, Pascale

**Comment by genegodbold** [comment]
The "movement in host" definitely introduces an odd constraint.

The terms "modulation", "positive regulation", and "negative regulation" should be avoided for actions where the symbiont is the agent. Why? Because these are the same terms used for homeostatic interactions within an organism. Different words like "disruption" and "perturbation" should be used so as to signal that these are NOT business-as-usual processes for the (host) organism.

"Induction" is also a strange term. I think it blurs agency. When a biological process is "induced" in one organism (the host) by a symbiont, is the host the agent? Is it detecting a symbiont molecule and then reacting (normally, as it should) to that stimulus? Or is the symbiont the instigator? Is the symbiont provoking an inflammatory response by enzymatically activating a host inflammatory pathway? Or is the host activating its own inflammatory pathway in recognition of the symbiont? In the former case the agency is with the symbiont while in the latter case the agency is with the host. But "induction" could cover both of these and so its use confuses the situation.

**Comment by genegodbold** [comment]
Pascale, I know you know these things but I wanted to get them down somewhere so I'll remember them better, especially as we write this up.
