### ISSUE TITLE
Fix labels and parents of viral entry terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26670]
- [ ] GO:0046718 viral entry into host cell >> change label to  'symbiont entry into host cell' & change definition to 'The process by which a symbiont breaches the plasma membrane or cell envelope and enters the host cell. The process ends when the symbiont or its genome is released into the host cell cytoplasm.'
- [ ] GO:0044409 entry into host >> change label to  'symbiont entry into host'
- [ ] GO:0044694 pore-mediated entry of viral genome into host cell >> change label to 'symbiont entry into host cell via pore formation in plasma membrane' &  change definition to 'Entry of a symbiont into a host cell by a pore formed by the symbiont in the host cell. Examples of this process include injection by a non-enveloped virus of the viral genome into the host cytoplasm, usually mediated by a viral pore-forming peptide associated with the viral capsid or bacteriophage tail.'
- [ ] GO:0098932 disruption by virus of host cell wall peptidoglycan during virus entry >> change label to 'symbiont entry into host cell via disruption of host cell wall peptidoglycan'; remove is_a  GO:0019048 ! modulation by virus of host process; add part_of GO:0046718 ! symbiont entry into host cell
- [ ] GO:0098994 disruption of host cell envelope during viral entry >> change label to symbiont entry into host cell by disruption of host cell envelope; add part_of GO:0046718 ! symbiont entry into host cell & change definition to "The disruption by a symbiont of host cell envelope components to allow entry into the host cell."
- [ ] GO:0098995  disruption by virus of host envelope lipopolysaccharide during virus entry >> change label to  symbiont entry into host cell via disruption of host cell envelope lipopolysaccharide; remove is_a: GO:0019048 ! modulation by virus of host process  ; change definition to "The disruption by a symbiont of host cell wall lipopolysaccharides to allow entry into the host cell. For example a phage entering a Gram-negative bacterium may actively break down outer membrane lipopolysaccharides."
- [ ] GO:0098996 disruption of host cell glycocalyx during viral entry >> change label to  symbiont entry into host cell by disruption of host cell glycocalyx & change definition to "The disruption by a symbiont of host cell capsule to allow entry into the host cell.
- [ ] GO:0099006 viral entry via permeabilization of endosomal membrane >> change label to symbiont entry into host cell via permeabilization of endosomal membrane; change definition to "The entry of a symbiont into a host cell, following endocytosis, via permeabilization of the endosomal membrane by membrane penetration protein(s) of the symbiont. This process mediates the entry of some non-enveloped virus into eukaryotic cells. In some cases, viral membrane-penetration protein require first to be activated to display its membrane penetrating activity. Activation can be due to receptor binding or the acidic pH of the endosomal lumen."; add +is_a: GO:0140267 ! symbiont entry into host cell via permeabilization of host membrane
- [ ] GO:0099008 viral entry via permeabilization of inner membrane  >> change label to symbiont entry into host cell via permeabilization of inner membrane; change definition to "The entry of a symbiont into the cytoplasm of a host cell, following fusion with the outer membrane, via permeabilization of the plasma (inner) membrane. This process mediates the entry of some non-enveloped viruses into prokaryotic cells. In the case of some double stranded RNA viruses of prokaryotes this occurs via interaction of a membrane-interacting component of the capsid, leading to depolarization an permeabilization of the plasma membrane."  
- [ ] GO:0140267 viral entry via permeabilization of host membrane >> change label to symbiont entry into host cell via permeabilization of host membrane; change definition to "The entry of a symbiont into the cytoplasm of a host cell, triggered by an interaction between the bilayer of a host membrane and a membrane-penetration symbiont protein. This process mediates the entry of some non-enveloped virus into host cells, and results in the release of the virus contents into the host cell's cytoplasm." 

- [ ] GO:0039678 viral genome ejection through host cell envelope >> change label to symbiont genome ejection through host cell envelope & definition to "Entry of a symbiont's genome into the host cell through the host cell envelope. Occurs in non-envelop
ed prokaryotic viruses. Caudovirales carry an ejection apparatus that can be long and contractile, long and 
noncontractile, or short, and is able to penetrate the host cell envelope to deliver the viral genome into t
he host cell cytoplasm." 
- [ ]  GO:0099000 viral genome ejection through host cell envelope, contractile tail mechanism >> change label to  symbiont genome ejection through host cell envelope, contractile tail mechanism & definition to "Entry of a symbiont's genome into the host cell through the host cell envelope via a contractile tail ejection system consisting of a baseplate, a central tube and an external contractile sheath. Upon binding to the host cell surface, the baseplate changes its conformation and triggers sheath contraction, driving the rigid internal tail tube through the cell envelope. Occurs in non-enveloped prokaryotic viruses." 
- [ ] GO:0099001  viral genome ejection through host cell envelope, long flexible tail mechanism >> change label to  symbiont genome ejection through host cell envelope, long flexible tail mechanism & change definition to  "Entry of a symbiont's genome into the host cell through the host cell envelope via a long, flexible tail ejection system consisting a baseplate, a central tube and a terminator complex which attaches the tail to the phage capsid. Upon binding to the host cell surface, the baseplate changes its conformation and triggers genome ejection into the host cell cytoplasm. Occurs in non-enveloped prokaryotic viruses." 
- [ ] GO:0099002 viral genome ejection through host cell envelope, short tail mechanism >> change label to symbiont genome ejection through host cell envelope, short tail mechanism  & change definition to "Entry of a symbiont's genome into the host cell through the host cell envelope via a short tail ejection system consisting a central tube, the connector which attaches the tail to the phage capsid and releases inner core proteins. Upon binding to the host cell surface, the phage displays a tube-like extension of its short tail that penetrates both host membranes. This tail extension comes from the release of viral core proteins with channel forming properties. Occurs in non-enveloped prokaryotic viruses."

**Comment by SIBvirus** [comment]
GO:0046718 viral entry into host cell >> change label to 'symbiont entry into host cell' & change definition to 'The process by which a symbiont breaches the plasma membrane or cell envelope and enters the host cell. The process ends when the symbiont or its genome is released into the host cell **cytoplasm/nucleus**.'

GO:0099006 viral entry via permeabilization of endosomal membrane >> change label to symbiont entry into host cell via permeabilization of endosomal membrane; change definition to "The entry of a symbiont into a host cell, following endocytosis, via permeabilization of the endosomal membrane by membrane penetration protein(s) of the symbiont. This process mediates the entry of some non-enveloped virus into eukaryotic cells. In some cases, viral membrane-penetration protein **requires** first to be activated to display its membrane penetrating activity. Activation can be due to receptor binding or the acidic pH of the endosomal lumen."; add +is_a: GO:0140267 ! symbiont entry into host cell via permeabilization of host membrane



GO:0099008 viral entry via permeabilization of inner membrane >> change label to symbiont entry into host cell via permeabilization of inner membrane; change definition to "The entry of a symbiont into the cytoplasm of a host cell, following fusion with the outer membrane, via permeabilization of the plasma (inner) membrane. This process mediates the entry of some non-enveloped viruses into prokaryotic cells. In the case of some double stranded RNA viruses of prokaryotes this occurs via interaction of a membrane-interacting component of the capsid, leading to depolarization **and** permeabilization of the plasma membrane."

 GO:0140267 viral entry via permeabilization of host membrane >> change label to symbiont entry into host cell via permeabilization of host membrane; change definition to "The entry of a symbiont into the cytoplasm of a host cell, triggered by an interaction between the bilayer of a host membrane and a membrane-penetration symbiont protein. This process mediates the entry of some non-enveloped virus into host cells, and results in the release of the virus contents into the host **cell** cytoplasm."

**Comment by pgaudet** [comment]
Thanks for reading this so carefully! I simplified the def for GO:0046718 viral entry into host cell >> change label to 'symbiont entry into host cell' & change definition to 'The process by which a symbiont breaches the plasma membrane or cell envelope and enters the host cell. The process ends when the symbiont or its genome is released into the host cell ~cytoplasm/nucleus~.'

OK ?
