### ISSUE TITLE
NTR: symbiont-mediated suppression of host immune response via inhibition of immunoglobulin activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26740]
Please provide as much information as you can: 

* **Suggested term label:**
symbiont-mediated suppression of host immunoglobulin activity

* **Definition (free text)**

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0052562 symbiont-mediated suppression of host immune response

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
@genegodbold please provide some references

**Comment by genegodbold** [comment]
- **BatB** from _Bordetella pertussis_ is an autotransporter with a conserved N-terminal and C-terminal region but a variable number of 88-amino acid repeats. BatB binds host immunoglobulin in vitro. In vivo, a B. pertussis mutant in which the gene for BatB is deleted was cleared more rapidly from the lower respiratory tract because of its inability to overcome the immune defenses. BatB prevents nonspecific antibodies from facilitating neutrophil-mediated clearance [PMID:18426869].
- Staphylococcal binder of immunoglobulin (Sbi) from _Staphylococcus aureus_: Both cell envelope-associated Sbi and secreted Sbi interact with host immunogloublin G (IgG)[PMID:22256861]. Sbi protein bound IgG from multiple species and canine complement C3, neutralized complement activity and bound to canine IgM and B cells. Evidence from this work suggests Sbi may play an important role in Staphylococcus pseudintermedius immune evasion [PMID:31335868].
- Endo-beta-N-acetylglucosaminidase (EndoS) from Streptococcus: EndoS removes carbohydrates from native immunoglobulin G (IgG). This renders antibodies incapable of eliciting host functions through either complement or Fcgamma receptors, providing the bacteria with a survival advantage [PMID:24753590].
- IgA1 protease (IgA1P) from _Haemophilus influenzae_: IgA1 proteases are extracellular proteases that cut the hinge region of human immunoglobulin A1 (IgA1) which predominate on mucosal membranes. Those from _H. influenzae_ are serine protease autotransporters whose proteolytic activity is limited to the hinge region of IgA1 [PMID:18165266].

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141140
+name: symbiont-mediated suppression of host immunoglobulin-mediated immune response
+namespace: biological_process
+def: "A process in which a symbiont interferes with, inhibits or disrupts the normal execution of the immunoglobulin-mediated immune response of the host organism. One common mechanism by which this happens is the direct inhibition of immunoglobulin activity, by direct binding or modification. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:18426869, PMID:22256861, PMID:24753590]
+synonym: "symbiont-mediated suppression of host immunoglobulin activity" RELATED []
+is_a: GO:0052562 ! symbiont-mediated suppression of host immune response
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26740" xsd:anyURI
+created_by: pg
+creation_date: 2024-01-16T09:55:22Z
+
