### ISSUE TITLE
NTR: evasion of symbiont recognition by host pattern recognition receptor

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26743]
Please provide as much information as you can: 

* **Suggested term label:**
New term: evasion of symbiont recognition by host pattern recognition receptor

* **Definition (free text)**
* by alteration or concealment of the ligand for the pattern recognition receptor

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
parent: evasion of host innate immune recognition'

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by genegodbold** [comment]
- **Peptidoglycan deacetylase** (PgdA) from _Listeria monocytogenes_: N-deacetylation of peptidoglycan by the the product of the pgdA gene allows Listeria monocytogenes to evade several components of the host innate immune system including recognition by the Toll-like receptor 2 (TLR2) and the NOD1 protein. The activity of the product of the pgdA gene renders the bacterium more resistant to the lytic activity of lysozyme [PMID:25157076]. Without deacetylation, the bacterium is 100,000 times more susceptible to killing by lysozyme. L. monocytogenes expressing a nonfunctional copy of the pgdA gene are impaired for survival in macrophages as well as for survival in the intestine. They do not escape the phagosome as do wild type bacteria. L. monocytogenes expressing a nonfunctional copy of the pgdA gene produce a far greater cytokine response (IL-6 and IFNβ in macrophages compared to those expressing a functional copy [PMID:17215377].
-  AlmG from _Vibrio cholerae_: AlmG is a peripheral membrane aminoacyl transferase that modifies Vibrio cholerae lipopolysaccharide (LPS) to provide resistance to destruction by cationic antimicrobial peptides. In Vibrio cholerae it functions in an operon with AlmE and AlmF [PMID:29101229].
- Serralysin (alkaline protease A; AprA) from Pseudomonas aeruginosa: AprA can inhibit detection of the bacterial flagellin via host TLR5 by proteolyzing the flagellin monomer [PMID:22131330]. LasB can cooperate with AprA/Serralysin to proteolyze bacterial flagellin to prevent host immune recognition [PMID:26502908].
- **PhoP-activated gene L** (PagL) and **PhoP-activated gene P** (PagP) from Salmonella: Four types of differently acylated lipid A are generated by the modifications catalyzed by PagL and/or PagP: (1) unmodified lipid A (2) deacylated lipid A, (3) palmitoylated lipid A (4) deacylated and palmitoylated lipid A. Both deacylated and palmitoylated lipid A demonstrate a decreased ability to activate NFκB through TLR4 [PMID:15014080]. PagL from Salmonella spp. is a 3-O-deacylase which, in concert with PagP from Salmonella sp, alters lipid A of bacterial lipopolysaccharide (LPS) so that it activates TLR4 less efficiently and lessens the innate immune response.

**Comment by pgaudet** [comment]
GO:0141141
 name: evasion of symbiont recognition by host pattern recognition receptor
 namespace: biological_process
+def: "A process by which a symbiont avoids recognition by host's innate immune response by altering or concealing a conserved molecule recognized by the host's cell surface and intracellular pattern recognition receptors, including Toll-like and NOD-like receptors. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:17215377, PMID:26502908, PMID:29101229]

**Comment by pgaudet** [comment]
Added a note to GO:0039537 symbiont-mediated suppression of cytoplasmic pattern recognition receptor signaling pathway:  Note that this term should be used when the symbiont directly inhibits a component of a host cytoplasmic receptor signaling pathway. In cases where the symbiont modifies its own molecules (proteins, DNA, RNA, lipids) to avoid recognition by the host, consider annotating to evasion of symbiont recognition by host pattern recognition receptor ; GO:0141141.


And to GO:0141141 evasion of symbiont recognition by host pattern recognition receptor : Note that this term should be used when the symbiont in cases where the symbiont modifies its own molecules (proteins, DNA, RNA, lipids) to avoid recognition by the host. In cases where the symbiont  directly inhibits a component of a host cytoplasmic receptor signaling pathway, consider annotating to evasion of symbiont recognition by host pattern recognition receptor ; GO:0039537.
