### ISSUE TITLE
Fix label and definiton GO:0044542 'plasminogen activation in another organism'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26812]
For the GO-PathGO alignment, we will 

- [x] change the label of GO:0044542 'plasminogen activation in another organism' to GO:0044542 symbiont-mediated activation of host plasminogen
- [x] change the definition to "A process in which a symbiont initiates, promotes, or enhances the normal activation of plasminogen, the pathway resulting in the processing of inactive plasminogen to active plasmin in the host organism."
- [x] move term under GO:0044003 'modulation by symbiont of host process'

@genegodbold to provide references and also to look into whether this is the same or one mechanism for complement inhibition? ie it could perhaps be a child of 
'symbiont-mediated suppression of host complement activation'

current children are: 

- 'symbiont-mediated suppression of host complement activation by complement sequestering'
- 'symbiont-mediated suppression of host complement activation by inactivation of complement proteins'
- 'symbiont-mediated suppression of host complement activation by recruitment of complement control protein'

**Comment by genegodbold** [comment]
- **Endopeptidase O** (**PepO**; **Neprilysin**) from _Streptococcus suis_: SsPepO binds host fibronectin [PMID:29253192]. SsPepO is a plasminogen-binding protein as assessed using ELISA plates coated with increasing concentrations of plasminogen. The fibronectin and plasminogen binding sites on SsPepO are independent of one another. SsPepO facilitates the attachment of the bacterium to plasminogen and enables adherence and invasion into rat brain microvessel endothelial cells. This is significant because _Streptococcus suis_ is one of the causes of meningitis. Host plasminogen bound to SsPepO can be converted to plasmin via proteolysis by host uPA and can then degrade host complement C3b and enabling the control of complement activation. A bacterial mutant lacking PepO has impaired adherence to plasminogen, invasion of rat brain microvessel endothelial cells, and is efficiently killed by human serum and blood [PMID:34305859].
- **Streptokinase** from _Streptococcus pyogenes_: Streptokinase is a host plasminogen (UniProtP00747) activator generating the serine protease plasmin [PMID:15972548]. Streptokinase hijacks the host fibrinolytic system to generate plasmin that can overcome defensive fibrin barriers thrown together by the host. On this account, streptokinase is a dissemination factor [PMID:28125743]. Host histones are antibacterial and hemolytic and complement the innate immune system in the formation of neutrophil extracellular traps (NETs) in defeating bacterial parasites. Streptococcus pyogenes protects itself from histone-killing by the acquisition of plasminogen. Plasminogen bound to the streptococcal surface via streptokinase protects the bacterial cell from histone-mediated killing. The streptokinase-plasminogen complex degrades all classes of histones and abrogates their antibacterial and hemolytic effects [PMID27533300].
