### ISSUE TITLE
Obsoletion request (maybe): GO:0005945 6-phosphofructokinase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26815]
I didn't think GO made/had protein-containing complex terms for homomers (complexes containing repeats of the same subunit)?
But maybe I'm wrong?

id: GO:0005945
name: 6-phosphofructokinase complex
namespace: cellular_component
def: "A protein complex that possesses 6-phosphofructokinase activity; homodimeric, homooctameric, and allosteric homotetrameric forms are known." [GOC:mah, GOC:vw, ISBN:0198506732]
intersection_of: GO:0032991 ! protein-containing complex
intersection_of: capable_of GO:0003872 ! 6-phosphofructokinase activity
relationship: part_of GO:0005829 ! cytosol

**Comment by pgaudet** [comment]
In the most recently updated guidelines, we say homodimers are in scope: 
https://wiki.geneontology.org/Protein_complexes

**Comment by pgaudet** [comment]
Should this be rediscussed? I sent this to the ontology editors group some time ago, but maybe we want wider feedback?

**Comment by sjm41** [comment]
Thanks for pointing me to that doc. Maybe it's fine, and I just had the wrong understanding.  Searching through the GO for 'homodimer', I do see more examples, so this isn't an isolated case.
But I imagine there are many more homomers that could be added if these are really within scope.

**Comment by deustp01** [comment]
> many more homomers that could be added

Many, many homomultimers, yes

**Comment by sjm41** [comment]
I notice we also have these two MF terms that relate to homodimers:
```
GO:0042802 identical protein binding
    |_GO:0042803 protein homodimerization activity
```

**Comment by pgaudet** [comment]
Right - I am not quite sure which complexes are really useful. @ValWood says she uses them to confirm that MF or BPs are correctly annotated; is this a common use case? 

How else do you use GO complexes?

**Comment by pgaudet** [comment]
So you dont use homomers ?

**Comment by sjm41** [comment]
I'm currently checking the FB policy for annotating homomeric complexes with @hattrill...
I think we just use the MF terms I mentioned to annotate such cases, but Helen will know better.

**Comment by ValWood** [comment]
For PomBAse this is the main reason

>FlyBase (at least) doesn't have systematic Complex Portal annotation

very few pombe entries in COmplexProtal, this is the only way we have to annotate complexes as most are initially via similarity. There si no annotation effort for complexes via Complex protal in most species so it will be a long time before this is comprehensive.

Very useful for QC too, tracking down missing complex components, and identifying missing orthologs and making sure that annotations across a complex are consistent.

I also use them to build networks  which will eventually seed GO-CAMs

I'm ambivalent about monomer complexes (since we don't usually include dimers), but I don't think they do any harm, and I have used a few.

**Comment by deustp01** [comment]
> So you dont use homomers ?

Reactome does, obsessively, because we want to catalog the molecular environment in which the enabling gene product carries out its enabling function. We also put protein : nonprotein cofactor complexes into our complex class but do not export those complexes to GO)

**Comment by ValWood** [comment]
Another use case
https://scholar.google.com/scholar_url?url=https://royalsocietypublishing.org/doi/pdf/10.1098/rsob.130053%3Fdownload%3Dtrue&hl=en&sa=T&oi=ucasa&ct=ufr&ei=HEOpZc7HNKmu6rQPqourgAo&scisig=AFWwaeYCQiah33C4mhdDfT3DLC6i

I used them successfully in an enrichment of phenotypes (worked better than processes  because complexes usually phenocopy each other)

<img width="1259" alt="Screenshot 2024-01-18 at 15 28 44" src="https://github.com/geneontology/go-ontology/assets/7359272/754ea035-45ed-40ff-8c78-68f0a6614178">


Somewhere I have a whole list of use-cases from when GO once considered obsoleting them

**Comment by sandraorchard** [comment]
For Complex Portal they are used for searching and grouping so only really find the more top-level terms useful e.g. to find all the ubiquitin-ligase complexes, not the rather random collection of child terms this has collected.
Can add more pombe to the Complex Portal if you send them over, as Flybase does.

**Comment by ValWood** [comment]
@sandraorchard  I can do that!
I will see if we can dig  out a list of the ones with experimental data!

**Comment by pgaudet** [comment]
@sjm41 Should we close this? I dont think it's a high priority (although we should make clearer guidelines at some point)

**Comment by sjm41** [comment]
Yes, we can close this specific ticket.

I was under the (false) impression that homomeric complex terms were disallowed in GO and GO:0005945 was an oddity - e.g. see this recent obsoletion ticket - https://github.com/geneontology/go-announcements/issues/458
But seems I was wrong!

Yes, definitely would be good to have clearer guidelines going forward - e.g. there are LOTS of homomeric complexes in the metabolic pathways we're starting to annotate, and annotating these with the current set of available GO complex terms for 'homomers' is going to result in patchy/inconsistent annotation. Should we request new GO terms for every homomeric complex we encounter to increase consistency/coverage of annotation? Probably not.

**Comment by sjm41** [comment]
Tagging @rozaru retrospectively.
