### ISSUE TITLE
"Ire1 complex" synonyms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26879]
Looks like the 3 "Ire1 complex" type synonyms on GO:1902555 and GO:1902556 should be deleted and added to GO:1990332? Can you confirm @vanaukenk ?

id: GO:1902555
name: endoribonuclease complex
namespace: cellular_component
def: "A protein complex which is capable of endoribonuclease activity." [GOC:bhm, GOC:TermGenie, PMID:18191223]
comment: An example is IRE1 in S. cerevisiae (UniProt ID P32361) in PMID:18191223 (inferred from direct assay).
synonym: "Ire1 complex dimer" RELATED []
synonym: "Ire1 complex homodimer" RELATED []
synonym: "Ire1 complex homooligomer" RELATED []
intersection_of: GO:0032991 ! protein-containing complex
intersection_of: capable_of GO:0004521 ! RNA endonuclease activity
created_by: bhm
creation_date: 2013-12-06T16:09:31Z

id: GO:1902556
name: phosphatidylinositol transporter complex
namespace: cellular_component
def: "A protein complex which is capable of phosphatidylinositol transporter activity." [GOC:bhm, GOC:TermGenie, PMID:9890948]
comment: An example is PDR16 in S. cerevisiae (UniProt ID P53860) in PMID:9890948 (inferred from direct assay).
synonym: "Ire1 complex dimer" RELATED []
synonym: "Ire1 complex homodimer" RELATED []
synonym: "Ire1 complex homooligomer" RELATED []
is_a: GO:1990351 ! transporter complex
intersection_of: GO:0032991 ! protein-containing complex
intersection_of: capable_of GO:0008526 ! phosphatidylinositol transfer activity
created_by: bhm
creation_date: 2013-12-06T16:12:25Z

id: GO:1990332
name: Ire1 complex
namespace: cellular_component
def: "A type-I transmembrane protein complex located in the endoplasmic reticulum (ER) consisting of an IRE1-IRE1 dimer, which forms in response to the accumulation of unfolded protein in the ER. The dimeric complex has endoribonuclease (RNase) activity and evokes the unfolded protein response (UPR) by cleaving an intron of a mRNA coding for the transcription factor HAC1 in yeast or XBP1 in mammals; the complex cleaves a single phosphodiester bond in each of two RNA hairpins (with non-specific base paired stems and loops of consensus sequence CNCNNGN, where N is any base) to remove an intervening intron from the target transcript." [GOC:bf, GOC:bhm, PMID:18191223, PMID:25437541]
comment: An example of this is Ire1 in Escherichia coli (P32361) in PMID:18191223 (inferred from direct assay).
synonym: "ERN1 complex" RELATED [HGNC:3449]
synonym: "IRE1 dimer" EXACT [PMID:25437541]
is_a: GO:1902554 ! serine/threonine protein kinase complex
relationship: capable_of GO:0004521 ! RNA endonuclease activity
relationship: capable_of_part_of GO:0036498 ! IRE1-mediated unfolded protein response
relationship: part_of GO:0005789 ! endoplasmic reticulum membrane
created_by: bhm
creation_date: 2014-03-17T10:46:58Z

**Comment by vanaukenk** [comment]
@sjm41 

I'm not aware of phosphatidylinositol transfer activity for IRE1 so perhaps the synonyms for phosphatidylinositol transporter complex (GO:1902556) are an error.

Since the Ire1 complex term (GO:1990332) is a child of endoribonuclease complex (GO:1902555), then I agree it makes more sense to have the synonyms on the child term.

Do you agree!

**Comment by ukemi** [comment]
I think that is why the synonyms are related. IRE1 is not unique.
PMID: 33140520

**Comment by sjm41** [comment]
Yes, I think those 3 synonyms should just be on the GO:1990332 Ire1 complex term.
I'll take care of it.

**Comment by ValWood** [comment]
Checking @ukemi s comment, because this would be a reason for a related synonym

PMID: 33140520 appears to also refer to  the same Ire1 complex in UPR response:

The **ER-bound kinase/endoribonuclease (RNase), inositol-requiring enzyme-1** (IRE1), regulates the phylogenetically most conserved arm of the unfolded protein response (UPR). However, the complex biology and pathology regulated by mammalian IRE1 cannot be fully explained by IRE1's one known, specific RNA target, X box-binding protein-1 (XBP1) or the RNA substrates of IRE1-dependent RNA degradation (RIDD) activity. Investigating other specific substrates of IRE1 kinase and RNase activities may illuminate how it performs these diverse functions in mammalian cells. 

If this is the case you can also add 
ER-bound kinase/endoribonuclease (RNase), inositol-requiring enzyme-1**  as an exact synonym (It makes sense to spell out the  acronym in case of future confusion)

**Comment by sjm41** [comment]
@ValWood  I will add "ER-bound kinase/endoribonuclease (RNase), inositol-requiring enzyme-1" as an exact synonym to "Ire1 complex", along with the other 3 synonyms.

But I'm confused - are you / @ukemi saying there's a good reason to keep the Ire1 synonyms as RELATED synonyms on the parent "endoribonuclease complex" term and/or the "phosphatidylinositol transporter complex" term ??

**Comment by ValWood** [comment]
I'll let @ukemi confirm, but I think he thought as I did that PMID: 33140520 was referring to a different IRE1 complex.
If the same label is used for different complexes, the synonym must be "related" because we can't have something as an exact_synonym for 2 different GO terms (and in that case we would need to disambiguate by changing the label to  qualify the differences i.e call it "ER-bound kinase/endoribonuclease (RNase), inositol-requiring enzyme-1").

**Comment by sjm41** [comment]
Reviewing this, I will do the following:

1. Remove the IRE1-related synonyms from the general parent term "GO:1902555 endoribonuclease complex" (this term was created in 2013)
2. Add those IRE1-related synonyms to the specific child term "GO:1990332 Ire1 complex" (which was created later, in 2014)
3. Also add "ER-bound kinase/endoribonuclease (RNase), inositol-requiring enzyme-1" as an exact synonym to "GO:1990332 Ire1 complex", as per Val's request.
4. Correct  the comment on GO:1990332 Ire1 complex from "An example of this is Ire1 in Escherichia coli (P32361) in PMID:18191223..." to "An example of this is Ire1 in S. cerevisiae (P32361) in PMID:18191223..."
5. Remove the IRE1-related synonyms from GO:1902556 phosphatidylinositol transporter complex - the reference given in the definition & comment (PMID:9890948) is about cerevisiae PDR16/17 and makes no mention of 'Ire1'.  Also, there's only 1 EXP annotation to GO:1902556 (to PDR16 from PMID:24403601) and that paper doesn't mention 'Ire1' either. So having these IRE1-related synonyms on GO:1902556 must be an error.

As far as I can tell, PMID: 33140520 (mentioned above) is talking about the same IRE1 enzyme/complex (mouse IRE1) as described by the "GO:1990332 Ire1 complex" term - i.e. mouse IRE1 from PMID: 33140520 is the ortholog of cerevisiae Ire1 from PMID:18191223. So I don't think that paper introduces any ambiguity here.
