### ISSUE TITLE
List of currency chemicals

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#26900]
From the 2024-01-29 ontology editors call:

Reactome has created a list of 'currency' chemicals that may help GO define those entities for use in the ontology and in annotation.

@deustp01 has asked Reactome curators/developers for help in getting this list.  Thx.

**Comment by deustp01** [comment]
Here is an e-mail thread that discusses the Reactome list of trivial / housekeeping / currency chemicals. The link to a Google doc in the thread points to a site restricted to Reactome personnel, so here is the table as an Excel spreadsheet:
[Trivial chemicals.xlsx](https://github.com/geneontology/go-ontology/files/14092484/Trivial.chemicals.xlsx)

Here's the e-mail thread:


Subject: | Re: List of trivial chemicals
-- | --
Fri, 27 Feb 2015 09:21:46 +0000
Phani Garapati <phani@ebi.ac.uk>
Henning Hermjakob <hhe@ebi.ac.uk>
Bijay Jassal <bj1@ebi.ac.uk>, Steve Jupe <sjupe@ebi.ac.uk>, Maximilian Koch <mkoch@ebi.ac.uk>, Antonio Fabregat Mundo<fabregat@ebi.ac.uk>

<br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Hi Henning,</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">I removed amino acids and ammonia. Not sure about oxygen and carbon dioxide either but we can try with this list and see how it effects the score.</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">I Will inform Max.</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Thanks,</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">Phani</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-size: medium; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; display: inline !important; float: none;">On 27/02/2015 06:00, Henning Hermjakob wrote:</span><br style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><blockquote type="cite" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-family: Aptos; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">Phani, could you please finalise and close the list this morning, and then notify Max?<br><br>On 26/02/2015 10:10, Bijay Jassal wrote:<br><blockquote type="cite">Hi Henning<br><br>Ah, I didn’t realise that. In that case no, they are not specific in<br>that respect to distinguish the pathway.<br><br>Cheers<br><br>Bijay<br><br><blockquote type="cite">On 26 Feb 2015, at 10:08, Henning Hermjakob &lt;<a class="moz-txt-link-abbreviated" href="mailto:hhe@ebi.ac.uk" contenteditable="false" title="mailto:hhe@ebi.ac.uk">hhe@ebi.ac.uk</a><br><a class="moz-txt-link-rfc2396E" href="mailto:hhe@ebi.ac.uk" contenteditable="false" title="mailto:hhe@ebi.ac.uk">&lt;mailto:hhe@ebi.ac.uk&gt;</a>&gt; wrote:<br><br>Hi Bijay,<br><br>the point (for this application) is not if the chemicals are important<br>for the reaction, but if they are SPECIFIC and help distinguished this<br>pathway from other pathways. I guess even in the examples you list,<br>that would not be the case?<br><br>On 26/02/2015 10:00, Bijay Jassal wrote:<br><blockquote type="cite">Hi Phani<br><br>Generally, the list so far would be OK to exclude but as ever, I think<br>there are exceptions where we can’t so it all depends on the context of<br>the reaction we’re looking at.<br>Take H+ for example.<br><br>Most of the time, I would be happy to exclude it but in some cases, H+<br>is a valid input/output of a reaction. Take the electron transport chain<br>example here<br><br><a class="moz-txt-link-freetext" href="https://urldefense.com/v3/__http://reactomecurator.oicr.on.ca/PathwayBrowser/*DIAGRAM=163200&amp;ID=163217&amp;PATH=1430728,1428517__;Iw!!MXfaZl3l!eg3hjdeUXie3cQXTU5PXWKu9RQxf7qOgYhi-enR4bdsYGcB-k8au5-6tl__nTkKPpKAKZUkbcF63WWgWDy0dXI01$" contenteditable="false" title="https://urldefense.com/v3/__http://reactomecurator.oicr.on.ca/PathwayBrowser/*DIAGRAM=163200&amp;ID=163217&amp;PATH=1430728,1428517__;Iw!!MXfaZl3l!eg3hjdeUXie3cQXTU5PXWKu9RQxf7qOgYhi-enR4bdsYGcB-k8au5-6tl__nTkKPpKAKZUkbcF63WWgWDy0dXI01$">http://reactomecurator.oicr.on.ca/PathwayBrowser/#DIAGRAM=163200&amp;ID=163217&amp;PATH=1430728,1428517</a><br><br>You need the electrochemical gradient generated by H+ pumping to<br>create ATP.<br><br>Also, ADP/ATP and GDP/GTP are important in nucleotide exchange reactions<br>to activate/deactivate enzymes.<br><br>Another issue crops up in transport reactions where some of these common<br>molecules are transported across membranes, so validly take part in the<br>reaction.<br><br>I guess there was always going to be exceptions and I wouldn’t know know<br>how to globally distinguish a H+ as common or valid.<br>However, I would still add these molecules to the exclusion list and see<br>what the output looks like after exclusion.<br><br>Cheers<br><br>Bijay<br><br><br><blockquote type="cite">On 26 Feb 2015, at 09:44, Phani Garapati &lt;<a class="moz-txt-link-abbreviated" href="mailto:phani@ebi.ac.uk" contenteditable="false" title="mailto:phani@ebi.ac.uk">phani@ebi.ac.uk</a><br><a class="moz-txt-link-rfc2396E" href="mailto:phani@ebi.ac.uk" contenteditable="false" title="mailto:phani@ebi.ac.uk">&lt;mailto:phani@ebi.ac.uk&gt;</a>&gt; wrote:<br><br>Hi Bijay,<br><br>I added few members to the doc looking through the reference molecule<br>list in curator tool. Can you check from that if any molecule is not<br>trivial.<br><br>Thanks,<br>Phani<br><br>On 26/02/2015 09:07, Bijay Jassal wrote:<br><blockquote type="cite">Hi guys<br><br>If anyone can find/retrieve the old pathfinder tool, that contained a<br>list of exclusion molecules.<br><br>Cheers<br><br>Bijay<br><br><blockquote type="cite">On 26 Feb 2015, at 06:45, Henning Hermjakob &lt;<a class="moz-txt-link-abbreviated" href="mailto:hhe@ebi.ac.uk" contenteditable="false" title="mailto:hhe@ebi.ac.uk">hhe@ebi.ac.uk</a><br><a class="moz-txt-link-rfc2396E" href="mailto:hhe@ebi.ac.uk" contenteditable="false" title="mailto:hhe@ebi.ac.uk">&lt;mailto:hhe@ebi.ac.uk&gt;</a><br><a class="moz-txt-link-rfc2396E" href="mailto:hhe@ebi.ac.uk" contenteditable="false" title="mailto:hhe@ebi.ac.uk">&lt;mailto:hhe@ebi.ac.uk&gt;</a>&gt; wrote:<br><br>Hi Phani,<br><br>could you please complete the list of "trivial chemicals" at [1]?<br>These are chemicals which are used frequently in Reactome, but are<br>very unspecific and don't carry much information, standard example<br>is water. I came across these because they are messing up the<br>pathway analysis. We have a good match between a set of Biomodels<br>identifiers and a Reactome pathway, but it's based on ATP, ADP, and<br>NADPH; not great.<br><br>These are also candidates to exclude when we try to present<br>simplified pathway diagrams in the future.<br><br>[1]<br><a class="moz-txt-link-freetext" href="https://urldefense.com/v3/__https://docs.google.com/spreadsheets/d/1F_lQY_4cOL9BxhThOMHX-nhU4B0VwsW--rSCUYe_Wb0/edit?usp=sharing__;!!MXfaZl3l!eg3hjdeUXie3cQXTU5PXWKu9RQxf7qOgYhi-enR4bdsYGcB-k8au5-6tl__nTkKPpKAKZUkbcF63WWgWD0FF5J8J$" contenteditable="false" title="https://urldefense.com/v3/__https://docs.google.com/spreadsheets/d/1F_lQY_4cOL9BxhThOMHX-nhU4B0VwsW--rSCUYe_Wb0/edit?usp=sharing__;!!MXfaZl3l!eg3hjdeUXie3cQXTU5PXWKu9RQxf7qOgYhi-enR4bdsYGcB-k8au5-6tl__nTkKPpKAKZUkbcF63WWgWD0FF5J8J$">https://docs.google.com/spreadsheets/d/1F_lQY_4cOL9BxhThOMHX-nhU4B0VwsW--rSCUYe_Wb0/edit?usp=sharing</a><span class="Apple-converted-space"> </span><br><br>--<span class="Apple-converted-space"> </span><br>Best regards,<br><br>Henning<br></blockquote></blockquote></blockquote></blockquote></blockquote></blockquote></blockquote>Subject:	Re: List of trivial chemicals
Date:	Fri, 27 Feb 2015 09:21:46 +0000
From:	Phani Garapati [<phani@ebi.ac.uk>](mailto:phani@ebi.ac.uk)
To:	Henning Hermjakob [<hhe@ebi.ac.uk>](mailto:hhe@ebi.ac.uk)
CC:	Bijay Jassal [<bj1@ebi.ac.uk>](mailto:bj1@ebi.ac.uk), Steve Jupe [<sjupe@ebi.ac.uk>](mailto:sjupe@ebi.ac.uk), Maximilian Koch [<mkoch@ebi.ac.uk>](mailto:mkoch@ebi.ac.uk), Antonio Fabregat Mundo [<fabregat@ebi.ac.uk>](mailto:fabregat@ebi.ac.uk)


Hi Henning,

I removed amino acids and ammonia. Not sure about oxygen and carbon dioxide either but we can try with this list and see how it effects the score.
I Will inform Max.

Thanks,
Phani

On 27/02/2015 06:00, Henning Hermjakob wrote:
Phani, could you please finalise and close the list this morning, and then notify Max?

On 26/02/2015 10:10, Bijay Jassal wrote:
Hi Henning

Ah, I didn’t realise that. In that case no, they are not specific in
that respect to distinguish the pathway.

Cheers

Bijay

On 26 Feb 2015, at 10:08, Henning Hermjakob <[hhe@ebi.ac.uk](mailto:hhe@ebi.ac.uk)
[<mailto:hhe@ebi.ac.uk>](mailto:hhe@ebi.ac.uk)> wrote:

Hi Bijay,

the point (for this application) is not if the chemicals are important
for the reaction, but if they are SPECIFIC and help distinguished this
pathway from other pathways. I guess even in the examples you list,
that would not be the case?

On 26/02/2015 10:00, Bijay Jassal wrote:
Hi Phani

Generally, the list so far would be OK to exclude but as ever, I think
there are exceptions where we can’t so it all depends on the context of
the reaction we’re looking at.
Take H+ for example.

Most of the time, I would be happy to exclude it but in some cases, H+
is a valid input/output of a reaction. Take the electron transport chain
example here

[http://reactomecurator.oicr.on.ca/PathwayBrowser/#DIAGRAM=163200&ID=163217&PATH=1430728,1428517](https://urldefense.com/v3/__http://reactomecurator.oicr.on.ca/PathwayBrowser/*DIAGRAM=163200&ID=163217&PATH=1430728,1428517__;Iw!!MXfaZl3l!eg3hjdeUXie3cQXTU5PXWKu9RQxf7qOgYhi-enR4bdsYGcB-k8au5-6tl__nTkKPpKAKZUkbcF63WWgWDy0dXI01$)

You need the electrochemical gradient generated by H+ pumping to
create ATP.

Also, ADP/ATP and GDP/GTP are important in nucleotide exchange reactions
to activate/deactivate enzymes.

Another issue crops up in transport reactions where some of these common
molecules are transported across membranes, so validly take part in the
reaction.

I guess there was always going to be exceptions and I wouldn’t know know
how to globally distinguish a H+ as common or valid.
However, I would still add these molecules to the exclusion list and see
what the output looks like after exclusion.

Cheers

Bijay


On 26 Feb 2015, at 09:44, Phani Garapati <[phani@ebi.ac.uk](mailto:phani@ebi.ac.uk)
[<mailto:phani@ebi.ac.uk>](mailto:phani@ebi.ac.uk)> wrote:

Hi Bijay,

I added few members to the doc looking through the reference molecule
list in curator tool. Can you check from that if any molecule is not
trivial.

Thanks,
Phani

On 26/02/2015 09:07, Bijay Jassal wrote:
Hi guys

If anyone can find/retrieve the old pathfinder tool, that contained a
list of exclusion molecules.

Cheers

Bijay

On 26 Feb 2015, at 06:45, Henning Hermjakob <[hhe@ebi.ac.uk](mailto:hhe@ebi.ac.uk)
[<mailto:hhe@ebi.ac.uk>](mailto:hhe@ebi.ac.uk)
[<mailto:hhe@ebi.ac.uk>](mailto:hhe@ebi.ac.uk)> wrote:

Hi Phani,

could you please complete the list of "trivial chemicals" at [1]?
These are chemicals which are used frequently in Reactome, but are
very unspecific and don't carry much information, standard example
is water. I came across these because they are messing up the
pathway analysis. We have a good match between a set of Biomodels
identifiers and a Reactome pathway, but it's based on ATP, ADP, and
NADPH; not great.

These are also candidates to exclude when we try to present
simplified pathway diagrams in the future.

[1]
[https://docs.google.com/spreadsheets/d/1F_lQY_4cOL9BxhThOMHX-nhU4B0VwsW--rSCUYe_Wb0/edit?usp=sharing](https://urldefense.com/v3/__https://docs.google.com/spreadsheets/d/1F_lQY_4cOL9BxhThOMHX-nhU4B0VwsW--rSCUYe_Wb0/edit?usp=sharing__;!!MXfaZl3l!eg3hjdeUXie3cQXTU5PXWKu9RQxf7qOgYhi-enR4bdsYGcB-k8au5-6tl__nTkKPpKAKZUkbcF63WWgWD0FF5J8J$) 

-- 
Best regards,

Henning

**Comment by pgaudet** [comment]
Thanks @deustp01 
I moved this to the wiki
https://wiki.geneontology.org/Currency_chemicals

(Note that in your list, UTP and NADP+ are present twice)

Thanks, Pascale

**Comment by pgaudet** [comment]
@deustp01 FYI

- I have changed the ChEBI Ids to the pH 7.3 (UniProt set) in the wiki table.  Most chemicals were changed, except for H2O, H+, CO2  and O2
- I removed OH-; I dont see any usage of this in GO or in RHEA. I think H2O is used instead. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi Peter, 

I added this to next Monday's ontology call for discussion. 

The key point, IMHO, is who is this list for? I thought it was internal to GO, to help define inputs and primary inputs in GO-CAMs. In this case we probably dont need the non-pH7.3 terms (and OH-). 

But I may not be thinking of all use cases of this list. 

Thanks, Pascale
