### ISSUE TITLE
NTR: recruitment of lysine acetyl transferase to promoter

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#26964]
Please provide as much information as you can: 

* **Suggested term label:**
recruitment of lysine acetyl transferase to promoter

* **Definition (free text)**
The directed movement of a protein to a part of a promoter DNA region that is organized into chromatin.

* **Reference, in format PMID:#######**
PMID:24051374 = Ravnskjaer K, Hogan MF, Lackey D, Tora L, Dent SY, Olefsky J, Montminy M. Glucagon regulates gluconeogenesis through KAT2B- and WDR5-mediated epigenetic effects. J Clin Invest. 2013 Oct;123(10):4318-28. doi: 10.1172/JCI69035. Epub 2013 Sep 24. 

* **Gene product name and ID to be annotated to this term**
mouse genes Crtc2 & Crtc3

* **Parent term(s)**
is_a establishment of protein localization to chromatin - GO:0071169

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
EXACT - "protein localization of lysine acetyl transferase to promoter" 
EXACT - "establishment of lysine acetyl transferase to promoter chromatin"

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
* I need a term to represent this recruitment of lysine acytltransferases to promoter regions by Crtc2 to replace annotations obsoleted by the histone modification term obsoletions. This represents the mechanism by which Crtc2 regulates transcription of target genes.

**Comment by ValWood** [comment]
Hi @krchristie @pgaudet  don't we annotate recruitment as an activity (i.e adaptors recruit?) . You can then also specify the modified for that does the recruiting
e.g [chromatin-protein adaptor activity](https://www.pombase.org/term/GO:0140463)

If it is a pathway/process   then is "directed movement" correct ? My understanding was that "directed movement" == transport ?

**Comment by ValWood** [comment]
I see  what you are annotating here. 

In this type of situation I have done, for example : 

1. clr4 histone H3K9 methyltransferase activity has_input hht1  part_of pericentric heterochromatin formation 

2. hht1 chromatin-protein adaptor activity "active form hht1(InitMet-/Me:(K9))" recruits clr4, part_of pericentric heterochromatin formation

3. clr4 histone reader activity has_input  hht1 (InitMet-/Ubiq:(K14)) part_of pericentric heterochromatin formation

I.e. I annotated to the process that the recruitment is involved in  (which for chromatin is usually some transcription, or chromatin remodelling) rather than 'localization" as a process which doesn't really capture the biological  purpose. This is more in line with GO-CAM and representing a pathway.  

(Note, the example above looks a bit circular because clr4 is both a reader and a writer of H3-K9 methylation but in most cases the pathway would be linear, in your example the entity would be the "lysine acetyl transferase")

If we add localisation annotation we don't really capture the process, plus nearly every step in most processes involving recruitment would require localisation terms. So far Pombase has 492 genes annotated as adaptors, some like cdc15 https://www.pombase.org/gene/SPAC20G8.05c  recruiting many gene products, (in this case the process is 'contractile ring assembly' rather than 'localization to contractile ring'). These annotations would require 100's of localization terms.

Over the past few years PomBase has reduced the number of genes annotated to localisation that isn't transport  (from >800 genes down to 78)    because it's an 'empty' annotation, and switched to the above format which captures the purpose of, and steps in the molecular pathway with no loss of information content (you can also use occurs_at for location to specify further). 

It might be useful to discuss  on an annotation call whether localization annotations are redundant with "recruitment" by an adaptor.

**Comment by ValWood** [comment]
@krchristie  closing this one for houskeeping , but reopen if this solution did not work for you
