### ISSUE TITLE
Obsoletion request: GO:0110046 signal transduction involved in cell cycle switching, mitotic to meiotic cell cycle

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27022]
Obsoletion notice: GO:0110046 signal transduction involved in cell cycle switching, mitotic to meiotic cell cycle

The reason for obsoletion is that this term represents a mix of different pathways. 

Thanks, Pascale

**Comment by ValWood** [comment]
I am now struggling with this one. For the time -being I can move up to "regulation of meiotic cel cycle"

but this has quite a loss of information, because this term was used to annotate the "mater regulators which control **entry into the meiotic cell cycle** downstream of stress, cAMP and mating pheromone signalling.

See the big oval in the right-hand panel here:

![signalling for conjugation](https://github.com/geneontology/go-ontology/assets/7359272/ac8dd055-a27c-485c-baaa-084f01c273d6)

So although I think the term label isn't great, I'm not keen on the loss of information either. Any suggestions?

**Comment by ValWood** [comment]
Historically, we wanted this term to be "sexual differentiation" so "sexual differentiation signalling", but this caused problems with how "differentiation" meaning in GO IIRC so we came up with this clunky term and made sexual differentiation an exact synonym.

@edwong57  do you know what budding yeast would use here?

If its a problem, I can just go with "regulation of meiotic cell cycle" and try to figure out the pathways later (It isn't my area of expertise at all!)

**Comment by edwong57** [comment]
@ValWood I'm not positive and can chat with SGD curators this week at TAGC, but if you are trying to capture signaling for mating, then it seems like a lot of the gene products in _S. cerevisiae_ involved in mating are annotated to [GO:0000750](https://amigo.geneontology.org/amigo/term/GO:0000750).

**Comment by ValWood** [comment]
Actually you can go ahead and obsolete. I will manage with the existing g terms. This area is not particularly well-curated at PomBase so when we get to it we can request any terms we think are missing.
v
