### ISSUE TITLE
NTR: [CD27 signaling pathway]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#27080]
Please provide as much information as you can: 

* **Suggested term label:**
CD27 signaling pathway

* **Definition (free text)**
The series of molecular signals initiated by the binding of the cell surface receptor CD27 to its physiological ligand CD70, and ending with the regulation of a downstream cellular process, e.g. transcription.

* **Reference, in format PMID:#######**
(REQUIRED)
PubMed:8387892, PMID: 26359318

* **Gene product name and ID to be annotated to this term**
CD27,  CD70...

* **Parent term(s)**
GO:0007166 cell surface receptor signaling pathway

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by addiehl** [comment]
No, the [tumor necrosis factor receptor superfamily (TNFRSF)](https://en.wikipedia.org/wiki/TNF_receptor_superfamily) is a large family of structurally similar proteins, for which the tumor necrosis factor receptor signaling pathway is just a prototype that is activated by a particular protein known as tumor necrosis factor (which itself is [a member of a superfamily](https://en.wikipedia.org/wiki/Tumor_necrosis_factor_superfamily)). It would be a misrepresentation of the biology to conflate the CD27 signaling pathway with the TNF signaling pathway, because there are completely separate receptor ligand pairs expressed in different cell types with different biological outcomes.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160162
+name: CD27 signaling pathway
+namespace: biological_process
+def: "The series of molecular signals initiated by the binding of the cell surface receptor CD27 to its physiological ligand CD70, and ending with the regulation of a downstream cellular process, e.g. transcription." [PMID:26359318, PMID:8387892]
+is_a: GO:0007166 ! cell surface receptor signaling pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27080" xsd:anyURI
+created_by: rynl
+creation_date: 2024-02-21T21:43:14Z
