### ISSUE TITLE
Obsoletion request: organomercury terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27153]
Dear all, 

The proposal has been made to obsolete the following terms: 

GO:0015548 organomercurial transmembrane transporter activity > 0 annotations; paper describes neutral amino acid transporter 
GO:0015897 organomercurial transport > same paper as above
GO:0018941 organomercury metabolic process
GO:0042191 methylmercury metabolic process
GO:0046414 organomercury biosynthetic process
GO:0046413 organomercury catabolic process
GO:0046412 phenylmercury acetate metabolic process 
GO:0018942 organometal metabolic process
GO:0018943 organotin metabolic process 

The reason for obsoletion is that there is no evidence that these processes are physiologically relevant. There are no annotations to these terms; these terms are not present in any subsets. 

You can comment on the ticket: 

Thanks, Pascale

**Comment by raymond91125** [comment]
From go-helpdesk

Greetings.

GO seems to have decided that GO:0042192   (methylmercury biosynthetic process)  should be made obsolete because

“there is no evidence for its physiological relevance.”

There is STRONG evidence, from bioinformatics, for its relevance.  

Many bacteria are sensitive to methylmercury.  They cleave it (using MerB), then run an efflux system to get rid of the mercury ion.

But it appears some bacteria are sensitive to mercury ion, and less sensitive to methylmercury.  For them, biosynthesis of methylmercury from mercury is likely to be a form of detoxification.   

Mercury is poisonous because its affinity for sulfur can mean destruction of cysteine active site residues in enzymes. But mercury has a dramatically greater affinity for selenocysteine.   In humans, selenoprotein P is protective against mercury poisoning, and it has something like 15 selenocysteines.

The HgcA and HgcB  gene pair  piggybacks  on the pathway of acetogenesis, which involves a methyl carrier.   HgcA and HgcB have been shown to be the specific gene pair for methylmercury biosynthesis.   It turns out that every bacterium that encodes HgcA and HgcB  encodes  multiple selenoproteins.    In most cases, a several of their selenoproteins act in Stickland metabolism, which enables amino acid fermentation is extremely anaerobic conditions.  Key components of the process are selenoprotein-containing glycine reductase and proline reductase complexes.     

How do we know that methylmercury biosynthesis is the physiological purpose of the HgcAB gene pair?  First of all, no other role has been suggested.  Second, in a discovery I made, it turns out that both HgcA  (in about 70% of species) and HgcB (in about 6% of species) are themselves selenoproteins!    It appears that CU (cysteine-selenocysteine) motifs, rare in selenoproteins, are relatively common in operons that contain a MerB  (organomercurial lysase) family proteins. 

Whether or no GO is inclined to believe that HgcA and HgcB are performing a function beneficial to the host bacterium, it is most definitely a biosynthetic process.  It is one of several related organomercurial biosynthetic processes.   Another is the biosynthesis of  dimethylmercury (although the responsible species and proteins are not yet described).     I infer there are others, because a number of different organomercurial lyases are known, with different specificities.  Known activity on several organomercurial compounds, suggesting there may be still unknown    organomercurials being produced in some still poorly studied environments.

Mercury is rare among metals in being able to form a covalent bond to carbon  (and not just some kind of ionic-bonded salt).    Cobalt is another.  The term “organometallic” is useful for that reason.   GO:0018942,  now made obsolete, is  "organometal metabolic process".     I guess its only child what methylmercury metabolic process. 

As I explain in[ https://pmc.ncbi.nlm.nih.gov/articles/PMC9879109/](https://pmc.ncbi.nlm.nih.gov/articles/PMC9879109/),    an article primarily about an 8-gene operon in which 6 of the proteins can be observed as selenoproteins,  the bioinformatic evidence, including the presence of a MerB-like protein with a CU motif, suggests the existence of a still uncharacterized world the formation and the breaking of covalent bonds between carbon and a heavy metal atom (mercury or something else), with physiological relevance and with more compounds involved than just (mono)methyl and dimethyl mercury.

I request that you restore the GO term GO:0018942,  which I had attached to 11 different protein families used in our annotation pipeline.  And GO:0042192.  Since apparently methylmercury is formed by the cell as a means of mercury detoxification system in order to product selenocysteine-dependent anaerobic fermentation processes that the cell requires to live.

Many thanks,

Daniel Haft

Staff Scientist

NCBI

**Comment by raymond91125** [comment]
PMID:23393089 The genetic basis for bacterial mercury methylation

**Comment by pgaudet** [comment]
We'd like to review the biology of this.

**Comment by pgaudet** [comment]
Email discussion: 

Pascale: 
> With respect to the papers you cite for the organomercury terms, the discussion that GO editors had at our last meeting was regarding whether 'methylmercury biosynthetic process’ was physiologically relevant, especially given its definition, "The chemical reactions and pathways resulting in the formation of methylmercury (MeHg+), a highly toxic organometal.”; it doesn’t sound like some compound that would has a physiological role. 

> Instead, this seems to be a pathway to detoxify inorganic mercury, and it seems more appropriate to create a term under ‘cellular detoxification’. Right now we have a general term that captures mercury detoxification, "GO:0050787 detoxification of mercury ion”. Admittedly this branch is quite shallow and does not explain the mechanisms of detoxification - we just haven’t dedicated much resources to this part of GO (yet), but it would be great to so do. As far as I know, detoxification can take place via export (which sometimes requires a chemical modification, as in the case of mercury here), there is also sequestration inside the cell, or conversion to an non-toxic compound. Would a term like this better capture the biology than 'methylmercury biosynthetic process’? 

Daniel
> I’m sympathetic to those expressing suspicion about methylmercury biosynthesis as a biological process. 

 >Still, I feel that what the HgcA/HgcB gene pair  (the first usually and second occasionally containing a rare selenocysteine residue)   needs a GO process term more specific than mercury detoxification.    If it could be shown that detoxification is a biological reason in bacteria with the process, then fine, methylmercury biosynthesis could have detoxification as one of its parents.

> However, I hate the idea that the biosynthesis of mercury has to disappear as a GO term because we don’t see an obvious reason other than detox.  In fact, a pathway often has two purposes.  It might both protect  HgcAB-containing bacteria and intentionally suppress growth of rival bacteria.  If methylmercury is poisonous to other bacteria  (and I think it is, because there are systems to degrade it and export the Hg),  but not to the producer, well, then there it is.   A toxic natural product is made at least in part for its adverse effects on competitors, and that’s all that’s needed.

> Dimethymercury also is biosynthesized.  By unknown enzymes of unknown species.    If it, too, targets rival species,  then methylmercury gets a friend.

 > For what it’s worth, I’m planning on making some more contributions in the near term.    I hope to earn this one special dispensation.

**Comment by pgaudet** [comment]
Hi @danielhhaft 

Looking at the GO definition (and some other papers), I am not sure anymore that detoxification is correct - GO states that MeHg+ is a a highly toxic organometal. Maybe there is no better parent for now.

**Comment by pgaudet** [comment]
Added comment: to [methylmercury biosynthetic process](http://purl.obolibrary.org/obo/GO_0042192)

> Note that there is no unequivocal evidence supporting a specific physiological role for the reaction leading to the synthesis of methylmercury. It may be a defense molecule, or serve to detoxify mercury. Once the physiological role is understood, this term will likely be obsoleted.

@danielhhaft @ValWood 


Thanks, Pascale
