### ISSUE TITLE
CD8+ T cell homeostasis

### ISSUE THREAD

**Issue by CP-SB** [geneontology/go-ontology#27184]
Please provide as much information as you can: 

* **Suggested term label:**

* **CD8+ T cell homeostasis maintained by immunoproteasomes and thymoproteasomes derived from medullary and cortical thymic epithelial cells, respectively. The proteasomes specifically act on CD8+ and not CD4+ which is why the parent term T cell homeostasis is too general**

* **Reference, in format PMID: 33815406, 30650357**

* **Parent term: T cell homeostasis (GO:0043029)**

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by addiehl** [comment]
This is a good new term.  I suggest using a definition similar to the parent term:
"The process of regulating the proliferation and elimination of CD8-positive alpha-beta T cells such that the total number of T cells within a whole or part of an organism is stable over time in the absence of an outside stimulus."

I also suggest using the full Cell Ontology derived cell type name for this term:
CD8-positive, alpha-beta T cell homeostasis
with synonyms
CD8+ T cell homeostasis (broad)
CD8-positive T cell homeostasis (broad)

The reason is that a subset of gamma-delta T cells are CD8, but the papers you cite are really about alpha-beta T cells.

I would argue we should also make a similar 'CD4-positive, alpha-beta T cell homeostasis' at the  same time using the same parent, a similar definition, and similar synonyms, and using [PMID:38329813](https://pubmed.ncbi.nlm.nih.gov/38329813/) as a reference.

Thanks, Alex

**Comment by CP-SB** [comment]
Hi Alex, thank you for responding to my term request. I agree with your suggestions for the term definitions and cell-type names. I support your suggestion for making a new term for 'CD4-positive, alpha-beta T cell homeostasis'.

This is my first term request - do I need to follow-up with anything else? Thanks again.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160165
+name: CD8-positive, alpha-beta T cell homeostasis
+namespace: biological_process
+def: "The process of regulating the proliferation and elimination of CD8-positi
ve alpha-beta T cells such that the total number of CD8-positive alpha-beta T ce
lls within a whole or part of an organism is stable over time in the absence of 
an outside stimulus." [PMID:30650357, PMID:33815406]
+synonym: "CD8+ T cell homeostasis" BROAD []
+synonym: "CD8-positive T cell homeostasis" BROAD []
+intersection_of: GO:0048872 ! homeostasis of number of cells
+intersection_of: acts_on_population_of CL:0000625 ! CD8-positive, alpha-beta T 
cell
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/
issues/27184" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-04T23:49:25Z

**Comment by raymond91125** [comment]
Thanks. If it's OK I think we could create 'CD4-positive, alpha-beta T cell homeostasis' when there is an immediate need for annotations.
