### ISSUE TITLE
Non-descriptive terms need "do not annotate" tag

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#27254]
From the inferred annotations in the SGD load, the following terms need the DO_NOT_ANNOTATE tag same as https://github.com/geneontology/go-ontology/issues/27054#issuecomment-1964704962

- [ ] GO:0042918 	alkanesulfonate transport' 	
- [ ] GO:0042959 	alkanesulfonate transmembrane transporter activity' 	
- [x] GO:0061425 	positive regulation of ethanol catabolic process by positive regulation of transcription from RNA polymerase II promoter 	
- [ ] GO:0071705 	nitrogen compound transport 	
- [ ] GO:0072337 	modified amino acid transport 	
- [ ] GO:1900068 	negative regulation of cellular response to alkaline pH 	
- [ ] GO:1900070 	negative regulation of cellular hyperosmotic salinity response 	
- [ ] GO:1900072 	positive regulation of sulfite transport 	
- [ ] GO:1903047 	mitotic cell cycle process

**Comment by pgaudet** [comment]
Obsolete GO:0061425 positive regulation of ethanol catabolic process by positive regulation of transcription from RNA polymerase II promoter as part of tx refactoring https://github.com/geneontology/go-ontology/issues/12739

**Comment by ValWood** [comment]
I'll try to do all the do_no_annotate tickets with ontobot tomorrow

**Comment by ValWood** [comment]
This didn't work? at least I don't see the do not annotate subset on GO:0042918 alkanesulfonate transport'

Also I was wondering about  adding to 
 GO:1900068 negative regulation of cellular response to alkaline pH
 GO:1900070 negative regulation of cellular hyperosmotic salinity response
 GO:1900072 positive regulation of sulfite transport

these are leaf node terms, if we don't want them to be used, presumably they should be obsoleted, not blocked?

**Comment by pgaudet** [comment]
Hi Val, 

Yes leaf terms should not have 'do not annotate'. But are these terms used for annotation? ('regulation of response' is quite dubious, but we need to also focus on the open/ongoing projects, this can be done at a later point.)

Here we should try to figure out why SGD is getting inferences, it may be a weird parent ? 

I noticed GO:0042918 alkanesulfonate transport' was used for annotation, did you check that the annotation could be replaced? 

Thanks, Pascale

**Comment by ValWood** [comment]
I didn't see any direct annotations to  GO:0042918 alkanesulfonate transport' in QuickGO, but  I  dodn't check thoroughly  becuuse I  thought you had approved, but now I see it was me doing the thumbs up! 

This raises a problem though- if these were a response to  incorrect inferred annotations. 
We can't  block terms only because  of an annotation transfer violation.
@suzialeksander  in these cases you need to report the specific  violations on the curation tracker:
https://github.com/geneontology/go-annotation/issues

The fix will need to be either
i) inference pipeline fix
ii) underlying annotation fix
iii) taxon restriction
or
iv) obsoletion

I agree that 
 GO:0071705 nitrogen compound transport
 GO:0072337 modified amino acid transport
seem general enough to be blocked, so I will check how many annotations would be affected by these additions.
