### ISSUE TITLE
Fix label and definition GO:0006307 DNA dealkylation involved in DNA repair 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27258]
**With @colinlog we have modified this term** rather than obsoleting it 

DNA dealkylation involved in DNA repair 

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  ~The reason for obsoletion is that this term is pre-composed and should be represented as a GO-CAM model.~

**Comment by pgaudet** [comment]
Changed label to "DNA alkylation repair"
and change definition to "The repair of alkylation damage in DNA, e.g. the removal of a non-physiological alkyl group from a nucleobase. This is usually mediated by DNA alkyltransferases." 

+ moved under DNA repair, as this is a DNA repair mechanism (instead of 'part of DNA repair)

Thanks, Pascale

**Comment by ValWood** [comment]
did you notice that
GO:0035552 oxidative single-stranded DNA demethylation
is under DNA alkylation?
That looks wrong?

**Comment by ValWood** [comment]
I just spotted it here:
https://www.pombase.org/term/GO:0035510

**Comment by pgaudet** [comment]
> did you notice that
GO:0035552 oxidative single-stranded DNA demethylation
is under DNA alkylation?

Methylation is a type of alkylation
But this term is now obsolete

**Comment by ValWood** [comment]
Of course!
