### ISSUE TITLE
Fix label and definition: cytolysis by symbiont of host cells and killing by symbiont of host cells

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27342]
GO:0001897 cytolysis by symbiont of host cells
- change label to 'symbiont-mediated cytolysis of host cell'
 - change definition from  "The killing by an organism of a cell in its host organism by means of the
 rupture of cell membranes and the loss of cytoplasm. The host is defined as the larger of the organisms involved in a symbiotic interaction." to  "A process mediated by a symbiont that results in the death of a host cell by means of the rupture of cell membranes and the loss of cytoplasm. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:add]

 id: GO:0001907 killing by symbiont of host cells
- change label to 'symbiont-mediated killing of host cell'
 - change definition from  "Any process mediated by an organism that results in the death of cells in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction." to  "A process mediated by a symbiont that results in the death of a cell in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:add]

Thanks, Pascale

**Comment by pgaudet** [comment]
@genegodbold can you please provide references?

**Comment by genegodbold** [comment]
**Symbiont-mediated cytolysis of host cells**: bacterial factors
- **Aerolysin** from _Aeromonas hydrophila_ is a pore-forming toxin with a median lethal dose in mice of 10 micrograms/kg. It causes hemolysis in several species and is cytotoxic toward a range of cell types [PMID:15258571]. Aerolysin is a pore-forming toxin secreted by the bacterium as a water-soluble protein. After binding target host cell receptors and, following proteolytic activation, aerolysin forms circular heptameric oligomers that insert into the plasma membrane thus permeabilizing it. Aerolysin is a beta-PFT, meaning that the pore spans the membrane in the form of a beta-barrel [PMID:7510043]. Cryo-EM structures of the aerolysin pore have been obtained [PMID:27405240].
- **HBL enterotoxin** from _Bacillus cereus_: HBL is composed of the B, L1 and L2 subunits. All three components bind to a host cell membrane independently [PMID:18175317]. After the three components of the hemolytic toxin bind to the host cell membrane independently, they form a complex which then forms a pore [PMID:8995253]. It is only toxic as a ternary complex; none of the individual components is toxic by itself. The tripartite toxin is cytotoxic, dermonecrotic, and can permeabilize blood vessels [PMID:7591080]. The B component is the most important for cytotoxicity [PMID:31137585]. Pore formation by HBL is achieved by stepwise, ordered binding of single components rather than simultaneous binding of multiple components [PMID:24204713].
- **Alpha toxin** from _Clostridium septicum_: Alpha toxin is both hemolytic and lethal. The median lethal dose in mice is approximately 10 micrograms/kg of bodyweight. Proteolytic activation of alpha toxin is required for its toxicity. The 45 residue C terminal propeptide, which is distinct from the previously cleaved signal peptide, inhibits oligomerization of the subunits to form the pore. After cleavage, the propeptide is not displaced from the subunits until they begin to oligomerize. Pore formation requires six or seven monomers [PMID:11423190]. Pore formation by alpha toxin causes an influx of extracellular calcium which lead to: (1) activation of the host calpain-cathepsin pathway, (2) disruption of host lysosomal and mitochondrial integrity, (3) reactive-oxygen species (ROS) production and (4) HMGB-1 nuclear translocation, all of which eventually conspire to induce cellular oncosis of the intoxicated cell [PMID:19284973]. 
- Cereolysin O (CLO) from _Bacillus cereus_ is nearly identical to anthrolysin O from Bacillus anthracis. CLO is a cholesterol-dependent cytolysin, a group of pore-forming proteins with a highly conserved tryptophan-rich sequence (ECTGLAWEWWR) of 11 residues close to the C-terminus, which participates in the binding of some CDCs to cholesterol-rich membranes. These proteins disrupt host cell membrane by forming pores up to 30 nanometers in diameter [PMID:23748204]. 

**Killing by symbiont of host cells**: bacterial factors
- **Pseudomonas exotoxin A** (PEA; ExoA; ETA) from _Pseudomonas aeruginosa_: After endosomal acidification, the translocation domain of the toxin mediates the transfer of the catalytic domain into the cytosol which ADP-ribosylates host elongation factor 2 (EF2), part of the protein translation machinery, thereby inhibiting protein synthesis and killing the cell [PMID:11123917]. The median lethal dose for ExoA toxin is 0.2 microgram/kg when administered intraperitoneally to a mouse. It has a similar mechanism of action to diptheria toxin and is among the more toxic proteins known [PMID:16406634].
- **Alpha toxin** of _Clostridium perfringens_ is a phospholipase C preferentially active toward sphingomyelin and phosphatidylcholine. It mediates development of gas gangrene. Cell death is accompanied by damage to the host lysosomes [PMID:26633512].
- **Certhrax toxin** from _Bacillus cereus_ is an ADP-ribosyltransferase that binds to NAD+ to cleave it into ADP-ribose and nicotinamide. This ADP-ribose is then transferred to its target host cell protein where it either alters or inhibits cellular activity. Certhrax is 60 fold more toxic than lethal factor from Bacillus anthracis against a mouse macrophage cell line [PMID:22992735].
- **Cholix toxin** from _Vibrio cholera_ transfers an ADP-ribose moiety from NAD to the eukaryotic ribosomal elongation factor 2 (EF-2), preventing translation from that ribosome [PMID:25494717]. The median lethal dose for ChxA in mice is 0.5 mg/kg. The three domains of cholix toxin are responsible for (i) receptor binding (ii) catalysis and (iii)  translocation into the cell [PMID:23230295].
