### ISSUE TITLE
Clarify SOP for sources of definitions for reaction terms

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27568]
Questions from @pgaudet 
> Is there a preference whether we add the EC or RHEA ID as the def xref?

proposal:

> The definition xref should describe the source of the definition. If RHEA and EC are the same, use RHEA. In cases where the definition is too divergent from RHEA, then use the appropriate source: EC, or a PMID.
( I usually do not keep both, but I noticed Raymond keeps both.)

Agreed, in all cases the definition should reflect the provenance. If we get from EC, then use the EC. If we get from RHEA, use the RHEA. If a curator altered this via their own interpretation, then use the curator in addition to the sources they used.

These should be universal rules for all terms in all ontologies.

> Is there a need/desire to preserve def xrefs like "[GOC:pz]" if the revised def is based solely on EC/RHEA?
> If we change the definition, then we should remove the GOC:curator xref, since they are not the source anymore.

I would assume if a curator xref is there then they did something other than copy the text over, and we should keep it. That assumption may not universally hold but I don't think there is a priority to go back and remove these now.

Carried on from:

_Originally posted by @pgaudet in https://github.com/geneontology/go-ontology/issues/27560#issuecomment-2048042201_

https://wiki.geneontology.org/Guidelines_for_GO_textual_definitions

I added this to the next ontology call to get some clarification.

**Comment by pgaudet** [comment]
@cmungall and I went over this together. For enzymes: 

1. If there is a RHEA that is an exact match to the GO term, use the RHEA definition and use RHEA as the definition cross-reference. 
2. If there RHEA is broader and the EC corresponds to the GO term, use the EC definition(see note 1)  and EC as the definition cross-reference. 
3. If neither match, use a PMID.
4. If the activity is not describe neither in RHEA not in EC, it may be appropriate to use another source, such as MetaCyc, UM_BBD, but these cases should be rare.


Notes: 
1. EC definitions must be edited: 
1.1 in GO, we use `=`rather than `<=>`or other notations
1.2 In GO, we dont wrap charges in parentheses (see also https://wiki.geneontology.org/Guidelines_for_GO_textual_definitions#Guidelines_on_chemical_nomenclature) 
2. The definition cress-reference should usually contain a single database source; otherwise it is ambiguous which source was used.
3. If a curator modified the definition significantly, they should also add themselves as definition cross-reference (GOC:initials as described in https://github.com/geneontology/go-site/blob/master/metadata/users.yaml)

**Comment by sjm41** [comment]
And for the case where we replace/update an existing enzyme definition that has a 'GOC:initials' xref with a new definition that **exactly** matches the RHEA/EC, then I'd say we should remove the old 'GOC:initials' and just have the RHEA or EC def xref.
Would you agree?

**Comment by pgaudet** [comment]
@sjm41 Let's discuss this on the ontology call tomorrrow.

**Comment by pgaudet** [comment]
I also propose we dont keep general textbook references, as these are almost untraceable, even if you know the edition (for eg 
https://isbnsearch.org/isbn/0201090910 in [fructose-1-phosphate aldolase activity](http://purl.obolibrary.org/obo/GO_0061609)

**Comment by deustp01** [comment]
> as these are almost untraceable,

But sources like Wikipedia that are freely editable provide an illusion of traceability - yes, that definition has a stable URL but that URL can point to a convoluted history of edits whose changes to the meaning of the definition can be complicated and hard to sort out, and may well lead ultimately back to that textbook. This is not an argument against Wikipedia, only a doubt about the possibility of coming up with sources that are truly transparent, stable, and accessible. Sorry, this is a tangent to the basic plan spelled out above, which looks like a plausible way to minimize disorder.

**Comment by pgaudet** [comment]
Updated https://wiki.geneontology.org/Guidelines_for_GO_textual_definitions#Cross-references_for_definitions

@raymond91105 @deustp01 @ValWood @sjm41 @cmungall @thomaspd 

Feedback is welcome!

**Comment by raymond91125** [comment]
Sometimes it's difficult to find a better worded definition than wiki's.
Should we adopt version-specific Wiki reference practice? If so, what is the format, Wikipedia:Endocytosis&oldid=1210084552?
