### ISSUE TITLE
NTR: [Secretory autophagy]

### ISSUE THREAD

**Issue by MariaLivia** [geneontology/go-ontology#27757]
Please provide as much information as you can: 

* **Suggested term label:**
* Secretory autophagy

* **Definition (free text)**
* Non-lytic type of autophagy in which the autophagic machinery leads to secretion/expulsion of cytoplasmic constituents instead of their degradation. 

* **Reference, in format PMID:#######**
PMID:25988755
PMID:38534758

* **Gene product name and ID to be annotated to this term**
APOLD1 (PMID: 35638551)

* **Parent term(s)**
GO:0006914 Autophagy

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by MariaLivia** [comment]
Hi,
any news about this term request? I see there is no assignee.

**Comment by pgaudet** [comment]
Thanks for the reminder ! I meant to ask @marcfeuermann about this; was this omitted on purpose during the autophagy refactoring ? Or it this missing and should be added?

**Comment by marcfeuermann** [comment]
Hello,
I've never heard of the term until now, and I've never seen it mentioned in any major article on autophagy. As far as I'm concerned, it's rather odd because in autophagy there's "phagy", i.e. degradation. For me, it's clearly another process. Secretory autophagy is a form of unconventional protein secretion that uses the autophagy machinery. So, as far as the ontology is concerned, this should be classified as a secretion process, and not as an autophagy sub-process. 
I hope this will help.
Best regards,
Marc.

**Comment by marcfeuermann** [comment]
In fact the problem comes from the term "secretory autophagy" itself which is nonsense. I would rather call this something like "autophagosome-dependent secretion" or "autophagosome-mediated secretion", and add "secretory autophagy" as a synonym. The emphasis would be on secretion.
Also we could make a more appropriate definition:
"Unconventional secretion pathway that uses the autophagy machinery to facilitate secretion of the cytosolic cargo such as leaderless cytosolic proteins which cannot enter the conventional secretory pathway operating via the endoplasmic reticulum and the Golgi apparatus."
Like that it would fit well as a child of "secretion".
Marc.

**Comment by MariaLivia** [comment]
Perfectly in agreement with Marc.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160192
+name: autophagosome-dependent secretion
+namespace: biological_process
+def: "A process of exocytosis that uses the autophagy machinery to facilitate secretion of the cytosolic cargo such as leaderless cytosolic proteins which cannot enter the conventional secretory pathway operating via the endoplasmic reticulum and the Golgi apparatus." [PMID:25988755, PMID:38534758]
+synonym: "autophagy-dependent secretion" EXACT []
+synonym: "secretory autophagy" EXACT []
+intersection_of: GO:0006887 ! exocytosis
+intersection_of: has_primary_input GO:0005776 ! autophagosome
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27757" xsd:anyURI
+created_by: rynl
+creation_date: 2024-07-03T16:58:30Z

**Comment by MariaLivia** [comment]
Great, thank you !
