### ISSUE TITLE
Textual definition update:  hydroxymethylglutaryl-CoA reductase (NADPH) activity (GO:0004420) (Hmg1)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27769]
* **GO term ID and label for which you request a definition update**

hydroxymethylglutaryl-CoA reductase (NADPH) activity (GO:0004420)

shouldn't this be bidirectional in the opposite direction to presented  
(does the mevalonate pathway operate in the reverse direction ? I don't see any evidence)

Catalysis of the reaction: (R)-mevalonate + CoA + 2 NADP+ = (S)-3-hydroxy-3-methylglutaryl-CoA + 2 H+ + 2 NADPH. [[PMID:29224355](http://www.ncbi.nlm.nih.gov/pubmed/29224355)]

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**

* **Reference(s)**
PMID:nnnnnnn

* **Additional information**

**Comment by pgaudet** [comment]
Hi @ValWood 
We write the reactions in the same way as RHEA/EC. In this case you can see in RHEA that most proteins catalyze the reverse reaction: https://www.rhea-db.org/rhea/15989

Reactions are represented in the standard IUBMB way, as described here: https://iubmb.qmul.ac.uk/enzyme/rules.html

Specifically (since this is a long document): 

> One important extension of this principle is the question of the direction in which the reaction is written for the purposes of classification. To simplify the classification, the direction chosen should be the same for all enzymes in a given class, even if this direction has not been demonstrated for all. Thus the systematic names, on which the classification and code numbers are based, may be derived from a written reaction, even though only the reverse of this has been actually demonstrated experimentally. In the list in this volume, the reaction is written to illustrate the classification, i.e. in the direction described by the systematic name. However, the common name may be based on either direction of reaction, and is often based on the presumed physiological direction.


So, please do not change the reaction. You can add a comment staitng that this reaction proceeds in the opposite direction.

**Comment by ValWood** [comment]
OK! I never knew that...
