### ISSUE TITLE
NTR: symbiont-mediated suppression of host complement activation by recruitment of host proteases

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27788]
NTR: symbiont-mediated suppression of host complement activation by recruitment of host proteases

For GO-PathGO alignment

@genegodbold to provide references

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141203
+name: symbiont-mediated suppression of host complement activation by recruitment of host proteases
+namespace: biological_process
+def: "A process by which a symbiont prevents host complement activation by recruiting host proteases, destroying the complement before it has its effect on the symbiont." [GOC:pg]
+is_a: GO:0042784 ! symbiont-mediated suppression of host complement activation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27788" xsd:anyURI
+created_by: pg
+creation_date: 2024-04-30T13:17:35Z

**Comment by pgaudet** [comment]
PR is here: https://github.com/geneontology/go-ontology/pull/27789

**Comment by genegodbold** [comment]
Hey @pgaudet I'd like to make a correction to the title: instead of "recruitment", can this be changed to "activation"? See staphylokinase

- **Staphylokinase from Staphylococcus aureus**: Staphylokinase is secreted by S_aureus and it activates human plasminogen into plasmin. SAK is anti-opsonic, inhibiting S_aureus from being phagocytosed by host neutrophils in vitro. S_aureus has several plasminogen-binding receptors at the cell surface which bind host plasminogen.  **Surface bound plasminogen can be activated into the active plasmin protease by SAK** on the surface of the bacterium.  This allows the surface-bound plasmin to cleave both immunoglobulin G (IgG) and the complement proteins C3b and C3bi, thus inhibiting bacterial destruction by complement. Thus SAK activation of bacteria-bound host plasminogen to plasmin on the bacterial surface protects the bacterium from host defenses [PMID:15792635].
- **M protein from Streptococcus**: Fibrils of M protein form a dense, covalently attached coat on the streptococcal surface blocking the deposition of antibodies and complement [PMID:18323455]. Human factor H is recruited to the streptococcal surface by PAM along with human plasminogen/ plasmin. These contribute to the degradation of the opsonin human C3b to its inactive product (iC3b), protecting the bacterium from phagocytosis. Factor H and factor I cleave C3b while plasmin cuts iC3b into smaller peptides [PMID:26945067].
- **Endopeptidase O (PepO; Neprilysin) from Streptococcus suis**: Host plasminogen bound to SsPepO can be converted to plasmin via proteolysis by host uPA and can then degrade host complement C3b and enabling the control of complement activation. A bacterial mutant lacking PepO has impaired adherence to plasminogen, invasion of rat brain microvessel endothelial cells, and is efficiently killed by human serum and blood [PMID:34305859].
