### ISSUE TITLE
Obsoletion request: GO:1900274 regulation of phospholipase C activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27854]
GO:1900274 regulation of phospholipase C activity
- GO:1900275 negative regulation of phospholipase C activity
- GO:0010863 positive regulation of phospholipase C activity
- GO:0007202 activation of phospholipase C activity

These represent molecular functions, and should probably be replaced by the appropriate signaling pathway. 

New terms have been created in #27845 
GO:0160185 phospholipase C activator activity
GO:0160186 phospholipase C inhibitor activity

**Comment by RLovering** [comment]
Hi

are you going to create the phospholipase A2 term: phospholipase A2-activating G protein-coupled receptor signaling pathway

so that positive regulation of phospholipase A2 activity annotations can be changed to the signaling pathway term?

As is the case for 	
positive regulation of phospholipase C activity annotations changing to phospholipase C-activating G protein-coupled receptor signaling pathway

Thanks

Ruth

**Comment by pgaudet** [comment]
Thanks for the question @RLovering 

I opened a new ticket for this: https://github.com/geneontology/go-ontology/issues/28033
