### ISSUE TITLE
 GO:2000311 - regulation of AMPA receptor activity

### ISSUE THREAD

**Issue by CP-SB** [geneontology/go-ontology#28028]
Hi, Hope you can help. Is there an alternative for this?  e.g regulation of AMPA receptor availability? Thanks

Relevant publication: PMID: 37228199

**Comment by pgaudet** [comment]
Hi @CP-SB 

Can you clarify your request? Which gene are you annotating from this paper? 


Thanks, Pascale

**Comment by pgaudet** [comment]
Thank you for the clarification. It doesn't seem like the 19S regulatory particle directly regulate the receptor activity (otherwise, I would have suggested [neurotransmitter receptor regulator activity](http://purl.obolibrary.org/obo/GO_0099602))

I see in the paper that the proposed mechanism of action is 
> Because surface AMPARs are endocytosed at sites distant from synapses ([39](https://www.science.org/doi/10.1126/science.adf2018?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed#core-R39)), it thus appears that the free 19S subcomplex stabilizes the (presumably synaptic) clustering of surface AMPARs and yet facilitates their internalization once they diffuse away. Once internalized, the free 19S subcomplex then stabilizes the reserve pool of AMPARs, preventing them from degradation. In addition, we found that free 19S facilitated AMPAR exocytosis, providing an alternative to their degradation fate (fig. S10D). These results demonstrate that proteasome-independent 19S DUB activity regulates AMPARs at multiple trafficking points, and all of these actions work together to maximize receptor availability at synapses

Do any of these terms work: 
- [protein stabilization](http://purl.obolibrary.org/obo/GO_0050821)
- [negative regulation of proteasomal ubiquitin-dependent protein catabolic process](http://purl.obolibrary.org/obo/GO_0032435)

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi again @CP-SB 
I discussed this paper with @vanaukenk and it seems like the exact mechanism by which the S19 subcomplex is regulating the AMPA receptor is unknown. The term you proposed to create, "regulation of AMPA receptor availability", seem to be what we call a read-out (see some annotation documentation here: https://wiki.geneontology.org/Tips_to_Produce_High_Quality_Annotations#Capture_the_conclusion,_not_the_assay). 

There may be other terms - but it seems like the data doesn't really show that: 
GO:0099637 neurotransmitter receptor transport
GO:0035418 protein localization to synapse

And/or you could use a more general term about  "synaptic function". 

Thanks, Pascale

**Comment by ValWood** [comment]
Closing as "regulation of activity" is out of scope for biological process.

Please reopen if you need an alternative term
