### ISSUE TITLE
NTR: response to queuine

### ISSUE THREAD

**Issue by rjdodson** [geneontology/go-ontology#28201]
Please provide as much information as you can: 

* **Suggested term label:** 
response to queuine

* **Definition (free text)**
Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a queuine stimulus.

* **Reference, in format PMID:#######**
PMID: 26424849

* **Gene product name and ID to be annotated to this term**
DNA (cytosine-5)-methyltransferase
Q54JH6

* **Parent term(s)**
GO:0010243
response to organonitrogen compound

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
CHEBI:17433

**Comment by pgaudet** [comment]
Hi @rjdodson , 

How are you ? 

The biology shown in this paper could be captured more precisely than with a 'response' term; in fact, the paper doesn’t demonstrate that there is a biological program for the organism or cell to respond to Q as a stimulus, so the requested term does not fit the definition of a BP. 

Instead, queuosine (Q) modification of the substrate tRNA enhances the activity of the methyltransferase, not free queuosine, so that PTM modification may be essential for the methylase to be able to recognize the substrate.

The paper also mentions that "queuine-stimulated in vivo methylation was abrogated by the absence of the enzyme that inserts queuine into tRNA? 
 
In GO-CAM we would capture this as the queuosine modifying enzyme _directly provides input for_ the methlytransferase; but the overall process is still tRNA modification. So for standard annotation, I suggest you use some 'tRNA modification' term. If you need help making a GO-CAM please let me know. 

Thanks, Pascale

**Comment by rjdodson** [comment]
Hi Pascale:

Okay, agreed that this is not an appropriate NTR. And thank you for clarifying the biology described here. 

I am fine-the major change for me is that both of my children are now grown and have left home, so I am a somewhat lonely empty-nester these days!

I hope all is well with you in Switzerland!
Bob

**Comment by pgaudet** [comment]
Sounds good. 

Time flies !!! :)
