### ISSUE TITLE
Glycogen/starch synthase MF terms (obsolete and name updates)

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28271]
There are these 4 GO terms that describe the function of glycogen/starch synthase.

GO:0004373 glycogen (starch) synthase activity 
EC: 2.4.1.11
UDP-glucose precursor

GO:0009011 starch synthase activity
EC:2.4.1.21
ADP-glucose precursor

GO:0033840
NDP-glucose-starch glucosyltransferase activity
EC:2.4.1.242

GO:0102502
ADP-glucose-starch glucosyltransferase activity
EC:2.4.1.242

Most mammals, fungi use UDP-glucose as a precursor while bacteria and plants use ADP-glucose.
Some plant enzymes can use both.

Proposition to simplify/clarify the GO terms:

- Obsolete GO:0102502 which is covered by GO:0009011 (no manual annotations) 

- change the name of the GO terms
GO:0004373 glycogen (starch) synthase activity  -> glycogen (starch) synthase (UDP-glucose) activity 
GO:0009011 starch synthase activity -> glycogen (starch) synthase (ADP-glucose) activity 
GO:0033840 NDP-glucose-starch glucosyltransferase activity -> glycogen (starch) synthase (NDP-glucose) activity

**Comment by raymond91125** [comment]
To clarify,
1. Shouldn't the merge be GO:0102502 ADP-glucose-starch glucosyltransferase activity -> GO:0033840 NDP-glucose-starch glucosyltransferase activity (as they both referenced EC:2.4.1.242)?
2. Is it best if we follow the EC accepted names and have the alternative names as synonyms? I do agree that the EC alternative names may be less confusing.

**Comment by pgaudet** [comment]
Hi @raymond91125 

Thanks for asking for confirmation. 
1. Yes the term we 'merge' into should be GO:0033840 NDP-glucose-starch glucosyltransferase activity; EC specifies that the enzymes can use either UDP- or ADP- glucose.
2. We dont need to stick to EC recommended names if they are not clear or consistent with GO practices. It seems like the 'NDP-glucose--starch glucosyltransferase'-type names are clearer; we just need to make sure that all terms are consistent (EC is not in this case).

**Comment by rozaru** [comment]
For point 2:

The 3 EC numbers cover enzymes that add UDP-glucose or ADP-glucose to a chain of glucose units to form either glycogen (mammals, bacteria, fungi) or starch (plants). The difference between glycogen and starch is the type of branching between the glucose units.

For the name, 'NDP-glucose--starch glucosyltransferase' describes better the reaction, although glycogen (starch) synthase are the most used names.

Maybe this could work:
GO:0004373 glycogen (starch) synthase activity -> UDP-glucose-glycogen (starch) glucosyltransferase activity
GO:0009011 starch synthase activity -> ADP-glucose-glycogen (starch) glucosyltransferase activity
GO:0033840 NDP-glucose-starch glucosyltransferase activity ->  no changes

**Comment by raymond91125** [comment]
There is another related term  GO:0033201 alpha-1,4-glucan synthase activity, which reference to EC:2.4.1.21 and RHEA:18189. It should probably be merged into GO:0009011.

**Comment by ValWood** [comment]
Both Pombe papers refer to UDP/ADP

PMID:17472966
Starch and glycogen synthases catalyse biosynthetic reactions in which the substrate UDP-glucose or ADP-glucose is polymerized into linear α(1,4)-glucan. 


Glycogen and starch synthases are glycosyltransferases that catalyze the formation of a (1,4)-α-glucosidic bond and transfer the α-glucose moiety from UDP-glucose or ADP-glucose to the nonreducing end of a pre-existing (1,4)-α-glucan primer.


PMID: 16420355
Glycogen and starch synthases are glycosyltransferases that catalyze the formation of a (1,4)-α-glucosidic bond and transfer the α-glucose moiety from UDP-glucose or ADP-glucose to the nonreducing end of a pre-existing (1,4)-α-glucan primer. 

but PMID: 16420355  also says
In animal and yeast cells, glycogen synthesis is initiated by autoglucosylation of the protein glycogenin, which catalyzes the transfer of glucose residues from UDP-glucose onto one of its tyrosine residues.

These are fungal cell wall alpha glucan synthases, 
i) I woul n't merge it into starch because that is a plant-specific polymer, this term is referring to alpha glycan a fungal cell wall component
ii)   I think the IEA annotations to this term for bacteria and plant might be incorrect  based on the gene product labels.
iii) If this is the case, and this term is specific for the α(1,4)-glucan in fungal cell walls, it could be UDP, so alignment with Rhea would be possible

**Comment by raymond91125** [comment]
Perhaps we could use term names that are more generic like NTP alpha-1,4-glucan glucosyltransferase activity and merge those involved in starch/glcogen/cell wall synthesis.

**Comment by rozaru** [comment]
The suggestion sounds good it would describe the reaction avoiding the mention of the type of final glycan made.

It would be to reorganise the following GO terms:

id: GO:0033201
name: alpha-1,4-glucan synthase activity
id: GO:0004373
name: glycogen (starch) synthase activity
id: GO:0009011
name: starch synthase activity
id: GO:0033840
name: NDP-glucose-starch glucosyltransferase activity
id: GO:0102502
name: ADP-glucose-starch glucosyltransferase activity

into perhaps 3 GO terms for each EC:

**NDP alpha-1,4-glucan glucosyltransferase activity**
Catalysis of the reaction:[(1→4)-α-D-glucosyl](n) + an NDP-α-D-glucose = [(1→4)-α-D-glucosyl](n+1) + a ribonucleoside 5'-diphosphate + H+, where NDP is ADP or UDP.

**UDP alpha-1,4-glucan glucosyltransferase activity**
Catalysis of the reaction:[(1→4)-α-D-glucosyl](n) + UDP-α-D-glucose = [(1→4)-α-D-glucosyl](n+1) +UDP +  H+		

**ADP alpha-1,4-glucan glucosyltransferase activity**
Catalysis of the reaction:[(1→4)-α-D-glucosyl](n) + ADP-α-D-glucose = [(1→4)-α-D-glucosyl](n+1) + ADP + H+	

I am unsure about the NDP at the beginning, it need to be mentioned, but I was wondering if alpha-1,4-glucan glucosyltransferase (NDP-glucose donor) activity would work instead.

**Comment by raymond91125** [comment]
> I am unsure about the NDP at the beginning, it need to be mentioned, but I was wondering if alpha-1,4-glucan glucosyltransferase (NDP-glucose donor) activity would work instead.

Adopted. Thanks.

**Comment by raymond91125** [comment]
The proposal is then merge (obsolete and replaced_by) GO:0033201 alpha-1,4-glucan synthase activity into GO:0033840 alpha-1,4-glucan glucosyltransferase (NDP-glucose donor) activity (note the new term name). @ValWood Is that OK?

**Comment by ValWood** [comment]
Yes, good for me!

**Comment by raymond91125** [comment]
Looks all set. Thanks!
