### ISSUE TITLE
NTR: [Regulation terms for GO:0031509 subtelomeric heterochromatin formation]

### ISSUE THREAD

**Issue by PCarme** [geneontology/go-ontology#28376]
Please provide as much information as you can: 

* **Suggested term label:**
regulation (positive and negative) of subtelomeric heterochromatin formation

* **Definition (free text)**
CC @ValWood 

* **Reference, in format PMID:#######**
(REQUIRED)
PMID:27538348
* **Gene product name and ID to be annotated to this term**
set3 
SPAC22E12.11c

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Is this really a regulator? The abstract of the paper you cite says 

> Set3, a core subunit of the Set3/Hos2 histone deacetylase complex (Set3C), as a contributor to the integrity and silencing of heterochromatin at centromeres, telomeres and silent mating-type locus.

This seems to be involved in chromatin formation; or else where would the process of 'subtelomeric heterochromatin formation' start and end? Right now the definition is "The compaction of chromatin into heterochromatin at the subtelomeric region."; is this too vague?


@colinlog Do you have suggestions to more narrowly define the process, and its regulation? 

Thanks, Pascale

**Comment by PCarme** [comment]
From what the paper describes, Set3 contributes to heterochromatin formation by regulating the expression of factors that are directly involved in constitutive heterochromatin formation. Which, to me, sounds more like a regulation mechanism than a direct involvement in heterochromatin assembly.

**Comment by ValWood** [comment]
@PCarme  mentioned that there were terms for other "regulation of heterochromatin assembly" but not for subtelomeric.

For the mating type heterochromatin formation, this is regulated in response to stress, and controlled by the MAPK pathway.
However,  how is pericentric heterochromatin assembly regulated?

I ask, because all the EXP annotations look incorrect:

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0090053&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

4 fission yeast annotations from CACAO (I will dispute these)
FlyBase has also annotated  Su(var)3-7 to the regulation term, but this is part  of the pathway.








Su(var)3-7
--



Su(var)3-7
--

**Comment by PCarme** [comment]
> OK I didn't reilise it was regulating transcription. This seems that it is likely part of the general role of Set3 in the regulation of transcription. So I would annotate to "regulation of transcription". It probably isn't regulating the process of heterochromatin formation directly because this is regulated post-translationally. My rule of thumb is to only regulate transcription factors which directly activate transcription of specific genes conditionally to "regulation of process". Examples are the ergosterol genes that are regulated in response to hypoxia, or the pho genes that are regulated in response to phosphate starvation. This is direct and rapid activation of a process via transcription.
> 
> A lot of the constitutively required proteins have a long half-life (often over multiple generations), and the processes don't generally appear to be transcriptionally regulated (although obviously, the process does not occur if some component essential for their transcription is mutated once the WT protein is titrated out ). I think that is probably what we are seeing here, so without further info, I would just use this as evidence for a role of set3 in transcription )which is currently only inferred). Otherwise everything involved in core transcription would be annotated to the regulation of every process.

I generally agree with this way of annotating to regulation terms, but this paper clearly makes a point that the PHD domain of Set3 is required for the expression of heterochromatin assembly factors (Rik1 and Clr4 from the CLRC complex) independently of the Set3C complex, which is associated with Set3's general transcriptional regulator. So in this case it appears to be different functions.

**Comment by ValWood** [comment]
OK, I'll take a closer look!

**Comment by colinlog** [comment]
Hi everyone, 

I took a close look at this paper. It does indeed appear that their evidence is consistent with the " Set3 promotes transcription of clr4+ and rik1+ " statement in the abstract. Still, an indirect effect on the transcription of those genes is not formally ruled out. Thereafter, the pericentric heterochromatin formation involvement is really a downstream effect, so I think that annotation should not be made for the set3 gene; it is a phenotype based on a synthetic heterochromatin-inserted ura4 reporter transgene and is likely (very) indirect.

Based on this 2016 publication the annotation to a transcription activation process that I would choose to give the S. pombe set3 gene would go to GO:0045815 (transcription initiation-coupled chromatin remodeling) because the demonstrated involvment of the PHD domain of Set3 is at the gene promoters. It does not appear to require the (H3K36) methyltransferase activity by the SET domain of the SET3 protein which underlies its role in the GO:0140673 transcription elongation-coupled chromatin remodeling process, but rather its PHD domain. And both of those annotations appaer to be separate from the GO:0003713 corepressor molecular function for the SET3 enzyme and the SET3C complex in terms of repression of the meiotic differentiation program. 

Let me add that a O:0045815 (transcription initiation-coupled chromatin remodeling) annotationfor SET3  is consistent with a paper from 2022 in elife, that argues that the PHD domain of SET3 reads to H3K4me2 mark (PMID: 35579426  "Mitotically heritable, RNA polymerase II-independent H3K4 dimethylation stimulates INO1 transcriptional memory ") and I would propose to cite that paper as well to support the annotation of the set3 gene (but not the SET3C complex) to GO:0045815 (transcription initiation-coupled chromatin remodeling).  

Finally, the 2009 paper PMID: 19379692 demonstrated that SET3C (via its PHD domain) can be annotated to the Molecular Function GO:0140566 histone reader activity. I suspect that this is the molecualr basis for the GO:0045815 (transcription initiation-coupled chromatin remodeling) for S. pombe set3 that is discussed above.

**Comment by ValWood** [comment]
Thanks, @colinlog, that makes sense.

- So Set3 has a general role in "transcription initiation-coupled chromatin remodelling", and we can use this paper to support that annotation.

- Is Set3 likely acting as co-activators for specific transcription factors? (in addition to the role as co-repressor via Set1C) or  is this acting as a general remodeller with a particularly noticeable  effect for the selected RITS complex genes? (I guess surveillance rates could be different for different transcripts too)

- If it is a co-activator for a specific TF  I don't think we can easily capture the regulated genes as targets of a specific MF term. So far I have only connected co-activators and co-repressors to  DNA binding transcription factor terms, and we don't have this info.  (@PCarme, for now, it's probably best to capture the RNA level changes as just phenotypes until we have more info).

-  I agree regulation  heterochromatin assembly  seems quite indirect  (this is more "affects" than regulates)

-  The Other 2 papers you mention are S. cerevisiae, so maybe @edwong57  can add the suggested remodelling annotations from these.
- 
- Note that human ortholog is annotated to "regulation of synapse assembly"  @pgaudet  should that be removed? (and "cognition"?) both seem to be indirect.

**Comment by pgaudet** [comment]
@ValWood Can you please also paste the ID of the genes you mention (generally) - it seems you were looking at it, it would be faster for me than to look for it, if that's not too inconvenient.

**Comment by pgaudet** [comment]
@ValWood in fact the human annotations are ISS - next time please send me the IEAs

**Comment by pgaudet** [comment]
It seems that SED% plays a general role in neural processes; do you think these can be removed altghether? I guess I dont know what *should* be annotated to these processes. For reference: paper annotated is https://pubmed.ncbi.nlm.nih.gov/31515109/

**Comment by ValWood** [comment]
Sorry, yes I will,  I added the gene details above. I assumed it was a UniPRot EXP annotation but it is transferred from mouse.

**Comment by ValWood** [comment]
terms like "GO:0050767  regulation of neurogenesis"
seem more appropriate than the specific phenotypes like "cognition" and "synapse assembly"?

**Comment by pgaudet** [comment]
I agree that 'regulation of development' is generally quite suspicious

**Comment by pgaudet** [comment]
In practice - what do you think should be done about this term request?

**Comment by ValWood** [comment]
I think we can close this ticket for this request.
