### ISSUE TITLE
EC:2.7.7.49 and telomerase terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28394]
EC 2.7.7.49 = RNA-directed DNA polymerase
a 2'-deoxyribonucleoside 5'-triphosphate + DNA(n) <=> diphosphate + DNA(n+1)
Catalyzes RNA-template-directed extension of the 3'-end of a DNA strand by one deoxynucleotide at a time.

So it makes sense we have EC:2.7.7.49 as the term and def xref on this term:

id: GO:0003964
name: RNA-directed DNA polymerase activity
namespace: molecular_function
def: "Catalysis of the reaction: deoxynucleoside triphosphate + DNA(n) = diphosphate + DNA(n+1). Catalyzes RNA-template-directed extension of the 3'- end of a DNA strand by one deoxynucleotide at a time." [EC:2.7.7.49]
synonym: "deoxynucleoside-triphosphate:DNA deoxynucleotidyltransferase (RNA-directed) activity" RELATED [EC:2.7.7.49]
synonym: "DNA nucleotidyltransferase (RNA-directed) activity" RELATED [EC:2.7.7.49]
synonym: "reverse transcriptase activity" RELATED [EC:2.7.7.49]
synonym: "revertase activity" RELATED [EC:2.7.7.49]
synonym: "RNA revertase activity" RELATED [EC:2.7.7.49]
synonym: "RNA-dependent deoxyribonucleate nucleotidyltransferase activity" RELATED [EC:2.7.7.49]
synonym: "RNA-dependent DNA polymerase activity" RELATED [EC:2.7.7.49]
synonym: "RNA-directed DNA polymerase, group II intron encoded" NARROW []
synonym: "RNA-directed DNA polymerase, transposon encoded" NARROW []
synonym: "RNA-instructed DNA polymerase activity" RELATED [EC:2.7.7.49]
synonym: "RT" RELATED [EC:2.7.7.49]
xref: EC:2.7.7.49
xref: MetaCyc:RNA-DIRECTED-DNA-POLYMERASE-RXN
is_a: GO:0034061 ! DNA polymerase activity

That GO term has two children, the second of which also uses EC:2.7.7.49 as the def xref.

```
RNA-directed DNA polymerase activity
        |__telomerase activity
        |__telomerase RNA reverse transcriptase activity
```

id: GO:0003720
name: telomerase activity
def: "Catalysis of the reaction: deoxynucleoside triphosphate + DNA(n) = diphosphate + DNA(n+1). Catalyzes extension of the 3'- end of a DNA strand by one deoxynucleotide at a time using an internal RNA template that encodes the telomeric repeat sequence." [GOC:krc, PMID:28732250]
is_a: GO:0003964 ! RNA-directed DNA polymerase activity

id: GO:0003721
name: telomerase RNA reverse transcriptase activity
def: "Catalysis of the extension of the 3' end of a DNA strand by one deoxynucleotide at a time. Cannot initiate a chain de novo; uses the RNA subunit of the telomerase enzyme complex as its template." [EC:2.7.7.49, PMID:11812242]
synonym: "telomerase, catalyst" EXACT []
is_a: GO:0003964 ! RNA-directed DNA polymerase activity
relationship: part_of GO:0003720 ! telomerase activity

- [ ] minimally, we should remove EC:2.7.7.49 from the def xref on GO:0003721
- [ ] but @pgaudet and I are struggling to see the difference between GO:0003720 and GO:0003721. Should these two terms be merged so that we have just one 'telomerase activity' term? (direct annotations to each term are very overlapping) Or if they are really different activities, can we define/distinguish them better?  Maybe @krchristie knows?

**Comment by pgaudet** [comment]
@RLovering I know your group has looked at these as well - do you know what the difference may be between 'GO:0003720 telomerase activity' and 'GO:0003721  telomerase RNA reverse transcriptase activity' ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale
I agree the difference seems very minor and it is possible that this term was created to be applied to the RNA component of telomerase? I think you could just merge these two terms.

Looking at the child terms and taking on the removal of BP regulates MF terms. I note that there is the term [GO:0010521]
telomerase inhibitor activity but not an activator term. I have just looked up one of the proteins associated with the positive reg term and UniProt describes NVL https://www.uniprot.org/uniprotkb/O15381/entry as: Participates in the assembly of the telomerase holoenzyme and effecting of telomerase activity via its interaction with TERT (PubMed:[22226966](https://www.uniprot.org/citations/22226966)). A SWIS annotation confirms NVL binds TERT. 
https://europepmc.org/article/MED/22226966 abstract points to the role of NVL in telomerase assembly and that NVL2 is an essential component of the telomerase holoenzyme.

Would this support telomerase activator activity? If so could this term be created before I start deleting all the pos reg terms? 

I can see that many of the other reg terms relate to signaling pathway proteins which presumably should be annotated to a pathway not reg of telomerase.

Many thanks, hope all is well with you

Ruth

**Comment by pgaudet** [comment]
Thanks @RLovering 
I see there are 42 EXP annotations to [GO:0051973](https://www.ebi.ac.uk/QuickGO/term/GO:0051973)    positive regulation of telomerase activity, so we need to check all of them, but for NVL, I would annotate this to 'protein complex assembly', not regulation; what do you think ? 

I am doing well, I hope you are too ! 

Pascale

**Comment by RLovering** [comment]
I think that 'protein complex assembly' does not indicate NVL has a role in telomerase assembly. I guess if NVL is involved in assembly of many complexes perhaps this specific role is not required. So I guess you are making me find a better paper to demonstrate that it activates not just assembles the complex. Before I look at this further, have you decided to annotate adaptor proteins as activating the complexes or signaling pathways they are associated with rather than just annotating them as involved in protein complex assembly? 

I would have thought that if the protein remains associated with the activated complex then it could be considered as part of the signaling pathway or activating the complex, (rather than just assembling the complex) although I am sure nothing is this simple.

I will see if I can find a better activator, I really do not want to check all these annotations without an alternative term to use if the gp is an activator.

Thanks

Ruth

**Comment by pgaudet** [comment]
I'll open a new ticket about the regulator activity to avoid conflating too many issues.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0003964 RNA-directed DNA polymerase activity and replace it by its parent, GO:0003720 telomerase activity, because they represent the same activity. 

There are 13 annotations to this term, that will be migrated automatically. There are mappings that need to be fixed: 
interpro2go
reactome2go
uniprotkb_kw2go
unirule2go
hamap2go
See https://github.com/geneontology/go-annotation/issues/5334

This term is not in any subsets. 
You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28394

Thanks, Pascale

**Comment by sjm41** [comment]
> The proposal has been made to obsolete GO:0003964 RNA-directed DNA polymerase activity and replace it by its parent, GO:0003720 telomerase activity, because they represent the same activity.

@pgaudet Did you meant to say "The proposal has been made to obsolete GO:0003721 telomerase RNA reverse transcriptase activity and replace it by GO:0003720 telomerase activity, because they represent the same activity."

??

**Comment by dsiegele** [comment]
@pgaudet I have the same question. GO:0003964 RNA-directed DNA polymerase activity is the parent of GO:0003720 telomerase not the other way around. Not all RNA-directed DNA polymerase activity is involved in making telomeres.

**Comment by deustp01** [comment]
Piling on (and quoting ticket #5334) -

Should be GO:0003964 RNA-directed DNA polymerase activity be retired, or should terms like telomerase activity (and others that differ by the RNA template used in the activity) be made children of it?
For aspects of DNA synthesis enabled by viral reverse transcriptase, I don't see how to avoid use of GO:0003964 RNA-directed DNA polymerase activity. GO:0003964 is an is_a child of GO:0034061 DNA polymerase activity - there are no terms of intermediate granularity. Do we indeed want to lump everything that uses any sort of RNA template into one term?

For example, Reactome uses this term for a step in reverse transcription of the HIV genome - [R-HSA-164520 "Minus strand DNA synthesis resumes"](https://reactome.org/PathwayBrowser/#/R-HSA-162587&SEL=R-HSA-164520&PATH=R-HSA-1643685,R-HSA-5663205,R-HSA-9824446,R-HSA-162906). Do we really want to assert that this is a kind of telemere elongation?

**Comment by pgaudet** [comment]
Hi everyone, 

Sorry I mixed up the terms in the announcement!! 

Indeed the proposal is to obsolete GO:0003721 telomerase RNA reverse transcriptase activity and replace it by GO:0003720 telomerase activity, because they represent the same activity.

Note that we have a small hierarchy of single-children: 
. GO:0003964 RNA-directed DNA polymerase activity
.. GO:0003720 telomerase activity
...  GO:0003721 telomerase RNA reverse transcriptase activity

EC has a single reaction, [EC:2.7.7.49](https://enzyme.expasy.org/EC/2.7.7.49), that represents reverse transcriptase/RNA-directed DNA polymerase activity, that covers TERT, ie telomerase activity. 

We could also merge GO:0003720 telomerase activity up into the parent GO:0003964 RNA-directed DNA polymerase activity to better align with EC (RHEA doesn't have this much specificity, a single RHEA covers 3 ECs: https://www.rhea-db.org/rhea?query=ec%3A2.7.7.49). Currently  GO:0003720 telomerase activity has no cross reference to enzyme databases, generally we'd like to avoid this but of course there may be exceptions. 

Thanks everyone for the feedback ! and sorry for the mix up. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also, obsolete the regulation terms: 

- [ ] GO:1905661 regulation of telomerase RNA reverse transcriptase activity >> replace by GO:0051972 regulation of telomerase activity
- [ ] GO:1905662 negative regulation of telomerase RNA reverse transcriptase activity >> replace by GO:0051974 negative regulation of telomerase activity
- [ ] GO:1905663 positive regulation of telomerase RNA reverse transcriptase activity >> replace by GO:0051973 positive regulation of telomerase activity
