### ISSUE TITLE
Missing parent: GO:0000162  tryptophan biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28553]
* **GO term ID and label for which you request a new superclass**

Missing parent: GO:0000162  tryptophan biosynthetic process

* **New superclass (parent) suggested**

is not a descendant of tryptophan metabolic process??

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by pgaudet** [comment]
Metabolic process is using the L form, but not biosynthetic process :( 

<img width="513" alt="image" src="https://github.com/user-attachments/assets/ff528fe9-48c1-42f4-bccb-70e1751728a2">

<img width="512" alt="image" src="https://github.com/user-attachments/assets/5e216ad5-62cf-4638-a1ef-fc8f0a18d254">

**Comment by pgaudet** [comment]
Compare to : 

<img width="512" alt="image" src="https://github.com/user-attachments/assets/5e216ad5-62cf-4638-a1ef-fc8f0a18d254">

**Comment by ValWood** [comment]
Is this a CHEBI issue?

**Comment by deustp01** [comment]
> Is this a CHEBI issue?

@cmungall has argued forcefully that it is and proposed a strategy that ChEBI could use to solve it - see [recent presentation](https://docs.google.com/presentation/d/1R3NRzH70ERjwebqecgt2OYKC8sIuB1_Xs7ENyWAXgjc/edit#slide=id.p). But what do we do while we wait?

**Comment by deustp01** [comment]
> Metabolic process is using the L form, but not biosynthetic process :(

If you look at Chris's presentation, you will see that his anatomy example has a stealth stereochemistry issue concealed in it - just to say that the definitlive clean-up extends beyond ionization states.

**Comment by ValWood** [comment]
What is the fix for this? I can ask CHebi but I'm not sure what the problem is.
Cant we just change the biosynthesis logical definition to match?

(I wan to fix this because it causes problems with search results (and seems off to have more entities annotated to biosynthesis than metabolism)

**Comment by deustp01** [comment]
> What is the fix for this?

But what exactly is the problem here? If the issue is which ChEBI instance to use in connection with reactions and processes that involve L-tryptophan, the answer, according to RHEA which is a really well-informed and consistent arbiter of biochemical structures, is CHEBI:57912 - L-tryptophan zwitterion - see [this RHEA search result](https://www.rhea-db.org/rhea?query=tryptophan).

If the question is a more general one like a good general term that is agnostic with respect to ionization and stereochemistry, then I think there may b=not be a good answer at present.
