### ISSUE TITLE
Missing parent: GO:0006857 oligopeptide transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28735]
* **GO term ID and label for which you request a new superclass**

GO:0006857   oligopeptide transport

* **New superclass (parent) suggested**

GO:0015833   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0015833/complete)
peptide transport

* **Reference(s), if appropriate**
spotted because peptide transport should be redundant here:

<img width="1122" alt="ticket_missing parent" src="https://github.com/user-attachments/assets/fca9c6a3-2962-4d29-8724-87a7e9535750">

(or remove "peptide" terms...?)

**Comment by edwong57** [comment]
So oligopeptide is a child of peptide. Peptide transport (GO:0015833) is defined as: transport and ('has primary input' some 'peptide zwitterion'). Rather than making oligopeptide transport a child of peptide transport specifically, w\ould it be better to fix this definition of peptide transport to be: transport and ('has primary input' some 'peptide')? Then, oligopeptide transport (along with others) the reasoner will automatically be placed as children. Here's a screenshot of the inferred class hierarchy in Protege after I did that -
![image](https://github.com/user-attachments/assets/24f8b341-58c0-4a83-bf79-168c0b891374)

Or another option is to change the definition of GO:0006857, and any other term that uses 'peptide' to use 'peptide zwitterion' to become children of peptide transport.

Is there a preferred method?

**Comment by pgaudet** [comment]
Hi @edwong57 

This is a ChEBI 7.3 problem - "peptide" is not 7.3 (only 'zwitterion'), so we cannot use it. 
I dont find the ChEBI 7.3 form of oligopeptide, so for now we have to assert this manually as a parent/child. 

Hopefully we can find a better solution in the near future. 

Pascale
