### ISSUE TITLE
Obsoletion request: GO:0004310 farnesyl-diphosphate farnesyltransferase activity & replace by GO:0051996 squalene synthase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28819]
Dear all, 

The proposal has been made to obsolete GO:0004310 farnesyl-diphosphate farnesyltransferase activity. The reason for obsoletion is that this reaction is a subreaction of GO:0051996 squalene synthase activity.

**Comment by pgaudet** [comment]
Annotations: https://github.com/geneontology/go-annotation/issues/5438

**Comment by pgaudet** [comment]
Done

**Comment by ValWood** [comment]
Hi @pgaudet 


farnesyl-diphosphate farnesyltransferase activity (GO:0004310)

is defined
Catalysis of the reaction: 2 farnesyl diphosphate = diphosphate + presqualene diphosphate.

input is 
2 farnesyl diphosphate (FPP)
(2-trans,6-trans-farnesyl diphosphate)



squalene synthase activity
presqualene diphosphate + NADPH = squalene + NADP+ + diphosphate.


does this mean the definition of 
squalene synthase activity needs to change,


i.e
(2-trans,6-trans-farnesyl diphosphate)
isn't
presqualene diphosphate

otherwise, my GO-CAM input no longer aligns inouta and outputs.

(in my model this is two steps, but both catalysed by erg9)

if squalene synthase represents one inseparable reacton, the definition should cover :

Formation of Squalene:
Condensation of Two FPP Molecules: Two molecules of farnesyl pyrophosphate (FPP) undergo a head-to-head condensation reaction.
Enzyme: The enzyme squalene synthase (also known as erg9 in yeast) catalyzes this reaction.
Reaction Mechanism:
Formation of Presqualene Diphosphate (PSPP): The two FPP molecules first condense to form presqualene diphosphate.
Cyclization and Reduction: The presqualene diphosphate is then reduced and cyclized to form squalene, a linear triterpene hydrocarbon.


tks, v

**Comment by pgaudet** [comment]
> does this mean the definition of squalene synthase activity needs to change,

No - the term I obsoleted was a part reaction, presqualene diphosphate is an intermediate. 

The overall reaction was correct for GO:0004310 farnesyl-diphosphate farnesyltransferase activity: 
primary input: (2E,6E)-farnesyl diphosphate
primary output: squalene 

Does that not work for your model?

**Comment by ValWood** [comment]
yes ,  that seems to work,

(2E,6E)-farnesyl diphosphate seems to be 
2-trans,6-trans-farnesyl diphosphate CHEBI:175763

was there a reason not to call it this?

**Comment by pgaudet** [comment]
It's because we use the UniProt/RHEA label (see synonyms section in ChEBI). 

We should also do this in Noctua?

**Comment by ValWood** [comment]
Do what in Noctua?

**Comment by ValWood** [comment]
I'm going by the 2 upstream reaction participants which include 2-trans,6-trans-farnesyl diphosphate.


geranyltranstransferase activity (GO:0004337)
Definition | Parents
-- | --
Catalysis of the reaction: geranyl diphosphate + isopentenyl diphosphate = 2-trans,6-trans-farnesyl diphosphate + diphosphate.


farnesyltranstransferase activity

Definition | Parents
-- | --
Catalysis of the reaction: 2-trans,6-trans-farnesyl diphosphate + isopentenyl diphosphate = diphosphate + geranylgeranyl diphosphate.

**Comment by pgaudet** [comment]
Good catch - we have not at all reviewed all MF terms... just the ones with that shared EC or RHEA mappings 

So, there are 47 terms still using "2-trans,6-trans-farnesyl diphosphate"

I fixed the following: 
GO:0102883	(+)-beta-chamigrene synthase activity
GO:0102881	(+)-beta-barbatene synthase activity
GO:0102878	(+)-alpha-barbatene synthase activity
GO:0004337	geranyltranstransferase activity

I will open another ticket for the rest. 

Thanks, Pascale
GO:0004161	dimethylallyltranstransferase activity
