### ISSUE TITLE
EC:1.1.1.331-related merges

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28858]
id: GO:0102911
name: (-)-secoisolariciresinol dehydrogenase activity
def: "Catalysis of the reaction: (-)-secoisolariciresinol + NAD = H+ + (-)-lactol + NADH." [EC:1.1.1.331, GOC:pz]
xref: MetaCyc:RXN-8680
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

id: GO:0102912
name: (-)-lactol dehydrogenase activity
def: "Catalysis of the reaction: (-)-lactol + NAD = H+ + (-)-matairesinol + NADH." [EC:1.1.1.331, GOC:pz]
xref: MetaCyc:RXN-8681
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

MetaCyc:RXN-8680 & MetaCyc:RXN-8681 describe subreactions of EC:1.1.1.331 (= RHEA:33887)
=> merge these 2 terms into GO:0120529:

id: GO:0120529
name: secoisolariciresinol dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: (-)-secoisolariciresinol + 2 NAD+ = (-)-matairesinol + 2 H(+) + 2 NADH." [RHEA:33887]
xref: EC:1.1.1.331 {source="skos:exactMatch"}
xref: KEGG_REACTION:R10129 {source="skos:exactMatch"}
xref: MetaCyc:RXN-13433 {source="skos:exactMatch"}
xref: RHEA:33887 {source="skos:exactMatch"}
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0102911 (-)-secoisolariciresinol dehydrogenase activity (5 EXP, UniProt) and 
GO:0102912  (-)-lactol dehydrogenase activity (no annotations) and replace them with GO:0120529 secoisolariciresinol dehydrogenase activity because these represent subreactions of GO:0120529 secoisolariciresinol dehydrogenase activity. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28858

Thanks, Pascale
