### ISSUE TITLE
Textual definition update: GO:0043490 malate-aspartate shuttle

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28982]
* **GO term ID and label for which you request a definition update**
GO:0043490 malate-aspartate shuttle
* **Missing Xref**
These are the Xref that are missing:

Add  MetaCyc ref MALATE-ASPARTATE-SHUTTLE-PWY

has_participant CHEBI:16810 2-oxoglutarate(2−)
has_participant CHEBI:29991 L-aspartate(1−)
has_participant CHEBI:29985 L-glutamate(1−)
has_participant CHEBI:16452 oxaloacetate(2−)
has_participant CHEBI:15589 (S)-malate(2−)
has_primary_output CHEBI:57945 ! NADH(2-)
has_primary_input CHEBI:57540 ! NAD(1-)"

* **Additional information**
*there is another ticket [#27924](https://github.com/geneontology/go-ontology/issues/27924) the parentage of this GO term.

> Could 'malate-aspartate shuttle' term become also a child of NADH oxidation?

I am trying to review the NAD branch that have several issue (I haven't made a ticket yet).

**Comment by sjm41** [comment]
Current 'malate-aspartate shuttle' entry is:

id: GO:0043490
name: malate-aspartate shuttle
namespace: biological_process
def: "The process of transferring reducing equivalents from the cytosol into the mitochondria; NADH is used to synthesise malate in the cytosol; this compound is then transported into the mitochondria where it is converted to oxaloacetate using NADH, the oxaloacetate reacts with gluamate to form aspartate, and the aspartate then returns to the cytosol to complete the cycle." [GOC:jl, GOC:mtg_electron_transport, ISBN:0716743663]
synonym: "malate aspartate shuttle" EXACT []
synonym: "malate/aspartate shuttle" EXACT []
synonym: "malate:aspartate shuttle" EXACT []
xref: Wikipedia:Malate-aspartate_shuttle
is_a: GO:1990542 ! mitochondrial transmembrane transport
relationship: part_of GO:0022904 ! respiratory electron transport chain


Compare with:

id: GO:0006127
name: glycerophosphate shuttle
namespace: biological_process
def: "The process of transferring reducing equivalents from the cytosol into the mitochondria; NADH is used to synthesise glycerol 3-phosphate in the cytosol; this compound is then transported into the mitochondria where it is converted to dihydroxyacetone phosphate (DHAP) using FAD; DHAP then returns to the cytosol to complete the cycle." [GOC:jl, GOC:mtg_electron_transport, ISBN:0716720094, PMID:16368075]
xref: MetaCyc:PWY-6118
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_part GO:0004368 ! glycerol-3-phosphate dehydrogenase (quinone) activity
intersection_of: has_part GO:0141152 ! glycerol-3-phosphate dehydrogenase (NAD+) activity
intersection_of: has_participant CHEBI:57597 ! sn-glycerol 3-phosphate(2-)
intersection_of: has_participant CHEBI:57642 ! glycerone phosphate(2-)
intersection_of: has_primary_input CHEBI:132124 ! 1,4-benzoquinones
intersection_of: has_primary_input CHEBI:57945 ! NADH(2-)
intersection_of: has_primary_output CHEBI:24646 ! hydroquinones
intersection_of: has_primary_output CHEBI:57540 ! NAD(1-)
relationship: part_of GO:0022904 ! respiratory electron transport chain
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26974" xsd:anyURI

**Comment by deustp01** [comment]
Fussy grammatical quibble - should the definition start, "A process ... " in each case because there are more than one?

**Comment by sjm41** [comment]
Based on the discussion on Monday's ontology call and subsequent discussion with @rozaru, here's a new proposal for how to amend the two NADH shuttle terms.

Specific points addressed:
- make new parent term to group the two related shuttle processes
- improve the textual definitions of the existing terms (attributed to PMID:16368075)
- add the MetaCyc xref to 'malate-aspartate shuttle' as suggested above
- change name of GO:0006127 to the more commonly used 'glycerol-3-phosphate shuttle'
- remove all the participant/input/output chemicals from the LD of 'glycerol-3-phosphate shuttle'
- retain the 'has_part' relations to the catalytic activities for 'glycerophosphate shuttle', though make these asserted classes rather than part of the LD; add the corresponding 'has_part' relations to 'malate-aspartate shuttle'
- remove the 'part_of GO:0022904 ! respiratory electron transport chain' relation on 'glycerol-3-phosphate shuttle'

See below for proposed new/revised term entries:

---

NTR:
name: mitochondrial NADH shuttle
def: The process of transferring reducing equivalents from NADH in the cytosol to the mitochondria via a combination of enzymatic reactions, thereby bypassing the impermeability of the inner mitochondrial membrane to NADH. This restores the NAD+ cytosolic pool necessary for glycolysis and provides electrons from cytosolic NADH to the respiratory electron transport chain. [PMID:16368075]
is_a: GO:0019674 ! NAD metabolic process
is_a: GO:0006091 generation of precursor metabolites and energy

---

id: GO:0043490
name: malate-aspartate shuttle
def: "The process of transferring reducing equivalents from NADH in the cytosol to the mitochondria via malate. Cytosolic aspartate aminotransferase converts aspartate to oxaloacetate, and cytosolic malate dehydrogenase uses NADH to convert oxaloacetate to malate in the cytosol; the malate-alpha-ketoglutarate carrier then transports the malate into the mitochondria where mitochondrial malate dehydrogenase uses NAD to convert malate back to oxaloacetate; the electrons on the reduced NADH are then available for use in the electron transport chain; mitochondrial aspartate aminotransferase converts oxaloacetate to aspartate, and the glutamate-aspartate carrier transports the aspartate back to the cytosol to complete the cycle." [PMID:16368075]
xref: MALATE-ASPARTATE-SHUTTLE-PWY  {source="skos:narrowMatch"}
intersection_of: NTR ! mitochondrial NADH shuttle
intersection_of: GO:1990542 ! mitochondrial transmembrane transport
relationship: has_part GO:0004069 ! L-aspartate:2-oxoglutarate aminotransferase activity
relationship: has_part GO:0030060 ! L-malate dehydrogenase (NAD+) activity

---

id: GO:0006127
name: glycerol-3-phosphate shuttle
def: "The process of transferring reducing equivalents from NADH in the cytosol into the mitochondria via glycerol-3-phosphate. Cytosolic glycerol-3-phosphate dehydrogenase uses NADH to convert dihydroxyacetone phosphate (DHAP) to glycerol-3-phosphate (G3P) in the cytosol; G3P then diffuses into the mitochondria where mitochondrial glycerol-3-phosphate dehydrogenase uses FAD to convert G3P back to DHAP; the electrons on the reduced FADH2 are then available for use in the electron transport chain, and DHAP returns to the cytosol to complete the cycle." [PMID:16368075]
synonym: "glycerophosphate shuttle" EXACT[]
synonym: "glycerol phosphate shuttle" EXACT[]
xref: MetaCyc:PWY-6118 {source="skos:exactMatch"}
intersection_of: NTR ! mitochondrial NADH shuttle
relationship: has_part GO:0141152 ! glycerol-3-phosphate dehydrogenase (NAD+) activity
relationship: has_part GO:0004368 ! glycerol-3-phosphate dehydrogenase (quinone) activity

---

Questions:
Q1) I can't see how to make an accurate LD for the NTR above, so have just suggested 2 asserted is_a relations. Maybe someone else can see a feasible LD??

Q2) The malate-aspartate shuttle involves transmembrane transporters, so is correctly a sub-class of 'mitochondrial transmembrane transport'. In contrast, the glycerol-3-phosphate shuttle does not use transmembrane transporters so correctly lacks this relation. I'm thinking the presence/absence of that relation in the LD (as shown above) sufficient to distinguish the two shuttle terms - is that right?

Q3) For now, the above proposal does not include any relations for input/output/participant chemicals - I'm not sure we made a decision on whether or not these should be included on the term as asserted relations? (The additional complication for these shuttles, is that it's not obvious what in a (primary) input/output given their cyclical nature - I guess adding all the chemicals as 'participants' remains an option.)

**Comment by sjm41** [comment]
Yep, will do! (Though I see the two instances of "synthesise" are in the current text defs, and don't appear in the new proposed defs!)

**Comment by pgaudet** [comment]
I fixed the spelling, a 3 other instances.

**Comment by sjm41** [comment]
I decided not to create the 'mitochondrial NADH shuttle' parent term to group the two specific shuttle terms - it's not really necessary and I was having trouble with the LD.

**Comment by sjm41** [comment]
Here's how the two terms look now:

id: GO:0043490
name: malate-aspartate shuttle
namespace: biological_process
def: "The process of transferring reducing equivalents from NADH in the cytosol to the mitochondria via malate. Cytosolic aspartate aminotransferase converts aspartate to oxaloacetate, and cytosolic malate dehydrogenase uses NADH to convert oxaloacetate to malate in the cytosol; the malate-alpha-ketoglutarate carrier then transports the malate into the mitochondria where mitochondrial malate dehydrogenase uses NAD to convert malate back to oxaloacetate; the electrons on the reduced NADH are then available for use in the electron transport chain; mitochondrial aspartate aminotransferase converts oxaloacetate to aspartate, and the glutamate-aspartate carrier transports the aspartate back to the cytosol to complete the cycle." [GOC:sjm, PMID:16368075]
synonym: "malate aspartate shuttle" EXACT []
synonym: "malate/aspartate shuttle" EXACT []
synonym: "malate:aspartate shuttle" EXACT []
xref: MetaCyc:MALATE-ASPARTATE-SHUTTLE-PWY
xref: Wikipedia:Malate-aspartate_shuttle
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_part GO:0004069 ! L-aspartate:2-oxoglutarate aminotransferase activity
intersection_of: has_part GO:0030060 ! L-malate dehydrogenase (NAD+) activity
intersection_of: has_primary_input CHEBI:57945 ! NADH(2-)
intersection_of: has_primary_output CHEBI:57540 ! NAD(1-)
relationship: has_part GO:1990542 ! mitochondrial transmembrane transport
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28982" xsd:anyURI

id: GO:0006127
name: glycerol-3-phosphate shuttle
namespace: biological_process
def: "The process of transferring reducing equivalents from NADH in the cytosol into the mitochondria via glycerol-3-phosphate. Cytosolic glycerol-3-phosphate dehydrogenase uses NADH to convert dihydroxyacetone phosphate (DHAP) to glycerol-3-phosphate (G3P) in the cytosol; G3P then diffuses into the mitochondria where mitochondrial glycerol-3-phosphate dehydrogenase uses FAD to convert G3P back to DHAP; the electrons on the reduced FADH2 are then available for use in the electron transport chain, and DHAP returns to the cytosol to complete the cycle." [GOC:sjm, PMID:16368075]
synonym: "glycerol phosphate shuttle" EXACT []
synonym: "glycerophosphate shuttle" EXACT []
xref: MetaCyc:PWY-6118
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_part GO:0004368 ! glycerol-3-phosphate dehydrogenase (quinone) activity
intersection_of: has_part GO:0141152 ! glycerol-3-phosphate dehydrogenase (NAD+) activity
intersection_of: has_primary_input CHEBI:57945 ! NADH(2-)
intersection_of: has_primary_output CHEBI:57540 ! NAD(1-)
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26974" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28982" xsd:anyURI


Which results in this inferred tree:

```
NAD metabolic process
   |_NADH metabolic process
        |_ NADH oxidation
            |_glycerol-3-phosphate shuttle
            |_malate-aspartate shuttle
```

As mentioned in https://github.com/geneontology/go-ontology/issues/27924, it seems the term 'GO:0006116 NADH oxidation' (def: "A metabolic process that results in the oxidation of reduced nicotinamide adenine dinucleotide, NADH, to the oxidized form, NAD+.  [no xrefs, no source publication) should be obsoleted since it's a single step MF, equivalent to:
id: GO:0003954
name: NADH dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: NADH + H+ + acceptor = NAD+ + reduced acceptor."

Shall I make a separate ticket for that obsoletion?

**Comment by pgaudet** [comment]
Yes please! We should obsolete 
GO:0006116 NADH oxidation'
and GO:0070995 'NADPH oxidation'

Right ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Probably, but @rozaru has just reminded me that she's looked into the NAD(P)H BP terms more than I have, so she and I will chat and review these on Monday before making the obsoletion tickets.

**Comment by deustp01** [comment]
(Jumping in here with a naive question and without really studying the details of the ticket.) In this ontology bit

NAD metabolic process
   |_NADH metabolic process
        |_ NADH oxidation
            |_glycerol-3-phosphate shuttle
            |_malate-aspartate shuttle

... why are the shuttles (is_a?) children of NAD metabolism. I'd think of the shuttles as whole processes, with goals / ends of their own, with NAD(H) turnover as one of their useful parts along with some small-molecule transport parts. The hierarchy here seems like making glycolysis, say, a child of ATP synthesis, or for that matter also a child of NADH metabolism.

I'm clearly missing something here.
