### ISSUE TITLE
GO:0101021 estrogen 2-hydroxylase activity with no cross reference

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#29035]
GO:0101021 estrogen 2-hydroxylase activity lacks EC/RHEA cross references.

The definition reference PMID:14559847 is also cited by
RHEA:47208 estrone + O2 + reduced [NADPH--hemoprotein reductase] = 2-hydroxyestrone + H(+) + H2O + oxidized [NADPH--hemoprotein reductase].
RHEA:47212 17beta-estradiol + O2 + reduced [NADPH--hemoprotein reductase] = 2-hydroxy-17beta-estradiol + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]

**Comment by pgaudet** [comment]
In case this helps: https://wiki.geneontology.org/Guidelines_for_catalytic_activity_terms#Catalytic_activity_definition

**Comment by deustp01** [comment]
> [RHEA:47212](https://www.rhea-db.org/rhea/47212) 17beta-estradiol + O2 + reduced [NADPH--hemoprotein reductase] = 2-hydroxy-17β-estradiol + H+ + H2O + oxidized [NADPH--hemoprotein reductase]
> 
> while GO has Catalysis of the reaction: estrogen + **donor-H2** + O2 = 2-hydroxyestrogen + H2O.
> 
> We need to include 'reduced [NADPH--hemoprotein reductase]' in substrates and 'oxidized [NADPH--hemoprotein reductase]' in products.

Just as we regularly have problems defining the exact boundaries of a biological process, I think there may be a reaction boundary problem here. This is partly a guess because my understanding of oxidation - reduction chemistry in biochemical reactions is limited. But anyway, my guess is that the basic textbook representation of this reaction would be the conversion of estrogen to hydroxyestrogen coupled to the conversion of NADPH + H+ to NADP+, all in one reaction, while the more complicated reality is that the estrogen conversion is coupled to the conversion of an enzyme-associated hemoprotein, and the henoprotein needs to be restored to its initial state in a separate reaction in order for the enzyme we're annotating to act on its next molecule of substrate estrogen. This pattern is common in steroid and eicosanoid metabolism and I don't have any good ideas about how to handle well.

**Comment by raymond91125** [comment]
> In case this helps: https://wiki.geneontology.org/Guidelines_for_catalytic_activity_terms#Catalytic_activity_definition

I don't think the guidelines address how to deal with multiple estrogen species.The narrowMatch crossrefs are not meant to be an exhaustive list of possible reactions. We can decide to make it so but that would be making a new and more restrictive definition for the GO term, I think.
