### ISSUE TITLE
Proton-transporting ATP synthase complex terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29067]
I wasn't sure where to put this ticket. It  is about GO-CAM modelling but overlaps with the ontology representation

I am building a CO-CAM for the respiratory chain/oxidative phosphorylation

For the ATP synthase complex we have a number of terms:

https://www.pombase.org/term/GO:0045259

The complex and its various parts.
1) catalytic core
2) coupling factor
3) central stalk
4) stator stalk

Are these 'sub parts' too granular for GO  (I am wondering what activities we could attach to these )

All 17 subunits have
 proton-transporting ATP synthase activity, rotational mechanism (GO:0046933)
 
Didn't we have a rule that we would only add complexes that were functional units?

**Comment by sjm41** [comment]
@ValWood Complex V terms are simpler than they used to be! See https://github.com/geneontology/go-ontology/issues/27253

As you say, the branch now looks like this:
```
|__proton-transporting ATP synthase complex
    |__proton-transporting ATP synthase complex, catalytic core F(1)
        |__proton-transporting ATP synthase, catalytic core
        |__proton-transporting ATP synthase, central stalk
    |__proton-transporting ATP synthase complex, coupling factor F(o)
        |__proton-transporting ATP synthase, stator stalk
```

At the time of making all the obsoletions in the other ticket, we did stop short of obsoleting these complex V subcomplexes - yes, partly because of nervousness of obsoleting even more, especially since these these subcomplexes are well characterized/defined and the terms are heavily used: 
proton-transporting ATP synthase complex, catalytic core F(1) - 750K annotations, 35 EXP
proton-transporting ATP synthase complex, coupling factor F(o) - 615K annotations, 31 EXP

That said, the GO [guidelines](https://wiki.geneontology.org/Protein_complexes) for complexes do say that subcomplexes are out of scope.

I'd be happy to see these subcomplex terms disappear from the GO.

**Comment by sjm41** [comment]
I can't remember - does PomBase not have Complex Portal IDs?

**Comment by sandraorchard** [comment]
Working on it - I can create ATP synthase for you if needed, Val.

**Comment by ValWood** [comment]
@sandraorchard funnily enough I moved it to the top of  your spreadsheet a couple of days ago ;)

**Comment by sandraorchard** [comment]
No problem then, I'll create a skeleton entry when I have a few minutes spare today and send you over the identifier.

**Comment by sjm41** [comment]
@rozaru

**Comment by sandraorchard** [comment]
CPX-25764

**Comment by raymond91125** [comment]
- [ ] GO:0045261 proton-transporting ATP synthase complex, catalytic core F(1)
- [ ] GO:0045263 proton-transporting ATP synthase complex, coupling factor F(o)
- [ ] GO:0045267 proton-transporting ATP synthase, catalytic core
- [ ] GO:0045269 proton-transporting ATP synthase, central stalk
- [ ] GO:0045265 proton-transporting ATP synthase, stator stalk
