### ISSUE TITLE
Obsoletion request: GO:0006268      DNA unwinding involved in DNA replication

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29153]
Please provide as much information as you can:

* **GO term ID and Label**

 GO:0006268      DNA unwinding involved in DNA replication

* **Reason for deprecation** Put an x in the appropriate box: 

 - [ ] The reason for obsoletion is that this term represents a molecular function.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
Hi @raymond91125 

This is right. We should also obsolete the parent GO:0032508 DNA duplex unwinding, since this is a single-step process (= DNA helicase activity), and the regulation terms:

- [ ] GO:1905462 regulation of DNA duplex unwinding
- [ ] GO:1905463 negative regulation of DNA duplex unwinding
- [ ] GO:1905464 positive regulation of DNA duplex unwinding

and regulation of DNA helicase activity: (this is covered by another ticket https://github.com/geneontology/go-ontology/issues/22455 but since there are few annotations (3 EXP), we can deal with these now): 

- [ ] GO:1905774 regulation of DNA helicase activity
- [ ] GO:1905775 negative regulation of DNA helicase activity
- [ ] [GO:1905776 positive regulation of DNA helicase activity

**Comment by raymond91125** [comment]
- [ ] GO:0032508 DNA duplex unwinding

**Comment by pgaudet** [comment]
Hi @raymond91125 

We should also obsolete GO:0010501 RNA secondary structure unwinding

**Comment by raymond91125** [comment]
GO:0000717 nucleotide-excision repair, DNA duplex unwinding

**Comment by pgaudet** [comment]
Yes ! I'm not sure what the G duplex is though. Should there be a process
to capture that?

Le ven. 15 nov. 2024, 19:13, Raymond Lee ***@***.***> a
écrit :

**Comment by raymond91125** [comment]
PMID:25653156 via the action of a DEAH-box ATP-dependent helicase.
