### ISSUE TITLE
Taxon constraint: peroxisome

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#29394]
Nadya spotted that a number of archaea, bacteria and viruses are annotated to the GO term "peroxisome" in uniprot. 

I see a number of taxon constraints have been applied to these terms since September, the most recent "only in eukaryotes" in november. 

In quickgo a number of bacteria and archaea (no viruses) are still annotated to this term https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0005777&taxonId=2157,2&taxonUsage=descendants

We assume these annotations will disappear next update (because of the constraint), but just wanted to check to make sure in case something is going awry? (the constraint was put in mid November, and I'm not sure if that is dependent on the builds or not?)

Cheers

**Comment by pgaudet** [comment]
Hi @Antonialock 

As far as I can tell, all annotations are coming from IEA or IBA. These need a pipeline run (GOC for IBA and GOA fro IEAs) to be removed; this hasn't happened since the taxon constraint was changed on Nov 20

<img width="765" alt="image" src="https://github.com/user-attachments/assets/8dc0f2e4-96e7-440b-9944-5965554c733e">


Do you want to close, or wait for the next releases to check it again?

**Comment by Antonialock** [comment]
Thanks, I thought it'd have to do with the builds but just wanted to make sure. I'll close!
