### ISSUE TITLE
merge fatty-acyl-CoA synthase activity (is a process)

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8102]
This is a compound function term.
EC 4.2.1.61 :  IUBMB
EC 2.3.1.39 : IUBMB
EC 2.3.1.86 : IUBMB
EC 2.3.1.38 : IUBMB
EC 1.3.1.9 : IUBMB

Perhaps oit should merge with fatty acid biosynthetic process?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/7887](https://sourceforge.net/p/geneontology/ontology-requests/7887)

**Comment by ukemi** [comment]
I'm closing this as being out of date since 1) we are moving towards the annotation of complexes with molecular functions. 2) Relations now exist that link molecular functions and processes and 3) We have accepted many other compound molecular functions, receptors etc as valid with corresponding has_part relations if possible.
