### ISSUE TITLE
attack of insect

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8665]
Hi,

I am looking for a term meaning a toxin activity against insects, and another term with a toxin activity against  vertebrates. These terms will be used when the protein is lethal or paralytic against the insect or the vertebrate.

I found "response to insect; GO:0009625", but I am not sure if the definition really matches my need. My protein is in the venom of the animal and is injected in the insect/mammal. 

If you think the term corresponds, I suggest a more precise one:

-response to insect; GO:0009625
\--attack of insect; new  \(or maybe attack response to insect\)

-response to vertebrate; GO:new
\--attack of vertebrate; new

Thanks
Florence

Reported by: fjungo

Original Ticket: [geneontology/ontology-requests/8453](https://sourceforge.net/p/geneontology/ontology-requests/8453)

**Comment by dosumis** [comment]
Closing because:
  (a) This ticket is very old - are the terms still needed?
  (b) The requested terms may not be in scope for GO

If still relevant, please re-open:

Judging by these papers, we could add inhibitor activities to record MF:

PMID:18849658 = Peptide toxins that selectively target insect Na(V) and Ca(V) channels.
Spiders:
PMID:17215013 = The differential preference of scorpion alpha-toxins for insect or mammalian sodium channels: implications for improved insect control.

I'd also be happy to add child classes of 'envenomation resulting in modification of morphology or physiology of other organism' indicating mode of action of toxins.

I think whether the toxins in questions are sometimes fatal to the envenomated organism is out of scope.
