### ISSUE TITLE
Endothelial development terms need relocation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8838]
Endothelial development \(go:0003158\) "Is a" epithelium development
\(go:0060429\) and
endothelial cell differentiation \(go:0045446\) "is a" epithelial cell  differentiation \(go:0030855\)

These do not reflect the current consensus regarding endothelial  development.  Endothelial cells apparently derive from bone marrow cells,  which are quite distinct/distant in origin from epithelial cells.

Endothelial cells line blood vessels, lymph vessels, and some other body  cavities.  Epithelial cells "face the outside world"...ie skin, lining of  the gut, lining of the lung, etc.

Reported by: lowr

Original Ticket: [geneontology/ontology-requests/8626](https://sourceforge.net/p/geneontology/ontology-requests/8626)

**Comment by ukemi** [comment]
Closing this issue as out of date because as Chris points out above, these terms now live as cross-products with the corresponding terms from the external ontologies. If the placement is incorrect,, it will have to be changed by the experts that curate those ontologies. GO is consistent with their representation.
