### ISSUE TITLE
TEAD-YAP cc terms too specific?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9300]
There are four cell component terms, GO:0071148, 49, 50, and 51 for complexes of the transcription co-activator YAP1 (yorkie) with each of the transcription factor family members TEAD1, 2, 3, and 4. These look to me like complexes of specific proteins, not a complex involving a protein family. Am I missing something or should these terms be handed over to PRO and replaced in GO by a more generic one?

Alternatively, if indeed these terms are within the scope of GO, could I have a grouping term for a complex on any TEAD protein with YAP1, and also one for a complex of any TEAD protein with WWTR1 (TAZ), to annotate some work that describes circumstances under which all TEAD proteins interact interchangeably with YAP (and with WWTR1(TAZ)) to form complexes that activate transcription of target genes (PMID: 19324876 and PMID: 18579750). Or, perhaps, if the current term is indeed too specific these four should be retired in favor of the single all-TEAD one?

Also, while these papers describe the pairwise interaction between YAP and a TEAD protein, that looks like a limitation of the experimental methods used, not evidence that the complex formed in vivo is a heterodimer as opposed to a larger complex whose members include these two proteins, so perhaps the definition should be changed from "A transcription factor complex that is composed of the DNA biding protein TEAD-n and the transcriptional coactivator YAP" to "A transcription factor complex that includes the DNA binding protein TEAD-n and the transcriptional coactivator YAP"?

Thanks.

Peter

Reported by: deustp01

Original Ticket: [geneontology/ontology-requests/9091](https://sourceforge.net/p/geneontology/ontology-requests/9091)

**Comment by pgaudet** [comment]
@vanaukenk  @bmeldal  Does this fit in the Protein Complex working group discussion ?

**Comment by bmeldal** [comment]
Maybe, but looks to me - without reading the paper as well - that @hdrabkin and @krchristie already made a very sensible decision or merging all 4 terms into one parent term. I had a few similar situation where I've requested a merge in the past. I certainly no longer request composition-specific complexes for each compositional iteration of functionally identical complexes. It would be different if the variants have experimentally different functions but then they should still be grouped by that function.

Going further, Harold says these are all complexes "that activate transcription of target genes", so shouldn't they all be GO:NEW "transcription activation complex", rather than making lots of compositional-specific terms?

It could be the complex term to go with GO:0140110 transcription regulator activity
https://github.com/geneontology/go-ontology/issues/13588

**Comment by bmeldal** [comment]
Do we need a label < complex working group >???

**Comment by krchristie** [comment]
I have a few comments.

1. Considering that the parent term of these 4 TEAD-YAP complexes is "**_RNA polymerase II_** transcription factor complex", it seems that if use a more general term, that it should still be specific to RNAP II. 

2. Regarding the suggested "GO:NEW "transcription activation complex", the idea of coding the direction of regulation, e.g. activation or repression, in CC terms concerns me. **MANY** TF complexes act as either activators or repressors depending on the location of the binding site. It seems like it would be cleaner to separate the direction of regulation from the CC terms.

3. If we are going to use a very general term instead of creating a CC term for all of the multitudinous DNA binding TFs for RNAP II, are we also going to consider obsoleting the majority of child terms currently under "RNA polymerase II transcription factor complex"?  If I recall correctly @ukemi and I proposed deleting a number of these very specific terms in 2010, but it was decided to keep the ones we have, but not add any more. Note: We would probably still want to keep the terms for the "general transcription factors", e.g. TFIIA, TFII_, etc, since these very general to much of RNAP II transcription and are limited in number.

**Comment by pgaudet** [comment]
@bmeldal 
Isn't the 'protein complex' label sufficient? How would you tell which issues go where ? 

One alternative approach to consider is a 'Project' where you can link tickets from any tracker to follow the progress of a project. What do you think ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
Add @krchristie 

> 1. Considering that the parent term of these 4 TEAD-YAP complexes is "RNA polymerase II transcription factor complex", it seems that if use a more general term, that it should still be specific to RNAP II.

Sorry, failed to check current hierarchy!

> 2. Regarding the suggested "GO:NEW "transcription activation complex", the idea of coding the direction of regulation, e.g. activation or repression, in CC terms concerns me. MANY TF complexes act as either activators or repressors depending on the location of the binding site. It seems like it would be cleaner to separate the direction of regulation from the CC terms.

Fair point. Let's not go down that route. I've had other situations, too, where activation or repression was situation dependent.

> 3. If we are going to use a very general term instead of creating a CC term for all of the multitudinous DNA binding TFs for RNAP II, are we also going to consider obsoleting the majority of child terms currently under "RNA polymerase II transcription factor complex"? If I recall correctly @ukemi and I proposed deleting a number of these very specific terms in 2010, but it was decided to keep the ones we have, but not add any more. Note: We would probably still want to keep the terms for the "general transcription factors", e.g. TFIIA, TFII_, etc, since these very general to much of RNAP II transcription and are limited in number.

Yes, systematic obsoletion of specific terms has been discussed several times and always abandoned due to a multitude of issues. 

- [ ] So, should we just merge the 4 composition-specific terms into one parent for this term?

@pgaudet 

- [ ] I think a "Project" would a excellent, then I can find related tickets much easier and also work on the project in fits and starts without having to keep track of numerous tickets. I've never created a Project, is it easy? Shall I start it? I see, there's a tab on the top!

**Comment by pgaudet** [comment]
Hi @bmeldal 
I created your project 
https://github.com/geneontology/go-ontology/projects/8
Skype me if you want a little overview of how to use this. 

Thanks, Pascale

**Comment by bmeldal** [comment]
Thanks, Pascale. I'll let you know if I need help. Only working 2 days this week and that includes a training course. Will get to it next week.

**Comment by krchristie** [comment]
@bmeldal 
> So, should we just merge the 4 composition-specific terms into one parent for this term?

Seems like a reasonable immediate action.

**Comment by bmeldal** [comment]
Yes, please, @krchristie

**Comment by pgaudet** [comment]
Hi @bmeldal @krchristie 
Just looking at this again - There are many transcription factor complexes, see list below. 
If we merge these TEAD-YAP complexes into "RNA polymerase II transcription factor complex", then all other siblings should also be merged: 

GO:0008230 ecdysone   receptor holocomplex
GO:0016513 core-binding factor   complex
GO:0016602 CCAAT-binding factor   complex
GO:0030232 insulin control element   activator complex
GO:0030907 MBF transcription complex
GO:0032444 activin responsive factor   complex
GO:0033309 SBF transcription complex
GO:0035189 Rb-E2F complex
GO:0036488 CHOP-C/EBP complex
GO:0070514 SRF-myogenin-E12 complex
GO:0070721 ISGF3 complex
GO:0070847 core mediator complex
GO:0071148 TEAD-1-YAP complex
GO:0071149 TEAD-2-YAP complex
GO:0071150 TEAD-3-YAP complex
GO:0071151 TEAD-4-YAP complex
GO:0071943 Myc-Max complex
GO:0089716 Pip2-Oaf1 complex
GO:0097221 M/G1 phase-specific MADS   box-forkhead transcription factor complex
GO:1990589 ATF4-CREB1 transcription   factor complex
GO:1990590 ATF1-ATF4 transcription   factor complex
GO:1990617 CHOP-ATF4 complex
GO:1990647 C/EBP complex
GO:1990711 Beta-catenin-ICAT complex
GO:1990907 beta-catenin-TCF complex


What do you think ? 

Thanks, Pascale

**Comment by bmeldal** [comment]
GO:0008230 ecdysone receptor holocomplex
also acts as a receptor so may need staying

GO:0016513 core-binding factor complex
regular DNA-bdg TF

GO:0016602 CCAAT-binding factor complex
regular DNA-bdg TF

GO:0030232 insulin control element activator complex
regular DNA-bdg TF

GO:0030907 MBF transcription complex
regular DNA-bdg TF

GO:0032444 activin responsive factor complex
regular DNA-bdg TF

GO:0033309 SBF transcription complex
regular DNA-bdg TF

GO:0035189 Rb-E2F complex
regular DNA-bdg TF

GO:0036488 CHOP-C/EBP complex
regular TF

GO:0070514 SRF-myogenin-E12 complex
regular TF

GO:0070721 ISGF3 complex
regular TF

GO:0070847 core mediator complex
very much a core transcription machinery and a term I would keen, together with the TFIIx terms as mentioned above by Karen.

GO:0071148 TEAD-1-YAP complex
GO:0071149 TEAD-2-YAP complex
GO:0071150 TEAD-3-YAP complex
GO:0071151 TEAD-4-YAP complex
as discussed above.

GO:0071943 Myc-Max complex
regular TF

GO:0089716 Pip2-Oaf1 complex
regular DNA-bdg TF

GO:0097221 M/G1 phase-specific MADS box-forkhead transcription factor complex
regular DNA-bdg TF

GO:1990589 ATF4-CREB1 transcription factor complex
regular DNA-bdg TF

GO:1990590 ATF1-ATF4 transcription factor complex
regular DNA-bdg TF

GO:1990617 CHOP-ATF4 complex
regular DNA-bdg TF

GO:1990647 C/EBP complex
regular DNA-bdg TF

GO:1990711 Beta-catenin-ICAT complex
regular TF

GO:1990907 beta-catenin-TCF complex
regular TF

So, apart form the mediator and GO:0008230 ecdysone receptor holocomplex I can see these complexes going as they really only are TFs (with or without DNA-bdg annotations).

But what would Val - and her users - say???

**Comment by krchristie** [comment]
Rereading through this thread, I realize it isn't very clear that what I was proposing previously when this thread was new was to have a single term for TEAD-YAP complex, not to merge all four of the current TEAD-n-YAP complex terms into their current parent term of "RNA polymerase II transcription factor complex".

As I have mentioned earlier in this ticket, David H and I proposed eliminating all of these specific complex terms, during the 2010 transcription overhaul, and there was significant resistance to the idea from Ruth, and possibly others, that they would lose information that they have already annotated if these terms are removed. I am not sure we have yet gotten to the stage where there is a good way to capture the more detailed info as an extension, or via Noctua, that people will be happy to eliminate all of these.

**Comment by pgaudet** [comment]
So, the proposal is to merge into a new term 'TEAD-YAP-type complex' ? 

That works for me. 

Thanks, Pascale

**Comment by krchristie** [comment]
Having just reread Peter's original comment, specifically:

> Also, while these papers describe the pairwise interaction between YAP and a TEAD protein, that looks like a limitation of the experimental methods used, not evidence that the complex formed in vivo is a heterodimer as opposed to a larger complex whose members include these two proteins, so perhaps the definition should be changed from "A transcription factor complex that is composed of the DNA biding protein TEAD-n and the transcriptional coactivator YAP" to "A transcription factor complex that includes the DNA binding protein TEAD-n and the transcriptional coactivator YAP"?

it might be worth considering merging this additional term "**TEAD-2 multiprotein complex**" (GO:0071147) into a single TEAD-YAP complex term also.

**Comment by bmeldal** [comment]
>As I have mentioned earlier in this ticket, David H and I proposed eliminating all of these specific complex terms, during the 2010 transcription overhaul, and there was significant resistance to the idea from Ruth, and possibly others, that they would lose information that they have already annotated if these terms are removed. I am not sure we have yet gotten to the stage where there is a good way to capture the more detailed info as an extension, or via Noctua, that people will be happy to eliminate all of these.

It was discussed again 2-ish years ago with David OS and again Val was opposed as they'd loose a tonne of annotations to these leave terms.

>it might be worth considering merging this additional term "TEAD-2 multiprotein complex" (GO:0071147) into a single TEAD-YAP complex term also.

According to review PMID:20439427 
http://genesdev.cshlp.org/content/24/9/862.full
the transcription factor is the dimer but YAP interacts with other proteins in the Hippo signalling pathway (see F2).

![image](https://user-images.githubusercontent.com/10517124/35725089-f5e1a9f4-07f7-11e8-900b-782c3493c3ac.png)

**Comment by pgaudet** [comment]
@ValWood @bmeldal @krchristie 

Can I go ahead and merge 
GO:0071148 TEAD-1-YAP complex
GO:0071149 TEAD-2-YAP complex
GO:0071150 TEAD-3-YAP complex
GO:0071151 TEAD-4-YAP complex
GO:0071147 TEAD-2 multiprotein complex
 into a single TEAD-YAP complex term ?

**Comment by ValWood** [comment]
Yeast don't have these, I guess so...

**Comment by krchristie** [comment]
OK by me - seems like the summary of what was agreed in this ticket.
