### ISSUE TITLE
Bone morphogenisis term request & 1 relation change as resul

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9436]
[New Term]
intramembranous bone morphogenesis
Def:The process in which bone that forms directly within mesenchyme, are generated and organized.
is_a  bone morphogenesis

[New Term]
dermal bone morphogenesis 
Def:The process in which bone which forms superficially in the organism are generated and organized.
is_a intramembranous bone morphogenesis

[New Term]
membrane bone morphogenesis
Def:The process in which bone which forms deep in the organism are generated and organized.
is_a intramembranous bone morphogenesis

[New Term]
replacement bone morphogenesis 
Def:The process in which bones are generated and organized as a result of the conversion of initial another structural tissue into bone.
is_a  bone morphogenesis

[New Relationship]
endochondral bone morphogenesis GO:0060350 
Def:The process in which bones are generated and organized as a result of the conversion of initial cartilaginous anlage into bone.
is_a replacement bone morphogenesis

[New Term]
perichondral bone morphogenesis  
Def:The process in which bones are generated and organized as a result of the conversion of initial connective tissue surrounding cartilage into bone.
is_a replacement bone morphogenesis

Reported by: cerivs

Original Ticket: [geneontology/ontology-requests/9227](https://sourceforge.net/p/geneontology/ontology-requests/9227)

**Comment by pgaudet** [comment]
Hello, 

The first term, intramembranous bone morphogenesis, has been created, but not the others. 

@sabrinatoro does ZFIN still need the terms? f you do, please provide references. 

Thanks, Pascale

**Comment by sabrinatoro** [comment]
I will talk with @cerivs (she is the one who made the request).

**Comment by cerivs** [comment]
Perichondral bone PMID:21901110 
Dermal bone: PMID:12588850 PMID:15003632
Endochondral bone: PMID:25639508 PMID:19855136 PMID:17013873 
Membrane bone: PMID:14579374 

Replacement bone is a parent type for both 
Perichondral bone and Endochondral bone  so will be useful for annotating gene function common to both types of  replacement bone morphogenisis probably the best reference is 10.1002/(SICI)1097-4687(199608)229:2<121::AID-JMOR1>3.0.CO;2-4

If more general development terms fit the current GO strategy better then making those terms instead of morphogenesis terms would be ok.

**Comment by ukemi** [comment]
Terms added, but still need UBERON terms for the logical defs. Need to request:

UBERON:0008913- perichondral bone
UBERON:0008907- dermal bone
UBERON:0007842- membrane bone
UBERON:0002513- endochondral bone
UBERON:0012075- replacement bone

#15099
