### ISSUE TITLE
NTR: tRNA (adenine-C2-)-methyltransferase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9902]
First, a MF term, definition: Catalysis of the reaction: 2 S-adenosyl-L-methionine + adenine(37) in tRNA = S-adenosyl-L-homocysteine + 5'-deoxyadenosine + L-methionine + C2-methyladenine(37) in tRNA.  Should be a child of  GO:0008169 C-methyltransferase activity and GO:0016426 tRNA (adenine) methyltransferase activity.  Though maybe the base postion, A37, should be left out of the definition?  The new activity was found in PMID 22891362.

Also perhaps a new BP term, tRNA base methylation, as a child term of tRNA methylation.  (N.B. I don't understand why there needs to be a "mitochondrial tRNA methylation" process term.)

Thanks,
Ingrid

Reported by: imk07

Original Ticket: [geneontology/ontology-requests/9696](https://sourceforge.net/p/geneontology/ontology-requests/9696)

**Comment by pgaudet** [comment]
To match EC and RHEA: 

- [ ] changed label from tRNA (adenine-C2-)-methyltransferase activity to : tRNA (adenine(37)-C2-)-methyltransferase activity
- [ ] added xrefs +xref: EC:2.1.1.192 {source="skos:broadMatch"} and xref: RHEA:43332 {source="skos:exactMatch"}
- [ ] removed part_of GO:0001510 ! RNA methylation and part_of GO:0030488 ! tRNA methylation, since the activity cannot be part of both processes at once
- [ ] fixed related term (ie, that shares the EC: GO:0070040
-name: rRNA (adenine-C2-)-methyltransferase activity
+name: rRNA (adenine(2503)-C2-)-methyltransferase activity; 
- [ ] changed EC to broadMatch
- [ ] added RHEA:42916
